### ISSUE TITLE
ClassReplacerRector - Do not replace classes in use statements?

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1006]
This is more likely question then a bug/issue, should it ignore use statements? Since it replaces with FQN I feel like it is useless.

<img width="1102" alt="screenshot 2019-02-02 22 43 51" src="https://user-images.githubusercontent.com/3995003/52169633-22fc6c80-273c-11e9-8f76-695698dfeb60.png">

**Comment by TomasVotruba** [comment]
This is cleaned up by coding standard, so we don't have to care about it.

**Comment by TomasVotruba** [comment]
If it's changed or not, the final result will be the same.

**Comment by JanMikes** [comment]
Okay, thx for explanation.
