### ISSUE TITLE
[PHPUnit] Rector for expectedException migration from php doc

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#1013]
The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9. Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageRegExp() instead

**Comment by TomasVotruba** [comment]
Do you mean this?
https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#exceptionannotationrector

**Comment by shyim** [comment]
Ohh thanks. I execute phpunit80 and there its missing.
Maybe it would awesome if the versions extend each over. phpunit80 contains everything from phpunit70

I love this tool <3

**Comment by TomasVotruba** [comment]
Thanks for feedback!

Include them all in one big line was initial idea, but it shown people need to be in control of upgrade path and need single version at a time.

But there is idea about upgrade command, that would basically upgrade everything that your composer.json needs: https://github.com/rectorphp/rector/issues/900
