### ISSUE TITLE
[DeadCode] Remove unused contructor injection + property

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1028]
Real example:
<img width="626" alt="screenshot 2019-02-09 15 44 15" src="https://user-images.githubusercontent.com/3995003/52522145-94c73f80-2c81-11e9-9396-70a1ad22dd74.png">

Diff:
<img width="1029" alt="screenshot 2019-02-09 15 45 34" src="https://user-images.githubusercontent.com/3995003/52522160-c2ac8400-2c81-11e9-9688-bfad1b660133.png">

I see we already have this: https://github.com/rectorphp/rector/issues/891 so it could be combination of extension for that -> new rector that will check the constructor injection.

**Comment by JanMikes** [comment]
@TomasVotruba is this already implemented?

<img width="1091" alt="screenshot 2019-02-09 15 50 22" src="https://user-images.githubusercontent.com/3995003/52522214-6eee6a80-2c82-11e9-827f-8fa185a7f357.png">

**Comment by TomasVotruba** [comment]
> @TomasVotruba is this already implemented?


Looks like so :) It needs removal from constructor as well.

**Comment by JanMikes** [comment]
Yeah, i just used it on real application, i just found one bug reported in #1029 so i will close this one. Thank you, i am surprised that it works 😄
