### ISSUE TITLE
A Kind Question

### ISSUE THREAD

**Issue by bgreatfit** [rectorphp/rector#1037]
Hello all, my legacy code of 10yrs old is mostly function based and also uses mysql_query. Can rector help with this

**Comment by TomasVotruba** [comment]
Hi,

if you can run Docker and the code is PHP 5.3+, you can use Rector to refactor it.
That's the only technical limitation :)

**Comment by TomasVotruba** [comment]
Here is the docs for Docker install -  https://github.com/rectorphp/rector#run-rector-in-docker

If you have any troubles, just create an issues with description of your problem.
