### ISSUE TITLE
cakephp  Combined Get/Set Methods

### ISSUE THREAD

**Issue by saeideng** [rectorphp/rector#1038]
hi
unlike of other set/get methods , some methods have different signature
```php
->config($key); // getter method
->config($key,$value); // setter method
```
### What happened
`vendor/bin/rector process src --level cakephp34 --dry-run`

```diff
-        $this->config($key);
-        $this->config($key,$value);
+        $this->setConfig($key);
+        $this->setConfig($key,$value);

```

### What you expected to happen

```diff
-        $this->config($key);
-        $this->config($key,$value);
+        $this->getConfig($key);
+        $this->setConfig($key,$value);
```
rector : 
https://github.com/rectorphp/rector/blob/6ba0b32f60f3326035f071b7e2a81d34d36ad431/config/level/cakephp/cakephp34.yaml#L35-L38

cakephp : 

https://github.com/cakephp/cakephp/blob/5c78a61c0ed7fbd56ce9d7cee3c6d6f9b27af46b/src/Core/InstanceConfigTrait.php#L176-L188

https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html#deprecated-combined-get-set-methods

**Comment by TomasVotruba** [comment]
Hi, thanks for beautiful report :+1: :clap: 

If I understand it corectly, some method behave:

- as getter with 1 argument 
- as setter with 2 arguments?

Could you give me list of those methods by type? I'd upgrade the Rector to work with them
