### ISSUE TITLE
[NetteToSymfony] Translation placeholder rename

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1050]
Kdyby → Symfony

Ref https://symfony.com/doc/current/components/translation/usage.html#message-placeholders

```diff
$translated = $translator->trans(
    'Hello %name%',
-    ['name' => $name]
+    ['%name%' => $name]
);
```

cc @JanMikes Could you confirm this is correct replacement?

**Comment by JanMikes** [comment]
I confirm i had to do this. 👍

**Comment by TomasVotruba** [comment]
Btw, the magic happens in custom Kdyby `translate()` method - https://github.com/Kdyby/Translation/blob/6b0721c767a7be7f15b2fb13c529bea8536230aa/src/Translator.php#L172

**Comment by JanMikes** [comment]
Thx for sharing :+1:
