### ISSUE TITLE
Replace define with const

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1073]
Hi,

I am trying to write my first rector that replaces `define()` with `const`. This is how I tried to solve it, but I get a LogicException from `\PhpParser\NodeTraverser::ensureReplacementReasonable()` that I am trying to replace an expression with a statement. Any suggestion?

```php
<?php

use PhpParser\Node;
use PhpParser\Node\Expr\FuncCall;
use Rector\Rector\AbstractRector;
use Rector\RectorDefinition\CodeSample;
use Rector\RectorDefinition\RectorDefinition;

class DefineToConstRector extends AbstractRector {

  /**
   * {@inheritdoc}
   */
  public function getDefinition(): RectorDefinition
  {
    return new RectorDefinition('Turns define() to const.', [
      new CodeSample('define("FOOO", "BAR");', 'const FOOO = "BAR";'),
    ]);
  }

  /**
   * {@inheritdoc}
   */
  public function getNodeTypes(): array
  {
    return [FuncCall::class];
  }

  /**
   * {@inheritdoc}
   */
  public function refactor(Node $node): ?Node
  {
    /** @var \PhpParser\Node\Expr\FuncCall $node */
    if (!$this->isName($node, 'define')) {
      return null;
    }

    return new Node\Stmt\Const_([
      new Node\Const_($node->args[0]->value->value, $node->args[1]->value)
    ]);
  }

}

```

**Comment by TomasVotruba** [comment]
Hi, first... very nice job :+1: 

Missing Expression error usually prevents this:

```diff
-const FOOO = 'BAR'
+const FOOO = 'BAR';
```

In your case, I'd try something like this:

```php
$constNode = new Node\Stmt\Const_([
    new Node\Const_($node->args[0]->value->value, $node->args[1]->value)
]);

return new Expression($constNode);
```

**Comment by mxr576** [comment]
@TomasVotruba Thanks for the help! I have managed to solve the problem: https://github.com/mxr576/drupal8-rector/blob/travis/src/CodeStyle/DefineToConstRector.php#L39

Moreover, I have managed to improve my Rector-skills in the past 24 hours ;) https://github.com/mxr576/drupal8-rector

I am closing this issue and I'll probably open a new one with bugs that I found and possible ideas.

**Comment by TomasVotruba** [comment]
That's also possible solution :+1: 

Amazing job :clap: , imagine what you'll be able to do in a week... or a month :)
