### ISSUE TITLE
[DeadCode] Remove constructors that does not do anything

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1091]
As you can see in this example, Rector removed the unused `entityTypeManager` property from the class but it kept the constructor of the class that does nothing now.
https://travis-ci.org/mxr576/drupal8-rector/jobs/496392367#L1726

**Comment by TomasVotruba** [comment]
How would the validation of useless constructor worked?

**Comment by TomasVotruba** [comment]
I made first implementation in #1124, so we have this simple case covered :+1: 

Add test case/comment there to improve it
