### ISSUE TITLE
Class self was not found while trying to analyse it

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1092]
[This line](https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.0-beta2/src/Entity/App.php#L419) caused this problem, I think `\self`is valid annotation so it should not cause failures like this.

https://travis-ci.org/mxr576/drupal8-rector/jobs/496392367#L4211

**Comment by TomasVotruba** [comment]
What minimal set of rules caused this?

**Comment by mxr576** [comment]
Indeed, if I remove `\` or replace it with an FQCN it works. Is it something that "works as designed"? Because then I'll close this issue.

**Comment by TomasVotruba** [comment]
I think so, because that how imported functions with same name just different namespace work.

Type declarations should be used without slashes.
