### ISSUE TITLE
[DeadCode] Incorrect detection of dead variable

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1093]
Test build: https://travis-ci.org/mxr576/drupal8-rector/jobs/496426067#L1174
Context: https://github.com/drupal/core/blob/8.6.10/modules/system/src/Controller/SystemController.php#L256

**Comment by TomasVotruba** [comment]
I made a test case and it passes. 
I fixed something similar in last week. Could you try Rector 0.4+?

If the bug still remains, provide minimal PHP code where it fails.

**Comment by mxr576** [comment]
Bumped the rector version to 0.4.2, but the problem still persists. I saw you pushed new commits to master related to this problem. I'll check this out again after a new release.

https://travis-ci.org/mxr576/drupal8-rector/jobs/498167020#L1212

Btw, is it safe to use `^0.4` constraint to depend on this library or should I strict to the patch-level restrictions?

**Comment by TomasVotruba** [comment]
Please, send failing test then.

It's a bit better to use patch version lock for dev 0.* line.

**Comment by TomasVotruba** [comment]
Closing for missing failing test case

**Comment by mxr576** [comment]
Sorry for the delayed answer :) Updated to 0.4.11 and it seems the problem has been solved since I reported it.
