### ISSUE TITLE
Level coding-style breaks Doctrine annotations

### ISSUE THREAD

**Issue by N0ps32** [rectorphp/rector#1116]
Before applying:
`use Doctrine\ORM\Mapping as ORM;`

After:
`use Doctrine\ORM\Mapping;`

However the actual annotations are not changed, resulting in broken code:
```
/**
 * @ORM\Id
 * @ORM\Column(type="integer")
 * @ORM\GeneratedValue(strategy="AUTO")
 */
protected $id;
```

Command:
`docker run -v (pwd):/project rector/rector:latest bin/rector process /project/src --level coding-style --autoload-file /project/vendor/autoload.php`

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

It's probably caused by `RemoveUnusedAliasRector`.

Could you add this as failing test here?

https://github.com/rectorphp/rector/blob/f12d3206eef46f3ef11495543ce3e7190e085385/packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/RemoveUnusedAliasRectorTest.php#L23

**Comment by gnutix** [comment]
I just had a similar issue when adding VichUploaderBundle annotations to an Entity. It already used Doctrine's and Symfony Validation's annotations with aliases fine, and these were not touched, but Rector tried to remove the alias from Vich :

```diff
1) src/Entity/SomeEntity.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -12,7 +12,7 @@
 use Symfony\Component\HttpFoundation\File\File;
 use Symfony\Component\HttpFoundation\File\UploadedFile;
 use Symfony\Component\Validator\Constraints as Assert;
-use Vich\UploaderBundle\Mapping\Annotation as Vich;
+use Vich\UploaderBundle\Mapping\Annotation;

 /**
  * @Vich\Uploadable
```

**Comment by TomasVotruba** [comment]
- What rule is responsible?
- Could you share your minimal config? Better run with `--set X` instead

**Comment by gnutix** [comment]
@TomasVotruba I've updated my example above. Using only `--set=coding-style` triggers the error too, with both `Rector\CodingStyle\Rector\Use_\RemoveUnusedAliasRector` and `Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector` listed (it seems that this second one is often concerned in many bugs I've reported... not sure what it does exactly though).

**Comment by TomasVotruba** [comment]
Good! I'll look at it

**Comment by TomasVotruba** [comment]
I don't see any `Vich` being used in the code above. Please create a new issue with code that causes the issue while copied, so we don't mix more problems at once here.

Thank you

**Comment by gnutix** [comment]
Failing test case added in 7d2b4dda4
