### ISSUE TITLE
[support] Add new use statement to a class

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1117]
How can I add a new import (use statement) to a class if a given condition met?

I have managed to replace a deprecated method call in `Foo\Bar\ClassA` with a new one from `Foo\Bar\ClassB`. How can I import ClassB to ClassA so I could do `ClassB::myMethod()` replacement instead `Foo\Bar\ClassB::myMethod()` replacement.

**Comment by TomasVotruba** [comment]
I don't understand.
Could you write that in a diff format?

**Comment by mxr576** [comment]
Sorry, it is easier for me to write it this way, I hope it helps, let me know if it is still unclear.

Initial setup:

```php
namespace Foo\Bar;

trait TraitA {
  /**
   * @deprecated
   */
  public function bar() {

  }
}

namespace Foo\Bar;

class ClassA {

  use TraitA;

  public function foo() {
     $this->bar();
  }
}

namespace Foo\Baz;

class ClassB {

  /**
   * Replaces deprecated \Foo\Bar\TraitA::bar().
   */
  public static function baz() {}
}
```

What I've managed to solve already is replacing deprecated method calls with the right ones but without importing the new classes that provide the correct methods.
```php
<php
class ClassA {

  use TraitA;

  public function foo() {
    \Foo\Baz\ClassB::baz();
  }
}
```

What I would like to solve is importing the new class that contains the correct method with my rector: 

```php
<?php


namespace Foo\Bar;

use \Foo\Baz\ClassB;

class ClassA {

  use TraitA;

  public function foo() {
    ClassB::baz();
  }
}
```

**Comment by TomasVotruba** [comment]
I see. That's job of coding standard.

I use this sniff: https://github.com/Symplify/Symplify/blob/master/packages/CodingStandard/config/symplify.yml#L11

Run it after Rector run and your code will be refactored and clean :)

**Comment by mxr576** [comment]
Hmm... I hoped that I can solve this with Rector :nerd_face: I know that PHPCS/PHPCS Fixer and friends can not be replaced with Rector, but it seemed something that can be solved by Rector.

Actually, I have managed to add a new `use` statement to a class that already had a `use` statement, but the position of the added statement was incorrect - it could not be calculated from previous/next node - therefore it rendered before `<?php` open tag. I haven't managed to add a new `use` statement to a class that hasn't had any imports before.

```php
<?php
class FooRector extends AbstractRector {
 private function addUrlImport(Node\Expr\MethodCall $node) {
        /** @var \PhpParser\Node\Stmt\Class_ $classNode */
        $classNode = $node->getAttribute(Attribute::CLASS_NODE);
        $alreadyImported = FALSE;
        /** @var \PhpParser\Node\Stmt\Use_ $useNode */
        foreach ($classNode->getAttribute(Attribute::USE_NODES, []) as $useNode) {
            /** @var \PhpParser\Node\Stmt\UseUse $use */
            foreach ($useNode->uses as $use) {
                if ($use->name === self::CLASS_NAME) {
                    $alreadyImported = TRUE;
                    break 2;
                }
            }
        }

        if (!$alreadyImported) {
            $useNodes = $classNode->getAttribute(Attribute::USE_NODES, []) ;
            if (!array_key_exists(0, $useNodes)) {
                // This does not work, because Use_ position in file should have been set I assume.
                $useNodes[0] = new Node\Stmt\Use_([]);
            }
            $useNodes[0]->uses[] = new Node\Stmt\UseUse(new Node\Name(self::CLASS_NAME));
            $classNode->setAttribute(Attribute::USE_NODES, $useNodes);
          // $this->addNodeAfterNode() can not be used here because it works with Expressions.
        }
    }
}
```

**Comment by mxr576** [comment]
Also tried to use the ClassMaintainer for this, but it does not provide utility functions for this purpose.

**Comment by TomasVotruba** [comment]
It is possible, the same way PHP can fly a :rocket: . You'll need coding standard one way or another :)


More on this topic:

- https://www.tomasvotruba.cz/blog/2018/10/25/why-ast-fixes-your-coding-standard-better-than-tokens/
- https://www.tomasvotruba.cz/blog/2018/10/22/brief-history-of-tools-watching-and-changing-your-php-code/

**Comment by damontgomery** [comment]
I've had mixed success (I'll open an issue here), but Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector is now part of rector which attempts to add `use` statements.

In our code, if you add a fully qualified name, Rector will convert that to a use statement.

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector#import-use-statements

**Comment by damontgomery** [comment]
Thanks, @TomasVotruba, this is super helpful. I was able to use those parameters and it's working well!

**Comment by TomasVotruba** [comment]
Great to hear that :wink:

**Comment by Charl13** [comment]
I've been spending a lot of time on finding out how to import a class with a use statement. In my case the class I needed to import was used in a `@var` property doc block.

I found out that `$node->implements[]` (`Class_`) automagically adds the use statement (which is a good thing in my opinion) but changing the `@var` type in the doc block did not.

As it turns out I had to enable `Option::IMPORT_DOC_BLOCKS` (mentioned in the readme) and use the `FullyQualifiedObjectType`.

```php
    // skip classes used in PHP DocBlocks, like in /** @var \Some\Class */ [default: true]
    $parameters->set(Option::IMPORT_DOC_BLOCKS, false);
```

Problem solved ✅

**Comment by liquid207** [comment]
I found a easy way to do this, It may be useful to others, so I put the content here.

Rector version: 0.15.24

Rector custom rule code example:

```
use PhpParser\Node;
use PhpParser\Node\Name;
use PhpParser\Node\Stmt\Namespace_;
use Rector\Core\PhpParser\Node\BetterNodeFinder;
use Rector\Core\Rector\AbstractRector;
use Rector\PostRector\Collector\UseNodesToAddCollector;
use Rector\StaticTypeMapper\ValueObject\Type\FullyQualifiedObjectType;

final class CustomRector extends AbstractRector
{
       public function __construct(private UseNodesToAddCollector $use_nodes_to_add_collector, BetterNodeFinder $better_node_finder)
    {
    }
    
    public function refactor(Node $node): ?Node
    {
       // custom logic
       ...
       
       // Add new use statement,
       $namespace = $this->betterNodeFinder->findParentByTypes($node, [Namespace_::class]);

            if ($namespace !== null) {
                $this->use_nodes_to_add_collector->addUseImport(new FullyQualifiedObjectType('Foo\Bar'));
            }
    }
}
```
