### ISSUE TITLE
Level phpunit80 does not convert all expectedException annotations

### ISSUE THREAD

**Issue by sebastianfeldmann** [rectorphp/rector#1147]
Hi

I'm using rector 0.4.3

Having a test class like this
```php
<?php
namespace MyNamespace\SomeProject;

use PHPUnit\Framework\TestCase;

class SomeClassTest extends TestCase
{
    /**
     * Tests SomeClass::something
     *
     * @expectedException \Exception
     */
    public function testSomethingFails()
    {
        $this->assertTrue(true)
    }
}
```
Rector did not modify the annotation to `$this->expectException(\Exception::class);`

I looked at the code at https://github.com/rectorphp/rector/blob/master/packages/PHPUnit/src/Rector/ExceptionAnnotationRector.php and it seems fine.

Can you put me in the right direction on how provide additional test cases, then I might be able to submit a pull request.

**Comment by sebastianfeldmann** [comment]
I found the issue.
The level phpunit80 was missing the `Rector\PHPUnit\Rector\ExceptionAnnotationRector: ~` entry
after adding it to the configuration it worked fine

Maybe think about using `\Exception::class` over `'Exception'`
The premium solution would then be to add the any required `use` statement und shorten the used namespace.

**Comment by TomasVotruba** [comment]
> I found the issue.
> The level phpunit80 was missing the Rector\PHPUnit\Rector\ExceptionAnnotationRector: ~ entry
after adding it to the configuration it worked fine

> Maybe think about using \Exception::class over 'Exception'
> The premium solution would then be to add the required use statement und shorten the used namespace.

This is job of coding standard: https://github.com/rectorphp/rector#how-to-apply-coding-standards

> Can you put me in the right direction on how provide additional test cases, then I might be able to submit a pull request.

Feel free to send one. It's part of phpunit70 set, but there is no harm to have it in phpunit80 too :)

**Comment by TomasVotruba** [comment]
@sebastianfeldmann Based on your feedback I've added the exception migration to PHPUnit 6-8. 

I see that deprecations in PHPUnit could stay 1-3 major versions, https://github.com/sebastianbergmann/phpunit/commit/1df87fc644f07f085b89a503ca8d90f46e257d45
so I now I see why this confuses people :) (and me)

Thank you :+1: 

See #1196

**Comment by sebastianfeldmann** [comment]
Awesome :)
