### ISSUE TITLE
UnsetAndIssetToMethodCallRector misnamed?

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#1150]
For me the Rector looks misnamed.
It should be named like ArrayAccessToMethodCallRector or something else.

The real magic __isset __unset does not work (e.g ```isset($this->container->foo)```)

**Comment by TomasVotruba** [comment]
Well, it's from isset/unset on some class so method call on the same class.

```diff
 $container = new SomeContainer;
-isset($container["someKey"]);
+$container->hasService("someKey");
```


> The real magic __isset __unset does not work (e.g isset($this->container->foo))

Not sure what you mean by this. Should test cases be extended?
