### ISSUE TITLE
[docs] Yaml config full example

### ISSUE THREAD

**Issue by JarJak** [rectorphp/rector#1156]
Hi!

I've came here after my project with ECS started shouting that I should use Rector instead :) Where can I find example of the YAML config, with levels, code style and custom rectors?

You can see my ECS config here:
https://github.com/bolt/four/blob/master/easy-coding-standard.yml

Then I just run in Travis for code style check:
```
  - ./vendor/bin/ecs check src
  - ./vendor/bin/phpstan analyse -c phpstan.neon src
```

How can I refactor my ECS config to be used in Rector?

**Comment by TomasVotruba** [comment]
Hi,

not sure what you mean. They're differnt tools for differnt purposes.

I'd start with README: https://github.com/rectorphp/rector#b-custom-sets

Also see `levels` for config inspiration: https://github.com/rectorphp/rector/tree/master/config/level

<br>

Btw, what is the error?

**Comment by JarJak** [comment]
The warning I get says:
`Package symplify/better-phpdoc-parser is abandoned, you should avoid using it. Use https://github.com/rectorphp/rector instead.`

**Comment by JarJak** [comment]
>They're differnt tools for differnt purposes.

Could you explain? For what I understand, `rector --with-style` runs ECS under the hood, doesn't it?

**Comment by JarJak** [comment]
How can I add levels to yaml config?

**Comment by TomasVotruba** [comment]
> How can I add levels to yaml config?

Since this is Symfony config, just import them: https://symfony.com/blog/new-in-symfony-3-3-import-config-files-with-glob-patterns

> Could you explain? For what I understand, rector --with-style runs ECS under the hood, doesn't it?

Not under the hood, just calls the `vendor/bin/ecs` package in vendor. 

Read [Brief History of Tools Watching and Changing Your PHP Code](https://www.tomasvotruba.cz/blog/2018/10/22/brief-history-of-tools-watching-and-changing-your-php-code/) for more on differences

**Comment by JarJak** [comment]
Ok now it is clear, thanks. But yet I am getting the warning, is it false-positive?

**Comment by TomasVotruba** [comment]
It's for deprecated package. If you don't use it directly, you don't have to care about this
