### ISSUE TITLE
[Laravel] RequestStaticValidateToInjectRector alias issue

### ISSUE THREAD

**Issue by azdanov** [rectorphp/rector#1176]
When using [`use Illuminate\Http\Request;`](https://github.com/rectorphp/rector/blob/3efa900de69c7bb3ff02cb177b1ea3febc6564b5/packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/Fixture/fixture.php.inc#L5) in [RequestStaticValidateToInjectRectorTest](https://github.com/rectorphp/rector/blob/master/packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/Fixture/fixture.php.inc) there are no issues.

But when an alias `use Request;` is used the test breaks.

Aliases for laravel can be specified by an user inside [`config/app.php`](https://github.com/laravel/laravel/blob/3b852a1f7f292953f47df64563cc01188db336ff/config/app.php#L218).
So I guess `use Request;` is the default, but it's possible to rename an alias to `use Req;`.

**Comment by TomasVotruba** [comment]
Could you send faling test for this?

**Comment by azdanov** [comment]
<details>
 <summary>RequestStaticValidateToInjectRector\Fixture</summary>

 ```php
<?php

namespace Rector\Laravel\Tests\Rector\StaticCall\RequestStaticValidateToInjectRector\Fixture;

use Request;

class SomeClass
{
    public function store()
    {
        $validatedData = Request::validate(['some_attribute' => 'required']);
    }
}

?>
-----
<?php

namespace Rector\Laravel\Tests\Rector\StaticCall\RequestStaticValidateToInjectRector\Fixture;

use Request;

class SomeClass
{
    public function store(\Illuminate\Http\Request $request)
    {
        $validatedData = $request->validate(['some_attribute' => 'required']);
    }
}

?>
```
</details>

**Comment by TomasVotruba** [comment]
Yes! Could you send that as PR targeting this branch?

**Comment by azdanov** [comment]
https://github.com/rectorphp/rector/pull/1178

**Comment by azdanov** [comment]
If there are any questions, I'll gladly help out.
