### ISSUE TITLE
[Docker] Make image easier to configure

### ISSUE THREAD

**Issue by azdanov** [rectorphp/rector#1181]
Right now I couldn't find a way to add `--level` or any other flag when using `docker run -v $(pwd):/project rector/rector:latest`. It only works with a `rector.yaml` file.

By changing Dockerfile it's possible to use `docker run -t rector process . --level symfony40 --dry-run`.

```dockerfile
FROM composer:latest AS composer

COPY ./composer.json /app

RUN composer install --no-dev


FROM php:7.1-cli

WORKDIR /rector

COPY . /rector
COPY --from=composer /app .

ENTRYPOINT [ "bin/rector" ]
# CMD ["bin/rector", "process", "/project", "--dry-run", "--config", "/project/rector.yaml"]

```

**Comment by azdanov** [comment]
I've modified the original image a little, it should be smaller. Any feedback?

```dockerfile
FROM php:7.1-cli-alpine

RUN apk update && \
  apk add --no-cache --virtual .build-deps git zip unzip && \
  php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer && \
  apk del .build-deps && rm -rf /var/cache/apk/* && rm -rf /tmp/*

COPY composer.json composer.json
COPY composer.lock composer.lock

ENV COMPOSER_ALLOW_SUPERUSER 1

RUN composer global require hirak/prestissimo && \
  composer install --prefer-dist --no-scripts --no-dev --no-autoloader && \
  rm -rf /root/.composer

WORKDIR /rector

COPY . /rector

ENTRYPOINT [ "bin/rector" ]
CMD ["--version"]
```

**Comment by JanMikes** [comment]
Hi, it was possible before, though the feature was not very well documented as docker usage is considered to be beta feature 😄 

It would be nice to keep multistage build, for example:
```Dockerfile
FROM composer:latest AS composer

ENV COMPOSER_ALLOW_SUPERUSER 1

COPY ./composer.json /app
RUN composer global require hirak/prestissimo
RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader

FROM php:7.1-cli-alpine
COPY --from=composer /app .
```
This will keep built image even smaller

**Comment by JanMikes** [comment]
Just to let you know, i think the original way to override default CMD for your use case was:
`docker run -v $(pwd):/project rector/rector:latest vendor/bin/rector process /project --level symfony40 --dry-run` which i agree is kind of awkward

**Comment by azdanov** [comment]
Ah, thanks for the feedback. Didn't know that CMD could be overridden after specified in the Dockerfile.

Here's a new version as you suggested. The size is definetely smaller.

```
rector/rector:alpine 131MB
rector/rector:latest 386MB
```

```dockerfile
FROM composer:latest AS composer

COPY composer.json composer.json
COPY composer.lock composer.lock

RUN composer global require hirak/prestissimo && \
  composer install --prefer-dist --no-scripts --no-dev --no-autoloader && \
  rm -rf /root/.composer

FROM php:7.1-cli-alpine

COPY --from=composer /app .

WORKDIR /rector

COPY . /rector

ENTRYPOINT [ "bin/rector" ]
```

Would you like a PR?

**Comment by JanMikes** [comment]
One thing i am not sure about is this line: `COPY composer.lock composer.lock`

Because `composer.lock` is gitignored, if you clone fresh repo and try to build dockerfile i am almost 100% sure this will fail.

> Would you like a PR?  

Sure thing, it is appreciated 👍
