### ISSUE TITLE
[PSR-4] Fix namespace of class

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1184]
Real life examples:

**Before:**  
File `app/presenters/CategoryPresenter.php`
FQN: `CategoryPresenter`  

**After:**  
Register PSR-4 directory root to `app/presenters/: MyApp\Presenters`
FQN: `MyApp\Presenters\CategoryPresenter`

---

**Before:**  
File `libs\Klarka\MyClass`
FQN: `Klarka\libs\MyClass`  

**After:**  
Register PSR-4 directory root to `libs/: Klarka`
FQN: `Klarka\MyClass`

Makes sense?

**Comment by TomasVotruba** [comment]
It does. It could load project's `composer.json` to detect directory root.

**Comment by TomasVotruba** [comment]
Closing as too vague to automate. This is better done manually, with human decission, e.g. in PHPStorm "refactor → move" 

See #1170
