### ISSUE TITLE
PHPUnit MethodCall Rectors do not fix staticly called methods

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#1185]
Hey there.

All rectors here: https://github.com/rectorphp/rector/tree/master/packages/PHPUnit/src/Rector/MethodCall do not support methods called statically, e.g. `static::assertContains(...)`. PHPUnit assert methods are static so rector should support both static and non static. 

Cheers!

**Comment by TomasVotruba** [comment]
Hi, 

I think it's tested on `self`.
Could you send failing test case to one of them?

**Comment by bendavies** [comment]
hi @TomasVotruba 
I was wrong above.

my assert is actually not being converted because this check fails:
https://github.com/rectorphp/rector/blob/d2c925d366a7bd26e2b34e63256b554780fcd4cf/packages/PHPUnit/src/Rector/MethodCall/SpecificAssertContainsRector.php#L89

My assert is like this:

```php
    protected function assertHeader(Response $response, string $contentType): void
    {
        self::assertContains(
            $contentType,
            $response->headers->get('Content-Type')
        );
    }
```

Can anything be done?

**Comment by TomasVotruba** [comment]
Can be somehow detected that `$response->headers->get('Content-Type')` return string?

**Comment by bendavies** [comment]
well, it us a `UnionType`. string or array or null. we have no way of knowing if it's string or iterable i guess.

btw, i notice that `SpecificAssertContainsRector` docs say that it can fix `assertIterableContains`, but that does not seem to be implemented.

**Comment by TomasVotruba** [comment]
> well, it is a UnionType. string or array or null. we have no way of knowing if it's string or iterable i guess.

In that case there is nothing we can do.

> btw, i notice that SpecificAssertContainsRector docs say that it can fix assertIterableContains, but that does not seem to be implemented.

Care to test that and fix that?

**Comment by bendavies** [comment]
nothing to do here

**Comment by TomasVotruba** [comment]
I just found out you were right. I'm sorry for false info.

There were 19 rules that only worked with `MethodCall` node.

The fix is ready: https://github.com/rectorphp/rector/pull/1197
