### ISSUE TITLE
[Docker] Missing autoload.php

### ISSUE THREAD

**Issue by philmoreau** [rectorphp/rector#1186]
Using the command from the documentation 

`docker run -v $(pwd):/project rector/rector:latest process /project/src --level symfony34 --dry-run`

leads to this error 

`Warning: require(//vendor/autoload.php): failed to open stream: No such file or directory in /bin/bootstrap.php on line 20

Fatal error: require(): Failed opening required '//vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /bin/bootstrap.php on line 20
`

Playing with the --autoload-file argument does not seem to do anything.

**Comment by JanMikes** [comment]
I have just experienced it as well.

I think this might be caused by #1181 

Im gonna check it out and try to fix 😉
