### ISSUE TITLE
IsCountableRector is executed even if php_version_features is < 7.3

### ISSUE THREAD

**Issue by endelwar** [rectorphp/rector#1191]
Using the following rector.yml with rector 0.4.4 it modifies the code using `is_countable` function which is [available only on PHP 7.3+](http://php.net/is_countable) (as expected by the IsCountableRector rule).

```
parameters:
  php_version_features: '7.2'
services:
  Rector\Php\Rector\BinaryOp\IsCountableRector: ~
```

Is this an expected behavior? Shouldn't IsCountableRector be bypassed due to php_version_features parameter?

**Comment by TomasVotruba** [comment]
You're right.

There should be condition for PHP 7.3 like:

https://github.com/rectorphp/rector/blob/b2463b755e6b52852e4bdc0afae81b8efe3ee953/packages/Php/src/Rector/Ternary/TernaryToNullCoalescingRector.php#L41-L43

Care for PR to add it?

**Comment by endelwar** [comment]
Sure, glad to help!
