### ISSUE TITLE
[Twig] Migration to namespaces

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#1194]
https://symfony.com/blog/new-in-twig-namespaced-classes

The classes with underscores are deprecated since Twig 2.7. It would be nice to have a rector to migrate application to use the new namespaced classes everywhere (both in code and in yaml).

**Comment by TomasVotruba** [comment]
https://github.com/rectorphp/rector/tree/master/config/level/twig

**Comment by enumag** [comment]
Ah, cool. Sorry, I didn't see it in the [docs](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#twig) so I thought it was not implemented.

**Comment by TomasVotruba** [comment]
I see. Checking `/levels` directory is also good idea, since this one is handled by generic Rector [`PseudoNamespaceToNamespaceRector`](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#pseudonamespacetonamespacerector).

**Comment by TomasVotruba** [comment]
Btw, I also posted in the comments under https://symfony.com/blog/new-in-twig-namespaced-classes few days ago, but they don't highlight links, so it's easy to skip :(

**Comment by enumag** [comment]
I'd suggest changing the readme somehow. There is no indication that the documentaion linked by the "all available Rectors" doesn't actually contain all available rectors (or rector levels).

**Comment by TomasVotruba** [comment]
> I'd suggest changing the readme somehow. 

What would you add to make it clear for you?

**Comment by enumag** [comment]
I'm not exactly sure about the terminology - mainly "rector" vs "level". It seems that the user is mainly interested in the "levels" which he can get using `vendor/bin/rector levels`? So maybe the link to all implemented rectors should be replaced with a link to all available levels since list of rectors is not the main interest? I'm not exactly sure, I'm new to rector and got confused by all this. :sweat_smile:

**Comment by TomasVotruba** [comment]
No troubles, I'll try to explain:

- level = set of multiple Rectors
- Rector = single class changing something

You can compose custom sets from any Rectors you like. 

Someone needs levels, someone needs specific Rector, e.g. to change namespace.

In coding standard terminology, someone needs psr2 set, someone else needs ArraySyntaxFixer.
