### ISSUE TITLE
Wrong argument passed to printToString()

### ISSUE THREAD

**Issue by philmoreau** [rectorphp/rector#1201]
When I run rector through docker it seems like all files lead to this error : 

` [ERROR] Could not process                                                      
         "..." file,
         due to:                                                                
         "Argument 1 passed to                                                  
         Rector\PhpParser\Printer\FormatPerservingPrinter::printToString() must 
         be of the type array, null given, called in                            
         /rector/src/Application/FileProcessor.php on line 104".`

Using `docker run -v $(pwd):/project rector/rector:latest process /project/src --level symfony34 --dry-run --autoload-file=/project/vendor/autoload.php`

**Comment by TomasVotruba** [comment]
Hi, what's the content that causes this?

**Comment by philmoreau** [comment]
It's a typical Symfony 2.8 app. The error isn't limited to one file. All files have this problem.

**Comment by TomasVotruba** [comment]
I ask because we need to be able to replicate this.

This will be probably issue with autoload and prefixed version. 

You're using Symfony 2.8, but Rector uses 3.4 at least, so there are conflicts.

Already opened in here: 
https://github.com/rectorphp/rector/issues/972

**Comment by philmoreau** [comment]
I'm a little confused then. Rector's [prepared sets](https://github.com/rectorphp/rector/tree/master/config/level/symfony)  support Symfony 2.6 onward, but Rector needs Symfony 3.4 to run. Does that mean you're supposed to first update the Symfony core to 3.4, and **then** execute all levels up to 3.4?

**Comment by TomasVotruba** [comment]
The issues is that there can be 2 version of one class:

- `Symfony\Component\Process\Process::run()` in version Symfony 2.8 in your application
- `Symfony\Component\Process\Process::run($value)` in version Symfony 3.4/4.x in Rector

This leads to all sort of bugs. Like yours.

<br>

The most reliable solution is to prefix the second:

- `RectorPrefix\Symfony\Component\Process\Process::run($value)`

There is a package that should prefix the Rector in the future: https://github.com/rectorphp/compiler
But it's not finished yet and I don't time for it. If you explore it and make it work, it might resolve your problem.

<br>

Until then, the second best way is to:

- 1. update your dependencies in `composer.json` to match those in Rector `composer.json`
- 2. then install Rector as dependency `composer require rector/rector --dev`
- 3. use it locally like `vendor/bin/rector`

**Comment by philmoreau** [comment]
I see! Thanks a lot for the clarification!

I've already upgraded to 3.4 anyway so I'll give it another try soon.
