### ISSUE TITLE
[Twig] underscore-to-namespace upgrade ignores annotations

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#1209]
I managed to run rector on my application by removing PHPStan completely from composer.json and then adding rector. This way it somewhat works with some hiccups:

### Rector outputs a lot of errors like this:

```
 [ERROR] Could not process "<filename>"   
         file, due to:                                                                                      
         "Name cannot be empty".
```

Which tells me nothing about what's wrong. But since some classes were updated anyway maybe it's not important.

### Annotations are ignored:

My classes ended up like this after the upgrade:

```
    /**
     * @var \Twig_Environment
     */
    private $twig;

    public function __construct(\Twig\Environment $twig)
    {
        $this->twig = $twig;
    }
```

As you can see while Rector did successfully upgrade the constructor typehint, it completely ignored the `@var` annotation.

Also I expected it to add a use-statement as well and change the contructor to `__construct(Environment $twig)` which did not happen either. Is there any way to enforce that?

**Comment by enumag** [comment]
Also for some reason Rector changed

```
 \Twig_Extension_Sandbox $sandboxExtension,
```

to this

```
 \Twig\Extension\Sandbox $sandboxExtension,
```

which is of course wrong because the correct class is

```
 \Twig\Extension\SandboxExtension $sandboxExtension,
```

I don't know why this happens, the [configuration](https://github.com/rectorphp/rector/blob/master/config/level/twig/underscore-to-namespace.yaml#L7) seems to be correct but overall it seems it only replaced underscores with backslashes.

**Comment by TomasVotruba** [comment]
There seems multiple issues in here. I'm getting lost.

1) Please add PR with test for the `@var` annotation issue to `RenameClassRector`

**Comment by enumag** [comment]
> Please add PR with test for the @var annotation issue to Rector\Rector\Namespace_\PseudoNamespaceToNamespaceRector

Sure, but this should apply to the RenameClassRector as well. Otherwise annotations with `@var Twig_Extension_Sandbox` would still be broken.

> Twig_Extension_Sandbox → Twig\Extension\SandboxExtension - it's look like config order was swtiched somehow, I'll check it

I see. `PseudoNamespaceToNamespaceRector` somehow got triggered before `RenameClassRector` or `RenameClassRector` for some reason ignored the occurrence.

> Could not process "<filename>" - could you provide minimal file causing this error?

It seems this occurred only for phpunit test classes. I'll try to confirm this.
