### ISSUE TITLE
packagist

### ISSUE THREAD

**Issue by landsman** [RectorPHP/Rector#122]
Hi,

is it on packagist already?
It looks really great, I want test it :)

```
 [InvalidArgumentException]                                                                                                                     
  Could not find package rector/rector at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
```

**Comment by TomasVotruba** [comment]
Hey, it's not tagged yet, so try `rector/rector:@dev`.

I'll update readme :) thanks for info

**Comment by landsman** [comment]
Thank you.
I am using `Symfony 2.8.x` and want upgrade to the lastest Symfony, Sonata Admin Bundle.

**Comment by TomasVotruba** [comment]
In that case, checkout this section: https://github.com/RectorPHP/Rector#how-to-use-on-php--71

You need to install it as standalone project and run it without dependency on your code.

**Comment by TomasVotruba** [comment]
FYI, I've just added dozens of [Symfony 3.0 rectors](https://github.com/RectorPHP/Rector/pull/126)

**Comment by landsman** [comment]
Twig 1.x to Twig 2 should be great too :-)

**Comment by TomasVotruba** [comment]
Just create an issue with link to upgrade file or any other source with deprecations. I'll see what can be easily added :)

**Comment by TomasVotruba** [comment]
Let me know if this issues still remains. I would close it otherwise

**Comment by tomasfejfar** [comment]
I think you need to call `composer create-project rector/rector:dev-master rector`. Otherwise, you get an error `Could not find package rector/rector with stability stable.`. Other option would be to set `minimum-stability` to `dev`.

**Comment by TomasVotruba** [comment]
Thanks for pointing that out. I've just relased v0.1.0 to make this eaiser and to notify about changes in relases.
