### ISSUE TITLE
[Twig] Rector priority is buggy

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#1225]
Reported previously in #1209 but I'll make separate issues now to avoid confusions.

Here is a part of code from one of my classes:

```php
        $this->safeTwigEnvironment = new \Twig_Environment(
            new \Twig_Loader_Array([])
        );
```

Even with latest dev-master version it was updated to this:

```php
        $this->safeTwigEnvironment = new \Twig\Environment(
            new \Twig\Loader\Array([])
        );
```

It should be renamed to `ArrayLoader`, see https://github.com/rectorphp/rector/blob/e36f9e3746933feaddde2346c723a922ef0b9f64/config/level/twig/underscore-to-namespace.yaml#L42.

So RenameClassRector still doesn't work correctly in combination with PseudoNamespaceToNamespaceRector.

**Comment by TomasVotruba** [comment]
I see. Tests case is needed.

You can copy this with new number: https://github.com/rectorphp/rector/tree/master/tests/Issues/Issue835

**Comment by TomasVotruba** [comment]
I'm looking into this

**Comment by TomasVotruba** [comment]
So the problem was no a priority, it's ok. But on name change, the helper attribute that is used to resolve name stayed the same.

```php
// Twig_Loader_Array
$this->getName($node); // "Twig_Loader_Array"

// change with ClassRenamRector

// Twig\Loader\ArrayLoader
$this->getName($node); // "Twig_Loader_Array" - wrong

// re-change with PseudoNamespaceToNamespaceRector - wrong
```

Fixed with this line: https://github.com/rectorphp/rector/pull/1228/files#diff-6ef90f7033aca66b84e893477376f923R248

**Comment by enumag** [comment]
I see. Thank you!

**Comment by TomasVotruba** [comment]
You're welcome
