### ISSUE TITLE
[Twig] Rector removed some newlines

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#1226]
When running `--level underscore-to-namespace` I encountered several cases where rector removed some newlines. For example code like:

```php
class A
{
	const TEST = 'test'; // test

    /**
     * @var int
     */
    private $id;
}
```

is changed to this:

```php
class A
{
	const TEST = 'test'; // test
    /**
     * @var int
     */
    private $id;
}
```

It seems to be related to the `//` comment after the constant. Properties with a comment after them also have the same issue.

**Comment by nschoellhorn** [comment]
Can you submit a failing test for that? That'd help! I guess we can figure that out soon then.

**Comment by enumag** [comment]
At the moment I'm unable to run Rector tests locally so not really.

```
PHP Warning:  include(/home/enumag/Projects/rector/rector/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /home/enumag/Projects/rector/rector/vendor/composer/ClassLoader.php on line 444
```

**Comment by TomasVotruba** [comment]
php-parser printer that Rector uses does not handle spacing. This will happen on many places.

Use prepared set or own coding standards: https://github.com/rectorphp/rector/blob/master/README.md#how-to-apply-coding-standards

**Comment by enumag** [comment]
I don't understand. How is this not a bug? I want rector to just rename some Twig classes and not change anything else in the code. There is no reason why it should remove some newlines.

**Comment by TomasVotruba** [comment]
I understand what you need. It's job of external tool. It's a feature of php-parser printer. It doesn't care about spaces, so it occasionally produces of mallformed code on various places.

Simply put:

- Rector handles context-aware changes
- coding standard cleans after him

**Comment by TomasVotruba** [comment]
> At the moment I'm unable to run Rector tests locally so not really.

Have you tried turning of the xdebug as I suggest you?

**Comment by enumag** [comment]
Oh so it's a but in another library, not rector itself. Alright.

> Have you tried turning of the xdebug as I suggest you? What happens?

I think my xdebug was just installed but not actually enabled. But I'll retry and confirm later.

**Comment by TomasVotruba** [comment]
> I think my xdebug was just installed but not actually enabled. But I'll retry and confirm later.

IIRC you had it enabled in some other issues, where you claim the same error: 

```
PHP Warning:  include(/home/enumag/Projects/rector/rector/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /home/enumag/Projects/rector/rector/vendor/composer/ClassLoader.php on line 444
```

Tests on Travis failed for same reasons once in the past.
