### ISSUE TITLE
[BUG] False positive with RemoveUnusedParameterRector

### ISSUE THREAD

**Issue by ejunker** [rectorphp/rector#1238]
It is not detecting the `compact()` where the `$group` variable is used

```
-    public function groupSponsorship(Group $group)
+    public function groupSponsorship()
     {
         return $this->render('layouts.partials.sidebar.groups._sponsorship', compact('group'));
     }
    ----------- end diff -----------

Applied rectors:

 * Rector\DeadCode\Rector\ClassMethod\RemoveOverriddenValuesRector
 * Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector
 * Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector
```

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

Are there any other "stringy" functions that should be checked?

**Comment by ejunker** [comment]
The only other thing I could think of would be `extract()` http://php.net/manual/en/function.extract.php

**Comment by TomasVotruba** [comment]
Thanks for the input and research.
 I'll look on this today

**Comment by repat** [comment]
@TomasVotruba  This doesn't seem fixed? I only used the `SetList::DEAD_CODE` list.

![image](https://user-images.githubusercontent.com/516807/114292730-b8e26d80-9ae4-11eb-8bb4-fc9ad007bc03.png)

Interestingly, it left the `compact('clients')` call but removed the object creation 🤔 

![image](https://user-images.githubusercontent.com/516807/114292723-a2d4ad00-9ae4-11eb-99cf-bdef2cda624b.png)

![image](https://user-images.githubusercontent.com/516807/114292727-ac5e1500-9ae4-11eb-8166-20832f63f17f.png)

This is afaik quite a common way to pass data to the views in Laravel, so it'd be grand if it could be fixed! :) 

Thank you

**Comment by TomasVotruba** [comment]
Thank you for an example!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
