### ISSUE TITLE
Wrong code sample for ExplicitBoolCompareRector?

### ISSUE THREAD

**Issue by jdreesen** [rectorphp/rector#1241]
The code sample for the [ExplicitBoolCompareRector](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#explicitboolcomparerector) seems wrong to me. 

If I'm not mistaken the equivalent for `!count($items)` is `count($items) < 1` or `count($items) === 0`. I doubt that `count($items) < 0` could ever happen.

As I'm new to rector I don't quite understand the implementation yet so not sure if it' only the documentation that's wrong.

**Comment by TomasVotruba** [comment]
I think you're right.

Could you send a fix PR?
