### ISSUE TITLE
[Twig] Rector is still buggy with annotations

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#1242]
While the fixes #1225 and #1209 seem to work individually, they don't work together.

Input:

```php
    /**
     * @throws \Twig_Error_Loader
     * @throws \Twig_Error_Runtime
     * @throws \Twig_Error_Syntax
     */
    public function render(): void
    {
        echo $this->twig->render(
            // ...
        );
    }
```

Expected output:

```php
    /**
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function render(): void
    {
        echo $this->twig->render(
            // ...
        );
    }
```

Actual output:

```php
    /**
     * @throws \Twig\Error\Loader
     * @throws \Twig\Error\Runtime
     * @throws \Twig\Error\Syntax
     */
    public function render(): void
    {
        echo $this->twig->render(
            // ...
        );
    }
```

Once again the [configuration](https://github.com/rectorphp/rector/blob/e36f9e3746933feaddde2346c723a922ef0b9f64/config/level/twig/underscore-to-namespace.yaml#L19-L21) is correct. My guess is that the fix from #1228 only works for code occurrences but not for annotations.

**Comment by TomasVotruba** [comment]
Other tags works?

**Comment by enumag** [comment]
You mean `@var`, `@param` and `@return`? I don't have such occurrences in my code. I'll check later but I assume they don't work either.

**Comment by enumag** [comment]
As I assumed this:

```php
    /**
     * @var \Twig_Error_Loader
     */
    public $test;
```

was changed to 

```php
    /**
     * @var \Twig\Error\Loader
     */
    public $test;
```

=> same issue...

**Comment by enumag** [comment]
Anyway there were only a few cases like this in my code so I fixed them manually. I don't need this issue to be fixed, just thought you should know about it.

**Comment by TomasVotruba** [comment]
> You mean @var, @param and @return? 

Yes!

> As I assumed this: `@var`

I see.

I thoguht it's covered by https://github.com/rectorphp/rector/tree/master/tests/Issues/Issue1225, but there are only classes.

> Anyway there were only a few cases like this in my code so I fixed them manually. I don't need this issue to be fixed, just thought you should know about it.

It's bug to be fixed :)
