### ISSUE TITLE
IDEA: Privatization rector

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1273]
```diff
-    const FILTER_TYPE_TOP = 'top';
+    public const FILTER_TYPE_TOP = 'top';
```

Check for usages of that constant, if it is not used outside of current object, it should be `private` instead of `public`.

Same is applicable for methods and properties.

**Comment by TomasVotruba** [comment]
Ah, it's already here: #151

Closing in favor of that issue and moving your comment there

**Comment by JanMikes** [comment]
Awesome, thank you 👍
