### ISSUE TITLE
Project specific rectors should be in their own repos

### ISSUE THREAD

**Issue by tomasfejfar** [RectorPHP/Rector#129]
This looks amazing! Really looking forward to testing it. One thing I noticed straight from the README, though. Shouldn't the nette, symfony, etc rectors be in their own repositories? I think it will be a pain, further down the road, to strip them from the main repo and notify everyone to update the dependencies, etc.

**Comment by grogy** [comment]
It is great idea, but for now I mean it is over engineering. Main primary reason is Rector API is not stable. I like this way - simple for use, simple for development, simple for tests :-)

**Comment by TomasVotruba** [comment]
I don't understand your issue. What should that solve?

**Comment by TomasVotruba** [comment]
Closing for now for reasons that @grogy mentioned. Let's focus on API maturation now instead of premature split

**Comment by TomasVotruba** [comment]
Closing for now for reasons that @grogy mentioned. Let's focus on API maturation now instead of premature split
