### ISSUE TITLE
Code sample for ExplicitBoolCompareRector cotains error

### ISSUE THREAD

**Issue by slepic** [rectorphp/rector#1290]
https://github.com/rectorphp/rector/blob/master/packages/CodeQuality/src/Rector/If_/ExplicitBoolCompareRector.php

-        if (!count($items)) {
+        if (count($items) !== 0) {

it is not equivalent:  ((!count($items)) === (count($items) !== 0)) === false
I'm not sure whether the rector itself is also wrong, i havent checked. I suppose it's ok. Anyway, also AllRectorsOverview carries this typo
https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md

And maybe there are other occurences...

**Comment by TomasVotruba** [comment]
What would be the correct replacement then?

See https://3v4l.org/UCd1b

**Comment by slepic** [comment]
!count($items) is true when there are no items
count($items) !== 0 is true when there is at least one item

the correct replacement imho is "count($items) === 0"

**Comment by slepic** [comment]
The test case seems ok tho
https://github.com/rectorphp/rector/blob/master/packages/CodeQuality/tests/Rector/If_/ExplicitBoolCompareRector/Fixture/count.php.inc

**Comment by TomasVotruba** [comment]
I see. It's just a typo
