### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [rectorphp/rector#1299]
Hello, I really like your project and I'd like to contribute by designing a logo for it. Before I start, I'd like to know if you want one, and if there's anything specific you'd want to have in the logo :)

**Comment by TomasVotruba** [comment]
Hi, thank for feedback, that's very nice of you :)

I'm happy with current logo and idea behind it - https://getrector.org/
But I'm always opened to innovations.

**Comment by newfinal100** [comment]
Oh I didn't realize you already have a logo, sorry :) but I have one variation which I did now, before I read your reply, so I'm attaching it here in case you'd want to use this one. If you like the idea I'll be happy to make any improvements or changes to it :) if not that's still okay!

![Rector variation-01](https://user-images.githubusercontent.com/49202520/55672793-6a6bba00-589f-11e9-9658-52a755727b59.jpg)

**Comment by TomasVotruba** [comment]
That happens :)

The logo must tell the Rector story.

Old house with holes in the left, brand new house with modern windows in the right. Instant reconstruction from your old house to new one. Easy and fast.

**Comment by newfinal100** [comment]
![Untitled-6-01](https://user-images.githubusercontent.com/49202520/55674056-b58dc900-58af-11e9-9d37-88e9a5e540e1.jpg)

What about this?

**Comment by TomasVotruba** [comment]
It looks like a batman sign a bit. Reconstruction is having a single house (code) that is only polished to a new verison.

**Comment by TomasVotruba** [comment]
I'll stick with current logo, thanks
