### ISSUE TITLE
Rector fails to run

### ISSUE THREAD

**Issue by tomasfejfar** [RectorPHP/Rector#130]
I run rector as standalone project. If I run it on my project like this:

`php w:\git\rector\bin\rector process src --level symfony40`

I get following error

```
...
 - src\Admin\Media\Image\EntityType.php

...and 356 more.

PHP Notice:  Undefined property: PhpParser\Node\Stmt\Trait_::$extends in W:\git\rector\src\NodeAnalyzer\ClassAnalyzer.php on line 48

Notice: Undefined property: PhpParser\Node\Stmt\Trait_::$extends in W:\git\rector\src\NodeAnalyzer\ClassAnalyzer.php on line 48
PHP Notice:  Undefined property: PhpParser\Node\Stmt\Trait_::$implements in W:\git\rector\src\NodeAnalyzer\ClassAnalyzer.php on line 58

Notice: Undefined property: PhpParser\Node\Stmt\Trait_::$implements in W:\git\rector\src\NodeAnalyzer\ClassAnalyzer.php on line 58
PHP Notice:  Undefined property: PhpParser\Node\Stmt\Interface_::$implements in W:\git\rector\src\NodeAnalyzer\ClassAnalyzer.php on line 58

Notice: Undefined property: PhpParser\Node\Stmt\Interface_::$implements in W:\git\rector\src\NodeAnalyzer\ClassAnalyzer.php on line 58

[Rector\BetterReflection\Reflector\Exception\IdentifierNotFound]
  Rector\BetterReflection\Reflection\ReflectionClass "XY\AppBundle\Sentry\SentryObject" could not be found in the located source
```

**Comment by TomasVotruba** [comment]
Could you alway provide minimal source code?

**Comment by tomasfejfar** [comment]
Sure, but from the error I have

**Comment by TomasVotruba** [comment]
It looks like part of your message is missing.

**Comment by tomasfejfar** [comment]
Oops, I started writing an email reply and then decided to wait and give it another try. Then I accidentally send the message :)

I gave it another try. But no luck. It seems like it has a hard time using Traits. The code tries to access "extends" on something `ClassLike`, but in case it's a trait extends is not defined (`src/NodeAnalyzer/ClassAnalyzer.php:48`).  That seems to be the case for the notice. 

And about the exception - I have no idea. The class exists and is empty (only with parent and interface). 

```
// src\Sentry\SentryObject.php
<?php

declare(strict_types = 1);

namespace XY\AppBundle\Sentry;

use Consistence\ObjectPrototype;
use Consistence\Sentry\SentryAware;

abstract class SentryObject extends ObjectPrototype implements SentryAware
{

}
```

I have no idea where to start debugging. How do I pinpoint where the problem is? It says "356 more" and then fails somewhere.

**Comment by TomasVotruba** [comment]
I had similar random issues while email-answering, so I unsubscribed and reply her only :)

Thanks for more detailed code, I'll see what I can do about the trait.

---

In the meaintime, the exception with reflection could be improve here:
https://github.com/RectorPHP/Rector/blob/master/packages/NodeTraverserQueue/src/NodeTraverserQueue.php#L106

By adding a file that fails on: https://github.com/RectorPHP/Rector/blob/0cc75d58bee80233531e5c1d41cd49fba9ca81bb/packages/NodeTraverserQueue/src/NodeTraverserQueue.php#L75

If you're able to add such more informative exception, I'd be happy to accept you PR.
