### ISSUE TITLE
Laravel to Symfony

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1310]
There is whole series about it https://medium.com/from-laravel-to-symfony/from-laravel-to-symfony-1-installation-development-server-12502c45e79

**Comment by TomasVotruba** [comment]
Waits on real project

**Comment by vladyslavstartsev** [comment]
@TomasVotruba the link is denied

**Comment by TomasVotruba** [comment]
What project have you migrated?

**Comment by vladyslavstartsev** [comment]
I haven't

**Comment by TomasVotruba** [comment]
So why the link update?

**Comment by vladyslavstartsev** [comment]
because if you got to medium for this article you will get error (410), the article is not available anymore.
So, I don't want this to be lost and provided link to web.archive.org

**Comment by vladyslavstartsev** [comment]
actually we can ping @krzysztofengineer (the author) for this, so he will move the article from medium

**Comment by TomasVotruba** [comment]
Oh, that's nice of you :+1:
