### ISSUE TITLE
Slim/Silex to Symfony

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1312]
## Silex to Symfony

- https://medium.com/@derrabus/the-silex-sunset-d0fb5f1129df
- https://medium.com/@peter.lafferty/converting-a-silex-project-to-a-symfony-project-1dc3dc30f049
- https://github.com/symfony/symfony-docs/issues/8678

## Practical PRs

- https://github.com/browscap/browscap-site/pull/45/files
- https://github.com/opencfp/opencfp/pull/895/files
- https://github.com/opencfp/opencfp/pull/867/files
- https://github.com/opencfp/opencfp/pull/888/files

**Comment by TomasVotruba** [comment]
Waits on real project

**Comment by felixb-croesus** [comment]
Was this ever implemented? I have 4 projects to migrate from php 5.4 to 8.2 using this specific tech

**Comment by TomasVotruba** [comment]
Not yet, it would require a motivated client with such a need.

**Comment by felixb-croesus** [comment]
I see, thank you!
