### ISSUE TITLE
[DeadCode] RemoveUnusedPrivateMethodRector removes private methods from traits

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1334]
There is a valid use case for using `private` in traits if you do not want child classes of a class that uses a trait to inherit the method/property that a trait defines.

https://3v4l.org/keT0W

RemoveUnusedPrivateMethodRector removes private methods from traits in <= 0.4.11 version.

![image](https://user-images.githubusercontent.com/1755573/56560592-21a54800-65a5-11e9-9c69-33593cddab25.png)

**Comment by TomasVotruba** [comment]
Thanks for the report with screenshot.

- Is the trait used anyhwere?
- What is the expected behavior?

**Comment by mxr576** [comment]
Yes, it is used in two classes and the `ensureTeamParameter()` method gets called in 4 places. 

The expected behavior that the private method is not being removed because it is in use.

**Comment by TomasVotruba** [comment]
I see, thanks for clarification
