### ISSUE TITLE
[Support request] How to find used traits in a class

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1335]
including inherited trait usages from parent classes.

I had had my own "hacky" solution with reflection to find whether XY trait for this but I thought... there must be a better way to do that. Checked some rectors and I found `\Rector\NodeContainer\ParsedNodesByType` and `\Rector\PhpParser\Node\Manipulator\ClassManipulator` services. It seems, both provide methods to find whether a trait is in use in a class but none of them is sufficient to figure out whether `Foo` trait is in use in `Baz` class in this example: https://3v4l.org/TVfkv

Can you help me figure out what should be the best way to get this information?

This is where I stuck:

```
    /**
     * @param string $node
     *
     * @return bool
     */
    private function isTraitInUse(Node\Stmt\Class_ $node): bool
    {
        $isUsed = array_key_exists(self::REPLACED_TRAIT_FQN, $this->classManipulator->getUsedTraits($node));
        if (!$isUsed && $node->extends !== null) {
            // This returns null because parent class has not been loaded...
            $parentClassNode = $this->parsedNodesByType->findClass($this->getName($node->extends));
            // $isUsed = array_key_exists(self::REPLACED_TRAIT_FQN, $this->classManipulator->getUsedTraits($parentClassNode));

        }

        return $isUsed;
    }
```

**Comment by mxr576** [comment]
Maybe I am trying to solve the actual task in an incorrect way here... 

The actual task is property removing a deprecated trait (Foo) from a codebase, which means:
* properties provided by a trait should be still available, even if they are not used
* methods provided by a trait should be still available, even if they are not used

So the actual question is this example is how can I figure out whether the "sayHello()" in the Baz class is coming from the Foo trait or somewhere else.

**Comment by TomasVotruba** [comment]
I'm getting lost in here.

What are you trying to achieve in your application?

**Comment by mxr576** [comment]
I may have thinking aloud a little bit in my previous comments... sorry about that :)

Here is a new example that I would like to refactor with my rector: https://3v4l.org/KCHNs

DeprecatedTrait trait has been deprecated and it will be removed in the next version, which means
* all non-private methods/properties that it provided should be added to all classes that used the trait to ensure BC - code style checker will remove unused methods later ✅ 
* All usage of sayHello() method that is inherited from DeprecatedTrait should be replaced with \NewClass::sayWelcome() call. ❓ 

For the last point, I would need to know whether a `$this->sayHello()` MethodCall node refers to a method inherited from the deprecated trait (class Foo and Bar) or not (class Baz).

How can I extract this information from a MethodCall node or its parent Class node?

**Comment by TomasVotruba** [comment]
Let's say you know `sayHello` is called from deprecated trait. What should happen then?

**Comment by mxr576** [comment]
Sorry for the delayed reply, my other projects required too much attention :S.

As I wrote: 
> All usage of sayHello() method that is inherited from DeprecatedTrait should be replaced with \NewClass::sayWelcome() call.

Actually, this is the rector that I wanted to optimize or rewrite if there is a better way to do what I implemented:
https://github.com/drupal8-rector/drupal8-rector/pull/15

**Comment by mxr576** [comment]
So the new ImportFullyQualifiedNamesRector gave me some ideas about how can I simplify and rewrite my UrlGeneratorTraitRector. Now I also know more about the order of Rector processes files and calls rectors on files. I do not know how many time I rewrote this rector and probably this is not the last time... after every new Rector release, I learn something new, its API changes quickly.

@TomasVotruba  Are you planning to create a blog post series about how to write your own rector? Or an introduction about different components in Rector? Ex.: classes in `Rector\NodeTypeResolver\NodeVisitor`  namespace.
If I would like to be completely honest, I really like the tool that you are building :tada: but its documentation could be better. Most of the times I have to reverse engineer a class or a method to understand what it does and how does it do ;S 

https://github.com/drupal8-rector/drupal8-rector/pull/15/commits/38b61f314629b5b64234d19dbe4847afcf3b0525

**Comment by TomasVotruba** [comment]
The first documentation is in README:
https://github.com/rectorphp/rector#1-create-new-rector-and-implement-methods

Writing documentation would mean copy-pasting whole code to markdown in some structure. There are so many things you can do with AST, so it would be constantly outdated and not useful at all :).

The code is the best documentation.

It's much better to read existing rules + tests and find the similar you need.

<br>

As for Node Visitor - I recommend reading all this: https://github.com/nikic/PHP-Parser/tree/master/doc

**Comment by TomasVotruba** [comment]
To your original issue, you could make use of `Rector\NodeContainer\ParsedNodesByType::findUsedTraitsInClass()`

On the other hand it might be useflu to add new method `findClassesUsingTraits()` based on similar principal.
