### ISSUE TITLE
Wrong repository class injected by Architecture\RepositoryAsService\ServiceLocatorToDIRector

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1337]
When using `Architecture\RepositoryAsService\ServiceLocatorToDIRector` the repository injected in the constructor is wrong.

In fact, I have the `Document` (from ODM = Entity from ORM) `WebResource` and for it I have a repository in `App\Repository\WebResourceRepository`.

But the injected repository have the namespace `App\Document\WebResourceRepository`, so, basically, using this rector breaks the application as the repo's class is not found.

**Comment by TomasVotruba** [comment]
Hi, could you provide minimal failing code and expected behavior (diff)?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Feel free to reopen with fixing PR
