### ISSUE TITLE
[DeadCode] RemoveUnusedPrivateMethodRector removes private methods used in static method

### ISSUE THREAD

**Issue by msvrtan** [rectorphp/rector#1338]
Hi,

When using RemoveUnusedPrivateMethodRector, it removes private methods used by static method inside the class, while it shouldnt: 

Just a simple example, `setId` should not be removed,
```
class Customer
{
    private $id;
    public static function create($id){
        $customer = new self();
        $customer->setId($id);
        return $customer;
    }
   private function setId($id){
      $this->id=$id;
   }

}
```

Running rector v0.4.11

**Comment by TomasVotruba** [comment]
Hi Miro,

agreed, thanks for reporting.
