### ISSUE TITLE
RemoveUnusedPrivatePropertyRector: removes properties used in trait

### ISSUE THREAD

**Issue by msvrtan** [rectorphp/rector#1341]
Given we have a set of classes that use a `ExampleTrait` that needs `ExampleDependency`, `RemoveUnusedPrivatePropertyRector` removes ExampleDependency from `Example`

```
class Example{
   use ExampleTrait;
   private $dep;
    public function __constructor(ExampleDependency $dep)
    {
       $this->dep = $dep;
    }
}

trait ExampleTrait{
   
    private function doSomething()
    {
       $this->dep->doWork();
    }
}
```

would result in 

```
class Example{
   use ExampleTrait;
    public function __constructor(ExampleDependency $dep)
    {
    }
}
```

and together with `RemoveUnusedPrivateMethodRector` bug reported in #1334 would result in:
```
trait ExampleTrait{
   
}
```

**Comment by TomasVotruba** [comment]
Thanks for reporting. Trais support is lacking now, it will covered in near future release
