### ISSUE TITLE
Downgrading code

### ISSUE THREAD

**Issue by filips123** [rectorphp/rector#1343]
Is it possible to "downgrade" code?

This would enable writing new and modern code, but running it on some old system (which maybe can't be updated).

**Comment by TomasVotruba** [comment]
Hi, it is not. You'd have to basically make all rules again to do that direction.

Doing that would probably slow development of upgrading to 30 %, so it's a no go.

But you can look at rules and make downgrading versions.

**Comment by TomasVotruba** [comment]
> Which maybe can't be updated

Btw, it if it's project on PHP 5.2-, it can't be upgraded/downgraded.

If it's PHP 5.3+, it can be updated :)

**Comment by TomasVotruba** [comment]
Hi,

good news from the past :) 

One year leater, this became a thing: 
https://twitter.com/rectorphp/status/1301822927604678659
