### ISSUE TITLE
Fatal error when updating Symfony 2.1 to 2.8

### ISSUE THREAD

**Issue by andyexeter** [rectorphp/rector#1344]
I'm trying to update a codebase from Symfony 2.1 to 2.8. I assume I need to actually update the version of Symfony the application uses to 2.8 before running rector, which I have done with `composer update`, then when I run the following command:

```
$ rector process src app --level symfony28
```

I get the following output:

```
Rector v0.4.11

    0/3303 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  330/3303 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   9%
  660/3303 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  19%
  990/3303 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  29%PHP Fatal error:  Access level to Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::$container must be protected (as in class Symfony\Component\HttpKernel\EventListener\SessionListener) or weaker in /home/vagrant/dev/api2/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/EventListener/SessionListener.php on line 22

Fatal error: Access level to Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::$container must be protected (as in class Symfony\Component\HttpKernel\EventListener\SessionListener) or weaker in /home/vagrant/dev/api2/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/EventListener/SessionListener.php on line 22
```

I had a look at `Symfony\Component\HttpKernel\EventListener\SessionListener` and it doesn't actually have a `$container` property so I'm not sure why it's erroring.

I have updated the Symfony bundle to 2.8.51 and am running PHP 7.1. I installed rector globally with `composer global require rector/rector` which I hoped would avoid conflicts as per #985

**Comment by TomasVotruba** [comment]
This could be resolve only with prefixed versoin, that creates unique class naming, see similar issues:

Same error as https://github.com/rectorphp/rector/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Awaits-on-prefixed

**Comment by andyexeter** [comment]
Thanks for the reply. Would https://github.com/rectorphp/compiler work if I compile and use a .phar?

**Comment by TomasVotruba** [comment]
Yes, but it still need some work and I have other priorities now

**Comment by TomasVotruba** [comment]
See #177
