### ISSUE TITLE
[Laravel] MinutesToSecondsInCacheRector: adds seconds to Carbon instance

### ISSUE THREAD

**Issue by devfrey** [rectorphp/rector#1345]
When running rector against a Laravel project with the following code, it actually breaks the implementation:

```php
Cache::put('cache_key', $somevalue, now()->addDay()); // it also accepts a Carbon (\DateTimeInterface) object
```

It turns it into this, which won't work:
```php
Cache::put('cache_key', $somevalue, now()->addDay() * 60);
```

**Comment by TomasVotruba** [comment]
What's the expected change?

**Comment by devfrey** [comment]
It should simply ignore it. `Cache::put()` accepts a `\DateTimeInterface`, which wasn't affected by the minutes-to-seconds change.
