### ISSUE TITLE
Improve SimplifyIfIssetToNullCoalescingRector check

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#1358]
I've found another pattern that we might want to implement in `SimplifyIfIssetToNullCoalescingRector`:
```diff
function foo(): ?string {
-    if (isset($this->foo[$bar])) {
-        return $this->foo[$bar];
-    }
+    return $this->foo[$bar] ?? null;
}
```

**Comment by TomasVotruba** [comment]
Well, the code is not substitute. There is `return null` missing in the first code

**Comment by carusogabriel** [comment]
@TomasVotruba The `null` in implicit, not explicit: https://3v4l.org/GFq8j.

Please, reopen the issue.
