### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mimmi20** [rectorphp/rector#1366]
I tried to run this command ` vendor/bin/rector process src --level symfony40 --dry-run` on my project (this is a sample from the readme.md).

I got this error:
```shell
[ERROR] Could not process "/home/developer/projects/BrowserDetector/src/Detector.php" file, due to:
         "Implement "PHPStan\PhpDocParser\Ast\PhpDoc\DeprecatedTagValueNode" to
         "Rector\BetterPhpDocParser\Attributes\Ast\AttributeAwareNodeFactory::createFromPhpDocValueNode"".
```

![image](https://user-images.githubusercontent.com/1120192/56957355-1f179500-6b47-11e9-8011-8c6623f7f328.png)

I used
- rector/rector@dev-master
- symplify/package-builder@dev-master as 5.4.17
as I require Nette 3.0

**Comment by TomasVotruba** [comment]
This looks like BC break in `phpstan/phpdoc-parser`.

```
"Implement "PHPStan\PhpDocParser\Ast\PhpDoc\DeprecatedTagValueNode" to
         "Rector\BetterPhpDocParser\Attributes\Ast\AttributeAwareNodeFactory::createFromPhpDocValueNode""
```

From the error I assume `DeprecatedTagValueNode` needs to be added in `AttributeAwareNodeFactory`.

**Comment by TomasVotruba** [comment]
Related to https://github.com/phpstan/phpdoc-parser/pull/23
