### ISSUE TITLE
[Idea] Child method compatible with parent (missing typehint or argument)

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1371]
## Situation 1:

```diff
abstract class Parent {
    public function a(string $a) { }
}

final class Child extends Parent {
-    public function a($a) { }
+    public function a(string $a) { }
}
```

Related to PHP 7.1 only: https://3v4l.org/Ev0XJ

## Situation 2

```diff
abstract class Parent {
-    public function a($a) { }
+    public function a($a, $b = null) { }
}

final class Child extends Parent {
    public function a($a) { }
    public function a($a, $b = null) { }
}
```
(i am not sure if situation 2 would work without optional parameter - default value)

Related to PHP 7.1+ - see https://3v4l.org/8K3sp

**Comment by TomasVotruba** [comment]
Covered by TypeDeclaration set. It needs to be used before the update of code-breaking change, as Rector cannot process invalid code
