### ISSUE TITLE
PSR-4 rector - when filename is different to any class in file, it stays untouched

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1372]
Config:

```yaml
services:
    Rector\Rector\Psr4\MultipleClassFileToPsr4ClassesRector: ~
```

File `A.php`:
```php
class B { }
Class C { }
```

command:
```
vendor/bin/rector process A.php
```

Result is that A.php stays with both classes and B.php and C.php are created.

I would expect either that A.php will be deleted or at least it will be edited, because this creates problem with duplicate classes.

**Comment by JanMikes** [comment]
Goodie! Thank you, will try it out

**Comment by JanMikes** [comment]
Confirming it works as expected now 👍

**Comment by TomasVotruba** [comment]
Thank you!
