### ISSUE TITLE
[PSR-4] Ultimate Psr4RootRector (maybe set)

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1374]
This could be set of rules (i don't think there should be only 1 rector handling this), migrating legacy project with classmap (or etc robotloader) autoloading to PSR-4.

Tasks:
- Rename file according to class
- Split multiple classes in same file to multiple files
- Read PSR-4 roots from composer.json and fix incorrect class namespace (there might be namespace missing completely)

**Comment by TomasVotruba** [comment]
In the meantime there are few Rectors covering this topic:

- https://github.com/rectorphp/rector/pull/1865
- https://github.com/rectorphp/rector/pull/1414

**Comment by TomasVotruba** [comment]
Covered by few Rectors for some time now.

Closing for now, as needs practical project to test on
