### ISSUE TITLE
[Bug] ImportFullyQualifiedNamesRector imports functions as classes

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1376]
I'm using the library https://github.com/thecodingmachine/safe.

Until now, I've used their functions this way:

    \Safe\sprintf(...);

Now, with the new Rector `ImportFullyQualifiedNamesRector` imported it this way:

```php

use Safe\sprintf;

\Safe\sprintf(...);

```

This causes issues with static analysis and with PHPStorm.

The solution is to import the functions using `import function Safe\sprintf`.

See https://github.com/phan/phan/issues/2705

**Comment by TomasVotruba** [comment]
I didn't include functions yet. Thanks for reporting
