### ISSUE TITLE
ShouldNotHappenException while running tests in phpstorm

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1380]
Hi, when i run `vendor/bin/phpunit` it is completely okay.

But when i want to run specific test using phpstorm, it ends up throwing
```
Rector\Exception\ShouldNotHappenException /Users/janmikes/Sites/rector/src/Testing/PHPUnit/AbstractRectorTestCase.php:73
```

Here is full command phpstorm is trying to run:
```
/usr/local/bin/php /Users/janmikes/Sites/rector/vendor/phpunit/phpunit/phpunit --no-configuration --filter "/(::test)( .*)?$/" Rector\Tests\Rector\Class_\RenameClassRector\RenameClassRectorTest /Users/janmikes/Sites/rector/tests/Rector/Class_/RenameClassRector/RenameClassRectorTest.php --teamcity
```

Having this working is extremely important to run and debug only specific test ;-) 

<img width="1633" alt="Screenshot 2019-05-03 15 58 03" src="https://user-images.githubusercontent.com/3995003/57142192-3f9c5500-6dbc-11e9-8570-a78b00cd8441.png">

**Comment by JanMikes** [comment]
Fixed :-) explicitly setting path to phpunit.xml solved the problem, i have no idea why phpstorm does not recognize it properly by default

<img width="804" alt="Screenshot 2019-05-03 16 00 18" src="https://user-images.githubusercontent.com/3995003/57142341-93a73980-6dbc-11e9-8594-2ca2c8c43f86.png">

**Comment by TomasVotruba** [comment]
I found the same solution :)

Btw, why is not phpunit.xml autolaoded by default? It look like bug in PHPStorm

**Comment by JanMikes** [comment]
Yeah i do not know, it might be because of the `--no-configuration` option, but still, phpstorm should recognize it and set it up properly

**Comment by TomasVotruba** [comment]
Indeed it should. If it happens again, we can extends the exception message with this solution
