### ISSUE TITLE
[CodingStyle] Split multi var definitions to own lines

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1384]
Own line in class:

```diff
-$whitespace = true, $unicode = false;
+$whitespace = true;
+$unicode = false;
```

Also for constants

**Comment by carusogabriel** [comment]
I don't think this statement is true: https://3v4l.org/h0J5F.

**Comment by JanMikes** [comment]
Hey, maybe @TomasVotruba you mean this?:
```php
class MyClass
{
    public $a = 4, $b = 5;
}
```

I have seen this often times anyways in Glami's legacy codebase 😄

**Comment by TomasVotruba** [comment]
@JanMikes Yes :)

**Comment by TomasVotruba** [comment]
I'm on it

**Comment by TomasVotruba** [comment]
https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#splitgroupedconstantsandpropertiesrector

:+1:
