### ISSUE TITLE
Print info about what level (set) is used

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1396]
Having following console output:
```log
▶ docker run -v $(pwd):/project rector/rector process --autoload-file /project/vendor/autoload.php --level symfony40 /project/app /project/src          
Rector No version set (parsed as 1.0.0)@
Config file: /rector/rector.yaml
```

It would be awesome to have `Level: symfony40` info there, so i am sure it is beign used, in same way as `Config file: xxx` is.

**Comment by TomasVotruba** [comment]
Config is displayed because there were more paths it can be autoloaded from and sometimes it was missed. 

Level is entered manually by used, so he or she knows the level. It would only clutter the output:

```bash
vendor/bin/rector process --level symfony
level: symfony
```

What's the motivation behind this?

**Comment by JanMikes** [comment]
I was running that command and only rector applied to project was `Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector` so i was not sure and have no way how to debug whether symfony level was really used or https://github.com/rectorphp/rector/blob/master/rector.yaml

**Comment by TomasVotruba** [comment]
I see. In that it's debug info, that you can display by `show` command.

UX and debug should not be combined. Common user would be bothered by printing so duplicated data.
