### ISSUE TITLE
ImportFullyQualifiedNamesRector: opt-out from docblock modification

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1409]
ImportFullyQualifiedNamesRector replaces fully qualified class names in doc blocks. This behavior causes a PHPCS issue in [Drupal](https://www.drupal.org/docs/develop/coding-standards/namespaces). It would great if this behavior could be disabled with a configuration.

![image](https://user-images.githubusercontent.com/1755573/57523468-5ba47700-7325-11e9-8868-77199f8cad8d.png)

**Comment by TomasVotruba** [comment]
It makes sense. Feel free to add constructor argument, that allow to disable it.

`$shouldImportDocblocks = true`
