### ISSUE TITLE
Error if magically set object in if()

### ISSUE THREAD

**Issue by tonymrakovcic** [rectorphp/rector#1413]
Hello,

First of all I would like to say I love this project and I think it's totally awesome!
I was testing it out, what it can do on a legacy project of mine, and found a weird behavior that I would like to submit to you to check out.
Maybe it's an issue, maybe it's not, I'll let you be the judge of that, since I am still just experimenting with Rector.

The issue seems to be related to magically set objects, when they are in an if statement without some kind of isset or similar (empty() etc)
I am trying this out on a Yii1 project.

Behaviour:

When using 
```
vendor/bin/rector process protected --level code-quality  --autoload-file vendor/autoload.php --dry-run
```

The code snippet that fails:
```
if($policy->insuranceinfo) {
```

It throws an error

```
 [ERROR] Could not process "/Users/tonymrakovcic/work/project/protected/views/site/overview.php" file, due to:       
         "Argument 1 passed to Rector\PhpParser\Node\Manipulator\ClassManipulator::getProperty() must be an instance of 
         PhpParser\Node\Stmt\Class_, null given, called in                                                              
         /Users/tonymrakovcic/work/project/vendor/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php on
         line 515".    
```

If the statement looks like this:
```
if(isset($policy->insuranceinfo)) {
```
or
```
if(empty($policy->insuranceinfo)) {
```

Everything is ok and it goes through processing.
$policy is an object (Model from yii1), and ->insuranceinfo is another object(Model, relation on Policy). These are magically set on the object.

Here is how Yii1 does it exactly (I know this is ancient but I guess this kind of library will want to try to handle these kind of things);

```
/**
 * PHP getter magic method.
 * This method is overridden so that AR attributes can be accessed like properties.
 * @param string $name property name
 * @return mixed property value
 * @see getAttribute
 */
public function __get($name)
{
	if(isset($this->_attributes[$name]))
		return $this->_attributes[$name];
	elseif(isset($this->getMetaData()->columns[$name]))
		return null;
	elseif(isset($this->_related[$name]))
		return $this->_related[$name];
	elseif(isset($this->getMetaData()->relations[$name]))
		return $this->getRelated($name);
	else
		return parent::__get($name);
}

```

Thats it.
Let me know if you need anything more elaborate on the subject.

**Comment by TomasVotruba** [comment]
Hi, could you provide the whole class? There will be something related

**Comment by tonymrakovcic** [comment]
Hi,

unfortunately I cannot provide the inner most class (Policy) due to the reason that it has business logic that I suspect the client would not be happy disclosing (its an ancient legacy system so I isn't the greatest piece of code)

The active record class is this:
https://github.com/yiisoft/yii/blob/master/framework/db/ar/CActiveRecord.php

it's a ```BELONGS_TO```relation

**Comment by TomasVotruba** [comment]
The exact code is not needed. Just the minimal PHP code. I think it will take 20 libes

**Comment by tonymrakovcic** [comment]
lets say something like this

```
class Policy extends CActiveRecord
{
    public $insuredPassengerArray = [];
    
    public function relations(): array
    {
        return [
            'contractorinfo' => [self::BELONGS_TO, 'ContractorInfo', 'personalInfoId'],
            'insuranceinfo' => [self::BELONGS_TO, 'InsuranceInfo', 'insuranceOptionsId'],
            'insuredpassenger' => [self::HAS_MANY, 'InsuredPassenger', 'policyId'],
            'travelinfo' => [self::BELONGS_TO, 'TravelInfo', 'travelInfoId'],
        ];
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Policy the static model class
     */
    public static function model($className = __CLASS__): Policy
    {
        return parent::model($className);
    }
}
```

and then instantiated with
```
$policyModel = new Policy();
$insuranceInfoModel = new InsuranceInfo();
$policyModel->insuranceinfo = $insuranceInfoModel;
```

**Comment by TomasVotruba** [comment]
Is that code from `overview.php`? I don't see any `if`

Last thing we need is rensponsible rector rule.

Try running it on the file with `--debug` verbosity.

```
vendor/bin/rector process protected/views/site/overview.php --level code-quality --debug
```

**Comment by TomasVotruba** [comment]
Missing failing tests case, PR is needed
