### ISSUE TITLE
[Bug] ImportFullyQualifiedNamesRector does not fix all FQCNs

### ISSUE THREAD

**Issue by mxr576** [rectorphp/rector#1421]
Because ImportFullyQualifiedNamesRector rector only checks files that have namespaced defined it it does not fix FQCNs in a procedural code like this.

```
<?php

function foo() {
    $baz = \Foo\Bar::Baz;
}
-----
<?php

use Foo\Bar;

function foo() {
    $baz = Bar::BAZ;
}

```

**Comment by TomasVotruba** [comment]
Indeed. Care to send PR?

**Comment by mxr576** [comment]
Not sure yet about the best solution for this problem, do you have an idea how this could be fixed?

**Comment by TomasVotruba** [comment]
Do 1 path for namespace and one without (this already exists).

**Comment by TomasVotruba** [comment]
Here is the exactly same issue just for different rule: https://github.com/rectorphp/rector/issues/1422

**Comment by TomasVotruba** [comment]
This will be more complicated, since it's not easy to add nodes without namespace above them.

I'll investigate

**Comment by mxr576** [comment]
Yeah, I bumped into to this problem before this was the reason why I asked your opinion about this :)

**Comment by TomasVotruba** [comment]
Sure :)

It will require adding new layer in Rector, that will work even with arrays of stmts, not just Node of type. I postponed this for a long time, because it's really not easy to solve.

**Comment by TomasVotruba** [comment]
It was a "bit" complicated, but it's done :rocket: 

![image](https://user-images.githubusercontent.com/924196/58189495-e3419c80-7cba-11e9-9700-0c57f4342978.png)


I've merged it to `master`. Could you test it on your code base?

**Comment by mxr576** [comment]
Awesome! 👍 This was a busy week, I'll try to check it in the weekend or early next week.

**Comment by mxr576** [comment]
Well, took more time as I expected... but now I am here. Testing it now :)
