### ISSUE TITLE
PHP fatal error Nette DI NeonAdapter

### ISSUE THREAD

**Issue by pavarnos** [rectorphp/rector#1427]
When i clean out my composer global directory, then do
`composer global require rector/rector`
i see
```
Using version ^0.4.12 for rector/rector
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 38 installs, 0 updates, 0 removals
.... etc
```

when i run `rector` from the command line i see

`PHP Fatal error:  Declaration of Nette\DI\Config\Adapters\NeonAdapter::load($file) must be compatible with Nette\DI\Config\Adapter::load(string $file): array in  .composer/vendor/nette/di/src/DI/Config/Adapters/NeonAdapter.php on line 19`

Looks like a package far upstream (NeonAdapter) has not realised that its dependency (Nette/DI) is now using strict types. Any chance of tweaking rector composer version dependencies to work around the problem while they fix the upstream?

**Comment by TomasVotruba** [comment]
Hi,

any "must be compatible error" can we solved by prefixed Rector. 

See other issues https://github.com/rectorphp/rector/issues?q=is%3Aissue+is%3Aopen+label%3Awaits-on-prefixed

I started some work here: https://github.com/rectorphp/compiler, but never  really finished

**Comment by pavarnos** [comment]
ok. thanks
after a bit of digging i think i see the problem.
rector 0.4.12 depends on phpstan 0.11.5 which has dependencies through to nette/di 2.4.7
my project has phpstan 0.11.6 installed, which depends on nette/di 3.0.0
your next release of rector depends on phpstan 0.11.6 so it will all sort itself out at your next rector release.

Problem happens in rector/bin/bootstrap.php which loads the _projects_ autoload in preference to the autoload for the directory where rector lives (which may be different eg in a `composer global` install).

If it were somehow possible that you did not depend on the autoload of the project (or could write a custom autoloader just for project source files that ignored project `vendor` files) then maybe possibly the compiler / prefixer would not be needed?

Random thought: feel free to ignore if it is way off track. 
Thanks for the great project: it saved me many many hours.

**Comment by TomasVotruba** [comment]
Afaik, PHP cannot autoload 2 same classes with different signature.

> Thanks for the great project: it saved me many many hours.

:love:
