### ISSUE TITLE
DocBlockManipulator - Poor performance

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1428]
After some digging (Thank you @TomasVotruba for hot tips!) we found out that this piece of code is extremely slow and causing rector to freeze when working with multiple rules:

```php
// RenameClassRector.php
foreach ($this->oldToNewClasses as $oldClass => $newClass) {
    $this->docBlockManipulator->changeType($node, $oldClass, $newClass);
}
```

**Comment by TomasVotruba** [comment]
... with Docker and xdebug.

https://github.com/rectorphp/rector/commit/eeae05176a5c07bbc5355b198968cc1e4df9fd7d

**Comment by JanMikes** [comment]
Actually it was without xdebug 😄 i will try it out and let you know, thank you 👍
