### ISSUE TITLE
DocBlockManipulator - Extremely poor performance (loop) if annotation contains whitespaced line - adding tons of new spaces

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1434]
I have been debugging for few hours and finally found where it is failing 😄 

Trying to run RenameClassRector on huge codebase was failing, we have some messed up annotations, for example containing empty line with whitespace:
```diff
- * 
+ *
```
I have found out this is making a lot of loops - when commenting (or deleting) `DocBlockManipulator.php:517` (`$node->setDocComment(new Doc($phpDoc));`)

It works.

I added new branch with failing test, where you can see what is wrong

**Comment by JanMikes** [comment]
So far i have fixed it via search & replace via IDE in whole project:
`(\*+)(\s+)\n` -> `$1\n`

**Comment by JanMikes** [comment]
Here is another example of what breaks up rector and starts infinity loop:

```php
/** @var  */
private $collation;
```

**Comment by TomasVotruba** [comment]
Performance test for `DocBlockManipulatorTest` is needed.

**Comment by JanMikes** [comment]
Okay! At least i have found what is causing the issues, test should not be problem, i will prepare it!! 👍

**Comment by TomasVotruba** [comment]
Closing with this solution as best:

https://github.com/rectorphp/rector/issues/1434#issuecomment-492689275
