### ISSUE TITLE
[RenameClassRector] Edge case - renaming class without namespace

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1437]
Hey, i had a situation:
```diff
+ namespace SomeOtherNamespace;
class A extends SomeNamespace\SomeClass {
    public function createSomeClass(): SomeNamespace\SomeClass
    {
        return new SomeNamespace\SomeClass;
    }
}
```

Adding namespace will cause bug as `SomeNamespace\SomeClass` is no longer valid class, it has to be prefixed with `\` or imported via use statements.

Running import fqn rector first could be option, but what do you think @TomasVotruba should we cover this edge case in RenameClassRector?

**Comment by TomasVotruba** [comment]
Indeed, it should fqnize all the names

**Comment by TomasVotruba** [comment]
Do you like to send PR or should I handle it?

**Comment by JanMikes** [comment]
Yeah, though i do not want to block you, since i know that you are working much harder on open source than me 😄

**Comment by TomasVotruba** [comment]
Go for it :) I don't think there are enough issues to fix for me

**Comment by JanMikes** [comment]
I just run into this issue again, check this (i have been doing it manually and it is just crazy, i will give this much higher prio): 

<img width="463" alt="Screenshot 2019-05-31 11 45 12" src="https://user-images.githubusercontent.com/3995003/58697288-9ab07000-8399-11e9-8043-081e314eb5fc.png">

All changes were like this:

<img width="742" alt="Screenshot 2019-05-31 11 45 57" src="https://user-images.githubusercontent.com/3995003/58697320-aa2fb900-8399-11e9-844c-2545ba83f322.png">
