### ISSUE TITLE
Consider renaming repository to lowercase

### ISSUE THREAD

**Issue by OndraM** [rectorphp/rector#144]
Hi,
please consider renaming the repository to just "rector" (until its too late to change anything :-D).

The default directory when running git clone is now "Rector", and on case-sensitive filesystems (Linux) this is unexpected (>90 % of repositories starts with lowercase character, also the composer requires the name to be lowercase, making it inconsistent ("Rector" repository, "rector" package) and hard to navigate in console (`r` + `tab` => no match).

I know its a matter of personal preference (and on case insensitive filesystems this is a non-issue), though see https://en.wikipedia.org/wiki/Principle_of_least_astonishment .

Thanks for the consideration ;)

**Comment by TomasVotruba** [comment]
Hey Ondra,
 
I never thought of this way. Thanks for explaining :+1: and POLA reference, I'll use it instead of Occam's razor.

In such case, it would make sense to make it consistent on organization as well: `rectorphp/rector`

What do you think?

**Comment by OndraM** [comment]
Hi, the org. name is used only in URL, which is on github case insensitive. It also has a benefit for being simplier to read with "PHP" uppercase (in comparison with "rector", which is just one word and the bettere readability doesn't play a role). So for me, I would keep the org. name as is.

(Yes, it may be inconsistent with composer name, but the org. name from composer is not used anywhere else...).

**Comment by TomasVotruba** [comment]
It would be wtf to have double approach in name and easy to misspell, as https://en.wikipedia.org/wiki/Principle_of_least_astonishment

Switching from one wtf to another doesn't make sense.
In PHPUnit, Symfony, Laravel way I'd keep both names having just one naming algorithm

**Comment by OndraM** [comment]
Well, I'm always thinking about actual impact of the change.

Cases in organization name does not impact **anything at all** but readability. So +1 for "RectorPHP". There is literally no place where this could astonish you (URL is case insensitive on github), so POLA not applies there.

Cases in repository name does impact you when cloning Git repository, as they are by default in the name of directory and big first letter is astonishing. So +1 for "rector" there while at the same time there is no influence on readability (rector/Rector makes no difference when reading).

But well, its up to you, and its actually not that important issue. I was just giving my feedback about  problem I have when cloning the repo ;-).

**Comment by TomasVotruba** [comment]
I understand it doesn't apply to your issue. I just I include human brain for **all other possible cases** I'm aware of. There ambiguity comes to play, so POLA applies.

Soon there might be issue "Consider naming Rector as in RectorPHP organization" :gun: :face_with_head_bandage: 

Thanks for feedback. I'll handle it soon :+1:

**Comment by OndraM** [comment]
If you say "organization name is RectorPHP" and "repositories are in lowercase", there is no ambiguity, you have different rule for different domain, which is fine, because every domain has its specific. And also, you don't use the organization name anywhere. So this is unnecessary oversimplifying IMO. But as your wish ¯\\\_(ツ)_/¯.

**Comment by TomasVotruba** [comment]
Done: https://github.com/rectorphp/rector/
