### ISSUE TITLE
[PHP 7.4] polish upcoming features accoring to nikita's talk

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1453]
Slides include many edge cases
https://twitter.com/nikita_ppv/status/1130188147940352000

**Comment by vladyslavstartsev** [comment]
There is also other fix in 7.4
https://github.com/php/php-src/pull/4092

What you can do, is to warn people about that they should check function argument before
See
https://github.com/phpstan/phpstan/issues/1827  and https://externals.io/message/104295 for example of what I mean

**Comment by TomasVotruba** [comment]
Hi, I've checked links but tl;dr; not sure what you talk about.

Could you give me small before/after PHP code of rule you suggest?

**Comment by vladyslavstartsev** [comment]
@TomasVotruba https://3v4l.org/D3s7J/rfc#output
see results for 7.4. I think you can't fix it, but at least you should warn people somehow

**Comment by TomasVotruba** [comment]
Thanks! 
Rector doesn't add work by reports, it changes code to make it work without bothering user. 

If I understand this correctly, this is the fix:

```diff
-bcadd('17 .123', '19.456', 10);
+bcadd('0', '19.456', 10);
```

**Comment by TomasVotruba** [comment]
Too broad
