### ISSUE TITLE
[Question] Rector one file to multiple

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#1454]
Hey,
I want to migrate some Doctrine models to another ORM. But I have to create multiple classes for the corresponding Model. Is there anything already implemented in Rector to do that?

Btw it would be a PR :)

**Comment by TomasVotruba** [comment]
Hi, do you the smallest example maybe?

There is PSR-4 split rule, that splits multiple classes to their own files named by the class:
https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md

**Comment by shyim** [comment]
Example Doctrine File (Source): https://github.com/shopware/shopware/blob/5.5/engine/Shopware/Models/Article/Article.php

to generate 3 files

Definition File: https://github.com/shopware/platform/blob/master/src/Core/Content/Product/ProductDefinition.php
Entity file:
https://github.com/shopware/platform/blob/master/src/Core/Content/Product/ProductEntity.php
Collection file:
https://github.com/shopware/platform/blob/master/src/Core/Content/Product/ProductCollection.php

**Comment by TomasVotruba** [comment]
> Hi, do you the smallest example maybe?

Code sample here, not links to files.

**Comment by shyim** [comment]
```php
class Article extends ModelEntity
{
   /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
}
```

to

```php
class ArticleDefinition extends EntityDefinition
{
    public function getEntityName(): string
    {
        return 'article';
    }
   protected function defineFields(): FieldCollection
    {
        return new FieldCollection([
            (new IdField('id', 'id'))->addFlags(new PrimaryKey(), new Required()),
]);
}
}
```

```php
class ArticleEntity extends Entity
{
// EntityIdTrait does provide $id as property
    use EntityIdTrait;

}

**Comment by shyim** [comment]
Ahh the rector has to extend AbstractFileSystemRector. I will start then with a PR :)

**Comment by TomasVotruba** [comment]
Yes, that would be the easiest way :) 

Is that some upgrade path for shopware next version? Seems like a huge BC break

**Comment by shyim** [comment]
Its a complete rewrite. Nothing is really same

**Comment by TomasVotruba** [comment]
I see, crazy

**Comment by crashkonijn** [comment]
@shyim I'm in the process of doing something similar, do you by any chance have an example of the rector you made? Thanks!
