### ISSUE TITLE
HTML report?

### ISSUE THREAD

**Issue by zspine** [rectorphp/rector#1455]
Hi

Really sorry if it's a support question. I just tried rector and it's amazing..... just wondering if there is any way to generate a html report? It might be really useful for team discussions.

**Comment by TomasVotruba** [comment]
Hi, that's what issues are for :)

Thanks for feedback.

What the use case? Could you give me small example of what you need?

Common standard is to have json output, that you can transfer to anything else.

**Comment by zspine** [comment]
Hi :) Thanks a lot for the quick response.

Use Case: Not relevant to coding and more of a business need. For example we used rector with --dry-run to find out the possibility of migrating an old php based app to symfony framework and now the changes needs to be discussed with the team before we apply to the code. At the moment I am dumping the output to a file with following command:

`vendor/bin/rector process private/classes --level code-quality --dry-run  > report.txt`

Yes, I agree json would be the perfect for this use case. Is it possible?

**Comment by TomasVotruba** [comment]
I see :+1: 

> Is it possible?

I'm open to accept PR.

**Comment by zspine** [comment]
If you are ready to accept PR, definitely will check in to it! 

Cheers!

**Comment by TomasVotruba** [comment]
I made this #1477, so it's more easier for you to add a new `OutputFormatter`.

All you need to do is implement `OutputFormatterInterface`

**Comment by zspine** [comment]
@TomasVotruba WOW excellent! Thanks a lot for your time and effort! this feature simplifies lots of work! Sure will check in to it and will give you an update!

**Comment by TomasVotruba** [comment]
Hi, we need this feature ASAP for Rector CI service. 
But I don't want to take your work, if you have already started. Would you say you'll get to it today/tomorrow?

If not, I'll handle it.

**Comment by zspine** [comment]
Hi @TomasVotruba 

Rector CI? Exciting.... I scheduled it for this weekend and I haven't started the work yet! Unfortunately Today/Tomorrow not possible :( REALLY SORRY ABOUT THAT (Month end and stuck with lots of deadline, otherwise I would love to do it)

Thank you

**Comment by TomasVotruba** [comment]
No troubles :) there are many other issues if you want to contribute ;)
Good luck with deadlines!

**Comment by zspine** [comment]
well done and thanks for the update! I love this feature, it's a game changer for us! I just checked the change list and lots of file change! Definitely I cannot work at that speed! I am still learning the internals of rector.

Cheers!

**Comment by TomasVotruba** [comment]
Thanks for honest cheerful feedback.

Let me know if you have any troubles :)

**Comment by matheusab** [comment]
I know it's closed, but in case anyone is looking for a html report generator, here it is:
https://github.com/matheusab-soft/rector-html-output-formatter

By the way, thanks for the amazing library, Tomas!
