### ISSUE TITLE
Backslash is prepended to every use of global class or function

### ISSUE THREAD

**Issue by tomasfejfar** [rectorphp/rector#1456]
I tried to use rector do replace `'MyClass'` and `'\MyClass'` with `MyClass::class`. 

I found [SplitStringClassConstantToClassConstFetchRector](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#splitstringclassconstanttoclassconstfetchrector). 

I set up the `rector.yml` as follows:
```
services:
  Rector\CodingStyle\Rector\String_\SplitStringClassConstantToClassConstFetchRector: ~
```
When I run it with `--config=rector.yml` is touches almost every file and replace every class that is not FQCN with it's FQCN. 

For example:

`$x = substr(0,1,$some)` → `$x = \substr(0,1,$some)`

That is unexpected. I assumed that it will only touch things that it fixes. Also, why does it prepend the backslash? I only have the one rector enabled.

**Comment by tomasfejfar** [comment]
Thanks for the tip. 

Well, anyway, that's just a first step. Next step would be to fix legacy calls to `$this->container('some.string.whatever')` to method calls like `$this->getWhatever(): Whatever`. 

But still prefixing everything with backslash while doing this seems unreasonable.

**Comment by TomasVotruba** [comment]
Slash at native function names is definitely annoying.

Could you send failing test to `SplitStringClassConstantToClassConstFetchRectorTest`?
I'll look at it.

Just to be sure, what Rector version do you use?

**Comment by TomasVotruba** [comment]
@JanMikes I think slashes are problem. The rule should be moved here: https://github.com/rectorphp/rector/issues/1457
Coding standards for programming are dead I guess :D

**Comment by TomasVotruba** [comment]
@tomasfejfar I'm looking into statements, and AST is not really good for coding standard changes. There will always some extra space, slash or something missing.

AST cannot never beat tokens in this and it's not effective to use AST for it.

Best practise is to use own style after Rector 
run: https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by tomasfejfar** [comment]
That's quite unfortunate. Not every aspect of how to code should look like is part of the coding standard. I thought that, as the AST contains location (`ast\Node::$lineno`), it's possible to limit the changes only to the affected region of the file. 

I would never expect it to match my code style, but I would expect it to affect only the smallest possible region of the file, rather than redumping the whole thing from scratch. It's quite hard to make a coding standard that formats any possible input to what it's supposed to look like in CS - when to wrap, how to wrap, when not to wrap, skip some parts, etc.

If rector were to limit it's changes to the actual changed lines, it would make it possible to review and fix the CS even manually. But when result is [whole codebase] or +100k/-100k lines it's not feasible as CS is not able to return all the "unchanged" lines to their previous state :( And we can't let +/-100k PR through without review. In the current situation it would actually be easier to do the changes manually using search/replace then doing it with rector :(

**Comment by TomasVotruba** [comment]
> Not every aspect of how to code should look like is part of the coding standard.

It should, otherwise you're wasting your time on robot work.



Yes, that's limit of technology - AST vs. token

Rector is tool that saves you work, coding standard is a tool that makes your code nicer (after Rector, yourself, code-review).

**Comment by tomasfejfar** [comment]
>> Not every aspect of how to code should look like is part of the coding standard.
> It should, otherwise you're wasting your time on robot work.

I don't disagree on that. 

It's just that we have to deliver features. We gradually build up what we agree on and what we check (https://packagist.org/packages/keboola/coding-standard). The rest is either not important (e.g. can be either way) or there is no check for it and there are more pressing issues then to write a sniffer for it. 

Getting to 100% "coverage" of CS wouldn't bring any value, except that we could easily use Rector.

**Comment by TomasVotruba** [comment]
> Getting to 100% "coverage" of CS wouldn't bring any value, except that we could easily use Rector.

Oh.
How do you use coding standard tools?

I just run it and commit it. It's no brainier taking less than 5 minutes while running first on huge project

**Comment by tomasfejfar** [comment]
I use it the same way as you do. By coverage I meant "covering all the possible cases that are now present in the decided, non-automated coding standard". 

Just running a ready-made CS and reformating everything only works if you are benevolent dictator that forces it on the rest of the team. If the team has been developing the project for the last 10 years, you can't simply say "we're using [this very strict](https://github.com/consistence/coding-standard) coding standards from this day on. It's either my way or highway". No, you need to take into account the way things have been for the last years and build upon that. And building a CS based on the actual state of the codebase is no small feat.

**Comment by TomasVotruba** [comment]
I think I use coding standards for automation of work, not adding it. People should not be bothered by that. That would not make sense.

Any way, I never had any troubles with Rector generated code that coding standard could not handle. I use it here for last 2 years and you can we how code looks.
