### ISSUE TITLE
[MultipleClassFileToPsr4ClassesRector] Original file is deleted and it should not be if it contains class matching filename

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1467]
The original file is being deleted completely, instead of just moving away duplicated classes.

I will investigate further and create failing test, i wonder if tests are passing now :-) 

Could be related to #1440 or #1360 ?

<img width="1244" alt="Screenshot 2019-05-24 11 21 37" src="https://user-images.githubusercontent.com/3995003/58317519-34b26e80-7e16-11e9-977b-e833732fe134.png">

**Comment by JanMikes** [comment]
Failing tests provided

**Comment by TomasVotruba** [comment]
Probably to https://github.com/rectorphp/rector/pull/1464
