### ISSUE TITLE
Is it possible to loosen required version of PHPStan

### ISSUE THREAD

**Issue by holtkamp** [rectorphp/rector#1490]
Currently Rector requires PHPStan [`0.11.6`](https://github.com/rectorphp/rector/blob/1b6c3134fa3163057766a1e161811a25b09c52b7/composer.json#L22), while PHPStan [`0.11.7`](https://github.com/phpstan/phpstan/releases/tag/0.11.7) is also available. 

Would it be possible to loosen the requirement for PHPStan a bit to also allow `0.11.7`? Or is the current master branch incompatible with PHPStan `0.11.17`?

**Comment by TomasVotruba** [comment]
As PHPStan makes bc breaks, it crashed Rector in the past, so using multiple version is not safe now.

Upgrading to `0.11.17` is better way. Care for PR?

**Comment by holtkamp** [comment]
ok, will have a look, my first observation is that the current master branch has 2 failed PHPUnit tests:

```
1) Rector\RemovingStatic\Tests\Rector\Class_\PassFactoryToEntityRector\PassFactoryToEntityRectorTest::test
Failed asserting that file "/tmp/rector_temp_tests/AnotherClassFactory.php" exists.

/Users/mennoholtkamp/workspace/rector/packages/RemovingStatic/tests/Rector/Class_/PassFactoryToEntityRector/PassFactoryToEntityRectorTest.php:20

2) Rector\RemovingStatic\Tests\Rector\Class_\PassFactoryToEntityRector\PassFactoryToEntityRectorTest::testMultipleArguments
Failed asserting that file "/tmp/rector_temp_tests/AnotherClassWithMoreArgumentsFactory.php" exists.
```

**Comment by holtkamp** [comment]
Can you tag a recent version of the Simplify packages to allow `nette/utils 3.0` to be used?

The latest tagged version `5.4.16` only allows `nette/utils 2.5`)
https://github.com/Symplify/Symplify/blob/v5.4.16/composer.json#L21


Apparently the new PHPStan requires `nette/schema ^1.0`, which requires `nette/utils ^3.0.1`
```
Problem 1
    - symplify/phpstan-extensions v5.4.16 requires nette/utils ^2.5 -> satisfiable by nette/utils[v2.5.3, v2.5.0, v2.5.1, v2.5.2].
    - symplify/phpstan-extensions v5.4.16 requires nette/utils ^2.5 -> satisfiable by nette/utils[v2.5.3, v2.5.0, v2.5.1, v2.5.2].
    - Can only install one of: nette/utils[v3.0.1, v2.5.0].
    - Can only install one of: nette/utils[v3.0.1, v2.5.1].
    - Can only install one of: nette/utils[v3.0.1, v2.5.2].
    - Can only install one of: nette/utils[v3.0.1, v2.5.3].
    - Can only install one of: nette/utils[v3.0.1, v2.5.3].
    - nette/schema v1.0.0 requires nette/utils ^3.0.1 -> satisfiable by nette/utils[v3.0.1].
    - phpstan/phpstan 0.11.7 requires nette/schema ^1.0 -> satisfiable by nette/schema[v1.0.0].
    - Installation request for phpstan/phpstan 0.11.7 -> satisfiable by phpstan/phpstan[0.11.7].
    - Installation request for symplify/phpstan-extensions ^5.4.16 -> satisfiable by symplify/phpstan-extensions[v5.4.16].
```

**Comment by TomasVotruba** [comment]
Just FYI, Symplify was tagged 2 days ago
