### ISSUE TITLE
"static" variable in a method causes an error in PHPStormVarAnnotationRector

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1494]
This simple method causes an ERROR:

```php
/**
     * Validates the param checking if it is accepted in one of the allowed sections.
     *
     * This is useful to inform the developer that were passed a parameter that is not supported at all.
     *
     * @param string $param
     */
    private function validateParam(string $param)
    {
        static $aggregatedParams = null;

        if (null === $aggregatedParams) {
            $aggregatedParams = array_merge(self::CONFIG_ACCESS, self::CONFIG_KIND, self::CONFIG_SETTINGS);
        }

        if (false === array_key_exists($param, $aggregatedParams)) {
            throw new \InvalidArgumentException(sprintf(
                'The parameter "%s" you passed is not supported in any section of a RemoteConfig. Allowed parameters in each section are: Kind => %s; Access => %s; Settings => %s.',
                $param,
                implode(', ', self::CONFIG_KIND),
                implode(', ', self::CONFIG_ACCESS),
                implode(', ', self::CONFIG_SETTINGS)
            ));
        }
    }
```

The error is this:

> [ERROR] Could not process                                                                                              
>         "/Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Bundles/bundle-my/src/Service/MyClass.php" file by "Rector\PHPStan\Rector\Assign\PHPStormVarAnnotationRector", due to:                                
>         "".

The error is caused by the use of the `static` keyword: if I remove it, the error disappears.

May be related to https://github.com/rectorphp/rector/issues/1407

**STEPS TO REPRODUCE**

I've tried to add a test case in `packages/PHPStan/test/Rector/Assign/PHPStormVarAnnotationRector/Fixture/fixture5.php.inc` with this content:

```php
<?php

function aFunctionWithStatisVariable() {
    static $variable = null;
}

?>
    -----
<?php

function aFunctionWithStatisVariable() {
    static $variable = null;
}

?>
```

The test fails with this message:

```
1) Rector\PHPStan\Tests\Rector\Assign\PHPStormVarAnnotationRector\PHPStormVarAnnotationRectorTest::test
Caused by /Users/Aerendir/Documents/JooServer/_ProjectsIContributeTo/rector/packages/PHPStan/tests/Rector/Assign/PHPStormVarAnnotationRector/Fixture/fixture5.php.inc
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 }\n
 \n
 ?>\n
-'
+    '
```

This not seem what I'm trying to reproduce.

Another way I found to reproduce the issue is by creating a simple `php` file with this function inside:

```php
<?php

function aFunctionWithStatisVariable() {
    static $variable = null;
}
```

This file will produce the error I get if I use the `static` keyword in a method.

**Comment by TomasVotruba** [comment]
Could you add failing test case? It was almost right, just few extra spaces:

```diff
-    -----
+-----
```

**Comment by Aerendir** [comment]
I've just tried: the test doesn't fail, but passes -.-'

So, the problem is in my code, but I don't know how to reproduce it using a failing test case...

Now I'm just upgraded to Rector 5.0: I'll inform you if it continue to fail...

**Comment by TomasVotruba** [comment]
How did you install Rector? There might be autoloading issue

**Comment by Aerendir** [comment]
@TomasVotruba I don't think: I install it via composer, it should autoload automatically...

In the meantime I'm trying version 5.0: there are some bugs I'm investigating...

**Comment by Aerendir** [comment]
This seems to be solved in the version 5, but now the problem is that the variable is redeclared as non static immediately before the static one.

I'll open another issue while closing this.
