### ISSUE TITLE
Feature Request: Symfony Rector to make commands lazy

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#1497]
See: https://symfony.com/doc/current/console/commands_as_services.html

**Comment by TomasVotruba** [comment]
What exactly that means for the class?

- remove `$this->setName(X)`
- add static property `$defalutName = X`

**Comment by stloyd** [comment]
@TomasVotruba Yes that would be the easiest approach.

So:
- look for `setName('command:doing:something')` call or for `parent::__construct('command:doing:something');` call (best on all files with name: `*Command.php` or something like that, eventually in given folders :) ),
- extract that `command:doing:something`,
- put `protected static $defaultName = 'command:doing:something';` back into class,
- remove calls to `setName()` if found,
- remove argument from `__construct` call on parent: `parent::__construct();`

**Comment by TomasVotruba** [comment]
Nice list, thanks :)

Would you like to learn how to do it?

**Comment by stloyd** [comment]
Following code in repository & example I was able to do step 1 & 5 but rest was black magic for me & I'm not sure I will have enough time for it.

But company for which I work for, may consider sponsoring this feature :)

**Comment by TomasVotruba** [comment]
> But company for which I work for, may consider sponsoring this feature :)

That would be amazing. There 2 ways to sponsor - one time or Patreon:
https://github.com/rectorphp/rector/blob/master/README.md#sponsors


I think I could add sponsoring company to the `@sponsor`annotation to the class.

I'll prepare prototype today.

**Comment by bendavies** [comment]
awesome!

**Comment by stloyd** [comment]
@TomasVotruba Check you email 😄
