### ISSUE TITLE
Unknown Rector doesn't "announce" itself

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1498]
There is a Rector that changes my code this way:

```console
    ...
    ----------- end diff -----------

5) src/Exception/BadMethodCallException.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -19,7 +19,7 @@
 /**
  * Thrown if a method is called in a non correct way.
  *
- * @since   1.3
+ * @since 1.3
  */
 class BadMethodCallException extends \BadMethodCallException implements RemotesException
 {
    ----------- end diff -----------

6) src/Exception/InvalidArgumentException.php

    ---------- begin diff ----------
    ...
```

As you can see, it correctly change the code, but then Rector doesn't tell me which rector is responsible for this change.

**Comment by TomasVotruba** [comment]
That's because it's not caused by Rector rule, but by service responsible for docblocks. We use phpdoc-parser here that doesn't know about each space.

If it causes error, it might be worth covering the edge case, but here I don't see reason to not accept this change

**Comment by Aerendir** [comment]
Yes, in fact I accepted it: I simply thought it was Rector that missed something, instead it isn't. So, it's all ok :)
