### ISSUE TITLE
[SOLID] Privatize all the methods and properties

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#151]
Rule: **use the least privacy possible** - e.g. when methods it not use in the outside, just make it private

## Related Sources

- Exakat https://www.exakat.io/make-everything-private-php-classes/ 
    - constant over property, that doesn't change
    - private constant/property/method if not used

## Created Rectors

- **privatize local-only method**: https://github.com/rectorphp/rector/pull/3084

- **privatize local-only property**: https://github.com/rectorphp/rector/pull/3100

- **privatize local-only constant**: https://github.com/rectorphp/rector/pull/1304

- **privatize local getter to local property**: https://github.com/rectorphp/rector/pull/3093

**Comment by carusogabriel** [comment]
Something like [PHP-CS-Fixer `protected_to_private` rule](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/src/Fixer/ClassNotation/ProtectedToPrivateFixer.php)?

**Comment by TomasVotruba** [comment]
Yea, but much more comlex

- aware of context of whole application
- knowing all the public calls of it's namespace

But when I think about this, it's already 90% implemented in here: https://github.com/Symplify/CodingStandard#possible-unused-public-method

**Comment by mfn** [comment]
> since Rector doesn't have such level of static analysis.

Hmm, too bad :-)

What would be "required"? Granted, I'm not familiar with rector.

I'm looking for a way to "safely" migrate `protected` to `private` (properties and methods). Safe as in:
- is not used in a parent/interface
- is not overridden/used in a derived class

**Comment by mfn** [comment]
> Do you have some minimal samples to describe these 2 cases?

Tried to come up with a bunch variations. The first once covers the only example which the protected method and property are convertible:

```php
<?php declare(strict_types = 1);

namespace Example;

// Refactorable

class RefactorableExampleA
{
    public $propertyPublicNotConverted;
    protected $propertyProtectedConverted;
    private $propertyPrivateNotConverted;

    public function methodPublicNotConverted(): void
    {
    }

    protected function methodProtectedConverted(): void {
        
    }

    private function methodPrivateNotConverted(): void
    {
    }
}

// Not refactorable due to abstract

abstract class NotRefactorableExampleAbstractForB
{
    public $propertyPublicNotConverted;
    protected $propertyProtectedNotConverted;
    private $propertyPrivateNotConverted;

    public function methodPublicNotConverted(): void
    {
    }

    abstract protected function methodProtectedNotConverted(): void;

    private function methodPrivateNotConverted(): void
    {
    }
}

class NotRefactorableExampleB extends NotRefactorableExampleAbstractForB
{
    public $propertyPublicNotConverted;
    protected $propertyProtectedNotConverted;
    private $propertyPrivateNotConverted;

    public function methodPublicNotConverted(): void
    {
    }

    protected function methodProtectedNotConverted(): void
    {
    }

    private function methodPrivateNotConverted(): void
    {
    }
}

// Not refactorable due to parent

class NotRefactorableExampleAbstractForC
{
    public $propertyPublicNotConverted;
    protected $propertyProtectedNotConverted;
    private $propertyPrivateNotConverted;

    public function methodPublicNotConverted(): void
    {
    }

    protected function methodProtectedNotConverted(): void
    {
    }

    private function methodPrivateNotConverted(): void
    {
    }
}

class NotRefactorableExampleC extends NotRefactorableExampleAbstractForC
{
    public $propertyPublicNotConverted;
    protected $propertyProtectedNotConverted;
    private $propertyPrivateNotConverted;

    public function methodPublicNotConverted(): void
    {
    }

    protected function methodProtectedNotConverted(): void
    {
    }

    private function methodPrivateNotConverted(): void
    {
    }
}

// Not refactorable due to grandparent

class NotRefactorableExampleGrandParentForD
{
    public $propertyPublicNotConverted;
    protected $propertyProtectedNotConverted;
    private $propertyPrivateNotConverted;

    public function methodPublicNotConverted(): void
    {
    }

    protected function methodProtectedNotConverted(): void
    {
    }

    private function methodPrivateNotConverted(): void
    {
    }
}

class NotRefactorableExampleParentForD extends NotRefactorableExampleGrandParentForD
{
    
}

class NotRefactorableExampleD extends NotRefactorableExampleParentForD
{
    public $propertyPublicNotConverted;
    protected $propertyProtectedNotConverted;
    private $propertyPrivateNotConverted;

    public function methodPublicNotConverted(): void
    {
    }

    protected function methodProtectedNotConverted(): void
    {
    }

    private function methodPrivateNotConverted(): void
    {
    }
}

// Not refactorable due to interface

interface NotRefactorableExampleInterfaceForE
{
    public function methodPublicNotConverted(): void;
}

class NotRefactorableExampleE implements NotRefactorableExampleInterfaceForE
{
    public $propertyPublicNotConverted;
    protected $propertyProtectedConverted;
    private $propertyPrivateNotConverted;

    public function methodPublicNotConverted(): void
    {
    }

    protected function methodProtectedConverted(): void
    {
    }

    private function methodPrivateNotConverted(): void
    {
    }
}
```

**Comment by TomasVotruba** [comment]
Looks good :+1:

**Comment by voha81** [comment]
Ни чего не понимаю

**Comment by TomasVotruba** [comment]
Moved from #1273 by @JanMikes 

```diff
-    const FILTER_TYPE_TOP = 'top';
+    public const FILTER_TYPE_TOP = 'top';
```
 
Check for usages of that constant, if it is not used outside of current object, it should be `private` instead of `public`.
 
Same is applicable for methods and properties.

**Comment by TomasVotruba** [comment]
Related https://www.exakat.io/make-everything-private-php-classes/

**Comment by gnutix** [comment]
@TomasVotruba What's the status of this ticket ? Is there more work needed, or is the current status of Rector handling all the use cases (with PrivatizeLocalClassConstantRector and such) ? If not, what would be the other Rectors to develop to close it ?

**Comment by TomasVotruba** [comment]
Property and class method rules are needed

**Comment by TomasVotruba** [comment]
I'm getting to this...

**Comment by TomasVotruba** [comment]
First result: https://github.com/rectorphp/rector/pull/3084

**Comment by TomasVotruba** [comment]
Closing as resolved

**Comment by mfn** [comment]
I tried to run it with this:
```
services:
  Rector\Privatization\Rector\ClassConst\PrivatizeLocalClassConstantRector: null
```
and via `vendor/bin/rector process --dry-run app/`

It _seems_ to work. I also tried the `PrivatizeLocalOnlyMethodRector`.

But there were so many changes to the source itself unrelated to this rector that I can't use the result.

I don't know where, but I think I read somewhere that it has to reprint the source and isn't able to keep it 1:1 as the original => guess that's the issue I'm facing 🤔

So I guess to benefit from this I need:
- a tool (ecs, etc.) to uniform the source
- apply rector
- run above tool again

(I'm currently using styleci but the preset is simply a very different one or simply don't complete each other)

But I noticed it does more, I saw lots FQCN where none were before…

**Comment by TomasVotruba** [comment]
Coding standard is a must have. 
See https://github.com/rectorphp/rector/blob/master/README.md#how-to-apply-coding-standards

**Comment by mfn** [comment]
> is a must have

Thought so, but FTR, the readme does not really express that: "aren't well-suited" and "it's better to" !== "must have" 😄 You might want to clarify that in the text.

But we're good here, once I've that requirement fixed I can give it a try, thanks for your work here 👍

**Comment by marhub** [comment]
What happened to those rectors? They seem to be removed, but I can't find anything in changelog etc.
