### ISSUE TITLE
Consider widen Composer's constraints for PHPStan

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1515]
Currently PHPStan is constrained at version `0.11.6` but the latest patch version is `0.11.8`.

This causes me to not be able to update to the latest patched version.

Is it possible to use a constraint like `phpstan:~0.11.6`? Or may this cause a BC that may require more deep refactorings in Rector (so, too much work for the moment and not as easy as changing the version constraint).

For reference: [Tilde version range](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-)

**Comment by TomasVotruba** [comment]
In past (around 2-5 months ago) it caused BC break issues, PHPStan was change a lot. But maybe now it's more stable.

So we can give it a try, Travis is already testing the lowest deps: https://github.com/rectorphp/rector/blob/a69d08bac5c5ee5b6ed12b7dd8d5950f4aff42bc/.travis.yml#L9

Try PR and let's see if tests pass

**Comment by Aerendir** [comment]
Ok, I'll do it ASAP... Currently I'm applying Rector to an existing app...

**Comment by TomasVotruba** [comment]
Closing as answered, feel free to send PR when ready
