### ISSUE TITLE
RenameClassRector wrongly aligns multiline comments

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1522]
Rector v0.5.3

```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -218,8 +218,7 @@

     /**
      * @param string      $orderSrcId
-     * @param string|null $channelId  Also if we do the check in the self::execute method,
-     *                                allow for null to make PHPStan pass
+     * @param string|null $channelId  Also if we do the check in the self::execute method,                                allow for null to make PHPStan pass
      * @param bool        $force
      * @param bool        $debug
      *
@@ -254,8 +253,7 @@
     }

     /**
-     * @param string|null $channelId Also if we do the check in the self::execute method,
-     *                               allow for null to make PHPStan pass
+     * @param string|null $channelId Also if we do the check in the self::execute method,                               allow for null to make PHPStan pass
      * @param bool        $force
      * @param bool        $debug
      *
    ----------- end diff -----------

Applied rectors:

 * Rector\Rector\Class_\RenameClassRector
```

UPDATE

I'm trying to reproduce the issue in a failing test case but I'm not able to do so.

Maybe the change is done in other places by other rectors... I don't know...

Also using the same exact function in the failing test case, copied-and-pasted from my class, the tests still pass.

Any ideas?

**Comment by TomasVotruba** [comment]
Hi, I came across this and tried to fix it in:
https://github.com/rectorphp/rector/commit/fca3bf38cafc40eca017aefba15b7663eb9fa9c9
There is also test case in *.txt file, just add your docblock to new file there.

It's merged in Rector 0.5.3, but I might miss some cases

**Comment by Aerendir** [comment]
I'm already using `v0.5.3`: the diff I reported is from this version...

Anyway I cannot see the file `doc14.txt` in my `vendor`, in the app, nor in my fork (also after having updated it).

But I see it on GitHub at the commit you linked: this is a bit strange, isn't it?

**Comment by Aerendir** [comment]
I've added a test as `multiline3.txt` with this content:

```
/**
 * @param string      $param1
 * @param string|null $param2 This is a simple multiline comment.
 *                            It should remain as is,
 *                            without any modification.
 */
```

The test pass: I'm not able to reproduce the issue: any suggestions?

**Comment by TomasVotruba** [comment]
I'll try it locally. Not sure if today, conference

**Comment by Aerendir** [comment]
Does it fails on your local system? On mine it didn't!

**Comment by TomasVotruba** [comment]
Yes.
Maybe you had to update dependencies with composer

**Comment by Aerendir** [comment]
@TomasVotruba Yes, I had to update them 😓

**Comment by TomasVotruba** [comment]
I got burnt so much on this, that I delete vendor and `composer.lock` everytime I test something. 

It's new "Have you tried to turn it off and on again?" :D

**Comment by Aerendir** [comment]
Ah ah ah ah ah, so stupid but so true! 😂😂😂
