### ISSUE TITLE
[phpspec-to-phpunit] support calls to "shouldHaveBeenCalled"

### ISSUE THREAD

**Issue by yakobe** [rectorphp/rector#1526]
At the moment it is not possible to convert files with `shouldHaveBeenCalled`. For example
```php
class ExampleSpec extends ObjectBehavior
{
    public function let(ObjectManager $objectManager): void {
        $this->beConstructedWith($objectManager);
    }

    public function it_runs_a_job(ObjectManager $objectManager): void {
        $this->run();
        $objectManager->flush()->shouldHaveBeenCalled();
    }
}
```

Is this something that should be tackled? If so, how? And how can I help 🙂

**Comment by yakobe** [comment]
PHPUnit has [build in support for prophecy](https://phpunit.readthedocs.io/en/8.1/test-doubles.html#prophecy). What are your feelings about using it? Maybe it would be easier to solve things like `shouldHaveBeenCalled` than trying to convert to a standard `Mock`?

**Comment by TomasVotruba** [comment]
What's the expected change in code? The diff would be the best

**Comment by yakobe** [comment]
I guess it depends on whether the built-in support for prophecy should be used, since that makes it easier to use spies. Then the change would be something like:

```php
// packages/PhpSpecToPHPUnit/tests/Rector/Class_/PhpSpecToPHPUnitRector/Fixture/spies.php.inc

<?php

namespace spec\Rector\PhpSpecToPHPUnit\Tests\Rector\MethodCall\PhpSpecToPHPUnitRector\Fixture;

use Rector\PhpSpecToPHPUnit\Tests\Rector\Class_\PhpSpecToPHPUnitRector\Source\DummyObjectBehavior;
use Doctrine\Common\Persistence\ObjectManager;

class ExampleSpec extends DummyObjectBehavior
{
    public function let(ObjectManager $objectManager): void {
        $this->beConstructedWith($objectManager);
    }

    public function it_runs_a_job(ObjectManager $objectManager): void {
        $this->run();
        $objectManager->flush()->shouldHaveBeenCalled();
    }
}

?>
-----
<?php

namespace Tests\Rector\PhpSpecToPHPUnit\Tests\Rector\MethodCall\PhpSpecToPHPUnitRector\Fixture;

use Rector\PhpSpecToPHPUnit\Tests\Rector\Class_\PhpSpecToPHPUnitRector\Source\DummyObjectBehavior;
use Doctrine\Common\Persistence\ObjectManager;

class ExampleTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var \Rector\PhpSpecToPHPUnit\Tests\Rector\MethodCall\PhpSpecToPHPUnitRector\Fixture\Example\
     */
    private $example;
    /**
     * @var ObjectManager|Prophecy\Prophecy\ObjectProphecy
     */
    private $objectManager;
    protected function setUp(): void
    {
        $this->objectManager = $this->prophesize(ObjectManager::class);
        $this->example = new \Rector\PhpSpecToPHPUnit\Tests\Rector\MethodCall\PhpSpecToPHPUnitRector\Fixture\Example($this->objectManager);
    }

    public function testRunsAJob(): void
    {
        $this->example->run();
        $this->objectManager->flush()->shouldHaveBeenCalled();
    }
}

?>
```

**Comment by TomasVotruba** [comment]
I see, so it's not about 'shouldHaveBeenCalled()` method support in phpunit, but rather using prophery instead.

That would require completely new set "phpspec to prophecy", or better "phpunit to prophecy" (more flexible and useful also for PHPUnit-only users).

This set was sponsored by commercial company, since it required many changes. Same would apply for "phpunit to prophecy" set. Creating just for this one case is not worth it, compared to other issues borad PHP community needs.

But if you want this set, get in touch with me :)

**Comment by yakobe** [comment]
Not necessarily. It's possible to do it without prophecy. Prophecy is just an alternative mocking system built into phpunit that makes "spies" easier to use. You can also create spies with `createMock`... it just doesn't read so nicely. 

There are many features of phpspec that are not yet supported by this rector to provide a generic solution for people looking to migrate away from phpspec. I would like to help extend the functionality of this rector since I saw it is in the open-source domain. However, if the goal is to only meet the requirements of individual commercial customers, let me know and I will look for alternative solutions. (i mean that in the nicest and sincerest way and no offense intended 🙂).

**Comment by TomasVotruba** [comment]
> Not necessarily. It's possible to do it without prophecy. Prophecy is just an alternative mocking system built into phpunit that makes "spies" easier to use. You can also create spies with createMock... it just doesn't read so nicely.

I didn't get that from the code, it looked very confusing for me, since the `shouldHaveBeenCalled()` method didn't change at all.

> However, if the goal is to only meet the requirements of individual commercial customers, let me know and I will look for alternative solutions

That's for sets that takes 40-60 hours to create and have very limited usage. You're the first one I know about that want to perform such migration + I need to finance my life, so I could developer Rector on sustainable bases.

> (i mean that in the nicest and sincerest way and no offense intended slightly_smiling_face).

It aws not my point, but understood :) 

> There are many features of phpspec that are not yet supported by this rector to provide a generic solution for people looking to migrate away from phpspec. 

In that case, send failing test to the `PhpSpecToPHPUnitRectorTest`. With minimal code as possible that is easy to read and covers 1 feature at at time if possible.

I'll try to explain, how to make such a rule.

**Comment by yakobe** [comment]
> I need to finance my life, so I could developer Rector on sustainable bases.

I totally understand. Many of us have to do similar 😊.

Sounds good... Maybe we can get the rector more complete so it can help a few more people. I will try to knock something together so we can discuss the options.

By the way, I find rector a very interesting project. I would like to understand more to see if i can contribute more if i find time.

**Comment by TomasVotruba** [comment]
> By the way, I find rector a very interesting project. I would like to understand more to see if i can contribute more if i find time.

Let's schedule a meeting and I can help you deep dive in :)
