### ISSUE TITLE
Not wanted changed indentation with RenameClassRector

### ISSUE THREAD

**Issue by soullivaneuh** [rectorphp/rector#1532]
With the symfony40 set, I have plenty of diffs like this:

```diff
--- Original
+++ New
@@ -76,8 +76,8 @@
      *
      * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Group")
      * @ORM\JoinTable(name="fos_user_user_group",
-     *     joinColumns={@ORM\JoinColumn(referencedColumnName="id")},
-     *     inverseJoinColumns={@ORM\JoinColumn(referencedColumnName="id")}
+     * joinColumns={@ORM\JoinColumn(referencedColumnName="id")},
+     * inverseJoinColumns={@ORM\JoinColumn(referencedColumnName="id")}
      * )
      */
     protected $groups;
```

The new indent is quite wrong to me, and I don't believe "fixing" indentation is the role of rector here, am I wrong?

**Comment by soullivaneuh** [comment]
The applied rector is: `Rector\Rector\Class_\RenameClassRector`

**Comment by soullivaneuh** [comment]
Oh I didn't see it seems to be fixed in cbdb6fa8a4c4c66fe49384b71f9456520c13d5b3, sorry.

May we have a fix release then? It hurt a lot of levels actually. :+1:

**Comment by soullivaneuh** [comment]
Hmm, the issue is not fixed to me with the master branch.

**Comment by TomasVotruba** [comment]
> Hmm, the issue is not fixed to me with the master branch.

Thanks for testing! 

It's annoying bug causes by PHPStan, they've removed more info about spacing during parsing docblocks, so I have to hack around it. 

I'll look on it.

**Comment by soullivaneuh** [comment]
Causes by PHPStan? How PHPStan can interfer here? I'm just using the rector command. :thinking:

**Comment by TomasVotruba** [comment]
See the commit you've referred → PR

**Comment by soullivaneuh** [comment]
All is working on master now, thanks! :+1:

**Comment by TomasVotruba** [comment]
Thanks for confirming
