### ISSUE TITLE
RemoveUnusedAliasRector doesn't announce itself

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1535]
```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -20,7 +20,7 @@

 use App\Manager\EmailManager;
 use InvalidArgumentException;
-use SerendipityHQ\Component\ValueObjects\Email\Email as EmailValue;
+use SerendipityHQ\Component\ValueObjects\Email\Email;
 use Symfony\Component\Validator\Constraint;
 use Symfony\Component\Validator\ConstraintValidator;
    ----------- end diff -----------
```

I expect to have the name of the applied rector somewhere, but there isn't.

**Comment by TomasVotruba** [comment]
Could you move it to the other issue you've created? I expect to be the same point of failure.

Also, minimal code that causes this case would be great. I assume this might be caused by another change in the code.

**Comment by Aerendir** [comment]
Moved to https://github.com/rectorphp/rector/issues/1534

**Comment by Aerendir** [comment]
About the code, unfortunately now I'm not able to provide it anymore: yesterday I did a lot of commits and the one I thought was the right one, is actually wrong: I'm not able to reproduce the issue anymore: sorry :(

**Comment by TomasVotruba** [comment]
I see, no troubles. I think it will appear once more :)

**Comment by Aerendir** [comment]
@TomasVotruba eh eh, I think the same 😅When it will appear I will be more careful!
