### ISSUE TITLE
RemoveUnusedAliasRector should take into account namespace conflicts

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1537]
```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -31,7 +31,7 @@
-use Aerendir\Component\DigitalCertificateVerifier\Client as DcClient;
+use Aerendir\Component\DigitalCertificateVerifier\Client;
@@ -45,7 +45,7 @@
-use SHQ\Component\Whois\Client as WhoisClient;
+use SHQ\Component\Whois\Client;
@@ -77,8 +77,8 @@
      */
     public function __construct(
-        DcClient $certificateClient,
-        WhoisClient $whoisClient,
+        Client $certificateClient,
+        Client $whoisClient
     ) {
         ...
    ----------- end diff -----------
```

Here `WhoisClient` and `DcClient` are two completely different classes but Rector changes them to be both `Client` and this will cause errors.

**SUGGESTED APPROACHES**

1. Maintain the namespace part that are required to differentiate the two classes;
2. Correctly consider the aliases as in use and so don't remove them.

I prefer the second option as in the code I can better understand when I call one client over the other.

**Comment by TomasVotruba** [comment]
> Correctly consider the aliases as in use and so don't remove them.

I like this, because it preffers the programmers intention over semantics/language syntax.
