### ISSUE TITLE
symfony finder update to ^4.3

### ISSUE THREAD

**Issue by serbancatalin** [rectorphp/rector#1546]
This commit https://github.com/rectorphp/rector/commit/9665d586ce6daccef753d785c97a9054787884b4 makes use of getFilenameWithoutExtension at: https://github.com/rectorphp/rector/blob/2ab3cfd12ec97bb8520451a5f6bba834f7af39c3/src/Console/Option/LevelOptionResolver.php#L130 that was introduced in symfony/finder 4.3.0 https://github.com/symfony/finder/commit/aae6c6d2cba156e5882621fe46ebbe9fc2ecbd32

Sould symfony/finder be updated to ^4.3 ? 
Also php to 7.1.3 https://github.com/symfony/finder/commit/29a3a80599cbc4461a3251d75905ddee918cc286 ?

**Comment by TomasVotruba** [comment]
Oh, thanks for reporting, didn't realize that.

Code should work with symfony/finder 3.4 as well, so people can easily install it on older Symfony projects. So instead of bumping composer version, the `getFilenameWithoutExtension` should be changed
