### ISSUE TITLE
[Symfony] 4.0 rectors

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#156]
- https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md

**Comment by TomasVotruba** [comment]
Too broad, feel free to create per feature PR

**Comment by carusogabriel** [comment]
The same as [Laravel 4.2 for Laravel 5.0](https://laravel.com/docs/5.0/upgrade#upgrade-5.0). Maybe I'll try 5.0 to 5.1, 5.1 to 5.2 and soo on

**Comment by TomasVotruba** [comment]
Laravel is very welcomed addition, since there is 0 Rectors for it at the moment :)
