### ISSUE TITLE
psr-4 autolaod compliancy needed for rector to work?

### ISSUE THREAD

**Issue by brainbugged** [rectorphp/rector#1575]
If I am working with a legacy codebase that has no psr-4 autoloading, do you have any suggestions about how I can use rector? It starts bombing for me with missing constants and some class definitions. And it almost looked like I won't be able to use rector if it is not ps-4 compliant. Please correct me if I am wrong or guide me to bypass this issue.

I can give more examples if needed.

**Comment by JanMikes** [comment]
Hello @brainbugged i think you do not need psr-4 compatible application to use rector, you just need autoloader to autoload your classes, check out this: https://github.com/rectorphp/rector#extra-autoloading

How are you autoloading your classes now? Anyways you can always use [classmap for composer autoloading](https://getcomposer.org/doc/04-schema.md#classmap).

**Comment by brainbugged** [comment]
@JanMikes : Thank you for your quick reply. I did try extra autoloading and it was doable but still needed some code uplift before I could use it successfully.
Although, I did miss on the classmap feature. I think that might just work for me. I will confirm and revert. Thank you.

**Comment by TomasVotruba** [comment]
Indeed, classes need to be sometimes autoloaded, so they can be 100 % reliably analyzed.
