### ISSUE TITLE
[security] prevent sql injections in code

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1579]
See https://github.com/rectorphp/demo/pull/14

Live coding from https://www.phpconference.nl/

**Comment by TomasVotruba** [comment]
- https://www.acunetix.com/blog/articles/prevent-sql-injection-vulnerabilities-in-php-applications/

**Comment by spaze** [comment]
FYI, just escaping (that's probably what you do in the demo, if I'm reading the code right) might not be enough to prevent SQL Injection.

No matter if the escaping is manual, or automated using emulated prepared statements (that's what PDO does for MySQL by default), the escaper needs to know the charset. If it is escaping without knowing the charset, it might not escape properly and SQL Injection is still possible (in some charsets, in GBK, not in UTF-8 for example).

Here's a [demo](https://github.com/spaze/emulated-prepared-statements) of SQL Injection via (wrongly configured, or not configured at all) emulated prepared statements, which is really just escaping under the hood.

**Comment by TomasVotruba** [comment]
The PHP code in diff would be more helpful, so we know what change how

**Comment by spaze** [comment]
Sorry, my Rector knowledge does not suffice and adding the feature would be quite an effort which I don't have the resources for right now.

You'd need to find whether charset has been set for the SQL client (that's PHP). For the deprecated ext/mysql that would be `mysql_set_charset()` but then it depends whether it's using mysqlnd or libmysql then it could also read the proper section of the config file). Sometimes people set charsets using `SET names` etc which might set the charset properly but might not, see the demo linked in my previous comment.

If proper charset is not set, then you can add a `mysql_set_charset()` call with correct charset which might/could be automatically determined by checking the charset of the database, or rewrite `SET names` calls to `mysql_set_charset()`.

For ext/mysqli there's another way of setting the charset, in newer version of PHP it uses mysqlnd which handles charset setting differently, see above.

Then there's PDO which uses charset in the constructor, see the demo linked above. I think the best would be to let the user configure the correct charset in the config file.

This was more like a heads up that "let's add `escape()`" might not be enough to fix SQL Injection. It could in some cases, but it requires quite a bit more work to handle other cases.

**Comment by TomasVotruba** [comment]
I mean classic PHP diff, e.g

```diff
-a
+b
```

That way we can change the code, other way are not in automated refactoring scope

**Comment by TomasVotruba** [comment]
Closing for now, waits for specific project
