### ISSUE TITLE
Bug: False positive in RemoveExtraParametersRector for MockInterface andReturns (call_user_func_array)

### ISSUE THREAD

**Issue by Levivb** [rectorphp/rector#1593]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.2                               |
| Full Command   | vendor/bin/rector --config rector.yml process Tests/SomeTest.php -n | 

```yml
# rector.yml
parameters:
  php_version_features: '7.2'

services:
  Rector\Php\Rector\FuncCall\RemoveExtraParametersRector: ~
```

## Current Behaviour 

```diff
Rector v0.5.5
Config file: /my-project/rector.yml

 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) Tests/SomeTest.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -35,8 +35,7 @@

         $this->model
             ->shouldReceive('get')
-            ->once()
-            ->andReturns($collection);
+            ->once()->andReturns();

         $this->assertSame($collection, $this->repository->findMany($ids));
     }
    ----------- end diff -----------

Applied rectors:

 * Rector\Php\Rector\FuncCall\RemoveExtraParametersRector

 [OK] Rector is done! 1 changed files
```
Didn't use `--debug` since output is pretty verbose for this rule and I doubt it's of much use. Feel free to ask for the whole `--debug` output anyway though

## Minimal PHP Code Causing Issue

```php
<?php namespace Tests;

use Illuminate\Database\Eloquent\Collection as SupportCollection;
use Illuminate\Database\Eloquent\Model;
use Mockery;
use Mockery\MockInterface;
use Modules\Core\Repositories\AbstractEntityRepository;
use Modules\Core\Tests\TestCase;

abstract class SomeTest extends TestCase
{
    /** @var Model|MockInterface */
    protected $model;

    /** @var AbstractEntityRepository */
    protected $repository;

    public function testMany(): void
    {
        $ids = [23, 454];

        $collection = new SupportCollection([
            Mockery::mock(Model::class),
            Mockery::mock(Model::class),
        ]);

        $this->model
            ->shouldReceive('whereIn')
            ->once()
            ->with('id', $ids)
            ->andReturnSelf();

        $this->model
            ->shouldReceive('get')
            ->once()
            ->andReturns($collection);

        $this->assertSame($collection, $this->repository->findMany($ids));
    }
}
```

## Expected Behaviour

I wouldn't expect Rector to remove an argument which isn't all that optional

The method signature of `andReturns` is:
```php
    /**
     * Set a return value, or sequential queue of return values
     *
     * @param mixed[] ...$args
     * @return self
     */
    public function andReturns(...$args)
    {
        return call_user_func_array([$this, 'andReturn'], $args);
    }
```

Removing the `$collection` parameter from `andReturns` obviously invalidates the test.

Remarkable, swapping `andReturns` for `andReturn` in the test doesn't issue any change anymore. So I can work around the issue for now, but it does look like an oversight in the `RemoveExtraParametersRector` rule

The method signature of `andReturns` is:
```php
     /**
     * Set a return value, or sequential queue of return values
     *
     * @param mixed[] ...$args
     * @return self
     */
    public function andReturn(...$args)
    {
        $this->_returnQueue = $args;
        return $this;
    }
```

Perhaps this is caused by the oversight of one of those "stringy" functions mentioned in https://github.com/rectorphp/rector/issues/1238

**Comment by TomasVotruba** [comment]
The behavior is correct. Look what's Mockery tells about andReturns() https://github.com/mockery/mockery/blob/d0e6b4d3d8deba978e4c5fa0846562ed416325cf/library/Mockery/ExpectationInterface.php#L45

I'll try to give priority on first implementation, not interface that actually doesn't require anything.

**Comment by Levivb** [comment]
Ow, right. Didn't notice the implemented interface. Prioritising implementation over interface would also support type variance coming in php 7.4 a bit better as well

**Comment by TomasVotruba** [comment]
See #1618 

Too bad, that will break even more stuff. Interface has lost its realiability.
