### ISSUE TITLE
Bug: False positive in CompleteDynamicPropertiesRector when calling closure bound to another class in runtime

### ISSUE THREAD

**Issue by Levivb** [rectorphp/rector#1595]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.2                               |
| Full Command   | vendor/bin/rector --config rector.yml process ServiceProvider.php -n | 

```yml
# rector.yml
parameters:
  php_version_features: '7.2'

services:
  Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector: ~
```

## Current Behaviour 

```diff
Rector v0.5.5
Config file: /my-project/rector.yml

 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) Providers/ServiceProvider.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -90,6 +90,10 @@
 class ServiceProvider extends ModuleServiceProvider
 {
     /**
+     * @var
+     */
+    public $items;
+    /**
      * @return void
      */
     public function boot(): void
    ----------- end diff -----------

Applied rectors:

 * Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector
 * Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
```

The problem here is that Laravel calls these registered macro's like this:
```php
return call_user_func_array(Closure::bind(static::$macros[$method], null, static::class), $parameters);
```
See https://github.com/laravel/framework/blob/master/src/Illuminate/Support/Traits/Macroable.php#L84

This means the closure isn't called with the ServiceProvider bound to `$this`, but actually the calling class, `Collection` in this case. I don't see a viable way for rector to detect magic like this, hence ignoring such code from the rule would be one of the few if not only options.

## Minimal PHP Code Causing Issue

Our ServiceProvider registers a macro on the Collection class of Laravel:
```php
class ServiceProvider {
    /**
     * @return void
     */
    private function registerCollectionMacros(): void
    {
        Collection::macro('ksort', function (): Collection {
            // macros callbacks are bound to collection so we can safely access
            // protected Collection::items
            $list = $this->items;
            ksort($list);

            return new static($list);
        });
    }
```

## Expected Behaviour
The `$this->items` call isn't called on the class the closure is defined in but is called from another class which binds itself to the closure. As a result, `$this->item` isn't a missing property of the `ServiceProvider`

I don't really see a way to detect this kind exception. So I presume the only way to get around this is to ignore this on a case by case: https://github.com/rectorphp/rector/issues/1591

But if you know of a way to detect this code magic in some way, I'm all ears!

**Comment by TomasVotruba** [comment]
I can see 3 different snippets, that seems incomplete. It's very difficult to idenfity a pattern there.

Could you provide minimal failing code without any Laravel code, so we could reproduce the generic issue?

**Comment by Levivb** [comment]
Sure, sorry for not being all to clear

The only own code:

```php
<?php
declare(strict_types=1);

namespace Modules\Core\Providers;

use Illuminate\Support\Collection;
use Illuminate\Support\ServiceProvider;

class CoreServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        Collection::macro('ksort', function (): Collection {
            // macros callbacks are bound to collection so we can safely access
            // protected Collection::items
            $list = $this->items;
            ksort($list);

            return new static($list);
        });
    }
}
```

Running rector on that file with this actual rector.yml (not truncated for clarity):
```yml
parameters:
  php_version_features: '7.2'

services:
  Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector: ~
```

Issuing rector:
```
$ vendor/bin/rector  --config ci/config/rector.yml process Providers/CoreServiceProvider.php -n
```

Gives this output:
```bash
Rector v0.5.5
Config file: /Users/Levi/Documents/Work/repositories/modulestest/packages/core/ci/config/rector.yml

 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) Providers/CoreServiceProvider.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -8,6 +8,10 @@

 class CoreServiceProvider extends ServiceProvider
 {
+    /**
+     * @var
+     */
+    public $items;
     public function register(): void
     {
         Collection::macro('ksort', function (): Collection {
    ----------- end diff -----------

Applied rectors:

 * Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector



 [OK] Rector is done! 1 changed files
```

Classes supporting Laravel's magic macroable trait (not just `Collection`):
![Screenshot 2019-06-17 at 23 30 47](https://user-images.githubusercontent.com/2494320/59638179-f9c30280-9157-11e9-966b-604b4e11c734.png)

**Comment by TomasVotruba** [comment]
There are 3 differnt snippets, so I'm not sure I understand Laravel magic, 
but I've tried come up with a solution, that skips anything in collection registration: https://github.com/rectorphp/rector/pull/1721/files#diff-18633c804f17d7c0337d3b2f066fe63f

Check it in #1721
