### ISSUE TITLE
Bug: StringClassNameToClassConstantRector throws notice when encountering '\\' string

### ISSUE THREAD

**Issue by Levivb** [rectorphp/rector#1596]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.2                               |
| Full Command   | vendor/bin/rector --config rector.yml process SomeClass.php -n | 

```yml
# rector.yml
parameters:
  php_version_features: '7.2'

services:
  Rector\Php\Rector\String_\StringClassNameToClassConstantRector: ~
```

## Current Behaviour 

```
Rector v0.5.5
Config file: /Users/Levi/Documents/Work/repositories/rudderkernel/packages/core/ci/config/rector.yml

 2/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  66%PHP Notice:  Uninitialized string offset: 0 in /Users/Levi/Documents/Work/repositories/rudderkernel/packages/core/vendor/composer/ClassLoader.php on line 375

Notice: Uninitialized string offset: 0 in /Users/Levi/Documents/Work/repositories/rudderkernel/packages/core/vendor/composer/ClassLoader.php on line 375
 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
```

## Minimal PHP Code Causing Issue

```php
<?php namespace Modules\Core\Http\ViewComposers;

class SomeClass
{
    public function __construct()
    {
        '\\';
    }
}
```

## Expected Behaviour
Rector should not show notices when parsing this rule when encountering `\\`.
Putting this string in other contexts like variable assignment, string concatenation to variable or argument passing doesn't alter current behaviour.

String concatenation to second string literal does prevent the error:
```php
<?php namespace Modules\Core\Http\ViewComposers;

class SomeClass
{
    public function __construct()
    {
        '\\' . 'asd'; // no notice
    }
}
```

**Comment by TomasVotruba** [comment]
Thanks for perfect bug report, very easy to work with it and figure out the fix :clap:
