### ISSUE TITLE
Bug: RemoveCodeAfterReturnRector removes comment tailing return statement

### ISSUE THREAD

**Issue by Levivb** [rectorphp/rector#1597]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.2                               |
| Full Command   | vendor/bin/rector --config rector.yml process SomeClass.php -n | 

```yml
# rector.yml
parameters:
  php_version_features: '7.2'

services:
  Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector: ~
```

## Current Behaviour 

```diff
--- Original
+++ New
@@ -4,6 +4,5 @@
 {
     public function returnStuff()
     {
-        return 'something'; // this comment explains stuff
-    }
+        return 'something';}
 }
    ----------- end diff -----------
```

## Minimal PHP Code Causing Issue

```php
<?php

class SomeClass
{
    public function returnStuff()
    {
        return 'something'; // this comment explains stuff
    }
}
```

## Expected Behaviour
The `RemoveCodeAfterReturnRector` currently removes a comment tailing the return statement
Technically all comment code is dead code. It's up for debate if you'd actually want it being removed by this rule. The rule itself can be easily circumvented by placing the comment before the return statement:

```php
// this comment explains stuff
return 'something';
```

I'll leave the decision to remove the tailing comment after a return statement up to you. If it were up to me I'd allow it since it's a common way to have a small explanation at the return statement.

The actual report this is about is that the closing bracket also gets collapsed on the same line the return statement is on. At first I actually thought the `}` was completely removed. Syntactically the code is still correct, but code sniffers will complain and preventing the removal of the newline might be an easy fix?

**Comment by TomasVotruba** [comment]
Are you sure it's `RemoveDeadReturnRector`? Because that rule handles only empty `return;`

Also test case passes, see #1600

**Comment by Levivb** [comment]
Ow, sorry. My bad. Seems I copy-pasted the wrong line.
It should be: `Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector`

**Comment by TomasVotruba** [comment]
No problem. Could you send failing test for that?

Basically add before/after in single file here: https://github.com/rectorphp/rector/blob/master/packages/DeadCode/tests/Rector/FunctionLike/RemoveCodeAfterReturnRector/RemoveCodeAfterReturnRectorTest.php#L12

**Comment by Levivb** [comment]
Thank for fixing! I haven't been home a lot this week since Monday. Was planning to address it tomorrow, but you beat me to it!  👍

**Comment by TomasVotruba** [comment]
I'm trying to keep fit :)

Look forward to your next reprort
