### ISSUE TITLE
[Symfony] Request is injected as method argument in an event method

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1607]
A collegue of mine quickly tested rector on a code base. Among the result, he showed me a change that was surprising. Unfortunately, he reverted before I could collect the code. But here's the pseudo-code :  

```diff
class MyAwesomeClass implement SomeEventThingyInterface
{
-    public function onKernelRequest(SomeEventClass $event)
+    public function onKernelRequest(SomeEventClass $event, Request $request)
    {
-        $request = $event->getRequest();
+        $request = $request;
        // use $request
    }
}
```

I don't have much more time right now to investigate, but maybe someone will.

**Comment by TomasVotruba** [comment]
Intresting, do you know what set was used? That would really help

**Comment by stloyd** [comment]
@TomasVotruba I can confirm that running:
```
# rector.yaml
services:
    Rector\Symfony\Rector\HttpKernel\GetRequestRector: ~
```
Does such strange change:
```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -29,9 +29,9 @@
         $this->logger = $logger;
     }

-    public function onKernelException(GetResponseForExceptionEvent $event)
+    public function onKernelException(GetResponseForExceptionEvent $event, \Symfony\Component\HttpFoundation\Request $request)
     {
-        $request = $event->getRequest();
+        $request = $request;
         if (!$request) {
             return;
         }
```
I guess you need to validate that class name is: `*Controller.php`.

**Comment by TomasVotruba** [comment]
> I guess you need to validate that class name is: *Controller.php & best to check that ->getRequest() is being run on $this.

Great idea! Do you want to try to fix it or should I handle it?

**Comment by JanMikes** [comment]
> I guess you need to validate that class name is: *Controller.php & best to check that ->getRequest() is being run on $this.

For some stupid idea (legacy reasons, that has to be fixed in future) our controllers are named with `*Presenter` suffix 😄

**Comment by TomasVotruba** [comment]
So basically refactor if:

- `$this` is type of `Symfony\Bundle\FrameworkBundle\Controller\Controller`, `Symfony\Bundle\FrameworkBundle\ControllerControllerTrait`
- suffix `"Controller"`
- suffix `"Presenter"`

And skip every else, right?

**Comment by stloyd** [comment]
I would say that suffix should be default to: `*Controller` but with option to replace it, so it will be more usable for ppl with not common controller names.

**Comment by TomasVotruba** [comment]
- option to change via parameters :+1: 

Why would you exclude `*Presenter`? That's common synonym for Controller
