### ISSUE TITLE
Configured config modifying code not applicable

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#1608]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | `PHP 7.2.16`                               |
| Full Command   | `bin/rector process ../../path/to/src/BindHQ/Bundle/AbacusBundle --autoload-file ../../path/to/vendor/autoload.php --level symfony42`  | 

## Current Behaviour 

Rector is making modifications that are not in the `symfony42` level e.g:

```diff
18) src/file.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -71,7 +71,7 @@
             $client->submit(
                 $newCrawler
                     ->filter('.form-new-nsf-invoice')
-                    ->form([])
+                    ->form([]), []
             );
         });

@@ -120,7 +120,7 @@
             $client->submit(
                 $newCrawler
                     ->filter('.form-new-nsf-invoice')
-                    ->form([])
+                    ->form([]), []
             );
         });
    ----------- end diff -----------

Applied rectors:

 * Rector\Rector\Argument\ArgumentAdderRector
 * Rector\Rector\Argument\ArgumentDefaultValueReplacerRector
 * Rector\Rector\Argument\ArgumentRemoverRector

27) src/file.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -7,7 +7,7 @@
 trait HasTransactionGroupTrait
 {
     /**
-     * @var ?string
+     * @var string|null
      */
     private $transactionGroupExternalId;
    ----------- end diff -----------

Applied rectors:

 * Rector\Rector\Class_\RenameClassRector
```

## Expected Behaviour

Only symfony42 rectors are applied

**Comment by TomasVotruba** [comment]
What is reported responsible rule?

**Comment by bendavies** [comment]
It's in my description isn't it? `Applied rectors:`

**Comment by TomasVotruba** [comment]
I see 3 rules there. Are they all 3 needed? What is their minimal configuration to reproduce?

**Comment by bendavies** [comment]
I'll try get a reproducer for you. But do you agree that the diff above is not expected?

**Comment by bendavies** [comment]
@TomasVotruba https://asciinema.org/a/gSVdmSAb1f8JWmaNQx2OwNC9V

**Comment by TomasVotruba** [comment]
> I'll try get a reproducer for you. But do you agree that the diff above is not expected?

The best is failing test case.

Thanks for the ascii, will check :+1:

**Comment by TomasVotruba** [comment]
@bendavies The first issue 

![image](https://user-images.githubusercontent.com/924196/59556720-b3d73480-8fc7-11e9-8de3-1d42620a853a.png)

is classic code collision, when you have 2 classes with same name. The only solution is [prefixed Rector](https://github.com/rectorphp/rector/issues?q=is%3Aopen+label%3Awaits-on-prefixed+sort%3Aupdated-desc) or install Rector as a dependency to the project

**Comment by TomasVotruba** [comment]
As for:

```diff
@@ -120,7 +120,7 @@
             $client->submit(
                 $newCrawler
                     ->filter('.form-new-nsf-invoice')
-                    ->form([])
+                    ->form([]), []
             );
         });
```

It's right in the set :check
https://github.com/rectorphp/rector/blob/600e6cbd9d29272c78feab39706af4c4aa60f9ec/config/set/symfony/symfony42.yaml#L17-L24

Check the links

**Comment by TomasVotruba** [comment]
As for:

```diff
     /**
-     * @var ?string
+     * @var string|null
      */
```

we use PHPStan doc parser here, that prints it correct way. Although it's side effect, I see it as a correct one. `?string` is not valid intersection annotation.

**Comment by bendavies** [comment]
thanks @TomasVotruba !

**Comment by bendavies** [comment]
> As for:
> 
> ```diff
> @@ -120,7 +120,7 @@
>              $client->submit(
>                  $newCrawler
>                      ->filter('.form-new-nsf-invoice')
> -                    ->form([])
> +                    ->form([]), []
>              );
>          });
> ```
> 
> It's right in the set ✔️
> https://github.com/rectorphp/rector/blob/600e6cbd9d29272c78feab39706af4c4aa60f9ec/config/set/symfony/symfony42.yaml#L17-L24
> 
> Check the links

@TomasVotruba 

I still don't see why this is correct.

This deprecation warning is for inheriting classes.
https://github.com/symfony/symfony/commit/f75fffa9974d98fb40f0e7365e99ec35e01e3509



```diff
-        $client->submit($form);
+        $client->submit($form, []);
```
This change is not needed.
The default value for the 2nd parameter is already `[]`

https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/BrowserKit/Client.php#L316
