### ISSUE TITLE
[Symfony] Guzzle to HttpClient

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1614]
Ref:

- https://symfony.com/blog/new-in-symfony-4-3-httpclient-component
- https://medium.com/@andreiabohner/symfony-4-3-httpclient-cheat-sheet-fbf695df12eb

**Comment by stloyd** [comment]
Replacing automatically Guzzle maybe hard/impossible, mostly cause it allows creating middlewares etc. so it's really split along the codebase.

Personally I would probably vote for replacing `file_get_contents('http(s)://')` etc. calls to that new client.

**Comment by TomasVotruba** [comment]
> Replacing automatically Guzzle may be hard/impossible, mostly cause it allows creating middlewares etc. so it's really split along the codebase.

That's a challange then :)

> Personally I would probably vote for replacing file_get_contents('http(s)://') etc. calls to that new client.

I'm not sure what you mean. Could you share a diff?

**Comment by stloyd** [comment]
I.e. from:
```php
$data = file_get_contents('https://api.github.com/repos/symfony/symfony-docs');
```
Into:
```php
$response = (HttpClient::create())
    ->request('GET', 'https://api.github.com/repos/symfony/symfony-docs');

$data = $response->getContent();
```

**Comment by stloyd** [comment]
Or i.e. `POST`:
```php
        $result = file_get_contents('https://github.com/', false, stream_context_create(['http' => [
            'method' => 'POST',
            'header' => 'Content-type: application/x-www-form-urlencoded',
            'content' => $postData,
        ]]));
```
Into:
```php
        $result = $this->httpClient->request('POST', 'https://github.com/', [
            'body' => $postData,
        ])->getContent();
```

**Comment by TomasVotruba** [comment]
I see. So plain PHP to Symfony/HttpClient?

How would the second code would look like with creation of the client?

**Comment by stloyd** [comment]
Can be exactly same as in first :)

**Comment by TomasVotruba** [comment]
Does it make sense to create new object per call thought? I don't know how you use it, so I need more examples from you to understand it better

**Comment by stloyd** [comment]
TBH. I dont really think I have such case currently in code (meaning `file_get_*` used via HTTP), so those above are more abstraction examples ;)

But for Guzzle, we use it, a lot, but I'm not sure how to help you with example to do some replacement ;)

**Comment by TomasVotruba** [comment]
Oh, I thought you need it :)
In that case I'm alright

**Comment by TomasVotruba** [comment]
Closing as too broad, needs specific project
