### ISSUE TITLE
[PHP 7.0] Unexpected function replace

### ISSUE THREAD

**Issue by abdala** [rectorphp/rector#1622]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | 7.2.15                               |
| Full Command   | rector process src --level php70  | 

## Current Behaviour 

It is replacing all ocurrences of `mktime()` to `time()` function

```diff
- $date = mktime(1, 2, 3);
+ $date = time(1, 2, 3);
```

## Expected Behaviour

It should replace only when there is no parameters set to `mktime()`

```diff
$date = mktime(1, 2, 3);
$date = mktime(1, 2, 3);

- $now = mktime();
+ $now = time();
```

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1:
