### ISSUE TITLE
[DeadCode] RemoveUnusedPrivatePropertyRector: removes properties/methods used in anonymous functions

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1630]
I've added the `dead-code` level to my project and discovered two false-positives :

1)

```diff
4) src/Form/SomeFormType.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -28,11 +28,6 @@
     private $router;

     /**
-     * @var ContentFinder
-     */
-    private $contentFinder;
-
-    /**
      * @var RequestStack
      */
     private $requestStack;
@@ -43,7 +38,6 @@
     public function __construct(RouterInterface $router, ContentFinder $contentFinder, RequestStack $requestStack)
     {
         $this->router = $router;
-        $this->contentFinder = $contentFinder;
         $this->requestStack = $requestStack;
     }
    ----------- end diff -----------

Applied rectors:

 * Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
```

The issue lies in the fact that `$this->contentFinder` is indeed used : 

```php
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // ...
        $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) use ($attr): void {
            $content = $this->contentFinder->someMethod((int) ($event->getData()['content']));
            $this->somePrivateMethod();
            // ...
        });
    }

    private function somePrivateMethod(): void {
        // ...
    }
```

2) A private method in the same class that would be called in the anonymous function above only (`somePrivateMethod` in the code example) would be removed too by the Rector.

**Comment by TomasVotruba** [comment]
I've added test case with your snippet: #1641 

And I cannot reproduce. Could you check PR and tell me, what's different in your code?

**Comment by TomasVotruba** [comment]
I cannot reproduce the issue on `master`
Add failing test case the same way as in #1641, only then I'll be able to fix it

**Comment by gnutix** [comment]
I'll try to produce a test case. From my first try, it seems to be quite complicated (a simple test doesn't turn the constants visibility, as expected, so it must be related to the complexity of our code base).

**Comment by TomasVotruba** [comment]
In the start it might be complicated and feel like "some magic",
but 99 % bugs here are related to 1-2 lines of code.
