### ISSUE TITLE
[Php73] Rector\Php\Rector\FuncCall\StringifyStrNeedlesRector: does the job twice

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1632]
Here's a strange result from rector using level "php73.yaml". I've run rector once, it found this fix (adding `(string)` before `$search->getQ()` in the `strpos` call), I applied it, and now when running Rector again it wants to do it all over again.

```diff
1) src/FileLogFinder.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -48,7 +48,7 @@
         if (!empty($search->getQ())) {
             $logs = array_filter($logs, function (FileLog $log) use ($search) {
                 $res = false;
-                if (false !== strpos($log->getText(), (string) $search->getQ())) {
+                if (false !== strpos($log->getText(), (string) (string) $search->getQ())) {
                     $res = true;
                 }
    ----------- end diff -----------

Applied rectors:

 * Rector\Php\Rector\FuncCall\StringifyStrNeedlesRector
```

**Comment by larsroettig** [comment]
I can verify this Issue I can also reproduce I try to fix it now we need this Rector for a Project Upgrade

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1:

**Comment by gnutix** [comment]
It's better (doesn't add it twice), but it still does add `(string)` to an argument even if it's of type string. Example : 

```php
# src/test.php
final class Test {
    public function getNeedle(): string {
        return 'needle';
    }
}

strpos('needle', (new Test)->getNeedle());
```

gives : 

```
1) src/test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -5,4 +5,4 @@
     }
 }

-strpos('needle', (new Test)->getNeedle());
+strpos('needle', (string) (new Test)->getNeedle());
    ----------- end diff -----------

Applied rectors:

 * Rector\Php\Rector\FuncCall\StringifyStrNeedlesRector
```

And then, PHPStorm highlights the `(string)` because it's useless, as `getNeedle` returns a `string` anyway.

Should I create a new issue ?

**Comment by TomasVotruba** [comment]
Better add a test case with this

**Comment by gnutix** [comment]
> Better add a test case with this

I'm not sure how to do that. Could you please reopen the issue so that someone (if not me later) might pick it up?

**Comment by TomasVotruba** [comment]
Adding test case is simple and it speeds up the fix, look here: https://github.com/rectorphp/rector/pull/1642/files

**Comment by gnutix** [comment]
Failing test added : https://github.com/rectorphp/rector/pull/2081

**Comment by gnutix** [comment]
Thanks! Confirm it works on our codebase. :)
