### ISSUE TITLE
[Php73] Rector\Php\Rector\FuncCall\JsonThrowOnErrorRector: adds `null` as a third parameter, `int` expected (512 by default)

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1633]
When adding the level php73, it refactors `json_decode($json, true)` to `json_decode($json, true, null, JSON_THROW_ON_ERROR)`. However, the third parameter is `int $depth` and therefore throws `TypeError: json_decode() expects parameter 3 to be int, null given`.

**Comment by TomasVotruba** [comment]
What is expected change? 

Could you use ``` diff syntax? It's easier to read

**Comment by TomasVotruba** [comment]
> What is expected change?

Oh, I see in the title `512` now. Could you put that into description next time? That's common place for that.

**Comment by TomasVotruba** [comment]
Ref https://3v4l.org/5HMVE
