### ISSUE TITLE
--with-style doesn't use easy-coding-standard.yml ?

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1635]
Am I wrong, or running Rector with the `--with-style` flag doesn't use the project's root `easy-coding-standard.yml` configuration file ? I get widely different results running Rector --with-style or Rector then ECS.

**Comment by TomasVotruba** [comment]
Yes, you're right.

It uses https://github.com/rectorphp/rector/blob/master/ecs-after-rector.yaml

What behavior would you expect? Or information?

**Comment by TomasVotruba** [comment]
Closing as a answered

**Comment by gnutix** [comment]
Well, I'm just thought that if the two tools were developed by the same person and meant to integrate with each other, they might do it "all the way" (notably by using the others' config). But maybe not; I'm not really sure what's the usage of `--with-style` then, if only to showcase what ECS can do to people discovering Rector and giving them the curiosity to try it out ?

**Comment by TomasVotruba** [comment]
It's described in README: https://github.com/rectorphp/rector#how-to-apply-coding-standards

> Rector ships with EasyCodingStandard set that covers namespaces import, 1 empty line between class elements etc.

The goal is simply to fix few basic coding standard issues, if you don't have any coding standar at all.

If you have your own config, use that.


**Maybe it would be better to not have this `--with-style` at all and let people only use their own coding standard. After all, the `--with-style` is very limited and mabye more confusing than helpful. **

What do you think?

**Comment by gnutix** [comment]
I personally agree that it's not very useful and creates confusion. I'd better have a sentence like `You might be interested in EasyCodingStandard [link], as it complements Rector to make sure your code looks as beautiful as ever.` ;)

**Comment by TomasVotruba** [comment]
I like it! Could you add it?
