### ISSUE TITLE
DX: Import previous levels' versions for Symfony/PHP/Twig/PHPUnit/etc.

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1637]
Currently, each level only contains its own fixes. So if you require `symfony34`, it won't include `symfony33` fixes.

I believe this is done to ease progressive migration (moving code from 3.2, to 3.3, to 3.4, etc) by including only the level you need. However, what happens when you use Rector more as an "code quality regression tester" ? For example, setting the level `php73` would ensure that we only use the latest and greatest of all PHP 7.x standards.

Currently, my config looks like this (same for Symfony, Twig, etc) : 

```yaml
# ...
    # PHP
    - { resource: 'vendor/rector/rector/config/level/php/php52.yaml' }
    - { resource: 'vendor/rector/rector/config/level/php/php53.yaml' }
    - { resource: 'vendor/rector/rector/config/level/php/php54.yaml' }
    - { resource: 'vendor/rector/rector/config/level/php/php55.yaml' }
    - { resource: 'vendor/rector/rector/config/level/php/php56.yaml' }
    - { resource: 'vendor/rector/rector/config/level/php/php70.yaml' }
    - { resource: 'vendor/rector/rector/config/level/php/php71.yaml' }
    - { resource: 'vendor/rector/rector/config/level/php/php72.yaml' }
    - { resource: 'vendor/rector/rector/config/level/php/php73.yaml' }
# ...
```

So that makes it quite complicated to read. Could there be a way to simplify this ? For example, having some parameters : 

```yaml
parameters:
    include_levels_up_to:
        php: 7.3
        symfony: 4.3
        phpunit: 8.0
        twig: 2.4
```

etc. Or even some `include_levels_according_to_composer: true` that would do it magically, based on composer requirements ?
What do you think ?

**Comment by TomasVotruba** [comment]
This might help
https://symfony.com/blog/new-in-symfony-3-3-import-config-files-with-glob-patterns
