### ISSUE TITLE
Fix spaces with rector

### ISSUE THREAD

**Issue by funivan** [rectorphp/rector#1638]
## Question
Can I add or remove spaces with rector?
I want to write custom fixer. Thanks.

**Comment by TomasVotruba** [comment]
Rector works with AST, that is not suitable for spacing issues.
Better use tokens.

You can read more about it here:
https://www.tomasvotruba.cz/blog/2018/10/25/why-ast-fixes-your-coding-standard-better-than-tokens/

I'd recommend my other tool Easy Coding Standard, that combined Sniffs and Fixers:

https://github.com/Symplify/EasyCodingStandard
