### ISSUE TITLE
[CLI] Return not called "rectors" for easier debug

### ISSUE THREAD

**Issue by stloyd** [rectorphp/rector#1649]
Right now when calling:
```bash
rector process --set symfonyXX
```
You can't know what _rectors_ where **not** being called.

It would be nice, when running in `-vv` or higher, to see at end/in summary, what rectors where not run, this would help too debug, if there is bug in rector or maybe too complicated file for him to parse it.

**Comment by TomasVotruba** [comment]
Hi, what's the use case?

It seems like other tools only show used rules. This would be confusing then
