### ISSUE TITLE
How to handle 'deprecated the autowiring types' ?

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#1655]
## Question
i have this deprecation but do not find which rector could fix it. Could you please tell me which? :)
I've seen nothing on https://github.com/rectorphp/rector/blob/master/config/set/symfony/symfony33.yaml

## Sources
https://symfony.com/blog/new-in-symfony-3-3-deprecated-the-autowiring-types
https://symfonycasts.com/screencast/symfony-3.3/deprecated-autowiring

**Comment by TomasVotruba** [comment]
I never used this feature, it looks like yaml.
If so Rector cannot help here.

**Comment by vasilvestre** [comment]
Alright, closed so.
