### ISSUE TITLE
How to add an autoload file?

### ISSUE THREAD

**Issue by vinioo** [rectorphp/rector#1658]
Hello! I'm trying to run rector but i'm getting the following message:
"Class x was not found while trying to    
         analyse it - autoloading is probably not configured properly.". Include
         your files in "parameters > autoload_paths".

What should i do? I tried to add a autoload file but i dont get it right. Thanks

**Comment by vinioo** [comment]
I'm running through docker

**Comment by TomasVotruba** [comment]
Hi, what happens what you try `--autoload-file` from README? 
https://github.com/rectorphp/rector#extra-autoloading

I don't use Docker, but @JanMikes might help you

**Comment by JanMikes** [comment]
Hi @vinioo what class is it please? Is it your class? Is it vendor class? Is it class that is introduced by some PHP extension?

If it is class added by PHP extension, you might want to check this https://github.com/rectorphp/rector/issues/1547

**Comment by vinioo** [comment]
Hello, thanks for the answers.
I solved the problem, just had to add my project path to autoload_paths at rector.yaml.

But, now i am getting the error message "Ambigous class". The project has a lot of duplicated classes. Is there a way to skip it? Or will i need to get just one class anyway?

**Comment by TomasVotruba** [comment]
> I solved the problem, just had to add my project path to autoload_paths at rector.yaml.

What does it mean? What does your full `rector.yaml` look like?

It's seem you're autoloading something twice

**Comment by vinioo** [comment]
rector.yaml
```
parameters:
    autoload_paths:
        - '/dados/webdesktop.git'
```

Just added the entire project

**Comment by TomasVotruba** [comment]
Ah, I never saw this usage. There should be only `vendor/autoload.php`

**Comment by vinioo** [comment]
how an autoload.php file should looks like?

**Comment by TomasVotruba** [comment]
Well, how do you autoload classes now? Composer or sth?

**Comment by TomasVotruba** [comment]
Original question resolved, closing

**Comment by afilina** [comment]
In case someone ends up here because they need Rector in a different project from the code being processed:

```
parameters:
  autoload_paths:
    - '../project_to_process/vendor/autoload.php'
```

**Comment by phazei** [comment]
This link no longer exists:
https://github.com/rectorphp/rector#extra-autoloading

But it's still given in the error

**Comment by TomasVotruba** [comment]
The README was changed to drop 50 % of clutter code and show all the options in one file:
https://github.com/rectorphp/rector#configuration
