### ISSUE TITLE
Parameter type hint rector is trying to add a non supported resource type hint

### ISSUE THREAD

**Issue by tigitz** [rectorphp/rector#1663]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | the one in docker image                               |
| Full Command   | docker run --rm -it -v $(pwd):/project rector/rector:latest process /project --config /project/rector.yaml --autoload-file /project/vendor/autoload.php -vvv  | 

## Current Behaviour 

```diff
@@ -221,7 +221,7 @@
      *
      * @return mixed A string representing the line or null if beginning of file is reached
      */
-    protected function readLineFromFile($file)
+    protected function readLineFromFile(resource $file)
```

With `Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector:`

## Minimal PHP Code Causing Issue

```
    /**
     * @param resource $file The file resource, with the pointer placed at the end of the line to read
     */
    protected function readLineFromFile($file)
    {
    }
```  

## Expected Behaviour

No fix.

Although it might be tricky as the following is valid php code

```php
class resource {}

function test(resource $test) {}

test(new resource);
```

**Comment by stloyd** [comment]
Yes, `resource` same as `mixed` are valid type-hints for phpdocs and for class names and as such they could be used, but they were (& probably never will) not implemented as _special_ language type-hints.

**Comment by tigitz** [comment]
I'm leaning on the side of "Dont try to fix resource or mixed" as it would be a more conservative approach (no runtime errors introduced like currently) and it would covers the far more popular case of devs that really wants to type a `resource` in their docs instead of a `resource class`
