### ISSUE TITLE
[Symfony 4.2] Missing parent call after update for ContainerAwareCommand

### ISSUE THREAD

**Issue by stloyd** [rectorphp/rector#1678]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.1.30                               |
| Full Command   | vendor/bin/rector process --dry-run --set symfony42  | 

## Minimal PHP Code Causing Issue

```php
<?php

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SomeCommand extends ContainerAwareCommand
{
    protected static $defaultName = 'some:command';

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $em = $this->getContainer()->get('doctrine')->getManager();
    }
}
```

## Actual Behaviour

```php
<?php

use Doctrine\Bundle\DoctrineBundle\Registry;
use Symfony\Bundle\FrameworkBundle\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SomeCommand extends \Symfony\Component\Console\Command\Command
{
    protected static $defaultName = 'some:command';

    /**
     * @var \Doctrine\Bundle\DoctrineBundle\Registry
     */
    private $registry;

    public function __construct(Registry $registry)
    {
        $this->registry = $registry;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $em = $this->registry->getManager();
    }
}
```

## Expected Behaviour

```php
<?php

use Doctrine\Bundle\DoctrineBundle\Registry;
use Symfony\Bundle\FrameworkBundle\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SomeCommand extends Command
{
    protected static $defaultName = 'some:command';

    /**
     * @var Registry
     */
    private $registry;

    public function __construct(Registry $registry)
    {
        $this->registry = $registry;

        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $em = $this->registry->getManager();
    }
}
```

As you can notice the require `parent::__construct()` call for the `Command` class is missing as well, the extended class name uses FCQN.

**Comment by TomasVotruba** [comment]
> the extended class name uses FCQN.

This is really matter of personal coding standard preferences, that you should always run after Rector. Some people prefer FQN, some short. FQN is easier to shorten.

> As you can notice the require parent::__construct() call for the Command class is missing 

That's an issue.

**Comment by stloyd** [comment]
> This is really matter of personal coding standard preferences, that you should always run after Rector. Some people prefer FQN, some short. FQN is easier to shorten.
For me kind of _issue_ here is that there is insert of both FCQN & `use` import.

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/issues/1564#issuecomment-499146022
