### ISSUE TITLE
[README] Add "big" note about why there are both FCQN in inject & imports

### ISSUE THREAD

**Issue by stloyd** [rectorphp/rector#1683]
As per comment: https://github.com/rectorphp/rector/issues/1564#issuecomment-499146022

> The best ways to solve this is using coding standard to handle your imports.
Using FQN by default is to allow them import or keep FQN - some people prefer first, some second. And it's harder to FQNize than import in coding standard rules.
>
> tl;dr; AST sucks in coding standard, and always will. It doesn't make sense to rewrite EasyCodingStandard, PHP CS Fixer or CodeSnffier. Just use it.
>
> See this comment for deeper answer: #1456 (comment)
>
> I recommend using option --with-style: https://github.com/rectorphp/rector#how-to-apply-coding-standards

This IMHO should be hardly noted in `README` file, so there is clear point why it's this way & why it will not be fixed.

**Comment by TomasVotruba** [comment]
I'm not the best person to do this, since I suffer author blindness.

Could you send PR so it's understanable for you as a tool user?
