### ISSUE TITLE
[DeadCode] Removing useless if statements

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1688]
Hey, i wave just made few changes in our code and making this change in like 60 places, wondering if we have already rector for it :-)
 
## Diff 
```diff
- /** @var ICache|null */
+ /** @var ICache */
private $cache;

- if ($this->cache) {
    $this->cache->save($x);
- }
```

PHPStan link: https://phpstan.org/r/1d1026c1-ab7c-46e4-8146-17c052eb8dae

To show how real this issue is, check this (just part of) phpstan report:
<img width="417" alt="Screenshot 2019-07-04 14 44 17" src="https://user-images.githubusercontent.com/3995003/60667614-3e45e200-9e6a-11e9-804b-5a5257c97cf9.png">

**Comment by TomasVotruba** [comment]
1 line is enough :D

**Comment by TomasVotruba** [comment]
Also, text is better, because I can copy-paste it and find responsbile PHPStan rule - mimic its logic much faster. Again, unique 1 line only.

**Comment by JanMikes** [comment]
Yeah, i just wanted to show how useful can rector be 😄 

Well, the cache is filled from `__construct()` so it imho never can be null (well, before filling in constructor).

**Comment by TomasVotruba** [comment]
Could you update the snippet so it's full? Best with PHPStan website link

**Comment by JanMikes** [comment]
> Could you update the snippet so it's full? Best with PHPStan website link

It took me while to understand what do you want from me 😄 the code snippet is complete. It does not have tobe filled via constructor, it can use etc `@inject` annotation, should it somehow check whether it can be null or not?

**Comment by TomasVotruba** [comment]
> It does not have tobe filled via constructor, it can use etc @inject annotation, should it somehow check whether it can be null or not?

Not sure. What's you use case?

**Comment by TomasVotruba** [comment]
Probably related https://github.com/phpstan/phpstan/commit/6771e622ad93f0aff16a100547811e1e50781acb

**Comment by TomasVotruba** [comment]
PHPStan is buggy https://phpstan.org/r/a98649a0-345c-44c4-b38a-81dde2e8816c
We can't relly on this, but we can do it better.

Let's start with constructor.

**Comment by JanMikes** [comment]
We have both use cases, either with `@inject` annotation (in parent presenters, where `__construct` can not be used because of constructor hell) and filling property in `__construct` wherever the class does not have any children.

**Comment by JanMikes** [comment]
> PHPStan is buggy https://phpstan.org/r/a98649a0-345c-44c4-b38a-81dde2e8816c

Well, it depends, because there is the annotation which says there is only instance of that object, missing `|null` in that, phpstan thinks it is fine - can rector do better? It should be developer's responsibility to keep annotations up to date, but as we all know, developers are lazy people and sometimes they forget to something, like updating the annotation 😄

**Comment by TomasVotruba** [comment]
> It should be developer's responsibility to keep annotations up to date.

In a dreamland maybe :D
