### ISSUE TITLE
[DeadCode] RemoveUnusedPrivateMethodRector don't address callables

### ISSUE THREAD

**Issue by ravanscafi** [rectorphp/rector#1700]
## Description

`Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector` is removing valid code due to some false positives regarding callables. I'm not quite sure how to tackle this, so I'm just leaving the issue, sorry.

## Current Behaviour 

```diff
 final class MyClass
 {
     public function run()
     {
         $array  = [3, 2, 1];

         usort($array, [$this, 'sort']);

         return $array;
     }
-
-    private function sort($a, $b)
-    {
-        return $a <=> $b;
-    }
 }
```

Either `[$this, 'sort']`, `[self::class, 'sort']`, `[static::class, 'sort']`, `[MyClass::class, 'sort']` are valid callables that I can recall.

## Minimal PHP Code Causing Issue
Probably `\Rector\NodeContainer\ParsedNodesByType::collect` is not accounting for it.

## Expected Behaviour

```diff
 final class MyClass
 {
     public function run()
     {
         $array  = [3, 2, 1];

         usort($array, [$this, 'sort']);

         return $array;
     }

    private function sort($a, $b)
    {
        return $a <=> $b;
    }
 }
```

**Comment by gnutix** [comment]
Related to https://github.com/rectorphp/rector/issues/1630 ?

**Comment by TomasVotruba** [comment]
@gnutix Only the same rule, but different bug
