### ISSUE TITLE
[PHPUnit] Specific method for true x > y  → greather than

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1726]
```diff
-self::assertTrue($decodedResponse[0]['start_date'] > $decodedResponse[1]['start_date']);
+self::assertGreaterThan($decodedResponse[0]['start_date'], $decodedResponse[1]['start_date']);
```

**Comment by keulinho** [comment]
Isn't that already part of the `AssertComparisonToSpecificMethodRector`?
The fixture for that rector has your feature already covered: https://github.com/rectorphp/rector/blob/master/packages/PHPUnit/tests/Rector/SpecificMethod/AssertComparisonToSpecificMethodRector/Fixture/fixture.php.inc#L10

**Comment by TomasVotruba** [comment]
Not sure. Could you add test fixture to prove that?

**Comment by keulinho** [comment]
On my way ;)
