### ISSUE TITLE
Continuous Integration/Check flag when running rector process

### ISSUE THREAD

**Issue by ravanscafi** [rectorphp/rector#1727]
I'm aware that we can run `rector process` with the `--dry-run` flag and it will suggest changes instead of changing the files.
What I'm after is a way to enforce that the rules are being followed by running it on the CI server. The flag, that could be `--ci` or `--check`, would work almost like `--dry-run`, but failing the command when a possible change is found. 

We could have other behaviors too, like simplified output, I don't know, but the main idea is being able to keep the code always "green".

**Comment by TomasVotruba** [comment]
Hi, I'm not sure I understand. What is your goal?
Could you show me example from some other tool?

**Comment by ravanscafi** [comment]
Right now, if you run `rector process . --dry-run`, the exit code will always be `0`. It doesn't matter if the output is `[OK] Rector is done! 1 changed files` or `[OK] Rector is done! 0 changed files`. With `--dry-run`, it is always OK with exit code `0`. 
           
What I want is: My `rector.yaml` is configured and when I run it, it shows `[OK] Rector is done! 0 changed files`. It's awesome, my code is green with no errors. How do I keep it like that? Well, I want to **enforce** that people follow these rules, so I would like to run something like  `rector process . --check` on my CI that would fail if some change is not following the rules. So it would return `[OK] Rector is done! 0 changed files`. and exit code `0` *OR* it would return `[FAIL] Rector found X files that needs to be changed` and exit code `1` (or any other one that is not `0`) so CIs would fail automatically on this step (and thus the files would need to be addressed by the developer).

As an example, take a look at [prettier's `--check` flag](https://prettier.io/docs/en/cli.html#check). Prettier "autoformat" your code (kinda like PHP_CodeSniffer), and you can run it on your CI to check if code is formatted. Rector is not a "autoformatter" but it can run like this (depending on the rules you set) to keep your code fresh.

**Comment by TomasVotruba** [comment]
The dry-run should invert the exit code, not return always 0.

It's hard for me to understand the issue.
Could you put it in 2-3 short points?

**Comment by TomasVotruba** [comment]
If you want CI report the Rector issues, use it as in this repository.
https://github.com/rectorphp/rector/blob/master/.travis.yml#L54

**Comment by ravanscafi** [comment]
Allow me to do some more tests, I'm missing something.

**Comment by TomasVotruba** [comment]
No troubles. These might help:

- https://github.com/rectorphp/rector/pull/805/files
- https://github.com/rectorphp/rector/issues/800
