### ISSUE TITLE
Import order causes incorrect type to be used

### ISSUE THREAD

**Issue by holtkamp** [rectorphp/rector#1729]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | `7.3.7`                           |
| Full Command   | `./vendor/bin/phpunit ./tests/Rector/Property/InjectAnnotationClassRector`  | 

## Current Behaviour 

Error in unit test in branch https://github.com/holtkamp/rector/tree/patch-intermixed-types

- https://github.com/holtkamp/rector/commit/0c93729d995d71ff8ac4e8fd73dcfbda81e4f7d1#diff-9b1ba2a53da8f03dc7cd241472c41895
- https://github.com/holtkamp/rector/blob/0c93729d995d71ff8ac4e8fd73dcfbda81e4f7d1/tests/Rector/Property/InjectAnnotationClassRector/Fixture/inject_from_var3.php.inc

## Minimal PHP Code Causing Issue

See test.

This is difficult to explain in words. 

It seems that the order of the imports / `use` statements influences which type is used for a node. 

## Expected Behaviour

I would expect that the proper type is used.

**Comment by TomasVotruba** [comment]
PR the test

**Comment by TomasVotruba** [comment]
Resolved by #1738
