### ISSUE TITLE
Migration SwiftMailer => Symfony Mailer

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#1733]
I was yesterday on a What's new in Symfony 4.3 and one core member mentioned that Swiftmailer will be deprecated and replaced with Symfony Mailer when its done.
We could add some rectors to migrate the Code to Symfony Mailer

**Comment by TomasVotruba** [comment]
Great idea. How would you start?

**Comment by TomasVotruba** [comment]
Waits for real project, closing for lack of feedback
