### ISSUE TITLE
Support reference symbol in phpdoc

### ISSUE THREAD

**Issue by tigitz** [rectorphp/rector#1734]
It seems that putting an `&` in the docblock of a parameter fails the `Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector`

I guess it would be a new feature to support this.

However even if this `&` is common in popular codebases it's not supported by phpdoc nor the PSR-5

I let you decide.

Some food for thoughts: https://github.com/phpstan/phpstan/issues/699
## Diff 

```diff
<?php

    /**
    * @param array &$array
    */
-    function test(&$array)
+    function test(array &$array)
    {

    };
```

**Comment by TomasVotruba** [comment]
Why not! Send PR with failing test case to `ParamTypeDeclarationRectorTest`
