### ISSUE TITLE
[PHP 7.4] deprecate for curly bracket array acess

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1741]
https://wiki.php.net/rfc/deprecate_curly_braces_array_access

**Comment by TomasVotruba** [comment]
Not relevant, nor matter of nodes. This will be probably handled by php-parser printer as other similar case are

**Comment by HenkPoley** [comment]
So a kind of 'null rule' for rector should already fix this? How to run that?

**Comment by TomasVotruba** [comment]
I'd look here for a fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by TomasVotruba** [comment]
There is a fixer that handles exactly this case: `NormalizeIndexBraceFixer`

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/src/Fixer/ArrayNotation/NormalizeIndexBraceFixer.php
- `NormalizeIndexBraceFixer`
