### ISSUE TITLE
What can I do, if 3rd party function uses func_get_args, but RemoveExtraParametersRectors want's to remove them.

### ISSUE THREAD

**Issue by przemo-hemmersbach** [rectorphp/rector#1746]
## Question
Accordingly to this [php variadics rfc](https://wiki.php.net/rfc/variadic) `::isVariadic` may not properly recognize variadic functions if they are using old style `func_get_args`.
`RemoveExtraParametersRector` will remove those arguments at call sites.

What workaround could I use to whitelist particular functions in 3rd party libs, while still benefit from this rector in functions I have a control over.

PS Question, since that's a "bug" in php reflection implementation if anything. Can create full bug report if advised to do so.

**Comment by TomasVotruba** [comment]
Hi, add PR with failing test case and I'll look at it.
It should be fixable

**Comment by TomasVotruba** [comment]
Closing for missing faling test, see https://github.com/rectorphp/rector/pull/1811#issuecomment-538743867
