### ISSUE TITLE
[DeadCode] `RemoveDeadConstructorRector` should not remove `private` construct

### ISSUE THREAD

**Issue by stloyd** [rectorphp/rector#1750]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | any                               |
| Full Command   | vendor/bin/rector process /src --set dead-code | 

## Current Behaviour 

Rector `Rector\DeadCode\Rector\ClassMethod\RemoveDeadConstructorRector` removes also `private` method, which should not be touched as it's done for purpose to not allow calls: `new SomeClass()`.

```diff
-    private function __construct()
-    {
-    }
-
     public static function someMethod(): bool
     {
```

## Minimal PHP Code Causing Issue

```php
<?php

class SomeClass
{
     private function __construct()
     {
     }

     public static function forExampleFactoryMethod()
     {
         return new self();
     }
}
```

## Expected Behaviour

No changes.

**Comment by TomasVotruba** [comment]
Good point! This is easy pick. Care for PR?
