### ISSUE TITLE
Rector behavior duplication in Symfony console rector

### ISSUE THREAD

**Issue by stloyd** [rectorphp/rector#1758]
Rector: `Rector\Symfony\Rector\FrameworkBundle\ContainerGetToConstructorInjectionRector` seems to be partial duplicate of: `Rector\Symfony\Rector\FrameworkBundle\GetToConstructorInjectionRector`

**Comment by TomasVotruba** [comment]
Could you copy tests from one to another to prove that?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Feel free to re-open with PR with moved tests
