### ISSUE TITLE
RemoveUnusedPrivatePropertyRector remove lines between methods in class

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#1763]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.2                               |
| Full Command   | vendor/bin/rector process src tests --dry-run  | 

The `rector.yml`:
```yml
services:
      Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector: ~
```

## Current Behaviour 

The `RemoveUnusedPrivatePropertyRector` is removing lines between methods in classes that have dead private properties.

## Minimal PHP Code Causing Issue

```php
class MyClass
{
    private $privateProperty;

    public function foo(): int
    {
        return 1;
    }

    public function baz(): string
    {
        return "1";
    }
}
```

## Expected Behaviour

I'd expect to not have the lines between class' methods removed.

**Comment by carusogabriel** [comment]
Looks like `RemoveUnusedPrivateMethodRector` and `RemoveUnusedPrivateConstantRector` have this same behaviour.

**Comment by TomasVotruba** [comment]
This cannot be handled by AST properly. You should run coding standard after reach AST change: https://github.com/rectorphp/rector#how-to-apply-coding-standards
