### ISSUE TITLE
Beautifying validation rules in Laravel

### ISSUE THREAD

**Issue by sashabeton** [rectorphp/rector#1766]
It would be great to create transformer from inline validation rules to array definition.

F.e.
```php
'required|exists:' . Model::class . ',attribute|string'
```
can be transformed to
```php
[  
  'required',  
  'exists:' . Model::class . ',attribute',  
  'string',  
]  
```
which is more beautiful, readable and editable.

Furthermore,
```php
'exists:' . Model::class . ',attribute'
```
can be transformed to
```php
\Illuminate\Validation\Rule::exists(Model::class, 'attribute')
```

**Comment by TomasVotruba** [comment]
Hi,

what Laravel version is this related to?

How does the code around the array look like? Transforming any array with `'string|string'` to `['string', 'string']` everywhere would break lot of code :D

**Comment by sashabeton** [comment]
Of course all matches shouldn't be transformed :)

This is usually used in [Illuminate\Foundation\Http\FormRequest](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Http/FormRequest.php) extensions, in function `rules`

F.e.

```php
<?php

use Illuminate\Foundation\Http\FormRequest;

class CustomRequest extends FormRequest
{
  public function rules(): array
  {
    return [
      'someAttribute' => 'required|string',
      // ...
    ];
  }
}
```

**Comment by TomasVotruba** [comment]
I see :). It seems pretty clear to me. If you want, I can guide you to create such a rule

**Comment by sashabeton** [comment]
It would be great!

**Comment by TomasVotruba** [comment]
Allright!

1. clone this repository
2. copy this file https://github.com/rectorphp/rector/blob/master/create-rector.yaml.dist to `create-rector.yaml`
3. complete all items + minimal code that is needed to be changed
4. run `bin/rector create`
5. send result as pull-request for further guidance
