### ISSUE TITLE
[DX] [RectorCI] Running multiple sets at once

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1775]
```bash
vendor/bin/rector process src --set php70 --set php71 --set php72 --set php73
```

**Comment by stloyd** [comment]
This is quite easy to implement on option side thanks to the Symfony Console: `InputArgument::IS_ARRAY`, but would require to be:
```bash
vendor/bin/rector process src --set php70 php71 php72 php73
```
https://symfony.com/doc/current/console/input.html#using-command-arguments

Or you can change this to options `InputOption::VALUE_IS_ARRAY`:
```bash
vendor/bin/rector process src --set=php70 --set=php71 --set=php72 --set=php73
```
https://symfony.com/doc/current/console/input.html#using-command-options

**Comment by TomasVotruba** [comment]
The set loading is needed as well

**Comment by stloyd** [comment]
Sorry but I don't get what do you mean.

**Comment by TomasVotruba** [comment]
https://github.com/rectorphp/rector/blob/master/bin/container.php#L16

**Comment by BenMorel** [comment]
Is this really fixed? I tried running:

```
vendor/bin/rector process src --set php70 --set php71
```

But only the `php70` set runs.
Using Rector v0.8.6.

**Comment by TomasVotruba** [comment]
This should be run separately, as one set might build on the other

```bash
vendor/bin/rector process src --set php70 
vendor/bin/rector process src --set php71 
```

**Comment by coosigma** [comment]
> This should be run separately, as one set might build on the other
> 
> ```shell
> vendor/bin/rector process src --set php70 
> vendor/bin/rector process src --set php71 
> ```
> 
> To get multipel sets at once, you need to use `rector.php` config

Could you please give an example? Thank you very much.

**Comment by TomasVotruba** [comment]
Yes, it's in the readme: https://github.com/rectorphp/rector#running-rector

Add the `SetList` constant with all the sets you need
