### ISSUE TITLE
[Slim] 3 to 4

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1792]
- https://www.slimframework.com/docs/v4/start/upgrade.html
- https://github.com/slimphp/Slim/pull/2769
- https://www.reddit.com/r/PHP/comments/cktvfi/slim_400_released/

**Comment by TomasVotruba** [comment]
Must come from community

**Comment by glensc** [comment]
I suppose nobody has published their work on this?

**Comment by TomasVotruba** [comment]
Afaik no. Most project I've heard of do migrate Slim projects directly to Symfony/Laravel, as much more maintained projects + easy to hire devs
