### ISSUE TITLE
Rector errors with anon class

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#1809]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | e.g. PHP 7.3                            |
| Full Command   | e.g. vendor/bin/rector process Foo.php  | 

## Current Behaviour 

```
 [ERROR] Could not process "Foo.php" file, due to:
         "Call to a member function getMethod() on null".

```

## Minimal PHP Code Causing Issue

```yaml
# rector.yaml
services:
    Rector\TypeDeclaration\Rector\Property\PropertyTypeDeclarationRector: ~
```

```php
class Foo
{
    private function makeClass(int $bar = 1)
    {
        $class =  new class() {
            public $bar;
        };
        $class->bar = $bar;
    }
}

```

## Expected Behaviour

no error, and:

```php
class Foo
{
    private function makeClass(int $bar = 1)
    {
        $class =  new class() {
            /** @var int */
            public $bar;
        };
        $class->bar = $bar;
    }
}

```

**Comment by TomasVotruba** [comment]
Send failing test case

**Comment by TomasVotruba** [comment]
Anonymous classes are very hard to analyse reliable, moreover when it comes to public scope, like public property assign. For that, be better skip it
