### ISSUE TITLE
Certain file paths ignored per default

### ISSUE THREAD

**Issue by scheb** [rectorphp/rector#1815]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.3.7                               |
| Full Command   | vendor/composer/bin/rector process src test -vvv | 

## Current Behaviour 

Hello there, I tried to upgrade my project with rector (great tool btw!) and was wondering why certain parts of my codebase aren't upgraded, although I haven't excluded these files and I've seen the files being auto-loaded during the parsing process. Running rector with `-vvv` revealed that they're never listed during `[parsing]`.

Recognized that it's only ignoring directories with name "fixtures", which is where I store classes to load fixture data and prepare state. They're part of the test suite and they're code like everything else following the same coding standards and autoloading conventions, so I want to include them in the upgrade process of course.

Turned out that rector has some hardcoded filters to ignore certain file paths per default (including "fixtures") and these rules cannot be deactivated/overwritten. Imo that's a bad idea, because it is not obvious to the user and there's no way to contol this behavior.

## Minimal PHP Code Causing Issue

https://github.com/rectorphp/rector/blob/548d13276e71db195c33819ec80aa23cca324849/src/FileSystem/FilesFinder.php#L100-L102

## Expected Behaviour

Rector should not make assumptions that certain paths can be excluded per default. Exclusion patterns should be required to be configured explicitly.

**Comment by TomasVotruba** [comment]
:+1: It could be a parameter

**Comment by scheb** [comment]
Thanks for the super-quick response. That would work for me :)

**Comment by scheb** [comment]
@TomasVotruba Do you have a suggestion how to name that parameter, then I may try myself on implementing it.

**Comment by TomasVotruba** [comment]
@scheb If you look how PHP version is provided, it should be the same:

- add `excluded_paths` to config like `php_version_features` - https://github.com/rectorphp/rector/blob/4e0ec2e173274587d1c11f9ca45699a33c770aef/config/config.yaml#L12
- then create e.g. `ExcludePathsProvider` like https://github.com/rectorphp/rector/blob/2883040d74fff65bb7d2900e63026f06a36c0587/src/Php/PhpVersionProvider.php#L24

**Comment by scheb** [comment]
Ok, got it.

Since there is already `exclude_paths` as a parameter, should we got with `default_exclude_paths: true/false` then?

**Comment by TomasVotruba** [comment]
Ah, what about passing this parameter to a command and keep it empty?

To be honest, I'm not sure why there are those default ignores. Possibly some left over from Symfony refactoring experiments a year back

**Comment by scheb** [comment]
Well, if you ask me, the best solution would be to remove these default excludes and instead ask people to explicitly configure them in `excluded_paths`, if they really need them. Just thought you want to keep them for a reason, but as I now understand there is no such reason ;)

**Comment by TomasVotruba** [comment]
Go for it :)
