### ISSUE TITLE
Rectors goes so far as to remove comments (which can contain valuable information)

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1846]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.3.8-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2019 09:52:12) ( NTS )                               |
| Full Command   | vendor/bin/rector --ansi process var/rector_test.php --level=code-quality  | 

## Current Behaviour 

```diff
Rector v0.5.9
Config file: rector.yaml

 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) var/rector_test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -5,12 +5,6 @@
     if ('A' === $input) {
         return false;
     }
-    
     // Some condition B we know it can't handle
-    if ('B' === $input) {
-        return false;
-    }
-    
-    // Yeah, everything else it should handle just fine
-    return true;
+    return (bool) ('B' !== $input);
 }
    ----------- end diff -----------

Applied rectors:

 * Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector


                                                                                                                        
 [OK] Rector is done! 1 changed files
```

## Minimal PHP Code Causing Issue

```
<?php
function canHandle($input)
{
    // Some condition A we know it can't handle
    if ('A' === $input) {
        return false;
    }
    
    // Some condition B we know it can't handle
    if ('B' === $input) {
        return false;
    }
    
    // Yeah, everything else it should handle just fine
    return true;
}
```

Which then turns into : 

```
<?php
function canHandle($input)
{
    // Some condition A we know it can't handle
    if ('A' === $input) {
        return false;
    }
    // Some condition B we know it can't handle
    return (bool) ('B' !== $input);
}
```

## Expected Behaviour

I don't think Rector should remove comments, as they can contain precious information. The Rector should skip this file change IMO.

**Comment by gnutix** [comment]
By the way, my code example was voluntarily simplified. The conditions are more complex and the comments help understanding them better.

> I wonder how you decide the comment is useful?

That's a tricky question to ask... I'd like to think that "you can't", and therefore shouldn't remove any comments, ever. But there might be cases where you'd like that, but I'd say it should only be done by specific rectors that you can enable/disable. Having a "SimplifyIfReturnBoolRector" that removes comments is dangerous IMHO.

**Comment by TomasVotruba** [comment]
Now I see the value in the comments and code being together.

Could you add a test case to `SimplifyIfReturnBoolRectorTest` with your example, that should be skipped?
https://github.com/rectorphp/rector/blob/1d510c0182aaa91533f780e147855ae8c2fbc47c/packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/SimplifyIfReturnBoolRectorTest.php#L30

I'll update the rule then

**Comment by gnutix** [comment]
Will do on Tuesday. Thanks a lot for your work on all these issues. :)

**Comment by gnutix** [comment]
Another example here where comments are removed by a Rector : https://github.com/rectorphp/rector/issues/2068

**Comment by TomasVotruba** [comment]
Being resolved in particual rules, closing
