### ISSUE TITLE
How to prevent Rector from doing style rewrites

### ISSUE THREAD

**Issue by redemption** [rectorphp/rector#1860]
## Question

I'm testing Rector to help do some php72 fixes, specifically the create_function and each() fixes, but I'm finding that Rector is applying changes unrelated to these Rectors.

Eg:

```
- $status = ($result) ? "created":"not created";
+ $status = $result ? "created" : "not created";
```

And:

```
if ($foo) {
} else if ($bar) {
} else {
}

```
becomes:

```
if ($foo) {
} else {
	if ($bar) {
	} else {
	}
}
```

Strings with linebreaks are also being rewritten with \n.

Eg

```
echo "Foo
Bar
Foobar";
```

becomes

```
echo "Foo\n Bar\n Foobar";
```

These are unwanted changes for us, and files that only needed only a few lines to be changed end up having dozens of lines changed.

Is there any way to configure the system to only do the changes we want?  We only need the Rectors in the php72.yaml file to run, not any additional stuff.

**Comment by TomasVotruba** [comment]
This is not possible due to technical limits of AST: https://github.com/rectorphp/rector#how-to-apply-coding-standards

You should have your coding standard setup and run it after Rector, as personal preferences might differ.
