### ISSUE TITLE
PHP Fatal error:  Uncaught Rector\Exception\DependencyInjection\ClassNotFoundException: Class "Rector\CodingStyle\Rector\Property\ArrayPropertyDefaultValueRector" was not found while loading "vendor/rector/rector/config/set/coding-style/coding-style.yaml"

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1867]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.3.8-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2019 09:52:12) ( NTS ) |
| Full Command   | vendor/bin/rector --ansi process var/ --level coding-style  | 

## Current Behaviour 

```
PHP Fatal error:  Uncaught Rector\Exception\DependencyInjection\ClassNotFoundException: Class "Rector\CodingStyle\Rector\Property\ArrayPropertyDefaultValueRector" was not found while loading "vendor/rector/rector/config/set/coding-style/coding-style.yaml"
```

## Minimal PHP Code Causing Issue

The command line above. 

## Expected Behaviour

Configuration files provided by Rector should work.

**Comment by snapshotpl** [comment]
@gnutix replace your rector to `Rector\CodingStyle\Rector\Class_\AddArrayDefaultToArrayPropertyRector`

**Comment by gnutix** [comment]
I'm not configuring directly this rector. It's done in `vendor/rector/rector/config/set/coding-style/coding-style.yaml`, which is not mine to update.

**Comment by TomasVotruba** [comment]
Related to: https://github.com/rectorphp/rector/pull/1863

The config should be updated as well (I forgot that :sweat_smile: )
