### ISSUE TITLE
[DeadCode] Requiring phpstorm-stubs leads to Multiple definitions exist for class...

### ISSUE THREAD

**Issue by atierant** [rectorphp/rector#1899]
## Question

Hi. I have a question about this commit https://github.com/rectorphp/rector/commit/bd909ab3
Can you tell me why phpstorm-stubs are not in require-dev ?

Requiring rector in my require-dev project part leads me to "multiple definitions exist" problem. Thank you !

![multiple_definitions_exist](https://user-images.githubusercontent.com/1587260/63679302-55ada580-c7f1-11e9-996a-a195fe87c9ea.png)

**Comment by TomasVotruba** [comment]
Hi, good job with commit reference!

Does the rule work locally when you remove the "phpstorm-stubs" package in your project? If so, please send PR for your proposal.

**Comment by atierant** [comment]
I'll check what I can do. I don't directly have "phpstorm-stubs" requirement in my project.
Of course, if I delete the jetbrains folder in vendors, the dead-code inspection fails.

````
me@mymachine:/mnt/c/GitSources/RectorRequirement$ rm -rf vendor/jetbrains
me@mymachine:/mnt/c/GitSources/RectorRequirement$ composer rector
> vendor/bin/rector process src --set dead-code --dry-run
PHP Warning:  require(/mnt/c/GitSources/RectorRequirement/vendor/composer/../jetbrains/phpstorm-stubs/PhpStormStubsMap.php): failed to open stream: No such file or directory in /mnt/c/GitSources/RectorRequirement/vendor/composer/au
toload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/mnt/c/GitSources/RectorRequirement/vendor/composer/../jetbrains/phpstorm-stubs/PhpStormStubsMap.php' (include_path='.:/usr/share/php') in /mnt/c/GitSources/RectorRequirement/ve
ndor/composer/autoload_real.php on line 66
Script vendor/bin/rector process src --set dead-code --dry-run handling the rector event returned with error code 255
````

I forked rector to check what I can do

**Comment by TomasVotruba** [comment]
What if you remove it from Rector's composer.json autoload and rebuild?

**Comment by atierant** [comment]
Simply like this ? https://github.com/rectorphp/rector/commit/e37c430e86d55a7bbb461e9ea2ead2d53f402d97

I updated my test project ([master branch](https://github.com/atierant/rector-phpstorm-stubs-requirements)) according to the fork to point out the diff.

````
me@mymachine:/mnt/c/GitSources/RectorRequirement$ composer rector
> vendor/bin/rector process src --set dead-code --dry-run
Rector dev-phpstorm-requirement@e37c430

 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 2/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  66%
 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) src/Inspect.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -17,7 +17,7 @@

     public function run()
     {
-        $this->runWithDefault([]);
+        $this->runWithDefault();
         $card = self::runWithStaticDefault([]);
     }
    ----------- end diff -----------

Applied rectors:

 * Rector\DeadCode\Rector\MethodCall\RemoveDefaultArgumentValueRector


 [OK] Rector is done! 1 changed files

Script vendor/bin/rector process src --set dead-code --dry-run handling the rector event returned with error code 1
me@mymachine:/mnt/c/GitSources/RectorRequirement$
````

**Comment by TomasVotruba** [comment]
> Simply like this ? e37c430

That's also a way.

Looks good :+1:

**Comment by atierant** [comment]
The script seems to output in error by the way.
I launched a CI on my branch to check : https://travis-ci.org/atierant/rector/builds/576815247

**Comment by TomasVotruba** [comment]
Try running it with: `--debug`

The dependency should not be removed, just moved to `autoload-dev`, because tests work with it.

**Comment by atierant** [comment]
Ok for the error, just a segfault in one of my php modules, nothing to do with rector.
When I run it on another clean env, everything looks fine.
P.R. is here: https://github.com/rectorphp/rector/pull/1901
Thank you for the lead ;)

**Comment by gnutix** [comment]
@TomasVotruba Now the stubs are located inside Rector's code in `stubs/`, which again leads to PhpStorm's `multiple definition exist for class %s` warnings. Could we add a `.gitattributes` file containing `/stubs export-ignore` so that stubs are ignored when installing Rector from Composer ?

**Comment by gnutix** [comment]
Wouldn't it make sense for a Rector not to work if the real classes are missing from the project ? That would indicate that the included Rector makes no sense, wouldn't it ?

**Comment by TomasVotruba** [comment]
Logically and yes, form user experince that means:

- find out why `PHPUnit_Framework_TestCase` is missing
- find how PHPUnit loads it 
- learn about `composer.json` and `require-dev` section
- learn about `files` section
- find out where is `PHPUnit_Framework_TestCase` located
    - if nowhere, figure out they have to create it manually
    - figure out how to autoloadit it 
    - figure out `composer dump-autoload` command, what it does

I had to do this 5 days ago, took me 15 minutes of life (and I wrote this :D )


Most people will get to step 1 and close it

**Comment by gnutix** [comment]
Couldn't we add a custom `spl_autoload_register` function which would catch missing classes errors and display an understandable error message like "The class %s is not loaded in your code and is needed by Rector %s. You should either include the library containing this class in your autoload section (or composer.json or rector.yaml) or skip the Rector %s in rector.yaml -> exclude_rectors" ?

**Comment by TomasVotruba** [comment]
That again, puts pressure on user. I'd hate such a tool, when I know it can do it

**Comment by gnutix** [comment]
What about this then : 

```
# rector.yaml  
parameters:
    remove_stubs: true
```

This option would : 

1) remove the stubs/ folder when running Rector
2) skip trying to load any stubs classes

That way the user is in control and can deal with the issue explicitly. And if we really want nice DX, we could add a nice error message in case the parameter is removed/turned off and we can't find the stubs/ folder (the error I previously shared above) that maybe the package needs to be reinstalled (`rm -rf vendor/rector && composer install`).

**Comment by TomasVotruba** [comment]
If it is optional parameter, we can try that :)

**Comment by atierant** [comment]
I had the same behaviour in my IDE, so as a workaround for now, I removed Rector from my dev dependencies, and I made a little shell script as told in the main readme :

    #!/bin/sh
    echo "Instant Upgrades and Instant Refactoring of php code."
    docker run -v $(pwd):/project rector/rector:latest \
    process /project/src /project/tests \
    --set symfony34 \
    --autoload-file /project/vendor/autoload.php

**Comment by gnutix** [comment]
You might want to add `docker pull rector/rector:latest` in your little script, so you're always running the latest version. :)
