### ISSUE TITLE
Docs Overview - better structure

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#1904]
Can we have a better separation of project specific (incl framework) and generic ones?
https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md
Currently, it is hard to spot those.

I suggest
- Generic
  - PHP
  - PSR4
  - ...
- Project
  - CakePHP
  - Doctrine
  - ...
- ...

This way the really project specific ones are after the more useful ones for pretty much everyone, the generic ones.

**Comment by TomasVotruba** [comment]
What do you suggest?

**Comment by dereuromark** [comment]
Might then not be as trivial. Thanks anyway for looking into this.
