### ISSUE TITLE
Rector that turns `?><some html><?php` into `echo '<some html>';`

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#1907]
A rector that turns 
`?>it's text<?php` 
into 
`echo 'it\'s text';` 

This is probably for legacy code that's way beyond what this project is focusing on, but it would be nice to have some transform that pulls all of "end PHP interpreter" / "start PHP interpreter" into PHP space.

Another one could be chaining consecutive `echo`'s together into a concatenation. And one that turns them into a `sprintf()` invocation.

That would ease transfering especially messy interwoven PHP code to a template language. I've inherited legacy code with up to 127 interpreter open/closes per file.

Currently I'm doing this process half-way manually in PhpStorm, which is messy and prone to errors.

**Comment by TomasVotruba** [comment]
Indeed, this is now what we focus on, as it has many edge-cases.

If you want to make it work, look at `BetterStandardPrinter`, these is some very basic handling of Html nodes that needs to be fixed (obviously).

Let me know if you need any guidance.

**Comment by HenkPoley** [comment]
For reference to other people dropping by: https://github.com/rectorphp/rector/blob/master/src/PhpParser/Printer/BetterStandardPrinter.php

And `<?php` is defined as T_OPEN_TAG in nikic/php-parser, which is a small part of the puzzle.

**Comment by TomasVotruba** [comment]
Closing as stated not-priority and hard to do right.

Might be re-open with specific proprietary projet set

**Comment by HenkPoley** [comment]
Makes sense, could you be so kind to spew a couple of edge case problems you are seeing? For my minimal use case I'd already be happy with a `echo <<< RANDOM_HEREDOC_ID`, which seems pretty straightforward. My editor should be able to pick up from there.

**Comment by TomasVotruba** [comment]
My knowledge is almost to zero in this field
