### ISSUE TITLE
[Dead-code] If condition is always true - remove it

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1913]
Hi, first, let me please thank you for doing your great job with rector!

I was thinking it would be awesome that rector could remove useless if conditions, detected by phpstan: https://phpstan.org/r/4f510796-260e-469d-a18e-7eb5ce7a9caa
 
## Diff 

```diff
- if (true) {
// do something
- }
```

**Comment by TomasVotruba** [comment]
Note, this case will be probalby remove, but this one is missed by `RemoveAlwaysTrueConditionSetInConstructorRector`:

```diff
-if ($a === $a) {
-}
```
