### ISSUE TITLE
Fatal Error on Doctrine\Common\Cache\RiakCache

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#1919]
For some reason rector seems to load Doctrine\Common\Cache\RiakCache from my local project, and then also from the global ~/.config/composer directory where I installed rector (and it's dependencies), because its requirements clashed with older libraries in my project.

| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS ) |
| Full Command   | ~/.config/composer/vendor/bin/rector process . --set laravel56  --debug  | 

## Current Behaviour 

[parsing]  /mnt/c/Users/hjpol/[..my project..]/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RiakCache.php
PHP Fatal error:  Cannot use Riak\Object as Object because 'Object' is a special class name in /home/henk/.config/composer/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RiakCache.php on line 8

## Minimal PHP Code Causing Issue

https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RiakCache.php

**Comment by TomasVotruba** [comment]
There is not much we can do, as 3rd party code is broken by using reserved PHP `Object` word.

What minimal PHP code your run Rector on is causing this?

**Comment by debo** [comment]
@TomasVotruba @HenkPoley the Riak library was fixed quite a while ago, so I guess it's just a matter of bumping the dependency version.

**Comment by HenkPoley** [comment]
I don't see anything specific Riak in my composer.lock. Only that doctrine/cache is v1.8.0, which seems to be latest.

**Comment by TomasVotruba** [comment]
Closing as root of the problem lies in 3rd party code

**Comment by HenkPoley** [comment]
With the side remark that this means that whole class of PHP software cannot use Rector at all; anything that uses Doctrine, and anything that depends on Doctrine for some of it's (unused) use cases.

**Comment by TomasVotruba** [comment]
I personally use Rector on many Doctrine projects and don't have such problem - e.g. migration id to uuid set or removing unused Doctrine properties.

We had this issues in the past and 3rd party code needs to be correct to perform analysis. Missing or invalid classes cannot be easily bypassed.

If you find a way though, let me know so we can integrate it here.

**Comment by HenkPoley** [comment]
Just a heads-up but with Laravel-5.5 and Rector 0.5.21 on otherwise much the same codebase, I'm not seeing the above problem anymore 🤷‍♂️

**Comment by TomasVotruba** [comment]
Thanks, that's great!
