### ISSUE TITLE
Allow regex on path

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#1920]
Let's say that I have 2k php files and 4k twig files, and that the symfony40 set only modify php files.
Running the --set symfony40 will analyse 6k files. I wonder if we couldn't match path with a regex to analyse only needed files like this :
```diff
-docker run -v $(pwd):/project rector/rector:latest process /project/src --autoload-file /project/vendor/autoload.php --set symfony40
+docker run -v $(pwd):/project rector/rector:latest process /project/src/**/*.php --autoload-file /project/vendor/autoload.php --set symfony40
```

It could improve performance by a lot no ? :)

**Comment by TomasVotruba** [comment]
This is handled by console tool like oh-my-zen shell :)

**Comment by vasilvestre** [comment]
> This is handled by console tool like oh-my-zen shell :)

It is ?

**Comment by TomasVotruba** [comment]
Yea, cannot find it now, but in ECS I promoted `check src/*/` as a feature, then I found out it's based on my shell.

You often need the context of whole application - dependencies, types etc., so it's better to run Rector on bigger amount of code.

If you need to test it to be sure it work the way you intent, run it on just 1-5 files at once at start.
