### ISSUE TITLE
[DeadCode] Remove coalesce null if previous variable is already nullable

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1936]
```diff
$nullableValueAlready = 1;
if (rand(0,2)) {
   $nullableValueAlready = null;
}

-return $nullableValueAlready ?? null;
+return $nullableValueAlready;
```

**Comment by keulinho** [comment]
Isn't the coalescing always dead code?
I don't get the `if previous variable is already nullable` part here, why bother if the variable is nullbale or not?

The coalescing would translate to the verbose:
```php
if ($nullableValueAlready === null) {
    return null;
}

return $nullableValueAlready;
```

I can't think of where a coalesce null makes sense.
Am i missing something here?

**Comment by TomasVotruba** [comment]
Not sure what was the issue about when I made it.

This can be closed
