### ISSUE TITLE
get value of specific variable

### ISSUE THREAD

**Issue by subabrain** [rectorphp/rector#1941]
## Question
Hello again,

i want to get the value of a variable - like this:

```
<?php

$test = "hi";
$test2 = $test;

//Now i want to get the value of $test2... in this case "hi"

?>
```

is this possible with rector?

thanks a lot!

Greetings Robert Beran

**Comment by TomasVotruba** [comment]
Hi, 2 thinks pop in mind to try or combine:

- 1) `Rector\PhpParser\Node\Value\ValueResolver` service
- 2) The scope of `$test2` variable

    ```php
    /** @var \PHPStan\Analyser\Scope */
    $scope = $node->getAttribute('scope');
    $scope->...?
    ```

**Comment by subabrain** [comment]
Hi,

thanks a lot!

could you give an example for the 1. think?

thx!

greetz - Robert

**Comment by TomasVotruba** [comment]
- create own Rector - https://github.com/rectorphp/rector#3-steps-to-create-own-rector
- add `getNodeType()` for [`Variable::class`], see Node overview - https://github.com/rectorphp/rector/blob/master/docs/NodesOverview.md#phpparsernodeexprvariable
- require `Rector\PhpParser\Node\Value\ValueResolver` in the constructor
- call it in `refactor()` method no the `$node`

**Comment by subabrain** [comment]
Hello and thanks,

ok i see - can i use "ValueResolverTest" for it too?

Thanks!

greetz - Robert

**Comment by subabrain** [comment]
hi - ok thanks!

but whats the "expected" for?

thx a lot :)

**Comment by TomasVotruba** [comment]
It's expected value for the input

**Comment by subabrain** [comment]
thx!

can you give me an example how this value is set?

Thanks a lot!

Greetings
Robert

**Comment by TomasVotruba** [comment]
The task is not trivial. You need to start here, that's the entry point: https://github.com/rectorphp/rector/issues/1941#issuecomment-527225620

Closing as the questions tend to ask for very basic unrelated content that was answered.
