### ISSUE TITLE
Library versioning

### ISSUE THREAD

**Issue by msvrtan** [rectorphp/rector#1944]
## Question

Is Rector following semver? Just few days ago, with a release of 0.5.12 set of new libraries have been added, making my setup harder (as I dont have it in the mainline so I had to install it again with each composer change). I'm not sure if patch version is the right place for adding dependencies, seems to make it harder to determine the version. For instance, doctrine/annotations 1.7 have been added as a dependency, which requires php 7.2 and composer didn't even try to install 0.5.11, I had to manually define the version... And this was not the only time I had issues, often when new phpstan comes out, you bump the dependencies up and composer is unable to install rector due to version mismatchs. I'm not 100% sure but I think by upgrading them only in minor versions, those issues should go away ..

**Comment by TomasVotruba** [comment]
### Related to Semver

Well, change of composer dependencies are not BC breaks, unless the installed class breaks something it should not. I'll borrow explanation from Doctrine team (the last section):  https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

As for 0.x, the semver is very benevolent compared to 1+.x
See: https://semver.org/#spec-item-4

<br>

### To your Specific Problem 

I simply used `composer require doctrine/annotations` and I didn't know doctrine/annotations 1.7 requires PHP 7.2. I've gone down to 1.6, that need PHP 7.1, see: https://github.com/rectorphp/rector/commit/194a423c6f393bdce8f79c2ddd43ed0583bda6c5

Let me know if current `master` resolves your problems

**Comment by Anyqax** [comment]
couldn't this be prevented if you set https://getcomposer.org/doc/06-config.md#platform to 7.1?

**Comment by TomasVotruba** [comment]
Resolved by allowing lower `doctrine/annotations` package
