### ISSUE TITLE
[Laravel] Add Laravel 6 instant upgrade set

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1949]
- https://laravel-news.com/laravel-6
- https://laravel.com/docs/6.0/upgrade
- https://github.com/laravel/docs/pull/5531

**Comment by TomasVotruba** [comment]
https://laravel.com/docs/6.0/upgrade

**Comment by bskiefer** [comment]
+1

**Comment by TomasVotruba** [comment]
-https://github.com/laravel/framework/commit/67a38ba0fa2acfbd1f4af4bf7d462bb4419cc091

**Comment by TomasVotruba** [comment]
- https://github.com/laravel/framework/commit/dcd6b59261ced042b56b85e40f3a9dfe364d206d

```diff
if (! $user->role->isEditor()) {
-    $this->deny("You must be an editor to edit this post.")
+    return $this->deny("You must be an editor to edit this post.")
}
```

**Comment by TomasVotruba** [comment]
- https://github.com/laravel/framework/commit/6c1e014943a508afb2c10869c3175f7783a004e1

extra argument added

**Comment by TomasVotruba** [comment]
> The Lang::trans and Lang::transChoice methods of the translator have been renamed to Lang::get and Lang::choice.

- method rename

**Comment by TomasVotruba** [comment]
> The Lang::get and Lang::getFromJson methods have been consolidated. Calls to the Lang::getFromJson method should be updated to call Lang::get.



- method rename

**Comment by TomasVotruba** [comment]
> The Input facade, which was primarily a duplicate of the Request facade, has been removed. If you are using the Input::get method, you should now call the Request::input method. All other calls to the Input facade may simply be updated to use the Request facade.

- static method call rename

**Comment by TomasVotruba** [comment]
> The form request's validationData method was changed from protected to public. If you are overriding this method in your implementation, you should update the visibility to public.

- method visibility change `protected` → `public'
-
