### ISSUE TITLE
Rector which creates stubs

### ISSUE THREAD

**Issue by localheinz** [rectorphp/rector#1959]
Perhaps it would make sense to create a rector that creates stubs, similar to https://github.com/rectorphp/rector/tree/master/stubs? 

These could be used in PhpStorm, for example, in projects which rely on code that is available via a PHAR only.

Perhaps this is out of the scope of this project, as for example, a user would perhaps like to create stubs from an existing project, rather than strip down an existing project to stubs.

For reference, see https://twitter.com/localheinz/status/1169878046968385536.

## Diff 

```diff
 function function bar(Baz $baz): Qux
 {
-    // body here      
 }

 class Foo
 {
     public function bar(Baz $baz): Qux
    {
-        // body here      
    }
 }
```

**Comment by TomasVotruba** [comment]
Could give me more detailed description of use?

How would you use it + configure it?

Do you mean stubs like https://github.com/rectorphp/rector/tree/master/stubs ?

**Comment by localheinz** [comment]
@TomasVotruba 

👍

**Comment by TomasVotruba** [comment]
How would you use it + configure it?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback & to broad to make generic withou propper research of status quo
