### ISSUE TITLE
Whitespace indentation breaking

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#1964]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | e.g. PHP 7.3 (invoke `php -v`)                               |
| Full Command   | e.g. vendor/bin/rector process /src --set=cakephp34  | 

Using latest dev-master branch.

## Current Behavior 

Dry-Run shows what will happen
```
                /** @var \Cake\Console\ConsoleInputSubcommand[] $subcommands */
-               $subcommands = $parser->subcommands();
+  $subcommands = $parser->subcommands();
```
and
```
        /**
-        * Get the option parser
-        *
-        * @return \Cake\Console\ConsoleOptionParser
-        */
-       public function getOptionParser() {
+  * Get the option parser
+  *
+  * @return \Cake\Console\ConsoleOptionParser
+  */
+ public function getOptionParser() {
```

Once applied it actually destroys the indentation (2 tabs => 2 spaces).

It looks like the docblock before could cause this.

## Expected Behavior

Current indentation/whitespace should not be touched/modified.
Especially, since in this case there is not even a change here done.

**Comment by dereuromark** [comment]
Another issue are file doc blocks above containing normal (spaces) whitespace:
```
- * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
- * @link          https://cakephp.org CakePHP(tm) Project
- * @since         3.0.0
- * @license       https://opensource.org/licenses/mit-license.php MIT License
+ * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
+ * @link https://cakephp.org CakePHP(tm) Project
+ * @since 3.0.0
+ * @license https://opensource.org/licenses/mit-license.php MIT License
  */
```

Those files are all modified here in a way that all valid changes are now cloaked.

**Comment by dereuromark** [comment]
I just did with the latest rector master and also fresh phpstan patch 0.11.16
Same issue remains, especially after docblocks, both inline and multiline, the indentation is broken and lost:
```
        /**
-        * Get the option parser for this shell.
-        *
-        * @return \Cake\Console\ConsoleOptionParser
-        */
-       public function getOptionParser() {
+  * Get the option parser for this shell.
+  *
+  * @return \Cake\Console\ConsoleOptionParser
+  */
+ public function getOptionParser() {

...

                /** @var \Cake\Console\ConsoleInputSubcommand[] $subcommands */
-               $subcommands = $parser->subcommands();
+  $subcommands = $parser->subcommands();
```

The opening tag line remains intact, it is the following lines that break.

**Comment by TomasVotruba** [comment]
Could you share the smallest PHP code that breaks in gist (https://gist.github.com/)? 

I'll try it locally

**Comment by dereuromark** [comment]
https://gist.github.com/dereuromark/bb2c50752c250389458c455d043c5b3f

**Comment by TomasVotruba** [comment]
Thanks! It passes locally, so I've added it to Travis test battery to see the result:
https://github.com/rectorphp/rector/pull/2027/files

I wonder... maybe MacBook might be the issue. I've seen some space troubles in the past.

**Comment by dereuromark** [comment]
You are using the wrong indentation. Please commit it as tab indentation! Your IDE probably auto-transformed to spaces. Spaces of course work, but it must also work on tab indentation.

**Comment by TomasVotruba** [comment]
> Your IDE probably auto-transformed to spaces.

That' the one, good catch :+1: 

I'll check the tabs.

**Comment by dereuromark** [comment]
My guess is: The phpstan tooling was always only meant to introspect code, thus the irrelevance for them to respect whitespace characters. Since the file was read-only accessed basically, the invalid changes here were never really important or noticeable.

**Comment by TomasVotruba** [comment]
Yes, for that reason I wrote complete new layer above it to perserve formatting (in packages/BetterPhpDocParser). 

I'll have to check if phpdoc-parser tokens differntiate between tab and space token.
