### ISSUE TITLE
Load files in separate processes

### ISSUE THREAD

**Issue by afilina** [rectorphp/rector#1977]
I work on some really old projects that don't use namespaces and are littered with global helper functions. This blows up Rector with a fatal error:

```
Cannot redeclare functionName() (previously declared in /path/to/helper1.php:3) in /path/to/helper2.php on line 10
```

There should be an optional flag to check each file in a separate process (like PHPUnit's `runInSeparateProcess`). Even if it means a great cost to performance. I have 1.2M NCLOC in 13 applications, so doing any kinds of fixes to the code to get Rector running is not feasible.

I'd be happy to contribute if you point me in a direction.

**Comment by TomasVotruba** [comment]
How did you solve it?

**Comment by afilina** [comment]
I decided not to use Rector. Feel free to reopen if someone else requests it, but I won't be able to contribute.

**Comment by TomasVotruba** [comment]
Could you elaborate alternative/why for similar visitors?

**Comment by afilina** [comment]
I wasn't sure whether Rector would even be useful to me, so didn't feel like investing that much time into a "maybe". I just used PHPCompatibility to run some reports for me instead.

**Comment by TomasVotruba** [comment]
I see, good choice for autolaoding incompatible code :+1:
