### ISSUE TITLE
[CodingStyle] strict array_search

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#2009]
```diff
-array_search($value, $items);
+array_search($value, $items, true);
```

**Comment by jeroenherczeg** [comment]
Hi Tomas,

I want to try this. But I don't know which directory to create this :)

![Screenshot 2019-09-21 22:17:22](https://user-images.githubusercontent.com/759412/65378787-e1fe9b80-dcbd-11e9-93d6-08d9fdc4668c.png)

**Comment by TomasVotruba** [comment]
Hey, you opened correct package :) look at `create-rector.yaml` if you want to save time generating rule and tests.

Otherwise it's /Rector/...used...node, here it would be /Rector/FuncCall
