### ISSUE TITLE
CountOnNullRector misses some edge cases

### ISSUE THREAD

**Issue by BackEndTea** [rectorphp/rector#2028]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | N/A           |
| Full Command   | N/A | 

## Current Behaviour 

The rector used `is_array` or instanceof Countable to determine if the variable can be counted. This misses 2 edge cases, namely `SimpleXmlElement` and `ResourceBundle`. Both of these can be `counted` but don't implement the `Countable` interface.

For exmaple, symfonys polyfill for `is_countable`: https://github.com/symfony/polyfill-php73/blob/2ceb49eaccb9352bff54d22570276bb75ba4a188/bootstrap.php#L16

## Minimal PHP Code Causing Issue

```php
function countSimple(?SimpleXMLElement $foo): int
{
    return count($foo);
}

```
## Expected Behaviour

The 2 classes should be part of the check to see if the variable is countable.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

Fix would be to add those 2 types to `isCountableType()` method here: https://github.com/rectorphp/rector/blob/b8de750cccb3abf560501185d88784b2cbbc3f2d/packages/NodeTypeResolver/src/NodeTypeResolver.php#L242

Could you verify?
