### ISSUE TITLE
Protected/private constructors are turned into public

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2057]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | `PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )` |
| Full Command   | `vendor/bin/rector --ansi --dry-run --debug process src` | 

Running `0.5.13` on our entire codebase applies the following unexpected changes : 

```diff
2) src/.../CropParameters.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -9,7 +9,7 @@

 final class CropParameters extends ParameterBag
 {
-    private function __construct(array $params)
+    public function __construct(array $params)
     {
         // Ensure mandatory parameters are present
         foreach (['width', 'height'] as $key) {
    ----------- end diff -----------

Applied rectors:

 * Rector\CodingStyle\Rector\ClassMethod\MakeInheritedMethodVisibilitySameAsParentRector
 * Rector\Rector\Argument\ArgumentRemoverRector
 * Rector\PHPUnit\Rector\ExceptionAnnotationRector
 * Rector\Renaming\Rector\Annotation\RenameAnnotationRector
 * Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector
 * Rector\Rector\Argument\ArgumentDefaultValueReplacerRector
 * Rector\Rector\Argument\ArgumentAdderRector
 * Rector\Rector\ClassMethod\WrapReturnRector

5) src/.../SystemFormats.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -33,7 +33,7 @@
-    protected function __construct(array $elements = [])
+    public function __construct(array $elements = [])
     {
         parent::__construct($elements);
     }
    ----------- end diff -----------

Applied rectors:

 * Rector\CodingStyle\Rector\ClassMethod\MakeInheritedMethodVisibilitySameAsParentRector
 * Rector\Rector\Argument\ArgumentRemoverRector
 * Rector\PHPUnit\Rector\ExceptionAnnotationRector
 * Rector\Renaming\Rector\Annotation\RenameAnnotationRector
 * Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector
 * Rector\Rector\Argument\ArgumentDefaultValueReplacerRector
 * Rector\Rector\Argument\ArgumentAdderRector
 * Rector\Rector\ClassMethod\WrapReturnRector
```

**Comment by TomasVotruba** [comment]
Hi, this is expected as you run code quality set that includes `MakeInheritedMethodVisibilitySameAsParentRector`

If you want to prevent the change, just ignore the rule as shown in README

**Comment by gnutix** [comment]
Okay, thanks for the explanation! I'll do just that then. :)

**Comment by TomasVotruba** [comment]
Btw, why should be the constructor `private`? It seems like a service to me + hidden parent behavior override

**Comment by TomasVotruba** [comment]
In this case it's only delegating values, so it could be removed completely like this,  right?

```diff
5) src/.../SystemFormats.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -33,7 +33,7 @@
-    public function __construct(array $elements = [])
-     {
-         parent::__construct($elements);
-     }
```

**Comment by gnutix** [comment]
It's using multiple [named constructors](http://verraes.net/2014/06/named-constructors-in-php/), thus the private constructor. Can't share all the code, it would be hard to anonymize.

**Comment by TomasVotruba** [comment]
I see. But why the parent public construct in parnet collection?
3rd party legacy?

**Comment by TomasVotruba** [comment]
I wonder if it could be excluded for `__construct`, since there might be some intention while doing this change. What do you think?

**Comment by TomasVotruba** [comment]
...or detect somehow named constructor? :) That might be the best!

**Comment by gnutix** [comment]
I guess you could look for "return new self/static" in static methods + protected/private constructor ? Not sure how hard it is to figure out such combination.

And yeah, the public parent comes from Symfony's HttpFoundation ParameterBag class.

**Comment by gnutix** [comment]
I've tried running `dev-master@f0222ea` and it still changes the `private/protected` constructors to `public` in the two examples above.

**Comment by TomasVotruba** [comment]
Could you send failing test case to `MakeInheritedMethodVisibilitySameAsParentRector` to provide exact failing code?

**Comment by gnutix** [comment]
There you go : https://github.com/rectorphp/rector/pull/2082

**Comment by TomasVotruba** [comment]
Thanks!

Better refer issue in PR, rather than other direction.

Than you can close it onr merge: https://help.github.com/en/articles/closing-issues-using-keywords
