### ISSUE TITLE
PHP 7.4 migration : what's the status ?

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2059]
As PHP 7.4.0 RC are being released, I thought it would be nice to try Rector to upgrade our codebase and benefit from the new typed properties.

I've successfully used `--level php74`, however I feel like there should be two more steps to have a proper migration :

1. Removing `@var` annotations that are not useful anymore. I've found https://github.com/rectorphp/rector/issues/886 which talks about it, and followed the advice to "Use official NoSuperfluousPhpdocTagsFixer" (through easy-coding-standard), but it seems that it only process `@param`/`@return` annotations. PHP-CS-Fixer is not ready for 7.4 apparently : https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4382

2. Removing `get*`/`set*`/`has*`/`is*` methods that have no custom logic (and were only here to ensure the type of the variable was respected). And therefore turn the properties to public and convert all methods calls to properties access.

Are there any Rectors / Fixers to do that yet ?
Thanks for your insights.

**Comment by TomasVotruba** [comment]
Hi, this is rather custom migration than PHP 7.4 upgrade, since it changes behavior and is opinionated.

Recommended reading (just Google translate) https://phpfashion.com/typed-properties-v-php-7-4-jsou-cool-ale-ne-jak-si-myslite

Saying that, if you want to write them for Rector, I can guide you, but I don't plan to add them.

**Comment by gnutix** [comment]
Thanks for the read! It reframes my understanding of how/when typed properties might be useful. And even for protected variables, as there's no variance yet, it seems very limited.

As I did this experiment just for fun, I won't write custom Rectors. But if I ever do need your help for such work, I'll let you know for sure! :)

Thanks again. Take care.

**Comment by TomasVotruba** [comment]
Well said :)

Personally I'll use https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#typedpropertyrector + keep methods
