### ISSUE TITLE
[CodeQuality] Allow private construtor for named constructors

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#2063]
I guess you could look for "return new self/static" in static methods + protected/private constructor ? Not sure how hard it is to figure out such combination.

And yeah, the public parent comes from Symfony's HttpFoundation ParameterBag class.

_Originally posted by @gnutix in https://github.com/rectorphp/rector/issues/2057#issuecomment-536229922_

**Comment by TomasVotruba** [comment]
@gnutix It seems like __construct visibility override is allowed from PHP 7.2+.
It throws fatal on PHP 7.1: https://3v4l.org/RFYmn

I guess you use PHP 7.2+?

**Comment by gnutix** [comment]
7.3 in general yes.
