### ISSUE TITLE
Install Rector globally

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#207]
Is possible to install `Rector` globally with composer, like `PHPUnit` and `PHP-CS-Fixer`, and use it? :zap:

**Comment by TomasVotruba** [comment]
What happened when you tried that?

**Comment by carusogabriel** [comment]
Sorry, I was missing the `--dev` flag. Got this working without it:
```diff
- composer global require --dev rector/rector @dev nikic/php-parser '4.0.x-dev'
+ composer global require rector/rector @dev nikic/php-parser '4.0.x-dev'
```

**Comment by TomasVotruba** [comment]
I recall I had many troubles with compser global at @ApiGen, let's narrow allowed installitions to composer create-project * and composer require to not waste time with that.

Preffered way to one path is `composer create-project *`, see: https://github.com/rectorphp/rector/blob/master/docs/HowUseWithOldPhp.md

**Comment by garethellis36** [comment]
For anyone who is coming to this issue through google and finding that the link mentioned in @TomasVotruba 's last comment is broken, you can follow this approach instead if you have dependency conflicts in your project vs Rector:
https://getrector.org/blog/2020/01/20/how-to-install-rector-despite-composer-conflicts

In case that link breaks:
`composer require rector/rector-prefixed`
`vendor/bin/rector`

**Comment by TomasVotruba** [comment]
I've updated the link, thanks :+1:

**Comment by svenluijten** [comment]
FWIW the link to the blog post changed (again) and it can now be found at https://getrector.com/blog/how-to-install-rector-despite-composer-conflicts.
