### ISSUE TITLE
let ConstructorInjectionToActionInjectionRector move even more

### ISSUE THREAD

**Issue by jeroensmit** [rectorphp/rector#2089]
Currently dependencies of private methods are skipped.

These can also be refactored. I can imagine multiple ways to do this.

**Option 1: ActionInject to all methods and that set properties**
[example](https://github.com/jeroensmit/rector/blob/ConstructorInjectionToActionInjectionRectorFeature/packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/move_more2.php.inc)
Easy fix, but also results in unneeded dependencies (though that already was the case using constructor injects)

**Option 2: ActionInject in methods calling the private methods (and calling methods that call methods) and that set properties**
[example](https://github.com/jeroensmit/rector/blob/ConstructorInjectionToActionInjectionRectorFeature/packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/move_more.php.inc)
More complex than above, but cleaner

**Option 3: ActionInject in methods calling the private methods (and calling methods that call methods) and pass as parameters**
[example](https://github.com/jeroensmit/rector/blob/ConstructorInjectionToActionInjectionRectorFeature/packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/move_more3.php.inc)
No need for properties, but can lead a lot of parameter passing if there is a method calling a method, calling a method....

My suggestion:
Add a "ChildMethodStrategy" parameter defining the behaviour with the following options:

- DoNothing (current behaviour)
- Property (Option 2)
- Parameter (Option 3) 

And skip option 1 because option 2 is always better.

Another solution is create other rectors.

What do you think?

**Comment by TomasVotruba** [comment]
I don't think this should be handled at all.

There are no direct dependencies in actoins
