### ISSUE TITLE
Simplify PHPUnit Rectors

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#209]
After @TomasVotruba's [comment](https://github.com/rectorphp/rector/pull/203#issuecomment-353068037) about not creating numerous `Rector`s, to avoid duplication of code and complexity, I found a `PHPUnit` `Rector` that could be generalized: `SpecificMethodCountRector`. It can become a `SpecificMethodCompareRector` because the logic for refactor is the same: [verify if the assertion method is `assertSame` or `assertEquals`](https://github.com/rectorphp/rector/pull/198/files#diff-a7ca84c531c86cadc201c1d5354dd0baR61) (and its negative forms). Them, [rename the method](https://github.com/rectorphp/rector/pull/198/files#diff-a7ca84c531c86cadc201c1d5354dd0baR94) and move arguments up. We could generalize the [`$renameMethodMap`](https://github.com/rectorphp/rector/pull/198/files#diff-a7ca84c531c86cadc201c1d5354dd0baR39) to match [`$oldToNewMethod`](https://github.com/rectorphp/rector/pull/203/files#diff-740e97ade92e0a9fb1358a5595da4d41R27) in `SpecificMethodRector` and work with multi-demensional arrays to specify what method should change.

This will avoid code duplication and make easier to extend. What do you think?

**Comment by TomasVotruba** [comment]
I think it's good idea to simplify them.
Could you provide before/after example? It's much more easier to imagine for me.

**Comment by carusogabriel** [comment]
Going to code and past the diff and examples here.

**Comment by TomasVotruba** [comment]
Could you rather open PR? I think it's better if you already have specific code idea in your mind.
 It's easier to start with and finish to merge and saves us both work.

**Comment by carusogabriel** [comment]
Actually, I’ve already open #211 at the same time you opened #210 😅
I didn’t update it, as you made a lot of improvements and changes. Can you take a look and guide me?
