### ISSUE TITLE
ConstructorInjectionToActionInjectionRector breaks code when constructor interacts with dependency

### ISSUE THREAD

**Issue by jeroensmit** [rectorphp/rector#2090]
[See example](https://github.com/jeroensmit/rector/blob/ConstructorInjectionToActionInjectionRectorFix2/packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/extra_calls_in_constructor.inc.php)

The example shows the current behaviour. Resulting in an undefined variable in the constructor.

I'm happy to provide a fix, but I'm not sure what the expected behaviour is. 

- Don't change the code
- Move to action but also keep the parameter in the constructor
- Also move the additional logic to the action

Like to hear your opinion

**Comment by TomasVotruba** [comment]
> Don't change the code

I'd go with this, since the `default` property must be the same in every action

**Comment by TomasVotruba** [comment]
Closing as answered
