### ISSUE TITLE
[Contributing] When should we update the docs/ files ?

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2092]
## Question

As a contributor to Rector, I happen to run locally `composer complete-check`, which ends with updating the files in `docs`. However, sometimes the updates in there do not match the feature I'm working on. Which begs the question : when should, and on which branch, should a contributor update the docs ? Or is it something you do when creating a new release only ?

**Comment by TomasVotruba** [comment]
It's rather random, since it's not in CI and depends on human action.

Any automated improvement are welcomed
