### ISSUE TITLE
Question: Running rector on windows returns Cygwin using Windows php, so the path must be translated

### ISSUE THREAD

**Issue by surfmuggle** [rectorphp/rector#2117]
## Question

I try to use rector on windows and did install rector using `PS C:\Dev\PHP\ResourceSpace_9_0_13357> composer require rector/rector --dev` this did run successfully without any errors.  The first lines are

```
Using version ^0.5.13 for rector/rector
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 44 installs, 0 updates, 0 removals
```
After the installation i did try to start a code-quality assessment by typing `C:\Dev\PHP\ResourceSpace_9_0_13357>php vendor/bin/rector process --level code-quality` but i assume that it did not work because of the output it gave (see below). 

```
C:\Dev\PHP\ResourceSpace_9_0_13357>php vendor/bin/rector process --level code-quality

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../rector/rector/bin" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/rector" "$@"
```

What can i do to use rector on windows to execute a code quality check? 
Did i misconfigure my php or rector installation? 
Thanks

**Comment by TomasVotruba** [comment]
Hi, I don't use Windows at all so I have no idea what is the problem.
Not sure what is the input and what is the output. Try `--debug` option as well to get more info.

It should work the same way e.g. PHP_CodeSniffer works.

**Comment by surfmuggle** [comment]
On my box Cygwin was not installed. I fixed it and updated [how-to-run-rector-on-windows](https://stackoverflow.com/questions/58253643/). I now get these errors

```
$ pwd
/cygdrive/c/Dev/PHP/ResourceSpace_9_0_13357/vendor/rector/bin

me@box /cygdrive/c/Dev/PHP/ResourceSpace_9_0_13357/vendor/rector/bin
$ rector process --level code-quality --dry-run
-bash: rector: command not found

me@box /cygdrive/c/Dev/PHP/ResourceSpace_9_0_13357/vendor/rector/bin
$ process --level code-quality --dry-run
-bash: process: command not found
```

Do you know if others have used rector under windows server 2016?

**Comment by BoGnY** [comment]
@surfmuggle you have to run the `.bat` executable in vendor bin-dir (don't require cygwin):
`C:\Dev\PHP\ResourceSpace_9_0_13357>php vendor/bin/rector.bat process --level code-quality`

**Comment by TomasVotruba** [comment]
Closing as answered

**Comment by phpfui** [comment]
The batch file in vendor\bin just calls the correct file in the composer installed source.  So just run that directly.  For example:

php vendor\rector\rector\bin\rector process src --set mysql-to-mysqli

Works great from a plain Windows 10 command shell with PHP 7.4 properly pathed
