### ISSUE TITLE
VarInlineAnnotationToAssertRector will almost always end up with failed assertions.

### ISSUE THREAD

**Issue by noximo** [rectorphp/rector#2118]
VarInlineAnnotationToAssertRector currently replace @var phpdoc with assertion on the same line. This will lead to a failed assertion because variable is usually defined on the line below and is thus undefined at the time of assert. 

Therefore line containing the variable definiton and assertion should be swapped. 

Also code sample in this rector is invalid - there's a method call on an undefined variable that would result in error.

**Comment by TomasVotruba** [comment]
I'm not sure I understand the issue. Could you rephase in simple words?

**Comment by noximo** [comment]
I'll try.

```php
/** @var int $newVariable */
$newVariable = $object->method();
```
turns into 
```php
assert(is_int($newVariable); //will assert to false since $newVariable doesn't exist yet 
$newVariable = $object->method();
```
but should turn into 
```php
$newVariable = $object->method();
assert(is_int($newVariable); //will assert to true since the type/content of the $newVariable is known at this point during execution (assuming the method() really returns int in this case)
```

This is a problem in PHPClean plugin for PHPStorm as well. PHPStorm complains about using phpdoc instead of assert but after fixing it with quick action it will complain about undefined variable.

**Comment by TomasVotruba** [comment]
I see, that makes sense :+1: 

Could you add it as a test fixture to the test via pull-request?
https://github.com/rectorphp/rector/tree/master/packages/StrictCodeQuality/tests/Rector/Stmt/VarInlineAnnotationToAssertRector/Fixture

Then I'll fix it to make test pass
