### ISSUE TITLE
  The "--level" option does not exist.

### ISSUE THREAD

**Issue by AntonioCS** [rectorphp/rector#2126]
After fighting innumerous issues to get this package to install on my project, from dependency issues, php language issues etc. I get it installed and I run the following command:
```
vendor/bin/rector process app --level php72
```
Only to get this: 
```
Rector v0.5.13

  The "--level" option does not exist.
```
I mean... you have this on your `README.md` in the little gif, why is this not working? You also have other blog posts, from the author, where this `--level` is used like this one: https://www.tomasvotruba.cz/blog/2019/02/28/how-to-upgrade-symfony-2-8-to-3-4/
This post is from February 28th, why did this change that much??

Can someone please update the `README.md` and maybe the author can put a little notice in his own blog posts?

**Comment by TomasVotruba** [comment]
Hi, 

thank for spottingthis problem.

These posts are not part of Rector repository. This is the correct repository to address: https://github.com/tomasVotruba/tomasvotruba.cz/

Also, you can send PR to update the posts right away

**Comment by AntonioCS** [comment]
Sure, maybe not that post but what about the gif in the `README.md`?

**Comment by TomasVotruba** [comment]
That needs to be updated too.

**Comment by tssajo** [comment]
@TomasVotruba Hello, I read your answer here: https://stackoverflow.com/questions/17986647/upgrade-php-mysql-code-to-use-mysqli-instead#
Your answer titled "**2019+ Answer**" and I try to do what you said:
`rector p . --level mysql-to-mysqli`
but I also get the error message:
`The "--level" option does not exist.`
Any suggestion on how to overcome this problem?
Thanks in advance!

**Comment by TomasVotruba** [comment]
It's been `--set` for couple of few months now.

Thanks for the hint, I'll update the SO post

**Comment by tssajo** [comment]
@TomasVotruba Yes, I just figured that out on my own. Thanks for replying!

Now I run into another issue, I get this message a lot for different PHP files in the project:
```
[ERROR] Could not process "some/php/file.php" file, due to:                                                     
         "File /full/path/to/some/php/file.php was not preparsed, so it cannot be printed.                
         Check "Rector\Core\Application\FileProcessor::parseFileInfoToLocalCache()" method.".                           
```
Can you please tell me why do I get many of these messages?
Thanks!

**Comment by TomasVotruba** [comment]
What command do you run?

**Comment by tssajo** [comment]
The one I mentioned above:
`rector p . --level mysql-to-mysqli`
Maybe the problem is that I installed rector globally on my PC?

**Comment by TomasVotruba** [comment]
1) Rector doesn't work installed globaly. Either use `composer require rector/rector --dev` or [prefixed version](https://getrector.org/blog/2020/01/20/how-to-install-rector-despite-composer-conflicts)

2) Always run these tools on specific directory, not global `.`. That leads to many problems with vendor loading, performance etc. Always use the minimal scope possible, moreover when using the tool for the first time.

```bash
vendor/bin/rector process /src --set mysql-to-mysqli
```

Even better:

```bash
vendor/bin/rector process /src/Repository --set mysql-to-mysqli
```

**Comment by tssajo** [comment]
@TomasVotruba OK, I'll try what you suggested, thanks!

**Comment by mehov** [comment]
Related: rectorphp/rector/issues/1905
