### ISSUE TITLE
[PHPUnit 8] Add rule to cope with PHPUnit deprecating assertArraySubset

### ISSUE THREAD

**Issue by DaveLiddament** [rectorphp/rector#2138]
PHPUnit has [deprecated](https://github.com/sebastianbergmann/phpunit/issues/3494) in v8. It will be removed in v9. It seems like a lot of people, myself included, use this assertion. 

The [solution proposed](https://github.com/sebastianbergmann/phpunit/issues/3494#issuecomment-480283612) is to use [dms/phpunit-arraysubset-asserts](https://github.com/rdohms/phpunit-arraysubset-asserts)  

NOTE: Composer needs to be run before this rule will work:
```sh
composer require --dev dms/phpunit-arraysubset-asserts
``` 

## Diff 

```diff
  <?php
  declare(strict_types=1);

  namespace Acme\Tests;

+ use DMS\PHPUnitExtensions\ArraySubset\Assert as AssertArraySubset;
  use PHPUnit\Framework\TestCase;


  final class AssertTest extends TestCase
  {
   
    public function testPreviouslyStaticCall(): void
    {
-    self::assertArraySubset(['bar' => 0], ['bar' => '0'], true);
+    AssertArraySubset::assertArraySubset(['bar' => 0], ['bar' => '0'], true);
    }

    public function testPreviouslyCalledWithThis(): void
    {
-    $this->assertArraySubset(['bar' => 0], ['bar' => '0'], true);
+    AssertArraySubset::assertArraySubset(['bar' => 0], ['bar' => '0'], true);
    }
 }
```

**Comment by TomasVotruba** [comment]
Well, default rules don't need any composer/CLI intervention, so running this would break rules.

Instead we might add it to `phpunit80-dms` with warning message, it needs to install particula package.

**Comment by DaveLiddament** [comment]
@TomasVotruba are you happy for me to have a go at writing this rule?

**Comment by TomasVotruba** [comment]
Where is the PR? :O

**Comment by TomasVotruba** [comment]
Any update? It needs to be solve soon as possible
