### ISSUE TITLE
[Proposal][PHPUnit] AssertTrueFalseComparisonToSpecificMethodRector

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#216]
There are a lot of comparisons that could be refactor to `PHPUnit` assertion method:

Current | Better
-- | -
`assertTrue($foo === $bar)` | `assertSame($bar, $foo)`
`assertTrue($foo <> $bar)` | `assertNotEquals($bar, $foo)`
`assertTrue($foo >= $bar)` | `assertGreaterThanOrEqual($bar, $foo)`

@TomasVotruba What do you think? Can I propose this `Rector`? :innocent: 

Nikita's `PHP-Parser` [does handle it](https://github.com/nikic/PHP-Parser/tree/master/lib/PhpParser/Node/Expr/BinaryOp) :+1:

**Comment by TomasVotruba** [comment]
Sure, that make sense :mrs_claus:

**Comment by TomasVotruba** [comment]
Feel free to do these in PR from the start, no need to create issue for it.

**Comment by carusogabriel** [comment]
I'm just finishing to work on #217, I'll start this one!

**Comment by TomasVotruba** [comment]
Take your time. Better 1 finished PR than 5 opened issues :1st_place_medal:
