### ISSUE TITLE
[PhpDoc] Add option to change just single doc annotation - DocRector

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#2161]
We have now 2 way to refactor application code:

- `Rector\Contract\Rector\PhpRectorInterface` - change specific PHP nodes
- `Rector\FileSystemRector\Contract\FileSystemRectorInterface` - change around whole file

Recently, there is more frequest focus on doc annotations as well. E.g.:
- change `@Template` to `@Route`
- complete `@var` type for `@ManyToMany`
- change `@OneToMany` nullable to true etc.

Saying that, it might be useful to introduce `PhpDocRectorInterface`, which would subscribe to instances of `PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTagValueNode`, e.g. one of following:

![peek](https://user-images.githubusercontent.com/924196/66767319-681e9400-eeb0-11e9-8c2c-e5d2bbd3aaad.gif)

That would make change of these tags simpler with same logic that is used to change PHP code or whole file.

```php
interface PhpDocRectorInterface extends RectorInterface
{
    /**
     * Subscribe to instances of PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTagValueNode
     * @return string[]
     */
	public function getNodeTypes(): array;

	public function refactor(PhpDocTagValueNode $node);
}
```

**Comment by TomasVotruba** [comment]
What do you think folks?

**Comment by TomasVotruba** [comment]
What do you think folks?

@gnutix @keulinho @sashabeton @HypeMC @markstory @jeroensmit @scheb @jeroenherczeg

**Comment by keulinho** [comment]
Looks good to me :+1:

**Comment by markstory** [comment]
Seems reasonable to me as well.

**Comment by scheb** [comment]
If you see a common pattern and expect more of these rectors in the future, it makes sense to generalize 👍

**Comment by TomasVotruba** [comment]
With the hindsight, the theory looks nice.
Waits on practical applience though.

Closing as better scope for coding standards. Let's stay with PHP code for now
