### ISSUE TITLE
[CodeQuality] Add merge of 2 arrays of unnested items to array

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#2170]
```diff
-$nodes = array_merge([$declareNode], [$node]);
+$nodes = [$declareNode, $node];
```

**Comment by rvanlaak** [comment]
This seems to cause `array_merge` to get replaced by splat operators although these issues have strings as keys, causing the following error:

> Cannot unpack array with string keys

e.g.

```php
$res = array_merge($array1, $array2);
```

results in 

```php
$res = [...$array1, ...$array2];
```

**Comment by TomasVotruba** [comment]
What do you think would be the best solution for this rule?

**Comment by rvanlaak** [comment]
Would it be possible to more safely check whether the input arrays could possibly have string keys? If not, maybe mark the replacement as risky?

**Comment by TomasVotruba** [comment]
Could you provide test case of arrays that should be merged and arrays that should be skipped?

Better if based on real data, so we can make rule as close to reality as possible.

**Comment by rvanlaak** [comment]
I'll try diving into a reproduction scenario a bit further, because just found out that `\Rector\Php74\Tests\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector\Fixture\SkipStringKeys` actually is there to verify string keys should get skipped.

**Comment by TomasVotruba** [comment]
It might be not good enough.
How does your minimal failing code look like?

**Comment by rvanlaak** [comment]
@TomasVotruba running `make upgrade-php` will show the change: https://github.com/rvanlaak/rector-tests

**Comment by TomasVotruba** [comment]
Could you put it into minimal code that doesn't need any dependency?

And link it here: https://getrector.org/demo

**Comment by rvanlaak** [comment]
Thank you for that demo link, that's useful!

https://getrector.org/demo/c1c1549f-22df-4237-95e1-dd4cdda566ee
