### ISSUE TITLE
Internal fatal error on process

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#2178]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | latest master          |
| PHP version    | PHP 7.3 |

## Current Behavior 

```
vendor/bin/rector process /.../src/ --set=cakephp36 --dry-run -a /.../vendor/autoload.php
```

> Fatal error:  Declaration of PhpParser\Node\Name::getSubNodeNames() must be compatible with PhpParser\Node::getSubNodeNames(): array in /...vendor/nikic/php-parser/lib/PhpParser/Node/Name.php on line 196

## Expected Behavior

No exceptions.

**Comment by TomasVotruba** [comment]
Failing php code is needed

**Comment by dereuromark** [comment]
This happens with *any* code basically, no matter what class/file and project.
It is also quite obvious once you look into the PhpParser source code. The IDE already blows up red once you open those files, as they inheritance here ob classes just cannot work by design in that version that got downloaded.
Even if I manually fix the missing return typehint on the child class, then other follow up errors appear:

> Fatal error:  Class PhpParser\Node\Name contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PhpParser\Node::getType) in /.../vendor/nikic/php-parser/lib/PhpParser/Node/Name.php on line 196

According to composer lock "v4.2.4", is the version downloaded for "nikic/php-parser".
Seems quite buggy that one.

**Comment by TomasVotruba** [comment]
Duplicate source of fail in:
https://github.com/rectorphp/rector/issues/177

**Comment by dereuromark** [comment]
I dont get this, if I install rector, shoudnt it require the correct versions of its dependencies on its own?
Also master seems broken here:

    "rector/rector": "dev-master as 0.5"

has the same issue.

**Comment by dereuromark** [comment]
with autoloader file though, shouldnt that work?
Ah, I see now, that conflicts with the autoloaded files, if prefixing is not used. Thank you.
Maybe this can be caught with a more meaningful error instead?
Looking into the autoloader and comparing with current version of root rector?

**Comment by TomasVotruba** [comment]
I personally never came across these errors.
If you find a way how to add such error, I'd be open to PR :+1:
