### ISSUE TITLE
From self-executing code to at function execution code

### ISSUE THREAD

**Issue by adaamz** [rectorphp/rector#2179]
# Diff
```diff
<?php
-include("config.php");
-session_start();
-$date =date('Y-m-d h:ia' );
-$day =  date('l');
-$Date = $day . ', ' . $date;
-if( $num_row == 1) {
-    $_SESSION['id']=$row['admin_id'];
-mysql_query("insert into admin_log (username,login_date,admin_id) values('$username','$Date',".$row['admin_id'].")")or die(mysql_error());
-}
- ?>
+$code = function() {
+    include("config.php");
+    session_start();
+    $date =date('Y-m-d h:ia' );
+    $day =  date('l');
+    $Date = $day . ', ' . $date;
+    if( $num_row == 1) {
+        $_SESSION['id']=$row['admin_id'];
+    mysql_query("insert into admin_log (username,login_date,admin_id) values('$username','$Date',".$row['admin_id'].")")or die(mysql_error());
+    }
+};

+run($code); // or maybe $code(), should be configurable
```

probably first step for https://github.com/rectorphp/rector/issues/1115

Goal of this FR is to have code wrapped inside function/class so we can upgrade/analyse code with some static analyser like rector/phpstan/... without actually executing it.

**Comment by TomasVotruba** [comment]
We depend on PHPStan, so if it can't handle it, neither can Rector

**Comment by adaamz** [comment]
But I created feature request in rector - so I want to create rector rule that will convert self-executing code to some function/class wrapped code.

I don't get your comment.

**Comment by TomasVotruba** [comment]
It's egg vs. chicken. This code gets executed now, so it will probably break the migration with fatal error.

You need to wrap it first, so PHPStan or Rector can work with it. But you want to use Rector to do that...

**Comment by adaamz** [comment]
Now I get it.

Do you have some idea how to automatize that?

**Comment by TomasVotruba** [comment]
Not really. It would require much research and experimenting to find approach to this, so it will have to wait for a paid project where the need will be enough to sponsor it.
