### ISSUE TITLE
error docker run: Nette\FileNotFoundException missing config.neon

### ISSUE THREAD

**Issue by tolry** [rectorphp/rector#2185]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | docker `rector/rector:latest` |
| PHP version    | docker |
| Full Command   | any `docker run -v $(pwd):/project rector/rector:latest --version` | 

## Current Behaviour 

```
Fatal error: Uncaught Nette\FileNotFoundException: File '/rector/vendor/symplify/phpstan-extensions/config/config.neon' is missing or is not readable. in /rector/vendor/nette/di/src/DI/Config/Loader.php:43
Stack trace:
#0 /rector/vendor/nette/di/src/DI/Config/Loader.php(60): Nette\DI\Config\Loader->load('/rector/vendor/...', false)
#1 /rector/vendor/nette/di/src/DI/Compiler.php(127): Nette\DI\Config\Loader->load('/rector/phpstan...', false)
#2 /rector/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(258): Nette\DI\Compiler->loadConfig('/rector/phpstan...', Object(Nette\DI\Config\Loader))
#3 /rector/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#4 /rector/vendor/nette/di/src/DI/ContainerLoader.php(79): Nette\DI\ContainerLoader->generate('Container_48b06...', Array)
#5 /rector/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile('Container_48b06...', Array)
#6 /rector/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(2 in /rector/vendor/nette/di/src/DI/Config/Loader.php on line 43

```

## Minimal PHP Code Causing Issue

No php code needed. Run using e.g. `docker run -v $(pwd):/project rector/rector:latest --version` and make sure to remove the local docker image before to make sure it's freshly downloaded.

Maybe docker image build is broken somehow, not copying the needed config file?

**Comment by JanMikes** [comment]
@TomasVotruba this excaption is caused by `symplify/phpstan-extensions` composer dependency is in `require-dev` and rector docker image is built without dev dependencies.

Im now investigating why is this config being loaded.

**Comment by JanMikes** [comment]
Repro steps without docker:  `composer update --no-dev && bin/rector`

**Comment by JanMikes** [comment]
Overall, this is not issue with docker, but problem is running some rector commands without dev dependencies.

**Comment by tolry** [comment]
yes, sure - depending on dev-dependencies for non-dev code is definitely ... problematic :wink: thanks for investigating

**Comment by Danack** [comment]
@JanMikes are there any plans to provide phar file downloads for rector releases?

It's not totally unreasonably for people to run rector in `--no-dev` environments, but at the same time, moving more dependencies to require, rather than require-dev, makes projects a little bigger to deploy.

Using rector from a phar release would avoid that, and probably avoid future dependencies issues.

**Comment by JanMikes** [comment]
@Danack in future definitely yes. @TomasVotruba had already have few tries but it showed up this task is very difficult to do and we will be trying again during long cold winter nights 😄.

@tolry this problem is a bit deeper and we are still investigating how we can fix this effectively.

**Comment by tolry** [comment]
@JanMikes thanks for the feedback, there is no hurry for me, since I can 'simply' run rector with another version to get it running for now

**Comment by JanMikes** [comment]
@TomasVotruba is there a way how to ignore (not load) phpstan.neon when running `bin/rector` command?

I have tested 2 workarounds and both worked for me:
- Remove phpstan.neon in  docker 
- Install rector in docker with dev dependencies
