### ISSUE TITLE
Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector should only apply to methods defined in a `@dataProvider` annotation.

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2187]
I've added `config/set/phpunit/phpunit-yield-data-provider.yaml` to my `imports`, which does the following : 

```yaml
services:
    Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector:
        PHPUnit\Framework\TestCase:
            - '#(provide|dataProvider)*#'
```

I would have assumed that this would apply only on methods targeted by a dataProvider, but it's not. I had a `private function getSomeData(): array;` method in a test that got changed by the Rector (furthermore, data providers in PHPUnit are **always** `public`!).

Is there something I misunderstood about the intended behavior of this config file ? Or should I try to add a broken test ?

**Comment by TomasVotruba** [comment]
Broken test would be great :+1:

**Comment by gnutix** [comment]
I've had a look at the existing fixtures (as I would have thought this issue would have been caught in there already), and I have to say that they are very obscure to me. I don't really understand what test cases they cover and how/why they are structured the way they are.

**Comment by TomasVotruba** [comment]
What file exactly do we talk about?

**Comment by TomasVotruba** [comment]
No need to explore old test cases, as they all passes.
We need your failing test case, so I'd just add your failing one.

**Comment by gnutix** [comment]
There you go : https://github.com/rectorphp/rector/pull/2273
