### ISSUE TITLE
PHP's current()/reset() may return false

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2201]
I encountered a bug in the following code : 

```php
<?php
class MediaManager
{
    public function find(int $id): ?Media
    {
        $search = new MediaSearch();
        $search->setId($id);

        return current($this->mediaRepository->search($search));
    }
}

interface MediaRepository
{
    public function search(MediaSearch $search): array;
}
```

If `$this->mediaRepository->search($search)` returns an empty array `[]` (because the provided `int $id` does not exist), `current()` will return `false` and PHP will error because `find` should return a `Media` or `null`, not `false`. I refactored the code as such : 

```php
<?php
class MediaManager
{
    public function find(int $id): ?Media
    {
        $search = new MediaSearch();
        $search->setId($id);

        $medias = $this->mediaRepository->search($search);
        $media = current($medias);
        if (!$media) {
            return null;
        }

        return $media;
    }
}
```

And this little story left me wondering if it would be better to add some inspection in PHPStan, or some Rector, or what... ? What do you think ? There's probably other PHP methods that might be "misused" in such a way, so I don't really know how to tackle this... (but I know I would love to have such a tool finding out these bugs for me ;) )

**Comment by TomasVotruba** [comment]
Not sure what is your question/goal here. Could you maybe put it in few words and code sample?

**Comment by gnutix** [comment]
Well, I had this issue which I think could be caught by a static analysis tool (checking if we return the result of a call to PHP's `reset` / `current` (and maybe others?) functions and the method is not supporting to return `false`. And I was wondering if that would be a better suit for Rector or PhpStan ?

**Comment by TomasVotruba** [comment]
Well:

* checking = PHPStan
* changing = Rector

**Comment by gnutix** [comment]
I guess it's more PHPStan, 'cause I'm not sure if it would be wise to refactor this kind of "potentially buggy" code automatically. Thanks for helping me sorting it out. :)

**Comment by gnutix** [comment]
Follow-up: https://github.com/phpstan/phpstan/issues/2539
