### ISSUE TITLE
Config Files (# rector.yml) Can Not be Loaded

### ISSUE THREAD

**Issue by ktomk** [rectorphp/rector#2204]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | 0.5.x-dev@5757e86 (master this morning)          |
| PHP version    | PHP 7.3.10                               |
| Full Command   | Various, see how to reproduce  | 

## Current Behaviour 

Passing a (temporary) path for a rector.yml configuraiton file via the `-c` / `--config=` option refuses
rector to use that configuration despite the file exists or the path is at least perfectly fine readable (and contains valid configuraiton data).

The Rectory utility requires the `.yml` suffix on the path which is quite unexpected as the option is documented to only need a file path as an argument. But not even perfectly standard files do work unless their name follows the explicit scheme to end with `.y[a]?ml`.

Further this defect blocks to read from paths that generally work on the system (e.g. `/dev/fd/63`) but are supported in PHP only via the `php://fd/63` wrapper (ref [PHP Bug #53465](https://bugs.php.net/bug.php?id=53465)), but the overall config loading layer refuses to operate on (existing) files and also on perfectly readable paths PHP is known to be capable of to deal with.

## How To Reproduce

~~~
$ <<RECTOR_YML | tee /tmp/the-file
# rector.yaml
parameters:
    exclude_paths:
        - 'tests/php-version-compat/**'
RECTOR_YML
~~~

~~~
$ bin/rector -c /tmp/the-file
~~~

To demonstrate the cause of issue being the suffix of the file:

~~~
$ cp /tmp/the-file{,.yml}
$ bin/rector -c /tmp/the-file.yml # works
~~~

Not being able to read from `/dev/fd/...` in specific is cumbersome as it is used by *process substitution* (bash, ksh, zsh etc.) as such paths are used in the implementation.

To reproduce:

~~~
bin/rector -c  <( <<EOD :
# rector.yaml
parameters:
    exclude_paths:
        - 'tests/php-version-compat/**'
EOD
  )
~~~

**Comment by TomasVotruba** [comment]
How would you fix it?

**Comment by ktomk** [comment]
I have some workaround for the process substitution but it's pretty hacky.

A fix I normally have for the PHP handling of the file handles is:

~~~
        /* @link https://bugs.php.net/bug.php?id=53465 */
        $path = preg_replace('(^/(?:proc/self|dev)/(fd/\d+))', 'php://\1', $path);
~~~

and it works well for me. However in case of rector this needs replacing the original resource with a temporary file which has the `.yml` suffix as loader, resolver and then the real file reader all do checks with `file_exists` which does not work for all stream wrappers. And these objects are across multiple components (IIRC rector itself (but very little), the library that wraps stuff to make it "easy", the symfony loader and then also the symfony yaml component.

Symfony components are normally very slow for such deeper fixes in the command line world, so I would give a shit there.

The component rector uses in the middle, I don't know.

For the parts directly in rector itself would perhaps be best for a viable fix.

So this would also depend a lot on feedback from the rector project itself as if I understand this right, the configuration file is also dependency injection (symfony) so it relies on these base components for it's core functionality.

So the easiest fix from my first look would be to pre-process the argument and turn device files into temporary files with the .yml extension and other files if not w/ .yml extension also into temporary files with the .yml extension. This is normally in ca. ten lines of code for the path / temp-file handling but then the argument needs to be exchanged and a good junction point to insert this would be needed.

The moment the (injected) file path ends w/ .yml and exists, this issue is gone.

**Comment by TomasVotruba** [comment]
I wonder how other project appraoch this of it should be handled at all.

**Comment by ktomk** [comment]
Depends a bit how inter-operable rector should become. Normally PHP supports stream wrapper therefore the one-liner above is normally sufficient in arguments parsing to handle process substitution in PHP utilities.

**Comment by TomasVotruba** [comment]
Btw, what do you need this for?

**Comment by ktomk** [comment]
Use of rector in the shell. Some parameters can only be set via the configuration file (`exclude_*` in the concrete case). Did process substitution for it, but it didn't work. Then I tried to work-around w/ a temp file and then discovered the requirements on the suffix.

It's basically giving it a test-run on a project and also learning about `rector usage`. The bug is not a show stopper for me, but I also didn't want to have this unnoticed while I currently fiddle with it. Please keep in mind that I'm new to rector.

**Comment by TomasVotruba** [comment]
I'll recommend you to use config as in any other Symfony app, as it is used internally and I don't think Symfony is ready for it.

Create your own `rector.yaml` in root of the project and write needed `exclude_*` there.

**Comment by ktomk** [comment]
Just to add: It does not need a `rector.yml`, any `*.yml` will do it.

**Comment by TomasVotruba** [comment]
Sure, it's just loaded by default
