### ISSUE TITLE
Config File-Path Injection by Not Passing a Config File Option Argument

### ISSUE THREAD

**Issue by ktomk** [rectorphp/rector#2205]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | 0.5.x-dev@5757e86 (master this morning)          |
| PHP version    | PHP 7.3.10                               |
| Full Command   | `bin/rector -c`  | 

## Current Behaviour 

When invoking rector with an empty `-c` option, the rector utility is looking for the config file in the path "`--ansi`" (and fatals w/ an uncaught exception).

For this case Tom suspects a flaw of the utilities self-configuration that is adding command line options at wrong places.

**Comment by TomasVotruba** [comment]
What behavior would you expect?

**Comment by ktomk** [comment]
Error is fine (maybe a bit verbose) but seeing some parameter injected there that never has been entered by the user looks fishy.

**Comment by TomasVotruba** [comment]
What would you suggest, then?

**Comment by ktomk** [comment]
I have no clue why it has `--ansi` in there honestly. Do you know something about it? It looks kinda leaking.

**Comment by TomasVotruba** [comment]
To show colors in terminals while using composer scripts

**Comment by TomasVotruba** [comment]
Empty `-c` option should fail, as the value is required. That's invalid behavior for some reason

**Comment by TomasVotruba** [comment]
Cannot reproduce:

![image](https://user-images.githubusercontent.com/924196/67723652-f9c3f080-f9dc-11e9-8d08-0dbcd7504951.png)


Please send PR with failing test case in Travis CI to show the error

**Comment by ktomk** [comment]
Hmm, I have this on master right now:

~~~
$ git describe --tags --always --dirty && bin/rector -c 
v0.5.19-20-ge72eb34a4
PHP Fatal error:  Uncaught Symplify\PackageBuilder\Exception\Configuration\FileNotFoundException: File "/home/user/develop/rector/--ansi" not found in "--ansi". in /home/user/develop/rector/vendor/symplify/package-builder/src/Configuration/ConfigFileFinder.php:26
Stack trace:
#0 /home/user/develop/rector/bin/container.php(28): Symplify\PackageBuilder\Configuration\ConfigFileFinder::detectFromInput('rector', Object(Symfony\Component\Console\Input\ArgvInput))
#1 /home/user/develop/rector/bin/rector(23): require_once('/home/use/devel...')
#2 {main}
  thrown in /home/user/develop/rector/vendor/symplify/package-builder/src/Configuration/ConfigFileFinder.php on line 26
~~~

**Comment by ktomk** [comment]
Found out more: This seems to only be an issue if xdebug extension is loaded.

I can reproduce your output by:

~~~
$ php -n -d extension=tokenizer.so -d extension=json.so -d extension=iconv.so -f bin/rector -- -c

                                           
  The "--config" option requires a value.  
                                           

list [--raw] [--format FORMAT] [-h|--help] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-c|--config CONFIG] [-s|--set SET] [--debug] [-d|--working-dir WORKING-DIR] [--] [<command> [<namespace>]]
~~~

The `--ansi` part maybe then comes from: https://github.com/rectorphp/rector/blob/master/bin/rector#L18

**Comment by ktomk** [comment]
@TomasVotruba: Failing https://travis-ci.org/rectorphp/rector/jobs/604199897#L417 confirms xdebug / XdebugHandler being involved.

**Comment by ktomk** [comment]
@TomasVotruba Fix for me would be to not pass the string "`--ansi`" as second parameter when creating the XdebugHelper. Just let me know if you would consider this a fix beforehand.

**Comment by TomasVotruba** [comment]
Thatmicbf

**Comment by TomasVotruba** [comment]
How this one would work?
https://github.com/phpstan/phpstan/commit/d437e70f929bf508569e3c0f55ecfee7f977bd01

**Comment by ktomk** [comment]
What means does not work on Mac?

If I remove the second parameter there won't be colors *unless* `recotor` utility is invoked with `--ansi` if xdebug is active.

**Comment by TomasVotruba** [comment]
Not sure here

**Comment by ktomk** [comment]
So would it be acceptable if there are no colors if not explicitly asked for it? My resolution suggestion can cause this.

**Comment by TomasVotruba** [comment]
Let's give it a try
