### ISSUE TITLE
Proper docs and tutorials?

### ISSUE THREAD

**Issue by eugenegorelikov** [rectorphp/rector#2209]
Hi, the things has a big potential, but proper documentation is lacking on all official repos. Considering the amount of components used in the Rector, the provided examples and explanations are way too little. Are there better examples and explanations available anywhere?

Thank you!

**Comment by TomasVotruba** [comment]
Hey,

as the docs would be just copy-pasting rules and methods from `AbstractRector`, it would become quickly outdated.

Saying that, there are some other resources to learn from:

* many posts on my blog: https://www.google.com/search?sitesearch=tomasvotruba.cz&q=rector
* overview of all Rector rules: https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md
* overview of all php-parser AST nodes: https://github.com/rectorphp/rector/blob/master/docs/NodesOverview.md

**Comment by eugenegorelikov** [comment]
Thank you for the information. On a more specific note, which folder should the `AbstractRector` extensions be placed? I am consistently getting the error that my class is not found.

**Comment by TomasVotruba** [comment]
Any place autoloaded by composer

**Comment by eugenegorelikov** [comment]
I suppose i'm missing a more basic thing here. Oh well, thank you for looking into this!

**Comment by TomasVotruba** [comment]
There is rule tutorial in readme I suppose you've read but didn't work out for you:
https://github.com/rectorphp/rector#3-steps-to-create-your-own-rector

Do you have some tips, how could we make it better?
