### ISSUE TITLE
'Rector\Contract\Bridge\EntityForDoctrineRepositoryProviderInterface' not found

### ISSUE THREAD

**Issue by fdbatista** [rectorphp/rector#2212]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.5.19        |
| PHP version    | PHP 7.3.10
| Full Command   | vendor/bin/rector process /app --dry-run --config config/packages/rector.yaml | 

## Current Behaviour 
```bash
PHP Fatal error:  Interface 'Rector\Contract\Bridge\EntityForDoctrineRepositoryProviderInterface' not found in /home/user/apps/lampstack-7.3.10-0/apache2/htdocs/app/src/Rector/EntityForDoctrineRepositoryProvider.php on line 7
```
## Expected Behaviour

Interface EntityForDoctrineRepositoryProviderInterface should be available, but not even that namespace is.

**Comment by TomasVotruba** [comment]
What's content of `config/packages/rector.yaml`?

**Comment by fdbatista** [comment]
> What's content of `config/packages/rector.yaml`?

<code>
services:
Rector\Rector\Architecture\RepositoryAsService\ReplaceParentRepositoryCallsByRepositoryPropertyRector: ~
  Rector\Rector\Architecture\RepositoryAsService\MoveRepositoryFromParentToConstructorRector: ~
  App\Rector\EntityForDoctrineRepositoryProvider: ~
</code>

**Comment by fdbatista** [comment]
Content of scr/Rector/EntityForDoctrineRepositoryProvider is:

<?php declare(strict_types=1);

namespace App\Rector;

use Rector\Contract\Bridge\EntityForDoctrineRepositoryProviderInterface;

final class EntityForDoctrineRepositoryProvider implements EntityForDoctrineRepositoryProviderInterface
{
    /**
     * @var string[]
     */
    private $map = [
        'App\Repository\PostRepository' => 'App\Entity\Post',
        'App\Repository\ProductRepository' => 'App\Entity\Product',
    ];

    public function provideEntityForRepository(string $name): ?string
    {
        return $this->map[$name] ?? null;
    }
}

This is the class that cannot find the Interface to implement it.

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/TomasVotruba/tomasvotruba.cz/pull/852

Renamed here: https://github.com/rectorphp/rector/commit/cd03b803d606e2f185d0853bc9365546b69305ac
