### ISSUE TITLE
Improved documentation in README.md for running a single rule

### ISSUE THREAD

**Issue by DaveLiddament** [rectorphp/rector#2213]
From the help on `process` command it looks like you can run a single rule...
```
vendor/bin/rector help process
```

Output includes...
```
  -r, --rule=RULE                      Run only this single rule
```

Running this:
```
vendor/bin/rector process --rule "Rector\\CodingStyle\\Rector\\Namespace_\\ImportFullyQualifiedNamesRector" -c rector.yaml tests/
```
Produces the output:
```
vendor/bin/rector process --rule "Rector\\CodingStyle\\Rector\\Namespace_\\ImportFullyQualifiedNamesRector" -c rector.yaml tests/ --debug
Rector v0.5.19
Config file: /vagrant/code/huntEngine/rector.yaml

PHP Fatal error:  Uncaught Rector\Exception\NoRectorsLoadedException: We need some rectors to run:
* register them in rector.yaml under "services:"
* use "--set <set>"
* or use "--config <file>.yaml" in /vagrant/code/huntEngine/vendor/rector/rector/src/Guard/RectorGuard.php:41
Stack trace:
#0 /vagrant/code/huntEngine/vendor/rector/rector/src/Console/Command/ProcessCommand.php(160): Rector\Guard\RectorGuard->ensureSomeRectorsAreRegistered()
#1 /vagrant/code/huntEngine/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Rector\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /vagrant/code/huntEngine/vendor/rector/rector/src/Console/Command/AbstractCommand.php(34): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /vagrant/code/huntEngine/vendor/symfony/symfony/src/Symfony/Component/Console/Applicat in /vagrant/code/huntEngine/vendor/rector/rector/src/Guard/RectorGuard.php on line 41
```

The error message does imply that either a `set` must be selected or the rule must be specified in config. If that is the case then what does the `-r` flag mean?

**Comment by TomasVotruba** [comment]
At the moment the `--rule` basically picks one rule from already registered ones. It's helper option to test just one rule from whole sets. `r` is just shortcut

Not sure if it should register it, because there might be missing configuration and race condition for container vs config

Saying that, this rule must be already registered

**Comment by TomasVotruba** [comment]
How could we improve  current behavior so it's clear that rule must be registered?

**Comment by ktomk** [comment]
Just an idea: Allow to provide the rule incl. configuration as JSON on the cmd-line. IIRC this is how PHP-CS-Fixer allows to "pick" rules via CLI options. No idea though if this is applicable for `rector`.

**Comment by TomasVotruba** [comment]
That's rather crazy. I mean keep current way, just add informative exceptoin.

**Comment by ktomk** [comment]
Okay, if that is crazy. Just another idea: Before actually running into an error based on the name of option, maybe making the option name more specific like pick / pick-rule / pick-single-rule / pick-single-configured-rule. So it's more self-speaking and in case it triggers (any) exception, it's perhaps already better understood.

**Comment by TomasVotruba** [comment]
Closing as answered, PR to improve docs or error is welcomed.
