### ISSUE TITLE
rector.yml docs

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#2228]
is there documentation around which yml-format/keys are supported in the `rector.yml` 

I can see lots of small snippets thrughout the docs and examples, but was not able to find a overall picture

**Comment by TomasVotruba** [comment]
Anything Symfony config uses

**Comment by clxmstaab** [comment]
not sure I get what you are saying... what do you mean?

example question on what I am refering to:
- is there a way to tell rector via `rector.yml` which folders should be analyzed/refactored? atm I alwas need to pass the folder name, e.g. `rector process models --set php70` .. but I would prefer to define the folders in my rector.yml instead

**Comment by TomasVotruba** [comment]
Oh. That's no possible now, it needs to be passed as argument in the command.

I won't add it, but I'm open to PR with your feature
