### ISSUE TITLE
[Feature Request] Show Exception Trace when Rector fails

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#223]
Is possible to show the `Exception Trace` when a Rector fail?

**Comment by TomasVotruba** [comment]
Have you tried `-vvv`? That should work as in any Symfony CLI app

**Comment by carusogabriel** [comment]
Yep. Let try to be more clear :sweat_smile: 

Is possible to show with external file did cause the failure of `Rector`?

**Comment by TomasVotruba** [comment]
Working on that already :+1:
