### ISSUE TITLE
Wrong type infered by CompleteVarDocTypePropertyRector

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#2230]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.5.20 (invoke `vendor/bin/rector --version`)          |
| PHP version    | PHP 7.2.9 (invoke `php -v`)                               |
| Full Command   | vendor/bin/rector process /src --set dead-code --debug  | 

## Current Behaviour 

Already existing code is typed with phpdoc on a property with a abstract-base-class or a interface-type should not be replaced by the concrete implementation used.

typing properties/variables with interfaces/abstract-class-types is superior to use the more concrete implementation specific types.

rector should not try to change the property in such cases

**Comment by TomasVotruba** [comment]
Real code is needed

**Comment by clxmstaab** [comment]
see e.g.

![image](https://user-images.githubusercontent.com/47448731/68117758-7df70600-fefe-11e9-90f3-dc6bf692ca50.png)

with the following type-hierarchy

- CacheAbstract
  - CacheInApc extends CacheAbstract
  - CacheMemcached extends CacheAbstract

**Comment by TomasVotruba** [comment]
I see. Could you add failing test case to `CompleteVarDocTypePropertyRectorTest`?
So we have this one covered

**Comment by clxmstaab** [comment]
> I see. Could you add failing test case to `CompleteVarDocTypePropertyRectorTest`?

I dont think that I can support you with a unit test for this case, sorry.

**Comment by TomasVotruba** [comment]
Why not?

**Comment by clxmstaab** [comment]
I dont get how the test-framework works you use

**Comment by TomasVotruba** [comment]
I see. Here is a PR with example: https://github.com/rectorphp/rector/pull/2071/files

Basically you add a single `*.php.inc` file with struture:

```bash
code before
-----
code after
```

**Comment by TomasVotruba** [comment]
Closing for missing test case to verify
