### ISSUE TITLE
ParamTypeDeclarationRector with inverted phpdoc notation

### ISSUE THREAD

**Issue by orklah** [rectorphp/rector#2272]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | last version         |
| PHP version    | PHP 7.3                           |

## Current Behaviour 

When trying to apply the ParamTypeDeclarationRector service, it doesn't recognize when the type and the variable are inverted:
```php
/**
 * @param $string string 
 */
```
could be matched and be hinted.

## Minimal PHP Code Causing Issue
```php
/**
 * @param $string string
 */
function test($string){

}
```

**Comment by TomasVotruba** [comment]
This is rather task for coding standard tools. AST cannot reach there
