### ISSUE TITLE
[idea] reactor to migrate from the deprecated constants of \Doctrine\DBAL\Types\Type

### ISSUE THREAD

**Issue by stof** [rectorphp/rector#2280]
Doctrine DBAL 2.10 is deprecating the constants in the `\Doctrine\DBAL\Types\Type` abstract class in favor of equivalent constants in `\Doctrine\DBAL\Types\Types` (most constants have the same name, but a few of the date-related types have `_MUTABLE` added in the constant name to make them symmetric with the `_IMMUTABLE` date types);

## Diff 

```diff
 use Doctrine\DBAL\Types\Type;
+use Doctrine\DBAL\Types\Type;

-$query->setParameter($a, Type::BOOLEAN);
-$query->setParameter($b, Type::DATE);
+$query->setParameter($a, Types::BOOLEAN);
+$query->setParameter($b, Types::DATE_MUTABLE);
```

Removing the existing use statement for `Doctrine\DBAL\Types\Type` might a nice bonus, but it requires to be careful (as it could be used for other things than referencing constants), and PHP-CS-Fixer can already be used to clean that after the migration anyway.

**Comment by TomasVotruba** [comment]
I overlooked this issues, just getting to it now.

I wonder if it would be more useful to cover whole https://github.com/doctrine/dbal/blob/master/UPGRADE.md, where possible

**Comment by TomasVotruba** [comment]
It's very hard to deduce migration path from the upgrade file, as FQN classes are missing and wording is often ambiguous. Diff examples would be more helpful.

I've started first set at #2514 
I'd be happy if you check it and fix/complete, if you find a way
