### ISSUE TITLE
Does not work with PHP 5.6?

### ISSUE THREAD

**Issue by ipkpjersi** [rectorphp/rector#2283]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | N/A          |
| PHP version    |  5.6.40-12                             |
| Full Command   | ./composer.phar require rector/rector --dev  | 

## Current Behaviour 

It does not work, it throws an InvalidArgumentException:

![](http://i.imgur.com/4I9CwmL.png)

## Minimal PHP Code Causing Issue

./composer.phar require rector/rector --dev

## Expected Behaviour

I expect it to not throw an InvalidArgumentException.

**Comment by TomasVotruba** [comment]
Rector require PHP 7.1+

To run it on lower PHP, you need to run it in Docker: https://github.com/rectorphp/rector#install

**Comment by ipkpjersi** [comment]
Wait... I'm kinda confused. A tool designed for upgrading PHP versions doesn't support a (very common) older PHP version?

**Comment by TomasVotruba** [comment]
It does support older PHP,  goes down to PHP 5.3.

**Comment by jperovic** [comment]
Hey Tomas, I am jumping way too late for this but I am having trouble wrapping this around my head. 

I am working on upgrading a legacy project (Symfony 2 / PHP 5.6) and I run the project locally via Docker

When I try to install rector via composer, I get the same message as @ipkpjersi did.

> To run it on lower PHP, you need to run it in Docker: https://github.com/rectorphp/rector#install

I am not quite following. The link does not seem to mention Docker. Can you please explain a bit more?

Thanks!

**Comment by jperovic** [comment]
Errmm I see this now: https://github.com/rectorphp/rector-src/pull/614 :(
