### ISSUE TITLE
It is possible to hit `$if = $else->stmts[0];` with an empty array or null in ShortenElseIfRector.php

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#2287]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | e.g. v0.5.21         |
| PHP version    | e.g. PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS ) |
| Full Command   | rector process . --set code-quality --dry-run  | 

## Current Behaviour 

https://github.com/rectorphp/rector/blob/e927baaad742993ddc3384606b090dd0c40e4f74/packages/CodeQuality/src/Rector/If_/ShortenElseIfRector.php#L83

## Minimal PHP Code Causing Issue

  

```php
<?php 

// put file content here
```

**Comment by TomasVotruba** [comment]
Closing for lack of feedback
