### ISSUE TITLE
Add --xdebug option to allow running with xdebug

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#2333]
Inspired by PHPStan's option `--xdebug`:

```
--xdebug                       Allow running with XDebug for debugging purposes
```

When i need to xdebug with rector i always have to go into code (because i do not remember that) and dig for it to find out that i have to add `RECTOR_ALLOW_XDEBUG=1` before my command, `--xdebug` option is much easier to remember.

**Comment by TomasVotruba** [comment]
It's already in ;)

**Comment by JanMikes** [comment]
Wow, that is damn awesome, did not know that! Big up! 👍

**Comment by TomasVotruba** [comment]
Try -h with command first, there are more options
