### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages SF2.8 to ...

### ISSUE THREAD

**Issue by donbrico** [rectorphp/rector#2334]
## Question

Hi,

I'm trying to install Reactor to upgrade my SF2.8 projetct toward SF3.0 first, but I didn't manage to install Reactor, here is the output  

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rector/rector ^0.5.22 -> satisfiable by rector/rector[v0.5.22].
    - Conclusion: remove symfony/symfony v2.8.52
    - Conclusion: don't install symfony/symfony v2.8.52
    - rector/rector v0.5.22 requires symfony/process ^3.4|^4.2 -> satisfiable by symfony/process[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8].
    - don't install symfony/process v3.4.0|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.1|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.10|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.11|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.12|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.13|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.14|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.15|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.16|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.17|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.18|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.19|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.2|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.20|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.21|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.22|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.23|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.24|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.25|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.26|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.27|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.28|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.29|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.3|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.30|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.31|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.32|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.33|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.34|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.35|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.4|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.5|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.6|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.7|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.8|don't install symfony/symfony v2.8.52
    - don't install symfony/process v3.4.9|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.0|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.1|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.10|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.11|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.12|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.2|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.3|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.4|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.5|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.6|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.7|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.8|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.2.9|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.0|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.1|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.2|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.3|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.4|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.5|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.6|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.7|don't install symfony/symfony v2.8.52
    - don't install symfony/process v4.3.8|don't install symfony/symfony v2.8.52
    - Installation request for symfony/symfony (locked at v2.8.52, required as ^2.8) -> satisfiable by symfony/symfony[v2.8.52].

Installation failed, reverting ./composer.json to its original content.`
Thank you very much for your help,

Don Brico

**Comment by Aerendir** [comment]
You cannot install the latest version of Rector using SF2.8: it is too old and the dependencies will conflict.

The best approach you can try is to don't set a version for Rector:

```console
composer req rector/rector
```

This command will use the version of Rector compatible with your current set of installed packages.

Obviously, you will not get the latest version of Rector, but you will be able to make easier the upgrade of SF.

Another approach is to require Rector in your `composer.json` without a version constraint:

```json
"rector/rector": "*"
```

**Comment by TomasVotruba** [comment]
See README and Docker 
or you can help with this issue https://github.com/rectorphp/rector/issues/177

The first is fast solution, but you may have version conflicts. The latter is more solid solution, but requires work to finish

**Comment by donbrico** [comment]
@Aerendir, thank you for your reply, I'll get back to you after my test.

**Comment by TomasVotruba** [comment]
Even better solution now - Rector prefixed: https://github.com/rectorphp/rector-prefixed
