### ISSUE TITLE
[DX] Remove unneded stubs on Rector install to prevent PHPStorm miss-match

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#2339]
![boom](https://user-images.githubusercontent.com/924196/69168337-c3b6ef80-0af6-11ea-9312-8093fec4fceb.gif)

**Comment by TomasVotruba** [comment]
See also:

- https://github.com/rectorphp/rector/issues/2186#issuecomment-545582628
- https://github.com/rectorphp/rector/issues/2068#issuecomment-537465172

cc @gnutix  Finally getting to that too. What would you suggest now to do about this?

**Comment by Aerendir** [comment]
To solve this problem you can exclude the directory from Preferences > Languages & Framework > PHP.

Here you need to remove the directory of Rector from the list.

<img width="1160" alt="Schermata 2019-11-19 alle 18 52 02" src="https://user-images.githubusercontent.com/1968622/69172203-b2bdac80-0afd-11ea-90e8-2cd3c287773c.png">

This is not a definitive solution, but is useful until a definitive one is found.

I also have the suspect that on each Composer's update, the directories are added again and so have to be removed again.

**Comment by Aerendir** [comment]
@TomasVotruba , this is not a definitive solution: I think that the directories have to be removed each time you run `composer update`... But I have to further verify this behavior...

**Comment by TomasVotruba** [comment]
@Aerendir :+1:  That's exactly what I suggested before

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector/pull/2391
