### ISSUE TITLE
Incorrect replacement of preg_split by Nette\Utils\Strings::split() for regexp with subpattern

### ISSUE THREAD

**Issue by rugabarbo** [rectorphp/rector#2348]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | `dev-master@225f873`          |
| PHP version    | `PHP 7.3.11`                               |
| Full Command   | `vendor/bin/rector process src tests --config rector-ci.yaml --dry-run`  | 

## Current Behaviour 

![19 11 23-16 18 14](https://user-images.githubusercontent.com/6429469/69479325-020d2100-0e0d-11ea-905c-3496403d6839.jpg)

Source: https://travis-ci.org/cpliakas/git-wrapper/jobs/615485754#L322-L353

## What is the problem

[Nette Utils](https://github.com/nette/utils) uses flag `PREG_SPLIT_DELIM_CAPTURE` by default when splitting lines:
https://github.com/nette/utils/blob/f1dc08536b040d5b569ee63354343145cbe6c591/src/Utils/Strings.php#L435

Because of this, [Strings::split()](https://doc.nette.org/en/3.0/strings#toc-split) also returns delimiters in the result set **in cases where regexp contains subpatterns**. Therefore, the Rector’s recommendation is incorrect, because in these cases method `Strings::split()` returns a different data set in the array.

**Comment by TomasVotruba** [comment]
What would be correct behavior and how to detect it?

**Comment by TomasVotruba** [comment]
Code to replicate:

```php
$content = 'Hi my name is Tom';
$pattern = '#(\s)#';

$nativePieces = preg_split($pattern, $content);
var_dump($nativePieces);

$utilsPieces = \Nette\Utils\Strings::split($content, $pattern);
var_dump($utilsPieces);

// should be true
var_dump($nativePieces === $utilsPieces);   
```

**Comment by TomasVotruba** [comment]
This fixes it:

```php
// @see https://stackoverflow.com/a/57787941/1348344
$utilsPieces = \Nette\Utils\Strings::split($content, $pattern, 0 & ~PREG_SPLIT_DELIM_CAPTURE);
dump($utilsPieces);
```
