### ISSUE TITLE
php namespaces replaced wrongly

### ISSUE THREAD

**Issue by sfarkas1988** [rectorphp/rector#2361]
## Question
I ran rector in all different variation, but for whatever reason rector always changes my php class pathes like here:

```diff
+use InvalidArgumentException;
+use DateTime;
+use RuntimeException;
use Carbon\Carbon;
use FOS\RestBundle\Controller\Annotations\Get;
use FOS\RestBundle\Controller\Annotations\Post;
@@ -89,7 +92,7 @@
         if (null !== $filters['dateStart']) {
             try {
                 $filters['dateStart'] = Carbon::parse($filters['dateStart']);
 -            } catch (\InvalidArgumentException $e) {
 +            } catch (InvalidArgumentException $e) {
                 $inputErrors['date_start'] = 'The start date is invalid';
             }
```

The latest command I ran is:

`docker run -v $(pwd):/project rector/rector:latest process /project/src --set symfony40 --autoload-file /project/vendor/autoload.php --dry-run --config /project/rector.yaml`

The config file just excludes the tests:

```
parameters:
    exclude_paths:
        - '*/src/*/Tests/*'

```

Do I have to set any setting to avoid replacing the php namespaces?

**Comment by TomasVotruba** [comment]
The auto import is on by default, you can disable it here:
https://github.com/rectorphp/rector#import-use-statements

**Comment by sfarkas1988** [comment]
What does auto_import mean in this case?
Is it about adding the use statement above? 
Even if, the generated code is wrong in my point of view, or am I wrong?

**Comment by TomasVotruba** [comment]
> Is it about adding the use statement above?

Yes, basically same as "Import" feature in PHPStorm.

> Even if, the generated code is wrong in my point of view, or am I wrong?

How? I'd have to see the whole file, in case the DateTime is imported somewhere else.

If not and you're using newest Rector 0.6, that's probably a bug. Please provide failing test case here - https://github.com/rectorphp/rector/tree/master/packages/Renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames (just copy-paste on file, rename it and add before/after content)

**Comment by TomasVotruba** [comment]
Closing as answered in README:
https://github.com/rectorphp/rector#import-use-statements
