### ISSUE TITLE
A rector that converts `'nonempty string with no numbers' == $a` to `'nonempty string with no numbers' === $a`

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#2362]
The 'Php Inspections (EA Extended)' plugin for PhpStorm/IntelliJ noted that certain string comparisons can be safely transformed to use no type-coercion. I'm not that into the PHP system to know if this is always true, like they assume. But from my cursory understanding, this works for strings that are non-empty and contain no numbers.

## Diff 

```diff
-if('a' == $a) next();
+if('a' === $a) next();
if('' == $b) next();
if('2' == $c) next();
```

**Comment by TomasVotruba** [comment]
It's already handled in:
https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#useidenticaloverequalwithsametyperector
