### ISSUE TITLE
A rector that converts `$bool ? boolean_statement : false` in `$bool && boolean_statement`

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#2363]
When the ternary operator ends in false, it can be simplified

## Diff 

```diff
-$value = $bool ? boolean_function() : false
+$value = $bool && boolean_function();
```

**Comment by TomasVotruba** [comment]
Good point!

Would you send PR with such feature?

**Comment by HenkPoley** [comment]
Sure, maybe I'll get to it somewhere in the next 6 months. It's more like a note after some code I spotted. I've currently no clue how to drive this beast.

**Comment by TomasVotruba** [comment]
Let's put it into dead code set
