### ISSUE TITLE
Blade to Twig rector

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector#2375]
one of those things to make migration from laravel to symfony easier (https://github.com/rectorphp/rector/issues/1310)
is to move from blade to twig. That is just subtask to the main laravel to symfony rector.

**Comment by TomasVotruba** [comment]
This is rather non-PHP migration, so Rector won't cover it.

You can create standalone package that we could host here though.

I made similar migration package for Latte → Twig: https://github.com/Symplify/LatteToTwigConverter
Probably moving it here (under Rector vendor, not to this package) a is good idea
