### ISSUE TITLE
Throws changed to void

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#2382]
```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -18,7 +18,7 @@
     /**
      * @param object $object
      */
-    public function hydrate(array $data, $object): object
+    public function hydrate(array $data, $object): void
     {
         throw new BadMethodCallException('Not implemented');
     }
    ----------- end diff -----------
Applied rules:
 * Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector
```

Where `hydrate` comes from interface where object is defined return type (by annotation)

**Comment by TomasVotruba** [comment]
I need more detailed description.

- What is responsbible command?
- What is the rector class causing this?

**Comment by TomasVotruba** [comment]
What class is extended here? Could you link to it on Github?

I wonder what should happen, because it's valid change. There is no object returned and return type was invalid before

**Comment by snapshotpl** [comment]
That's right, however this class implements [interface](https://github.com/zendframework/zend-hydrator/blob/master/src/HydrationInterface.php) where `hydrate` has `object` as returned type. This class doesn't returned anything, but also always throw exception, so this is the point.

**Comment by snapshotpl** [comment]
I use exactly this version of interface https://github.com/zendframework/zend-hydrator/blob/2.4.2/src/HydrationInterface.php

**Comment by TomasVotruba** [comment]
I'm looking into this, thanks for all the links :+1:

**Comment by TomasVotruba** [comment]
The change above is actually correct and valid. Method doesn't return anything and return type only extends the allowed typee from the interface (none).

On the other hand I found a bug in case of `object` behing pattern type in type declaratoin. It's overriden to `void` which violates the contract:
https://3v4l.org/siKZq

**Comment by TomasVotruba** [comment]
Btw, it's funny that last interface change of that hydrator is removing `object` type declaration :D 

https://github.com/zendframework/zend-hydrator/commit/4155c25d834f31dc38cafa4e36c15ccd9a3c1359
