### ISSUE TITLE
Doesn't work with phpstan 0.12

### ISSUE THREAD

**Issue by hugochinchilla** [rectorphp/rector#2385]
A new version of phpstan has been published and rector doesn't work with it.

**Comment by TomasVotruba** [comment]
There were many changes there. The best solution would be locking it in our composer.json to 0.11.19

**Comment by ondrejmirtes** [comment]
What you mean by "doesn't work with it" exactly?

**Comment by michaljusiega** [comment]
He means probably that problem:

```
Problem 1
    - Installation request for rector/rector ^0.5.12 -> satisfiable by rector/rector[v0.5.12].
    - rector/rector v0.5.12 requires phpstan/phpstan ^0.11.13 -> satisfiable by phpstan/phpstan[0.11.13, 0.11.14, 0.11.15, 0.11.16, 0.11.17, 0.11.18, 0.11.19] but these conflict with your requirements or minimum-stability.
```

**Comment by ondrejmirtes** [comment]
So yeah, I was right in https://github.com/rectorphp/rector/pull/2389#issuecomment-561829088, locking to 0.11.19 does not help your issue.

**Comment by TomasVotruba** [comment]
I see. I thought it's about BC conflicts.
I that case, composer version needs to be bumped and CI needs to pass
