### ISSUE TITLE
php warning: "The use statement with non-compound name...has no effect"

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#2387]
in the past I used rector to process my codebase using `php70` set using `rector 0.5.*`.

it added a lot of use statements. some of them trigger a php warning, described in detail on https://stackoverflow.com/questions/9317022/troubleshooting-the-use-statement-with-non-compound-name-has-no-effect

with phpstan 0.12 these will also be reported as errors, so my build is broken because of this statements which were only php warnings before.

my questions:
- is it possible to tell rector to remove these imports again?
- is this problem fixed so processing my sources will not re-add this use statements again?

Example of code beeing affected:

```php
<?php

use ApplicationController;
// .. snip

class SearchagentController extends ApplicationController
{
}
```

**Comment by TomasVotruba** [comment]
How can I reproduce the error?

**Comment by clxmstaab** [comment]
before I try to get a repro for my initial question: could you give me a hint whether rector is able to delete these imports which lead to this warnings/errors?

**Comment by TomasVotruba** [comment]
Yes, that can be achieved with `AbstractFileSystemRector`, that works with higher file-level context.

Thanks for example :

**Comment by clxmstaab** [comment]
> Yes, that can be achieved with `AbstractFileSystemRector`, that works with higher file-level context.

not sure what you mean by that.

**Comment by TomasVotruba** [comment]
You need to extend + implement this: https://github.com/rectorphp/rector/blob/master/packages/FileSystemRector/src/Rector/AbstractFileSystemRector.php

**Comment by TomasVotruba** [comment]
I'll look on it this weekend

**Comment by TomasVotruba** [comment]
The #2368 should fix the problem.

As for removing, I recommend revert commit `git revert <hash-of-commit>`
or replace with regex in PHPStorm: https://regex101.com/r/nnuCEM/2 `#^use \w+;#`
