### ISSUE TITLE
[NFR] Scan for fatal errors

### ISSUE THREAD

**Issue by ruudboon** [rectorphp/rector#2388]
When an interface changes the extended class should be adjusted.
Normally PHP will let you know that by generating a fatal error. It would be nice if you could scan your codebase for these kind of errors. Since it's a fatal error you need something to make sure the script continues.
I created a prototype to show a way how to solve this. It's a prototype just to show the idea. Code needs some improvement ;)

Our fatal error (test.php)
```php
<?php
    class test {
        public function add(string $message="") {

        }
    }

    class extendTest extends test {

        public function add($message) {

        }
    }
```
And the scanner
```php
<?php

class interfaceErrorDetector {
    public $errors=[];

    public function __construct()
    {
        set_error_handler([$this, 'logError']);
    }

    public function logError ( $num, $str, $file, $line, $context = null) {
        $this->errors[$file] = $str;
    }

    public function scanFile($file) {
        $content = str_replace("<?php", "", file_get_contents($file));
        eval($content);
    }

    public function __destruct()
    {
        restore_error_handler();
    }
}

$handler = new interfaceErrorDetector();
$handler->scanFile("test.php");
print_r($handler->errors);
```

**Comment by ondrejmirtes** [comment]
Hi, this what's the main job of PHPStan - to find errors like this in your codebase.

Check out this introductory article: https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3

And also this one about the latest release: https://medium.com/@ondrejmirtes/phpstan-0-12-released-f1a88036535d

**Comment by TomasVotruba** [comment]
@ondrejmirtes That's completely unrelated to the issue. Please stop overpromoting with unrelated comments

**Comment by ondrejmirtes** [comment]
I've read the issue carefully and I think I get what the user really wants. They're not asking to refactor their code using Rector, they really want the error detected. I'm just trying to help.

**Comment by ondrejmirtes** [comment]
And I thought we were friends.

**Comment by TomasVotruba** [comment]
Related: https://github.com/rectorphp/rector/issues/2379

**Comment by Wirone** [comment]
@TomasVotruba why did you delete Ondrej's comments and blocked him?

**Comment by TomasVotruba** [comment]
@Wirone Because he was spamming with PHPStan copy-paste links here and under my blogposts, with unrelated content. I asked him first politely first, but it didn't help. 

I'm ok with sharing tool ideas, but with not repeated overpromoting under content that the person doesn't even read.

**Comment by Wirone** [comment]
@TomasVotruba as far as I know Ondrej shared information about that PHPStan already does what @ruudboon asks for. Since you've deleted comments it can't be confronted but from my point of view Ondrej wanted to help Rector's team to dispatch this issue and provide useful information to OP. You're using PHPStan as part of Rector so I find it not fair to block its creator/maintainer who tries to help, not to steal your users.

**Comment by TomasVotruba** [comment]
Can I somehow undelete them? I never used this feature before, I just didn't want to spam issue.


This issue was created by @ruudboon at my request. To keep feature in mind.

I don't find it very polite to post link to another tools. Imagine Laravel guys would post linksto Laravel in Symfomy issues.

**Comment by Wirone** [comment]
Laravel people tweets about migrating to new version of Symfony and Symfony people retweets. It's not that hard.

I would find it rude if Rector didn't use PHPStan and Ondrej would like to advertise competitive tool. But he only linked to the tool which is used here.

**Comment by ruudboon** [comment]
I'm sure no harm intended from all sides. Let's don't make it bigger then needed. 
If you can undelete comments it would be nice gesture, if it isn't possible I did read them in the email alerts. We all love working on cool stuff and the cool thing about opensource it's the ideal place to work together so let keep doing that. Learn, inspire and help each other.

Regarding the issue, it's indeed an introduction to something that could be an addition to rector for easy refactoring, not only detecting. So think it's good to have this issue here and Ondrej thank you for pointing out the PHPStan feature, missed that one.

**Comment by TomasVotruba** [comment]
For reference: https://3v4l.org/gFAT0

**Comment by TomasVotruba** [comment]
Also return types need to be covered: https://3v4l.org/i0JHs
