### ISSUE TITLE
Unclear expected behaviour of NodeTypeResolver::resolve

### ISSUE THREAD

**Issue by jeroensmit** [rectorphp/rector#2412]
## Question
What is the expected behaviour of \Rector\NodeTypeResolver\NodeTypeResolver::resolve
In case om method calls and classConst for example it seems to return the class on which is called rather than the return type of the method:
```php
        if ($node instanceof ClassMethod || $node instanceof ClassConst) {
            return $this->resolveClassNode($node);
        }
```
For casts it seems to be whatever it was casting rather than the result
```php
        if ($node instanceof Cast) {
            return $this->resolve($node->expr);
        }
```

On the other end, in the useCase of \Rector\Rector\AbstractRector\NodeTypeResolverTrait::getObjectType as it is used in 
packages/Php71/src/Rector/FuncCall/RemoveExtraParametersRector.php:133 it is assumed to return the return type of the method call.

Which one is expected?

**Comment by TomasVotruba** [comment]
This was based rather on pragmatic cases, *to make it work* with rules where this is used. I understand it's rather confusing in some cases.

So my question would be, how would you change it for better?

**Comment by jeroensmit** [comment]
I think a good definition might be that it returns the type that node might represent at that specific point (what would you see if you put it in a var_dump)

Behaviour for each node in this example:
```php
function foo($a) {
    $a = '1';
    $a = $a + 1;
}
```

```

Stmt_Function : InvalidArgumentException  (use different function to get return type)
    Identifier : InvalidArgumentException
    Param: MixedType
        Expr_Variable: MixedType

    Stmt_Expression : StringType
    Expr_Assign: StringType
        Expr_Variable: MixedType (not assigned yet)
        Scalar_String: StringType
    
    Stmt_Expression: IntegerType
        Expr_Variable : StringType (not assigned yet)
        Expr_BinaryOp_Plus : IntegerType
            Expr_Variable: StringType
            Scalar_LNumber: IntegerType
```

Important in this example is the different types the variable a can be at certain places.

deducing example:
```php
<?php

function foo($a) {
    try {
        bar($a); //$a => MixedType
        var_dump($a); //$a => StringType
    } catch (Throwable $throwable) {
        var_dump($a); //$a => MixedType
    }
    return $a;  //$a => MixedType
}
function bar(string $b) {
    //content not relevant
}

```
In this example $a would be MixedType twice (in Param and MethodCall) the third time it StringType. 

I think that while looking at the typeresolving it is good to consider making docblock parsing  optional. This because quite often in real live codebases those aren't reliable. 

How does this sound to you?

**Comment by TomasVotruba** [comment]
I would have to see it in the PR and how it influences the rest of the code.

**Comment by TomasVotruba** [comment]
Closing as waiting for RFC with PR
