### ISSUE TITLE
Rector and PHP extensions

### ISSUE THREAD

**Issue by LordOfTheRats** [rectorphp/rector#2418]
## Question
We use a PHP extension, [wxPHP](https://github.com/wxphp/wxphp/) to be specific, in some of our classes. When running Rector it complains about not finding classes from this extension, even if the extension has been explicitly loaded using `php -dextention=wxwidgets.so`.

```
"Analyze error: "Class wxFrame not found and could not be autoloaded.". Include your files in "parameters > 
autoload_paths".   
```

For now I just removed any reference to the wxPHP classes from my code. Is there a better way to do it?

**Comment by TomasVotruba** [comment]
That's weird, is the extension active also in php.ini for CLI?

**Comment by LordOfTheRats** [comment]
Usually the extension is only loaded on demand, using `dl()`. For use with Rector I explicitly loaded it using PHP's `-d` parameter. But fair enough, I'll add it to php.ini to make sure this isn't the issue.

(Dang, you are quick to reply :D :+1: )

**Comment by LordOfTheRats** [comment]
Hm strange, it actually makes a difference:

Before:
```
$ php -dextension=wxwidgets.so -i | grep "wxWidgets =>"
wxWidgets => enabled

$ php -dextension=wxwidgets.so rector.phar process src --set symfony28
[...]
"Analyze error: "Class wxDialog not found and could not be autoloaded.". Include your files in "parameters > autoload_paths".
[...]
```

After:
```
$ php -i | grep "wxWidgets =>"
wxWidgets => enabled

$ php rector.phar process src --set symfony28
[...]
[OK] Rector is done! 0 changed files
```

**Comment by TomasVotruba** [comment]
Closing as resolved
