### ISSUE TITLE
Invalid output when running TernaryToElvisRector

### ISSUE THREAD

**Issue by JoyceBabu** [rectorphp/rector#2421]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.0          |
| PHP version    | PHP 7.3.12                               |
| Full Command   | composer/bin/rector process rector/test.php -vvv  | 

## Current Behaviour 
I was trying to upgrade a very old code. `TernaryToElvisRector` converts 

    $val = ($a - $b) ? ($a - $b) : $c;

to 
    $val = ($a - $b) ? () : $c;

```
1 file with changes
===================

1) rector/test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -1,4 +1,4 @@
 <?php

-$val = ($a - $b) ? ($a - $b) : $c;
+$val = ($a - $b) ? () : $c;
    ----------- end diff -----------

Applied rules:

 * Rector\Php53\Rector\Ternary\TernaryToElvisRector
```

## Minimal PHP Code Causing Issue

  

```php
<?php

$val = ($a - $b) ? () : $c;

```

## Expected Behaviour

    $val = ($a - $b) ?: $c;

**Comment by TomasVotruba** [comment]
Thanks for the report.

Could you add test case to `TernaryToElvisRectorTest`?

**Comment by JoyceBabu** [comment]
How do I do that? I create a new test case file under 

    rector/packages/Php53/tests/Rector/Ternary/TernaryToElvisRector/Fixture/

**Comment by TomasVotruba** [comment]
Yes, basically.

With

```
// input content
-----
// expected changed code
```

**Comment by JoyceBabu** [comment]
Created PR https://github.com/rectorphp/rector/pull/2423
