### ISSUE TITLE
Cannot load bleedingEdge from phpstan

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#2431]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.1          |
| PHP version    | PHP 7.3.12                               |
| phpstan version    | v0.12.2                               |

## Current Behaviour 

After run process:

```
rector process module/ --dry-run

Fatal error: Uncaught _HumbugBox22f0dbe102af\Nette\FileNotFoundException: File 'phar://phpstan.phar/conf/bleedingEdge.neon' is missing or is not readable. in phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php on line 29

_HumbugBox22f0dbe102af\Nette\FileNotFoundException: File 'phar://phpstan.phar/conf/bleedingEdge.neon' is missing or is not readable. in phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php on line 29

Call Stack:
    0.0558     458192   1. {main}() /var/www/vendor/rector/rector/bin/rector:0
    1.4034   23744432   2. ContainerKpKdxQ6\HttpKernelRector_HttpKernel_RectorKernelProd5699145Container->get() /var/www/vendor/rector/rector/bin/rector:47
    1.4034   23744432   3. ContainerKpKdxQ6\HttpKernelRector_HttpKernel_RectorKernelProd5699145Container->make() /var/www/vendor/symfony/dependency-injection/Container.php:225
```

## Minimal PHP Code Causing Issue

My phpstan config includes `bleedingEdge.neon`, which is fine, even in phar.
```neon
includes:
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon
```

## Expected Behaviour
No fatal, bleedingEdge included.

**Comment by TomasVotruba** [comment]
How Is this solved in PHPStan itself?

**Comment by snapshotpl** [comment]
https://github.com/phpstan/phpstan/blob/master/conf/bleedingEdge.neon

**Comment by TomasVotruba** [comment]
How is this file loaded there?

**Comment by snapshotpl** [comment]
Look at my first post

**Comment by TomasVotruba** [comment]
I mean how PHPStan handles it internally. We need the same change here

**Comment by snapshotpl** [comment]
I think @ondrejmirtes can help here

**Comment by ondrejmirtes** [comment]
phar://phpstan.phar path is only valid from inside PHPStan. Otherwise you need to use absolute path to the file on disk.

But Rector doesn’t need bleedingEdge for anything, it can be removed.

**Comment by snapshotpl** [comment]
bleedingEdge is not included by Rector, but by my project which require Rector and PHPStan

**Comment by ondrejmirtes** [comment]
The stack trace looks like bleedingEdge.neon is trying to be loaded when you run Rector. Which means that your phpstan.neon gets picked up by Rector for some reason...

**Comment by TomasVotruba** [comment]
@snapshotpl Could you provide full steps to reproduce the issue? Including install and your minimal local `rector.yaml` and/or `phpstan.neon` configs.

I'll try to reproduce locally

**Comment by TomasVotruba** [comment]
I see the problem now. This is correct:

```yaml
# phpstan.neon
includes:
    - 'vendor/phpstan/phpstan/conf/bleedingEdge.neon'
```

But there is fallback inside the phar:

```yaml
# vendor/phpstan/phpstan/conf/bleedingEdge.neon
includes:
	- phar://phpstan.phar/conf/bleedingEdge.neon
```

Where PHP can reach, unless run from `phpstan.phar`.

**Comment by TomasVotruba** [comment]
The file https://github.com/phpstan/phpstan-src/blob/master/conf/bleedingEdge.neon is actually empty, this bug has not much value neither for PHPStan :/

**Comment by ondrejmirtes** [comment]
The file `bleedingEdge.neon` should not be included when running Rector at all, that's the root problem.

`bleedingEdge.neon` is currently empty but it wasn't empty in 0.11.19 and it won't be empty soon, it doesn't make sense to break people's builds just because there are currently no bleeding edge features.

**Comment by TomasVotruba** [comment]
Yea, but how can it be excluded?

**Comment by ondrejmirtes** [comment]
It's not included anywhere by default, user has to opt-in in their phpstan.neon>

**Comment by ondrejmirtes** [comment]
It looks like @snapshotpl somehow uses their phpstan.neon when running Rector and I don't see why.

**Comment by TomasVotruba** [comment]
> It's not included anywhere by default, user has to opt-in in their phpstan.neon.

Well, that's what breaks Rector run now and the error is very helpful.

> when running Rector and I don't see why

Rector uses PHPStan to analyse types.

**Comment by ondrejmirtes** [comment]
Let me repeat - PHPStan does not force the user to include `bleedingEdge.neon`. I don't see why and where is it actually included by Rector. It can be removed.

**Comment by ondrejmirtes** [comment]
If it's the case that Rector requires its own configuration using rector.yml or rector.neon or whatever, I think it's a design flaw to also require and read user's phpstan.neon - it shouldn't be necessary.

**Comment by ondrejmirtes** [comment]
Looks like this feature should be removed or changed: https://github.com/rectorphp/rector/pull/2184/files

**Comment by TomasVotruba** [comment]
> Let me repeat - PHPStan does not force the user to include bleedingEdge.neon. I don't see why and where is it actually included by Rector. It can be removed.

It just throws error when not run in phar. It can be removed, but there is no phpstan exception that would tell the user to do that. Exception burden is moved to Rector, this issue.

> If it's the case that Rector requires its own configuration using rector.yml or rector.neon or whatever, I think it's a design flaw to also require and read user's phpstan.neon - it shouldn't be necessary.

That's the only way to configure it with default `phpstan.neon` extension now.

**Comment by ondrejmirtes** [comment]
I do this logic to recursively detect all included files by the users' configuration: https://github.com/phpstan/phpstan-src/blob/master/src/Command/CommandHelper.php#L361-L439

You can copy it to filter it and remove all `phar://...` paths.

**Comment by TomasVotruba** [comment]
Rector only runs the PHPStan factory, it doesn't work with *.neon files itself.

This is the best solution for now: https://github.com/rectorphp/rector/pull/2550

**Comment by TomasVotruba** [comment]
> I do this logic to recursively detect all included files by the users' configuration:

This should be on `ContainerFactory` level, not in command
