### ISSUE TITLE
Parsing stops suddenly

### ISSUE THREAD

**Issue by paul-gene** [rectorphp/rector#2433]
Just installed Rector in order to look at refactoring some Magento 1 PHP 5.4 code to PHP 7.2

Rector seems to start running fine, but suddenly stops. I used the verbosity flag, and it shows files being parsed, but then just errors out.

Is there any form of log created when running Rector?

Is it a case that I'm giving it too much to parse?

**Comment by TomasVotruba** [comment]
Try `--debug` and provide minimal file. It's usually 1 line

E.g. `vendor/bin/rector process src/SomeFile.php --debug`

**Comment by paul-gene** [comment]
Looks like it's one of the classes causing issues with apparently sending headers when it shouldn't.
