### ISSUE TITLE
is it support pure php ?

### ISSUE THREAD

**Issue by Q8hma** [rectorphp/rector#2434]
hello ,, first thnx for this program i have one question 

## Question

is it support pure php ? no Framework no other staff??

if yes how ?? becuase im new in this world

thnx

**Comment by TomasVotruba** [comment]
Hey, it depends. 

Headers and global non-functoin code can be very hard to refactor.
But if you have functions without side effect, there is no reason it should not work.

**Comment by TomasVotruba** [comment]
This is full list of upgrade sets for PHP:
https://github.com/rectorphp/rector/tree/master/config/set/php

Use as described in README:

```bash
vendor/bin/rector process src --set php72
```
