### ISSUE TITLE
Rename method name called on property

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#2440]
Hi Tomas,
first of all, I would like to thank you for this amazing tool.

I have a problem with `Rector\Renaming\Rector\MethodCall\RenameMethodRector` when the method is called on class property:

```php
class SomeClass
{
    /** @var SomeOtherClass */
    protected $someOtherClass;

    public function __construct(SomeOtherClass $someOtherClass)
    {
        $this->someOtherClass = $someOtherClass;
    }

    public function doSomething()
    {
        $this->someOtherClass->methodToBeRenamed();   // this is not renamed
    }

    public function doSomethingElse()
    {
        $someOtherClass = new SomeOtherClass();
        $someOtherClass->methodToBeRenamed();    // this is renamed
    }
}
```

I am not sure if this is problem of rector or php parser.

**Comment by TomasVotruba** [comment]
Hi, please add failing test case to the `RenameMethodRectorTest`

**Comment by lulco** [comment]
I added test https://github.com/rectorphp/rector/pull/2456 case but it is not failing :D I don't understand why...
In this repository it still failing: https://github.com/lulco/rector-nette-api
Method `getApiHandler` should be renamed at this line https://github.com/lulco/rector-nette-api/blob/master/nette-api-app/app/Presenters/ApiPresenter.php#L48

**Comment by TomasVotruba** [comment]
The class is probably missing in configuration

**Comment by lulco** [comment]
Not sure what do you mean. I have got this in configuration:
```
Rector\Renaming\Rector\MethodCall\RenameMethodRector:
    Tomaj\NetteApi\ApiDecider:
        addApiHandler: 'addApi'
        getApiHandler: 'getApi'
        getHandlers: 'getApis'
```

And also if I changed metod to this:
```
protected function createComponentApiConsole(): ApiConsoleControl
{
    $apiDecider = new ApiDecider();
    $api = $apiDecider->getApiHandler($this->method, $this->version, $this->package, $this->apiAction);
    return new ApiConsoleControl($this->getHttpRequest(), $api['endpoint'], $api['handler'], $api['authorization']);
}
```
It works
