### ISSUE TITLE
Is it possible to run Rector on Nette2.1 project?

### ISSUE THREAD

**Issue by nikolaslada** [rectorphp/rector#2441]
## Question
I tried to run Rector from Docker on project which was written in PHP5.6 and Nette2.1. It failed with message:
> Fatal error: Cannot use 'Object' as class name as it is reserved 

Ok that makes sense with the newest PHP. So I tried to run older release of Rector with older PHP from another directory. If failed with strange message:

> PHP Fatal error:  Uncaught Nette\MemberAccessException: Call to undefined method PHPStan\DependencyInjection\Configurator::addServices(). in /home/nikolas/projects/betsys/vendor/nette/nette/Nette/common/ObjectMixin.php:96

But there is no PHPStan in our project.
Do you have any idea?

**Comment by TomasVotruba** [comment]
This might help: https://github.com/rectorphp/rector-prefixed
