### ISSUE TITLE
RemoveDeepChainMethodCallNodeVisitor got me...

### ISSUE THREAD

**Issue by natepage** [rectorphp/rector#2444]
Hey there!

Today I've spent a couple hours trying to understand why Rector was telling me that my private property wasn't used even when I can see with my own eyes that it is used!!!!! 😄 Thought I was getting crazy for a second.

But fortunately I ended up finding the `RemoveDeepChainMethodCallNodeVisitor` and this issue #1646  and everything made sense!

## My code

Here is my Doctrine Repository sample:

```php
/**
 * {@inheritdoc}
 */
public function findLimitsForDecision(
	string $type,
    bool $strict,
    ?string $providerId = null,
    ?string $eventId = null
): array {
	$queryBuilder = $this->createQueryBuilder('l');

	// ... Build this massive query ...
	
	$queryBuilder
    	->andWhere($queryBuilder->expr()->orX(
        	$queryBuilder->expr()->lte('l.startAt', ':now'),
            $queryBuilder->expr()->isNull('l.startAt')
        ))
        ->andWhere($queryBuilder->expr()->orX(
            $queryBuilder->expr()->gte('l.endAt', ':now'),
            $queryBuilder->expr()->isNull('l.endAt')
        ))
        ->andWhere($queryBuilder->expr()->eq('l.active', true))
        ->setParameter('now', $this->dateTime->getNow()); // <-- Here is the property

	return $queryBuilder->getQuery()->getResult();
}
```

## Question

Are we removing deep chain method calls only for performance issues? Or because it's not a good practice?

I think that regardless of the answer to the previous questions, Rector should let the user know that some nodes have been removed instead of removing them silently 😄 

## Suggestion

Maybe we could implement a Rector to refactor deep chain method calls, so my code would become:

```php
/**
 * {@inheritdoc}
 */
public function findLimitsForDecision(
	string $type,
    bool $strict,
    ?string $providerId = null,
    ?string $eventId = null
): array {
	$queryBuilder = $this->createQueryBuilder('l');

	// ... Build this massive query ...
	
	$queryBuilder->andWhere($queryBuilder->expr()->orX(
        $queryBuilder->expr()->lte('l.startAt', ':now'),
        $queryBuilder->expr()->isNull('l.startAt')
    ));
    $queryBuilder->andWhere($queryBuilder->expr()->orX(
        $queryBuilder->expr()->gte('l.endAt', ':now'),
        $queryBuilder->expr()->isNull('l.endAt')
    ));
    $queryBuilder->andWhere($queryBuilder->expr()->eq('l.active', true));
    $queryBuilder->setParameter('now', $this->dateTime->getNow()); // <-- Here is the property

	return $queryBuilder->getQuery()->getResult();
```

Any thoughts?

**Comment by TomasVotruba** [comment]
I'm sorry about that :/ 

The node visitor was added for performance issues: https://github.com/rectorphp/rector/pull/767

Too deep method nesting can cause fatal errors with PHPStan:
https://github.com/phpstan/phpstan/issues/254


## Ideas

- send failing test case to the unused private property Rector
- try to lower the limit number for removed methods

**Comment by natepage** [comment]
Hi @TomasVotruba, sorry but I technically don't understand your ideas.. 😄 

Could you please reword it? Thank you

**Comment by TomasVotruba** [comment]
- here would be place for test case: https://github.com/rectorphp/rector/tree/master/packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture

**Comment by TomasVotruba** [comment]
This is the minimal limit of chain methods, that are removed. If you encrease it, your application might die on performance issues.

- https://github.com/rectorphp/rector/blob/108b78e6d9ba71bfafec52ba59b0e38e7d218ebd/packages/NodeTypeResolver/src/PHPStan/Scope/NodeVisitor/RemoveDeepChainMethodCallNodeVisitor.php#L24

**Comment by TomasVotruba** [comment]
Any update on this?

**Comment by TomasVotruba** [comment]
I'll make the configurable, so it's easier to handle it

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/pull/2567
