### ISSUE TITLE
GetParameterToConstructorInjectionRector does not handle parameters with dots "."

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#2460]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector v0.6.2 | dev-master pulled yesterday          |
| 7.2    | PHP 7.2.24-1+ubuntu16.04.1+deb.sury.org+1                               |
| php vendor/rector/rector/bin/rector process src --dry-run --set=symfony-constructor-injection
 

## Current Behaviour 

```
-        $isDebug   = $this->getParameter('kernel.debug');
+        $isDebug   = $this->kernel.debug;
```

## Minimal PHP Code Causing Issue

```php
<?php 
$isDebug = $this->getParameter('kernel.debug');
```

## Expected Behaviour
```
-        $isDebug   = $this->getParameter('kernel.debug');
+        $isDebug   = $this->kernelDebug;
```

There are many parameters in Symfony that include a dot in their name (run `php bin/console debug:container --parameters | grep .` to see them).

The GetParameterToConstructorInjectionRector does not account for that, and ends up making class properties with invalid names.

Replacing all dots with underscores before passing it off to the `propertyNaming->underscoreToName` would fix it, I believe. I'd be happy to offer a pull request if you are in agreement.

Btw, thank you for fixing #2360, I believe this project will save us a huge amount of time.

**Comment by TomasVotruba** [comment]
Thanks for report :+1:
