### ISSUE TITLE
Class 'Symplify\EasyCodingStandard\Exception\Configuration\SetNotFoundException' not found

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#2462]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector v0.6.2 | dev-master pulled yesterday          |
| 7.2    | PHP 7.2.24-1+ubuntu16.04.1+deb.sury.org+1                               |
| php vendor/rector/rector/bin/rector process src --dry-run --set=symfony-constructor-injection
 

## Current Behaviour 

```
[ERROR] Class 'Symplify\EasyCodingStandard\Exception\Configuration\SetNotFoundException' not found
```

## Minimal PHP Code Causing Issue

  

Not dependent on any PHP code.

## Expected Behaviour

An exception being displayed in the console which explains that I typed in the wrong set name like a dummy.

It looks like `Symplify\SetConfigResolver\SetResolver` throws a `Symplify\EasyCodingStandard\Exception\Configuration\SetNotFoundException` when you specify a set that does not exist, but EasyCodingStandard isn't required as part of rector, so it's not available on my system.

I guess EasyCodingStandard is listed as a require-dev for the project, but my understanding is require-dev only gets included when they are in the root, so me doing a`composer require rector/rector` won't add EasyCodingStandard, and thus the error.

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1:
