### ISSUE TITLE
[Solid] remove fluent rector

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#247]
Remove `return $this;` from code, to prevent unnecessary fluent

**Comment by carusogabriel** [comment]
I’ll try to take care of it 👨🏻‍💻

**Comment by TomasVotruba** [comment]
That would be great! :bowing_man: 

You can inspire here:
https://github.com/rectorphp/rector/blob/master/src/Rector/Dynamic/ValueObjectRemoverRector.php
Which removes values objects from code, e.g. `new String('name')` → `'name'`

**Comment by TomasVotruba** [comment]
This should follow rector that will change code, that is fluent no more.
E.g. 

```php
$git->addName()
    ->addEmail();
```

into

```php
$git->addName();
$git->addEmail();
```

**Comment by carusogabriel** [comment]
Should we refactor `Rector`, and also create a `Rector` for that?

**Comment by TomasVotruba** [comment]
That could be also used. I hope there are no fluent interfaces in this code... but there is no coding standard checker for that... yet

**Comment by carusogabriel** [comment]
@TomasVotruba Can you take this to you? I thought would be easy, but I'm not getting success on this :disappointed:

**Comment by TomasVotruba** [comment]
Sure, just open PR with what you've got so far :+1: I'll try to help 
Tests would be nice, and they don't have to pass yet
