### ISSUE TITLE
[PHP] CountOnNull on properties with PHPDoc shouldn't apply

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2474]
I've had the case in my code base that the following code change was triggered : 

```diff
/** @var string[] $array */
$array = $someObject->someMethod();

- if (count($array) > 0) {
+ if (is_countable($array) ? count($array) > 0 : 0) {

}
```

I was quite surprised by this proposition, as IMO a `string[]` doesn't need to be surrounded by `is_countable` (if the developer is misusing type hints/doc blocks, PHPStan should warn him).

I digged into it and even noticed there's a test Fixture that seems to affirm this behavior : 

`packages/Php71/tests/Rector/FuncCall/CountOnNullRector/Fixture/property_with_doc.php.inc`

Isn't that weird ?

**Comment by TomasVotruba** [comment]
Hi, it seems weird. 

Could you send failing test case to confirm?
Be sure to check PHP version in config for the test, so it's the same you use locally.

**Comment by gnutix** [comment]
I'm still having the issue using current `master` : 

```diff
-        if (count($command->tags) > 0) {
+        if ((is_countable($command->tags) ? count($command->tags) : 0) > 0) {
```

Where `$command->tags` is `@var SomeIdentifierClass[]`.

**Comment by TomasVotruba** [comment]
Without failing test case, there is not much to do

**Comment by gnutix** [comment]
I managed to create a reproducible code set in my playground repository : https://github.com/gnutix/rector-playground/pull/3 :)

**Comment by TomasVotruba** [comment]
> Maybe a clue : running on src/ produces the error, running on src/CreateExpenseHandler.php does not.

Any idea why?

**Comment by gnutix** [comment]
I guess it should be autoloaded properly, as Rector does not error out with autoloading messages as it often does.
