### ISSUE TITLE
Laravel FacadeStaticCallToConstructorInjectionRector

### ISSUE THREAD

**Issue by HDVinnie** [rectorphp/rector#2498]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | Rector v0.6.2        |
| PHP version    | PHP 7.4.0                               |
| Full Command   | vendor/bin/rector process /var/www/UNIT3D-Community-Edition/app --set laravel-static-to-injection  | 

## Current Behavior 
When using this command it will as it should turn things like `$seconds = config('hitrun.seedtime');` to `$seconds = $this->configRepository->get('hitrun.seedtime');` while of course adding the required code.

```
    /**
     * @var \Illuminate\Contracts\Config\Repository
     */
    private Repository $configRepository;

    public function __construct(Repository $configRepository)
    {
        $this->configRepository = $configRepository;
    }
```

The issue is that the original `$seconds = config('hitrun.seedtime');` was in a `public static function` so now the new `$seconds = $this->configRepository->get('hitrun.seedtime');`  it changed it to throws a `Using $this when not in object context` because its a static function.

**Comment by TomasVotruba** [comment]
Hi, what's the expected behavior?

**Comment by HDVinnie** [comment]
I would assume to not change the original helper usage if its within a `static function` seeing you cannot use `$this` in a `static function`.

**Comment by TomasVotruba** [comment]
I see, so if it's in a static method, it should skip it?

**Comment by HDVinnie** [comment]
> I see, so if it's in a static method, it should skip it?

Yes.
