### ISSUE TITLE
Impossible to obtain the desired result. Too little documentation and examples.

### ISSUE THREAD

**Issue by BoGnY** [rectorphp/rector#2513]
| Subject | Details |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.4 |
| PHP version | PHP 7.3.11 |
| Full Command | `vendor\bin\rector.bat process --config rector.yaml --dry-run --debug` | 

## Current Behaviour 

`rector.yaml`:
```yaml
parameters:
  php_version_features: '7.3'
  auto_import_names: true
  import_short_classes: false
  import_doc_blocks: false
  paths:
    - 'app'
  exclude_paths:
    - 'app/Http/Controllers/Api/V1/Auth/*'
services:
  Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector: ~
  Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector: ~
```

## Minimal PHP Code Causing Issue

`app/Http/Controllers/Api/V1/Auth/AuthenticateController.php`:
```php
<?php

namespace App\Http\Controllers\Api\V1\Auth;

use App\Http\Controllers\Controller;
use App\Http\Resources\User as UserResource;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthenticateController extends Controller
{
    /**
     * Return the user's access token.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return UserResource|\Illuminate\Http\JsonResponse
     */
    public function authenticate(Request $request): mixed
    {
        if (Auth::attempt(['email' => $request->input('email'), 'password' => $request->input('password')])) {
            $user = User::where('email', $request->input('email'))->first();

            return (new UserResource($user))
                ->additional(['meta' => [
                    'access_token' => $user->api_token
                ]]);
        }

        return response()->json(['message' => 'This action is unauthorized.'], 401);
    }
}
```

## Expected Behaviour

The expected result is that this file is excluded... Unfortunately, however, the result is the following:

`app/Http/Controllers/Api/V1/Auth/AuthenticateController.php`:
```php
<?php

namespace App\Http\Controllers\Api\V1\Auth;

use App\Http\Controllers\Controller;
use App\Http\Resources\User as UserResource;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthenticateController extends Controller
{
    /**
     * Return the user's access token.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return UserResource|\Illuminate\Http\JsonResponse
     */
    public function authenticate(Request $request): \UserResource
    {
        if (Auth::attempt(['email' => $request->input('email'), 'password' => $request->input('password')])) {
            $user = User::where('email', $request->input('email'))->first();

            return (new UserResource($user))
                ->additional(['meta' => [
                    'access_token' => $user->api_token
                ]]);
        }

        return response()->json(['message' => 'This action is unauthorized.'], 401);
    }
}
```

This is the log:
```log
File "C:\www\my-blog/vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 65"
File "C:\www\my-blog\vendor\rector\rector/../../autoload.php" is about to be loaded in "AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 97"
Rector v0.6.3
Config file: rector.yaml

[parsing] app/Http/Controllers/Api/V1/Auth/AuthenticateController.php
[refactoring] app/Http/Controllers/Api/V1/Auth/AuthenticateController.php
    [applying] Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector
    [applying] Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector
    [applying] Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector
[printing] app/Http/Controllers/Api/V1/Auth/AuthenticateController.php

1) app/Http/Controllers/Api/V1/Auth/AuthenticateController.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -17,7 +17,7 @@
      *
      * @return UserResource|\Illuminate\Http\JsonResponse
      */
-    public function authenticate(Request $request): mixed
+    public function authenticate(Request $request): \UserResource
     {
         if (Auth::attempt(['email' => $request->input('email'), 'password' => $request->input('password')])) {
             $user = User::where('email', $request->input('email'))->first();
    ----------- end diff -----------

Applied rules:

 * Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector

 [OK] Rector is done! 1 changed file
```

The problems here are multiple:
- `mixed` is replaced with an alias (that break the code)
- a file that should be ignored is instead rector-ized
- I have not found any configuration/example to specify which rector services (so without sets) to use with some path exclusions (I will have tried dozens of combinations without success)

Thanks.

**Comment by TomasVotruba** [comment]
Thanks for reporting issue!

> a file that should be ignored is instead rector-ized

You're doing right, but there is no Windows developers on this project. So the Windows support is not very well tested: Looking at code, I assume it will be related to \ /  slashes.

I assume it will be in the method, that handles excluded files: https://github.com/rectorphp/rector/blob/67c4f76268e83b699b23f1fd96d549510a3b823b/src/FileSystem/FilesFinder.php#L159-L171


> mixed is replaced with an alias (that break the code)

How it breaks the code?

**Comment by BoGnY** [comment]
> > a file that should be ignored is instead rector-ized
> 
> You're doing right, but there is no Windows developers on this project. So the Windows support is not very well tested: Looking at code, I assume it will be related to \\ / slashes.

Yes, you are right. On Ubuntu machine the file is ignored correctly.
Maybe can be added a check that, if OS is Windows, perform a replace of slashes??

> > mixed is replaced with an alias (that break the code)
> 
> How it breaks the code?

The problems are:
- `mixed` are replaced by `\UserResource` that does not exists. `UserResource` is an alias and "leading slash" it break the code ("Class not found")
- there are two different return type for that function:
  - `UserResource` which is an alias for `\App\Http\Resources\User`
  - and `\Illuminate\Http\JsonResponse`

**Comment by TomasVotruba** [comment]
> Maybe can be added a check that, if OS is Windows, perform a replace of slashes??

Could you try that and verify it works? If so, please send PR

> The problems are:

I see. Could you provide whole + minimal code from  `app/Http/Controllers/Api/V1/Auth/AuthenticateController.php` that causes it?
Alias problem should will be easy to fix, just need the code sample to replicate error.


> Finally, is it possible to specify, for a single Rector service, a file exclusion??

There are 2 way - one is described in README:

https://github.com/rectorphp/rector#exclude-paths-and-rectors

I'll add the otherway now

**Comment by BoGnY** [comment]
> > Maybe can be added a check that, if OS is Windows, perform a replace of slashes??
> 
> Could you try that and verify it works? If so, please send PR

Ok, I will try in the next few days.

> I see. Could you provide whole + minimal code from `app/Http/Controllers/Api/V1/Auth/AuthenticateController.php` that causes it?  
> Alias problem should will be easy to fix, just need the code sample to replicate error.

The code above is all the code of my `app/Http/Controllers/Api/V1/Auth/AuthenticateController.php`. Create the dirs tree, and with this simple `rector.yaml`, you can reproduce the issue:

```yaml
parameters:
  php_version_features: '7.3'
  auto_import_names: true
  import_short_classes: false
  import_doc_blocks: false
  paths:
    - 'app'
services:
  Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector: ~
```

> 
> > Finally, is it possible to specify, for a single Rector service, a file exclusion??
> 
> There are 2 way - one is described in README:
> 
> [https://github.com/rectorphp/rector#exclude-paths-and-rectors](https://github.com/rectorphp/rector#exclude-paths-and-rectors)
> 
> I'll add the otherway now... UPDATE, there it is: [https://github.com/rectorphp/rector/pull/2519/files](https://github.com/rectorphp/rector/pull/2519/files)

Thanks, my goal was to apply multiple Rectors to all files, but excluding one of those Rectors from a specific file (and only that). So the second way was perfect for me 👍

**Comment by TomasVotruba** [comment]
> The code above is all the code of my app/Http/Controllers/Api/V1/Auth/AuthenticateController.php. Create the dirs tree, and with this simple rector.yaml, you can reproduce the issue:

That won't work. It needs all the dependencies, so it can be reproducible.

We need failing test case for `ReturnTypeDeclarationRectorTest`, that fail.
To add a test, just copy fixture here:

https://github.com/rectorphp/rector/tree/master/packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture

And add file in this format:

```
A (input code)
-----
B (expecte code after the change)
```

The smaller the code the better, 5 lines should show what happens there

**Comment by BoGnY** [comment]
I've re-tested it with latest version 0.6.10 and this error is no more present 👍

**Comment by TomasVotruba** [comment]
That's great. Thanks for confirmation :+1:
