### ISSUE TITLE
Detect feature-detecting code as dead code

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#2540]
Its a good practice to use feature detects instead of hardcoding certain version-checks or try to sniff the environment.

This can lead to dead code, e.g.

```php
        // prevent session locking trough other addons
        if (function_exists('session_abort')) {
            session_abort();
        } else {
            session_write_close();
        }
```

This code is written like that because depending on the php-version the function in question might exists or not. In case it is missing we have implemented a less optimal alternative. 

When upgrading the min-php version of the project this code might easily be dead, because the function will always exist.

Maybe there is some way to detect this kind of codes and report it as dead

**Comment by TomasVotruba** [comment]
Rector needs before/after, so how would you refactor it?

How would you detect which PHP version is it used in?

**Comment by staabm** [comment]
In this concrete case it would be

Before (project supports php 5.5+ - defined in composer.json)
```
        // session locking trough other addons
        if (function_exists('session_abort')) {
            session_abort();
        } else {
            session_write_close();
        }
```

After (php 7.1+)
```
        // session locking trough other addons
            session_abort();
```

**Comment by TomasVotruba** [comment]
That's pretty neat, I like it

How would you make such set?

**Comment by staabm** [comment]
> How would you make such set?

Not sure what you mean?

**Comment by TomasVotruba** [comment]
*name

**Comment by staabm** [comment]
The example itself is some kind  of dead-code detection

**Comment by TomasVotruba** [comment]
It might be, but it depends on PHP version. Same way code quality could be considered dead code, but we try to use descriptive categories for rules, so it's easier to manage them later when there will be hunderds of rules. If most of them would in *dead code*, it might be a mess.

I think it's rather back/future compatibility or polyfill code

**Comment by staabm** [comment]
> I think it's rather back/future compatibility or polyfill code

This describes at best what my initial intension was :)

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/pull/2569
