### ISSUE TITLE
How should I deal with ambiguous class resolution?

### ISSUE THREAD

**Issue by bentinata** [rectorphp/rector#2542]
Currently I'd just fork the offending package, and maybe make a request to the package author to merge my changes.

Any other solutions?

**Comment by TomasVotruba** [comment]
I'm not sure I understand. Could you provide breaking code, so I have better idea?

**Comment by TomasVotruba** [comment]
This needs to be solved manually now, as Rector/PHPStan needs unique classes to work with.

**Comment by tmotyl** [comment]
I’ve run into the ambigous class error when trying to set up rector for Magento 1 code base. 
In Magento its common to replace core classes with modified version on autoload level (autoloader first check for the class in „local” path and the in the „core” path.

So autoloader know which class should be loaded.
Unfortunatelly rector failed (on ambigous class from magento core), despite having custom autoloader configured and having path to analyze narrowed to a single package (which is a 3rd party module).

How can I solve situations like that?

**Comment by TomasVotruba** [comment]
Hi, I'm not sure how to solve this issue even without Rector. 
I always convert every project into `composer.json` valida autoload, then I use Rector.

**Comment by tmotyl** [comment]
I think the problem is that rector finds files  containing classes which are never returned by autoloader (autoloader picks class from different location).

**Comment by TomasVotruba** [comment]
Not sure. If you find a way to fix it, feel free to send PR

**Comment by tmotyl** [comment]
maybe it will be useful for others
I've created an example config for magento 1 which works with rector 0.11.53
https://gist.github.com/tmotyl/b8d86fad64b4afffbebb1000116f7d28
