### ISSUE TITLE
PHPStan 0.12+ @implements and @extends annotations

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2544]
I've encountered two new errors related to PHPStan 0.12 support for generics : 

```                                                                                                                        
 [ERROR] Could not process "test.php"  
         file, due to:                                                                                                  
         "Implement "PHPStan\PhpDocParser\Ast\PhpDoc\ExtendsTagValueNode" to                                            
         "Rector\BetterPhpDocParser\Attributes\Ast\AttributeAwareNodeFactory::createFromPhpDocValueNode"".              
```

```                                                                   
 [ERROR] Could not process "test2.php" file, due  
         to:                                                                                                            
         "Implement "PHPStan\PhpDocParser\Ast\PhpDoc\ImplementsTagValueNode" to                                         
         "Rector\BetterPhpDocParser\Attributes\Ast\AttributeAwareNodeFactory::createFromPhpDocValueNode"".              
```

```php
<?php
# test.php

/**
 * @extends ArrayCollection<int, SomeEntity>
 */
final class SomeEntityCollection extends ArrayCollection
{
    // ...
}
```

```php
<?php
# test2.php

/**
 * @implements IteratorAggregate<int, SomeObject>
 */
final class SomeObjectIterator implements IteratorAggregate
{
    // ...
}
```

**Comment by TomasVotruba** [comment]
Could you add it then?

**Comment by gnutix** [comment]
I'm not sure how to handle this one. I don't really understand what Rector is trying to do with these annotations. I'm missing some background here.

**Comment by TomasVotruba** [comment]
Sure, I'll help with that. All you need is in the exception:

This method `AttributeAwareNodeFactory::createFromPhpDocValueNode()` is missing `PHPStan\PhpDocParser\Ast\PhpDoc\ExtendsTagValueNode`

1) New `$phpDocTagValueNode instanceof ExtendsTagValueNode` must be added, like this one:
https://github.com/rectorphp/rector/blob/b221a16f0698be754412e5e78bcbf181023c8760/packages/BetterPhpDocParser/src/Attributes/Ast/AttributeAwareNodeFactory.php#L160-L162

2) New `AttributeAwareExtendsTagValueNode` must be added, basically copy of `AttributeAwareGenericTagValueNode`

**Comment by snapshotpl** [comment]
Same problem in my codebase. @gnutix are you working on fix?
