### ISSUE TITLE
[DeadCode] Trait inheritance and removing unused private properties

### ISSUE THREAD

**Issue by panychek** [rectorphp/rector#2549]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.5 |
| PHP version    | 7.3.13 |
| Full Command   | vendor/bin/rector process src --set deadcode --dry-run  | 

## Current Behaviour 

The `RemoveUnusedPrivatePropertyRector` recipe wants to get rid of a private property even if it's being used in some of the traits this class depends on.

![Screenshot from 2020-01-03 23-03-50](https://user-images.githubusercontent.com/29440141/71743204-67791680-2e7d-11ea-8d85-f68e7ebdbac0.png)

## Minimal PHP Code Causing Issue

**ClassA.php**:

```php
<?php 

namespace Test;

class ClassA
{
    use TraitA;

    private $property = 10;
}

```

**TraitA.php**:

```php
<?php

namespace Test;

trait TraitA
{
    use TraitB;
}
```

**TraitB.php**:

```php
<?php

namespace Test;

trait TraitB
{
    public function foo()
    {
        echo $this->property;
    }
}
```

## Expected Behaviour
The existing code should remain intact, since it's not really dead. If we access the property within `TraitA`, everything works fine.

**Comment by TomasVotruba** [comment]
We need test case in `RemoveUnusedPrivatePropertyRectorTest`
