### ISSUE TITLE
Removed last space in Doctrine annotation

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#2551]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | dev-master@e66d4cf          |
| PHP version    | PHP 7.3.13                               |

## Current Behaviour 

```
    ---------- begin diff ----------
--- Original
+++ New
@@ -23,7 +23,7 @@

     /**
      * @ORM\ManyToOne(targetEntity="Entity\Product", inversedBy="photos")
-     * @ORM\JoinColumn(name="product_id", referencedColumnName="id",nullable=false,onDelete="CASCADE")
+     * @ORM\JoinColumn(name="product_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
      * @var Product
      */
     private $product;
    ----------- end diff -----------

Applied rules:

 * Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
```
I would expect remove all spaces or do nothing because Doctrine (or another standard?) annotation.

**Comment by TomasVotruba** [comment]
It actually adds spaces so the format is standard. See https://github.com/rectorphp/rector/blob/e66d4cfab718eb36a82aa2fb506df83d07d66646/packages/BetterPhpDocParser/src/PhpDocNode/Doctrine/Property_/JoinColumnTagValueNode.php#L82-L119 for more.

This would be really hard to fix, as there no ast format preserving for doc nodes.

**Comment by TomasVotruba** [comment]
I recommend to use regexp in PHPStorm to add spaces after `,` in annotations.
Or let Rector do it. Now it would be waste of energy.

**Comment by snapshotpl** [comment]
You have right. I :eyes: other change that it really was. Sorry for that.
