### ISSUE TITLE
Change return type breaking interface

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#2552]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | dev-master@e66d4cf          |

I have interface:
```
interface Query
{
    /**
     * @throws AccountNotExist
     */
    public function get(string $email): UuidInterface;
}
```
And test implementation:
```
final class NotFoundQuery implements Query
{
    /**
     * @throws AccountNotExist
     */
    public function get(string $email): UuidInterface
    {
        throw new AccountNotExist();
    }
}
```

However rector try to change return type to `void` in implementation.

```
    ---------- begin diff ----------
--- Original
+++ New
@@ -12,7 +12,7 @@
     /**
      * @throws AccountNotExist
      */
-    public function get(string $email): UuidInterface
+    public function get(string $email): void
     {
         throw new AccountNotExist();
     }
    ----------- end diff -----------

Applied rules:

 * Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
 * Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector
```

**Comment by TomasVotruba** [comment]
Could you add failing test case to `ReturnTypeDeclarationRectorTest`?

**Comment by snapshotpl** [comment]
I cannot reproduce this case in tests. Maybe it depends on configuration?

**Comment by TomasVotruba** [comment]
If you have empty `rector.yaml`, the config should be the same.

Have you tried moving the interface to `Source` instead of `Fixtures` in test?

**Comment by TomasVotruba** [comment]
Closing as stale.

If still a problem, please add failing https://getrector.org/demo
