### ISSUE TITLE
replacing twig function

### ISSUE THREAD

**Issue by craigh** [rectorphp/rector#2554]
## How can I write a custom rector to replace a twig function?

I would like to replace `{{ __(<anycontent>) }}` with something like `{% trans %}<anycontent>{% entrans %}`

I have been looking at your docs for a while and don't see any twig-related nodes. Have I completely missed something?

I'm sorry in advance if this is the wrong forum for questions. I looked on SO and slack but didn't find something. please let me know if I should take my questions elsewhere.

**Comment by TomasVotruba** [comment]
Hi, Rector is PHP-only tool at the moment. There might be some RectorTwig in the future, if someone would take the lead. It would be great addition :+1: 

Good inspiration to start such project could be: https://github.com/Symplify/LatteToTwigConverter

As a quick solution, I'd use regexp, see https://regex101.com/r/xTRMzp/2/

From top of my head:

```php
$newFileContent = Nette\Utils\Strings::replace(
    $fileContent, 
    '#{{\s+__\((?<content>.*?)\)\s+}}#',
    '{% trans %}$1{% entrains %}'
);
```

**Comment by craigh** [comment]
ah. bummer. I guess I misunderstood. I appreciate the quick response. I'll look into other solutions. thank you!

**Comment by TomasVotruba** [comment]
Good luck! 

Let me know what you'll use in the end, I'm curious if there is a tool for it
