### ISSUE TITLE
Add simple regex replace

### ISSUE THREAD

**Issue by craigh** [rectorphp/rector#2564]
create a rector that takes a regex arg that can replace/reformat with second arg

e.g. refs #2554 

```
$newFileContent = Nette\Utils\Strings::replace(
    $fileContent, 
    '#{{\s+__\((?<content>.*?)\)\s+}}#',
    '{% trans %}$1{% entrains %}'
);
```

ideally, the filetype could be limited by another arg

**Comment by TomasVotruba** [comment]
I'd need some working prototype of this to add it to Rector. There have been some *ideas* about Twig, but no real result.

**Comment by craigh** [comment]
oof. 

OK - well, I didn't mean this to be twig specific. I think it could be a useful **very generic tool.** I was just thinking a rector that takes three args:

1. regex search
2. replace
3. filetype

then rector scans for filetypes and applies the regex search and replace as needed.

**Comment by TomasVotruba** [comment]
As stated in the first issue, Rector handles only PHP. So this is out of scope of this specific repository.
 
It doesn't mean anyone cannot start similar tool for what you suggest. I bet it could fit into Rectors instant refactoring ecosystem.

**Comment by craigh** [comment]
understood. sorry to bother

**Comment by TomasVotruba** [comment]
No troubles.
