### ISSUE TITLE
Phalcon 4: The save() method no longer accepts parameters to set data.

### ISSUE THREAD

**Issue by ruudboon** [rectorphp/rector#2571]
From the [docs](https://docs.phalcon.io/4.0/en/upgrade#save). 

> For Phalcon 4 The save() method no longer accepts parameters to set data. You can use assign instead.

We missed this in the docs and just added this. I think this is also missing from rector. Can we add this to rector?
 
## Diff 

```diff
-$model->save($data);
+$model->assign($data);
+$model->save();
```

**Comment by TomasVotruba** [comment]
I'm on it
