### ISSUE TITLE
Remove dead code based on php version

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#2573]
## Before

```php
if (1 == version_compare(PHP_VERSION, '7.2', '<')) {
  // do something1
} else if (1 == version_compare(PHP_VERSION, '7.3', '<')) {
  // do something2
} else {
  // do something3
}
```

## After running with min php version = 7.3
```
  // do something3
```

Inspired by https://github.com/redaxo/redaxo/blob/46d0ace6cd1ca0d40fa233abd637bea53c694daa/redaxo/src/core/pages/setup.php#L147

Similar issue https://github.com/rectorphp/rector/issues/2574

**Comment by TomasVotruba** [comment]
Work in progress...
