### ISSUE TITLE
PHPStan\Analyser\MutatingScope constructor error

### ISSUE THREAD

**Issue by ghostika** [rectorphp/rector#2580]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | 0.6.x-dev@9a330e2         |
| PHP version    |  7.3.2-3                               |
| Full Command   | vendor/bin/rector process bin src  --set symfony41 --dry-run  | 

## Current Behaviour 

```
 [ERROR] Could not process ".../Model/Contact.php" file, due to:
         "Argument 3 passed to PHPStan\Analyser\MutatingScope::__construct() must be an instance of
         PHPStan\Type\DynamicReturnTypeExtensionRegistry, instance of Rector\PhpParser\Printer\BetterStandardPrinter
         given, called in
         phar:///var/www/symfony/vendor/rector/rector-prefixed/rector/packages/NodeTypeResolver/src/PHPStan/Scope/ScopeF
         actory.php on line 41".
```

I just installed `rector/rector-prefixed` and tried to run the symfony41 update and got these error and also rector wants to remove all the namespace import, e.g.:
```
-use Psr\Log\LoggerInterface;
+ LoggerInterface;
```

Maybe this is connected to the main error.

**Comment by TomasVotruba** [comment]
Related https://github.com/rectorphp/rector/pull/2575

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector/pull/2575
