### ISSUE TITLE
[Symfony] Process error with Internationalized routing

### ISSUE THREAD

**Issue by ghostika** [rectorphp/rector#2585]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.6          |
| PHP version    |  PHP 7.3.2                            |
| Full Command   | vendor/bin/rector process bin src --set symfony41 --dry-run  | 

## Current Behaviour 

```
 [ERROR] Could not process "/var/www/symfony/src/Controller/ContactController.php" file, due to:
         "Argument 1 passed to Rector\BetterPhpDocParser\PhpDocNode\Symfony\SymfonyRouteTagValueNode::__construct() must
         be of the type string, null given, called in
         /var/www/symfony/vendor/rector/rector/packages/BetterPhpDocParser/src/PhpDocNodeFactory/Symfony/SymfonyRoutePhp
         DocNodeFactory.php on line 40".
```

## Minimal PHP Code Causing Issue

```php
class ContactController
{
    /**
     * @Route({
     *     "en": "/send-us-an-email",
     *     "nl": "/stuur-ons-een-email"
     * }, name="contact")
     */
    public function send()
    {
        // ...
    }
}
```

It looks like the problem is, that the constructor of the `SymfonyRouteTagValueNode` expects a string for the $path, but actually it can be an array.

**Comment by TomasVotruba** [comment]
What happens when you update the SymfonyRouteTagValueNode to work with array as well?

**Comment by ghostika** [comment]
I just did a little bit of digging. Changing the argument to array would not work, because in this case, internationalized routes are not on the `path` property but on the `localizedPaths` and `path` is then null. 
Making `path` nullable would solve this problem, but I'm not sure, what other problems would arise from that.

The object representation of the route from my post in the `SymfonyRoutePhpDocNodeFactory` class, what is then provided for `SymfonyRouteTagValueNode`class.

<img width="384" alt="Screenshot 2020-01-07 at 09 07 54" src="https://user-images.githubusercontent.com/2512578/71878964-3a528f80-312d-11ea-808d-53a35b068a4a.png">

**Comment by TomasVotruba** [comment]
> Making path nullable would solve this problem, but I'm not sure, what other problems would arise from that.

I think that's the solution. Looking at annotation object, it can be.

**Comment by TomasVotruba** [comment]
Could you send PR with that?
