### ISSUE TITLE
Class 'Symplify\AutowireArrayParameter\DependencyInjection\CompilerPass\AutowireArrayParameterCompilerPass' not found

### ISSUE THREAD

**Issue by localheinz** [rectorphp/rector#2596]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | `0.6.6`|
| PHP version    | `7.3.13`|
| Full Command   | `vendor/bin/rector --help`  | 

## Minimal PHP Code Causing Issue

Running

```
$ php -v
```

yields

```
PHP 7.3.13 (cli) (built: Dec 18 2019 16:08:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies
```

I ran

```
$ composer require --dev rector/rector:~0.6.6
```

in an empty directory (entirely new project without `composer.json`).

Running

```
$ ./vendor/bin/rector process --help
```

yields

```
 [ERROR] Class 'Symplify\AutowireArrayParameter\DependencyInjection\CompilerPass\AutowireArrayParameterCompilerPass' not
         found
```

## Expected Behaviour

A bit of help.

**Comment by TomasVotruba** [comment]
Should be fixed in 0.6.7, just released.

Could you confirm?

**Comment by localheinz** [comment]
Can confirm!

Thank you, @TomasVotruba!

**Comment by OskarStark** [comment]
Thanks
