### ISSUE TITLE
[ParamTypeDeclarationRector] adds types when parent interface have none (breaks PHP)

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2597]
Given a class : 

```php
<?php

declare(strict_types=1);

namespace OurVendor\Symfony\Serializer;

use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;

final class SomeClassNormalizer implements DenormalizerInterface
{
    /**
     * @param mixed $data
     * @param string $class
     * @param string|null $format
     * @param mixed[] $context
     */
    public function denormalize($data, $class, $format = null, array $context = []): ?SomeClass
    {
        // ...
    }
}
```

Produces the following change : 

```diff
-    public function denormalize($data, $class, $format = null, array $context = []): ?Snowflake
+    public function denormalize($data, string $class, ?string $format = null, array $context = []): ?SomeClass
``` 

Even though the parent interface is : 

```php
<?php
namespace Symfony\Component\Serializer\Normalizer;
// ...
interface DenormalizerInterface
{
    /**
     * Denormalizes data back into an object of the given class.
     *
     * @param mixed  $data    Data to restore
     * @param string $type    The expected class to instantiate
     * @param string $format  Format the given data was extracted from
     * @param array  $context Options available to the denormalizer
     *
     * @return object|array
     */
    public function denormalize($data, $type, $format = null, array $context = []);

    // ...
}
```

Which breaks PHP (in versions prior to 7.4 at least, didn't checked with the new type covariance things in 7.4).

**Comment by TomasVotruba** [comment]
That should not happen in case you don't have PHP 7.4.

Could you add failing test case?

**Comment by gnutix** [comment]
What is weird is that there is already a test case covering this (as far as I understood) : `packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/external_scope.php.inc` and the code already seems to handle with  packages/TypeDeclaration/src/Rector/FunctionLike/ParamTypeDeclarationRector.php:143 which calls `$this->vendorLockResolver->isParameterChangeVendorLockedIn()`. :thinking:

**Comment by TomasVotruba** [comment]
I'd try to use minimal 3-lines example instead of 50. It might be easier to spot the bug

**Comment by TomasVotruba** [comment]
Sometimes I also create test in `whatever` directory in the Rector root. Put code there, put 3rd party code to `src` and run Rector on it:

```bash
bin/rector p whatever/TheFile.php
```

It helped me to discover those edgy bugs.

If that works, feel free to commit it and add:

```bash
bin/rector p whatever/TheFile.php
```

to travis. That way I can see it and then fix it

**Comment by gnutix** [comment]
I can't reproduce anymore with the latest version of Rector (`0.6.x-dev@a21b805`).
