### ISSUE TITLE
The compiler is dumped when running the PHAR and systematically even outside of the PHAR

### ISSUE THREAD

**Issue by theofidry** [rectorphp/rector#2611]
Reading https://www.tomasvotruba.com/blog/2019/12/02/how-to-box-symfony-app-to-phar-without-killing-yourself/ , especially [this line](https://www.tomasvotruba.com/blog/2019/12/02/how-to-box-symfony-app-to-phar-without-killing-yourself/#nobody-ever-used-symfony-in-phar-before), I'm certain there is something wrong here.

So checking locally, I with a few dump statements, I can confirm my suspicions. If you go to `vendor/symfony/http-kernel/Kernel.php`, you can do:

```php
protected function initializeContainer()
    {
        $class = $this->getContainerClass();
        $cacheDir = $this->warmupDir ?: $this->getCacheDir();
        $cache = new ConfigCache($cacheDir.'/'.$class.'.php', $this->debug);
        $cachePath = $cache->getPath();

        // Silence E_WARNING to ignore "include" failures - don't use "@" to prevent silencing fatal errors
        $errorLevel = error_reporting(\E_ALL ^ \E_WARNING);

        try {
            if (file_exists($cachePath) && \is_object($this->container = include $cachePath)
                && (!$this->debug || (self::$freshCache[$cachePath] ?? $cache->isFresh()))
            ) {
// Added debug statement here
                \file_put_contents('php://stdout', 'container is fresh'.\PHP_EOL);
                self::$freshCache[$cachePath] = true;
                $this->container->set('kernel', $this);
                error_reporting($errorLevel);

                return;
            }
        } catch (\Throwable $e) {
        }

// Added debug statement here
        \file_put_contents('php://stdout', 'init container'.\PHP_EOL);

        // ...
    }
```

And if I do:

```
$ bin/rector --version
boot
init container
Rector 0.6.x-dev@9ae9807
$ bin/rector --version
boot
init container
Rector 0.6.x-dev@9ae9807
```

Note that this happens _each time_. So even without talking about the PHAR here, there is already an issue: your container is being dumped _every single time_ instead of done once and re-used. Obviously not a performance killer, but that can definitely be improved!

Now let's talk about the PHAR. The issue is actually simple and described in details [here](https://github.com/humbug/box/blob/master/doc/symfony.md#symfony-support). From your article you ran into the issue of the globs not working properly. My point would be to say you should never need them in the first place: you should see your PHAR as if you packaged your application in a read-only container ready to be used for production purposes. Hence you need to make sure its cache is warmed up properly so that there is no write occurring at runtime.

But I would argue this is going to be hard to do as long as the first issue described is not solved. The way you do it in tradition Symfony is described in the article: dump the prod settings, warm up the cache and ship the PHAR. It sets those settings in stone and the _dumped_ compiler is shipped in the PHAR and won't cause any issue at runtime because should not try to compile itself again. Since you are consuming the Symfony packages here, you might need a few tweaks but I don't think it should be too hard

**Comment by TomasVotruba** [comment]
I'm not sure what the issue is, I don't understand it at all.

> ...a few tweaks but I don't think it should be too hard

Could you send PR to fix whatever the issue you see?

**Comment by theofidry** [comment]
>I'm not sure what the issue is, I don't understand it at all.

The issue is that your container is being initialized at each run, which means whenever you are booting the Symfony kernel it will:

- collect all the service definitions
- parse those service definitions
- resolve those service definitions
- dump the resolved container
- use the dumped container

Which is a very expansive process. Which is why the resolved container can be dumped and re-used so that you avoid steps 1 to 4.

>Could you send PR to fix whatever the issue you see?

I'm too unfamiliar with the codebase & too busy with Infection atm to be able to dig into that. Plus from the brief look I saw it might require to change the way you handle the kernel parameters (environment & debug).

**Comment by TomasVotruba** [comment]
I see.

If you change a parameter config, lets say password to a database, in normal Symfony app. The container will rebuild once on deploy and then it will stay the same on production.

If you have CLI application, anyone can change parameter before each run, e.g. add new Rector set or ignore rule. That's on-purpose architecture of CLI app, so it can rebuild container on config change.

So what you experience is expected in configurable CLI applicatoins.

**Comment by theofidry** [comment]
Do I understand correctly that you inject the user config directly in the
container potentially changing its configuration? If this cannot be changes
then this is indeed a problem.

You then indeed would need to work around the glob thing the way you did.
Still maybe an improvement then would be to find a way to dump the
initialised container: it would avoid attempting to write in the PHAR which
is another issue

**Comment by TomasVotruba** [comment]
> Do I understand correctly that you inject the user config directly in the
container potentially changing its configuration?

Yes, Same way you configure PHPUnit with `phpunit.xml`.

> You then indeed would need to work around the glob thing the way you did.
Still maybe an improvement then would be to find a way to dump the
initialised container: it would avoid attempting to write in the PHAR which
is another issue

It's rather bug in Symfony, but not useful to invest time in, since I'm the only one who builds *active* Symfony apps in PHARS.

**Comment by theofidry** [comment]
It’s a different issue though. Neither PHPUnit, PHP-Scoper, Box or
Infection have a dynamic configuration that alters the application
container itself. It’s especially more problematic in your case because of
the nature of the Symfony container: it’s does IO lookups for resolving it
and IO writes to dump itself.

So the issue it’s not the fact that you use a Symfony app for a CLI, but
that your dynamic configuration directly changes the container
configuration.

Anyway, it’s a design choice like another, burn it clears up a bit more why
Rector was much harder to get working with PHAR than another app.

Feel free to close the issue then, since the reported bug is the expected
behaviour. I can’t from my phone :)

**Comment by TomasVotruba** [comment]
> Symfony container: it’s does IO lookups for resolving it
and IO writes to dump itself.

Indeed, it's not ready for it :) I consider it a bug, because PHAR are somewhare supported.

> Anyway, it’s a design choice like another, burn it clears up a bit more why
Rector was much harder to get working with PHAR than another app.

That's a relief, I'm very happy to read it from you. I felt really stupping hitting all these walls, when other made their PHAR compilation work.

> Feel free to close the issue then, since the reported bug is the expected
behaviour. I can’t from my phone :)

Sure! Thanks for feedback :+1:
