### ISSUE TITLE
[NFR] Detect deprecated nested ternary operators for PHP74

### ISSUE THREAD

**Issue by ruudboon** [rectorphp/rector#2621]
## Diff 
Would be nice to detect and replace this deprecated method (https://www.php.net/manual/en/migration74.deprecated.php) 

```diff
-1 ? 2 : 3 ? 4 : 5;   // deprecated
+(1 ? 2 : 3) ? 4 : 5; // ok

Or 
-1 ? 2 : 3 ? 4 : 5;   // deprecated
+1 ? 2 : (3 ? 4 : 5); // ok
```

**Comment by TomasVotruba** [comment]
I tried it before and PHP-Parser doesn't allow such a detail syntax modification.
It's job for coding standard, that can work with `(` or `)`

**Comment by ruudboon** [comment]
Okido. Let's close it in that case. Thnx

**Comment by TomasVotruba** [comment]
:+1: 


Same goes for:

```diff
-$values{$1};
+$values[$1];
```

etc.
