### ISSUE TITLE
[CodingStyle] Why implement them as Rector instead of Slevomat's Sniffs or PhpCsFixer's Fixers ?

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2626]
I'm currently setting up coding standards tools on CI, and I have so far ECS and Rector.

```yaml
# rector.yml
parameters:
    sets:
        - 'coding-style'
```

```yaml
# easy-coding-standard.yaml
parameters:
    sets:
        - 'psr12'
```

Let's say some developer adds a line `private const TEST1 = 1, TEST2 = 2;` in a class. The final (proper) code for our standards should be :

```
/**
 * @var int
 */
private const TEST1 = 1;

/**
 * @var int
 */
private const TEST2 = 2;
```

Currently, here's how it works : 

1. Run Rector : 

```
/**
 * @var int
 */
const TEST1 = 1;
const TEST2 = 2;
```

Applied rules:

 * Rector\CodingStyle\Rector\ClassConst\SplitGroupedConstantsAndPropertiesRector
 * Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector

1. Run Rector again : 

```
/**
 * @var int
 */
const TEST1 = 1;

/**
 * @var int
 */
const TEST2 = 2;
```

Applied rules:

 * Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector

3. Run ECS : 

```
/**
 * @var int
 */
public const TEST1 = 1;

/**
 * @var int
 */
public const TEST2 = 2;
```

Applied fixers:

* PhpCsFixer\Fixer\ClassNotation\VisibilityRequiredFixer

I find these steps quite tedious (and more importantly : impossible to automate !), as they force the developer to have only a "partial fix" proposed by the CI output on the first run, which he applies, pushes, waits, only to see the build declined again by another needed partial fix - and that around and around).

And so I'm wondering : wouldn't it be better to have the CodingStyle Rectors implemented as PhpCsFixer Fixers insteads ? Any reason (technical, political, ...) for it not being the case from the start ?

Thanks for your thoughts.

(and while we're here : should there be some kind of priority set between Rector\CodingStyle\Rector\ClassConst\SplitGroupedConstantsAndPropertiesRector and Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector ?)

**Comment by TomasVotruba** [comment]
I'm not against implementing any Rector rules as cs fixer.

**Comment by TomasVotruba** [comment]
Cs fixers works the same way. Sometimes you need to re-run it few times to make them complete. It's not possible to have clear order, since rules can be concurent. Either cs or ast. 

Implementing them in different technology doesn't solve the problem.

What you could do, is to add feature "runAfterRectorRule()", which would resolve the issues above. But be sure it's not 100 % perfect.

**Comment by gnutix** [comment]
Thanks for the blog post, interesting ! What about running Rectors in ECS ? (as it's already built to run Sniffs and Fixers, maybe it would be possible to add Rectors too - so it's only one tool that handles all the code style changes) ? (that's a naive question, I haven't checked ECS internals ever)

**Comment by TomasVotruba** [comment]
I think it will only hurt both projects. I've tried to build many overlords in my life, all them end up in maintenance hell.

I prefer [unix manifesto](https://en.wikipedia.org/wiki/Unix_philosophy) :)

But feel free to do it the same way I made ECS. That is also join of 2 sipmle tools. Maybe you're on right track.

**Comment by TomasVotruba** [comment]
Also, experiments over ideas.
