### ISSUE TITLE
What to do with "mixed" pseudo-type ?

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2632]
What is this issue about : the usage and handling of the `mixed` pseudo-type by Rector.

> _mixed_ indicates that a parameter may accept multiple (but not necessarily all) types.
https://www.php.net/manual/en/language.pseudo-types.php#language.types.mixed

Currently, Rector mostly (always ?) replaces instances of `mixed` in the code with the infered type. Sometimes it does so accurately : 

```diff
    /**
-     * @return mixed[]
+     * @return float[]|string[]|null[]
     */
    private function someMethod(SomeObject $object): array
    {
        return [
            'item' => $object->item, // string
            'amount' => $object->amount, // float|null
            'currency' => $object->currency, // string|null
        ];
    }
```

And sometimes not so much : 

```diff
    /**
-     * @var mixed[]
+     * @var string|int|string[]|null[]
     */
    public const ARRAY_CONST = [
        'key' => 'value',
        'key2' => ['value2', 1234],
        1 => null,
    ];
```

(examples using `Rector\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector`)

If we wanted to have specific infered type, this one should rather be `@var array<int|string, string|array<string|int>|null>` (or something like that... :smile: ), which is not yet a syntax supported by IDEs but only PHPStan 0.12+. I don't think it's possible to write that structure down properly using supported syntax as of today (please indulge me if I'm wrong!).

The current option are : 

1. Keep replacing by (sometimes wrong) infered types
2. Do not replace `mixed`
3. Make it configurable (with a boolean flag like `parameters.prefer_infered_types_over_mixed`)
4. Decide / make configurable how deep array|iterable structures should be documented ? There's already a constant in AddArrayReturnDocTypeRector for that, arbitrarily (I guess?) set to "3".

**Comment by TomasVotruba** [comment]
3. :+1:

**Comment by gnutix** [comment]
Relevant : https://wiki.php.net/rfc/mixed_type_v2

**Comment by TomasVotruba** [comment]
If it passes, dump it here #3127
