### ISSUE TITLE
--rule argument is not working

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2651]
I've noticed that running `process --rule "[someRectorFQCN] [path]` throws an error (even though the `[-r|--rule RULE]` argument is described) : 

```
Rector 0.6.x-dev@a21b805

In RectorGuard.php line 41:
                                                    
  We need some rectors to run:                      
  * register them in rector.yaml under "services:"  
  * use "--set <set>"                               
  * or use "--config <file>.yaml"                   

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [-e|--hide-autoload-errors] [--match-git-diff] [-r|--rule RULE] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--] [<source>...]
```

Thrown by `\Rector\Guard\RectorGuard::ensureSomeRectorsAreRegistered()`.

I've tried to investigate, but I don't understand how `\Rector\PhpParser\NodeTraverser\RectorNodeTraverser` gets populated (in `\Rector\Console\Command\ProcessCommand::execute()` there's only a call to `$this->configuration->resolveFromInput($input);`, but the Configuration class is not aware of `RectorNodeTraverser` :thinking: and `\Rector\PhpParser\NodeTraverser\RectorNodeTraverser::getPhpRectorCount()` references a `$this->visitors` which is defined nowhere...). Is there some services / autowiring / compiler pass or whatnot going on here ?

**Comment by TomasVotruba** [comment]
This option only limits **registered rules**, as they might need some configuration.

How would expect it to work?

**Comment by gnutix** [comment]
I would have expected it to work like :+1: 

```yaml
# rector.yaml
services:
    SomeRector: ~
```

**Comment by TomasVotruba** [comment]
I have no idea how to make it. That means registering services to the container in `bin/rector`

**Comment by gnutix** [comment]
Then the argument should probably be renamed to --filter with an explanation that it allows to run only one Rector from the loaded ones.

**Comment by TomasVotruba** [comment]
Sound good :+1:
