### ISSUE TITLE
When running vendor/bin/rector process vendor/zendframework/zendframework1 --set php74 --dry-run  : file permission errors

### ISSUE THREAD

**Issue by vaishalilodhi** [rectorphp/rector#2677]
| File permission denied error| When running vendor/bin/rector process vendor/zendframework/zendframework1 --set php74 --dry-run  command  in windows :include(): read of 4096 bytes failed with errno=13 Permissio`n denied in D:\laragon\www\rector_test\vendor\symfony\http-kernel\Kernel.php on line 486
|
| :------------- | :----------------------------------------------------------- |
| 
| v0.6.10 | 
| 7.4 | 
| vendor/bin/rector process vendor/zendframework/zendframework1 --set php74 --dry-run|

**Comment by TomasVotruba** [comment]
Hi, it seems you have to use `chmod +x` on your project or Rector directory.
