### ISSUE TITLE
TypedPropertyRector - nullable bug

### ISSUE THREAD

**Issue by solcik** [rectorphp/rector#2684]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.10 |
| PHP version    | v7.4.1 |
| Full Command   | vendor/bin/rector process /src --set php7.4 --debug  | 

## Minimal PHP Code Causing Issue

  

```php
<?php 

/**
 * @var User|null
 */
private $user;
```

## Current Behaviour

```php
<?php 

private User $user;
```
## Expected Behaviour

```php
<?php 

private ?User $user;
```

**Comment by TomasVotruba** [comment]
Test case is need I  `TypedPropertyRectorTest`

**Comment by TomasVotruba** [comment]
See https://getrector.org/demo/4a082481-7e3b-4ab7-b1e8-0aebcc1bce24

**Comment by solcik** [comment]
I tried to debug that and found out, that `rector/rector/packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer.php` inferred type without null in the example below as you can see in the screenshot. If I would set explicit default value null, it is inferred correctly.

<img width="1280" alt="Screenshot 2020-01-17 at 23 21 28" src="https://user-images.githubusercontent.com/1543737/72650250-3a019200-3980-11ea-805b-c7052ecbf35d.png">

```
➜ ./vendor/bin/rector process ./src --set php7.4
Rector v0.6.10
Config file: rector.yaml

 720/720 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) src/TMO/Http/Web/Timer/Project/ElementPresenter.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -41,10 +41,7 @@

-    /**
-     * @var Element|null
-     */
-    private $element;
+    private Element $element;

     public function __construct(
    ----------- end diff -----------

Applied rules:

 * Rector\Php74\Rector\Property\TypedPropertyRector

 [OK] Rector is done! 1 file have been changed.
```


```php
class Element{}

interface GetElement
{
    public function __invoke(UuidInterface $id): Element;
}

final class ElementPresenter
{
    /**
     * @var Element|null
     */
    private $element;

    /**
     * @var GetElement
     */
    private GetElement $getElement;

    public function __construct(GetElement $getElement)
    {
        $this->getElement = $getElement;
    }

    public function actionDetail(string $id): void
    {
        $element = ($this->getElement)(Uuid::fromString($id));
        $this->element = $element;
    }
}
```

**Comment by TomasVotruba** [comment]
I'm looking only at the snippet code you provide and at first sight, it's correct.

The variable is never `null`. There is only one public function, that assigns the value. This assign value is always `Element`. 

It would be a bug if there would be e.g. comparison `$this->element === null` before above this code or in the property called in any other public method.

**Comment by solcik** [comment]
Ok, I understand.

Since I did not assign the default value neither in the property nor in the constructor. It is uninitialized = null in previous versions of PHP till 7.4.

When I would add another method in the future, where I would try to access that property, I am going to know, that it is ?Element = uninitialized in my case at least rom my point of view.

**Comment by TomasVotruba** [comment]
Exactly. Value must be initialized in ctor, otherwise it's nullable

**Comment by solcik** [comment]
I think, that we do not understand each other ./ I made the demo for my problem. 

https://getrector.org/demo/46d77073-2684-4f30-9714-6c66e81c5c47

**Comment by TomasVotruba** [comment]
That's pretty clear.

We need test case for this in `TypedPropertyRectorTest`. I'll look at the fix then
