### ISSUE TITLE
Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector doesn't respect the interface

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#2696]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | 0.6.10|
| PHP version    | PHP 7.2|

## Current Behaviour 

```diff
1) src/Email/Email.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -42,7 +42,7 @@
      * @throws \InvalidArgumentException
      * @throws StringsException
      */
-    public function __construct($value)
+    public function __construct(string $value)
     {
         $validator = new EmailValidator();
    ----------- end diff -----------

Applied rules:

 * Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
 * Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector
 * Rector\TypeDeclaration\Rector\ClassMethod\AddParamTypeDeclarationRector
 * Rector\Rector\Argument\ArgumentRemoverRector
 * Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector
 * Rector\CodeQuality\Rector\If_\RemoveAlwaysTrueConditionSetInConstructorRector
 * Rector\DeadCode\Rector\ClassMethod\RemoveOverriddenValuesRector
 * Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector

```

The class `Email` inherits from a generic interface with this signature:

```php
interface SimpleValueObjectInterface extends ValueObjectInterface
{
    /**
     * Accepts a simple scalar value.
     *
     * @param mixed $value
     */
    public function __construct($value);
}
```

Adding the type hint `string` causes the code to break.

I'm going to write a failing test case for this.

**Comment by TomasVotruba** [comment]
What would be the expected behavior?

**Comment by Aerendir** [comment]
Not adding the param type hinting if the interface from which the class inherits from doesn't have it in its signature.

If the interface doesn't have the type hint, the inheriting class cannot add it or the code breaks.

**Comment by TomasVotruba** [comment]
What if both cases are in your code and adding string is the change you'd do manually?

**Comment by Aerendir** [comment]
I think I’m missing your point...

My is this: if I implement a third party interface, I don’t want Rector adds the type hint to method parame if the third party interface from which I’m inheriting doesn’t have them, don’t I?

Does my thoughts sounds good to you?

**Comment by TomasVotruba** [comment]
Ah, 3rd party interface. Yes that makes sense.

I didn't get that from: https://github.com/rectorphp/rector/pull/2697/files

In that case, the interface cannot be in `Fixture` directory there (~= your app code),
but in `Source` directory (~= `vendor` code)

**Comment by Aerendir** [comment]
Forgive me: I didn’t know about this difference 😅

**Comment by TomasVotruba** [comment]
No troubles :), it hidden tests convention.
