### ISSUE TITLE
Encountering an Error when running on my project

### ISSUE THREAD

**Issue by rotexdegba** [rectorphp/rector#2701]
## Question
Hi there I am doing a dry run on my project: https://github.com/rotexsoft/versatile-collections
Using the following yaml file: https://github.com/rotexsoft/versatile-collections/blob/master/rector.yaml
With the command below:
* **./vendor/bin/rector process src --dry-run**

I am getting the following error message:

```
 [ERROR] Could not process
         "/var/www/html/versatile-collections/src/CollectionInterfaceImplementationTrait.php" file, 
         due to:
         "Rector\NodeTypeResolver\StaticTypeMapper::mapPHPStanTypeToDocString for PHPStan\Type\ThisType".
```

Can someone please tell me why I am getting this error?

**Comment by TomasVotruba** [comment]
Does it persist on `dev-master`? I did big refactoring about it recently

**Comment by rotexdegba** [comment]
> 
> 
> Does it persist on `dev-master`? I did big refactoring about it recently

Yes it does.

However, I commented the rule below in the project's **rector.yaml** file and it worked without errors:
**Rector\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector: ~**

The problem must be with **Rector\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector**

**Comment by TomasVotruba** [comment]
I just tested it and dev-master works.

Here is the PR to your repository: https://github.com/rotexsoft/versatile-collections/pull/18

I'll release new version shortly to prevent this confusion

**Comment by rotexdegba** [comment]
> 
> 
> I just tested it and dev-master works.
> 
> Here is the PR to your repository: [rotexsoft/versatile-collections#18](https://github.com/rotexsoft/versatile-collections/pull/18)
> 
> I'll release new version shortly to prevent this confusion

Thanks a lot!
