### ISSUE TITLE
Assert\Choice values are removed with PHP74 set

### ISSUE THREAD

**Issue by benr77** [rectorphp/rector#2721]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | 0.6.11 |
| PHP version    | 7.4                               |
| Full Command   | bin/rector process src --set php74 | 

## Current Behaviour 

The PHP74 set is removing values from Assert\Choice() constraint annotations

```
     /**
-     * @var string
      *
-     * @Assert\Choice({"sales_and_management", "management_only"})
+     * @Assert\Choice
      */

```
## Expected Behaviour

```
     /**
-     * @var string
      */
```

**Comment by TomasVotruba** [comment]
We'll need more code,not just diffs

Could you provide minimal failing code via
https://getrector.org/demo

It's fresh website, so not sure if it will work with annotation classes, but there is just way to find out :)

**Comment by benr77** [comment]
I'm LOVING the test page!

Here you go 
https://getrector.org/demo/943c8e34-f32e-44f7-9238-548e1de2901b

**Comment by TomasVotruba** [comment]
> I'm LOVING the test page!

Thanks! :heart: 


It helps us to uncover issues more easily

**Comment by benr77** [comment]
Awesome thanks for the speedy fix.
