### ISSUE TITLE
Change baseclass of class Rector

### ISSUE THREAD

**Issue by C0pyR1ght** [rectorphp/rector#2729]
The request is based on the `ChangeZendControllerClassToSymfonyControllerClassRector`. The idea is to make a more general and abstract approach with a new rector that allows you to change the baseclass of all classes with this specific baseclass.

## Example 

```diff
-class SomeAction extends Old_Controller_Action //<- identified by baseclass
+class SomeAction extends New_Controller_Action
 {
 }
```

## Example config
```
ChangeBaseclassOfClassRector:
  $BaseclassNames:
    Old_Controller_Action: New_Controller_Action
```

I don't know how often a case like this occures in projects. You are more experienced to evaluate the need of the suggested rector.

**Comment by TomasVotruba** [comment]
Hi,
this rule handles it: https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#renameclassrector

**Comment by C0pyR1ght** [comment]
Hi,
you're right! Seems that I overlooked this one..
Thanks
