### ISSUE TITLE
Improve Reflection speed

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#273]
At the moment whole 3rd party code is parsed by php-parser via BetterReflection just to get class types.

The performance is very poor:

![image](https://user-images.githubusercontent.com/924196/34644763-1d4d6e3a-f33d-11e7-97b0-c684497ec38d.png)

**Comment by carusogabriel** [comment]
Any clue how to do that?

**Comment by TomasVotruba** [comment]
I'd start with [SmartClassReflector](https://github.com/rectorphp/rector/blob/f2cd14dcef98c2e7404290935aee8fa894047895/packages/BetterReflection/src/Reflector/SmartClassReflector.php#L47) that handles reflection via BetterReflection

The BetterReflection now parses whole `/vendor` just to find out reflection for file. The order of `SourceLocator` should preffer autoloaded classes first.

But that's just one of my ideas, I believe you can find more places.

**Comment by TomasVotruba** [comment]
### Inspire for TypeResolving at Psalm

This could help with resolving type and performance issue we have with BetterReflection

- https://github.com/vimeo/psalm/tree/master/src/Psalm/Visitor
- https://github.com/vimeo/psalm/tree/master/src/Psalm/Storage

**Comment by TomasVotruba** [comment]
So far so good. It's be better to delegate on BetterReflection bump to php-parser 4: https://github.com/Roave/BetterReflection/pull/410 and not reinvent the wheel
