### ISSUE TITLE
Rector removes lines in switch-case that is not dead

### ISSUE THREAD

**Issue by escopecz** [rectorphp/rector#2730]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | https://github.com/rectorphp/rector-prefixed/releases/tag/v0.6.13               | 
| PHP version    | 7.2.26                                | 
| Full Command   | `mautic (3.x) $ bin/rector process app/bundles/AssetBundle --set dead-code --dry-run1`          | 
| Demo link      | https://getrector.org/demo/4db04e11-6f12-407c-9b4d-97133acff941  | 
| rector.yaml    | No config             | 

## Current Behaviour 
Rector works for Mautic!!! 🎉 I tried to run Rector on AssetBundle and noticed following removed lines which I don't think is correct.

We use a static [method to convert upload size to bytes in Mautic](https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/AssetBundle/Entity/Asset.php#L1322-L1349), but it was borrowed from [Symfony](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/File/UploadedFile.php#L215-L243):

Rector suggests to remove these lines:
```php
         switch (strtolower(substr($size, -1))) {
             case 't':
-                $max *= 1024;
                 // no break
             case 'g':
-                $max *= 1024;
                 // no break
             case 'm':
-                $max *= 1024;
                 // no break
             case 'k':
                 $max *= 1024;
    ----------- end diff -----------
```

## Minimal PHP Code Causing Issue

  

```php
<?php declare(strict_types=1);

final class DemoFile
{
    public static function convertSizeToBytes($size)
    {
        if ('' === $size) {
            return PHP_INT_MAX;
        }

        $max = ltrim($size, '+');
        if (0 === strpos($max, '0x')) {
            $max = intval($max, 16);
        } elseif (0 === strpos($max, '0')) {
            $max = intval($max, 8);
        } else {
            $max = intval($max);
        }

        switch (strtolower(substr($size, -1))) {
            case 't':
                $max *= 1024;
                // no break
            case 'g':
                $max *= 1024;
                // no break
            case 'm':
                $max *= 1024;
                // no break
            case 'k':
                $max *= 1024;
        }

        return $max;
    }
}
```

## Expected Behaviour
I don't think it should remove the lines.

**Comment by TomasVotruba** [comment]
> Rector works for Mautic!!! tada 

That's great :clap:  :tada: 

<br>

Ah, at first it looked correct, but now I see there is no default.

Could you tell me responsible rule?

**Comment by TomasVotruba** [comment]
On second though, I think it's correct. All 4 items return the bottom value.

**Comment by escopecz** [comment]
I see it now too. Rector is clever!

**Comment by TomasVotruba** [comment]
Yea, Rector is based on pure distilled human lazyness :D

**Comment by escopecz** [comment]
Getting back to this. It is a bug. Since there are no breaks in the switch case then Rector's change breaks the behavior. Consider calling `DemoFile::convertSizeToBytes('1K')`. The result is `1024`. If you call `DemoFile::convertSizeToBytes('1M')` then in the modified version it's still `1024` instead of `1048576` that it used to be before the change and which is also the right result.

**Comment by TomasVotruba** [comment]
I see. it's comulative.

Could you send failing test case?

What is the rule to separate this from duplication? Modifying the same value?

**Comment by TomasVotruba** [comment]
Any ideas?

**Comment by escopecz** [comment]
TBH, I don't use switches that much. Trying to avoid them with better design. This was new behaviour to me:

> The switch statement executes line by line (actually, statement by statement). In the beginning, no code is executed. Only when a case statement is found whose expression evaluates to a value that matches the value of the switch expression does PHP begin to execute the statements. PHP continues to execute the statements until the end of the switch block, or the first time it sees a break statement. If you don't write a break statement at the end of a case's statement list, PHP will go on executing the statements of the following case

_source: https://www.php.net/manual/en/control-structures.switch.php_

So I don't think Rector should squash case statements if they do not contain break. Does it make sense?

**Comment by TomasVotruba** [comment]
> So I don't think Rector should squash case statements if they do not contain break. Does it make sense?

:+1:  Yes, that's what I was looking for. Simple and clear. I'll fix it
