### ISSUE TITLE
"Auto import names" breaks code with imported class as alias

### ISSUE THREAD

**Issue by Great-Antique** [rectorphp/rector#2753]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | v0.6.13                   |
| PHP version    | PHP 7.4.1                                       |
| Demo link      | https://getrector.org/demo/76fe6abf-1d46-4ef0-b3fd-721fbb3079f2#result  | 

## Current Behaviour 

Replaces aliased class name with original one in places where class name used but not in `use` section.

## Minimal PHP Code Causing Issue

Details see in demo link.

## Expected Behaviour
Do not replace alias with original class name.

**Comment by TomasVotruba** [comment]
CI passes, it's fixed by some other fix probably :)

**Comment by Great-Antique** [comment]
I had to update my code from upstream before merging. You changed (as I understand) folder structure.

My fixtures are in `packages` folder and current ones are in `rules` folder. So they aren't loading in current data provider and my tests aren't running.

To run them you should move fixtures and sources:
```console
$ git mv packages/renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/*.php.inc rules/renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/
$ git mv packages/renaming/tests/Rector/Class_/RenameClassRector/Source/* rules/renaming/tests/Rector/Class_/RenameClassRector/Source/
```

**Comment by TomasVotruba** [comment]
Oh, I forgot that, you're right
Could you send PR with that fix?

**Comment by Great-Antique** [comment]
Done  #3074
