### ISSUE TITLE
Mysql to Mysqli migration

### ISSUE THREAD

**Issue by viksts** [rectorphp/rector#2766]
Hi,

How does rector handles parameter changes while changing mysql to mysqli. Because in mysql connection parameter is optional but in mysqli connection parameter is mandatory. For example in mysql_query() you don't require to pass connection however in mysqli_query() connection parameter is mandatory so how does rector handles it.

**Comment by TomasVotruba** [comment]
Hi, could you providesome code?
Ideally from: https://getrector.org/demo

**Comment by viksts** [comment]
`
$host = 'localhost';
$user = 'root';
$password = '';
$database = 'test';

$conn = mysql_connect($host, $user, $password);

// Check connection
if (!$conn) {
    die("Connection failed: " . mysql_connect_error());
}
echo "Connected successfully";
echo "<br>";
$db_selected = mysql_select_db($database);
if(!$db_selected){
	die ('Can\'t use foo : ' . mysql_error());
}
echo "Database selected";
echo "<br>";

$name = "vikas's";
echo $sql = "INSERT INTO t_table(name) VALUES('".mysql_real_escape_string($name)."')";
echo "<br>";
$status = mysql_query($conn, $sql);
if(!$status){
	die('Error: ' . mysql_error());
}
echo "Data added successfully!";

mysql_close($conn);
`
This is my code and i want to migrate it from mysql to mysqli. So how would rector handle the paramater changes.

**Comment by TomasVotruba** [comment]
Demo link is needed

**Comment by viksts** [comment]
How can i create demo link?

**Comment by TomasVotruba** [comment]
https://github.com/rectorphp/rector/issues/2766#issuecomment-578676519

**Comment by vaishalilodhi** [comment]
on behalf of @viksts  I tried using 
```
$host = 'localhost';
$user = 'root';
$password = '';
$database = 'test';

$conn = mysql_connect($host, $user, $password);
$db_selected = mysql_select_db($database);
$sql=""SELECT * FROM Users;
$status = mysql_query($conn, $sql);
mysql_close($conn);
```
but it resulted in an error https://getrector.org/demo/4acc4202-9fe7-4da4-8d27-e9257793eb86#result (demo link)

**Comment by TomasVotruba** [comment]
You cannot run code in our production, as you could break the  docker

Use function or class wrapper instead, e.g.

```php
function some()
{
    // your code
}
```

**Comment by vaishalilodhi** [comment]
@TomasVotruba  Please have a look at this https://getrector.org/demo/5c239b8b-2ea3-4edf-9e77-ead500e15005#result

**Comment by TomasVotruba** [comment]
@vaishalilodhi I see the link. But what is wrong there?

**Comment by andersonmuller** [comment]
Hi @TomasVotruba 

I think @viksts is talking about this scenario: https://getrector.org/demo/2ac4b25f-14f7-449b-9747-420c8de4960d#result

mysql_query() or mysql_error() don't require to pass connection/link, but mysqli_query() does. So, the result code will throw 2 errors:
Warning: mysqli_query() expects at least 2 parameters, 1 given... Warning: mysqli_error() expects at least 1 parameter, 0 given...

**Comment by TomasVotruba** [comment]
Hi @andersonmuller 

What is the expected change then? Before/after, so we can improve the rule

**Comment by andersonmuller** [comment]
I really don't know if this is the best solution, but I would expect something like this:

```php
-$conn = mysql_connect('host', 'user', 'pass');
+$conn = mysqli_connect('host', 'user', 'pass');
 	
-$db_selected = mysql_select_db($database);
+$db_selected = mysqli_select_db($conn, $database);

 if(!$db_selected){
-	die ("Can't use db : " . mysql_error());
+	die ("Can't use db : " . mysqli_error($conn));
 }
```

**Comment by TomasVotruba** [comment]
I see.

How do you make `$conn` in your real life code? Above in variable?

**Comment by andersonmuller** [comment]
When I'm not using a framework, I prefer PDO, but alot of projects (mainly legacy) are using mysqli

**mysqli, procedural style**
```php
$link = mysqli_connect('localhost', 'username', 'password', 'database');
mysqli_query($link, "SELECT * FROM users");
```

**mysqli, object oriented style**
```php
$mysqli = new mysqli('localhost', 'username', 'password', 'database');
$mysqli->query("SELECT * FROM users");
```

**PDO**
```php
$pdo = new PDO("dsn", "username", "password");
$arr = $pdo->query("SELECT * FROM users")->fetchAll(PDO::FETCH_ASSOC);
```

**Comment by TomasVotruba** [comment]
Here is the fix: https://github.com/rectorphp/rector/pull/2920

Is there more functions that needs this connection argument?
