### ISSUE TITLE
RemoveSetterOnlyPropertyAndMethodCallRector removes methods required by interface

### ISSUE THREAD

**Issue by escopecz** [rectorphp/rector#2777]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | v0.6.13               |
| PHP version    | PHP 7.2                                     |
| Full Command   | vendor/bin/rector process /src         | 
| Demo link      | https://getrector.org/demo/88129a64-f23e-430a-a8d4-fe282d39553d  | 
| rector.yaml    | See the demo             | 

## Current Behaviour 

See the demo. The method it removes must remain as it's required by the interface.

## Minimal PHP Code Causing Issue

  

```php
<?php

interface DemoInterface
{
	public function demoMethod($demoVar);
}

class DemoClass implements DemoInterface
{
    private $demoVar;
	
	public function demoMethod($demoVar)
	{
		$this->demoVar = $demoVar;
	}
}
```

## Expected Behaviour

It should remove only the useless variable. Not the required method. It should leave it empty.

**Comment by TomasVotruba** [comment]
Thanks for reporting. Demo link is pretty clear, I'm on it.
