### ISSUE TITLE
How to run a sinlge rule?

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#2785]
I just need to run one rule from rector, nothing else. Can't find how to do it in neither readme nor `vendor/bin/rector help process`.

According to https://github.com/rectorphp/rector/issues/2213 there was a `--rule` option in the past but it seems to have been removed since. What can I use instead?

**Comment by enumag** [comment]
It seems I have to use `--only` now and that it has to be used together with `--set`. That's quite poor DX to be honest. I found a rule I wanted to run and don't know nor care which set it comes from. :disappointed:

**Comment by enumag** [comment]
And it doesn't work even work... I tried to run

```
vendor/bin/rector process src --set symfony --only "Rector\Symfony\Rector\ClassMethod\MergeMethodAnnotationToRouteAnnotationRector" --dry-run
```

but the diff is showing some completely unrelated (and completely wrong) changes like:

```

 use Doctrine\DBAL\Schema\Schema;
 use Doctrine\Migrations\AbstractMigration;
-
-class Version20180810121127 extends AbstractMigration
+class Version20180810121127 extends \Doctrine\Migrations\AbstractMigration
 {
-    public function up(Schema $schema): void
+    public function up(\Doctrine\DBAL\Schema\Schema $schema): void
     {
         $this->abortI
```

**Comment by TomasVotruba** [comment]
It does work. The diff shows changed by auto import feaure. That's PHP parser design

**Comment by enumag** [comment]
Is there a way to get a diff without these changes? Like this the diff is completely useless to me. Also would these auto import changes be applied when I don't use `--dry-run`? If so, how do I revert them afterwards without reverting the changes from my chosen rector rule?

**Comment by TomasVotruba** [comment]
You need to use coding standard anyway, ast cannot handle it

**Comment by enumag** [comment]
Huh? I don't understand you at all.

**Comment by TomasVotruba** [comment]
https://github.com/rectorphp/rector/blob/master/README.md#how-to-apply-coding-standards

**Comment by enumag** [comment]
I mean... yeah sure ofc I need to have the changed code formatted by cs fixer or whatever afterwards. But why does it touch the existing code and breaks imports? I'm not even sure if my coding standard can revert such changes.

**Comment by TomasVotruba** [comment]
It doesn't break them. It's the fqn version.

Ast is not designed for formatting code 100 %, so without coding standard, there always will be edge cases like this. You'd have to contribute to PHP parser to fix this. Not an easy task

**Comment by enumag** [comment]
Do you have a tool that can be used to revert the FQN changes? My coding standard doesn't do it at the moment. I can't use Rector at all without a way to revert them.

**Comment by TomasVotruba** [comment]
`ecs.yaml` here does it

**Comment by enumag** [comment]
I assume you don't know which rule is doing it for you. Alright, I'll try to find out and tell you when I do. This absolutely has to be in rector readme.

**Comment by TomasVotruba** [comment]
> I assume you don't know which rule is doing it for you. 

Exactly. I just type `cs`, there I focus on something else.

> This absolutely has to be in rector readme.

It is, I sent you a link in comment above.

**Comment by TomasVotruba** [comment]
How it could be written better there?

**Comment by enumag** [comment]
I mean the readme should warn that rector will mess up imports like this, that it is expected behaviour and specify the exact cs fixer / code sniffer rule that can be used to fix it afterwards.

**Comment by TomasVotruba** [comment]
I agree.
How would such text exactly look like?

**Comment by enumag** [comment]
Something like this? https://github.com/rectorphp/rector/compare/master...enumag:patch-1

**Comment by enumag** [comment]
@TomasVotruba It seems Rector is also doing some other changes that I don't really want. Is there some way to run Rector to only change the code as it wants to without any rules whatsover? I'd like to experiment with reverting those changes first before I actually get into using some rules.

**Comment by TomasVotruba** [comment]
That's not possible, since the whole file is changed.

I assume there will be some anomally in your code, OS or filesystem, as this doesn't happen to me, on Travis nor Github Actions.

**Comment by enumag** [comment]
Well I'm running this:

```
vendor/bin/rector process src --set symfony --only "Rector\Symfony\Rector\ClassMethod\MergeMethodAnnotationToRouteAnnotationRector"
```

And the result is:
- class/interface usages changed to FQNs
- empty line between last `use` and `class` is removed
- empty line between two class constants, properties or methods is removed
- some other empty lines in the code removed
- some long lines reformatted to multiline code
- `protected abstract function` changed to `abstract protected function`

Some of these changes are good and I'd even use them but I certainly can't let rector remove the empty lines. Does that happen for you too?

**Comment by enumag** [comment]
Oh and the `Method` and `Route` annotations were NOT refactored. :man_shrugging:

**Comment by enumag** [comment]
Well thankfully I know regular expressions quite well so I managed to refactor the annotations in my project using a few replaces in PHPStorm. :stuck_out_tongue:

**Comment by TomasVotruba** [comment]
Without failing test case there is not much we can do

**Comment by stedekay** [comment]
Hey @enumag can you share your regex? I seem to have the exact same problem like you. Some controllers are really messed up after executing rector.

**Comment by enumag** [comment]
@stedekay Sorry but since it was one-time usage I didn't save the regular expressions I used. It was several regexes for the different conventions in out app. Most notably one for singleline Route annotations and one for multiline Route annotations.

**Comment by stedekay** [comment]
@enumag Yeah, thought so. But thanks for your quick answer.

**Comment by TomasVotruba** [comment]
It's been deprecated, because slashes and quotes confused many people that complained about this feature not working.

The best way to run Rector with one rule is to simply register it in config:

```yaml
# rector.yaml
services:
    YourRector: null
```

**Comment by afilina** [comment]
I wrote a more detailed comment after I found out that all options to run a single rule were dropped: https://github.com/rectorphp/rector/pull/3287#issuecomment-641564849

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/issues/3342#issuecomment-644728458
