### ISSUE TITLE
[CodingStyle] function camel-case to snake-case rector

### ISSUE THREAD

**Issue by C0pyR1ght** [rectorphp/rector#2803]
I was looking for a rector that converts function names that are written in camel-case to snake-case. As far as I am concerned there is no such rector.

`function getArticleInfo()` --> `function get_article_info()`

Do you know any rector to build up on or another good starting point for this?

**Comment by TomasVotruba** [comment]
Look at this rule: https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#renamefunctionrector

Subscriber to `FuncCall` and `Function_` nodes and rename the function name .

**Comment by C0pyR1ght** [comment]
thanks.
I will try building up on that.

**Comment by TomasVotruba** [comment]
The best to learn it is to send PR with `create` command - https://github.com/rectorphp/rector/blob/master/docs/RectorRecipe.md

Even if it is not finished, just send it and I'll give you feedback to get there
