### ISSUE TITLE
[SOLID] false positive

### ISSUE THREAD

**Issue by alex-bacart** [rectorphp/rector#2806]
Hello!
Here is my example https://getrector.org/demo/373b7456-b871-4505-bd5b-b6f632163dcb
If I''ll follow Rector's recommendation and make a constant private PHP would not compile the code.

![image](https://user-images.githubusercontent.com/13940752/73954888-83a42380-4913-11ea-8073-5936bdd2e2b9.png)

**Comment by TomasVotruba** [comment]
Why is expected behavior?

**Comment by TomasVotruba** [comment]
Could you add failing test case to https://github.com/rectorphp/rector/tree/master/packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture ? 

Thanks

**Comment by alex-bacart** [comment]
Expected behavior is that here https://getrector.org/demo/373b7456-b871-4505-bd5b-b6f632163dcb Rector would not complain at all.

**Comment by TomasVotruba** [comment]
3v4l ref: https://3v4l.org/RQ2j0

**Comment by TomasVotruba** [comment]
Resolved by #2814

**Comment by alex-bacart** [comment]
The snippet in a link I provided in this issue still suggests changing protected constants to private ones. #2814 isn't not merged in 7.2?

**Comment by TomasVotruba** [comment]
It is.

Please provide new demo link (0.7.2 is there), so I can invesigate

**Comment by TomasVotruba** [comment]
Could you test it locally with `dev-master`?

**Comment by alex-bacart** [comment]
Checked in `dev-master`, suggestion remains.

**Comment by TomasVotruba** [comment]
Seems like suggestion is correct: https://3v4l.org/8eQLl

The constant is never used in children

**Comment by TomasVotruba** [comment]
If your issues still remans, please also provide https://3v4l.org/ link to failed use case
