### ISSUE TITLE
Rector 0.6.14 strictly requires phpstan:0.12.7 making impossible to update PHPStan 

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#2815]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | e.g. v0.6.14|

## Current Behaviour 

Trying to install rector:0.6.14 with phpstan:0.12.9 is impossible

```console
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rector/rector 0.6.14 -> satisfiable by rector/rector[v0.6.14].
    - rector/rector v0.6.14 requires phpstan/phpstan 0.12.7 -> satisfiable by phpstan/phpstan[0.12.7] but these conflict with your requirements or minimum-stability.
```

But using rector:0.6.13 it is possible to upgrade phpstan to 0.12.9.

I currently have phpstan:0.12.9 and rector:0.6.13:

```json
{
    ...
    "require-dev": {
        "phpstan/phpstan": "0.12.9",
        ...
        "rector/rector": "0.6.13",
...
```

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/issues/2749
