### ISSUE TITLE
Error when param is typed callback

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#2841]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | e.g. v0.6.14 (invoke `vendor/bin/rector --version`)                   |
| PHP version    | e.g. PHP 7.4.2 (invoke `php -v`)                                        |
| Demo link      | https://getrector.org/demo/ea80a2fb-2646-4af9-b8f6-8617ef6bc0be  |

**Comment by TomasVotruba** [comment]
What kind of format is that?
What's the expected output?

**Comment by snapshotpl** [comment]
https://psalm.dev/docs/annotating_code/type_syntax/callable_types/

It this case should change any thing because property cannot be typed as callable. But it can be Closure and then type should be moved to native notation:

``'php
<?php

class CallableParam
{
    /** @var Closure():int */
    protected Closure $param;
}
```

**Comment by TomasVotruba** [comment]
I see. Rector uses PHPStan to analyse types, so this will be evaluated as mixed

**Comment by snapshotpl** [comment]
I understand. But is there any chance to fix this error?

**Comment by TomasVotruba** [comment]
Yes, it will be reported as mixed though.
I'll look on it now

**Comment by snapshotpl** [comment]
@TomasVotruba Now rector remove all type details about callable
https://getrector.org/demo/2d246607-7763-4235-822b-a9b702fdd577#result

**Comment by snapshotpl** [comment]
@TomasVotruba This [example](https://getrector.org/demo/2d246607-7763-4235-822b-a9b702fdd577#result) should working now on demo?

Anyway I have update to current master and rector still removes this types.

**Comment by TomasVotruba** [comment]
Demo is not automatically updated I think, is it? @JanMikes Would be great though, mainly for issue check like this.

**Comment by TomasVotruba** [comment]
@snapshotpl Please add test case as in referenced PR, so we have it covered. I think there will be lot of differences, if you use Psalm

**Comment by TomasVotruba** [comment]
Here: https://github.com/rectorphp/rector/blob/de2279a9b449914ef05e092489f6e1ab19128818/packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/callable.txt
