### ISSUE TITLE
ArraySpreadInsteadOfArrayMergeRector bug

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#2854]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | Rector 0.6.x-dev@b2c0c3e                  |
| PHP version    | 7.4.2                                       |
| Full Command   |            | 
| Demo link      | https://getrector.org/demo/c85519dc-4feb-469e-b30d-fffc4d7f279c
| rector.yaml    |               | 

## Current Behaviour 

`ArraySpreadInsteadOfArrayMergeRector` is buggy because
```php
array_merge(...$values)) !== [...$values]
```

```php
<?php

$values = [
  [new stdClass],
  [new stdClass]
];

var_dump(array_merge(...$values) === [...$values]);
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/c85519dc-4feb-469e-b30d-fffc4d7f279c

## Expected Behaviour
`ArraySpreadInsteadOfArrayMergeRector` is not applied

**Comment by TomasVotruba** [comment]
3v4l.org would help too
What's the difference?

**Comment by bendavies** [comment]
https://3v4l.org/8E3E4

**Comment by bendavies** [comment]
Here is the issue:

https://3v4l.org/m2adm

You can't apply `ArraySpreadInsteadOfArrayMergeRector` if the array_merge has argument unpacking with `...`

**Comment by TomasVotruba** [comment]
Thanks, much better! Could you send failing test case to `ArraySpreadInsteadOfArrayMergeRectorTest`?
