### ISSUE TITLE
How to remove multiline comment?

### ISSUE THREAD

**Issue by oldy777** [rectorphp/rector#2864]
Hi, I trying to make new rule and stuck with removing multiline comment. 
It looks like:
```php
 /**
     * @DI\InjectParams({
     *     "repository" = @DI\Inject("repository"),
     *     "option" = @DI\Inject("%option%"),
     * })
 */
```
I use
```php
$inf = $constructMethod->getAttribute(AttributeKey::PHP_DOC_INFO);
$inf->removeByName('DI');
```
but this command removes only 1 line
```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -21,7 +21,6 @@
     /**
-     * @DI\InjectParams({
      *     "repository" = @DI\Inject("repository"),
      *     "option" = @DI\Inject("%option%"),
      * })
    ----------- end diff -----------
```
Also I tried to make custom TagValueNode, but didn't find a way to registered new PhpDocNodeFactory. 

Need help :) 
rector version dev-master(v0.7.0)

**Comment by TomasVotruba** [comment]
Hi, failing test case is needed

**Comment by TomasVotruba** [comment]
Any update?

**Comment by oldy777** [comment]
I will try to do it on weekends.

**Comment by TomasVotruba** [comment]
Demo should be enough for me: https://getrector.org/demo

**Comment by oldy777** [comment]
Cool! https://getrector.org/demo/4fb4118d-63cb-4c54-8bc2-082be6ddf328

**Comment by TomasVotruba** [comment]
Demo doesn't show any diff nor bug.

**Comment by TomasVotruba** [comment]
Have you had something like this in mind?

https://github.com/rectorphp/rector/blob/71f5a43b89d658cc9000af5020d342168af5d478/docs/AllRectorsOverview.md#jms

**Comment by oldy777** [comment]
Yes, that's exactly what I needed. Thank you very much

**Comment by oldy777** [comment]
@TomasVotruba Hi! I trying to run [RemoveJmsInjectParamsAnnotationRector](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#removejmsinjectparamsannotationrector) on my codebase and seems it doesn't work.

I created rector.yaml
```YAML
services:
    Rector\JMS\Rector\ClassMethod\RemoveJmsInjectParamsAnnotationRector: null
```
Then run 
`php vendor/bin/rector process utils/Test.php  --dry-run`
Annotation was not deleted. But if I run your test, it works. 

And one more problem, I can't run rector unit tests:
`PHP Fatal error:  Cannot declare class Rector\Architecture\Tests\Rector\Class_\ConstructorInjectionToActionInjectionRector\Fixture\DuplicateController, because the name is already in use in /tmp/rector_temp_tests/original_066106da16a7_duplicate.php on line 34`

I removed /tmp/rector_temp_tests but it not helped

**Comment by TomasVotruba** [comment]
Could you provide demo link?
https://getrector.org/demo

**Comment by oldy777** [comment]
@TomasVotruba There is no such rector
https://getrector.org/demo/3ea88594-ebc8-498f-9cf4-519247e9ba0c

**Comment by TomasVotruba** [comment]
@oldy777 Ha, it seems the Rector version on demo is not updated.

@JanMikes Hi, could you look at update of demo Rector version?
It doesn't use the latest one. 

The `RemoveJmsInjectParamsAnnotationRector class is [here in code](https://github.com/rectorphp/rector/blob/master/rules/jms/src/Rector/ClassMethod/RemoveJmsInjectParamsAnnotationRector.php), but is missing in demo:  https://getrector.org/demo/ace7ba3a-6641-40ee-9d5d-f9b39021e960#result

**Comment by JanMikes** [comment]
Hi, i checked, demo is updated and latest image is downloaded, because the file is present in docker:

```
root@getrector.org:~# docker run -it --entrypoint="" rector/rector-secured:latest ls -l rules/jms/src/Rector/ClassMethod
total 4
-rw-r--r-- 1 root root 2045 Feb 26 00:00 RemoveJmsInjectParamsAnnotationRector.php
```

I am investigating, will let you know with update

**Comment by JanMikes** [comment]
Oh man, stupid school boy mistake 😄 

Fixed by https://github.com/rectorphp/getrector.org/commit/c4954e7f56de66ed3bf0f41faa3441e704e85e29 (will be deployed in few minutes).

I was living in other reality, though we had :latest tag docker image in production already, but instead it was in different branch.

**Comment by JanMikes** [comment]
Here you go: https://getrector.org/demo/19757a20-7974-41bc-98e6-c596ac74e7d2#result

**Comment by TomasVotruba** [comment]
Shit happens :) that's how programmers get work :D.  

Thanks for quick fix :+1:

**Comment by oldy777** [comment]
@TomasVotruba It seems I found out the problem. Everything works correct on rector/rector (v0.7.3), but it doesn't work on rector/rector-prefixed (0.8.x-dev)

**Comment by TomasVotruba** [comment]
@oldy777 We need failing test case to confirm that

**Comment by oldy777** [comment]
@TomasVotruba I don't know how to do it. 
I have a file like in demo
```php
<?php

use JMS\DiExtraBundle\Annotation as DI;

class SomeClass
{
    /**
     * @DI\InjectParams({
     *     "subscribeService" = @DI\Inject("app.email.service.subscribe"),
     *     "ipService" = @DI\Inject("app.util.service.ip")
     * })
     */
    public function __construct()
    {
    }
}
```
Run rector-prefixed:
```
php vendor/bin/rector process test.php

Rector 0.8.x-dev@e72639d
Config file: rector.yaml

 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] Rector is done!     
```                                                                                              
Then run  rector:
```diff
php ../demo/vendor/bin/rector process test.php

Rector v0.7.3
Config file: rector.yaml

 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -4,13 +4,7 @@

 class SomeClass
 {
-    /**
-     * @DI\InjectParams({
-     *     "subscribeService" = @DI\Inject("app.email.service.subscribe"),
-     *     "ipService" = @DI\Inject("app.util.service.ip")
-     * })
-     */
     public function __construct()
     {
     }
 }
\ No newline at end of file
    ----------- end diff -----------

Applied rules:

 * Rector\JMS\Rector\ClassMethod\RemoveJmsInjectParamsAnnotationRector


                                                                                                                        
 [OK] Rector is done! 1 file have been changed.       
```

**Comment by TomasVotruba** [comment]
The best would be to copy existing workflow in rector-prefixed,
https://github.com/rectorphp/rector-prefixed/tree/master/.github/workflows

add your setup, code, config and command line,
and send it as pull-request. Having that, it should fail.

Also, if possible, verify that `JMS\DiExtraBundle\Annotation` is autoloaded by your projects' `composer.json`.
