### ISSUE TITLE
Whitespace indentation breaking in DocBlock

### ISSUE THREAD

**Issue by Ivorius** [rectorphp/rector#2877]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | dev-master@85aa4dd                 |
| PHP version    | PHP 7.3                                     |
| Full Command   | vendor/bin/rector  process --set kdyby-translator-to-contributte-translation  --dry-run        | 
| Demo link      | https://getrector.org/demo/f9279b5e-7528-4378-968a-89c18f5f3947#result  | 

## Current Behaviour 
Change tab to space in DocBlock and property definition
![image](https://user-images.githubusercontent.com/552101/74677808-a65af580-51b9-11ea-9b70-38e230467d67.png)

## Minimal PHP Code Causing Issue

  

```php
<?php

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity()
 * @ORM\Table(name="slides")
 **/
class Slide
{
	/**
	 * @ORM\Column(type="boolean", nullable=FALSE, options={"default": 1})
	 * @var bool
	 */
	protected $active = true;
}
```

## Expected Behaviour
Current tab should not be modified. Especially in this case when there is only set for refactoring class name.

Btw. why is FALSE transform to lowercase? Is there some configuration in rector for this?

**Comment by TomasVotruba** [comment]
I see you're using tabs. That will be probably the issues.

Is is possible the file mixed tabs and spaces to indent?

> Btw. why is FALSE transform to lowercase? Is there some configuration in rector for this?

Docblocks are printed from an object, so there is just bool value, not much formatting options.

Here it's configured: https://github.com/rectorphp/rector/blob/85aa4dd4bc5cb464b3ef21fcab7f6bdf99a5b744/packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/ColumnTagValueNode.php#L129

**Comment by Ivorius** [comment]
I don´t know why, but if I remove DocBlock above class, it work´s well. Compare https://getrector.org/demo/f9279b5e-7528-4378-968a-89c18f5f3947#result and without comments  https://getrector.org/demo/929f0a68-e1d7-4516-a2dc-41a347e1ccb2#result

**Comment by Ivorius** [comment]
Is possible disabled docblocks processing?

**Comment by TomasVotruba** [comment]
Not really, it needs to fixes
