### ISSUE TITLE
infer types of getters/setters from properties

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#2887]
would be great if rector could infer the param-type of a setter and the return-type of a getter

before
```php
<?php declare(strict_types=1);

final class DemoFile
{
	/**
	 * @var int
	 */
	private $id;
	
	public function setId($id) {
		$this->id = $id;
	}
	public function getId() {
		return $this->id;
	}
}
```

after
```php
<?php declare(strict_types=1);

final class DemoFile
{
	/**
	 * @var int
	 */
	private $id;
	
	public function setId(int $id) {
		$this->id = $id;
	}
	public function getId():int {
		return $this->id;
	}
}
```

**Comment by Aerendir** [comment]
Did you saw those rectors?

- https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#returntypedeclarationrector
- https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#addparamtypedeclarationrector

**Comment by staabm** [comment]
Partly this is what I want to achieve. But the rectors mentioned do not work on the corresponding properties of the setter/getter but on the phpdocs of the methods itself

**Comment by TomasVotruba** [comment]
@staabm I think it's mentioned as inspiration.

**Comment by staabm** [comment]
Oh sorry. Misread the comment. Thx for pointing me into the direction. 

I will open a internal dev task so someone can work on it

**Comment by TomasVotruba** [comment]
Just getting into it...

- *return type already works like this*

https://getrector.org/demo/bb02c26b-7414-43ac-8b97-03909ebc26ba#result

![image](https://user-images.githubusercontent.com/924196/77811785-130cbe00-709d-11ea-8351-012165a6b129.png)
