### ISSUE TITLE
TypedPropertyRector: add null assign?

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#2894]
Hi there,

Given this:
https://getrector.org/demo/8a5be694-957f-4981-9189-5c7d835698da

What do you think about making this the result instead?
```php
final class DemoFile
{
    private ?int $foo = null;
}
```

it adds the null assignment, which would be compatible with the old code (implicit null).

without the assignment, there is the possibility for
`Fatal error: Uncaught Error: Typed property DemoFile::$foo must not be accessed before initialization...
`

**Comment by TomasVotruba** [comment]
Hi, I don't use typed properties so I have no idea how practical is this to status quo.

Could more PHP 7.4 people share their experience/view on this?

**Comment by TomasVotruba** [comment]
Any update?

**Comment by althaus** [comment]
I've just switched the first project to typed properties and the assigning `null` is a valid starting point on nullable properties.

**Comment by TomasVotruba** [comment]
Feel free to change it via PR
