### ISSUE TITLE
[Laravel] Add Laravel Rectors

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#290]
Following [Symfony migration on Rector](https://github.com/rectorphp/rector/tree/master/src/config/level/symfony), I guess we can have that automation as well for [Laravel](https://laravel.com/). List of versions:
- [ ] [5.0 to 5.1](https://laravel.com/docs/5.1/upgrade#upgrade-5.1.0)
- [ ] [5.1 to 5.2](https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0)
- [ ] [5.2 to 5.3](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0)
- [ ] [5.3 to 5.4](https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0)
- [ ] [5.4 to 5.5](https://laravel.com/docs/5.5/upgrade#upgrade-5.5.0)

Also, make use of `CHANGELOG-5.x.md` files in [Framework's core](https://github.com/laravel/framework). Some useful and undocumented changes may be found there :man_technologist: 

---

EDIT by @TomasVotruba 

## Resources

- [x] https://laravel.com/docs/5.8/upgrade
- [ ] https://laravel.com/docs/5.7/upgrade
- [ ] https://laravel.com/docs/5.6/upgrade
- [ ] https://laravel.com/docs/5.5/upgrade
- [ ] https://laravel.com/docs/5.4/upgrade
- [ ] https://laravel.com/docs/5.3/upgrade
- [ ] https://laravel.com/docs/5.2/upgrade

**Comment by carusogabriel** [comment]
Closing as Laravel migrations usually adds new folders struct, new helper methods, and bugfixes. Out of scope for Rector now.

**Comment by TomasVotruba** [comment]
Also handled better by https://laravelshift.com

We can now focus in improving Symfony and architecture Rectors

**Comment by TomasVotruba** [comment]
- maybe make a demo list, just to make this really free:

- also a post https://medium.com/@taylorotwell/laravel-blog-contest-may-mayhem-edition-1aa9f8ac25a9

**Comment by TomasVotruba** [comment]
In the meantime, looks like the author of Laravel Shifts is taking care of the products: https://medium.com/@jasonmccreary/laravel-by-the-numbers-262a1cdd9c72

I really like it and price seems affordable. I also don't want decrease somebody's workin business just because I can.

Let's make focus on projects that do not have such a service - Symfony, Guzzle, Doctrine... first

**Comment by TomasVotruba** [comment]
On the other hand, it might be useful many freelancers who use own free projects.

**Comment by TomasVotruba** [comment]
After hangout with core team, it's not a priority for 2019.

Use https://laravelshift.com/ instead

**Comment by barryvdh** [comment]
But are you still open for PR's? No urgent plans yet, but the Cache minutes (for 5.7.) or seconds (5.8) to DateTime instances seems like a good first migration; https://laravel.com/docs/5.8/upgrade#cache-ttl-in-seconds.

```php
// Laravel 5.7 - Store item for 30 minutes...
Cache::put('foo', 'bar', 30);

// Laravel 5.8 - Store item for 30 seconds...
Cache::put('foo', 'bar', 30);

// Laravel 5.7 / 5.8 - Store item for 30 seconds...
Cache::put('foo', 'bar', now()->addSeconds(30));
```

**Comment by TomasVotruba** [comment]
> But are you still open for PR's?

Definitely! :+1: If features has tests and helps people, no reason to not merge it.

If you want to contribute, there is `vendor/bin/rector create` command that uses `create-rector.yaml.dist` (remove ".dist" part before use). There you can create boiler plate code for tests, level config and description.

**Comment by TomasVotruba** [comment]
Inspired by https://medium.freecodecamp.org/moving-away-from-magic-or-why-i-dont-want-to-use-laravel-anymore-2ce098c979bd

**Comment by TomasVotruba** [comment]
## Laravel 5.7

```diff
// Return a 301 redirect...
-Route::redirect('/foo', '/bar', 301);
+Route::permanentRedirect('/foo', '/bar');
```

**Comment by TomasVotruba** [comment]
## Laravel 5.6

- This `getDateFormat` method is now public instead of protected, probably https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Database/Grammar.php#L196

**Comment by TomasVotruba** [comment]
## Laravel 5.5

- `Illuminate\Console\Command` - fire() → handle()
