### ISSUE TITLE
BarewordStringRector from php72 silently ends 

### ISSUE THREAD

**Issue by simivar** [rectorphp/rector#2927]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.1         |
| Installed as   | composer dependency                      |

I have some legacy code that consists of some standalone scripts. In one of them, there's a function that ends with `exit`. Because of that rule, `BarewordStringRector` ends without any output. 

## Minimal PHP Code Causing Issue

https://getrector.org/demo/b9f2faf0-7853-42cf-a035-880c478413f9#result

## Expected Behaviour

```php
<?php 

function someFuncWithExit() {
	exit;	
}

someFuncWithExit();
$env = 'SOME_STRING';
```

**Comment by TomasVotruba** [comment]
This is not possible to improve, as it's a code with side effect.

- this file needs to be included to analyse strings and present constants (PHP cannot load them without including)
- the function is run
- the code gets exited

Possible workarounds (but be careful about it):

- comment out exit for Rector run
