### ISSUE TITLE
rector-prefixed breaks use statements and triggers errors

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2929]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | since https://github.com/rectorphp/rector/commit/1b052ca9b8e04faad429008af42756380d7dd0b7 |
| Installed as   | prefixed Rector PHAR                      |

It's been quite some time I haven't updated Rector on our project. Today I decided to do so and noticed some issues, so I went back in time (downloading previous versions of rector-prefixed's phar) until I had a working one. Here's the history :

1. Updated Rector to commit https://github.com/rectorphp/rector/commit/d0a2b47587d975dbd2b23639205e4b3a63bc9975 : works ! :+1: 
2. Updated Rector to commit https://github.com/rectorphp/rector/commit/1b052ca9b8e04faad429008af42756380d7dd0b7 broken with `[ERROR] The file "../utils" does not exist (in: phar:///app/rector.phar/src/HttpKernel/../../config).`.
3. Updated Rector to commit https://github.com/rectorphp/rector/commit/6547a656767037113d8bd416e3cb738781f833b9 broken with `Warning: require(phar:///app/rector.phar/vendor/composer/../../helpers/rector_dump_function.php): failed to open stream: phar error: "helpers/rector_dump_function.php" is not a file in phar "/app/rector.phar" in phar:///app/rector.phar/vendor/composer/autoload_real.php on line 57`
4. Updated Rector to commit https://github.com/rectorphp/rector/commit/768b94d9964288f46f62a6244d2ed239c8e80f47 +
Updated Rector to commit https://github.com/rectorphp/rector/commit/02ac09fc2915617bb1e745a803acf1b356dd8e6b +
Updated Rector to commit https://github.com/rectorphp/rector/commit/0e46944b8fa6c522c232e330ba7478b77a4ad30c broken with `[ERROR] The file "../utils" does not exist (in: phar:///app/rector.phar/src/HttpKernel/../../config).`
5. Updated Rector to commit https://github.com/rectorphp/rector/commit/7e0bf17920cdbf9ba7e0aecf5a8f8c05c5592196 and all versions up to HEAD broken with : 

```                                                                   
 [ERROR] Could not process "src/Some/File.php" file,   
         due to:                                                                                                        
         "Class '_HumbugBox551e43838180\JetBrains\PHPStormStub\PhpStormStubsMap' not found".                            
```

And all "use" statements are broken like this : 

```diff
<?php
-use DataURI\Data;
-use DataURI\Dumper;
-use PHPUnit\Framework\TestCase;
-use Symfony\Component\Filesystem\Filesystem;
-use Webmozart\Assert\Assert;
-
+use Data;
+use Dumper;
+use TestCase;
+use Filesystem;
+use Assert;
```

6. Updated Rector to commit [HEAD](https://github.com/rectorphp/rector/commit/945c35465480fdf7561092ade60483ca4de20894) also has the following extra error :
                                                                    
```                                                    
 [ERROR] Could not process "src/Some/File.php" file by                      
         "Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector", due to:                                       
         "Call to a member function changeVarType() on null".                                                           
```

Any idea what changes might have triggered all this ?

**Comment by TomasVotruba** [comment]
Failing CI would be much better :+1:

**Comment by gnutix** [comment]
> Any idea what changes might have triggered all this ?

Means I have absolutely no idea what might be broken, nor why, so making CI fail might be too hard...

**Comment by TomasVotruba** [comment]
Closing as duplicated of #2879

**Comment by gnutix** [comment]
This is not exactly a duplicate of #2879... There's two extra errors in here that are not listed in that issue : 

1. the broken `use` statements
2. `"Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector", due to "Call to a member function changeVarType() on null"`

**Comment by TomasVotruba** [comment]
Do not mix 2 issues at once. please re-open with new ones. Also, do not re-open issues, or I'll have to decrease your access. it's really frustrating to organize Rector issues with you doing it.

Demo link for this is needed.
