### ISSUE TITLE
[ServiceLocatorToDIRector] Error "Unable to resolve repository argument"

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2930]
# Bug Report

When running Rector with set `doctrine-repository-as-service`, I get the following error : 

```                                                                                           
 [ERROR] Could not process "tests/Unit/App/Doctrine/ItemRepositoryTest.php" file by  
         "Rector\Rector\Architecture\RepositoryAsService\ServiceLocatorToDIRector", due to:                             
         "Unable to resolve repository argument".                                                                       
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/c301546c-7d92-4b99-b1b6-1955831a6f39

## Expected Behaviour

No errors ? ^^

**Comment by gnutix** [comment]
I'm not sure how the demo site works, but right now if I click again the "process" button on the demo I provided, it still fails. Does it uses master? Is there a delay?

**Comment by TomasVotruba** [comment]
> I'm not sure how the demo site works, but right now if I click again the "process" button on the demo I provided, it still fails. Does it uses master? Is there a delay?

I think it needs to be manually updated.

**Comment by JanMikes** [comment]
Hi, i have updated the demo's docker image right now, added cron to periodically update and working on a webhook trigger.

Thank you 👍

**Comment by JanMikes** [comment]
I have checked with given demo and it still fails. For me it seems that the code is incompatible with that set. @TomasVotruba is the usage correct?

**Comment by TomasVotruba** [comment]
The original code should be fixed. Maybe there were more bugs, but I covered just one.

**Comment by gnutix** [comment]
This Rector should not apply on a Test file I guess ?

**Comment by TomasVotruba** [comment]
Location doesn't matter. The goal is to convert 'strings' to `Class::constants`

**Comment by TomasVotruba** [comment]
Confirm original issues is fixed, just tested locally the file

**Comment by gnutix** [comment]
Confirmed! Thanks. :)
