### ISSUE TITLE
Rename PhpStorm stubs file extensions

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#2936]
# Feature Request

This is a problem: https://twitter.com/frankdejonge/status/1232358285757513729
 
## Diff 

This is how I solved it: https://twitter.com/OndrejMirtes/status/1232412799852302337 (https://github.com/phpstan/phpstan-src/commit/e18b3b47c8e1b91f1844dd3c91d961e912476d86)

I suggest you to do the same.

Related: https://github.com/rectorphp/rector/issues/2602

**Comment by Aerendir** [comment]
It is way more simple.

Go to Preferences > Directories.

Then use the field "Exclude files" and put into `*stub*`.

**Comment by ondrejmirtes** [comment]
Yes, but you're generating work for all the users. With this proposed change, nobody has to do it anymore.
