### ISSUE TITLE
Rector adds whitespace in comments

### ISSUE THREAD

**Issue by fsok** [rectorphp/rector#2939]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |   dev-master@37cd497   |
| Installed as   | composer dependency     |

When a doc block line only contains a whitespace char, rector adds another whitespace char. When rector is run again this keeps happening - in each run another whitespace is added.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/0a8a1c75-b66b-4437-ab01-aa1ad7fca0c2

## Expected Behaviour

No change of doc block.

**Comment by Aerendir** [comment]
The demo doesn't work as you describe: it simply remove a line and then adds it again; the same for the closing of the docblock.

**Comment by TomasVotruba** [comment]
Seems like it's `\r\n` vs `\n` problem.

![image](https://user-images.githubusercontent.com/924196/75434481-e3f61600-5951-11ea-8d6d-1a53a6163184.png)

**Comment by TomasVotruba** [comment]
@fsok I guess you're using Windows, right?

**Comment by TomasVotruba** [comment]
I tried to debug it for few hours, but I'm not very experienced with Windows spacing on Linux. 

If you're able to send failing test case and fix it, I'd be happy to merged it.

**Comment by dimacros** [comment]
It happens to me now and I am using linux. Example file:

```
<?php

namespace AppBundle\Domain\Shipment;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Embeddable
 */
final class TransportMeans implements \JsonSerializable
{
    /**
     * Marca del vehiculo
     *                                                                
     * @ORM\Column(type="string")
     */
    private $vehicleBrand;

    /**
     * Numero de placa del vehiculo que realiza el traslado
     *                                                                
     * @ORM\Column(type="string")
     */
    private $licensePlateNumber;

    public function __construct(
        string $vehicleBrand, 
        string $licensePlateNumber
    ) {
        $this->vehicleBrand = $vehicleBrand;
        $this->licensePlateNumber = $licensePlateNumber;
    }

    public function jsonSerialize()
    {
        return [
            'vehicleBrand' => $this->vehicleBrand(),
            'licensePlateNumber' => $this->licensePlateNumber(),
        ];
    }

    public function vehicleBrand(): string
    {
        return $this->vehicleBrand;
    }

    public function licensePlateNumber(): string
    {
        return $this->licensePlateNumber;
    }
}

```

**Comment by dimacros** [comment]
It happens to me now and I am using linux.
Output:
![screenshot](https://i.imgur.com/RYje4xz.png)

Example file:
```
namespace AppBundle\Domain\Shipment;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Embeddable
 */
final class TransportMeans
{
    /**
     * Marca del vehiculo
     *                                                                
     * @ORM\Column(type="string")
     */
    private $vehicleBrand;

    /**
     * Numero de placa del vehiculo que realiza el traslado
     *                                                                
     * @ORM\Column(type="string")
     */
    private $licensePlateNumber;
}
```

**Comment by fsok** [comment]
@TomasVotruba thanks for investigating.

No, I don't use Windows.

I added a failing test in https://github.com/rectorphp/rector/pull/2943.

Seems to have something to do with this line: https://github.com/rectorphp/rector/blob/master/packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php#L224
