### ISSUE TITLE
Parallel run speedup feature

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#2971]
# Inspiration

- https://github.com/phpstan/phpstan-src/commit/9124c66dcc55a222e21b1717ba5f60771f7dda92
- https://github.com/phpstan/phpstan-src/pull/125
- https://github.com/symplify/symplify/pull/3325

## Notes

* https://tomasvotruba.com/blog/introducing-up-to-16-times-faster-easy-coding-standard/

**Comment by TomasVotruba** [comment]
@JanMikes this is starting point with few resources

**Comment by TomasVotruba** [comment]
@JanMikes Here are the 3 processed I talked about yesterday:
https://github.com/rectorphp/rector/blob/220e2c9daf444bd194e167f11d3e92f743aed248/src/Application/RectorApplication.php#L140-L169

Each of them needs to be parallelized:

- run step 1 in parallel
- finish
- run step 2 in parallel
- finish
- run step 3 in parallel
- finish

**Comment by JanMikes** [comment]
I considered following packages:
- AMP
- ReactPHP
- Swoole
- Spatie/async

AMP is the winning choice for me and i will implement parallel running with.

I dont like ReactPHP and Swoole bcoz they both use sockets and AMP has better performance than Spatie/async + spatie/async probably does not work on windows (due to how it handles signals in unix vs windows.

**Comment by vladyslavstartsev** [comment]
@JanMikes @TomasVotruba any progress on this?

**Comment by vladyslavstartsev** [comment]
this wil be SUPER useful

**Comment by TomasVotruba** [comment]
> @JanMikes @TomasVotruba any progress on this?

Not really. 

> this will be SUPER useful

You can't imagine how useful this would be.
This challange is looking for its hero :)

**Comment by JanMikes** [comment]
Hi, unfortunately this issue is currently blocked - i have not found a way how to serialize+deserialize nodes from php parser.

Because of how parallelism works and the fact, that parent process must be able to communicate (exchange data) with children processes in some format (for example json) and since we need to pass nodes between processes and not able to, i could not get it working.

**Comment by vladyslavstartsev** [comment]
@JanMikes just an idea. Maybe it's worth a look at how psalm/phpstan/php_codesniffer does this?

**Comment by ruudk** [comment]
I'm trying to run rector on a very large project and every run takes ±60 minutes on a 3,6 GHz 8-Core Intel Core i9. 

To speed it up and take advantage of all the cores in my machine I chunk all my directories and run them through gnu `parallel`
```
find src src-dev tests -type d -d 2 | parallel "echo \"Processing {}\"; vendor/bin/rector process {}"
```

**Comment by JanMikes** [comment]
@vladyslavstartsev i did, but all of these works a little different and does not need to serialize AST nodes, so their solution is not applicable here :-/ 

@ruudk it might work, but i would be careful, sometimes there might be some unintended effects, as afaik rector needs context of all files and it might break in some specific conditions.

**Comment by olivernybroe** [comment]
@JanMikes What about the json serialization that php parser has, can you use that for serialisation?
https://github.com/nikic/PHP-Parser/blob/master/doc/component/JSON_representation.markdown

**Comment by JanMikes** [comment]
Hi @olivernybroe!

Hmm, that looks pretty good and i think it could actually work!! Actually im busy with analysing other feature request on rectorphp, in next week i can give it a try!

**Comment by olivernybroe** [comment]
@JanMikes Amazing! Hope it works.

Thanks for looking into this btw. ❤️

**Comment by TomasVotruba** [comment]
Inspiration in successful implementation in ECS:

* https://github.com/symplify/symplify/pull/3332
* https://github.com/symplify/symplify/pull/3325

**Comment by TomasVotruba** [comment]
I have good news about refreshing of this topic :slightly_smiling_face: 

We've added first jsonable objects to Rector https://github.com/rectorphp/rector-src/pull/1178 - first preparation step to pass json data around

**Comment by TomasVotruba** [comment]
Related package https://clue.engineering/2018/introducing-reactphp-ndjson

**Comment by TomasVotruba** [comment]
One more step closer - file processors now returns arrays of data, that allows parallel process json :tada: 
https://github.com/rectorphp/rector-src/pull/1378

**Comment by TomasVotruba** [comment]
All file processors including @typo3-rector now return uniformed array of jsonable objects.
We're getting closer folks :+1: :heart_eyes:

**Comment by PhilETaylor** [comment]
Are you interested in any feedback at this point? I get this when PARALLEL option enabled from time to time.

Please feel free to ignore this - at this time - if it distracts from your great work, just trying to help :) 

```
PHP Fatal error:  Uncaught RectorPrefix20211228\Symplify\EasyParallel\Exception\ParallelShouldNotHappenException: Process "z5eb1fbfsu" not found. in /Users/phil/Sites/manage.mysites.guru/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ProcessPool.php:28
Stack trace:
#0 /Users/phil/Sites/manage.mysites.guru/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ProcessPool.php(45): RectorPrefix20211228\Symplify\EasyParallel\ValueObject\ProcessPool->getProcess('z5eb1fbfsu')
#1 /Users/phil/Sites/manage.mysites.guru/vendor/rector/rector/packages/Parallel/Application/ParallelFileProcessor.php(135): RectorPrefix20211228\Symplify\EasyParallel\ValueObject\ProcessPool->quitProcess('z5eb1fbfsu')
```

**Comment by TomasVotruba** [comment]
Thanks ☺️

How can I reproduce? Ideally failing GitHub action would help

**Comment by PhilETaylor** [comment]
unfortunately I cannot replicate in GitHub Actions... only on my intel and M1Pro Macs at present. 

The actual run is astonishingly quick - and this bombs out right after the last file has been processed. 

I'll keep digging. I know Im early adopting here :)

**Comment by PhilETaylor** [comment]
I came back to this today and cannot replicate the process bug with the very latest version. 

Running on a 2020 Intel-Based iMac - My stats are impressive. 1302 files. Run with no cache (manually deleted cache before both these runs)

With `->set(Option::PARALLEL, true)` = 33 secs

<img width="863" alt="Screenshot 2021-12-30 at 14 50 56" src="https://user-images.githubusercontent.com/400092/147762284-cc40aae0-96c3-432a-afdb-a0e0e0bb854f.png">

With `->set(Option::PARALLEL, false)` = 2m 57secs

<img width="833" alt="Screenshot 2021-12-30 at 14 53 34" src="https://user-images.githubusercontent.com/400092/147762492-c48ecb96-e27b-4d74-be0d-6d712c39e5ca.png">

**Comment by TomasVotruba** [comment]
Wow, thanks for reaching out with beautiful data :+1: 

Could you also try both runs with some change, e.g. add obvious dead code?

How many threads do you have... 8?

**Comment by PhilETaylor** [comment]
Sure, Im out for a walk right now, but when I get home I'll checkout my git tag of this same code from last year (before using rector/phpstan/phpsalm/ecs), and run it on that (And then go make a coffee as there will be LOADS to fix haha) and I'll report back.

**Comment by TomasVotruba** [comment]
Thank you!

> And then go make a coffee as there will be LOADS to fix haha 

:laughing: :+1: 

> its a 10-core i9 3.6Ghz iMac

Ah, I see my calculation was wrong and that's expected result :+1:

**Comment by PhilETaylor** [comment]
My old code was so bad that it just created Exceptions and rector would not complete. :-( 

Therefore, I have attempted to downgrade my clean project (along with my normal rector config, many rules running) with the following to cause file changes.

`$containerConfigurator->import(DowngradeLevelSetList::DOWN_TO_PHP_80);`

Caches manually cleaned before runs. I also note the Parallel does 1282/1302ish files, almost immediately, and then slows down for a couple of seconds before completing. 

1264 files. 143 files have been changed by Rector. 
Parallel
vendor/bin/rector process  184.94s user 18.51s system 595% cpu 34.165 total
vendor/bin/rector process  175.06s user 17.40s system 603% cpu 31.874 total

Not Parallel
vendor/bin/rector process  110.00s user 3.84s system 98% cpu 1:56.02 total
vendor/bin/rector process  107.30s user 3.24s system 99% cpu 1:50.88 total

And now from my clean PHP 8.1 codebase downgrading to 7.4 ( I also note the Parallel does 1282/1302ish files, almost immediately, and then slows down for a couple of seconds before completing.)

``$containerConfigurator->import(DowngradeLevelSetList::DOWN_TO_PHP_74);``

1264 files. 173 files have been changed by Rector. 
Parallel
vendor/bin/rector process  204.85s user 21.29s system 591% cpu 38.256 total
vendor/bin/rector process  207.09s user 21.60s system 596% cpu 38.317 total

Not Parallel
vendor/bin/rector process  129.00s user 3.33s system 99% cpu 2:12.60 total
vendor/bin/rector process  129.71s user 3.35s system 99% cpu 2:13.20 total

let me know if you want anything else, or when you want another test done later in development.

**Comment by fancyweb** [comment]
I tested it on a project (before/after):
![Screenshot from 2021-12-30 18-35-13](https://user-images.githubusercontent.com/3658119/147775295-e9e755d3-e2ea-4ade-91c3-05fb1da03540.png)

However, I noticed that non parallel run on current 0.12.x-dev is way longer than the latest 0.12 version (4min25s in my case).

**Comment by TomasVotruba** [comment]
>  I also note the Parallel does 1282/1302ish files, almost immediately, and then slows down for a couple of seconds before completing.

That's due to long-lasting files. Usually the largest file is the one all proceces wait for. PHPStan and ECS behaves the same way.

Numbers look good, thank you :+1: 

Does the diff with `--dry-run` and file changing work propperly?

**Comment by TomasVotruba** [comment]
@fancyweb Thank you for sharing. Which is the time for process run? I never used these metrics.

**Comment by PhilETaylor** [comment]
> Does the diff with --dry-run and file changing work propperly?

Seems to work - I did not check every diff and every file change, but it did give me a diff in colour and the files do change

**Comment by fancyweb** [comment]
@TomasVotruba Unfortunately, I don't really know much about the "time" thing, all I know is that real = the real elapsed time for the human in the chair :smile: It looks like my computer has 12 procs.

**Comment by samsonasik** [comment]
Tested in CodeIgniter4 project in Github action, 2x faster 
https://github.com/codeigniter4/CodeIgniter4/pull/5523

![Screen Shot 2022-01-02 at 04 25 32](https://user-images.githubusercontent.com/459648/147860507-077547a4-3cb3-4500-92f4-ca825736dcc3.png)

**Comment by olivernybroe** [comment]
Just wanted to say that we added the new parallel feature to our codebase which is rather large and no errors happened, just an amazing speed improvement 😍 

Thank you so much for your hard work!
![image](https://user-images.githubusercontent.com/5870441/154663219-bb6a530d-89ba-4e1a-8b81-ca4f581f03eb.png)

**Comment by TomasVotruba** [comment]
@olivernybroe That's amazing, thanks for sharing the screenshot :tada:

**Comment by AlexSkrypnyk** [comment]
365 files

| Cache   | Number of processes     | Job size | Time (s) |
|---------|-------------------------|----------|------|
| absent  | parallel() not used     | none     | 45   |
| present | parallel() not used     | none     | 2.7  |
| absent  | 16                      | 16       | 45   |
| present | 16                      | 16       | 2.7  |
| absent  | 100                     | 100      | 51   |
| present | 100                     | 100      | 3.3  |
| absent  | 100                     | 16       | 47   |
| present | 100                     | 16       | 2.8  |
| absent  | 16                      | 100      | 56   |
| present | 16                      | 100      | 2.8  |
