### ISSUE TITLE
[Console] make --version show version for composer package

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#298]
Ref https://github.com/Symplify/Symplify/issues/579#issuecomment-358059063

**Comment by carusogabriel** [comment]
So we just need to add https://github.com/Jean85/pretty-package-versions?

**Comment by TomasVotruba** [comment]
Yes, it waits for monorepo support at the moment: https://github.com/Ocramius/PackageVersions/pull/57
But it might take a while to build a monorepo here.
