### ISSUE TITLE
AddArrayParamDocTypeRector adds a @param instead of editing the existing one

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#2983]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.3              |
| Installed as   | composer dependency                      |

The rector `Rector\TypeDeclaration\Rector\ClassMethod\AddArrayParamDocTypeRector` adds a new annotated `@param` instead of editing the existing one.

This causes a double annotation for the same param.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/c33ba461-8163-4aef-8c21-ed1db7188f76

```diff
/**
      * @param array $meta
      *
-     * @return Message
-     */
+     * @return Message
+     * @param mixed[] $meta
+     */
     public function setMeta(array $meta): self
     {
         $this->meta = $meta;
```

## Expected Behaviour

The expected behavior is that the already existing param is the one edited or, at least, that it is removed and only the one created by Rector remains in the docblock.

**Comment by TomasVotruba** [comment]
Any idea why?

**Comment by Aerendir** [comment]
I didn't inspected the issue honestly: it happened on an app of a client and didn't had the time...
