### ISSUE TITLE
comments get removed by rector

### ISSUE THREAD

**Issue by C0pyR1ght** [rectorphp/rector#2989]
rector removes the comments on the given example. This only happens if there is no whitespace between // and the first letter and if there is only a single word. Also notice that only the comments inside `array()` get removed. So not all single word comments with no whitespace are affected.

This behavior seems to occur on serveral / all rectors.

**expected**: comments should remain
```
$vetechs = array(
            //Transferdruck
            4 => array(
                'description' => $translations[$this->t_getLanguage()->getKuerzel()][4],
                'image' => '/img/vearten/ink.svg'
            ),

            //Stick
            5 => array(
                'description' => $translations[$this->t_getLanguage()->getKuerzel()][5],
                'image' => '/img/vearten/bestickbar.svg'
            )
        );
```

https://getrector.org/demo/0721014a-c0f7-4f6f-b1ee-3fe9c7a09e23

**Comment by TomasVotruba** [comment]
Fixed
