### ISSUE TITLE
invalid phpdoc should not be changed

### ISSUE THREAD

**Issue by C0pyR1ght** [rectorphp/rector#2991]
rector changes invalid phpdoc annotations instead of leaving them as they are.

This behavior seems to occur on serveral / all rectors.

**expected**: `@return multitype:number` should remain the same
````
	/**
    * count artfarbenids in aset of articles (used in basket and stock)
    *
    * @param unknown $array
    * @return multitype:number
    */
````

see: https://getrector.org/demo/ebb0f613-a6df-4231-9aa2-a43dc22aeea4

**Comment by TomasVotruba** [comment]
Fixed
