### ISSUE TITLE
[ERROR] You have requested a non-existent service "Doctrine\Common\Annotations\AnnotationReader".

### ISSUE THREAD

**Issue by vaklinzi** [rectorphp/rector#2995]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.0 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency / prefixed Rector PHAR                      |

"symplify/easy-coding-standard": "^7.2",

"rector/rector": "^0.7.3"

![image](https://user-images.githubusercontent.com/16841490/75771988-c5c65680-5d53-11ea-8e6d-fae12cffdd51.png)

![image](https://user-images.githubusercontent.com/16841490/75771946-a8918800-5d53-11ea-9c0f-9d4ce4a6783b.png)

![image](https://user-images.githubusercontent.com/16841490/75772089-f1494100-5d53-11ea-983e-5409681313e7.png)

No matter what I run as `rector` command I receive:

![image](https://user-images.githubusercontent.com/16841490/75771768-4d5f9580-5d53-11ea-954a-0fd8f0095494.png)

![image](https://user-images.githubusercontent.com/16841490/75772178-1b9afe80-5d54-11ea-8103-79249a603023.png)

**Comment by TomasVotruba** [comment]
What happens when you install doctrine/common package?

**Comment by vaklinzi** [comment]
@TomasVotruba The same, no difference:

![image](https://user-images.githubusercontent.com/16841490/75773200-16d74a00-5d56-11ea-9902-0d62bc739fa6.png)

![image](https://user-images.githubusercontent.com/16841490/75773222-22c30c00-5d56-11ea-9c70-8ae6c5239a63.png)

**Comment by TomasVotruba** [comment]
Sorry, the namespace was wrong.
It's `doctrine/annotations`

**Comment by TomasVotruba** [comment]
If the problem still persist, failing CI Github Action is needed.

Just copy paste this *.yaml and replace last `run` section with your code: https://github.com/rectorphp/rector/pull/2891/files

**Comment by vaklinzi** [comment]
@TomasVotruba thank you for time and effort. Maybe the problem is something with my configuration. The strange is that if I run Rector from the .composer folder (I use global installation), everything works fine:

![image](https://user-images.githubusercontent.com/16841490/75801203-6aac5800-5d83-11ea-8f29-ff44ecf4dd41.png)

But if I run it from the somewhere else, even from PHPStorm, it doesn't work and I have the same error from above:

![image](https://user-images.githubusercontent.com/16841490/75801359-acd59980-5d83-11ea-9411-e12db766418d.png)

**Comment by vaklinzi** [comment]
I fix it with changing `Working directory` in PHPStorm, which is working as expected:

![image](https://user-images.githubusercontent.com/16841490/75804809-4d7a8800-5d89-11ea-80dc-f085b33fdc17.png)

@TomasVotruba Thank you again!

**Comment by TomasVotruba** [comment]
Oh. I never used composer this way, always just from CLI

Thanks for sharing
