### ISSUE TITLE
Regression: comments can no longer be added

### ISSUE THREAD

**Issue by afilina** [rectorphp/rector#3000]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.0+              |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

Since the upgrade to v0.7.0, comments no longer get added when I call
`$statement->setDocComment(new Doc('my comment'));`. This is currently breaking half of my custom rectors.

## Expected Behaviour

Expected to get a comment on top of a statement. Not getting any comments anymore.

**Comment by afilina** [comment]
Sending 200 USD to whoever fixes this regression.

**Comment by TomasVotruba** [comment]
You need to use PhpDocInfo object.
Failing code of your rule would be better.

**Comment by TomasVotruba** [comment]
If you provide the Rector rule I can handle it tomorrow at 8-12 UCT

**Comment by TomasVotruba** [comment]
Solved by https://github.com/rectorphp/rector/pull/3005
