### ISSUE TITLE
Unexpected behavior when using `-e` option

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3002]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.3 (invoke `vendor/bin/rector --version`)              |
| Installed as   | prefixed Rector PHAR                      |

## Minimal PHP Code Causing Issue

I don't know how to create a small demo from this.

I created 3 very similar tests using Github Actions, that demonstrate the issue:
The demo is using Drupal and a module called `metatag`.
When testing a certain path in this module there's another library missing `drupal/console`.

- [x] Running Rector with `drupal/console` library - results in expected behavior - no changes are needed.
Test: https://github.com/rectorphp/rector/runs/484080076?check_suite_focus=true#step:4:237
```
 [OK] Rector is done!                                                           
```

- [x] Running Rector without `drupal/console` library - results in expected behavior - error that autoload files are missing.
Test: https://github.com/rectorphp/rector/runs/484080045?check_suite_focus=true#step:4:206
```
 [ERROR] Could not process                                                      
         "/home/runner/work/rector/rector/test-paths/drupal-rector073/web/module
         s/contrib/metatag/src/Generator/MetatagGroupGenerator.php" file, due   
         to:                                                                    
         "Analyze error: "Class Drupal\Console\Core\Generator\Generator not     
         found and could not be autoloaded.". Include your files in "parameters 
         > autoload_paths".                                                     
         See https://github.com/rectorphp/rector#extra-autoloading".            

 [ERROR] Could not process                                                      
         "/home/runner/work/rector/rector/test-paths/drupal-rector073/web/module
         s/contrib/metatag/src/Generator/MetatagTagGenerator.php" file, due to: 
         "Analyze error: "Class Drupal\Console\Core\Generator\Generator not     
         found and could not be autoloaded.". Include your files in "parameters 
         > autoload_paths".                                                     
         See https://github.com/rectorphp/rector#extra-autoloading".            
```

- [ ] But running Rector without `drupal/console` library and with the option `-e` - results in unexpected behavior - it seems like Rector runs code linting rule or something, which was not in the config file.
Test: https://github.com/rectorphp/rector/runs/484079970?check_suite_focus=true#step:4:206
```
 use Drupal\Console\Core\Generator\Generator;
 use Drupal\Console\Extension\Manager;
 use Drupal\Console\Core\Utils\TwigRenderer;
-
 /**
  * Drupal Console plugin for generating a group.
  */
-class MetatagGroupGenerator extends Generator {
-
-  /**
-   * The console manager.
-   *
-   * @var \Drupal\Console\Extension\Manager
-   */
-  protected $extensionManager;
-
-  /**
-   * The twig renderer.
-   *
-   * @var \Drupal\Console\Core\Utils\TwigRenderer
-   */
-  protected $renderer;
.
.
.
...
```

## Expected Behaviour
When using `-e` option, I expect Rector to skip the files that are missing, without printing additional errors, but also without applying a code linting rule.

**Comment by TomasVotruba** [comment]
Looks like format preserving issues. Basically spaces/tabs are changed, right?

**Comment by shaal** [comment]
That's correct.
I also noticed that 
```
class MetatagTagGenerator extends Generator
```
Changed to

```
class MetatagTagGenerator extends \Drupal\Console\Core\Generator\Generator
```

**Comment by TomasVotruba** [comment]
Be sure to read about AST limits:
https://github.com/rectorphp/rector/blob/master/README.md#how-to-apply-coding-standards

**Comment by shaal** [comment]
I wasn't expecting rector to apply any coding standards because it wasn't in the config file.

That is why I think it's a bug: an edge case of missing files AND `-e` option is enabled, adds additional rules that were not suppose to run.

**Comment by TomasVotruba** [comment]
It seems no rule was added, it's just reprited without preserving format.

**Comment by TomasVotruba** [comment]
If that can be somehow worked around (rarely can) or it can be handled by coding standard (much more reliable way, see the README) are 2 options for your stack.

I prefer using coding standards and not care about AST formatting.
In the end code is both refactored and 100 % formated to respect my needs.

**Comment by shaal** [comment]
I am trying to get consistency in running Rector.
I know I can run code-quality special rules when I need.

This issue is about the unexpected result (breaks the consistency) when running Rector with `-e` option.
I run `-e` option to avoid error messages of autoload files that are missing. I don't want to get new diffs because of that.

**Comment by shaal** [comment]
I tested this with Rector version 0.7.6 this is still an issue.
Is there any way I can describe the problem better?

I do not want any formatting / code standards running, when I don't call it in my rector.yaml file (and right now it is running when I add the `-e` option)

**Comment by TomasVotruba** [comment]
Failing test case is needed

**Comment by shaal** [comment]
Thank you @TomasVotruba 

In the main description of this issue, I referenced the 3 tests I already created that show this issue. Are these tests sufficient? is there a different test I should create?

**Comment by TomasVotruba** [comment]
I don't see our CI failing. What PR is it in?

**Comment by shaal** [comment]
Here's the PR - https://github.com/rectorphp/rector/pull/3001

This is the failing CI (failing = unexpected rule is running because I added `-e` option)
https://github.com/rectorphp/rector/runs/484079970?check_suite_focus=true#step:4:206

**Comment by TomasVotruba** [comment]
Please retry with current master. There've been many fixes since last month

**Comment by shaal** [comment]
Thank you @TomasVotruba.
I updated to latest version (Drupal-Rector 0.4.0 which uses Rector 0.7.16)

I still see the same behavior -
Without `-e`, Rector display autoload errors, and doesn't find anything to fix (which is what I expect)
https://github.com/rectorphp/rector/runs/606539385?check_suite_focus=true#step:6:10

With `-e`, Rector find things to fix! (which is unexpected
https://github.com/rectorphp/rector/runs/606539451?check_suite_focus=true#step:6:13

I also added another run with `-e` and `--debug` if that helps.

**Comment by shaal** [comment]
Oh wait. what?
`-e` vs. `-e --debug` behave differently!

On the run with `-e --debug` Rector did **not** find anything to fix.

**Comment by TomasVotruba** [comment]
Looking at option `e` now, it was added to improve working with legacy projects that misses autoloading.

Yet, nowadays Rector and PHPStan that we use here 100 % needs classes to be autoloaded, so the `e` option willl be dropped. It only creates false positive bugs that cannot be solve without autoloading. PHPStan has same approach and shows these errors.
