### ISSUE TITLE
Check for sql injections and provide escaping strategy

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#3006]
# Feature Request

Inspired by https://github.com/emanuil/php-reaper I thought about rector beeing able to fix sql injection vulnerabilities by checking queries sent via pdo and check for unescaped variables used in the queries 
 
## Example

Before
```
$pdo = new PDO( ... );
$a = $_GET['a'];
$sql = 'SELECT name, color, calories FROM fruit WHERE a='. $a .' ORDER BY name';
$pdo->query($sql);
```

After
```
$pdo = new PDO( ... );
$a = $_GET['a'];
$sql = 'SELECT name, color, calories FROM fruit WHERE a='. $pdo->quote($a) .' ORDER BY name';
$pdo->query($sql);
```

Wdyt?

If this is feasible we could further think about transaction handling like https://emanuilslavov.com/php-unlocker/ - which is a separate issue, for sure.

**Comment by TomasVotruba** [comment]
I had similar idea before, but as I don't use SQL for ages, I had no expertise to do it: https://github.com/rectorphp/rector/issues/1579

So thanks for re-opening the idea with real example :)

<br>

This looks pretty clear. Concat and before/after is string with SQL.
Care to send PR?

**Comment by TomasVotruba** [comment]
Closing as stale
