### ISSUE TITLE
ArgumentTypeProbe: possibility to change file path / use database

### ISSUE THREAD

**Issue by simivar** [rectorphp/rector#3007]
# Feature Request

It would be nice to have an option to change path of the file where probes are saved or change it to, for example, database.

**Comment by TomasVotruba** [comment]
PR is welcomed.

**Comment by simivar** [comment]
@TomasVotruba is there any service (rule) that accepts parameters (options) right now?

**Comment by TomasVotruba** [comment]
Parameters can be used in `config.yaml` like this:

```yaml
parameters:
    auto_import_names: false
```

Then just pass `ParameterProvider` service and get parameter like this: https://github.com/rectorphp/rector/blob/fa5d62948abe5847b1b9deb516477b5def4316b5/rules/coding-style/src/Application/NameImportingCommander.php#L44

**Comment by TomasVotruba** [comment]
Closing as answered. Feel free to send PR with parameter change
