### ISSUE TITLE
[CodeQuality] ForToForeachRector incorrectly replaces other uses of loop variable

### ISSUE THREAD

**Issue by crishoj** [rectorphp/rector#3026]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.6              |
| Installed as   | composer dependency                      |

`ForToForeachRector` replaces e.g. 
- `for ($i = 0; $i < count($tokens); $i++) { $token[$i]` with 
- `foreach ($tokens as $token) { $token`

However, when the loop counter `$i` is used to index _other_ variables in the loop, these get replaced as well.

As an example, the statement `$other[$i]` is also changed to `$token`, which is incorrect. 

## Minimal PHP Code Causing Issue

https://github.com/crishoj/rector/commit/052fb9a506783fb7577e7ff51c046b30444eed31

## Expected Behaviour

In cases where the loop index variable is also used for other purposes, `ForToForeachRector` should probably skip the loop entirely.

**Comment by TomasVotruba** [comment]
Please send the failing code in pull-request, as a new fixture file

**Comment by crishoj** [comment]
Sure, here is a PR with the new fixture: #3027
