### ISSUE TITLE
Question regarding ImportFullyQualifiedNamesRector

### ISSUE THREAD

**Issue by bavamont** [rectorphp/rector#3028]
When i have two classes with the same name (but with different namespaces), ImportFullyQualifiedNamesRector adds "use Classname" for the first class it finds, but ignores the second one ffrom the different namespace.

for example:

$a = new \Model\A\MyClass();    // namespace of the class is Model\A 
$b = new \Model\B\MyClass();    // namespace  of the class is Model\B 

ImportFullyQualifiedNamesRector does this:

use Model\A\MyClass;
$a = new MyClass();
$b = new \Model\B\MyClass();

how can i "force" it to also add the "use" for the second class, to have (for example) something like this:

use Model\A\MyClass as AMyClass; // or maybe as ModelAMyClass
use Model\B\MyClass as BMyClass; // or maybe as ModelBMyClass
$a = new AMyClass(); // or maybe new ModelAMyClass();
$b = new BMyClass(); // or maybe new ModelBMyClass();

**Comment by TomasVotruba** [comment]
It's not possible now and not in the scope of this rule.
This would require standalone rule that imports same-named classes with specific format of alias.

**Comment by bavamont** [comment]
Ah, okay. Thanks for the fast reply!
I’ll take a look at how to create a new rule.

**Comment by TomasVotruba** [comment]
Feel free to send PR with such rule, I'll be happy to merge it.

**Comment by TomasVotruba** [comment]
This might be source of inspiration: https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#removeunusedaliasrector
