### ISSUE TITLE
ReturnTypeDeclarationRector does not respect multiple method returns

### ISSUE THREAD

**Issue by SergeC** [rectorphp/rector#3043]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector v0.7.7              |
| Installed as   | composer dependency                      |

I generated Symfony CRUD with a command `bin/console make:crud`.

## Minimal PHP Code Causing Issue
Controller action method looks like this:
```php
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        if (!$user instanceof UserInterface) {
            throw new AccessDeniedException;
        }
        $page = new Page();
        $page->setUser($user);
        $form = $this->createForm(PageType::class, $page);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($page);
            $entityManager->flush();

            return $this->redirectToRoute('page_index'); // returns RedirectResponse
        }

        return $this->render('page/new.html.twig', [
            'page' => $page,
            'form' => $form->createView(),
        ]); // returns Response
    }
```
The `RedirectResponse` is inherited from `Response`. Rector is changing return type to `RedirectResponse` by mistake.

```
-    public function new(Request $request): Response
+    public function new(Request $request): RedirectResponse
```

## Expected Behaviour
Handle multiple returns from a method with different types. Don't change `Response` return type to `RedirectResponse` in this case.

**Comment by SergeC** [comment]
Changing this way creates a psalm error:
```
ERROR: MoreSpecificReturnType - src/Controller/PageController.php:39:44 - The declared return type 'Symfony\Component\HttpFoundation\RedirectResponse' for App\Controller\PageController::new is more specific than the inferred return type 'Symfony\Component\HttpFoundation\Response'
    public function new(Request $request): RedirectResponse
```

**Comment by TomasVotruba** [comment]
Demo link is needed https://getrector.org/demo

**Comment by SergeC** [comment]
@TomasVotruba https://getrector.org/demo/16c6fe12-9774-4820-9025-95926f89791e

**Comment by TomasVotruba** [comment]
Thanks, I'm on it

**Comment by SergeC** [comment]
@TomasVotruba Nice. Thanks a lot.
