### ISSUE TITLE
How to disable inlining of a constant in annotation

### ISSUE THREAD

**Issue by SergeC** [rectorphp/rector#3044]
# Question
How to disable this?

```diff
    public const RATINGS_DISCRIMINATOR_MAP = [
        '5star' => FiveStar::class,
        '4star' => FourStar::class,
    ];
     /**
      * @Assert\NotBlank()
-     * @Assert\Choice(choices=App\Entity\Rating\Rating::RATINGS_DISCRIMINATOR_MAP)
+     * @Assert\Choice({"5star":"App\Entity\Rating\FiveStar", "4star":"App\Entity\Rating\FourStar"})
      */
```

**Comment by TomasVotruba** [comment]
Demo link is needed https://getrector.org/demo

**Comment by SergeC** [comment]
@TomasVotruba I have no idea how to create an online demo from Symfony project. May be with GitHub repo? Here is my attempt to create an online demo https://getrector.org/demo/e01d38b8-23ca-44b8-8230-41fb7b583ba8 but this is not reproducing an issue. However local output looks like this:
```
    ---------- begin diff ----------
--- Original
+++ New
@@ -16,7 +16,7 @@
     private ?string $title = null;
     /**
      * @Assert\NotBlank()
-     * @Assert\Choice(choices=App\Entity\Rating\Rating::RATINGS_DISCRIMINATOR_MAP)
+     * @Assert\Choice({"5star":"App\Entity\Rating\FiveStar", "4star":"App\Entity\Rating\FourStar"})
      */
     private ?string $ratingType = null;
    ----------- end diff -----------

```

**Comment by TomasVotruba** [comment]
The demo link should be minimal and contain ONLY the code and sets that break it. Usually 5-10 lines of code is enough. Anything more only distracts and doesn't show the real issue.

Without reproducing the bug, we're not able to fix it

**Comment by SergeC** [comment]
@TomasVotruba finally made it https://getrector.org/demo/9b995adb-edb0-4845-b44b-6a102e783012

**Comment by TomasVotruba** [comment]
I'm looking at it

**Comment by SergeC** [comment]
@TomasVotruba added one more use case. https://getrector.org/demo/aff64619-e52a-40f8-80bf-4637e5fbd32b

For Doctrine it does not inline const while for Assert it does.

**Comment by TomasVotruba** [comment]
I dig deep a bit and it seems like constant reference is parsed to value: https://github.com/doctrine/annotations/blob/904dca4eb10715b92569fbcd79e201d5c349b6bc/lib/Doctrine/Common/Annotations/DocParser.php#L981

Which is bad to preserve format. I have to figure out how to put the constant reference back

**Comment by SergeC** [comment]
I'm not sure if Symfony uses Doctrine's annotation library https://github.com/symfony/validator/blob/master/Constraints/Choice.php
https://github.com/symfony/validator/blob/master/composer.json - dev requirement.

**Comment by TomasVotruba** [comment]
It is, we use it to parse annotations.

https://github.com/rectorphp/rector/blob/11b4dd9c7a86f65696cab742ad19d9c168ad124e/packages/better-php-doc-parser/src/AnnotationReader/NodeAnnotationReader.php#L69-L80

**Comment by SergeC** [comment]
One more example with non-associated array inlined https://getrector.org/demo/7500b21c-fc10-4926-8983-d1abd4627eeb . The way to solve it is to check the output. If `{`,`}` found then restore the original content.

**Comment by TomasVotruba** [comment]
I think that's too late

**Comment by SergeC** [comment]
Ok. Waiting for the new release to try it.

**Comment by TomasVotruba** [comment]
New release of what? `doctrine/annotations`? 

It's been there for years and we have to handle it on Rector's side anyway. Probably some reflection will be needed :/

**Comment by TomasVotruba** [comment]
This finally solves these bugs: https://github.com/rectorphp/rector/pull/5974
