### ISSUE TITLE
PregReplaceEModifierRector should work if $pattern is an array

### ISSUE THREAD

**Issue by derflocki** [rectorphp/rector#3045]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.7              |
| Installed as   | composer dependency                      |

The `PregReplaceEModifierRector` throws Exception if `$pattern` is an array.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/dfc1a6b3-aac1-478f-a8c4-f2d4fb63e98c

## Expected Behaviour

It should work, or at least not throw an Exception but rather indicate, that manual intervention might be necessary.

**Comment by TomasVotruba** [comment]
What's the expected change?

**Comment by derflocki** [comment]
Given, that all items in `$pattern` have the `/e` modifier, the result would be the same as if it was a string:

    preg_replace_callback($pattern, $callback, ...);

But since, only one of them COULD match producing the correct output would be tricky.

I have also encounterd that it also fails if $pattern is not "obviously" a string (is composed of function calls):

https://getrector.org/demo/22f5b2b4-0823-48cc-8ce5-8a6b52fa2487

**Comment by TomasVotruba** [comment]
I've covered the concat case.

If you find a replacement for https://getrector.org/demo/dfc1a6b3-aac1-478f-a8c4-f2d4fb63e98c, send PR with failing fixture. Just copy one of: https://github.com/rectorphp/rector/tree/master/rules/php55/tests/Rector/FuncCall/PregReplaceEModifierRector/Fixture and add 

```bash
before
-----
after
```

 code in them.
