### ISSUE TITLE
PHPUnit 7 level

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#306]
PHPUnit 7 [was released](https://phpunit.de/announcements/phpunit-7.html), and all the `@scenario` annotations should be renamed to `@test`.

@TomasVotruba Is there a Rector for this already, or we should create/modify one?

**Comment by TomasVotruba** [comment]
There is only annotation removal at the moment. The one that takes care of @expectException

The annotation renamer needs to be created yet

**Comment by carusogabriel** [comment]
@TomasVotruba Is it like https://github.com/rectorphp/rector/blob/master/src/Rector/Dynamic/PropertyNameReplacerRector.php, but for annotations?

**Comment by TomasVotruba** [comment]
@carusogabriel Kind off. I could give it like 30 minutes now, to get back into this. Ok?
