### ISSUE TITLE
[DeadCode] Empty array checker before foreach

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3060]
If values is always array, the check before `foreach` is useless

![image](https://user-images.githubusercontent.com/924196/77492342-a39a9280-6e40-11ea-8046-d58b4373e1e5.png)

cc @afilina Just saw it in my code... Is that what you had in mind?
https://twitter.com/afilina/status/1242173453429608448

**Comment by afilina** [comment]
Yes, precisely.

**Comment by alexanderschnitzler** [comment]
Does this rector cover these cases as well or should I open issues for it?

```php
if (!empty($array)) {
    foreach($array as $value){}
}
```

and


```php
if (count($array) > 0) {
    foreach($array as $value){}
}
```

**Comment by TomasVotruba** [comment]
Send PR with text fixture. Also beware of null iteration
