### ISSUE TITLE
 Permission denied ... Kernel.php on line 486

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#3067]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.7              |
| Installed as   | both                   |

When running rector I started getting the following errors:

When run regular (rector/rector)
```
vendor\bin\rector process src --set=php74 --dry-run
PHP Notice:  include(): read of 4096 bytes failed with errno=13 Permission denied in \rector-test-2\vendor\symfony\http-kernel\Kernel.php on line 486
Notice: include(): read of 4096 bytes failed with errno=13 Permission denied in \rector-test-2\vendor\symfony\http-kernel\Kernel.php on line 486
```

When run prefixed:

```
vendor\bin\rector process src --set=php74 --dry-run
PHP Notice:  include(): read of 4096 bytes failed with errno=13 Permission denied in phar://.../rector-test/vendor/rector/rector-prefixed/rector/vendor/symfony/http-kernel/Kernel.php on line 487
Notice: include(): read of 4096 bytes failed with errno=13 Permission denied in phar://.../rector-test/vendor/rector/rector-prefixed/rector/vendor/symfony/http-kernel/Kernel.php on line 487
```

I made a new folder and then included rector via composer and nothing else:
composer require rector/rector-prefixed OR composer require rector/rector

Then I made a super simple PHP file in src called HelloWorld.php that's blank.

We started getting this error in our real setup when upgrading rector, but I hope the above is a simple enough way to replicate it.

So right now it's happening in our real, more complex project, and in these two super simple test cases. It's happening on multiple computers.

I've tried setting windows permissions to give full control of the files to everyone, but it hasn't helped.

These are all Windows computers. I do not get the error when doing same thing from Ubuntu.

If there are changes to be made, Rector will still make them. But it always put those two lines of error at the top, which breaks JSON parsing of the output.

**Comment by TomasVotruba** [comment]
What happens with `--debug` option?

How did you debug `Kernel.php on line 486`?

**Comment by UFTimmy** [comment]
Here's the debug output

```
C:\...\rector-test-2>vendor\bin\rector process src --set=php74 --dry-run --debug
File "C:\...\rector-test-2/vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 63"
File "C:\...\rector-test-2\vendor\rector\rector/../../autoload.php" is about to be loaded in "AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 95"
PHP Notice:  include(): read of 4096 bytes failed with errno=13 Permission denied in C:\...\rector-test-2\vendor\symfony\http-kernel\Kernel.php on line 486
Notice: include(): read of 4096 bytes failed with errno=13 Permission denied in C:\...\rector-test-2\vendor\symfony\http-kernel\Kernel.php on line 486
Rector v0.7.7



 [OK] Rector is done!
```

Sorry, I don't understand your question about me debugging that line. I did not. But that's the full error that it gives, it says Permission denied on that line.

**Comment by TomasVotruba** [comment]
In the report I see `Kernel.php on line 486`

You can open that file on that line and debug it. I think there will be more intell on your problem.

**Comment by UFTimmy** [comment]
I'm sorry, can you tell me what you mean by debug it? Do you mean step through with Xdebug?

**Comment by UFTimmy** [comment]
Ok, I think I see what you mean. I assumed it was erroring trying to load the Kernel.php file, but it looks like that line is responsible for loading the Symfony cache. It looks like it's trying to load cache from this path:

C:\Users\Tim\AppData\Local\Temp/_rector/Rector_Core_HttpKernel_RectorKernelProd169155Container.php

How do I fix permissions there? I've tried running the cmd prompt as an admin, but that has no effect.

**Comment by TomasVotruba** [comment]
I don't work with Windows for ~8 years, so I have no idea.

**Comment by UFTimmy** [comment]
So I don't have a solution for this, but I'm going to close it anyway. 

The RectorKernel is telling Symfony to create the cache in `sys_get_temp_dir() . '/_rector';`

That should be fine, I should have permission to that folder, since I can create files there. But I don't. I've tried changing the path to other places, and I've tried giving full control to every user, but nothing works.

**Comment by TomasVotruba** [comment]
It's only that comes to my mind:

```diff
-sys_get_temp_dir() . '/_rector';
+sys_get_temp_dir() . DIRECTORY_SEPARATOR . '_rector';
```

**Comment by UFTimmy** [comment]
Good suggestion, but it didn't seem to help.

**Comment by TomasVotruba** [comment]
Then you can add option to change this path via parameter.

**Comment by UFTimmy** [comment]
So I did some more sleuthing into that code in the Symfony Kernel, and I realized it's trying to read from a file that it has locked. And then I was able to find a GitHub issue from Symfony that references it. It is indeed a Symfony/PHP7.4 bug in Windows.

Here's the GitHub issue:
https://github.com/symfony/symfony/issues/36132

And here's the Symfony fix:
https://github.com/symfony/symfony/pull/36169

I think if you upgrade Rector's Symfony version to 4.4.6 then it will be fixed.

I appreciate your help in looking into it.

**Comment by TomasVotruba** [comment]
> I think if you upgrade Rector's Symfony version to 4.4.6 then it will be fixed.

Could you try that locally?

If it works, send PR here to `composer.json`

Awesome work :clap: :+1:

**Comment by UFTimmy** [comment]
So I did a composer update `rector/rector --with-dependencies` locally, and it updated all of the Symfony packages from 5.0.5 to 5.0.6 (including symfony/http-kernel where the fix is).

That fixed the error for me. Since rector's composer.json files allow you to get the fix, I'm not sure there's merit in restricting it to 4.4.6 or 5.0.6, but if you'd like me I will make the PR.

**Comment by TomasVotruba** [comment]
> ...but if you'd like me I will make the PR.

Yes, go for it!
