### ISSUE TITLE
Rector makes Regexs in Controller Route Annotation to be invalid

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#3075]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector v0.7.6             |
| Installed as   | composer dependency                     |

Rector is converting regexes that make sure a route parameter match into an invalid format.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/542a1bea-7013-47fb-9581-b944e29640fe

It's converting `[a-z]` to `{a-z}`.

It doesn't seem to matter what sets you use. On my box I was using php74 and I did a dry run. It reported the following rectors made changes:

```
 * Rector\Core\Rector\Argument\ArgumentAdderRector
 * Rector\Core\Rector\ClassMethod\WrapReturnRector
 * Rector\Core\Rector\Argument\ArgumentDefaultValueReplacerRector
 * Rector\Core\Rector\Argument\ArgumentRemoverRector
```

So I added all of those to the skipped rectors, and it still made the change.

Also, it's converting the `letter=` to `letter:`. That doesn't seem to break anything, but why is it making that change?

## Expected Behaviour

Do nothing.

**Comment by TomasVotruba** [comment]
> Also, it's converting the letter= to letter:. That doesn't seem to break anything, but why is it making that change?

It's because the input is based on doctrine/annotatoins, that only parse content to values. They don't care about the format. Rector is different, because it **prints the code back**. In most cases, we have it covered. This one is missing.

I'll look on it.

**Comment by TomasVotruba** [comment]
Thank you for great report! It have me lot of intell on the issue to solve it
