### ISSUE TITLE
PHP 7.4 set messes with routes

### ISSUE THREAD

**Issue by COil** [rectorphp/rector#3090]
[20:49:51] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ vendor/bin/rector --version

    Rector v0.7.7

# Bug Report

I tried this set :
    
    vendor/bin/rector process src --set php74

Rector refactor or deletes my routes.

## Minimal PHP Code Causing Issue

See command.

## Expected Behaviour

My routes shouldn't be updated.

Old route :

   * @Route({"en": "/en", "fr": "/fr"}, name="homepage"

Modified by rector : 

     * @Route(name="homepage")

It's not only about i18n routes, but also standard ones : 

Old route : 

     * @Route("/index.php/en/snippets/tag/dev",                                                                                  defaults={"redir": "/en/snippets/tag/dev"})
     * @Route("/index.php/en/snippets/the-perfect-makefile-for-symfony/run",                                                     defaults={"redir": "/en/snippets/the-perfect-makefile-for-symfony/run"})

Modified by rector : 

     * @Route("/index.php/en/snippets/tag/dev", defaults={"redir":"/en/snippets/tag/dev"})
     * @Route("/index.php/en/snippets/tag/dev", defaults={"redir":"/en/snippets/tag/dev"})

**Comment by TomasVotruba** [comment]
Could you try `dev-master`? This was fixed already.

If you confirm that it work, I'll release new tag to prevent these bugs

**Comment by COil** [comment]
[23:02:40] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ vendor/bin/rector --version
Rector dev-master@23b08fc

Same result. 

```
@@ -23,9 +23,8 @@ final class AppController extends AbstractController
     }

-
     /**
-     * @Route({"en": "/en", "fr": "/fr"}, name="homepage")
+     * @Route(name="homepage")
      */
     public function homepage(string $_locale, ArticleRepository $articleRepository, array $goals): Response
     {
```

**Comment by TomasVotruba** [comment]
Could add demo? https://getrector.org/demo

**Comment by COil** [comment]
Hum, it involves several classes (controller), I'am not sur if a "demo" is doable. Does it work if a fresh project?

**Comment by TomasVotruba** [comment]
It is. Just minimal scope that shows the error, is needed. Usually 5-10 lines of code.

See similar issue with route demo: https://getrector.org/demo/60f9e0f7-ef77-485f-b1fb-fd2903c2b13e

**Comment by COil** [comment]
I have 

    Class "App\Controller\AbstractController" is missing. Complete it to code input, e.g. "class App\Controller\AbstractController {}"

**Comment by TomasVotruba** [comment]
How do you understand the message? It's same as in php

**Comment by COil** [comment]
I don't understand sorry.

**Comment by TomasVotruba** [comment]
If class is missing in PHP, either you can add it to the code, or remove it.
I don't think it's needed at all, for the snippet. Just the `@Route`, so I'd remove it from the code.

**Comment by TomasVotruba** [comment]
For example: https://getrector.org/demo/f92af8a5-43f0-4ad1-95c6-3078e7563e2e#result

**Comment by COil** [comment]
yes it's Ok:

https://getrector.org/demo/b72a759d-0fba-49b1-aba0-cdfe6d1e87b1#result

**Comment by TomasVotruba** [comment]
Thanks :+1: 

I've narrowed it down a bit:
https://getrector.org/demo/97b1ee5f-e260-4327-93a0-8bd98138e98e#result

It seems the array is an issue. I'll investigate, thank you for snippet
