### ISSUE TITLE
[PHPUnit 9.1] Migrate PHPUnit test class from built-in Prophecy integration to trait

### ISSUE THREAD

**Issue by sebastianbergmann** [rectorphp/rector#3099]
[The tight integration of Prophecy into PHPUnit is deprecated in PHPUnit 9.1](https://github.com/sebastianbergmann/phpunit/issues/4141) and will be [removed in PHPUnit 10](https://github.com/sebastianbergmann/phpunit/issues/4142).

A rector would be nice that looks for classes that extend `PHPUnit\Framework\TestCase` and call `$this->prophesize()`. The class needs to be changed to use the `Prophecy\PhpUnit\ProphecyTrait` trait:

```diff
 use PHPUnit\Framework\TestCase;
+use Prophecy\PhpUnit\ProphecyTrait;
 
final class ExampleTest extends TestCase
 {
+    use ProphecyTrait;
+
     public function testOne(): void
     {
         $prophecy = $this->prophesize(\AnInterface::class);
```

**Comment by TomasVotruba** [comment]
I'll look on it this week. Thanks for clear diff!

**Comment by TomasVotruba** [comment]
Done: https://github.com/rectorphp/rector/pull/3117
