### ISSUE TITLE
level symfony30

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#310]
I suggest improving config [here](https://github.com/rectorphp/rector/blob/master/src/config/level/symfony/symfony30.yml#L35) as it replaces any method with name getName() in form and breaks my code.

Example

```php
'choice_label' => function ($allChoices) {
// before
   return $allChoices->getDescr()[0]->getName();
// after
   return $allChoices->getDescr()[0]->getBlockPrefix();
}
```

**Comment by TomasVotruba** [comment]
Would you send PR if you knew how to fix that?

**Comment by mssimi** [comment]
I think I will manage.

**Comment by TomasVotruba** [comment]
Let me know if you need any help

**Comment by mssimi** [comment]
Actually I do need help with another idea, I tried to contact you on google hangouts:)

**Comment by TomasVotruba** [comment]
What needs to be done here to original issue?

**Comment by mssimi** [comment]
I am busy now, I may look at that next week. My plan is rector that renames only methods of class itself.
