### ISSUE TITLE
[Legacy] function + function calls to static methods and static calls

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3101]
## Before

```php
# some_utils_class.php

function some_function()
{
}

some_function('lol');
```

## After

```php
# some_utils_class.php

class SomeUtilsClass
{
    public static function some_function()
    {
    }
}

SomeUtilsClass::some_function('lol');
```

**Comment by staabm** [comment]
I like the idea of getting rid of funtions, because we have a log of them in our legacy apps and have problems with them because they are not autoloadable.

How would a application be upgraded after the framework it uses refactored its functions to classes?

**Comment by TomasVotruba** [comment]
Exactly the autoload issue.

> How would a application be upgraded after the framework it uses refactored its functions to classes?

What do you mean?
