### ISSUE TITLE
NameImporter sometimes fails to add the use Statement

### ISSUE THREAD

**Issue by hco** [rectorphp/rector#3104]
First, thank you for creating rector!
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.7              |
| Installed as   | composer dependency (not-prefixed)                      |

I created a custom rector that uses the [NameImporter](rules/coding-style/src/Node/NameImporter.php) to import a new parent class.
It works if I call rector for the directory the file is in, but not if I run rector for a parent directory.
When I run it for a parent directory, the `use` Statement is missing, but still the shorthand version is being used in the `extends` clause.

## Minimal PHP Code Causing Issue
I did not see an option to use a custom rector in https://getrector.org/demo/, so I created a [demo repository](https://github.com/hco/rector-nameimporter-issue).

You can see the output in Github Actions. There are two runs of rector, look at the missing use statement in the second run: https://github.com/hco/rector-nameimporter-issue/runs/543850934?check_suite_focus=true

I noticed there were changes to NameImporter in master and created a [branch](https://github.com/hco/rector-nameimporter-issue/tree/rector-master) using the master version of rector. In that case it does not work in either rector runs, but I get an exception in the second one. You can also see the results in [Github Actions](https://github.com/hco/rector-nameimporter-issue/runs/543875686?check_suite_focus=true)

Please let me know if you need more help from my side. I can also look at fixing this, but I might need some pointers where to look at :-)

**Comment by TomasVotruba** [comment]
Hi, what is the motivation to implement this?

Rector already handles it

**Comment by TomasVotruba** [comment]
Looking at the code, you can achieve the same goal by using this option in config:
https://github.com/rectorphp/rector#import-use-statements
