### ISSUE TITLE
[DeadCode] Remove unused public method

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3107]

**Comment by samsonasik** [comment]
Public method is accessible by outside, so removing public method may require check area that may possibly using it, which the class that has it can be consumed as vendor.

There is already remove empty method which already in master https://getrector.org/demo/4c9da70c-91ff-4213-8f53-283fac03f614#result

**Comment by TomasVotruba** [comment]
That is true only for open source and frameworks (we have a parameter for that).

Private projects don't use public methods outside, so if public methods is unused, it can be removed

**Comment by samsonasik** [comment]
I guess it is related with usage with `! $this->isOpenSourceProjectType()` ? What unused usage check required, in only existing file?, eg:

```php
// DemoFile.php
class DemoFile
{
    public function unusedpublicMethod()
    {
        
    }
}
```

Above, the `unusedpublicMethod()` method is on file `DemoFile.php`, do we check only in the `DemoFile.php` or check in other area, eg: in some directory ?

**Comment by TomasVotruba** [comment]
Other files (or classes) should be checked too.

There is no need to load multiple files. One with multiple classes is good enough.

There might be some inspiration in similar class constat removing rule:
https://github.com/rectorphp/rector/blob/2030badc199c918a6baefd7f491585bc71975a57/rules/dead-code/tests/Rector/ClassConst/RemoveUnusedClassConstantRector/RemoveUnusedClassConstantRectorTest.php

**Comment by lulco** [comment]
Some public methods could be called in non-php files like neons or yamls. For example setup of service in Nette

**Comment by TomasVotruba** [comment]
How could we cover it?

**Comment by lulco** [comment]
I didn’t even know that class rename is covered. Where / how it is implemented? Is it also method rename covered?

**Comment by TomasVotruba** [comment]
> I didn’t even know that class rename is covered

That's good. If it works, you should not notice any bugs :+1: 

> Where / how it is implemented? 

The implementaiton is using regex. Here: https://github.com/rectorphp/rector/blob/250e8511233ed4143f5fc910828b1aa18216fb85/src/NonPhpFile/NonPhpFileClassRenamer.php

> Is it also method rename covered?

Only class rename.
