### ISSUE TITLE
Migrating to new dispatch signature does not work for the EventDispatcher interface

### ISSUE THREAD

**Issue by stof** [rectorphp/rector#3109]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.7              |
| Installed as   | composer dependency                     |

I also tried it with the prefixed phar, and it is also impacted.

The MakeDispatchFirstArgumentEventRector migrating `dispatch` calls to the new Symfony signature does not properly migrate code using the `Symfony\Component\EventDispatcher\EventDispatcherInterface` interface as typehint (i.e. all old code as the new `Symfony\Contracts\EventDispatcher\EventDispatcherInterface` does not exist in older versions).

## Minimal PHP Code Causing Issue

```php
<?php

use Symfony\Component\EventDispatcher\Event;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

class Test
{
    private $eventDispatcher;

    public function __construct(EventDispatcherInterface $eventDispatcher)
    {
        $this->eventDispatcher = $eventDispatcher;
    }

    public function test()
    {
        $this->eventDispatcher->dispatch('test', new Event());
    }
}

## Expected Behaviour

The `dispatch` call should be updated to put the event as first argument.

**Comment by TomasVotruba** [comment]
Demo link is needed

https://getrector.org/demo

**Comment by stof** [comment]
I tried this in the demo at https://getrector.org/demo/a041fb03-0a2c-4fb1-84c0-79b7a7d3dce6#result, but it seems my minimal code removed too many things compared to my project, as it is working there (that, or the demo uses a different version, but I cannot know it as it does not tell which version is used).

**Comment by TomasVotruba** [comment]
Could you try `dev-master`? I think the demo uses lastest Rector version. Is that right @JanMikes ?

**Comment by TomasVotruba** [comment]
Closing as demo link is correct.
