### ISSUE TITLE
Rector replaces ::class constant with FQCN in annotations

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#3119]
# Bug Report

Thanks for all your help and speedy fixing of issues.!

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector dev-master@2fb3149              |
| Installed as   | composer dependency                       |

Rector replaces ::class constant with FQCN in annotations

Note, it doesn't seem to matter what sets or Rectors I use, and Rector doesn't report what Rectors are actually making the change.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/ff7b303a-d4cb-4a87-a315-35ab4a7a5d92#result

## Expected Behaviour

Leave the ::class constant alone.

**Comment by TomasVotruba** [comment]
Same issue as here: https://github.com/rectorphp/rector/pull/3050#discussion_r397415911
