### ISSUE TITLE
Rector mangles @Route annotations from Symfony

### ISSUE THREAD

**Issue by Seldaek** [rectorphp/rector#3121]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.7  |
| Installed as   | composer dependency |

The `@Route` annotations get damaged, regardless of which rector set is used. This means you always need to go through and undo changes in controllers, which wastes a ton of time.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/5d9604c7-cef9-4b39-94bd-43347e6839db
https://getrector.org/demo/f93e65ae-4469-498c-96d6-fc80983483a4 (tried even without `%param%` to check if this was the root cause)

## Expected Behaviour

The `@Route` annotations, even with host, should be left intact

**Comment by TomasVotruba** [comment]
Thanks for great report :+1:

**Comment by Seldaek** [comment]
Thanks for the quick fix
