### ISSUE TITLE
[Symfony 5] Best directory rector.yaml - prepared sets

### ISSUE THREAD

**Issue by seb-jean** [rectorphp/rector#3123]
# Question

Hi,

I wanted to know which the best directory or I could put the rector.yaml file in a Symfony 5 project.

Then, what are the prepared sets to use for a symfony 5 project?

Thank you :)

**Comment by TomasVotruba** [comment]
Hi, the best location is `rector.yaml` in the root directory.

All the symfony sets can be found in `/config/set/` directory: https://github.com/rectorphp/rector/tree/master/config/set/symfony
