### ISSUE TITLE
[PHP 8.0] [Meta] 

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3127]
# New Accepted Features 

### `get_resource_id()`

- PR: https://github.com/php/php-src/pull/5427

### `mixed` type

- RFC: https://wiki.php.net/rfc/mixed_type_v2

### constructor promotion

- RFC: https://wiki.php.net/rfc/constructor_promotion

<br>

## Generic sources

- https://www.reddit.com/r/PHP/comments/g5w52s/php_8_will_add_union_types_the_jit/
- https://wiki.php.net/rfc/deprecations_php_8_0

<br>

### 1. `str_starts_with()` / `str_ends_with()`  :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/add_str_starts_with_and_ends_with_functions
- Issue: https://github.com/rectorphp/rector/issues/3221

### 2. `str_contains()`  :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/str_contains
- Issue: https://github.com/rectorphp/rector/issues/3025

### 3. `Stringable` interface for classes with `__toString()`  :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/stringable

### 4. Attributes v2 :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/attributes_v2

### 5. `static` type  :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/static_return_type
- in e.g. Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector

### 6. `::class` on objects  :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/class_name_literal_on_object

### 7. `get_debug_type` :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/get_debug_type

### 8. `token_get_all` to `PhpToken`  :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/token_as_object

### 9. `catches` without $variable   :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/non-capturing_catches

### 10. `match` :heavy_check_mark: 

- RFC: https://wiki.php.net/rfc/match_expression_v2
- Rector PR: https://github.com/rectorphp/rector/pull/3569

<br>

### New features, without no path to upgrade

- https://wiki.php.net/rfc/throw_expression

**Comment by staabm** [comment]
get_debug_type() see https://wiki.php.net/rfc/get_debug_type

Object-based token_get_all() https://wiki.php.net/rfc/token_as_object

**Comment by TomasVotruba** [comment]
@staabm Could you provide diffs for both of them? So we can make rules of it

**Comment by staabm** [comment]
another merged PR: https://github.com/php/php-src/pull/5427

before php8
```
$resource = fopen(...); // example way to get a resource 
echo (int) $resource;
```

with php8
```
$resource = fopen(...); // example way to get a resource 
echo get_resource_id($resource);
```

**Comment by staabm** [comment]
> Could you provide before/after diff snippet for both of them? So we can make rules of it and focus on that part only

regarding: Object-based token_get_all() wiki.php.net/rfc/token_as_object

before
```
$tokens = token_get_all($code);
foreach ($tokens as $token) {
    if (is_array($token)) {
       $name = token_name($token[0]);
       $text = $token[1];
    } else {
       $name = null;
       $text = $token;
    }
}
```

after  (php8+)
```
$tokens = PhpToken::getAll($code);
foreach($tokens as $phpToken) {
   // it is not necessary to continuously check whether an array or string token is being used.

   $name = $phpToken->getTokenName();
   $text = $phpToken->text;
}
```

**Comment by TomasVotruba** [comment]
AFAIK all cases are resolved now :+1:
