### ISSUE TITLE
PHP Fatal Error: Cannot redeclare Functional\*

### ISSUE THREAD

**Issue by rodnaph** [rectorphp/rector#3145]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  dev-master@d5329e5              |
| Installed as   | composer global                      |

## Minimal PHP Code Causing Issue

Running on a project using [lstrojny/functional-php](https://github.com/lstrojny/functional-php):

```
PHP Fatal error:  Cannot redeclare Functional\filter() (previously declared in /Users/me/example-project/vendor/lstrojny/functional-php/src/Functional/Filter.php:23) in /Users/me/example-project/vendor/lstrojny/functional-php/src/Functional/filter.php on line 23
```

This is the case for all functions exported by this library that I've tried (eg. map, select, etc...)

## Expected Behaviour

No errors should be thrown.

**Comment by TomasVotruba** [comment]
We need minimal failing code or failing CI link

**Comment by rodnaph** [comment]
Unfortunately I haven't been able to reproduce this on a minimal repo, only in a larger project (and don't have the knowledge of Rector to debug it atm). I was hoping this was an error pattern you were [familiar with](https://github.com/rectorphp/rector/issues/3112)...

I'll let you know if I do come up with a reproduction then 👍 Thanks

**Comment by TomasVotruba** [comment]
We'd need `composer.json`, app code, `rector.yaml`, your environment etc.

**Comment by TomasVotruba** [comment]
Closing as stale
