### ISSUE TITLE
Default null in nullable

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#3147]
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.8 |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/8a6573f7-2f5a-4c98-9cbf-1c4b4c9da267

## Expected Behaviour

No error because is `null` value guarantee by constructor

**Comment by TomasVotruba** [comment]
This might introduce bugs like these:

```diff
 public function __construct($defaultArray = [])
 {
-    $this->defaultArray = [];
     foreach ($this->defaultArray as $item) {
     }

     // ...
 }
```

Also it would require lot of developers attention to handle those cases.

**Comment by TomasVotruba** [comment]
Feel free to send PR with optional confugration (off by default), if you need this feature.
