### ISSUE TITLE
createMockToCreateStub rector fixes too many methods

### ISSUE THREAD

**Issue by greg0ire** [rectorphp/rector#3157]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.11             |
| Installed as   | rector/rector-prefixed                      |

I tried using the rector on https://github.com/sonata-project/SonataAdminBundle, and here is the result: https://github.com/sonata-project/SonataAdminBundle/pull/6043#discussion_r407072534

## Minimal PHP Code Causing Issue
Could not reproduce it on the demo, because it would imply defining several interfaces
```php
<?php

declare(strict_types=1);

namespace Sonata\AdminBundle\Tests\Admin;

use PHPUnit\Framework\TestCase;
use Sonata\AdminBundle\Model\ModelManagerInterface;
use Sonata\DatagridBundle\Datagrid\DatagridInterface;

class AdminTest extends TestCase
{
    public function testGetFilterFieldDescription(): void
    {
        $modelManager = $this->createStub(ModelManagerInterface::class);
        $modelManager
            ->method('getNewFieldDescriptionInstance')
            ->willReturnCallback(static function () {
            });

        $datagrid = $this->createMock(DatagridInterface::class);
        $datagrid->expects($this->once())
            ->method('getPager');
    }
}

```
## Expected Behaviour

The change to `createStub` should not be done

**Comment by TomasVotruba** [comment]
I had similar issue with another PHPUnit rule, that also worked in demo but not in prefixed.

The rule detects `PHPUnit\Framework\TestCase` that is actually prefixed in `rector-prefixed`.

```diff
-use PHPUnit\Framework\TestCase;
+use SomePrefix\PHPUnit\Framework\TestCase;
```


This should fix it: https://github.com/rectorphp/rector/commit/dd3db1d28b503e49c4cafb7abddecfbd377d5f09

**Comment by greg0ire** [comment]
I'm not sure: there does not seem to be a check against `TestCase` in https://github.com/rectorphp/rector/pull/3047

**Comment by TomasVotruba** [comment]
Aha, that might be a problem :)
