### ISSUE TITLE
False positive on annotations

### ISSUE THREAD

**Issue by 50bhan** [rectorphp/rector#3158]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.11              |
| Installed as   | composer dependency                      |

Hey @TomasVotruba 

I get false positive from Rector when using different annotations in the code. The source of problem is from PhpStan required annotations for ignoring some stuff.

## Minimal PHP Code Causing Issue
https://getrector.org/demo/453703d2-496e-423d-a9a4-b4ae06699f7e

At first glance it might be OK! But look and the last line. It will be more clear in a diff from Rector itself:

```
    ---------- begin diff ----------
--- Original
+++ New
@@ -25,7 +25,7 @@
     {
         $this->output = $output;
         //@anything
-    }
+}
    ----------- end diff -----------

```

## Expected Behaviour
Rector should not change anything here! Because this change is incorrect and against styling rules.

**Comment by TomasVotruba** [comment]
Thanks for repoting. I cannot see in the demo link though. Could you update it to show the error?

**Comment by 50bhan** [comment]
@TomasVotruba No problem. Here is: https://getrector.org/demo/7d36a3bc-a02b-4dd4-8bec-d813f9c9c97b

**Comment by TomasVotruba** [comment]
![image](https://user-images.githubusercontent.com/924196/79454869-3ff12880-7fec-11ea-9a03-18979d93753e.png)

I still can't see it there.

**Comment by 50bhan** [comment]
@TomasVotruba You mean you can't see annotation?

**Comment by 50bhan** [comment]
Let me put it this way: when using annotations like `@anything`, Rector will fail because it says the closing bracket is wrong and you should change identation of it. And it cause CI failure.

```
    ---------- begin diff ----------
--- Original
+++ New
@@ -25,7 +25,7 @@
     {
         $this->output = $output;
         //@anything
-    }
+}
    ----------- end diff -----------
```

Compare this two:
With annotation: https://getrector.org/demo/7d36a3bc-a02b-4dd4-8bec-d813f9c9c97b
Without annotation: https://getrector.org/demo/dbc8776b-460e-4767-a6f6-481bff3ba7b0

**Comment by TomasVotruba** [comment]
So the demo isn't showing the bug?

**Comment by 50bhan** [comment]
No, demo will remove the last two closing brackets.

**Comment by TomasVotruba** [comment]
It's not removing it. It just show parts of the code.

Look at this example: https://getrector.org/demo/65bb3e16-0968-459b-8bb7-fd2eea1b3f59#result

It doesn't remove first 2 lines with `use` there. It just doesn't show them, because nothing changed those lines.

**Comment by 50bhan** [comment]
Ah ok. So you should check the diff I posted. Apparently it can't be reproduced via demo and I reported it because it was the reason of CI failure couple of times. So I leave it to you to confirm or close this issue.

BTW, I know you just rely on demo because it is the right and safe way to save time and figure out situation, but you can see our CI log to understand the problem we had:
https://travis-ci.org/github/nunomaduro/phpinsights/jobs/673751065

**Comment by TomasVotruba** [comment]
Failing CI is perfect. I see there more issues with Rector. 

Thanks, I'm looking at it

**Comment by TomasVotruba** [comment]
I cannot find the `rector.yaml` there. Could you link me to the PR so I can replicate Rector run locally?

**Comment by TomasVotruba** [comment]
[This commit](https://github.com/rectorphp/rector/commit/7b8b482a96e9a72aac4e79f4dd17479d214c30cb) fixes

![image](https://user-images.githubusercontent.com/924196/79462349-a596e200-7ff7-11ea-9858-923a8cb71f79.png)

**Comment by 50bhan** [comment]
Awesome, this is the PR: https://github.com/nunomaduro/phpinsights/pull/393

**Comment by TomasVotruba** [comment]
I got there, but didn't find added `rector.yaml`.
I'm using this version https://github.com/nunomaduro/phpinsights/blob/master/rector.yaml - is that correct?

If so, the annotaion is kept. 

![fixes](https://user-images.githubusercontent.com/924196/79462834-556c4f80-7ff8-11ea-9bf6-b21f34d624fe.gif)

**Comment by TomasVotruba** [comment]
Try the PR again with current `dev-master` Rector on that repository. It seems fixed.

**Comment by 50bhan** [comment]
Thanks!

**Comment by TomasVotruba** [comment]
:+1: 

Here is test case that check that: https://github.com/rectorphp/rector/pull/3177/files#diff-b418338cd7c1457fe9847e71e42ed7a4

Also be sure your code has consistent line endings and consistent spaces or tabs. That might be causing troubles (also in all coding standard tools).
