### ISSUE TITLE
Could not process

### ISSUE THREAD

**Issue by HDVinnie** [rectorphp/rector#3160]
# Question

Not sure this is a bug because I cannot replicate it on the DEMO site. However I am using latest rector installed today and get the following error when trying to run any of the set on any files.

```
"Call to undefined method PhpParser\Comment\Doc::getStartTokenPos()".  
```

**Comment by TomasVotruba** [comment]
It's a conflict of PHPStan and php-parser 4.4, see: https://github.com/rectorphp/rector/pull/3156#issue-402038893

There should be limit in `composer.json` to allow only `php-parser` 4.3

**Comment by holtkamp** [comment]
To clarify https://github.com/rectorphp/rector/issues/3160#issuecomment-612787069 for others: add this to `composer.json`:

```
"nikic/php-parser": "4.3.*",
```
