### ISSUE TITLE
Annotation processing is handling quotes incorrectly

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#3163]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@a25adb1              |
| Installed as   | getRector demo                      |

String quoting on Annotations isn't quite right. For constants in the form of ClassName::CONSTANT it's putting them in quotes. For other things which need the quotes it's removing them.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/65bb3e16-0968-459b-8bb7-fd2eea1b3f59#result

## Expected Behaviour

Do nothing.

**Comment by TomasVotruba** [comment]
Thanks for reporting!
