### ISSUE TITLE
Changelog is not up to date

### ISSUE THREAD

**Issue by prisis** [rectorphp/rector#3165]
# Feature Request

Create a process to have a up to date chagelog file, maybe 
- https://packagist.org/packages/jwage/changelog-generator
- https://packagist.org/packages/symplify/changelog-linker
- https://packagist.org/packages/phly/keep-a-changelog

**Comment by TomasVotruba** [comment]
We use symplify/changelog-linker already.
How would you automate it?

**Comment by prisis** [comment]
A github action that only runs on master?

Maybe you can use the dry run mode of the symplify/changelog-linker?

**Comment by TomasVotruba** [comment]
Technically sounds good. How would you deal with failing CI on every new PR? I imagine it might be annoying for all the contributors.

Should be fully automated IMO.

**Comment by prisis** [comment]
If you use github actions, this should work https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration

**Comment by TomasVotruba** [comment]
That's the same issue. `master` would be failing after every merge

**Comment by prisis** [comment]
But is it a problem if on job fails?

**Comment by TomasVotruba** [comment]
> But is it a problem if on job fails?

Yes. The CI must pass. If it's failing, something is wrong :)

**Comment by TomasVotruba** [comment]
Closing then. Feel free to re-open with some automated solution, I'm :100:  for it!
