### ISSUE TITLE
Refactoring Symfony2.8 project

### ISSUE THREAD

**Issue by christianlupus** [rectorphp/rector#3166]
# Current setting and problem
The [PartKeepr projekct](https://github.com/partkeepr/PartKeepr) was abandoned for some time by the main developer and now the dependencies are heavily outdated. Some guys (including me) try to get the ship back on track. Therefore, we need to migrate to a recent symfony version in a first step to get things going.
Our idea was to use rector to aid us with the migration process.

# Steps tried so far
I tried to use rector now on the code base but did not succeed.
## Part 1 using docker
The first idea was to use the docker image in order to allow rector to update the code. I got a whole bunch of errors stating that most of our files were not found by the autoloader. 
Some back-and-forth later, it ran somehow but changed all of the files causing a huge diff but all of the changes I checked manually were syntactic sugar: Newlines, indentation and the like.

## Part 2 using rector-prefixed
I wrote an email to Tomas requesting for help. He directed me to the Github issues and [this article](https://getrector.org/blog/2020/01/20/how-to-install-rector-despite-composer-conflicts). There I found that the docker approach is mainly there for php version updates but might not help due to class name clashes.
The suggested approach on the page is to use the `rector/rector-prefixed` package. Here I get another error, I am not able to make much sense of:
```
$ COMPOSER_MEMORY_LIMIT=-1 composer require rector/rector-prefixed --dev
Using version ^0.7.14 for rector/rector-prefixed
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rector/rector-prefixed v0.7.14 conflicts with nikic/php-parser[v0.9.4].
    - rector/rector-prefixed v0.7.14 conflicts with nikic/php-parser[v0.9.4].
    - rector/rector-prefixed v0.7.14 conflicts with nikic/php-parser[v0.9.4].
    - Installation request for rector/rector-prefixed ^0.7.14 -> satisfiable by rector/rector-prefixed[v0.7.14].
    - Installation request for nikic/php-parser (locked at v0.9.4) -> satisfiable by nikic/php-parser[v0.9.4].


Installation failed, reverting ./composer.json to its original content.
```
I assume this is due to the fact that `nikic/php-parser` is used both by the rector package as well as by out project and there is a version mismatch. However I thought, the `-prefixed` version was there to solve these types of issues.

Can you give us a hint, how we might approach this further?

**Comment by TomasVotruba** [comment]
That's the only package that cannot be prefixed :sweat_smile: 

I recommend removing local php-parser

**Comment by christianlupus** [comment]
The thing is, it is a dependency chain:

- partkeepr
- dunglas/api-bundle
- phpdocumentor/reflection
- nikic/php-parser

Are you suggesting to break this chain (I did not even know if this is possible with composer)? If I remove the api-bundle it will break some of the dependencies in the main app. Is Rector even able to run if the dependencies are not satisfiable?

**Comment by TomasVotruba** [comment]
Without `php-parser` of correct version there is no way to run Rector.

**Comment by christianlupus** [comment]
OK, I will try if that brings me to a working point. 

If that is not working, I had another idea: Is there an old rector release (here on git you can travel to the past without much hassle) that might be better suited to migrate to symfony 3.x so that a newer rector might take over from there?

You misinterpreted my question. Of course, rector needs a working dependency tree. I meant if it can workign with a brogen dependency tree of the app to be refactored.

**Comment by TomasVotruba** [comment]
> that might be better suited to migrate to symfony 3.x so that a newer rector might take over from there?

That depends on your custom `composer.json` and code base.
Composer would tell you already if there would be such version. 

> I meant if it can workign with a brogen dependency tree of the app to be refactored.

Depends on many factors, like if class needs to be reflected, if PHPStan needs it etc. I'd try it.

---

Another thing I do with huge legacy code bases is to refactor them piece by piece. E.g. I go for framework first - I need only symfony bundles. If it needs more, I focus on less amount of code etc.

**Comment by TomasVotruba** [comment]
Closing as answered
