### ISSUE TITLE
array_push with spread operator incorrectly replaced

### ISSUE THREAD

**Issue by Kanti** [rectorphp/rector#3169]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Used Rector version: 0.8.x-dev@5758d7c                          |
| Installed as   | https://getrector.org/demo                                      |

## Minimal PHP Code Causing Issue
```diff
 class SomeClass
 {
     public function run()
     {
         $items = [1];
         $items2 = [2,3];
-        array_push($items, ...$items2);
+        $items[] = $items2;
     }
 }
```
The change does not give the same result.

https://getrector.org/demo/c5171729-7e17-4a6a-8619-4626d3026165#result
https://3v4l.org/Z0iQH

## Expected Behaviour

Rector skip it

**Comment by TomasVotruba** [comment]
Thank you for reporting. Great job with 3v4l.org link!

I'll look into it today
