### ISSUE TITLE
Rector 0.7.14 shows an error that wasn't shown in 0.6.13

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3170]
# Bug Report
This is part of [Drupal-Rector](https://github.com/palantirnet/drupal-rector) project, so it's hard to produce a minimal PHP code that is causing the issue.

Rector 0.6.13 works well, but there's a new error displayed when we try to work with Rector 0.7.14

When running rector 0.7.x on example files we've created, we are getting the following error:
```
PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException:
Pick more specific node than "PhpParser\Node\Expr\StaticCall" in 
phar:///home/runner/work/drupal-rector/drupal-rector/drupal-rector07/vendor/rector/rector-prefixed/rector/packages/node-name-resolver/src/NodeNameResolver.php:81
```

Here's the test for Rector 0.6.13, that completes with no errors.
https://github.com/palantirnet/drupal-rector/runs/590380767?check_suite_focus=true#step:4:261

And here's the error when running the same file with Rector 0.7.14:
https://github.com/palantirnet/drupal-rector/runs/590380771?check_suite_focus=true#step:4:214

**Comment by TomasVotruba** [comment]
Thanks for reporting and CI links with `--debug`. I cannot be more happier :) (expect PR with fix + test of course :P)

I'll look into it today

**Comment by TomasVotruba** [comment]
Tip: separate `composer install` and Rector run to 2 separated lines. It's easier to look just into Rector output than to scan through composer reports too.

https://github.com/rectorphp/rector/blob/6ea597d650a5672f9d93d9c94760594b922b6e49/.github/workflows/ecs.yaml#L18-L19

**Comment by TomasVotruba** [comment]
Answered here: https://github.com/palantirnet/drupal-rector/pull/16#issuecomment-614602325

**Comment by shaal** [comment]
Thank you @TomasVotruba !

When I try to separate the different commands into multiple `run:`, I am getting an error:
https://github.com/palantirnet/drupal-rector/runs/594206621?check_suite_focus=true#step:6:5

**Comment by TomasVotruba** [comment]
You need to look at the error. 

```bash
cp: cannot stat 'vendor/palantirnet/drupal-rector/rector.yml': No such file or director
```
