### ISSUE TITLE
Allow relative class names during auto import

### ISSUE THREAD

**Issue by alexanderschnitzler** [rectorphp/rector#3173]
# Feature Request

Hi Tomas,
while running rector on a large code base to apply auto import on all files I came across a possible improvement.

It would be great to be able to configure the import of only those classes that are outside the scope/namespace of the processed class.

 
## Diff 

Given this code block

```php
namespace Foo;

class FooClass
{
    public function __construct(
        Foo\Bar\BazClass $bazClass,
        Vendor\WhateverClass $whateverClass
    ) {}
}
```

the current behaviour is this:

```diff
namespace Foo;

+ use Foo\Bar\BazClass;
+ use Vendor\WhateverClass;

class FooClass
{
    public function __construct(
-        Foo\Bar\BazClass $bazClass,
+        BazClass $bazClass,
-        Vendor\WhateverClass $whateverClass
+        WhateverClass $whateverClass
    ) {}
}
```

but it could also be this:

```diff
namespace Foo;

+ use Vendor\WhateverClass;

class FooClass
{
    public function __construct(
-        Foo\Bar\BazClass $bazClass,
+        Bar\BazClass $bazClass,
-        Vendor\WhateverClass $whateverClass
+        WhateverClass $whateverClass
    ) {}
}
```

In words, this means allowing to not import classes that are relative to the current namespace which results in only external classes being imported. This is an edge case of course and only makes real sense for files in the root namespace of a package.

**Comment by TomasVotruba** [comment]
I'm open to such feature, if you care to implement it.

**Comment by alexanderschnitzler** [comment]
Great. I think I won't have time soon but it's not really urgent as well.

**Comment by TomasVotruba** [comment]
No troubles. Feel free to reopen with PR when you're ready, I'll guide you
