### ISSUE TITLE
Rector returns exit code 0 even when there are errors displayed

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3178]
When running Rector, (this was an earlier version, before we fixed it in https://github.com/palantirnet/drupal-rector/pull/16#issuecomment-614766788)
A few errors are displayed, and yet the exit code is 0, and CI reports it as a success.

https://github.com/palantirnet/drupal-rector/runs/593017901?check_suite_focus=true#step:4:961

**Comment by TomasVotruba** [comment]
That's because its PHP Notice level. This would have to be changed in PHP code itself.
