### ISSUE TITLE
 Simple comment breaks PHPUnit ExceptionAnnotationRector

### ISSUE THREAD

**Issue by DeyV** [rectorphp/rector#3179]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  Rector v0.7.16            |
| Installed as   | composer global       - Windows 10, php 74              |

Simple comment line between two methods, like // test break this rector 

`>  rector process  ./example/`

```

 [ERROR] Could not process "example/ExceptionMessageTest.php" file by "Rector\PHPUnit\Rector\ExceptionAnnotationRector",
         due to:                                                                                                        
         "Call to a member function hasByName() on null".  

```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/5f9a2a8a-34fd-471d-9869-41b52cb1e888#result

and attached as zip. 
[example.zip](https://github.com/rectorphp/rector/files/4491167/example.zip)

**Comment by TomasVotruba** [comment]
Rector cannot be installed as global dependency.

Only local or prefixed Rector should be used: https://getrector.org/blog/2020/01/20/how-to-install-rector-despite-composer-conflicts

**Comment by DeyV** [comment]
please open again

thanks for reminding me about instalation, but problem is not connected. 

```
vendor/bin/rector process ./example/
Rector v0.7.16
Config file: rector.yaml

 3/3 [============================] 100%


 [ERROR] Could not process "example/ExceptionMessageTest.php" file by "Rector\PHPUnit\Rector\ExceptionAnnotationRector",
         due to:
         "Call to a member function hasByName() on null".
```

```
php -v
PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.4, Copyright (c) 2002-2020, by Derick Rethans
```

[example.zip](https://github.com/rectorphp/rector/files/4501514/example.zip)

**Comment by DeyV** [comment]
Problem is active even on master: 

```
 ./vendor/bin/rector process ./example/
Rector dev-master@7e2394e
Config file: rector.yaml


 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [ERROR] Could not process "example/ExceptionMessageTest.php" file by "Rector\PHPUnit\Rector\ExceptionAnnotationRector",
         due to:
         "Call to a member function hasByName() on null".
```


[example-master.zip](https://github.com/rectorphp/rector/files/4501653/example-master.zip)

**Comment by TomasVotruba** [comment]
Failing demo is still needed.
