### ISSUE TITLE
Infer method param phpdocs based on property phpdocs

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#3188]
# Feature Request

before
```
class rex_form_base
{
    /** @var string */
    protected $fieldset;

    public function addFieldset($fieldset)
    {
        $this->fieldset = $fieldset;
    }
}
```

After

```

class rex_form_base
{
    /** @var string */
    protected $fieldset;

    /**
      * @param string $fieldset
      */
    public function addFieldset($fieldset)
    {
        $this->fieldset = $fieldset;
    }
}
```

Same for getter/setter/__construct()

Should also work for return types phpdocs

**Comment by TomasVotruba** [comment]
I don't have time for it, but feel free to implement such feature.

All you need to do is add a new services, that implements: https://github.com/rectorphp/rector/blob/master/rules/type-declaration/src/Contract/TypeInferer/ParamTypeInfererInterface.php
