### ISSUE TITLE
Rector Prefixed composer requirements

### ISSUE THREAD

**Issue by damontgomery** [rectorphp/rector#3189]
# Question

Sorry for potential misunderstandings, etc on how PHAR packages work. :(

We got a support question for `palantirnet/drupal-rector` relating to `phpstan/phpstan`.

I believe the issue they were having is caused by the stated conflict in the `composer.json` for rector/rector-prefixed`.

```
: composer show rector/rector-prefixed
name     : rector/rector-prefixed
descrip. : Prefixed version of Rector compiled in PHAR
keywords :
versions : * v0.7.16
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/rectorphp/rector-prefixed.git 33a6b4d7d046639c04480a09c7f0a34dd0e52f0e
dist     : [zip] https://api.github.com/repos/rectorphp/rector-prefixed/zipball/33a6b4d7d046639c04480a09c7f0a34dd0e52f0e 33a6b4d7d046639c04480a09c7f0a34dd0e52f0e
path     : /Users/dan/Sites/test-install/drupal-rector-sandbox/vendor/rector/rector-prefixed
names    : rector/rector-prefixed, rector/rector

requires
php ^7.2

conflicts
nikic/php-parser <4.3
phpstan/phpstan <0.12

replaces
rector/rector self.version
```

Can you explain if and why those two packages have conflicts?
Is there a limitation with PHAR packages that we can't remove all dependencies?

I recommended the user see if they could update `phpstan/phpstan` and then try to install `palantirnet/drupal-rector` which includes `0.7.16` of `rector/rector-prefixed`.

Thanks again for all the help. We'll try to explain these dependencies in our readme to help other users who might encounter these issues.

**Comment by TomasVotruba** [comment]
It's just related to the version. Rector uses `phpstan.neon` config, and PHPStan 0.11 has different API than 0.12, thus the conflict.
