### ISSUE TITLE
Rector\Php73\Rector\FuncCall\RegexDashEscapeRector breaking the regexp

### ISSUE THREAD

**Issue by sidux** [rectorphp/rector#3190]
# Bug Report

Rector version | 0.5.23

## Minimal PHP Code Causing Issue
https://getrector.org/demo/6c42cc3b-1c82-40a9-8bb4-94349ba79f64

## Expected Behaviour
it should not escape the backslash

**Comment by staabm** [comment]
Are you sure you are using rector 0.5.23?

You should update this really old release to something more recent..

**Comment by sidux** [comment]
@staabm I guess the website https://getrector.org uses a more recent version ? but the issue is still reproducible there also.

**Comment by staabm** [comment]
Ahh .. makes sense..sorry for the noise

**Comment by TomasVotruba** [comment]
It's in `dev-master` too, I'll look at it :+1: 

@sidux Next time please use the most recent verison, so we're not confused :laughing:

**Comment by TomasVotruba** [comment]
Code sample: https://3v4l.org/HOedn
