### ISSUE TITLE
Annotation processing inlining - Doctrine 

### ISSUE THREAD

**Issue by cmodijk** [rectorphp/rector#3202]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@915faa8              |
| Installed as   | composer dependency   |

Based on the fix on #3180 i updated to the latest `dev-master` but on by locale instance i still get this diff.

```diff
- * @ORM\Entity(repositoryClass=EntityRepository::class)
+ * @ORM\Entity(repositoryClass="EntityRepository::class")
```
```diff
-     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
+     * @ORM\CustomIdGenerator(class="UuidGenerator::class")
```

## Minimal PHP Code Causing Issue

The demo url does not reflect both issues but only one 
https://getrector.org/demo/35dce657-7709-4597-9e4b-82ebe90cfb8c#result

## Expected Behaviour

No change

**Comment by TomasVotruba** [comment]
The #3180 was hot fix for particular annotation and property.

I have to come up with more generic solution coverring all the tag value nodes.

**Comment by cmodijk** [comment]
Cool @TomasVotruba thanks!
