### ISSUE TITLE
Implement "deformatter" - collect rector json results and create ErrorAndDiffCollector

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#3203]
In parallel processing there is Parent and Child process.

Child processes output jsons (via `JsonOutputFormatter` to stdout and parent is collecting them). 

I need to be able to collect these json results, deserialize them and make parent process able to output them in different output formatter (the one user wants).

Code snippet worth 1000 words:
```php
$jsonsFromChildren = []; // array of results created by JsonOututFormatter, can be either merged to single array with all results or collection of results and let the service handle merging together

// I need something like this:
$errorAndDiffCollector = $this->createErrorAndDiffCollectorFromJsonArrays($jsonFromChildren);

// So i can output here again but in different format
$outputFormat = (string) $input->getOption(Option::OPTION_OUTPUT_FORMAT);
$outputFormatter = $this->outputFormatterCollector->getByName($outputFormat);
$outputFormatter->report($errorAndDiffCollector);
```

**Comment by TomasVotruba** [comment]
This would require closer cooperatoin to make it happen.
Closing as in-person hackaton is needed :)
