### ISSUE TITLE
How to instruct Rector to ignore specific lines?

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3207]
# Question

https://twitter.com/ondrejmirtes/status/1252115874317832193?s=21
`PHPStan 0.12.19 finally lets you ignore errors directly in code with @​phpstan-ignore-line and @​phpstan-ignore-next-line :tada: (That’s one big “finally”.)`

Is it possible to do something similar in Rector?

**Comment by TomasVotruba** [comment]
This might help: https://github.com/rectorphp/rector#exclude-paths-and-rectors

**Comment by shaal** [comment]
Thank you!

I tested this code and it worked:
```php
  /** @noRector \DrupalRector\Rector\Deprecation\FormatDateRector */
  return $formatted_date = format_date(123456);
```

**Comment by chester-af** [comment]
Just posting for anyone else that comes across this, `@noRector` is deprecated, you now need to use `->withSkip` in the rector config. Here is the PR that deprecated it:

https://github.com/rectorphp/rector-src/pull/3148
