### ISSUE TITLE
How can I generate docs using dump-rectors in Drupal-Rector?

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3208]
# Question
https://github.com/rectorphp/rector/blob/master/composer.json#L267

Using [Drupal-Rector](https://github.com/palantirnet/drupal-rector)
I tried running `vendor/rector/rector-prefixed/rector dump-rectors`
and got:
```
  Command "dump-rectors" is not defined.
```

I tried running `~/code/test/rector/bin/rector dump-rectors` inside document root of drupal-rector
(Using the full rector repo instead of rector-prefixed)

But I got what seems to be the built-in rectors, without any Drupal-Rector specific rules.
```
# All 497 Rectors Overview

- [Projects](#projects)
- [General](#general)

## Projects

- [Architecture](#architecture)
- [Autodiscovery](#autodiscovery)
- [CakePHP](#cakephp)
- [CakePHPToSymfony](#cakephptosymfony)
- [Celebrity](#celebrity)
- [CodeQuality](#codequality)
- [CodingStyle](#codingstyle)
- [DeadCode](#deadcode)
- [Doctrine](#doctrine)
.
.
.
```

**Comment by TomasVotruba** [comment]
Yea, this is `dev` only command.

You'd have to modify it to work with external repositories.

**Comment by shaal** [comment]
Thank you. I will look into how they did it in typo3-rector:
https://github.com/sabbelasichon/typo3-rector/commit/6a9c7a06e09b5190e07ba0533b581104baa2592d#diff-047fb30222b144a2bd3720f099232455

**Comment by TomasVotruba** [comment]
Well, that's wrong appraoch. It just copy pasting the code from here.
Instad the command should be changed here, so anyone can use it.

**Comment by TomasVotruba** [comment]
https://github.com/rectorphp/rector/blob/463dccb91ebc313c1050ea8a6e33a2817458760e/utils/documentation-generator/src/Command/DumpRectorsCommand.php#L45-L50

These lines needs to be modified to generic one.

**Comment by TomasVotruba** [comment]
I'm on this

**Comment by shaal** [comment]
@TomasVotruba you rock! Thank you

**Comment by TomasVotruba** [comment]
How does it work? :smiley:

**Comment by shaal** [comment]
I'll be happy to test it! 
I will report results soon

**Comment by shaal** [comment]
@TomasVotruba It works!
https://github.com/palantirnet/drupal-rector/blob/docs/docs/drupal-rector.md

**Comment by TomasVotruba** [comment]
```diff
-docs/docs/drupal-rector.md
+docs/drupal-rector.md
```
