### ISSUE TITLE
How to add a line to yml file

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3209]
# Question
What's the recommended way to add the line
```
core_version_requirement: ^8 || ^9
```
to `my_project.info.yml` file, if that line does not exist already?

**Comment by TomasVotruba** [comment]
Hi, I'm not sure what is the question.
Rector handles only PHP code.

**Comment by shaal** [comment]
Thank you, I wanted to make sure that I'm not missing any hidden functionality.
