### ISSUE TITLE
[PHP 8.0] Doc annotations to php attributes

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3210]
- Ref #3127
- RFC: https://wiki.php.net/rfc/attributes_v2#voting

![image](https://user-images.githubusercontent.com/924196/80210009-4ce8ca00-8633-11ea-8bed-2d53e36447d8.png)

Now we have to do it :laughing:

**Comment by TomasVotruba** [comment]
Covered in #3254

**Comment by TomasVotruba** [comment]
https://twitter.com/VotrubaT/status/1255264005771481096

**Comment by mrcodefinger** [comment]
Hi @TomasVotruba!
Is there a way to set @noRector as an attribute now?
`bin/rector rectify --future/attributes.php` gives me an  

> Command "rectify" is not defined. 

error.

Greetz
Gabriel

**Comment by TomasVotruba** [comment]
Hi, the attribute is not yet supported.

The `rectify` command was removed few years ago :) use `process` instead.
