### ISSUE TITLE
Move few static rectors to dynamic ones

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#322]
## Inspiration

- https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/QueryBuilder.php

### Start Case

- method name change + arg change, like Control redrawControl
    - https://github.com/rectorphp/rector/blob/bb4938db6e940eccfc88547b7c2dbc0ae42d801c/src/Rector/Contrib/Nette/Application/ValidateControlRector.php
    - https://github.com/nette/application/commit/afd8d321dd9eecd61fb96957d7a088933a7945ca#diff-c1f2adfe9e39de4486c15b301dc871eb

![image](https://user-images.githubusercontent.com/924196/36592755-54a57894-1897-11e8-9fe7-67126f13d380.png)

**Comment by TomasVotruba** [comment]
An approach inspired by Google's [ClangMR](https://research.google.com/pubs/pub41342.html) could look like:

```php
$rectorBuilder = new RectorBuilder;

$rectorBuilder->matchMethodCallByName('validateControl')
    ->changeTo('redrawControl')
    ->addArgument(2, false);
```

What do you think @carusogabriel ?

**Comment by carusogabriel** [comment]
@TomasVotruba Great ideas, I'll take a look this weekend :smile:

**Comment by carusogabriel** [comment]
I really like this, make the creation of a new Rector by a simple method chaining API, looks like a game changer :muscle:

**Comment by TomasVotruba** [comment]
Closing in favor of #435
