### ISSUE TITLE
Additional (code standard?) rules are running by default

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3222]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.16 (invoke `vendor/bin/rector --version`)              |
| Installed as   | prefixed Rector PHAR                      |

## Minimal PHP Code Causing Issue

In this example a docblock is being removed, because there's an empty docblock after it:
```
-/**
- * This docblock is being deleted when there's an empty docblock after it.
- */
-
-/**
- * 
- */
-
```
https://getrector.org/demo/9dbe8d1d-b062-4b16-97d2-605769834cbc#result

In this example empty comment lines are being removed, and 2 lines are being removed and added back the same way:
```

 /**
  * The empty line after this docblock is being deleted.
- */
-
+ */
 /**
  * Another dockblock.
- * 
+ *  
  *
  * first_function()
- * 
+ *  
  *
- * second_function()
- * third_function()
+ * second_function()
+ * third_function()
  * fourth_function()
- */
-
+ */
```
https://getrector.org/demo/0737a1e7-0b83-4e50-9e64-72f2e33476c8#result

## Expected Behaviour

I'm expecting rector to run only the rules that are set in rector.yml, and if it's not explicitly called it shouldn't run.

**Comment by shaal** [comment]
@TomasVotruba Can you please help us?
This became a major/urgent bug for us.

We are running [Drupal Rector](https://github.com/palantirnet/drupal-rector) against 10,000 projects (Drupal modules), to help them upgrade their code to the upcoming Drupal 9.

The Rector rules we implemented can already help 3,000 of these projects, as you can see in this list (rightmost column):
https://dev.acquia.com/drupal9/deprecation_status?name=&result=&error=&type=&group=&plan=&patch=available&op=Submit

But because Rector is running these additional code style rules, we cannot send the patches to all these projects that could benefit from it.

Here's an example with a mix of expected Rector rules and unexpected code style rules -
(lines 91, 99-260, 270, 278-395)
https://dispatcher.drupalci.org/job/phpstan/1462/artifact/phpstan-results/google_analytics.2.4.rector.patch/*view*/

(same file uploaded to github)
[google_analytics-drupal-module--rector-generated-patch.txt](https://github.com/rectorphp/rector/files/4524774/google_analytics-drupal-module--rector-generated-patch.txt)

**Comment by TomasVotruba** [comment]
If you provide failing PR with minimal test case (1 file), it makes it much simpler to fix.

**Comment by shaal** [comment]
Thank you.
These are the minimal test cases I created in main description of this issue:
- https://getrector.org/demo/9dbe8d1d-b062-4b16-97d2-605769834cbc#result
- https://getrector.org/demo/0737a1e7-0b83-4e50-9e64-72f2e33476c8#result

Please let me know if there's a better way to provide test cases.

**Comment by TomasVotruba** [comment]
I don't mean demo, but pull-request to code here. So continuous integration unit test are failing.

**Comment by shaal** [comment]
@TomasVotruba Do you mean creating something similar to this PR?
https://github.com/rectorphp/rector/pull/2943/files#diff-3ac972f8fab9c120f8727f6c02594334

If yes, how do I know were it should be located? I don't know what rule is creating these changes and where might it be called from.

**Comment by TomasVotruba** [comment]
Yes. The location is good question. We don't have such tests here AFAIK, just for particular @annotatoin. But I'd look somewhere in `packages/better-php-doc-parser/tests`

**Comment by damontgomery** [comment]
@shaal & @TomasVotruba, I created https://github.com/rectorphp/rector/pull/3250 to try and start this process.

The `AbstractRectorTestCase` tests didn't seem like they were the way to go because they only ran a single rule (which I can't identify) and they also didn't report failures the way the one I submitted did.

I may have time next week to look at this more.

**Comment by tedbow** [comment]
Is this related to #3212  and #2994?

**Comment by TomasVotruba** [comment]
@tedbow No, that is spacing of class annotations. This one is about multiple comments.

It was introduced in this PR: https://github.com/rectorphp/rector/pull/2775
There will be also a bug, in `BetterStandardPrinter` and `update*` method
