### ISSUE TITLE
Rector can't handle multiple @Route annotations

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#3230]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.0.-v0.7.17 (and online: 0.8.x-dev@a2e11ba)|
| Installed as   | composer dependency                      |

Symfony allows multiple routes per controller action, but Rectors removes it.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1a789879-ee5c-45ee-a721-ddec93b96839#result

## Expected Behaviour

Multiple routes is allowed, so it should stay the same.

**Comment by TomasVotruba** [comment]
I see it now. There is extra `)` in the end. It must be removed.

```diff
    /**
-     * @Route("/new", name="route_1", methods={"GET", "POST"}))
+     * @Route("/new", name="route_1", methods={"GET", "POST"})
      * @Route("/{id}", name="route_2", methods={"GET", "POST"})
      */
``` 

It's processed correctly then: https://getrector.org/demo/4d6234ba-b5e7-4ed2-b0e3-778bec91c8f8#result

**Comment by stephanvierkant** [comment]
I'm sorry, you're right!

**Comment by alister** [comment]
I've got what I think is a clean, failing, test for a multiple-route annotation failure - https://getrector.org/demo/169c2867-dac5-4b88-b770-355745b74552

When I use multiple routes at an __invoke-able class level (not as default route prefixes, but as alternate routes to the same action), the second list @'Route' is removed, and the first is duplicated. 

```diff
  * @Route("/blogish/", defaults={"page"="1", "_format"="html"}, methods={"GET"}, name="blogish_index")
- * @Route("/blogish/rss.xml", defaults={"page"="1", "_format"="xml"}, methods={"GET"}, name="blogish_rss")
- */
+ * @Route("/blogish/", defaults={"page"="1", "_format"="html"}, methods={"GET"}, name="blogish_index")
+ */
```

The `bin/console debug:router` shows access to both routes with the 2-`Route()` original code.
```
> bin/console debug:router | grep blogish -C 1
  blog_search                GET        ANY      ANY    /{_locale}/blog/search
  blogish_index              GET        ANY      ANY    /{_locale}/blogish/
  blogish_rss                GET        ANY      ANY    /{_locale}/blogish/rss.xml
  security_login             ANY        ANY      ANY    /{_locale}/login
```

When the Route annotations are moved immediately above the `public function __invoke(..)` method, rector does nothing with them.

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1:
