### ISSUE TITLE
Rector removes empty name from @Route annotation

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#3234]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.17              |
| Installed as   | composer dependency                       |
```

In Symfony you can annotate a name and path in a Controller class, which is actually a prefix of controller actions in that class:

/**
 * @Route("front", name="front")
 */
final class FrontController extends Controller
{
    /**
     * @Route("/", name="")
     */
    public function homepage() : Response
    {
         //...
    }
}
attribute
>  bin/console debug:router
`  front                                   GET|POST            ANY      ANY    /front/`

Rector removes the empty name attribute, which means the route is removed.

```
## Minimal PHP Code Causing Issue

https://getrector.org/demo/9dee6b7b-b443-4432-915b-5c22a80a4106#result

## Expected Behaviour

An empty attribute is required in this case so it should be untouched.

**Comment by TomasVotruba** [comment]
Could you add failing test case to other routes?

**Comment by TomasVotruba** [comment]
Basically:

-  create new file from one of these: https://github.com/rectorphp/rector/tree/master/packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/SymfonyRoute
- rename class + rename the file name
- put invalid content in it
- send PR
