### ISSUE TITLE
 [Rector-Prefixed] Call to a member function getByType() on null

### ISSUE THREAD

**Issue by decad7never** [rectorphp/rector#3247]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.x-dev@8896f0a              |
| Installed as   | composer                     |

When i try to scan my folder we get the following error message, and the scan stop:

PHP Fatal error:  Uncaught Error: Call to a member function getByType() on null in phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php:38
Stack trace:
#0 phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer.php(46): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer\DoctrineRelationPropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#1 phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/rules/php74/src/Rector/Property/TypedPropertyRector.php(88): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#2 phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/src/Rector/AbstractRector.php(111): Rector\Php74\Rector\Property\TypedPropertyRector->refactor(Object(PhpParser\Node\Stmt\Property in phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php on line 38
Fatal error: Uncaught Error: Call to a member function getByType() on null in phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php:38
Stack trace:
#0 phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer.php(46): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer\DoctrineRelationPropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#1 phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/rules/php74/src/Rector/Property/TypedPropertyRector.php(88): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#2 phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/src/Rector/AbstractRector.php(111): Rector\Php74\Rector\Property\TypedPropertyRector->refactor(Object(PhpParser\Node\Stmt\Property in phar:///xxxxx/xxxxx/xxxxx/xxx/xxxxxx/vendor/rector/rector-prefixed/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php on line 38

Its not simple to found the source of this issue.

Thanks for a solution.

Regards 

decad7

**Comment by TomasVotruba** [comment]
Thanks for the report.

This should fix it: https://github.com/rectorphp/rector/pull/3253
