### ISSUE TITLE
Wiki - consider releases process

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#325]
This is very important part for end users, to be aware of what will happend when.
No need to resolve this now, just think about it

See
https://github.com/sebastianbergmann/phpunit/wiki/Release-Process

**Comment by carusogabriel** [comment]
@TomasVotruba Good idea to have, but let's wait for PHP-Parser v4, and launch Rector v1!

**Comment by TomasVotruba** [comment]
I think releasing v1 would take more than 1-2 years, we're barely pass 0.1 now. This is just something not to forget after getting into v1. I love how Sebastian handles those upgrades.

**Comment by TomasVotruba** [comment]
Blocker #389

**Comment by TomasVotruba** [comment]
Too soon at the moment, still many issues to resolve for public stable use
