### ISSUE TITLE
Undefined property: PhpParser\Node\Expr\ArrowFunction::$stmts 

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#3257]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.16|
| Installed as   | composer dependency|

```
PHP Notice:  Undefined property: PhpParser\Node\Expr\ArrowFunction::$stmts in
.../vendor/rector/rector/rules/dead-code/src/Rector/FunctionLike/RemoveCodeAfterReturnRector.php on line 64
```

**Comment by TomasVotruba** [comment]
Demo link is needed

**Comment by TomasVotruba** [comment]
Already fixed 9 days ago: https://github.com/rectorphp/rector/commit/7b8b482a96e9a72aac4e79f4dd17479d214c30cb

Be sure to always check first demo (latest version) or latest tag before reporting issues.
