### ISSUE TITLE
Processing inline phpdoc can duplicate closing tag (syntax error)

### ISSUE THREAD

**Issue by davidbrnovjak** [rectorphp/rector#3258]
# Bug Report

When inline @var phpdoc is used in code without space before closing tag a closing tag `*/` is duplicated.
```
final class DemoFile
{
-	/** @var MyService*/
+	/** @var MyService*/ */
     public $service;
}
```
Duplicated closing tag causes rector to fail subsequently with `Could not process "XYZ" file, due to: "Syntax error, unexpected '*' on line 23"`

I’m not sure if this is an issue in Rector or underlying lib.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/677fac26-6d8e-4e52-8449-3ee815a4ca80

## Expected Behaviour

Should skip or add space before origin closing tag.

**Comment by TomasVotruba** [comment]
Fixed by https://github.com/rectorphp/rector/commit/8c486b52e7bebddfbbc108c569f847d4d75285e9
