### ISSUE TITLE
Bundled box.phar file overwriting default php functions in IDE

### ISSUE THREAD

**Issue by MetalArend** [rectorphp/rector#3259]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.18              |
| Installed as   | composer dependency                      |

After installing the latest version of Rector, PHPStorm started giving me autocompletion on standard PHP functions like for example `error_reporting`, with the result `\_HumbugBox3ab8cff0fda0\error_reporting()`. After some digging, I found it came from the file [compiler/build/box.phar](https://github.com/rectorphp/rector/blob/master/compiler/build/box.phar) that is bundled with Rector. Is there a way to not include this phar by default in the package?

There's a few other solutions, like using the phar file or a global install, but I would think box would be a dev dependency. I might be missing something, though. ;) It's just extremely annoying, as you cannot exclude vendor directories in PHPStorm, and the autocompletion 'knows' of every function in there.

Thanks for looking into this, and for all the efforts on developing Rector!

**Comment by TomasVotruba** [comment]
Agreed, this file should not be there :disappointed: 

> Is there a way to not include this phar by default in the package?

Look into https://github.com/rectorphp/rector/blob/master/compiler/src/Console/Command/CompileCommand.php
There all the compile magic happen.

If you find a way to fix this, I'd love to merge it.

**Comment by MetalArend** [comment]
Wow, you're going fast :o Thank you for the quick fix.

**Comment by TomasVotruba** [comment]
:+1: 

It wasn't that hard to add 1 line. There are much harder problems, that took me weeks (*not so fast*) :laughing:
