### ISSUE TITLE
Invalid file created when replacing partial NS

### ISSUE THREAD

**Issue by jarektkaczyk** [rectorphp/rector#3263]
# Bug Report

Hi @TomasVotruba and the team. First let me thank you for the great tool 🚀 🚀 

Here's something I stumbled upon in my codebase when using `auto_import_names: true`:

```
use Money; <----- NS rather than specific class import
use AnotherNs\Currency; <----- this is why Money is imported as NS rather than classes `use Money\Money` & `use Money\Currency`
+use Money\Money; <------ this becomes conflicting import error

@@ -180,9 +181,9 @@
     /**
      * @return Money\Money  <-------- this should change
      */
-    public function getBalance(): Money\Money
+    public function getBalance(): Money
     {
-        return new Money\Money($this->transactions()->sum('amount'), new Money\Currency('SGD'));
+        return new Money($this->transactions()->sum('amount'), new Money\Currency('SGD'));
     }
```

So the issues are following:
1. creating faulty file after adding conflicting import `use Money\Money`
2. not using `use Money\Currency as CurrencyAlias` and not replacing also `new Money\Currency('SGD')` part of the code
3. not replacing `@return Money\Money` with `@return Money` after adding `use Money\Money`
4. missing rule in the process summary - see below

**I'm happy to dig deeper and serve you with a PR 😄 .**
I would love some hints as where to start - it's literally first time I'm looking at rector here and not sure which rules specifically applies here as the cli output shows only `short closure`

<img width="878" alt="image" src="https://user-images.githubusercontent.com/6928818/80294808-129c3b80-879f-11ea-819b-3cd21cc1b3d7.png">

**Comment by TomasVotruba** [comment]
Hey,

> Hi @TomasVotruba and the team. First let me thank you for the great tool rocket rocket

Thanks :+1:  

To your issue. Rector currently imports all he can, including partial namespaces.

Correct approach would be removing `use Money;` import, as it it's not a class namespace.

In `Rector\PostRector\Rector\UseAddingPostRector`

**Comment by javaDeveloperKid** [comment]
I'm having the same issue. Using namespace in use statements instead of classes is something normal so this should import only added classes, not to modify.
```
--- Original
+++ New
@@ -2,6 +2,7 @@
 namespace App\Repository;

use Doctrine\ORM\Query\Expr;
+use Doctrine\ORM\Query\Expr\Join;
@@ -153,7 +154,7 @@
             $qb->leftJoin(
                 'orderPositions.orderPrices',
                 'orderPricesChild',
-                Expr\Join::WITH,
+                Join::WITH,
                 'orderPricesChild.parentCompany = :parentCompany'
             );
```

**Comment by TomasVotruba** [comment]
Failing test case is needed

**Comment by TomasVotruba** [comment]
Closing as stale
