### ISSUE TITLE
[Rector-Prefixed] Symlink

### ISSUE THREAD

**Issue by decad7never** [rectorphp/rector#3268]
When a launch the scan with this command.

vendor/bin/rector process inscription --config rector_inscription.yaml --dry-run --debug

I can look that rector doesn't scan recursively all directorys inside the directory inscription if symlinks are used for that. Exemple 

inscription / document_root / (symlink -> bo) => ../.../bo

All files inside the folder linked with the symlink BO are not scanned by rector. How i can do that please ?

Thansk 

Regards

Decad7

**Comment by TomasVotruba** [comment]
Hi, I'd look at this section: https://github.com/rectorphp/rector/blob/525ed1e2cbc41a1e49493a7e43e8bb686a59cf48/src/FileSystem/FilesFinder.php#L113

Might be tuned to return symlinked files too.

**Comment by TomasVotruba** [comment]
Hi, I'd look at this section: https://github.com/rectorphp/rector/blob/525ed1e2cbc41a1e49493a7e43e8bb686a59cf48/src/FileSystem/FilesFinder.php#L113

Might be tuned to return symlinked files too.

**Comment by decad7never** [comment]
Ok but today we have no configuration way to return symlinked files ?

**Comment by TomasVotruba** [comment]
Not really.
