### ISSUE TITLE
Does RemoveUnusedPrivatePropertyRector remove to much? 

### ISSUE THREAD

**Issue by tomasnorre** [rectorphp/rector#3291]
# Question

In TYPO3 we have the `PublicPropertyDeprecationTrait` and `PublicMethodDeprecationTrait` which used two private Properties see example below. 

The rector rule `Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector` want to remove them as they are not directly used in the code, but by the trait. 

Is this something that I need to handle on my site, or is this something in Rector that doesn't fit TYPO3 (yet)? 

```
2) Classes/Service/ProcessService.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -53,26 +53,6 @@
     use PublicPropertyDeprecationTrait;

     /**
-     * @var string[]
-     */
-    private $deprecatedPublicProperties = [
-        'queueRepository' => 'Using queueRepository is deprecated since 9.0.1 and will be removed in v10.x',
-        'crawlerController' => 'Using crawlerController is deprecated since 9.0.1 and will be removed in v10.x',
-        'countInARun' => 'Using countInARun is deprecated since 9.0.1 and will be removed in v10.x',
-        'processLimit' => 'Using processLimit is deprecated since 9.0.1 and will be removed in v10.x',
-        'verbose' => 'Using verbose is deprecated since 9.0.1 and will be removed in v10.x',
-    ];
-
-    /**
-     * @var string[]
-     */
-    private $deprecatedPublicMethods = [
-        'multiProcess' => 'Using ProcessService::multiProcess() is deprecated since 9.0.1 and will be removed in v10.x',
-        'reportItemStatus' => 'Using ProcessService::reportItemStatus() is deprecated since 9.0.1 and will be removed in v10.x',
-        'startRequiredProcesses' => 'Using ProcessService::startRequiredProcesses() is deprecated since 9.0.1 and will be removed in v10.x',
-    ];
-
-    /**
      * @var int
      */
     private $timeToLive;
    ----------- end diff -----------

Applied rules:

 * Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
```

**Comment by TomasVotruba** [comment]
I don't think it's possible to resolve traits using some private properties (too much nested magic).

Either use `@noRector` for these cases or better refactor to better design. Regardless tooling, reading such code would be WTF for me.

**Comment by tomasnorre** [comment]
Thanks for your input, will see what I do.

**Comment by TomasVotruba** [comment]
From the top of my head, I'd approach it like this:

```php
/**
 * @deprecated 
 * @since 9.0.1
 */
public $somePropertyToBeRemoved;
```

+ better parent method, but trait would also do

```php
public function __get($name)
{
    // is local property?
    // get it's docs
    // is @deprecated? 
    // show warning or whatever
}
```

That way all you need to add are annotations, and your IDE will also show this ~~nice effect~~:

![image](https://user-images.githubusercontent.com/924196/80866661-37594d00-8c90-11ea-96ce-556c8fbacb86.png)

**Comment by tomasnorre** [comment]
I normally would too, but I would like to profit from the traits given by the TYPO3 Core. 
The trait also handles the error handling etc. on the deprecations so I honestly think it's quite elegant, but I also understand your point. 

Thanks for a fast reply as always.

**Comment by TomasVotruba** [comment]
Ah, I see. Bad 3rd party design is the worst :cry:

**Comment by tomasnorre** [comment]
The `@noRector` does not work for me.. 

Doing something wrong? 

```php
/**
 * @var string[]
 * @noRector \Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
 */
```

**Comment by TomasVotruba** [comment]
Not sure, I don't use the annotation.

Try one of these:

- https://github.com/rectorphp/rector/issues/3207
- https://github.com/rectorphp/rector#exclude-paths-and-rectors
- https://github.com/rectorphp/rector/blob/525ed1e2cbc41a1e49493a7e43e8bb686a59cf48/src/Exclusion/Check/ExcludeByDocBlockExclusionCheck.php#L35

**Comment by tomasnorre** [comment]
I think there is something not quite right with the rector and the @noRector annotation. 

I know it's not preferred to used it, but it's offered as part of the rector and it should then work as designed then. 

I have the following demo on your online demo:
https://getrector.org/demo/c8b95592-2d1b-4dc5-b675-e6e2a44a5857#result

and I have added a branch on my private fork, no PR yet, that tests this functionality, unfortunately, the tests fail.
https://github.com/tomasnorre/rector/commit/ff590d84cbf7d040eefd6b99fddb0884f3021a29

I have checked which rules that are checked during the test run, and the one I'm filtering for is not checked and therefore never a match and then the annotated property is removed.

These are the regexes check during my tests:

```
#@noRector\s*\\?Rector\\DeadCode\\Rector\\Plus\\RemoveDeadZeroAndOneOperationRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\Plus\\RemoveDeadZeroAndOneOperationRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\Plus\\RemoveDeadZeroAndOneOperationRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\ClassMethod\\RemoveEmptyClassMethodRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\ClassMethod\\RemoveEmptyClassMethodRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\ClassMethod\\RemoveEmptyClassMethodRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\Plus\\RemoveDeadZeroAndOneOperationRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\Plus\\RemoveDeadZeroAndOneOperationRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\Plus\\RemoveDeadZeroAndOneOperationRector#i
#@noRector\s*\\?Rector\\DeadCode\\Rector\\Plus\\RemoveDeadZeroAndOneOperationRector#i
```

**Comment by TomasVotruba** [comment]
We need better way to verify than whole CI.
Could you add failing test case? 

Copy of issues here:
https://github.com/rectorphp/rector/tree/master/tests/Issues

**Comment by tomasnorre** [comment]
I'll do that later tonight, so keep as is, and add the additional tests issue?

**Comment by TomasVotruba** [comment]
Yes.

**Comment by TomasVotruba** [comment]
Could you send https://github.com/tomasnorre/rector/commit/ff590d84cbf7d040eefd6b99fddb0884f3021a29 as PR? We need to see the CI failing

**Comment by tomasnorre** [comment]
That was my first commit in the PR till we started the dialog on that I should add them to Issues under test.

**Comment by TomasVotruba** [comment]
I see. I just explore it now as another option to find a bug. Next time, send it as PR right away, so we can immediately see CI feedback.

**Comment by tomasnorre** [comment]
Cool, thanks. 

But don't get why I need to add both annotations. 

```
@noRector \Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
@noRector \Rector\DeadCode\Rector\Class_\RemoveSetterOnlyPropertyAndMethodCallRector
```

The first one I get, but the second, not really.

**Comment by TomasVotruba** [comment]
Because both rules try to remove it.
Personally I'd go just with `@noRector` here.

**Comment by TomasVotruba** [comment]
> If both are required, I think the documentation on that should be updated with an additional example.
rectorphp/rector#exclude-paths-and-rectors

I think it's common for annotations that they can be used multiple times.

**Comment by tomasnorre** [comment]
> Because both rules try to remove it.
> Personally I'd go just with `@noRector` here.

I thought it had to be specified which rule. Thanks

**Comment by TomasVotruba** [comment]
> I thought it had to be specified which rule. Thanks

That would be my guess :D... I haven't add/used the feature yet.

**Comment by tomasnorre** [comment]
I'm sorry to bother you again.. I still have issues with the `@noRector` that I don't get. 

```
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@noRector" in property AOE\Crawler\Service\ProcessService::$deprecatedPublicProperties was never imported. Did you maybe forget to add a "use" statement for this annotation?
```
I get the above error by running the tests
Any idea how to bypass this? The rector works, but the application doesn't accept the annotation. :(

**Comment by tomasnorre** [comment]
I found the solution that to @sabbelasichon 
```php
@ignoreAnnotation("noRector")
```

On class level did the trick for me.

**Comment by TomasVotruba** [comment]
I assume you use Doctrine and it's parser. This should be part of your AnnotationParser setup.

Look for "ignore" keyword here: https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/annotations.html
