### ISSUE TITLE
Multiple lines become single line

### ISSUE THREAD

**Issue by rochamarcelo** [rectorphp/rector#3316]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.0 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency            |

The process command is transforming multiple lines into single lines.

I tested with different sets (php56, php70)

## Minimal PHP Code Causing Issue
Replaced this 
```
$parameters = [
            'host' => $destination->host,
            'port' => $destination->port,
            'aeTitle' => $destination->aet,
        ];
```
 into 

``` 
$parameters = ['host' => $destination->host, 'port' => $destination->port, 'aeTitle' => $destination->aet];

```

## Expected Behaviour

The lines should not become on single line.

**Comment by TomasVotruba** [comment]
This can be only solved by own coding standard, see https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by shaal** [comment]
@TomasVotruba isn't this issue related to #3222 ?
Where Rector is changing the code where it wasn't expected?

**Comment by TomasVotruba** [comment]
These are spacing on item - originated in `nikic/php-parser`.

The #3222 is about false positive on mergin of doc comments - that's Rector scope.

**Comment by maliayas** [comment]
I'm confused. In [this comment](https://github.com/nikic/PHP-Parser/issues/344#issuecomment-354009287) Nikita says multiline status is preserved. [The commit](https://github.com/nikic/PHP-Parser/commit/1c7fd314d182bafd7254ca8d025a4d83a72a2d6a) is still there. So I'd expect this bug automatically would disappear. What am I missing? Is Rector overriding the original behaviour hence the bug still persists?

Other than that, preserving formatting as much as possible while modifying code is IMHO a desired functionality. Also helps when reviewing the changes. Applying a coding standart suite for this purpose can be considered an overkill.

Thanks for giving us Rector.

**Comment by samsonasik** [comment]
@maliayas that preserved because of no-reprint, changing long array to short array require re-print, so can't be preserved.
