### ISSUE TITLE
Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector misfires

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#3334]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rectror v0.7.22             |
| Installed as   | composer dependency / prefixed Rector PHAR                      |

The rule (sometimes?) translates `if(!$something)` into irrelevant `if($something === 0)` or `if($something === [])`. 

## Minimal PHP Code Causing Issue

For example: why would an int be `=== []` ??

https://getrector.org/demo/43d58b6a-133d-487e-ad9e-ec51824520d6

**Comment by TomasVotruba** [comment]
The annotation syntax is incorrect, see
https://getrector.org/demo/c676e726-0b5a-42b5-ab28-0828b2975641#result

Without `/**` the PHPStan, it will be missed
