### ISSUE TITLE
Prevent rewrite of partial namespace imports

### ISSUE THREAD

**Issue by lstrojny** [rectorphp/rector#3336]
Given this input

```php
<?php
use Symfony\Component\Validator\Constraints as Assert;

$constraint = new Assert\Blank();
```

Rector would apply this change
```diff
--- Original
+++ New
@@ -1,4 +1,5 @@
 <?php
+use Symfony\Component\Validator\Constraints\Blank;
 use Symfony\Component\Validator\Constraints as Assert;

-$constraint = new Assert\Blank();
+$constraint = new Blank();
```

How to prevent rector to refactor towards fully qualified imports?

**Comment by TomasVotruba** [comment]
We need failing test case for that here: https://github.com/rectorphp/rector/tree/c915743c3e3a4eb21dc33204a4c485b0afba36c9/rules/coding-style/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture

**Comment by lstrojny** [comment]
What can I do to help? Open a PR with the test case?

**Comment by TomasVotruba** [comment]
Yes :+1:

**Comment by lstrojny** [comment]
@TomasVotruba here we go: #3101
