### ISSUE TITLE
Revert "drop confusing --only option" Commit

### ISSUE THREAD

**Issue by lukas9393** [rectorphp/rector#3342]
I wanted to ask why you removed the "--only" argument [9eaeb3053e6449bf2e6a871b3a9f0f65cd0b1daf]. Is it still possible to select only one "Rector" via the console? If there is no other option than to customize the config, is there a chance to revert the commit?

`  The "--only" option does not exist.  `

**Comment by TomasVotruba** [comment]
See the PR, it's in the top left corner of the commit.

**Comment by lukas9393** [comment]
> it's confusing, people are unable to use it #3020 (comment)
I'm sorry that people have problems dealing with this, but in my opinion, this cannot be the reason for removing a feature.

> the --only="Namespace\Class" must be quoted right - slashes? single? double? + OS differences
Maybe we can extend the api to include this backslash, slash, single, double... and reduce complexity. Or we extend the documentation to explains it better. I would like to point out that we use this feature, and it would be nice to think about it again.

I'm sorry to bother you with this

**Comment by lukas9393** [comment]
I have worked out a solution for myself that now works without the "--only" argument. I create a tmp config file with the rector I want to run and start the command. It's a bit overhead but that's the way it is.

```php
use Symfony\Component\Yaml\Yaml;

class RectorCommand
{
    public static function execute(string $rector, string $file): array
    {
        $configPath = self::createRectorConfig($rector);
        $command    = [
            "executable"           => "php vendor/bin/rector",
            "refactor source code" => "process",
            "show only diff"       => "--dry-run",
            "hide progress bar"    => "--no-progress-bar",
            "disable ANSI output"  => "--no-ansi",
            "path to config file"  => "-c $configPath",
            "output format"        => "--output-format json",
            "file to check"        => $file,
        ];
        $command    = implode(" ", $command);
        $result     = shell_exec($command);
        $actual     = json_decode($result, true);
        unset($actual['meta']);
        return [$command, $actual];
    }

    public static function createRectorConfig(string $rector): string
    {
        $data      = [
            "parameters" => [
                "auto_import_names" => true,
            ],
            "services"   => [
                $rector => null,
            ],
        ];
        $tmpConfig = tempnam(sys_get_temp_dir(), "").".yml";
        file_put_contents($tmpConfig, Yaml::dump($data));
        return $tmpConfig;
    }
}
```

**Comment by TomasVotruba** [comment]
@afilina  Seeing so much effort from you, I'll rething adding it.

I've noticed the standalone command PR, that might be a way to go as it's clear from the command name.

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/pull/3539

**Comment by TomasVotruba** [comment]
The `--only` option is causing troubles again.

Since the summer switch from YAML to PHP configs, the set optoins was also redisigned to be used purely in PHP. The set names from CLI were mismatched to their PHP names. The `--set` option CLI has been removed as well, so the config would be the single place to use

See: https://github.com/rectorphp/rector/issues/4699
