### ISSUE TITLE
The string '<?php  ?>' is being mistakenly removed

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3352]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.25 (prefixed)              |
| Installed as   |  prefixed Rector PHAR                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f1bc0f86-1bfa-4527-80de-3ab3839347f0#result

## Expected Behaviour

Rector should leave that string `'<?php  ?>'` as is and not remove it.

**Comment by TomasVotruba** [comment]
This is part of php-parser empty print cleanup.

It's dead code, that doesn't do any behavior and should not be in your code.

What troubles it causes you?

**Comment by shaal** [comment]
The assumption is that Rector will not change anything in the code, unless it was specifically instructed to do so through rector.yml

`<?php ?>' is used in various Drupal projects, when a string is sent to Drupal multilingual system (the t() function), like this:
```
$description .= ' ' . $this->t('If the PHP option is chosen, enter PHP code between %php. Note that executing incorrect PHP code can break your Drupal site.', ['%php' => '<?php ?>']);
```

List of projects using it:
http://grep.xnddx.ru/search?text=%3C%3Fphp+%3F%3E&filename=

**Comment by TomasVotruba** [comment]
I see. I'm not sure how to solve this in the printer though.

**Comment by shaal** [comment]
PR #3395 resolved this issue.
