### ISSUE TITLE
phpstan-src no longer usable on PHP < 7.4 out of the box

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#3353]
Hi,
please see this PR: https://github.com/phpstan/phpstan-src/pull/202

You need to call `bin/transform-source.php` in phpstan-src before compiling the Rector PHAR.

**Comment by TomasVotruba** [comment]
Hi, thanks for the script!

**Comment by ondrejmirtes** [comment]
FYI another update - `scoper.inc.php` needs updating according to this commit: https://github.com/phpstan/phpstan-src/commit/2ebe211ab48d3b2b43559b99b0c287e636712b2c#diff-463a36e4a5687fb2366b5ee56cdad92d

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by TomasVotruba** [comment]
Added to phar release process

**Comment by TomasVotruba** [comment]
Covered in https://github.com/rectorphp/rector/commit/d7c5a923c1a5651c2c8a831d5e2374f864ba5798
