### ISSUE TITLE
Rector to replace count() >0 with !empty()

### ISSUE THREAD

**Issue by tmotyl** [rectorphp/rector#3373]
# Feature Request

In order to avoid iteration over (potentially big) dataset, !empty should be used instead of count to check emptiness of an array 

## Diff 

```diff
-if (count($array)) {
+if (!empty($array)) {
```
```diff
-if (count($array) > 0) {
+if (!empty($array)) {
```

**Comment by TomasVotruba** [comment]
`empty()` actually checks much more than arrays (quoting [docummentaiton](https://www.php.net/manual/en/function.empty.php))

```
"" (an empty string)
0 (0 as an integer)
0.0 (0 as a float)
"0" (0 as a string)
NULL
FALSE
array() (an empty array)
```

So it makes code very fragile. It's like replacing `string|int` with `mixed`.

<br>

Why do you think it should be part of Rector core?

**Comment by tmotyl** [comment]
Sure empty() allows more input types then count.
But if count was used in the code, it means the variable was array or Countable already. 
And for these types I don't see how checking empty instead of count() > 0 would make code more fragile.
hmm ok I see the problem with countable. This refactoring would make sure we're operating on arrays only.
If you don't think this fits rector, please close the issue.

**Comment by TomasVotruba** [comment]
Refactoring would work. It's about reading it by future programmer or you few months later.

`empty()` doesn't tell anything about type and can silently accept invalid input.
