### ISSUE TITLE
Preserving comments and whitespace

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3375]
# Feature Request

I read your tweet the other day https://twitter.com/VotrubaT/status/1260207064338571264?s=20

On that HHAST project they wrote how they can fully create an updated file after mutating the AST, preserving comments and whitespaces.
https://github.com/hhvm/hhast/blob/master/docs/linters-development.md#whitespace-and-comments

Is that something that can be implemented in Rector? or it has to be done through https://github.com/nikic/PHP-Parser ?

**Comment by TomasVotruba** [comment]
I think this method is broken: 
https://github.com/rectorphp/rector/blob/c29e0273c58bd82706776882f444f34932d50846/packages/node-type-resolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php#L117

**Comment by TomasVotruba** [comment]
Closing as answered
