### ISSUE TITLE
[Semantical Error] The annotation "@Doctrine\ORM\Mapping\Index" in class ... was never imported

### ISSUE THREAD

**Issue by realdo-msk** [rectorphp/rector#3380]
Hi.
After update version to 0.7.26,  during analyze code of my project I receive the error:

Could not process "src/Voting/Infrastructure/Entity/VotingEntity.php" file, due to:                            
         "[Semantical Error] The annotation "@Doctrine\ORM\Mapping\Index" in class                                      
         App\Voting\Infrastructure\Entity\VotingEntity was never imported. Did you maybe forget to add a "use" statement
         for this annotation?". 

but in "src/Voting/Infrastructure/Entity/VotingEntity.php" there is:

use Doctrine\ORM\Mapping\Index;

is this a bug?

**Comment by TomasVotruba** [comment]
Hi, could you try later `dev-master`? 

I've encoutered similar error and solved it by bumping `doctrine/annotations` to `1.10`, see https://github.com/rectorphp/rector/commit/4b4c524af8194fb2c0a6d7b2573dfa251a61bf89

**Comment by realdo-msk** [comment]
composer show doctrine/annotations:


name     : doctrine/annotations
descrip. : Docblock Annotations Parser
keywords : annotations, docblock, parser
versions : * 1.10.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : http://www.doctrine-project.org
source   : [git] https://github.com/doctrine/annotations.git b9d758e831c70751155c698c2f7df4665314a1cb
dist     : [zip] https://api.github.com/repos/doctrine/annotations/zipball/b9d758e831c70751155c698c2f7df4665314a1cb b9d758e831c70751155c698c2f7df4665314a1cb
path     : /app/vendor/doctrine/annotations
names    : doctrine/annotations

autoload
psr-4
Doctrine\Common\Annotations\ => lib/Doctrine/Common/Annotations

requires
doctrine/lexer 1.*
ext-tokenizer *
php ^7.1

requires (dev)
doctrine/cache 1.*
phpunit/phpunit ^7.5

**Comment by realdo-msk** [comment]
I try to update rector to dev-master, but there is the error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rector/rector dev-master -> satisfiable by rector/rector[dev-master].
    - rector/rector dev-master requires symplify/auto-bind-parameter ^8.0 -> satisfiable by symplify/auto-bind-parameter[8.0.x-dev, v8.0.0-beta1, v8.0.0-beta2] but these conflict with your requirements or minimum-stability.

**Comment by TomasVotruba** [comment]
I wonder how to simulate this... could you make reproucible repository, so I can run `composer install` and `vendor/bin/rector` and have the same error?

**Comment by realdo-msk** [comment]
I created a new symphony project with the same configuration files but the error did not repeat, but I used only a couple of my php source files in the project

here is the file on which the error appears in my project:

<?php

namespace App\Voting\Infrastructure\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Index;

/**
 * @ORM\Entity
 * @ORM\Table(schema="Voting", name="Voting", indexes={
 *     @Index(name="voter_created", columns={"voter_id", "created"}),
 *     @Index(name="voted_for_type", columns={"voted_for_id", "vote_type"})}
 * )
 */
class VotingEntity
{
    /**
     * @ORM\Column(type="bigint")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="bigint")
     */
    private int $voterId;
    /**
     * @ORM\Column(type="bigint")
     */
    private int $votedForId;
    /**
     * @ORM\Column(type="string")
     */
    private string $voteType;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTime $created;

    public function __construct(
        int $voterId,
        int $votedForId,
        string $voteType,
        DateTime $created
    ) {
        $this->voterId = $voterId;
        $this->votedForId = $votedForId;
        $this->voteType = $voteType;
        $this->created = $created;
    }

    public function getVoterId(): int
    {
        return $this->voterId;
    }

    public function getVotedForId(): int
    {
        return $this->votedForId;
    }

    public function getVoteType(): string
    {
        return $this->voteType;
    }
}



after running vendor/bin/rector:

src/Voting/Infrastructure/Entity/VotingEntity.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -6,8 +6,7 @@

 use DateTime;
 use Doctrine\ORM\Mapping as ORM;
-use Doctrine\ORM\Mapping\Index;
-
+use Index;


and then:

 [ERROR] Could not process "src/Voting/Infrastructure/Entity/VotingEntity.php" file, due to:                            
         "[Semantical Error] The annotation "@Doctrine\ORM\Mapping\Index" in class                                      
         App\Voting\Infrastructure\Entity\VotingEntity was never imported. Did you maybe forget to add a "use" statement
         for this annotation?".

**Comment by TomasVotruba** [comment]
Hi,

there've been samo annotation fixed related to annotations.

Also I see there is mix of use imports. That might cause it, as it's very atypical code.

Try this:

```diff
use Doctrine\ORM\Mapping as ORM;
-use Doctrine\ORM\Mapping\Index;

/**
 * @ORM\Entity
 * @ORM\Table(schema="Voting", name="Voting", indexes={
- *     @Index(name="voter_created", columns={"voter_id", "created"}),
+ *     @ORM\Index(name="voter_created", columns={"voter_id", "created"}),
- *     @Index(name="voted_for_type", columns={"voted_for_id", "vote_type"})}
+ *     @ORM\Index(name="voted_for_type", columns={"voted_for_id", "vote_type"})}
 * )
 */
```

**Comment by realdo-msk** [comment]
i'am was  update rector to 0.7.29 and applied your's diff but the result the same:

Could not process "src/Voting/Infrastructure/Entity/VotingEntity.php" file, due to:                            
         "[Semantical Error] The annotation "@Doctrine\ORM\Mapping\Index" in class                                      
         App\Voting\Infrastructure\Entity\VotingEntity was never imported. Did you maybe forget to add a "use" statement
         for this annotation?".

**Comment by TomasVotruba** [comment]
That's really weird.

Could you give us the demo example that fails? https://getrector.org/demo
That way' we can reproduce and fix it

**Comment by TomasVotruba** [comment]
Closing as stale and demo link or reproducible repository is needed.
