### ISSUE TITLE
RenameAnnotationRector using hasByName() on null

### ISSUE THREAD

**Issue by eclipxe13** [rectorphp/rector#3381]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.26              |
| Installed as   | composer dependency                     |

rector fails with message: *[ERROR] Could not process "tests/SomeTest.php" file by "Rector\Renaming\Rector\Annotation\RenameAnnotationRector", due to:                                                                                                                     "Call to a member function hasByName() on null".*

## Minimal PHP Code Causing Issue

```php
<?php
// file tests/SomeTest.php
namespace tests;

class SomeTest extends \PHPUnit\Framework\TestCase
{
    /*
     * This is a comment and not a docblock
     */
    public function testSomething()
    {
        $this->assertTrue(false, 'Expected failure!');
    }
}
```

running: `rector process --set phpunit70 --dry-run tests/SomeTest.php`

The error is not thrown if instead of a comment enclosed by `/* .. */` is replaced by `/** ... */`.

The error is also present if `// ...` is used

## Expected Behaviour

Do not fail on `RenameAnnotationRector` rule.

## More information

Related to `ExceptionAnnotationRector`, a similar issue is present.
On commit #3199 issue #3179 is solved by checking if the instance returned by `$node->getAttribute(AttributeKey::PHP_DOC_INFO);` is not null, I think that the same check should be placed for `RenameAnnotationRector`.

IMO this is an easy PR. If you would like me to solve the issue by adding the null check after `$node->getAttribute()` I can make it, but I'm not familiar with rector development. Please advise.

PD: Thanks for rector and all this work!

**Comment by TomasVotruba** [comment]
> I think that the same check should be placed for RenameAnnotationRector

Yes. Could you send PR?

**Comment by eclipxe13** [comment]
for sure... cooking!
