### ISSUE TITLE
Symfony Annotation @Route localized multiline

### ISSUE THREAD

**Issue by rem42** [rectorphp/rector#3388]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.26               |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    /**
     * @Route({
     *     "en": "/about-us",
     *     "nl": "/over-ons"
     * }, name="about_us")
     */
    public function about()
    {
        // ...
    }
}
```

https://getrector.org/demo/ae6c32fc-c193-4919-9567-57f19a82a670

## Expected Behaviour

Rector need to skip it, because it's in Symfony doc : https://symfony.com/doc/current/routing.html#localized-routes-i18n

**Comment by TomasVotruba** [comment]
Hi, we need failing fixture to be added here:
https://github.com/rectorphp/rector/tree/master/packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/SymfonyRoute

Just copy one of them, change name and the content.

Thank you

**Comment by noahlvb** [comment]
Hi I also ran into this issue and wanted to resolve it. I created the failing test, but I cannot seem te figure out what te right approach  is to fix it.
