### ISSUE TITLE
CakePHP showcase

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#340]
Accroding to
https://book.cakephp.org/3.next/en/appendices/3-6-migration-guide.html
there have been many class rename and method rename cases.

It might be worth to prepare simple config for them

@EdoBarnas This might be nice intro issue. Would you take it? I can help of course

**Comment by TomasVotruba** [comment]
@EdoBarnas This might be nice intro issue. Would you take it? I can help of course

**Comment by EdoBarnas** [comment]
Yes, I agree.

**Comment by TomasVotruba** [comment]
Great! So I'd find `symfony40.yml` file and create similar one in `phpcake36`.

Read the link and try to add all the cases you know.

**Comment by TomasVotruba** [comment]
Done in #346
