### ISSUE TITLE
Node "PHPStan\PhpDocParser\Ast\Type\ConstTypeNode" was missed

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#3401]
note sure what this error is trying to tell me?
```
 [ERROR] Could not process "lib/debug_toolbar/DebugToolbar.php" file, due to:
         "Node "PHPStan\PhpDocParser\Ast\Type\ConstTypeNode" was missed in
         "Rector\BetterPhpDocParser\Attributes\Ast\AttributeAwareNodeFactory::createFromNode". Generate it with:
         bin/rector sync-types".
```

do I use some kind of declartion/notation which rector is not aware of/does not support?

**Comment by TomasVotruba** [comment]
This means PHPStan has a new type, that is not ported to Rector yet.

You can it via pull-request:

```
Generate it with: bin/rector sync-types
```

**Comment by staabm** [comment]
my regular rector runtime (installed via composer) does not have a sync-types command .
I guess I need to clone the rector repo and run the command from there?

**Comment by staabm** [comment]
hmm running sync-types from a repo cloned from github master tells me nothing is missing:
```
mstaab@NB-COMPLEX-15 MINGW64 ~/Documents/GitHub/php-rocket (rector-set-71)
$ php /c/dvl/GitHub/rector/bin/rector sync-types
Rector 0.8.x-dev@80f429b
Config file: rector.yml

 [OK] All PHPStan Doc Parser nodes are covered with attribute aware mirror in Rector
```

**Comment by TomasVotruba** [comment]
Yes, to contribute here you need to fork.

What PHPStan versions is your project and is Rector fork?

**Comment by staabm** [comment]
running rector from latest master branch instead of the stable-release does not error.

I guess its a already fixed problem.



> What PHPStan versions is your project and is Rector fork?

I have phpstan 0.12.25 with php 7.4.5 and rector@80f429b5b

**Comment by TomasVotruba** [comment]
You can verify that by searching the PHPStan class in Rector's code

**Comment by staabm** [comment]
I guess its here: https://github.com/rectorphp/rector/blob/851ba5da5509fedaebb1311c333c8f0e4d14f780/packages/attribute-aware-php-doc/src/Ast/Type/AttributeAwareConstTypeNode.php#L7

**Comment by TomasVotruba** [comment]
Yes, that's the place.
