### ISSUE TITLE
Convert symfony routes from yaml to annotation

### ISSUE THREAD

**Issue by andreybolonin** [rectorphp/rector#3402]
# Feature Request

Hi all, no ideas how to make this changes automatically?
 
## Diff 

```diff
-hb.sale_funnel.organic.block6author.photo.update:
-  path: /course/sale_funnel/organic/block6/author/photo/update/{id}
-  defaults: { _controller: 'hb.admin.controller.sale_funnel.organic.block6author.image.update:handleAction' }
-  requirements:
-   id: \d+
-  options:
-    expose: true
+    /**
+     * @Route("/course/sale_funnel/organic/block6/author/photo/update/{id}", name="hb.sale_funnel.organic.block6author.photo.update"), options={"expose"=true}, requirements={"id"=\d+}
+     */
```

**Comment by TomasVotruba** [comment]
Hi, 

- you can create a rule that takes path to file with routes in __constructor
- then find controller in your projects container
- is subscribed to `ClassMethod`
- matches the class name to your project's controllers
- adds the `RouteTagValueNode` annotation if matched

**Comment by TomasVotruba** [comment]
Closing as answered. If you make this rule, I'd be happy to include it in Recto core. It might be useful for whole Symfony community.

**Comment by Herz3h** [comment]
Could you update the procedure for current code, want to work on this, thank you
