### ISSUE TITLE
Adding phpunit80.yaml as a resource on rector-prefixed 

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3408]
# Question
I want to run the rules that are in phpunit80.yaml, on Rector-prefixed (to upgrade a drupal project) 

If I add to rector.yml, under imports 
```
- { resource: "vendor/rector/rector/config/set/phpunit/phpunit80.yaml"} 
```

Rector-prefixed says it cannot find it. 

The temporary solution I found was installing full rector on a separate directory, copy the vendor directory from there to rector-prefixed. 

But I'm sure there's a better way. Can you tell me how?

**Comment by TomasVotruba** [comment]
Paths to config are hard to use. Moreover when you need to prefix them in phar.

What about `sets` parameter in config?
https://github.com/rectorphp/rector/blob/master/README.md#a-prepared-sets

**Comment by shaal** [comment]
Oh, much easier than I thought. For some reason I thought only `phpunit` is a set.

Adding this to `rector.yml` solves the problem. Thank you!
```yml
parameters:
  sets:
    - phpunit80
```

**Comment by TomasVotruba** [comment]
I see. I'm glad it works!

There is actually lot of sets:

- https://github.com/rectorphp/rector/tree/master/config/set
