### ISSUE TITLE
Class 'Symplify\BetterReflectionDocBlock\CleanDocBlockFactory' not found

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#342]
Hi, running `vendor/bin/rector process src --level nette24` i got following error:

```
[ERROR] Class 'Symplify\BetterReflectionDocBlock\CleanDocBlockFactory' not found in                                    
         /private/var/folders/2m/28z_py912fqff7x8sr0x0rxw0000gn/T/_rector_cache/ContainerCjlV94i/getDocBlockFactoryService.php on line 8   
```

It seems that there is `symplify/better-reflection-docblock` dependency missing in rector composer dependencies.

**Comment by TomasVotruba** [comment]
Good point. I forgot to add it when I removed ECS. Could you add it please?

**Comment by Lexinek** [comment]
Yeah, i will send a PR, just need to solve #343  first

**Comment by vasilvestre** [comment]
I got it, today, on dev branch

**Comment by WillyReyno** [comment]
Having the same error here...

**Comment by TomasVotruba** [comment]
How to replicate it?

**Comment by WillyReyno** [comment]
@TomasVotruba 

I installed Safe PHP and wanted to refactor the code with Rector

I first tried to reproduce it on a fresh project but everything works.
So I created an other project with the same composer.lock file as the project where I had this error, and it shows up when I do : 
```
vendor/bin/rector process app/ --config vendor/thecodingmachine/safe/rector-migrate.yml
```

Here's my repository : https://github.com/WillyReyno/laravel-rector-safe

**Comment by TomasVotruba** [comment]
What Rector version do you use?

**Comment by TomasVotruba** [comment]
Could you try the most recent one? I think I've fixed this before

Try to removing `composer.lock` + `/vendor` and set it manually to `composer.json`

**Comment by TomasVotruba** [comment]
There is a demo project, that uses Rector as 3rd party dependency: https://github.com/rectorphp/demo/blob/master/composer.json

And it passes, see `.travis.yml`

**Comment by WillyReyno** [comment]
Updating manually in composer.json worked!

**Comment by TomasVotruba** [comment]
Thanks for letting me know
