### ISSUE TITLE
Doctrine Default Options

### ISSUE THREAD

**Issue by tavy315** [rectorphp/rector#3424]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.26             |
| Installed as   | composer dependency                      |

I'm trying to understand what Rector rule produces this diff and why. Is this a bug or a feature?

![image](https://user-images.githubusercontent.com/6184412/82903810-31dae400-9f6a-11ea-87e8-076c3f55eba5.png)

I tried reproducing it on Rector demo, but I get different output there:

https://getrector.org/demo/628bca03-12c5-41f3-b549-72fa7122b528

**Comment by TomasVotruba** [comment]
Demo had a 1 month old version untill few minutes ago.

This should be fixed now:
https://getrector.org/demo/39e1cf93-b153-4d1a-8b07-6a4cd156a3b7#result

**Comment by tavy315** [comment]
Not sure you understood my statement: `{"default":1}` should be transformed to `{"default"=1}`? And if so, which rule/transformer does that?

**Comment by TomasVotruba** [comment]
It should not and is not. See the demo link

**Comment by tavy315** [comment]
My bad, I assumed it was related to doctrine, but seems to be related to "symfony50" ruleset. See demo https://getrector.org/demo/f35c24d0-21e5-4bd8-b90c-68c0c77f212a#result

**Comment by TomasVotruba** [comment]
This is a design choice based on official Symfony/Doctrine docs, since there is no parsing tool for ":/=" in annotations.

See:

- https://github.com/rectorphp/rector/pull/3241
- https://github.com/rectorphp/rector/pull/3308

The meaning is the same, I recommend using `=` consistently in all Symfony/Doctrine annotations in nested arrays.

**Comment by tavy315** [comment]
Snippet from [Doctrine's documentation](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/annotations-reference.html#line-number-8f3e950b7cf37a3ab5ef14ee89a4561aa0df5f58-1):

![image](https://user-images.githubusercontent.com/6184412/84696199-c8406b00-af54-11ea-99d0-9753a371bac2.png)
