### ISSUE TITLE
MergeMethodAnnotationToRouteAnnotationRector malfunctions with one-liner doc blocks

### ISSUE THREAD

**Issue by phanan** [rectorphp/rector#3425]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.16             |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

I don't know how to specify the Rector demo to work with v0.7.16 so I'm posting the minimal code here instead:

`PostController.php`:

```php
<?php
use Symfony\Component\Routing\Annotation\Route;

class PostController
{
    /** @Route("/basically-anything") */
    public function indexAction()
    {
    }
}
```

`rector.yaml`:

```yml
services:
    Rector\Symfony\Rector\ClassMethod\MergeMethodAnnotationToRouteAnnotationRector: ~
```

## Expected Behaviour

Since there's no `@Methods` annotation here, the file should be left as is.

## Actual Behaviour

The closing tag `*/` of the doc block is gone, leaving the file in a broken state:

```diff
 class PostController
 {
-    /** @Route("/basically-anything") */
+    /** @Route("/basically-anything")
     public function indexAction()
     {
     }
```

Kindly let me know should you need more information.

**Comment by TomasVotruba** [comment]
Hi,

first, try the latest version or even `dev-master` version. There've been many fixes since yours version.

**Comment by phanan** [comment]
Thanks for replying. Here is the `dev/master` version: https://getrector.org/demo/822ed782-4a82-4768-b67c-59ceb481037f#result. I don't think it looks right, either.

**Comment by TomasVotruba** [comment]
There is no code change, so it looks right, right?

**Comment by phanan** [comment]
Oh indeed, I misread the result, sorry. Let me try it locally and update the issue.

**Comment by TomasVotruba** [comment]
Closing as fixed 

https://getrector.org/demo/23928b0a-9817-4304-aebe-736f333487a7#result
