### ISSUE TITLE
ChangeReadOnlyVariableWithDefaultValueToConstantRector struggles with $a = $b = ''

### ISSUE THREAD

**Issue by tigitz** [rectorphp/rector#3433]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.x-dev@7286f34             |
| Installed as   | docker                   |

## Minimal PHP Code Causing Issue

```php
class A {
   public function foo() {
       $a = $b = '';
   }
}
```
## Current Behaviour
```php
class A {
   const B = '';
   public function foo() {
       $a = self::B = ''; // Error: Expression is not assignable 
   }
}
```
## Expected Behaviour

if `$a` is not read only and `$b` is read only
```php
class A {
   const B = '';
   public function foo() {
       $a = self::B
   }
}
```

if `$b` is not read only and `$a` is read only
```php
class A {
   const A = '';
   public function foo() {
       $b = self::A
   }
}
```
if `$a` and `$b` are read only
```php
class A {
   const B = '';
   const A = '';
   public function foo() {
   }
}
```

More generally, keep all the non-readonly variables in the multi assignment statement but assign one of readonly constant as their value.

```php
$readOnly1 = $notReadOnly1 = $readOnly2 = $notReadOnly2 = 0;
```
to
```php
const READ_ONLY_1 = 0;
const READ_ONLY_2 = 0;

$notReadOnly1 = $notReadOnly2 = self::READ_ONLY_1;
```

**Comment by TomasVotruba** [comment]
Thanks for repoting, I'll look into it.

**Comment by TomasVotruba** [comment]
In general, Rector skip multi-case, e.g. multiple properties, `public $one, $two` as they are much complicated to handle.

So how to handle this case? There are *split* rules, that separate grouped operation to own lines.


- [one for multi assigns](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#splitdoubleassignrector)
- [one for properties and constants](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#splitgroupedconstantsandpropertiesrector)
- and [one for traits](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#splitgroupeduseimportsrector))

First, run these on your code, split to stnadalone lines and commit.

Then apply the `ChangeReadOnlyVariableWithDefaultValueToConstantRector` rule. I've fixed it, so it skips the multi assigns.
