### ISSUE TITLE
Split UnderscoreToPascalCaseVariableAndPropertyNameRector to Variable only rector and Property only rector

### ISSUE THREAD

**Issue by tigitz** [rectorphp/rector#3436]
# Feature Request

I inherited a laravel legacy code base and would like to apply pascal case rector only on variables as there's a lot of eloquent model usage like `$user->first_name` that I obviously don't want to touch for now.

That would mean splitting the current `UnderscoreToPascalCaseVariableAndPropertyNameRector` into:

- UnderscoreToPascalCaseVariableRector
- UnderscoreToPascalCasePropertyNameRector

Does it seem reasonable to you @TomasVotruba  ?

Remaining question would be "Does the `UnderscoreToPascalCaseVariableAndPropertyNameRector` be kept for backward-compatibility ?"

**Comment by TomasVotruba** [comment]
Hi, if it's related only to magic call on certain type of object, this rule should skip it.

Other property fetches are not related to Eloquent, right?

**Comment by tigitz** [comment]
Hey Tomas !

So I haven't dove deep enough in the big diff to check if there are "legit" use case of non-magic property fetches but if that's the case, indeed, that would be great to ignore the magical ones rather than simply discard every properties fetch.

So when you say 

> this rule should skip it.

You mean the current behaviour is supposed to skip them already and it's a bug or it's a feature that must be implemented ?

**Comment by TomasVotruba** [comment]
>  it's a feature that must be implemented ?

This one :+1:

**Comment by tigitz** [comment]
Alright, thanks to this legacy project I have a ~10 items list of edge cases where rector falls short. I'll try to work on them including this one.

Do you have any tips on how I'll be able to guess if the property is a magical one or not ?  

Property declaration or lack of ? Seems fragile as it don't necessarily mean it's a magic one.
If a __set() method exists ? Property can be left untouched by the method.

**Comment by TomasVotruba** [comment]
> Do you have any tips on how I'll be able to guess if the property is a magical one or not ?

There is a rule, that completes properties, that are called without definition (magically created).

See: https://github.com/rectorphp/rector/blob/master/rules/code-quality/src/Rector/Class_/CompleteDynamicPropertiesRector.php#L54


> Property declaration or lack of ? Seems fragile as it don't necessarily mean it's a magic one.
> If a __set() method exists ? Property can be left untouched by the method.

Could you provide demo link for both of these cases? https://getrector.org/demo

**Comment by ishan-biztech** [comment]
+1 to this Feature Request. In some legacy project people want to change variable names to camelCase but do not want to change property name as some of the side effects(#3516) that come with it.
