### ISSUE TITLE
`@template T as <type>` phpdoc changes to `@template T of <type>`

### ISSUE THREAD

**Issue by someniatko** [rectorphp/rector#3438]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.26              |
| Installed as   | composer dependency (global) |

Annotation `@template T as <type>` gets transformed into `@template T of <type>`, regardless of used rectors, which may be undesirable due to the "visual noise" changes.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/a6a52fee-ddc2-4794-9efd-e95518b21a13

## Expected Behaviour

`@template T as <type>` should stay as-is.

**Comment by TomasVotruba** [comment]
Thanks for repoting, I'll look into it.
