### ISSUE TITLE
Wrongly prefixed classes in rector-prefixed

### ISSUE THREAD

**Issue by nziermann** [rectorphp/rector#3444]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@8a32ed3 (commit: cae75a5c4175a8a4d017c39863961217d7fe2443)              |
| Installed as   | prefixed Rector PHAR                      |

I have problems with the following rectors:
- GetToConstructorInjectionRector
- ContainerGetToConstructorInjectionRector

After looking inside the classes it can be seen that the symfony classes are also prefixed with _HumbugBox0dc5136a9e25. In the case of GetToConstructorInjectionRector I could manually specify the correct classes in my rector config after which it worked as expected.

## Minimal PHP Code Causing Issue

The examples in the fixtures fail for me with:

    Rector\Symfony\Rector\FrameworkBundle\GetToConstructorInjectionRector: ~

but work with

    Rector\Symfony\Rector\FrameworkBundle\GetToConstructorInjectionRector:  
        $getMethodAwareTypes:
          - 'Symfony\Bundle\FrameworkBundle\Controller\Controller'
          - 'Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait'

## Expected Behaviour
It should behave the same in both cases.

**Comment by TomasVotruba** [comment]
Thanks for reporting and specific locations and how to spot the bug. I gave me clear idea where to look for the issue.
