### ISSUE TITLE
Fix fqsen annotations by strict ReflectionDocBlock

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#345]
Follow up from https://github.com/rectorphp/rector/issues/307, validate cases like

```php
namespace AAA;
class BBB
{
    /**
      * @see Oracle http://def.gh
      */
    public function ccc() {}
}
```

---

```
  [InvalidArgumentException]
  "\App\AfsModule\Components\EntityHistory\array[string" is not a valid Fqsen.
```
for code
```php
    /**
     * @var array[string month => int times]
     */
    private $monthTimes = [];
```

---

or callable with additional info
```
[InvalidArgumentException]
  "\App\IpMap\callable[];" is not a valid Fqsen.

```
for code:
```php
    /**
     * @var callable[]; function (IpMap $map)
     */
    public $onDataRequest = [];
```

**Comment by carusogabriel** [comment]
@TomasVotruba Is this something that we can fix, or is related to our dependencies?

**Comment by TomasVotruba** [comment]
@carusogabriel It's related to BetterReflectionDocBlock, but here we can get the example where it fails and send test case to Symplify.

**Comment by TomasVotruba** [comment]
Resolved in Symplify https://github.com/Symplify/Symplify/pull/757
