### ISSUE TITLE
Upgrade PHP 5.6 codebase to 7.2

### ISSUE THREAD

**Issue by jchorvat** [rectorphp/rector#3454]
Hi,

I am not able to update from PHP 5.6 to 7.2. I am changing php_version_features, but nothing changed. Errors are from PHP 7.2. For example: Fatal error: Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name.

I am running rector from docker: docker run -v e:/www/7.2/quantum:/project rector/rector:latest process /project --dry-run --config /project/rector.yml

content of rector.yml
parameters:
    php_version_features: '5.6'
    sets:
        - 'dead-code'
    autoload_paths:
        - '/project/libs/autoload.php'
        - '/project/app'
        - '/project/libraries'

What I am doing wrong?

Thank you.

**Comment by TomasVotruba** [comment]
Hi,

the `PhpOffice\PhpWord` in your vendor has to be updated to version compatible with PHP 7.0, where `string` is reserved word.

<br>

You have to 2 options:

- rename class manually to `String_` in `/vendor` - I'd to id now, as it's fast solution  and the package will be updated anyway
- update the package in `composer.json` to version compatible with PHP 7.0

**Comment by jchorvat** [comment]
Hi,

thank you for answer.

Source code has to be in PHP >= 7.0? I wanted to upgrade code from 5.6, so I thought rector will do it.

In readme is written this "Upgrade your code from PHP 5.3 to PHP 7.4".

**Comment by TomasVotruba** [comment]
Source code has to be in at least 5.3 syntax.

But this is something different. It's your local PHP that interprets the code, so anything that is not allowed in you PHP version, like reserved keyword, will not work.

You were lucky enough to hit one of very rare BC breaks in PHP 7.


`php_version_features` let's say you run localy PHP 7.4, but on production you use PHP 7.0. Rector would upgrade your code to PHP 7.4 features, e.g. adding `void`, and typed property etc., so to keep it at 7.0, use:

```yaml
parameters:
    php_version_features: '7.0'
```

**Comment by jchorvat** [comment]
Thank you.

It is working now.
