### ISSUE TITLE
support glob wildcards in "paths" config

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#3462]
would be great I could configure the `paths:` property using a glob pattern:

```json
parameters:

  paths:
    - 'app/*/models/'   # <<----
    - 'lib/'
    - 'models/'
```

that way I would not need to configure a lot of separate paths on their own

maybe its already supported, but just not mentioned in the readme/docs?

**Comment by TomasVotruba** [comment]
I'm open to such feature. Feel free so send PR
