### ISSUE TITLE
use `is_countable()` in `CountOnNullRector`

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#3463]
I am wondering why there is this complex expression in 

https://github.com/rectorphp/rector/blob/2a96e5cf3b08a3c22e614f265cc1e220a7e4ebd7/rules/php71/src/Rector/FuncCall/CountOnNullRector.php#L49

 when you could also use https://www.php.net/is_countable as of 7.3 which is way more readable.

is there a particular reason I dont see?

**Comment by clxmstaab** [comment]
just realized I mixed up `is_iterable()` with `is_countable()`. adjusted the issue accordingly

**Comment by TomasVotruba** [comment]
The code you shared is for PHP 7.1.
The function is available since PHP 7.3, so it would break PHP 7.1 code
