### ISSUE TITLE
RemoveNullPropertyInitializationRector should not remove null on typed properties

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#3464]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.x-dev@5c82ca6              |
| Installed as   | composer dependency                 |

Rector should not remove `= null` from typed properties, as assigning null to typed properties prevents the property not initialized error in PHP 7.4.

Without the `= null`, you cannot access the variables before giving them a value due to the error talked about here: https://stitcher.io/blog/typed-properties-in-php-74#uninitialized

You could give them a value in the constructor, sure, but that seems to go against other rules Rector has, like giving every property typed to an array an initial value of [].

I am opening this issue because of your message to me here: https://github.com/rectorphp/rector/pull/1880#issuecomment-621330867

## Minimal PHP Code Causing Issue

https://getrector.org/demo/5693607b-b520-4610-948c-2459a1f2b7f4#result

The corrected code will error if you call `getSomeProperty` whereas it would not error in the uncorrected version.

## Expected Behaviour

Rector should skip it.

**Comment by TomasVotruba** [comment]
Agreed :+1: 

Could you send PR with fix? This one is easy pick

**Comment by TomasVotruba** [comment]
Resolved by #3465
