### ISSUE TITLE
Rector should display a clear error message when running with PHP < 7.2

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3501]
# Feature Request

## Suggestion:
Rector should display a clear error message when the minimum required PHP version is not met.

## Problem to be solved:
Through the use of [Drupal Rector ](https://github.com/palantirnet/drupal-rector) we've seen many instances where people using Docker that has PHP 7.1

They install Rector **outside** of Docker (on their machine they have PHP>=7.2 and Composer wouldn't have any problem), but then they run Rector **inside** Docker, where they have PHP 7.1, and getting this error:
```
PHP Fatal error:  Declaration of _HumbugBox3630ef99eac4\Symfony\Component\HttpKernel\Config\FileLocator::locate($file, $currentPath = NULL, $first = true) must be compatible with _HumbugBox3630ef99eac4\Symfony\Component\Config\FileLocatorInterface::locate(string $name, ?string $currentPath = NULL, bool $first = true) in phar:///var/www/html/vendor/rector/rector-prefixed/rector/vendor/symfony/http-kernel/Config/FileLocator.php on line 20
Fatal error: Declaration of _HumbugBox3630ef99eac4\Symfony\Component\HttpKernel\Config\FileLocator::locate($file, $currentPath = NULL, $first = true) must be compatible with _HumbugBox3630ef99eac4\Symfony\Component\Config\FileLocatorInterface::locate(string $name, ?string $currentPath = NULL, bool $first = true) in phar:///var/www/html/vendor/rector/rector-prefixed/rector/vendor/symfony/http-kernel/Config/FileLocator.php on line 20
```

**Comment by TomasVotruba** [comment]
Agreed :+1: 
Could you add it?

**Comment by shaal** [comment]
@TomasVotruba I created a PR #3513 , can you please review it?
