### ISSUE TITLE
I found a bug with the ChangeNestedForeachIfsToEarlyContinueRector

### ISSUE THREAD

**Issue by derrickschoen** [rectorphp/rector#3504]
# Bug Report

| ChangeNestedForeachIfsToEarlyContinueRector Bug| When there is a comment inside the if statement before the brace, it misses a brace creating the early continue statement. |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.29              |
| Installed as   | composer dependency                    |

## Minimal PHP Code Causing Issue
```
class CommentInsideIfStatement
{
    public function run()
    {
        $items = [];
        foreach ($values as $value) {
            if ($value === 5) //why am I doing this?
            {
                if ($value2 === 10) {
                    $items[] = 'maybe';
                }
            }
        }
    }
}
```
 https://getrector.org/demo/9757fa4a-ed15-4130-8bdc-ae150305360e

## Expected Behaviour
```
class CommentInsideIfStatement
{
    public function run()
    {
        $items = [];
        foreach ($values as $value) {
            if ($value !== 5) {
                //why am I doing this?
                continue;
            }
            if ($value2 !== 10) {
                continue;
            }
            $items[] = 'maybe';
        }
    }
}
```

Rector is producing invalid php when I try this.

https://github.com/rectorphp/rector/pull/3503

**Comment by TomasVotruba** [comment]
I think this is part of php-parser desing. Where `{` `}` are not nodes, so they can't have comments

You can report it there.

Also you can try this coding standard rule, that solves such errors:
https://github.com/slevomat/coding-standard#slevomatcodingstandardcommentingdisallowcommentaftercode-
