### ISSUE TITLE
[composer] migration for plugin 2.0

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3510]
See https://github.com/composer/composer/blob/2.0.0-alpha1/UPGRADE-2.0.md#for-integrators-and-plugin-authors

**Comment by TomasVotruba** [comment]
- https://github.com/symfony/flex/pull/617/

**Comment by simivar** [comment]
Is there any work required for this? I see that all of Workflows run on version 2 already.

**Comment by TomasVotruba** [comment]
It's not related to composer 2 here.
It was an idea to make a Rector set to upgrade composer plugins from 1 to 2.

Yet, it does not seem to get any traction. I'm closing this and leave it for community to contribute if needed.
