### ISSUE TITLE
[PHPExcel] migration to [PhpSpreadsheet]

### ISSUE THREAD

**Issue by Kaczorex** [rectorphp/rector#3514]
# Migrate from PHPExcel to PhpSpreadSheet
Hello, i want to migrate from my PHPExcel to PhpSpreadSheet with migrator 
i used 
```
composer require rector/rector --dev
vendor/bin/rector process src --set phpexcel-to-phpspreadsheet
composer remove rector/rector
```

```https://phpspreadsheet.readthedocs.io/en/latest/topics/migration-from-PHPExcel/```
or 
```https://getrector.org/blog/2020/04/16/how-to-migrate-from-phpexcel-to-phpspreadsheet-with-rector-in-30-minutes```

but it's not full migrate, it only migrate namespace, but forgets the method names

what i get:
```
$workbook = new PHPExcel();
```
to

```
new \PhpOffice\PhpSpreadsheet\Spreadsheet();
```

also i expect changes example: 
```
$sheet->setSharedStyle(...)
```
should be renamed to 
```
$sheet->duplicateStyle(...)
```

What i do wrong? or my are my expectations too high?

**Comment by TomasVotruba** [comment]
Could you check if `setSharedStyle` is part of the `phpexcel-to-phpspreadsheet` set? It might not be 100 % yet.

If not, provide full before/after example snippet of what should be changed and how.

**Comment by Kaczorex** [comment]
@TomasVotruba not only those method are not change in my file, all method mentioned in 
``` https://github.com/PHPOffice/PhpSpreadsheet/blob/50d78ce7898ee3a540cefd9693085b3636e578e6/docs/topics/migration-from-PHPExcel.md ``` are not change.

**Comment by TomasVotruba** [comment]
Minimal PHP snippets is needed.

**Comment by TomasVotruba** [comment]
The best would be a failing demo: https://getrector.org/demo

**Comment by Kaczorex** [comment]
@TomasVotruba but my question is: it should this change or not, using this migrator?

**Comment by TomasVotruba** [comment]
I think so:

https://github.com/rectorphp/rector/blob/b4acc0fc438bddfbeba5a286c0e150bf19ca24dc/config/set/php-office/phpexcel-to-phpspreadsheet.yaml#L25

**Comment by Kaczorex** [comment]
@TomasVotruba this is sample of my code 

Before
```
$workbook = new PHPExcel();
$sheet=$workbook->setActiveSheetIndex(0);
$sheet->setTitle($bookmark);
$sheet->setSharedStyle(StyleWithoutBorder('9999FF', 10, true, 'HORIZONTAL_CENTER',0,'Arial','VERTICAL_CENTER',false,false,'FFFFFF'), "A1:N1");
```
After
```
$workbook = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet=$workbook->setActiveSheetIndex(0);
$sheet->setTitle($bookmark); 
$sheet->setSharedStyle(StyleWithoutBorder('9999FF', 10, true, 'HORIZONTAL_CENTER',0,'Arial','VERTICAL_CENTER',false,false,'FFFFFF'), "A1:N1");
```

**Comment by TomasVotruba** [comment]
Great, I'll look into it today

**Comment by TomasVotruba** [comment]
Just to be sure: *after* is current output or expected output? 

If the current one, what is the expected output?

**Comment by TomasVotruba** [comment]
I made a test case for your use case: https://github.com/rectorphp/rector/pull/3529/files#diff-eb5638693781658ab832b255631b9728

And CI is passing it... what si different in that test case compared to your PR?

<br>

How is `--config` different to `--set`?

```bash
vendor/bin/rector process src --config vendor/rector/rector/config/set/php-office/phpexcel-to-phpspreadsheet.yaml

**Comment by Kaczorex** [comment]
@TomasVotruba I am close to prefection, 

i use command to migrate : ```vendor\bin\rector process src --set phpexcel-to-phpspreadsheet --autoload-file vendor\autoload.php```

and a lot of more was migrate but still some will ignoring

before migration:
``` 
                $header->applyFromArray(
                    array('fill' => array('type'=> PHPExcel_Style_Fill::FILL_SOLID, 'color'=> array('argb' => 'C0C0C0')),
                        'borders' => array(
                            'bottom' => array('style' => PHPExcel_Style_Border::BORDER_THIN),
                            'top' => array('style' => PHPExcel_Style_Border::BORDER_THIN),
                            'left' => array('style' => PHPExcel_Style_Border::BORDER_THIN),
                            'right' => array('style' => PHPExcel_Style_Border::BORDER_THIN)),
                        'font' => array('bold' => true, 'size' => 11, 'name' => 'Calibri', 'color'=> array('argb' => '000000')),
                        'alignment' => array(
                            'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
                            'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER)
                ));
```
after migration:
```
                $header = new \PhpOffice\PhpSpreadsheet\Style\Style();
                $header->applyFromArray(
                    array('fill' => array('type'=> \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID, 'color'=> array('argb' => 'C0C0C0')),
                        'borders' => array(
                            'bottom' => array('style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN),
                            'top' => array('style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN),
                            'left' => array('style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN),
                            'right' => array('style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN)),
                        'font' => array('bold' => true, 'size' => 11, 'name' => 'Calibri', 'color'=> array('argb' => '000000')),
                        'alignment' => array(
                            'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_LEFT,
                            'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER)
                ), true);
```
should be:
```
$header = new \PhpOffice\PhpSpreadsheet\Style\Style();
                $header->applyFromArray(
                    array('fill' => array('fillType'=> \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID, 'color'=> array('argb' => 'C0C0C0')),
                        'borders' => array(
                            'bottom' => array('borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN),
                            'top' => array('borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN),
                            'left' => array('borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN),
                            'right' => array('borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN)),
                        'font' => array('bold' => true, 'size' => 11, 'name' => 'Calibri', 'color'=> array('argb' => '000000')),
                        'alignment' => array(
                            'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_LEFT,
                            'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER)
                ), true);
```

Like you see those ignore border ```style``` and do not change to ```borderStyle``` and other thinks ```fillType```

still not perfect. some ideas?

**Comment by TomasVotruba** [comment]
Could you send PR with your before/after code fixture as in https://github.com/rectorphp/rector/pull/3529 ?

**Comment by TomasVotruba** [comment]
Closing for missing test case.

**Comment by khanks** [comment]
> 
> 
> I made a test case for your use case: https://github.com/rectorphp/rector/pull/3529/files#diff-eb5638693781658ab832b255631b9728
> 
> And CI is passing it... what si different in that test case compared to your PR?
> 
> Be aware, that old phpexcel package must be part of `composer.json` dependencies, or autoloaded by any other way.

PHPExcel has been around for so long that a lot of us didn't use composer to use it or load it.

**Comment by TomasVotruba** [comment]
Give it a try. It's pretty simple with autoload classmap
