### ISSUE TITLE
Best practices for adding new nodes to a file

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#3517]
# Question
We have some custom rectors and basically what they are trying to do it convert phpunit to pest.
We have something basic up and working, but just want to hear about some best practices.

The rectors can for example make the following conversion

<details>
  <summary>Conversion example</summary>
  
```php
<?php
use PHPUnit\Framework\TestCase;

class AfterClassTest extends TestCase
{
    /**
     * @afterClass
     */
    public function after()
    {
        echo 'afterAll';
    }

    public function testAfterClass()
    {
        $this->assertTrue(true);
    }
}
?>
-----
<?php
use PHPUnit\Framework\TestCase;
afterAll(function () {
    echo 'afterAll';
});
it('testAfterClass', function () {
    $this->assertTrue(true);
});
?>

```
</details>

One of our rectors here are the `@afterClass` converter rector

<details>
  <summary>AfterClassToAfterAllRector</summary>
  
```php
class AfterClassToAfterAllRector extends AbstractPHPUnitToPestRector
{
    public function getNodeTypes(): array
    {
        return [ClassMethod::class];
    }

    /**
     * @param ClassMethod $methodNode
     */
    public function refactor(Node $methodNode): ?Node
    {
        /** @var Class_ $classNode */
        $classNode = $methodNode->getAttribute(AttributeKey::CLASS_NODE);
        if (!$this->isObjectType($classNode, TestCase::class)) {
            return null;
        }

        if (!$this->isAfterClassMethod($methodNode)) {
            return null;
        }

        $newNode = $this->createPestAfterAll($methodNode);

        $this->addNodeAfterNode($newNode, $classNode);
        $this->removeNode($methodNode);
        return $methodNode;
    }

    private function isAfterClassMethod(ClassMethod $method): bool
    {
        /** @var PhpDocInfo $phpDoc */
        $phpDoc = $method->getAttribute(AttributeKey::PHP_DOC_INFO);

        return $phpDoc && $phpDoc->hasByName('afterClass');
    }

    private function createPestAfterAll(ClassMethod $method): FuncCall
    {
        return $this->builderFactory->funcCall(
            'afterAll',
            [
                new Closure(['stmts' => $method->stmts]),
            ]
        );
    }
}
```
</details>

The rector does the following steps

1. Check that the ClassMethod's class is a phpunit class
2. Check that the ClassMethod is a phpunit afterClass method
3. Creates a new node which calls the pest equivalent to afterClass and adds a closure with all the statements in the phpunit method.
4. Adds this new node after the class node
5. Deletes the method node.

Another rector will then check if all methods in the class has been deleted and then delete the class also.

For me this seems a little weird to add the new node after the class node, when we delete the class node later on. Also because I just want to add the new node into the file.
Is there a better approach for this?

**Comment by TomasVotruba** [comment]
The best would be to work removed node and traverse down, so `Class_` here.

It's more intuitive and fluent, than replacing nodes, then traversing up, get the `Class_`, remove it, add nodes afte it... etc.

Otherwise your rule is correct - `addNodeAfterNode()` is used exactly for this case.

**Comment by olivernybroe** [comment]
Ah alright, makes sense. So we listen for `Class_` type instead of `ClassMethod`. 

Then we use the `traverseNodesWithCallable` over all the `ClassMethod` on the `Class_` node. 

We can then use that callable to remove the nodes, but adding the new node in still needs to use the `addNodeAfterNode` method right? 

Or am I misunderstanding something?

<details>

```php
class AfterClassToAfterAllRector extends AbstractPHPUnitToPestRector
{
    public function getNodeTypes(): array
    {
        return [Class_::class];
    }

    /**
     * @param Class_ $node
     */
    public function refactor(Node $node): ?Node
    {
        if (!$this->isObjectType($node, TestCase::class)) {
            return null;
        }

        $this->traverseNodesWithCallable($node->getMethods(), function (Node $classMethod) use ($node) {
            if (! $classMethod instanceof ClassMethod) {
                return null;
            }

            if (!$this->isAfterClassMethod($classMethod)) {
                return null;
            }

            $newNode = $this->createPestAfterAll($classMethod);
            $this->addNodeAfterNode($newNode, $node);

            $this->removeNode($classMethod);
            return NodeTraverser::DONT_TRAVERSE_CURRENT_AND_CHILDREN;
        });

        return $node;
    }

    private function isAfterClassMethod(ClassMethod $method): bool
    {
        /** @var PhpDocInfo $phpDoc */
        $phpDoc = $method->getAttribute(AttributeKey::PHP_DOC_INFO);

        return $phpDoc && $phpDoc->hasByName('afterClass');
    }

    private function createPestAfterAll(ClassMethod $method): FuncCall
    {
        return $this->builderFactory->funcCall(
            'afterAll',
            [
                new Closure(['stmts' => $method->stmts]),
            ]
        );
    }
}
```
</details>

**Comment by TomasVotruba** [comment]
Yes, that looks fine :+1:

**Comment by TomasVotruba** [comment]
If you want a quick code-review on some rule, just ping me there. I'll give it few minutes if I'll be free

**Comment by olivernybroe** [comment]
Awesome, will do that! 👍 Thanks a lot!
