### ISSUE TITLE
Add dynamic property declaration after use statement

### ISSUE THREAD

**Issue by ishan-biztech** [rectorphp/rector#3531]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@57fc2ab             |
| Installed as   | prefixed Rector PHAR                      |

Adds dynamic property above `use` statement.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f422e76c-7a47-4d00-9dcc-758363d5292e

## Expected Behaviour

As per [PSR-12](https://www.php-fig.org/psr/psr-12/#42-using-traits) standard 

> The `use` keyword used inside the classes to implement traits MUST be declared on the next line after the opening brace.

So rector should not add property declaration above the `use` statement instead add after `use` statement if trait is used inside the class.

**Comment by TomasVotruba** [comment]
The code is correct.

As for the coding standards, you have to use a coding standard tool for that:
https://github.com/rectorphp/rector#how-to-apply-coding-standards
