### ISSUE TITLE
Assume that Rector can be installed in a different directory than the project

### ISSUE THREAD

**Issue by afilina** [rectorphp/rector#3540]
# Feature Request

I always install Rector in its own directory. To do otherwise will clash with many of the project's dependencies. Here's an example: https://github.com/rectorphp/rector/issues/2417#issuecomment-564397169

Currently, Rector assumes that we install it into the vendor folder of the project. Some rules reflect that. Example: https://github.com/rectorphp/rector/blob/master/rules/psr4/src/Composer/PSR4AutoloadPathsProvider.php#L50
 
## Diff 

The example above would probably need to be refactored so that the `getcwd()` could instead come from a config.

Also, I'd just like the maintainers to keep this in mind when developing any filesystem-sensitive rules.

**Comment by TomasVotruba** [comment]
Failing reproductible repository would fasten this feature :+1:

**Comment by Aerendir** [comment]
@afilina , try use `bamarni/composer-bin-plugin`.

I'm using it with success: Rector works like a charm and all dependencies conflicts gone away.

**Comment by TomasVotruba** [comment]
Closing as bamarni solution is good enough here
