### ISSUE TITLE
Generator replaced by void with ReturnTypeDeclarationRector

### ISSUE THREAD

**Issue by orklah** [rectorphp/rector#3542]
# Bug Report

Rector ignore a reference used in a native function and replace a correct return type by void with ReturnTypeDeclarationRector

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f373a677-197e-4bde-b7ea-bc5cfff57337

## Expected Behaviour

Nothing changing in given example. In any case, void is forbidden when there is a return or a yield in a function: https://3v4l.org/FeKld
Maybe a php -l after rectoring a file could detect big issues like that?

**Comment by TomasVotruba** [comment]
Just checking safe_types are irelevant to this, broken even without them.

See https://getrector.org/demo/761557ab-d6b8-462b-9130-7cdd9b64b0cf#result

**Comment by orklah** [comment]
Yes, safe_types is not relevant, I only came accross this bug and some other while checking for safe_types issues so the yaml file is setup for that

**Comment by TomasVotruba** [comment]
Also, it works with `yield` alone: https://getrector.org/demo/4523a536-bc78-4767-9eec-80ce89bae04a#result

So the `yield <from>` is causing it.
