### ISSUE TITLE
return type made non-nullable when setter is not nullable

### ISSUE THREAD

**Issue by orklah** [rectorphp/rector#3543]
# Bug Report

When rector detects that a setter exists for an attribute, it changes the return type of the getter to match the setter. When there is no parameter type or when the parameter is nullable, you may want to keep the null possibility because the getter can be called before the setter (and it will return null at that point)

## Minimal PHP Code Causing Issue

https://getrector.org/demo/c3725f71-65c9-4e7b-af0e-5764e80139ae#result

## Expected Behaviour

Nothing changing in given example.
One could argue that with safe types activated, Rector should only change the return type of a getter based on the parameter type, because when there is no parameter type, the parameter *could* contain anything

**Comment by samsonasik** [comment]
It seems already fixed ref https://getrector.org/demo/2985c358-67ce-48a5-a152-c0ae9658c18d#result

**Comment by TomasVotruba** [comment]
I see. Thanks for verification
