### ISSUE TITLE
[idea] Migration to PHP7

### ISSUE THREAD

**Issue by EdoBarnas** [rectorphp/rector#355]
Example using:
```
services:
    Rector\Rector\Dynamic\StrictPhp7Rector: ~
    Rector\Rector\Dynamic\StrictPhp71Rector: ~
    Rector\Rector\Dynamic\StrictPhp72Rector: ~
```

Use cases:
- add strict directive to the beginning of the php files
` declare(strict_types=1);"`
- add argument's typehint by parent class or interfaces if exists

**Comment by TomasVotruba** [comment]
Good idea!

But I think that is already covered by coding standards: https://github.com/Symplify/Symplify/blob/master/packages/EasyCodingStandard/config/php70.yml

Rector should focus new features rather then duplicating existing solutions.

**Comment by carusogabriel** [comment]
I’m with Tomas here, PHP 7 migration is already covered by CS
