### ISSUE TITLE
Fatal Error when starting the script.

### ISSUE THREAD

**Issue by metham** [rectorphp/rector#3567]
When I execute ` vendor/bin/rector process src --set phpexcel-to-phpspreadsheet`

I get this error : 

`316/1125 [=======>--------------------]  28%Fatal error: Cannot declare class App\Entity\Admin\Books, because the name is already in use in C:\wamp64\www\dior-calendar\src\Entity\Admin\Books.php on line 24
`

# Question

Is there a way to get a log or anything to know why I get this error ? Books is one of my own entities and I never had an error like this before.
I am currently trying to upgrade a project from Symfony 3 to 4.4 with a php 7 upgrade. I removed PHPExcel and tried the script to move on to PhpSpreadSheet, but I don't know how to solve the error that the script raised.

Do you have any ideas ? 

Thank you 😃

**Comment by TomasVotruba** [comment]
How did you solve it?

**Comment by metham** [comment]
Somewhere in my code this entity wasnt imported, I wasnt receiving any errors since it was just for a return type of a function.
It was my bad

**Comment by TomasVotruba** [comment]
So clearing cache? :D

**Comment by metham** [comment]
I just imported it, cleared the cache and yes it worked just fine ^^

**Comment by TomasVotruba** [comment]
How did you import it? Some use statement or yaml config?

I'm asking, because more people can have similar issues and clear PHP code solution would be really helpful for them.

**Comment by metham** [comment]
Ok, sorry if I was unclear.

It was a part which was autogenerated by composer and it was imported like this `\Books` so I could either replace it by `App\Entity\Admin\Books` or a simple use statement at the begining of the file (which I did).

**Comment by TomasVotruba** [comment]
I see.
