### ISSUE TITLE
config should be root level

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#357]
config/ inside src/ dir is not obvious or expected - and hard to spot there.
Instead it should be a root dir besides bin/ and the others.
Usually only classes are inside /src IMO.

It will make it a bit easier to work with.
Thanks for the great work btw.

**Comment by ravage84** [comment]
Agree, config is not a "source".

Even though I do not fully agree with everything [PDS](https://github.com/php-pds/skeleton/tree/1.0.0#summary) defines, I agree with the config folder name and its location in the root.

**Comment by TomasVotruba** [comment]
Do you have some examples of such approach in PHP projects?

**Comment by TomasVotruba** [comment]
If so, could you prepare PR for this?
@ravage84 @dereuromark

**Comment by ravage84** [comment]
> Do you have some real examples of such approach in PHP projects?

@TomasVotruba you mean the location and name of the configuration folder?

How about these?

https://github.com/cakephp/app/tree/3.5.1/config
https://github.com/symfony/demo/tree/v1.2.2/config
https://github.com/laravel/laravel/tree/v5.6.7/config

**Comment by TomasVotruba** [comment]
Yep, thank you. Let's go for it :+1:
