### ISSUE TITLE
Symfony: Cannot use FormTypeInstanceToClassConstRector within instances of AbstractController

### ISSUE THREAD

**Issue by andyexeter** [rectorphp/rector#3570]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.37             |
| Installed as   | composer dependency                    |

I noticed that the `Rector\Symfony\Rector\MethodCall\FormTypeInstanceToClassConstRector` rector isn't working for controllers which extend `Symfony\Bundle\FrameworkBundle\Controller\AbstractController`. 

Having a look at the code, I think this is because the rector only runs on controllers which extend `Symfony\Bundle\FrameworkBundle\Controller\Controller`

Is is possible to get the rector to run on instances of `Symfony\Bundle\FrameworkBundle\Controller\AbstractController`?

## Minimal PHP Code Causing Issue
```php
<?php

namespace App\Controller;

use App\Type\RectorTestType;

class RectorTestController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    public function rectorTestAction()
    {
        $this->createForm(new RectorTestType());
    }
}
```

## Expected Behaviour

```php
<?php

namespace App\Controller;

use App\Type\RectorTestType;

class RectorTestController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    public function rectorTestAction()
    {
        $this->createForm(RectorTestType::class);
    }
}
```

**Comment by TomasVotruba** [comment]
Demo link is needed: https://getrector.org/demo

**Comment by andyexeter** [comment]
There is no error, it just skips the file.

Demo using `\Symfony\Bundle\FrameworkBundle\Controller\AbstractController`: https://getrector.org/demo/efc84a42-4635-4a76-8ce4-0fa5b284861f#result - no replacement is made.

Demo using`Symfony\Bundle\FrameworkBundle\Controller`: https://getrector.org/demo/aa098649-c69a-4d28-8574-671c144929f1#result - works as expected.
