### ISSUE TITLE
Identifying method chaining in nodes

### ISSUE THREAD

**Issue by EclipseGc** [rectorphp/rector#3575]
# Question
Working within the context of things happening over in Drupal right now, we do a lot of method chaining which might look similar to the following:

`$node->getEntityType()->getLowercaseLabel()`

Using `Node\Expr\MethodCall::class` seems insufficient to the task of identifying chained methods. What should I be using here?

Related question, in a similar case, would it be possible for me in the refactor() method code to investigate the parent node? It'd be nice to see if this was occurring on a call to getEntityType().

**Comment by shaal** [comment]
I'd love to know the answer to that as well

**Comment by TomasVotruba** [comment]
You're doing it right. In chained methods, the `MethodCall->var` is a `MethodCall` node.

> code to investigate the parent node?

You can get parent node easily:

```php
$node->getAttribute(AttributeKey::PARENT_NODE);
```

<br>

If you're exploring Rector, I recommend checking all the attributes available on the node you work with:

```php
dump($node->getAttributes());
```

There might be something useful that you need.

**Comment by TomasVotruba** [comment]
Also, the search on Github is helpful:

https://github.com/rectorphp/rector/search?q=chain+methods&unscoped_q=chain+methods

Check the first service

**Comment by EclipseGc** [comment]
Thanks for the answer, I'll try to put this into practice today. I ask because I'm getting errors when I have chained examples that I don't get with unchained method calls. I'll fetch that error message and come back shortly.

**Comment by EclipseGc** [comment]
Ok, the error I'm running into when trying to address this is as follows:

`[ERROR] Could not process "vendor/palantirnet/drupal-rector/rector_examples/entity_type_getsingularlabel.php" file, due
         to:                                                                                                            
         "Pick more specific node than "PhpParser\Node\Expr\MethodCall", e.g. "$node->name"                             
                                                                                                                        
         Caused in "vendor/palantirnet/drupal-rector/rector_examples/entity_type_getsingularlabel.php" file on line 25  
         on code "$node->getEntityType()"                                                                               
                                                                                                                        
         Look at vendor/palantirnet/drupal-rector/src/Rector/Deprecation/Base/MethodToMethodBase.php:63".`

The code that it's looking at here is line 25 of this file:

`<?php

/**
 * EntityType::getSingularLabel() now handles lower-casing the entity type label; getLowercaseLabel() deprecated.
 */

/**
 * A simple example.
 */
function simple_example() {
  /* @var \Drupal\node\Entity\Node $node */
  $node = \Drupal::entityTypeManager()->getStorage('node')->load(123);
  $entity_type = $node->getEntityType();
  $entity_type->getLowercaseLabel();
}

/**
 * A chained example.
 *
 * Seems like we should support this, but the method chaining errors out.
 */
function chained_example() {
  /* @var \Drupal\node\Entity\Node $node */
  $node = \Drupal::entityTypeManager()->getStorage('node')->load(123);
  $label = $node->getEntityType()->getLowercaseLabel();
}
`

This is using our MethodToMethodBase class: https://github.com/palantirnet/drupal-rector/blob/master/src/Rector/Deprecation/Base/MethodToMethodBase.php

That class is relatively short, but the relevant bit for matching the node type is:

`  /**
     * @inheritdoc
     */
    public function getNodeTypes(): array
    {
        return [
            Node\Expr\MethodCall::class,
        ];
    }`

I don't seem to be making it into my refactor method at all. Is this a sensible problem I'm running into? or am I just confused? Not sure how to make use of your suggestions since I am never getting to the refactor method.

Thanks

**Comment by EclipseGc** [comment]
Ok, I'm wrong. The refactor method IS being executed, I just have 2 copies of the code right now due to how our sandbox is setup and I was commenting out the wrong one. Pushing ahead with what you gave me. I'll try to put some clear docs here for others who follow.

**Comment by EclipseGc** [comment]
After a bit of debugging, I learned that NameResolverTrait::getName() doesn't work on MethodCall or StaticCall. The abstract class we've built attempts to do $this->getName($node->var) which appears dangerous to me since there's no accounting for method chaining in that case which will 100% break this code path all the time.

To solve this in my own testing, I overrode the getName() method on my Deprecation Rector.

```
    public function getName(Node $node): ?string {
        if ($node instanceof \PhpParser\Node\Expr\MethodCall || $node instanceof \PhpParser\Node\Expr\StaticCall) {
            return $this->getName($node->name);
        }
        return parent::getName($node);
    }
```

Doing this made it possible for me to continue executing $this->getName($node->var), however the fix is straight forward enough that I fear there's a good reason the NodeNameResolver is not doing this and I just haven't learned what pitfall I'm not seeing yet.

What am I missing?

**Comment by TomasVotruba** [comment]
This was how Rector behaved in the past.

Yet it the API was confusing. How?

```php
$variable->getName();
```

This is a `MethodCall`. 

When you call `$this->getName($metodCall)`, what should be returned?

- "variable"?
- "getName"?
- "variable->getName?"

Sometimes you need the variable name, sometimes the method name. To remove this magic and prevent confussion, this *hack* was removed.

**Comment by TomasVotruba** [comment]
Closing as original question answered.

**Comment by EclipseGc** [comment]
Thanks for the answer.
