### ISSUE TITLE
__construct() has no argument named "$perClassPropertyToMethods" error

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#358]
I was running it as per readme docs and https://www.reddit.com/r/PHP/comments/82ddpt/the_cakephp_core_team_is_excited_to_announce_the/dvaa8kv/
```
composer require bamarni/composer-bin-plugin --dev
composer bin rector require --dev rector/rector:'dev-master' nikic/php-parser:'4.0.x-dev'

vendor/bin/rector process /src --level cakephp36 --dry-run
```

Yields error:

> [ERROR] Invalid service "Rector\Rector\Dynamic\PropertyToMethodRector": method 
         "__construct()" has no argument named "$perClassPropertyToMethods".    
         Check your service definition. in                                      
         .../app.local/vendor-bin/rector/vendor/symfony/dependency-injection/Compiler
         /ResolveNamedArgumentsPass.php on line 64

**Comment by TomasVotruba** [comment]
Thanks for report :+1: 

There was argument typo in Rector class
