### ISSUE TITLE
ChangeNestedForeachIfsToEarlyContinueRector bug

### ISSUE THREAD

**Issue by derrickschoen** [rectorphp/rector#3580]
# Bug Report

| ChangeNestedForeachIfsToEarlyContinueRector bug | Boolean Operands cause ChangeNestedForeachIfsToEarlyContinueRector to produce code that gives a different output from the original code. |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.34              |
| Installed as   | composer dependency                    |

## Minimal PHP Code Causing Issue
```
<?php
$loaded = true;
$usePackages = true;
$notBad = true;
$partPackageList = [ new \StdClass(), null, 'string', 0, [] ];
$payload = [];

foreach( $partPackageList as $partPackage )
{
    if( ! is_null( $partPackage ) && ! is_object($partPackage) )
    {
        if ($loaded || ($usePackages && $notBad))
        {
            $payload[] = $partPackage;
        }
    }
}
```

https://getrector.org/demo/88a502a5-5c37-4c2c-af8b-63c137cdfb4d
## Expected Behaviour
```
<?php
$loaded = true;
$usePackages = true;
$notBad = true;
$partPackageList = [ new \StdClass(), null, 'string', 0, [] ];
$payload = [];

foreach( $partPackageList as $partPackage )
{
	if (! (
           ! is_null( $partPackage ) && ! is_object($partPackage))
        ) {
		continue;
	}
	if (! (
            $loaded || ($usePackages && $notBad))
        ) {
		continue;
	}
	$payload[] = $partPackage;
}
```

This rector reverses the logic of the code when applied.
See: 
http://sandbox.onlinephpfunctions.com/code/8304e92bbfc483d05136e31b1874d2a9b988c376

Pull request with failing test:
https://github.com/rectorphp/rector/pull/3579

**Comment by derrickschoen** [comment]
This codebase is way over my head.

My best guess to fix it would be to simplify what the rector tries to do.
Make it so that it only tries to wrap the if logic in parenthesis, then negate it, then early continue. 

See the Expected behavior above.

**Comment by TomasVotruba** [comment]
Btw, no need to duplicate PR to extra issue. 

Let's keep it simple at #3579, so we don't have to jump around 2 conversations :D
