### ISSUE TITLE
RepeatedLiteralToClassConstantRector shouldn't create constants named 'CLASS'

### ISSUE THREAD

**Issue by TavoNiievez** [rectorphp/rector#3599]
### RepeatedLiteralToClassConstantRector shouldn't create constants named 'CLASS'

Rector **v0.7.41** Installed as **composer dependency**.

When i run set 'solid', rule 'Rector\SOLID\Rector\Class_\RepeatedLiteralToClassConstantRector' creates **constants** named 'CLASS' which then generate execution errors:

```
PHP Fatal error:  A class constant must not be called 'class'; it is reserved for class name fetching in *file* on line *line_number*.
```

This usually happens in the Symfony form classes.

**Rector should skip** the creation of constants named like that.

**Comment by TomasVotruba** [comment]
Hi, it's hard to guess the code.
We need demo link that shows the broken use case: https://getrector.org/demo

**Comment by TavoNiievez** [comment]
Something like this: [Rector Use Case](https://getrector.org/demo/e77962d3-f989-444d-a463-76636f7278ad)

At top of class rector creates this:

```
/**
 * @var string
 */
private const CLASS = 'class';
```

**Comment by TomasVotruba** [comment]
Demo link is needed

**Comment by TavoNiievez** [comment]
._. I already provided it

> 
> Something like this: [Rector Use Case](https://getrector.org/demo/e77962d3-f989-444d-a463-76636f7278ad)
> 
you can see how Rector changes 'class' to 'self :: CLASS'.

**Comment by TomasVotruba** [comment]
I think we don't understand each other. We don't need piece of code snippet pasted here. 

We need working to demo on Rector website. How to do that?

- Click on this link → https://getrector.org/demo
- Add broken code there
- Click on "Process" button
- Copy  url and paste it here

It should look like this: https://getrector.org/demo/f9782921-32b6-4a0b-a9aa-779506d4ed3a

**Comment by TavoNiievez** [comment]
Oh, excuse me. It's https://getrector.org/demo/cebf75cf-66a0-4ee1-9e1a-59208d9c179a easier to understand?

**Comment by TomasVotruba** [comment]
Yes, that's perfect! Thank you :+1:

**Comment by TomasVotruba** [comment]
Resolved in latest version :+1:
