### ISSUE TITLE
after changes now composer issue

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#361]
Problem 1
    - rector/rector dev-master requires symplify/better-reflection-docblock ^4.0 -> satisfiable by symplify/better-reflection-docblock[4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - rector/rector dev-master requires symplify/better-reflection-docblock ^4.0 -> satisfiable by symplify/better-reflection-docblock[4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for rector/rector dev-master -> satisfiable by rector/rector[dev-master].

so composer update of the installed one doesnt work anymore, cant pull the fixes.

**Comment by dereuromark** [comment]
The vendor-bin composer json just has
```
{
    "require-dev": {
        "rector/rector": "dev-master",
        "nikic/php-parser": "4.0.x-dev"
    }
}
```
I think it should then have the stability flag added

**Comment by dereuromark** [comment]
How do you get

    "minimum-stability": "dev",
    "prefer-stable": true

into that vendor-bin composer json?
Is there some hook involved? This is not the main one here.

But I can confirm that it works then.

**Comment by TomasVotruba** [comment]
I have no idea. I'll probably revert PR for the time being, to prevent these complicatios.
