### ISSUE TITLE
Disappearance of indent

### ISSUE THREAD

**Issue by lBeJIuk** [rectorphp/rector#3617]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector v0.7.41             |
| Installed as   | composer dependency                      |

If after the declaration of the class, after curly brackets, add "//" indentation will be deleted.
![bug](https://user-images.githubusercontent.com/13604404/86092456-ce366000-baad-11ea-866a-f993eeb60048.jpeg)

## Minimal PHP Code Causing Issue
Unfortunately, I can't reproduce the error online.

App.php
```php
<?php

final class BE_R {

  protected $t = 0;
  
  private function __construct() {
    self::init();
  }
  
}

?>
```

Rector.php
```php
<?php
declare(strict_types=1);

namespace Utils\Rector;
use PhpParser\Node\Expr\StaticCall;
use PhpParser\Node;
use Rector\Core\Rector\AbstractRector;
use Rector\Core\RectorDefinition\RectorDefinition;

final class CmRector extends AbstractRector
{
  public function getNodeTypes(): array
  {
    return [StaticCall::class];
  }
  public function refactor(Node $node): ?Node
  {
    return null;
  }
  public function getDefinition(): RectorDefinition
  {
    return new RectorDefinition('test');
  }
}
```

Rector.yaml
```yaml
services:
    Utils\Rector\CmRector: ~
parameters:
    autoload_paths:
        - 'src/App.php'
```

## Expected Behaviour
The indentation will not be altered.

**Comment by TomasVotruba** [comment]
Hi, this by design of abstract syntax tree.

1. Only coding standard can handle these properly, see: https://github.com/rectorphp/rector#how-to-apply-coding-standards

2. For comments *after* the node, they have to be above. In https://github.com/slevomat/coding-standard they have a rule that handle it. I can't find it now.

I recomment removing `//` after  `}` for all nodes, as they have no added value.

**Comment by lBeJIuk** [comment]
Thank you for the answer!
Unfortunately, removing these characters will not pass the code review in my team =).
So I'm just gonna use my hands to revert the changes.

**Comment by TomasVotruba** [comment]
> Unfortunately, removing these characters will not pass the code review in my team =).

Then you need to educate your team about coding standard first :).

I always start with them, when I come to a new project and there none yet.
