### ISSUE TITLE
[RemovingMagic] Defluent rector should handle nested return value

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3619]
Related rule: `Rector\MagicDisclosure\Rector\MethodCall\DefluentMethodCallRector`

<br>

Expected

```diff
-return (new User())->setType(1);
+$user = (new User());
+$user->setType(1);
+return $user
```

**Comment by dobryy** [comment]
We can close this issue according to this fixture:
https://github.com/rectorphp/rector/blob/71247e15877c043fbd2a251e16eb299576b23b2c/rules/magic-disclosure/tests/Rector/MethodCall/DefluentMethodCallRector/Fixture/return_with_new.php.inc

**Comment by TomasVotruba** [comment]
Thanks for confirmation
