### ISSUE TITLE
[RFC] Migration from winzou/state-machine -> symfony/workflow

### ISSUE THREAD

**Issue by stloyd** [rectorphp/rector#3625]
# Feature Request

I would like to start discussion about adding new migration from:
- https://github.com/winzou/StateMachineBundle
- https://github.com/winzou/state-machine

Into the Symfony Workflow component: https://github.com/symfony/workflow

From first look the most of work would be probably on YAML file levels, thus there comes question, it that doable or it would require to much of new logic to be done to cover it properly.

**Comment by TomasVotruba** [comment]
Hi, 

this seems like a big pile of work not useful to the most of PHP community (I never saw this package before). 
It requires bit time investment just to explore what needs to be done and how many custom rules needs to be created.

Saying that, I can accept PR. 
Another option is to handle it as paid work as we do in similar cases.
