### ISSUE TITLE
use statements should not have a leading backslash

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#363]
```
vendor/bin/rector process src/Model/ --level cakephp36 --dry-run
```
results in
```
-use Cake\Network\Exception\ForbiddenException;
+use \Cake\Http\Exception\ForbiddenException;
```

The leading slash is not correct here, or at least not necessary.
I would expect
```
-use Cake\Network\Exception\ForbiddenException;
+use Cake\Http\Exception\ForbiddenException;
```

**Comment by TomasVotruba** [comment]
As coding standards are recommended to run after Rector, this is just detail.

But you're right. If you want to improve this, here is a place to validate presence of parent note that is Use statement:
https://github.com/rectorphp/rector/blob/98fe2891e09dfd92b34da6871131e0a2ba7e21e2/src/Rector/Dynamic/ClassReplacerRector.php#L49

**Comment by dereuromark** [comment]
Fair enough then. I guess the CS should fix this for now.
