### ISSUE TITLE
PHP 7.4 rector converts floats to ints

### ISSUE THREAD

**Issue by melkamar** [rectorphp/rector#3635]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.41 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/b0d03518-e931-4424-aa8b-ca97aa07d473#result

## Expected Behaviour

When there is a float number, such as `5000.0`, rector will convert it to `5_000`, making it an integer. This breaks our tests that use `PHPUnit::assertSame()` and require types to match.

**Comment by TomasVotruba** [comment]
Thanks for great report!
