### ISSUE TITLE
Incompatibility with Nikic PHp Parser 4.6

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#3643]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.41              |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

Run `composer update` and be sure the version 4.6.0 of `nikic/php-parser`.

Then a series of errors will be thrown:

```
PHP Notice:  Undefined property: PhpParser\Node\Param::$flags in /path/to/app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 21
Notice: Undefined property: PhpParser\Node\Param::$flags in /path/to/app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 21
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpParser\PrettyPrinterAbstract::pModifiers() must be of the type integer, null given, called in /path/to/app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 21 and defined in /path/to/app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:1035
Stack trace:
#0 /path/to/app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(21): PhpParser\PrettyPrinterAbstract->pModifiers(NULL)
#1 /path/to/app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pParam(Object(PhpParser\Node\Param))
#2 /path/to/app/vendor/nikic/php-parser/lib/ in /path/to/app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php on line 1035
```

# Suggested fix

In the Rector's `composer.json`, mark as incompatible `nikic/php-parser: 4.6.0`, waiting for a fix by Nikic:

```
"conflict": {
        "nikic/php-parser": "4.6.0"
    }
```

# Workaround

To work around this issue in your own apps and libraries, add this to the `composer.json` file:

```
"conflict": {
        "nikic/php-parser": "4.6.0"
    }
```

This will force Composer to not download the version `4.6.0` that will break the use of Rector.

**Comment by TomasVotruba** [comment]
I think it waits for PHPStan to upgrade to 4.6, as it uses static reflection and prefers its php-parser version.

For now I've locked it to 4.5.

**Comment by Aerendir** [comment]
The new hotfix doesn't solve the problem:

Problem 1
    - Installation request for rector/rector ^0.7.42 -> satisfiable by rector/rector[v0.7.42].
    - rector/rector v0.7.42 requires jetbrains/phpstorm-stubs dev-master#11e2d07705b8b7063a984f49a27d8c3120288e31 -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.

I'm trying with `conflict`.

**Comment by TomasVotruba** [comment]
I've noticed your comment about phpstorm stubs. I accidentaly added prefixed `composer.json`, that has it. My bad.

Should be fixed now in 43
