### ISSUE TITLE
Formatting bug for Doctrine ORM annotations

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#3647]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@0a8bef3             |
| Installed as   | docker latest image                      |

Demo https://getrector.org/demo/3fc3d6bc-177a-45b5-9f58-ec42e7c889f3#result
Analogous problem to https://github.com/rectorphp/rector/issues/3645. 
It looks like it's about spaces. 
In this demo https://getrector.org/demo/3a10ee63-dd81-4a4b-b877-1981bf7734de#result there are no spaces around = sign in `default` option.

This one leads to error like the following:
```php
[Semantical Error] Couldn't find constant default, property MyEntity::$isActive.                            
```

## Expected Behaviour

Rector should not touch it.

**Comment by javaDeveloperKid** [comment]
Checked ECS for rule to remove spaces around `=` and found PhpCsFixer\Fixer\DoctrineAnnotation\DoctrineAnnotationSpacesFixer.
It works for `@Assert\Email(message = "email.email")` and removes spaces but does not work for `@ORM\Column(name="is_active", type="boolean", options={"default" = 1})`, i.e. it does not remove spaces `"default" = 1`. Not cool.

**Comment by TomasVotruba** [comment]
To cover this with test, I usually a fixture here: https://github.com/rectorphp/rector/tree/master/packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture

To the particular directory, based on annotation.

**Comment by TomasVotruba** [comment]
For "default" → default bug is probably responsible method `quoteKeys()`:
https://github.com/rectorphp/rector/blob/3fb42ea7358870075f091963cce41d795c48d446/packages/better-php-doc-parser/src/PartPhpDocTagPrinter/Behavior/ArrayPartPhpDocTagPrinterTrait.php#L103-L116

**Comment by TomasVotruba** [comment]
>  Checked ECS for rule to remove spaces around = and found PhpCsFixer\Fixer\DoctrineAnnotation\DoctrineAnnotationSpacesFixer.
It works for @Assert\Email(message = "email.email") and removes spaces but does not work for @ORM\Column(name="is_active", type="boolean", options={"default" = 1}), i.e. it does not remove spaces "default" = 1. I did set all possible config options to false. Not cool.

Could you make an issue/PR for this in Simplify?
We'll have to implement it ourselves.

**Comment by TomasVotruba** [comment]
I've just found out there is CS rule that might help solve this with few modifications
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2220

**Comment by TomasVotruba** [comment]
Closing as answered
