### ISSUE TITLE
[Naming] Name variable after get/create method

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3656]
```diff
-$value = $this->getSomeValue();
+$someValue = $this->getSomeValue();
```

Based on https://github.com/rectorphp/rector/pull/3653#discussion_r449898288

**Comment by dobryy** [comment]
Reopening to do not forget about `create`, and maybe `resolve`, rule.

**Comment by TomasVotruba** [comment]
Closing as not a priority ATM
