### ISSUE TITLE
[Downgrade] PHP 7.4 to 5.6 set

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3660]
Set for downgrading any code down the PHP version.

Useful for more comfortable development in the latest PHP, while allowing composer install on older PHP versions.

E.g. @phpstan https://github.com/phpstan/phpstan-src/blob/master/bin/transform-source.php from untyped properties

The partial goal might be to run Rector on itself to get to version PHP 5.6  :1st_place_medal: 

## Gradual Steps

- [ ] add Rector to CI here on PHP 5.6 and allow failure

## PHP 7.1 → 7.0

- [ ] move void type to docs

## PHP 7.0 → 5.6

- [ ] move param/return scalar types to docs
- [ ] remove strict_types

**Comment by TomasVotruba** [comment]
Re-opening, as the set is not complete at all.

The goal might be to run Rector on itself, so version running PHP 5.6 is made  :1st_place_medal: 

## Gradual Steps

- add Rector to CI here on PHP 5.6

## PHP 7.1 → 7.0

- move void type to docs


## PHP 7.0 → 5.6

- move param/return scalar types to docs
- remove strict_types

**Comment by staabm** [comment]
It would be great to use such a process to downgrade the requirements for a lib/tool to a older version while the upstream project can require latest php versions.

The process could/should also adjust the composer.json php version requirement, I guess.

**Comment by staabm** [comment]
e.g. some tools of ocramius are not usable for use, because he defines very recent version requirements which do not fit into a world where we need ubuntu lts servers with not so recent libs like php etc

**Comment by TomasVotruba** [comment]
Exactly. I work mostly with newest PHP, so I'm not sure what are the most common blockers to downgrade code.

Could you think of exact steps per each PHP version and extend the list I started?

**Comment by ondrejmirtes** [comment]
I think the main thing you need is to make sure all users are using the PHAR version. This is why I made the switch so that phpstan/phpstan is distributed as PHAR and it's used by everyone, it allows me to have a build step to change the source before releasing.

Otherwise I'd install the dependencies as if they're for PHP 7.4. You then need to run the "downgrade Rector" on vendor too. Also, Symfony polyfills are useful for the missing functions from newer PHP versions.

BTW I think that PHP 5.6 is too ambitious. I'd opt-in for 7.4 -> 7.1 and then maybe 7.0.

**Comment by staabm** [comment]
I might have misinterpreted the initial question:

do we talk about rector recipies which allow me to downgrade other tools from e.g. hpp 7.4 requirement to 7.1 - or do we talk about a lowered version requirement of rector itself?

**Comment by ondrejmirtes** [comment]
I'd guess eventually both.

**Comment by TomasVotruba** [comment]
> do we talk about rector recipies which allow me to downgrade 'any' 

Any. It's general purpose set.

**Comment by TomasVotruba** [comment]
@ondrejmirtes It's not about Rector, but any code. 

> on vendor too

Exactly :+1: 

I think the most problematic feature would be the traits to multiple class inheritance, but that's PHP 5.4 (too far). I'll have to explore domain, seems to simple now.

> BTW I think that PHP 5.6 is too ambitious. 

Thing is, the biggest problem for legacy probjects I get migrate request for are PHP 5.6 to PHP 7.0 jump. It's the biggest gap in the features and also dependency vendor-lock. If you're already on PHP 7.0, it's quite simple to jump to PHP 7.4

**Comment by staabm** [comment]
> Could you think of exact steps per each PHP version and extend the list I started?

I guess one could have a look at the official php docs regarding the migration process
e.g. https://www.php.net/manual/en/migration70.incompatible.php .. not sure it make sense to "support" any incompatbile change though.

regarding the process: I guess one could use a relatively recent framework/component with good testcoverage (e.g symfony), apply the transformation on it and check whether the testsuite still passes on older php versions.

**Comment by TomasVotruba** [comment]
> I guess one could have a look at the official php docs regarding the migration process

That's already ported here in Rector code: https://github.com/rectorphp/rector/tree/master/config/set/php

> not sure it make sense to "support" any incompatbile change though.

:+1: Just those forward compatibility breaking, FC break :).

> with good testcoverage (e.g symfony)

It depends. If the legacy project doesn't use Symfony code at all, it's would be just test for itself.
Test must model reality, where the tool is used.

**Comment by TomasVotruba** [comment]
Already being worked on in practical implementation.

See https://github.com/rectorphp/rector/pull/4447

**Comment by TomasVotruba** [comment]
Rector 0.10 is no successfuly downgraded to PHP 7.1 :heavy_check_mark: :tada: 

<br>

Follow up in https://github.com/rectorphp/rector/issues/6079
