### ISSUE TITLE
Rector failing to run

### ISSUE THREAD

**Issue by Kerrialn** [rectorphp/rector#3666]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.46 |
| Installed as   | composer dependency |
| Phalcon | 3.1 |

Getting an error when running Rector. Tried both, prefixed and non-prefixed versions and got the same error. 

## Minimal PHP Code Causing Issue

rector.yaml as per [cleaning-lady-notes-from-class-mess-to-psr4-step-by-step-with-confidence](https://tomasvotruba.com/blog/2020/07/06/cleaning-lady-notes-from-class-mess-to-psr4-step-by-step-with-confidence/)
```
# rector.yaml 
services:
  Rector\PSR4\Rector\Namespace_\NormalizeNamespaceByPSR4ComposerAutoloadRector: null
  Rector\PSR4\Rector\FileSystem\NormalizeNamespaceByPSR4ComposerAutoloadFileSystemRector: null
```

Console command and output
```
vendor/bin/rector process app                                                                       
 [ERROR] Cannot autowire service "Rector\AttributeAwarePhpDoc\AttributeAwareNodeFactoryCollector": argument             
         "$attributeAwareNodeFactories" of method "__construct()" is type-hinted "array", you should configure its value
         explicitly.      
```                                                                                              
                       
## Expected Behaviour

Expected rector to run.

**Comment by TomasVotruba** [comment]
- How does the output change if you remove these rules?
- And add how does it change if you add `--set php70` to command line?

**Comment by Kerrialn** [comment]
- If I change the rules, same error. 
- If I change the set, same error. 
- If I add default value in the `AttributeAwareNodeFactoryCollector.php` constructor, same error.

**Comment by TomasVotruba** [comment]
I see. Reproducible repository is needed then.

**Comment by Kerrialn** [comment]
I seemed to have an extension active in my php.ini that caused t

**Comment by Kerrialn** [comment]
I can run Rector out side the docker container, but not within it.
