### ISSUE TITLE
Error when comment in comment @ORM annotation

### ISSUE THREAD

**Issue by piotrbelina** [rectorphp/rector#3673]
# Bug Report

Hello, first of all, thanks for creating Rector :)

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector v0.7.47              |
| Installed as   | prefixed Rector PHAR                      |

When having comment word in comment in `@ORM` annotation, it is escaped, although it should not

## Minimal PHP Code Causing Issue

https://getrector.org/demo/c3112beb-a4c0-4634-bfa2-488902b5a8b0

## Expected Behaviour

The line 10 should be left alone.

```php
/**
 * @ORM\Column(name="test", type="string", length=255, nullable=true, options={"comment"="The comment fails"}) 
 */
```

**Comment by jawira** [comment]
Same here. I'm using the **phar** file, version **Rector 0.8.x-dev@8604515**.

This is my **rector.php** file:

```php
<?php declare(strict_types=1);

// Rector configuration file

use Rector\CodingStyle\Rector\Throw_\AnnotateThrowablesRector;
use Rector\Core\Configuration\Option;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(AnnotateThrowablesRector::class);

    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PHP_VERSION_FEATURES, '7.4');
    $parameters->set(Option::EXCLUDE_PATHS, [__DIR__ . '/src/Migrations']);
    $parameters->set(Option::AUTOLOAD_PATHS, [__DIR__ . '/vendor/autoload.php']);
};

```

This is my rectified code:

```diff
    /**
-     * @ORM\Column(type="string", length=2, options={"default" : App\Entity\User::EN})
+     * @ORM\Column(type="string", length=2, options={default=App\Entity\User::EN})
     * @Assert\NotBlank()
     * @Assert\Choice(choices=App\Entity\User::LANGUAGES)
     */
    protected string $language = User::EN;
```
