### ISSUE TITLE
Idea - EntityForDoctrineRepositoryProvider automatic provider 

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#368]
I was thinking about automatization of [this](https://github.com/rectorphp/rector/blob/master/tests/Rector/Architecture/DoctrineRepositoryAsService/Source/EntityForDoctrineRepositoryProvider.php#L13).

What about something like this to automate it?

```php
<?php declare(strict_types=1);

namespace App\Utils\rector;

use Doctrine\ORM\EntityManagerInterface;
use Rector\Contract\Bridge\EntityForDoctrineRepositoryProviderInterface;

final class EntityForDoctrineRepositoryProvider implements EntityForDoctrineRepositoryProviderInterface
{

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
        $this->populateMap();
    }

    /**
     * @var string[]
     */
    private $map = [];

    /**
     * @param string $name
     * @return null|string
     */
    public function provideEntityForRepository(string $name): ?string
    {
        return $this->map[$name] ?? null;
    }

    /**
     * @return array
     * @throws \Doctrine\ORM\ORMException
     */
    private function entities(): array
    {
        return $this->entityManager->getConfiguration()->getMetadataDriverImpl()->getAllClassNames();
    }

    private function populateMap(): void
    {
        foreach ($this->entities() as $entity) {
            $this->map[\get_class($this->entityManager->getRepository($entity))] = $entity;
        }
    }
}
```

Maybe we could add it to rector itself what do you think @TomasVotruba?

**Comment by TomasVotruba** [comment]
How would you configure it in config?
What if sb has different version?

**Comment by mssimi** [comment]
> How would you configure it in config?

I could use some help here, if I knew how to do that, I would create pull request, atm I cannot make it work even with simple provider probably due to #303. I posted it so we can discuss, if we can make it work.

> What if sb has different version?

What is sb?

**Comment by TomasVotruba** [comment]
Sb = somebody (on mobile abroad, so shortcutting :)). Every user can depend on different Doctrine version. So what happens when I use this package with incompatible Doctrine version?

I'm not sure either, since I don't have the code to test on. I thought you've made it work for you code base.

Well, what happens when you register it as service? And go from there.

Using this approach you have to basically register whole Doctrine to Rector, which is crazy. I'd provide simple array instead , using your script in `README` as tip how to get that list.

**Comment by mssimi** [comment]
If we mention that example in README, it may be fine enought:)

> I thought you've made it work for you code base.
No I cannot make it work, autoload issues, I spend 3 hours w/o any progress.

**Comment by TomasVotruba** [comment]
All right, docs it is :+1: 

Autoloader can be solved only PHAR issue, see https://github.com/rectorphp/rector/pull/319

**Comment by TomasVotruba** [comment]
I think #319 is blocker for this right?

**Comment by mssimi** [comment]
Yes.

**Comment by TomasVotruba** [comment]
Blocker #319 is now resolved.

Is this still relevant? If so, please move onward

**Comment by TomasVotruba** [comment]
Closing for no reply for many months, feel free to reopen if relevant enough
