### ISSUE TITLE
Wrong typehint generated by Rector\Php74\Rector\Property\TypedPropertyRector

### ISSUE THREAD

**Issue by ludekbenedik** [rectorphp/rector#3684]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@f5daacc              |
| Installed as   | prefixed Rector PHAR                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1859c889-0c72-4664-b7c6-a3c2bd90825b#result

```php
class ClassA
{
    /** @var string|null */
    private $x;

    public function __construct(?ClassB $b = null)
    {
        if ($b !== null) {
            $this->x = $b->getX();
        }
    }
}

class ClassB
{
    public function getX(): string
    {
        return 'x';
    }
}
```

Use Rector\Php74\Rector\Property\TypedPropertyRector

```php
class ClassA
{
    private string $x;

    public function __construct(?ClassB $b = null)
    {
        if ($b !== null) {
            $this->x = $b->getX();
        }
    }
}
```

## Expected Behaviour

```php
class ClassA
{
    private ?string $x = null;

    public function __construct(?ClassB $b = null)
    {
        if ($b !== null) {
            $this->x = $b->getX();
        }
    }
}
```

**Comment by TomasVotruba** [comment]
Updated PHP Demo link: https://getrector.org/demo/dc6f3048-26b6-4749-9f4d-dccc7cccc861#result

Bug is still there

**Comment by TomasVotruba** [comment]
I'll look into this
