### ISSUE TITLE
Another wrong typehint generated by Rector\Php74\Rector\Property\TypedPropertyRector

### ISSUE THREAD

**Issue by ludekbenedik** [rectorphp/rector#3685]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@f5daac              |
| Installed as   | prefixed Rector PHAR                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/2ee820c5-c32c-459b-b0ef-358ef0b46cc1#result

## Expected Behaviour

```php
class MyClass
{
    private ?string $name = null;

    // ...
}
```

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1:
