### ISSUE TITLE
Comment causes rector to refactor incorrectly and cause syntax errors

### ISSUE THREAD

**Issue by plasticlobster** [rectorphp/rector#3711]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.48              |
| Installed as   | prefixed Rector PHAR                      |

Having a comment before and after the opening brace of an if statement causes the opening brace to be removed from the if statement. EDIT: It also appears the multi-line string has something to do with this. See: https://getrector.org/demo/fd0d3d07-4ac7-4c4b-92f6-902a299016b0#result for another example.

## Minimal PHP Code Causing Issue
```
<?php

    function foo ($id, $a_boolean = false)
    {
        if ($a_boolean) // a comment goes here
        {
            //  another comment goes here
            $sql = "A 
                multi-line
                query";
                $result = db_query($sql);
        }
        return $values;
    }
```
(See the second demo example below for a more functional PHP example that doesn't break dead-code due to missing functions and variables)

https://getrector.org/demo/c632cff7-e023-4fb1-be21-a71af7be69ad#result <-- Broken using phpexcel-to-phpspreadsheet
https://getrector.org/demo/3572ff7a-cc72-4381-8913-68819f6f1ee3#result <-- Also broken using dead-code
https://getrector.org/demo/e31180aa-f0fa-4d79-934c-d499c773e2ef#result <-- Works

## Expected Behaviour
Considering I was trying to run phpexcel-to-phpspreadsheet, I expected no changes to be made to this file. However, it appears even that set is removing empty whitespace characters and seems to be attempting to simplify some code. That said, the expected result is in the third demo URL posted above. No changes should be made to the code, and the comment inside the if block should have no bearing on the parsing.

**Comment by phpfui** [comment]
This is exactly the same issue I had in https://github.com/rectorphp/rector/issues/3639 It appears to be a bug in Rector but not in PhpParser, which correctly parses the code into the correct AST.

Checkout the source code in the issue.  The workaround for now is to change the type of comment in the braces.  Change it from // to /* */ style and it should work.

If I get some more time, I will try to figure out where this is broken, but really annoying, as it breaks good code.

**Comment by plasticlobster** [comment]
@phpfui Unfortunately this isn't all rector changes for us, as we just got started with Rector to attempt to use its phpexcel-to-phpspreadsheet set. However, a good move might be to run the rector phpexcel-to-phpspreadsheet set, then do a `php -l` on all the changed files. The ones that have syntax errors after rector runs are probably due to this issue, and we can kill them. I think in a 200k line codebase, we have 3? instances of this.

Feel free to close this ticket as a dupe of #3639 and I can follow it there.

**Comment by plasticlobster** [comment]
Looks like I can close it myself. It's a dupe of #3639
