### ISSUE TITLE
[PHP7.4] Invalid type with ::class in ORM

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#3716]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest              |
| Installed as   | Docker                      |

## Minimal PHP Code Causing Issue

```php
class Download
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Package::class, inversedBy="downloads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $package;
}
```
getting to
```php
class Download
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\ManyToOne(targetEntity=Package::class, inversedBy="downloads")
     * @ORM\JoinColumn(nullable=false)
     */
    private \Package::class $package;
}
```

## Expected Behaviour

I guess we should just replace `::class`

**Comment by TomasVotruba** [comment]
- Could you provide demo link?
- What is Rector version?
- OS?

**Comment by shyim** [comment]
https://getrector.org/demo/24a6eb87-7be6-4aad-af9e-4a3434dead6e#result

Version: 0.8.x-dev@ae3adef
OS: NixOs (Its wayne its docker)

**Comment by TomasVotruba** [comment]
Interesting. Could you send PR with failing test fixture to the rule?

I can fix it right away then.
