### ISSUE TITLE
[PHP 8.0]

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3728]
ParamTypeDeclarationRector to support union types.

**Comment by TomasVotruba** [comment]
Be sure to check list of rules before proposing: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md

It's done since php-src implementation.

Also there is meta issues for PHP 8.0 features - https://github.com/rectorphp/rector/issues/3127

**Comment by GrahamCampbell** [comment]
It doesn't look like it's implemented. I was looking at that list of rules already, which is why I quoted the name of the rule that needed to be updated: ParamTypeDeclarationRector.

**Comment by TomasVotruba** [comment]
I do control + F, type "Union" and it's 2nd result.

https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#uniontypesrector

What is the difference?

**Comment by GrahamCampbell** [comment]
Why was that implemented as a separate rule, rather than making the existing rule aware of the target php version?

**Comment by GrahamCampbell** [comment]
Why would the existing rule do scalar types, but not union types?

**Comment by TomasVotruba** [comment]
To make intention on upgrade to union type explicit. 

In the hindsight, people don't use generic rules, like move doc to type declaration. But on PHP 8.0 release they want union types, thus separation.

**Comment by TomasVotruba** [comment]
Update of `ParamTypeDeclarationRector` is welcomed :+1: , if not done yet.

**Comment by TomasVotruba** [comment]
Check the tests, it's already done too :wink: 

Try to explore current state before suggesting already implemented features.

**Comment by GrahamCampbell** [comment]
Wait, so why do we even have this union types rector. What is the use case for moving down a union type but not a normal type? Would `Foo|null` be moved but not `?Foo`?
