### ISSUE TITLE
[RFC] Delete UnionTypesRector

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3729]
Replace by making the existing phpdoc to types rector do this, by being aware of the PHP version. Nobody should need to be aware of the concept of a union type being special. It's either "convert the phpdoc types to real types, or not". Knowing if we can convert scalars, nullables or union types should be determined by the target PHP version, and nothing else.

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/issues/3728#issuecomment-659624568

**Comment by GrahamCampbell** [comment]
Hmmm, who are these "people", because I didn't think to search for union types. I wanted to convert param types to genuine types.
