### ISSUE TITLE
DocBlock: Symfony Serializer annotations are removed

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#3743]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | ^0.7.47
| Installed as   | composer dependency |

DocBlock comments that relates to ApiPlatform and to Symfony Serializer are wrongly removed.

```diff
--- Original
+++ New
@@ -44,10 +44,6 @@
     /**
      * @var Collection
      *
-     * @ORM\OneToMany(targetEntity="App\TargetEntity", mappedBy="theClass", cascade={"persist", "remove"}))
-     * @ApiSubresource()
-     * @Groups({"get_the_class", "post_the_class"})
-     * @MaxDepth(1)
-     */
+     * @ORM\OneToMany(targetEntity="App\TargetEntity", mappedBy="theClass", cascade={"persist", "remove"}) */
     private $aCollection;
 }
```

## Minimal PHP Code Causing Issue

Impossible to reproduce on Rector's Demo.

Minimal code required:

```php
<?php

declare(strict_types=1);

namespace App\Business\Entity;

use ApiPlatform\Core\Annotation\ApiSubresource;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;

class TheClass
{
    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="App\TargetEntity", mappedBy="theClass", cascade={"persist", "remove"}))
     * @ApiSubresource()
     * @Groups({"get_the_class", "post_the_class"})
     * @MaxDepth(1)
     */
    private $aCollection;
}
```

The sets enabled are irrelevant: the bug exists independently from the set used. Anyway, I tried enabling only `coding-styles` and enabling only `symfony-phpunit`.

## Expected Behaviour

The DocBlock is left untouched.

## Other info

I tried to reproduce the issue in the demo, but it seems it is fixed in version 8.

I tired to add a failing test case, but I'm not able to reproduce the issue through tests.

I tried to add one to `rector/packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/` but it didn't failed.

I did another try adding a test to https://github.com/rectorphp/rector/blob/v0.7.48/packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/MultilineTest.php and adding the source in https://github.com/rectorphp/rector/tree/v0.7.48/packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source , but, again, I was not able to make it fail (obviously I tried to adjust the test `MultilineTest`, but, again obviously, I did something wrong).

**Comment by TomasVotruba** [comment]
Removing extra )) on first line helps

**Comment by Aerendir** [comment]
@TomasVotruba , It doesn't help! It solved the issue!

Thank you very much! I spent a lot of time trying to debug this issue and alone I would have never spotted the mistyping!

**Comment by TomasVotruba** [comment]
@Aerendir I'm glad it works :+1: 

> I spent a lot of time trying to debug this issue and alone I would have never spotted the mistyping!

I feel you, I've been there too. First it took me like 4 hours to discover it :face_with_head_bandage:  

One would never assume that Doctrine Annotation parser allows such bugs. And there is more to come ;)
