### ISSUE TITLE
Rector\CodeQuality\Rector\Foreach_\ForeachItemsAssignToEmptyArrayToAssignRector incorrect?

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3751]
Consider the example from the docs:

```diff
 class SomeClass
 {
     public function run($items)
     {
         $items2 = [];
-        foreach ($items as $item) {
-             $items2[] = $item;
-        }
+        $items2 = $items;
     }
 }
```

An example as small as `[1 => 1]` shows the refactor is incorrect. Before `$items2` was `[0 => 1]`, but after is `[1 => 1]`.

**Comment by TomasVotruba** [comment]
We need demo link

**Comment by TomasVotruba** [comment]
Actually, in this case a fixture that implements `RunnableInterface` to compare results before and after.

See e.g. https://github.com/derrickschoen/rector/blob/7fc803694636fc8ceef7e178a9c5efbbfa3d78f6/rules/php70/tests/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector/Fixture/fixture.php.inc

**Comment by GrahamCampbell** [comment]
> We need demo link

The code example is copy-pasted from your docs.

**Comment by TomasVotruba** [comment]
Closing as that's not possible to fix without failing test case. Feel free to re-open with PR.

**Comment by GrahamCampbell** [comment]
I gave you a failing test case in the issue...

**Comment by GrahamCampbell** [comment]
> An example as small as [1 => 1] shows the refactor is incorrect. Before $items2 was [0 => 1], but after is [1 => 1].
