### ISSUE TITLE
Rector\CodeQuality\Rector\Foreach_\UnusedForeachValueToArrayKeysRector and antipattern?

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3752]
Can result in code with sub-linear average time complexity being forced to linear, because array_keys is strictly evaluated first, rather than the keys only being considered when needed.

**Comment by TomasVotruba** [comment]
We need demo link

**Comment by TomasVotruba** [comment]
Actually, in this case a fixture that implements `RunnableInterface` to compare results before and after.

See e.g. https://github.com/derrickschoen/rector/blob/7fc803694636fc8ceef7e178a9c5efbbfa3d78f6/rules/php70/tests/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector/Fixture/fixture.php.inc

**Comment by GrahamCampbell** [comment]
A demo link is of **absolutely no relevance** here.

**Comment by TomasVotruba** [comment]
Closing as that's not possible to fix without failing test case. Feel free to re-open with PR.

As I explained in other issues without any reaction.
Locking to prevent futher bikeshedding.

**Comment by GrahamCampbell** [comment]
Your bug issue tempalte doesn't ask for a dekmo link
