### ISSUE TITLE
Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector an antipatern

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3753]
This rule has the effect of deleting type information, general!

**Comment by TomasVotruba** [comment]
We need demo link

**Comment by GrahamCampbell** [comment]
Why, there is not a "bug", as such. The rule just has the effect of deleting type information, say if the original function had a generic type, then is replaced by a closure without the generic return type information. It cannot be recovered.

**Comment by TomasVotruba** [comment]
Closing as without fixture there is nothing we can do.

**Comment by GrahamCampbell** [comment]
I am suggesting you delete it from the code quality rule set. I am not suggesting that you fix it. it cannot be fixed...

**Comment by GrahamCampbell** [comment]
It makes the code quality worse, not better.
