### ISSUE TITLE
Rector\CodeQuality\Rector\Identical\GetClassToInstanceOfRector incorrect in general

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3754]
The reason I complain about this rule is because it is included in the general code-quality ruleset, but I don't think it should be blindly applied to code to "improve quality".

**Comment by TomasVotruba** [comment]
Personal preference is unique by person. To exclude rules form particular sets, see https://github.com/rectorphp/rector#exclude-paths-and-rectors

**Comment by GrahamCampbell** [comment]
I am not saying this is a personal preference. I am arguing that the defaults are bad, and this rule should be opt-in, and not part of the preset.
