### ISSUE TITLE
Rector\CodingStyle\Rector\FuncCall\CallUserFuncCallToVariadicRector incorrect

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3755]
`call_user_func_array($callable, ['foo' => 'bar'])` cannot be replaced by `$callable(...['foo' => 'bar'])`

**Comment by GrahamCampbell** [comment]
The only safe way to do this is if we know the type of the array is "list".

**Comment by TomasVotruba** [comment]
Please stop opening issues without demo link or fixture. They have absolute zero value for fixing it. I've already replied you 3 times the same without any reaction.

Locking to prevent more such issues.
