### ISSUE TITLE
https://github.com/rectorphp/rector/issues/3752

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3756]
I don't think you understood this issue report. There is no **broken code**. The fixer just has the result of slowing down code that could early return. I don't understand why you don't want to discuss this issue.

I suppose I throw away the remaining issues I have collected over the last few days then, if you are not interested.

**Comment by TomasVotruba** [comment]
I answered the issue, the rule can be excluded. 
This goes for any rule for any reason that anyone don't prefer the rule.
