### ISSUE TITLE
Impossible to load rules from sets

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#3758]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.52             |
| Installed as   | composer dependency                      |

It is impossible to run rector using only sets.
It always requires loading some rectors through `services` key.

```console
parameters:
    paths:
        - 'src'
        - 'tests'
    sets:
        # architecture
        - code-quality
Rector v0.7.52
Config file: rector.yaml

PHP Fatal error:  Uncaught Rector\Core\Exception\NoRectorsLoadedException: We need some rectors to run:
* register them in rector.yaml under "services:"
* use "--set <set>"
* or use "--config <file>.yaml"
```

Also the online demo of Rector seems to be broke: go to https://getrector.org/demo/ and try to press "Process" without editing anything: it will return an error message:

> rector.yaml parameters: sets: - 'dead-code'

**Comment by TomasVotruba** [comment]
What happens when you switch config to PHP?

**Comment by Aerendir** [comment]
I didn't tried to switch to PHP: I'm not ready yet.

**Comment by TomasVotruba** [comment]
I don't mean switch, just for debugging purpose

Try removing `rector.yaml` and using this:

```php
// rector.php
use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::SETS, [SetList::CODE_QUALITY]);
};
```

**Comment by TomasVotruba** [comment]
Found a way to fix it.

Still the YAML syntax is deprecated now and will be removed in Rector 0.8

<br>

Switch is matter of 2 bash lines: https://twitter.com/VotrubaT/status/1283003111074922497

**Comment by Aerendir** [comment]
Yes: I just saw your tweet... tomorrow I will try to use migrify 💪🏻
