### ISSUE TITLE
RemoveUnusedAliasRector incorrectly removing a used alias

### ISSUE THREAD

**Issue by u01jmg3** [rectorphp/rector#3764]
# Bug Report

| Subject        | Details             |
| :------------- | :-------------------|
| Rector version | `v0.7.48`           |
| Installed as   | composer dependency |

[`Rector\CodingStyle\Rector\Use_\RemoveUnusedAliasRector`](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#removeunusedaliasrector) is incorrectly removing a *used* alias

```diff
<?php

namespace App\Helpers;

-use Stripe\PaymentIntent as StripePaymentIntent;
+use Stripe\PaymentIntent;

class StripeHelper
{
    public static function createPaymentIntent()
    {
        return StripePaymentIntent::create([
            'receipt_email' => auth()->user()->email,
        ]);
    }
}
```

## Minimal PHP Code Causing Issue

- https://getrector.org/demo/675867b4-7d2a-40cc-9abf-50cb78daa96c
- (Also, there looks to be an issue with the result output on getrector.org warning about switching from the YAML format)

## Expected Behaviour

Rector should *not* be removing the alias as it is in use

**Comment by TomasVotruba** [comment]
Hi, thanks for report :+1:
