### ISSUE TITLE
Issue updating to `v0.7.52`

### ISSUE THREAD

**Issue by u01jmg3** [rectorphp/rector#3767]
# Bug Report

| Subject        | Details             |
| :------------- | :-------------------|
| Rector version | v0.7.52             |
| Installed as   | composer dependency |

Attempted to update Rector to `v0.7.52` to try out my shiny new Rector PHP config but I am getting:

```
ERROR Look at "Rector\Core\Set\SetResolver::resolveSetFileInfoByName()" on line 44
```

Tried to go back to `v0.7.48` which previously worked but now I get:

```
[ERROR] Call to undefined method Symplify\SetConfigResolver\ConfigResolver::resolveSetFromInputAndDirectory()
```

Rector is now broken for me 😢

**Comment by TomasVotruba** [comment]
Could you verify if there is a change in 0.7.53?

**Comment by u01jmg3** [comment]
🎉 working now but complains that the set `laravel` is missing. If you omit, Rector runs.

**Comment by TomasVotruba** [comment]
:+1: 

There is no 'laravel` set, it was probably some magic config typo.

Better use specific sets from `SetList` class

**Comment by u01jmg3** [comment]
https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#laravel?

**Comment by TomasVotruba** [comment]
That's a category name for documentation, not [a set](https://github.com/rectorphp/rector/tree/master/config/set).

**Comment by u01jmg3** [comment]
Ah - I misinterpreted the docs. I see it is versioned which makes sense so `laravel54`.

> _it was probably some magic config typo (that's why we shift from magic YAML to clear PHP)_

Glad this is now a thing of the past!
