### ISSUE TITLE
ForeachItemsAssignToEmptyArrayToAssignRector shoud skip IteratorAggregate

### ISSUE THREAD

**Issue by bohacpetr** [rectorphp/rector#3769]
# Bug Report

`ForeachItemsAssignToEmptyArrayToAssignRector` rwrites foreach over `IterratorAggregate` and returns object (`$this`) instead of array produced by `Generator`

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.0
| Installed as   | composer dependency

## Minimal PHP Code Causing Issue

https://github.com/rectorphp/rector/pull/3768

## Expected Behaviour

Rewrite should be skipped

**Comment by TomasVotruba** [comment]
Btw, no need to duplicate PR and issue.
PR alone is good enough.
