### ISSUE TITLE
rector does not install if phpstan 0.12.33 is installed

### ISSUE THREAD

**Issue by kunalbedi** [rectorphp/rector#3771]
Hi,
rector cannot be installed when phpstan latest version is present

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rector/rector ^0.7.53 -> satisfiable by rector/rector[v0.7.53].
    - rector/rector v0.7.53 requires phpstan/phpstan 0.12.32 -> satisfiable by phpstan/phpstan[0.12.32] but these conflict with your requirements or minimum-stability.

Regards
Kunal Bedi

**Comment by TomasVotruba** [comment]
Hi,

yes, that's due to conflicts with new version.
I have other focus now, so I won't look into it.
