### ISSUE TITLE
Weird behaviour for mysql-to-mysqli set

### ISSUE THREAD

**Issue by skitpl** [rectorphp/rector#3772]
Hi,
Have a test file (name testing.php) with code
```
<?php

mysql_query($sql, $dbx);
$res = mysql_query($sql2, $dbx);

```
Ran the following command
`vendor\bin\rector process testing.php --set mysql-to-mysqli --dry-run`

Produces this output

```
Rector v0.7.53

 5/5 [============================] 100%

1 file with changes
===================

1) testing.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -1,4 +1,4 @@
 <?php

-mysql_query($sql, $dbx);
-$res = mysql_query($sql2, $dbx);
+mysql_query($dbx, $sql);
+$res = mysqli_query($res, $dbx, $sql2);
    ----------- end diff -----------


Applied rules:

 * Rector\Core\Rector\Argument\SwapFuncCallArgumentsRector
 * Rector\MysqlToMysqli\Rector\FuncCall\MysqlQueryMysqlErrorWithLinkRector
 * Rector\Renaming\Rector\Function_\RenameFunctionRector
```

The code is wrong 
$res = mysqli_query($res, $dbx, $sql2);

Why $res is made a part of the argument list for mysqli_query when the function has originally two variables only.

Please do check and advise.

Regards
Kunal Bedi

**Comment by TomasVotruba** [comment]
Hi, 

what is expected output code?

**Comment by kunalbedi** [comment]
Hi,
Thanks for getting back so quickly.

The expected output is:

```
<?php

mysql_query($sql, $dbx);
$res = mysql_query($dbx, $sql2);


```

Basically the line:
`
$res = mysql_query($sql2, $dbx);

`
Should become:
`
$res = mysql_query($dbx, $sql2);

`

but the output is taking the assigned variable of the statement **$res** and putting it in the function call as a first parameter while also swapping the two original variables like it should and giving:

**$res = mysqli_query($res, $dbx, $sql2);**

**This is absolutely wrong as mysqli_query() function only take two parameters mysqli_query($db-link, $sql-statement)**.

My dev environment is:
Windows 10
Latest composer
rector/rector current version

Looking forward to hearing from you.

Regards
Kunal Bedi

**Comment by kunalbedi** [comment]
Just edited some obvious errors in my message above. Had forgotten to take coffee before writing it in. LOL
Thank you Tomas for being so prompt.

**Comment by TomasVotruba** [comment]
I'm not sure when I get to it. 

What rule is actually causing it? It should be in the Rector output, under the changed code.

**Comment by TomasVotruba** [comment]
My guess it's related to one of these 2 lines:

- https://github.com/rectorphp/rector/blob/712811c8969e4eec13494c4a7f8172146f5ec138/rules/mysql-to-mysqli/src/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector.php#L99
- https://github.com/rectorphp/rector/blob/39bd17f96f1509fc7e2c76a906cec0bc900b87ab/config/set/mysql-to-mysqli.php#L32

You can try to debug it locally, change those lines and see what happens.

**Comment by kunalbedi** [comment]
Hi,

Applied rules:

 * Rector\Core\Rector\Argument\SwapFuncCallArgumentsRector
 * Rector\MysqlToMysqli\Rector\FuncCall\MysqlQueryMysqlErrorWithLinkRector
 * Rector\Renaming\Rector\Function_\RenameFunctionRector

These is what rector reports.

**Comment by kunalbedi** [comment]
I will try to debug as per your input

**Comment by jjthiessen** [comment]
This should be solved by https://github.com/rectorphp/rector/pull/4119

**Comment by TomasVotruba** [comment]
Thanks :+1:
