### ISSUE TITLE
New Rector for utilising short echo tags

### ISSUE THREAD

**Issue by u01jmg3** [rectorphp/rector#3783]
# Feature Request
 
## Diff 

Before I go any further, I wondered whether you would be interested in a Rector that produces the following:

```diff
-<?php echo 'Hello World!'; ?>
+<?= 'Hello World!'; ?>
```

If you are interested, do you _a)_ know how to produce the `<?=` tag using PHP Parser and _b)_ know how to check that `echo 'Hello World!';` is the only expression between the opening and closing tags?

I just need to be pointed in the right direction 😉

---

Here is a post that discusses the pros/cons for using `<?=`: https://softwareengineering.stackexchange.com/questions/151661/is-it-bad-practice-to-use-tag-in-php

**Comment by TomasVotruba** [comment]
Since PHP 7.4 there is trend to remove short tags:
https://wiki.php.net/rfc/deprecate_php_short_tags_v2

We can assume this would continue so promoting it would give people more work with upgrades later.

---

This feature cannot be handled by Rector, as opening/closing tag is not part of AST. 
I recommend looking at php-cs-fixer

**Comment by u01jmg3** [comment]
> [_The <?= combined opening and echo tag is not controlled by short_open_tag. It is always available, and will continue to be always available after this RFC._](https://wiki.php.net/rfc/deprecate_php_short_tags_v2#:~:text=The%20%3C%3F%3D%20combined%20opening%20and%20echo%20tag%20is%20not%20controlled%20by%20short_open_tag.%20It%20is%20always%20available%2C%20and%20will%20continue%20to%20be%20always%20available%20after%20this%20RFC.)

> [_Short open tags <? will be removed. <?= continues to always be available._](https://wiki.php.net/rfc/deprecate_php_short_tags_v2#backward_incompatible_changes:~:text=Short%20open%20tags%20%3C%3F%20will%20be%20removed.%20%3C%3F%3D%20continues%20to%20always%20be%20available.)

Thanks for the info. For now, it looks like the RFC doesn't negatively affect the use of `<?=` but perhaps that could change.

---

> _This feature cannot be handled by Rector, as opening/closing tag is not part of AST.
I recommend looking at [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)._

👌

**Comment by TomasVotruba** [comment]
I'm just curious, why do you personally prefer <?/<?= over classic tags? 

I've never used them in my last 17 years, so I wonder what are the reasons for people who do.

**Comment by u01jmg3** [comment]
Purely a preference thing. Why write `<?php echo 'x' ?>` when you can write something shorter and more concise `<?= 'x' ?>`. It's very similar to the [TernaryToElvisRector](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#ternarytoelvisrector). Shorter syntax for the same thing.

Obviously doesn't apply to Laravel applications because of [Blade templating](https://laravel.com/docs/5.0/templates#other-blade-control-structures:~:text=Echoing%20Data). Mainly applies to CodeIgniter and legacy code.

**Comment by TomasVotruba** [comment]
Ah, you use CodeIgniter nowadays? Cool. I don't know many people using it.

**Comment by u01jmg3** [comment]
Moving away from CodeIgniter in preference of Laravel but still have to support CodeIgniter until everything has moved. Meanwhile trying to keep the codebase tidy and concise.

**Comment by TomasVotruba** [comment]
Undrestood, that makes sense :+1: Would you be open to publish scripts that help you with such migration? 

I feel there will be lot of migrations from Zend/Codeigniter/Phalcon to Laravel/Symfony frameworks

**Comment by u01jmg3** [comment]
We start from scratch reintroducing functionality as new rather than porting over any old code. Therefore, there aren't any "publish scripts" - sorry! The legacy code is just too old and not well written. Better starting from fresh.

**Comment by TomasVotruba** [comment]
Good luck with the migration. The first steps are the hardest, but it gets easier along
