### ISSUE TITLE
PHPStan rules remove docblock comments when it should not

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#3804]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.54              |
| Installed as   | composer dependency                      |

```diff
--- Original
+++ New
@@ -185,9 +185,6 @@

         /**
          * Search in the deeper levels of the array.
-         *
-         * @var int|string $key
-         * @var mixed $value
          */
         foreach ($array as $value) {
             // If this value is an array...
```

The demo doesn't work as it requires the config in PHP while it is currently in yaml.

Anyway, the demo code is there: https://getrector.org/demo/b0eb4bdb-b2a6-4666-a9d5-3e6ff68e18f8

## Expected Behaviour

The Docblock comments are not removed.

**Comment by TomasVotruba** [comment]
Why closed?

**Comment by Aerendir** [comment]
It wasn't an error: there is no key set in the foreach.

**Comment by Aerendir** [comment]
But maybe the $value annotation should not be removed 🤔 but there is no rector applied.

It is something related to pho doc parser I imagine.

**Comment by TomasVotruba** [comment]
What's the added value of `mixed` type in that caes?

**Comment by Aerendir** [comment]
@TomasVotruba I think I added it because of complaints of some static analysis tool.

**Comment by TomasVotruba** [comment]
I see
