### ISSUE TITLE
ChangeReadOnlyPropertyWithDefaultValueToConstantRector wrongly creates variables and constants

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#3810]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.54              |
| Installed as   | composer dependency                      |

```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -22,7 +22,7 @@
  */
 final class Validator
 {
-    private $schemas = ['1.2'];
+    private const SCHEMAS = ['1.2'];
     /** @var array */
     private $errors = [];

@@ -97,7 +97,8 @@
      */
     private function getSchema(?string $schemaVersion): string
     {
-        $schemaVersion = $schemaVersion ?? end($this->schemas);
+        $self::SCHEMAS = self::SCHEMAS;
+        $schemaVersion = $schemaVersion ?? \end($self::SCHEMAS);
         $finder        = new Finder();
         $iterator      = $finder->name($schemaVersion . '.xsd')->in(__DIR__ . DIRECTORY_SEPARATOR . '../Schemas')->getIterator();
         $iterator->rewind();
    ----------- end diff -----------
```

~~Caused by: `Rector\SOLID\Rector\Property\ChangeReadOnlyPropertyWithDefaultValueToConstantRector`~~

Applied rules:

 * Rector\Core\Rector\Argument\ArgumentAdderRector
 * Rector\Core\Rector\Argument\ArgumentDefaultValueReplacerRector
 * Rector\Core\Rector\Argument\ArgumentRemoverRector
 * Rector\Core\Rector\Argument\SwapFuncCallArgumentsRector
 * Rector\Core\Rector\ClassMethod\WrapReturnRector
 * Rector\Core\Rector\FuncCall\RemoveFuncCallArgRector
 * Rector\MysqlToMysqli\Rector\FuncCall\MysqlFuncCallToMysqliRector
 * Rector\MysqlToMysqli\Rector\FuncCall\MysqlQueryMysqlErrorWithLinkRector
 * Rector\Php54\Rector\FuncCall\RemoveReferenceFromCallRector
 * Rector\Php70\Rector\FuncCall\NonVariableToVariableOnFunctionCallRector
 * Rector\Php70\Rector\FuncCall\RandomFunctionRector
 * Rector\Renaming\Rector\Annotation\RenameAnnotationRector
 * Rector\Renaming\Rector\Function_\RenameFunctionRector
 * Rector\SOLID\Rector\Property\ChangeReadOnlyPropertyWithDefaultValueToConstantRector

The proposed change is not correct.

PHP (via PHPStorm) complains about it:

> Only variables can be passed by reference

## Minimal PHP Code Causing Issue

Demo (not working due to the yaml config): https://getrector.org/demo/b5fb1b21-4008-44aa-9a13-f34b93e95060
## Expected Behaviour

There are various alternatives:

1. Assign the value of the constant to a variable correctly named
2. Don't change the array into a constant (I suppose really really complex to achieve)

In case one, the diff should be this (assuming the rule is already applied):

```diff
     private function getSchema(?string $schemaVersion): string
     {
-        $self::SCHEMAS = self::SCHEMAS;
+        $schemas = self::SCHEMAS;
-        $schemaVersion = $schemaVersion ?? \end($self::SCHEMAS);
+        $schemaVersion = $schemaVersion ?? \end($schemas);
         $finder        = new Finder();
         $iterator      = $finder->name($schemaVersion . '.xsd')->in(__DIR__ . DIRECTORY_SEPARATOR . '../Schemas')->getIterator();
         $iterator->rewind();
```

As you can see, in fact, the generated variable `$self::SCHEMAS` is anyway not correct syntactically.

**Comment by Aerendir** [comment]
UPDATE

It seems that simply excluding `Rector\SOLID\Rector\Property\ChangeReadOnlyPropertyWithDefaultValueToConstantRector::class` doesn't work, so the problem is elsewhere.

I've update the first comment to include the full stack of applied rectors.

**Comment by TomasVotruba** [comment]
Thanks for great report :+1:

**Comment by TomasVotruba** [comment]
Updated demo link with PHP config: https://getrector.org/demo/3c066449-1b75-4a56-9461-ae107fd1c79f#result
