### ISSUE TITLE
Unsound foreach to assignment conversion

### ISSUE THREAD

**Issue by raoz** [rectorphp/rector#3812]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.54            |
| Installed as   | composer dependency                     |

## Minimal PHP Code Causing Issue
https://getrector.org/demo/0b2a71e9-6f4c-484b-a9a0-3d427f421016#result

```php
 <?php
 $arr = [];
 foreach ($a as $b) {
-        foreach ($b->getC() as $c) {
-                 $arr[] = $c;
-         }
+        $arr = $b->getC();
 }

```
Applied rules:

 * Rector\CodeQuality\Rector\Foreach_\ForeachItemsAssignToEmptyArrayToAssignRector

## Expected Behaviour
Perhaps array_merge would be the correct behaviour, but the current one is clearly wrong.

**Comment by TomasVotruba** [comment]
Thanks for reporting.

Could you share me an expected behavior with snippet from https://3v4l.org/?
So we have it verified

**Comment by raoz** [comment]
Original:
https://3v4l.org/QZNdR
Rector output (changes behaviour):
https://3v4l.org/DBtF5
Perhaps best:
https://3v4l.org/JCC71

**Comment by HenkPoley** [comment]
Saw something similar:

```diff
@@ -159,10 +160,7 @@
             ],
         ]);

-        /** @var array $log */
-        foreach ($logResponse as $log) {
-            $performanceDataResult[] = $log;
-        }
+        $performanceDataResult = $logResponse;

         return \response($performanceDataResult);
     }
```

I think here `array_values(performanceDataResult)` would have been a more appropriate result.

**Comment by TomasVotruba** [comment]
Failing test fixture for `ForeachItemsAssignToEmptyArrayToAssignRector` is needed

**Comment by TomasVotruba** [comment]
Failing test fixture for `ForeachItemsAssignToEmptyArrayToAssignRector` is needed

**Comment by samsonasik** [comment]
It seems already fixed in latest master, see https://getrector.org/demo/b57255b6-1ad1-4dcd-95ec-5bf7a558a4a7#result
