### ISSUE TITLE
unsound conversion from identity check with false to negation

### ISSUE THREAD

**Issue by raoz** [rectorphp/rector#3813]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.54                 |
| Installed as   | composer dependency                    |

## Minimal PHP Code Causing Issue
```php
<?php

$a = @file_get_contents('test.txt');
if ($a === false) {
    echo "file not found\n";
} else {
    echo $a;
}

```
gets converted to 
```php
<?php
$a = @file_get_contents('test.txt');
if (!$a) {
    echo "file not found\n";
} else {
    echo $a;
}

```
(which differ if `test.txt` is an empty file)
## Expected Behaviour

This should probably be skipped any time there is a === instead of ==, as ! coerces like ==.

**Comment by raoz** [comment]
On a further look, the rule is Rector\CodingStyle\Rector\Identical\IdenticalFalseToBooleanNotRector, which is explicitly for ===. It checks if it result of a function returning an integer or false, but that is not sufficient. Probably the correct behaviour would be to check if the only possible type is boolean.

**Comment by TomasVotruba** [comment]
I see. Could you send PR with failing test fixture?

**Comment by TomasVotruba** [comment]
Closing as stale
