### ISSUE TITLE
[docs] Complete info about util service to build Rectors

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#382]
Good point! Asked by @mssimi on meetup in Brno

It would make them easier to use and combine, rather than search in every class manually

**Comment by TomasVotruba** [comment]
@mssimi What exactly would you like to describe here? I'm not sure what to include since I personally know most of them.

Could you prepare PR to chat over?

**Comment by mssimi** [comment]
Well I wanted to make auto generator from definition, but fails for rectors where interface needs to be implemented. I suggested decouple definition from rector, you suggested providing default implementations:)

**Comment by TomasVotruba** [comment]
Could you hide that one for now, so it's not blocker for this?

**Comment by TomasVotruba** [comment]
For example:

![image](https://user-images.githubusercontent.com/924196/39399712-24995c74-4b23-11e8-925f-07dbf2df651b.png)
