### ISSUE TITLE
AddDefaultValueForUndefinedVariableRector incorrectly duplicating a variable that already exists

### ISSUE THREAD

**Issue by u01jmg3** [rectorphp/rector#3828]
# Bug Report

| Subject        | Details             |
| :------------- | :-------------------|
| Rector version | `v0.7.55`           |
| Installed as   | composer dependency |

[`Rector\Php56\Rector\FunctionLike\AddDefaultValueForUndefinedVariableRector`](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#adddefaultvalueforundefinedvariablerector) is duplicating a variable that already exists

```diff
<?php
    
namespace ICal;

class ICal
{
    protected function processEvents()
    {
        $checks = null;
+       $checks = null;
        $events = [];

        foreach ($events as $event) {
            $checks[] = true;

            unset($checks);
        }
    }
}
```

## Minimal PHP Code Causing Issue

- https://getrector.org/demo/7b175930-13d6-4fbc-9e4b-9377c22b6aff
- (Also, there looks to be an issue with the result output on getrector.org warning about switching from the YAML format)

## Expected Behaviour

Rector should not be duplicating a variable that is already present

**Comment by TomasVotruba** [comment]
Thanks for great report!

Could you add pull-request with test fixture to `AddDefaultValueForUndefinedVariableRectorTest`?

**Comment by u01jmg3** [comment]
Done 👍
