### ISSUE TITLE
Chain of methods replacer rector

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#3843]
# Question

Hey, I was just looking into all rectors documented and I cannot find a way how to replace chain of methods, is there any way or there is no rector that can do that so far?

Example:

Before
```php
final class Car
{
    private CarType $carType;
    
    public function getCarType() :CarType
    {
        return $this->carType;
    }
}

final class CarType
{
    private string $type;

    public function getType(): string
    {
        return $this->type;
    }
}

final class SomeClass
{
    public function something()
    {
        $car = new Car();
        $car->getCarType()->getType();
    }
}
```

After:

```php
final class Car
{
    private string $type;
    
    public function getType() :string
    {
        return $this->type;
    }
}

final class SomeClass
{
    public function something()
    {
        $car = new Car();
        $car->getType();
    }
}
```

Does not even have to remove CarType class and replace attribute in Car class, as that is simple, I am just looking for way how to refactor all `$car->getCarType()->getType()` to `$car->getType()`.

**Comment by TomasVotruba** [comment]
Hey, thanks for code example!

I'm just working on it :D 

There should be some "defluent" rule, but not sure how well it works.

https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#defluentmethodcallrector

**Comment by TomasVotruba** [comment]
I look closely now and it seems like there is a method removed completely. 

This seems like refactoring to me, that is handled much better by PHPStorm. Rector doesn't have good tooling for such refactoring. Yet, I'd like to know more about your idea.

How would Rector know what method should removed?

How would rule configuration look like?

**Comment by mssimi** [comment]
I am trying to implement it myself, but I am stuck, if you can help me, I can submit MR

```php
    /**
     * @return string[]
     */
    public function getNodeTypes(): array
    {
        return [MethodCall::class];
    }

    /**
     * @param MethodCall $node
     */
    public function refactor(Node $node): ?Node
    {
        foreach ($this->methodCallRemoverArgument as $className => $methodName) {
            if (! $this->isObjectType($node->var, $className)) {
                continue;
            }

            if ($node->name->name !== $methodName) {
                continue;
            }

            return new Variable('this'); 
        }

        return $node;
    }
```

I have problem with line `return new Variable('this'); `, I don't know how to retrieve variable name that is before method call.

Example:
$this->getCarType()->getType() to $this->getType() works as I want
$car->getCarType()->getType() to $this->getType() does not, coz it should result in $car->getType() and I have no idea how to get variable name, so I can't refactor that correctly.

**Comment by TomasVotruba** [comment]
If you're able to send PR with failing test case, I might give you more direct feedback on it.

**Comment by mssimi** [comment]
Actually I have no idea how to do safely this kind of refactoring in PHPStorm, while I am quite close to do that with rector, beside refactor already has pretty similar rules.

This [rector](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#servicelocatortodirector) for example replaces method call with property fetch, I just want to remove that instead replacing with property fetch.
