### ISSUE TITLE
Which filters were applied?

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector#3844]
# Question
Hello all,

I didn't find where I can see which filters have been applied after running a `process --dry-run` command. I see the git diff but if I don't want a specific change (=one rule), where can I retrieve his name so I can exclude it...

The `--debug` option is telling '[applying] ...` for, I think, all scanned rules... (if my understanding is correct, applying is more "scanning" or "checking" no?)

(concretely, I desired to retrieve the name of the rule that cause the addition of the `use stdClass` line so I can exclude it but my question is more global; for all applied rules)

```txt

    ---------- begin diff ----------
--- Original
+++ New
 <?php
+use stdClass;

     /**
     * [...]
      */
-    public static function get(\stdClass $request, string $prefix = ''): array
+    public static function get(stdClass $request, string $prefix = ''): array
     {
    ----------- end diff -----------

 [OK] Rector is done! 1 file would have changed (dry-run).
```

Many, many thanks.

**Comment by TomasVotruba** [comment]
Hi, this is not any filter, but rather auto import. 

It's generic feature that stands outside the rules:
https://github.com/rectorphp/rector#import-use-statements

**Comment by cavo789** [comment]
**Thank you @TomasVotruba** 

It explains why I can see the "Applied filter is ..." here.
