### ISSUE TITLE
rector.php - Whitelisting several rules at once.

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector#3846]
# Question

I'm very new to rector (which is an amazing tool) and I would like to have two scripts; the first will be "just do it" i.e. I'll run rector and I wish that some rules will be applied directly. The second script will be fired with "--dry-run" so I can visually see the differences and apply them or not.

For the first script, I'm writing my `rector.php` file with a list of whitelisted rules.  Below part of that file.
And I doubt about the syntax : can I code multiple `$services->set()` statements or should I do made only one with an array of classes, ...

**Thanks.**

```php
use Rector\Core\Configuration\Option;
use Rector\CodeQuality\Rector\Concat\JoinStringConcatRector;
use Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector;
use Rector\Order\Rector\Class_\OrderPrivateMethodsByUseRector;
use Rector\Order\Rector\Class_\OrderPropertyByComplexityRector;
use Rector\CodingStyle\Rector\String_\SymplifyQuoteEscapeRector;
use Rector\Order\Rector\Class_\OrderPublicInterfaceMethodRector;
use Rector\Performance\Rector\FuncCall\PreslashSimpleFunctionRector;
use Rector\CodeQuality\Rector\Catch_\ThrowWithPreviousExceptionRector;
use Rector\CodingStyle\Rector\Catch_\CatchExceptionNameMatchingTypeRector;
use Rector\DeadCode\Rector\Property\RemoveNullPropertyInitializationRector;
use Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    // [ ... ]

    $services = $containerConfigurator->services();

    $services->set(IntvalToTypeCastRector::class);
    $services->set(JoinStringConcatRector::class);
    $services->set(PreslashSimpleFunctionRector::class);
    $services->set(SymplifyQuoteEscapeRector::class);
    $services->set(RemoveNullPropertyInitializationRector::class);
    $services->set(ThrowWithPreviousExceptionRector::class);
    $services->set(CatchExceptionNameMatchingTypeRector::class);
    $services->set(OrderPrivateMethodsByUseRector::class);
    $services->set(OrderPropertyByComplexityRector::class);
    $services->set(OrderPublicInterfaceMethodRector::class);
    $services->set(ThisCallOnStaticMethodToStaticCallRector::class);

    // [ ... ]
};

```

**Comment by TomasVotruba** [comment]
Hi,

we're using Symfony config here. So you can use anythign in that scope.
I'm not aware of different syntax.

**Comment by cavo789** [comment]
For the second time, thank you Tomas.

Your confirmation helped me understand where my problem was (it seemed to me that the rules weren't being fired) : in my `rector.php` file I had this option set:

```php
$parameters->set(
        Option::PATHS,
        [
            getcwd() . '/src',
            getcwd() . '/tests'
        ]
    );
```

So I've thought it wasn't need to specify the `src` folder when running the batch `%APPDATA%\composer\vendor\bin\rector.bat process --config=config\rector-safe.php`  but, no, it doesn't work like that, I should specify the folder on the command line : `%APPDATA%\composer\vendor\bin\rector.bat process --config=config\rector-safe.php src` (then a second call for the `tests` folder).

Thank you for your precious help.

**Comment by TomasVotruba** [comment]
You're welcome :+1: 

I'm glad you found a way that works for you
