### ISSUE TITLE
Update to php-parser 4.0.1 with new builder methods

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#385]
https://github.com/nikic/PHP-Parser/releases/tag/v4.0.1

**Comment by carusogabriel** [comment]
@TomasVotruba I'll do it tonight. We'll have to deal with composer `require` section as #330 wasn't finish yet, but should be easy :smile:

**Comment by TomasVotruba** [comment]
I thought you'd like it :+1: 

It doesn't depend necessarily, this should be enough:

```json
    "nikic/php-parser": "v4.0.1 as 4.0.x-dev"
```

**Comment by TomasVotruba** [comment]
Any updates on this?

**Comment by carusogabriel** [comment]
Gonna push these changes tonight

**Comment by carusogabriel** [comment]
@TomasVotruba The idea is to remove some methods from `NodeFactory` and use `BuilderFactory` as a dependency?

**Comment by TomasVotruba** [comment]
Yes, delegate code we don't need to maintain

**Comment by carusogabriel** [comment]
@TomasVotruba Perfect, I'll code it :man_technologist:
