### ISSUE TITLE
TypeError in ValueResolver::resolveClassConstFetch()

### ISSUE THREAD

**Issue by fsok** [rectorphp/rector#3851]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@efa35bb              |
| Installed as   | composer dependency                   |

Rector exits with a TypeError when evaluating a non string class constant.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/37fb8161-2a26-442a-ae69-1ac8384808a5#result

## Expected Behaviour

No exception thrown.

**Comment by TomasVotruba** [comment]
Hi, 

thanks for reporting. Looks like this line: https://github.com/rectorphp/rector/blob/3aa2fc87276b8af4021ef30e45ef52b9b51b96ed/src/PhpParser/Node/Value/ValueResolver.php#L194

If return type is changed to anything, it should work. Could you confirm?

```diff
+   /**
+    * @return mixed
+    */  
-   private function resolveClassConstFetch(ClassConstFetch $classConstFetch): string
+   private function resolveClassConstFetch(ClassConstFetch $classConstFetch)
```

**Comment by fsok** [comment]
yes, I can confirm. it works without return type / mixed return type.

**Comment by TomasVotruba** [comment]
Great! Thanks. 

Could you send it as pull-request change here?
