### ISSUE TITLE
A big thank you to all contributors!

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector#3873]
Thank you for this amazing tool that is rector.

We can say that it is a fabulous tool, we can say that the support is just incredible, we can also marvel at the number of rules and their relevance.

Rector makes it possible to make evolve rather quickly an old codebase towards a more modern solution (from php 5.3 to php 7.3 for example).

I would like to thank the developers and contributors to this wonderful project who are like a good friend, who look at our source code with a friendly eye and who propose this or that code improvement.

Rector is not just a tool but a coach who helps us understand some of our bad habits and keeps us up to date with the evolution of the PHP language ("Did you know my friend that today it is possible to do like this?").

Thank you for this coach.

**Comment by TomasVotruba** [comment]
You're welcome. Thank you for such a detailed nice words :heart: 
It means a lot to me see how exactly my daily work brings good to others.

> Rector is not just a tool but a coach who helps us understand some of our bad habits and keeps us up to date with the evolution of the PHP language 

Nailed it :clap:
