### ISSUE TITLE
Unexpected return type added

### ISSUE THREAD

**Issue by genesiscz** [rectorphp/rector#3880]
# Bug Report
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.61, dev-master,  dev-master@2bd1eac   |
| Installed as   | composer dependency    |                 
## Minimal PHP Code Causing Issue

```php
<?php
namespace App;
if (! function_exists('route')) {
    /**
     * Generate the URL to a named route.
     *
     * @param  array|string  $name
     * @param  mixed  $parameters
     * @param  bool  $absolute
     * @return string
     */
    function route($name, $parameters = [], $absolute = true)
    {
        if ($name) {
            return $name;
        }
        throw new Exception();
    }
}
class Authenticate
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return route('login');
        }
    }
}
```
https://getrector.org/demo/4c5eba96-f60e-4971-ba59-dd89aae2c08a#result

## Expected Behaviour

Skipping based on function behavior. Function route is a Laravel function but shouldn't probably be the cause since it is in if statement and it's calling could be skipped, yielding in no return/void I guess?
I know the PHPDoc is kinda not stating void and is wrong, but it's generated by the Framework (again wrongly, probably based on older versions of PHP), but shouldn't the rector work on behaviour more than on PHPDoc here? Is there a way to go around it?

**Comment by genesiscz** [comment]
Oh and wait, even doing 

```diff
-* @return string|null
+* @return string|null|void
```

doesn't solve the problem.

**Comment by TomasVotruba** [comment]
Thank for reporting, I'm working on a fix
