### ISSUE TITLE
[Order] Order first level Class statements

### ISSUE THREAD

**Issue by dobryy** [rectorphp/rector#3890]
# Feature Request

## Diff 

```diff
- private $variable;
- public const SOME_CONST = 'value';
- public function publicFunctionName();
- use SomeTrait;
+ use SomeTrait;
+ public const SOME_CONST = 'value';
+ private $variable;
+ public function publicFunctionName();
```

**Comment by cavo789** [comment]
For info, php-cs-fixer has an option for this: https://github.com/FriendsOfPHP/PHP-CS-Fixer. Take a look to the different **order_xxx** options.

**Comment by TomasVotruba** [comment]
Thanks. We used that before, but we're doing much more related ordering in Rector, e.g. order private method by their call order.
It more logical than syntactical, so AST is better for these than tokens.

**Comment by TomasVotruba** [comment]
Closing as finished
