### ISSUE TITLE
RenamePropertyToMatchTypeRector issue

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#3897]
# Bug Report RenamePropertyToMatchTypeRector

Rector version: v0.7.61
Installed as composer dependency

**Vendor interface**

```php
namespace Some\Vendor\Namespace;

interface SomethingInterface 
{
    public function doSomething(Request $req): void;
}
```

**Before RenamePropertyToMatchTypeRector**

```php
namespace App\Service;

use Some\Vendor\Namespace\SomethingInterface;

final class Something implements SomethingInterface 
{
    public function doSomething(Request $req): void {
        // ...
    }
}
```

**After RenamePropertyToMatchTypeRector**

```php
namespace App\Service;

use Some\Vendor\Namespace\SomethingInterface;

final class Something implements SomethingInterface 
{
    public function doSomething(Request $request): void {
        // ...
    }
}
```

**Expected Behaviour**

Keep it as is. RenamePropertyToMatchTypeRector must not rename properties of methods that are implementation of vendor interface, as it will break code.

**Comment by TomasVotruba** [comment]
Demo link with failing code or failing test case is needed

**Comment by mssimi** [comment]
I just gave you example that breaks it. **SomethingInterface** is vendor code, variables can't be changed just like that in your app.

**Comment by mssimi** [comment]
I have updated example in original msg, but point is simple, RenamePropertyToMatchTypeRector must not rename properties that are signatures of vendor interfaces.

**Comment by TomasVotruba** [comment]
I'm confused. I see params in the snippet, but here you talk about properties.

**Comment by mssimi** [comment]
Can we just have a call?

**Comment by mssimi** [comment]
Well right, I talk about properties coz rector is named RenameProperty..., but it actually renames params.

**Comment by mssimi** [comment]
Test is not example of real world, how would I simulate vendor package?

**Comment by dobryy** [comment]
I see what you mean @mssimi. Pull Request with test fixture could be helpful :)

**Comment by mssimi** [comment]
@dobryy Thx, I would made test instead of issue, if I knew how to simulate interface is in vendor in that fixture. :)

**Comment by dobryy** [comment]
Check out this folder 
You can create Interface for testing purposes [here](https://github.com/rectorphp/rector/tree/master/rules/naming/tests/Rector/Class_/RenamePropertyToMatchTypeRector/Source
) and use it in Test Fixture in order to reproduce an issue.

**Comment by mssimi** [comment]
Example you given show how to simulate interface, but does not show how to simulate, that interface is part of vendor package.

**Comment by mssimi** [comment]
I think we still don't understand each other, sadly I don't know how can I provide more info.

**Comment by TomasVotruba** [comment]
> vendor package?

That's a good question. Put the *vendor* file into `/Source` directory

```bash
/Fixture // autolaoded and parsed
/Source // autoloaded, not parsed, as /vendor in real-life
RectorTest.php
```

**Comment by dobryy** [comment]
> Example you given show how to simulate interface, but does not show how to simulate, that interface is part of vendor package.

You're right... but I guess, it should skip not only classes/methods that implement interfaces in vendor folder but also interfaces outside of `included` and inside `excluded` paths configured in rector.php. `Source` folder is the one that is excluded thus if Test Class use Interface from it it should skip the renaming. Am I right here @TomasVotruba 

> I think we still don't understand each other, sadly I don't know how can I provide more info.

I definitely do understand what you mean.

**Comment by mssimi** [comment]
> it should skip not only classes/methods that implement interfaces from vendor folder but also interfaces outside of included and inside excluded paths configured in rector.php

And that is what I think too, I am happy we understand each other.

@TomasVotruba thx for clarification, I did not know that. I will try provide test later today than.

**Comment by TomasVotruba** [comment]
@mssimi 

> Can we just have a call?

I've just noticed it. No need to ask, just call next time. The ringing of phone is question itself :)
