### ISSUE TITLE
New SetList paths completely broke if using bamarni/composer-bin-plugin

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#3915]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.62              |
| Installed as   | composer dependency                      |

I'm using `bamarni/composer-bin-plugin`.

it installs Rector in `vendor-bin/phpstan/vendor/rector`.

The file `Rector\Set\ValueObject\SetList` uses fixed paths:

```php
...
/**
     * @var string
     */
    public const ACTION_INJECTION_TO_CONSTRUCTOR_INJECTION = __DIR__ . '/../../config/set/action-injection-to-constructor-injection.php';
...
```

This, obviously, breaks the paths as they are not found and Rector cannot run.

# Suggested solution

I really have no idea 😅

# How to reproduce the issue

```console
composer rem rector/rector && composer req bamarni/composer-bin-plugin && composer bin rector req rector/rector && vendor/bin/rector process --dry-run
```

(this command should work: I'm writing it on the fly, without testing it)

**Comment by TomasVotruba** [comment]
The paths are relative to the class, so they should be always there. Even in PHAR.


Where is this file located in your installation?

```
__DIR__ . '/../../config/set/action-injection-to-constructor-injection.php';
```

**Comment by TomasVotruba** [comment]
> it installs Rector in vendor-bin/phpstan/vendor/rector

Why in PHPStan?

**Comment by TomasVotruba** [comment]
> (this command should work: I'm writing it on the fly, without testing it)

Test it first please, so I don't waste time re-producing bug that's not there :D

**Comment by Aerendir** [comment]
@TomasVotruba the bug is there: this is sure. I’m not sure the commands will recreate the correct environment to reproduce it (but they are correct at 99%).

**Comment by Aerendir** [comment]
In Phpstan because rector depends on it.

**Comment by TomasVotruba** [comment]
I don't use barmani, so I can't really help here. Maybe somebody else might give you hints

**Comment by Aerendir** [comment]
@TomasVotruba , ok, so...?

Anyway, this is the repo on which it is failing: https://github.com/Aerendir/bundle-aws-ses-monitor

**Comment by Aerendir** [comment]
Anyway, bamarni is way better than phar versions as it can be configured with Dependabot and dependencies will be automatically updated (or at least you will be notified of updates): managing dependencies is way easier...
