### ISSUE TITLE
[BUG] Nette tests crashes PHPUnit in PHP 7.2

### ISSUE THREAD

**Issue by carusogabriel** [rectorphp/rector#393]
Several Nette tests have an 

```php
use Nette\Object;
```

and this crashes the tests as `object` as it is a reserved word. Should we remove them?

![nette-tests](https://user-images.githubusercontent.com/16328050/38178278-a9be3aa8-35e5-11e8-89d0-b04ab561a9c3.png)

**Comment by TomasVotruba** [comment]
You're right. It shall run on PHP 7.1 at least.

Do you think that's possible?

**Comment by carusogabriel** [comment]
Maybe we can skip them with PHPUnit annotations, I'll try it :+1:
