### ISSUE TITLE
TypedPropertyRector should not remove DocBlock comment when it specifies the values contained in an array

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#3930]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.63|
| Installed as   | composer dependency|

The rule `Rector\Php74\Rector\Property\TypedPropertyRector` removes the docblock also when it is useful for static analysis:

```diff
final class DemoFile
 {	
-    /** @var \DateTime[]|null */
-    private $times2;
+    private ?array $times2 = null;
 }
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/bfb5f4e9-b039-4ac3-9242-1cc32a81bb56

## Expected Behaviour

```diff
final class DemoFile
 {	
    /** @var \DateTime[]|null */
-    private $times2;
+    private ?array $times2 = null;
 }
```

**Comment by TomasVotruba** [comment]
Thanks for report. Would you like to try to fix it?

**Comment by Aerendir** [comment]
@TomasVotruba , I don't think I can :(

**Comment by TomasVotruba** [comment]
I believe in you. Let me know if you need helping hand

**Comment by Aerendir** [comment]
@TomasVotruba , oh, it’s really kind to hear this from you :)

Unfortunately I meant in this moment I’m not able to spent time on this: I’m already overwhelmed 😅

**Comment by TomasVotruba** [comment]
> I’m already overwhelmed sweat_smile

Same here :D good luck with your priorities!

**Comment by samsonasik** [comment]
I've created PR https://github.com/rectorphp/rector/pull/4102 for it
