### ISSUE TITLE
[CodeQuality] Isset on property object to property_exists()

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#3939]
Similar to `ArrayKeyExistsOnPropertyRector`

![image](https://user-images.githubusercontent.com/924196/89887696-0bbefa80-dbcf-11ea-94a7-f1aa8eb28d8d.png)

**Comment by samsonasik** [comment]
I can't find code reference for `if (isset($node->stmts))`, it seems already changed ? ref https://github.com/rectorphp/rector/blob/41121a94f062697ad1f8b1169aeccf9ce9743dca/packages/node-type-resolver/src/NodeVisitor/StatementNodeVisitor.php#L43

**Comment by TomasVotruba** [comment]
Yes, it's an example for making a new Rector rule, that will handle this automatically

**Comment by samsonasik** [comment]
As I understand, `isset()` in property object may return false when property exists but value is `null`, while `property_exists()` will always return true if property exists, even value is `null` ref https://3v4l.org/vbvHB

Any value check required ?

**Comment by TomasVotruba** [comment]
I did't know that, interesting.

> Any value check required ?

Not for now, but please include the 3v4l.org link in the resource above the rule like this: https://github.com/rectorphp/rector/blob/8311a555737dadb2abb462328141eb6e2629d661/rules/symfony/src/Rector/New_/RootNodeTreeBuilderRector.php#L18

Let's see how this applied in the wild. If it breaks more than fixes, we can always extend the rule

**Comment by samsonasik** [comment]
`isset` seems not a `FuncCall`, looking at `PhpParser\Node\Expr\Isset_`. Could you give me information for how to verify if passet `isset` is an `object->property` ?

```php

use PhpParser\Node;
use PhpParser\Node\Expr\Isset_;
use Rector\Core\Rector\AbstractRector;
use Rector\Core\RectorDefinition\CodeSample;
use Rector\Core\RectorDefinition\RectorDefinition;
use Rector\NodeTypeResolver\Node\AttributeKey;

    /**
     * @return string[]
     */
    public function getNodeTypes(): array
    {
        return [Isset_::class];
    }

    /**
     * @param Isset_ $node
     */
    public function refactor(Node $node): ?Node
    {
        $parent = $node->getAttribute(AttributeKey::PARENT_NODE);
        if ($parent === null) {
            return null;
        }

        return $node;
    }
```

**Comment by TomasVotruba** [comment]
When I work with nodes for first few month, I just dumped the node to see what's inside. Often I found somethign to use

```php

    /**
     * @param Isset_ $node <- this is important for IDE autocomplete
     */
    public function refactor(Node $node): ?Node
    {
        dump($node);
        die;
    }
```

There you can see that isses has `expr` and you can verify what's in it.


```php
    /**
     * @param Isset_ $node <- this is important for IDE autocomplete
     */
    public function refactor(Node $node): ?Node
    {
        if (! $node->expr instanceof PropertyFetch) {
            // not a property fetch → skip
            return null;
        }

        // ...
    }
```

**Comment by TomasVotruba** [comment]
If you'd like to know more about nodes, we have prepared node list with properties and examples:
https://github.com/rectorphp/rector/blob/master/docs/nodes_overview.md#phpparsernodeexprisset_
