### ISSUE TITLE
Stop on violation

### ISSUE THREAD

**Issue by andreybolonin** [rectorphp/rector#3942]
# Feature Request

I found this great post 

https://tomasvotruba.com/blog/2019/03/18/how-to-detect-dead-php-code-in-code-review-in-7-snippets/
 
## Diff 
And I want to use this feature (dead code detection) on my CI

In `php-cs-fixer` we have `--stop-on-violation` key
And CI is build failed on found violation

Can we implement something like this?

And any ideas how to search usedd method also in `templates` folder in a Symfony?

**Comment by TomasVotruba** [comment]
Hi, for these CI cases, the `--dry-run` does exactly what you need.
Thanks for the PR though, it gave me the understanding of your need :+1:

**Comment by andreybolonin** [comment]
`--dry-run` is not stopped on found violation

**Comment by TomasVotruba** [comment]
It does the same behavior as in PR.
