### ISSUE TITLE
Fix code based on a phpstan error message

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#3948]
# Feature Request

we work on legacy code bases most of our time.
its the reason why we have X-thousand phpstan errors in there and we tackle them when time allows.

one of such errors is e.g. 
> Parameter #3 $cols of method Zend_Db_Select::join() expects array|string, null given.

this error happens when our old code uses `null` instead of `array()`  as a parameter in calls to `Zend_Db_Select::join()`.
fixing this errors is pretty straigt forward, but doing so across a huge code-base makes it a tedious and time-comsuming task.

this problem made me think, that it might be a rector use-case in which rector might be able to help us, by fixing one issue at a time across the whole codebase.
would it be possible to have a rector in which I feed in a phpstan error message, like `Parameter #3 $cols of method Zend_Db_Select::join() expects array|string, null given.` and it would allow me fix this issue using the AST rector API.

So instead of programatically write code which detects faulty code, we would use phpstans knowledge of the codebase and base the necessary refactoring onto that..?

maybe its just crazy, or maybe just a start of a usefull conversation.. who knows :-)

**Comment by TomasVotruba** [comment]
Hi,

there are many type-related rules now, that handles these cases.

- for @var annotations https://tomasvotruba.com/blog/2019/01/03/how-to-complete-type-declarations-without-docblocks-with-rector/
- for property/param/return in type-declaration rules: https://github.com/rectorphp/rector/tree/master/rules/type-declaration/src/Rector

**Comment by TomasVotruba** [comment]
> maybe its just crazy, or maybe just a start of a usefull conversation.. who knows :-)

If you can make such a prototype that works and is reliable, why not :)

**Comment by TomasVotruba** [comment]
Closing as idea accepted :+1:  and to keep issue tracker priorities focused.
