### ISSUE TITLE
Migration from 3.2 -> 4.0 composer required --dev rector/rector ^0.7.25

### ISSUE THREAD

**Issue by amitvkhajanchi** [rectorphp/rector#3956]
# Bug Report

**Subject:** Rectory version needs to be defined in migration documentation.
When following the guideline of the migration from 3.2 -> 4, for custom codes it says you can use rector.   However, when installing rector following the instruction I ran into issue where the latest rector required doctrine/annotation 1.10.*, however, Akeneo stops at doctrine/annotation 1.8 and fails.

Solution: Instead of just doing composer require --dev rector/rector add ^0.7.25 at the end (latest version of rector that used annotation 1.8.

Hence final code should look like:

composer required --dev rector/rector ^0.7.25

**Comment by amitvkhajanchi** [comment]
After testing further the scan-fatal-errors command is removed in 0.7.21
https://github.com/rectorphp/rector/search?q=scan-fatal-errors&unscoped_q=scan-fatal-errors

So if you want to use the scan-fatal-errors command, the rector version needs to be 0.7.20

**Comment by amitvkhajanchi** [comment]
Sorry, wrong repo.  Was supposed to be on Akeneo's repo as they had instruction for using rector.
I will copy this issue and you can close this issue.

**Comment by TomasVotruba** [comment]
Closing then
