### ISSUE TITLE
Throw error if custom rector is defined but not found/used

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#3960]
# Bug Report

I added a custom rector as per docs in /utils/Rector/ and adjusted composer.json psr4 autoload-dev
Then I added it in the rector.php root file:

    $services->set(MyCustomRector::class);

But when running rector it said: All green, done

In fact, it never ran this rector as it was apparently not found.
I needed some time to debug and found that composer dump-autoload wasn't run (which is needed for composer to resolve the file location for rector).

So here the rector was silently skipped.
I would expect the services::set() to either directly throw an exception (class not found), or then the runner to issue some kind of feedback on why this isn't used, or better yet abort with an error here.

**Comment by TomasVotruba** [comment]
Hi,

it's possible the rule is not autoloaded, if you used `generate` command to create it There have been some fixes today to that process.

1. I'd try to see if the rule is loaded.

```bash
vendor/bin/rector show
```

2. How can you validate the `rector.php` is loaded?

**Comment by dereuromark** [comment]
Sure.
But the code clearly has a ::set() call of such rector rule
It just wasn't found/loaded yet. So instead of silently skipping, it would help if that would be noticed, so the developer knows the current one isn't green because all OK but green because nothing just ran.

I will check again latest version then.
