### ISSUE TITLE
Bug running Rector on Laravel Providers

### ISSUE THREAD

**Issue by TavoNiievez** [rectorphp/rector#3974]
Running set `SetList::LARAVEL_STATIC_TO_INJECTION` on Rector 0.7.63 :

```
   TypeError 

Argument 1 passed to App\Providers\AppServiceProvider::__construct() must be an instance of Illuminate\View\Factory, instance of Illuminate\Foundation\Application given, called in C:\...\vendor\laravel\framework\src\Illuminate\Foundation\Application.php on line 690
```
How to fix:
```diff
<?php declare(strict_types=1);

namespace App\Providers;

+ use Illuminate\Contracts\Foundation\Application;
use Illuminate\Support\ServiceProvider;
- use Illuminate\View\Factory;
+ use Illuminate\Contracts\View\Factory as View;

final class AppServiceProvider extends ServiceProvider
{
-    private \Illuminate\View\Factory $factory;
+    private View $view;

-    public function __construct(\Illuminate\View\Factory $factory)
+    public function __construct(Application $app)
    {
-        $this->factory = $factory;
-        parent::__construct();
+        parent::__construct($app);
+        $this->view = $app->get(View::class);
    }
}
```

**Comment by TavoNiievez** [comment]
I have found some other bugs running rector in laravel, (and also in Symfony with rector.php), but I have been short of time, as soon as I get the space I will try to explain my issues and how they could be solved. Thanks you.

**Comment by TavoNiievez** [comment]
something similar happens in Middleware\Authenticate.php but the constructor receives instead an instance of `Illuminate\Contracts\Auth\Factory`. making it difficult to 'inject' the dependency into the constructor, so I think the best solution for this is simply:

```diff
-        View::share('app_name', env('APP_NAME'));

+        use Illuminate\View\Factory as View;

+        /** @var View $view  */
+        $view = $this->app->get(View::class);
+        $view->share('app_name', env('APP_NAME'));
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.


- What rule is responsible for the incorrect change?
- Could you add failing test fixture with pull-request, so we have it covered here?

**Comment by TavoNiievez** [comment]
I'd like to, but when I try to run it:

![imagen](https://user-images.githubusercontent.com/37160403/90402136-a0f53f80-e064-11ea-8cf7-d594414fa3d3.png)

and I don't know if it's really the code...

```php
<?php

use Illuminate\Support\ServiceProvider;

class abc extends ServiceProvider {
	function xyz() {
		return view('opq');
	}
}
```

or the just page.

In any case, the rule is the same: `Rector\Laravel\Rector\FuncCall\HelperFunctionToConstructorInjectionRector`
and it should be executed when finding this line of code:
```php
return view('opq');
```

**Comment by TomasVotruba** [comment]
That's something else, a demo link. We need failing code in this repository.

I've replied in your other issues few minutes ago. Let me know what else you need to create failing test fixture there.

**Comment by TavoNiievez** [comment]
Sorry, i read it a few seconds ago.
I didn't have github open as i was trying to run it.
I'm sorry i'm not so familiar with the lingo.

**Comment by TomasVotruba** [comment]
No troubles, we all learn everyday.

**Comment by TomasVotruba** [comment]
Closing as failing test fixture is missing
