### ISSUE TITLE
redirect inconsistency on Laravel Rector

### ISSUE THREAD

**Issue by TavoNiievez** [rectorphp/rector#3975]
Running set SetList::LARAVEL_STATIC_TO_INJECTION on Rector 0.7.63 : 

```
            return redirect(RouteServiceProvider::HOME);
```
I would hope to be:
```diff
-            return $this->redirector->back(RouteServiceProvider::HOME);
+            return $this->redirector->back();
```
API for` redirector->back()` is:  `public function back($status = 302, $headers = [], $fallback = false)`, so passing it a route as an argument makes no sense.
Although this modifies the behavior of the application, the actual translation would be:
```diff
-            return $this->redirector->back(RouteServiceProvider::HOME);
+            return $this->redirector->to(RouteServiceProvider::HOME);
```

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting.

Could you add failing fixture to the responsible rule? That way we have it covered and we know what is expected output. I'll look into fix then

**Comment by TavoNiievez** [comment]
:neutral_face: https://getrector.org/demo/5ca02a2d-2d09-4ad5-866f-2285f7bf7bc5

**Comment by TomasVotruba** [comment]
Thanks

Could you add that as failing fixture to our tests?

Just copy one of files here and add failing content
https://github.com/rectorphp/rector/tree/master/rules/laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture

**Comment by TomasVotruba** [comment]
Closing as failing test case is needed
