### ISSUE TITLE
All rules are applied with prefixed

### ISSUE THREAD

**Issue by seb-jean** [rectorphp/rector#3976]
Hi,

I use https://github.com/rectorphp/rector-prefixed but when I run it a command for example: `vendor/bin/rector process src --set php80 --dry-run` or `vendor/bin/rector process src --set symfony40 --dry-run`, all rules are applied.

Thanks :)

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting.

- What is expected behavior?
- What changes if you remove `--dry-run` option?

**Comment by seb-jean** [comment]
The expected behavior is that php80 is only applied.
The same applies to symfony40.

If I remove --dry-run option, it's the same.

**Comment by TomasVotruba** [comment]
I see. Thanks

**Comment by TomasVotruba** [comment]
Closing as failing CI is needed
