### ISSUE TITLE
Calling a static method on a class-string variable

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#3981]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.53         |
| Installed as   | composer dependency                   |

Rector crashes when calling a static method on a class-string variable

## Minimal PHP Code Causing Issue
https://getrector.org/demo/88314d95-fdc2-4dff-a286-9fa577a029ca

And change the setList to `SetList::PHP_70`

## Expected Behaviour
It should give some output

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

Could you add failing test case to responsible rule?
