### ISSUE TITLE
Move rector.phar to releases

### ISSUE THREAD

**Issue by jawira** [rectorphp/rector#3985]
# Feature Request

Hi, I can see that a phar file is available at "rector-prefixed" repository. The request is: Is it possible to add the phar file to the  "releases" section?

The reason is that I use Phive to download phar files. Phive is capabable to download phar files directly from repositories but they must be located in "releases" section.

Examples:

![phar1](https://user-images.githubusercontent.com/496541/90604253-db91e000-e1fc-11ea-8c47-615b019e7bc8.png)

![phar2](https://user-images.githubusercontent.com/496541/90604258-dd5ba380-e1fc-11ea-998a-2d4c0fe4740e.png)

Thank you :)

**Comment by TomasVotruba** [comment]
Hi, sure 👍 
Could you send PR to add it?

**Comment by jawira** [comment]
> Hi, sure 👍
> Could you send PR to add it?

Well, strictly answering your question: not sure I can send a PR, but I can try. Can you give me some pointers please?

**Comment by TomasVotruba** [comment]
Honestly, I have no idea

**Comment by TomasVotruba** [comment]
Closing as idea accepted. PR is needed now

**Comment by JanMikes** [comment]
Hi, i did quick reasearch and found out this: https://docs.github.com/en/rest/reference/repos#upload-a-release-asset 

Looks like this can only be done via github api. The best possible way would be it to become part of CI.
