### ISSUE TITLE
[DX] Add PHPStan rule to check that class that implements ConfigurableRectorInterface has ConfiguredCodeSample

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4027]

**Comment by samsonasik** [comment]
@TomasVotruba is it already implemented at https://github.com/rectorphp/rector/blob/59e1413b82e06455c730d83b76d26ad3c2f832b7/utils/phpstan-extensions/src/Rule/ConfigurableRectorRule.php ?

**Comment by TomasVotruba** [comment]
Yes, this is covered. Thank you
