### ISSUE TITLE
[Naming] Swapped naming of Pascal and Camel

### ISSUE THREAD

**Issue by TomPavelec** [rectorphp/rector#4040]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.65 |
| Installed as   | composer dependency |

Method `StaticRectorStrings::underscoreToPascalCase` returns string with first character in lowercase.
Method `StaticRectorStrings::underscoreToCamelCase` returns string with first character in upprecase.

## Expected Behaviour
It should be the other way.

```
StaticRectorStrings::underscoreToPascalCase('test_string');
// TestString

StaticRectorStrings::underscoreToCamelCase('test_string');
// testString
```

Then repair all occurances of those methods e.g. rename `UnderscoreToPascalCasePropertyNameRector` to `UnderscoreToCamelCasePropertyNameRector`

**Comment by TomasVotruba** [comment]
I see and agree 👍 

Could you send PR with a fix?

**Comment by TomPavelec** [comment]
Sure, here it is https://github.com/rectorphp/rector/pull/4047

**Comment by TomasVotruba** [comment]
Thanks

Tip for automated issue close on PR merge
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by TomPavelec** [comment]
> Tip for automated issue close on PR merge
> https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Nice, thank you
