### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by garak** [rectorphp/rector#4046]
# Question

I know this can sound like a silly question, but I'm stuck with nothing happening. I guess that I'm missing something basic...

My situation:
`~/.composer/bin/rector --version` is returning "Rector v0.7.65"

`~/.composer/bin/rector process src --dry-run -v` is printing a lot of file names (with parsing/refactoring/post rectors/printing written before), then "[OK] Rector is done!". No changes are made, nor displayed as diff (as I would expect)

Also tried with `~/.composer/bin/rector process src --set=php74 --dry-run -v`, same result.

Projects where I'm trying this are php 7.2 projects, so with class properties like this one:

```
<?php 
class Foo
{
    /** @var UuidInterface */
    private $id;
}
```

where I'd expect properties to be affected by rector, but nothing happens 😔

Trying with more verbosity (`-vvv`) I also get with few files something more, like "[applying] Rector\RectorGenerator\Rector\Closure\AddNewServiceToSymfonyPhpConfigRector", but again without any actual outcome

**Comment by mhabibi** [comment]
@garak you need a `rector.php`, read here https://github.com/rectorphp/rector#running-rector

**Comment by garak** [comment]
> @garak you need a `rector.php`, read here https://github.com/rectorphp/rector#running-rector

ah! That' working, thanks.
So, maybe the absence of such file should be pointed out somehow?

**Comment by TomasVotruba** [comment]
Rector should run without any config, although it's better to use it.

What happens on `vendor/bin/rector show` command?

**Comment by TomasVotruba** [comment]
I'm trying the rule now, and the PHP version in Docker might be the problem:

```diff
 # rector.php
-$parameters->set(Option::PHP_VERSION_FEATURES, '7.2');
+$parameters->set(Option::PHP_VERSION_FEATURES, '7.4');
```

To use PHP features newer than current version, the config must be used.
So `rector.php` is indeed needed for this case :)

**Comment by TomasVotruba** [comment]
It's also best pratise to use the version, so everyone knows where to change it PHP 8.0 when it's out

**Comment by garak** [comment]
What's "current version"? I'm using php 7.4
Anyway, don't you think that a message should be shown in such case?

If I try `~.composer/bin/rector show`, I get:
 
>Rector v0.7.65
> * Rector\RectorGenerator\Rector\Closure\AddNewServiceToSymfonyPhpConfigRector

**Comment by TomasVotruba** [comment]
> Anyway, don't you think that a message should be shown in such case?

Good idea. Could you add such mechanism?

**Comment by garak** [comment]
> Good idea. Could you add such mechanism?

I don't even know what the problem is.

**Comment by TomasVotruba** [comment]
Ah. I thought there is some problem. Allright then

**Comment by garak** [comment]
There *is* a problem: what are the purpose of passing `--set` if I need to specify it in a configuration file?
And, anyway, a message about missing configuration file should be provided

**Comment by TomasVotruba** [comment]
> There is a problem: what are the purpose of passing --set if I need to specify it in a configuration file?

That's not needed. Same way `composer require x/y` only installs packages that comply with your PHP version. To get a different PHP version than local, you need to specify it in the `config > platform`

Same applied for PHP version with Rector
See https://github.com/rectorphp/rector/issues/4046#issuecomment-683312102

**Comment by garak** [comment]
I'm still confused.
I can't understand what "current version" means. My current version of php is php 7.4 (I'm not using rector with Docker)
The project I'm trying to correct is on php 7.4 too, but has a php 7.2 syntax (e.g. without typed properties).

**Comment by TomasVotruba** [comment]
> "current version"

It should be:

```
php -v
```

This is the service responsible for PHP version in Rector:

https://github.com/rectorphp/rector/blob/dbfaf6e11d70c68a6aaf17acd16c0af5b675a995/src/Php/PhpVersionProvider.php#L25-L46

The problem you describe could be anywhere. I think we need reproductible repository in this case, just to prevent random guesses.
