### ISSUE TITLE
Enhance JsonThrowOnErrorRector error handling

### ISSUE THREAD

**Issue by SilverFire** [rectorphp/rector#4050]
# Feature Request

Rector [JsonThrowOnErrorRector](https://github.com/rectorphp/rector/blob/master/rules/php73/src/Rector/FuncCall/JsonThrowOnErrorRector.php)

If the existing json_encode/decode call already has some error handling – move it in a try-catch block.

## Diff 

Currently:

```diff
-        $json = json_decode($body, true);
+        $json = json_decode($body, true, 512, JSON_THROW_ON_ERROR);
         if (json_last_error() !== JSON_ERROR_NONE) {
             return null;
         }
```

Nice to have:

```diff
-        $json = json_decode($body, true);
-        if (json_last_error() !== JSON_ERROR_NONE) {
+        try {
+            $json = json_decode($body, true, 512, JSON_THROW_ON_ERROR);
+        } catch (JsonException $exception) {
             return null;
         }
```

**Comment by TomasVotruba** [comment]
Hi, I'd be happy to accept this PR

**Comment by TomasVotruba** [comment]
Closing as idea accepted :+1:  and to keep issue tracker priorities focused.
