### ISSUE TITLE
[DX] Add custom fixture check for namespace

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4065]
- make sure the fixture file is in correct namespace
- the class inside name respects the file name, e.g `Fixture/some_file.php.inc` must have `class SomeFile` in it

**Comment by samsonasik** [comment]
is it using phpstan rule ? if yes, the fixture directory seems excluded in phpstan.neon

https://github.com/rectorphp/rector/blob/61828cdb6798cfc6be5f1839a6a40b7f1fe932ae/phpstan.neon#L173

**Comment by TomasVotruba** [comment]
This will not be PHPStan, nor coding standard rule.

It requires custom PHP command, something like: https://github.com/rectorphp/rector/blob/master/utils/project-validator/src/Command/ValidateFixtureSuffixCommand.php

- find all "Fixture/*php.inc" files
- check their expected namespace, e.g. tests/Some/Fixture/file.php → `Rector\Tests\Some\Fixture`
- validate the namespace is correct in the file, split file with `-----` in before/after fixture
- report missmatched namespaces

**Comment by samsonasik** [comment]
Ok, I will try.

**Comment by samsonasik** [comment]
It is implemented. I am closing it.

**Comment by TomasVotruba** [comment]
Thank you :+1:
