### ISSUE TITLE
[EarlyReturn] Change if && to early return

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4071]
![image](https://user-images.githubusercontent.com/924196/91659453-e89db180-eacf-11ea-8f25-4997e98646c0.png)

**Comment by TomasVotruba** [comment]
![image](https://user-images.githubusercontent.com/924196/91876339-df9e1300-ec7c-11ea-8b04-6a9816c4cd11.png)

↓

![Uploading image.png…]()

**Comment by TomasVotruba** [comment]
![rector_to_early_return](https://user-images.githubusercontent.com/924196/91888122-0c0d5b80-ec8c-11ea-8784-94e6ebe9123a.png)

**Comment by dobryy** [comment]
Should be a new early-return set? I've noticed that we already have some early return rules in SOLID set.

**Comment by TomasVotruba** [comment]
I'd go with SOLID then

**Comment by samsonasik** [comment]
It seems already implemented at https://github.com/rectorphp/rector/pull/4395 . I am closing it.
