### ISSUE TITLE
[DX] Add rule to check not "Tests" namespace outside "tests" directory

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4075]

**Comment by dobryy** [comment]
https://github.com/rectorphp/rector/pull/4091

**Comment by TomasVotruba** [comment]
This inverse rule would be next: https://github.com/rectorphp/rector/issues/4061

**Comment by TomasVotruba** [comment]
Issues can be closed by Github itself:

Tip for closing keywords:
https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by dobryy** [comment]
Thank you, I know I just forgot to add the keyword in PR ;)
