### ISSUE TITLE
*GetToConstructorInjectionRector rectors lost default configuration

### ISSUE THREAD

**Issue by alister** [rectorphp/rector#4090]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | current dev-master              |
| Installed as   | any                      |

The default configurations have been lost for (at least) the rectors:
* GetToConstructorInjectionRector
* ContainerGetToConstructorInjectionRector

In commit fe72e003e, when the classes were made configurable, the `$getMethodAwareTypes` & `$containerAwareParentTypes`, previously set in the __construct() method of the rectors were not added to the configuration file config/set/symfony-constructor-injection.php (or set as default properties, which has happened with some other rector upgrades).

The similar configuration for config/set/easy-admin-bundle20.php was upgraded in fe72e003e, and originally set in commit bc0d9b367 (in file config/set/easy-corp/easy-admin-bundle20.php).

Other rectors that may have also lost configuration from default __constructor parameters (from commit fe72e003e):

* rules/order/src/Rector/ClassMethod/OrderConstructorDependenciesByTypeAlphabeticallyRector.php  
* rules/php74/src/Rector/Function_/ReservedFnFunctionRector.php

**Comment by TomasVotruba** [comment]
Hi, 

thanks for reporting.
The configuration should be moved to `configure()` method call.
If this is not the case, could you add it in configs?

**Comment by alister** [comment]
As the `$containerAwareParentTypes` & `$getMethodAwareTypes` are so closely linked to Symfony, I think that they may be better as property defaults, so that if they were ever explicitly enabled (without using config/set/symfony-constructor-injection.php), they would still work as expected without additional setup. Property defaults are used in StringClassNameToClassConstantRector, which can be replaced by `configure()`.

**Comment by TomasVotruba** [comment]
Agreed :+1:
