### ISSUE TITLE
Proposal: allow to not add docblocks when downgrading code (property types, type unions)

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4094]
# Feature Request

When downgrading the typed properties ([DowngradeTypedPropertyRector](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#downgradetypedpropertyrector)) and union types (#4062), allow to configure the rules to simply remove the code, and avoid adding the docblocks.

Why? Because I'm using these rules to compile code for production, so that:

- I develop with PHP 7.4 (and 8.0 later on)
- I deploy to PHP 7.2

For production, I do not need the docblocks. However, they have an inconvenient side effect: they shift the line numbers of the code. Then, if in production I have a bug, the log saying it happens on line 30, I can't just go to my code in development and see what is there on line 30. But if the docblocks are not generated, then line 30 in production is line 30 in development.

**Comment by TomasVotruba** [comment]
Hi,

your proposal makes sense. :+1: 

The rule needs to be made configurable with `ConfigurableRectorInterface`. You can look at some other rules that implement this interface on how to make it.
