### ISSUE TITLE
[DX] PHPStan rule to check, that value objects do not have value object suffix

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4096]
It is already in the noun

```diff
-Rector\ValueObject\PersonValueObject
+Rector\ValueObject\Person
```

**Comment by dobryy** [comment]
Is it enough to check that there is no ValueObject prefix at all in all class names? :) 
If not, am I right that the only possible way to recognize value object is that all value objects are under `\..\ValueObject\` namespace?

**Comment by TomasVotruba** [comment]
> Is it enough to check that there is no ValueObject prefix at all in all class names? :)

That could be quick solution, but it would be hard to re-use such rules in the future. E.g. to inversed idea, require a suffix if in some namespace.

So it would be better to do it with the namespace check too :)

> If not, am I right that the only possible way to recognize value object is that all value objects are under \..\ValueObject\ namespace?

Yes :+1:
