### ISSUE TITLE
Tiny nuisance: newline added after comment inside a function

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4097]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.65 |
| Installed as   | composer dependency   |

The code below has a comment inside a function with the same shape as a docblock. Rector is adding a newline after it.

This code:

```php
function bar()
{
	// Some code here
	echo 'Hello';

	/**
	 * Can NOT sort interfaces yet! Because interfaces may depend on other interfaces,
	 * they must follow their current order to be initialized,
	 * which happens when creating instances of `InterfaceType` in type `Schema`
	 *
	 * @todo Find a workaround if interfaces need to be sorted
	 */
	// if (!is_null($this->fullSchemaDefinition[SchemaDefinition::ARGNAME_INTERFACES])) {
	//     ksort($this->fullSchemaDefinition[SchemaDefinition::ARGNAME_INTERFACES]);
	// }
}
```

Is replaced with this one:

```php
function bar()
{
	// Some code here
	echo 'Hello';

	/**
	 * Can NOT sort interfaces yet! Because interfaces may depend on other interfaces,
	 * they must follow their current order to be initialized,
	 * which happens when creating instances of `InterfaceType` in type `Schema`
	 *
	 * @todo Find a workaround if interfaces need to be sorted
	 */
	// if (!is_null($this->fullSchemaDefinition[SchemaDefinition::ARGNAME_INTERFACES])) {
	//     ksort($this->fullSchemaDefinition[SchemaDefinition::ARGNAME_INTERFACES]);
	// }

}
```

Notice the newline added at the end, after `    // }` and before `}`

## Minimal PHP Code Causing Issue

https://getrector.org/demo/8e9de570-fff7-463e-bd88-1b358aa1d1f1#result

## Expected Behaviour

That newline should not be added

**Comment by TomasVotruba** [comment]
Hi,

the docblock are extremely hard to process, as there is no tool to work with them, like we have AST and php-parser. We already make enormous effort to keep docblock as they are with regular expressions.
Until there is such tool, or PHP 8 with attributes, there is not much we can do.

Never the less, this can be compensated in most cases with good quality coding standard
Be sure to use ECS or any other coding standard with good quality sets, as stated in the README: https://github.com/rectorphp/rector#how-to-apply-coding-standards

Here is our [`ecs.php`](https://github.com/rectorphp/rector/blob/master/ecs.php) for inspiration
