### ISSUE TITLE
Proposal: [Downgrade] PHP 8.0 mixed type

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4108]
# Feature Request

PHP 8.0 will add the [`mixed` type](https://stitcher.io/blog/new-in-php-8#new-mixed-type-rfc). It would be cool to be able to remove it, as to compile PHP 8.0 code to lower versions.
 
## Diff 

```diff
-function foo(mixed $bar): mixed {}
+/**
+ * @param mixed $bar
+ * @return mixed
+ */
+function foo($bar) {}
```

**Comment by TomasVotruba** [comment]
Would you like to contribute this?

**Comment by leoloso** [comment]
Ok, can
