### ISSUE TITLE
Missing Ruleset does not throw SetNotFoundException

### ISSUE THREAD

**Issue by julianpollmann** [rectorphp/rector#4116]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.5              |
| Installed as   | composer dependency by cakephp/upgrade                     |

Applying rector rules with the cakephp/upgrade tools rector function with missing ruleset throws this error:

```
PHP Fatal error:  Uncaught Error: Class 'Symplify\EasyCodingStandard\Bootstrap\InvalidSetReporter' not found in /xxx/upgrade/vendor/rector/rector/bin/rector:74
Stack trace:
#0 {main}
  thrown in /xxx/upgrade/vendor/rector/rector/bin/rector on line 74

Fatal error: Uncaught Error: Class 'Symplify\EasyCodingStandard\Bootstrap\InvalidSetReporter' not found in /xxx/upgrade/vendor/rector/rector/bin/rector on line 74

Error: Class 'Symplify\EasyCodingStandard\Bootstrap\InvalidSetReporter' not found in /xxx/upgrade/vendor/rector/rector/bin/rector on line 74

Call Stack:
    0.0003     425344   1. {main}() /xxx/upgrade/vendor/rector/rector/bin/rector:0

```

## Minimal PHP Code Causing Issue
/xxx/vendor/bin/rector process  --autoload-file='/yyy/vendor/autoload.php' --set='cakephp41' --working-dir='/yyy/src

## Expected Behaviour
Throw a SetNotFoundException.

The InvalidSetReporter has been [moved](https://github.com/symplify/set-config-resolver/commit/6e361d638d60af8847835bf1e95ddd8d5b7470d9) from **symplify/easy-coding-standard** to **symplify/set-config-resolver**

**Comment by TomasVotruba** [comment]
Hi, 

I see the fix commit, but can't find the pull-request.
Could you create it?
