### ISSUE TITLE
JoinStringConcatRector create lines with length > 120 chars

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector#4121]
# Bug Report

When using `JoinStringConcatRector`, rector seems to not respect the max. lenght of `120` characters.

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.65           |
| Installed as   | composer dependency - global (resintalled right now) |

Perhaps linked to #4052 or not...

### My rector.php configuration file

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\CodeQuality\Rector\Concat\JoinStringConcatRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::PHP_VERSION_FEATURES, '7.2');
	
    $services = $containerConfigurator->services();
    // https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#joinstringconcatrector
    $services->set(JoinStringConcatRector::class);
};
```

### Before 

Simplified sample:

```php
<?php

function setDatabaseName(): void
{
    Assert::regex(
        $this->dsn,
        $pattern,
        'The connectionString ' .
        'defined in ' .
        'the configuration file seems to ' .
        'not mention a database name; please check ' . $this->Config . ' and ' .
        'the key nammed components.db.connectionString, ' .
        'current value is "' . $this->dsn . '"'
    );
}
```

### After 

```php
<?php

function setDatabaseName(): void
{
    Assert::regex(
        $this->dsn,
        $pattern,
        'The connectionString defined in the configuration file seems to not mention a database name; please check ' . $this->Config . ' and ' .
        'the key nammed components.db.connectionString, ' .
        'current value is "' . $this->dsn . '"'
    );
}
```

As we can see, rector has concat severall lines (so great!) but the lenght is bigger than `120` (actually `145` characters).
Other static tools like PHP-CS-FIXER will then complains about that lenght.

## Expected Behaviour

Lines can't be greater than `120` chars.

Many thanks

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. It looks like bug.

Could you add failing demo link too?

https://getrector.org/demo

**Comment by cavo789** [comment]
I've already tried on the demo site but there, the problem isn't replicable (only on my machine??): https://getrector.org/demo/e09e0dd7-f96a-4685-a3ef-178d86f5f215

**Comment by TomasVotruba** [comment]
Ah. It's possible it's already fixed.

The linked PR: https://github.com/rectorphp/rector/pull/4052 is part of 0.8.0+

![image](https://user-images.githubusercontent.com/924196/92232170-5ec65d80-eeae-11ea-86c4-69bb50d97ee3.png)

<br>

The demo usually runs the latest version. If you bump to `0.8.5` or even `dev-master`, does the problem still remain?

**Comment by cavo789** [comment]
Ouch ! That really strange... You're right of course.

My global composer.json contains:

```
"rector/rector-prefixed": "^0.7.39"
```

This morning I've force the update of dependencies and I've got `v0.7.65` has mentionned earlier.

I've now changed to 

```
"rector/rector-prefixed": "^0.8"
```

and the installed version is now, indeed, `v0.8.6`.

**The problem is indeed solved.**

*(just a notice: why strings are not concatenated until the max is reached? For instance, in my [demo](https://getrector.org/demo/e09e0dd7-f96a-4685-a3ef-178d86f5f215), the two lines ` 'The connectionString ' .` and ` 'defined in ' .` can be merged here since less than 120 chars)*

Thanks Tomas.

**Comment by TomasVotruba** [comment]
Glad it helped :+1: 

<br>

Personally, I found global composer more buggy more then helpful (not everything that can be used, should be used). Only valid case are tools like prestissimo. 

Everything else just goes wrong :D 


It's also hard to see what version do you have and can collide with differnt project. E.g. one project has Symfony 3, so it needs prefixed Rector, the other is new one, so can use 0.8 version.

That's why I always install Rector/ECS/PHPStan/PHPUnit per package. It's also easy to add Rector to continuous integration, if it's in `composer.json`.

**Comment by TomasVotruba** [comment]
> (just a notice: why strings are not concatenated until the max is reached? For instance, in my demo, the two lines 'The connectionString ' . and 'defined in ' . can be merged here since less than 120 chars)

I'd ask this in the PR, I haven't implemente the feature.
