### ISSUE TITLE
EXCLUDE_PATHS option does not work X-OS

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#4127]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.8.6 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency                       |

a rector.php config which defines path in a linux-style manner, like

```
    $parameters->set(Option::EXCLUDE_PATHS, [
        __DIR__.'/app/views/*',
    ]);
```

does not work on a windows workstation, because the `FilesFinder` does not normalize the directory separators.

paths with backslashes get compared against paths with slashes and therefore never match

## Expected Behaviour

I would expect I can use linux-style paths in the rector.php so it can work across operating systems

**Comment by staabm** [comment]
phpstan does a lot of normalizing before comparing the paths.. maybe some inspiration can be taken from there (or maybe even the implementation can be re-used)

https://github.com/phpstan/phpstan-src/blob/02425e61aa48f0668b4efb3e73d52ad544048f65/src/File/FileExcluder.php#L30-L38

https://github.com/phpstan/phpstan-src/blob/02425e61aa48f0668b4efb3e73d52ad544048f65/src/File/FileHelper.php#L40-L74

**Comment by TomasVotruba** [comment]
I don't use Windows/Mac OS, so I can't fix it.
What change in `FilesFinder` fixes it?
