### ISSUE TITLE
Proposal: Add the PHP namespace to the downgrade rules

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4143]
# Feature Request

As much as there's namespace `Php71`, `Php72`, etc, to migrate to new features, I think it makes sense to add such namespaces below `Downgrade`, to indicate from what version we are downgrading from.

This makes it easier to add them into the set, since the downgrading must be executed in order:

- First all PHP 8.0 rules
- Then all PHP 7.4 rules
- Then all PHP 7.3 rules
- ...

This is because `??=` in 7.4 downgrades to `??` from 7.3, which can itself be downgraded to `isset` in 5.6.

In addition, a great side effect of adding the namespace is that, I imagine, when listing all rules in the rules overview `.md`, they with all be ordered all together by PHP version.
 
## Diff 

```diff
-namespace Rector\Downgrade\Rector\Property;
+namespace Rector\Downgrade\Php74\Rector\Property;

final class DowngradeTypedPropertyRector
```

**Comment by TomasVotruba** [comment]
I agree with custom namespace, to separate PHP versions.
We use always just 1 category, to make it simple. Nesting with X categories can go wrong quickly, e.g. `namespace Rector\Symfony\34\Quality\Risky`...

Saying that, this would keep namespaces unique and 1-level:

```php
namespace Rector\DowngradePhp74\Rector\Property;
```

What do you think?

**Comment by leoloso** [comment]
If it makes sense to you, I'm OK with it

**Comment by leoloso** [comment]
If I'm not wrong, with your proposal, the new PHP 8 rectors could be already merged to master, but without adding the `psr-4` entry in `composer.json` so then it won't fail... does that make sense?

Please confirm on the way to go, and I'll submit a PR with this change (I need to do it before implementing the PHP 8 rectors)

**Comment by TomasVotruba** [comment]
It can be added as any other rule.

It won't fail, since PHPUnit tests will require PHP 8.0 and there is no PHP 8.0 yet in Github Actions. I'm working on it, yet there are some bugs with composer I have to figure out first.

**Comment by leoloso** [comment]
Great, I'll start working on it

**Comment by TomasVotruba** [comment]
Thank you :clap:
