### ISSUE TITLE
Argument 8 passed to PHPStan\Analyser\MutatingScope::__construct() must implement interface

### ISSUE THREAD

**Issue by mohdimran-3pg** [rectorphp/rector#4148]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.2 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency                     |

## Minimal PHP Code Causing Issue
Hi Team,
I have PHP 7.2.1 when i run rector dry-run i am getting below errors

 **[ERROR] Could not process                                                                                              
         "/Users/Documents/Rector+ES/Upgrade/api/app/models/JobPostCategory.p
         hp" file, due to:                                                                                              
         "Argument 8 passed to PHPStan\Analyser\MutatingScope::__construct() must implement interface                   
         PHPStan\Parser\Parser, instance of PHPStan\Analyser\ScopeContext given, called in                              
         /Users/Documents/Rector+ES/Upgrade/vendor/rector/rector/packages/node-type-resolv
         er/src/PHPStan/Scope/ScopeFactory.php on line 76".**
       
      [ERROR] Could not process                                                                                              
         "/Users/Documents/Rector+ES/Upgrade/api/app/models/custom/adapters/C
         rimcheckScreeningAdapter.php" file, due to:                                                                    
         "leaveNode() may only return an array if the parent structure is an array".

   **[ERROR] Could not process                                                                                              
         "/Users/Documents/Rector+ES/Upgrade/api/app/models/custom/adapters/C
         svAdapter.php" file, due to:                                                                                   
         "Argument 1 passed to Rector\Core\PhpParser\Node\Manipulator\ClassManipulator::getProperty() must be an        
         instance of PhpParser\Node\Stmt\ClassLike, null given, called in                                               
         /Users/Documents/Rector+ES/Upgrade/vendor/rector/rector/rules/code-quality/src/Re
         ctor/If_/RemoveAlwaysTrueConditionSetInConstructorRector.php on line 185".**

## Expected Behaviour

It should not show the errors.

**Comment by TomasVotruba** [comment]
There is version 0.8 now where this should be fixed
