### ISSUE TITLE
[Downgrade PHP 8.0] Named arguments

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4155]
# Feature Request

Downgrade new feature from PHP 8.0 to its equivalent PHP 7.4 code.

Diff example taken from [here](https://stitcher.io/blog/php-8-named-arguments).
 
## Diff 

```diff
-setcookie(
-    name: 'test',
-    expires: time() + 60 * 60 * 2,
-);
+setcookie(
+    'test',
+    '',
+    time() + 60 * 60 * 2,
+);
```

**Comment by TomasVotruba** [comment]
Closing as not required by any active project at the moment. Let's narrow scope and focus on relevant PHP versions, 7.1 and 7.2, that Rector now needs to downgrade.
