### ISSUE TITLE
[Downgrade PHP 8.0] Concatenation precedence

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4161]
# Feature Request

Downgrade new feature from PHP 8.0 to its equivalent PHP 7.4 code. [RFC with explanation](https://wiki.php.net/rfc/concatenation_precedence)
 
## Diff 

```diff
-echo "sum: " . $a + $b;
+echo ("sum: " . $a) + $b;
```

**Comment by TomasVotruba** [comment]
This is related to tokens, not AST. There is nothing we can do in Rector scope.

It can be only handled by php-cs-fixer rule. Possibly space for external package.
