### ISSUE TITLE
[Downgrade PHP 7.3] Trailing commas in function calls

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4168]
# Feature Request

Downgrade new feature from PHP 7.3 to its equivalent PHP 7.2 code
 
## Diff 

```diff
$compacted = compact(
    'posts',
-    'units',
+    'units'
);
```

**Comment by quisse** [comment]
After some digging I can conclude that this is not possible using php-parser because php-parser isn't aware of the trailing comma AFAIK.
Any help would be appreciated.

**Comment by TomasVotruba** [comment]
Closed by https://github.com/rectorphp/rector/pull/4273,

merged in https://github.com/rectorphp/rector/pull/4796
