### ISSUE TITLE
[Downgrade PHP 7.2] Abstract method overriding

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4170]
# Feature Request

Downgrade new feature from PHP 7.2 to its equivalent PHP 7.1 code. [Feature description](https://www.php.net/manual/en/migration72.new-features.php#migration72.new-features.abstract-method-overriding)
 
## Diff 

```diff
abstract class A
{
    abstract function test(string $s);
}
abstract class B extends A
{
-    // overridden - still maintaining contravariance for parameters and covariance for return
-    abstract function test($s) : int;
+    /**
+     * @return int
+     */
+    abstract function test(string $s);
}
```

**Comment by TomasVotruba** [comment]
Already part of sub issue https://github.com/rectorphp/rector/issues/4421
