### ISSUE TITLE
[Downgrade PHP 7.2] Trailing comma for grouped namespaces

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4171]
# Feature Request

Downgrade new feature from PHP 7.2 to its equivalent PHP 7.1 code. [Feature description](https://www.php.net/manual/en/migration72.new-features.php#migration72.new-features.trailing-comma-in-grouped-namespaces)
 
## Diff 

```diff
-use Foo\Bar\{
-    Foo,
-    Bar,
-    Baz,
-};
+use Foo\Bar\Foo;
+use Foo\Bar\Bar;
+use Foo\Bar\Baz;
```

**Comment by TomasVotruba** [comment]
This is rather edge case only seen to be examples. Closing now so we can focus on common code.

We can deal with it later, if it's reported.
