### ISSUE TITLE
getrector.org/demo broken

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4173]
# Bug Report

Plain source code with `function_exists()` seems not to work in getrector.org/demo. 

```
<?php
function d() {}

if (!function_exists('d')) {
	function d() {}
}

d();
```
See (not working) getrector.org/demo here:

https://getrector.org/demo/acf76090-c0ab-4e95-83f1-0c7ed7897568#result

## Expected Behaviour

Some output

## Actual Behaviour

500 Internal Server Error

**Comment by TomasVotruba** [comment]
It seems the whole demo is down:
https://getrector.org/demo/3e518ef6-fa6d-4cbc-a6b9-98133a91cfc1#result

**Comment by powtac** [comment]
I tested some of the demos while seeing this 500. Back then the demo itself seemed to work. Maybe results were cached when I hit em multiple times ...

**Comment by TomasVotruba** [comment]
The Rector version is broken for some reason.

One of attempt to fix:
https://github.com/rectorphp/getrector.org/pull/174

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/getrector.org/pull/177

Thanks to @JanMikes :cla

**Comment by powtac** [comment]
Again broken. See https://getrector.org/demo/47334dd1-e0bc-4f06-8f23-8546d7d67f63

![grafik](https://user-images.githubusercontent.com/36167/104380354-2d7c2f00-552b-11eb-8ba4-7536445f54b6.png)

**Comment by TomasVotruba** [comment]
cc @JanMikes Hi Honza, could you look into this?

**Comment by JanMikes** [comment]
@TomasVotruba seems like some BC break was done, actually it fails on `File path "/project/composer.json" was not found` which is correct, there is no composer.json and there never was any. Any idea which commit could break this?

Command that is run in demo and it did NOT Needed composer.json and now it does need it, any idea why?

```
rector \
    process /project/rector_analyzed_file.php \
    --autoload-file /project/rector_analyzed_file.php \
    --output-format json \
    --config /project/rector.php
```

**Comment by TomasVotruba** [comment]
@JanMikes  Thanks for super fast reply!

composer json bug will be probably related to yesterday midnight merge of: https://github.com/rectorphp/rector/pull/5161

cc @lulco Could you check it?

**Comment by TomasVotruba** [comment]
@lulco I'm quickly looking into it. I guess this line should be skipped if `composer.json` file not found: https://github.com/rectorphp/rector/pull/5074/files#diff-6ac00ca5ab4c40e2d2ed6f061d33c2af8d3304ca791183fadc6377c63a014873R54

**Comment by lulco** [comment]
@TomasVotruba PR added

**Comment by TomasVotruba** [comment]
Demo is back :tada: 


@powtac To your comments issue, it still remains This is known problem, that will be only fixed by format preserving printer.  See https://github.com/rectorphp/rector/issues/4334
