### ISSUE TITLE
Downgrade sets must be executed in order from higher to lower PHP versions

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4176]
# (Potential) Bug Report

When executing downgrade sets, they can be executed in any order, such as:

```php
$parameters->set(Option::SETS, [
  SetList::DOWNGRADE_PHP74,
  SetList::DOWNGRADE_PHP80,
  SetList::DOWNGRADE_PHP73,
  SetList::DOWNGRADE_PHP72,
]);
```

However, the downgrading must be executed in order from higher to order PHP versions:

- First all PHP 8.0 rules
- Then all PHP 7.4 rules
- Then all PHP 7.3 rules
- ...

This is because, for instance, `??=` in 7.4 downgrades to `??` from 7.3, which can itself be downgraded to `isset` in 7.0. Then, executing sets like this:

```php
$parameters->set(Option::SETS, [
  SetList::DOWNGRADE_PHP70,
  SetList::DOWNGRADE_PHP74,
]);
```

... could leave a `??` behind (result from downgrading `??=`) that was not downgraded to `isset`

**Comment by leoloso** [comment]
Maybe this could be solved by having sets of sets. For instance, set `downgrade-php80-to-php72` would execute sets `downgrade-php80`, `downgrade-php74` and `downgrade-php73`

**Comment by TomasVotruba** [comment]
This is rather implicit/logical upgrade knowledge for any versioned sets.

If you'd migrate manually from Symfony 3, you would probably not read Symfony 5.3 upgrade guide, but go one minor version after another 3.0, 3.1 .

Might be worth mentioning in docs, but I don't think so. Closing.
