### ISSUE TITLE
Debug output with annoying whitespace gap

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4187]
# Bug Report

Console output via `-vvv` does not properly align `[refactoring]` and `[applying]`.

```
[refactoring] /thirdparty/Zend/Locale/Math/PhpMath.php
    [applying] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[refactoring] /thirdparty/Zend/Log.php
    [applying] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[refactoring] /thirdparty/Zend/Log/Exception.php
[refactoring] /thirdparty/Zend/Log/Filter/Interface.php
    [applying] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[refactoring] /thirdparty/Zend/Log/Filter/Message.php
```

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.x-dev@172653b              |
| Installed as   | prefixed Rector PHAR                      |

## Expected Behaviour

Align console debug output somehow properly.

**Comment by TomasVotruba** [comment]
This is on porpuse, as many rules can be applied to single file and in log of dozens of files this is hard to spot.

```
[****] /thirdparty/Zend/Locale/Math/PhpMath.php
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] /thirdparty/Zend/Locale/Math/PhpMath.php
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
[****] Rector\Php70\Rector\FunctionLike\Php4ConstructorRector
```

If you need to remove the spaces for some work with the output in anothe tool, regex `^(\s+)\[` should do

**Comment by powtac** [comment]
Ah, I've just understood the comment in https://github.com/rectorphp/rector/blob/7ac228c638949a69289473b7f36670aad80beef0/src/Rector/AbstractRector.php#L365 the other way...

**Comment by TomasVotruba** [comment]
I see. Maybe the name is confusing.

How could we rename the "refactoring" or "appliing" so it's more clear?
