### ISSUE TITLE
MultipleClassFileToPsr4ClassesRector deletes none class files

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4190]
# Bug Report

"Simple" PHP files that do not contain a class/interface/trait/... will be deleted by the MultipleClassFileToPsr4ClassesRector rule.

https://getrector.org/demo/a362d9f8-828d-428b-945a-f6e21df33908#result

## Expected Behaviour

"Simple" PHP files should be not touched by this rule.

**Comment by TomasVotruba** [comment]
We need failing test case for this

**Comment by powtac** [comment]
Maybe this is the issue: something like `and not in global namespace` is missing!

https://github.com/rectorphp/rector/blob/f2ecdeb0b1f13093de23a6bb668998c9cdea73e5/rules/psr4/src/Rector/MultipleClassFileToPsr4ClassesRector.php#L178

**Comment by TomasVotruba** [comment]
It might. Could you add test case to cover it?

**Comment by samsonasik** [comment]
It seems already fixed in latest master https://getrector.org/demo/d6ac3924-bec3-4f10-966d-4b9716e4e9d6#result . I am closing it.
