### ISSUE TITLE
[Downgrade PHP 7.1] iterable pseudo-type

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4195]
# Feature Request

Downgrade new feature from PHP 7.1 to its equivalent PHP 7.0 code. [Feature description](https://www.php.net/manual/en/language.types.iterable.php)

Docblock tags should be converted to `array|\Traversable`, not to `iterable`. From the description:

> It accepts any array or object implementing the Traversable interface
 
## Diff 

```diff
class SomeClass
{
-    public function run(iterable $iterator): iterable
+    /**
+     * @param array|\Traversable $iterator
+     * @return array|\Traversable
+     */
+    public function run($iterator)
     {
     }
}
```

**Comment by norberttech** [comment]
Hey, just want to confirm one thing. 
Currently the behavior of translating param/return type `iterable` into the docblock looks like this:

```
* @param mixed[] $iterator
```

and it should be changed into:

```
@param array|\Traversable $iterator
```

?

**Comment by leoloso** [comment]
In [the description](https://www.php.net/manual/en/language.types.iterable.php#language.types.iterable), it says that an iterable is either:

- an array
- an object implementing the `Traversable` interface

Hence, when downgrading, we do not know which of these 2 options the downgraded code is, and to be safe we add both of them: `array|\Traversable`

**Comment by norberttech** [comment]
ok so the current behavior should stay as it is and only when downgrading we should change `iterable` into `array|\Traversable` correct? 

btw. `array` or maybe `mixed[]`? Not sure which one is preferred

**Comment by leoloso** [comment]
> ok so the current behavior should stay as it is and only when downgrading we should change `iterable` into `array|\Traversable` correct?

Just the signature of the method must change: remove any `iterable` return or param type declaration, and add the docblock with `array|\Traversable` in its place.

Btw, there are plenty several rules doing some version of this, such as [`DowngradeParamObjectTypeDeclarationRector`](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#downgradeparamobjecttypedeclarationrector) and [`DowngradeReturnObjectTypeDeclarationRector`](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#downgradereturnobjecttypedeclarationrector).

> btw. array or maybe mixed[]? Not sure which one is preferred

Maybe `mixed[]` is better, so that PHPStan doesn't give a warning on it (even though, even if it does, we shouldn't care so much for downgraded code, which we already knows works well)

**Comment by norberttech** [comment]
Yeah I figured out that `mixed[]` might be better, #4649 should do the job

**Comment by TomasVotruba** [comment]
Thank you @norberttech 

Merged rebased in https://github.com/rectorphp/rector/pull/4706
