### ISSUE TITLE
Remove PHP closing tag

### ISSUE THREAD

**Issue by BenMorel** [rectorphp/rector#4201]
# Feature Request

It would be nice if Rector had a rule to remove the optional closing PHP tag `?>` when it ends a script!
 
## Diff 

```diff
-?>
(EOF)
```

**Comment by TomasVotruba** [comment]
Hi,

thanks for the idea.

This is already covered by php-cs-fixer with [`NoClosingTagFixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/bb9f72904497cea78b59faa3abeca21aaa5390a5/src/Fixer/PhpTag/NoClosingTagFixer.php#L26)

Use [ECS](https://github.com/symplify/easy-coding-standard) with `NoClosingTagFixer` and it will have the effect you need
