### ISSUE TITLE
[DX] Change phpversion from string to php constant int type 

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4205]
## Tasks

- Change features types we use in 
https://github.com/rectorphp/rector/blob/master/src/ValueObject/PhpVersionFeature.php
into PHP integers

- update related behaviors in 
    - https://github.com/rectorphp/rector/blob/88d57114364c1f86b7a46cbb3e0dcf06838e8389/src/Rector/AbstractRector.php#L266-L269
    - https://github.com/rectorphp/rector/blob/88d57114364c1f86b7a46cbb3e0dcf06838e8389/src/Php/PhpVersionProvider.php

---

E.g. `70400`

<br>

This way here could re-used another numeric value.

What do you think?

...

`70400` <= I like it, it simplifies the comparison, and you can directly check against `PHP_VERSION_ID`.

Better doing `-1` instead of `-0.1` then it's always an `int`:

```php
public const BEFORE_NULLABLE_TYPE = NULLABLE_TYPE - 1;
```

_Originally posted by @TomasVotruba amd @leoloso in https://github.com/rectorphp/rector/pull/4192#discussion_r487393083_

**Comment by TomasVotruba** [comment]
@samsonasik Hi, could you take this as one of next tasks? 
What information do you need to start?

Thank you

**Comment by samsonasik** [comment]
@TomasVotruba is string '7.4' need to be changed to 70400 ?

**Comment by samsonasik** [comment]
I will try
