### ISSUE TITLE
Is it possible to tell the rector not to apply any implicit rules?

### ISSUE THREAD

**Issue by naex** [rectorphp/rector#4223]
# Question
Hi,
my problem with rector is, that I am not able to process ONLY my own rules. If I try tu run rector with the default setup, it changes all class usages with fully qualified names. So I tried to set option Option::AUTO_IMPORT_NAMES to true in the rector.php file, but rector in this case tries to demage imports as follows:

```
-use Carbon\Carbon;
-use Illuminate\Database\Eloquent\Builder;
+use Carbon;
+use Builder;
```

Another annoying thing is that rector implicitly tries to format multi-line code to a single line.
For example:

```
-                    $this->logger->logSuccess($user, 'Everything is OK', [
-                        'key' => $key,
-                    ]);
-
+                    $this->logger->logSuccess($user, 'Everything is OK', ['key' => $key]);
```
Is there any way to switch off these implicit rules and tell the rector not to apply any implicit rules?

Thanks for the reply

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting these. One of them is bug, the other is limitation of AST technology. 

> but rector in this case tries to demage imports as follows:

This should not happen. We need minimal demo to reproduce this - https://getrector.org/demo

> that rector implicitly tries to format multi-line code to a single line

Abstract Syntax Tree we use here cannot handle this, that's why coding standard is needed. You can read more about it here:
https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by naex** [comment]
Unfortunately I am not able to run the demo with my configuration. :(
https://getrector.org/demo/783d2176-1349-430c-891f-fb8c038b31d5
Result:
Warning: proc_open() has been disabled for security reasons in /rector/vendor/symfony/console/Terminal.php on line 162 Warning: proc_open() has been disabled for security reasons in /rector/vendor/symfony/console/Terminal.php on line 162 Warning: proc_open() has been disabled for security reasons in /rector/vendor/symfony/console/Terminal.php on line 162 Warning: proc_open() has been disabled for security reasons in /rector/vendor/symfony/console/Terminal.php on line 162 In RectorGuard.php line 29: We need some rectors to run: * register them in rector.php under "services():" * use "--set <set>" * or use "--config <file>.yaml" process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--match-git-diff] [--only ONLY] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--output-file OUTPUT-FILE] [--cache-debug] [--clear-cache] [--] [<source>...]

**Comment by TomasVotruba** [comment]
It needs to be simplified to minimum PHP code. In the end should be around 10 lines of code.

We're unable to fix it without that

**Comment by naex** [comment]
My code in demo is:
```
<?php

declare(strict_types=1);

use Carbon\Carbon;

final class DemoFile
{
    public function run()
    {
		Carbon::parse('2012-01-01');
    }
}
```

Configuration is:
```
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
	
	$parameters->set(Option::AUTO_IMPORT_NAMES, true);
};
```

And the result is still:
```
Warning: proc_open() has been disabled for security reasons in /rector/vendor/symfony/console/Terminal.php on line 162 Warning: proc_open() has been disabled for security reasons in /rector/vendor/symfony/console/Terminal.php on line 162 Warning: proc_open() has been disabled for security reasons in /rector/vendor/symfony/console/Terminal.php on line 162 Warning: proc_open() has been disabled for security reasons in /rector/vendor/symfony/console/Terminal.php on line 162 In RectorGuard.php line 29: We need some rectors to run: * register them in rector.php under "services():" * use "--set <set>" * or use "--config <file>.yaml" process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--match-git-diff] [--only ONLY] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--output-file OUTPUT-FILE] [--cache-debug] [--clear-cache] [--] [<source>...]
```

**Comment by TomasVotruba** [comment]
3rd party classes can't be used, as it means there is full `/vendor` dependency.

The Carbon class has to be changed into your own cummy class that simulates minimal behavior.

Somethign like this:

```php
class CustomCarbon
{
    public static function parse(...)
    {
        // some minimal code that leads to fail
    }
}


final class DemoFile
{
    public function run()
    {
		CustomCarbon::parse('2012-01-01');
    }
}
```

**Comment by TomasVotruba** [comment]
I made a sandbox code for you, so you can just edit it with your own code:
https://getrector.org/demo/d53474d0-d083-45f0-85d9-ac1d0219dd45#result

Update the code snippet and hit "Process" button

**Comment by TomasVotruba** [comment]
Thank you for your time. We're unable to reproduce without failing demo or failing test case - here is how you add a test case: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

Closing as stale.
