### ISSUE TITLE
Unable to install with PHPUnit 6

### ISSUE THREAD

**Issue by LarryBarker** [rectorphp/rector#4230]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.6              |
| Installed as   | composer dependency                      |

Just trying to install this for the first time to run the `phpexcel-to-phpspreadsheet` set on a single file. `composer require rector/rector` fails:
![image](https://user-images.githubusercontent.com/28734844/93281323-798fb080-f791-11ea-908d-59595ada6b22.png)

I also tried copying the single file to a new directory, and running the command there but am faced with another error about autoloading and parameters:

```
 Could not process "src/ExcelController.php" file, due to:
         "Analyze error: "Class app\controllers\ExcelController was not found
         while trying to analyse it - discovering symbols is probably not
         configured properly.". Include your files in "parameters >
         autoload_paths".
         See https://github.com/rectorphp/rector#extra-autoloading".
```

## Minimal PHP Code Causing Issue

None available.

## Expected Behaviour

Would like to be able to run `vendor/bin/rector process ExcelController.php --set phpexcel-to-phpspreadsheet` and migrate from PHPExcel to PHPSpreadsheet with minimal downtown.

**Comment by TomasVotruba** [comment]
Hi, 

in case of conflicts, you need to use prefixed version:
See https://github.com/rectorphp/rector#install
