### ISSUE TITLE
How is the execution of a rule invoked inside the tests?

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4232]
For example: in `rules/psr4/tests/Rector/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php`, the method `test()`, as far as I can see, simply prepares test files in [line 23](https://github.com/rectorphp/rector/blob/master/rules/psr4/tests/Rector/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php#L23) and then just after that does the assertions starting in [line 26](https://github.com/rectorphp/rector/blob/master/rules/psr4/tests/Rector/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php#L26). But I don't see where the Rule is applied here!? 

I did some research up to [`AbstractKernelTestCase`](https://github.com/symplify/symplify/blob/master/packages/package-builder/src/Tests/AbstractKernelTestCase.php) but still I have no clear idea how/where the corresponding Rule from getRectorClass is invoked or executed. Especially in the context of "just" a simple call of `doTestFileInfo()` in the unit test.

Related to https://github.com/rectorphp/rector/issues/4190#issuecomment-691249841

**Comment by TomasVotruba** [comment]
Hi,

it's in the first parent or the test file.

![Screenshot_20200916-144240](https://user-images.githubusercontent.com/924196/93338678-e7d48180-f82a-11ea-99e0-c9adf69e16db.png)

This line
https://github.com/rectorphp/rector/blob/4f1beae3fd36f184be29bf5b598d26ea1e98b7cd/src/Testing/PHPUnit/AbstractFileSystemRectorTestCase.php#L67

**Comment by powtac** [comment]
Is there a way to run tests on multiple files eg folders ?

**Comment by TomasVotruba** [comment]
In iteration, e.g `foreach ($fileInfos as $fileInfo) ...`

**Comment by TomasVotruba** [comment]
I'm curious :) What you working on?

**Comment by powtac** [comment]
I try to setup a test case for https://github.com/rectorphp/rector/issues/4190#issuecomment-691249841. Where a folder with muliple files are processed. As mentioned in #4190, the rule seems to delete files ...

**Comment by TomasVotruba** [comment]
I see.

How do you know that you need at least 2 files to test it? The rule seems to work even on single file.

**Comment by powtac** [comment]
I suspect that the rule uses some sort of "collector" to match found file names to found class names. Then the "retification" starts and  what was not found will be deleted...

**Comment by TomasVotruba** [comment]
I see. It could be the case. 
I'd like to help you more, but actually, I haven't use this rule for a while, so I have no idea how it works inside.

**Comment by powtac** [comment]
Hm, you also can see here that content is about to be deleted:
https://getrector.org/demo/d8044ada-5466-450f-88d5-22138384a324#result
Not sure though if it really is related to multiple files on directories.

**Comment by powtac** [comment]
> 
> 
> I see. It could be the case.
> I'd like to help you more, but actually, I haven't use this rule for a while, so I have no idea how it works inside.

I will try to do a test with a single file first, that proves the lost code.

**Comment by TomasVotruba** [comment]
Closing as answered
