### ISSUE TITLE
mysql_query to mysqli_query parameter error

### ISSUE THREAD

**Issue by Dimas-sc** [rectorphp/rector#4233]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.8.6              |
| Installed as   | composer dependency                      |

I migrating PHP 5.6 code to PHP 7.4 and trying to apply the set mysql-to-mysqli it don't work with mysql_query conversion
I execute: vendor/bin/rector process /var/www/cdr/formPulmo.php --dry-run --set=mysql-to-mysqli

## Minimal PHP Code Causing Issue

-            $res = mysql_query("INSERT INTO ".$formulari." (uidComu, imatge, edat, fumador, simptomalogia) VALUES
-           ($idComu, '" . $_POST['imatge'] . "', '" . $_POST['edat'] . "', '" . $_POST['fumador'] . "', '$simptomalogia')", $link) or die (mysql_error());

translates to

+          $res = mysqli_query($res, $link, "INSERT INTO ".$formulari." (uidComu, imatge, edat, fumador, simptomalogia) VALUES
+           ($idComu, '" . $_POST['imatge'] . "', '" . $_POST['edat'] . "', '" . $_POST['fumador'] . "', '$simptomalogia')") or die (mysqli_error($res));

## Expected Behaviour
mysqli_query should have only one parameter before the query, and the good one is $link, not $res. The same with mysqli_error().

+          $res = mysqli_query($link, "INSERT INTO ".$formulari." (uidComu, imatge, edat, fumador, simptomalogia) VALUES
+           ($idComu, '" . $_POST['imatge'] . "', '" . $_POST['edat'] . "', '" . $_POST['fumador'] . "', '$simptomalogia')") or die (mysqli_error($link));

**Comment by TomasVotruba** [comment]
Hi, could you add failing test fixture to responsible rule?

**Comment by Dimas-sc** [comment]
> Hi, could you add failing test fixture to responsible rule?

Sorry, could you explain me how to do it?

**Comment by TomasVotruba** [comment]
Sure.

- 1. Find the responsible rule - right in the `vendor/bin/rector` output under the diff

- 2. Find it's tests - RuleName + "Test"

- 3. There is `/Fixture` directory

- 4. Add minimal before/after PHP code to the `/Fixture` directory, that causes the bug


This is example of such failing test case: https://github.com/rectorphp/rector/pull/2700/files

**Comment by simivar** [comment]
I've tried to reproduce the issue and only one I found out is the one ine #4793. I don't know if that's the one you meant @Dimas-sc. As there was no response for 3 months in this issue I am closing it. Feel free to re-open the issue if it's not the one in PR I provided but please remember to attach failing example.
