### ISSUE TITLE
Dockerized rector does not seem to work properly

### ISSUE THREAD

**Issue by rgeraads** [rectorphp/rector#4234]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.x-dev              |
| Installed as   | docker container                      |

When I run the following command:
```
docker run -v $(pwd):/project rector/rector:latest process /project/src --set symfony40 --dry-run
```
or 
```
docker run -v $(pwd):/project rector/rector:latest process /project/src --set symfony40 --dry-run --autoload-file /project/vendor/autoload.php
```
https://github.com/rectorphp/rector#run-rector-in-docker

I get a lot of the following errors. e.g.:
```
 [ERROR] Could not process                                                      
         "../project/src/User/UserService.php" file, due to:  
         "Analyze error: "Class                                                 
         User/User not found.". Include 
         your files in "parameters > autoload_paths".                           
         See https://github.com/rectorphp/rector#extra-autoloading".  
```

The code itself works, so autoloading is set up correctly.

Am I doing something wrong? or is the docker container not working properly?

**Comment by TomasVotruba** [comment]
Hi,

it seems like classic bug with Docker vs project vs PHAR paths.

How successful are you with using `rector.php` and setting autoload paths in it?

**Comment by rgeraads** [comment]
I tried the following rector.php:
```
<?php

// rector.php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    // here we can define, what sets of rules will be applied
    $parameters->set(Option::SETS, [SetList::CODE_QUALITY]);

    $parameters->set(Option::AUTOLOAD_PATHS, [
        // autoload specific file
        __DIR__ . '/vendor/autoload.php',
    ]);

    // get services
    $services = $containerConfigurator->services();

    // register single rule
    $services->set(TypedPropertyRector::class);
};
```

And I ran:
```
docker run --rm -v $(pwd):/project rector/rector:latest process /project/src \
    --config /project/rector.php \
    --autoload-file /project/vendor/autoload.php \
    --dry-run
```

But it gave the same errors.

**Comment by TomasVotruba** [comment]
I see, thanks for trying it.
My knowledge is very limited with Rector in Docker. Maybe @JanMikes might help

**Comment by phazei** [comment]
I'm having the exact same issue.  Going to attempting rector-prefixed instead.

**Comment by JanMikes** [comment]
Hi, i will try to investigate.

**Comment by JanMikes** [comment]
Hi, i was able to reproduce the error, without using `--autoload-file` option:

```
❯ docker run -v $(pwd):/project rector/rector:latest process /project/projects/car-audit/src/App/Controller/GetCarAuditStructureController.php --set symfony40 --dry-run 
Rector dev-master@c4cedab

 0/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%


 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% [ERROR] Could not process                                                      
         "../project/projects/car-audit/src/App/Controller/GetCarAuditStructureC
         ontroller.php" file, due to:                                           
         "Analyze error: "Class                                                 
         Carvago\CarAudit\App\Controller\GetCarAuditStructureController was not 
         found while trying to analyse it - discovering symbols is probably not 
         configured properly.". Include your files in "parameters >             
         autoload_paths".                                                       
         See https://github.com/rectorphp/rector#configuration".                
```

With `--autoload-file /project/vendor/autoload.php` the problem is fixed:
```
❯ docker run -v $(pwd):/project rector/rector:latest process /project/projects/car-audit/src/App/Controller/GetCarAuditStructureController.php --set symfony40 --dry-run --autoload-file /project/vendor/autoload.php
Rector v0.8.7@869441e

 0/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 2/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [OK] Rector is done!   
```

So i am not able to reproduce the error exactly the way you do 😞 

Please is it possible create github repository with minimal code that will break?

All you would need is just composer.json with autoloading and `src/SomeClass.php` with just `class SomeClass { }` and trying to analyse it if it works?

Now from my point of view, there might be broken autoloading in your project and might not be issue with rector in docker at all. In order to fix the issue i must be able to reproduce it, which so far i was not successful.

**Comment by JanMikes** [comment]
Please, can you try running with testing image `rector/rector:docker-autoload-fix` with little improvements, if it somehow fixed your issues?

Please try this command (as well it is possible instead of processing whole `src` to start with just single file like i did in previous comment):
```
docker run -v $(pwd):/project rector/rector:docker-autoload-fix process src --set symfony40 --dry-run
```

**Comment by rgeraads** [comment]
I did a docker pull today, and now `docker run -v $(pwd):/project rector/rector:latest process /project/src --set symfony40 --dry-run --autoload-file /project/vendor/autoload.php
` is working!

```
docker run -v $(pwd):/project rector/rector:latest --version                                                                                  
Rector dev-master@c4cedab
```

`docker run -v $(pwd):/project rector/rector:docker-autoload-fix process src --set symfony40 --dry-run` is working for me without having to specify the autoload file!
