### ISSUE TITLE
Canonicalize class constants

### ISSUE THREAD

**Issue by alister** [rectorphp/rector#4235]
# Feature Request

Where a class constant is referenced via a specific class, but it was defined in a parent class, then use the class where it was defined as its 'official' or 'canonical' name.

Example: https://getrector.org/demo/e41ad11a-456e-4fdf-81a4-55dc44a4ca5b

The canonical name of the constant `TEST` is `A::TEST`.  It can also be used as `B::TEST`.  If class 'B' is changed so that it no longer extends 'A' (for example, removing A to flatten a class hierarchy, such as removing a 'base' controller, or service class), then B::TEST would not be able to be found.  It can also be difficult to search for, as it would be expected to be `A::TEST` everywhere.

The feature would be to change the reference from `B::TEST` to `A::TEST` (unless a more local definition exists).

I often see this simpler example in Symfony code:

```php
use Symfony\Component\Routing\RouterInterface;  // or Router::

$url = $this->generateUrl('route_name', [], RouterInterface::ABSOLUTE_PATH);
```
`RouterInterface` does not define that constant. The actual (and only) definition of it is: `\Symfony\Component\Routing\Generator\UrlGeneratorInterface::ABSOLUTE_PATH`.

I came across these issues when refactoring some older Symfony code that had a couple of parent class levels for controllers or services. These base-services had constructors, properties (usable by the hierarchy below them), and constants. The constants had evolved over time and were being referenced by various class-names, not all of which were the defining class (So - as B::constant, not the A::constant where they were defined).  

```
$class = B::class;    // B::TEST used in code
$reflectConstant = new \ReflectionClassConstant($class, 'TEST');
$constDeclaredOnClass = $reflectConstant->getDeclaringClass()->getName();
if ($constDeclaredOnClass !== $class) {
    // "'TEST' Should be used as A::TEST, actually used as {$class}::TEST";
```

**Comment by TomasVotruba** [comment]
Hi,

thanks for the idea. I have troubles understanding the idea and the problem/bug? I haven't not came across this problem myself.

What PHP version is it related to?

Could you put it in PHP only minimal code diff?

```diff
-before
+after
```

**Comment by alister** [comment]
I think a complete, but (very) simple, example would be like this:
```diff
class A
{
    protected const TEST = 1;
}

class B extends A
{
    public function something() {
-        echo B::TEST;
+        echo A::TEST;
    }
}
```

or for the Symfony Routing example:

```diff
-$url = $this->generateUrl('route_name', [], RouterInterface::ABSOLUTE_PATH);
+$url = $this->generateUrl('route_name', [], \Symfony\Component\Routing\Generator\UrlGeneratorInterface::ABSOLUTE_PATH);
```

**Comment by TomasVotruba** [comment]
Sorry for late reply, I got caught up in new Rector release.

This could be part code quality set. 

We don't have it on priority list. Would you like to contribute this or shall I close the issue?

**Comment by alister** [comment]
I'm going to give it a look, and see what I can do.

**Comment by TomasVotruba** [comment]
Thank you

**Comment by TomasVotruba** [comment]
This feature will be accepted, when PR is ready.

Closing to cleanup issue pipe-line and keep only active relevant problems here.

Thank you
