### ISSUE TITLE
Not recognized syntax: $model

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#4239]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.6              |
| Installed as   | composer dependency                      |

> Could not process "tests/Model/ModelSmokeTest.php" file, due to:                                               
>         "Pick more specific node than "PhpParser\Node\Expr\MethodCall", e.g. "$node->name"                             
>
> Caused in "tests/Model/ModelSmokeTest.php" file:88 on code "$method->getName()"                                
>
> Look at                                                                                                        
>         vendor-bin/phpstan/vendor/rector/rector/rules/php70/src/Rector/FuncCall/NonVariableToVariableOnFunctionCallRect
>         or.php:76". 

## Minimal PHP Code Causing Issue

Unrecognized syntax:

```php
$model->{$method->getName()}();
```

https://getrector.org/demo/cfe97677-72df-43c9-b250-e831e4e65900

## Expected Behaviour

The syntax is recognized.

## Workaround

Use a more verbose syntax:

```php
$method = $method->getName();
$model->$method();
```

**Comment by TomasVotruba** [comment]
Thanks for reporting.

Could you make the demo minimal code that fails? It should be round 2-3 lines that causes this.
It's hard to read now.

**Comment by mssimi** [comment]
@TomasVotruba I will take it, how can I assign myself?

**Comment by TomasVotruba** [comment]
:+1: 

I usually use "Control + F" on the page I'm on.

![image](https://user-images.githubusercontent.com/924196/93532326-180e4400-f941-11ea-811c-2f934295a165.png)

**Comment by TomasVotruba** [comment]
Btw, could you finish the test of cache invalidation first? Just so we have just one thign at a time

**Comment by mssimi** [comment]
Ok, I see it now, I had no right. Let's call about cache later.

**Comment by Aerendir** [comment]
> Could you make the demo minimal code that fails? It should be round 2-3 lines that causes this.
It's hard to read now.

@TomasVotruba , done: now should be more readable...
