### ISSUE TITLE
[Naming] Add param naming convention related to bool params

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4240]
To prevent these:

![image](https://user-images.githubusercontent.com/924196/93376442-e4a4ba00-f859-11ea-901f-8031d90e3895.png)

Follow up to https://github.com/rectorphp/rector/pull/4215

## Example

```diff
-public function someMethod(bool $name)
+public function someMethod(bool $isName)
 {
-   $this->isName = $name;
+   $this->isName = $isName;
 }
```

We make an assumption choice on is/has/was, but it's the only thing we can do.

**Comment by TomasVotruba** [comment]
@dobryy You might enjoy this :)

**Comment by dobryy** [comment]
```diff
-bool $enableCache,
+bool $isCacheEnabled,
```
Are you kidding me? :D This case is damn tricky!

**Comment by dobryy** [comment]
Do not forget about https://github.com/rectorphp/rector/pull/4242#discussion_r489739962

**Comment by TomasVotruba** [comment]
Not priority ATM
