### ISSUE TITLE
ReturnTypeDeclarationRector not working

### ISSUE THREAD

**Issue by mohdimran-3pg** [rectorphp/rector#4247]
# Question
Hi Team,

When i set `$services->set(ReturnTypeDeclarationRector::class);` this rule in rector.php and run `vendor/bin/rector process myproject/api/app/controllers --dry-run`
I am getting following errors.

<img width="388" alt="Screenshot 2020-09-17 at 2 30 41 PM" src="https://user-images.githubusercontent.com/50764249/93449098-f5a10a00-f8f1-11ea-8151-dc7aaefd9963.png">

I am also attaching my rector.php screenshot file here.

<img width="821" alt="Screenshot 2020-09-17 at 2 34 02 PM" src="https://user-images.githubusercontent.com/50764249/93449475-6cd69e00-f8f2-11ea-9d7e-58d178694fc7.png">

can you please help me what i am doing wrong here?

**Comment by mohdimran-3pg** [comment]
Thanks i have resolved the issue

**Comment by TomasVotruba** [comment]
Thanks for solving this!

Could you share where was the problem, in case somebody else will came across the same issue?
