### ISSUE TITLE
Wrong FQN for a rector (and maybe more)

### ISSUE THREAD

**Issue by Driky** [rectorphp/rector#4266]
# Bug Report

| The Rector `Php4ConstructorRector` has the wrong FQN associated to it in the list | `Rector\Php70\Rector\ClassMethod\Php4ConstructorRector` is wrong and should be replaced by `"Rector\Php70\Rector\FunctionLike\Php4ConstructorRector`|
| :------------- | :---------------------------------------------------------------|

## Minimal PHP Code Causing Issue
No need for a custom script. Simply try to call  Php4ConstructorRector using the FQN mentioned in the list.

## Expected Behaviour

Php4ConstructorRectoris called.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

I'm sure, where exactly is *the list*? Is that rector overview markdown file? Could you share a link, so we're both on the same page?

Thanks

**Comment by TomasVotruba** [comment]
Closing as stale
