### ISSUE TITLE
Crash on start: Class or interface 'PHPStan\Symfony\ServiceMapFactory' not found.

### ISSUE THREAD

**Issue by soullivaneuh** [rectorphp/rector#4268]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.7 |
| Installed as   | composer with composer bin plugin                 |

Rector immediately crash on start, even with `--version`:

```
e 54
sullivan@187971a0093c:/app$ vendor/bin/rector --version
Fatal error: Uncaught _HumbugBox10beb0db089e\Nette\InvalidArgumentException: Service 'symfony.serviceMapFactory': Class or interface 'PHPStan\Symfony\ServiceMapFactory' not found. in phar:///app/vendor-bin/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Definitions/Definition.php:52
Stack trace:
#0 phar:///app/vendor-bin/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php(46): _HumbugBox10beb0db089e\Nette\DI\Definitions\Definition->setType('PHPStan\\Symfony...')
#1 phar:///app/vendor-bin/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Extensions/ServicesExtension.php(67): _HumbugBox10beb0db089e\Nette\DI\Definitions\ServiceDefinition->setType('PHPStan\\Symfony...')
#2 phar:///app/vendor-bin/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Extensions/ServicesExtension.php(51): _HumbugBox10beb0db089e\Nette\DI\Extensions\ServicesExtension->updateServiceDefinition(Object(_HumbugBox10beb0db089e\Nette\DI\Definitions\ServiceDefini in phar:///app/vendor-bin/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Extensions/ServicesExtension.php on line 54
```

I'm not sure what information to give right now. Please ask me if needed! :+1:

**Comment by TomasVotruba** [comment]
Unfortunatelly, composer bin plugin install is not supported

Pick one of 3 options here: https://github.com/rectorphp/rector#install

**Comment by soullivaneuh** [comment]
@TomasVotruba Is this bug known with composer bin plugin ?

I'm quite surprised here, because composer bin plugin is just installing rector on a standalone folder with a composer.json inside.

**Comment by TomasVotruba** [comment]
I'm not sure. Check the older issues.

**Comment by TomasVotruba** [comment]
Here is why it can't be relied on: https://getrector.org/blog/2020/01/20/how-to-install-rector-despite-composer-conflicts
