### ISSUE TITLE
Annotation callback changed to const

### ISSUE THREAD

**Issue by maarekj** [rectorphp/rector#4274]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.7@869441e |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/96aa33a1-1472-40fa-b3f6-82914632e817#result

The callbacks in annotation are changed to const.
Example

```php
    /**
     * @Assert\Choice(callback={Invoice::class, "typeChoices"})
     */
    private ?string $type;
```

will be changed to
```php
    /**
     * @Assert\Choice(callback={Invoice::class, typeChoices})
     */
    private ?string $type;
```

## Expected Behaviour

Nothing has to be changed

**Comment by samsonasik** [comment]
It seems cause by `RemoveUnusedDoctrineEntityMethodAndPropertyRector` https://getrector.org/demo/6cdb5620-d9b0-4fe4-b1e4-7df900d40724#result

**Comment by samsonasik** [comment]
It seems happen in any rector rule, so the issue seems down to the `BetterStandardPrinter`

**Comment by TomasVotruba** [comment]
Same issue as in https://github.com/rectorphp/rector/issues/4573#issuecomment-725001430

**Comment by maarekj** [comment]
No, it is not the same issue.
Here, there is a bug in the application source code.

This:
`@Assert\Choice(callback={Invoice::class, "typeChoices"})`

is not equivalent to that
`@Assert\Choice(callback={Invoice::class, typeChoices})`

The second form is a bug with doctrine annotation parser. (syntax error)

**Comment by TomasVotruba** [comment]
The symptoms are different, but the issue is the same. Php doc printer not preserving the format.
