### ISSUE TITLE
[Generic] RenamePropertyRector doesn't handle conflicts and could cause problems with public and protected properties

### ISSUE THREAD

**Issue by dobryy** [rectorphp/rector#4276]
Follow-up https://github.com/rectorphp/rector/pull/4231#issuecomment-693667850

**Comment by dobryy** [comment]
@TomasVotruba Isn't it better to move this rule to Renaming set? If I do understand the idea correctly it doesn't belong to Naming.

**Comment by TomasVotruba** [comment]
Yes :+1:

**Comment by TomasVotruba** [comment]
Closing until this hypothetical case is reported in practise.
