### ISSUE TITLE
ArrayKeyExistsTernaryThenValueToCoalescingRector misbehaves

### ISSUE THREAD

**Issue by infabo** [rectorphp/rector#4286]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. 0.8.7            |
| Installed as   | composer dependency                       |

`ArrayKeyExistsTernaryThenValueToCoalescingRector` is applied where it should not.
The rectoreed code is not the same as before.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/a047e490-98e3-4796-bcbf-d6461a480f4b

## Expected Behaviour

`DemoFile->run()` should return `null` instead of `['value' => null]`.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting :+1:

**Comment by TomasVotruba** [comment]
More data on https://3v4l.org/X9id4
