### ISSUE TITLE
Any Rector PHAR call fails fails with error/exception (class \Migrify\PhpConfigPrinter\CaseConverter\AliasCaseConverter not found)

### ISSUE THREAD

**Issue by lptn** [rectorphp/rector#4294]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | master ([link](https://github.com/rectorphp/rector-prefixed/raw/master/rector.phar))            |
| Installed as   | prefixed Rector PHAR                      |

Any call fails with the following error:
```
 [ERROR] Expected to find class "Migrify\PhpConfigPrinter\CaseConverter\AliasCaseConverter" in file                     
         "phar:///tmp/rector.phar/vendor/migrify/php-config-printer/config/../src/
         CaseConverter/AliasCaseConverter.php" while importing services from resource                                   
         "phar:///tmp/rector.phar/vendor/migrify/php-config-printer/config/../src"
         , but it was not found! Check the namespace prefix used with the resource.                       
```

**Comment by lptn** [comment]
PS: can't we use GitHub assets as psalm do: https://github.com/vimeo/psalm/releases/latest

Pros: there is an evergreen link to the latest released .phar: https://github.com/vimeo/psalm/releases/latest/download/psalm.phar


As for this repo, we have to use .phar created from the master branch (which is not always stable): https://github.com/rectorphp/rector-prefixed/raw/master/rector.phar

**Comment by TomasVotruba** [comment]
Any idea why it's that happening?

> PS: can't we use GitHub assets as psalm do: vimeo/psalm/releases/latest ?

We can, we just need a contributor who would add them :)

**Comment by Denis-Sidorov** [comment]
Hi, this problem appears in 0.8.8.

**Comment by TomasVotruba** [comment]
Here is the link to failing Travis job: https://travis-ci.com/github/rectorphp/rector/builds/187090181#L627

I have no idea what is wrong wick phar packing. 
This file is not loading services for some reason: https://github.com/migrify/migrify/blob/3eaf5e8d93133e12f58156c040a9778abe69ada1/packages/php-config-printer/config/config.php#L25-L26

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector/commit/a71d3d2d2b9537ae2eb86b3999df4090380c5b1c
