### ISSUE TITLE
RenameStaticMethodRector produces relative namespace (missing slash at the beginning)

### ISSUE THREAD

**Issue by tmotyl** [rectorphp/rector#4295]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.8.10             |
| Installed as   | composer dependency             |

The code produced with RenameStaticMethodRector has relative namespace instead of absolute (the slash is missing at the beginning of the class namespace, which make the code invalid).

## Minimal PHP Code Causing Issue

See here:
https://github.com/rectorphp/rector/blob/master/rules/renaming/tests/Rector/StaticCall/RenameStaticMethodRector/Fixture/fixture2.php.inc

the code produced is:
```
$result = Nette\Bridges\FormsLatte\Runtime::renderFormBegin($someArgs);
```
but should be 
```
$result = \Nette\Bridges\FormsLatte\Runtime::renderFormBegin($someArgs);
```

We have similar case in typo3-rector 
see rector:
https://github.com/sabbelasichon/typo3-rector/blob/master/config/typo3-104.php#L20

And fixture (which is green now, but should be red):
https://github.com/sabbelasichon/typo3-rector/blob/master/tests/Rector/Core/Utility/Fixture/use-environment-api2.php.inc#L9

line 9 should be `\TYPO3\CMS\Core\Core\Environment::isRunningOnCgiServer();`

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

@samsonasik Could you check it?

**Comment by samsonasik** [comment]
@TomasVotruba is it related to `getNewClass()` method at https://github.com/rectorphp/rector/blob/master/rules/renaming/src/Rector/StaticCall/RenameStaticMethodRector.php#L99 ?
