### ISSUE TITLE
Proposal: Rename UnderscoreToCamelCaseLocalVariableNameRector to SnakeCaseToCamelCaseLocalVariableNameRector

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#4299]
Follows #4284

Based on https://twitter.com/votrubat/status/1309790554058887168?s=21

cc @samsonasik

**Comment by samsonasik** [comment]
@dobryy since you work at #4283 that related for Underscore to camel case, do you have opinion?

**Comment by dobryy** [comment]
@samsonasik I don't mind to rename it and it seems correct to me but at the same time when someone says `snake case` I don't get what is it immediately, I'm more used to `underscore`.

**Comment by TomasVotruba** [comment]
Underscore is naming is more clear naming here. 
Snake, camel and pascal require more investigation of what that exactly that means.

Closing following the principle of least surprise
