### ISSUE TITLE
Prepare Nette intro task for Eda

### ISSUE THREAD

**Issue by TomasVotruba** [RectorPHP/Rector#43]

**Comment by TomasVotruba** [comment]
Hey @EdoBarnas, before we start, have you looked at some rector rules?
E.g. this one could be easy to understand  https://github.com/RectorPHP/Rector/pull/66/files#diff-7c262fee93abbbb1dd81c32d77d886ad

**Comment by EdoBarnas** [comment]
It looks good. I think, that understand it. Do I have to something focus on?

**Comment by TomasVotruba** [comment]
Great :+1: 

Do you have an idea of rector that **would help you with your code** in Nette application?

**Comment by EdoBarnas** [comment]
I will think on a moment

**Comment by EdoBarnas** [comment]
Do you have any list with use cases? When i do mistake in english text, please corret me. Thanks. :)

**Comment by TomasVotruba** [comment]
> When i do mistake in english text, please corret me. Thanks. :)

Ok :) you can use "I" instead of "i". *E*nglish with capital.

---

Do you have any list with use cases? 

This could be nice to start with:
https://github.com/Kdyby/Doctrine/pull/298/files

I recall I had to do on many places manually.

**Comment by TomasVotruba** [comment]
Ref #81
