### ISSUE TITLE
Rector rule name convetion

### ISSUE THREAD

**Issue by dobryy** [rectorphp/rector#4301]
At the moment, we only require to have "Rector" word at the end of the name. 
My proposals are:

1.  Require one of the words above at the beginning of the name:

> rename
> make
> change
> replace
> remove
> add
> swap
> wrap
> move
> split

These are the most used in current rules, the list could be extended.
Or, we can require the words above as nouns (renamer, maker, changer, etc...)  before the word "Rector".

2. Require usage of the node type name from `getNodeTypes` (or last part of the namespace) method in the rule name.  
Sometimes node type doesn't mean that we are changing this particular node but the node within it. The example could be `RenamePropertyToMatchTypeRector` and many others. That is why we can simplify this proposal to require the name of any node type there is in PhpParser.

3. I noticed that there is a case when in one rule name we use "Arg" and in another "Argument". We can require to use some particular one form (e.g. Arg).  PS Didn't notice any other example after the quick check. 

Let me know what do you think.

**Comment by TomasVotruba** [comment]
Closing as overly detailed and not relevant at the moment
