### ISSUE TITLE
[Docs] FixUp commit for documentation

### ISSUE THREAD

**Issue by dobryy** [rectorphp/rector#4313]
I noticed that quite often we (I?) do forget to update the documentation.

Is there any reason to do not add fixup commit for documentation to CI?

**Comment by TomasVotruba** [comment]
We had it as part of CI, but it was rather annoying for new contributors. So we decided to do it once upon one remembmers. It's not perfect for us, but it makes people developing Rector more relaxed :)

Idealy... this should be automated by some external tool that would commit here once a day. Possibly some Github Actions.

**Comment by TomasVotruba** [comment]
Answered
