### ISSUE TITLE
Proposal: Create exceptions `DowngradeNotImplementedException` and `DowngradeNotPossibleException`

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4316]
# Feature Request

There are features from new PHP version that cannot be downgraded to a previous version, such as #4317, so we could throw `DowngradeNotPossibleException` whenever finding these features in the code.

There could also be features that can be downgraded, but we haven't done it yet (eg: because we disregarded that use case).

For instance, the downgrade rule from #4314 may be applied to a still-unsupported use case. Then, the rule could fail with throwing `DowngradeNotImplementedException`, and showing an error message asking the developer to add an issue for this new use case in the Rector repo.

If after analyzing the use case, we come to the conclusion that it cannot be downgraded, then we could throw a `DowngradeNotPossibleException`, explaining why this feature cannot be supported by previous PHP versions. This may well happen with annotations from PHP 8.0 (#4156)

Several exceptions could happen in a single run, so we could extract the message from all of them and show them all together once the run has ended.

**Comment by TomasVotruba** [comment]
This work for PHPStan rules. Better make standalone project

**Comment by leoloso** [comment]
Why PHPStan? This is purely about downgrading, not about validation of code.

`DowngradeNotPossibleException` I think is needed, as I explained in https://github.com/rectorphp/rector/issues/4324#issuecomment-738023936

Concerning `DowngradeNotImplementedException`, it would allow to implement certain downgrade rules in a partial manner. For instance, annotations cannot be naturally downgraded, but the annotation for deprecation can. So we can at least support that bit, and throw an error for everything else.

These are enabling features. I think you should consider reopening this

**Comment by TomasVotruba** [comment]
Because PHPStan is read-only and Rector write-only. This would mix features of both.

We can get back to it, after the known downgrade paths are covered.

**Comment by leoloso** [comment]
But if you close it, it will be out of sight, and we'll forget about it. Why don't we keep it open, and maybe add a label "low priority"? Or otherwise, if you want it close, what about adding a new column "Review later" on [the downgrades project](https://github.com/rectorphp/rector/projects/3) and place it there?

**Comment by TomasVotruba** [comment]
Low priority is basically closed, to prevent issues overflow. That's what we have now.
We should get under 30 active issues, so it's clear what is important and what not. Also for contributors.
