### ISSUE TITLE
[Downgrade or DowngradeNotPossible PHP 7.4] WeakReference class

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4317]
# Feature Request

The [`WeakReference` class](https://www.php.net/manual/en/class.weakreference.php) added to PHP 7.4 cannot be downgraded, so the `DOWNGRADE_PHP74` set should throw `DowngradeNotPossibleException` whenever `WeakReference` is found in the code.

**Comment by leoloso** [comment]
Actually, deciding if `WeakReference` can be transpiled or not is tricky.

When doing:

```php
$obj = new stdClass;
$weakref = WeakReference::create($obj);
var_dump($weakref->get());
unset($obj);
var_dump($weakref->get());
```

This will print:

```
object(stdClass)#1 (0) {
}
NULL
```

Using PHP 7.3, the object would not be destroyed unless all references to it are removed:

```php
$obj = new stdClass;
$array = [$obj];
var_dump($array);
unset($obj);
var_dump($array);
```

This will print:

```
array(1) {
  [0]=>
  object(stdClass)#412 (0) {
  }
}
array(1) {
  [0]=>
  object(stdClass)#412 (0) {
  }
}
```

Hence, we need to find out if the new behavior is acceptable or not.

For instance, if the only difference is that the application will consume more memory (because garbage collections is less efficient), that may be acceptable, so projects depending on some caching service can still be transpiled.

Now, if the logic needs to assert that an object is `null` after unsetting it, then downgrading will not work.

**Comment by leoloso** [comment]
Please notice that [Symfony Polyfill / Php74](https://github.com/symfony/polyfill-php74/) does not backport this class

**Comment by TomasVotruba** [comment]
Closing for same reasons as other un-downgradable changes: https://github.com/rectorphp/rector/issues/4316#issuecomment-738029246
