### ISSUE TITLE
[Downgrade or DowngradeNotPossible PHP 8.0] Weak maps

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4318]
# Feature Request

We would like to downgrade [Weak maps](https://wiki.php.net/rfc/weak_maps) from PHP 8.0 to its equivalent PHP 7.4 code, but that might not be possible.

From the [RFC](https://wiki.php.net/rfc/weak_maps#differences_to_spl_object_id_and_weakreference):

> Weak maps require first-class language support and cannot be implemented using existing functionality provided by PHP. 

We may think a Weak map can be satisfied by `WeakReference` class (added to PHP 7.4), but that is not the case:

> [With `WeakReference`] The data will not be released when the object is destroyed. It will only be released on the next access with an object that has the same reused ID, or if a garbage collection mechanism, which performs regular sweeps of the whole map, is implemented.

This situation is similar to #4317: we would still like to downgrade this feature, so that projects relying on caching services using it can still be transpiled, and ignore the extra memory consumption.

Is it doable? Or should throw `DowngradeNotPossibleException`?

**Comment by leoloso** [comment]
Please notice that [Symfony Polyfill / Php80](https://github.com/symfony/polyfill-php80/) does not backport this class

**Comment by TomasVotruba** [comment]
Closing for same reasons as other un-downgradable changes: https://github.com/rectorphp/rector/issues/4316#issuecomment-738029246
