### ISSUE TITLE
[Downgrade or DowngradeNotPossible PHP 8.0] Create DateTime objects from interface

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4319]
# Feature Request

Can [these new functions to PHP 8.0](https://stitcher.io/blog/new-in-php-8#create-datetime-objects-from-interface) be downgraded to 7.4?

```php
DateTime::createFromInterface(DateTimeInterface $other);

DateTimeImmutable::createFromInterface(DateTimeInterface $other);
```

Check that [there's no RFC for this feature yet](https://wiki.php.net/rfc).

**Comment by leoloso** [comment]
I imagine it's not possible, because [Symfony Polyfill / Php80](https://github.com/symfony/polyfill-php80/) doesn't backport them, nor does [Symfony Polyfill / Php73](https://github.com/symfony/polyfill-php73/) backport the related function `DateTime::createFromImmutable` (#4320)

**Comment by TomasVotruba** [comment]
Closing for same reasons as other un-downgradable changes: https://github.com/rectorphp/rector/issues/4316#issuecomment-738029246
