### ISSUE TITLE
[Downgrade or DowngradeNotPossible PHP 7.3] DateTime::createFromImmutable

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4320]
# Feature Request

Can this function introduced in PHP 7.3 be downgraded to 7.2? ([Documentation](https://www.php.net/manual/en/datetime.createfromimmutable.php))

```php
 public static DateTime::createFromImmutable ( DateTimeImmutable $object ) : DateTime
```

**Comment by leoloso** [comment]
Notice that [Symfony Polyfill / Php73](https://github.com/symfony/polyfill-php73/) doesn't backport it

**Comment by TomasVotruba** [comment]
Closing for same reasons as other un-downgradable changes: https://github.com/rectorphp/rector/issues/4316#issuecomment-738029246
