### ISSUE TITLE
[Downgrade PHP 8.0] PhpToken class

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4321]
# Feature Request

Transform from class `PhpToken`, [introduced in PHP 8.0](https://wiki.php.net/rfc/token_as_object), to its PHP 7.4 equivalent code using `token_get_all`.

From [the proposal in the RFC](https://wiki.php.net/rfc/token_as_object#proposal):

>  The `PhpToken::getAll()` method is the replacement for `token_get_all()`, which returns an array of `PhpToken` objects instead of a mix of strings and arrays.

**Comment by TomasVotruba** [comment]
There is just a couple of tools using `token_get_all()`, even less with `PhpToken`, so this would be exception to found.

Closing to keep focus on common cases. We'll deal with it when reported in the wild
