### ISSUE TITLE
[DowngradeNotPossible PHP 7.4] Allow exceptions from __toString() 

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4322]
# Feature Request

From the [PHP 7.4 migration guide](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.tostring-exceptions):

>  Throwing exceptions from `__toString()` is now permitted. Previously this resulted in a fatal error. Existing recoverable fatal errors in string conversions have been converted to `Error` exceptions.

This means that if the code throws an exception inside `__toString()`, there is no equivalent to transform it to in PHP 7.3 and before, so the rule should throw a `DowngradeNotPossibleException`.

**Comment by TomasVotruba** [comment]
This is out of Rectors scope now.
Work for PHPStan rule, possibly standalone package

**Comment by leoloso** [comment]
The issue is that anyone downgrading from PHP 7.4 to 7.3, if `__toString()` throws an exception then their application will fail on runtime. If we can already catch the issue statically, and alert the developer in advance, then why not?

This is about downgrading, so I believe it's Rector's scope, not PHPStan's.
