### ISSUE TITLE
[Downgrade or not? PHP 7.4] List of new PHP 7.4 features to maybe downgrade, maybe not?

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4323]
# Feature Request

These are the new features from different PHP versions that I wouldn't know if we need to downgrade or not.

## PHP 7.4

From the [migration guide](https://www.php.net/manual/en/migration74.new-features.php):

 <div>
  <h3>CURL</h3>
  
  <p>
   <a href="https://www.php.net/manual/en/class.curlfile.php" class="classname">CURLFile</a> now supports stream wrappers in addition
   to plain file names, if the extension has been built against libcurl &gt;= 7.56.0.
  </p>
 </div>

 <div>
  <h3>Filter</h3>
  
  <p>
   The <strong><code>FILTER_VALIDATE_FLOAT</code></strong> filter now supports the
   <code>min_range</code> and <code>max_range</code>
   options, with the same semantics as <strong><code>FILTER_VALIDATE_INT</code></strong>.
  </p>
 </div>

 <div>
  <h3>FFI</h3>

  <p>
   FFI is a new extension, which provides a simple way to call
   native functions, access native variables, and create/access
   data structures defined in C libraries.
  </p>
 </div>

 <div>
  <h3>GD</h3>

  <p>
   Added the <strong><code>IMG_FILTER_SCATTER</code></strong> image filter
   to apply a scatter filter to images.
  </p>
 </div>

 <div>
  <h3>Hash</h3>

  <p>
   Added <code>crc32c</code> hash using Castagnoli's polynomial.
   This CRC32 variant is used by storage systems, such as
   iSCSI, SCTP, Btrfs and ext4.
  </p>
 </div>

 <div>
  <h3>Multibyte String</h3>

  <p>
   Added the <span class="function"><a href="https://www.php.net/manual/en/function.mb-str-split.php" class="function">mb_str_split()</a></span> function, which provides
   the same functionality as <span class="function"><a href="https://www.php.net/manual/en/function.str-split.php" class="function">str_split()</a></span>, but operating
   on code points rather than bytes.
  </p>
 </div>

 <div>
  <h3>OPcache</h3>

  <p>
   <a href="https://www.php.net/manual/en/opcache.preloading.php" class="link">Support for preloading code</a> has been added.
  </p>
 </div>

 <div>
  <h3>Regular Expressions (Perl-Compatible)</h3>

  <p>
   The <span class="function"><a href="https://www.php.net/manual/en/function.preg-replace-callback.php" class="function">preg_replace_callback()</a></span> and <span class="function"><a href="https://www.php.net/manual/en/function.preg-replace-callback-array.php" class="function">preg_replace_callback_array()</a></span>
   functions now accept an additional <code class="parameter">flags</code> argument, with support for the
   <strong><code>PREG_OFFSET_CAPTURE</code></strong> and <strong><code>PREG_UNMATCHED_AS_NULL</code></strong> flags.
   This influences the format of the matches array passed to to the callback function.
  </p>
 </div>

 <div>
  <h3>PDO</h3>

  <p>
   The username and password can now be specified as part of the PDO DSN for
   the mysql, mssql, sybase, dblib, firebird and oci drivers. Previously this
   was only supported by the pgsql driver. If a username/password is specified
   both in the constructor and the DSN, the constructor takes precedence.
  </p>
  <p>
   It is now possible to escape question marks in SQL queries to avoid them
   being interpreted as parameter placeholders. Writing <code>??</code>
   allows sending a single question mark to the database and e.g. use the
   PostgreSQL JSON key exists (<code>?</code>) operator.
  </p>
 </div>

 <div>
  <h3>PDO_OCI</h3>

  <p>
   <span class="methodname"><a href="https://www.php.net/manual/en/pdostatement.getcolumnmeta.php" class="methodname">PDOStatement::getColumnMeta()</a></span> is now available.
  </p>
 </div>

 <div>
  <h3>PDO_SQLite</h3>

  <p>
   <code>PDOStatement::getAttribute(PDO::SQLITE_ATTR_READONLY_STATEMENT)</code>
   allows checking whether the statement is read-only, i.e. if it doesn't modify
   the database.
  </p>
  <p>
   <code>PDO::setAttribute(PDO::SQLITE_ATTR_EXTENDED_RESULT_CODES, true)</code>
   enables the use of SQLite3 extended result codes in <span class="function"><a href="https://www.php.net/manual/en/pdo.errorinfo.php" class="function">PDO::errorInfo()</a></span>
   and <span class="function"><a href="https://www.php.net/manual/en/pdostatement.errorinfo.php" class="function">PDOStatement::errorInfo()</a></span>.
  </p>
 </div>

 <div>
  <h3>SQLite3</h3>

  <p>
   Added <span class="methodname"><strong>SQLite3::lastExtendedErrorCode()</strong></span>
   to fetch the last extended result code.
  </p>
  <p>
   Added <code>SQLite3::enableExtendedResultCodes($enable = true)</code>,
   which will make <span class="methodname"><a href="https://www.php.net/manual/en/sqlite3.lasterrorcode.php" class="methodname">SQLite3::lastErrorCode()</a></span>
   return extended result codes.
  </p>
 </div>

 <div>
  <h3>Standard</h3>

  <div>
   <h4>Custom object serialization</h4>
   <p>
    A new mechanism for custom object serialization has been added, which
    uses two new magic methods: <code>__serialize</code>
    and <code>__unserialize</code>.
    </p><div>
     <div>
<pre><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br></span><span style="color: #FF8000">//&nbsp;Returns&nbsp;array&nbsp;containing&nbsp;all&nbsp;the&nbsp;necessary&nbsp;state&nbsp;of&nbsp;the&nbsp;object.<br></span><span style="color: #007700">public&nbsp;function&nbsp;</span><span style="color: #0000BB">__serialize</span><span style="color: #007700">():&nbsp;array;<br><br></span><span style="color: #FF8000">//&nbsp;Restores&nbsp;the&nbsp;object&nbsp;state&nbsp;from&nbsp;the&nbsp;given&nbsp;data&nbsp;array.<br></span><span style="color: #007700">public&nbsp;function&nbsp;</span><span style="color: #0000BB">__unserialize</span><span style="color: #007700">(array&nbsp;</span><span style="color: #0000BB">$data</span><span style="color: #007700">):&nbsp;</span><span style="color: #0000BB">void</span><span style="color: #007700">;<br></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></pre>
     </div>

    </div>
    The new serialization mechanism supersedes the
    <span class="interfacename"><a href="https://www.php.net/manual/en/class.serializable.php" class="interfacename">Serializable</a></span> interface,
    which will be deprecated in the future.
   <p></p>
  </div>

  <div>
   <h4><span class="function"><a href="https://www.php.net/manual/en/function.proc-open.php" class="function">proc_open()</a></span> function</h4>
   <p>
    <span class="function"><a href="https://www.php.net/manual/en/function.proc-open.php" class="function">proc_open()</a></span> now accepts an array instead of a
    string for the command. In this case the process will be opened
    directly (without going through a shell) and PHP will take care of
    any necessary argument escaping.
    </p><div>
     <div>
<pre><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br>proc_open</span><span style="color: #007700">([</span><span style="color: #DD0000">'php'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'-r'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'echo&nbsp;"Hello&nbsp;World\n";'</span><span style="color: #007700">],&nbsp;</span><span style="color: #0000BB">$descriptors</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$pipes</span><span style="color: #007700">);<br></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></pre>
     </div>

    </div>
   <p></p>
   <p>
    <span class="function"><a href="https://www.php.net/manual/en/function.proc-open.php" class="function">proc_open()</a></span> now supports
    <code>redirect</code> and <code>null</code> descriptors.
    </p><div>
     <div>
<pre><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br></span><span style="color: #FF8000">//&nbsp;Like&nbsp;2&gt;&amp;1&nbsp;on&nbsp;the&nbsp;shell<br></span><span style="color: #0000BB">proc_open</span><span style="color: #007700">(</span><span style="color: #0000BB">$cmd</span><span style="color: #007700">,&nbsp;[</span><span style="color: #0000BB">1&nbsp;</span><span style="color: #007700">=&gt;&nbsp;[</span><span style="color: #DD0000">'pipe'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'w'</span><span style="color: #007700">],&nbsp;</span><span style="color: #0000BB">2&nbsp;</span><span style="color: #007700">=&gt;&nbsp;[</span><span style="color: #DD0000">'redirect'</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">]],&nbsp;</span><span style="color: #0000BB">$pipes</span><span style="color: #007700">);<br></span><span style="color: #FF8000">//&nbsp;Like&nbsp;2&gt;/dev/null&nbsp;or&nbsp;2&gt;nul&nbsp;on&nbsp;the&nbsp;shell<br></span><span style="color: #0000BB">proc_open</span><span style="color: #007700">(</span><span style="color: #0000BB">$cmd</span><span style="color: #007700">,&nbsp;[</span><span style="color: #0000BB">1&nbsp;</span><span style="color: #007700">=&gt;&nbsp;[</span><span style="color: #DD0000">'pipe'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'w'</span><span style="color: #007700">],&nbsp;</span><span style="color: #0000BB">2&nbsp;</span><span style="color: #007700">=&gt;&nbsp;[</span><span style="color: #DD0000">'null'</span><span style="color: #007700">]],&nbsp;</span><span style="color: #0000BB">$pipes</span><span style="color: #007700">);<br></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></pre>
     </div>

    </div>
   <p></p>
  </div>
 </div>

**Comment by TomasVotruba** [comment]
These would be very rare to happen. There are more likely rules to be implemented.

Lets skip it now, untill we came across it in the real life
