### ISSUE TITLE
[DowngradeNotPossible PHP 7.4] ReflectionReference

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4324]
# Feature Request

[Class `ReflectionReference`](https://www.php.net/manual/en/class.reflectionreference.php) ([added in PHP 7.4](https://www.php.net/manual/en/migration74.new-classes.php)) can't be downgraded, so throw `DowngradeNotPossibleException`

**Comment by TomasVotruba** [comment]
Nothing we can do here, work for PHPStan

**Comment by leoloso** [comment]
@TomasVotruba this is not a downgrade rule, but a `DowngradeNotPossible` exception. The idea is not to downgrade, but to throw an error whenever the developer wants to downgrade code below PHP 7.4, and it contains this class.

We can have this working in less than 2 hours, and we are adding consistency and a strong message for the developers: whatever can be downgraded, Rector will do it; whatever cannot, Rector will let you know about it. I think it's worth doing

**Comment by TomasVotruba** [comment]
I know. See https://github.com/rectorphp/rector/issues/4316#issuecomment-738029246
