### ISSUE TITLE
[Downgrade PHP 7.4] <?php tag at end of file

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4325]
# Feature Request

Downgrade from PHP 7.4 to 7.3.

From [here](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.php-tag):

> `<?php` at the end of the file (without trailing newline) will now be interpreted as an opening PHP tag. Previously it was interpreted either as a short opening tag followed by literal php and resulted in a syntax error (with `short_open_tag=1`) or was interpreted as a literal `<?php` string (with `short_open_tag=0`). 
 
## Diff 

Add a trailing newline at the end of the file:

```diff
<?php
// ...
?>
<p>Hello world!</p>
<?php
+
```

**Comment by TomasVotruba** [comment]
This would be very rare to happen. There are more likely rules to be implemented.

Lets skip it now, untill we came across in the real life
