### ISSUE TITLE
[DowngradeNotPossible PHP 7.3] Any of the new global constants

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4327]
# Feature Request

[Global constants added to PHP 7.3](https://www.php.net/manual/en/migration73.constants.php). If any of them is referenced in the code, it may not be possible to downgrade it.

Notice that none of them has been backported in [Symfony Polyfill / Php73](https://github.com/symfony/polyfill-php73/)

Double check if it can be downgraded or not!

**Comment by TomasVotruba** [comment]
Closing for same reasons as other un-downgradable changes: https://github.com/rectorphp/rector/issues/4316#issuecomment-738029246
