### ISSUE TITLE
Replacing iterator_to_array with unpack could result in Cannot unpack array with string keys

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#4333]
# Bug Report

To reproduce (PHP 7.4):
```php
<?php

function getGenerator($key): \Generator {
    yield $key => 'value';
    yield 'value';
}

var_dump(iterator_to_array(getGenerator(0)));
var_dump(iterator_to_array(getGenerator('key')));
var_dump([...getGenerator(0)]);
var_dump([...getGenerator('key')]);

```

```txt
array(2) {
  [0]=>
  string(5) "value"
  [1]=>
  string(5) "value"
}
array(2) {
  ["key"]=>
  string(5) "value"
  [0]=>
  string(5) "value"
}
array(2) {
  [0]=>
  string(5) "value"
  [1]=>
  string(5) "value"
}
PHP Fatal error:  Uncaught Error: Cannot unpack Traversable with string keys in Standard input code:11
Stack trace:
#0 {main}
  thrown in Standard input code on line 11
```
I'm not sure you can detect if the generator contains string keys, but otherwise this is adding potential bugs.

According to an answer in https://stackoverflow.com/questions/40663687/cannot-unpack-array-with-string-keys I suppose the unpacking will work in PHP 8

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting. This is definitely a bug.

Could you add this failing fixture to responsbile rule into `/Fixture` directory via pull-request? So we have it covered :+1:

**Comment by gisostallenberg** [comment]
You mean 'add a file' in `rules/php74/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Fixture/`?

**Comment by gisostallenberg** [comment]
I'm not really sure what to do to help you 😄

**Comment by TomasVotruba** [comment]
> You mean 'add a file' in

Yes ;)

**Comment by gisostallenberg** [comment]
@TomasVotruba I'm really not sure how to help, I'm sorry.
I would add somehting like this, right?:
`rules/php74/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Fixture/skip_string_keys_from_generator.php.inc`
```php
<?php

namespace Rector\Php74\Tests\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector\Fixture;

function x(): \Generator
{
    yield 'key' => 'value';
}

class SkipStringKeysFromGenerator
{
    public function run()
    {
        return \iterator_to_array(x());
    }
}
```

But that does not fix the issue, right?

**Comment by TomasVotruba** [comment]
Exactly :+1:

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector/pull/4415
