### ISSUE TITLE
[FPDP] Format preserving doc printer

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4334]
Mirror of https://github.com/nikic/PHP-Parser/issues/344, just for phpdoc

It might be worth to create https://github.com/phpstan/phpdoc-parser which actually preserver format

Here is knowledge snippet from php-parser: https://github.com/nikic/PHP-Parser/issues/487

## Related Issues

- https://github.com/rectorphp/rector/issues/3932

**Comment by staabm** [comment]
> It might be worth to create [phpstan/phpdoc-parser](https://github.com/phpstan/phpdoc-parser) which actually preserver format

what does this mean? do you have a plan/a idea of what needs to be done?

**Comment by TomasVotruba** [comment]
We need a new package that builds on https://github.com/phpstan/phpdoc-parser,
but also add printing the docblock back.

I don't have any ETA on that.

**Comment by staabm** [comment]
Whats the job of this package? What should it provide on top of what phpstan/phpdoc-parser already can?

**Comment by TomasVotruba** [comment]
> Whats the job of this package? 

Current job of existing package is getting docs block to types.

E.g.

```php
/**
 * @var int
 */
```

↓

Very rougly:

```php
new VarTagNode(new IntegerType())
```

The problem is, all these cases:

```php
/**
 * @var int
 */

/**
 * @var integer
 */

/**
 *  @var     int
 */
```

Are printed back as:

```php
/**
 * @var int
 */
```

<br><br>

> What should it provide on top of what phpstan/phpdoc-parser already can?

Keep the format in it's original form.

**Comment by TomasVotruba** [comment]
Work in progress https://github.com/rectorphp/phpdoc-parser-printer

**Comment by TomasVotruba** [comment]
Big jump forward via:

- https://github.com/rectorphp/rector/pull/5841
- and native attribute support in phpdoc-parser https://github.com/phpstan/phpdoc-parser/pull/65 :tada:

**Comment by TomasVotruba** [comment]
We've just added another jump with static doctrine annotatoin parsing https://github.com/rectorphp/rector/pull/6040

Before, to parse class-based annotations the https://github.com/doctrine/annotations was needed:

```php
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Product
{
}
```

That required the `Doctrine\ORM\Mapping\Entity` class to be present and autoloaded. That kind-of kills the advantage of [static reflection added in Rector 0.10](https://getrector.org/blog/2021/03/15/legacy-refactoring-made-easy-with-static-reflection) for annotations.

Further more, this approach required every such annotation to have own php doc node class and factory to make it. In total, Rector contained ~50 such classes + factories.

<br>

The https://github.com/rectorphp/rector/pull/6040 PR solves this using https://github.com/phpstan/phpdoc-parser and copying the doctrine/annotation behavior 1:1 without autoloading used classes and constants.

Now, Rector is now using static for annotations making it more accessible to wide PHP comunity :hugs: :+1:

**Comment by TomasVotruba** [comment]
Since last 2 comments and full month of testing we have exactly 0 reported issues with docblocks :+1: 

I think we can close this issue as resolved :slightly_smiling_face:
