### ISSUE TITLE
[PHP 8.0] Add Symfony/Validator to attributes

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4349]
See https://github.com/symfony/symfony/pull/38309

**Comment by derrabus** [comment]
While the validator itself understands attributes now, I'm still working on migrating the individual constraints.

**Comment by TomasVotruba** [comment]
If migration path has the same logic as @Route → #[Route], then all we need to do here is to add validator annotatoin classes.

**Comment by TomasVotruba** [comment]
Link to all constraint classes: https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Validator/Constraints

**Comment by derrabus** [comment]
There are a few more:
* https://github.com/symfony/symfony/tree/master/src/Symfony/Bridge/Doctrine/Validator/Constraints
* https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Security/Core/Validator/Constraints

**Comment by derrabus** [comment]
Most constraints have been migrated now.
* Composite constraints (like `All` and `AtLeastOneOf`) must remain Doctrine-style annotations because we cannot nest PHP attributes unfortunately.
* The `UniqueEntity` constraint hasn't been migrated because we need to wait for a compatible Doctrine ORM version.

**Comment by TomasVotruba** [comment]
Thank you for updates. Could you also link PRs with those changes? Just so its easier to implement it.

My priorities shifted now, but I'll give a try in the future.

**Comment by derrabus** [comment]
Sure:
* symfony/symfony#38382
* symfony/symfony#38410
* symfony/symfony#38499

**Comment by TomasVotruba** [comment]
Closing as out of scope ATM. Feel free to contribute if you find a time
