### ISSUE TITLE
Remove Fluent Builder

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#435]
Having time to think about this feature, I found few reasons this might hurt the rector code base. Why?

- it would take lot of work to make it work properly, with order, all required argument etc
- it's not clear what to use when, imagine PHP CS Fixer has similar approach, Fixer, sets, fluent builders, providers... etc. Super complex
- Unix approach with little professionalized tools work best combined together beats universal general Windows like system
- noone used it since added, I've rather added more other functionality instead - that's the best proof

**Comment by mssimi** [comment]
I agree with this.

**Comment by TomasVotruba** [comment]
@mssimi Could you explain more? I'd like to know your view

**Comment by mssimi** [comment]
For me implementing AbstractRector seems to be way to go for both simple and complex rectors. I don't have to think what to use when as you said above. Besides I don't really see more complexity by using regular approach for simple use cases too. Why maintaining two ways of building rectors for such insignificant gain?

**Comment by TomasVotruba** [comment]
I appreciate your point of wiev because I might be in-too-deep and part of confirmation dissonance (I look for what I want to see, regardless arguments).

So I'm glad you see it this way for reasons you explained.

The only issue we still need to solve this is, when change requires coordination of 2 rectors in a specific order, e.g.

- remove argument from `one($argument)` method
- rename method from `one()` to `another()`

Or do you think having them in config.yml with a note is good enough?
