### ISSUE TITLE
Can't run rector 0.8.14.

### ISSUE THREAD

**Issue by michaljusiega** [rectorphp/rector#4358]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | rector/rector-prefixed               0.8.14                 |
| Installed as   | prefixed Rector PHAR                      |

As Locally:
```
 [ERROR] Expected to find class "Symplify\ComposerJsonManipulator\ComposerJsonFactory" in file                          
         "phar:///var/www/intranet/vendor/rector/rector-prefixed/rector/vendor/symplify/composer-json-manipulator/config
         /../src/ComposerJsonFactory.php" while importing services from resource                                        
         "phar:///var/www/intranet/vendor/rector/rector-prefixed/rector/vendor/symplify/composer-json-manipulator/config
         /../src", but it was not found! Check the namespace prefix used with the resource.        
```
In Gitlab CI/CD.
![Screenshot_2020-10-05 rector-checkstyle (#5499) · Jobs · luxmed intranet](https://user-images.githubusercontent.com/16488888/95076276-dee01d00-0711-11eb-8bfb-ce8a60dd0f2b.png)

## Minimal PHP Code Causing Issue
vendor/bin/rector --version
vendor/bin/rector show -c rector.php

## Expected Behaviour
Should not throws Exception

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

I tried to rebuild. Could you try `0.8.15`?

**Comment by michaljusiega** [comment]
Yes. `0.8.15` solve issue. Thanks.

**Comment by TomasVotruba** [comment]
Great, thanks for confirmation :+1:
