### ISSUE TITLE
Add a "hacktoberfest" repository topic

### ISSUE THREAD

**Issue by SilverFire** [rectorphp/rector#4360]
Hey, @TomasVotruba 

Since Hacktoberfest updated their policies, pull-requests are encountered only in the repositories with "hacktoberfest" topic. Why not encourage someone to put some love in Rector ;)

**Comment by TomasVotruba** [comment]
Hi, sure. What should we do? :)

**Comment by SilverFire** [comment]
![image](https://user-images.githubusercontent.com/4499203/95172610-3b9a1100-07c0-11eb-8e47-1238249a52e6.png)

Add a "hacktoberfest" topic here

**Comment by TomasVotruba** [comment]
Done! :+1: 

I'd like to give new contributors a reward in form of Jetbrains license, let's say 5 of them.
But I don't have time to explore the rule and organize it (I didn't know about this tagging either).

Do you think I could ask you for your help with that?

**Comment by TomasVotruba** [comment]
Done! :+1: 

I'd like to give new contributors a reward in form of Jetbrains license, let's say 5 of them.
But I don't have time to explore the rule and organize it (I didn't know about this tagging either).

Do you think I could ask you for your help with that?

**Comment by SilverFire** [comment]
Emm... I know nothing about the JetBrains Hacktoberfest perks.

Just googled that they give a monthly subscription to all JetBrains products at https://www.jetbrains.com/lp/hacktoberfest-2020/#get-the-tools and automatically send a 3-months subscription after 4 valid PRs

> Thank you! We’ve just sent you a coupon for a new All Products Pack subscription that is valid for one month. You can use it for your Hacktoberfest contributions. At the end of the event, we will check your Hacktoberfest contributions and, provided they are completed, we will email you a coupon code for a 3 months subscription – you don’t need to re-submit the form.

It seems it works by default and we should not do anythong

**Comment by TomasVotruba** [comment]
> Emm... I know nothing about the JetBrains Hacktoberfest perks.

I don't mean 3rd party companies. I mean Rect perks :) 
I would give 5 Rector contributors a reward from myself for their first-time work on Rector.

**Comment by simivar** [comment]
I will close this issue as it's almost two months old and Hacktoberfest is already over. Thanks to everyone who contributed. :)
