### ISSUE TITLE
PHP 7.4 property with direct assignment and union type is wrongly fixed to typed property

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#4363]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.15 |
| Installed as   | composer dependency |

While creating typed properties a property with an assignment but a doc-block with a union type still gets converted to a typed property. After this the property can no longer be assigned another type. Maybe `int` is no problem, but it does this as well with classes.

```diff
--- Original
+++ New
@@ -3,8 +3,5 @@
 namespace App;

 class Foo {
-    /**
-     * @var bool|int
-     */
-    private $bar = 0;
+    private int $bar = 0;
 }
```

```diff
--- Original
+++ New
@@ -3,8 +3,5 @@
 namespace App;

 class Foo {
-    /**
-     * @var bool|int
-     */
-    private $bar = false;
+    private bool $bar = false;
 }
```
```diff
--- Original
+++ New
@@ -3,8 +3,5 @@
 namespace App;

 class Foo {
-    /**
-     * @var bool|int
-     */
-    private $bar = true;
+    private bool $bar = true;
 }
```

## Expected Behaviour
I would expect rector to respect the docblock for PHP 7.4 and add a union type in PHP 8.

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting. Could you add a failing fixture to that rule?
