### ISSUE TITLE
Rector won't load YAML anymore

### ISSUE THREAD

**Issue by althaus** [rectorphp/rector#4365]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.8            |
| Installed as   | prefixed Rector PHAR                      |

I've just fetched the v0.8.8 prefixed phar and let it run on my project. It won't load my existing rector.yaml anymore. It worked with an older version.

~~~
$ ./tools/rector.phar process --dry-run --config=rector.yaml

 [ERROR] Cannot load resource "D:\dev\project\rector.yaml".
~~~

Yes, I'm running it throught Git Bash on Windows. He must find the file as using a non-existing name results in a "file not found" error.

I've put a `rector.php` next to the yaml and tried that. Works fine:

~~~
$ ./tools/rector.phar process --dry-run --config=rector.php
Rector v0.8.8
Config file: rector.php

 [OK] Rector is done!
~~~

Both contain a single rule for testing purpose.

## Expected Behaviour

YAML works the same as PHP again?

Kind regards
Matthias

**Comment by TomasVotruba** [comment]
Hi, the yaml is not supported for ~3 months and it was removed in Rector 0.8

Is there same place we still mention YAML? We have to change it.

See post: https://getrector.org/blog/2020/08/31/rector-is-moving-from-yaml-to-php-configs-what-changes-and-how-to-get-ready

The best to learn about this is Twitter: https://mobile.twitter.com/rectorphp

**Comment by althaus** [comment]
Oh... I've followed the news a bit, but missed that YAML was droppped completely. Maybe I didn't expect that to happen on a minor release.

Perhaps rector could explicit warn if you're not feeding it with a PHP config?

I'll check if I drop back to 0.7 or use migrify for conversion. Got a quite compley YAML atm and only little time to spare.

Thanks for the fast reply!
Matthias

**Comment by TomasVotruba** [comment]
The semver for 0.x is different. The minor version is same as major in 1+.x, see https://semver.org/

> Perhaps rector could explicit warn if you're not feeding it with a PHP config?

That makes sense, would you like to contribute it?

Migrify will help you migrate in few seconds, it's the way to go.
