### ISSUE TITLE
[Doctrine] alias to class Rector

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#438]
Follow up to #434 

This alias support is [removed in Doctrine 2.7+](https://github.com/doctrine/doctrine2/commit/63cb8018dd1a889be4e08a31fad1e76f4cc876d0#diff-824ad31297dda8bacca99948535bc937), so this belongs to `doctrine27.yml`

There should be Rector that handles 'App:Post' => `AppBundle\Entity\Post` conversion, to cover this case
https://github.com/rectorphp/rector/pull/434/files#diff-1959c4870ae07888515b8c6ed0d52831

Also related to #428

**Comment by mssimi** [comment]
I'm on it:)

**Comment by TomasVotruba** [comment]
Good idea!
