### ISSUE TITLE
[Downgrade PHP 7.3] JSON_THROW_ON_ERROR

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4385]
# Feature Request

Downgrade from PHP 7.4 to its equivalent PHP 7.3 code. [RFC](https://wiki.php.net/rfc/json_throw_on_error)

[From the migration guide](https://www.php.net/manual/en/migration73.other-changes.php#migration73.other-changes.json):

> A new flag has been added, **JSON_THROW_ON_ERROR**, which can be used with `json_decode()` or `json_encode()` and causes these functions to throw the new `JsonException` upon an error, instead of setting the global error state that is retrieved with `json_last_error()` and `json_last_error_msg()`. **JSON_PARTIAL_OUTPUT_ON_ERROR** takes precedence over **JSON_THROW_ON_ERROR**. 
 
## Potential solution:

Wrap calls to `json_encode` with `json_encode_wrapper` (or some other name), which does this:

```php
function json_encode_wrapper(...$args) {
  json_encode($args);
  if (json_last_error()) {
    throw new JsonException(json_last_error_msg());
  }
}
```

**Comment by TomasVotruba** [comment]
Not needed yet
