### ISSUE TITLE
PHAR file impossible to open since 0.8.16

### ISSUE THREAD

**Issue by michaljusiega** [rectorphp/rector#4386]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.16             |
| Installed as   | prefixed Rector PHAR                      |

Since `0.8.16` the phar file is impossible to open and analyze via PHPStorm, which shows the following two screenshots.

0.8.15:
![obraz](https://user-images.githubusercontent.com/16488888/95648034-85db0500-0ad4-11eb-9bdc-f1b458881858.png)

0.8.16:
![obraz](https://user-images.githubusercontent.com/16488888/95647993-41e80000-0ad4-11eb-81ff-6bea9a73cb47.png)

## Minimal PHP Code Causing Issue

Update to 0.8.16 and higher.

## Expected Behaviour

Should be okey.

**Comment by TomasVotruba** [comment]
Hi,

this is out of our scope of development for PHAR. PHAR is not designed to be opened by definition, the priority is working PHAR process defined by passing CI: https://github.com/rectorphp/rector-prefixed/actions

Got ideas how to make it work?

**Comment by michaljusiega** [comment]
I have no idea about this problem :(

Well, it becomes problematic when PHPStorm does not use its capabilities because there is something wrong with the file :)

So far, I have personally applied workaround:

`"rectorphp/rector-prefixed": ">= 0.8.16"`

**Comment by michaljusiega** [comment]
The obvious problem is on your side with building the file.

Other files like `phpstan.phar` works as it should.

https://github.com/rectorphp/rector/compare/0.8.15...0.8.16 looking good, there is nothing that could cause this error.

**Comment by TomasVotruba** [comment]
I actually have the same with `phpstan.phar` from time to time. I gave it few days, but in the end it I didn't find a way. It started working, probably some glitch in PHPStorm :)

If we put apart yellow underline in PHPStorm, what bug does it actually cause?

**Comment by michaljusiega** [comment]
> ... what bug does it actually cause?

I trying to find it.

**Comment by TomasVotruba** [comment]
Btw, what is the exact PHPStorm message for the yellow underline?

**Comment by michaljusiega** [comment]
Sorry for late answer:
![Bez tytułu](https://user-images.githubusercontent.com/16488888/95781604-77f0d400-0cce-11eb-9fba-90d73b147aaa.png)

**Comment by TomasVotruba** [comment]
The message does not make sense. This looks like bug in PHPStorm itself.

**Comment by michaljusiega** [comment]
First of all, PHPStorm has a problem parsing the phar file, so next issue are related to the non-analysis.

Maybe I will send issue to Jetbrains ?

**Comment by TomasVotruba** [comment]
I'd give a try. The message is definitely a non-sense bug.

**Comment by michaljusiega** [comment]
@TomasVotruba What is the situation?

**Comment by TomasVotruba** [comment]
I didn't came across this problem. What about PHPStorm?

**Comment by michaljusiega** [comment]
I'd give a try send issue to Jetbrains ;)

**Comment by TomasVotruba** [comment]
I thought you already did. Go for it :) 

Anyway, this issue is not really relevant to Rector codebase at the moment, as phar is not designed to be opened or worked with. And it seems as IDE bugs. Closing to keep more focus on bug issues.

**Comment by michaljusiega** [comment]
Added in https://youtrack.jetbrains.com/issue/WI-56504
