### ISSUE TITLE
RenameParamToMatchTypeRector (called in rector-ci.php) renames variables only in few places, not everywhere

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4397]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.18              |
| Installed as   | composer dependency                      |

Running rule `Rector\Naming\Rector\ClassMethod\RenameParamToMatchTypeRector` in my computer, it is converting the name of a variable in the function signature, but not in the body, thus breaking the code.

In this code, `$item` becomes `$arrayItem` in the signature, but not in the body:

```diff
-private function getItemByRefOrNull(?ArrayItem $item, int $condition): ?ArrayItem
+private function getItemByRefOrNull(?ArrayItem $arrayItem, int $condition): ?ArrayItem
{
    if ($item === null) {
        return null;
    }
    // Check if the item is a nested list/nested array destructuring
    if ($item->value instanceof List_ || $item->value instanceof Array_) {
        // Recursive call
        /** @var List_|Array_ */
        $nestedList = $item->value;
        $hasItemByRef = false;
        if ($condition === self::ALL) {
            $hasItemByRef = $this->hasAllItemsByRef($nestedList->items);
        } elseif ($condition === self::ANY) {
            $hasItemByRef = $this->hasAnyItemByRef($nestedList->items);
        }
        return $hasItemByRef ? $item : null;
    }
    return $item->value instanceof Variable && $item->byRef ? $item : null;
}
```

But then, using getrector.org/demo, the result is different! (Check link below). There it also breaks the code, but like this:

```diff
} elseif ($condition === self::ANY) {
                 $hasItemByRef = $this->hasAnyItemByRef($nestedList->items);
             }
-            return $hasItemByRef ? $item : null;
+            return $hasItemByRef ? $arrayItem : null;
         }
-        return $item->value instanceof Variable && $item->byRef ? $item : null;
+        return $arrayItem->value instanceof Variable && $arrayItem->byRef ? $arrayItem : null;
     }
-}
+}
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/284aa440-5a58-469f-b30c-7612ea660550#result

## Expected Behaviour

Rename `$item` as `$arrayItem` everywhere

**Comment by TomasVotruba** [comment]
We need failing test case for this one

**Comment by leoloso** [comment]
Added test case in #4815. It seems to work well, but in getrector.org it still shows failing!?

**Comment by TomasVotruba** [comment]
Thank you for verification. Closing then.

The website is not updated daily. A cron GitHub action could handle it.
