### ISSUE TITLE
ReturnTypeDeclarationRector with Object return type and PHP71 set breaks code

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#4398]
# Bug Report

Hi, combination of sets `SetList::PHP_71`, `SetList::TYPE_DECLARATION` has unexpected results in return typehint where `@return object` is used

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@50f75c9              |
| Installed as   | online demo                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/daa09cae-3c03-4b50-a88e-f462387cd010#result

## Expected Behaviour

Either return `object` or leave it in annotation, but code must work after rector processing.

**Comment by JanMikes** [comment]
Might be related to https://github.com/rectorphp/rector/issues/1435

**Comment by samsonasik** [comment]
@JanMikes I think you can use `Option::PHP_VERSION_FEATURES` to 7.1 ? :

```php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
	
	$parameters->set(Option::AUTO_IMPORT_NAMES, true);
        $parameters->set(Option::PHP_VERSION_FEATURES, '7.1');
	
	$parameters->set(Option::SETS, [
        SetList::PHP_71,
        SetList::TYPE_DECLARATION,
    ]);
};
```

see https://getrector.org/demo/23e507ef-6b02-4c27-8b51-044742128861#result

**Comment by samsonasik** [comment]
I am closing it. It can use `Option::PHP_VERSION_FEATURES` to `7.1` https://getrector.org/demo/d580225b-37bb-4935-87bc-835bc8ce4f06#result

**Comment by JanMikes** [comment]
Hi, sorry for the delay.

Honestly i do not understand the solution. We are running PHP 7.4 so why should we limit rector features to 7.1? 

Is it correct to use `SetList::PHP_71` even when running > PHP 7.1? 

This specific sets combination is breaking our CI pipeline, so we had to ignore something anyways.

**Comment by samsonasik** [comment]
using 7.4 seems working fine https://getrector.org/demo/697d0885-0ccc-4923-afc5-e51bdaf3b765#result
