### ISSUE TITLE
DowngradeNumericLiteralSeparatorRector must not convert 1.0 to 1

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4401]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.21       |
| Installed as   | composer dependency                      |

Running rector `DowngradeNumericLiteralSeparatorRector` (to replace `1_000` with `1000`) on an `int` such as `1.0` currently replaces it with `1`:

```diff
-if (0 > $beta = $beta ?? 1.0) {
+if (0 > $beta = $beta ?? 1) {
```

It must not.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/715a5acd-2f03-4db3-a7f2-d9e0a5d02ba5#result

## Expected Behaviour

Do not replace `1.0` with `1`, keep it as it is.

**Comment by samsonasik** [comment]
1.0 seems already skipped, `PHP_FLOAT_MAX` value seems still lose last 3 digits.

**Comment by samsonasik** [comment]
https://getrector.org/demo/d064e859-12c7-4fe0-9bf7-01c0eb201ab9

**Comment by leoloso** [comment]
> 1.0 seems already skipped

Yes, I fixed that issue already. Sorry for not mentioning in this PR.

The other issue still happens but, I believe, cannot be fixed (unless keeping the parsed number, in string format, as an attribute).

You can decide to close this issue.
