### ISSUE TITLE
Coverage report doesn't show correctly in readme

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#4403]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest             |
| Installed as   | *                  |

Last uploaded report coverage to coveralls is  ` Committed 19 Sep 2020 - 9:27 coverage increased (+0.07%) to 72.875% ` at https://coveralls.io/github/rectorphp/rector?branch=master

![Screen Shot 2020-10-14 at 4 53 11 PM](https://user-images.githubusercontent.com/459648/95973383-c5d81a00-0e3d-11eb-9ec7-860fd28612b5.png)

**Comment by TomasVotruba** [comment]
The coverage is in disabled workflows, because it stopped working for unknown reason.

Could you look at the fix?

**Comment by samsonasik** [comment]
I will try.

**Comment by samsonasik** [comment]
Closing for now while it only can show `src` directory for coverage. But it works.
