### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#441]
I did some testing with blackfire.io you can check it [here](https://blackfire.io/profiles/6503441a-e657-4a00-8ed3-90a0e935751e/graph).

It seems like performance bottleneck comes from https://github.com/rectorphp/BetterReflection.

I did some testing and I think we may improve performance by adding caching [here](https://github.com/rectorphp/BetterReflection/blob/368e2698e36e1ba1fe2a5d6c2cba8f33747d7a5c/src/SourceLocator/Type/AbstractSourceLocator.php#L41). I tested in on simple Symfony Form and I noticed it is actually doing same thing 3 times, if we cache it, we should improve performance by 300%.

**Comment by TomasVotruba** [comment]
Why not send PR instead? :)

**Comment by mssimi** [comment]
May be BC break.

**Comment by carusogabriel** [comment]
> May be BC break.

@mssimi Don't worry, Rector isn't even in Alpha, we can break whatever we want :joy:

**Comment by TomasVotruba** [comment]
Closing as unclear intentions
