### ISSUE TITLE
ArraySpreadInsteadOfArrayMergeRector should not convert iterator_to_array to spread operator

### ISSUE THREAD

**Issue by drupol** [rectorphp/rector#4413]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.24              |
| Installed as   | composer dependency                      |
| Related issues | #4333 |

I'm writing a lazy PHP collection library working with iterator and generators. This library is available for `php >= 7.1.3`.
I'd like to publish a new major release for `php > 7.4` and I used rector to convert the code and rewrite some parts, especially the closures.

After that, I tried to run the tests and many tests were failing because `iterator_to_array($var)` was converted to `[...$var]`.
While this seems to be valid most of the time, it can be wrong as well when `$var` is an iterator containing duplicated key values.

## Minimal PHP Code Causing Issue

Context: https://3v4l.org/YSABX

Code:

```php
<?php

$generator = static function()
{
    yield 1 => 1;
    yield 2 => 2;
    yield 1 => 3;
    yield 2 => 4;
};

var_dump(iterator_to_array($generator()));
var_dump([...$generator()]);
```

## Expected Behaviour

I think in this case, while in most of the cases it will work, rector should not change `iterator_to_array()` to spread operator.
Adding a check prior converting would be too much of a hassle and not efficient.

Also, the spread operator cannot unpack with non-integer keys while `iterator_to_array()` does: https://3v4l.org/uECeu

**Comment by TomasVotruba** [comment]
Hi,

thanks for report. This should be definitely skipped.

Could you add failing test case for `ArraySpreadInsteadOfArrayMergeRector`? Here is [short step by step guide](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md) how to
