### ISSUE TITLE
Rule for moving function from global namespace to defined namespace?

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4414]
Is there a rule to move a userland function from the global namespace (none defined) to a defined namespace? The function should not become a method of a namespaced class, it should stay a [function but inside a namespace](https://www.simonholywell.com/post/2015/08/namespace-php-functions/).

```
<?php

function a() {}

// some implementations
$a = a();

// should become this:

namespace A\B;
function a() {};

// some implementations
use function A\B\a;
$a = a();
```

**Comment by TomasVotruba** [comment]
Hi,

there not such rule yet.

There is one that adds namespaced based on your `composer.json`: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#normalizenamespacebypsr4composerautoloadrector

Then updates the class names. Maybe it could be re-used in your case.

What logic is for adding those namespaces (if not psr-4)?

**Comment by powtac** [comment]
> What logic is for adding those namespaces (if not psr-4)?

It is part of a refactoring roadmap.

**Comment by TomasVotruba** [comment]
Good :+1: 

Maybe you can [add a failing test case](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md) to `NormalizeNamespaceByPSR4ComposerAutoloadRector`, that will add a namespace to a file with function, but also prefix the function call name.


Something like:

```diff
+namespace App;

 function lonely_function()
 {
 }

-lonely_function();
+\App\lonely_function();
```

**Comment by TomasVotruba** [comment]
Closing as answered
