### ISSUE TITLE
Running NormalizeNamespaceByPSR4ComposerAutoloadFileSystemRector shows missleading "! [NOTE] File "/x.php" will be added:" notice

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4418]
# Bug Report

When running the `NormalizeNamespaceByPSR4ComposerAutoloadFileSystemRector` rule with a composer.json file and it matches a file/class and introduces a namespace to a file, but does not rename the file itself there is still a yellow notice on the command line saying "! [NOTE] File "/x.php" will be added:". This is somehow confusion although the technical explainition behind this behaviour probably is, that a file with a new namespace is reccognized by rector as a fresh new file ...

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.x-dev@172653b              |
| Installed as   | prefixed Rector PHAR                      |

## Minimal PHP Code Causing Issue
a.php
```
<?php 

class a{}
```

composer.json
```
{
 "autoload": {
    "psr-4": {
	"A":     "../src/",
    }
}
```

rector.php 
```
// [...]
return static function (ContainerConfigurator $containerConfigurator): void {
        $parameters = $containerConfigurator->parameters();

        $services = $containerConfigurator->services();
	$services->set(NormalizeNamespaceByPSR4ComposerAutoloadFileSystemRector::class); // composer.json to Filesystem

	$parameters->set(Option::EXCLUDE_RECTORS, [
		ReturnThisRemoveRector::class,
		Rector\MagicDisclosure\Rector\Return_\DefluentReturnMethodCallRector::class,
		Rector\MagicDisclosure\Rector\MethodCall\InArgFluentChainMethodCallToStandaloneMethodCallRector::class,
		Rector\MagicDisclosure\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector::class,
		Rector\Performance\Rector\FuncCall\PreslashSimpleFunctionRector::class,
	]);
	
	$parameters->set(Option::PHP_VERSION_FEATURES, '7.1');
        $parameters->set(Option::AUTO_IMPORT_NAMES, true);
        $parameters->set(Option::IMPORT_SHORT_CLASSES, false);
        $parameters->set(Option::IMPORT_DOC_BLOCKS, false);
}
```
running

`php -d memory_limit=5G ./rector.phar process -vvv --dry-run ../`

shows 

```
[...]
----------------------------------------

 ! [NOTE] File "[...]a.php" will be added:

----------------------------------------
[...]
```

## Expected Behaviour

There should not be a notice about a file beeing added when there is no file beeing added.

**Comment by TomasVotruba** [comment]
Nice and clear report!

Could you find where is this confusing message created?

**Comment by powtac** [comment]
> Could you find where is this confusing message created?

https://github.com/rectorphp/rector/blob/52ccfc05270ec4e2cd039818017cde89ac9768da/src/Application/FileSystem/RemovedAndAddedFilesProcessor.php#L69

**Comment by TomasVotruba** [comment]
I see. Where is the file incorrectly added to `removedAndAddedFilesCollector` in `NormalizeNamespaceByPSR4ComposerAutoloadFileSystemRector`?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback.

We'll need a reproducible repository on GitHub to be able to fix it.
