### ISSUE TITLE
Replace method + anonymous function with the content of the anonymous function

### ISSUE THREAD

**Issue by gbirke** [rectorphp/rector#4423]
# Question

We have many method calls like this in our code:

    $myGodClass->doAfterInitialization(function( $service1, $service2 ){
       $service1->call();
       $service2->doSomething();
   });

I'd like to replace the complete method call and the anonymous function with code like this:

    $service1 = $this->getService1();
    $service2 = $this->getService2();
    $service1->call();
    $service2->doSomething();

What I couldn't figure out from the documentation and some code reading were the following questions:

   * Is it possible to replace a `MethodCall` with multiple statements (returning an array of Nodes or a special compound Node from `refactor`)?
   * How do I get to the function body (statements) from a `Param` object if it's a callable (an anonymous function)?

**Comment by TomasVotruba** [comment]
Hi, thanks for intersting question.

1. It is possible:

```php
// $this->addNodeAfterNode(<nodeToBeAdded>, <positoinNode);
$this->addNodeAfterNode($first, $methodCall);
$this->addNodeAfterNode($second, $methodCall);

$this->removeNode($methodCall);
```

**Comment by gbirke** [comment]
Thank you so much! With your help I could write a custom class in no time:

```php
class ExtractCallback extends AbstractRector {

   /**
     * @return string[]
     */
    public function getNodeTypes(): array
    {
  
        return [MethodCall::class];
    }

    /**
     * @param MethodCall $node - we can add "MethodCall" type here, because
     *                         only this node is in "getNodeTypes()"
     */
    public function refactor(Node $node): ?Node
    {
        if (! $this->isName($node->name, 'withCallback')) {
            // return null to skip it
            return null;
		}

		$currentClass = new Variable('this');
		$serviceOne = new Variable('service1');
		$serviceTwo = new Variable('service1');
		$serviceOneInit = new Assign($serviceOne, new MethodCall($currentClass, 'getService1'));
		$serviceTwoInit = new Assign($serviceOne, new MethodCall($currentClass, 'getService2'));
		$this->addNodeAfterNode($serviceOneInit, $node);
		$this->addNodeAfterNode($serviceTwoInit, $node);

		$callbackFunction = $node->args[0]->value;
		foreach($callbackFunction->stmts as $stmt) {
			$this->addNodeAfterNode($stmt, $node);
		}
		$this->removeNode($node);

		return null;
    }

    /**
     * From this method documentation is generated.
     */
    public function getDefinition(): RectorDefinition
    {
        return new RectorDefinition(
            'Replace "withCallback" calls with service initialization and callback contents', [
                new CodeSample(
                    <<<'CODE_SAMPLE'
'$this->withCallback(function($service1, $service2) {
	// first statement
	// second statement
	// ...
	});'
CODE_SAMPLE
		,
			<<<'CODE_SAMPLE'
	$service1 = $this->getService1();
	$service2 = $this->getService2();
	// first statement
	// second statement
	// ...
CODE_SAMPLE
                ),
            ]
        );
    }

}
```

Would you like me to add some documentation (not with this very specific example, but a little bit more generalized) that shows the usage of `addNodeAfterNode` and `removeNode`?

One more question: The code I'm trying to refactor is test code, with "significant whitespace": Blank lines separating the statements into [Arrange-Act-Assert](https://wiki.c2.com/?ArrangeActAssert) blocks. Those lines get dropped during refactoring, is there any way to preserve them?

**Comment by TomasVotruba** [comment]
> Thank you so much! With your help I could write a custom class in no time

That's epic skill :muscle: congrats!


> Would you like me to add some documentation

That would be amazing! Please add it under `/docs` and link it in the README file. These is a list of docs pages.

**Comment by TomasVotruba** [comment]
> Those lines get dropped during refactoring, is there any way to preserve them?

You've just hit a weak spot of AST, as we describe here: https://github.com/rectorphp/rector#how-to-apply-coding-standards

Sometimes the spaces are removed. You could integrate coding standards into Rector, but that would be like crashing 2 wheels into one. The best to handle it with coding standard tool, where you defined such rules in clear & realiable way.

**Comment by TomasVotruba** [comment]
Closing as answered.
