### ISSUE TITLE
Having trouble using Rector on a CodeIgniter project without Composer

### ISSUE THREAD

**Issue by Looouuu** [rectorphp/rector#4437]
# Question
Hello ! I'm trying to use Rector (especially the php7x sets, and maybe the CI4 one !) on a CodeIgniter 3 project. The project doesn't use Composer. 

I don't really understand how everything works :/ I tried this : 

    docker run --rm -v $(pwd):/project rector/rector:latest process [my app]/application --set php70   

which gives me a ton of errors that looks like

    Class xxx was not found while    
         trying to analyse it - discovering symbols is probably not configured  
         properly.

I had the best results with this config file and the composer package

```
<?php

// rector.php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    // paths to refactor; solid alternative to CLI arguments
    $parameters->set(Option::PATHS, [
        __DIR__.'/application/config',
        __DIR__.'/application/controllers',
        __DIR__.'/application/core',
        __DIR__.'/application/helpers',
        __DIR__.'/application/models',
        __DIR__.'/application/views',
    ]);
    
    // is there a file you need to skip?
    $parameters->set(Option::EXCLUDE_PATHS, [

    ]);
    $parameters->set(Option::SETS, [SetList::DEAD_CODE]);
    // // Rector relies on autoload setup of your project; Composer autoload is included by default; to add more:
    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__.'/vendor/autoload.php',
        __DIR__.'/system/core',
        __DIR__.'/system/libraries',
        __DIR__.'/application/core',
        __DIR__.'/application/controllers',
        __DIR__.'/application/libraries',
        __DIR__.'/application/models',
        // __DIR__.'/autoload-rector.php', 
    ]);

    // auto import fully qualified class names? [default: false]
    $parameters->set(Option::AUTO_IMPORT_NAMES, true);
};
```

Which gives me this error with --debug:

```
File "/var/www/html/[my project]/vendor/rector/rector/../../autoload.php" is about to be loaded in "AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 134"
Rector 0.8.27
Config file: rector.php

[parsing] application/config/autoload.php
[parsing] application/config/config.php
PHP Fatal error:  Uncaught Nette\InvalidStateException: Ambiguous class Ajax resolution; defined in /var/www/html/[my project]/application/controllers/app/Ajax.php and in /var/www/html/[my project]/application/controllers/Ajax.php. in /var/www/html/[my project]/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php:227```
```

Any idea how I could fix that ?

Thanks a lot :)

**Comment by TomasVotruba** [comment]
Hi,

thanks for detailed report.

This mean the classes is loaded twice. I'd check:

```php
 $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__.'/vendor/autoload.php',
        __DIR__.'/system/core',
        __DIR__.'/system/libraries',
        __DIR__.'/application/core',
        __DIR__.'/application/controllers',
        __DIR__.'/application/libraries',
        __DIR__.'/application/models',
        // __DIR__.'/autoload-rector.php', 
    ]);
```

and `composer.json` → `autoload` section.

It's loaded in both places, probably. If your code contains `include`/`require`, it might be related too.

**Comment by jeanmobayed** [comment]
I'm trying to use this tool to migrate PHPExcel, and I've been getting this error:

"Class xxx was not found while trying to analyse it - discovering symbols is probably not configured properly"

Is there any way to use this with Codeigniter 3?

**Comment by TomasVotruba** [comment]
That looks like autoload issue. The class must be autoloaded in `composer.json` or in autoload paths as mentioned in the [comment above](https://github.com/rectorphp/rector/issues/4437#issuecomment-711135221).

Good practise is to run PHPStan first, fix autoload issues, than run Rector. It will save lot of issue that would appear using Rector.

**Comment by TomasVotruba** [comment]
Closing as answerd
