### ISSUE TITLE
Remove param and return declaration docblock when type is equal and with no description

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#4453]
I have idea for rector rule that can remove `@param` and `@return` declaration docblock when type is equal and with no description, @TomasVotruba what do you think?

## Diff 

```diff
/**
-* @param string $a
 * @param string $b description
-* @return Type
*/
function foo(string $a, string $b): Type
{

}
```

**Comment by samsonasik** [comment]
@TomasVotruba btw, I am online at google meet if you want to talk ;)

**Comment by TomasVotruba** [comment]
This might be useful to re-use:

- https://github.com/rectorphp/rector/blob/042d1e0ddf0334725bc1c8011af2a0e3b35c7f83/rules/php74/src/Rector/Property/TypedPropertyRector.php#L200-L234
