### ISSUE TITLE
[RemoveEmptyClassMethodRector] Removed method but not related calls

### ISSUE THREAD

**Issue by natepage** [rectorphp/rector#4472]
Hi there 👋 

Consider the following rector output:
![Screen Shot 2020-10-21 at 4 07 35 pm](https://user-images.githubusercontent.com/11576446/96675860-aa2dc000-13b7-11eb-95fc-dbb1e8668bc2.png)

Makes sense because this method is empty, however, in the same class we were calling this method rector removed but this call hasn't been removed. So we end up having code calling a method which doesn't exist anymore.

- Should this be the responsibility of `RemoveEmptyClassMethodRector`?
- Or maybe there is already an existing rector for that and it's not in the DeadCode set?
- Or maybe it is in the DeadCode set but it runs before `RemoveEmptyClassMethodRector`?

**Comment by TomasVotruba** [comment]
Could you link the method call line in real code? I'll check it

The method call removal should be handled by `RemoveEmptyMethodCallRector` rule - https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#removeemptymethodcallrector

**Comment by natepage** [comment]
@TomasVotruba sorry I didn't see you commented on this...

I can't link to the method call in real code because I ran rector before committing (as everybody should do 😛 

But if you want to reproduce the class was really simple, consider the following:

```php
final class GeneratorStub
{
	public function __construct()
	{
		// This call was not removed by rector, even after removing the method itself
		$this->validateLineLengths(); 
	}

	protected function validateLineLengths(): void
	{
	}
}
```

So rector removed the method `validateLineLengths` but didn't remove the call in the constructor

**Comment by samsonasik** [comment]
@TomasVotruba it seems `RemoveEmptyMethodCallRector` doesnt remove method call when calling from `$this` inside a classmethod, see https://getrector.org/demo/68df5793-7f29-4f11-9999-d8334ee07e20#result
