### ISSUE TITLE
README example to exclude paths is wrong

### ISSUE THREAD

**Issue by JanWennrichPCSG** [rectorphp/rector#4473]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.40              |
| Installed as   | composer dependency                      |

I followed the [README example](https://github.com/rectorphp/rector/blob/master/README.md#configuration) to exclude folders from being parsed/processed by rector. When running rector with the `--debug` flag I saw that the excluded folders were still parsed.

## Minimal PHP Code Causing Issue

```php
    $parameters->set(Option::EXCLUDE_PATHS, [
        // single file
        __DIR__ . '/src/ComplicatedFile.php',
        // or directory
        __DIR__ . '/src',
        // or fnmatch
        __DIR__ . '/src/*/Tests/*',
    ]);
```

## Expected Behaviour

The specified folders should be excluded. I found out that removing the `__DIR__` prefix fixes this problem. Therefore rector expects relative and not absolute paths, I guess?

This should be fixed in the README.

**Comment by TomasVotruba** [comment]
Hi, thanks for report.

- Could you provide full command you use?
- How does PHPStorm autocompletes the path in the config?
- What OS do you use?
- What is you minimal real `rector.php` config?

**Comment by JanWennrichPCSG** [comment]
> Could you provide full command you use?

In the same directory as the `rector.php` file I executed: `vendor/bin/rector process . --debug --dry-run`

-----------

> How does PHPStorm autocompletes the path in the config?

I used PHPStorm's autocompletion to create the paths with the `__DIR__` prefix in the config. You can find the config below.

--------------

> What OS do you use?

I'm running an up-to-date Kubuntu 20.04

---------------

> What is you minimal real rector.php config?

My `rector.php` config I used is the following:

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Assign\NullCoalescingOperatorRector;
use Rector\Php74\Rector\Class_\ClassConstantToSelfClassRector;
use Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector;
use Rector\Php74\Rector\Double\RealToFloatTypeCastRector;
use Rector\Php74\Rector\FuncCall\ArrayKeyExistsOnPropertyRector;
use Rector\Php74\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector;
use Rector\Php74\Rector\FuncCall\FilterVarToAddSlashesRector;
use Rector\Php74\Rector\FuncCall\GetCalledClassToStaticClassRector;
use Rector\Php74\Rector\FuncCall\MbStrrposEncodingArgumentPositionRector;
use Rector\Php74\Rector\Function_\ReservedFnFunctionRector;
use Rector\Php74\Rector\MethodCall\ChangeReflectionTypeToStringToGetNameRector;
use Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Php74\Rector\StaticCall\ExportToReflectionFunctionRector;
use Rector\Renaming\Rector\FuncCall\RenameFunctionRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    // not sure why this is here, seems like I forgot to remove it  - doesn't match my folder structure
    $parameters->set(Option::PATHS, [__DIR__ . '/src', __DIR__ . '/tests']);

    // Tried this with and without the asterisks
    $parameters->set(Option::EXCLUDE_PATHS, [
        __DIR__ . 'flugh2/full/datasource/libraries/external/tcpdf/fonts/*',
        __DIR__ . 'flugh2/full/datasource/tcpdf/fonts/*',
        __DIR__ . 'vendor/*'
    ]);

    $parameters->set(Option::ENABLE_CACHE, true);

    $parameters->set(Option::AUTOLOAD_PATHS, []);

    $services = $containerConfigurator->services();

    $services->set(TypedPropertyRector::class);

    $services->set(RenameFunctionRector::class)
        ->call('configure', [[
            RenameFunctionRector::OLD_FUNCTION_TO_NEW_FUNCTION => [
                'is_real' => 'is_float',
                'apache_request_headers' => 'getallheaders'
            ],
        ]]);

    $services->set(ArrayKeyExistsOnPropertyRector::class);

    $services->set(FilterVarToAddSlashesRector::class);

    $services->set(ExportToReflectionFunctionRector::class);

    $services->set(ClassConstantToSelfClassRector::class);

    $services->set(GetCalledClassToStaticClassRector::class);

    $services->set(MbStrrposEncodingArgumentPositionRector::class);

    $services->set(RealToFloatTypeCastRector::class);

    $services->set(NullCoalescingOperatorRector::class);

    $services->set(ReservedFnFunctionRector::class);

    $services->set(ClosureToArrowFunctionRector::class);

    $services->set(ArraySpreadInsteadOfArrayMergeRector::class);

    $services->set(ChangeReflectionTypeToStringToGetNameRector::class);

    $services->set(RestoreDefaultNullToNullableTypePropertyRector::class);
};
```

**Comment by TomasVotruba** [comment]
I see. Thanks for the answers.

```php
    $parameters->set(Option::EXCLUDE_PATHS, [
        __DIR__ . 'flugh2/full/datasource/libraries/external/tcpdf/fonts/*',
        __DIR__ . 'flugh2/full/datasource/tcpdf/fonts/*',
        __DIR__ . 'vendor/*'
    ]);
```

Could you dump each of those 3 lines? What's the content you get back them?

**Comment by JanWennrichPCSG** [comment]
Okay, seems like the problem was my fault:

```
Array
(
    [0] => /var/www/flughafenflugh2/full/datasource/libraries/external/tcpdf/fonts/*
    [1] => /var/www/flughafenflugh2/full/datasource/tcpdf/fonts/*
    [2] => /var/www/flughafenvendor/*
)
```

There should be a `/` after `/var/www/flughafen` so I'm missing the `/` after the `__DIR__` constant in my array.

After adding the `/` it works correctly - sorry for the inconvenience.

**Comment by TomasVotruba** [comment]
I see. 

I think we should help user avoid these typos. Any ideas?

**Comment by JanWennrichPCSG** [comment]
Maybe write the paths in the example like this:

```php
__DIR__ . '/' .  'this/is/my/path/*'
```

**Comment by TomasVotruba** [comment]
I see. That looks rather bug, as there is no reason to separate 2 strings.

What about some check in code?

**Comment by JanWennrichPCSG** [comment]
A check in code could be a good idea. 

Maybe you could check if the specified paths exist and if not, a warning is shown when starting the script.

**Comment by TomasVotruba** [comment]
That sounds good!
Would you like to implement it?
