### ISSUE TITLE
Replace symfony role strings with their corresponding class constants

### ISSUE THREAD

**Issue by TavoNiievez** [rectorphp/rector#4474]
### Replace symfony role strings with their corresponding class constants.

less mistakes, more info on how the security component works.

```diff
<?php

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
+ use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;

return static function (ContainerConfigurator $configurator): void
{
    $configurator->extension('security', [
        'access_control' => [
            [
				'path' => '^/login',
-				'roles' => 'IS_ANONYMOUS'
+               'roles' => AuthenticatedVoter::IS_ANONYMOUS
			]
        ]
    ]);
};
```

**Comment by TomasVotruba** [comment]
Hi,

thanks for the idea. It could be part of [`SYMFONY_CODE_QUALITY`](https://github.com/rectorphp/rector/blob/master/config/set/symfony-code-quality.php) set.

Yet, we don't have on out priority list. 
Would you like to contribe it or shall we close this?

**Comment by TavoNiievez** [comment]
I'm not really sure how to contribute, is it too complex?

**Comment by TomasVotruba** [comment]
This one should be quite easy. 

- Get a `String_` node
- Check if inside a Symfony config closure
- If `IS_ANONYMOUS` value, replace it with `new ClassConstFetch()`

The best way to start is Docs for [Create own rule](https://github.com/rectorphp/rector/blob/master/docs/create_own_rule.md).


This rule is also working with Symfony PHP Config - you can find some inspiration there: https://github.com/rectorphp/rector/blob/master/rules/symfony-php-config/src/Rector/MethodCall/AutoInPhpSymfonyConfigRector.php
