### ISSUE TITLE
Doctrine annotation gets Semantical Error

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#4476]
# Bug Report

Rector creates an annotation with a Semantical Error: Couldn't find constant token.

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.42, dev-master@0d6b5ae              |
| Installed as   | composer dependency                       |
| PHP | 7.4.11 |

## Minimal PHP Code Causing Issue

Before:
```
<?php
use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Table(name="UserPasswordReset", uniqueConstraints={
 *      @ORM\UniqueConstraint(
 *          name="unique_reset", columns={
 *              "token"
 *          }
 *      )
 * })
 */
class UserPasswordReset {}
```

After:
```
<?php
use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Table(name="UserPasswordReset", uniqueConstraints={
 *      @ORM\UniqueConstraint(
 *          name="unique_reset", columns={token}
 *              )
 *          }
 *      )
 */
class UserPasswordReset {}
```
## Expected Behaviour

I think the 'before' code should be untouched, there's nothing wrong with it.

https://getrector.org/demo/b33a8393-de10-4d79-88ca-496b1cbaee2e#result

**Comment by stephanvierkant** [comment]
I found the reason: Rector can't handle the line breaks. `columns={"token"}` does work properly.

**Comment by simivar** [comment]
It gets applied as well when running Rector with `--only` option, for example:
```
vendor/bin/rector process src --dry-run --set code-quality --only SimplifyUselessVariableRector
```
