### ISSUE TITLE
Fixer to migrate from `DateTime` to `DateTimeInterface`

### ISSUE THREAD

**Issue by JoyceBabu** [rectorphp/rector#4478]
# Feature Request
Is there a fixer to allow migration from `DateTime` to `DateTimeInterface`? If not, would you think such a fixer would be useful?

`DateTime` is mutable, whereas `DateTimeImmutable` is immutable. Call to methods `add`, `modify`, `setDate`, `setISODate`, `setTime`, `setTimestamp`, `setTimezone` and `sub` modify the original object in `DateTime`, whereas a new object is returned in case of `DateTimeImmutable`. Other than that, the behaviour is exactly the same between `DateTime` and `DateTimeImmutable`. And all instances of `DateTime` can be replaced with `DateTimeInterface`.

Switching from `DateTime` to `DateTimeInterface` this way will cause static analyzers to spew warnings, since the above methods are not part of `DateTimeInterface`. If it is possible to add a `@param \DateTimeImmutable|\DateTime $var` phpdoc annotation on changing the function signature, that would solve this.

`DateTimeInterface` [cannot be implemented](https://github.com/php/php-src/blob/41b096b392e551df51c80d29f6f30c163a0630ea/ext/date/php_date.c#L1565) by other classes, so it is safe to assume that `DateTime` and `DateTimeImmutable` are the only classes implementing `DateTimeInterface`.
 
## Diff 

```diff
- function nextDay(\DateTime $datetime) {
-     $datetime->modify('+1 day');
      return $datetime;
+ /**
+  * @param \DateTime|\DateTimeImmutable $datetime
+  */
+ function nextDay(\DateTimeInterface $datetime) {
+     $datetime = $datetime->modify('+1 day');
      return $datetime;
}

- function getDay(\DateTime $datetime) {
+ /**
+  * @param \DateTime|\DateTimeImmutable $datetime
+  */
+ function getDay(\DateTimeInterface $datetime) {
     return $datetime->format('n');
}

- /**
-  * @param \DateTime $datetime
-  */
- function foo(\DateTime $datetime) {
-     return getDay($datetime->modify('+1 day'));
+ /**
+  * @param \DateTime|\DateTimeImmutable $datetime
+  */
+ function foo(\DateTimeInterface $datetime) {
+     return getDay($datetime = $datetime->modify('+1 day'));
}
```

**Comment by TomasVotruba** [comment]
Hi, 

there is no such rule yet. It might be useful for code quality set.

We don't have it in our plan, but if you'd like contribute it, I can guide you in the pull request

**Comment by JoyceBabu** [comment]
I might require this for an upcoming migration. If so, I will give it a try.

Can you please point me to any rector that modifies PhpDoc annotation?

**Comment by simivar** [comment]
I would say that those phpdocs are unnecessary when you have type-hint like `\DateTimeInterface`. Why would you restrict it to `\DateTime|\DateTimeImmutable`?

**Comment by simivar** [comment]
@JoyceBabu will you be working on it? I can try to implement it myself if you don't have time. If you are doing it and maybe need some help feel free to write to me as well.

**Comment by JoyceBabu** [comment]
> @JoyceBabu will you be working on it? I can try to implement it myself if you don't have time. If you are doing it and maybe need some help feel free to write to me as well.

@simivar I haven't started working on it. Please go ahead.
