### ISSUE TITLE
Remove redundant (default) values from @ORM annotations

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#4493]
# Feature Request

`\Doctrine\ORM\Mapping\JoinColumn::$nullable` defaults to `true`, so it makes no sense to configure it. A rector that removes redundant configured options would be nice.

## Diff 

```diff
use Doctrine\ORM\Mapping as ORM;
// ..

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
-    * @ORM\JoinColumn(name="user", nullable=true)
+    * @ORM\JoinColumn(name="user")
     */
    private ?User $user = null;
```

Same goes for `\Doctrine\ORM\Mapping\Column::$unique` (false), `\Doctrine\ORM\Mapping\Column::$nullable` (false), `\Doctrine\ORM\Mapping\Entity::$readOnly` (false), etc.

**Comment by TomasVotruba** [comment]
Hi, this feature would be nice contribution to Doctrine code quality set.
Unfortunately, it's not on our timeline.

Would you like to contribute it?

**Comment by simivar** [comment]
I wanted to try writing my first rule and decided on taking on this issue. #4531 is ready to be reviewed. :)

**Comment by TomasVotruba** [comment]
Closed by https://github.com/rectorphp/rector/pull/4542
