### ISSUE TITLE
I tried to use "phpexcel-to-phpspreadsheet", but it producted broken code

### ISSUE THREAD

**Issue by voku** [rectorphp/rector#4494]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.44)              |
| Installed as   | prefixed Rector PHAR                      |

I saw some problems after I tried "phpexcel-to-phpspreadsheet". 

1. broken property name

```php
    /**
     * @var PHPExcel
     */
    protected $PHPExcel;
```
⇉ becomes
```php
    /**
     * @var PhpOffice\PhpSpreadsheet\Spreadsheet
     */
    protected $PhpOffice\PhpSpreadsheet\Spreadsheet;
```

2. broken "Spreadsheet_Worksheet" usage

```php
   /**
     * @param PHPExcel_Worksheet $sheet
     * @param string             $range
     * @param mixed              $value
     * @param bool               $similarity
     *
     * @return array
     */
```
⇉ becomes
```php
   /**
     * @param PhpOffice\PhpSpreadsheet\Spreadsheet_Worksheet $sheet
     * @param string             $range
     * @param mixed              $value
     * @param bool               $similarity
     *
     * @return array
     */
```
... but ```PhpOffice\PhpSpreadsheet\Worksheet\Worksheet``` should be used here

3. broken "PHPExcel_Worksheet_HeaderFooterDrawing" usage
```php
$objDrawing = new PHPExcel_Worksheet_HeaderFooterDrawing();
```
⇉ becomes
```php
$objDrawing = new Spreadsheet_Worksheet_HeaderFooterDrawing();
```
... but ```PhpOffice\PhpSpreadsheet\Worksheet\HeaderFooterDrawing``` should be used here

4. broken "PHPExcel_Style_Protection" usage
```php
PHPExcel_Style_Protection::PROTECTION_UNPROTECTED;
```
⇉ becomes
```php
PhpOffice\PhpSpreadsheet\Spreadsheet_Style_Protection::PROTECTION_UNPROTECTED
```
... but ```\PhpOffice\PhpSpreadsheet\Style\Protection``` should be used here

PS: thanks for your work

**Comment by TomasVotruba** [comment]
Hi, we'll need test case for this

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Feel free to reopen with failing test case. [Here is how you can add it](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md)
