### ISSUE TITLE
Code gets duplicated

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4499]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.44             |
| Installed as   | composer dependency                     |

When running a set (any set) on file `stubs/Symfony/Component/VarDumper/Test/VarDumperTestTrait.php`, its code gets duplicated:

```diff
if (trait_exists('Symfony\Component\VarDumper\Test\VarDumperTestTrait\VarDumperTestTrait')) {
     return;
+}if (trait_exists('Symfony\Component\VarDumper\Test\VarDumperTestTrait\VarDumperTestTrait')) {
+    return;
 }
```

It doesn't indicate which is the applied rule

## Minimal PHP Code Causing Issue

https://getrector.org/demo/67559c76-b2e7-44bd-bca2-ec78a35d7f47#result

**Comment by leoloso** [comment]
This situation happens with many classes under `stubs/`

**Comment by leoloso** [comment]
For instance, for `stubs/Symfony/Component/EventDispatcher/EventDispatcherInterface.php`:

```diff
if (interface_exists('Symfony\Contracts\EventDispatcher\EventDispatcherInterface')) {
     return;
+}if (interface_exists('Symfony\Contracts\EventDispatcher\EventDispatcherInterface')) {
+    return;
 }
```

https://getrector.org/demo/b3c17423-ed9b-4aa9-8805-a4c3700f2e78#result

**Comment by TomasVotruba** [comment]
We'll need a failing test fixuter for this. See https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
@TomasVotruba the code duplication happen in any set, not only dead-code set, it may related with the process on updating node?

**Comment by TomasVotruba** [comment]
Agreed. The printed is doing something twice.
Still, having a tests case with one rule will show it.
