### ISSUE TITLE
[DX] Remove "'#Add regex101\.com link to that shows the regex in practise, so it will be easier to maintain in case of bug/extension in the future#'" from PHPStan

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4503]
These cases:
https://github.com/rectorphp/rector/blob/35804361aa4fbf34d99c324757fdf23dcecff485/phpstan.neon#L655-L771

@samsonasik Could you look at this? Basically the same work you've done for Symplify

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
fixed at https://github.com/rectorphp/rector/pull/4504
