### ISSUE TITLE
CallableThisArrayToAnonymousFunctionRector changes class’ fields default values where expressions not allowed

### ISSUE THREAD

**Issue by lptn** [rectorphp/rector#4516]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.7@869441e              |
| Installed as   |prefixed Rector PHAR                      |

`CallableThisArrayToAnonymousFunctionRector` changes class’ fields default values to anonymous functions,  but expressions not allowed in this context

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f0bfdd44-5851-4d6a-822b-ae715eca3d32

## Expected Behaviour

Rector should skip class field declarations

**Comment by lptn** [comment]
It looks like  `ArrayThisCallToThisMethodCallRector` does the same

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting!
