### ISSUE TITLE
Nette\Application\UI\Control has no constructor so it cannot be called

### ISSUE THREAD

**Issue by xpavp03** [rectorphp/rector#4539]
The [refactored version](https://github.com/rectorphp/rector/blob/5c90d522e94b5044e6c4a116797cd8c30c00917c/rules/nette/tests/Rector/ClassMethod/RemoveParentAndNameFromComponentConstructorRector/Fixture/back_order.php.inc#L29
) of this RemoveParentAndNameFromComponentConstructorRector test fixture calls constructor of Nette\Application\UI\Control which doesn't exist:
> Fatal error: Uncaught Error: Cannot call constructor in ... on line ...
> Error: Cannot call constructor in ...

I don't think the [version before refactoring](https://github.com/rectorphp/rector/blob/084805774b8073b6a3afb8aecca6fa0abd3afc99/rules/nette/tests/Rector/ClassMethod/RemoveParentAndNameFromComponentConstructorRector/Fixture/back_order.php.inc#L12) would exist like this in real life, accepting $value as the third parameter. AFAIK, Nette\Application\UI\Control never accepted anything other than $parent and $name.

In theory, you could pass more arguments to it than what it was accepting but why would you do it.

IMHO the refactored version should drop parent::__construct() completely.

A related question: Does this Rector rule cover extended cases like
> MyControl extends MyBaseControl
> MyBaseControl extends Nette\Application\UI\Control

Would it correctly remove $parent and $name from new MyControl, MyControl::__construct() and MyBaseControl::__construct()?

**Comment by TomasVotruba** [comment]
The fixture only demonstrates correct parameter removal, the rest is irelevant and can't existing in real life.

**Comment by TomasVotruba** [comment]
> Does this Rector rule cover extended cases like

Depends. Could you add [a test](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md) for that?

**Comment by TomasVotruba** [comment]
Closing as issue question was answered
