### ISSUE TITLE
Fatal error: Cannot use FG\ASN1\Object as Object because 'Object'

### ISSUE THREAD

**Issue by berndlosert** [rectorphp/rector#4555]
# Bug Report

**Rector version**: dev-master@0cc7b66
**Installed as**: docker image

When I run `rector process`, it dies with

```
Fatal error: Cannot use FG\ASN1\Object as Object because 'Object' is a special class name in /project/vendor/spomky-labs/jose/src/KeyConverter/ECKey.php on line 17
```

This is a known problem: 

 - https://github.com/Spomky-Labs/jose/pull/298
 - https://github.com/fgrosse/PHPASN1/issues/65

I guess some of the dependencies need to be updated.

**Comment by TomasVotruba** [comment]
Hi,

this needs to be updated in the dependencies, as `object` is reserved keyword since PHP 7.2

**Comment by berndlosert** [comment]
Oops. The dependency is from the code of my project. I mistankingly thought it was from Rector. My bad.

**Comment by TomasVotruba** [comment]
I see, no troubles
