### ISSUE TITLE
php-parser's PrettyPrinter\Standard cause code-duplication in BetterStandardPrinter

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#4556]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest              |
| Installed as   | composer dependency / prefixed Rector PHAR                      |

This related too https://github.com/rectorphp/rector/issues/4499 that print code duplication `if (interface_exists('InterfaceName')) {}` or `if trait_exists('TraitName') { }` followed by `interface InterfaceName` or `trait TraitName`.

There is rector tweak for that https://github.com/rectorphp/rector/pull/4553 but probably better fix in php-parser side. 

## Minimal PHP Code Causing Issue

- https://github.com/rectorphp/rector/tree/3940e42d259c4dff681a71c2a8bae392e8283e36/tests/Issues/Issue4499/DoNotDuplicateCode/Fixture

The issue happen for both has bracket and not has bracket syntax.

## Expected Behaviour

Should be works without tweak.

**Comment by TomasVotruba** [comment]
Closed by https://github.com/nikic/PHP-Parser/issues/738

**Comment by samsonasik** [comment]
ok, I am closing it.
