### ISSUE TITLE
PHP8: Named arguments fix

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#4558]
# Feature Request

Auto fix named argument signature diff for methods.

Currently, e.g. psalm finds these already:
```json
        {
            "severity": "error",
            "line_from": 38,
            "line_to": 38,
            "type": "ParamNameMismatch",
            "message": "Argument 1 of ...UploadedFileCsvTypeValidator::isValidRowCount has wrong name $file, expecting $uploadedFile as defined by ...UploadedFileTypeValidatorInterface::isValidRowCount",
            "file_name": "...UploadedFileCsvTypeValidator.php",
            "snippet": "    public function isValidRowCount(UploadedFile $file, int $rowCountLimit): bool",
            "selected_text": "$file",
            "error_level": 7,
            "shortcode": 230
        },
```

See e.g.
```php
    /**
     * @param \Symfony\Component\HttpFoundation\File\UploadedFile $file
     * @param int $rowCountLimit
     *
     * @return bool
     */
    public function isValidRowCount(UploadedFile $file, int $rowCountLimit): bool
    {
        $uploadedOrder = $this->utilCsvService->readUploadedFile($file);

        return $rowCountLimit >= count($uploadedOrder);
    }
```

Even though the parent class or interface is
```php
    /**
     * @param \Symfony\Component\HttpFoundation\File\UploadedFile $uploadedFile
     * @param int $rowCountLimit
     *
     * @return bool
     */
    public function isValidRowCount(UploadedFile $uploadedFile, int $rowCountLimit): bool;
```

Renaming this with str_replace is not a good idea, as you could miss the scope, or rename too much in that file
So a safe way to rename all occurrences inside the scope (excluding e.g. subscopes as callables) would be needed here.
IDEs can usually do that using ShiftReplace (Safe replace), but on a more automated tooling level this wouldn't be practical to prepare for PHP 8.

**Comment by TomasVotruba** [comment]
Hi,

I'm not sure I understand as I haven't worked with named arguments yet. 
Could you sum-up very shortly what should happen when?

Ideally with 1-diff example

```diff
-public function isValidRowCount(UploadedFile $file, int $rowCountLimit): bool

**Comment by dereuromark** [comment]
Yes, sure
The parent signature is the leading one, so if that says `$uploadedFile` then all extending classes should also use the same variable name inside the signature.
Otherwise PHP 8 named arguments will have a problem.

So above:
```diff
-public function isValidRowCount(UploadedFile $file, int $rowCountLimit): bool
+public function isValidRowCount(UploadedFile $uploadedFile, int $rowCountLimit): bool
{
```
as you said.

**Comment by TomasVotruba** [comment]
I see. So the interface is the main source of truth?

**Comment by dereuromark** [comment]
Any parent, it could also be an abstract class or even a normal class that you extend.
But from a named param perspective any change in variable name is a BC break on the named argument functionality.

**Comment by TomasVotruba** [comment]
I see. So the highest parent class/parent interface should propagate the name to all its children?

**Comment by dereuromark** [comment]
Thats what I understand from it - and also https://stitcher.io/blog/php-8-named-arguments

> PHP will silently allow changing the name of $event to $myEvent, and $handler to $myHandler; but if you decide to use named arguments using the parent's name, it will result in a runtime error. This pragmatic approach was chosen to prevent a major breaking change when all inherited arguments would have to keep the same name

But you can easily see that if a vendor library like Symfony or CakePHP decides to use a different variable as any extending parent, if in a minor or patch, could easily lead to project code being now breaking hard.

**Comment by TomasVotruba** [comment]
Hi, it's not on our priority list ATM as scoped and downgraded version are more relevant to PHP community. 
But we're open to external contribution. Feel free to reopen with PR :+1:
