### ISSUE TITLE
checkout fails with windows - path name too long

### ISSUE THREAD

**Issue by maddy2101** [rectorphp/rector#4566]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | checkout with master and 0.8.48 (latest release)              |
| Installed as   | composer dependency / git checkout

I get this error:

$ git clone https://github.com/rectorphp/rector.git
Cloning into 'rector'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 162139 (delta 26), reused 41 (delta 15), pack-reused 162066R
Receiving objects: 100% (162139/162139), 33.57 MiB | 5.17 MiB/s, done.
Resolving deltas: 100% (96416/96416), done.
error: unable to create file rules/doctrine/tests/Rector/ClassMethod/ServiceEntityRepositoryConstructorToDependencyInjectionWithRepositoryPropertyRector/ServiceEntityRepositoryConstructorToDependencyInject
ionWithRepositoryPropertyRectorTest.php: Filename too long
Updating files: 100% (6529/6529), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

## Minimal PHP Code Causing Issue

just try to checkout master

## Expected Behaviour

please shorten the file name. Windows does not like it.

Bonus ;) TYPO3 got a similar problem some time back, and we added this check to our test suite in order to prevent it from happening again: https://github.com/TYPO3/TYPO3.CMS/blob/master/Build/Scripts/maxFilePathLength.sh

**Comment by TomasVotruba** [comment]
That's a great idea with that script 👏

Thanks for sharing it, well add it here

**Comment by shyim** [comment]
Why not increasing it in Windows? 😅

**Comment by TomasVotruba** [comment]
@shyim To improve Rector DX :) it's our priority, regarding the scope it handles. Also it's probably a poorly written test
