### ISSUE TITLE
[PHP80] Attribute migration breaks with aliased use

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#4569]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@b4fd520             |
| Installed as   | Docker                      |

## Minimal PHP Code Causing Issue

https://github.com/FriendsOfShopware/packages/blob/4d5a139c517319b8c899ce2ed27928053227a587/src/Entity/Download.php

Result:
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[@ORM\Entity(repositoryClass: 'DownloadRepository::class')]
class Download
{
    #[@ORM\Id]
    #[@ORM\GeneratedValue]
    #[@ORM\Column(type: 'integer')]
    private int $id;
```

Seems like aliasing breaks it

```


## Expected Behaviour

The file work as expected

**Comment by TomasVotruba** [comment]
Hi, thanks for report.
Could you add failing test for it?

Here is how: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by TomasVotruba** [comment]
Closing for missing test case. Feel free to re-open with test PR
