### ISSUE TITLE
Symfony Route annotations are broken by Rector DEAD_CODE

### ISSUE THREAD

**Issue by dameert** [rectorphp/rector#4573]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector dev-master@4764fd1             |
| Installed as   | composer dependency                       |

Rector "DEAD_CODE" changes Symfony Route annotations defaults incorrectly. `defaults={"_format": "json"}` becomes `defaults={"_format"="json"}`.

## Minimal PHP Code Causing Issue
```
<?php
namespace App;

use Symfony\Component\Routing\Annotation\Route;

class Controller
{
    /**
     * @Route("/route/{view}.{_format}", name="views.test", defaults={"_format": "json"}, methods={"POST"})
     */
    public function updateAction()
    {
        return 'oops';
    }
}
```

https://getrector.org/demo/8d9faf4a-1729-4c34-8d56-6adf9cc63eaf#result

## Expected Behaviour
Rector DEAD_CODE should not change the `: ` (including space) to  `=` in Route annotations.

**Comment by dameert** [comment]
Might be related to #3932 however the change made is different. I am eager to find a solution, but am not sure where to start looking for these annotation updates using the DEAD_CODE set.

**Comment by TomasVotruba** [comment]
Hi,

this is well known problem. The annotation don't have a tool in PHP world that would parse it and preserve the format. There are made few assumption, to make php doc changes work.

What real issue this causes aparat different syntax?

**Comment by TomasVotruba** [comment]
Sub-problem of https://github.com/rectorphp/rector/issues/4334
