### ISSUE TITLE
Fixer to add return type-hints to methods in PHPUnit test cases

### ISSUE THREAD

**Issue by simivar** [rectorphp/rector#4608]
# Feature Request

Is there maybe a fixer that adds return type-hints to methods in PHPUnit test cases? I mean:
- to `test*()` or marked `@test` adds `void`
- to `@dataProvider` adds `array` or `\Generator`
- to `setUp()`, `tearDown()` etc. adds `void`
 
## Diff 

```diff
final class MyTest extends \PHPUnit\Framework\TestCase 
{
-    public function testSomething()
+    public function testSomething(): void
    {
        self::assertSame(1, 1);
    }
}
```

**Comment by TomasVotruba** [comment]
Check this one: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#addreturntypedeclarationrector
