### ISSUE TITLE
phpunit assertEquals -> assertEqualsWithDelta keep assertEquals without delta

### ISSUE THREAD

**Issue by mvorisek** [rectorphp/rector#4619]
# issue
![image](https://user-images.githubusercontent.com/2228672/99236046-f6bdbd00-27f6-11eb-80cb-459d6bd9fc61.png)

1st assertEquals without delta fails and only assertEqualsWithDelta should be added

# config - sets
```
[
SetList::PHPUNIT_80,
]
```

**Comment by TomasVotruba** [comment]
Hi,

could you provide failing test case to the rule?

Here is how: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by mvorisek** [comment]
Tomáši, I am not gonna do that.

**Comment by TomasVotruba** [comment]
I see. We need failing test case to fix it. 
There could be so many other things that go wrong, like environment, PHP version, miss configured installataion etc.
