### ISSUE TITLE
Variable cannot begin with a number in PHP

### ISSUE THREAD

**Issue by popovserhii** [rectorphp/rector#4621]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector dev-master@765862c (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/b983bbd2-3e35-4e32-af6c-f4ae1f2a130b

## Expected Behaviour

`$_3p` variable shouldn't be changed to `$3p`, because this is not a valid variable name in PHP (tested on PHP 7.3).

**Comment by TomasVotruba** [comment]
:+1: 

Thank you @samsonasik for the fix
