### ISSUE TITLE
Argument 8 passed to PHPStan\Analyser\MutatingScope::__construct() must implement interface PHPStan\Parser\Parser

### ISSUE THREAD

**Issue by escopecz** [rectorphp/rector#4626]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.25             |
| Installed as   | tried both: composer dependency and prefixed Rector PHAR                      |

Hi Tomas and the team! Long time no see. It's again time of the year where we upgrade Symfony Framework on the mautic/mautic OS project. And I thought this time I will use Rector! Because the prefixed version was not ready last year in time and I can even use the real library this time. We are using it in CI anyway. It works!

So I'm several hours after that thought and hitting an error after error. Here's quick timeline:

1. I hit an error that was fixed in December 2019. Simple enough, I'll upgrade the library to the latest.
2. Following https://tomasvotruba.com/blog/2019/02/28/how-to-upgrade-symfony-2-8-to-3-4/ I wanted to run `vendor/bin/rector process app src --set symfony34` which is the current Symfony version we use. Just to see if there is something we missed during manual upgrade last year. But Rector says that the `--set` param doesn't exist. No docs for that but I notice that the Rector config has changed from yaml to php. Easy enough, I'll re-write it to the new syntax.
3.But PHP doesn't see the namespaces in the prefixed version. I don't see any docs about that nor issues. Simple enough we can use the real deal this time. Removing the prefixed Rector and installing rector/rector. The latest possible version is 0.7.25.
4. It still uses yaml, so no need to change the syntax of the config file :tada:. I run the synfony34 set again. It knows the command param again 🎉 . However it ends with a flood of `Could not process "app/middlewares/CatchExceptionMiddleware.php" file, due to: "Argument 1 passed to Rector\NodeCollector\NodeFinder\ClassLikeParsedNodesFinder::findInterface() must be of the type string, null given, called in vendor/rector/rector/rules/dead-code/src/Rector/ClassConst/RemoveUnusedClassConstantRector.php on line 80".`. Simple enough. I'll exclude the `Rector\DeadCode\Rector\ClassConst\RemoveUnusedClassConstantRector`.
5. Running Rector again. It ends with a flood of `Could not process "app/migrations/Version20200815153711.php" file, due to: "Argument 8 passed to PHPStan\Analyser\MutatingScope::__construct() must implement interface PHPStan\Parser\Parser, instance of PHPStan\Analyser\ScopeContext given, called in /var/www/html/vendor/rector/rector/packages/node-type-resolver/src/PHPStan/Scope/ScopeFactory.php on line 77".` I don't know what to do here. I upgraded PHPSTAN as well. To version 0.12.55. Any clue what to try next? It somehow feels that manual upgrade will be faster.

## Minimal PHP Code Causing Issue

Can't tell what's wrong.

**Comment by TomasVotruba** [comment]
Hi,

thanks for detailed report and sorry for the troubles.

I see version 0.7.* and it very old and not developed anymore. Upgrade to version `0.8.56` and see if the problem persists.

**Comment by escopecz** [comment]
Thanks for a quick answer! That's what I did in step 2 with rector-prefixed. However I cannot get PHP config work. That's why I chose to use raw rector but Composer cannot install higher version than 0.7.*. So I guess the path forward is to go back to rector-prefixed but how does the PHP config work there? I cannot use namespaces that are in the rector docs as those are prefixed, right? Do you have any docs about that?

**Comment by TomasVotruba** [comment]
> However I cannot get PHP config work.

That's the place we need to fix. What exactly is problem there?

**Comment by TomasVotruba** [comment]
Closing as Rector 0.7 is not supported anymore, so original issue is not viable.

Feel free to create new issue on how to make `rector.php` config work.
