### ISSUE TITLE
Unable to install with symplify/easy-hydrator 9.0.0-BETA2 - cyclic composer reference

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#4627]
Hi, there is cyclic reference for packages `symplify/easy-hydrator` and `rector/simple-php-doc-parser` both requires `symplify/package-builder` but in different version.

## Steps reproduce:
composer.json:
```json
{
    "require": {
        "php": "7.4.*",
        "symplify/easy-hydrator": "dev-master",
        "rector/rector": "0.8.*|dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```
Run `composer install`

## The problem:
```
❯ composer update

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symplify/easy-hydrator 9.0.0-BETA2 -> satisfiable by symplify/easy-hydrator[9.0.0-BETA2].
    - Only one of these can be installed: rector/simple-php-doc-parser[0.8.56], rector/rector[dev-master]. rector/rector replaces rector/simple-php-doc-parser and thus cannot coexist with it.
    - symplify/easy-hydrator 9.0.0-BETA2 requires rector/simple-php-doc-parser ^0.8.56 -> satisfiable by rector/simple-php-doc-parser[0.8.56].
    - Root composer.json requires rector/rector dev-master -> satisfiable by rector/rector[dev-master].
```

## Proposed solution
My proposal is to add `|9.0.x-dev` (or dev-master) here: https://github.com/rectorphp/rector/blob/master/packages/simple-php-doc-parser/composer.json#L10 which will temporarily fix the issue and allow these 2 packages to coexist in same project.

This is temporary as when releasing rector 0.9 i believe there will be dependency bump up to newer symplify 9.0 once it gets released too :-).

**Comment by TomasVotruba** [comment]
Now I see why it didn't run. `monorepo-builder.php` needed an update :) 

![image](https://user-images.githubusercontent.com/924196/99321157-800fd680-286d-11eb-9955-ffadbfdad4f9.png)

**Comment by TomasVotruba** [comment]
There it is:
https://github.com/rectorphp/rector/commit/e618d3d74f39ad35d76072909753028ddbf4a63b

**Comment by JanMikes** [comment]
Thanks.

Yeah, now we need bump in symplify 😄 as dev-master symplify/easy-hydrator requires `rector/simple-php-doc-parser: ^0.8.56` which requires again stable symplify, this is real circular dependency 😄

**Comment by TomasVotruba** [comment]
As I wrote in the DM, there will be lot of BC breaks on all 3 `dev-master`s now :), so I'd avoid any upgrading for next 2 weeks and wait for the stable.

**Comment by JanMikes** [comment]
Yeah, i thought i am able to handle it but impossible 😄 i was forced to run `composer update` in our project but i can avoid it. 

Good luck and i will be waiting for the release ❤️ 

Feel free to close this issue as it will be addressed in release

**Comment by TomasVotruba** [comment]
> i was forced to run composer update in our project

Who did that to you? :laughing: 


> Good luck and i will be waiting for the release heart

Thanks :+1: 

<br>


Closing as there `dev-master` is not stable in many cases yet, just to prevent people adding obvious issues.

**Comment by JanMikes** [comment]
> Who did that to you? 😆

Myself 😄 moving last 3 repositories into monorepo and i wanted to do it all at once, instead i was able to solve it by `composer update X` step by step, i was too hursh 😄 

Yep, thank you!

**Comment by TomasVotruba** [comment]
I see :D
