### ISSUE TITLE
[Doctrine] Rules to upgrade DBAL from 2 to 3

### ISSUE THREAD

**Issue by simivar** [rectorphp/rector#4635]
# Feature Request

[doctrine/dbal](https://github.com/doctrine/dbal/blob/3.0.x/UPGRADE.md) of version 3 was released. It would be nice to have rectors to migrate from version 2 to 3. Upgrade list is available [here](https://github.com/doctrine/dbal/blob/3.0.x/UPGRADE.md). As there are many breaking changes it would be nice to prepare some specific issues and break them down into specific rules under one set.

**Comment by TomasVotruba** [comment]
There has been done some work already: https://github.com/rectorphp/rector/pull/4517

See set: https://github.com/rectorphp/rector/blob/master/config/set/doctrine-dbal-30.php


We currently don't have any project with Dbal that we upgrade, so we'll not handle it.

Extending set is welcomed :+1:
