### ISSUE TITLE
"file does not exist" error when running rector-prefixed

### ISSUE THREAD

**Issue by garethellis36** [rectorphp/rector#4636]
# Bug Report

I am experiencing this error when installing rector-prefixed as a composer dependency, or when downloading the phar file from the rector-prefixed github page.

I run `$ php rector.phar init` or `app/Vendor/bin/rector init` and get:

```
Rector 0.8.52

In Filesystem.php line 38:

  Failed to copy "phar://C:/inetpub/<project>/rector.phar/src/Console/Command/../../../templates/rector.php.dist" because file does not exist.init
```

The version installed with composer is `"rector/rector-prefixed": "^0.8.52"`.

I am on Windows 10 and PHP 7.3 I've tried running it in cmd.exe, cygwin, and in vagrant, and get the same error in every case.

**Comment by TomasVotruba** [comment]
Hi, 

thanks for reporting. I recall the path to `rector.php.dist` was changed.

Does it still appear in 0.8.56?

**Comment by garethellis36** [comment]
I don't know because `0.8.56` doesn't appear as a [tag on rector-prefixed](https://github.com/rectorphp/rector-prefixed/tags). I installed it with composer this morning using `composer require --dev` and no version constraints.

**Comment by TomasVotruba** [comment]
I see :/. We need to fix the tagging there.

Thanks for letting me know.

**Comment by garethellis36** [comment]
Any update on this? Anything I can do to help? Happy to contribute, if I can 🙂

**Comment by TomasVotruba** [comment]
This should work on `dev-master`. Could you confirm?

**Comment by garethellis36** [comment]
First of all I get this:

> Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.23. in C:\inetpub\itrans\app\Vendor\rector\rector-prefixed\vendor\composer\platform_check.php on line 24

If I switch to 7.4 just to run Rector, I get this error when trying to do `rector init`:

> Fatal error: Uncaught Error: Class 'Doctrine\Inflector\Inflector' not found in C:\inetpub\itrans\app\Vendor\rector\rector-prefixed\vendor\doctrine\inflector\lib\Doctrine\Inflector\GenericLanguageInflectorFactory.php on line 21


This is when installing `rector/rector-prefixed:dev-master` with composer.

**Comment by TomasVotruba** [comment]
Should by resolved by https://github.com/rectorphp/rector/pull/4559

**Comment by garethellis36** [comment]
Confirmed. Thank you!

**Comment by checcoux** [comment]
Hello, I'm on symfony 3.4 with php 7.3 and `rector/rector-prefixed:dev-master` but when I run `vendor/bin/rector init` I get this:

> File "/vendor/rector/rector-prefixed/src/Console/Command/../../../templates/rector.php.dist" not found i
  n "Rector\Core\Console\Command\InitCommand::execute".

**Comment by samsonasik** [comment]
@checcoux please use dev-main instead of dev-master if you want to use development version.

**Comment by checcoux** [comment]
Yess sorry, I noticed that dev-master isn't longer available so I used dev-main and composer installed the package correctly. But the error happens when I run `vendor/bin/rector init`

**Comment by samsonasik** [comment]
Thank you for verify, re-open it.

**Comment by TomAdam** [comment]
PHP 7.1 here, using the latest tagged version and I am getting the same error.

**Comment by samsonasik** [comment]
should be fixed now in latest rector-prefixed dev-main https://github.com/rectorphp/rector-prefixed/blob/main/templates/rector.php.dist
