### ISSUE TITLE
Autoimport when name is already in use causes BC break

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#4650]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.48 / dev-master              |
| Installed as   | composer dependency                      |

Hi! There is issues with autoimport when that class is in use already and importing that again would make conflict. We faced it with `\DateTimeImmutable` vs `\Safe\DateTimeImmutable`

## Minimal PHP Code Causing Issue

https://getrector.org/demo/5fa0b696-87ba-41a7-b61f-c40d0de315f7#result

## Expected Behaviour

I would expect to not touch this code or import as alias (could be complicated what alias should be used? name of class + Alias postfix?)

**Comment by samsonasik** [comment]
fixed by https://github.com/rectorphp/rector/pull/4785

**Comment by JanMikes** [comment]
Thank you! 👍
