### ISSUE TITLE
Check PHP Version when running Rector agains top 50 github projects

### ISSUE THREAD

**Issue by orklah** [rectorphp/rector#4654]
This is a feature request related to https://github.com/rectorphp/rector/pull/4644.

First, let me applaud you for this cool idea, it gives me really cool ideas of what Rector could do:
- Automated PR in willing projects
- A tool available in https://getrector.org/ where anyone could enter it's publicly available repo and get an email with all the rectors that could be applied in a project (something like "Rector detected changes for those sets: Php72, Php73, Php74...")
- Automated CI checks when adding features in rector, kinda like what Psalm do (it runs Psalm against PHPunit to check if anything broke)

But for that, it would need a crucial feature: parsing composer.json to select the rectors that should be suggested
For example, if a specific project require php 7.2 as the minimum php version, Rector should not suggest typed properties. It could also check for known tools to suggest specific rectors (phpunit, symfony, laravel...)

Thanks!

**Comment by staabm** [comment]
Rector already has a setting regarding which features the codebase support with https://github.com/rectorphp/rector/blob/dade40765a88c4ff86bb5b04b1633e8697b188e2/src/Configuration/Option.php#L37

It does not infer this information from composer.json though

**Comment by TomasVotruba** [comment]
@orklah Thanks for the applaud :hugs: 


We've just added the the `composer.json` version resolver https://github.com/rectorphp/rector/pull/5031

Let me know there in the PR, how can we improve it

**Comment by TomasVotruba** [comment]
I've also repushed https://github.com/rectorphp/rector/pull/4644 to get fresh result with Rector 0.9
