### ISSUE TITLE
Wrong suggestion for array of union types

### ISSUE THREAD

**Issue by orklah** [rectorphp/rector#4655]
This is a bug report related to https://github.com/rectorphp/rector/pull/4644

I noticed a weird suggestion in one of phpdoc's repo:
https://github.com/rectorphp/rector/pull/4644/checks?check_run_id=1418484197#step:7:288
The corresponding code is:
https://github.com/phpDocumentor/TypeResolver/blob/1.x/tests/unit/TypeResolverTest.php#L733

One correct suggestion could be:
```php
-     * @return (string|bool)[][]
+     * @return (string[]|bool[])[]
```
But if we ultimately want something more readable for IDEs, it should be:
```php
-     * @return (string|bool)[][]
+     * @return string[][]|bool[][]
```

**Comment by TomasVotruba** [comment]
We'll need a specific responsible rule and failing fixture for this.

Here is [How to Add Test for Rector Rule](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md)

**Comment by orklah** [comment]
Sorry, I have no idea what rule is responsible here because there was a crash just after and it wasn't displayed.

**Comment by TomasVotruba** [comment]
No problem.

The [link also shows](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md) how to detect the responsible rule.
