### ISSUE TITLE
TypedPropertyRector FQCN property not work

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#4664]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master             |
| Installed as   | try in https://getrector.org/demo/                     |

Current existing saved URL example:

https://getrector.org/demo/19ac6368-a647-43eb-a762-d16abe61dfff

New executed URL example:

https://getrector.org/demo/c9050f8a-4685-4b3d-9d01-813e78122334#result

**Comment by TomasVotruba** [comment]
It's not clear what is expected restult for what input.
Could you add failing test case?

**Comment by samsonasik** [comment]
It seems happen only in the demo website, I tried reproduce with failing but it seems working ok. 

The expected result is when we re-click process button in the demo website, the diff is equal with existing saved url in the typed property navigation.

**Comment by TomasVotruba** [comment]
Demo is probably outdated and does not provide full autoloading features of local code. It's on file after all.

So if tests passes in CI, there is no issue.

**Comment by samsonasik** [comment]
ok 👍
