### ISSUE TITLE
[ClassRenaming] Add support to rename classes in Laravel Blade templates

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4671]
E.g. to remove aliases and replace them with FQN facade classes

**Comment by TomasVotruba** [comment]
Already covered

**Comment by ngmy** [comment]
@TomasVotruba 
I apologize for referring to an older article, but I have a question regarding the following post:

https://getrector.com/blog/laravel-facades-to-constructor-injection-replace-facade-aliases-with-full-classes-in-2-hours#content-blade-templates

Does the application of `RenameClassRector` to Blade templates still work in version 2.3.6?

When I tested it with version 2.3.6, it was applied inside `<?php` tags, but it did not seem to be applied within Blade directives such as `@if`.

Am I missing any configuration, or has the behavior changed in recent versions?
