### ISSUE TITLE
Missing class in Rector prefixed 

### ISSUE THREAD

**Issue by jakzal** [rectorphp/rector#4673]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest (--version crashes)             |
| Installed as   |  prefixed Rector PHAR                      |

## Steps to reproduce the issue

```
composer require --dev rector/rector-prefixed
./vendor/bin/rector
```

## Expected Behaviour

Rector runs without crashing.

## Actual behaviour

```
Fatal error: Uncaught Error: Class 'Rector\Core\Console\Style\SymfonyStyleFactory' not found in /Users/kuba/Projects/toolbox/vendor/rector/rector-prefixed/bin/rector:39
Stack trace:
#0 {main}
  thrown in /Users/kuba/Projects/toolbox/vendor/rector/rector-prefixed/bin/rector on line 39
```

**Comment by samsonasik** [comment]
duplicate with https://github.com/rectorphp/rector/issues/4606#issuecomment-731526772
