### ISSUE TITLE
An hybrid command between "Yes, make the changes" and "Dry-run mode"

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector#4675]
Hello all, hello Tobias,

Rector is definitely my favourite PHP code analysis tool.

Since months now, I'm running Rector twice on my projects : first, in a mode I've called `rector-safe` then the `rector-dry-run` mode.

What is `rector-safe`: I'm running rector with a `rector-safe-config.php` configuration file where I've whitelisted all the rules I know and I'm happy with them.  "Please awesome rector, just do the changes; thanks!". These changes are some rules that will not break my code (like the [MultiDirnameRector](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#multidirnamerector)). 

Some rules are risky and there I wish to validate the change (or make the change myself, manually, depending on the case). My `rector-dry-run` configuration will only contains a list of exclusions (I really don't want these rules like [RenameVariableToMatchMethodCallReturnTypeRector](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#renamevariabletomatchmethodcallreturntyperector)) and I expect from rector to see the others rules.

Indeed, I've whitelisted rules in my first run (`rector-safe`) and I'm exlcuding somes in my `rector-dry-run` mode so  `rector-dry-run` will fire all others rules.

My current process is thus:

1. I run rector --config rector-safe-config.php and wait until all changes have been done in my codebase
2. I run rector --config rector-dry-run-config.php with the `--dry-run` argument and then process changes one by one.

I hope I have been clear enough 😉 

So ... I'm running rector twice; every time...

Do you think an hybrid mode can exists in Rector: a list of whitelisted rules (make the changes), a list of excluded rules (never run them) and a list of dry-run rules (show the result on screen and ask the user if he want to proceed them)?

How are you doing on your side to manage this?  (make the changes / don't proceed / ask before)

Thanks in advance for your advices.

(PS: I don't use `RenameVariableToMatchMethodCallReturnTypeRector` because in one of my project I've an "Appraisal" class that I'm using twice in the same code; one appraisal (survey) is for the trainer who has given the course and one appraisal is filled in by course participants; so I've something like `$participantsAppraisal = new Appraisal($surveyId);` and `$trainerAppraisal = new Appraisal($surveyId);`  on the second line; my variable names should stay).

**Comment by TomasVotruba** [comment]
Hi Cavo,

what you do is actually completely correct. Having 2 setups and runs for different needs is what we do here to. We have 3 Rector runs per directory, to improve performance. In the future we'll add 4th standalone with dead code detection, as it's needed just once in a while and takes a lot of time.

Adding more options to running might confuse Rector users in how to use it and when.

So I'd stick with this approach :) 

Btw, if some rule is not performing well and creating bad code, we should resolve it in the core instead.

Also, it's easy to [exclude the rule in the config](https://github.com/rectorphp/rector/blob/master/docs/how_to_ignore_rule_or_paths.md). That's what I'd do in your case, as the rule is quite young and still looking to cover edge cases.

**Comment by TomasVotruba** [comment]
In non-Rector project the Rector actually does not run in CI-reviews at all. It was slowing us down and annoying contributors with changed code. Rector actually added more work, instead of saving it.

So we switched into automated pull-requests.

It's run once a day and creates a pull-request for changed code:
https://github.com/symplify/symplify/blob/master/.github/workflows/daily_pull_request.yaml

Again, in your case you can have 2 such pull-requests: 

- one save with rule you trust
- one advisory, to inspire and just see what Rector could do

<br>

Feel free to copy the Github Action and tune it to your needs. Hope it serves you well :+1:

**Comment by cavo789** [comment]
Like always: many thanks Tomas!
