### ISSUE TITLE
Make MoveVariableDeclarationNearReferenceRector assign expr configurable

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#4680]
# Feature Request

To make choose is expr only for variable or allow any other expression. ref https://twitter.com/Ocramius/status/1330981123158118403

**Comment by Ocramius** [comment]
Makes sense: I know phpstan does not have this information, but any inferred purity can allow applying this rector in a generalized (and safe) way.

Until purity is 100% ensured (very restrictive conditions), using this rector is generally too risky for all codebases 😞

**Comment by TomasVotruba** [comment]
Indeed. As any other Rector rule, this needs to be tested in the wild. E.g. references etc.
It took a 2-3 months to make this rule from idea to production. At the moment the Rector rule passes on our code base, soon to be expanded to external ones.

Often, these is less edge cases than one would expect. The rule `@doesNotPerformAssersions` in PHPUnit has to work with same expecations, and is very reliable.

Yet the exact cases would be very helpful to improve this rule.

**Comment by TomasVotruba** [comment]
This rule can be used to add pure/impure calls detection
https://github.com/rectorphp/rector/blob/master/rules/phpunit/src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php

**Comment by TomasVotruba** [comment]
Closing as mostly resolved and waits for exact use case from useland.
