### ISSUE TITLE
include the "set" of each rector in rector_rules_overview

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#4690]
# Story

I want to run single rectors like described in https://github.com/rectorphp/rector/blob/master/docs/how_to_run_one_rule_from_command_line.md

therefore I opened the list of all rectors and checked which one I should start with
https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md

I figured https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#changeandiftoearlyreturnrector would be a good start.

as described in https://github.com/rectorphp/rector/blob/master/docs/how_to_run_one_rule_from_command_line.md I need the rector name and also the set in which this rector is contained. but the set is not available from the rules-overview.

# Feature Request

would be great to somehow know, which set contains a single rector on the rules-overview page, so I could easily run it.

**Comment by TomasVotruba** [comment]
The first link is an outdated rather hacking practice, before be moved to PHP config this summer. I had concerns about it's misunderstandings like these, yet gave it a try. 

How to do it right?
Running single rule should be done in `rector.php`, with $services->set().
