### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by simivar** [rectorphp/rector#4704]
Currently, `CHANGELOG.md` is out of date and the last changes it contains are of version 0.8.29 which was released over 1.5 months ago (almost 30 releases). Is there another place where I can tell what changed? Is there an option to update the changelog to reflect the current 0.8.56?

**Comment by TomasVotruba** [comment]
The `CHANGELOG.md` is updated weekly by a bot: https://github.com/rectorphp/rector/pull/4668

Last PR is contains is week old: https://github.com/rectorphp/rector/pull/4666

**Comment by simivar** [comment]
Why is it that I can't find `0.8.56` in the changelog and almost all of them I see are `Unreleased`? Isn't that a bug?

**Comment by TomasVotruba** [comment]
I suppose. The regenerate command only creates new content, but does not update old `Unreleased` tags.

**Comment by samsonasik** [comment]
The changelog command is from `composer changelog` which run `vendor/bin/changelog-linker` command which from symplify. Is is a bug in symplify/changelog-linker ?

**Comment by TomasVotruba** [comment]
> Is is a bug in symplify/changelog-linker ?

Yes, this issue can be moved there :+1:

**Comment by samsonasik** [comment]
This may related to this https://github.com/symplify/symplify/pull/2333 . On tests, the method call:

```php
        $this->changelogFileSystem->addToChangelogOnPlaceholder('## Unreleased - [#1] Added foo', '## Unreleased');
        $this->changelogFileSystem->addToChangelogOnPlaceholder('## Unreleased - [#2] Added bar', '## Unreleased');
```

will result:

```php
## Unreleased

 - [#2] Added bar
 - [#1] Added foo
```

I tried debug the `Symplify\ChangelogLinker\Console\Command\DumpMergesCommand`, and the 2nd value called on : 

```php
$this->changelogFileSystem->addToChangelogOnPlaceholder($content, self::CHANGELOG_PLACEHOLDER_TO_WRITE);
```

is `<!-- changelog-linker -->`. @TomasVotruba is it probably the reason why `## Unreleased` not merged ?

**Comment by samsonasik** [comment]
Should be fixed by https://github.com/symplify/symplify/pull/2660 that handle unmerged "Unreleased" title.

Old tags probably need manual update .

**Comment by powtac** [comment]
https://github.com/rectorphp/rector/blob/master/CHANGELOG.md was not updated since 6th dec 2020 (1 month ago). Although there were several releases according to https://github.com/rectorphp/rector/tags .

**Comment by samsonasik** [comment]
@powtac the changelog generation is scheduled each week ,previous week is not running due fork check issue in github action, ref #5047 and should be handled by #5058
