### ISSUE TITLE
Use more labels for issues

### ISSUE THREAD

**Issue by simivar** [rectorphp/rector#4705]
Personally, I find it difficult right now to navigate through Issues here as their topics could both mean an issue with an existing rule and/or a feature request for a new rule. I would propose to add new labels that would clearly state that issue is:
- a request for a new rule
- a bug in the existing rule/in general
- reproducible bug 

What do you think?

**Comment by TomasVotruba** [comment]
It could help to navigate through issues, but there is currently no one who would maintain these labels.

**Comment by simivar** [comment]
If you want that and need any help I can go through current issues and fill them with proper labels. If not I think this issue can be closed thanks to #4719.

**Comment by TomasVotruba** [comment]
> If you want that and need any help I can go through current issues and fill them with proper labels

That would be very helpful. Thanks!
What access level do you need to be able to do that?

**Comment by simivar** [comment]
From what I read on [this page](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/managing-labels):
> To create, edit, **apply**, or delete a label, you must have **write access** to the repository.

**Comment by TomasVotruba** [comment]
I've just send you the invitation

**Comment by simivar** [comment]
I went through all open issues that currently are here in the repository and added (what I thought) are proper labels.

I created as well some new ones to make it better:
- [dx](https://github.com/rectorphp/rector/issues?q=is%3Aopen+is%3Aissue+label%3Adx) (7 issues)
- [docs](https://github.com/rectorphp/rector/issues?q=is%3Aopen+is%3Aissue+label%3Adocs) (1 issue)
- [feature](https://github.com/rectorphp/rector/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) (70 issues)
- [on-hold](https://github.com/rectorphp/rector/issues?q=is%3Aopen+is%3Aissue+label%3Aon-hold) (1 issue)
- [performance](https://github.com/rectorphp/rector/labels/performance) (2 issues)
- [support](https://github.com/rectorphp/rector/issues?q=is%3Aopen+is%3Aissue+label%3Asupport) (7 issues)

**Comment by TomasVotruba** [comment]
I'll go trought it :) 

Could you narrow it down to 5 top most used and drop the rest? That way we can maintain in the future and work with them effectively without adding too much maintenance
