### ISSUE TITLE
PHPStorm finds duplicates classes coming from rector-prefixed/stubs

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#4738]
I just noticed that PHPStorm was suggesting a stub for `ObjectManager` coming from `rector-prefixed`.
<img width="1074" alt="Screenshot 2020-11-30 at 19 47 04@2x" src="https://user-images.githubusercontent.com/104180/100650840-d63c4980-3344-11eb-9af5-9cd90a4d4ec8.png">

When I opened the directory, I noticed there were lots of files that I don't believe are needed for a release. For example `.github, ci, ecs configs, markdown files`.
<img width="394" alt="Screenshot 2020-11-30 at 19 44 35@2x" src="https://user-images.githubusercontent.com/104180/100650616-7d6cb100-3344-11eb-99e8-d871d0a665f8.png">

I'm using `"rector/rector-prefixed": "^0.8.52"` in my `composer.json`.

Is this going as expected? Or did something go wrong with the automatic split? Because I never saw this before. For example https://github.com/rectorphp/rector-prefixed/tree/7e9ea94ab320763da3bb6ae1aad50e179a803287 did not include all these files and stubs.

Would it be an idea to use [.gitattributes](https://github.com/symfony/security-core/blob/5.x/.gitattributes)?

**Comment by TomasVotruba** [comment]
Stubs are not part of prefixed version anymore:
https://github.com/rectorphp/rector-prefixed

Solved :heavy_check_mark:  :)
