### ISSUE TITLE
[UnusedForeachValueToArrayKeysRector] array_keys expects the first parameter to be of type array

### ISSUE THREAD

**Issue by sebastian84** [rectorphp/rector#4748]
# Bug Report

| Subject            | Details                         |
| :-------------- | :-----------------------|
| Rector version | 0.8.56                          |
| Installed as      | composer dependency |

The UnusedForeachValueToArrayKeysRector changes foreach with unused $value but only $key to array_keys() if the expression is an instance of a class that implements IteratorAggregate. That causes an error because array_keys() expects the first parameter to be of type array.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/d652bd92-49ac-44e2-a286-c915d98bae0c

## Expected Behaviour

The UnusedForeachValueToArrayKeysRector should not use the function array_keys if the expression of a foreach is not of type array.

**Comment by simivar** [comment]
Thank you for the report. It was fixed in #4750, feel free to re-test it now :).

**Comment by TomasVotruba** [comment]
@simivar Thank you! :)

[Tip for closing keywords](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords), so you dn't have to close issues manually in the future.
