### ISSUE TITLE
CodeSample parameters order

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#4756]
# Question
Hi,
after downloading dev-master of rector to my project I am little bit confused with definitions. I have changed all getDefinition methods to getRuleDefinition and also classnames to Symplify\RuleDocGenerator\ValueObject\RuleDefinition / Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample.

CodeSample has first parameter named goodCode and second one is named badCode. But there are still Rules where it seems like old code. For example in class `Rector\Nette\Rector\ClassMethod\TranslateClassMethodToVariadicsRector`:

```
return new RuleDefinition(
            'Change translate() method call 2nd arg to variadic',
            [
                new CodeSample(
                    <<<'CODE_SAMPLE'
use Nette\Localization\ITranslator;

final class SomeClass implements ITranslator
{
    public function translate($message, $count = null)
    {
        return [$message, $count];
    }
}
CODE_SAMPLE
,
                    <<<'CODE_SAMPLE'
use Nette\Localization\ITranslator;

final class SomeClass implements ITranslator
{
    public function translate($message, ... $parameters)
    {
        $count = $parameters[0] ?? null;
        return [$message, $count];
    }
}
CODE_SAMPLE
                ),

            ]);
```

So the question is: What is correct? Should I change all rules and switch parameters in CodeSample?

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting. That's incorrect naming in the `Symplify\RuleDocGenerator\ValueObject\AbstractCodeSample` class. The first one should be bad code.

**Comment by lulco** [comment]
Ok, than I am pretty sure, I saw some Rectors in dev-master with "wrong" order of parameters in CodeSample but now I can't find them...

**Comment by TomasVotruba** [comment]
Only the naming of parameters might be consusing, the samples might be in correct order.

One way or another, I think they will show themselves :)

**Comment by TomasVotruba** [comment]
The `TranslateClassMethodToVariadicsRector` is correct.

If you find any bugs in good/bad snippet order, please send PR with their swap.

<br>

Closing as fixed in @symplify. Thank you @samsonasik

**Comment by lulco** [comment]
Hi,
there is wrong parameters order in other AbstractCodeSample implementations:
- ExtraFileCodeSample
- ComposerJsonAwareCodeSample
- ConfiguredCodeSample

**Comment by lulco** [comment]
Ah, true. That is another package. Sorry, no PC time during weekend. Maybe on monday, but I don’t want to overdue your weekend release, so please fix it yourself.

**Comment by lulco** [comment]
You did it already :) thanks

**Comment by TomasVotruba** [comment]
No problem :)
