### ISSUE TITLE
ChangePhpVersionInPlatformCheckRector creates trouble

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4760]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | master             |
| Installed as   | composer dependency                      |

Rule `ChangePhpVersionInPlatformCheckRector` is creating trouble in the downgrade sets, because it's converting `PHP_VERSION_ID` used to validate if a feature is available or not.

For instance, Nette has [this code](https://github.com/nette/application/blob/master/src/Application/UI/Presenter.php#L1109):

```php
$attrs = PHP_VERSION_ID >= 80000
    ? $rc->getAttributes(Application\Attributes\Persistent::class)
    : null;
```

After running the downgrade rule, it becomes this:

```php
$attrs = PHP_VERSION_ID >= 70200
    ? $rc->getAttributes(Application\Attributes\Persistent::class)
    : null;
```

And then everything explodes, because PHP 7.2 doesn't support `RefectionMethod::getAttributes`

**Comment by leoloso** [comment]
I've commented out adding this rule in the PR to downgrade Rector to 7.1:

https://github.com/rectorphp/rector/pull/4447/commits/c0b2c83b9b734918e221774b0229b5a4f81b2b73

Then, the script finishes without errors

**Comment by leoloso** [comment]
Btw, this rule is also producing other side effects. Check how this code was also transformed, even though it has no relationship to the PHP version:

```diff
-            throw new CacheException('Memcached >= 2.2.0 is required.');
+            throw new CacheException('Memcached >= 7.2 is required.');
```

**Comment by TomasVotruba** [comment]
I see, that's a bug. 

This rule should run only in file with name `platform_check.php` (https://php.watch/articles/composer-platform-check)
