### ISSUE TITLE
Try Rector in getrector.org prints JSON object for results

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4761]
# Bug Report

Is this bug or feature? Checkout how the results are printing the JSON object, instead of the error message:

https://getrector.org/demo/4cee31f5-4db1-44b3-94ea-f3dbf0fb4a61#result

![Screenshot_2020-12-03 Try Rector Online Rector - Automated Way to Instantly Upgrade and Refactor any PHP code](https://user-images.githubusercontent.com/1981996/100969997-07985d80-356f-11eb-88e1-222ce89cfa62.png)

**Comment by TomasVotruba** [comment]
Currently it's a feature, but improvements are welcomed. 

PR should go to the other repository with website: 
https://github.com/rectorphp/getrector.org
