### ISSUE TITLE
[PHP 8.0] Undocumented BC breaks

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4765]
These should be part of PHP 8 set

See https://github.com/rectorphp/rector/pull/4762/commits/82e92c0c0dca26287b4fc43ec2ce9ce98265f5e7

- `private` and `final` cannot be used together on class method
	→ drop `final`, as `private` is stating it clearly for both

- parent cannot be called, if no parent class
	→ remove parent (handled by code quality rule)

- `__setState()` must be `static`
	→ add visibility to it

**Comment by simivar** [comment]
Closing as it was done in #4792, #4794 and #4795.

**Comment by TomasVotruba** [comment]
Thank you :+1:
