### ISSUE TITLE
rector-recipe.dist uses a class that isn't available in the latest stable version

### ISSUE THREAD

**Issue by matthiasnoback** [rectorphp/rector#4773]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.56              |
| Installed as   | composer dependency                      |

It's not really a bug with Rector, but more an issue with the documentation. The issue is that https://github.com/rectorphp/rector/blob/master/docs/rector_recipe.md says I have to copy the recipe dist file, but it refers to the one from the master branch. If I copy this recipe to a project that has the latest stable version, 0.8.56, installed, then it uses a class that is not available: `use Symplify\SymfonyPhpConfig\ValueObjectInliner;`. Maybe it's possible to point to the dist file that reflects the latest stable version?

**Comment by TomasVotruba** [comment]
Rector is in big WIP for last couple of weeks, so that might be related to it :)

0.8.56 has the correct file - https://github.com/rectorphp/rector/blob/0.8.56/rector-recipe.php.dist

Though, it might be better to have something like this to avoid any confusion:

```bash
vendor/bin/rector init-recipe
```

**Comment by matthiasnoback** [comment]
It isn't a big deal, but I think it could indeed improve the DX.
