### ISSUE TITLE
Run tool

### ISSUE THREAD

**Issue by grogy** [RectorPHP/Rector#48]
Hi,

I have trouble with run Rector. After creating rector as project (via #46) then I run

```
rector/bin/rector process /path/to/my-files
```

Iteration from files was correct (I dumped file names) but it did nothing. Where is the problem, maybe it is in rewrited command?

**Comment by TomasVotruba** [comment]
Hey, thanks for reporting.

This feature is actually not ready yet. I'll give it a priority so you can test it on your code.

**Comment by TomasVotruba** [comment]
Fixed!

Could you retry?

**Comment by grogy** [comment]
Thanks, it looks better.

For now I run `rector/bin/rector process www/app/` and I have config

```
rectors:
  - Rector\Rector\Contrib\Nette\InjectPropertyRector
```

Then I get exception   [ReflectionException]   `Function recurse() does not exist`.

My environment is: Docker container, PHP in version 7.1.9. Is any problem in my side?

**Comment by TomasVotruba** [comment]
I got idea... Could you provide minimal failing code? Probably something with `* function recurse()`.

**Comment by TomasVotruba** [comment]
So I could replicate your use case:

![image](https://user-images.githubusercontent.com/924196/30975340-572f928c-a472-11e7-9014-a7998823e9fc.png)



Fix in progress...

**Comment by grogy** [comment]
Great, it works for my now. But sometimes I get some exception how you - `iniFlag()`.

**Comment by TomasVotruba** [comment]
Mmm, intereseting. Could you check 

https://github.com/RectorPHP/Rector/blob/master/packages/NodeTypeResolver/src/TypeContext.php#L122-L126

**Comment by TomasVotruba** [comment]
Closing for now. Feel free to reopen with specific report for the `iniFlag()`.
