### ISSUE TITLE
[Downgrade] Copy traits' methods to class, before changing signatures

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4816]
# Feature Request

The "covariant return type" (#4163), "contravariant argument type" (#4164) and "parameter type widening" (#4754) downgrade rectors modify the signature of the method, if it is different than in an ancestor class or implemented interface:

```diff
class ParentType {}
class ChildType extends ParentType {}

class A
{
    public function covariantReturnTypes(): ParentType
    { /* … */ }
}

class B extends A
{
-    public function covariantReturnTypes(): ChildType
+    /**
+     * @return ChildType
+     */
+    public function covariantReturnTypes(): ParentType
    { /* … */ }
}
```

What happens if the code to modify is inside a trait? For instance:

```php
class ParentType {}
class ChildType extends ParentType {}

class A
{
    public function covariantReturnTypes(): ParentType
    { /* … */ }
}

trait Trait
{
    public function covariantReturnTypes(): ChildType
    { /* … */ }
}

class B extends A
{
    use SomeTrait;
}
```

We might downgrade the code within the trait, like this:

```diff
class ParentType {}
class ChildType extends ParentType {}

class A
{
    public function covariantReturnTypes(): ParentType
    { /* … */ }
}

trait SomeTrait
{
-    public function covariantReturnTypes(): ChildType
+    /**
+     * @return ChildType
+     */
+    public function covariantReturnTypes(): ParentType
    { /* … */ }
}

class B extends A
{
    use SomeTrait;
}
```

But this can fail, because the same trait could be used by another class which has no relationship to the ancestor class or implemented interface, so it doesn't expect the function to be modified:

```php
class Standalone
{
    use SomeTrait;

    function foo():
    {
      $someObjOfChildType = $this->covariantReturnTypes();
      // ...
    }
}
```

A way to solve this problem is to keep the trait unaffected, copy the methods of the trait to the affected class, and then modify these signatures in the class only:

```diff
class ParentType {}
class ChildType extends ParentType {}

class A
{
    public function covariantReturnTypes(): ParentType
    { /* … */ }
}

trait SomeTrait
{
    public function covariantReturnTypes(): ChildType
    { /* … */ }
}

class B extends A
{
    use SomeTrait;

+    /**
+     * @return ChildType
+     */
+    public function covariantReturnTypes(): ParentType
+    { /* … */ }
}

class Standalone
{
    use SomeTrait;

    function foo():
    {
      $someObjOfChildType = $this->covariantReturnTypes();
      // ...
    }
}
```

Now, class `B` has the downgraded signature, and class `Standalone` has not been affected.

If implementing this strategy, we must watch out for copying the right method when referencing multiple traits:

```diff
trait FooTrait
{
    public function covariantReturnTypes(): ChildType
    {
      echo "foo";
      /* … */
    }
}

trait BarTrait
{
    public function covariantReturnTypes(): ChildType
    {
      echo "bar";
      /* … */
    }
}

class B extends A
{
    use FooTrait, BarTrait {
      FooTrait::covariantReturnTypes insteadof BarTrait;
    }

+    /**
+     * @return ChildType
+     */
+    public function covariantReturnTypes(): ParentType
+    {
+      echo "foo";
+      /* … */
+    }
}
```

@TomasVotruba thoughts?

**Comment by TomasVotruba** [comment]
Mix of traits overriding methods and types is very rare to see. Same as before, closing to focus on existing downgrade problems, untill we meet this issue in practise.

**Comment by leoloso** [comment]
As it turns out, we actually need this to downgrade Rector: Symfony Cache uses this method, making the downgrade script currently [throw this error](https://github.com/rectorphp/rector/pull/4447/checks?check_run_id=1537458916):

```
 [ERROR] Could not process                                                      
         "vendor/symfony/cache/Adapter/CouchbaseBucketAdapter.php" file by      
         "Rector\DowngradePhp72\Rector\ClassMethod\DowngradeParameterTypeWidenin
         gRector", due to:                                                      
         "Argument 3 passed to                                                  
         Rector\DowngradePhp72\Rector\ClassMethod\DowngradeParameterTypeWidening
         Rector::removeParamTypeFromMethod() must be an instance of             
         PhpParser\Node\Stmt\ClassMethod, null given, called in                 
         rules/downgrade-php72/src/Rector/ClassMethod/DowngradeParameterTypeWide
         ningRector.php:147".     
```

The reason is that [`CouchbaseBucketAdapter.php` has this signature](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Cache/Adapter/CouchbaseBucketAdapter.php#L185) (without `string`):

```php
protected function doHave($id): bool
{
    //...
}
```

and its original definition with `string`, in its parent class `AbstractAdapter`, is [implemented through trait `AbstractAdapterTrait`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Cache/Traits/AbstractAdapterTrait.php#L65):

```php
abstract protected function doHave(string $id);
```

So @TomasVotruba would you agree with my proposal to copy the trait's method to the class, and then refactor it there? Or you prefer to refactor it on the trait itself, which could well generate bugs?

**Comment by TomasVotruba** [comment]
Damn traits :/. 

I'd go with the less intrusive one:

```php
abstract protected function doHave(string $id);
```

**Comment by leoloso** [comment]
Decided to not implement this downgrade rule yet, because Rector doesn't use `CouchbaseBucketAdapter`, so we can just skip downgrading this class. If the issue happens somewhere else, which is used by Rector, will reopen it then
