### ISSUE TITLE
Invalid modification of PHPDoc comments

### ISSUE THREAD

**Issue by buffcode** [rectorphp/rector#4817]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | [dev-master@ca35301](https://github.com/rectorphp/rector/tree/ca35301)             |
| Installed as   | Online rector                      |

**This might be an upstream issue**

When rector checks the given minimal testcase below, the second route annotation will be modified.
The quotes around the **string** parameter `name` get removed which is wrong, because
1. No rector is modifying it (parser issue?)
2. The first route, though being identical is not touched (inconsistency)
3. The parameter is a string and as such should not be touched at all (`null` vs `"null"` is obviously a difference)

## Minimal PHP Code Causing Issue

https://getrector.org/demo/92c921ea-1bd9-40ea-bccd-c3bc9b4a95c8

## Expected Behaviour

Code should not get modified at all.

**Comment by TomasVotruba** [comment]
Related to #4454

**Comment by buffcode** [comment]
@TomasVotruba Is the close/relation correct? #4454 is a merged PR from end of october.

**Comment by TomasVotruba** [comment]
Miss click on a phone. I've fixed the number now

Thank you for letting me know
