### ISSUE TITLE
BarewordStringRector does not work with code that calls "die()"

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4847]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.56 |
| Installed as   | composer dependency |

## Minimal PHP Code Causing Issue

A.php
```
<?php
class A {
    static function b($c) {}
}
```
test.php
```
<?php
A::b(C);
die('THIS FILE SHOULD NOT BE EXECUTED');
```

rector.php

```
<?php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Php72\Rector\ConstFetch\BarewordStringRector;

return static function (ContainerConfigurator $containerConfigurator): void {
        $parameters = $containerConfigurator->parameters();
	$services   = $containerConfigurator->services();
	$services->set(BarewordStringRector::class);
        $parameters->set(Option::AUTOLOAD_PATHS, ['A.php']);
};
```

https://getrector.org/demo/9beb47c6-ecf1-4fda-bb2f-aa93dfacf9cc#demo_result

## Expected Behaviour

rector should not stop working and no php code should be executed by a static analyser.

## Hints

* This is triggered by https://github.com/rectorphp/rector/blob/master/rules/php72/src/Rector/ConstFetch/BarewordStringRector.php#L80
* Maybe eval would work here since exit in eval'ed code is only respected within the eval'ed code but not in calling code.

**Comment by TomasVotruba** [comment]
Rector 0.7 is not maintained anymore.

Does the same happen with 0.9?

**Comment by powtac** [comment]
> Rector 0.7 is not maintained anymore.
> Does the same happen with 0.9?

I adjusted the example and specified the rector version to latest stable 0.8.56.

**Comment by TomasVotruba** [comment]
Thank you!

The BarewordStringRector must be load the full file, so all the constants are known.
Eval might help, but it would still [execute code](https://www.php.net/manual/en/function.eval.php):

> The eval() language construct is very dangerous because it allows execution of arbitrary PHP code.

This could be solve only with static reflection:
https://github.com/rectorphp/rector/issues/3490

**Comment by TomasVotruba** [comment]
In the meaintime, you can disable the `BarewordStringRector` rule in config.
