### ISSUE TITLE
get_class() inside method crashes PHP 8 ClassOnObjectRector rule

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4852]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.56              |
| Installed as   | composer dependency  |

[`get_class()`](https://www.php.net/manual/function.get-class) inside a method crashes PHP_80 Rector. There are no changes regarding PHP 8 mentioned in the docs. Only that since 7.2.0 explicit parameter null is no longer valid. The first parameter is still optional.

Error messages are like:
```
Notice: Undefined offset: 0 in /vendor/rector/rector/rules/php80/src/Rector/FuncCall/ClassOnObjectRector.php on line 70
Notice: Trying to get property 'value' of non-object in /vendor/rector/rector/rules/php80/src/Rector/FuncCall/ClassOnObjectRector.php on line 70
Fatal error: Uncaught TypeError: Argument 1 passed to PhpParser\PrettyPrinter\Standard::pDereferenceLhs() must implement interface PhpParser\Node, null given, called in /vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 593 and defined in /vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php:1018
```

## Minimal PHP Code Causing Issue

A.php
```
<?php
class A {
    function b() {
        return get_class();
    }
}
```

rector.php
```
<?php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Php80\Rector\FuncCall\ClassOnObjectRector;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $services   = $containerConfigurator->services();

    $parameters->set(Option::PHP_VERSION_FEATURES, '8.0');
    $services->set(Rector\Php80\Rector\FuncCall\ClassOnObjectRector::class);

    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__.'/A.php',
    ]);
};
```

## Expected Behaviour
rector not crashing

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting! This could be easy pick.

We need failing test case in `ClassOnObjectRectorTest` - [here is how to add it](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md).

**Comment by samsonasik** [comment]
I think `get_class()` without parameter can be changed to `self::class` as it will return same result, ref https://3v4l.org/3O2MU
