### ISSUE TITLE
don't exists class Rector\Core\ValueObject\PhpVersion

### ISSUE THREAD

**Issue by 4n70w4** [rectorphp/rector#4854]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.56              |
| Installed as   | composer dependency                      |

I copy `Full Config Configuration` from https://github.com/rectorphp/rector/blob/master/README.md#full-config-configuration

to my `rector.php`. But `Rector\Core\ValueObject\PhpVersion` don't exists. `ValueObject` contains only:

```
|-- Application
|   |-- ParsedStmtsAndTokens.php
|   `-- RectorError.php
|-- MethodName.php
|-- PhpVersionFeature.php
|-- ProjectType.php
|-- RenamedNamespace.php
|-- Reporting
|   `-- FileDiff.php
|-- SprintfStringAndArgs.php
`-- StaticNonPhpFileSuffixes.php
```

**Comment by TomasVotruba** [comment]
Hi,

thanks for new issue report!

The README is related to `dev-master`, where the value object already exists.
You can either use older version README https://github.com/rectorphp/rector/releases/tag/0.8.56,
or update to `dev-master`.

Next stable Rector 0.9 should be released in ~week.

**Comment by samsonasik** [comment]
I am closing it as answered.
