### ISSUE TITLE
@Route annotations broken, no matter which set is used 

### ISSUE THREAD

**Issue by jlefebvre1997** [rectorphp/rector#4855]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master              |
| Installed as   | docker                      |

When using rector with any set, @Route annotations break (quotes are removed, line breaks added...)

## Minimal PHP Code Causing Issue

Didn't manage to reproduce the issue at getrector.org/demo... Here is the result after `rector process` 
![image](https://user-images.githubusercontent.com/22916167/101897630-21f3bc00-3bab-11eb-9d5e-fe782c6acf9d.png)

## Expected Behaviour

@Route annotations shouldn't be changed as they were fine before `rector process`

**Comment by TomasVotruba** [comment]
Hi,
thanks for reporting :+1: 

This is known issue cause by: https://github.com/rectorphp/rector/issues/4334
