### ISSUE TITLE
[EarlyReturn] Single return of && && to ealry returns

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4869]
- new rule for `EarlyReturn` set
- name, e.g. `ReturnBinaryAndToEarlyReturnRector` 
 
## Diff 

```diff
 class SomeClass
 {
     public function accept($something, $somethignElse)
     {
-        return $something && $somethignElse;
+ 		 if (! $something) {
+            return false;
+        }
+        return $somethignElse;
     }
 }
```

**Comment by samsonasik** [comment]
@TomasVotruba the `return $somethingelse;` may be false positive (need to be converted to truthy check), for example https://3v4l.org/ZEWn9 vs https://3v4l.org/56Zq2 . The possible way is to cast last return to `(bool)`:

```php
class SomeClass
{
    public function accept($something, $somethingelse)
    {
        if (! $something) {
            return false;    
        }
        
        return (bool) $somethingelse;
    }
}
```

**Comment by TomasVotruba** [comment]
> The possible way is to cast last return to (bool):

Yes, that's correct. The non-bool variables should be casted like this.
