### ISSUE TITLE
wrong replacement

### ISSUE THREAD

**Issue by calvera** [rectorphp/rector#4871]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Installed as   | docker                      |

Wrong annotation fix

## Minimal PHP Code Causing Issue

https://getrector.org/demo/430b8076-1fc7-4f69-8e54-cd256326ca66#demo_result

## Expected Behaviour

Skip...

**Comment by TomasVotruba** [comment]
Related to superior issue: https://github.com/rectorphp/rector/issues/4334
