### ISSUE TITLE
Wrong parameter removal

### ISSUE THREAD

**Issue by calvera** [rectorphp/rector#4872]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Installed as   | docker                   |

See example

## Minimal PHP Code Causing Issue

https://getrector.org/demo/ffa79f68-01fb-4f5c-a236-670249234720#demo_result
## Expected Behaviour

do not remove parameter $io

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting. That should not happen.

We [need a failing test case](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md) to be added into `RemoveUnusedParameterRectorTest`

**Comment by samsonasik** [comment]
@calvera that's because the parameter class `SymfonyStyle` is not loaded. It may because it not defined in use statement or not defined before, see https://getrector.org/demo/0fab175f-1fde-4fa9-9555-d58a42b157e9#demo_result that working ok.

I am closing it.

**Comment by calvera** [comment]
not true!

https://getrector.org/demo/0d894e5c-6968-4f70-bdbd-ef73673b82df#demo_result

**Comment by TomasVotruba** [comment]
@calvera Still, we need a failing test case as I linked
