### ISSUE TITLE
Upgrade a symfony 2.8 project

### ISSUE THREAD

**Issue by bbouabou** [rectorphp/rector#4873]
# Question
Hello,

I'm trying to upgrade a symfony 2.8 project to a least the LTS and if it's not too difficult maybe to version 5.2.

I tried to use the last version of rector-prefixed but it was not working, as suggested by @arnaud-fr [here ](https://github.com/rectorphp/rector/issues/4736#issuecomment-740438611) I instaled the version 0.8.52 but it's still not working, now I have this error : 

![error](https://user-images.githubusercontent.com/6256196/102021789-bb28fb00-3d82-11eb-9724-2cf0e3b94885.png)

If I clear cache I only have the first error, all the next errors are similar.

This is my rector.php file : 

```
use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // here we can define, what sets of rules will be applied
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::SETS, [
        SetList::SYMFONY_28, 
        // SetList::SYMFONY_30
    ]);

    // // set paths to directories with your code
    $parameters->set(Option::PATHS, [
        __DIR__ . '/app',
        __DIR__ . '/src',
    ]);
    $parameters->set(Option::AUTOLOAD_PATHS, [
        // autoload specific file
        __DIR__ . '/app/autoload.php',
    ]);
    // register single rule
    $services = $containerConfigurator->services();
    $services->set(TypedPropertyRector::class);
};
```
The project was running in php 7.1 in production  but I'm actully running it in a php 7.2 container, I would like to also update to the lts version of php.

Am I missing something ?

Thanks for your help.

**Comment by TomasVotruba** [comment]
Hi,

thanks for detailed screenshots including configuration.
From a quick look, you're trying to process Symfony files. Those Symfony files probably use some magic, and should be rather part of vendor (as in Symfony 3, 4...).

Personally I'd exclude them and run Rector only on your own custom code. Somethign like:

```php
  // // set paths to directories with your code
    $parameters->set(Option::PATHS, [
        __DIR__ . '/app/Controller',
        __DIR__ . '/src',
    ]);

    $parameters->set(Option::EXCLUDE_PATHS, [
	 	// here put files you want to exclude from paths above
        __DIR__ . '/app/Controller/SomeSymfony.php',
    ]);
 ```

**Comment by bbouabou** [comment]
Hi,

Thank you for your reply.

I actually tried to do that and I didn’t have errors  but when I ran the process, it just says OK in green, I tried with all symfony version in my rector.php and it’s the same ...
The only way to get a diff was with `setlist::CODE_QUALITY `

 Is it a normal behavior ?

Thanks.

**Comment by TomasVotruba** [comment]
It usually runs some checks, but it depends how you run Rector on which code.
