### ISSUE TITLE
[DX] "generate" command should generate files in specific set

### ISSUE THREAD

**Issue by simivar** [rectorphp/rector#4875]
# Feature Request

When you run `generate` command it only asks a question about `composer.json` and generates all files in the default set:
```
 * rules/utils/src/Rector/MethodCall/RenameMethodCallRector.php
 * rules/utils/tests/Rector/MethodCall/RenameMethodCallRector/Fixture/fixture.php.inc
 * rules/utils/tests/Rector/MethodCall/RenameMethodCallRector/RenameMethodCallRectorTest.php
```
 
What I would like as a person working on a new Rectors is to get more questions about, for example, "bundle" for which the Rector should be created as well the name. As well we could check if the "bundle" (here: symfony5) exists and if not add it to `composer.json` by default without asking question.

# Expected result

```
* rules/symfony5/src/Rector/New_/PropertyAccessorCreationBooleanToFlagsRector.php
* rules/symfony5/tests/Rector/New_/PropertyAccessorCreationBooleanToFlagsRector.php
* rules/symfony5/tests/Rector/New_/Fixture/fixture.php
```

#

**Comment by TomasVotruba** [comment]
If you're using Rector as dependency, then it's correct.

If you're contributing our repository, that would be a bug. But that's weird, because it worked for last 450 rules correctly.

In the latter case, please provide GitHub Actions job, that shows this.

**Comment by TomasVotruba** [comment]
I see. That's because the "package" has to be changed to "Symfony5" first.

I'll move the category up, so it's harder to miss.

**Comment by simivar** [comment]
What do you think about moving away from `rector-recipe.php` configuration file to just asking questions after running `generate` command? If you work on multiple rules from different "packages" it would be easier.

**Comment by TomasVotruba** [comment]
Sounde doable. How would it include code samples that are used for RuleDefinition and test fixture?

To avoid mixing 2 behavior, there should be option to invoke Q&A behavior:

```bash
generate -i
generate --interactive
```

**Comment by simivar** [comment]
Sure. Could you point me to the place where the current `generate` method is located?

**Comment by TomasVotruba** [comment]
We respect simple command naming convention, so "generate + comand" will find the class:

- https://github.com/rectorphp/rector/blob/master/packages/rector-generator/src/Command/GenerateCommand.php

> I would generate then some dummy CodeSamples that would have to be changed by hand, unfortunately. I don't see any other solution.

:+1: If it's documented here https://github.com/rectorphp/rector/blob/master/docs/rector_recipe.md, it should be ok

**Comment by TomasVotruba** [comment]
Hi, I'm thinking about way how to make Rector simpler and less ambiguous. We've got a feedback about its complexity and try to drop everything that is not neccessary, so 95 % of users can learn it faster and with less know-how.

I've just realized we have this feature that I never used and I wanted to ask about your experience with it. How is usage of this feature?
