### ISSUE TITLE
[Downgrade Script] Can make Option::PATHS and Option::SKIP more intelligent?

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4884]
# Feature Request

The `ChangePhpVersionInPlatformCheckRector` rule modifies file `vendor/composer/platform_check.php`. In the downgrade script, this behavior is currently not working, because when downgrading Rector's source code, [the `/vendor` folder is excluded](https://github.com/rectorphp/rector/blob/b7246b88786533496d5ee5eaa1635b5c72de6061/ci%2Fdowngrade%2Frector-downgrade-rector-to-php74.php#L14):

```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::SKIP, DowngradeRectorConfig::RECTOR_EXCLUDE_PATHS);

    // ...
};

final class DowngradeRectorConfig
{
  public const RECTOR_EXCLUDE_PATHS = [
      __DIR__ . '/../../vendor/*',
      // ...
  ];
}
```

If `vendor/` were not excluded, the downgrade would take much longer.

## Proposal

Would it be possible to have `Option::PATHS` be able to override some excluded value from `Option::SKIP`, and vice versa, based on how specific their values are?

For instance, this configuration could exclude folder `vendor/`, but still allow `vendor/composer/platform_check.php` since it is more specific:

```php
$parameters->set(Option::PATHS, ['src/*', 'vendor/composer/platform_check.php']);
$parameters->set(Option::SKIP, ['vendor/*']);
```

**Comment by leoloso** [comment]
Their mutual overriding must be able span multiple levels.

Then, in a single Rector call, we can downgrade Rector and the dependencies. We first compute `Option::PATHS` via Composer and pass it to Rector via CLI:

```bash
bin/rector process src/ vendor/symfony/cache/ vendor/symfony/console/ vendor/symfony/finder/ ...
```

And we configure `rector-downgrade.php` with these folders to exclude:

```php
$parameters->set(Option::SKIP, [
    // Baseline: Exclude all dependencies
    __DIR__ . '/vendor/*',
    
    // Exclude files not used by Rector which produce some error
    __DIR__ . '/vendor/symfony/cache/DoctrineProvider.php',
    __DIR__ . '/vendor/symfony/cache/Messenger/EarlyExpirationHandler.php',
    // ...
]);
```

Then:

- `vendor/` is excluded
- but `vendor/symfony/cache/`,  `vendor/symfony/console/`,  `vendor/symfony/finder/`, etc are included
- but `vendor/symfony/cache/DoctrineProvider.php`, `vendor/symfony/cache/Messenger/EarlyExpirationHandler.php`, etc are exculded

**Comment by TomasVotruba** [comment]
Hi, we're using a skipper component here for handling `Option::SKIP`: https://tomasvotruba.com/blog/2020/12/10/new-in-symplify-9-skipper-skipping-files-and-rules-made-simple/

So the right repository to report this is @symplify:
https://github.com/symplify/symplify
