### ISSUE TITLE
FluentChainMethodCallToNormalMethodCallRector breaks code

### ISSUE THREAD

**Issue by 4n70w4** [rectorphp/rector#4890]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.56              |
| Installed as   | composer dependency                      |

```patch
    ---------- begin diff ----------
--- Original
+++ New
@@ -52,8 +52,8 @@
                 ]
             );
         });
-
-        $models->chunk(50)->each(function ($models) {
+        $models->chunk(50);
+        $models->each(function ($models): void {
             static::insert($models->all());
         });
    ----------- end diff -----------

Applied rules:

 * Rector\Defluent\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector
 * Rector\TypeDeclaration\Rector\Closure\AddClosureReturnTypeRector
```

Rule breaks code because `$models->chunk(50);` returns new object, but rule ignores it.

https://github.com/laravel/framework/blob/3aa700cc795803f09f47da43a6d1e7d27c7fd30a/src/Illuminate/Support/Collection.php#L1058

## Minimal PHP Code Causing Issue

```php
        $models->chunk(50)->each(function ($models) {
            static::insert($models->all());
        });
```

## Expected Behaviour

Don't breaks code =)

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting the issue.

We'll need a failing test fixture in: `FluentChainMethodCallToNormalMethodCallRectorTest`
[Here is how to add it](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md)

**Comment by TomasVotruba** [comment]
Closing for missing test case.

**Comment by 4n70w4** [comment]
LOL ))))
