### ISSUE TITLE
Provide a link to the rector implementation in the documentation

### ISSUE THREAD

**Issue by funivan** [rectorphp/rector#4891]
# Feature Request
For example it would be cool to jump into the Rector implementation directly from the documentation

```
ServiceLocatorToDIRector
Turns $this->getRepository() in Symfony Controller to constructor injection and private property access.
class: [Rector\Architecture\Rector\MethodCall\ServiceLocatorToDIRector](link...to...the...php..class)
```

**Comment by TomasVotruba** [comment]
We're using external package, symplify/rule-doc-generator from @symplify 
The feature should go to: https://github.com/symplify/symplify
