### ISSUE TITLE
checkout on windows errors with 'filename too long'

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#4894]
checking the current rector revision 51f5a42 I get

```
  HEAD is now at 51f5a4219 [Downgrade] Add ".0" after downgrading the numeric literal separator on floats (#4889)
  error: unable to create file rules/nette-kdyby/tests/Rector/ClassMethod/ReplaceMagicEventPropertySubscriberWithEven
  tClassSubscriberRector/ReplaceMagicEventPropertySubscriberWithEventClassSubscriberRectorTest.php: Filename too long
  error: unable to create file rules/nette/tests/Rector/MethodCall/GetConfigWithDefaultsArgumentToArrayMergeInCompile
  rExtensionRector/GetConfigWithDefaultsArgumentToArrayMergeInCompilerExtensionRectorTest.php: Filename too long
  error: unable to create file rules/solid/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector
  /Fixture/skip_class_that_implements_single_interface_but_defines_own_public_methods.php.inc: Filename too long
  error: unable to create file rules/solid/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector
  /Fixture/skip_class_that_implements_single_interface_but_uses_trait_with_additional_methods.php.inc: Filename too long
```

see details in https://github.com/rectorphp/rector/issues/4691#issuecomment-745242271

**Comment by TomasVotruba** [comment]
Could you come up with PR with shorter names that will make Windows happy? :)

**Comment by clxmstaab** [comment]
windows max path length is arround 260 chars:
https://www.google.com/search?q=windows+max+path+length

maybe it would make sense to create a phpstan rule regarding too long file names?
I guess a sensible limit would be something arround 200, since we need roughly 60 chars to put rector into github desktop default checkout path of /c/Users/mstaab/Documents/GitHub/

wdyt?

**Comment by TomasVotruba** [comment]
> maybe it would make sense to create a phpstan rule regarding too long file names?

You're reading my thoughts :) please include it with the fix, so we're sure.

**Comment by clxmstaab** [comment]
in which folder/repo do you want such rule?

**Comment by samsonasik** [comment]
It seems already fixed in latest master. I am closing it.

**Comment by TomasVotruba** [comment]
Resolved in https://github.com/rectorphp/rector/pull/4999

**Comment by TomasVotruba** [comment]
(Miss click :))
