### ISSUE TITLE
Upgrade Symfony 5.2 with PHP 7.2

### ISSUE THREAD

**Issue by wazum** [rectorphp/rector#4903]
# Question

Sorry, I don't get how I make this work. 
I want to use rector to upgrade a Symfony 5.1 project to 5.2.
The latest tag does not include the Symfony 5.2 set, when I use master I can't use it with PHP 7.2 …

tia

**Comment by TomasVotruba** [comment]
Hi,

in the future we'll have per-PHP version releases. @leoloso is now working even on PHP 7.1 code https://github.com/rectorphp/rector/pull/4447

Untill then, apply the same way the old Symfony 2.8 to 3.4 needs to upgrade PHP in specific order:
https://tomasvotruba.com/blog/2019/02/28/how-to-upgrade-symfony-2-8-to-3-4/#upgrade-symfony-and-php

In your case, first upgrade to PHP 7.3, then upgrade to Symfony 5.2 with newer Rector.
