### ISSUE TITLE
Release Schedule 

### ISSUE THREAD

**Issue by HDVinnie** [rectorphp/rector#4911]
# Question

Just curious as to what the release schedule is? Last release was over a month ago and there has been 216 commits to master since then.

Thanks for the great project.

**Comment by TomasVotruba** [comment]
Hi, there no specific release schedule. We were waiting for PHP 8, Symfony 5.2 and Symplify 9 to be released and tested.

Now we need testing of next release, that should happen this week.
If you can use `dev-master` and give feedback on what is broken, that might help to speed it up.

**Comment by HDVinnie** [comment]
> Hi, there no specific release schedule. We were waiting for PHP 8, Symfony 5.2 and Symplify 9 to be released and tested.
> 
> Now we need testing of next release Rector 0.9, that should happen this week.
> If you can use `dev-master` and give feedback on what is broken, that might help to speed it up.

100% will get to testing. Thanks!

**Comment by TomasVotruba** [comment]
Thanks for asking. I'm happy the next version is needed :)

I've made a special issue for testing:
https://github.com/rectorphp/rector/issues/4913

I also posted a tweet with ask for help:
https://twitter.com/rectorphp/status/1339591326292045827
RT would help too
