### ISSUE TITLE
[CodingStyle] Add UnSpreadOperatorRector

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#4916]
Spready operators are hard to read - is it array of arrays of just an array?
Often missused as arrays, just for runtime type analysis.

Goal is to remove spread operator where not needed, e.g. like this:

![image](https://user-images.githubusercontent.com/924196/102692878-c498e400-4216-11eb-8c9c-5e6f5d1fa36d.png)

- replace `(... $items)` with `(array $items)`
- handle only method calls on non-`/vendor` classes (local)

**Comment by samsonasik** [comment]
The result seems different? ref https://3v4l.org/M08m4

```php
function test(array ...$array)
{
    var_dump($array[0]);
}

function test2(array $array)
{
    var_dump($array[0]);
}

function test3(...$array)
{
    var_dump($array[0]);
}

test(['a']);
test2(['a']);
test3(['a']);
```

Got:

```bash
array(1) {
  [0]=>
  string(1) "a"
}

string(1) "a"

array(1) {
  [0]=>
  string(1) "a"
}
```

**Comment by TomasVotruba** [comment]
The argument passing has `...` too:

https://3v4l.org/UKd5m

This migration should move from `test3()` to `test2()`

**Comment by CoeusCC** [comment]
I wish I had seen this when it was first being proposed. I feel like there's a good use case for spread operators to be used in lieu of generics:

```diff
- public function __construct(DefinitionInterface ...$definitions)
+ public function __construct(array $definitions = [])
```

Plus on the other side of the equation when I'm creating a new object I'm using the inverse of the pattern:

```php
new DefinitionCollection(
    ...array_filter(array_map(
        [$this, 'createDefinition'],
        array_keys((array)$libraryObject),
        (array)$libraryObject
    ))
);
```

That said, is there an easy way to import a SetList _except_ for certain rules, or is the pattern just to copy the SetList to a custom SetList and customize per project?
