### ISSUE TITLE
Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector

### ISSUE THREAD

**Issue by MartkCz** [rectorphp/rector#4918]
# Bug Report

Output:
```
    ---------- begin diff ----------
--- Original
+++ New
@@ -8,9 +8,6 @@

        use SmartObject;

-       final public function __construct() {
-       }
-
    ----------- end diff -----------

```

But code `final public function` is not dead code in abstract class

**Comment by samsonasik** [comment]
please provide reproducible code at https://getrector.org/demo

**Comment by MartkCz** [comment]
https://getrector.org/demo/7df10589-4703-4fe8-a1b1-b6df1e402907#demo_result
