### ISSUE TITLE
Creating class from $variable

### ISSUE THREAD

**Issue by jkuchar** [rectorphp/rector#4937]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master             |
| Installed as   | composer dependency  |

This code produces rector error (see example)
https://gist.github.com/jkuchar/b8f54c1e909cb50f25c9374fa405e655

It seems to me that this happens whenever I create class from `class-string<WhateverClass>`.

**Comment by TomasVotruba** [comment]
We'll need at least demo link:
https://getrector.org/demo

**Comment by TomasVotruba** [comment]
Closing for lack of demo code. Possibly solved by another fix in last 2 days

**Comment by jkuchar** [comment]
Yep, these dynamic references has been already resolved.

**Comment by TomasVotruba** [comment]
:+1:
