### ISSUE TITLE
AddArrayDefaultToArrayPropertyRector and shape types

### ISSUE THREAD

**Issue by jkuchar** [rectorphp/rector#4952]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@24e1758            
| Installed as   | composer dependency                      |

When there is a property with shape array, AddArrayDefaultToArrayPropertyRector crashes with following error:

```
PHP Fatal error:  Uncaught Rector\Core\Exception\NotImplementedException: Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper::mapToPHPStanType for Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode in /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/PhpDoc/PhpDocTypeMapper.php:39
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/dddda7bb-3c8c-4f96-abe9-d1e9bf381ee9#demo_result

**Comment by TomasVotruba** [comment]
Closing as duplicated of https://github.com/rectorphp/rector/issues/4958,
we'll continue there
