### ISSUE TITLE
SecurityContextInterface deprecation Rector

### ISSUE THREAD

**Issue by berezuev** [rectorphp/rector#4961]
# Feature Request

Hi.

First of all, thanks for developing such useful tool.

I found a case of Symfony 2.6 deprecation that haven't been covered by rector rule sets.

Symfony\Component\Security\Core\SecurityContextInterface has been deprecated since version 2.6 and removed in 3.0 because of ISP violation.
They recommend using `Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface` and `Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface` instead.

Follow [Symfony blog](https://symfony.com/blog/new-in-symfony-2-6-security-component-improvements) for more info.

I could try to write the rule. Hope, you can tell me where to start right after I init new rule (I'm interested in examples of working with services and appending/removing class parameters).
Or, maybe I should write separated rules, use existed ones?

## Diff 

```diff
 <?php
 
-use Symfony\Component\Security\Core\SecurityContextInterface;
+use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
+use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
 
 class Example
 {
     /**
-     * @var SecurityContextInterface
+     * @var TokenStorageInterface
      */
-    private $securityContext;
+    private $tokenStorage;
+
+    /**
+     * @var AuthorizationCheckerInterface
+     */
+    private $authorizationChecker;
 
     public function __construct(
-        SecurityContextInterface $securityContext
+        TokenStorageInterface $tokenStorage,
+        AuthorizationCheckerInterface $authorizationChecker
     ) {
-        $this->securityContext = $securityContext;
+        $this->tokenStorage = $tokenStorage;
+        $this->authorizationChecker = $authorizationChecker;
 
-        $this->securityContext->setToken(/*token*/); //just an example
+        $this->tokenStorage->setToken(/*token*/); //just an example
     }
 
     final public function verifyAccess()
     {
-        if (!$this->securityContext->isGranted('Someprivilege')) {
+        if (!$this->authorizationChecker->isGranted('Someprivilege')) {
             die('no access');
         }
     }
 
     final public function getUserName()
     {
-        $token = $this->securityContext->getToken();
+        $token = $this->tokenStorage->getToken();
 
         return $token->getUsername();
     }

```

**Comment by TomasVotruba** [comment]
Hi,

welcome to your first Rector rule.

Here is a documentation on how to create it:
https://github.com/rectorphp/rector/blob/master/docs/create_own_rule.md

The right location for rule from Symfony 2.6 is here:
https://github.com/rectorphp/rector/tree/master/rules/symfony2/src/Rector

The most effective way is review on real pull-request with basic structure and failing test case. I can help you there with feedback :)

**Comment by TomasVotruba** [comment]
Closing as accepted and waiting for PR :+1:
