### ISSUE TITLE
Incorrect behavior of ChangeSwitchToMatchRector – converts to match even when there are :void methods

### ISSUE THREAD

**Issue by jkuchar** [rectorphp/rector#4965]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master           |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/b87a0d8f-0fc6-4f6c-b188-7668c133f333

```php
<?php

declare(strict_types=1);

final class DemoFile
{

    public function getState(): string {}
    public function doSth(): void {}
    
    public function save(): void
	{
		switch ($this->getState()) {

			case 'inserted':
			        $this->doSth();
				break;
                
		}
	}
}
```

### Responsible rules

* ChangeSwitchToMatchRector

## Expected Behavior

Probably not covert switch to match at all? Or is there even way how to use `match() {}` with methods returning `:void`? Current behavior results into invalid code.

phpstan says:
```
Result of method doSth() (void) is used.
```

**Comment by TomasVotruba** [comment]
The match arm return value (e.g .`doSth()`) can be `void`:

https://3v4l.org/Kv1EE

---

The argument is `null` for functions with `void`: https://3v4l.org/RAXcb

This one is not related to the void, but rather to missing deafult case.

**Comment by jkuchar** [comment]
I have tested this with enumerated values (where phpstan knows what values can be input into `match()` ) and I still get an error from phpstan, that I have used a void value (even I do not use return value of `match()` itself)

E.g.


```php
<?php

declare(strict_types=1);

final class DemoFile
{

    public function getState(): bool {}
    public function doSth(): void {}
    
    public function save(): void
	{
		switch ($this->getState()) {

			case true:
			        $this->doSth();
				break;

         case false:
			        $this->doSthElse();
				break;

                
		}
	}
}
```



All cases are covered in this scenario. However I still get an error that I use value of doSth(). Maybe this is more phpstan's error in rule? (and also phpstorm EA plugin's)

**Comment by TomasVotruba** [comment]
PHPStan is stricter than PHP in this case. PHP allows void and retypes as null.

Question is, if the behavior is the same before and after, or should match Rector skip this one. What do you think?

**Comment by jkuchar** [comment]
It looks like this is more phpstan issue. As if value of match is not used, then it should not care if there is an void function inside of match. Hmm? So rector can convert it and it it is still the same behaviur.

**Comment by jkuchar** [comment]
reported https://github.com/phpstan/phpstan/issues/4292

**Comment by jkuchar** [comment]
After Ondrej's reaction I think that this one should be also converted to `match()`. As Ondra is also considering current behaviour as bug.

**Comment by TomasVotruba** [comment]
I'm getting lost in here. We'll need a failing test case

**Comment by jkuchar** [comment]
I think this is not a bug as it is supported by PHP and phpstan considers current behaviour as wrong.

**Comment by TomasVotruba** [comment]
Thanks for closing and investigating 👍
