### ISSUE TITLE
[mysql-to-mysqli] Not renaming mysql_query to mysqli_query on legacy PHP5 code

### ISSUE THREAD

**Issue by genesiscz** [rectorphp/rector#4977]
https://github.com/rectorphp/rector/blob/9433616c634e3e2513112dd441b8163dc12f6767/config/set/mysql-to-mysqli.php#L39

Here it says it should swap the parameters and then rename the function. mysql_query, mysql_real_escape_string are two that are not being renamed.

On another note, second parameter in most of these functions are optional, which is connection handler. Rector doesn't correctly work in this situation. I understand that this is because of rector not being able to find the $connection, but shouldn't this be stated somewhere in the execution/documentation of the set?

**Comment by TomasVotruba** [comment]
Hi, 

we'll need some code, how it should be changed and where is the bug.

**Comment by genesiscz** [comment]
Oh I used it a bit wrong. However I found another "buggy" behavior about this.
## Minimal PHP Code Causing Issue

See https://getrector.org/demo/ed152941-9482-4f5c-90f5-7d93fb729d28

```php
<?php

final class DemoFile
{
    public function run()
    {
		$connection = mysql_connect("host", "user", "name"); // this line gets deleted by rector
                mysql_query("SELECT * FROM tbl");
    }
}
```

### Responsible rules
* Set DEAD_CODE
* RemoveUnusedVariableAssignRector


-----

Another one:

This works
https://getrector.org/demo/bca2ad02-f596-4fb8-ac3c-a0f323803cb2

This doesn't
https://getrector.org/demo/2d2118b8-8d78-4f77-81cf-9e1a7a3576e4

The only difference between these to is variable name ($conn vs $connection).

**Comment by TomasVotruba** [comment]
Hi, legacy code doesn't sleep on Christmass ;) this year is lockdown with spring temperatures here. Feels like spring after war :D 

<br>


We'll need a test fixture to be added here:
https://github.com/rectorphp/rector/blob/51dd6b899afe5b1d4d519466a16151b61033508d/rules/mysql-to-mysqli/tests/SetTest.php#L23

You can inspire in other files:
https://github.com/rectorphp/rector/tree/master/rules/mysql-to-mysqli/tests/Fixture

**Comment by genesiscz** [comment]
Guess I got it to the point it should be - failing tests but others passing.
