### ISSUE TITLE
Rector still changes PHPDoc annotation although there is no rule for that

### ISSUE THREAD

**Issue by Guuzen** [rectorphp/rector#5018]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.0              |
| Installed as   | composer dependency                           |

Same type of issue as described in #4620 
Tested migration to php 8 and faced issue that route annotations formatting was changed.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/90d8b757-e337-4f50-8b39-17d91d7a0248

## Expected Behaviour

Annotation for routes should not change because there is no explicit rule about it.

**Comment by TomasVotruba** [comment]
Thanks for reporting. 

Until #4334 is finished, the only way around is to use inlined form:
https://getrector.org/demo/db0282f7-a0e4-4f9a-b181-a9dbe463478e

Closing as sub-issue of #4334
