### ISSUE TITLE
Don't use Slevomat dev-master

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#5021]
I'm using Doctrine's Coding Standards and they're using `^6.3.9` of Slevomat. Rector 0.9 uses dev-master, which removed `SlevomatCodingStandard.Classes.UnusedPrivateElements`. So Rector 0.9 breaks my phpcs/phpcbf. Can we use a stable version of Slevomat instead?

**Comment by TomasVotruba** [comment]
Sure, go for it!
