### ISSUE TITLE
Fatal error redeclare class: class_exists check triggers re-including project file via composer based autoloading

### ISSUE THREAD

**Issue by ktomk** [rectorphp/rector#5024]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.9.1 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer rector/rector-prefixed  (rector/rector fatals, confirm of #4559 fixed to prefix (?!))               |

## Minimal PHP Code Causing Issue

I could not isolate the problem. What is causing the issue is the following line in a method docblock:

~~~
 * @param \DateTime $time1
~~~

## Expected Behaviour + More Information

`class_exists()` check on the parameter type should reveal that the PHP global DateTime class is loaded.

However the leading backslash `\` is taken into the class_exists() check and the whole suffixed to the files `namespace` declaration
making the class_exists() check report it does not exists *and* triggers the auto-loader which then tries to load the class (but does backslash namespace normalization) and therefore re-includes a file leading to a fatal error as that class in the namespace already exists.

The error message:

> Fatal error:  Cannot declare class Name\Space\DateTime, because the name is already in use in ...

Excerpt from stack-trace w/ Xdebug:
~~~
    6.5453   80157776  41. Rector\NodeTypeResolver\ClassExistenceStaticHelper::doesClassLikeExist($classLike = 'Name\\Space\\\\DateTime') /home
    6.5453   80157776  42. class_exists($classname = 'Name\\Space\\\\DateTime') /home/user/.config/composer/vendor/rector/rector-prefixed/packag
    6.5453   80157864  43. spl_autoload_call($class_name = 'Name\\Space\\\\DateTime') /home/user/.config/composer/vendor/rector/rector-prefixed/
    6.5453   80157952  44. Composer\Autoload\ClassLoader->loadClass($class = 'Name\\Space\\\\DateTime') ...
~~~

`class_exists()` call that triggers `spl_autoload()`: https://github.com/rectorphp/rector/blob/master/packages/node-type-resolver/src/ClassExistenceStaticHelper.php#L11

([full output](https://gist.github.com/ktomk/bf1b0fbd9b4c430efdf88deb19562aa1))

## Initial Guesswork

Me assumes right now it's an issue on the backslash to slash conversion from class-name to file-name. Operating on a Linux system here and you can have as many slashes in sequence in a path as you like, here there is no difference whether there is one or two consecutive, they always work as a directory separator and hence the file is found on disk and re-included triggering the fatal error.

This kind of normalization does not apply for `class_exists()` ( https://3v4l.org/rhWfu ).

**Comment by TomasVotruba** [comment]
Hi, 

thanks for reporting a bug and detailed investigation.

I have a rough idea where this might be fixed, but we'll need to reproduce it in Rector code base so we know it's fixed. Otherwise we might spend weeks of pinging back and forth with random commits.

The ideal way is isolated mimimal PHP code in demo: https://getrector.org/demo,
the less ideal is reproducible repository on Github with failing Github Action.

**Comment by ktomk** [comment]
Yes, sure. I'm currently preparing this, it but I have this in a full repo so far which is a bit bulky. Hope I can update this report soon.

**Comment by ktomk** [comment]
I could pin-point it to the `SetList::PHPUNIT_60` set that is provoking the fatal.

So far can offer already the less ideal reproduction per Github repo: https://github.com/ktomk/rector-report/runs/1618601166?check_suite_focus=true#step:6:10 - this is the currrent bare-minimum I could compress it to.

As auto-loading is involved, I would need help to turn this into a https://getrector.org/demo , https://getrector.org/demo/72288433-f228-4fc5-afe9-4c8fdd7b88cd was my start there, but not sure how to make two files there etc.

**Comment by ktomk** [comment]
Small update with a stracktrace: https://github.com/ktomk/rector-report/runs/1618657972?check_suite_focus=true#step:7:1

For local reproduction PHP 7.4 and checkout on master of ktomk/rector-report.

It should be possible to spilt the set to further pin-point this down, if I'm able I'll update.

**Comment by ktomk** [comment]
I could pin-point it further to a single rector:

* `\Rector\Renaming\Rector\FileWithoutNamespace\PseudoNamespaceToNamespaceRector`

([40. in stack-trace](https://github.com/ktomk/rector-report/runs/1618918304?check_suite_focus=true#step:7:49))

What I do not fully grasp is why backslash prefixed `@param` type annotations aren't put into the global namespace directly as especially on the level of comment type annotations they are less ambibuous.

The stack-trace shows that this is about parsing the `@param` type annoatation for the `test` method.

In code `\Rector\TypeDeclaration\PHPStan\Type\ObjectTypeSpecifier::matchSameNamespacedObjectType` is doing the faulty concatenation:

~~~
$namespacedObject = $namespaceName . '\\' . $objectType->getClassName();
~~~

So a not well understood "fix" of mine would be to do a prefix check here.

Or better as the method is not documented I would do an assertion:

```
assert(0 !== strncmp($objectType->getClassName(), '\\', 1));
```

No idea thought if rector is making use of assertions (would at least allow to test for undefined behaviour already with a chance to trigger the issue in builds already w/o the need of autoloading).

The assertion alone wouldn't fix it though. Looks to me that culprit is the string concatenation, it misses proper domain logic on how to add a class-name to the namespace (to not trigger a fatal error through class_exists() checks).

In the reported case, this would be a correct concatenation:

~~~
// resolve class-name to name-space
$className = $objectType->getClassName();
if (0 === strncmp($className, '\\', 1)) {
    $namespacedObject = $className;
} else {
    $namespacedObject = $namespaceName . '\\' . $className;
}
~~~

Affects public `\Rector\TypeDeclaration\PHPStan\Type\ObjectTypeSpecifier::narrowToFullyQualifiedOrAliasedObjectType` behaviour. Three direct call points are visible to me, two docblock related
on first glance.

**Comment by TomasVotruba** [comment]
Wow, that's great. You've just prepared a patch :) 

Could you add test case to `PseudoNamespaceToNamespaceRectorTest` and include the fix as well?

**Comment by ktomk** [comment]
Thanks for the feedback, I'm not so fluent with Rector so thanks for the confirmation it's a good spot for the fix.

Let me see if I can add a regression test. And also if the current behaviour is unspecified in tests I may add another test for the current happy path.

**Comment by ktomk** [comment]
o_O, looks like that `PseudoNamespaceToNamespace` relies on the concatenation of the file namespace with the @param etc. notations ... the "correct" ones are skipped (by ::shouldSkip).

So the fatal error is only triggered if there is auto-loading and the file-namespace creates such a clash via file-path normalization rules on the file-system.

This could also explain why this has not been reported earlier.

In my case the fatal-error could also be prevented by normalizing the class-name similar to the path-name rules on the file-system: merge consecutive backslashes into one. A fix then could look like:

~~~
$namespacedObject = $namespaceName . '\\' . ltrim($objectType->getClassName(), '\\');
~~~

Also I have the problem to actually test if auto-loading fires up. Maybe I can register an auto-loader in the test via spl_register_autoloader() and then do the assertion that only correct class-names (or expected ones with a white-list) are given.

Or do you know something about checking auto-loading in `AbstractRectorTestCase`? @TomasVotruba

**Comment by TomasVotruba** [comment]
I'm a bit lost. Could you add a test case where this error appears? That would help

**Comment by ktomk** [comment]
Yes, sure, pushed it already, but I have more the problem that in the test-suite I can not really test for the auto-loading that is provoking the fatal error which is the real issue as it brings rector down while processing. So currently still the de-facto test is
in ktomk/rector-report, still I can not straight-forward port the case into the phpunit test-suite of rector.

So looking first now to get the fatal-error out. We'll find something appropriate I'm sure, it's merely that this is never as straight forward as me thinks in the first place.

I gave the ltrim variant a run, with it the checks are all green (with the first proposal they went red at multiple places): https://github.com/rectorphp/rector/pull/5026/checks

Boot-times in tests are similar slow as in the cli btw. :)

**Comment by ktomk** [comment]
Okay, for the rector-report repo I can confirm the fix with ltrim. Makes total sense as the concatenation is identified as the culprit but the issue is the double-backslash, not the "wrong" namespaced object.

Testing against the larger repo is not possible as I need this as rector-prefixed (clashes w/ S.Bergm./Differ and Rector Service definitions). Can I build prefix locally? @TomasVotruba

**Comment by TomasVotruba** [comment]
Could you link me to PR? Just so we're clear what code you talk about :)

> Can I build prefix locally? @TomasVotruba

There is `build-rector-scoped.sh` script. We run it to build the scoped version.
The bug should appear unrelated to scoped version though.
