### ISSUE TITLE
Conflicting `phpstan/phpdoc-parser` in Rector 0.9 / ECS 9.0

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector#5037]
# Bug Report

I wanted to upgrade project to PHP8 along with Rector 0.9 (from `dev-master#01e6554600ee599f164be41d3d6d5570458a97ef`) and unfortunately I still (related: #4905) have conflicts between Rector and ECS (with its requirement `slevomat/coding-standard` actually).

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.2 |
| Installed as   | composer dependency |

```
$ composer update --with-all-dependencies              
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to ">=5.2.1"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symplify/easy-coding-standard ^9.0 -> satisfiable by symplify/easy-coding-standard[9.0.0, ..., 9.0.22].
    - rector/rector[0.9.0, ..., 0.9.2] require phpstan/phpdoc-parser ^0.4.10 -> satisfiable by phpstan/phpdoc-parser[0.4.10].
    - You can only install one version of a package, so only one of these can be installed: phpstan/phpdoc-parser[0.4.5, ..., 0.4.10].
    - Conclusion: install phpstan/phpdoc-parser 0.4.9 (conflict analysis result)
    - Root composer.json requires rector/rector ^0.9 -> satisfiable by rector/rector[0.9.0, 0.9.1, 0.9.2].
```

It's because:
- [Rector requires `phpstan/phpdoc-parser: ^0.4.10`](https://packagist.org/packages/rector/rector#0.9.2) (bumped in 61e1ceaf)
- [`slevomat/coding-standard` requires `phpstan/phpdoc-parser: 0.4.5 - 0.4.9`](https://packagist.org/packages/slevomat/coding-standard#6.4.1)

## Minimal PHP Code Causing Issue

```
{    
    "type": "project",    
    "license": "proprietary",    
    "require": {    
        "rector/rector": "^0.9",    
        "symplify/easy-coding-standard": "^9.0"    
    },    
    "config": {    
        "optimize-autoloader": true,    
        "preferred-install": {    
            "*": "dist"    
        },    
        "sort-packages": true    
    }    
}  
```

`composer install` result:

```
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symplify/easy-coding-standard ^9.0 -> satisfiable by symplify/easy-coding-standard[9.0.0, ..., 9.0.22].
    - rector/rector[0.9.0, ..., 0.9.2] require phpstan/phpdoc-parser ^0.4.10 -> satisfiable by phpstan/phpdoc-parser[0.4.10].
    - Conclusion: don't install phpstan/phpdoc-parser 0.4.10 (conflict analysis result)
    - Root composer.json requires rector/rector ^0.9 -> satisfiable by rector/rector[0.9.0, 0.9.1, 0.9.2].
```

## Expected Behaviour

As [pointed](https://github.com/rectorphp/rector/issues/4905#issuecomment-746322340) in #4905 there should be possibility to install Rector 0.9 along with ECS 9.0.

**Comment by TomasVotruba** [comment]
Try 9.0.22

**Comment by Wirone** [comment]
@TomasVotruba it does not work with 9.0.22 too, as you can see in the output (`satisfiable by symplify/easy-coding-standard[9.0.0, ..., 9.0.22]`). Rector `^0.9` and ECS `^9.0` cannot be installed at the same time. Check minimal setup provided in the description.

Currently I try to force Rector `dev-master` version before 61e1cea but somehow Composer still resolves it wrong: `rector/rector dev-master requires phpstan/phpdoc-parser ^0.4.10` :thinking:

**Comment by TomasVotruba** [comment]
That's weird. I use the 9.0.22 here https://github.com/rectorphp/phpdoc-parser-printer/pull/2/files

Have used the patch explicitly? I see only 9.0
Composer needs help sometimes to use the exact patch.

**Comment by TomasVotruba** [comment]
For the phpdoc-parser in Rector, send PR please

**Comment by Wirone** [comment]
@TomasVotruba in the linked PR you use `rector/rector-prefixed` which has far less dependencies, also there is explicit  `"phpstan/phpdoc-parser": "^0.4.9"` constraint so there is no conflict. Rector 0.9 requires `^0.4.10` and it cannot be resolved.

I don't know if I can provide valid PR because I don't know why `^0.4.10` was forced. As far as I see `0.4.10` was only about CI automation, so it looks like going with `^0.4.9` would work (this is first version with support for PHP8). What do you think?
