### ISSUE TITLE
Unknown Error in AddArrayReturnDocTypeRector

### ISSUE THREAD

**Issue by brucealdridge** [rectorphp/rector#5042]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.2 / demo              |
| Installed as   | prefixed Rector / demo                           |

AddArrayReturnDocTypeRector errors with an unhelpful error
~~~json
{ "meta": { "version": "dev-master@8175188", "config": "/project/rector.php" }, "totals": { "changed_files": 0, "removed_and_added_files_count": 0, "removed_node_count": 0, "errors": 1 }, "errors": [ { "message": "", "file": "rector_analyzed_file.php", "line": 0 } ] }
~~~
or via cli
~~~
[ERROR] Could not process "filename.php" file, due to:
         "".
~~~

## Minimal PHP Code Causing Issue

https://getrector.org/demo/8ddce49d-3cd8-4f27-a99e-75fb6d8d58db

## Workaround

Manually add `/** @return array */` to docblock

**Comment by TomasVotruba** [comment]
Thanks for reporting!

Fixed in https://github.com/rectorphp/rector/pull/5043
