### ISSUE TITLE
Incorrect behavior of `CountOnNullRector`

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#5048]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/199a23f7-7cad-4f6d-8ffe-154c54287894

```php
<?php

final class DemoFile
{
    public function run($startPath)
    {
        $splitPath = function ($path) {
            $result = [];

            foreach (explode('/', trim($path, '/')) as $segment) {
                if ('..' === $segment) {
                    array_pop($result);
                } elseif ('.' !== $segment && '' !== $segment) {
                    $result[] = $segment;
                }
            }

            return $result;
        };
        
        $startPathArr = $splitPath($startPath);
        
        // Determine how deep the start path is relative to the common path (ie, "web/bundles" = 2 levels)
        if (1 === \count($startPathArr) && '' === $startPathArr[0]) {
            $depth = 0;
        } else {
            $depth = \count($startPathArr) - $index;
        }
    }
}
```

extracted from https://github.com/symfony/symfony/blob/e905b8d8d81d046f003e5d6b51180bcd77dee756/src/Symfony/Component/Filesystem/Filesystem.php#L443-L479

identified in https://github.com/rectorphp/rector/pull/4644

### Responsible rules

* `CountOnNullRector`

## Expected Behavior

I did not expect rector adding `is_countable` because the type is known to be a `array` at this point, which is always countable

**Comment by staabm** [comment]
wow: 'create a issue' from the demo worked perfectly <3

**Comment by samsonasik** [comment]
array return type declararion is needed to know about the array type: https://getrector.org/demo/f8f1b8a6-df7f-4fde-b328-c69743ebc95f

I am closing it.

**Comment by TomasVotruba** [comment]
As @samsonasik stated. 

This could be an improvement in PHPStan :) then it would work as expected.

**Comment by staabm** [comment]
https://github.com/phpstan/phpstan/issues/3115
