### ISSUE TITLE
A tag is badly named vO.7.43

### ISSUE THREAD

**Issue by lyrixx** [rectorphp/rector#5049]
Hello Tomas

I noticed a tag is badly named, it's a O (letter) instead of a 0 (the number)

https://github.com/rectorphp/rector/tree/vO.7.43

It's not a big deal at all, but you may want to fix it.

Anyway, thanks for this projet and what you do 💛

**Comment by TomasVotruba** [comment]
Hi @lyrixx ,

good point, it's rather confusing. Done :) Thank you :+1: 


> Anyway, thanks for this projet and what you do yellow_heart

Glad to help! 

If you find my open-source free time work useful, you can support me on https://github.com/sponsors/TomasVotruba
