### ISSUE TITLE
[Nette 3.0] RemoveParentCallWithoutParentRector has no effect

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#5051]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.2 (but I think all versions are affected)              |
| Installed as   | prefixed Rector and also composer dependency                          |

In nette-30.php there is 
```
$services->set(\Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector::class);
```
which should remove parent::__construct() from all children of `\Nette\ComponentModel\Component` e.g. children of `\Nette\Application\UI\Control`. This rule has no effect because in time when Rector is executed, there is Nette 2.4 installed and in this version __construct() still exists.

## Expected Behaviour
Rector should remove parent::__construct() call in children, but with different approach.

**Comment by TomasVotruba** [comment]
> This rule has no effect because in time when Rector is executed, there is Nette 2.4 installed and in this version __construct() still exists.

Such behavior is correct then.

**Comment by lulco** [comment]
OK, I am little bit confused now :) What is the correct way to run rector to upgrade Nette application from 2.4 to 3.0?

If I first change composer packages versions, run composer update and then run rector process with nette_30 set, I get an error because of incompatibility of classes in my project - missing return types, parameter types etc.

So, I found it correct to run rector first on Nette 2.4, then change composer packages versions, run composer update and then run this one rule (RemoveParentCallWithoutParentRector) on Nette 3.0.

**Comment by TomasVotruba** [comment]
> So, I found it correct to run rector first on Nette 2.4, then change composer packages versions, run composer update and then run this one rule (RemoveParentCallWithoutParentRector) on Nette 3.0.

That's right :+1: 

Due to fatal errors of type conflict it's not possible to just upgade to Nette 3.0.
It's best practise to do this on any package upgrade, as new return type = fatal error.
