### ISSUE TITLE
Full upgrade of codebase including changes in composer.json

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#5054]
# Feature Request
If this is already possible, stop reading here and please tell me how to do it :)

What if Rector can update codebase of application and also change composer.json (ideally with executing composer update)?

I am upgrading Nette applications from 2.4 to 3.0 (but this would be usable for all upgrades and also downgrades), I run Rector and then I have to change my composer.json manually and run composer update manually.

I was thinking about some non-php rule which will change composer.json, configuration should be like this:

```
$services->set(ComposerRector::class)
    ->call('configure', [[
        'change_package_version' => [  // change version of package which is already in composer.json
            'nette/application' => '^3.0',
            'nette/forms' => '^3.0',
            ...
        ],
        'add_package' => [    // add new package or change version of existing package
            'nette/mail' => '^3.1',
            ...
        ],

         // maybe some other changes like remove packages and change packages
    ]]);
```

All sets could include this rule.

For example. Update php to 8.0 should change composer.json this way:
```diff
-"php": "^7.1",
+"php": "^8.0",
```

If there would be some interest for this feature, I can try to implement it. The only issue I found for now is how to find composer.json file while executing rector process command

**Comment by lulco** [comment]
Maybe it could be different command - not the `process`, it will just change composer.json and run composer update. Config should be similar to process command as mentioned above

**Comment by TomasVotruba** [comment]
Hi, no, we don't have such feature yet :) 

> If there would be some interest for this feature, I can try to implement it.

I'm in as people have to do this manually anyway. Please, go for it :+1: 

> how to find composer.json file while executing rector process command

Typical location `getcwd . '/composer.json'` is good enough. We use it to [determine PHP version of the project already](https://github.com/rectorphp/rector/blob/630c3d324ee6798050b710b1a2994095c7aeb0c7/src/Php/PhpVersionProvider.php#L49-L55).

**Comment by lulco** [comment]
> Maybe it could be different command - not the `process`, it will just change composer.json and run composer update. Config should be similar to process command as mentioned above

Hm, if it will be different command, it probably can't be part of set...

**Comment by lulco** [comment]
I've added [implementation](https://github.com/rectorphp/rector/pull/5074) and showcase for usage in [Nette30 set](https://github.com/lulco/rector/pull/1)
