### ISSUE TITLE
[fixtures] require "skip_" prefix on skipped files

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5080]
Based on `skip-` standardization of non-changing fixtures

## Basic Rules

- if fixture should not be changes, does not have `----` in it, it should start with `skip-`
- if the fixture is changed, has`-----`, it cannot start with `skip-`

This is manual case by case work.

<br>

There was 190 cases in the start, 1/3 of the work has been done in: https://github.com/rectorphp/rector/pull/5079, check there for inspiration how it should be handled

To discovery invalid cases, uncomment following from `.github/workflows/code_analysis.yaml`: 

```yaml
                    # make sure skipped files have "skip_" prefix
#                    -
#                        name: Validate Fixtures skip file prefix
#                        run: vendor/bin/easy-testing validate-fixture-skip-naming rules tests
```

**Comment by TomasVotruba** [comment]
Could you check this one as next? It's mostly test fixture file renaming

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
closing as implemented.
