### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivatePropertyRector

### ISSUE THREAD

**Issue by brucealdridge** [rectorphp/rector#5088]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/5357d885-2a33-4f2e-bd6c-8a546e96b78c

```php
<?php

final class A
{
    private B $b;
    private C $c;
    
    public function __construct(B $b) 
    {
        $this->b = $b;
        $this->c = new C($b);
    }

    public function c()
    {
        $c->run();
    }
}
```

### Responsible rules

* `RemoveUnusedPrivatePropertyRector`

## Expected Behavior

private var $b should be removed from the class, as well as the set call, but the method signature should not change as $b is used elsewhere.

~~~php
final class A
{
    private C $c;
    
    public function __construct(B $b) 
    {
        $this->c = new C($b);
    }

    public function c()
    {
        $c->run();
    }
}
~~~

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. Could you provide exact expected code?

**Comment by brucealdridge** [comment]
@TomasVotruba updated issue with code.
Issue is the constructor is changed, removing $b when it is still referenced elsewhere in the method.

**Comment by TomasVotruba** [comment]
Thanks :+1: 

This particular line change is correct. The unused behavior is the same while unused property is removed:

```diff
-$this->c = new C($b);
+new C($b);
```

But I get the `public function __construct(B $b) ` should remain
