### ISSUE TITLE
PHAR release

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector#5093]
# Feature Request

Is it possible to configure https://github.com/box-project/box and release a **single** PHAR file?
 
It would be great to just `phive install rector` :)

**Comment by TomasVotruba** [comment]
We actually moved from phar to editable, scoped and dowgnraded releases, see: https://getrector.org/blog/2020/12/28/rector-09-released#debuggable-rector-prefixed

If you want, you can pack Rector yourself. It it works well, we can promote it as official PHAR release.

**Comment by szepeviktor** [comment]
It takes 1 minute.

```
git clone https://github.com/rectorphp/rector-prefixed.git
phive install humbug/box --force-accept-unsigned
tools/box compile
    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 3.11.1@83567c4 2021-01-02 09:53:51 UTC

 // Loading without a configuration file.

🔨  Building the PHAR "/home/viktor/src/RandomOpenSource/rector/bin/rector.phar"

? No compactor to register
? Adding main file: /home/viktor/src/RandomOpenSource/rector/bin/rector
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? Yes
? Exclude dev files? Yes
? Adding files
    > 3322 file(s)
? Generating new stub
  - Using shebang line: #!/usr/bin/env php
  - Using banner:
    > Generated by Humbug Box 3.11.1@83567c4.
    >
    > @link https://github.com/humbug/box
? Dumping the Composer autoloader
? Removing the Composer dump artefacts
? No compression
? Setting file permissions to 0755
* Done.

No recommendation found.
No warning found.

 // PHAR: 3362 files (46.25MB)
 // You can inspect the generated PHAR with the "info" command.

 // Memory usage: 87.38MB (peak: 88.29MB), time: 7secs
```

What is the next step?

**Comment by TomasVotruba** [comment]
I have no idea. Depends what you want to do :)

**Comment by szepeviktor** [comment]
I'd like to `phive install rector`
Should I open a `szepeviktor/rector-phar` repo?

**Comment by szepeviktor** [comment]
@TomasVotruba Very good news 🚀 
https://github.com/szepeviktor/rector-phar/releases
The only one step remaining is GPG signing it...

**Comment by MacDada** [comment]
> https://getrector.org/blog/2020/12/28/rector-09-released#debuggable-rector-prefixed

https://web.archive.org/web/20230202215412/https://getrector.com/blog/2020/12/28/rector-09-released#debuggable-rector-prefixed
