### ISSUE TITLE
FixClassCaseSensitivityNameRector will cause a fatal error

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/rector#5102]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.5             |
| Installed as   | composer dependency                           |

## Minimal PHP Code Causing Issue

When I have a file has the same name as a function/constant, FixClassCaseSensitivityNameRector will cause a fatal error:
```
Fatal error: Cannot redeclare Pest\Faker\faker() (previously declared in /Users/zing/data/code/github/pest-faker-test/vendor/pestphp/pest-plugin-faker/src/Faker.php:11) in /Users/zing/data/code/github/pest-faker-test/vendor/pestphp/pest-plugin-faker/src/faker.php on line 11
```

composer.json
```json
{
    "name": "zing/pest-faker-test",
    "require-dev": {
        "rector/rector": "^0.9.5",
        "pestphp/pest-plugin-faker": "^1.0"
    }
}
```

rector.php
```php
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Name\FixClassCaseSensitivityNameRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(FixClassCaseSensitivityNameRector::class);
};
```

test.php
```php
<?php

use function Pest\Faker\faker;

faker();
```

Run with: `vendor/bin/rector process test.php`

## Expected Behaviour

`vendor/bin/rector process test.php` should be success.

**Comment by samsonasik** [comment]
duplicate with https://github.com/rectorphp/rector/issues/3383
