### ISSUE TITLE
Option::AUTOLOAD_PATHS has no effect

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#5104]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  v0.9.5             |
| Installed as   |  prefixed Rector                           |

If I add `Option::AUTOLOAD_PATHS` to `$parameters`, it will not load files in these paths.

I did some debugging here:
AdditionalAutoloader loads these paths correctly, they are sent to method `autoloadDirectories()` and also they are stored in `\sys_get_temp_dir() . '/_rector_robot_loader'` directory, but they are not used because of some reason. I tried to add `$robotLoader->refresh();` to the end of autoloadDirectories() method but it didn't help me.

## Minimal PHP Code Causing Issue
```
$parameters->set(Option::AUTOLOAD_PATHS, 'dir-which-is-not-already-loaded');
```
## Expected Behaviour
Classes will be loaded

**Comment by TomasVotruba** [comment]
The reproducible repository is needed for this one

**Comment by lulco** [comment]
@TomasVotruba here it is: https://github.com/lulco/rector-nette-api

**Comment by TomasVotruba** [comment]
There are 2 repositories, it should be just one, as Rector is working as a dependency. Anything else can  crash for incompatible deps

**Comment by lulco** [comment]
Yes, they are two folders to show that this option is not working.

If everything is loaded as project dependency than it works, but not thanks to autoload_path option -it can be omitted. It is just loaded thanks to composer autoloader

**Comment by TomasVotruba** [comment]
It's like loading Nette project in one directory with own composer, but actually having Nette dependency in another. There will be conflicts and failures.

Closing as composer constraint.

**Comment by lulco** [comment]
Conflicts? That's why you have prefixed rector or not?

I have 100+ apps to upgrade to Nette 3.0, I don't want to install rector to all of them. I just want to install it once and use the same config for all of them (and I want to do it without docker :) I know I am not only one, because there were some issues on github, but I can't find them now :D)

So, I just want to run:
```
vendor/bin/rector process /var/www/my-app/app --autoload-file /var/www/my-app/app/bootstrap.php
```

This used to work before there was feature of finding composer.json via `getcwd() . '/composer.json'`. After it I have to run rector in reverse way - from my-app:

```
/var/www/rector/vendor/bin/rector process ./app --autoload-file ./app/bootstrap.php
```

And here is the problem, that not all rectors are loaded. My package `efabrica/rector-tomaj-nette-api` is installed in /var/www/rector/ as composer dependency with prefixed-rector.

So I need at least one thing to be fixed / added:
- Option::AUTOLOAD_PATHS (this should be fixed anyway because it is really bug)
- add command option or parameter for setting composer.json path

**Comment by TomasVotruba** [comment]
Prefixed versions resolves conflicts on single-package level. Other packages can break.

Rector now only supports composer dependency approach. We don't support other cases.
Contribution to allow your use case is welcomed :)

**Comment by lulco** [comment]
FYI: my setup seems to work with option `--working-dir`:
```
vendor/bin/rector process /var/www/my-app/app --working-dir /var/www/my-app --autoload-file /var/www/my-app/app/bootstrap.php
```

**Comment by TomasVotruba** [comment]
This might be useful in Docker docs for future users.

**Comment by lulco** [comment]
I don't know, maybe :) I don't use Docker too, but maybe my setup is very close to it. Not sure
