### ISSUE TITLE
Rector cannot be used to upgrade PHPUnit 5.x project running on PHP 7.3?

### ISSUE THREAD

**Issue by sanmai** [rectorphp/rector#5154]
```
phpunit/phpunit       5.7.27  requires  sebastian/diff ^1.4.3
rector/rector[v0.2.0, ..., v0.5.8] requires sebastian/diff ^3.0
```

Therefore one cannot install PHPUnit 5.x and Rector of any recent version together on PHP 7.3. But that's not all: running Docker version of Rector will naturally trigger autoload of installed libraries, including above-mentioned `sebastian/diff`, resulting in the following error:
```
 [ERROR] Invalid service "differ": method                                       
         "SebastianBergmann\Diff\Differ::__construct()" has no argument named   
         "$outputBuilder". Check your service definition.                       
```

**Comment by TomasVotruba** [comment]
Hi,
for version conflicts, there is prefixed Rector: https://github.com/rectorphp/rector-prefixed

**Comment by sanmai** [comment]
Fair enough. Let me try it:
```
composer require rector/rector-prefixed
```

I wish this was more clear in the README.md. Currently it suggests using Rector Prefixed, but going over that link show a list of files. No README, no instructions or explanations.

**Comment by TomasVotruba** [comment]
It's right in the install section: https://github.com/rectorphp/rector#install

The README was there, ups. I'll fix it, thanks for reporting

**Comment by sanmai** [comment]
Yup, it's there, but the README thing... Thank you too!
