### ISSUE TITLE
PrivatizeLocalClassConstantRector change public ERROR_MESSAGE constant to private in php 8

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#5159]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master              |
| Installed as   | composer dependency / prefixed Rector                           |

In symplify, I tried run in php 8 : 

vendor/bin/rector process --ansi packages/phpstan-rules/src/Rules --dry-run

```diff
-    public const ERROR_MESSAGE = '"%s" regex need to use string named capture group instead of numeric';
+    private const ERROR_MESSAGE = '"%s" regex need to use string named capture group instead of numeric';

     /**
      * @var NodeFinder
    ----------- end diff -----------


Applied rules:

 * Rector\Privatization\Rector\ClassConst\PrivatizeLocalClassConstantRector
```

It somehow change public method to private as well.

## Expected Behaviour

Should keep.

**Comment by TomasVotruba** [comment]
This is expected, as provided source doesn't contain tests, where it's used:

```bash
vendor/bin/rector process --ansi packages/phpstan-rules/src/Rules packages/phpstan-rules/tests/Rules --dry-run

**Comment by samsonasik** [comment]
ok 👍
