### ISSUE TITLE
ValueObjectInliner::inline (or something else) changed code in generated Container and causes TypeError

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#5171]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@713915d)              |
| Installed as   | git pull                           |

ValueObjectInliner (or something else) somehow changed the code and from string ^3.0 it created object Version('^3.0')

Fatal error: Uncaught TypeError: Argument 2 passed to Rector\Composer\ValueObject\ComposerModifier\ChangePackageVersion::__construct() must be of the type string, object given, called in /tmp/_rector/ContainerUtOpXnQ/getComposerProcessorService.php on line 21 and defined in /rector/rules/composer/src/ValueObject/ComposerModifier/ChangePackageVersion.php:31 

## Minimal PHP Code Causing Issue

https://getrector.org/demo/3ec88662-8f02-4f26-8d36-3ec2eb64f4fe

```php
$services->set(ComposerModifier::class)
        ->call('configure', [
            ValueObjectInliner::inline([
                new ChangePackageVersion('nette/nette', '^3.0'),
        ]),
    ]);
```
## Expected Behaviour

Version will be used as string not as Version object

**Comment by lulco** [comment]
For me there are 3 possible solutions:
1) Fix ValueObjectInliner (if it is its fault), but if some programs depends on this behavior it will be probably BC break and honestly I have no idea how it works
2) Change second parameter of ChangePackageVersion from string to new Version('^3.0') which is not very user friendly, but it will work and probably it will be the "path of least resistance"
```
$services->set(ComposerModifier::class)
        ->call('configure', [
            ValueObjectInliner::inline([
                new ChangePackageVersion('nette/nette', new Version('^3.0')),
        ]),
    ]);
```
3) Change __construct implementation of ChangePackageVersion to:
```
    /**
     * @var string
     */
    private $packageName;

    /**
     * @var string <---- changed type from Version to string
     */
    private $targetVersion;

    /**
     * @param string $packageName name of package to be changed (vendor/package)
     * @param string $targetVersion target package version (1.2.3, ^1.2, ~1.2.3 etc.)
     */
    public function __construct(string $packageName, string $targetVersion)
    {
        $this->packageName = $packageName;
        new Version($targetVersion);   // <---- do not assign object, use it only for validation
        $this->targetVersion = $targetVersion;
    }
```

@TomasVotruba which of these solution would you prefer?

**Comment by TomasVotruba** [comment]
First, we'll need a test case for this use case.

**Comment by lulco** [comment]
well I was trying to create some, but not sure how to create this
```php
$services->set(ComposerModifier::class)
        ->call('configure', [
            ValueObjectInliner::inline([
                new ChangePackageVersion('nette/nette', '^3.0'),
        ]),
    ]);
```
in tests because I got error:

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator".
```

**Comment by TomasVotruba** [comment]
That's a good direction.

The next step is using `provideConfigFileInfo()` method, e.g. like this:

https://github.com/rectorphp/rector/blob/713915d1b2bb5c0cf0d93903535cc445dc3984d9/rules/mysql-to-mysqli/tests/SetTest.php#L26-L29

In the config, there should be minimal config that would containt the content your provided.

It easier to nagive for me over real PR, rather then guessing the weak spot.

**Comment by lulco** [comment]
@TomasVotruba I added failing test case: https://github.com/rectorphp/rector/pull/5175 It throws the same error now
