### ISSUE TITLE
Consider installing PHP intl extension on docker image

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#5180]
See this error on current ['latest'](https://hub.docker.com/layers/rector/rector/latest/images/sha256-53135c964b180ae47f889a1ed68adb4e2835fcd595a6f3aa6ae723fe5ebfbca5?context=explore) rector/rector docker pull.

```
Notice: Nette\Utils\Strings::toAscii(): it is recommended to enable PHP extensions 'intl'. in /rector/vendor/nette/utils/src/Utils/Strings.php on line 152
```

I suppose it's `/bin/sh -c docker-php-ext-enable intl` in some deployment script.

Probably here: https://github.com/rectorphp/rector/blob/e09d2ab0ab1a9b9762823dd89a6fbc8ac429d065/Dockerfile#L15-L17

**Comment by HenkPoley** [comment]
Still debugging 

```
 [ERROR] Could not process "somefile.php" file, due to:
         "Class 'Symplify\Astral\ValueObject\NodeBuilder\PropertyBuilder' not
         found".
```

Which appears to be used from here in rector: https://github.com/rectorphp/rector/blob/6c11a254aad70bef41681462d8aa54f7b8ce77e4/src/PhpParser/Node/NodeFactory.php#L237

Maybe some missing or changed Composer package?

**Comment by TomasVotruba** [comment]
Hi, this has been reported many times. I guess we can give it a try to ease the Docker usage.

Could you send PR with adding intl?

**Comment by TomasVotruba** [comment]
> Maybe some missing or changed Composer package?

You're right, I'm on it

**Comment by samsonasik** [comment]
should be fixed by https://github.com/rectorphp/rector/pull/5182 and https://github.com/rectorphp/rector/pull/5184

**Comment by samsonasik** [comment]
re-open, docker build in github action seems failed https://github.com/rectorphp/rector/runs/1701806223?check_suite_focus=true

**Comment by samsonasik** [comment]
it seems already fixed in latest master https://github.com/rectorphp/rector/runs/1705631667

**Comment by HenkPoley** [comment]
Thanks. I ought to have tested it on my machine (if I knew how) 😅
