### ISSUE TITLE
ASC\DESC to Criteria::ASC\DESC

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector#5183]
Thank you for such a cool tool!

# Feature Request
I see a lot in code, that people don't use `Doctrine\Common\Collections\Criteria` constants such as `Criteria::ASC` or `Criteria::DESC`, but they use strings `ASC` or `DESC`. I would like to move string to constants.
 
## Diff 

```diff
- ->orderBy('item.id', 'DESC')
+ ->orderBy('item.id', Criteria::DESC)
```
also if you would look in the code, you can see that `Doctrine ORM` accepts criteria parameter as insensitive one, and then converts to upper case.
So this one also counts
```diff
- ->orderBy('item.id', 'DeSc')
+ ->orderBy('item.id', Criteria::DESC)
```

Yet another case for this is `findBy`/`findOneBy` methods, where the 2nd argument is `array $orderBy`
so the diff will look like this
```diff
- ->findOneBy(['id' => 1], ['dateEnd' => 'DESC']);
+ ->findOneBy(['id' => 1], ['dateEnd' => Criteria::DESC])
```
or
```diff
- ->findOneBy(['lastName' => 'Smith'], ['dateEnd' => 'DESC']);
+ ->findOneBy(['lastName' => 'Smith'], ['dateEnd' => Criteria::DESC])
```
--------------------
Leaving it here for history reasons, maybe some one will catch up (maybe I'll do it in my free time)

**Comment by TomasVotruba** [comment]
Hi,

give a try to this rule: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#replacestringwithclassconstantrector

**Comment by vladyslavstartsev** [comment]
wow! this is the thing that I need

**Comment by TomasVotruba** [comment]
Great :) you're lucky, we've added it yestereday for https://getrector.org/blog/2021/01/11/switch-symfony-string-route-names-to-constants

If it works for you, could you add it to `doctrine-code-quality.php` set? It think it's the right place to have it :)

**Comment by vladyslavstartsev** [comment]
Sure!

**Comment by TomasVotruba** [comment]
Closing as answered.

Another way of running Rector on old code base is prefixed version:

- https://github.com/rectorphp/rector-prefixed
