### ISSUE TITLE
Not Implemented Yet exception thrown

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#5234]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.10             |
| Installed as   | composer dependency                           |

When running rector it fails on a bunch of files, however the errors I was getting looked like this
```
 [ERROR] Could not process "app/Listeners/NotifyInvoiceBooked.php" file, due to:                                        
         "".    
```
So I tried running it again with verbose on and got

```
In AbstractReadNodeAnalyzer.php line 60:
                                                      
  [Rector\Core\Exception\NotImplementedYetException]  
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/289c2eaf-c214-4f7d-995d-c1f8a9a6dff0

## Expected Behaviour

That rector would be able to run the files.

**Comment by olivernybroe** [comment]
Sorry for the code example 😟 

I took my file and kept deleting stuff and simplifying until I couldnt delete more. Might be some other changes which could have been made, however this was the most basic I could do for the issue.

**Comment by TomasVotruba** [comment]
I'm on it
