### ISSUE TITLE
Join forces with CakePHP Upgrades

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#524]
To cover 3.x upgrades 

- https://github.com/cakephp/upgrade
- Rules here: https://github.com/dereuromark/upgrade/tree/develop/src/Shell/Task
- https://www.dereuromark.de/2018/03/14/cakephp-3-6-is-coming/

> There is a very useful PHP tool that can help with deprecation replacement called rector.
It introspects the code and can very reliably identify and replace code pieces.

Thanks @dereuromark for the mention :clap: :clap:  :+1: I didn't even notice CakePHP is promoting Rector.

Is there anything I can do for you to migrate `dereuromark/upgrade` rules or improve current migrations?

**Comment by dereuromark** [comment]
I like your idea of community joined forces here.

For the time being the most helpful would be to cover most easy renames and deprecations (e.g. combined sth() getter/setter in its standalone parts getSth()/setSet() etc) from the migration guides, up to current 3.6 one:
https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html

Apart from that we could look into a few more edge cases that my tool or the core rules offer.
But I think the main benefit of your tool would be to apply all the standard use cases for now.

**Comment by TomasVotruba** [comment]
Thanks, I prefer saving one's energy and focus it on something new

I like your the plan :+1: 

Migration to CakePHP 3.6 was added few months ago: https://github.com/rectorphp/rector/pull/346/files#diff-725bd3c9cd02d029773d467d694a77f2

Is there something important missing?

I don't know what versions are most used in CakePHP. It might be more effective to add CakePHP 3.5, 3.4... 3.0 migrations, rather than making just CakePHP 3.6 perfect. What do you think?

**Comment by dereuromark** [comment]
Most people usually already migrated to 3.5 or now 3.6 (midway)
As such the full 3.6 (yours is still somewhat incomplete by the way) really should be the focus.

**Comment by TomasVotruba** [comment]
I see, thanks!

Could you point me to code parts in your upgrader, that is missing in Rector?

That way I'd could prepare rules to migrate it

**Comment by TomasVotruba** [comment]
Ping @dereuromark

**Comment by TomasVotruba** [comment]
Where can I start, @dereuromark ?

**Comment by TomasVotruba** [comment]
That's already covered: https://github.com/rectorphp/rector/pull/346/files#diff-725bd3c9cd02d029773d467d694a77f2
