### ISSUE TITLE
Using Option::AUTO_IMPORT_NAMES, the class name of the imported class is wrong

### ISSUE THREAD

**Issue by DieterHolvoet** [rectorphp/rector#5241]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.10              |
| Installed as   | prefixed Rector  (also tried with regular)                          |

Using `Option::AUTO_IMPORT_NAMES`, the class name of the imported class is wrong. 

## Minimal PHP Code Causing Issue

https://gist.github.com/DieterHolvoet/282fca44f3122285f6ff77dba4f4a8ea

## Expected Behaviour
Work as expected

**Comment by TomasVotruba** [comment]
Hi,
thanks for reporting.

What is the exact expected output? In Diff or PHP code

**Comment by DieterHolvoet** [comment]
This is the output from the command:
```
> /vendor/bin/rector process test.php
Rector 0.9.10
Config file: rector.php

 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ! [NOTE] File "test.php" was changed

1 file with changes
===================

1) test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -12,10 +12,10 @@

 class BrochureService
 {
-    protected EntityTypeManager $entityTypeManager;
+    protected \App\EntityTypeManagerInterface $entityTypeManager;

     public function __construct(
-        EntityTypeManager $entityTypeManager
+        \App\EntityTypeManagerInterface $entityTypeManager
     ) {
         $this->entityTypeManager = $entityTypeManager;
     }
    ----------- end diff -----------


Applied rules:

 * Rector\Renaming\Rector\Name\RenameClassRector



 [OK] Rector is done! 1 file has been changed.
```

This is the actual file:
```php
<?php

namespace App;

class EntityTypeManagerInterface
{
}

class EntityTypeManager extends EntityTypeManagerInterface
{
}

class BrochureService
{
    protected \App\EntityTypeManagerInterfaceInterface $entityTypeManager;

    public function __construct(
        \App\EntityTypeManagerInterfaceInterface $entityTypeManager
    ) {
        $this->entityTypeManager = $entityTypeManager;
    }
}
```

**Comment by TomasVotruba** [comment]
That looks like expected output

**Comment by DieterHolvoet** [comment]
No, the word _interface_ is double: `EntityTypeManagerInterfaceInterface`

**Comment by TomasVotruba** [comment]
I see. In that case we'll need a failing test case.

[Here is how to add it](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md)

**Comment by DieterHolvoet** [comment]
I tried, but I cannot seem to be able to reproduce it using a test. I did however notice it's not a problem with RenameClassRector: even when no rules are applied, the import of `EntityTypeManagerInterface` is changed to `EntityTypeManagerInterfaceInterface`. It probably has something to do with `Option::AUTO_IMPORT_NAMES`.

I can give you this, I can recreate the issue using this code and config: https://gist.github.com/DieterHolvoet/282fca44f3122285f6ff77dba4f4a8ea

**Comment by TomasVotruba** [comment]
> I tried, but I cannot seem to be able to reproduce it using a test. 

Maybe there is little detail missing in the test. Send what you've got and we'll check it :)

**Comment by TomasVotruba** [comment]
> I tried, but I cannot seem to be able to reproduce it using a test. 

Maybe there is little detail missing in the test. Send what you've got and we'll check it :)

**Comment by DieterHolvoet** [comment]
I started writing a test for `RenameClassRector`, but since I discovered that the rule is not directly related to this issue I'm not exactly sure where the test should be located.

**Comment by TomasVotruba** [comment]
You can place it in `RenameClassRector` tests, as it's the place it was discovered. Principle of least surprise.

There should be also test related to imports only - https://github.com/rectorphp/rector/blob/master/rules/renaming/tests/Rector/Name/RenameClassRector/AutoImportNamesParameterTest.php

**Comment by TomasVotruba** [comment]
Any updates on this one?

**Comment by DieterHolvoet** [comment]
Haven't had the time to work on this, I probably will have during the coming week.

**Comment by DieterHolvoet** [comment]
I already spent hours on this and I can't seem to reproduce it using a test. I can reproduce it using the files attached in the gist. I added my WIP test in a MR.

**Comment by TomasVotruba** [comment]
I'll look into this

**Comment by TomasVotruba** [comment]
Closing as tests is passing correctly in `dev-main` now 

Thank you for testing :+1:

**Comment by DieterHolvoet** [comment]
The test I tried to write wasn't finished yet, like I said before I couldn't reproduce the issue using a test. You can find minimal PHP Code causing the issue in the Gist linked in the issue description. The issue is still present when using `rector/rector-prefixed:0.10.4`.

**Comment by DieterHolvoet** [comment]
Another example. It even happens in YAML files.

<img width="1002" alt="Screenshot 2021-04-10 at 11 42 53" src="https://user-images.githubusercontent.com/3606531/114265588-e5698d00-99f1-11eb-8797-7b750b379f7d.png">

**Comment by TomasVotruba** [comment]
Thanks for reaching out.

> You can find minimal PHP Code causing the issue in the Gist linked in the issue description

We'll need a failing Github Action on Github repository to verify. Could you move this there and add Github Action so we can see the fail?
