### ISSUE TITLE
[MakeCommandLazyRector] Broken behaviour with php8 constructor property promotion and empty body

### ISSUE THREAD

**Issue by dvapelnik** [rectorphp/rector#5244]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.9.10              |
| Installed as   | composer dependency                           |

## Minimal PHP Code Causing Issue'

I'm using the rector's class with set `SetList::SYMFONY_CODE_QUALITY` and see wrong behavior

```diff
1) app/Cli/GenerateInviteCodeCommand.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -16,12 +16,6 @@
      */
     protected static $defaultName = 'calendar:security:generate-invite-code';

-    public function __construct(
-        private InviteRegistrationGeneratorInterface $inviteRegistration
-    ) {
-        parent::__construct();
-    }
-
     protected function execute(InputInterface $input, OutputInterface $output): int
     {
         $output->writeln($this->inviteRegistration->generate());
    ----------- end diff -----------


Applied rules:

 * Rector\Symfony\Rector\Class_\MakeCommandLazyRector
```

In my opinion the reason is empty body of constructor which deletes by method `MakeCommandLazyRector::removeConstructorIfHasOnlySetNameMethodCall()`

## Expected Behaviour

Empty constructor with constructor property promotion should not be deleted

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting.

We'll need minimalistic demo on: https://getrector.org/demo 
With single responsible Rector rule.

**Comment by dvapelnik** [comment]
Hi Tomas
It looks like the demo platform does not support php8 syntax
<img width="985" alt="image" src="https://user-images.githubusercontent.com/1562244/105090916-bd7c2480-5aa7-11eb-9475-745d3aaf8dda.png">

**Comment by TomasVotruba** [comment]
The link should be available anyway

**Comment by dvapelnik** [comment]
Hi, Tomas

I create demo code snipped but with an error about unsupported token in the constructor
https://getrector.org/demo/045e6e4b-9d4f-4fb7-8b03-de277be1be09

**Comment by TomasVotruba** [comment]
Thanks for the link :+1: 

That looks like a bug in demo page :/ I'll check it.


In the meantime, we'll need a failing test case to be added in `MakeCommandLazyRectorTest`. [Here is how to add a test](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md)
