### ISSUE TITLE
Rector to replace constructor with static method call

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#5245]
Hi there,

I had a look through the rectors, but couldn't find anything.
Is there a rector that can do this?
before:
```php
new Foo('bar');
```
after
```php
Foo::create('bar');
```

many thanks!

**Comment by TomasVotruba** [comment]
Hi Ben,

such rules could be found in "Transform" group. E.g. method call to static call etc.

Maybe this one:
https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#newtostaticcallrector

**Comment by bendavies** [comment]
Doh! thankyou @TomasVotruba !

**Comment by TomasVotruba** [comment]
You're welcome :)
