### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivatePropertyRector

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector#5247]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.9.10      |
| Installed as   | rector-prefixed  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/83375544-1a55-4f44-a079-92488b8d23b2

```php
<?php

final class DemoFile
{
    private A $a;

    public function __construct(A $a)
    {
        $this->a = $a;
    }

    public function f()
    {
       $o
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($this->a->g($d->f1()))
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
            ->f1($d->f1())
        ;
    }
}
```

### Responsible rules

* `RemoveUnusedPrivatePropertyRector`

## Expected Behavior

Rector should skip to change this code, since `$this->a` is used

**Comment by TomasVotruba** [comment]
Hi,

chain calls are often memory/CPU expensive and can crash both PHPStan and php-parser.
To avoid that, Rector have a default limit of 30 nodes.

It usually works for most code bases. To make your code base apply, change the parameter to higher value:
https://getrector.org/demo/63df356a-2cbf-4f38-99aa-0552083606b8
