### ISSUE TITLE
Incorrect behavior of RemoveConcatAutocastRector (make rector friends with psalm)

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector#5249]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.9.10      |
| Installed as   | rector-prefixed  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1088de57-c4e8-4fa5-bcea-0fa742a09ee0

```php
<?php

class A
{   
    public function d():?string
    {
        return rand(0, 1) ? 'string;' : null;
    }
}

class C
{
    public function b(): string
    {
        return 'asddas' . (string) (new A())->d();
    }
}
```

### Responsible rules

* `RemoveConcatAutocastRector`

## Expected Behavior

First see psalm link
https://psalm.dev/r/295581859d - non "fixed" 
https://psalm.dev/r/d9fdd01acd - "fixed"

I want both tools to  coexist, in this case psalm is right (imho).
Is there a way, for rector to check if the casted value would be of right type after deleting casting operation?

**Comment by TomasVotruba** [comment]
Such behavior is correct, as concat autocasts to `string`.

See even `null` case: https://3v4l.org/irbQj
