### ISSUE TITLE
Incorrect behavior of AddDefaultValueForUndefinedVariableRector

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector#5253]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.9.10      |
| Installed as   | rector-prefixed  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/62ab1e88-6035-4fa6-87bb-c600dac418b2

```php
<?php

final class DemoFile
{
    public function run()
    {
        $a['a'] = 'b';
        $a['a'] = 'b';
        $a['a'] = 'b';
    }
}
```

### Responsible rules

* `AddDefaultValueForUndefinedVariableRector`

## Expected Behavior

if you go to the link, rector always sets the default value to `null`. But it can guess, based on the type that is used, which default value to set. In example that I gave, it is reasonable to have empty array as default value. I haven't discovered other cases yet.

**Comment by TomasVotruba** [comment]
Hi, thanks for report.

Could you add failing test case to `AddDefaultValueForUndefinedVariableRectorTest` to confirm what is expected? That way we'll have it covered for the future.
