### ISSUE TITLE
RemoveUnusedPublicMethodRector removes public constructors

### ISSUE THREAD

**Issue by j2L4e** [rectorphp/rector#5256]
# Bug Report

Rector Version: 5e882a7

RemoveUnusedPublicMethodRector removes public constructors even if the class is `new`ed.

## Minimal PHP Code Causing Issue
Failing test fixture:

```
<?php

namespace Rector\DeadCode\Tests\Rector\ClassMethod\RemoveUnusedPublicMethodRector\Fixture;

final class Fixture
{
    public function __construct() 
    {
    }
}

new Fixture();

?>
```

https://getrector.org/demo/48213d30-8e42-4f9f-885b-30906a78970f
## Expected Behaviour

Public constructors shouldn't be removed. In my opinion not even if the class is never `new`ed as that would be taken care of by RemoveUnusedClassesRector

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting. We need a failing test case to be added via PR: [here is how](https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md)

**Comment by j2L4e** [comment]
#5257

**Comment by TomasVotruba** [comment]
@j2L4e Thank you
