### ISSUE TITLE
Parsing error on `@var` in v0.9.12   

### ISSUE THREAD

**Issue by vhenzl** [rectorphp/rector#5267]
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.12              |
| Installed as   | prefixed |

Parsing this code:

```php
<?php declare(strict_types=1);

namespace RectorBugTest;

class RectorBug
{
    public function fails(\Symfony\Component\HttpFoundation\Request $request): void
    {
        $request->query->get('xxx');
    }
}
```

results in this parsing error on `@var` annotation:

```
[parsing] src/RectorBug.php
PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser::parseTagValue()" on line 137 in <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php:137
Stack trace:
#0 <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php(128): Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser->parseTagValue(Object(PHPStan\PhpDocParser\Parser\TokenIterator), '@var')
#1 <project>\vendor\phpstan\phpdoc-parser\src\Parser\PhpDocParser.php(53): Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser->parseTag(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#2 <project>\vendor\phpstan\phpdoc-parser\src\Parser\PhpDocParser.php(40): PHPStan\PhpDocParser\Parser\PhpDocParser->parseChild(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#3 <project>\v in <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php on line 137
Fatal error: Uncaught Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser::parseTagValue()" on line 137 in <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php:137
Stack trace:
#0 <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php(128): Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser->parseTagValue(Object(PHPStan\PhpDocParser\Parser\TokenIterator), '@var')
#1 <project>\vendor\phpstan\phpdoc-parser\src\Parser\PhpDocParser.php(53): Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser->parseTag(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#2 <project>\vendor\phpstan\phpdoc-parser\src\Parser\PhpDocParser.php(40): PHPStan\PhpDocParser\Parser\PhpDocParser->parseChild(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#3 <project>\v in <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php on line 137
```

I'm not sure what's special about Symfony's `Request` but I wasn't able to reproduce the problem with a custom code.

Surprisingly, the error shows even here: https://getrector.org/demo/15c3fd41-9764-4f6d-8f3e-e9ccc36b252d

Different line numbers (180 vs 137) because of unprefixed vs prefixed version

**Comment by althaus** [comment]
Have the same issue. Running the command verbose shows this error:

~~~
PHP Fatal error:  Uncaught Error: Call to undefined function get_debug_type() in <project>/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php:682
...
~~~

Seems like the PHP8 polyfill is missing? Rector runs on 7.4. here.

**Comment by TomasVotruba** [comment]
I'm on it, thanks for report :+1:

**Comment by TomasVotruba** [comment]
In demo, the `Request` class is missing. When you add it, it works correctly:
https://getrector.org/demo/ceb979ec-3cd5-4f80-a50d-2fc7519e618f
Same applies for your project. 

We'll need a reprorucible repository with failing GitHub action to be able to fix it.

**Comment by TomasVotruba** [comment]
@althaus Hi, that's a different bug. Could send PR with adding that package?

**Comment by vhenzl** [comment]
@TomasVotruba Yeah, I know, that's why I was surprised I actually got the same error there (I though `Request` might be present and autoloaded when the demo processed on server).

As I said, I wasn't able to reproduce it with a custom code. Creating a fake `Request` class as you did isn't helpful.

The real `Request` in my project exists, it's autoloaded, the project works normally. Rector can load the file as well. If I dump vars in `BetterPhpDocParser#parseTagValue()`, I can see `$tag` contains `@var`, `$tokenIterator` contains the whole doc comment, but `currentNodeProvider->getNode()` returns `null` and that's why `ShouldNotHappenException` is thrown. Who and where should set the current node?

Any advice on how to create a repro?

**Comment by TomasVotruba** [comment]
I have no idea. We'll need to see the problematic code.

> Any advice on how to create a repro?

Ideally GitHub repository with:

- composer install with least dependencies
- minimal `rector.php` setup 
- minimal PHP code - ideally 1 class
- GitHub action setup where `vendor/bin/rector p src --debug` is run

**Comment by vhenzl** [comment]
Done: https://github.com/vhenzl/rector-issue-5267

Looks like a Window specific problem. Runs correctly on Ubuntu and fails on Windows.

**Comment by TomasVotruba** [comment]
Ay. That would be tricky, as I don't use Windows and cannot debug it.

What happens when you try to find calls above the reported one?

**Comment by vhenzl** [comment]
Well, seems like @althaus is actually right and it is the same problem. If I run it on Windows with PHP 8 installed, it runs correctly.

**Comment by TomasVotruba** [comment]
Tht's great! Could you send PR with fix?

**Comment by vhenzl** [comment]
> What happens when you try to find calls above the reported one?

There isn't much else to see in `\Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser` nor `\PHPStan\PhpDocParser\Parser\PhpDocParser`. `$tokens` (or `$tokenIterator`) correctly contains comment tokens for https://github.com/symfony/http-foundation/blob/4.4/Request.php#L91-L95. So the file is read. The problem is that `CurrentNodeProvider` instance doesn't contain the current node (what type node should it be? `\PhpParser\Comment\Doc`?)

So my question again is, where should the current node be set? Which part of Rector to look at? To be able to debug, what's happening there…

> Could you send PR with fix?

Fix for what? To add the PHP8 polyfill? That's not a solution. `symfony/polyfill-php80` is installed in both my project and the repro. And it still fails. So the missing polyfill might be part of the problem but not the problem itself. The question to ask is why and where Rector silently ignores a problem which later escalates as the current node being null.

**Comment by TomasVotruba** [comment]
> Fix for what? To add the PHP8 polyfill?

Yes, it was one of bug fixes.

The `CurrentNodeProvider` has a `setNode()` method. IDE should tell where it is called:

![image](https://user-images.githubusercontent.com/924196/105429603-066fdc80-5c52-11eb-9734-012413578f1b.png)

**Comment by ERuban** [comment]
Have the same issue with Rector 0.9.14 and almost all project files with the `Request` class. ¯\_(ツ)_/¯

**Comment by vhenzl** [comment]
I have simplified the repro so that the failing code doesn't depend on Symfony. And it's now failing on both Windows and Ubuntu and both PHP 7.4 and PHP 8.0.

As for `CurrentNodeProvider#setNode()`, the only relevant place where it could be called is in `PhpDocInfoFactory` but none of its public methods is called during the parsing phase.

**Comment by vhenzl** [comment]
Something has been changed between versions [0.9.10 and 0.9.11](https://github.com/rectorphp/rector/compare/0.9.10...0.9.11).

0.9.10 works: https://github.com/vhenzl/rector-issue-5267/actions/runs/505812604
0.9.11 fails: https://github.com/vhenzl/rector-issue-5267/actions/runs/505815492

#5250 seems to be the culprit.
