### ISSUE TITLE
Typed properties added don't respect interfaces higher in the hierarchy

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#5270]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.12             |
| Installed as   | composer dependency                           |

```diff
interface SimpleValueObjectInterface
{
    /**
     * Accepts a simple scalar value.
     *
     * @param float|int|string $value
     */
    public function __construct($value);
}

interface VatRateInterface extends SimpleValueObjectInterface
{
     /**
      * @param string $countryCode
      */
-    public function __construct($countryCode);
+    public function __construct(string $countryCode);
 }
 
 final class VatRate implements VatRateInterface
 {
+    public string $countryCode;
     /**
      * {@inheritDoc}
      *
      * @param string $countryCode
      */
-    public function __construct($countryCode)
+    public function __construct(string $countryCode)
     { 
         $this->countryCode = $countryCode;
     }
}
```

## Minimal PHP Code Causing Issue

I've reproduced the issue here: https://getrector.org/demo/58520b99-1c52-4f0f-9ba2-24aa254a5908

This is a failed attempt to simplify it: https://getrector.org/demo/e1ba922e-f3ab-4f63-b3fb-384fdcb3327a

You can check the failed build here: https://github.com/Aerendir/component-value-objects/pull/201/checks?check_run_id=1740739769

## Expected Behaviour

The parameters of the constructor are not typed to respect the interface.

**Comment by TomasVotruba** [comment]
Hi,

thanks for report. Here is minimal code to reproduce: https://getrector.org/demo/56b352cf-6ba5-4fd5-8186-dd071d1e4010
Is that correct?

If so, we'll need a failing test case to `ParamTypeDeclarationRectorTest`. There is a link in demo that helps with creating PR :) give it a try

**Comment by Aerendir** [comment]
Yes, it is correct!

I've create the PR, hoping it is right 😅

**Comment by Aerendir** [comment]
Ok, there is a bug in the builder: the generated code doesn't add correctly the namespace... I'm going to edit it manually...

**Comment by Aerendir** [comment]
Perfect: it now works... in the sense that the PHPUnit tests fail... correctly 🤯 ... 😂

The ability to create a failing test case directly from the demo is a game changer! 🚀
