### ISSUE TITLE
Incorrect behavior of ConsoleExecuteReturnIntRector

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector#5273]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.9.10      |
| Installed as   | rector-prefixed  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/2ce24767-1f3c-4f0c-b74f-bbea4b441678

```php
<?php

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

final class DemoCommand extends \Symfony\Component\Console\Command\Command
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        return (int) random_int(0,1);
    }
}
```

### Responsible rules

* `ConsoleExecuteReturnIntRector`

## Expected Behavior

it should change nothing because the value before return is casted to `int`

related to #5272

**Comment by Aerendir** [comment]
Waiting for the @TomasVotruba 's feedback, you can use https://getrector.org/demo to reproduce the issue.

Then, directly from the demo, you can generate a failing test case and send a PR.

I've just done it (https://github.com/rectorphp/rector/issues/5270) and it is really simple, fast and useful... This will also speed up the fixing times 💪
