### ISSUE TITLE
Improve detection of side effects

### ISSUE THREAD

**Issue by j2L4e** [rectorphp/rector#5284]
Any rule that removes "useless" nodes needs to detect if that node has side-effects, which would likely mean it's unsafe to proceed.

It boils down to walking the node recursively and checking if all children are side-effect free. Unfortunately there's no way to tell if calling a builtin or extension function is in fact side-effect free (or "pure").

There's `PureFunctionDetector::detect` that's based on a blacklist of well-known impure functions:
https://github.com/rectorphp/rector/blob/9cd09e95125d4f04bd62a26c8ab90dada2cd6a33/rules/dead-code/src/SideEffect/PureFunctionDetector.php#L16-L103
That approach always classifies non-listed functions as `pure` leading to false positives. An example would be `array_pop` which isn't listed but clearly has a side-effect.

JetBrains maintains stubs for phpstorm under apache 2. Those also include info on known pure functions (e.g. https://github.com/JetBrains/phpstorm-stubs/blob/868a838943337026e55e3e647ff01b4da6a322ef/PDO/PDO.php#L1653). Extracting these would allow for a whitelist-based approach which is much less error-prone.

**Comment by TomasVotruba** [comment]
I like it :+1:

**Comment by TomasVotruba** [comment]
Closing as accepted. Feel free to send PR when you're ready
