### ISSUE TITLE
Incorrect behavior of TemplateMagicAssignToExplicitVariableArrayRector

### ISSUE THREAD

**Issue by RiKap** [rectorphp/rector#5286]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 9.14      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/cb7a63bb-d6ab-4f83-916e-714531f095bd

```php
<?php

namespace App
{
    class TestPresenter extends \Nette\Application\UI\Presenter
    {

        public function __construct($logger)
        {
            $this->logger = $logger;
        }
        
        public function renderDefault()
        {

        }
        
    }
}
    
namespace Nette\Application\UI
{
    class Presenter extends Control
    {
    }
    
    class Control
    {
    }
}
```

### Responsible rules

* `TemplateMagicAssignToExplicitVariableArrayRector`

## Expected Behavior

- It should ignore `__construct`

**Comment by TomasVotruba** [comment]
Hi Richard,

thanks for reporting. 
Could you send failing test fixture with expected output in a PR to `TemplateMagicAssignToExplicitVariableArrayRectorTest`?

"Create a Test" button on demo might help :)
