### ISSUE TITLE
[Nette 3.1] The save() method does not accept callable anymore

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5318]
See https://github.com/nette/caching/commit/5ffe263752af5ccf3866a28305e7b2669ab4da82#diff-c3abbeb8a7d04b072c4f38e38e10d763123f5503f1719f852ec21e1602c4c4db

```diff
-$result = $this->cache->save($key, function () {
-    return $this->getSomeHeavyResult();
-});

+$result = $this->getSomeHeavyResult();
+$this->cache->save($key, $result);
```

**Comment by lulco** [comment]
I have never used it :) callback in load function yes, but save?

**Comment by TomasVotruba** [comment]
What's not forbidden... :)

That's from one of Nette project I work on.

**Comment by TomasVotruba** [comment]
I'm on it
