### ISSUE TITLE
Why am I getting an old version of rector?

### ISSUE THREAD

**Issue by jkester1986** [rectorphp/rector#5320]
# Question
I ran `composer require rector/rector --dev`, then `vendor/rector/rector/bin/rector init`. This is the output:
```
Rector v0.5.23
                                  
  Command "init" is not defined.  
                                  
```
I know this is an old version of Rector, but I have no idea how to get an up-to-date version

**Comment by TomasVotruba** [comment]
Hi, probably other packages in your project. Composer can only install packages that are compatible with them.

Try: https://github.com/rectorphp/rector-prefixed

What PHP version do you use?

**Comment by jkester1986** [comment]
was using PHP 7.1. Switched over to 7.2, I think I'm ok now? I don't see anything in the readme mentioning what version to use, but the init command did work now.

**Comment by TomasVotruba** [comment]
Good :+1: 

Each tag uses different version. E.g. last one uses PHP 7.3 as min:
https://github.com/rectorphp/rector/blob/e00106ee498b237b0d54329dc803c4d79114b7e8/composer.json#L23
