### ISSUE TITLE
ServiceEntityRepositoryParentCallToDIRector throws Exception when Repository class contains methods

### ISSUE THREAD

**Issue by DominikFirla** [rectorphp/rector#5323]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.9.5 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency / prefixed Rector                           |

ServiceEntityRepositoryParentCallToDIRector will throw: 
`Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\Doctrine\Rector\ClassMethod\ServiceEntityRepositoryParentCallToDIRector::removeParentConstructAndCollectEntityReference()" on line 174`

This happens, if processed class extending ServiceEntityRepository has methods other than just __construct.

## Minimal PHP Code Causing Issue

In this fork, I have added fixture that will trigger the error when running the test:
https://github.com/rectorphp/rector/compare/master...DominikFirla:entity-repo-rule-error

Used  this command to run the test:
`vendor/bin/phpunit rules/doctrine/tests/Rector/ClassMethod/ServiceEntityRepositoryParentCallToDIRector --stop-on-failure`

On actual project I also noticed in diff that when this error occurs, it will remove all function parameters from the first function following the __construct but that could be side-effect of the actual error. Will test this again after the original issue is solved.
![image](https://user-images.githubusercontent.com/22476600/105840797-e20a5c00-5fd3-11eb-98ac-8c2d9e2089bd.png)

## Expected Behaviour
The exception should not occur - it is totally expected that a Repository class will have methods other than __construct defined.

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting. We'll need a failing fixture to be added via pull-request.
Here is how to add it:
https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by DominikFirla** [comment]
Hi,
pull request: https://github.com/rectorphp/rector/pull/5332
