### ISSUE TITLE
PSR-4 namespacing migration produces files referencing classes from old namespace

### ISSUE THREAD

**Issue by jkuchar** [rectorphp/rector#5326]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master              |
| Installed as   | composer dependency                    |

PSR-4 namespacing migration produces files referencing classes from old namespace. 

## Minimal PHP Code Causing Issue

N/A as [on-line rector is not able to run PSR-4 ruleset](https://getrector.org/demo/dfb96a92-e53d-4fe9-a9fe-746a77459c56). How should I send a failing test for this ruleset?

## Expected Behaviour

To migrate code to new namespace (which is done properly) and all references to classes which are now in new namespace are updated (after migration it still references classes using old FQN, which does not exists)

**Comment by TomasVotruba** [comment]
The demo doesn't have `composer.json`, so PSR-4 won't do there.

Well need a test responsible rule - here is how https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by TomasVotruba** [comment]
Closing for lack of test
