### ISSUE TITLE
Incorrect behavior of ForToForeachRector

### ISSUE THREAD

**Issue by mkrauser** [rectorphp/rector#5338]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/679daae2-1fb3-4f01-86a6-a8c44e91a991

```php
<?php

final class DemoFile
{
    public function run()
    {
        $test = ['t', 'e', 's', 't'];

        for($i = 0; $i < count($test); $i++) {
            echo $test[$i];
            echo " ";
        }
    }
}
```

### Responsible rules

* `ForToForeachRector`

## Expected Behavior

Rector modifies the loop like this:

`foreach ($test as $i => $test) {`

which of course does not work. The issue is, that ForToForeachRector tries to guess the variable name by singularizing it using the Inflector. 
Some iterable-names, like $test cannot be singularized so the Inflector returns the same name, which leads to this problem. And in my experience names like this are found a lot in legacy codebases.

At least the singularized name should be checked if it is different from the iterable variable name. If not, the value-variable needs to be constructed in some other way. 
If anyone comes up with an idea how to do this, I'll be happy to submit a PR.

Thank you for your work and this awesome project!

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting the error.
We'll need a failing fixture with expected result, here is how you add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
The possible solution may be change the singular value var to something more general, eg: "$value", with the following conditions:

1. if "$value" is used before foreach, skip, nothing we can do.

```php
$value = 'some value';
foreach ($test as $test) { // skip change

}

echo $value; // here can be a bug if `$test` changed to `$value`
```

2. if expr itself named "$value", change value var to a variable like "$v" with check if `$v` used in previous loop

```php
foreach ($value as $v) { // change to "$v"

}

echo $v; // here can be a bug if previous loop has `$v`
```

3. if value var is not named "$value" change to "$value"

```php
foreach ($x as $value) { // change to "$value"
    
}
```

@TomasVotruba @mkrauser what do you think?

**Comment by mkrauser** [comment]
I also thought about pluralizing the original variable, but that would be require too much change outside the loop.
So going in the direction of your suggestions seems logical. Another possibility would be to use a prefix, like this:

```php
foreach($test as $singleTest) { // or $oneTest
   
}
```

This would probably cause less trouble, than using $value
