### ISSUE TITLE
Why does SetList::PHP_74 apply Rector\Php74\Rector\Class_\ClassConstantToSelfClassRector ?

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#5341]
# Question

I had a little off-topic chat about this here: https://github.com/rectorphp/rector/pull/5190#issuecomment-768198603 but it is more about the initial commit at: https://github.com/rectorphp/rector/commit/2e7bdca4e2c2b630d638b2fb3bd58b09a951c154

Basically this rector transforms `__CLASS__` to `self::class`. But..

* Both are _still legal_ in PHP 7.4, 8.0(, and 8.1 I think)
* Both were _equal_ since PHP 5.5

So.. why apply it at the version level SetList::PHP_74 ? Why not at SetList::PHP_55? I mean, if it is objectively better for some reason, sure apply it as soon as possible (yuck dynamic 'constants' or something). Maybe there was some discussion that they wanted to kick it because it makes the (then upcoming) JIT go loopy and slow, but I'm _not_ seeing such referenced. Then it could be a SetList::PHP_80.

And.. is it not just a SetList::CODE_QUALITY or SetList::CODING_STYLE thing ?

I just found it odd that the only 'upgrade' to my codebase that SetList::PHP_74 did was something inconsequential for running it on that PHP version 🤷‍♂️. Or maybe there are subtilties around this with PHP >=7.4 that I haven't seen.

Edit: I see [Exacat has a similar rule](https://exakat.readthedocs.io/en/latest/Rules.html#detect-current-class), which reference the deprecated deprecation 😉 around `get_called_class()` that is no longer is longer on [the PHP 7.4 deprecation list](https://wiki.php.net/rfc/deprecations_php_7_4).

Edit2: I see the `get_called_class()` part (probably a different rector) is up for grabs for PHP ~~8.0~~/8.1/9 again: https://wiki.php.net/rfc/deprecations_php_8_0 <-- about PHP 8.1 ??

**Comment by TomasVotruba** [comment]
Hi,

Rector's upgrade is not only to fix BC breaks, but to use the latest language features.

Upgrades are not only about fixing deprecated features, but also about using the topmost tier that new PHP or packages allows. E.g. typed properties are not the only way that works in PHP 7.4, the old is still supported, but goal of upgrades is so devs can enjoy the newest features available :)

**Comment by HenkPoley** [comment]
Set: [SetList::PHP_74](https://github.com/rectorphp/rector/blob/master/config/set/php74.php)

Rule: [Rector\Php74\Rector\Class_\ClassConstantToSelfClassRector](https://github.com/rectorphp/rector/blob/master/rules/php74/src/Rector/Class_/ClassConstantToSelfClassRector.php)

Well.. 'self::class' has been the 'latest language feature' since PHP 5.5

**Comment by TomasVotruba** [comment]
I see. I didn't get your issue right. 

So you're proposing to move the `ClassConstantToSelfClassRector` to `PHP_55`?

I agree :+1:

**Comment by HenkPoley** [comment]
Another part of my question was, what is the reason of choosing 'self::class' over '__CLASS__'?

Apart from 'it kind of looks nicer' (I guess).

**Comment by TomasVotruba** [comment]
The principle of least surprise and Occams razor:

- `self::class` vs `SomeClass::class`
- `__CLASS__` vs ?
