### ISSUE TITLE
[Privatization] Add static property to constant rule

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5342]
See https://github.com/symfony/symfony/pull/39959

**Comment by simonberger** [comment]
This might be a bit harder to do than obvious in the first moment. There are several situations this cannot applied (most are well known; some might not)
- PHP < 7.1
- Write access to the static property
- Any dynamic static property access - how to reliably detect it?
  - Best maybe to stop this rule as soon as there is a dynamic const access on self or class-name (https://stackoverflow.com/questions/22495096/access-static-object-property-through-variable-name)
- `static::` read access on private static properties leaves a small possible BC when changed to const. An extending class can replace the value with a same named static property in visibility protected or public

**Comment by TomasVotruba** [comment]
Hi, thansk for feedback.

- What do you mean by `PHP < 7.1` in specific?

Only read-only static properties should be changed. Both public and private access can be detected.

**Comment by simonberger** [comment]
> * What do you mean by `PHP < 7.1` in specific?

There is no const visibility modifier before PHP 7.1.

**Comment by TomasVotruba** [comment]
Ah. This not about visibility, but to static property to constant change.
If PHP 7.1 will be used, then visibility can be added, but it's not required.

```diff
-static $property = [
   0 => 'no',
   1 => 'yes',
];
```

**Comment by simonberger** [comment]
Just wanted to mention with this condition that there is a likely situation in PHP 5.5 for example.

```diff
-private static $listValues = [
+const LIST_VALUES = [
    0 => 'no',
    1 => 'yes',
 ];
```

which could be an unwelcome change of visibility. Still a helpful task to suggest changes when refactoring applications but not that much in automation processes.

**Comment by TomasVotruba** [comment]
Understood :+1:
