### ISSUE TITLE
Add TemporaryRectorInterface without getDefinition()

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5343]
For local easy use without annoying getDefinition() contract :) 

cc @matthiasnoback

**Comment by matthiasnoback** [comment]
Another option might be to create a `DocumentedRectorInterface extends PhpRectorInterface` which contains the `getRuleDefinition()` method, so you can always add it later to your class which extends `AbstractRector`.

**Comment by matthiasnoback** [comment]
I've mentioned this in another place as well, but thought it would be useful to copy it here:

I have some doubts about "temporary" because I think it's the incorrect label in some situations. E.g. the DateTime migration rules could be part of my project forever, it's just that I'm not contributing them to the project (or my own rule library), so I don't feel the need to document them.

I think that extending from AbstractRector shouldn't require getRuleDefinition(), but if you want to document the rule, or have to because you contribute it, you should also implement DocumentedRectorInterface or something. So then you don't need two different abstract classes either.

**Comment by TomasVotruba** [comment]
I've read the first comment first, so I'll copy reply here too :D 

---

First I pushed another rule named `AbstractCoreRule` but then 650 files in Rector changed their parent and it made me think. 99 % contributions to Rector would take `AbstractRector` (as obvious name at first sight) and we'd have to explain them this naming process. Opt-in (`DocumentedRectorInterface`) would create many rules without documentation and a mess for Rector maintainers.

That's why going with opt-out (`TemporaryRectorInterface`) seems better for Rector project itself. 

The idea of Rector is to have one common collection of rules that are generic and re-usable for whole PHP community, that's why `AbstractRector` should take this message. Another idea could be to implement only `PhpRectorInterface`, and that would require some architectural changes. But would be definitelly cleaner :)

**Comment by TomasVotruba** [comment]
The `Temporary` name is missleading here, you're right. What name would describe the rule better while keeping the `AbstractRector` documented by default?

**Comment by matthiasnoback** [comment]
> That's why going with opt-out (TemporaryRectorInterface) seems better for Rector project itself.

I get it, another option here would be to have a PHPStan rule in the Rector project that says: every Rector should implement `DocumentedRectorInterface`, to make this requirement explicit only for actually contributed rules. That way, regular users don't have to worry about documentation.

**Comment by matthiasnoback** [comment]
> The Temporary name is missleading here, you're right. What name would describe the rule better while keeping the AbstractRector documented by default?

If you don't agree with my previous suggestion, then maybe `UndocumentedRector`? However, any of these opt-out names might result in the user feeling bad about it (e.g. who wants to write anything undocumented, or only temporary).

**Comment by TomasVotruba** [comment]
> I get it, another option here would be to have a PHPStan rule in the Rector project that says: every Rector should implement DocumentedRectorInterface, to make this requirement explicit only for actually contributed rules. That way, regular users don't have to worry about documentation.

I thought of that. It would be easy for me, but for external contributors, it might by another brick in the contribution.

**Comment by TomasVotruba** [comment]
> If you don't agree with my previous suggestion, then maybe UndocumentedRector? However, any of these opt-out names might result in the user feeling bad about it (e.g. who wants to write anything undocumented, or only temporary).

I get it. So we need a name that:

- is not slowing contributions to core
- does not require documentation
- is nice :) 

:thinking: 

What about `LocalRule`?
