### ISSUE TITLE
Show an error if the user creates files in Fixtures/ with extensions other than `.php.inc`

### ISSUE THREAD

**Issue by matthiasnoback** [rectorphp/rector#5349]
# Feature Request

I often make the mistake of calling my fixture files `.inc.php` instead of `.php.inc`. I think in general there should be no `.php` files in `Fixtures/` anyway, so it would be helpful if Rector would recognize those files and throw an exception. It could even suggest putting supporting code and classes in `Source/`, next to `Fixtures/`. If the filename ends with `.inc.php` it could suggest to rename it to `.php.inc`.

**Comment by samsonasik** [comment]
There is `validate-fixture-suffix` command for that for fixture : 

```
 bin/rector validate-fixture-suffix
```

![Screen Shot 2021-01-28 at 21 50 01](https://user-images.githubusercontent.com/459648/106167991-5efa2900-61c0-11eb-9a25-05ccd204a4eb.png)

**Comment by samsonasik** [comment]
The `validate-fixture-suffix` command can be found at https://github.com/rectorphp/rector/blob/92fef472e42597dc7202533ff7ce60ae21917352/utils/project-validator/src/Command/ValidateFixtureSuffixCommand.php

**Comment by matthiasnoback** [comment]
I didn't know that, great! However, I think it would be helpful if this doesn't require a manual step, because it's just a typo the developer makes while test-driven developing a new rule. So when you add a new fixture, the test case should immediately warn you when something is wrong, instead of requiring a manual command.

**Comment by TomasVotruba** [comment]
I agree with @matthiasnoback , this should be reported on test run itself. The goal is to have this information even for 3rd party developers, who have no clue about Rector-core practises.

We might add validation layer to `AbstractRectorTestCase`, that warns about this incorrect suffix.

**Comment by matthiasnoback** [comment]
Nice work!
