### ISSUE TITLE
[Nette 3.0] [CodeQuality] Add template object extraction for Presenters

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5351]
See https://blog.nette.org/en/latte-how-to-use-type-system#toc-how-to-declare-types

Related Nette commits:

- https://github.com/nette/application/commit/6c24aaa7f48b4a27a0fc898000a40ca7ffe733d2
- https://github.com/nette/application/commit/84b9b398c8874cae095287e8c12425679ff4fcda
- https://github.com/nette/application/commit/e2eec4d25ad84aac12a8acad12ca8a786bf61b07

**Comment by jkuchar** [comment]
more info here:
- https://forum.nette.org/en/32893-custom-template-class-for-presenter-and-control-experimental-feature
- released in 2.7.0 – https://forum.nette.org/en/33822-nette-latte-v2-7-0-released

**Comment by lulco** [comment]
see also macro {templatePrint}

**Comment by TomasVotruba** [comment]
Closing due missing project to provide it for, see https://github.com/rectorphp/rector/pull/5375

Contributions of this rule is welcomed in https://github.com/rectorphp/rector-nette
