### ISSUE TITLE
Do not change `isset($this->myProperty)` to avoid fatal errors on not yet initialized properties

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#5378]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

This change is wrong as if the property is not initialized, using `null === $this->myProperty` causes a fatal error.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/7f91a0fb-a4df-4f29-8042-b89543db0242

```php
<?php

final class Entity
{
    private string $myProperty;
    
    public function run()
    {
        if (false === isset($this->myProperty) || null === $this->myProperty) {
            return true;
        }
        
        return false;
    }
}
```

### Responsible rules

* `SimplifyBoolIdenticalTrueRector`

* `SimplifyIfReturnBoolRector`

* `IssetOnPropertyObjectToPropertyExistsRector`

## Expected Behavior

Code is unchanged.

**Comment by TomasVotruba** [comment]
We'll need a test for single rule to be able to change it.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback
