### ISSUE TITLE
Incorrect behaviour of RenameClassRector. New interface is implemented twice

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#5389]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f4a19e82-821f-4fe8-8374-cbb0a2b4922b

```php
<?php

interface ViewHelperInterface {};
interface ChildNodeAccessInterface {};
interface CompilableInterface {};

final class DemoFile implements ChildNodeAccessInterface, CompilableInterface
{
    
}
```

### Responsible rules

* `RenameClassRector`

## Expected Behavior

```php
<?php

interface ViewHelperInterface {};
interface ChildNodeAccessInterface {};
interface CompilableInterface {};

final class DemoFile implements ViewHelperInterface
{
    
}
```

**Comment by TomasVotruba** [comment]
Hi Sebastian,

we'll need a failing test case for this one to be added. So it's clear what is expected and covered against regression.

Demo page helps with that now :)
