### ISSUE TITLE
Rector changes annotations, however shouldn't

### ISSUE THREAD

**Issue by popovserhii** [rectorphp/rector#5392]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@a4f0c01              |
| Installed as   | composer dependency                    |

## Minimal PHP Code Causing Issue
https://getrector.org/demo/86d6de76-cfb2-4f81-bcc4-229617dc892a

## Expected Behaviour
Rector shouldn't change annotations at all.

**Comment by TomasVotruba** [comment]
Related to #4334

**Comment by TomasVotruba** [comment]
The removed parameters are actually unused, so is removed related `@param` docs.
Could you clarify exactly where is the issue?

**Comment by popovserhii** [comment]
@TomasVotruba
Take a note at `defaults={"_is_public" = true}` in `@Route`, after rules were applied there are no quotes anymore. This throws an error in Symfony.

before
`defaults={"_is_public" = true}`

after
`defaults={_is_public=true}`

**Comment by TomasVotruba** [comment]
Ah, I understand it now. Then it's related to #4334

**Comment by samsonasik** [comment]
it seems already fixed ref https://getrector.org/demo/4f6ef7a8-5a7d-4f80-955c-74b30a5bb988 . I am closing it.
