### ISSUE TITLE
How to write Rector rule to rename directories

### ISSUE THREAD

**Issue by MartinMystikJonas** [rectorphp/rector#5411]
I am trying to write rector rule to rename directories in project but I am stuck. How can I inctruct Rector to rename directory? I tried to use `$this->addMovedFile` but result is deletion of original directory and creation of empty file in place of new. Any tips?

**Comment by TomasVotruba** [comment]
Hi, this is better done with PhoStorm. It also renamed namespace in most places and takes 5 seconds to use.

What exactly is your usecase?

**Comment by MartinMystikJonas** [comment]
I tried to automate fixing of namespace - folder structure. I have some legacy code that uses all lowercase folder names and I want to upgrade it to folder names equivalent to Namespace namespace structure.

**Comment by TomasVotruba** [comment]
There is a rule that uses `composer.json` as a source of truth, then updates class names to match `composer.json` definition:

https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#normalizenamespacebypsr4composerautoloadrector
