### ISSUE TITLE
Create a cache file so Rector does not goes over the same analyzed files once again unless forced

### ISSUE THREAD

**Issue by reypm** [rectorphp/rector#5422]
# Feature Request

As the title says the idea is to create some Rector cache file for example: `.rector.cache` so it does no goes over the same file once again if you re-run rector on the same directory. Let say you have the following Rector config file:

```
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::IMPORT_SHORT_CLASSES, true);
    $parameters->set(Option::IMPORT_DOC_BLOCKS, false);
    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);

    $parameters->set(Option::SKIP, [
        __DIR__ . '/legacy',
    ]);

    $parameters->set(Option::SETS, [
        SetList::PHP_74,
    ]);
};
```
 and you run the command: `vendor/bin/rector process src` that will process all the files in there which is good and you perform some manual cleanup because you disagree with something that Rector changed for you and that is fine. Tomorrow you merge 5 files from the upstream and you need to run rector one more time but just to fix those five new files, well Rector will go once again all over the files and undone any manual change that you have done and also will take time to execute.

Having said that the idea is to create a cache file that will be used only if you did not force it to skip it and the reason to skip the cache would be for example when you add more rules to your rector that you want to apply to all the files.

I have not found any open|closed issue regarding this topic nor a functionality currently implemented. If needed I could try to make some PR and contribute but I would need some guidance|ideas on where to start :)

**Comment by TomasVotruba** [comment]
Hi,

how would you compoare it to existing cache?

```php
    // Run Rector only on changed files
    $parameters->set(Option::ENABLE_CACHE, true);
```

**Comment by reypm** [comment]
Hi @TomasVotruba I did not know about such option 🤔  perhaps would be good to add all the supported flags when you run `rector init` for first time and let the developer delete or comment those that are not needed. 

And as for the comparison I was thinking in going line by line on the file (dunno the structure yet have to take a looK) and the compare the current file name/path and skip it if it is already there, however I am having second thoughts on this like: if I need to run a rule in all of them just delete the created cache file and that will do the job.

**Comment by TomasVotruba** [comment]
Hi,

the init command is for dumping `rector.php` file only.

It's Symfony console convention to display all options on `--help`. You can check `vendor/bin/rector process -h` to get all the options. 

I'm not sure what you suggest, bug any caching improvement is welcomed. PR would be better to talk discuss real changes.

> it uses the FQDN for the class even if it is already on the use statement, can that be changed somehow?

There is documentation for the important options that answers both your questions: https://github.com/rectorphp/rector#full-config-configuration → `AUTO_IMPORT_NAMES`

**Comment by reypm** [comment]
@TomasVotruba am I missing something?

**Comment by TomasVotruba** [comment]
Not sure what you mean

**Comment by reypm** [comment]
ohh I think I am missing this one:

**Comment by garethellis36** [comment]
What does `Option::ENABLE_CACHE` do? If I run `process --dry-run` with this enabled, will it make the next call without `--dry-run` much faster?

**Comment by TomasVotruba** [comment]
It runs only on changed files since last run and their dependency tree.
