### ISSUE TITLE
disabled diff output

### ISSUE THREAD

**Issue by PartosK** [rectorphp/rector#5423]
# Question
Can you tell me how to disable the collection of information at all? this is an already time-consuming process, I don't want to waste resources on it too

now using output in json:
bin/rector process /var/www/source_code/src --no-progress-bar --output-file=/var/www/app/log_process.log --output-format=json

**Comment by TomasVotruba** [comment]
Hi,

try `--no-diffs` option: https://github.com/rectorphp/rector/pull/5368

**Comment by PartosK** [comment]
when is the next release planned with this option? @TomasVotruba

**Comment by TomasVotruba** [comment]
It's part of last release 6 days ago
