### ISSUE TITLE
[PHP 8] Don't promote properties with docblock annotations

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#5437]
| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Example

See https://getrector.org/demo/49c030f3-8c80-4f2e-8236-efd76ba4c54c

```php
<?php

/**
 * @ORM\Entity
 * @ORM\Table(name="UserActivity")
 */
class UserActivity
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue()
     * @ORM\Id
     */
    private ?int $id = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"persist"})
     * @ORM\JoinColumn(name="user_id", nullable=false, onDelete="CASCADE")
     */
    private User $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }
}
```

### Responsible rules

* `ArgumentAdderRector`

* `ClassPropertyAssignToConstructorPromotionRector`

* `UnionTypesRector`

## Expected Behavior
The property shouldn't be promoted, since it has essential annotations. In the above example, promoting one property doesn't make it more readable.

**Comment by TomasVotruba** [comment]
Hi, we'll need a demo link: https://getrector.org/demo

Property with annotations can be promoted, see https://wiki.php.net/rfc/constructor_promotion#reflection

**Comment by stephanvierkant** [comment]
Aha, you're right, this is not a bug! From a readability perspective, I don't see this example (https://getrector.org/demo/49c030f3-8c80-4f2e-8236-efd76ba4c54cs) as an improvement.

Maybe this behaviour (promote properties with docblock annotations) can be configurable? I'll update this issue accordingly.

**Comment by TomasVotruba** [comment]
The provided demo link leads to default example.

Ah, if it's undesired preference, just skip it for entities in `rector.php` with `SKIP` parameter.

**Comment by TomasVotruba** [comment]
```diff
-    /**
-     * @ORM\Column(type="integer")
-     * @ORM\GeneratedValue()
-     * @ORM\Id
-     */
-    private ?int $id = null;


+    public function __construct(
+         #[ORM\Column(type: 'integer')]
+         #[ORM\GeneratedValue]
+         #[ORM\Id]
+         private ?int $id = null;
+    )
```
