### ISSUE TITLE
Rector reports spaces as error on Windows

### ISSUE THREAD

**Issue by nelson6e65** [rectorphp/rector#5444]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.56             |
| Installed as   | composer dependency                           |
| OS | Windows |
| PHP| 7.2+|

I run a composer script to perform linting with Rector and is reporting error. The same codebase is failing on Windows but works fine on Linux.

[![alt text](https://uploads.disquscdn.com/images/28572e70e934b5a13121308252b24eca51fbb6b0e127df1020c7150a161f1c47.png)](https://tomasvotruba.com/blog/2019/11/18/how-to-delegate-code-reviews-to-ci/#comment-5240038972)

> Post: [how-to-delegate-code-reviews-to-ci](https://tomasvotruba.com/blog/2019/11/18/how-to-delegate-code-reviews-to-ci/#comment-5240038972)

**CI Workflow run:**
⛔  https://github.com/nelson6e65/rector-issue-ex/actions/runs/544525144

## Minimal PHP Code Causing Issue

Minimal reproduction repo: https://github.com/nelson6e65/rector-issue-ex/tree/4b6ab04b4d614579d37407a58842f57a35a07c2e

## Expected Behaviour

Simple spaces/lines should not be reported as error.

**Comment by TomasVotruba** [comment]
Hi,

the 0.8 is quite old. It's recommended to use 0.9 now. Be sure to upgrade first.
As for Windows, we don't have much Windows contributors, so we can't help with this. Are you willing to help with the bug?

**Comment by nelson6e65** [comment]
There is another way to install it? Or is required to be in the composer.json? Can I use it as a global installation?

I still use PHP 7.2, to generate documentation only, so I can't update rector 0.9 in my composer.json.

If this is an issue with WIndows only I can ignore it for now.

----
> Are you willing to help with the bug?

I don't know how to start 😅

**Comment by samsonasik** [comment]
@nelson6e65 you may can try with `--ignore-platform-reqs`:

```bash
composer update rector/rector:^0.9 --ignore-platform-reqs
```

and verify if it fixed in 0.9 version. If 0.9 fixed the issue, you may need to upgrade your php version to php 7.3+.

**Comment by nelson6e65** [comment]
@samsonasik I only use PHP 7.2 on CI to build the documentation for my library. I'm had not migrated to phpDocumentor 3, I'm still using 3.9, which is not compatible with PHP 7.3+.

Locally, I use PHP 7.4 (as the first image I attached). 

I'll try to upgrade to Rector 0.9 and use `composer install --ignore-platform-req=php` in my CI when PHP < 7.3.

**Comment by TomasVotruba** [comment]
Btw, there is PHP 7.1 compatible version: https://github.com/rectorphp/rector-php71

**Comment by nelson6e65** [comment]
This does not applies to 0.9. All works fine after the upgrade.

Ignoring platform allows me to run `composer install` on PHP 7.2, but not using Rector, which is fine. I just need to run `phpdoc`. Now I have to figure out how to customize the install command on Netlify. 😅

Thanks for your help. I was just using an old version.

**Comment by nelson6e65** [comment]
By the way: 

> There is another way to install it? Or is required to be in the composer.json? Can I use it as a global installation?

**Comment by TomasVotruba** [comment]
> There is another way to install it? Or is required to be in the composer.json? Can I use it as a global installation?

Global installation or any other proven to be very problematic. Rector is trying to work with the worst code possible, so the least requirement is to be installed as dependency with full access to autoloader.

So `composer install` is the only way to install it (reliably) :) 

<br>

I hope you manage to resolve your dependendencies to get to PHP 7.3.

> Btw, there is PHP 7.1 compatible version: rectorphp/rector-php71

How does this version work?

**Comment by nelson6e65** [comment]
> Btw, there is PHP 7.1 compatible version: rectorphp/rector-php71
> How does this version work?

It's the same problem. My library (https://github.com/nelson6e65/php_nml) is compatible with 7.2+. So I have will need to add `rectorphp/rector-php71` to my composer.json which will works on PHP 7.1 but will be unable to install on PHP 7.2+. So, I also require `rector/rector:^0.9` when running PHP 7.3. Does not conflict?

I just want to skip installation of Rector when using PHP 7.2 to build my documentation.

> Global installation or any other proven to be very problematic. So composer install is the only way to install it (reliably) :)

😓😓😓

Thanks for your help.

**Comment by TomasVotruba** [comment]
Oh, rector-php71 work on PHP 7.1-7.4

**Comment by nelson6e65** [comment]
I ended up by allowing Rector 0.8: 

https://github.com/nelson6e65/php_nml/blob/d060bf759a1591554234b93c801b32409796bd8c/composer.json#L33-L35

This allows me to use 0.9 to [check problems on my supported PHP versions](https://github.com/nelson6e65/php_nml/runs/1851246537?check_suite_focus=true#step:10:1) and [build the documentation with PHP 7.2 on Netlify without failing due to incompatible version](https://github.com/nelson6e65/php_nml/pull/57#issuecomment-774809444) (Rector is not necessary for this).

Thanks for your support! 😀
