### ISSUE TITLE
AnnotationToAttributeRector removes empty lines

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#5447]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/edb98391-fcaf-4f4b-941c-db7afb2a6127

```php
<?php
use Symfony\Component\Routing\Annotation\Route;

final class SomeController
{
    /**
     * @Route(
     *     path = "/foo",
     *     name = "foo",
     *     methods = {"POST"}
     * )
     */
    public function foo()
    {
        $foo = true;
        
        $bar = false;
    }
}
```

### Responsible rules

* `ArgumentAdderRector`

* `AnnotationToAttributeRector`

## Expected Behavior

Rector removes an empty line:

```
-        $foo = true;
-        
-        $bar = false;
+        $foo = true;
+        $bar = false;
```
This shouldn't be happening.

**Comment by TomasVotruba** [comment]
Hi, this is expected behavior. Coding style must be handled by your coding standard tool.

See
https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by stephanvierkant** [comment]
Sorry, I don't understand what you mean. Why does Rector remove those lines?

**Comment by TomasVotruba** [comment]
See the linked https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by stephanvierkant** [comment]
I've read that and I'm using ECS. But ECS can't add those removed lines, isn't it?

**Comment by TomasVotruba** [comment]
If it's not in ECS yet, you need to provide your own rule. 
There is not much I can add over the link.

**Comment by stephanvierkant** [comment]
Sorry, I'm afraid you don't understand what I mean.

With `AnnotationToAttributeRector`, the line is removed. I don't see why.

**Comment by TomasVotruba** [comment]
I understand that. It's a side effect of AST changes. The reprint to the original content is not always 100 %. It's limitation of technology itself. This is in the linked content.

This will happen accidentaly for many changes in AST nodes, unrelated to any specific rule.

You can read more about it here: https://github.com/nikic/PHP-Parser/issues/344

**Comment by stephanvierkant** [comment]
Ok, thanks for clarifying!

It didn't expect the body to be touched in the first place, since the body seems to be unrelated to this rector . That's why I thought it might be another problem.

**Comment by TomasVotruba** [comment]
@svitiashchuk Thank you for sharing this exact solution. I'll definitely use it soon in refactoring that I make with Rector :+1:

**Comment by algimantas** [comment]
It would be really nice if AnnotationToAttributeRector would not touch function body.

**Comment by samsonasik** [comment]
@algimantas most of the line removal from `AnnotationToAttributeRector` is solvable by `NewlineAfterStatementRector` rule by add new line on most common usage of new line after stmts registered 

https://github.com/rectorphp/rector-src/blob/93030d3ef7bdf94769d3ea5c8b7d15fe9fb99658/rules/CodingStyle/Rector/Stmt/NewlineAfterStatementRector.php#L43-L59

**Comment by smilesrg** [comment]
@samsonasik could you modify the `AnnotationToAttributeRector` to not touch empty lines to not mess with solutions like this? https://github.com/rectorphp/rector/issues/5447#issuecomment-1105402840

**Comment by raziel057** [comment]
@svitiashchuk I tried the solution proposed here https://github.com/rectorphp/rector/issues/5447#issuecomment-1105402840 but the patch (git apply -v --unidiff-zero no-removed-blank-lines.patch) only applies on the first route of each class.

**Comment by raziel057** [comment]
@svitiashchuk It's cause by the perl transformation as the different ``@@ -24,4 +22 @@ class BrandController extends ImportController`` are lost (maybe related to my version)
```
perl -v

This is perl 5, version 26, subversion 3 (v5.26.3) built for i686-cygwin-threads-64int-multi
(with 7 registered patches, see perl -V for more detail)
```

**Comment by raziel057** [comment]
If I remove the perl part, I have the following result:

```diff
diff --git a/src/PTC/AdminBundle/Controller/Import/BrandController.php b/src/PTC/AdminBundle/Controller/Import/BrandController.php
index 433a3879..9a8ed902 100644
--- a/src/PTC/AdminBundle/Controller/Import/BrandController.php
+++ b/src/PTC/AdminBundle/Controller/Import/BrandController.php
@@ -13 +12,0 @@ use Symfony\Component\Routing\Annotation\Route;
- * @Route("/secured/transport/brand/import")
@@ -14,0 +14 @@ use Symfony\Component\Routing\Annotation\Route;
+#[Route(path: '/secured/transport/brand/import')]
@@ -17,3 +17 @@ class BrandController extends ImportController
-    /**
-     * @Route("/get/fields", name="brand_import_get_field_definitions", methods={"POST"})
-     */
+    #[Route(path: '/get/fields', name: 'brand_import_get_field_definitions', methods: ['POST'])]
@@ -24,4 +22 @@ class BrandController extends ImportController
-
-    /**
-     * @Route("/get/import/file", name="brand_import_get_file", methods={"POST"})
-     */
+    #[Route(path: '/get/import/file', name: 'brand_import_get_file', methods: ['POST'])]
@@ -32,4 +27 @@ class BrandController extends ImportController
```

**Comment by raziel057** [comment]
As a minimal reproducer, you can just get the file in the following zip and try to run the perl command:

[no-removed-blank-lines.zip](https://github.com/rectorphp/rector/files/8753259/no-removed-blank-lines.zip)

```
cat no-removed-blank-lines.patch | perl -0 -pwe "s/@@.+\n\-\n//g" > test.diff
```

**Comment by TomasVotruba** [comment]
Repository would be better, as we'll need to make it work online first. Otherwise we can get to "works on my machine" situation.
