### ISSUE TITLE
CorrectDefaultTypesOnEntityPropertyRector throws error with null default value for integer doctrine entity field

### ISSUE THREAD

**Issue by runawaycoin** [rectorphp/rector#5454]
# Question
Not sure if this is a bug / not catered for yet or I'm doing something wrong?

When using the `CorrectDefaultTypesOnEntityPropertyRector` i'm hitting the `NotImplementedYetException` inside `refactorToIntType` with the following Doctrine Entity code. Its due to the null default value.

```
 /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $myInt = null;
```

The error i get is:

```
[ERROR] Could not process "src/Entity/MyEntity.php" file by                                                            
         "Rector\DoctrineCodeQuality\Rector\Property\CorrectDefaultTypesOnEntityPropertyRector", due to:                
         "".                                                                                                            
                 
```

**Comment by TomasVotruba** [comment]
Hi, we'll need a failing demo link to have context: https://getrector.org/demo

**Comment by runawaycoin** [comment]
Hi,

Great tool, sorry i didn't use this in my initial post.

I think this is reproducing it:
https://getrector.org/demo/3b637639-ed29-4fd9-941c-caf89cb9bf22

Thanks.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by TomasVotruba** [comment]
We've just switch to a custom static doctrine annotation parser, where this issues should be resolved.

https://github.com/rectorphp/rector/pull/5974
