### ISSUE TITLE
Make sets fix deprecations

### ISSUE THREAD

**Issue by berezuev** [rectorphp/rector#5455]
# Feature Request

Currently rule sets fix logic that have already changed. So, if we update e.g. Symfony 2.8 -> 3.0, we need to make huge PR.
Its hard to review and test. But if we do some preparatory work we can check it and then just do `composer update symfony/symfony:~3.0` in separate PR.
Second advantage is that we fix dozens of annoying deprecation notices in logs and profiler. 

What about rearranging sets in favor of fixing deprecates? For example, we can move `Symfony\Component\ClassLoader\UniversalClassLoader\UniversalClassLoader`, `Symfony\Component\HttpKernel\Log\LoggerInterface` and some other changes from symfony30 to symfony28 rule.
Or we can run them in both sets to save BC.

**Comment by TomasVotruba** [comment]
PHP sets are actually designed this way. Promoted properties are used since PHP 8, even though old form off property assign works.

So I agree with you :+1:
