### ISSUE TITLE
[DeadCode] Remove check exact value instanceof on type hinted ClassMethod

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#5458]
# Feature Request

To remove unneded check same exact value instanceof like the following code:

https://github.com/rectorphp/rector/blob/e9cdf37d160ea7dab2a7662c95508ec2d1db2988/rules/renaming/src/Rector/MethodCall/RenameMethodRector.php#L125-L131

The `$classMethod` is a `ClassMethod`, no need to check if `$classMethod` is a `ClassMethod`

**Comment by TomasVotruba** [comment]
That makes sense :+1:
