### ISSUE TITLE
Incorrect behavior of JsonThrowOnErrorRector

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#5462]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/22986871-208b-4f73-a1f3-21d9d11115a4

```php
<?php

final class DemoFile
{
    public function run() : array
    {
        $campaigns = json_decode($input['campaigns'] ?? '', true) ?? [];
        
        return $campaigns;
    }
}
```

### Responsible rules

* `JsonThrowOnErrorRector`

## Expected Behavior

Rector should skip this because there is a `?? []` fallback that is used when `json_decode` returns false.

**Comment by TomasVotruba** [comment]
Thanks for report!

We'll need a failing test case for this one

**Comment by ruudk** [comment]
My example is wrong anyway.... it uses the Null Coalescing Operator `??` which only falls back when the left side is `null`. 

That means that the fallback is not meant to handle the `json_decode` error.

But when I change it to use the Ternary Operator `?:` the result is the same.

I will create a test for that.

**Comment by TomasVotruba** [comment]
Closing as there is no need anymore: https://github.com/rectorphp/rector/pull/5469#issuecomment-779659279
