### ISSUE TITLE
[Php7.1 Scoped] Make run all the tests

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5471]
See https://github.com/rectorphp/rector-php71/pull/1/files

The repository is build and deployed here, in `rector/rector`: https://github.com/rectorphp/rector/blob/9f6834c46ea7599446dce808d21a069a4a6a9189/.github/workflows/build_php71.yaml#L12-L105

<br>

## The Downgrade Scripts

- https://github.com/rectorphp/rector/blob/master/.github/workflows/scripts/downgrade_packages.sh
- If you find a way to simplify it any way, go for it :+1: It would help us to maintain it and use it

<br>

## How to modify the `rectorphp/rector-php71`? 

- not directly, just test is there, but the repository is deployed from here so any work will be overriden
- the workflow code is copied from https://github.com/rectorphp/rector/tree/master/ci/downgrade/target-repo - modify these files

## Tasks

- [ ] merge downgrade configs to single 1 - @TomasVotruba

**Comment by samsonasik** [comment]
@TomasVotruba I don't have write permission access to `rector/rector-php71` repository:

```
➜  rector-php71 git:(testing) git push origin testing
ERROR: Permission to rectorphp/rector-php71.git denied to samsonasik.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Could you add me to allow write access to `rector/rector-php71` repository for testing? Thank you.

**Comment by TomasVotruba** [comment]
@samsonasik Done :heavy_check_mark:

**Comment by samsonasik** [comment]
Thank you,  @TomasVotruba I added require/dev and autoload/dev into composer.json in rector/rector-php71, currently got:

```
PHP Fatal error:  Class 'Symplify\PackageBuilder\Testing\AbstractKernelTestCase' not found in /home/runner/work/rector-php71/rector-php71/packages/testing/src/PHPUnit/AbstractRectorTestCase.php on line 43
5
Error: Process completed with exit code 255.
```

It seems packages need to be added to autoload ?

**Comment by samsonasik** [comment]
@TomasVotruba symplify/package-builder seems already require php 7.2 since version `7.0.0`, and class `Symplify\PackageBuilder\Testing\AbstractKernelTestCase` seems not exists yet in version `6.0.0`, any idea?

**Comment by TomasVotruba** [comment]
That's ok. There packages have to be downgraded in the build workflow here.

**Comment by samsonasik** [comment]
@TomasVotruba is that means the package need to be registered at https://github.com/rectorphp/rector/blob/master/ci/downgrade/composer.json ?

**Comment by TomasVotruba** [comment]
@samsonasik That's one of places it could be, yes. At least during build step, the final version can be without it.

**Comment by samsonasik** [comment]
@TomasVotruba using wget for phpunit 7 means we back to the first issue, other dev-dependencies require php 7.3, how to register the dev dependencies, eg: symplify/astral to downgrade version as the workflow is removing the `dev` require ?

**Comment by TomasVotruba** [comment]
The dev dependencies must be downgraded too. Whole vendor + our code must pass on PHP 7.1 linter.

**Comment by samsonasik** [comment]
@TomasVotruba could you give hint where the `dev` depencencies need to be registered in the script? Thank you.

**Comment by TomasVotruba** [comment]
I'm not sure, as I didn't write the script. I would have to go through it in detail and I need to do another work.

**Comment by samsonasik** [comment]
Ok, thank you 👍

**Comment by TomasVotruba** [comment]
Covered in https://github.com/rectorphp/rector-prefixed/tree/main/.github/workflows
