### ISSUE TITLE
Docs > rector_rules_overview.md > Add link to rector source

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#5476]
The [rector_rules_overview.md](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md) overview is great to discover new rules. 

It would be great if there was a link to the rector source that points to `rules/%class%.php`.

This makes it easier to read more about the rector and to see if edge cases are handled.

**Comment by TomasVotruba** [comment]
That would be great indeed :+1: 

This is the package responsible for the documentation:
https://github.com/symplify/rule-doc-generator
