### ISSUE TITLE
Rule to change argument?

### ISSUE THREAD

**Issue by strarsis** [rectorphp/rector#5491]
# Question
Is there an existing Rector rule to simply change an argument of a function of given name?
Example:
```php
__( 'some string', 'domain' );
````
All functions with the name `__` should be selected and the 2nd argument `domain` should be changed to something else, e.g. `newdomain`:

```diff
-__( 'some string', 'domain' );
+__( 'some string', 'new domain' );
```

If there is no rule for this yet, what rule comes closest to this or how can I implement a rule like this with least amount of extra code?

**Comment by sabbelasichon** [comment]
`php`
<?php
declare(strict_types=1);


namespace Ssch\TYPO3Rector\Rector\Functions;


use PhpParser\Node;
use PhpParser\Node\Expr\FuncCall;
use PhpParser\Node\Scalar\String_;
use Rector\Core\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

final class FromDomainToNewDomainRector extends AbstractRector
{
    public function getNodeTypes(): array
    {
        return [FuncCall::class];
    }

    /**
     * @param FuncCall $node
     */
    public function refactor(Node $node): ?Node
    {
        if(!$this->isName($node->name, '__')) {
            return null;
        }

        if(!$this->valueResolver->isValue($node->args[1]->value, 'domain')) {
            return null;
        }

        $node->args[1]->value = new String_('new domain');

        return $node;
    }

    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('Convert second argument of function __ with value domain to new_domain', [new CodeSample(<<<'PHP'
__( 'some string', 'domain' );
PHP
            , <<<'PHP'
__( 'some string', 'new domain' );
PHP
        )]);
    }

}

**Comment by strarsis** [comment]
@sabbelasichon: Awesome! Thanks! Would it make sense to add this rule to Rector core?

**Comment by TomasVotruba** [comment]
@sabbelasichon I think there is no rule like that yet.

@strarsis It might be useful. It's important to define a generic API use case:

- How would you configure it?
- What are the practical use cases?

**Comment by strarsis** [comment]
@TomasVotruba: WordPress base theme Sage. It uses `sage` as translation domain. Search and replace of just the string `sage` would not work as that string is also used for other purposes. Replacing all those strings would result in errors.

**Comment by TomasVotruba** [comment]
:+1: 

How would you configure it - PHP code config? For example, this is how we configure class rename: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#renameclassrector

**Comment by strarsis** [comment]
@ThomasVotruba: The theme is created by using `composer create-project`. That Rector rule usually only runs once at the very beginning to re-assign all existing default translation domains to something the developer can enter. So as a CLI tool that asks for the new translation domain.

**Comment by TomasVotruba** [comment]
I see. That looks more like a job for PHPStorm refactoring, then pattern refactoring for Rector.

Personaly I would use the solution @sabbelasichon proposed above: https://github.com/rectorphp/rector/issues/5491#issuecomment-777028447

Or PHPStorm pattern replace:

![image](https://user-images.githubusercontent.com/924196/108169964-c2a9af00-70f9-11eb-86b0-79fe1aa256cb.png)

```bash
// input
__\((\s+)?\'some string\'(\s+)?,(\s+)?\'(domain)\'(\s+)?\)\;

// output
__\(\'some string\', 'new_domain\'\)\;
```

![Peek 2021-02-17 08-26](https://user-images.githubusercontent.com/924196/108170082-ed940300-70f9-11eb-8f21-22860bde8f53.gif)
