### ISSUE TITLE
MoveRepositoryFromParentToConstructorRector not working for ServiceEntityRepository

### ISSUE THREAD

**Issue by TavoNiievez** [rectorphp/rector#5495]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.20                                                          |
| Installed as   | composer dependency                                             |

Referring to [the article](https://getrector.org/blog/2021/02/08/how-to-instantly-decouple-symfony-doctrine-repository-inheritance-to-clean-composition#comment-5262026808): *"How to Instantly Decouple Symfony Doctrine Repository Inheritance to Clean Composition"*,

When I try to run that Rector, this step: `MoveRepositoryFromParentToConstructorRector::class` doesn't work if the repository extends from the class `Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository` .

## PHP Code Causing Issue

Sorry to share the full class instead of a minified version, but I think in this case it's important to know that the Rector does both well.

```php
<?php

declare(strict_types=1);

namespace App\Person\User\Infrastructure\Repository\Doctrine;

use App\Person\User\Domain\Model\User;
use App\Person\User\Domain\Repository\UserRepositoryInterface;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Security\Core\User\PasswordUpgraderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

final class UserRepository extends ServiceEntityRepository implements UserRepositoryInterface, PasswordUpgraderInterface
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, User::class);
    }

    public function save(User $user): void
    {
        $this->_em->persist($user);
        $this->_em->flush();
        $this->_em->clear();
    }

    public function findOneByEmail(string $email): ?object
    {
        return $this->findOneBy([
            'email' => $email
        ]);
    }

    /** @param User $user */
    public function upgradePassword(UserInterface $user, string $newEncodedPassword): void
    {
        $user->setPassword($newEncodedPassword);
        $this->_em->flush();
    }

    public function deleteByEnabled(): void
    {
        foreach ($this->findByEnabled(false) as $inactiveUser) {
            $this->_em->remove($inactiveUser);
        }
        $this->_em->flush();
    }

    /** @return User[] */
    public function findByEnabled(bool $enabled): array
    {
        return $this->findBy([
            'enabled' => $enabled
        ]);
    }

    public function findOneById(int $id): ?object
    {
        return $this->find($id);
    }

    public function findByPasswordRequestToken(): ?array
    {
        $query = $this->_em->createQuery('SELECT u FROM App\Person\User\Domain\Model\User u WHERE u.passwordRequestToken != ?1');
        $query->setParameter(1, '');
        return $query->getResult();
    }
}

```
## Expected Behaviour

I'm not sure of the expected behaviour because I tried to do the refactor manually without succeeding...

## Additional considerations

When I tried to do it just the `$this->` blocks were replaced.

The calls to the entityManager `$this->_em` were not replaced.

Also, by default class: `Doctrine\ORM\EntityRepository` is injected instead of interface. And in my app I get an error telling me that this service does not exist...

So I tried doing something like the following...:

```php
# PHP 8.0

final class UserRepository implements UserRepositoryInterface
{
    private ObjectRepository $userRepository;

    public function __construct(private EntityManagerInterface $entityManager)
    {
        $this->userRepository = $entityManager->getRepository(User::class);
    }

	//...
}
```

But doing that my tests fail for 'exceeded nesting level, xdebug stopped execution'.

Probably due to a circular dependency problem.

Since in my mapping, the repository class is the same:

```xml
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping">
    <entity name="App\Person\User\Domain\Model\User" table="users" repository-class="App\Person\User\Infrastructure\Repository\Doctrine\UserRepository">
        <id name="id" type="integer">
            <generator/>
        </id>
    </entity>
	// fields...
</doctrine-mapping>
```
So `->getRepository` tries to get the same class over and over again.

I know I am describing various issues but it was what I got when trying to make this refactor.

**Comment by TomasVotruba** [comment]
I'm looking into it right now. Thanks for the clear report :+1:

**Comment by TomasVotruba** [comment]
> But doing that my tests fail for 'exceeded nesting level, xdebug stopped execution'.

This is because your entity is referencing the repository. So when you look for a repository, it will look for the entity with that repository, which will look for a repository, which will look for an entity with that repository...

This change si also covered by this set. In particular:

```diff
/**
- * @ORM\Entity(repositoryClass="Rector\DoctrineCodeQuality\Tests\Set\DoctrineRepositoryAsServiceSet\Fixture\SomeEntityRepository")
 */
+ * @ORM\Entity()

class Some
{
}
```

**Comment by TomasVotruba** [comment]
I've just pushed couple of fixes for your issue in https://github.com/rectorphp/rector/pull/5540

Could you re-try on `dev-master` and let me know, how it works for you?
