### ISSUE TITLE
RenameClassRector doesn't work when PHPUNIT_60 and PHPUNIT_70 sets are enabled together

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#5496]
# Bug Report

I ran into a very weird issue. The `RenameClassRector` doesn't work when both `PHPUNIT_60` and `PHPUNIT_70` are enabled. When only enabling one of the two, it works. When removing both, it works. 🤯 

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest              |
| Installed as   | prefixed Rector                           |

## Minimal PHP Code Causing Issue

:x: Both sets enabled: https://getrector.org/demo/a86c11df-eef0-4ff2-af96-2a4651ad6a51
✅  Only PHPUNIT_60 set enabled: https://getrector.org/demo/bb129f1f-2897-4fdf-9ae8-b4ae1f38c3ee
✅  Only PHPUNIT_70 set enbled: https://getrector.org/demo/10e90400-1473-4f84-a1b6-d42f930fe3a6
✅  No sets enabled: https://getrector.org/demo/687214ff-ae83-4ffb-92bf-d67288b32fe1

## Expected Behaviour

It should change my code

**Comment by ruudk** [comment]
It's probably because they use the `RenameClassRector` too. Does that mean that after using the sets, you should remove them? And that calling `$services->set(RenameClassRector::class)->call('configure', [[]])` does not work when it's already done? Or are the sets maybe executed afterwards and do they overwrite my configure?

**Comment by TomasVotruba** [comment]
This might be similar to: https://github.com/rectorphp/rector/issues/5490

The configuration for `'configure'` should merge from all the used configs.

This is responsible compiler pass:
`Rector\Core\DependencyInjection\CompilerPass\MergeImportedRectorConfigureCallValuesCompilerPass`

**Comment by OskarStark** [comment]
IMHO `$services->set(RenameClassRector::class)->call('configure', [[]])` this call would force it to an empty array via

`$this->oldFunctionToNewFunction = $configuration[self::OLD_FUNCTION_TO_NEW_FUNCTION] ?? [];`

What about? (currently untested), but will check when back:

```diff
-        $this->oldFunctionToNewFunction = $configuration[self::OLD_FUNCTION_TO_NEW_FUNCTION] ?? [];
+        $this->oldFunctionToNewFunction = array_merge(
+            $this->oldFunctionToNewFunction,
+            $configuration[self::OLD_FUNCTION_TO_NEW_FUNCTION] ?? []
+        );
```

**Comment by ruudk** [comment]
The call with empty array was just a short example. It's not what I used in the demo, see url. Sorry for confusion.

**Comment by OskarStark** [comment]
Doesn't matter as the property is set, new bales needs to merged IMHO

Can you try if this fixes the issue?

**Comment by ruudk** [comment]
First I'm going to write a failing test and then start debugging it.

I assume this happens for all configure calls, right?

**Comment by OskarStark** [comment]
It looks like kn my referenced PR it is the same method which causes problems.

I would say all configure calls yes. Maybe only the ones with nested arrays? Because it would need a deep recursive merge 🧐

**Comment by OskarStark** [comment]
0.9.21 was released a few minutes ago, maybe it's worth double testing it

**Comment by ruudk** [comment]
I tried with 0.9.21 and the same problem exists.

**Comment by ruudk** [comment]
Created a failing test to show what's going wrong: https://github.com/rectorphp/rector/pull/5502

**Comment by samsonasik** [comment]
It seems already fixed https://getrector.org/demo/da7fdc50-89b7-4f8f-ba82-47554c3b1b8c

Closing.
