### ISSUE TITLE
NotYetImplemented exception in RemoveUnusedPrivatePropertyRector

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#5501]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.21           |
| Installed as   | prefixed Rector                           |

When using the `RemoveUnusedPrivatePropertyRector` I get a `NotYetImplemented` exception thrown.

## Minimal PHP Code Causing Issue
https://getrector.org/demo/44198f3b-044d-4f56-9a1b-f3ae933cc203

## Expected Behaviour
Delete the unused private property.

**Comment by olivernybroe** [comment]
@TomasVotruba I wouldn't mind creating a failing test, however I have no idea what to call the test file 🤣 
Not completely sure why it is failing.

**Comment by TomasVotruba** [comment]
It seems there is magic property :) so `remove_magic_property.php.inc`?

**Comment by olivernybroe** [comment]
Awesome! Hopefully the bad legacy file in our project with a lot of dead code can run now :D 

It's a pretty good file for finding really edge cases in rector 🤣

**Comment by TomasVotruba** [comment]
The worse the better 😜
