### ISSUE TITLE
Nette 3.1 Renaming class Template

### ISSUE THREAD

**Issue by stanislav-janu** [rectorphp/rector#5519]
Hi,

this rule is problematic, because DefaultTemplate is final class and can not be extended.
https://github.com/rectorphp/rector/blob/fb1bf1f5542c06202b5b932ba2428b98688d0ede/config/set/nette-31.php#L39

Rector do this:
```
app/Presenters/BaseTemplate.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
 use App\Model\Menu\MenuIterator;
 use Nette;

-class BaseTemplate extends Nette\Bridges\ApplicationLatte\Template
+class BaseTemplate extends \Nette\Bridges\ApplicationLatte\DefaultTemplate
 {
        public Nette\Security\User $user;
        public string $baseUrl;
    ----------- end diff -----------


Applied rules:

 * Rector\Renaming\Rector\Name\RenameClassRector
```

Or am I doing something wrong?

Thanks.

**Comment by TomasVotruba** [comment]
Hi,

that should not happen. What is the expected change?

**Comment by stanislav-janu** [comment]
I think, that is correct: `class BaseTemplate extends Nette\Bridges\ApplicationLatte\Template`. 

Latte needs interface `Nette\Application\UI\Template`. That is implemented only in `Nette\Bridges\ApplicationLatte\Template`. Rector rewrite this to `Nette\Bridges\ApplicationLatte\DefaultTemplate` and `DefaultTemplate` is final class and there is fatal error.

Yes, I can implement interface `Nette\Application\UI\Template`, but there is required write methods `render()`, `setFile()` and `getFile()`. Not comfortable.

Solutions:
* Make DefaultTemplate extendable.
* Or remove rule from rector.

My settings:
```
	$parameters->set(Option::SETS, [
		SetList::PHP_74,
		SetList::CODE_QUALITY,
		SetList::NETTE_CODE_QUALITY,
		SetList::NETTE_UTILS_CODE_QUALITY,
		SetList::NETTE_RETURN_TYPES,
		SetList::NETTE_PARAM_TYPES,
		SetList::NETTE_31,
	]);
```

**Comment by lulco** [comment]
I vote for non-final DefaultTemplate

**Comment by TomasVotruba** [comment]
The non-final `DefaultTempalte` must be solved in Nette itself.

**Comment by lulco** [comment]
Yes, or we could use parent class of DefaultTemplate but it doesn’t contain properties like presenter, flashes etc. But I still prefer DefaultTemplate

**Comment by TomasVotruba** [comment]
So what do you suggest to do now?

**Comment by stanislav-janu** [comment]
My opinion is: DefaultTheme is used if I do not have any self-made variant. DefaultTemplate is not specified for extensions. Programmer have two options. Do not use Templates and there will be used DefaultTemplate. Or write own Template extends `Nette\Bridges\ApplicationLatte\Template`.

Solution: Not rewrite `Nette\Bridges\ApplicationLatte\Template` to  `Nette\Bridges\ApplicationLatte\DefaultTemplate `.

Maybe @dg can help with explanation right usage? :-)

**Comment by lulco** [comment]
Yes it makes sense. But then we have to add these lines to all our custom templates right? 


	/** @var Nette\Application\UI\Presenter */
	public $presenter;

	/** @var Nette\Application\UI\Control */
	public $control;

	/** @var Nette\Security\User */
	public $user;

	/** @var string */
	public $baseUrl;

	/** @var string */
	public $basePath;

	/** @var \stdClass[] */
	public $flashes = [];

**Comment by TomasVotruba** [comment]
@stanislav-janu 

> Solution: Not rewrite Nette\Bridges\ApplicationLatte\Template to Nette\Bridges\ApplicationLatte\DefaultTemplate .

That's a good idea, at least for `extends` where it causes fatal error.

Are there another places where use of `Nette\Bridges\ApplicationLatte\DefaultTemplate` causes troubles?

**Comment by stanislav-janu** [comment]
> Yes it makes sense. But then we have to add these lines to all our custom templates right?
> 
> ```
> /** @var Nette\Application\UI\Presenter */
> public $presenter;
> 
> /** @var Nette\Application\UI\Control */
> public $control;
> 
> /** @var Nette\Security\User */
> public $user;
> 
> /** @var string */
> public $baseUrl;
> 
> /** @var string */
> public $basePath;
> 
> /** @var \stdClass[] */
> public $flashes = [];
> ```

I do same thing as BasePresenter. I make BaseTemplate with globals and others inherit it.

**Comment by stanislav-janu** [comment]
> @stanislav-janu
> 
> > Solution: Not rewrite Nette\Bridges\ApplicationLatte\Template to Nette\Bridges\ApplicationLatte\DefaultTemplate .
> 
> That's a good idea, at least for `extends` where it causes fatal error.
> 
> Are there another places where use of `Nette\Bridges\ApplicationLatte\DefaultTemplate` causes troubles?

I know only about `extends`.
