### ISSUE TITLE
Fully qualified name of function is imported as use instead of use function

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#5521]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@45caffd)              |
| Installed as   | git clone                           |

I am trying to add some lines to my deploy.php (using https://github.com/deployphp/deployer). I wrote my own rector which do that, but when I turn on AUTO_IMPORT_NAMES, function Deployer\set is moved to imports like it is class, so I have:
```
use Deployer\set;
use function Deployer\set;
```
instead of
```
use function Deployer\set;
```

## Minimal PHP Code Causing Issue
Failing test case https://github.com/rectorphp/rector/pull/5520

## Expected Behaviour
Functions are imported as `use function`

**Comment by TomasVotruba** [comment]
Do you have both statements imported?

```bash
use Deployer\set;
use function Deployer\set;
```

The function must be autoloaded, otherwise there is no way to find out if it's function or class.

**Comment by lulco** [comment]
I think yes, see failing test case. When it was not loaded it throws na error that it is not loaded so I add some require and then it acts like in my project.

**Comment by TomasVotruba** [comment]
I see, I'll look into it :+1: Thanks for the PR

**Comment by lulco** [comment]
> Do you have both statements imported?

I read it again and you probably asked if both statements were added by rector at the same time. Then: no. Only `use Deployer\set;` was added. `use function Deployer\set;` was already there before rectoring

> The function must be autoloaded, otherwise there is no way to find out if it's function or class.

I'm interesting in this statement. Why function must be autoloaded? If there is `something()` in code, it is always a function. Unless it is a constructor, but there have to be `new` keyword. Or am I missing something?

**Comment by TomasVotruba** [comment]
I thought I've replied this, but I can't see my comment. I'm sorry for delayed reply.

> I'm interesting in this statement. Why function must be autoloaded? If there is something() in code, it is always a function. Unless it is a constructor, but there have to be new keyword. Or am I missing something?

That's how it works now, but it can be improved as you suggest.

This is the line that decides that unimported function that does not exists is treated as a class: https://github.com/rectorphp/rector/blob/59e1063b50b9271e5c7059c210049b8b1f8bafa8/rules/coding-style/src/Node/NameImporter.php#L212-L232

The method could be split into 2 and check for function node in "If there is something() in code, it is always a function" way

**Comment by lulco** [comment]
Yes, you did in PR with failing test for this issue. No problem for delay, I will have at least two months of vacation (almost fully without computer) so I can’t implement it now.

**Comment by TomasVotruba** [comment]
No problem :+1: That sounds cool :open_mouth:  Where you heading for early summer? :sunglasses:

**Comment by lulco** [comment]
Haha nothing like that. Second baby will born soon, so I will be full-time father for first one :)

**Comment by TomasVotruba** [comment]
Oh, congrats and have fun! That's million times better than any vacation :tada:

**Comment by samsonasik** [comment]
It seems fixed by https://github.com/rectorphp/rector/pull/5755
