### ISSUE TITLE
[Docker] Build of docker is failing for unknown reason

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5522]
![image](https://user-images.githubusercontent.com/924196/107799603-ea95bd00-6d5d-11eb-801b-c65391b40dcb.png)

See https://github.com/rectorphp/rector/runs/1888924456

---

It's happening since https://github.com/rectorphp/rector/commit/47354793691c35d27365b43b0aae33a939ba75d2, but randomly.
Another commit next day passed it green.

Now I have to restart the build (5 times so far) and it still does not get through. No idea what is going on.

@JanMikes Could you help? :)

**Comment by JanMikes** [comment]
Hi, will look into it ;)

**Comment by JanMikes** [comment]
Closing as seems to be fixed via #5531
