### ISSUE TITLE
Consider changing isCandidate() to Node class subsriber

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#553]
Since PHP_CodeSniffer, PHP CS Fixer and PHPStan use the same approach: https://github.com/spaze/phpstan-disallowed-calls/blob/master/src/MethodCalls.php

And its not often clear where to put condition and "active..." helper properties are used.

Early returns might work better and also faster, due to only token subscription.

**Comment by TomasVotruba** [comment]
@carusogabriel What do you think about this?

 Would you take this one? Its pretty much just code cleanup

**Comment by carusogabriel** [comment]
@TomasVotruba So, you're suggesting to combine our `isCandidate` + `refactor` into a `processCandidate`, for example?

> Early returns might work better and also faster, due to only token subscription.

"only token subscription" what this means? Where can I study it? :)

**Comment by TomasVotruba** [comment]
Subscriber mean there is method, that tells what to listen to.
In this context a node type, see: https://github.com/spaze/phpstan-disallowed-calls/blob/51a791847d4d8e61d0479b9ee92c42c40058113e/src/MethodCalls.php#L49

In example:

### Before

```php
class SomeRector ...
{
	public function isCandidate(Node $node): bool
	{
		// part A
	}

	public function refactor(Node $node): Node
	{
		// part B
	}
}
```

### After

```php
class SomeRector ...
{
	public function getNodeType(): string
	{
		return Class_::class;
	}

	public function refactor(Node $node): Node
	{
		// part A
		// part B
	}
}
```

**Comment by carusogabriel** [comment]
> I can also change one Rector as an example, it would be more claer

If you can, please. Also, how this is gonna help us in performance? Just asking, before starting this giant change :)

**Comment by TomasVotruba** [comment]
> How this is gonna help us in performance?

Well, at the moment ever `isCandidate()` method in active Rector is invoked on every node.

So let's say there is 400 nodes in one file and just one of them is `Class_`.
With old approach, `isCandidate()` is called 400 times.

With new approach, **it would be just once** for the `Class_` node.

**Comment by carusogabriel** [comment]
@TomasVotruba I see the performance :warning: 


> I can also change one Rector as an example, it would be more claer

Please, do it, so I can reproduce and fix all Rectors
