### ISSUE TITLE
[RemoveUnusedConstructorParamRector] Broken behaviour with php8 constructor property promotion and empty body

### ISSUE THREAD

**Issue by dvapelnik** [rectorphp/rector#5533]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.27 |
| Installed as   | composer dependency                          |

```diff
--- Original
+++ New
@@ @@
      */
     private const TABLE_NAME = 'storage';

-    public function __construct(
-        private Connection $connection
-    ) {
+    public function __construct()
+    {
     }

     public function add(UuidInterface $id): void
```

https://getrector.org/demo/d4666d60-65d4-4fac-9b0f-fdb50601a84a

## Expected Behaviour

Constructor property promotion should be present after fixing because it used in methods

**Comment by dvapelnik** [comment]
As I see #5533 is already released and tagged with v0.9.28 but after updating the same buggy behavior still present

**Comment by samsonasik** [comment]
I can reproduce at https://getrector.org/demo/050186a3-dce7-4f10-9e12-f13fe0a247dc , probably try dev-master.

**Comment by dvapelnik** [comment]
I have removed `vendor` directory and `composer.lock` file and reinstall all dependencies with `minimum-stability: dev` (`rector/rector (dev-master 1fce3e0)` used) and no errors found on checking code with `rector/rector`.

Then I have removed my changes back (minimum stability and version of `rector/rector` to `^0.9.10` (`v0.9.28` actually used)) and reinstalled dependencies again. In this stack, I have buggy behavior again. Maybe this fix does not include in the fresh version `v0.9.28` yet?

**Comment by samsonasik** [comment]
Yes, still in `dev-master`: https://github.com/rectorphp/rector/commit/c910b262531cc3e1e02725bf7fbe374b72fe4354
The released version is previous commit: https://github.com/rectorphp/rector/commit/cd5cc8e12e98f6ed0a9378f7b40475441aefebfd

You can wait for next release or use `dev-master` for now.

**Comment by dvapelnik** [comment]
@samsonasik thanks for the answer
yes, I will wait for the next release and will skip this check on my project
thank you!
have a nice day!
