### ISSUE TITLE
RemoveUnreachableStatementRector removes function content after exit() or return

### ISSUE THREAD

**Issue by addshore** [rectorphp/rector#5571]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.29              |
| Installed as   | composer dependency                          |

RemoveUnreachableStatementRector removes code that is not actually dead when functions are declared below an `exit()`

## Minimal PHP Code Causing Issue

I couldn't reproduce in the tool, maybe because an `exit()` call is needed?
The code I had reproduced this with was https://gist.github.com/addshore/d46bfacbecc932957d332df1438ed3e4
I imagine a minimal reproducion would be

```php
<?php
foo();
exit(0);
function foo(){
    echo "foo";
}
```

This can be seen to not be dead code https://3v4l.org/C8eDS

The set for reproduction would be the dead code set.

```php
    $parameters->set(Option::SETS, [SetList::DEAD_CODE]);
```

## Expected Behaviour

I would not expect the foo method, or methods declared after the `exit()` to be removed as they will be read by PHP already.

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting.
We'll need a failing demo link: https://getrector.org/demo

**Comment by addshore** [comment]
> Hi,
> 
> thanks for reporting.
> We'll need a failing demo link to verify the needed code for test: https://getrector.org/demo

The tool doesn't appear to allow me to test this code.

![image](https://user-images.githubusercontent.com/3308769/108050303-58cdce80-7041-11eb-8794-38587c9a0d7b.png)

But a link would be https://getrector.org/demo/90c72ecb-b39e-4fb6-a0d1-80d4717c0e11

I can reproduce it locally though and hope the following output is enough.

This includes:
 - `cat` of the test file
 - `cat` of the config
 - output with --dry-run
 - output of running test.php (which correctly echos "foo")
 - output of rector version

```
(rector)$ $ cat test.php
<?php
foo();
exit(0);
function foo()
{
echo "foo";
}

(rector)$ $ cat rector.php
<?php

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::SETS, [
        SetList::DEAD_CODE,
        ]);

};

(rector)$ $ vendor/bin/rector process ./test.php --ansi --dry-run
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
 exit(0);
 function foo()
 {
-echo "foo";
 }
    ----------- end diff -----------


Applied rules:

 * Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector



 [OK] Rector changed 1 file would have changed (dry-run).


(rector)$ $ php test.php
foo


(rector)$ $ composer show | grep "rector/rector"
rector/rector                        0.9.29             Instant upgrade and refactoring of your PHP code

**Comment by TomasVotruba** [comment]
Thanks, that looks good :+1: 

We'll need a failing test case for `RemoveUnreachableStatementRector`.
Here is how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

Could you add the test case, so we can see the failing CI here?

**Comment by addshore** [comment]
And having written the test I now have a working example for the demo tool too ;)

https://getrector.org/demo/cccc2f8e-4ec0-4f86-b0b5-2ec21c321f66
