### ISSUE TITLE
All ConstantRectors are adding type annotation on constants

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector#5574]
# Feature Request

 
For example, I've used `Rector\Privatization\Rector\Class_\RepeatedLiteralToClassConstantRector` as part of `SetList::PRIVATIZATION`, what I don't like, is that rector adds types to constants, at my team this is obvious and it's against our coding style. I do know, that you @TomasVotruba even wrote an article about that. But this is something that I see should be configurable.

## Diff 

```diff
-    /**
-     * @var string
-     */
-    private const ASD = 'ASD';
+    private const ASD = 'ASD';

```

My idea is to add `Rector\Core\Contract\Rector\ConfigurableRectorInterface` to all rectors that add constants and `configure` if they need to add type to them or not ( by default it should add types)

**Comment by TomasVotruba** [comment]
It makes sense. Are you willing to contribute this option?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Feel free to send PR with this parameter :+1:
