### ISSUE TITLE
ThrowWithPreviousExceptionRector problem

### ISSUE THREAD

**Issue by stanislav-janu** [rectorphp/rector#5576]
# Bug Report

| Subject | Details |
| :-------| :--------|
| Rector version | v0.9.29  |
| Installed as | composer dependency |

If is in code use new exception without any parameter and without brackets, rector will broke code.

## Minimal PHP Code Causing Issue

Before:

	public function renderEdit(int $id): void
	{
		try {
			// ... some code ...
		} catch (ImportNotExistException $exception) {
			throw new ForbiddenRequestException;
		}
	}

	/**
	 * @param int $id
	 *
	 * @throws \Nette\Application\AbortException
	 */
	public function handleJsonData(int $id): void
	{
		...

Rector:
```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ @@
         *
         * @throws \Nette\Application\AbortException
         */
+       public function handleJsonData($exception->getCode(), $exception;
+               }
+       }
+
+
+       /**
+        * @param int $id
+        *
+        * @throws \Nette\Application\AbortException
+        */
        public function handleJsonData(int $id): void
        {
                $data = [];
    ----------- end diff -----------


Applied rules:

 * Rector\CodeQuality\Rector\Catch_\ThrowWithPreviousExceptionRector
```

## Expected Behaviour

```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ @@
	} catch (ImportNotExistException $exception) {
-		throw new ForbiddenRequestException;
+		throw new ForbiddenRequestException($exception->getMessage(), $exception->getCode(), $exception);
	}
    ----------- end diff -----------
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
That looks like a bug in php-parser.

Could you provide failing demo link? http://github.com/demo

**Comment by stanislav-janu** [comment]
see https://getrector.org/demo/25a3025c-3832-4f07-b0f8-34a469989473

**Comment by TomasVotruba** [comment]
Thanks, that is very nice bug :)


Could you add testing fail case to our repository? That way we can fix it:
Here is how:
https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by stanislav-janu** [comment]
I can try it. :-)

**Comment by stanislav-janu** [comment]
I tried it. Is it ok?
