### ISSUE TITLE
Prefixed rector contains dump();

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#558]
Prefixed rector does not work due dump usage.

[Example](https://github.com/rectorphp/rector-prefixed/blob/6f991d5f9be1afa28fd52f6ce88afc383a8ea5a8/vendor/symplify/package-builder/src/Yaml/ParameterInImportResolver.php#L51)

**Comment by TomasVotruba** [comment]
PR?

**Comment by TomasVotruba** [comment]
It's look like that `composer publish-prefixed` fails on humbug/php-scoper bug
where composer autoload is prefixed only in file, not in string.

**Comment by TomasVotruba** [comment]
Both issues resolved:

- https://github.com/rectorphp/rector-prefixed/blob/master/vendor/symplify/package-builder/src/Yaml/ParameterInImportResolver.php
- https://github.com/rectorphp/rector-prefixed/blob/master/vendor/autoload.php
