### ISSUE TITLE
[Configuration] Refactor to ContainerFactory, use Configuration as value object

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5584]
To improve architecture to avoid hacking like https://github.com/rectorphp/getrector.org/pull/268/files#diff-d6ffa4379b5039ee21e1b2b877f702491610a30767ed2bacf9661d4c18152cdbR83-R89

With methods:

- `createFromInput()`
- `createFromArray()`

What do you think @JanMikes ?

**Comment by JanMikes** [comment]
Here are my opinions:

```
public function __construct(ParameterProvider $parameterProvider)
```
This is so bad, coupling with some external service. Consider this as DTO, it should be immutable, getting all values in constructor, possibly with static named constructors, etc `::fromParameterProvider(ParameterProvider $parameterProvider)`. 


```php
/**
 * @param array<mixed> $data
 */
public static createFromArray(array $data): self
```
Is good enough for now 👍 

I will come with some deeper analysis and proposals and PRs, how architecture could be improved, it might as well impact performance in the positive way.

**Comment by TomasVotruba** [comment]
Factory from array would be better, as `ParameterProvider` is already a service.

I want to avoid any `static` and `self` as long as possible, as it create weak contracts for no gain. It should be super clear what is dummy object and what is a service. There is already some form of valition in `createFromInput()` that should be part of service:

- `Configuration`
- `ConfigurationFactory`

We could also use PHPStan rule you talked about to require creation of the object only via factory :)

**Comment by TomasVotruba** [comment]
I just found a bug that is caused by this WTF. The configuration was used in one service `__construct()` before it was configured in `execute()` :D :facepalm: 

https://github.com/rectorphp/rector/pull/5618/files#diff-8cbefd6252b8f32ff15ed62b6ab39485a476d4a301e64a7704c899e884c4a791

**Comment by TomasVotruba** [comment]
Closing as idea is accepted, and so will the PR :+1:
