### ISSUE TITLE
Consider new release

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#559]
Release v0.3.3 is unusable when regularly installed due to wrong relative imports. I noticed it is fixed in master. I suggest creating new tag, coz non-working version is installed when installation docs are followed.

**Comment by TomasVotruba** [comment]
Agreed. 

What do you mean by "wrong relative imports"?

After this is resolved there is not reason not to relase: https://github.com/rectorphp/rector/issues/553

**Comment by carusogabriel** [comment]
@mssimi Please notice that Rector is still in Alpha, so, you should always use master, not a specific version.

**Comment by TomasVotruba** [comment]
I see

**Comment by TomasVotruba** [comment]
Done: https://github.com/rectorphp/rector/releases/tag/v0.3.4

I'll release dev tags more often, since packagist doesn't update well those untagged
