### ISSUE TITLE
How does Rector interfere/require with my project's libraries and/or PHP version?

### ISSUE THREAD

**Issue by mpdude** [rectorphp/rector#5593]
👋🏼 This is about my struggles trying to use Rector for the first time. Sorry for the long post 😕.

I would like to use Rector to upgrade – step by step – various things in a project that is currently on PHP 7.2.

Since the latest released version of Rector requires at least PHP 7.3, and since I learned that it is generally useful to install _tools_ not as Composer requirements but somehow as standalone entities (to prevent messing up project and tooling dependency requirements/restrictions, for example), my naïve assumption was that [running Rector in Docker](https://github.com/rectorphp/rector/blob/master/docs/how_to_run_rector_in_docker.md) would be the way to go.

```bash
$ docker run --rm -v $(pwd):/project rector/rector:latest process tests --dry-run

 [ERROR] strlen(): Argument #1 ($str) must be of type string, array given
```

A helpless attempt of mine was to add `-vvv`, hoping to elicit a bit more context, but no... 

I then found #5059, suggesting to try 

`docker run --rm -v $(pwd):/project -w /rector rector/rector:latest process /project/tests --config /project/rector.php --autoload-file=/project/vendor/autoload.php --dry-run`

This, at least, gives a new error message: 

`Fatal error: Array and string offset access syntax with curly braces is no longer supported in /project/vendor/mikey179/vfsstream/src/main/php/org/bovigo/vfs/vfsStream.php on line 309`

So, obviously there must be a problem because some project code (a dependency, actually) uses PHP <8 syntax; and the Docker image has been updated to use PHP 8.0 just a few days ago (#5536).

Which leads me to the first question: 

Why is there a conflict between the PHP version used by the _tool_ itself and the version of code (i. e. input, data?) the tool _works on_? How useful is an upgrade tool if it requires me to be PHP 8-compatible already? 🤔 

But, secondly, the #5059 PR also contains [this comment](https://github.com/rectorphp/rector/pull/5059#issuecomment-753975182), stating that this is way of running the Docker image is not a good/recommended default approach, since it changes the working directory from the project to the Rector installation inside the container. 

It then refers to [another comment](https://github.com/rectorphp/rector/issues/5003#issuecomment-752733167) that deals with how this change of the `cwd` changes autoload priorities to use Rector's dependencies over project dependencies, how this can be used to sidestep version conflicts between the version of Symfony components required by Rector and the project, and that in general, this would be "unexplored area".

So, second question: 

How can it be that there is such a conflict between the code/vendors required by the _tool_ itself and those of the code (i. e. input, data) the tool _works on_? 🤔

At least, that comment mentioned that there is https://packagist.org/packages/rector/rector-prefixed, which might be able to solve the second problem.

So, I cobbled up the following `Dockerfile.prefixed`:

```Dockerfile
FROM php:7.4-cli as base

WORKDIR /rector

RUN apt-get update && apt-get install -y libzip4 libicu63 && rm -rf /var/lib/apt/lists/*

FROM base as build

# Install php extensions
RUN apt-get update && apt-get install -y git g++ libzip-dev libicu-dev zip \
    && pecl -q install zip \
    && docker-php-ext-configure intl \
    && docker-php-ext-install zip intl

COPY --from=composer:2.0.9 /usr/bin/composer /usr/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_MEMORY_LIMIT=-1

RUN composer require rector/rector-prefixed --dev --optimize-autoloader --prefer-dist

FROM base as rector

COPY --from=build /rector /rector
COPY --from=build /usr/local/lib/php /usr/local/lib/php
COPY --from=build /usr/local/etc/php /usr/local/etc/php

ENTRYPOINT [ "rector" ]

ENV PATH /rector/vendor/bin:$PATH

VOLUME ["/project"]
WORKDIR "/project"
```

Build this with `docker build -t rector-prefixed -f Dockerfile.prefixed .`, and run:

`docker run --init -it --rm  -v $(pwd):/project rector-prefixed process --dry-run tests` ✅

So, third question:

Wouldn't it make sense to provide Docker images like these, with (if necessary) PHP 7 and/or even PHP 5 variants? 

I'd be glad to contribute to such an effort, but probably I'd need to understand the underlying issues (questions one and two) first.

**Comment by JanMikes** [comment]
Hello there!

You are right about prefixed version in Docker, we do not build it automatically yet, though for some bigger refactorings we have used it already, but did not publish the image. It is not our top priority, right now, but definitely something that is going to happen 😄 

> Wouldn't it make sense to provide Docker images like these, with (if necessary) PHP 7 and/or even PHP 5 variants?

Im not sure i understand, like having multiple tags of docker image? 
```
rector/rector:php-72
rector/rector:php-73
rector/rector:php-74
rector/rector:php-80
```

Docker image requires minimal php version which is code of rector written with (currently >=7.3).

> So, obviously there must be a problem because some project code (a dependency, actually) uses PHP <8 syntax; and the Docker image has been updated to use PHP 8.0 just a few days ago (#5536).

Yes, this is real problem. Right now i do not know what is causing it and i think it might not be docker related at all. Please give me some time to investigate, i will share my outcomes.

First idea is that it is caused by rector autoloading the files and it fails on syntax error and might be solved by solving #3490 but i need to verify this assumption first.

**Comment by mpdude** [comment]
Wow, what an incredibly fast and nice reply. Sorry if I put too much of initial frustration into my OP.

Regarding the PHP versions: What I meant was that, _if_ there is a requirement to use a PHP7-based Rector on non-PHP8-compatible code, would it make sense to have PHP 7 and PHP 8 variants of the Docker image?

#5536 seems to suggest that Rector can work on code with PHP 8 features only if it uses PHP 8, and my case shows that code not yet compatible with PHP 8 requires PHP 7.

About building rector-prefixed images: Would it make sense to bind this to https://github.com/rectorphp/rector/blob/master/.github/workflows/build_scoped_rector_tagged.yaml, so that these images could be published whenever there is a new released version?

**Comment by JanMikes** [comment]
> Sorry if I put too much of initial frustration into my OP

No worries. We are trying our best. There is always space for improvements and we are aware of that - if anything is not working correctly, we fix it asap.


> Regarding the PHP versions: What I meant was that, if there is a requirement to use a PHP7-based Rector on non-PHP8-compatible code, would it make sense to have PHP 7 and PHP 8 variants of the Docker image?
> #5536 seems to suggest that Rector can work on code with PHP 8 features only if it uses PHP 8, and my case shows that code not yet compatible with PHP 8 requires Rector to be run with PHP 7.

Well, for me it is too early to say if this is the way or not, i think it is all about correctly configuring nikic/php-parser under the hood, which i will try as part of #3490 and as bonus it would mean to close 2 issues with 1 mr 🎉 😄 


> About building rector-prefixed images: Would it make sense to bind this to https://github.com/rectorphp/rector/blob/master/.github/workflows/build_scoped_rector_tagged.yaml, so that these images could be published whenever there is a new released version?

Definitely yes. There are multiple ways, but they are just matter of code organization - we can put it directly to this workflow, make new workflow that will be triggered after this one finished, or workflow in target rector-prefixed repo that will be triggered once pushed... does not matter 😄 

Process should be always the same: 1) create prefixed rector 2) build docker image with it 3) publish docker image

**Comment by JanMikes** [comment]
Please what is status of this? Can we close or are there still any unanswered questions (there were many discussions ongoing in many different places 😊)?

**Comment by mpdude** [comment]
Yes, we can close this – for one, we've improved the Docker images already show that issue should not happen again. Second we're still working on documenting other limitations in #5678.

Thanks for your help!
