### ISSUE TITLE
symfony-constructor-injection.yml does not cover all use-cases

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#560]
Example of code to refactor which is not refactored:

```php
final class AnyController extends Controller
{
    public function anything()
    {
         $this->get('translator')->trans('something');
    }
}
```
I managed to find out rector ends up [here](https://github.com/rectorphp/rector/blob/02fa25d458d0e98946ed45d02a6df61c381a6c7f/packages/Symfony/src/Bridge/DefaultAnalyzedSymfonyApplicationContainer.php#L48).

**Comment by TomasVotruba** [comment]
How does `dev-master` perform? PHPStan might fix this

**Comment by mssimi** [comment]
I am using master as it is the only one that runs:)

**Comment by TomasVotruba** [comment]
Ok. 

Could you send failing test? I'll get to this ASAP

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/pull/564
