### ISSUE TITLE
`--match-git-diff` removes code which is used in non changed files

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#5604]
# Question
Not sure if this is a bug or intended behavior.
But I have a class which contains a public const that is getting removed every time I run rector with `--match-git-diff`. 

I expect this is because it does not scan the files which is not part of the git, however this does mean that it deletes used code.

**Comment by TomasVotruba** [comment]
Hi,

that's very interesting.
Could you provide Github Action demo repository that shows this?

Also with one job without `--match-git-diff`, to make sure it's related

**Comment by olivernybroe** [comment]
Hmm, looks like `--match-git-diff` also doesn't do what I thought. 

As it runs a `git diff` it will always be zero changed files when running in a github action, because the files has been committed. 
https://github.com/olivernybroe/Rector-demo/runs/1927509712?check_suite_focus=true


So for you to test this out locally, clone the dummy repo and change something in the `Dummy` file and then try running `vendor/bin/rector process src --dry-run --match-git-diff`.

**Comment by TomasVotruba** [comment]
The `--match-git-diff` runs only on changed uncommited files, so the behavior is correct.

**Comment by TomasVotruba** [comment]
Looking at feature added 15 months ago, https://github.com/rectorphp/rector/pull/2347, it used to be replacement for cache. It depends on current `git` state and might be confusing as you describe.

Now we have optoin `ENABLE_CACHE` that does the same process, just uses local cache to remember, what files were changed or not. The `--match-git-diff` can be dropped then and cache should be used as replacement.

**Comment by TomasVotruba** [comment]
The other job looks good: https://github.com/olivernybroe/Rector-demo/runs/1927509681?check_suite_focus=true

**Comment by olivernybroe** [comment]
@TomasVotruba True, I guess it's because in the docs it says that `--match-git-diff` is great for CI, however looking at my demo here, it's not really that great for putting into GitHub CI.



Hmm, so to do what I intended to do in my GitHub action, I would use the cache option and then use github cache to cache the cache file? Or how would you then make a github action only report rector changes on changed files?
(might just not be something you should do, like with phpstan)

**Comment by TomasVotruba** [comment]
> @TomasVotruba True, I guess it's because in the docs it says that --match-git-diff is great for CI, however looking at my demo here, it's not really that great for putting into GitHub CI.

Yes, that is confusing. We'll avoid this in #5609 

> Hmm, so to do what I intended to do in my GitHub action, I would use the cache option and then use github cache to cache the cache file? Or how would you then make a github action only report rector changes on changed files?
(might just not be something you should do, like with phpstan)

Personally I would run Rector on whole code base, just to be sure no spot or new nested dependency was missed. PHPStan also has few bugs on cache (it's hard), so we run it without cache in CI too.

**Comment by olivernybroe** [comment]
Thanks @TomasVotruba! 

I'll try something like that. Hopefully we will also soon see progress on the parallel support 👍 wrote a comment such might fix the problems that halted it.

**Comment by TomasVotruba** [comment]
Parallel is waiting for its hero :1st_place_medal:
