### ISSUE TITLE
Rule ChangeSwitchToMatchRector works wrong

### ISSUE THREAD

**Issue by roxblnfk** [rectorphp/rector#5607]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.29              |
| Installed as   | composer dependency                           |

If in a `switch-case` body missed break statement the rector also converts it to short `match` construnction

## Minimal PHP Code Causing Issue

```
switch ($suffix) {
    /** @noinspection PhpMissingBreakStatementInspection */
    case 'M':
        $value *= 1024;
    case 'K':
        $value *= 1024;
        break;
}
```
converts to
```
match ($suffix) {
    'M' => $value *= 1024,
    'K' => $value *= 1024,
};
```

## Expected Behaviour

Rector should skip it

https://3v4l.org/S3vFa

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting the bug. We'll need a failing test case to be added to `ChangeSwitchToMatchRectorTest`.

Here is how to add it:
https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
