### ISSUE TITLE
Incorrect behavior of ArgumentAdderRector, ClassPropertyAssignToConstructorPromotionRector, UnionTypesRector

### ISSUE THREAD

**Issue by roxblnfk** [rectorphp/rector#5608]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/8ace6951-fa83-4f9e-8b1d-19aa8c54bf54

```php
<?php

final class DemoFile
{
    private ?DatetimeInterface $time;
    public function __construct(DatetimeInterface $time = null)
    {
        $this->time = $time;
    }
}
```

### Responsible rules

* `ArgumentAdderRector`

* `ClassPropertyAssignToConstructorPromotionRector`

* `UnionTypesRector`

## Expected Behavior

```php
<?php

final class DemoFile
{
    public function __construct(private ?DatetimeInterface $time = null)
    {
    }
}
```

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting. We'll need a failing test case to `ClassPropertyAssignToConstructorPromotionRectorTest`. The other 2 options are unrelated - https://getrector.org/demo/c460ea7e-b528-4f6f-9734-191da5526660

Here is how to add test case: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
