### ISSUE TITLE
Incorrect behavior of SetList::TYPE_DECLARATION (AddArrayParamDocTypeRector & AddArrayReturnDocTypeRector)?

### ISSUE THREAD

**Issue by addshore** [rectorphp/rector#5612]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/39b2d6ff-84cb-4f25-be48-d075cb5c090e

### Responsible rules

* `AddArrayParamDocTypeRector`
* `AddArrayReturnDocTypeRector`

Apparently....
But Setting these 2 rules doesn't cause the issue https://getrector.org/demo/1be88ca2-bad3-4fd5-a476-53a2a06db50d
Only when using the whole of `SetList::TYPE_DECLARATION`

I believe a combination of the 2 rules ends up causing the issue, or something more confusing?

- `ParamDocType` alone doesn't cause the issue. https://getrector.org/demo/d92b95ed-dba9-4fa3-9e1b-fd81afd7d1f1
- `ReturnDocType` sets a phpdoc of `mixed[][]` for the data provider, but doesnt touch the other method https://getrector.org/demo/fbd49cdc-c2c2-4fe8-ac09-8bbad050cae1
- `ParamDocType applied once this phpdoc is added also does nothing https://getrector.org/demo/edda7854-eb0b-4f6d-8bb1-a6e64cd8d2a0
- Even both rules with the phpdoc already existing doesn't cause the issue https://getrector.org/demo/bae4bc38-c79e-4f22-9aec-ef66571a0974

## Expected Behavior

`array` is not the correct type for the parameter.
This should probably be left alone entirely

**Comment by TomasVotruba** [comment]
Hi,

this is a tricky one. We'll need a failing test case.
It can be added even with multiple rules or sets, like this: https://github.com/rectorphp/rector/commit/11fbc4c1c90d0405bbf8c6004a1c9374b4242b6d#diff-f9b531f4de96ebfd52019da0ee102ba24bff4f8c88a67e57ca08c67433e270fa

**Comment by addshore** [comment]
Will do! :)
