### ISSUE TITLE
CHANGELOG missing level 2 headings for versions since 0.8.29 (October 2020)

### ISSUE THREAD

**Issue by addshore** [rectorphp/rector#5666]
The last CHANGELOG level 2 heading is `## [0.8.29] - 2020-10-16`
~60 releases has happened since this point but the CHANGELOG doesn't contain the correct headings for these.
Instead the document mainly consists of level 3 headings with no separations.

https://github.com/rectorphp/rector/blob/master/CHANGELOG.md

**Comment by samsonasik** [comment]
Yes, duplicate with https://github.com/rectorphp/rector/issues/5663

**Comment by addshore** [comment]
@samsonasik could we re open this one? as #5663 didn't fix the issue described in the title?
Unless we don't want the existing changelog fixed

**Comment by samsonasik** [comment]
for latest heading tag, it may need wait for next release. I am not sure if old releases will re-generated or requires manual check, @TomasVotruba what do you think?

**Comment by TomasVotruba** [comment]
@samsonasik The changelog linker output should generated old tags too, so deleting the file and generating again should help

**Comment by samsonasik** [comment]
@TomasVotruba thank you. I think it is close-able in next relase then?

**Comment by TomasVotruba** [comment]
The release does not depend on changelog linker. You can run it now too

**Comment by samsonasik** [comment]
I tried remove CHANGELOG.md and re-create it, then run: `composer changelog` got the following output:

![Screen Shot 2021-02-28 at 14 53 54](https://user-images.githubusercontent.com/459648/109411457-d942e680-79d4-11eb-8f6b-572093c43661.png)

```bash
> vendor/bin/changelog-linker dump-merges --ansi

In SmartFileSystem.php line 30:
                                                                                                                                                                                                           
  Failed to read "/Users/samsonasik/www/rector/CHANGELOG.md" file: "Since symfony/dependency-injection 5.1: The "Symfony\Component\DependencyInjection\ContainerInterface" autowiring alias is deprecated  
  . Define it explicitly in your app if you want to keep using it. It is being referenced by the "Symplify\PackageBuilder\Parameter\ParameterProvider" service."                                           
                                                                                                                                                                                                           

dump-merges [--in-categories] [--in-packages] [--dry-run] [--since-id SINCE-ID] [--base-branch [BASE-BRANCH]] [-c|--config CONFIG]

Script vendor/bin/changelog-linker dump-merges --ansi handling the changelog event returned with error code 1
```

Is there something missing?

**Comment by TomasVotruba** [comment]
It's probably needs an empty file.

**Comment by samsonasik** [comment]
I use empty file, previously, when no file exits yet, it got different error:

```bash
composer changelog
> vendor/bin/changelog-linker dump-merges --ansi

In FileSystemGuard.php line 17:
                                                                                                                                           
  File "/Users/samsonasik/www/rector/CHANGELOG.md" not found in "Symplify\ChangelogLinker\FileSystem\ChangelogFileSystem::readChangelog".  
                                                                                                                                           

dump-merges [--in-categories] [--in-packages] [--dry-run] [--since-id SINCE-ID] [--base-branch [BASE-BRANCH]] [-c|--config CONFIG]

Script vendor/bin/changelog-linker dump-merges --ansi handling the changelog event returned with error code 1
```

**Comment by TomasVotruba** [comment]
Maybe new file could be created in this case instead. Could you handle it in Symplify?

**Comment by samsonasik** [comment]
I will try.

**Comment by TomasVotruba** [comment]
We won't be using CHANGELOG anymore, see https://github.com/symplify/symplify/issues/3027 for explanation
