### ISSUE TITLE
Cache dry-run results

### ISSUE THREAD

**Issue by berezuev** [rectorphp/rector#5668]
# Feature Request

`--dry-run` option is used to check if rector will do it's work properly. I think, if it worked correct, most of users run the same command second time, w/o `--dry-run` and spend time again.

WDYT about caching results of dry run in tmp directory (e.g. as git patch) and write message like:
> Run `git apply /tmp/somefile.patch` to apply differences

?

**Comment by TomasVotruba** [comment]
Hi, that would create 2 ways to change code. Problems with caching and another layer above filesystem.

The speed issue can be solved with parallel approach. That's the only way to speed up both dry run and sharp run.

We'd appreciate your help there 100 %
https://github.com/rectorphp/rector/issues/2971
