### ISSUE TITLE
Process stuck while analysing lambda functions with parameter names present in the same scope

### ISSUE THREAD

**Issue by beroso** [rectorphp/rector#5673]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.31             |
| Installed as   | composer dependency                           |

Process stuck while analysing lambda functions with parameter names present in the same scope.

## Minimal PHP Code Causing Issue

I'm putting the sample code here, because https://getrector.org/demo don't stop processing it.

### Input Code:
```php
<?php

final class ThingHelper
{
    public static function generateThing(string $name): string
    {
        $thingMaker = fn ($name) => $name . ' thing';

        return $thingMaker($name);
    }
}
```

### Config (rector.php)
```php
<?php

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::SETS, [SetList::CODE_QUALITY]);
};

```

## Expected Behaviour

Process finishing normally, with no code changes.

## Additional info

It works when i change the lambda's parameter name:

```php
$thingMaker = fn ($someName) => $someName . ' thing';
```

**Comment by samsonasik** [comment]
could you try with --debug to get the nearest rule that may causing it? Thank you.

**Comment by beroso** [comment]
I was trying to debug using xdebug, but for some reason the breakpoints are not working. But I managed to debug manually. The process got stuck in a infinite loop, in the following call pattern:

```php
Rector\CodeQuality\Rector\ClassMethod\DateTimeToDateTimeInterfaceRector::isDateTimeParam()
Rector\NodeTypeResolver\NodTypeResolver::isObjectType();

Rector\NodeTypeResolver\NodeTypeResolver::resolve();
Rector\NodeTypeResolver\NodeTypeResolver\ParamTypeResolver::resolve();
Rector\NodeTypeResolver\NodeTypeResolver::resolve();
Rector\NodeTypeResolver\NodeTypeResolver\VariableTypeResolver::resolve();
Rector\NodeTypeResolver\NodeTypeResolver::resolve();
Rector\NodeTypeResolver\NodeTypeResolver\ParamTypeResolver::resolve();
// ... endless loop
```

Hope this information could help.

**Comment by samsonasik** [comment]
You can run `vendor/bin/rector process --debug` and it will show the rules processing on and you may see nearest rector rules that causes it.

**Comment by beroso** [comment]
The last rule of the debug output is:

[applying] Rector\CodeQuality\Rector\ClassMethod\DateTimeToDateTimeInterfaceRector

**Comment by samsonasik** [comment]
The nearest rule in `config/set/code-quality.php` after `DateTimeToDateTimeInterfaceRector` are:

- `DateTimeToDateTimeInterfaceRector` itself
- `UnwrapSprintfOneArgumentRector`
- `SwitchNegatedTernaryRector`

But I can't reproduce it. I even tried with `JoinStringConcatRector` which uses in next directory rules after `DateTimeToDateTimeInterfaceRector` but still can't reproduce.

Please try one by one or half by half of services registered in `config/set/code-quality.php`.

**Comment by beroso** [comment]
Alright! I'm doing it now

**Comment by beroso** [comment]
It fails when I register only DateTimeToDateTimeInterfaceRector.

I made a repo with a minimal example to reproduce this problem. Could you take a look?
https://github.com/beroso/rector_issue_5673_demo

**Comment by samsonasik** [comment]
Thank you, it seems related with read `$name` parameter in the class method. Removing `$name` hide the issue. I will check if I can solve it.

**Comment by beroso** [comment]
Yes, it fails when lambda has a parameter with the same name of a parameter in class method. Thanks for your commitment on this task 👍
