### ISSUE TITLE
RemoveUnusedAliasRector removes aliases even though they are referenced in a class constant

### ISSUE THREAD

**Issue by DieterHolvoet** [rectorphp/rector#5687]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.10              |
| Installed as   | prefixed Rector                           |

`RemoveUnusedAliasRector` removes aliases even though they are referenced in a class constant.

## Minimal PHP Code Causing Issue

```php
<?php

namespace App;

use App\Bar as BarAlias;

class Foo
{
    private $classMap = [
        BarAlias::class => 'bar',
    ];
}

```

## Expected Behaviour

The alias should not be removed.

**Comment by samsonasik** [comment]
After PR https://github.com/rectorphp/rector-src/pull/784 , I think ClassConstFetch should be removed too if there is no conflict with use alias, it only make sense to have alias only if has conflict name in use statement.

I created a PR https://github.com/rectorphp/rector-src/pull/785 for it.
