### ISSUE TITLE
[ThrowWithPreviousExceptionRector] Previous exception duplication while named arguments used

### ISSUE THREAD

**Issue by dvapelnik** [rectorphp/rector#5697]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.31 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency                           |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/81c701e0-a2c6-4f5b-93f0-486e87d37d64

```diff
@@ -7,7 +7,7 @@
 		try {
             $this->run();
         }catch(\Throwable $e) {
-            throw new LogicException('Some exception', previous: $e);
+            throw new LogicException('Some exception', previous: $e, $e);
         }
     }
 }
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
