### ISSUE TITLE
Incorrect behavior of ChangeAndIfToEarlyReturnRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#5701]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e978ab32-e78c-4f60-8898-90f9f760a59e

```php
<?php

class rex_var_link extends rex_var
{
    protected function getOutput()
    {

        if ($this->hasArg('widget') && $this->getArg('widget')) {

        } else {
            if ($value && $this->hasArg('output') && 'id' != $this->getArg('output')) {
                $value = rex_getUrl($value);
            }
        }

        return $value;
    }
    

}

abstract class rex_var {
    /**
     * Returns the output.
     *
     * @return false|string
     */
    abstract protected function getOutput();    
    /**
     * Checks whether the given arguments exists.
     *
     * @param string $key
     * @param bool   $defaultArg
     *
     * @return bool
     */
    protected function hasArg($key, $defaultArg = false)
    {
        return isset($this->args[$key]) || $defaultArg && isset($this->args[0]);
    }

    /**
     * Returns the argument.
     *
     * @param string          $key
     * @param null|string|int $default
     * @param bool            $defaultArg
     *
     * @return null|string|int
     *
     * @template T as null|string|int
     * @phpstan-template T
     * @psalm-param T $default
     * @psalm-return string|T
     */
    protected function getArg($key, $default = null, $defaultArg = false)
    {
        if (!$this->hasArg($key, $defaultArg)) {
            return $default;
        }
        return $this->args[$key] ?? $this->args[0];
    }
}
```

### Responsible rules

* `ChangeAndIfToEarlyReturnRector`

## Expected Behavior

not sure how the resulting code should look like at best, but at least ot should obey the rules of the parent-method, which is defined as `@return false|string` in this case, but rector is adding (implicit) `null` returning statements.

after the rector process phpstan reports

> The declared return type 'false|string' for rex_var_link::getOutput is not nullable, but 'false|null|string' contains null

**Comment by staabm** [comment]
Simplified version 1:
https://getrector.org/demo/7bb70fda-e4a6-4f5b-8f6b-1f1749b10c6b

**Comment by TomasVotruba** [comment]
The change seems correct, but the docblock is invalid. There is no return.

We'll need expected behavior to be defined precisely.

**Comment by staabm** [comment]
Simplified https://getrector.org/demo/28002d78-c5d2-4f62-aaaa-0e4ccfd86558

**Comment by staabm** [comment]
Faling PR with expected result: https://github.com/rectorphp/rector/pull/5707

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector/pull/5711
