### ISSUE TITLE
Incorrect behavior of PrivatizeLocalOnlyMethodRector: Symfony Route with PHP 8 Attributes

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#5724]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/cfcba653-8f4b-4fcb-9163-22293a12a43d

```php
<?php
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/')]
final class FrontController
{
    #[Route(path: '', name: 'homepage')]
    public function homeAction() : Response
    {
    }
}
```

### Responsible rules

* `PrivatizeLocalOnlyMethodRector`

## Expected Behavior

See #5670 and #5671.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
