### ISSUE TITLE
Incorrect behavior of ConsoleExecuteReturnIntRector

### ISSUE THREAD

**Issue by OndraM** [rectorphp/rector#5733]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.9.31      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/d163eaf1-f599-4f4a-9683-5d593dd40b79

```php
<?php

function returns_bool(): bool {
    return true;
}

class RunCommand extends \Symfony\Component\Console\Command\Command
{
    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        $boolVariable = returns_bool();
        
        return $boolVariable ? 0 : 1;
    }
}
```

### Responsible rules

* `ConsoleExecuteReturnIntRector`

## Expected Behavior

The results of ternary expression `$boolVariable ? 0 : 1` is always an integer, so there is no need to typecast the result as suggested by Rector:
```diff
-        return $boolVariable ? 0 : 1;
+        return (int) ($boolVariable ? 0 : 1);
```

BTW this works properly when `$boolVariable` value is directly associated like this: https://getrector.org/demo/15150d54-496d-4f42-a179-5e157c67bfc0

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

Could you include also add method call that returns bool? I suspect the `function` is the problem :)

**Comment by OndraM** [comment]
Hi,

> Could you send a failing test case in a pull-request, 
I don't think I'm able to deep dive in this now, sorry. I tried to at least prepare the reproducible demo above, hope it can help.

>  I suspect the function is the problem :)
In real world this was actually a call to a public method of another object, and the behavior there was the same.
