### ISSUE TITLE
[TypedPropertyRector] properties annotated with a core class are not processed

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#5738]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.31             |
| Installed as   | composer dependency                          |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/75fbe8fd-0479-4f8d-8043-7dfd4abbb860

## Expected Behaviour

`private \DateTimeInterface $date;`

If this is not a bug and I'm missing somethig then please update the docs so next person does not waste time on debugging or searching issues.

**Comment by javaDeveloperKid** [comment]
I've changed https://github.com/rectorphp/rector/blob/master/rules/php74/tests/Rector/Property/TypedPropertyRector/Fixture/class_property.php.inc to test `\DateTime` run unit tests `vendor/bin/phpunit rules/php74/tests` on tag 0.9.31 and they pass. Also changed to `private string $anotherClass;` and test fails so it's fine too.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by javaDeveloperKid** [comment]
Do you mean a failing test with \DateTimeInterface -> string or a passing one with core class case covered? How would you test against the former?

**Comment by TomasVotruba** [comment]
The case that you find broken. With input and expected output.

**Comment by javaDeveloperKid** [comment]
I think I was misunderstood. I set `string` type in output template but left \DateTimeInterface on input template. It failed as expected. Did this just to make sure. Wrapping up: tests behave like I expect but demo or my app changes do not.

**Comment by TomasVotruba** [comment]
I need to see real code to undrestand. Could you link me to fixture where this is already covered and works?

**Comment by javaDeveloperKid** [comment]
I will create a reproduce app because I have multiple end cases in several files. Give me a few minutes.

**Comment by TomasVotruba** [comment]
Great! Failing Github Action would be the best with `--debug` option, to see what is failing exactly where

**Comment by javaDeveloperKid** [comment]
https://github.com/javaDeveloperKid/rector-reproducer-1
I've never used GitHub Actions. I can past `--debug` output here.

**Comment by javaDeveloperKid** [comment]
src/Entity/Document.php - DateTime fields are not type hinted
src/EventSubscriber/RequestLoggerEventSubscriber.php - here everything works fine
src/Service/MyService.php - non core type hints have FQCN type hint and \DateTime field is processed fine

```bash
 12/12 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

3 files with changes
====================

1) src/Entity/Document.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
 class Document
 {
     /**
-     * @var string
      *
      * @ORM\Id()
      * @ORM\Column()
      * @ORM\GeneratedValue(strategy="NONE")
      */
-    private $id;
+    private string $id;

     /**
-     * @var string
      *
      * @ORM\Column()
      */
-    private $state;
+    private string $state;

     /**
-     * @var array
      *
      * @ORM\Column(type="json")
      */
-    private $data = [];
+    private array $data = [];

     /**
      * @var \DateTime
    ----------- end diff -----------


Applied rules:

 * Rector\Php74\Rector\Property\TypedPropertyRector


2) src/EventSubscriber/RequestLoggerEventSubscriber.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
  */
 class RequestLoggerEventSubscriber implements EventSubscriberInterface
 {
-    /**
-     * @var string
-     */
-    private $id;
+    private string $id;

-    /**
-     * @var TokenStorageInterface
-     */
-    private $tokenStorage;
+    private TokenStorageInterface $tokenStorage;

-    /**
-     * @var LoggerInterface
-     */
-    private $logger;
+    private LoggerInterface $logger;

     public function __construct(TokenStorageInterface $tokenStorage, LoggerInterface $logger)
     {
    ----------- end diff -----------


Applied rules:

 * Rector\Php74\Rector\Property\TypedPropertyRector


3) src/Service/MyService.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
  */
 class MyService
 {
-    /**
-     * @var SerializerInterface
-     */
-    private $serializer;
+    private \Symfony\Component\Serializer\SerializerInterface $serializer;

-    /**
-     * @var AutoMapperInterface
-     */
-    private $autoMapper;
+    private \AutoMapperPlus\AutoMapperInterface $autoMapper;

-    /**
-     * @var \DateTime
-     */
-    private $date;
+    private \DateTime $date;

     /**
      * @param SerializerInterface $serializer
    ----------- end diff -----------


Applied rules:

 * Rector\Php74\Rector\Property\TypedPropertyRector


                                                                                                                        
 [OK] Rector changed 3 files have been changed.
```

**Comment by TomasVotruba** [comment]
The best time to start :)

You can use this workflow and replace path with your own:
https://github.com/rectorphp/rector/blob/9f96242e8a37d3807c880944974f43cdfba2f697/.github/workflows/rector.yaml#L62

**Comment by javaDeveloperKid** [comment]
Ok, I will try but later because I'm at the work right now.
P.S. Updated to 8.0 and found next awkward thing. Two fields annotated with Doctrine annotations, $id and $state which are also arguments to __constructor method changed like this:

```php
    public function __construct(/**
     * @ORM\Id()
     * @ORM\Column()
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private string $id, /**
     * @ORM\Column()
     */
    private string $state)
    {
        $this->createdAt = new \DateTime();
    }
```

**Comment by javaDeveloperKid** [comment]
Hi, I've set up GitHub Actions. https://github.com/javaDeveloperKid/rector-reproducer-1/commits/master
Btw. Example in my previous comment is a bug? I can't say if your like was about me setting up workflow later or my post scriptum.

**Comment by TomasVotruba** [comment]
Hi, thanks! Could you run it just on single file that breaks and link me the failing line in the CI?

**Comment by javaDeveloperKid** [comment]
> src/Entity/Document.php - DateTime fields are not type hinted
src/EventSubscriber/RequestLoggerEventSubscriber.php - here everything works fine
src/Service/MyService.php - non core type hints have FQCN type hint and \DateTime field is processed fine

I updated workflow to do 2 runs: one on 1st and one 3rd file. 
https://github.com/javaDeveloperKid/rector-reproducer-1/runs/2048096219?check_suite_focus=true
The effect remains.

**Comment by TomasVotruba** [comment]
Could you narrow it to just 1 error one one property? So we know what exactly to cover. 
When we resolve it, we can move next.

**Comment by javaDeveloperKid** [comment]
Done

**Comment by TomasVotruba** [comment]
Thanks! Could you link the build line a what is expected value?

**Comment by javaDeveloperKid** [comment]
https://github.com/javaDeveloperKid/rector-reproducer-1/runs/2048198756#step:5:29 
fqcn instead of class name

**Comment by TomasVotruba** [comment]
Thanks. This option must be set to false to disable FQN imports: https://github.com/javaDeveloperKid/rector-reproducer-1/blob/e2403f4ecead29e8a56e4af3b05cd2d5158512a8/rector.php#L25

**Comment by javaDeveloperKid** [comment]
It is set to `true` and it **does not** move FQCNs to use statements. This is the problem.

**Comment by TomasVotruba** [comment]
Ah, so expected is short class instead of fqcn?

**Comment by TomasVotruba** [comment]
I wonder what you did wrong with the test case.

I was able to create the test fixture that fails: https://github.com/rectorphp/rector/pull/5791/files

**Comment by TomasVotruba** [comment]
Thanks for the test case :+1: It helped me to narrow the issue to incorrect short name resolver for docblocks :slightly_smiling_face:

**Comment by javaDeveloperKid** [comment]
Yeah, when I read that comment right now I can see you could understand the opposite.
About the test, I don't remember right now. Would have to check again, but as this issue is closed let's the show go on.
Thank you Tomas!
