### ISSUE TITLE
Incorrect behavior of CreateFunctionToAnonymousFunctionRector

### ISSUE THREAD

**Issue by AndreaFar** [rectorphp/rector#5769]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@4758dad             |
| Installed as   | composer dependency / prefixed Rector                           |

I have used this rector configuration file to update all the deprecated _create_function_ uses.
I have used the following rector init code

```
<?php

use Rector\Core\Configuration\Option;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector;

return static function (ContainerConfigurator $containerConfigurator) {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src',
    ]);

    $services = $containerConfigurator->services();
    $services->set(CreateFunctionToAnonymousFunctionRector::class);
};
```

As result rector has replaced sections as

```
function register_skin_deactivation_hook_function($code, $function) {
    $GLOBALS[ 'register_skin_deactivation_hook_function' . $code] = $function;
    $fn=create_function('$skin', ' call_user_func($GLOBALS["register_skin_deactivation_hook_function' . $code . '"]); delete_option("skin_is_activated_' . $code. '");');
    add_action( 'switch_s' , $fn );
}
```
with

```
function register_skin_deactivation_hook_function($code, $function) {
    $GLOBALS[ 'register_skin_deactivation_hook_function' . $code] = $function;
    $fn=function ($skin) use ($GLOBALS, $code) {
            call_user_func($GLOBALS["register_skin_deactivation_hook_function{$code}"]);
            delete_option("skin_is_activated_{$code}");
    };
    add_action( 'switch_s' , $fn );
}
```

That isn't a correct syntax and it causes
**Fatal error: Cannot use auto-global as lexical variable**

on

`$fn=function ($skin) use ($GLOBALS, $code) {`

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by AndreaFar** [comment]
> Thank you for your report!
> 
> We'll need an isolated failing demo link from: http://getrector.org/demo,
> that way we can reproduce the bug.


This is the output 
# Bug Report


| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/79aed683-3e94-4f7b-82b4-e5016592ea25

```php
<?php

final class DemoFile
{
   function register_skin_deactivation_hook_function($code, $function) {
    $GLOBALS[ 'register_skin_deactivation_hook_function' . $code] = $function;
    $fn=create_function('$skin', ' call_user_func($GLOBALS["register_skin_deactivation_hook_function' . $code . '"]); delete_option("skin_is_activated_' . $code. '");');
    add_action( 'switch_s' , $fn );
}
}
```

### Responsible rules

* `CreateFunctionToAnonymousFunctionRector`

**Comment by TomasVotruba** [comment]
Thank you for your finding minimal PHP code and the demo link!

Could you send a failing test case in a pull-request with expected change, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
