### ISSUE TITLE
Multiarch Docker build

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#5771]
When I do `docker pull rector/rector:<tag>` on my Apple Silicon based Macbook, it fails, because image is not compatible with my CPU architecture (arm64) and I have to build it locally.

We need to use multiarch builds to publish images for multiple architectures.

**Comment by JanMikes** [comment]
i will get into this tomorrow, if no one picks it earlier.

@mpdude i know you might be interested in this one :-)

**Comment by mpdude** [comment]
You send me an appropriate MacBook for testing ;-)? DM for contact details.

**Comment by mpdude** [comment]
https://jaimyn.com.au/how-to-build-multi-architecture-docker-images-on-an-m1-mac/

**Comment by JanMikes** [comment]
Ok, it will not be that easy :-) https://github.com/rectorphp/rector/runs/2031153082?check_suite_focus=true

**Comment by JanMikes** [comment]
Needed to setup qemu using `docker/setup-qemu-action@v1` action

**Comment by JanMikes** [comment]
🎉  success! 

<img width="1267" alt="Screenshot 2021-03-04 at 15 07 11" src="https://user-images.githubusercontent.com/3995003/109975833-5afb8280-7cfb-11eb-9a53-866a91d5034c.png">
