### ISSUE TITLE
Incorrect behavior of RemoveCodeAfterReturnRector

### ISSUE THREAD

**Issue by esambe** [rectorphp/rector#5779]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/7ec2983f-dc47-4f61-816e-614e5b56a8d7

```php
<?php

final class DemoFile
{
    public function run()
    {
        return 5;

        // we never get here
        return 10;
    }
}
```

### Responsible rules

* `RemoveCodeAfterReturnRector`

**Comment by samsonasik** [comment]
the red part is expected, and that means removed.
