### ISSUE TITLE
[Phpunit] AssertEqualsToSameRector fails if markTest* exists in function

### ISSUE THREAD

**Issue by Bl00D4NGEL** [rectorphp/rector#5799]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.9.29              |
| Installed as   | prefixed Rector                           |

It seems that the AssertPropertyExistsRector fails if a markTestIncomplete or markTestSkipped is present in the (test) function it tries to refactor. The error is `Uncaught Error: Call to a member function getType() on null in <path-to-vendor>/rector/rector-prefixed/rules/phpunit/src/Rector/MethodCall/AssertEqualsToSameRector.php:92` which is the return in this code snippet:
```
    private function getNodeType(\PhpParser\Node\Expr $expr) : \PHPStan\Type\Type
    {
        /** @var Scope $nodeScope */
        $nodeScope = $expr->getAttribute(\Rector\NodeTypeResolver\Node\AttributeKey::SCOPE);
        return $nodeScope->getType($expr);
    }
```

## Minimal PHP Code Causing Issue
https://getrector.org/demo/e3267adc-56d3-4fc6-a1d3-7c46c71d256a

## Expected Behaviour
No error is thrown, refactor for assertEquals -> assertSame should still be applied

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by Bl00D4NGEL** [comment]
Changed the title of the issue as I was confusing rectors. Created https://github.com/rectorphp/rector/pull/5800 for the test fixtures

**Comment by Bl00D4NGEL** [comment]
Issue fixed with https://github.com/rectorphp/rector/pull/5800

**Comment by TomasVotruba** [comment]
Thank you :clap:
