### ISSUE TITLE
Crazy dependencies in Nette 0.9

### ISSUE THREAD

**Issue by grogy** [RectorPHP/Rector#58]
I get project with full of problems in codebase. For example how are created dependencies:

```php
  protected function createComponent($name)
  {
    switch ($name)
    {
      // models
      case 'catalog': $this->addComponent(Environment::getService('CatalogModel'), $name); return;
      case 'library': $this->addComponent(Environment::getService('LibraryModel'), $name); return;
      case 'page': $this->addComponent(Environment::getService('PageModel'), $name); return;
      case 'seo': $this->addComponent(Environment::getService('SeoModel'), $name); return;
      case 'shop': $this->addComponent(Environment::getService('ShopModel'), $name); return;
      case 'user': $this->addComponent(Environment::getService('UserModel'), $name); return;

      default:
        return parent::createComponent($name);
    }
  }
```

and using of dependency:

```
$this['shop']->getShopSubcategories(..);
```

Any idea how automaticaly repair this? :-))

**Comment by TomasVotruba** [comment]
Well I'd split it to more steps. Those that could be reused by community and those specific for your projects

### Reusable

1. Find `Environment::getService('SeoModel')` cases
2. Look into container, what type is 'SeoModel'
3. Add it to constructor
4. Add property
5. Replace `Environment::getService('SeoModel')` with `$this->setModel`

### Specific

6. Find `$this['shop']` cases, get `"shop"` from it
7. Find `createComponent` function, find "shop" inside it's body
8. Detect nearest `$this->setModel` access (local property access)
9. Replace `$this['shop']` from step 6. with `$this->setModel` code (local property access)

For the reusable part you can make use of [GetterToPropertyRector](https://github.com/RectorPHP/Rector/blob/af59aa372c6069de79750d1699c696cc220425a7/src/Rector/Contrib/Symfony/HttpKernel/GetterToPropertyRector.php#L18-L21) for Symfony, which:

converts all:

```php
 $this->get('some_service') # where "some_service" is name of the service in container.
```

into:

```php
$this->someService # where "someService" is type of the service
```

**Comment by TomasVotruba** [comment]
I might look that Reusable part tomorrow. You can try to figure out the Specific part meanwhile.

**Comment by TomasVotruba** [comment]
**I've just added support for part A.**

- [GetServiceToConstructorInjectionRector](https://github.com/RectorPHP/Rector/blob/ee6e8ec1f6f52c2705349a32fa3df520c71af263/src/Rector/Contrib/Nette/Environment/GetServiceToConstructorInjectionRector.php#L15-L21)

**Comment by TomasVotruba** [comment]
Closing for now as resolved by rector above and no reseponse
