### ISSUE TITLE
Analyze error for class definition inside of if(class_exists(...

### ISSUE THREAD

**Issue by aguenther** [rectorphp/rector#5801]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.9.31              |
| Installed as   | composer dependency                          |

If a PHP file checks for the existence of a class before defining it, Rector throws an Analyze Error: "Class X was not found while trying to analyse it", and skips the entire file.

## Minimal PHP Code Causing Issue

```
<?php
if (!class_exists('Foobaer')) {
    class Foobaer {

    }
}
```

## Expected Behaviour

Rector should be able to analyse a file with such a construct in it, without throwing errors

**Comment by TomasVotruba** [comment]
This should be solved by static reflection merged a week ago: https://github.com/rectorphp/rector/pull/5665

It's still not released, because it needs in-depth testing.
Could you verify this works with `dev-master`?

**Comment by aguenther** [comment]
I can verify that this indeed does work with dev-master :+1:

**Comment by samsonasik** [comment]
Closing as works in dev-master then. @aguenther thank you for verify.
