### ISSUE TITLE
Failed to build rectorphp/rector-prefixed with Box

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector#5846]
# Bug Report

Built with

https://github.com/szepeviktor/rector-phar/blob/1529dfbd6d79eac52794cf77c6f0a82cc2af40a1/.github/workflows/release.yml#L43-L47

and got a fatal error when running the PHAR file

> PHP Fatal error:  Uncaught Error: Class 'Rector\Core\Console\Style\SymfonyStyleFactory' not found in phar:///home/viktor/rector.phar/bin/rector.php:32

this was version 0.9.3

https://github.com/szepeviktor/rector-phar/releases/tag/0.9.3

Please help me.

**Comment by TomasVotruba** [comment]
This bug was fixed already.
Always build the latest version or used the built Rector

**Comment by szepeviktor** [comment]
@TomasVotruba Thank you for your response.
I've checked out the main branch and issued `bin/rector`

```
PHP Fatal error:  Uncaught Error: Class 'RectorPrefix20210314\Composer\InstalledVersions' not found in /home/viktor/a/rector-prefixed/vendor/jean85/pretty-package-versions/src/PrettyVersions.php:17
```

What am I doing wrong?

**Comment by TomasVotruba** [comment]
That's the latest bug we know of.

See https://github.com/rectorphp/rector/issues/5851, @samsonasik is working on it
