### ISSUE TITLE
Create simple roadmap

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#587]
See https://github.com/javiereguiluz/easybook/issues/137 for inspiration

**Comment by carusogabriel** [comment]
Something we **do need**: reduce the number of dependencies, current 50+.

Also, consider making the prefixed version compatible with lowe PHP versions. Older projects don't use PHP 7+ for sure.

**Comment by TomasVotruba** [comment]
Why reduce dependencies?  

As for PHP, most of PHP 5 code runs on PHP 7 as well. There is transpiler tool if needed: https://github.com/jaytaph/Transphpile

**Comment by TomasVotruba** [comment]
From step of time I see there are poping up new issues with various priorites and I don't feel the need for roadmap at the moment. It would not be stable anyway, maybe later :)
