### ISSUE TITLE
RenameClassRector should also rename imports

### ISSUE THREAD

**Issue by DieterHolvoet** [rectorphp/rector#5871]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.31              |
| Installed as   | prefixed Rector                           |

When using `RenameClassRector` to change the namespace of the class without changing the actual class name, the class ends up with imports of both the old and the new class, but with different namespaces. In this case, this is not automatically handled by autoimport and coding standard as [this comment](https://github.com/rectorphp/rector/blob/f92c18514ab60694692be986551b7bd4807c9e66/rules/Renaming/NodeManipulator/ClassRenamer.php#L180) indicates.

The issue is fixed for me when I remove the following if statement:
```php
if ($parentNode instanceof \PhpParser\Node\Stmt\UseUse && ($parentNode->type === \PhpParser\Node\Stmt\Use_::TYPE_NORMAL || $parentNode->type === \PhpParser\Node\Stmt\Use_::TYPE_UNKNOWN)) {
    // no need to rename imports, they will be handled by autoimport and coding standard
    // also they might cause some rename
    return null;
}
```

## Minimal PHP Code Causing Issue

Example config:

```php
<?php

declare(strict_types=1);

use Rector\Renaming\Rector\Name\RenameClassRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(RenameClassRector::class)
        ->call('configure', [[
            RenameClassRector::OLD_TO_NEW_CLASSES => [
                Drupal\hook_event_dispatcher\Event\Views\ViewsQueryAlterEvent::class => Drupal\views_event_dispatcher\Event\Views\ViewsQueryAlterEvent::class,
            ],
        ]]);
};

```

## Expected Behaviour

Make sure imports are also renamed.

**Comment by TomasVotruba** [comment]
Thank you for your report!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by lulco** [comment]
I think this is test case which would cover this bug, but it is wrong configured: https://github.com/rectorphp/rector/blob/main/rules-tests/Renaming/Rector/Name/RenameClassRector/FixtureAutoImportNames/rename_class_with_same_name_but_different_namespace.php.inc

I believe that if auto_import_names is true, classnames should be in uses, not in code body, so test should looks like this:
```
<?php

namespace Rector\Tests\Renaming\Rector\Name\RenameClassRector\FixtureAutoImportNames;

use Rector\Tests\Renaming\Rector\Name\RenameClassRector\Source\FirstNamespace\SomeServiceClass;

$someService = new SomeServiceClass();

?>
-----
<?php

namespace Rector\Tests\Renaming\Rector\Name\RenameClassRector\FixtureAutoImportNames;

use Rector\Tests\Renaming\Rector\Name\RenameClassRector\Source\SecondNamespace\SomeServiceClass;

$someService = new SomeServiceClass();

?>

```

**Comment by lulco** [comment]
I've added failing test for something else, but it could be used here as well: https://github.com/rectorphp/rector/pull/6035

New use is added rather then the old one would be changed.

**Comment by TomasVotruba** [comment]
The linked test is now fixed accidentally :) by https://github.com/rectorphp/rector/pull/6057/files#diff-52148f61c2a7771df0acefc602486e967d7ea57d86b904b9e00ff3ab54e55ee6
