### ISSUE TITLE
remove shadowed local variable in dead-code detection

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#5873]
# Feature Request

since the locally defined variable is overriden in the IF and also the ELSE case, the declaration before the IF/ELSE should be removed

https://getrector.org/demo/cbfeab47-4b9e-4f55-9185-0ecbda0fb1ce
 
## Diff 

```diff
-$fromDate = null; // should be removed
+
```

_I will provide a failing test-case within this week_

**Comment by TomasVotruba** [comment]
This can be quite complicated to implement right. Nested if/foreaches
But if you would add this feature and the tests, we can merge it :+1: 

Closing as accepted if contributed
