### ISSUE TITLE
uncalled private methods should be removed in dead-code detection

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#5876]
# Feature Request

the whole private method `notcalled` should be removed because its private and not called within the same class

https://getrector.org/demo/6831aa4c-3092-4f1a-afb7-2e25dd0f232f
 

_I will provide a failing test-case within this week_

**Comment by Bl00D4NGEL** [comment]
Once you get around adding (failing) test-cases I'd be happy to implement it if you don't want to do it/have the time for it. Just ping me once you have some fixtures up :)

**Comment by staabm** [comment]
just created a failing testcase in https://github.com/rectorphp/rector/pull/5896

I think we should continue our investigation in the PR.
