### ISSUE TITLE
only read private properties should be removed in dead-code detection

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#5877]
# Feature Request

the private property which is only read but never written to, should be removed.

https://getrector.org/demo/29847930-1490-4fee-b34b-96f8e21da596 

_I will provide a failing test-case within this week_

**Comment by TomasVotruba** [comment]
> I will provide a failing test-case within this week

:+1:

**Comment by staabm** [comment]
My fellow worker sent the failing test in the linked PR

**Comment by TomasVotruba** [comment]
Full contribution is needed to accept this
