### ISSUE TITLE
[PhpSpecToPHPUnit] Moved file does not contain all rector changes 

### ISSUE THREAD

**Issue by laurent35240** [rectorphp/rector#5878]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.31             |
| Installed as   | composer dependency                           |

When using PhpSpecToPHPUnit, rector will move spec file to tests directory but with original file content instead of content fixed by rector

## Minimal PHP Code Causing Issue

`rector.php` file
```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::AUTOLOAD_PATHS, [__DIR__ .'/spec']);

    $parameters->set(Option::SETS, [
        SetList::PHPSPEC_TO_PHPUNIT,
    ]);
};
```

Example a spec file `spec/Acme/CalculatorSpec.php`
```php
<?php

namespace spec\Acme;

use Acme\Calculator;
use PhpSpec\ObjectBehavior;

class CalculatorSpec extends ObjectBehavior
{
    function it_is_initializable()
    {
        $this->shouldHaveType(Calculator::class);
    }
}
```

Running `bin/rector process spec` will then produce file `tests/Acme/CalculatorTest.php` but with same content as original file.

## Expected Behaviour

File `tests/Acme/CalculatorTest.php` should be created with following content
```php
<?php

namespace Tests\Acme;

use Acme\Calculator;
use PhpSpec\ObjectBehavior;

class CalculatorTest extends \PHPUnit\Framework\TestCase
{
    private \Acme\Calculator $calculator;
    protected function setUp(): void
    {
        parent::setUp();
        $this->calculator = new \Acme\Calculator();
    }
}
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

I'm not sure when I get to this as I have full focus on static reflextion and Rector release.
Could you try to fix it?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback and missing test case.
Feel free to reopen with a test.

How to send a failing test case? Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
