### ISSUE TITLE
Add ability to extends custom SetList

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#5891]
# Feature Request

Currently, it seems there is no way to have custom `SetList` as the configuration is a constant and the config is early read:

https://github.com/rectorphp/rector/blob/c815334bed781c555f08dff82ce7861d758e9e7a/packages/Set/RectorSetProvider.php#L30

ref https://github.com/laminas/laminas-servicemanager-migration/pull/2#issuecomment-801530436

**Comment by TomasVotruba** [comment]
How can we abstract this without hardcoding the values in `RectorSetProvider`?

**Comment by samsonasik** [comment]
probably check at `RectorConfigsResolver` ?

https://github.com/rectorphp/rector/blob/a389839c5cb0dbcbfc480012bee31762e336011b/src/Bootstrap/RectorConfigsResolver.php#L58-L87

**Comment by TomasVotruba** [comment]
How would it look like without hardcoding `DowngradeSetList` and `SetList`?

**Comment by samsonasik** [comment]
I am not sure, how about create static property and update if not found?

**Comment by samsonasik** [comment]
I found the solution for it with import via `$containerConfigurator->import()`:

```php
<?php
// rector.php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Laminas\ServiceManager\Migration\Rector\Set\ValueObject\SetList;
use Rector\CodingStyle\Rector\FuncCall\CountArrayToEmptyArrayComparisonRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $services = $containerConfigurator->services();
    $containerConfigurator->import(SetList::LAMINAS_SERVICEMANGER_40);

    $parameters->set(Option::PATHS, [__DIR__ . '/module']);
    $services->set(CountArrayToEmptyArrayComparisonRector::class);
};
```

![Screen Shot 2021-03-20 at 18 04 03](https://user-images.githubusercontent.com/459648/111867464-ac1b9f80-89a6-11eb-867e-d9ad97afacec.png)

I am closing it.

**Comment by TomasVotruba** [comment]
Great approach, I didn't think of this :+1: 
Set constant is basically config file, so this makes 100 % sense.
