### ISSUE TITLE
Add nikic/php-parser ^4.10.2 to 0.8.57+

### ISSUE THREAD

**Issue by tomasnorre** [rectorphp/rector#5901]
# Feature Request

Would it be possible to update the `nikic/php-parser` to `^4.10.2` instead of `4.10.2`. As I see it there should be no problems for Rector to have e.g. 4.10.4 installed instead. Correct me if I'm wrong. 
 
This would help me resolve a composer conflict that I have currently. 
https://twitter.com/tomasnorre/status/1372621416902881281

The rector Phar isn't working for me, and I cannot drop support for PHP 7.2 yet, so upgrading to rector 0.9.x  isn't an option for me. 

## Diff 

```diff
- "nikic/php-parser": "4.10.2",
+ "nikic/php-parser": "^4.10.2",
```

What do you think about the change?

**Comment by TomasVotruba** [comment]
The 0.8 is super old version with many bugs, but I get you need the PHP 7.2. 

Next Rector 0.10 version will have support for static reflection: https://phpstan.org/blog/zero-config-analysis-with-static-reflection

This will be better solution: https://twitter.com/rectorphp/status/1371605561251405825

I'm working on last fixes like missing PHP 7.1 polyfill functions.

**Comment by tomasnorre** [comment]
This sounds good. 

Let me know if I can do anything to support this work.

**Comment by TomasVotruba** [comment]
There are 2 ways:

- taking :x:  crosses here https://github.com/rectorphp/rector-prefixed, modifing this script https://github.com/rectorphp/rector/blob/main/build/downgrade-rector.sh#L19-L34 that handles the downgrade and make them :heavy_check_mark:  again - that's what I'm doing last 3 weeks almost non-stop
- add a downgrade rule from `array_key_first` to previous form - basically invert rule https://github.com/rectorphp/rector/blob/157c39aefcee753d54a5c18cc120f11af7a95862/rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php

**Comment by tomasnorre** [comment]
I'll have a look what I can do. Don't have time before next week.

**Comment by tomasnorre** [comment]
I'm closing this as this is something you are already trying to solve.

**Comment by TomasVotruba** [comment]
The build might be green, but that might be not enough tests :) 

Could you try it out and let me know how it works?
https://github.com/rectorphp/rector-prefixed

**Comment by tomasnorre** [comment]
Looks quite promising. I still have some problems with autoloading. But that's is something on my side. 

```
[ERROR] Could not process "Classes/Api/CrawlerApi.php" file, due to:                                                   
         "Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::setAttribute()".  
```

**Comment by tomasnorre** [comment]
Doesn't solve my problem. Will need to look into when I have more time.

**Comment by TomasVotruba** [comment]
Oh... and `phpdoc-parser`:`^0.5`, some other packages uses.

**Comment by tomasnorre** [comment]
The repository is the https://github.com/aoepeople/crawler

**Comment by tomasnorre** [comment]
I know it's a problem with the non-standard vendor folder, but even when correcting that I still have a problem. 
But as mentioned I will look into this. I think the problem is on my site/repo.

**Comment by TomasVotruba** [comment]
Missing `setAttribute()` method is related to this change https://github.com/phpstan/phpdoc-parser/pull/65 that requires at least:

- rector/rector-prefixed dev-main or 0.10 alias (minimal-stability dev, prefer-stable true)
- phpstan/phpstan 0.12.82
- phpstan/phpdoc-parser 0.5

I wanted to help, but I see only Rector 0.8 in the composer and no pull-requests with Rector update. 

Try to bump them all

**Comment by tomasnorre** [comment]
It's really nice of you, I'll let you know when I have something ready, your input already helped me a lot.
