### ISSUE TITLE
Fatal error:  Class Rector\BetterPhpDocParser\ValueObject\PhpDocNode\PHPUnit\PHPUnitDataProviderTagValueNode contains 1 abstract method ...

### ISSUE THREAD

**Issue by msassa** [rectorphp/rector#5911]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.9.32 |
| Installed as   | composer dependency |

# vendor/bin/rector process manage --dry-run
 1081/3400 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  31%PHP 

Fatal error:  Class Rector\BetterPhpDocParser\ValueObject\PhpDocNode\PHPUnit\PHPUnitDataProviderTagValueNode contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPStan\PhpDocParser\Ast\Node::hasAttribute) in src/vendor/rector/rector/packages/better-php-doc-parser/src/ValueObject/PhpDocNode/PHPUnit/PHPUnitDataProviderTagValueNode.php on line 11

Fatal error: Class Rector\BetterPhpDocParser\ValueObject\PhpDocNode\PHPUnit\PHPUnitDataProviderTagValueNode contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPStan\PhpDocParser\Ast\Node::hasAttribute) in src/vendor/rector/rector/packages/better-php-doc-parser/src/ValueObject/PhpDocNode/PHPUnit/PHPUnitDataProviderTagValueNode.php on line 11

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

**Comment by TomasVotruba** [comment]
Should be fixed now by https://github.com/rectorphp/rector/commit/5ecfec4ae83f6187f09584579cacee08658dc3a9

Upgrade to https://github.com/rectorphp/rector/releases/tag/0.9.33
