### ISSUE TITLE
Abandoned Packages - migrify/migrify-kernal and migrify/php-config-printer

### ISSUE THREAD

**Issue by jasteele12** [rectorphp/rector#5915]
# Bug Report

| Subject        | Details                                                       |
| :------------- | :--------------------------------------------|
| Rector version | 0.8.56 |
| Installed as      | composer require rector/rector --dev |

Just tried installing this today, and received these errors from Composer:

Package migrify/migrify-kernel is abandoned, you should avoid using it. Use symplify/symplify-kernel instead.
Package migrify/php-config-printer is abandoned, you should avoid using it. Use symplify/php-config-printer instead.

Composer version 2.0.11 2021-02-24 14:47:23
PHP 7.4.15 (cli) (built: Feb 18 2021 21:36:17) ( NTS )

**Comment by TomasVotruba** [comment]
Hi, the version 0.8 is not supported. Upgrade to Rector 0.9

**Comment by jasteele12** [comment]
Uh, why is it giving me an old version on a fresh install - following the directions from the repository?

How do I upgrade to 0.9?

**Comment by TomasVotruba** [comment]
Probably some dependency conflict. Try this to find out why:

```
composer require rector/rector:0.9
```

**Comment by jasteele12** [comment]
Okay, so I deleted everything (./vendor, composer.json, composer.lock).

composer require rector/rector:0.9

Then ran a simple test of ./src (only 2 php files), and get this error:

PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Symplify\PackageBuilder\Reflection\PrivatesCaller::callPrivateMethod() must be of the type array, object given, called in
 [ ... ] vendor/rector/rector/src/Console/Style/SymfonyStyleFactory.php on line 32 and defined in
 [ ...]  vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php:21

Again, this is a fresh install, no other composer dependencies.  Still doesn't explain why the repository directions give me an old version...

**Comment by TomasVotruba** [comment]
Interesting. I don't have any clue. Could you create reproducible repository on GitHub?
