### ISSUE TITLE
Demo errors: Cannot retrieve a version for package rector/rector 

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#5922]
# Bug Report

It seems the demo site does not work right now

## Minimal PHP Code Causing Issue

open https://getrector.org/demo/e3cd9d32-cbc6-4fb1-8f60-853b5ac8add8 and click „process“

errors with 

> Fatal error: Cannot retrieve a version for package rector/rector since it is replaced by some other package

## Expected Behaviour

No error

**Comment by samsonasik** [comment]
Duplicated with https://github.com/rectorphp/getrector.org/issues/293
