### ISSUE TITLE
Lower minimum PHP version for prefixed version

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#593]
Hello,
Here's my problem :
My server will never use php 7.1 but I need to evolve it now. Also, the project is so old that I can't use php7.1 for multiple reasons. 
I can go from 5.3 to 5.6 but our application isn't compatible... I'm evolving a 2.1 to 2.8 (done) and I want to use rector to evolve to 3.4 easier.
What's the procedure to make it work ? Thanks.

**Comment by TomasVotruba** [comment]
Hi, Rector depends on many PHP 7.1 packages, even more of PHP 7. You can Google for some package that modify code to lover PHP versions. I could not find anything useful.

**The analysed code can be in PHP 5**, but you have to have running PHP 7 to run Rector.

Some of my friends solve this situation by running a Docker with PHP 7.1.

**Comment by vasilvestre** [comment]
I already tried and actually run with Docker but I will give you the error Rector throw

**Comment by vasilvestre** [comment]
Are we ok that Rector can't be installed globally ?

**Comment by TomasVotruba** [comment]
The code Rectors proccesses code you give it to process. Pass is the directory with your code, never /vendor.

Autoloading is described here: https://github.com/rectorphp/rector#extra-autoloading

**Comment by vasilvestre** [comment]
I choose my project/src/ directory but the command with `--autoload-file project/vendor/autoload.php` option still fail.

```
1 vagrant@DEV-VM ~/projects % vendor/bin/rector process itisanoo/src/ --level symfony34 --autoload-file itisanoo/vendor/autoload.php                                                                      :(

3 Loaded Rectors
================

 - Rector\Rector\Argument\ArgumentRemoverRector
 - Rector\YamlRector\Rector\ReplaceStringYamlRector

Processing 645 files
====================

   1/645 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%

In ProcessCommand.php line 194:

  Processing of "itisanoo/src/Itisanoo/LdapBundle/Tests/Controller/DefaultControllerTest.php" file failed.


In Broker.php line 345:

  Class Symfony\Bundle\FrameworkBundle\Test\WebTestCase not found and could not be autoloaded.


In Broker.php line 345:

  Class Symfony\Bundle\FrameworkBundle\Test\KernelTestCase not found and could not be autoloaded.


In Broker.php line 345:

  Class PHPUnit\Framework\TestCase not found and could not be autoloaded.
```

**Comment by vasilvestre** [comment]
The project is legacy and do not follow good practices, there's also .js files in /src ...
Is there a way to exclude directory ?

**Comment by TomasVotruba** [comment]
I see. Not yet, you can create a feature request

**Comment by vasilvestre** [comment]
Most of my problems are coming from bad practice of the project..
I created Issue for most of problems, I think the documentation need a part about a global `composer require` for Rector.
I through I had to `composer require` it to my project, this may seem easy for many, but not for newcomers..

If you are okay with it, I will close the issue there

**Comment by TomasVotruba** [comment]
Ok, thanks for lettimg me know.

Closing as original question is answered
