### ISSUE TITLE
Register invalid rule in services in config skipped, should throw exception

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#5938]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.33             |
| Installed as   | composer dependency |

Register invalid services in rector config seems skipped and not show any error, eg:

```php
<?php

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(Foo\Bar\Baz::class);
};
```

ref https://getrector.org/demo/3b3215ad-2086-4f2d-8a47-66253d989b95

## Expected Behaviour

It should throw an exception that the service not found, to avoid user not know that service already deleted/moved, eg `DeadDocBlock` moved to `DeadCode` in https://github.com/rectorphp/rector/pull/5936 , the user will not know if service already moved.

**Comment by TomasVotruba** [comment]
Closing as this should be handled in the project itself:

- by Symfony itself - https://github.com/rectorphp/rector/pull/5940#issuecomment-803630739
- by PHPStan rule for checking class existance - https://github.com/rectorphp/rector/runs/2160177167
