### ISSUE TITLE
Request service could be catched as the Rector

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#594]
Hi,

I got deprecated error `The "request" service is deprecated and will be removed in 3.0. Add a typehint for Symfony\Component\HttpFoundation\Request to your controller parameters to retrieve the request instead.` that drive me to this : 

```php
$request = $this->get('request');
```
This one is similar to [GetRequestRector](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#symfonyhttpkernel) but it look like it will be catched as [GetToConstructorInjectionRector](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#gettoconstructorinjectionrector)

It should be treated as GetRequestRector. I don't know the behaviour of this Rector as I'm not able to run it.

**Comment by TomasVotruba** [comment]
Hey,

what is diff for such a change? Something like this?

```diff
-public function someAction()
+public function someAction(Request $request)
{
-    $request = $this->get('request');
+    $request = $request;
}
```

**Comment by vasilvestre** [comment]
You have to add it to the method signature and remove it from code

**Comment by TomasVotruba** [comment]
Fixed in master, thank you :+1:

**Comment by vasilvestre** [comment]
If someone is writing a different name than $request like $oRequest, it take $oRequest to avoid breaking things in code ?
Like this :
```diff
-public function someAction()
+public function someAction(Request $oRequest)
{
-    $oRequest = $this->get('request');
}
```

**Comment by TomasVotruba** [comment]
It won't, it only affects the `$this->get('request')`:

```diff
-public function someAction()
+public function someAction(Request $oRequest)
{
-     $oRequest = $this->get('request');
+     $oRequest = $request;
}
```

The `$A = $B` cleanup is job delegated to coding standards.
