### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#5948]
# Feature Request
There are a lot of folders which are included in the composer package which could be removed and reduce the package size + increase user's local indexing, as there would be fewer files.

This could be done via `.gitattributes` file  or `archive.exclude` in `composer.json`.

**Comment by TomasVotruba** [comment]
Could you send a PR?

**Comment by olivernybroe** [comment]
What would you prefer, `.gitattributes` or `composer.json` solution?

**Comment by TomasVotruba** [comment]
What do you recommend based on your experience?
Including building prefixed Rector

**Comment by olivernybroe** [comment]
Hmm I normally see other projects going with `.gitattributes`, so I think that would be the easiest to maintain. 

Just quickly read up on how the prefixed rector works, and unfortunately this approach won't affect it. 

I think the best solution would be to write a script that deletes the files in the prefixed rector after building based on the `.gitattributes` information.

**Comment by TomasVotruba** [comment]
Sounds good :+1:

**Comment by olivernybroe** [comment]
I can see a lot of the tests classes were actually already fixed when upgrading to a newer version, as all tests were moved inside `rules-test` instead.

**Comment by TomasVotruba** [comment]
Yes, I realized we have too complicated namespace imports :) 

So I made refactoring to 2 dirs:

- https://github.com/rectorphp/rector/pull/5826
- https://github.com/rectorphp/rector/pull/5824

**Comment by olivernybroe** [comment]
That's soo awesome! 😄 
Those changes also made such big impact on the package size, so really a win-win.

**Comment by TomasVotruba** [comment]
Btw, could you compare 0.9 size and 0.10 size after those 2 refactoring? I'm curious how much it helped :)

**Comment by olivernybroe** [comment]
Rector 0.10.3 = 5.5 MB
Rector 0.9 = 10.6 MB

So about half the size 👍 That's pretty good so far

**Comment by TomasVotruba** [comment]
That's very good :+1:
