### ISSUE TITLE
Can't install rector ^0.10

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#5949]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.10              |
| Installed as   | composer dependency   |

1. Update composer.json requirement to `"rector/rector": "^0.10",`
2. Run composer update
3. Got the following errors:

```bash

  Problem 1
    - Root composer.json requires rector/rector ^0.10 -> satisfiable by rector/rector[0.10.0].
    - rector/rector 0.10.0 requires symplify/symfony-php-config ^9.2.12 -> found symplify/symfony-php-config[dev-main, 9.3.x-dev (alias of dev-main)] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Latest version in packagist for `symplify/symfony-php-config` is 9.2.11, it seems need new tag.

## Expected Behaviour

It should works.

**Comment by TomasVotruba** [comment]
I'll look into it

**Comment by TomasVotruba** [comment]
https://packagist.org/packages/symplify/symfony-php-config needed a manual update

**Comment by TomasVotruba** [comment]
Could you verify?

**Comment by samsonasik** [comment]
yes, it works now 👍 . I am closing it.
