### ISSUE TITLE
Convert "read_only" form option to attr option

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#595]
Hi,

`The form option "read_only" is deprecated since Symfony 2.8 and will be removed in 3.0. Use "attr['readonly']" instead.`

FooType.php

Before : 
```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('cuid', TextType::class, array('label' => 'CUID', 'max_length' => 8, 'read_only' => true))
    ;
}
```

After : 
```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('cuid', TextType::class, array('label' => 'CUID', 'max_length' => 8, 'attr' => ['readonly' => true]))
    ;
}
```

In the case all field in the Type are read_only, you can also make them all readonly with that

```php
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
        'attr' => ['readonly' => true],  
    ]);
}
```

**Comment by TomasVotruba** [comment]
Hey,

this is similar to:

- https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#optionnamerector
- https://github.com/rectorphp/rector/blob/master/packages/Symfony/src/Rector/Form/OptionNameRector.php

You can create a similar one, that would turn option to nested option.

**Comment by vasilvestre** [comment]
I will try it if I can run Rector in my project

**Comment by TomasVotruba** [comment]
It would be better to fork this repository, clone it and than add new Rector class with test.

**Comment by TomasVotruba** [comment]
I'm not sure what you mean.

**Comment by vasilvestre** [comment]
I mean that i can't create any Rector because Rector doesn't work with our application

**Comment by TomasVotruba** [comment]
You application and Rector code are 2 standalone code bases.

Do you mean the PHP version? You'd have to have PHP 7.1 somewhere, that's minimal requirement of this package.

**Comment by vasilvestre** [comment]
I mean that I currently can't use my free time for Rector, I have school project to finish. And my work hours can't be used for Rector if I can't use Rector on my legacy application :)

**Comment by TomasVotruba** [comment]
Well, the feature can't work untill it's coded ;)
