### ISSUE TITLE
rectorphp/rector-prefixed has a wrong tag: "${GITHUB_REF#refs/tags/}" instead of 0.10.0

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#5950]
The tag in https://github.com/rectorphp/rector-prefixed/tags came out wrong:

<img width="826" alt="Screenshot 2021-03-22 at 10 59 22 PM" src="https://user-images.githubusercontent.com/1981996/112010481-51c73e00-8b62-11eb-9b7a-9d6e193dfb12.png">

**Comment by TomasVotruba** [comment]
Oh, it should return value instead of string, thanks for lettimg me know :+1:

**Comment by TomasVotruba** [comment]
Hotifxed: https://github.com/rectorphp/rector-prefixed/tags


Todo: figure out correct tagging on release

**Comment by sabbelasichon** [comment]
@TomasVotruba I have done it with https://github.com/sabbelasichon/typo3-rector/blob/master/.github/workflows/build_scoped_typo3_rector.yaml#L48

**Comment by TomasVotruba** [comment]
@sabbelasichon Thanks for sharing. We used the same approach, but the monorepo split action takes 4-5 minutes. So much waiting for no reason :) 

Using native git speeded this up to just ~10 seconds.

Here is an example refactoring commit: https://github.com/symplify/symplify/commit/ecf651d94c79dda7b851b00fa4cdea738ba6fd51#diff-73eebd3be8ed937fb602de59bc027f6b2699949af6de3fc362e01aa5e854f0c1

I recommend the same approach there :+1:

**Comment by TomasVotruba** [comment]
Closing via https://github.com/rectorphp/rector/commit/7accd071bec191c6ff95ced1c7c5c93f7351143d#diff-23292bd9e76fae269defd8417e54b807a8579772359ae91f16ae296c6829890a
