### ISSUE TITLE
autoload file defined in Option::AUTOLOAD_PATHS not loaded

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#5951]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.10             |
| Installed as   | composer dependency |

## Minimal PHP Code Causing Issue

Start from rector 0.10, somehow, the autoload defined in Option::AUTOLOAD_PATHS not loaded. Example repo for it:

https://github.com/samsonasik/rector-issue-010-autoload

The command:

```
vendor/bin/rector process system/Fixture/SomeClass.php --debug
```

should exit early as in the `system/bootstrap.php` ,it exits early via:

```php
<?php

die;
```

Autoload file should executed. There are some `require_once` not executed in the `system/bootstrap.php` even `die;` removed:

```php
require_once __DIR__ . '/Common.php';
require_once __DIR__ . '/CLI.php';
```

## Expected Behaviour

I guess it related with Static Reflection started in 0.10, which possibly make `require_once` ignored.

Ref issue https://github.com/codeigniter4/CodeIgniter4/pull/4468

**Comment by samsonasik** [comment]
@TomasVotruba it possibly related with usage of `DynamicSourceLocatorProvider` somewhere here:

https://github.com/rectorphp/rector/blob/de14023b881e8e63285080066f80f38709176595/packages/NodeTypeResolver/Reflection/BetterReflection/SourceLocatorProvider/DynamicSourceLocatorProvider.php#L56-L77

**Comment by samsonasik** [comment]
Temporary solution is by add autoload file outside rector config with early require_once ref https://github.com/codeigniter4/CodeIgniter4/pull/4468/commits/1eb86d89ad75c5596807ce5fa385837bb7d6d051

**Comment by leoloso** [comment]
I'm having the same issue, `Option::AUTOLOAD_PATHS` is not loading the files.

**Comment by TomasVotruba** [comment]
I'm looking in PHPStan implementaiton. They have option to include files, e.g. to load constants. Maybe we should have that too:
https://phpstan.org/user-guide/discovering-symbols#global-constants

Failing test case in Rector would be helpful

**Comment by TomasVotruba** [comment]
This will fix it:
https://github.com/rectorphp/rector/pull/5964

**Comment by leoloso** [comment]
@TomasVotruba It supposed to be working on the latest v0.10.3, right? Because it does not.

Check:

Using Rector's latest version: https://github.com/leoloso/PoP/pull/537/checks?check_run_id=2182321099#step:5:130

Error still happening: https://github.com/leoloso/PoP/pull/537/checks?check_run_id=2182321099#step:6:16790

That error `"Class WP_List_Table not found."`, that class is loaded in the autoload path...

**Comment by TomasVotruba** [comment]
No the old approach, you need to change the config from autoload to includes:
https://github.com/codeigniter4/CodeIgniter4/pull/4481/files

**Comment by leoloso** [comment]
Yep, using `Option::BOOTSTRAP_FILES` works, thanks!
