### ISSUE TITLE
Incorrect behavior of RemoveDeadInstanceOfRector - Removing instanceof checks in traits

### ISSUE THREAD

**Issue by addshore** [rectorphp/rector#5952]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/b7384c80-7087-4fdc-b350-c585959ac567

```php
<?php

interface HasA{
    public function getA();
}
trait A {
	public function getA(){
		return "A";
	}
}
trait B {
    public function getB(){
        if($this instanceof HasA) {
        	return $this->getA();
        }
    }
}
class C implements HasA {
    use A;
    use B;
}
class D{
    use B;
}

echo (new C())->getB();
echo (new D())->getB();
```

### Responsible rules

* `RemoveDeadInstanceOfRector`

## Expected Behavior

Having such an instance of check should be allowed.
The code example demonstrates this as valid PHP https://3v4l.org/8Mg3b

**Comment by TomasVotruba** [comment]
Thanks for reporting and the 3v4l.org example, I used it as a test fixture :+1:
