### ISSUE TITLE
Incorrect behavior of AddArrayReturnDocTypeRector - Second @return doc added, instead of replacing existing doc

### ISSUE THREAD

**Issue by addshore** [rectorphp/rector#5954]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/5883f3a5-c835-4fee-af3b-9c8b4d05cc51

```php
<?php

use Addwiki\Mediawiki\DataModel\Content;
use Addwiki\Mediawiki\DataModel\EditInfo;
use Addwiki\Mediawiki\DataModel\PageIdentifier;
use Addwiki\Mediawiki\DataModel\Revision;
use Addwiki\Mediawiki\DataModel\Title;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class DemoFile
{
    /**
      * @return array<int, array<int|string|Content&MockObject|EditInfo&MockObject|PageIdentifier|null>>
     */
	public function provideValidConstruction(): array {
		$mockEditInfo = $this->getMockBuilder( EditInfo::class )
			->disableOriginalConstructor()
			->getMock();
		$mockTitle = $this->getMockBuilder( Title::class )
			->disableOriginalConstructor()
			->getMock();

		return [
		[ "a", new PageIdentifier( $mockTitle ), 1 , $mockEditInfo, 'foo', null ],
		[ 1, new PageIdentifier( $mockTitle, 3 ), 1 , $mockEditInfo, 'foo', '20141212121212' ],
		];
	}
}
```

### Responsible rules

* `AddArrayReturnDocTypeRector`

## Expected Behavior

The new doc that is added by rector would be the only `@return` doc left after the change

**Comment by TomasVotruba** [comment]
I'm looking into this

**Comment by TomasVotruba** [comment]
This one was hard candy... it seems the PHPStan fails on the docblock with invalid tag: https://phpstan.org/r/fc5f486f-4c87-4dda-8ffd-bc60cacd90ce

The @return tag is then evaluated as `InvalidTagValueNode`, thus the "replacemenet" duplication

To make it work, you have to update the original syntax with (...)

```diff
+* @return array<int, array<int|string|Content&MockObject|EditInfo&MockObject|PageIdentifier|null>>
-* @return array<int, array<int|string|(Content&MockObject)|(EditInfo&MockObject)|PageIdentifier|null>>
```

**Comment by TomasVotruba** [comment]
Here is exact PHPStan message: 
![image](https://user-images.githubusercontent.com/924196/114215674-287e1e80-9966-11eb-88ba-ce4b6018696d.png)

I strongly recommend running PHPStan on your project first. This will prevent many bugs
