### ISSUE TITLE
Can Rector check that the PHP version in the code is the right one?

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#5963]
# Question

I'm downgrading code from PHP 8.0 to 7.1. Then, I want to test that the downgraded code is all compatible with 7.1 (eg: it doesn't contain features for which there are no rules to downgrade them, such as annotations).

My idea is to run `rector/rector-prefixed` on the downgraded code, expecting that, if there's any 7.2+ code, Rector will throw an error.

But it doesn't always work!

For instance, if running Rector on PHP 7.2 on source code with:

✅ the `match` operation (from PHP 7.4), then Rector throws an error (new syntax)

❌ doing `[&$a, [$b, &$c]] = $d;` (which is the "Array Destructuring supports Reference Assignments" feature, from PHP 7.3), then Rector doesn't complain, and it processes the file (all syntax already existing in PHP 7.2)

Is there any way to make Rector throw an error in this latter case?

i.e. Could Rector somehow validate that the source code is valid PHP code?

**Comment by TomasVotruba** [comment]
We handle this with PHP-linter - that is the fastest and safest way to validate code run on specific PHP version:  https://github.com/rectorphp/rector/blob/2d469d30680c30a577ef7661c02748774ad29c73/.github/workflows/build_scoped_rector.yaml#L49-L55

**Comment by leoloso** [comment]
Thanks, I'll check it out.

I'll let you know if it works well, please don't close this issue yet.

**Comment by leoloso** [comment]
Alright, with PHP Parallel Lint it worked beautifully. Thanks!

**Comment by TomasVotruba** [comment]
Glad it helped :+1:
