### ISSUE TITLE
Add backslashes when a class is not found

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [rectorphp/rector#5966]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.10.0              |
| Installed as   | composer dependency                  |

When a class extends another class without a use statement, Rector adds backslashes to the extended class but it also adds backslashes to other parts like `true` `null`.
Instead, if the class is found it doesn't add any backslashes.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/d5d405d5-5b7d-4fed-84bd-feb44f5b611d

## Expected Behaviour

Is it possible to avoid adding backslashes to `true`, `null` etc?
It could be ok to add backslashes to extended class but I  am not expecting backslashes in other parts.

Thanks

**Comment by TomasVotruba** [comment]
Hi,

thanks for repoting. This file should be skipped completely, as all class must present.

We use PHPStan static reflection here and it would be also skipped: https://phpstan.org/r/cda68ee1-e159-49b8-9ab6-2d3f1b5d2d93

I'm looking into how skip errored files completely

**Comment by AlessandroMinoccheri** [comment]
Ok, let me know If I can help with something.

**Comment by TomasVotruba** [comment]
Thanks :+1: 

It should be fixed now via https://github.com/rectorphp/rector/pull/5967
