### ISSUE TITLE
Remove requirement of framework specific rectors

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#5976]
# Feature Request

I love that we now have packages for the framework specific rectors, however I think we could benefit from removing them as a requirement in the base of rector.

E.g. I am a Laravel developer, so I really don't need to have `cakephp` and so on rectors included in my codebase. 

## Pros
Smaller package size
For me, as I would only require the Laravel rector package, my filesize would be reduced with about 1.2 MB 👍 

## Cons
User's having to require another package before they can use rector. + would this work correctly when using prefixed rector?

**Comment by samsonasik** [comment]
The inclusion seems currently used to avoid direct BC break, see deprecation at:

https://github.com/rectorphp/rector/blob/e776d753efb775f769916e66b1848d93143f93ae/packages/Set/ValueObject/SetList.php#L30-L35

Also, on set usage, removing it  means the  `VerifyRectorServiceExistsCompilerPass` will need to have updated message when service not found, eg:

https://github.com/rectorphp/rector/blob/e776d753efb775f769916e66b1848d93143f93ae/src/DependencyInjection/CompilerPass/VerifyRectorServiceExistsCompilerPass.php#L29

for more verbose message, like addition information:

```
You may need to find in separate rector rules package (installable via composer):

- rector/rector-cakephp
- rector/rector-laravel
...
```

**Comment by TomasVotruba** [comment]
Hi @olivernybroe ,

that's something we plan for one of next releases. We wan't to take it step by step, so community adapts the change slowly.

The hard question now is:

- How can we allow use of parackaes like `rector/rector-phpunit` in prefixed/PHP 7.1 downgraded version?

**Comment by lulco** [comment]
Hi all,
imho the main problem is we need to allow rector/rector-* packages to work with rector/rector and also with rector/rector-prefixed version right?

If not, stop reading and ignore next lines :D

So we need something like `or` in composer:
```
"require": {
    "rector/rector or rector/rector-prefixed": "^0.10"
}
```
There are several issues about this problem in composer repository and there is also one solution it could work (I've never use it just read about it):
https://github.com/composer/composer/issues/751#issuecomment-148745204

If both packages rector/rector and rector/rector-prefixed will provide the same "interface" like:
```
"provide": {
    "rector/rector-abcdefg": "0.10.3" // TODO find the name instead of abcdefg, TODO try if version could be self.version
}
```
Then all rector/rector-* packages could require this "rector/rector-abcdefg" and the final decision of what will be installed is up to user (or script) if he/she/it will require rector/rector or rector/rector-prefixed

**Comment by olivernybroe** [comment]
@lulco Yes, so that problem could be fixed by a package named something like `rector/rector-contracts`.

However, the next problem is that the packages are not written in PHP 7.1, however `rector/rector-prefixed` is downgraded to `7.1`, so we need a way to handle all the packages which are written in another version and use rector to downgrade them to `7.1` and have that as a separate package. 
This might have to be `rector/rector-laravel-prefixed` and so on, and then some GitHub actions to do the work for us.

**Comment by lulco** [comment]
@olivernybroe hm, I forgot that PHP7.1 thing :) If there will be rector/rector-*-prefixed, imho there is no need for rector/rector-contracts.

Another solutions are 1) to write rector and packages directly in PHP 7.1 or 2) do not support this version at all

**Comment by olivernybroe** [comment]
@lulco I don't think writing the packages in PHP 7.1 is a nice solution. It seems like something that will give other issues down the road 👍 

As the prefixed rector already is bundled, I think it shouldn't matter that all the packages are pre-bundled into it. If people want lower file size, then don't use the prefixed bundle.

**Comment by lulco** [comment]
Well, for example I don’t want to use prefixed Rector but I have to because of conflicts with symfony packages used in Rector and my projects. And I also would like to have only Rector packages I need. No laravel, no symfony etc.

**Comment by olivernybroe** [comment]
Hmm, yeah I guess the best solution for that would then be to "simply" have a rector/rector-*-prefixed for each of the packages then.

**Comment by lulco** [comment]
Yeah probably

**Comment by TomasVotruba** [comment]
First step towards decoupling https://github.com/rectorphp/rector/pull/6174

**Comment by TomasVotruba** [comment]
After few dicussions with active rule users, I've came to conclusion that priority is in simple Rector use with 1 package - downgraded and prefixed. Making users to downgrade their own package would require tremendeous effort from them. Let's keept it simple.

We might come back to this in the future, when it changes.

**Comment by sabbelasichon** [comment]
I totally agree. I think the same.

**Comment by olivernybroe** [comment]
Hi @TomasVotruba, 

I just wanna understand completely here, does that mean you will drop `rector/rector` and only have `rector/rector-prefixed` in the future?

**Comment by TomasVotruba** [comment]
@olivernybroe Hi, I have not decided yet, but I think it's quite possible that it will happen. As PHPStan did in PHPStan 0.12 https://phpstan.org/blog/phpstan-0-12-released#phar-distribution-by-default

It would definitelly remove most of WTF on old and conflicting projects.

But we're still 2 version away and Rector needs to grow up a bit :)
