### ISSUE TITLE
Incorrect behavior of RenameForeachValueVariableToMatchExprVariableRector when the expression variable is predefined variable

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/rector#5977]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/18d18b97-037e-4fec-9323-6f304e970b34

```php
<?php

final class DemoFile
{
    public function run()
    {
        foreach ($_FILES as $file) {
            dump($file);
        }
    }
}
```

### Responsible rules

* `RenameForeachValueVariableToMatchExprVariableRector`

## Expected Behavior

Nothing needs to be changed

**Comment by samsonasik** [comment]
The issue seems not a handling predefined variable, but `$_` prefix, eg:

```php
foreach ($_FOO as $file) {

}
```

it will changed to:

```php
foreach ($_FOO as $) {

}
```

as well. see https://getrector.org/demo/d1dce0c9-6d3f-4fbb-9a00-c2748affb4b8
