### ISSUE TITLE
[Downgrade 8.0] Union Type downgrade on anonymous functions

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#5989]
# Feature Request

`DowngradeUnionTypeDeclarationRector` is currently not handling anonymous functions, so it must be completed.

I can work on it.
 
## Diff 

```diff
$ids = array_map(
-    function (int | string $id) {
+    function ($id) {
        return 'v' . $id;
    },
    $ids
);
```

**Comment by TomasVotruba** [comment]
Go for it :+1:

**Comment by leoloso** [comment]
@TomasVotruba I offered to do it 1 month ago, when I had a window of time. Now I'm pretty busy. So please wait some 45 days, when I finish my deadline.

Otherwise, your team can also do it (this one will take you guys like 3 min to do).

Same with #5961.

Also, I just found out that the `mixed` type in anonymous functions is also not being downgraded:

```php
$foo = array_filter(
  $list,
  // This needs be removed for PHP 7.1, currently it is not
  function (mixed $fieldArgValue) {
    return is_null($fieldArgValue);
  }
);
```

And maybe there are other things in anonymous functions that need be downgraded?

**Comment by TomasVotruba** [comment]
For a bugfix just send PR next time, no need to create issues that stale ;)

**Comment by TomasVotruba** [comment]
Closing as we don't use union types in downgraded Rector yet. Feel free to contribute :+1:
