### ISSUE TITLE
How can I get the constructor args from a New_?

### ISSUE THREAD

**Issue by jdart** [rectorphp/rector#6001]
I'm using `\Rector\Transform\Rector\StaticCall\StaticCallToMethodCallRector` which adds a parameter to the class constructor. I was thinking I'd need to write a new Rector to add the new parameter in unit tests where the class would be constructed by hand. My first attempt was to look through all `Node\Expr\New_` but I can't figure out how to get and look at the signature of the constructor to see if I need to modify anything. Is that a good way to go about solving adding the parameter or is there a better way?

**Comment by TomasVotruba** [comment]
Hi, we have a repository dedicated to node overview, that is exactly for these questions :)

Here, see `New_` node:
https://github.com/rectorphp/php-parser-nodes-docs#phpparsernodeexprnew_

**Comment by jdart** [comment]
Thanks @TomasVotruba ... it just occurred to me that I could use normal php reflection to get the parameters of the constructor... does that sound like the way to go?

**Comment by TomasVotruba** [comment]
:+1: 

Reflection can be used too. We're not using native PHP reflection, but static reflections based on better-reflection package: https://github.com/rectorphp/rector/pull/5665
