### ISSUE TITLE
Setting Option::FILE_EXTENSIONS does not preserve .php suffix

### ISSUE THREAD

**Issue by mglaman** [rectorphp/rector#6008]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector dev-main@{no ref              |
| Installed as   | Project dependency                           |

In https://github.com/palantirnet/drupal-rector/pull/134 we are upgrading to Rector 0.10. We add the Drupal-specific file extensions, however, it turned out nothing was being processed. We set the file extensions without including `.php` and it turns out, this caused nothing to process.

## Minimal PHP Code Causing Issue

Configuration

```
    $parameters->set(Option::FILE_EXTENSIONS, [
      'module',
      'theme',
      'install',
      'profile',
      'inc',
      'engine'
    ]);
```

## Expected Behaviour

While adding custom file extensions, I would expect `.php` to still be analyzed.

**Comment by TomasVotruba** [comment]
Hi,

the 'php' must be in file exensions explicitly. Any other behavior would be too magical and impossible to exclude.
