### ISSUE TITLE
Undefined constant 'PREG_UNMATCHED_AS_NULL' on rector-prefixed build php 7.1

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6013]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |
| Installed as   | latest rector prefixed repository                           |

Current generated rector-prefixed got the following error on php 7.1:

![Screen Shot 2021-03-30 at 02 09 04](https://user-images.githubusercontent.com/459648/112887137-fe726400-90fc-11eb-84ae-3217bc9fa3b7.png)

I can't find define `PREG_UNMATCHED_AS_NULL` on symfony polyfill 7.2. It seems the solution is add custom define constant for it.

@TomasVotruba what do you think?

**Comment by samsonasik** [comment]
Even `PREG_UNMATCHED_AS_NULL` exists, it seems the functionality will not working as expected in php 7.1. The possible solution is set the PHP version to 7.1.

Possible path that can be changed:

https://github.com/rectorphp/rector/blob/c060086f69575172502e79d4c1ff340b587167d3/.github/workflows/build_scoped_rector.yaml#L28

@TomasVotruba what do you think?

**Comment by samsonasik** [comment]
It seems set ` php-version: 7.3` very first is not the solution, as it read root composer.json first. So must be 7.3 first.

**Comment by samsonasik** [comment]
another solution is possibly create a downgrade php 7.2 rule to handling it.

**Comment by TomasVotruba** [comment]
> another solution is possibly create a downgrade php 7.2 rector rule to handle it.

That's a way to go, as we need to code run on PHP 7.1, where this constant does not exist.
