### ISSUE TITLE
Error on T_NS_SEPARATOR when processing files

### ISSUE THREAD

**Issue by Guikingone** [rectorphp/rector#6024]
# Bug Report

| Subject            | Details                                                                                                    |
| :-------------  | :---------------------------------------------------------------|
| Rector version | e.g. v0.10.3                                                                                        |
| Installed as      | prefixed Rector                                                                                     |

## Minimal PHP Code Causing Issue

Hi Rector team 👋🏻 

I'm facing an issue when using a prefixed version of Rector, using the following configuration file: 

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Doctrine\Set\DoctrineSetList;
use Rector\Set\ValueObject\SetList;
use Rector\Symfony\Set\SymfonySetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_73);

    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__ . '/vendor/autoload.php',
    ]);

    $parameters->set(Option::PATHS, [
        __DIR__ . '/src',
    ]);

    $parameters->set(Option::SKIP, [
         // ...
    ]);

    $parameters->set(Option::SETS, [
        DoctrineSetList::DOCTRINE_25,
        SetList::DEAD_CODE,
        SetList::PHP_70,
        SymfonySetList::SYMFONY_34,
    ]);

    $parameters->set(Option::ENABLE_CACHE, true);
    $parameters->set(Option::CACHE_DIR, __DIR__ . '/var/rector_cache');

    $parameters->set(
        Option::SYMFONY_CONTAINER_XML_PATH_PARAMETER,
        __DIR__ . '/var/cache/dev/appDevDebugProjectContainer.xml'
    );
};

```
And using `rector process --config rector.php`, the following errors occurs on several files:

```bash
[ERROR] Could not process "path_to_file.php" file, due to:                
         "Syntax error, unexpected T_NS_SEPARATOR, expecting ';' or '{':3".
```

## Expected Behaviour

The files must be analyzed without throwing an error.

Thanks again for the help and have a great day 👋🏻

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by TomasVotruba** [comment]
Closing for missing test fixture. We cannot do much without it :)
