### ISSUE TITLE
Infinite loop with Undefined offset: -2 in PhpDocInfoPrinter.php on line 268

### ISSUE THREAD

**Issue by ChristianRiesen** [rectorphp/rector#6026]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector dev-master@aa36ff4 |
| Installed as   | Docker image 7.4-latest                      |

I restricted to run it on a single file, which breaks in a strange way.  It does 4 lines (which I don't understand thy it's 4 on a single file) and then seems to be done, but the notice happens. This notice then happy counts up to inifinity, going -1 each loop. This is the log I got out from a run:

```
docker :  0/4 [ΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæ]   0%
At line:1 char:1
+ docker run --rm -v ${PWD}:/project rector/rector:latest-php7.4 proces ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ( 0/4 [ΓûæΓûæΓûæ...ΓûæΓûæΓûæ]   0%:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
 2/4 [ΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæΓûæ]  50%
 3/4 [ΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûæΓûæΓûæΓûæΓûæΓûæΓûæ]  75%
 4/4 [ΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûôΓûô] 100%Notice: Undefined offset: -1 in /rector/packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php on 
line 268
Notice: Trying to access array offset on value of type null in /rector/packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php on line 268
Notice: Undefined offset: -2 in /rector/packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php on line 268
Notice: Trying to access array offset on value of type null in /rector/packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php on line 268
```

I have not found anything on here or on google using the last part of the error message that would bring me closer to a solution.

The file has clear parts that probably should be changed (using TypedPropertyRector as service as the only setting in rector.php) but nothing is altered.

## Minimal PHP Code Causing Issue

Tried reproducing it, but it doesn't seem to cause that issue on the demo page: https://getrector.org/demo/216151c4-c4b8-4f87-93bf-df0df2843120

## Expected Behaviour

Change the var annotations to 7.4 typed properties. Not infinite loop in PhpDocInfoPrinter

**Comment by ChristianRiesen** [comment]
I went into it by hand and replaced the `@var` anotations with properties, ran it again and the bug did not happen. As soon as one of them (tried with id at the top and completed property at the bottom) has the var annotation without also having the 7.4 declaration it crops up. So even if there is a var header, but the property already has a declaration then it passes. I hope there is something that I can do to avoid this bug as I would not want to change all these files by hand :)

**Comment by samsonasik** [comment]
@ChristianRiesen I can't reproduce in latest `dev-main`, please try update rector require-dev to:

```json
    "rector/rector": "dev-main"
```

**Comment by ChristianRiesen** [comment]
@samsonasik It's happening with the docker container 7.4-latest tag.
The host is a window box if that makes any difference, but shouldn't really. It's also quite a bit slower than if you use it with composer.

Because of dependency hell I couldn't install it directly. I tried some lower versions but none would fly. Then I went a completely different route, by making a new dir, do `composer require rector/rector` in it, and copy the tests and src folder over. Then add dependencies to that so rector could find the libraries that the code actually depended on. That gave me a decent output, still lots of errors and cases it didn't catch though.

Maybe a 7.4-nightly tagged container would be interesting? I gladly do more testing on this, as I think that would be the ideal use case for my needs.

**Comment by TomasVotruba** [comment]
Try https://github.com/rectorphp/rector-prefixed to avoid install conflicts.

We'll need a reproductible repository with failing GitHub Action.

**Comment by ChristianRiesen** [comment]
The prefixed version didn't work either for me, that's why I hoped to use the docker container in a reliable fashion. I have not been able to reproduce this issue online somewhere, it happens only locally on my machine, which should not make a difference with the docker container. I will spend some more time on this and see if I can find something. If not I will just close the ticket.

My hope was that this error maybe points to something that could have gone under somewhere, like an under run or missing extra check, even if you can't 100% reproduce it right now, could be worth taking a look in that code and what calls it that could lead to such an output.
