### ISSUE TITLE
Use of `is_countable()` in `CountOnNullRector`

### ISSUE THREAD

**Issue by MarkBaker** [rectorphp/rector#6027]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.10.3              |
| Installed as   | composer dependency                           |

Running rector with `SetList::PHP_71` includes the `CountOnNullRector`; but this is replacing the count on null using the `is_countable()` function, which is not available until PHP 7.3, and therefore it updates the code with a function that will fail when run against the targeted version of PHP 7.1.

The currently generated diff is:

```php
-            $argc   = count($args);
+            $argc   = is_countable($args) ? count($args) : 0;
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f1fb39a0-baef-4f6e-825a-601745785c1c

## Expected Behaviour

Perhaps as actually [documented](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#countonnullrector)

```php
-$count = count($values);
+$count = count((array) $values);
```

**Comment by samsonasik** [comment]
You need to add: 

```php
use Rector\Core\ValueObject\PhpVersion;

// ... 
$parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_71);
```

see https://getrector.org/demo/2a60365f-1ee3-4f59-8123-cee7ca486682 . It actualy checked at : 

https://github.com/rectorphp/rector/blob/1224a69c8a4bbf7a16b5e588da28dea13ae2ccb2/rules/Php71/Rector/FuncCall/CountOnNullRector.php#L123
