### ISSUE TITLE
is there a way for the following: explain loaded rules, only run save rules

### ISSUE THREAD

**Issue by sunnysideup** [rectorphp/rector#6028]
Love your work.

here are two questions:

1. is there a way to only run save rules - I am running this right now: https://github.com/sunnysideup/silverstripe-easy-coding-standards/blob/master/rector.php#L47-L71. I want to just make my code super awesome smart without introducing any breaking changes.  I found the rules I excluded to that, but I found these by basically going through change-sets. I am trying to build a rule-set for Silvestripe.org

2. is there  a way to show all the config loaded rules with their explanations - show `getRuleDefinition` for all rules loaded: `rector show` with extras basically ;-))

**Comment by lulco** [comment]
Hi @sunnysideup!

To number 2. answer is probably here https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md

**Comment by sunnysideup** [comment]
@lulco - I was hoping for a list of the rules I have loaded with my config ....

**Comment by lulco** [comment]
They are in `rector show`, maybe there are some links when running with -vvv or you can send PR :)

**Comment by TomasVotruba** [comment]
Hi @sunnysideup !

The 2. was answered https://github.com/rectorphp/rector/issues/6028#issuecomment-812880197 by @lulco 


The 1. that is responsibility of each rule and its author. You can split it into 2 sets, eg. `SILVERSTIRPE_09` and `SILVERSTIRPE_09_SAFE`, running the latter first.

**Comment by sunnysideup** [comment]
Thank you ... What does the 09 stand for?

**Comment by TomasVotruba** [comment]
It's a version I made up :). E.g. this is how set for Nette upgrade looks like: https://github.com/rectorphp/rector-nette/blob/main/src/Set/NetteSetList.php

You can copy it's structure for Silverstripe, as it's a package that focuses purely on 1-framework upgrade
