### ISSUE TITLE
How rector works?

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#6030]
# Question
I'm using rector few months now, but sometimes I still don't understand how it works 👼 🤣 

- What is the order of rules execution? Can I change it somehow in rector.php config - switching lines where they are configured? How it works with imports?
- When the analysis of node types is executed? Is it updated after some rename / remove rectors (like RenameClassRector or RemoveInterfacesRector) are executed?

**Comment by lulco** [comment]
It looks like node types are not updated after some rectors are executed https://github.com/rectorphp/rector/pull/6035

**Comment by TomasVotruba** [comment]
Hi @lulco, don't worry, that's quite allright :).
It took me 6 months to understand how php-parser works :D 

> What is the order of rules execution?

Rector is build on php-parser traversing, from top to bottom. I would only copy-paste its documentation:
https://github.com/nikic/PHP-Parser/blob/master/doc/component/Walking_the_AST.markdown

Basically, namespace is traversed first, then class is traversed, then class's methods, then methods arguments, then methods inner lines, then ifs/whiles inside the methods... etc.

> When the analysis of node types is executed? Is it updated after some rename / remove rectors (like RenameClassRector or RemoveInterfacesRector) are executed?

Answer to this question is in this class: https://github.com/rectorphp/rector/blob/fb1e74615780a4bb196e8dca96dd0eaff35748e2/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php#L95

The files are parsed to nodes, then nodes are decorated with names/types/parent nodes/FQN names etc.

Then the Rector rules are run. It's described here: https://github.com/rectorphp/rector/blob/main/docs/how_it_works.md#2-parse-and-reconstruct-1-file

**Comment by TomasVotruba** [comment]
> It looks like node types are not updated after some rectors are executed #6035

That is correct. Mostly because the Rector rules are run just once on everyfile and once node is changed, it won't be refactored.

**Comment by TomasVotruba** [comment]
If you want, we can get a 15-min call to help you dive in Rector faster. It would be more effective for me and you could ask ad-hoc questions :).

**Comment by lulco** [comment]
> If you want, we can get a 15-min call to help you dive in Rector faster. It would be more effective for me and you could ask ad-hoc questions :).

@TomasVotruba sure, that would be great. We can manage it right after I will go back to work :)

**Comment by TomasVotruba** [comment]
Related: I've just added automated re-adding parent nodes on changed node:
https://github.com/rectorphp/rector/pull/6057
Works pretty well, also discovered 2 bugs :) 

Same approach can be used for other attributes too

**Comment by TomasVotruba** [comment]
Nono, that only fixes parent nodes.

**Comment by TomasVotruba** [comment]
Closing as original 2 questoins were answered :+1:
