### ISSUE TITLE
Help the user find the node type they should target

### ISSUE THREAD

**Issue by matthiasnoback** [rectorphp/rector#6041]
# Feature Request

This is somewhat of a DX idea: when I create a new rule, I provide an empty array as return value of `getNodeTypes()`. I just don't know what type to choose! I do have a certain transformation in mind, including before and after code. Here's a suggestion: when you run the test for a rule that returns no node types, Rector would parse the "before" snippet and print out the nodes, to assist the user in selecting the right node type.

Part 2: If Rector notices you have no implementation for `refactor()` either, it will parse the "after" snippet and print out the nodes, to help you model the manipulations you should do in `refactor()`.

**Comment by TomasVotruba** [comment]
This is hard for me to imagine as I'm used to use nodes here and in PHPStan.
But if you can implement it prototype, we can add it
