### ISSUE TITLE
Incorrect behavior of ChangeReadOnlyPropertyWithDefaultValueToConstantRector

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/rector#6044]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

Similar as #4959

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/c2fe122c-152a-4fec-90c2-9f6be9929614

```php
<?php

final class DemoFile
{
    private $items = [];
    public function run()
    {
        $this->set($this->items, 'foo', 'bar');
    }
    
    public function set(&$array, $key, $value)
    {
        $array[$key] = $value;
        return $array;
    }
}
```

### Responsible rules

* `ChangeReadOnlyPropertyWithDefaultValueToConstantRector`

## Expected Behavior

Nothing needs to be changed

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by zingimmick** [comment]
> Thank you for your report and demo link!
> 
> Could you send a failing test case in a pull-request, so we have it covered in Rector?
> Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

Failing test #6048
