### ISSUE TITLE
Rector unable to process PHP native class ?

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#605]
A part of my code use ZipArchive(); a native library of PHP.
Rector can't proceed to this part of the code as the class isn't loaded by Composer (and isn't supposed to)

What to do ?

**Comment by TomasVotruba** [comment]
What exactly do you need to do?

**Comment by vasilvestre** [comment]
Proceed my class, here's a sample : 
```php
<?php
use ZipArchive;

class DownloadController extends ItisanooController
{
    function zipFlux($sFileNameFlux, $sFileFullPath, DateTime $time_start, $sUrlZip)
    {
        $oZip = new ZipArchive();
        ....
    }
}
```

ZipArchive is a php native library and rector have error loading this class

**Comment by TomasVotruba** [comment]
I see. That should be possible, I'll look on it.

**Comment by TomasVotruba** [comment]
That happens :)

Exception is a good idea :+1: . Could you prepare some PR where would you expect such exception and how it should be detect?

**Comment by vasilvestre** [comment]
I do ! At least, I try

**Comment by TomasVotruba** [comment]
Closing as original issue is resolved.
