### ISSUE TITLE
PHP Notice from PHP 7.0 rule PHP4Constructor

### ISSUE THREAD

**Issue by aka-tpayne** [rectorphp/rector#6062]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.10.3              |
| Installed as   | composer dependency                           |

Notice: Undefined property: PhpParser\Node\Stmt\For_::$expr in vendor/rector/rector/rules/Php70/Rector/ClassMethod/Php4ConstructorRector.php on line 148

Several classes under PhpParser\Node\Stmt: For, Nop, While, If, 

## Minimal PHP Code Causing Issue

```php
/** @var Expression $methodStmt */
foreach ($classMethod->stmts as $methodStmt) {
    $methodStmt = $methodStmt->expr;
    if (! $methodStmt instanceof StaticCall) {
        continue;
    }

    $this->processParentPhp4ConstructCall($methodStmt);
}
```

## Expected Behaviour
Not display a notice.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by aka-tpayne** [comment]
@TomasVotruba I'm going to assume you don't need that demo now? 😄

**Comment by TomasVotruba** [comment]
You're right :D but next time it would save us lot of time. Code is worth thousands words  :+1:
