### ISSUE TITLE
@param/@throws space after type should be ignored by rector

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6065]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. dev-main             |
| Installed as   | composer dependency                          |

Hi @TomasVotruba I tried rector `dev-main` in CodeIgniter4 project, as current `1.10.3` is hang. The `dev-main` is working ok, but it cause removal of spaces, like the following:

```diff
-	 * @throws             Exception
+	 * @throws Exception
```

ref https://github.com/codeigniter4/CodeIgniter4/pull/4538#issuecomment-816759159

which the multi space should be ignored. On debugging, I found that the auto import option:

```php
$parameters->set(Option::AUTO_IMPORT_NAMES, true);
```

cause it. I tried to create failing fixture for it, but it showing ok:

![Screen Shot 2021-04-09 at 22 40 16](https://user-images.githubusercontent.com/459648/114205529-933e5280-9984-11eb-818d-aa6a9871a3de.png)

![Screen Shot 2021-04-09 at 22 39 07](https://user-images.githubusercontent.com/459648/114205352-6b4eef00-9984-11eb-937a-0071b994c593.png)

It possibly due to post rector ?

**Comment by TomasVotruba** [comment]
It happens in this method: https://github.com/rectorphp/rector/blob/fae4a7512e36a0ee203d1c963ebe6f19dbcc9f13/packages/NodeTypeResolver/PhpDocNodeVisitor/NameImportingPhpDocNodeVisitor.php#L94

The node is imported and replaced by another node, so it's reprinted again with new spacing.
It should be skipped on no change instead

**Comment by samsonasik** [comment]
Thank you, I will check.
