### ISSUE TITLE
Replace `isset` with `!== null`

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6066]
# Feature Request

the [latest phpstorm release](https://blog.jetbrains.com/phpstorm/2021/04/phpstorm-2021-1-release/) contains a nice refactoring:

> Using the isset() function is only effective for arrays and variables. In all other cases, it makes sense to verify whether the operand is not null. Use Alt+Enter to replace isset() checks with null checks.

code like

```php
<?php

final class DemoFile
{
    public function run()
    {
        $b = new DemoFile();
        if (isset($b->x())) {
          echo "x";
        }
        return 5;
    }
    public function x() {
    }
}
```

should be turned into a null check:
 
## Diff 

```diff
-if (isset($b->x())) {
+if ($b->x() !== null) {
```

-----

btw: I tried to run this code on https://getrector.org/demo but got a syntax error, not sure why

![grafik](https://user-images.githubusercontent.com/120441/114210184-c15d6b80-995f-11eb-9fc4-386cb69a4349.png)

**Comment by TomasVotruba** [comment]
Not sure why the syntax is wrong :thinking: , probably some glitch in validation service.

We're currently busy with other topics, like https://github.com/rectorphp/rector/issues/6079, so we won't have time for it.

Would you like to contribute it?

**Comment by staabm** [comment]
I will give it a try

**Comment by TomasVotruba** [comment]
Feel free to send PR whenever ready :+1: 
Closing to keep focus on active bugs.
