### ISSUE TITLE
Composer problem

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#6071]
# Question
I just pulled main branch to create some pull requests and after running composer update, I got this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rector/rector 0.9.x-dev -> satisfiable by rector/rector[0.9.x-dev].
    - rector/rector-doctrine 0.10.2 conflicts with rector/rector[0.9.x-dev].
    - Installation request for rector/rector-doctrine ^0.10.2 -> satisfiable by rector/rector-doctrine[0.10.2].
```

When removing rector-doctrine from composer I got:
```
  Problem 1
    - Installation request for rector/rector 0.9.x-dev -> satisfiable by rector/rector[0.9.x-dev].
    - rector/rector-phpunit 0.10.6 conflicts with rector/rector[0.9.x-dev].
    - Installation request for rector/rector-phpunit ^0.10.6 -> satisfiable by rector/rector-phpunit[0.10.6].
```

I don't understand what the rector/rector[0.9.x-dev] means in this context. There is
```
"extra": {
        "branch-alias": {
            "dev-main": "0.10-dev"
        }
    },
```
in composer...

Do you have any idea how to fix it?

**Comment by TomasVotruba** [comment]
I'll check it

**Comment by TomasVotruba** [comment]
Could you provide steps to reproduce including PHP version?

This works for me (PHP 8):

```bash
git clone git@github.com:rectorphp/rector.git --depth 1
cd rector
composer install
```

**Comment by lulco** [comment]
PHP 7.4
Composer version 1.10.21

Deleting vendor and composer.lock was first thing I tried :) Not working :))

I have an older fork of rector (origin), where I always merge main branch from rectorphp/rector (upstream). It worked several month. I don't get why it stoped yesterday. 

And no it is not connected with this https://github.com/rectorphp/rector/pull/6035#issuecomment-816964229 :D it didn't work before I did rebase .

Anyway... 
```
git clone git@github.com:rectorphp/rector.git
cd rector
composer install
```
works, so probably I will delete my fork and try it again from zero :)

**Comment by TomasVotruba** [comment]
Yea, it gets messed up sometimes. I remove forks of projects I work with once a 3 months and start with fresh ones :) it just works.

At least, I'd definitelly bump to Composer 2. Some dependency rules changed there too.

**Comment by lulco** [comment]
> Yea, it gets messed up sometimes. I remove forks of projects I work with once a 3 months and start with fresh ones :) it just works.

Yes :) I just don't know what will happen to my PR which are not merged for now :D we will see...

> At least, I'd definitelly bump to Composer 2. Some dependency rules changed there too. It's also blazing fast.

Yeah I know, I just can't do it for now on my env :)

**Comment by lulco** [comment]
fresh start worked... thank you for your time :)

**Comment by TomasVotruba** [comment]
> Yes :) I just don't know what will happen to my PR which are not merged for now :D we will see...

Good point :). I've merged the other one to keep it simple: https://github.com/rectorphp/rector/pull/6029
