### ISSUE TITLE
Output changelog url in OutputFormatterInterface

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6072]
# Feature Request

In TYPO3-Rector we have an option to output the url to the changelog https://github.com/sabbelasichon/typo3-rector/blob/master/src/Configuration/Typo3Option.php#L12

The url is defined in the Rector via @see docblock. Should be better an @link docblock.

In order to achieve this i have created a rather nasty Decorator for the ConsoleOutputFormatter.php https://github.com/sabbelasichon/typo3-rector/blob/master/src/Console/Output/DecoratedConsoleOutputFormatter.php

I would like to have this in rector itself. I know it is only my itch, but maybe it is useful for others. 

I am gonna create a PR for that even if it gets rejected.

**Comment by lulco** [comment]
Can you provide some screenshot how it would look like?

**Comment by sabbelasichon** [comment]
@lulco Uploaded an image here: https://github.com/rectorphp/rector/pull/6073
