### ISSUE TITLE
Bad TypeHint path in signature

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#608]
Before : 
```php
    public function fooAction()
    {
        $request = $this->getRequest();
    }
```

After : 
```php
    public function fooAction(Symfony\Component\HttpFoundation\Request $request)
    {
        $request = $request;
    }
```

What it should be : 
```diff
-   public function fooAction(Symfony\Component\HttpFoundation\Request $request)
+   public function fooAction(\Symfony\Component\HttpFoundation\Request $request)
    {
        $request = $request;
    }
```

**Comment by TomasVotruba** [comment]
Very nice report! This is an easypick. 

Which Rector did cause this? Look into it and look for `PhpParser\Node\Name`. Then replace it with `PhpParser\Node\Name\FullyQualified` and send PR.

Just edit file on Github.

**Comment by TomasVotruba** [comment]
Very nice report! This is an easypick. 

Which Rector did cause this? Look into it and look for `PhpParser\Node\Name`. Then replace it with `PhpParser\Node\Name\FullyQualified` and send PR.

Just edit file on Github.

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

Fixed
