### ISSUE TITLE
Incorrect behavior of ChangeReadOnlyPropertyWithDefaultValueToConstantRector

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/rector#6082]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

Similar as #6044, but this time it is a static call

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e87e2831-f782-4fc2-a586-c70df9b829ef

```php
<?php

final class DemoFile
{
    private $value = [];

    public function run()
    {
        self::process($this->value);
    }

    private static function process(array &$value)
    {
    }
}
```

### Responsible rules

* `ChangeReadOnlyPropertyWithDefaultValueToConstantRector`

## Expected Behavior

Nothing needs to be changed

**Comment by zingimmick** [comment]
Failing test case #6083

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector/pull/6084
