### ISSUE TITLE
Running without a rule but a NonPhpFileProcessor is not possible

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6087]
As the new baby is out i tried it and it actually works like a charm in our context.
But one thing popped up. If i try to run the process command without any set or rector but only with the FilesProcessor it failed due to a guard clause in rector. Maybe we could also take the FilesProcessor into account before stopping the process.

**Comment by TomasVotruba** [comment]
Could you link the guard clause line in Rector codebase? I'll look into in it

**Comment by sabbelasichon** [comment]
If you link i can provide a PR for that. I was not sure if something speaks against it.

**Comment by TomasVotruba** [comment]
The command run with `--debug` should show the line of origin

**Comment by sabbelasichon** [comment]
I have solved this for me by implementing the RectorInterface in my non php processors as marker interface. 
That´s fine for me.

**Comment by TomasVotruba** [comment]
That's only nasty workaround. There should be clear separation of those kept on all levels.

**Comment by sabbelasichon** [comment]
@TomasVotruba Could you elaborate what do you mean with 2 classes. Should we create a new marker interface for the NonPhpFiles. Don´t really get it. But from a developer user experience perspective i would like run rector without a having to define a DummyRector class.

**Comment by TomasVotruba** [comment]
Sure. The file processor exactly 1 role - process file of specific suffix with rules of specific interface.

- `PhpFileProcessor` → `PhpRectorInterface`

The file processor should not do any concrete change, only iterate through the rules.

**Comment by sabbelasichon** [comment]
Do you think we should create new marker interfaces for every file type? So, i don´t really get what to do.

**Comment by lulco** [comment]
@sabbelasichon me neither :) so I gave up this non php processors for now. As Tomáš says in https://github.com/rectorphp/rector-nette/pull/7 he will work on it so maybe we will see soon how he want us to implement it...

**Comment by TomasVotruba** [comment]
> Do you think we should create new marker interfaces for every file type?

Basically yes, like `ComposerFileProcessor` has `ComposerRectorInterface[]`

**Comment by TomasVotruba** [comment]
This should make it simpler: https://github.com/rectorphp/rector/pull/6241/files

**Comment by sabbelasichon** [comment]
But the fact that the FileProcessors are extensible you cannot know all the Marker interfaces beforehand. I have something in mind, but i am afraid it is different from your expectations. If you could point me in your direction with an example i am glad to implement this feature.

**Comment by TomasVotruba** [comment]
What do you need to know marker beforehand for?

**Comment by sabbelasichon** [comment]
But how do you determine if any of the FileProcessors has at least one rule defined?

**Comment by TomasVotruba** [comment]
That should be part of FileProcessorInterface, e.g. `$fileProcessor->isActive()`

**Comment by sabbelasichon** [comment]
I am going to create something.

**Comment by TomasVotruba** [comment]
First step to fix this 
https://github.com/rectorphp/rector/pull/6286

**Comment by TomasVotruba** [comment]
This is how tests is refactored to comply with 2 classes contract:
https://github.com/rectorphp/rector/issues/6087
