### ISSUE TITLE
Possibility to exclude directory via CLI + config

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#609]
Everything's in title.
Just a reminder of why I ask it, it's because tests and js files are in my code directory. Maybe adding a File mask could be a great option too

**Comment by TomasVotruba** [comment]
Ready in #611, could you code-review it?

**Comment by TomasVotruba** [comment]
It might be alos useful to allow asterisk use in arguments:

```bash
bin/rector process "src/Symfony/Components/*/test" --level phpunit60
```
