### ISSUE TITLE
PHP can't have two same name parameter

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#610]
Before : (note that the $request in param is useless)
```php
public function fooAction(Request $request) {
    $oRequest = $this->getRequest();
}
```

After : 
```php
public function fooAction(Request $request, Symfony\Component\HttpFoundation\Request $request) {
    $oRequest = $request;
}
```

PHP generate an error about same name in signature, should be check.
I still don't know what behaviour it should have..

**Comment by vasilvestre** [comment]
```diff
-public function someAction(Request $request)
+public function someAction(Request $request)
{
-    $oRequest = $this->get('request');
+   $oRequest = $request;
}
```
OR
```diff
-public function someAction(Request $request)
+public function someAction(\Symfony\Component\HttpFoundation\Request $request)
{
-    $oRequest = $this->get('request');
+   $oRequest = $request;
}
```

This is a real case

**Comment by TomasVotruba** [comment]
So basically, if property of that type is already added, do not add twice and just use it?

**Comment by vasilvestre** [comment]
Yes it has to be. But you need to be sure it's the same class, not just with the same name.

\Symfony\HttpFoundation\Request and \Symfony\TestCase\Request are different for example.
