### ISSUE TITLE
Allow whitelist for Option::(AUTO_IMPORT_NAMES|IMPORT_SHORT_CLASSES|IMPORT_DOC_BLOCKS)

### ISSUE THREAD

**Issue by dvc** [rectorphp/rector#6105]
Hello everybody! Thanks to authors for this great project!

# Feature Request

I need to refactor single class (replace class by interface). And i want to fix codestyle (simplify fqcn everywere) only for this class/interface. Or nothing. To minimize commit size.

What do you think about array in parameter value? Should it useful for anybody?

before:

```php
$map = [
    CacheService::class => CacheServiceInterface::class,
    CacheConst::class => \App\Bundles\InfraBundle\Application\Contract\Cache\Option::class,
    CacheItem::class => CacheItemInterface::class,
];

// style nothing
$parameters->set(Option::AUTO_IMPORT_NAMES, false);
$parameters->set(Option::IMPORT_SHORT_CLASSES, false);
$parameters->set(Option::IMPORT_DOC_BLOCKS, false);

$services->set(RenameClassRector::class)
    ->call('configure', [[ RenameClassRector::OLD_TO_NEW_CLASSES => $map]]);
```

after:

```php
...
$whitelist = array_merge(array_keys($map), array_values($map));

// style only refactored
$parameters->set(Option::AUTO_IMPORT_NAMES, $whitelist);
$parameters->set(Option::IMPORT_SHORT_CLASSES, $whitelist);
$parameters->set(Option::IMPORT_DOC_BLOCKS, $whitelist);
...
```

**Comment by TomasVotruba** [comment]
Hi, using 2 standards for importing FQN would be very confusing.
Soon we might have 2 standard for space tabs on each line :)

I recommend to import FQNs first, then do another refactoring. That would keep your code standardized and next changes small :+1:
