### ISSUE TITLE
Is UnderscoreToCamelCasePropertyNameRector gone?

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#6108]
# Question
Hi, So I finally got around to updating Rector, however I ran into an issue that one of the rules we have registered `UnderscoreToCamelCasePropertyNameRector` is not there anymore.

Has it been renamed or is it just gone?

**Comment by TomasVotruba** [comment]
Hi, see https://github.com/rectorphp/rector/issues/5750#issuecomment-799813551

There rules should be now implemented in coding standards instead of AST.

**Comment by olivernybroe** [comment]
Ah right... Thanks a lot! 

I usually try to solve everything with AST's if possible as I find it much simpler 👍
But will move the checks to phpcs then

**Comment by TomasVotruba** [comment]
It still can be done. Feel free to implement rule in own Rector package :+1: 

It can be based on one we split https://github.com/rectorphp/rector-nette
