### ISSUE TITLE
Larastan and rector

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#6109]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.10.4              |
| Installed as   | composer dependency                         |

I know issues has been opened about this before, however for me they worked well together before 0.10, but now Larastan and rector does not work together. 

Not sure if it was a Larastan or a rector update which caused it 👍 

So let's try and get them to play nicely ❤️ 

I have created a demo repository with a default Laravel installation, nothing changed in it except for adding Larastan, rector and a github action.
https://github.com/olivernybroe/dummy-larastan

We have a GitHub action failing in there which shows the error and hopefully makes us able to figure out what's wrong and how Larastan and Rector can be friends again 🤗 

Failing CI test with verbose on:
https://github.com/olivernybroe/dummy-larastan/runs/2324626233?check_suite_focus=true

@canvural might be of interest for you?

**Comment by TomasVotruba** [comment]
Seems the `GuardDynamicStaticMethodReturnTypeExtension` class is failing: https://github.com/olivernybroe/dummy-larastan/runs/2324626233#step:5:17

Be sure to have the latest PHPStan + phpdoc-parser. The second is bundled in PHPStan, but Rector need it in specific version. They have to be equal.

**Comment by olivernybroe** [comment]
@TomasVotruba Yes, it seems like that is the class that fails, however it does not fail when running phpstan, only when it's running through rector. 

Not sure I completely follow your second comment. However everything is up to date with the latest versions 👍

**Comment by TomasVotruba** [comment]
Yea, this one is tricky because of PHAR :) 

The PHPStan can contains e.g phpdoc-parser 0.4, but composer missed it, as it's scoped inside a PHAR.
But there is one more phpdoc-parser needed in Rector, that can be 0.5. This would create conflict.

So while it seems it might be uptodate, it **can** still crash, because of PHAR inner dependency conflict.

**Comment by canvural** [comment]
I don't have any crashes or issues with Rector 0.10, PHPStan 0.12.83, phpdoc-parse 0.5.4 and Larastan 0.7.3

**Comment by olivernybroe** [comment]
@TomasVotruba Hmm, checked the versions and this is them. Looking at PHPStan lock file it should be [0.5.4](https://github.com/phpstan/phpstan-src/blob/0.12.83/composer.lock#L2339) also.
PHPStan 0.12.83
Rector 0.10.4
Phpdoc-parse 0.5.4
Larastan 0.7.3


@canvural Huh interesting, the repo I shared has the exact same versions and fails 🤔

**Comment by TomasVotruba** [comment]
As mentioned above, this is caused in `GuardDynamicStaticMethodReturnTypeExtension` from larastan. The extension must be fixed there.
