### ISSUE TITLE
[DX] Add convention-based config loading to allow services from extension to be loaded

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6129]
**Problem:** If you create and Rector extension, to run Rector with it the `rector.php` must include it explicitly. Without it, the extension does not load its services. 

The workaround is to add config manually e.g. in `bin/rector.php`: https://github.com/sabbelasichon/typo3-rector/blob/b7a6b8a67adf0c2e84974eb1be6f8469de1b920e/bin/rector.php#L48

<br>

Solution would be to include config in `composer.json` configuration, like PHPStan composer pluging does: https://github.com/phpstan/extension-installer

The generated class is used during DI creation: https://github.com/phpstan/phpstan-src/blob/c471c7b050e0929daf432288770de673b394a983/src/Command/CommandHelper.php#L193-L217

<br>

It would also help with magical loading we currently have:

https://github.com/rectorphp/rector/blob/021ffc7ada2bd57772481c067aeeca158f6bdc68/config/config.php#L15-L29

<br>

Based on call with cc @sabbelasichon

**Comment by sabbelasichon** [comment]
Thanks for taking care. I would like to create something here. Maybe not so fast as you do, but it is nothing with time pressure, right?

**Comment by TomasVotruba** [comment]
You can go for it 👍

**Comment by sabbelasichon** [comment]
Basically i am done. Would you create a dedicated rector/rector-installer package or is it just part of rector itself?

**Comment by TomasVotruba** [comment]
> is it just part of rector itself

:+1: I would do it as MVP and see how it works.

**Comment by sabbelasichon** [comment]
Sorry, but i think it should be a standalone package because it must be of type composer-plugin to register it correctly. I don´t like to give the whole rector package the type of composer-plugin.

**Comment by sabbelasichon** [comment]
If you like you could create a rector/rector-installer repository and i am gonna fork it and provide my solution.

**Comment by TomasVotruba** [comment]
Yes, plugin is standalone and imlementation in Rector is part of core.

There you go: https://github.com/rectorphp/rector-installer, you should have write access so no fork is needed :+1:

**Comment by sabbelasichon** [comment]
The installer package is ready, https://github.com/rectorphp/rector-installer/
We have to register the package at packagist.org still.

**Comment by sabbelasichon** [comment]
If you like as a follow up i could also add the configurations to rector/rector-*. Just tell me. I would be happy to help.

**Comment by TomasVotruba** [comment]
There you go - https://packagist.org/packages/rector/rector-installer

> If you like as a follow up i could also add the configurations to rector/rector-*. Just tell me. I would be happy to help.

Yea, go for it :+1:

**Comment by sabbelasichon** [comment]
I have tested it to remove the magic config integration. It works very well. But would you make the rector-installer be a requirement for rector itself? If so, everything is fine, if not as in phpstan, we have to think about an alternative to register the extension configs. What do you think? I would suggest to make the rector-installer a first class citizen of rector itself.

**Comment by TomasVotruba** [comment]
Could you sum up why it's a requirement?

**Comment by sabbelasichon** [comment]
Sure. If i am removing the config lines here https://github.com/rectorphp/rector/blob/021ffc7ada2bd57772481c067aeeca158f6bdc68/config/config.php#L15-L29 the configs are not loaded anymore without the rector-installer. Or do is miss something here?

**Comment by TomasVotruba** [comment]
That should work, yea. I'm not sure how the added feature works, so I'm only curious :)

Could you explain the steps by step for me and why does the `rector-installer` be a requirement for rector itself?

**Comment by sabbelasichon** [comment]
Thanks for merging. This issue can be closed then, right?

**Comment by TomasVotruba** [comment]
Yes! :+1: 

Just a tip to automate this. If you put "closes x" in PR description, it will close the issue automatically on PR merge. See https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
