### ISSUE TITLE
using static reflection from within a custom rector rule

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#6135]
# Question

I want to use phpstans static reflection from within rector.
therefore I am using the `ReflectionProvider`.

I try to use static reflection on a class which is known to rector because of the `Option::AUTOLOAD_PATHS` setting.
I have the feeling that the `ReflectionProvider` does not know about the extended autoloading path and therefore doesn't know about my class. when using regular composer autoloading the `ReflectionProvider` works like expected.

my custom rector rule wors like expected on the master branch, without the above changes from the pull request.

see https://github.com/staabm/rector-view-scope/pull/19 for a small repro

**Comment by TomasVotruba** [comment]
Closing as dicussion continues in linked PR.

**Comment by clxmstaab** [comment]
underlying problem was fixed in https://github.com/rectorphp/rector/pull/6239
