### ISSUE TITLE
The currentFileProvider is not updated the actual file during processing

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6136]
This is a nasty one. I am gonna provide a PR for that right now.

**Comment by sabbelasichon** [comment]
Sorry. I was wrong. It is already fixed in the main branch.

**Comment by sabbelasichon** [comment]
Did you notice by yourself ;-)

**Comment by TomasVotruba** [comment]
Yea, I got a bug yestereday, where the "SKIP" was not working... because it only checked the first File in the loop :D 

Should be fixed in 0.10.6 - https://github.com/rectorphp/rector/commit/c81b77dceddff647ae527da8fab646f9a9f367b5
