### ISSUE TITLE
Rector docker stops randomly -- extra logs somewhere?

### ISSUE THREAD

**Issue by Syzgyn** [rectorphp/rector#6142]
# Question
I'm trying to run Rector against a codebase using PHP 5.3 via docker, since installing it as a package didn't work with such an outdated version.  I'm running it with the following command:

`docker run --rm -v $(pwd):/project rector/rector:php7.3 process /project --config=/project/rector.php --dry-run -v`

Everything seems to be going fine, it starts listing files as it parses them, then after a certain point it just stops.  There's no error show, I'm just back to the command line.  It never stops at the same file, always stopping a little after 3 minutes.  Here's my rector config:

```
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    // Define what rule sets will be applied
    $parameters->set(Option::SETS, [
        SetList::PHP_54,
        SetList::PHP_55,
        SetList::PHP_56,
    ]);

    $parameters->set(Option::PATHS, [
        __DIR__ . '/app',
        __DIR__ . '/batch',
        __DIR__ . '/lib',
        __DIR__ . '/migrate',
        __DIR__ . '/tests',
        __DIR__ . '/vendor',
    ]);

    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__ . '/app/lib/xxxxxxx/Exceptions.php',
    ]);

};
```

I'm hoping there's some log somewhere I can check to see what's going on and why it's stopping

**Comment by staabm** [comment]
You could  use `-vvv` for extra verbose output

**Comment by Syzgyn** [comment]
Well I could've sworn I did that before, but that seems to have done the trick.  I'm getting errors that I can deal with now.  Thank you @staabm!
