### ISSUE TITLE
General pretty printing guidance

### ISSUE THREAD

**Issue by jdart** [rectorphp/rector#6146]
# Question
I saw the part of the readme with a link to your ecs.php and tried it out, but it didn't fix most of the unwanted changes and added more. Do you know of a fixer that will remove leading slashes on global functions and things like parent, and true? Do you know of a fixer that will replace a fqn with a class name if it's imported? It would be really great to provide a minimal ecs config that fixes common things php parser changes, maybe that's impossible.

```
        \parent::setUp();
        \app();
        // not using imported class, instead using fqn
        \true

```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

The `parent` and `true` should not be prefixed with `\\` by Rector.

Could you provide minimal failing code snippet that is causing it? https://getrector.org/demo

**Comment by jdart** [comment]
I'm not able to reproduce there but I should mention I'm using the prefixed build (RectorPrefix20210414\).

**Comment by jdart** [comment]
I tried reproducing with a fresh composer.json with the prefixed build and was again unable to reproduce so there must be something funny with my dependencies. Any ideas for troubleshooting?

**Comment by TomasVotruba** [comment]
Hi, I would copy paste the latest patch version from your test repository to you main repository.

E.g. 

```diff
-rector/rector:^0.10
+rector/rector:^0.10.5
```

for all other packages too

**Comment by jdart** [comment]
I believe I'm able to reproduce now...

composer.json
```
{
    "name": "jdart/rekt",
    "authors": [
    ],
    "require": {},
    "require-dev": {
        "rector/rector-prefixed": "^0.10.6"
    },
    "autoload": {
        "psr-4": {
          "App\\": "app/"
        }
    }
}
```

app/ThingTest.php
```
<?php

declare(strict_types=1);

class BaseC {
    public function setup(): void
    {
    }
}

class Extender extends BaseC
{
    public function setup(): void
    {
        parent::setup();
    }
}
```

rector.php
```
<?php

declare(strict_types=1);

return static function (\RectorPrefix20210414\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(\Rector\PSR4\Rector\FileWithoutNamespace\NormalizeNamespaceByPSR4ComposerAutoloadRector::class);
};
```

Output:
```
❯ ./vendor/bin/rector process --debug --clear-cache app/ThingTest.php
[parsing] app/ThingTest.php
[refactoring] app/ThingTest.php
    [applying] Rector\PSR4\Rector\FileWithoutNamespace\NormalizeNamespaceByPSR4ComposerAutoloadRector
arstarstarst[post rectors] app/ThingTest.php
[printing] app/ThingTest.php


1 file with changes
===================

1) app/ThingTest.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php

 declare(strict_types=1);
+namespace App;

 class BaseC {
     public function setup(): void
@@ @@
     {
     }
 }
-class Extender extends BaseC
+class Extender extends \BaseC
 {
     public function setup(): void
     {
-        parent::setup();
+        \parent::setup();
     }
 }
    ----------- end diff -----------


Applied rules:

 * NormalizeNamespaceByPSR4ComposerAutoloadRector



 [OK] 1 file has been changed by Rector
```

**Comment by TomasVotruba** [comment]
I see, thanks for tests. I've added a test fixture to NormalizeNamespaceByPSR4ComposerAutoloadRector

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector/pull/6159 :+1:

**Comment by jdart** [comment]
Thanks @TomasVotruba 

BTW would you happen to know of a fixer that will replace a fqn with a class name if it's imported? I.e. after rector process runs it seems like all class names are replaced with the FQN even if the class is imported.

**Comment by TomasVotruba** [comment]
Try auto import parameter
