### ISSUE TITLE
Overzealous behavior of SimplifyUselessVariableRector

### ISSUE THREAD

**Issue by alexanderpas** [rectorphp/rector#6152]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/c7cf4475-26bf-4f8e-bd6b-aec734779cf9

```php
<?php

final class DemoFile
{
    public function hello(string $name)
    {
        $output = "Hello $name";
        
        if (empty($name)){
        	$output = $output . "World";
        }
        
        $output = $output . ', Meet Rector';
        
        // Future additions to the end of the string could be placed here
        // This should not change the lines above and below in version control
        
        return $output;
    }
}
```

### Responsible rules

* `SimplifyUselessVariableRector`

## Expected Behavior

Rector should not adjust single variable return statements at the end of a function, as this is a VCS friendly pattern, unless the variable itself can be completely removed from the function or method.

The solution provided by rector makes for more noise in future diffs, increases the risk of future errors, since code needs to be adjusted which is not directly related to the new code being added.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

This rule takes an approach of removing just for sake variable. What you suggest is against YAGNI approach. A code snippet not having value now, but ready for some future changes.

It can be personal preference to have such snippets in your code. To avoid using something you don't like, you can exclude the `SimplifyUselessVariableRector` rule in `SKIP` parameter.
