### ISSUE TITLE
ConsistentPregDelimiterRector escaping delimiter in extended mode

### ISSUE THREAD

**Issue by JoyceBabu** [rectorphp/rector#6161]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `v0.10.6`              |
| Installed as   | `composer dependency`                           |

`ConsistentPregDelimiterRector`  is escaping end delimiter of multi line extended mode pattern on every run. Single line pattern is left alone as expected.

## Minimal PHP Code Causing Issue

I am unable to replicate this on the online interface. But the minimal example and rector configuration is available below

https://getrector.org/demo/94e49b2f-269b-4fd0-bd8b-08c3d4186d62

## Actual Behavious

```
$ ./vendor/bin/rector --config rector2.php process public_html/test.php
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) public_html/test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php
 $path = preg_replace('~^/(
     test
-).*/~x', '/$1/', $path);
+).*/\~x', '/$1/', $path);


 $path = preg_replace('~^/(videos).*/~x', '/$1/', $path);
    ----------- end diff -----------


Applied rules:

 * ConsistentPregDelimiterRector



 [OK] 1 file has been changed by Rector
```
**Run 2**
```
$ ./vendor/bin/rector --config rector2.php process public_html/test.php
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) public_html/test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php
 $path = preg_replace('~^/(
     test
-).*/\~x', '/$1/', $path);
+).*/\\\~x', '/$1/', $path);


 $path = preg_replace('~^/(videos).*/~x', '/$1/', $path);
    ----------- end diff -----------


Applied rules:

 * ConsistentPregDelimiterRector



 [OK] 1 file has been changed by Rector
```

** Run 3**
```
$ ./vendor/bin/rector --config rector2.php process public_html/test.php
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) public_html/test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php
 $path = preg_replace('~^/(
     test
-).*/\\\~x', '/$1/', $path);
+).*/\\\\\~x', '/$1/', $path);


 $path = preg_replace('~^/(videos).*/~x', '/$1/', $path);
    ----------- end diff -----------


Applied rules:

 * ConsistentPregDelimiterRector



 [OK] 1 file has been changed by Rector
```

## Expected Behaviour

Rector should skip the instance.

**Comment by samsonasik** [comment]
Could you try latest `dev-main` version?  If it still invalid, please create PR with added fixture for it with expected input/output at https://github.com/rectorphp/rector/tree/main/rules-tests/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture . 

I tried to reproduce but seems it got different output.

**Comment by JoyceBabu** [comment]
I was able to replicate this on the latest `dev-main` version too.

I have added a fixture

https://github.com/rectorphp/rector/pull/6165

```
$ ./vendor/bin/rector --version
Rector dev-main@2b88d9d

$ php -v
PHP 8.0.3 (cli) (built: Apr 12 2021 09:04:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```
