### ISSUE TITLE
WrapEncapsedVariableInCurlyBracesRector does not show as having made changes

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#6169]
Howdy,

The Rector `WrapEncapsedVariableInCurlyBracesRector` makes changes, but it doesn't appear in the list of Rectors applied after running. This can make it difficult to find out why a particular change is being made.

Demo:
https://getrector.org/demo/e2e6d624-5f03-4f9c-b857-e693f1357503

The line gets changed, but it does not give you the name of the rector responsible for making the change. This is difficult when using a whole set or multiple sets, as the only way to find the Rector is through a process of elimination.

**Comment by TomasVotruba** [comment]
Hi,

it took a while to discovery why this happen.

I've found out the original php-parser ignores `{}` or `` enscapsed strings and always prints them with `{}`. So I had to add extra check for just this node. Should be fine now :)
