### ISSUE TITLE
Idea: don’t touch by AddLiteralSeparatorToNumberRector already formatted literals

### ISSUE THREAD

**Issue by lptn** [rectorphp/rector#6188]
## Feature Request

When a money amount is presented in minor currency units (e.g. cents), we need separate cents by divider. Most of currencies have 100 minor units in a major unit, so the formatting should be like `100_00`.

I propose to have an option in AddLiteralSeparatorToNumberRector to don't change literals that are already formatted. I understand, such solution is not ideal, but I couldn't find a better one

**Comment by TomasVotruba** [comment]
Agreed 👍

**Comment by TomasVotruba** [comment]
This might help: https://github.com/nikic/PHP-Parser/pull/655

**Comment by samsonasik** [comment]
@lptn could you add https://getrector.org/demo for issue demo or failing test case for it? Thank you.

**Comment by lptn** [comment]
@samsonasik 
sure, https://getrector.org/demo/cd168f51-d9b1-4f37-ab79-1dead8e415bc
