### ISSUE TITLE
Take editorconfig into account for non php files.

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6215]
Often times many people are "complaining" about the wrong formatting output after transforming their files.
What i have done is taking the editorconfig into account for each file which is processed. 
https://github.com/sabbelasichon/typo3-rector/commit/66e7675053f91990179a808d68f7e122aea72197

What do you think? Should we add this for the composer part?

**Comment by sabbelasichon** [comment]
If you like it, i could create a PR for that.

**Comment by TomasVotruba** [comment]
Seems good idea, especially for multi formats. Go for it!

**Comment by sabbelasichon** [comment]
Hi, i have used this little neat package here https://github.com/idiosyncratic-code/editorconfig-php. But i am thinking of taking it under my umbrella to fit our needs. Or would you like to add it under the symplify organization and i am gonna maintain it at the beginning.

**Comment by TomasVotruba** [comment]
Hi, if you can take care of your umbrela, it would be the best. Other options require some maintenance cost for me.
