### ISSUE TITLE
GetRequest should check extended method signature

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#622]
Example :
FooController extend Controller and create a getUser() method
Signature of Controller::getUser() is empty
Signature of FooController::getUser() can't be getUser(Request $request)

This is the actual behaviour that doesn't work :
```diff
<?php
namespace AppBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class MyController extends Controller
{
-    public function getUser()
+    public function getUser(Request $request)
    {
        $user = parent::getUser();
        
        if ($user != null) {
-            $request = $this->getRequest();
+            $request = $request;
            $session = $request->getSession();
            
            // etc.
    }
}
```

This one generate an error like "Controller::getUser() declaration isn't compatible with MyController::getUser() signature"

This is the behaviour that's supposed to be used :

```diff
<?php
namespace AppBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class MyController extends Controller
{
    public function getUser()
    {
        $user = parent::getUser();
        
        if ($user != null) {
-            $request = $this->getRequest();
+            $request = $this->get('request_stack')->getCurrentRequest();
            $session = $request->getSession();
            
            // etc.
    }
}
```

**Comment by TomasVotruba** [comment]
I think these cases are better to be fixed manually. There is too much unexpected behavior going, e.g. the parent class could be 3rd party code, or it's not a services and is created manually and so on.

**Comment by vasilvestre** [comment]
This seem ok, so I close it. Thanks.
