### ISSUE TITLE
Cannot autowire service JMSDITypeResolver

### ISSUE THREAD

**Issue by lptn** [rectorphp/rector#6246]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.10.11        |
| Installed as   | composer dependency                          |

Update rector update (from 0.10.10 to 0.10.11), we have got this error:
```
rector process '--dry-run'

Error: ] Cannot autowire service                                                
         "Rector\DependencyInjection\TypeAnalyzer\JMSDITypeResolver": argument  
         "$serviceMapProvider" of method "__construct()" references class       
         "Rector\Symfony\DataProvider\ServiceMapProvider" but no such service   
         exists.                                                                
```

**Comment by sabbelasichon** [comment]
I guess this is due to the new rector-installer. Could you please do a composer install again. The rector-installer should autowire the config behind the scenes.

**Comment by TomasVotruba** [comment]
That's due to new way we install Rector extensions:
https://github.com/rectorphp/rector/pull/6174

```bash
composer install
```

Should invoke the composer plugin to install them

**Comment by TomasVotruba** [comment]
But it shows our wrong architetcure... The `AnnotatedPropertyInjectToConstructorInjectionRector` now depends on rector-symfony package, so we should extra it there to own rule.

**Comment by lptn** [comment]
I've got this error on CI, but probably we use a wrong caching strategy for composer install. I'll check it out, thanks!

**Comment by sabbelasichon** [comment]
Are you running it with --no-scripts?

**Comment by lptn** [comment]
@sabbelasichon 
yes:
```sh
composer install -q --no-interaction --no-scripts --no-progress --prefer-dist --no-ansi
```

**Comment by sabbelasichon** [comment]
I think that is the problem.

**Comment by TomasVotruba** [comment]
@lptn If you use GitHub CI, this is the best way with cache included  https://github.com/rectorphp/rector/blob/91d58e0c7d446d44475161df277bcffa7ccaa11f/.github/workflows/tests.yaml#L32

**Comment by lptn** [comment]
Hey @TomasVotruba and @sabbelasichon 
yes, the issue was `--no-scripts` option. I also needed to change composer install caching strategy, because `composer install` and `composer install --no-scripts` generates different output (and thus require to use different cache). 

As usually, thanks a lot for your awesome product and super-fast responses 👍 .
