### ISSUE TITLE
[Prefixed] Wrong extended function signature

### ISSUE THREAD

**Issue by userbig** [rectorphp/rector#6253]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | rector/rector-prefixed                0.10.11               |
| Installed as   |  prefixed Rector                           |

## Minimal PHP Code Causing Issue

```
user@74a557294af3:/opt$ vendor/bin/rector init
PHP Warning:  Declaration of Rector\Core\PhpParser\Printer\BetterStandardPrinter::pStmts(array $nodes, bool $indent = true): string should be compatible with PhpParser\PrettyPrinterAbstract::pStmts(array $nodes, $indent = true) in /opt/vendor/rector/rector-prefixed/src/PhpParser/Printer/BetterStandardPrinter.php on line 31


PHP Fatal error:  Declaration of PHPStan\Parser\PhpParserDecorator::parse(string $code, ?PhpParser\ErrorHandler $errorHandler = NULL): array must be compatible with PhpParser\Parser::parse($code, ?PhpParser\ErrorHandler $errorHandler = NULL) in phar:///opt/vendor/rector/rector-prefixed/vendor/phpstan/phpstan/phpstan.phar/src/Parser/PhpParserDecorator.php on line 7

```

`BetterStandardPrinter::pStmts(array $nodes, bool $indent = true)` 
`PhpParser\PrettyPrinterAbstract::pStmts(array $nodes, $indent = true)`

**Comment by TomasVotruba** [comment]
Hi, 

thanks for reporting.

This might be due to conflict with PHPStan version of php parser.

We need exact steps to reproduce with composer require.

**Comment by userbig** [comment]
> Hi,
> 
> thanks for reporting.
> 
> This might be due to conflict with PHPStan version of php parser.
> 
> We need exact steps to reproduce with composer require.

@TomasVotruba just one step was - prefixed version installation;

```
  - Installing phpstan/phpstan (0.12.84): Extracting archive
  - Installing rector/rector-prefixed (0.10.11): Extracting archive
```

FYI: PHP version 

`PHP 7.1.33 (cli) (built: Nov 22 2019 18:34:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
`

**Comment by userbig** [comment]
As I can see some other packages in my project are required `nikic/php-parser: 3.1.5`

**Comment by userbig** [comment]
also, this exception fired too

`PHP Fatal error:  Declaration of PHPStan\Parser\PhpParserDecorator::parse(string $code, ?PhpParser\ErrorHandler $errorHandler = NULL): array must be compatible with PhpParser\Parser::parse($code, ?PhpParser\ErrorHandler $errorHandler = NULL) in phar:///opt/vendor/rector/rector-prefixed/vendor/phpstan/phpstan/phpstan.phar/src/Parser/PhpParserDecorator.php on line 7`

**Comment by sabbelasichon** [comment]
Can confirm this even in the prefixed / scoped version. At the moment the PHPStan and PHPParser namespaces are excluded from scoping. But maybe it is useful to only exclude the PHPParse Node classes from scoping because these classes are part of the API. That´s at least my experience.

**Comment by TomasVotruba** [comment]
It seems this is the only solution:
https://github.com/phpstan/phpstan-src/commit/87897c2a4980d68efa1c46049ac2eefe767ec946

**Comment by TomasVotruba** [comment]
Steps to replicate:

```bash
composer require nikic/php-parser:^3.1 rector/rector-prefixed:^0.10
vendor/bin/rector list
```

**Comment by TomasVotruba** [comment]
WIP https://github.com/rectorphp/rector/commit/f15648eb057eab040e36804d860f1713d532a007

**Comment by TomasVotruba** [comment]
We should be up an running: https://github.com/rectorphp/rector-prefixed/runs/2470736626 :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/924196/116620747-8937c000-a942-11eb-891b-a5c8fd0b7c23.png)


This is the workflow in CI: https://github.com/rectorphp/rector-prefixed/blob/main/.github/workflows/php_parser_3.yaml
