### ISSUE TITLE
[cakephp] 3.4 set + 3.5 set

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#626]
Ref:

- https://github.com/rectorphp/rector/issues/619#issuecomment-421952317
- https://github.com/cakephp/cakephp/commit/49722a80c424230df1c3510404d15267f2faac9a#diff-c5c39ed515f278a9bfe7261c0abada25

**Comment by dereuromark** [comment]
https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html
and
https://book.cakephp.org/3.0/en/appendices/3-5-migration-guide.html
basically also make sense, this those deprecations now are showing up in 3.6 with the deprecation warnings and should also be auto-resolved if possible.

**Comment by TomasVotruba** [comment]
https://github.com/cakephp/cakephp/blob/2341c3cd7c32e315c2d54b625313ef55a86ca9cc/src/Console/Shell.php#L245

**Comment by TomasVotruba** [comment]
Good news! I've just finished CakePHP 3.4 set - in #634

There is all I could think of. Please test it and let me know how it works for you.
