### ISSUE TITLE
Do we need some kind of priority for the FileProcessors?

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6267]
I am not sure in which order the FileProcessors are registered right now. Before we had this feature the so called NonPhpFileProcessor ran after the PhpFileProcessor. Did we maybe break this behaviour? And if so, maybe we should add a priority method and take this into account in the CompilerPass.

**Comment by lulco** [comment]
Hi,
imho we need something like that.

**Comment by TomasVotruba** [comment]
Hi, what is the use case where this causes troubles?

**Comment by lulco** [comment]
Honestly, my use case was composer processor (running composer update). But you turned it off :)

**Comment by sabbelasichon** [comment]
I don't have one ;-). But was thinking about it after the discussion during the morning about running FileProcessors in general. And i had the feeling that the order matters. Feel free to close this issue.

**Comment by TomasVotruba** [comment]
@sabbelasichon Ok, closing. Let me know if file processors create some collision. They should be idempotent.

**Comment by lulco** [comment]
If composer update was executed as first one, other rectors would fail because application itself is inconsistent (at least my nette apps where bootstrap.php is included as autoload path), so composer has to be executed after all php changes were done.

Also I remember the comment from ProcessCommand which says that NonPhpProcessor has to be executed after PhpProcessors.

**Comment by lulco** [comment]
Here it was:

```
        // must run after PHP rectors, because they might change class names, and these class names must be changed in configs
        $neonYamlFileInfos = $this->filesFinder->findInDirectoriesAndFiles($paths, ['neon', 'yaml', 'xml']);
        $this->nonPhpFileProcessor->runOnFileInfos($neonYamlFileInfos);
```

**Comment by TomasVotruba** [comment]
I see, thanks. As a Rector user I would expect these to be independent on each other. Also static reflection might have already solved this.

Could you provide the smallest failing test case where this fails now and worked before? I'll try to look into it if it can be solved

**Comment by lulco** [comment]
I don't have one :) for now. I just think that probably some day it will be required.
