### ISSUE TITLE
Upgrade sets available in rector-prefixed

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#6268]
# Feature Request

Hi :) is there any reason why upgrade sets (upgrade directory) are not available in rector-prefixed? Recently I had to upgrade some older library using rector 0.9.x and I had to copy and paste the file rector_010.php from rector repository to my project.

**Comment by TomasVotruba** [comment]
Hi, the reason is that noone really needed it yet :) feel free to add them :+1:

**Comment by lulco** [comment]
ok I will prepare PR :)
