### ISSUE TITLE
[PHP8] Deprecated values in version_compare function's 3rd argument

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#6271]
# Feature Request

I've discovered by migrating Zend Framework 1 (see https://github.com/zendframework/zf1/blob/master/library/Zend/Xml/Security.php#L172 ) to PHP 8 (don't ask, you don't wanna know... :see_no_evil: ) that PHP's function `version_compare` used to accept `gte` and `lte` as 3rd arguments, whereas it now accepts `ge` and `le` in PHP 8.0 and up.
 
## Diff 

```diff
-version_compare(PHP_VERSION, '5.6', 'gte')
+version_compare(PHP_VERSION, '5.6', 'ge')
```

Here's the code running on most PHP versions : https://3v4l.org/9Lnhe
The `ge` and `le` values work in all PHP versions : https://3v4l.org/b28Hu (so there's no need to develop a "downgrader")

Is there already a Rector that could be used to alter this value, or should it be a custom development ?

Thanks for your insights.

**Comment by TomasVotruba** [comment]
Hi, extending rule might be a way
https://github.com/rectorphp/rector/blob/main/rules/Arguments/Rector/ClassMethod/ArgumentDefaultValueReplacerRector.php

**Comment by sabbelasichon** [comment]
Would you create a dedicated Rector for it? Or should it be a new configurable Rector for FuncCalls? Extending the existing to work also with FuncCall nodes make it rather complex.

**Comment by TomasVotruba** [comment]
>  Extending the existing to work also with FuncCall nodes make it rather complex.

Dedicated rule might a better way in here :+1:  There is couple of re-usable methods that can be extracted from the `ArgumentDefaultValueReplacerRector` code and used by both methods.

**Comment by sabbelasichon** [comment]
Assign me here. I will try to do implement a new Rector for it.

**Comment by gnutix** [comment]
Seems like there will be some more changes in PHP 8.1 too : https://php.watch/versions/8.1/version_compare-operator-restrictions

**Comment by TomasVotruba** [comment]
@gnutix Thanks for reference!

Thanks @Ayesh for making these posts :+1:

**Comment by TomasVotruba** [comment]
I recall this was resolved somewhere, or wasn't it? Just in case we missed the PR :)

**Comment by sabbelasichon** [comment]
It isn´t solved. I am on it.

**Comment by sabbelasichon** [comment]
Should this be part of a any available set?

**Comment by sabbelasichon** [comment]
If it doesn´t break any code if we change it to the bullet proof future version, it could be part of the Code Quality set. I am not really sure here.

**Comment by sabbelasichon** [comment]
@gnutix Do you think it makes sense to add this new rules to a specific Set shipped with Rector?

**Comment by TomasVotruba** [comment]
> whereas it now accepts ge and le in PHP 8.0 and up.

I think it should be part of PHP_80 set.
