### ISSUE TITLE
[config] report typo parameters

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#629]
*exclude_paths* parameter could by typoed as:

-> exclude_files
-> excluded_files
-> exclude_dir
-> excluded_dir

Report typo in parameters.
Use service

**Comment by carusogabriel** [comment]
@TomasVotruba How does PHPStan handles it? We could get some inspiration there :)

**Comment by TomasVotruba** [comment]
I think it's doesn't, myself got lost with "ignore_error" before
