### ISSUE TITLE
PHP 8.0 Downgrade missing one rule, not correctly applying another

### ISSUE THREAD

**Issue by Rumperuu** [rectorphp/rector#6315]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.10.16           |
| Installed as   | composer dependency                         |

The `SetList::PHP_80` includes [`ChangeSwitchToMatchRector`](https://github.com/rectorphp/rector/blob/c18327824304401098f762d43e36d298a42f830e/rules/Php80/Rector/Switch_/ChangeSwitchToMatchRector.php) and [`StrContainsRector`](https://github.com/rectorphp/rector/blob/c18327824304401098f762d43e36d298a42f830e/rules/Php80/Rector/NotIdentical/StrContainsRector.php). However, these are not downgraded when I run `DowngradeSetList::PHP_80`. 

[`DowngradeChangeMatchToSwitchRector`](https://github.com/rectorphp/rector/blob/main/config/set/downgrade-php80.php#L30) is listed, but isn't applied. No ‘DowngradeStrContainsRector’ seems to exist. 

`DowngradeChangeMatchToSwitchRector` also seems to block `DowngradeUnionTypeTypedPropertyRector` somehow.

## Minimal PHP Code Causing Issue

In [this demo](https://getrector.org/demo/4499ab39-35e5-4f8d-a4bf-b0ec5105efcc), it correctly applies `ChangeSwitchToMatchRector` but you can see that there is no ‘DowngradeStrContainsRector’. I have no idea why `ChangeSwitchToMatchRector` is working in the demo tool but not on my machine, as I copy-pasted both the `rector.php` and test file exactly. See my local terminal output (the PHP Notice happens whenever I run Rector, I don't think it's relevant here):

![Screenshot from 2021-05-03 19-31-48](https://user-images.githubusercontent.com/5621904/116917429-90aee000-ac46-11eb-82dd-31100527b36e.png)

If I then remove the `match` statement from my test file, `DowngradeUnionTypeTypedPropertyRector` runs. If I leave the `match` statement but remove only the `str_contains()` call, then it doesn't, so it definitely seems like `DowngradeChangeMatchToSwitchRector` is doing something fishy.

![Screenshot from 2021-05-03 19-32-12](https://user-images.githubusercontent.com/5621904/116918083-60b40c80-ac47-11eb-9fb9-84b1f2f981f1.png)

## Expected Behaviour

I've only just started using the tool and the fact that the demo tool is working (at least on points 1 & 2 below) makes me think it might be partly a local environment issue, but I can't think what it might be. Ideally, though, Rector should:

1. not have the running of one rector be affected by the failure of another;
2. correctly run the `DowngradeChangeMatchToSwitchRector`;
3. include a `DowngradeStrContainsRector`.

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting.
Where is `DowngradeStrContainsRector` in Rector code code? I can't find it.

For the other rule, we'll need a failing test case.
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by sabbelasichon** [comment]
@Rumperuu Could you add a failing test here or is your issue already solved?

**Comment by Rumperuu** [comment]
> @Rumperuu Could you add a failing test here or is your issue already solved?

### `DowngradeChangeMatchToSwitchRector`

I've not been able to write a failing test case, as the issue does not occur on the demo tool; as you can see [here](https://getrector.org/demo/0d8d5ee0-635a-4f59-a017-9b3ec4e4e097), both `DowngradeMatchToSwitchRector` and `DowngradeUnionTypeTypedPropertyRector` are correctly applied. However, when using identical `test.php` and `rector.php` on my local machine, neither rector gets applied; if I remove the `match` statement from `test.php`, `DowngradeUnionTypeTypedPropertyRector` _does_ get applied.

I've attached the files I am using, which are identical to those submitted to the demo tool. 

#### 
[mwe.zip](https://github.com/rectorphp/rector/files/6487590/mwe.zip)
Additional Testing

- I have upgraded to Rector v0.11.2;
- I have installed `php-intl` to suppress the warnings I was getting; and
- I have copied the same minimal project on three different devices (two running Ubuntu 21.04, one running 20.10):
    - one of the 21.04 was a fresh OS reinstallation and so should not have had any conflicting config settings in play.

The issue still occurs reliably on all devices, as does the unblocking of `DowngradeUnionTypeTypedPropertyRector` when I removed the `match` statement in `test.php`.

As far as I can tell it seems to be an Ubuntu-related issue, but as I don't any other devices available I'm unable to test with another OS.

### DowngradeStrContainsRector

I'll have a go at writing this rector tomorrow and see how I get on.

**Comment by Rumperuu** [comment]
I've written a `DowngradeStrContainsRector` with test fixtures, but I can't figure out where to place them or how to test it from the documentation.

`docker build .` fails at step 19/10 because `vendor/{nikic/php-parser,symplify/symfony-php-config}/` are missing. If I add them as dependencies manually, it fails due to the following error instead:

```
Fatal error: Uncaught Error: Class "Rector\Core\Console\Style\SymfonyStyleFactory" not found in /rector/bin/rector.php:34
```

I'm assuming the Docker step is required, because if I just run them from my normal terminal none of the commands in the [contributing guide](https://github.com/rectorphp/rector/blob/main/CONTRIBUTING.md), [test guide](https://github.com/rectorphp/rector/blob/main/docs/how_to_add_test_for_rector_rule.md) or [rector generator](https://github.com/rectorphp/rector-generator) work.

I've attached the files [here](https://github.com/rectorphp/rector/files/6489296/DownGradeStrContainsRector.zip), but I'm happy to submit a PR if you can point me in the right direction with doing so.

**Comment by TomasVotruba** [comment]
Hi, thanks for your effort. I'll try to help with the right direction.

Docker is not needed, also we don't use it for dev. Note that tests must be added in development repository: https://github.com/rectorphp/rector-src 

I guess that's the main issue. Let me know if you have more troubles adding test in  https://github.com/rectorphp/rector-src
