### ISSUE TITLE
T_ENUM Undefined class constants, on all ops, even --version

### ISSUE THREAD

**Issue by pierrejoye** [rectorphp/rector#6322]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Current (current version, cannot run --version                |
| Installed as   | composer dependency                                 |

Fail to execute altogether

## Minimal PHP Code Causing Issue

PHP 7.4.14 (cli)
> vendor/bin/rector --version
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 172.31.160.1:9003 (through xdebug.client_host/xdebug.client_port) :-(
PHP Fatal error:  Uncaught Error: Undefined class constant 'T_ENUM' in /home/pierre/test/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:517

## Expected Behaviour

Not sure, I did not debug yet, but standard PHP 7.4 install.

**Comment by samsonasik** [comment]
You can temporary pin:

```javascript
"nikic/php-parser": "4.10.4",
```

in your composer.json for now, see https://github.com/rectorphp/rector/blob/21bf53f2ec4a8e686f8cc437e7379eade99c0705/composer.json#L39

**Comment by pierrejoye** [comment]
Thanks for the quick reply! I will install from git (was using the phar as well :).

**Comment by TomasVotruba** [comment]
I've just released Rector 0.10.18 that pins php-parser to 4.10.4 :+1:

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector/commit/442b5b3d51e9a3cb00bbff5c9795ed5e6097ac72#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

Upgrade to next release:
https://packagist.org/packages/rector/rector#0.10.19

**Comment by pierrejoye** [comment]
thanks a lot!

**Comment by pierrejoye** [comment]
Not sure if it is related but now rector tries to get php-parser from the wrong vendor directory:

require_once(/home/pierre/.../vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Lexer.php): failed to open stream: No such file or directory

where vendor is located as usual in:

vendor/nikic/php-parser/lib/PhpParser/Lexer.php

**Comment by samsonasik** [comment]
@pierrejoye please try latest 0.10.19, rector should find the correct php-parser's vendor dir.
