### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by jdbaha** [rectorphp/rector#6334]
root@40b1d7f2a82d:/var/app# vendor/bin/rector init

Warning: require_once(/var/app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Lexer.php): failed to open stream: No such file or directory in /var/app/vendor/rector/rector/preload.php on line 5

Call Stack:
    0.0001     390640   1. {main}() /var/app/vendor/rector/rector/bin/rector:0
    0.0009     409096   2. require_once('/var/app/vendor/rector/rector/bin/rector.php') /var/app/vendor/rector/rector/bin/rector:4
    0.0023     460528   3. require_once('/var/app/vendor/rector/rector/preload.php') /var/app/vendor/rector/rector/bin/rector.php:29

Fatal error: require_once(): Failed opening required '/var/app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Lexer.php' (include_path='.:/usr/local/lib/php') in /var/app/vendor/rector/rector/preload.php on line 5

Call Stack:
    0.0001     390640   1. {main}() /var/app/vendor/rector/rector/bin/rector:0
    0.0009     409096   2. require_once('/var/app/vendor/rector/rector/bin/rector.php') /var/app/vendor/rector/rector/bin/rector:4
    0.0023     460528   3. require_once('/var/app/vendor/rector/rector/preload.php') /var/app/vendor/rector/rector/bin/rector.php:29

**Comment by samsonasik** [comment]
@jdbaha please try latest "rector/rector": "0.10.19"
