### ISSUE TITLE
Rector suddenly exists

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector#6342]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.10.19 |
| Installed as   | prefixed Rector                           |

```php
new EDDUpdater(...
```

This makes Rector stop without any output/exit status.

## Minimal PHP Code Causing Issue

Stops even when reducing to `new EDDUpdater();`

https://github.com/BracketSpace/Notification/blob/32a41db9da2cbdd4122c9f2ee354621ab1e5c3b8/src/classes/Admin/Extensions.php#L221

https://github.com/BracketSpace/Notification/blob/32a41db9da2cbdd4122c9f2ee354621ab1e5c3b8/src/classes/Utils/EDDUpdater.php

## Expected Behaviour

Continue operation.

Please help me.

**Comment by szepeviktor** [comment]
It turns out that class contained `if ( ! defined( 'ABSPATH' ) ) exit;`

I'm sorry.

**Comment by TomasVotruba** [comment]
That happens, no problem.

Would running PHPStan first help with this?

**Comment by szepeviktor** [comment]
> Would running PHPStan first help with this?

No, there is a WordPress extension that knows of `ABSPATH` ([developed by me](https://github.com/szepeviktor/phpstan-wordpress))

**Comment by TomasVotruba** [comment]
I see
