### ISSUE TITLE
Running the process command without defining a rule is still processing

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6361]
As @lulco already mentioned in one issue the RenameClassNonPhpRector is always registered and therefore running rector without defining a rule be it a Php one or from another FileProcessor the MissingRectorRulesReporter is not popping up. 

I guess the simplest solution would be to do this:
```php
$activeRectors = array_filter($this->rectors, function (RectorInterface $rector): bool {
            return ! $rector instanceof PostRectorInterface && ! $rector instanceof NonPhpRectorInterface;
        });
```

**Comment by TomasVotruba** [comment]
This shoud be refactored to opt-in rule instead.
