### ISSUE TITLE
Documentation about FileProcessors

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6374]
I would like to document, as promised, the new FileProcessors API.

@lulco:
Would you like to join me? 
I would like to talk about the FileProcessors and the FileFormatters together because this seem somehow interconnected.

**Comment by lulco** [comment]
Yes!
But first I have to learn how it works now and finish this PR https://github.com/rectorphp/rector-nette/pull/7 :)

**Comment by TomasVotruba** [comment]
Just checking, what blockers are to move this forward?

**Comment by sabbelasichon** [comment]
None.

**Comment by sabbelasichon** [comment]
At least for me. Lacking of time ;-)

**Comment by lulco** [comment]
Few notes from me after working on some nette non-php file processors. {Type} can be some file type:
- we need some {Type}RectorInterface which extends RectorInterface (here we can add some methods to change content)
- implement some services of {Type}RectorInterface which do their work (they change content of supported files)
- than we need some {Type}FileProcessor which implements FileProcessorInterface (as parameter in constructor, there is an array of {Type}RectorInterface). It just iterate all supported files and apply all {Type}Rectors

But that's obvious, right? :D

**Comment by sabbelasichon** [comment]
@lulco Thanks. Sound good. Yes, for you and me it is obvious, but not for others, so you added already good points to start with from a beginners perspective. Would you be able to start a PR with some notes and i try to add or comment on it?

**Comment by lulco** [comment]
I'm not very comfortable with writing documentation O:-) that's why I wrote those notes for you :)

**Comment by sabbelasichon** [comment]
I am on it.
