### ISSUE TITLE
Add PHP 5.3 to 7.4 upgrades

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#638]
Mission: develop PHP core faster without letting anyone behind.

# Resources

- [x] https://github.com/php/php-src/blob/PHP-7.2/UPGRADING

- [x] PHP 7.3 Regex regression - https://github.com/rectorphp/rector/pull/847

    ```diff
    -preg_match("#[\w-()]#", 'some text');
    +preg_match("#[\w\-()]#", 'some text');
    ```

- [x] **https://www.oreilly.com/ideas/upgrading-to-php7 - VERY GOOD**
- [x] https://auth0.com/blog/amp/migrating-a-php5-app-to-php7-part-two/

- [x] https://github.com/php/php-src/blob/PHP-7.0/UPGRADING
- [x] https://github.com/php/php-src/blob/PHP-7.1/UPGRADING

- [x] removed `create_function`, [e.g. PR](https://github.com/Automattic/jetpack/pull/8478/files#diff-e854d0045a643c0938d4cb9816afc4f3R273), [PR2](https://github.com/Automattic/jetpack/pull/8870/files)

- [x] Interesting source: https://www.exakat.io/get-ready-php-7-2/
- [x] PHP 7.1 argument count - https://www.reddit.com/r/PHP/comments/a1ie7g/is_there_a_linter_for_argumentcounterror_for_php/

- [x] https://wiki.php.net/rfc/null_coalesce_equal_operator `??=`
- [x] https://www.exakat.io/get-ready-php-7-2/  - function changes + `get_class(null);` - https://github.com/rectorphp/rector/pull/842
- [x] PHP 7.1 typehints to code, same as properties typehints - https://github.com/rectorphp/rector/pull/795
- [x] PHP 7.3 flexible here/now doc - https://github.com/rectorphp/rector/pull/707
- [x] case insensitive constants: 
https://wiki.php.net/rfc/case_insensitive_constant_deprecation, https://github.com/nikic/php-src/blob/fb60f60ad8b459ea635b1dab762bb1c7f8de3977/Zend/tests/case_insensitive_constant_deprecation.phpt  [PHP73]
- [x] removed functions and their alternatives - https://github.com/PHPCompatibility/PHPCompatibility/blob/master/PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php 	
- [x] `echo VAL;`, if VAL is not a constant, it returns "VAL" string → use constant or "...", ref: http://php.net/manual/en/migration72.deprecated.php - https://wiki.php.net/rfc/deprecate-bareword-strings
 [PHP72]
- [x] https://github.com/php/php-src/blob/PHP-7.3/UPGRADING
- [x] https://www.reddit.com/r/PHP/comments/80x2gb/53_to_72/
- [x] count() requires not `null`
    - detect type and use `is_countable` pre-run
    - https://www.drupal.org/files/issues/2018-06-06/2977851-views-php72-count-2.patch
    - https://www.drupal.org/files/issues/2018-09-11/2885610-32-followup.patch
- [x] https://www.tomasvotruba.cz/blog/2018/08/16/whats-new-in-php-73-in-30-seconds-in-diffs/
    - [x] `array_key_first`
    - [x] `array_key_last`
- [x] `is_countable`, Thanks @carusogabriel 
- [x] `is_iterable`, Thanks @carusogabriel 
- [x] assings items to strings no more
    ```php
    $var = '';
    $var[] = 1;
    ```
- [x] ereg to preg - https://stackoverflow.com/questions/6270004/how-can-i-convert-ereg-expressions-to-preg-in-php
- [x] List cannot be empty - https://github.com/PHPCompatibility/PHPCompatibility/blob/master/PHPCompatibility/Sniffs/Lists/ForbiddenEmptyListAssignmentSniff.php

- [x] https://github.com/Alexia/php7mar/blob/master/classes/tests/critical.php
- [x]  http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.list
- [x] removed `each()`
- [x] https://auth0.com/blog/migrating-a-php5-app-to-php7-part-two/
- [x] `list()` can no longer unpack string variables. str_split() should be used when performing this form of operation.
- [x] multiple exceptoins - https://wiki.php.net/rfc/multiple-catch
- [x] https://devel.cz/otazka/migrace-z-php-5-6
- [x] https://support.acquia.com/hc/en-us/articles/360005438654-Upgrading-from-PHP-5-6-to-7-1-or-7-2
- [x] PHP 7.4 as well: https://twitter.com/SammyK/status/1044962340616261634 - use attribute for php74_type + modify printer for property
- [x] PHP 7.2 - parse_str, 2nd argument
- [x] Php72 - https://stackoverflow.com/questions/7081896/anyone-ever-used-phps-unset-casting
- [x] new reserved keyword: object, create general Rector
- [x] https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/f070c3ac21ebcfa1ad89f454bc23ae956146fe3e/src/RuleSet.php#L199-
- [x] Multi switches - https://3v4l.org/iGDVW
- [x] pow → exp `**`
- [x] `isset() ? : ` → `??`
- [x] `*_random` methods
- [x] public constant
- [x] PHP4 construct
- [x] nested dirname()

**Comment by TomasVotruba** [comment]
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/f070c3ac21ebcfa1ad89f454bc23ae956146fe3e/src/RuleSet.php#L257

**Comment by carusogabriel** [comment]
:+1: For this one. There're some PHPUnit Assertions that are only available in some versions, and there are also some PHP functions in the same boat

**Comment by TomasVotruba** [comment]
Do you know any **nice** references for A -> B changes in PHP apart the php cs fixer one?

A not the list of all changes please :D

**Comment by TomasVotruba** [comment]
Include 7.4 as well: https://twitter.com/SammyK/status/1044962340616261634

https://www.tomasvotruba.cz/blog/2018/08/16/whats-new-in-php-73-in-30-seconds-in-diffs/

**Comment by TomasVotruba** [comment]
PHP 7.2

- `echo VAL;`, if VAL is not a constant, it returns "VAL" string → use constant or "...", ref: https://youtu.be/rKXFgWP-2xQ?t=1160

**Comment by TomasVotruba** [comment]
https://github.com/php/php-src/blob/PHP-7.3/UPGRADING

**Comment by carusogabriel** [comment]
- PHP 7.0 -> 7.1

```diff
-is_array($foo) || $foo instanceof Traversable
+is_iterable($foo)
```

- PHP 7.2 -> 7.3
```diff
-is_array($foo) || $foo instanceof Countable
+is_countable($foo)
```

**Comment by carusogabriel** [comment]
> PHP 7.4 as well: https://twitter.com/SammyK/status/1044962340616261634 - use attribute for php74_type + modify printer for property

@TomasVotruba This should be handled by CS, not Rector :)

**Comment by TomasVotruba** [comment]
Why?

**Comment by carusogabriel** [comment]
@TomasVotruba Should be pretty straightforward for CS handle this migration. Rector is supposed to handle more complex and complicated changes.

Move a docBlock to a type is already handled:
```diff
-/**
- * @return string
- */
-public function foo()
+public function foo(): string
```

So shouldn't be that difficult to handle
```diff
-/** @var string */
-public $foo;
+public string $foo;
```

But is up to you, as I wouldn't have the time to code it.

**Comment by TomasVotruba** [comment]
I've gotten lot of intel that most folks needs update they code safely from PHP 5.3 to 7 (at least).

It can be done, yes. But CS tools still work only with tokens. That's not safe at all. Imagine if PHPStan would rely on tokens.

**Comment by TomasVotruba** [comment]
You've challanged me to write a prototype before going :sleeping: :smile:  : 
https://github.com/rectorphp/rector/pull/643

**Comment by carusogabriel** [comment]
> isset() ? : → ??

@TomasVotruba This is already handled at Slevomat, recognizing even `if/else`

**Comment by TomasVotruba** [comment]
It's still this case: https://github.com/rectorphp/rector/issues/638#issuecomment-425660987

I'll check it, thanks :+1:

**Comment by TomasVotruba** [comment]
@carusogabriel I've merged our Iterable/Countable comments to points above. Just to make it clear what is done and what is not.

**Comment by TomasVotruba** [comment]
Php72 - https://stackoverflow.com/questions/7081896/anyone-ever-used-phps-unset-casting

**Comment by TomasVotruba** [comment]
Php 7.3, flexible herenowdoc

This change was actually brought up in a previous RFC (PHP RFC: Loosening heredoc/nowdoc scanner). One of the big gotchas that it mentioned, however, was that if the ending marker was found at the start of a line, then regardless of whether it was a part of another word, it would still be considered as the ending marker. For example, the following would not work (due to ENDING containing END):

$values = [<<<END
a
b
ENDING
END, 'd e f'];
/*
Parse error: syntax error, unexpected 'ING' (T_STRING), expecting ']' in %s on line %d

Ref: https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

**Comment by TomasVotruba** [comment]
Replicate constant loading as in here:
https://stackoverflow.com/questions/17404351/including-php-defines-using-composer

**Comment by TomasVotruba** [comment]
Interesting source: https://www.exakat.io/get-ready-php-7-2/

**Comment by TomasVotruba** [comment]
Related https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3258

**Comment by TomasVotruba** [comment]
### PHP 7.3 Regex regression

```diff
-preg_match("#[\w-()]#", 'some text');
+preg_match("#[\w\-()]#", 'some text');
```

- https://github.com/dmitry-kulikov/yii2-domain-validator/commit/f35d0f36a9c924ada72767235a17e97840c6dc8a
- https://3v4l.org/OqMP4

**Comment by TomasVotruba** [comment]
### PHP 7.1 argument count

- https://www.reddit.com/r/PHP/comments/a1ie7g/is_there_a_linter_for_argumentcounterror_for_php/
- http://php.net/manual/en/class.argumentcounterror.php

**Comment by TomasVotruba** [comment]
## PHP 7.3

- compact() usage with undefined variables

**Comment by TomasVotruba** [comment]
- good source https://github.com/PHPCompatibility/PHPCompatibility/tree/master/PHPCompatibility/Sniffs

**Comment by TomasVotruba** [comment]
Closing as the main set is completed now.

For any following idea, just open a new issue with `[PHP X.Y] ...` naming.

That will keep issues separated.
