### ISSUE TITLE
Show Progressbar for every FileProcessor

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6380]
At the moment the Progressbar is only shown for the PhpFileProcessor. Would be nice to show the ProgressBar for every FileProcessor. Would like to create a PR for that.

**Comment by TomasVotruba** [comment]
Hi, I wonder what would the added value that for end-user?

I mean we don't run have multiple progress bars in PHPUnit for unit tests, functional tests, integration tests...

If we clutter user with information, it musts bring them value.

**Comment by sabbelasichon** [comment]
I see and agree. But now there is no feedback for user when running FileProcessors other than the Php one.

**Comment by TomasVotruba** [comment]
There should be diff files in case of change.

**Comment by sabbelasichon** [comment]
I am gonna think about it.

**Comment by sabbelasichon** [comment]
The diff is there. That´s true. But until the diffs are shown no user feedback or application status is shown if you only run other FileProcessors other than the Php one. I know everything started with Php but now we have also other formats. Would really like to have some ProgressBar for other formats. Otherwise you gonna wait some time depending on the amount of files which are processed.

**Comment by sabbelasichon** [comment]
@TomasVotruba To not spoil the list on issues here, i would like to close this one here. In practice it is not a big deal. 

I am still struggling with the part to split up the PhpFileProcessor to run the files one by one. Maybe someday we will have an idea how to do it. But for now i don´t care.
