### ISSUE TITLE
Caching is not working anymore.

### ISSUE THREAD

**Issue by mssimi** [rectorphp/rector#6389]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.10.5 and greater            |
| Installed as   | composer dependency                      |

Rector cache is not working(processing all files over and over). I am like 99% sure this pull request(https://github.com/rectorphp/rector/pull/6085) is the cause. 

Latest version with working caching is v0.10.4.

**Comment by samsonasik** [comment]
Looking at the `ProcessCommand`, the following code:

```php
$files = $this->fileFactory->createFromPaths($paths);
```

call `FileFactory's` `createFromPaths()`:

https://github.com/rectorphp/rector/blob/e7ea2f625d4a418b739ec3cbed0ddbe8adb6d0f1/src/ValueObjectFactory/Application/FileFactory.php#L39-L42

The code:

```php
$fileInfos = $this->filesFinder->findInDirectoriesAndFiles($paths, $supportedFileExtensions);
```

call : 

https://github.com/rectorphp/rector/blob/e7ea2f625d4a418b739ec3cbed0ddbe8adb6d0f1/src/FileSystem/FilesFinder.php#L74-L76

which check `cache` key. Somehow, the cache is always cleared on after created of cache data on next command:

https://github.com/rectorphp/rector/blob/e7ea2f625d4a418b739ec3cbed0ddbe8adb6d0f1/src/FileSystem/FilesFinder.php#L90-L91

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/270
