### ISSUE TITLE
Cannot autowire service "Rector\PHPUnit\Rector\Class_\AddProphecyTraitRector"

### ISSUE THREAD

**Issue by alanbem** [rectorphp/rector#6400]
Subject | Details
-- | --
Rector version | v0.10.21
Installed as | composer dependency

![image](https://user-images.githubusercontent.com/320410/117588996-5ef6b700-b127-11eb-9ea6-26239ac3df60.png)

I can not tell you anything more as I didn't investigate the problem further.

edit:
Problem occurred in my CI pipeline and it was caused by running `composer install --no-scripts --no-interaction --optimize-autoloader --ansi`. 
Removing ` --no-scripts` fixed the issue.

**Comment by TomasVotruba** [comment]
Hi, removing `--no-scripts` is the way to go.
See https://github.com/rectorphp/rector/issues/6347
