### ISSUE TITLE
Incorrect behavior of SimplifyUselessVariableRector with return-by-ref functions

### ISSUE THREAD

**Issue by webmaster777** [rectorphp/rector#6401]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/fa9b69b8-58ba-4f8c-b06b-ff59b18f795c

```php
<?php
interface ValueAccessor
{
    public function & accessValue($object, $memberName);
}
final class DemoFile implements ValueAccessor
{
    public function & accessValue($object, $memberName)
    {
        $value = count($object);
        return $value;
    }
}
```

NB: I am completely aware that return-by-ref and param-by-ref is a snake pit and that this kind of code should be abolished. Dealing with legacy code here.

### Responsible rules

* `SimplifyUselessVariableRector`

## Expected Behavior

return by ref must return a var or use a function that returns by-ref. `count()` does not return by-ref. If the change is applied this will result in PHP warnings: https://3v4l.org/f8GDO

Rector should skip this kind of return statements for simplifying.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by webmaster777** [comment]
like this? https://github.com/rectorphp/rector-src/pull/15

**Comment by webmaster777** [comment]
Small addendum: I implemented skipping whenever the "functionlike" of the return statement returns by reference. However, if the expression is a reference it could still be optimized.

e.g.

```php
<?php

function & foo()
{
  $x = new stdClass();
  return $x;
}

function & bar()
{
  $result = foo();
  return $result;
}

$x = bar();
```

`bar()` could be optimized to:

```php
function & bar()
{
  return foo();
}
```

because foo() returns by ref.

That would require additional checking of the "to-be-optimized" expression.

**Comment by TomasVotruba** [comment]
Good idea!

That is handled by one of rules from dead code.
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#removeunusedassignvariablerector
