### ISSUE TITLE
[ERROR] Class "Symplify\ComposerJsonManipulator\Bundle\ComposerJsonManipulatorBundle" not found                        

### ISSUE THREAD

**Issue by ekinhbayar** [rectorphp/rector#6407]
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.10.21             |
| Installed as   | composer dependency                           |

Hi! First of all, thanks a lot for your time and effort in this project. I really appreciate all your work :heart:!

I'm having trouble with the latest release 0.10.21 to the point that I cannot run `vendor/bin/rector --version` or `vendor/bin/rector init`, anything really. Both of those commands give me the error mentioned in the issue title: `[ERROR] Class "Symplify\ComposerJsonManipulator\Bundle\ComposerJsonManipulatorBundle" not found`

We've noticed this as part of our CI setup in a project where we ran rector on our highest dependencies, however I can see this happening just by dev-requiring the project on a barebone repository.

## Minimal PHP Code Causing Issue

Start an empty project ([here is mine](https://github.com/ekinhbayar/rector-bug0.10.21)).

composer dev-require rector/rector; 
`vendor/bin/composer require --dev rector/rector`

Try to run any of below commands:
`vendor/bin/rector --version`
`vendor/bin/rector init`

## Expected Behaviour

Any output but a failure with `[ERROR] Class "Symplify\ComposerJsonManipulator\Bundle\ComposerJsonManipulatorBundle"`

**Comment by TomasVotruba** [comment]
Hi, thank you for your report and exact steps how to reproduce :+1: 

This should be fixed as described in duplicated issue:
https://github.com/rectorphp/rector/issues/6406
