### ISSUE TITLE
rector/rector-prefixed is already abandoned while rector/rector is not yet tagged

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#6409]
Composer is complaining that `rector/rector-prefixed` is abandoned and that I should upgrade to `rector/rector`. But that's not possible because it's not yet tagged. 

I would suggest to undo the abandon until `rector/rector` is tagged.

**Comment by TomasVotruba** [comment]
Souds legit! :+1:

**Comment by TomasVotruba** [comment]
It's abou time now https://github.com/rectorphp/rector/releases/tag/0.11.0 :)

**Comment by ruudk** [comment]
Happy to hear! Thanks 😊
