### ISSUE TITLE
Rector Demo isn't doing any transformations

### ISSUE THREAD

**Issue by tylerc** [rectorphp/rector#6412]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Whatever getrector.org is running              |
| Installed as   | https://getrector.org/demo/                           |

I've been working through understanding which Rector transformations make the most sense for the project I'm working on, and in the past I've used the demo page https://getrector.org/demo as an easy way to try some experiments.

Today when I tried it, I always get "What did Rector change?" `// no change` no matter what input or configuration I use.

For example, the default demo showing dead code elimination is doing nothing for me:

![image](https://user-images.githubusercontent.com/42798/118156397-29bfc280-b3ce-11eb-957d-3cd57afd1829.png)

## Expected Behaviour

I'd expect the default demo to work at least.

**Comment by TomasVotruba** [comment]
Thanks for reporting, we'll look into it :+1:

**Comment by TomasVotruba** [comment]
Should be fixed: https://getrector.org/demo/800bb28b-4dc3-4fd4-9584-60f7867ce4d3

**Comment by tylerc** [comment]
Lookin' good! Thanks!
