### ISSUE TITLE
Class Symplify\PackageBuilder\Strings\StringFormatConverter not found on custom rule

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6414]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main              |
| Installed as   | composer dependency                           |

## Minimal PHP Code Causing Issue

When consuming `Symplify\PackageBuilder\Strings\StringFormatConverter` on custom rector rule, it got error:

```bash
 [ERROR] Cannot autowire service "App\Rector\UnderscoreToCamelCaseVariableNameRector": argument                       
         "$stringFormatConverter" of method "__construct()" has type                                                    
         "Symplify\PackageBuilder\Strings\StringFormatConverter" but this class was not found.    
```

We can test in `CodeIgniter4` project with `rector/rector:dev-main`, on custom rule at 

https://github.com/codeigniter4/CodeIgniter4/blob/43e0e9611b7e527a4b927127fc6f26a1c6d123a5/utils/Rector/UnderscoreToCamelCaseVariableNameRector.php#L16

When its dependency removed, another error shows:

```bash
Uncaught Error: Class 'Nette\Utils\Strings' not found
```

## Expected Behaviour

It should works. Possible solutions:

- skip prefixing for symplify and nette/utils packages
- add documentation for possible missing deps that need to be manually added if create custom rules.

**Comment by TomasVotruba** [comment]
Hi, this expected behavior, because this dependency is now Rector's internal.

That means any your local dependency that was accidentaly required by Rector too, must be included explicitly now.


This would be a way to go:

> add documentation for possible missing deps that need to be manually added if create custom rules.

:+1:

**Comment by TomasVotruba** [comment]
P.S. Be sure to use stable tag Rector `0.11.1` to avoid in-between version breaks
