### ISSUE TITLE
Throw exception when provideConfigFilePath is not overridden

### ISSUE THREAD

**Issue by matthiasnoback** [rectorphp/rector#6415]
When upgrading from Rector 0.8 to 0.11, you should no longer implement `provideConfigFileInfo()` in tests but instead return the config file path from `provideConfigFilePath()`. If you don't do this, the error you get will be hard to interpret and fix:

```
File path "" was not found while creating "RectorPrefix20210514\Symplify\SmartFileSystem\SmartFileInfo" object.
 /opt/project/vendor/rector/rector/vendor/symplify/smart-file-system/src/SmartFileInfo.php:31
 /opt/project/vendor/rector/rector/packages/Testing/PHPUnit/AbstractRectorTestCase.php:58
 /opt/.phpstorm_helpers/codeception.php:51
 ```

The empty string comes from the default implementation in `AbstractRectorTestCase`, but instead of saying "// must be implemented` and returning `''` it should throw an exception (imo) because it will help the user find out what's wrong.

**Comment by matthiasnoback** [comment]
(or mark the method as `abstract`?)

**Comment by sabbelasichon** [comment]
I think there was a time where different options were possible like use this class or either this config file. But now as far as i can see this is the only option to configure which rules should be applied.

**Comment by sabbelasichon** [comment]
The method is already required through the RectorTestInterface. So no need to mark it as abstract.

**Comment by matthiasnoback** [comment]
> The method is already required through the RectorTestInterface. So no need to mark it as abstract.

Ah, I didn't know. In that case I think it should not be implemented in `AbstractRectorTestCase`.

**Comment by sabbelasichon** [comment]
Best Pull Request i ever had: https://github.com/rectorphp/rector-src/pull/32/files
Put both together, what´s the result ;-)

**Comment by sabbelasichon** [comment]
This can be closed.

**Comment by samsonasik** [comment]
@sabbelasichon I closed it, thank you.
