### ISSUE TITLE
Incorrect behavior of DowngradeStreamIsattyRector

### ISSUE THREAD

**Issue by pdelre** [rectorphp/rector#6416]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e5905dc9-f669-4f6e-9e11-f272dffa61af

```php
<?php

final class DemoFile
{
    public function run($stream)
    {
        return stream_isatty($stream);
    }
}
```

### Responsible rules

* [`DowngradeStreamIsattyRector`](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#downgradestreamisattyrector)

## Expected Behavior

The resulting code relies on [`posix_isatty`](https://www.php.net/manual/en/function.posix-isatty.php) being defined, which requires the POSIX extension to be loaded. When the extension is not loaded, consuming execution fails with the following example.

```
PHP Fatal error:  Uncaught Error: Call to undefined function posix_isatty() in /workdir/vendor/symplify/easy-coding-standard/vendor/symfony/console/Output/StreamOutput.php:103
--
  | Stack trace:
  | #0 /workdir/vendor/symplify/easy-coding-standard/vendor/symfony/console/Output/StreamOutput.php(105): ECSPrefix20210513\Symfony\Component\Console\Output\StreamOutput->ECSPrefix20210513\Symfony\Component\Console\Output\{closure}()
  | #1 /workdir/vendor/symplify/easy-coding-standard/vendor/symfony/console/Output/StreamOutput.php(47): ECSPrefix20210513\Symfony\Component\Console\Output\StreamOutput->hasColorSupport()
  | #2 /workdir/vendor/symplify/easy-coding-standard/vendor/symfony/console/Output/ConsoleOutput.php(40): ECSPrefix20210513\Symfony\Component\Console\Output\StreamOutput->__construct()
  | #3 /workdir/vendor/symplify/easy-coding-standard/vendor/symplify/package-builder/src/Console/Style/SymfonyStyleFactory.php(32): ECSPrefix20210513\Symfony\Component\Console\Output\ConsoleOutput->__construct()
  | #4 /workdir/vendor/symplify/easy-coding-standard/b in /workdir/vendor/symplify/easy-coding-standard/vendor/symfony/console/Output/StreamOutput.php on line 103
```

The impact of this can be seen in `symplify/easy-coding-standard`'s transformation of `symfony/console`'s [`StreamOutput::hasColorSupport`](https://github.com/symplify/easy-coding-standard/blob/main/vendor/symfony/console/Output/StreamOutput.php#L86).

`symfony/console` might have a hint in an alternative solution without the dependency on the POSIX extension. In 4.4, they had a slightly different ordering to verify if a stream was TTY capable, which was changed for 5.0 (dropping 7.1.x support in turn) in https://github.com/symfony/symfony/commit/c9b8b046a7ec2c2b722156813fa7df683110375b

```php
if (\function_exists('stream_isatty')) {
    return @stream_isatty($this->stream);
}

if (\function_exists('posix_isatty')) {
    return @posix_isatty($this->stream);
}

$stat = @fstat($this->stream);
// Check if formatted mode is S_IFCHR
return $stat ? 0020000 === ($stat['mode'] & 0170000) : false;
```

**Comment by TomasVotruba** [comment]
Hi, thank for analysis. Could you add downgrade rule for this function?
