### ISSUE TITLE
Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector with callable

### ISSUE THREAD

**Issue by MartkCz** [rectorphp/rector#6421]
# Bug Report

Version: `Rector dev-main`

Code:
```php
	/** @var callable */
	private $fallback;

	/**
	 * @param mixed[] $cache
	 */
	public function __construct(callable $fallback, private array $cache = [])
	{
		$this->fallback = $fallback;
	}
```

rector's result:
```php
public function __construct(private callable $fallback, private array $cache = [])
```

`callable` argument type is not valid

**Comment by TomasVotruba** [comment]
Thank you for your report and clear example!

Could you send a failing test case in a pull-request to https://github.com/rectorphp/rector-src, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
