### ISSUE TITLE
Exclude a single rule when using a set

### ISSUE THREAD

**Issue by dnna** [rectorphp/rector#6422]
# Question
Hello,

First of all, I was recently introduced to rector and I would like to say it really is awesome and something that was sorely missing from the PHP ecosystem.

One thing that I haven't been able to find a solution for, is that I want to use a set (let's say CODE_QUALITY), but I want to exclude a single rule from it (for example RemoveExtraParametersRector). I looked something like `$services->unset`, but I haven't been able to find anything to allow me to remove a rule once set.

Is there a way to achieve this other than creating my own set?

**Comment by sabbelasichon** [comment]
Look for Option::SKIP parameter.

**Comment by dnna** [comment]
Ah, it's quite different than I expected, but that works, thank you!
