### ISSUE TITLE
[downgrade] the scoped bootstrap.php has to be downgraded too

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6426]
This file would crash on PHP 7.0 and bellow - https://github.com/rectorphp/rector/blob/main/bootstrap.php

Similar fix in ECS: https://github.com/symplify/symplify/pull/3210/commits/b64e2f1f78139f86f30e34ca1edf6d936dac7d2a

<br>

See 

![image](https://user-images.githubusercontent.com/924196/118542279-16f11900-b753-11eb-9b89-0992cd723587.png)

**Comment by samsonasik** [comment]
Handled at https://github.com/rectorphp/rector-src/pull/50/commits/028491a1ccdf84f1b94d2904449d7d29534a2999

**Comment by TomasVotruba** [comment]
Already known
