### ISSUE TITLE
[Downgrade] If PHP 7.0 set is included, it breaks downgrade of scalar types

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6427]
See https://github.com/symplify/easy-coding-standard/runs/2603926642

Hotfix: https://github.com/symplify/symplify/pull/3210/files#diff-c28bbabd03454fe04f6720d5e3fc69073771426caacc643d000d7d81415097e2

**Comment by samsonasik** [comment]
@TomasVotruba it may related with notice on https://github.com/rectorphp/rector-src/pull/68#issuecomment-846369714 comment, I still couldn't reproduce in failing test case for it.

**Comment by TomasVotruba** [comment]
Closing for lack of failing test case.
