### ISSUE TITLE
Disable Pull Requests on this repository

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6431]
Hi @TomasVotruba , I think Pull Request should be disable for this repository so contributor can send pull request to https://github.com/rectorphp/rector-src instead.

**Comment by TomasVotruba** [comment]
Hi @samsonasik, good idea! This is not possible in GitHub itself though.
Any ideas how to limit it?

**Comment by samsonasik** [comment]
@TomasVotruba this repo-lockdown action probably can be used https://github.com/dessant/repo-lockdown .

Also, add contributing.md like @garak mentioned at https://github.com/rectorphp/rector/pull/6430#issuecomment-843145641

**Comment by TomasVotruba** [comment]
I tried the dessant/repo-lockdown in @symplify, but it requires an access token from the contributors, AFAIK.

**Comment by samsonasik** [comment]
auto-closer github action can be alternative, for example:

https://github.com/laminas/laminas-db/blob/7663f838059e27da94df02fe4aa88c2c7fd7aa1c/.github/workflows/auto-close.yml

It may needs organization token which seems can be saved at .github repository in org level, eg: https://github.com/laminas/.github

The example result is : https://github.com/laminas/laminas-db/issues/189#issuecomment-819573099

**Comment by samsonasik** [comment]
Handled by https://github.com/rectorphp/rector-src/pull/84 demo https://github.com/rectorphp/rector/pull/6445#issuecomment-845367214
