### ISSUE TITLE
Phpdoc on Stmt_InlineHTML

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6439]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.9.5 (invoke `vendor/bin/rector --version`)  0.11.5            |
| Installed as   | composer dependency / prefixed Rector                           | 

## Minimal PHP Code Causing Issue

given a file containing `<h1><?php echo $hello; ?></h1>`

with ast
```
array(
    0: Stmt_InlineHTML(
        value: <h1>
    )
    1: Stmt_Echo(
        exprs: array(
            0: Expr_Variable(
                name: hello
            )
        )
    )
    2: Stmt_InlineHTML(
        value: </h1>
        )
```

when adding a phpdoc to Stmt_InlineHTML

```php
assert($statement instanceof Stmt_InlineHTML);
$phpDocInfo = $this->phpDocInfoFactory->createFromNodeOrEmpty($statement);

$phpDocInfo->addTagValueNode(new VarTagValueNode(new IdentifierTypeNode('string'), '$hello', ''));

```

i would expect a final html of

```php

<?php
/**
 * @var string $hello
 */
?>
<h1><?php echo $hello; ?></h1>

```

but I get

```php

/**
 * @var string $hello
 */
<h1><?php echo $hello; ?></h1>

```

**Comment by staabm** [comment]
Any feedback? Do you agree this is a bug?

If so I would be willing to work on it... could I have some pointers where to start?

**Comment by TomasVotruba** [comment]
I actually don't work with inlined HTML nodes, so I can't help here. Rector is waiting for the spaghetti expert who would teach it :)

Contribution is welcomed :+1:

**Comment by staabm** [comment]
thx for the feedback.

initially I thought its a problem with `PhpDocInfo`. I feel like I realized that since the phpdoc itself is correct, its just placed onto the wrong node (or it needs the php-tags wrapped arround it) there most be some logic somehwere which inserts the phpdoc into the ast.

could you give me a pointer where to look?

**Comment by staabm** [comment]
In the meantime, while trying to reproduce the problem in a unit tests, I think I found out that the unit test should not be put into `PhpDocInfoTest` or `PhpDocInfoPrinterTest`.

there must be some glue logic somehwere which brings the phpdoc into the ast, and for this class in question the unit test needs to be added.

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector-src/pull/88
