### ISSUE TITLE
Is it possible to refactor to use a method instead of a property on calling class X ?

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#6440]
# Question

I have the following deprecations:
```
  7x: Since fakerphp/faker 1.14: Accessing property "word" is deprecated, use "word()" instead.
    1x in WunschnameTest::fromStringProvider from App\Tests\Unit\Domain\Value\Abo
    1x in GegnerTest::fromStringProvider from App\Tests\Unit\Domain\Value\Akte
    1x in VentureTest::fromStringProvider from App\Tests\Unit\Domain\Value\Akte
    1x in HandynummerTest::fromStringProvider from App\Tests\Unit\Domain\Value\User
    1x in IconTest::fromStringProvider from App\Tests\Unit\External\Value
    1x in AboVoterTest::voteProvider from App\Tests\Unit\Security\Voter
    1x in UserTest::canSetAndGetRoles from App\Tests\Unit\Entity
```

Is there a way rector can help me with this transition? Property to method call or sth like that?

Cheers, Oskar

**Comment by TomasVotruba** [comment]
Hi, I'm not sure what does that mean. 
Could you provide a minimal diff example in pseudo code?

**Comment by OskarStark** [comment]
Sure sorry:

```diff
-$faker->word
-$faker->word()
```

if `$faker` is instance of `\Faker\Generator`

**Comment by TomasVotruba** [comment]
I see. Check existing rules with "node A" to "node B".
In this I would look for `PropertyFetchToMethodCall`

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#propertyfetchtomethodcallrector

**Comment by sabbelasichon** [comment]
This does not work. I haven´t found a configurable for that. But find it very useful. Let´s do it.

**Comment by TomasVotruba** [comment]
@sabbelasichon Should be part of `PropertyFetchToMethodCallRector`.

**Comment by sabbelasichon** [comment]
Because it is listening to Assign. And not every PropertyFetch is part of an Assignment. I will show you an example

**Comment by sabbelasichon** [comment]
https://getrector.org/demo/f7bf642b-548e-4ff9-866e-ba765b052af5

**Comment by TomasVotruba** [comment]
I see. It should be fixed then

**Comment by sabbelasichon** [comment]
I am gonna fix it.

**Comment by OskarStark** [comment]
Thank you @sabbelasichon

**Comment by sabbelasichon** [comment]
In the case of faker where __get and __call magic methods are used, it would be even cooler to have also some kind of magic in the rector rule. I am gonna think about it, how we could achieve this.

**Comment by sabbelasichon** [comment]
So refactor every propertyfetch of object x to the method call with the same name.

**Comment by sabbelasichon** [comment]
@OskarStark Just in case you missed it. What you could in order to achieve the modification from property to method call is this here:

```php
use Rector\Transform\Rector\Assign\PropertyFetchToMethodCallRector;
use Symplify\SymfonyPhpConfig\ValueObjectInliner;
use Faker\Generator;
$services->set(PropertyFetchToMethodCallRector::class)
        ->call('configure', [[
            PropertyFetchToMethodCallRector::PROPERTIES_TO_METHOD_CALLS => ValueObjectInliner::inline(
                [
                    new PropertyFetchToMethodCall(Generator::class, 'word', 'word'),           
                ]
            ),
        ]]);
```

**Comment by OskarStark** [comment]
Amazing, thank you guys 😃

**Comment by TomasVotruba** [comment]
@sabbelasichon Thank you :muscle:

**Comment by OskarStark** [comment]
Works like a charm! 👍
