### ISSUE TITLE
Incorrect behavior of RenameClassRector

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6441]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/abf577a0-a6ca-4f8b-b394-f50c34558faa

```php
<?php

use Foo\Bar;

final class DemoFile
{
    public function run()
    {
        $bar = new Bar();
    }
}
```

### Responsible rules

* `RenameClassRector`

## Expected Behavior

Rector should remove the old use statement

**Comment by TomasVotruba** [comment]
> If i am trying to create a failing test with current implementation in rector/rector-src it failed once and now after rerun the failure is gone.

Maybe removing cache dir might help? `/tmp/rector_...`

**Comment by sabbelasichon** [comment]
I had to look closely to the test case and make a diff with my eyes. I hardly failed. Had to put on my Rector-Glasses ;-)
The test was not wrapped in a class but the failing test case on https://getrector.org/demo is.

**Comment by sabbelasichon** [comment]
Failed: https://github.com/rectorphp/rector-src/pull/86/checks?check_run_id=2642617649

**Comment by sabbelasichon** [comment]
This is fixed by https://github.com/rectorphp/rector-src/pull/86
