### ISSUE TITLE
Comments between elseif and endif being duplicated

### ISSUE THREAD

**Issue by JoosuaKoskinen** [rectorphp/rector#6443]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.5 / main branch             |

Every time Rector is ran on file, it duplicates the amount of comments between `elseif` and `endif` and appends extra `<?php` on one of the new comments.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/d41f6738-3729-4fa1-aa73-5e1881092aa0

## Expected Behaviour

Comments shouldn't be duplicated and extra `<?php` shouldn't be added.

**Comment by sabbelasichon** [comment]
I have just tried it quickly with nikic/php-parser itself. By reading the code in and printing it back. It is already broken there as far as i can see. So from 

```php
```

**Comment by TomasVotruba** [comment]
@JoosuaKoskinen  Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
I created failing fixture to `nikic/PHP-Parser` repo https://github.com/nikic/PHP-Parser/pull/797

**Comment by samsonasik** [comment]
You can change with `{` `}` open close syntax instead of `:` with `endif` for now ref https://getrector.org/demo/1ebec22a-2aab-6b0a-a0a6-2b8b5e9f6874

**Comment by TomasVotruba** [comment]
Closing as related to external behavior in php-parser: https://github.com/rectorphp/rector/issues/6443#issuecomment-882975274
