### ISSUE TITLE
[PHP 8.0] Remove unused PHP_VERSION_ID conditions

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6448]
See https://github.com/symfony/symfony/pull/41295/files

Changes from this PR would be awesome to ingreated to PHP 8 upgrade set

**Comment by samsonasik** [comment]
Do you think it needs read the PHP version from `composer.json`, and fallback to `Option::PHP_VERSION_FEATURES`?

**Comment by TomasVotruba** [comment]
There is PhpVersoinProvider service already :heavy_check_mark:
