### ISSUE TITLE
Unable to install rector, dependency on phpstan is too narrow

### ISSUE THREAD

**Issue by janedbal** [rectorphp/rector#6450]
# Bug Report

Unable to install rector v0.11.5 when following instructions in readme when my project requires phpstan 0.12.88.

## Minimal PHP Code Causing Issue

```
composer require rector/rector --dev

...
  Problem 1
    - Root composer.json requires rector/rector ^0.11.5 -> satisfiable by rector/rector[0.11.5].
    - rector/rector 0.11.5 requires phpstan/phpstan 0.12.86 -> found phpstan/phpstan[0.12.86] but it conflicts with your root composer.json require (0.12.88).
...
```

## Expected Behaviour

Successful installation, use phpstan 0.12.88.

**Comment by sabbelasichon** [comment]
@TomasVotruba Yes, we should fix this also here: https://github.com/rectorphp/rector-src/blob/main/build/target-repository/composer.json#L10

Last time i have only done it here: https://github.com/rectorphp/rector-src/blob/main/composer.json#L23
