### ISSUE TITLE
Return type not removed from anonymous function on downgrade

### ISSUE THREAD

**Issue by JoosuaKoskinen** [rectorphp/rector#6451]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 / main branch             |

Return type declaration is not removed from anonymous functions on downgrade with `\Rector\DowngradePhp70\Rector\FunctionLike\DowngradeScalarTypeDeclarationRector`.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/5ac2d7b6-13b1-4f92-b1d9-d776ae9484bd

## Expected Behaviour

I assume it should remove the type declaration because `\Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector::class` adds them.

**Comment by samsonasik** [comment]
Could you create non-fatal error example? It seems invalid example, ref https://3v4l.org/S4h9I
