### ISSUE TITLE
CallableThisArrayToAnonymousFunctionRector forces return type declaration

### ISSUE THREAD

**Issue by JoosuaKoskinen** [rectorphp/rector#6453]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.5 / main branch             |

`\Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector` always forces return type declaration to anonymous function even thought it's not required for anonymous functions and breaks backwards compatibility.

Currently I have to run Rector once with `CallableThisArrayToAnonymousFunctionRector`, then remove it and and run again with `DowngradeScalarTypeDeclarationRector`. When they are in `rector.php` at the same time, `DowngradeScalarTypeDeclarationRector` has no effect.

Can I somehow make `CallableThisArrayToAnonymousFunctionRector` not add the type declaration or somehow remove them on same rector run?

## Minimal PHP Code Causing Issue

https://getrector.org/demo/bf1a7bd3-13c9-4f4a-812c-5a55d2e0a1d2

## Expected Behaviour

Expected `CallableThisArrayToAnonymousFunctionRector` to not generate version specific code as converting callable array to anonymous function doesn't require version specific code.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
It seems fixed now, see https://getrector.org/demo/bf5e5c8e-7cc8-4fce-bd2d-faf499f641fd
