### ISSUE TITLE
Option to rename file when RenameClassRector is used

### ISSUE THREAD

**Issue by janedbal** [rectorphp/rector#6454]
# Feature Request

When using PSR-4 autoloading, refactoring by RenameClassRector breaks my application. It would be very handy to provide some option to rename also the file with the class (if matches).

**Comment by TomasVotruba** [comment]
Hi, such feature would be great :+1:

**Comment by TomasVotruba** [comment]
Closing as not an issue and suggestion is accepted. To keep focus on relevant and opened issues.

Feel free to send PR :+1:
