### ISSUE TITLE
Old Doctrine Annotations to new PHP8 Doctrine Attributes

### ISSUE THREAD

**Issue by cniry** [rectorphp/rector#6456]
# Feature Request
Hi, thank you for your nice work with rector!

Is possible to create rules for migration from old Doctrine Annotations to PHP8 Doctrine 2.9+ Attributes?

https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/attributes-reference.html

**Comment by samsonasik** [comment]
its here https://github.com/rectorphp/rector-doctrine/pull/5 on progress

**Comment by samsonasik** [comment]
implemented at https://github.com/rectorphp/rector-doctrine/pull/5 , need new release of rector-doctrine for the usage.

**Comment by TomasVotruba** [comment]
Just released 0.11.3
