### ISSUE TITLE
Add info about Docker to readme

### ISSUE THREAD

**Issue by adaamz** [rectorphp/rector#6457]
# Question
Hi,
I'm curious that in readme there is no info about usage in existing Docker image. Also on Docker hub there is a lot of "useless" text about not running in Docker, Docker usage is mentioned at the end of page.

**Comment by TomasVotruba** [comment]
Hi,

since prefixed & downgraded version in [Rector 0.11](https://getrector.org/blog/prefixed-rector-by-default), the preffered usage is `composer require ...`.

The for Docker docs can be found in `/docs` directory by convention.

> Also on Docker hub there is a lot of "useless" text about not running in Docker, Docker usage is mentioned at the end of page.

That certainly is an issue. I'm not sure how Docker Hub works with README. How can we improve this?

**Comment by adaamz** [comment]
Docker docs are in `/docs` directory, I already `discover` that, but it would be nice to have at least link to this directory/document from readme 🙂 

From Docker hub page I would literally remove all stuff that is not related to Docker usage... I'm on Docker hub page because I'm interested in running the application in Docker, I m not interested in running any other way (composer deps or what are other ways to install/use), so it only messes with useful info 🙂 

btw some link/documentation of sets would be nice too, it took me some time to find how can I run set for mysql2mysqli, because Dockerized app died with error message that `--set parameter is unknown` 🤯

**Comment by TomasVotruba** [comment]
It's not in README on purpose to keep focus on main docs. There was way too many docs link and people kept asking about linked pages. Who needs Docker, usually knows where to look for it.

> From Docker hub page I would literally remove all stuff that is not related to Docker usage... 

:+1: 

Could you come up with such content in `/docs/...docker.md`? How can we push that file there?



---

Sets are described in README right under install: https://github.com/rectorphp/rector#running-rector
Where did you found `--set`? Should be removed from everywhere as it's deprecated for months.

**Comment by adaamz** [comment]
Yeah, but at least some note about Docker image existence would be nice. I also saw few readmes used as entrance to other docs.

Set parameter is mentioned at the end of page on Docker hub https://hub.docker.com/r/rector/rector

**Comment by rajyan** [comment]
@TomasVotruba @adaamz 
Does changing the readme path to 
https://github.com/rectorphp/rector/blob/main/docs/how_to_run_rector_in_docker.md
by this action
https://github.com/peter-evans/dockerhub-description#specifying-the-file-path

in https://github.com/rectorphp/rector/blob/main/.github/workflows/publish_docker_images.yaml
solve the problem?

**Comment by TomasVotruba** [comment]
If it updates the README on Dockerhub, then yes :+1:

**Comment by rajyan** [comment]
@TomasVotruba 
Ok, I'll test it and send a PR!

**Comment by rajyan** [comment]
@TomasVotruba 

I tested and it works perfectly!
https://github.com/rajyan/testworkflow/blob/main/.github/workflows/test_workflow.yaml
https://hub.docker.com/r/rajyan/test

Although, as noted in https://github.com/peter-evans/dockerhub-description#action-inputs,
there seems to be a issue in Docker Hub API that only password can be used (not personal access token).
Is this ok for rectorphp docker hub repository?

**Comment by TomasVotruba** [comment]
Thanks :+1: 
Let's give it a try and see. Could you send PR?
