### ISSUE TITLE
VersionCompareFuncCallToConstantRector throws ShouldNotHappenException

### ISSUE THREAD

**Issue by JoosuaKoskinen** [rectorphp/rector#6459]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 / main branch            |

`Rector\CodingStyle\Rector\FuncCall\VersionCompareFuncCallToConstantRector` throws `ShouldNotHappenException` ([VersionCompareFuncCallToConstantRector.php#L145](https://github.com/rectorphp/rector-src/blob/main/rules/CodingStyle/Rector/FuncCall/VersionCompareFuncCallToConstantRector.php#L145)) when the version is in short format (eg. `7.4`, not `7.4.0`) or is a variable.

## Minimal PHP Code Causing Issue

With short version string: https://getrector.org/demo/8b6404ca-1760-4fcf-b99e-d1f69e6a2ba9
With variable: https://getrector.org/demo/0abaf126-bcf0-4f43-8ba8-d578ad6eb7e2

## Expected Behaviour

Either skip the `version_compare` or assume `.0` at the end of version string.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
