### ISSUE TITLE
RemoveUnusedAssignVariableRector removes used code

### ISSUE THREAD

**Issue by JoosuaKoskinen** [rectorphp/rector#6460]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 / main branch           |

`Rector\DeadCode\Rector\Assign\RemoveUnusedAssignVariableRector` removes code that clearly can't be removed (see the example link).

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1947c3bf-8be3-4f7d-916b-c56381f91d70

## Expected Behaviour

Only unused code should be removed.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
