### ISSUE TITLE
Would love to see a new release

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6461]
Hi Tomas,
i would love to see an official new release with typo3-rector included.  Thank you so much.

**Comment by TomasVotruba** [comment]
I just tagged a new release https://github.com/rectorphp/rector-src/releases/tag/0.11.6 :partying_face: 

Then I found out typo3-rector has 2 broken tests: https://github.com/rectorphp/rector-src/runs/2701499065#step:5:23

Let me know if you can fix it and need re-release :)

**Comment by sabbelasichon** [comment]
Will have a look later

**Comment by sabbelasichon** [comment]
Thanks a bunch

**Comment by sabbelasichon** [comment]
Weird. The pipeline was green. Locally not. Fixed it. Would you mind to create another tag. Thanks a lot.

**Comment by TomasVotruba** [comment]
I've triggered the failed build, let's see: https://github.com/rectorphp/rector-src/runs/2701499065

**Comment by TomasVotruba** [comment]
Looks good: https://github.com/rectorphp/rector-src/runs/2701893385

**Comment by TomasVotruba** [comment]
Tagged 0.11.7

**Comment by TomasVotruba** [comment]
Btw, I'm having some troubles running rules possibly since 0.11.7. 

When Rector displays rules for empty `rector.php`, there are 3 typo3 rules that should be there:

![image](https://user-images.githubusercontent.com/924196/120086718-b1e9db80-c0e1-11eb-9b6f-0ead09b0411f.png)

This might cause side-effect we want to avoid. Could you remove them?

**Comment by sabbelasichon** [comment]
Yeah. Done it. Version 0.11.13 is without them.

**Comment by sabbelasichon** [comment]
It was never an issue for me before. Have to be careful now. Thanks for taking

**Comment by TomasVotruba** [comment]
Thanks!

It might be something else... still digging, clearing cache etc. :)

**Comment by TomasVotruba** [comment]
Ha, it was local conflict with stubs :+1:  Remove the `RectorInterface` and now it works. It was not related to typo3 at all, my bad.

**Comment by sabbelasichon** [comment]
Yeah, but the TYPO3 rules should not be included anyways. That was definitely related to my repo ;-)

**Comment by sabbelasichon** [comment]
You know what, TYPO3 people were also complaining about this magic / implicit rules. So now we have killed two birds with one stone
