### ISSUE TITLE
Rector\DeadCode\Rector\For_\RemoveDeadIfForeachForRector doesn't remove "if" with "else"

### ISSUE THREAD

**Issue by JoosuaKoskinen** [rectorphp/rector#6462]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 / main branch            |

DeadCode set removes dead code from `ìf`'s but that leaves alot of empty ifs like in the example below. If the if is empty but there's something in else, `Rector\DeadCode\Rector\For_\RemoveDeadIfForeachForRector` doesnt remove it.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/460a1428-3fad-4fa8-9818-6953ab1ffa38
https://getrector.org/demo/2a7f7ab7-983c-4f3e-a57e-8078ad034b3e (empty elses are neither removed)

## Expected Behaviour

Instead of leaving
```
if ( $condition ) {   
} else {
  echo "something";   
}
```

it could reverse the condition and remove the if:
```
if ( ! $condition ) {
  echo "something";
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
