### ISSUE TITLE
EditorConfigParserTest fails on windows

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6463]
# Bug Report

running `RectorsChangelogResolverTest` on windows fails with

```
D:\a\rector-src\rector-src\packages-tests\ChangesReporting\Annotation\AppliedRectorsChangelogResolver\RectorsChangelogResolverTest.php:36

3) Rector\Tests\FileFormatter\EditorConfig\EditorConfigParser\EditorConfigParserTest::testComposerJsonFile
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'tab'
+'space'
```

see https://github.com/rectorphp/rector-src/pull/99/checks?check_run_id=2677399492

**Comment by staabm** [comment]
I am not 100% sure where the problem source is, but I guess it is related to the underlying library, since rector does not implement that much logic on top of it.

created a upstream issue: https://github.com/idiosyncratic-code/editorconfig-php/issues/13

**Comment by staabm** [comment]
Maybe @sabbelasichon has an idea what is going on here?

**Comment by sabbelasichon** [comment]
@staabm Could you try to change this line locally https://github.com/idiosyncratic-code/editorconfig-php/blob/main/src/EditorConfig.php#L55 to 

```php
return implode(PHP_EOL, $config);
```

**Comment by staabm** [comment]
@sabbelasichon thanks for the suggestion. it doesn't seem to make a difference though.

if helpful: my observation is that [$configuration = $this->editorConfig->getConfigForPath($smartFileInfo->getRealPath());](https://github.com/rectorphp/rector-src/blob/e5ed4fb18439fe63142354dfc87d1907447cf366/packages/FileFormatter/EditorConfig/EditorConfigParser.php#L28) returns an empty array and therefore it does not return the value configured within the .editorconfig file

**Comment by staabm** [comment]
It turns out that the [fnmatch](https://github.com/idiosyncratic-code/editorconfig-php/blob/50f742daee8b7a632b795f5927d8d88c43dd3a4f/src/Section.php#L76) tries to match the pattern `**/*`
 against a path `C:\dvl\GitHub\rector-src-staabm\packages-tests\FileFormatter\EditorConfig\EditorConfigParser\Fixture\composer.json"`, which does not work because of different `DIRECTORY_SEPARATORS`

**Comment by staabm** [comment]
fix incoming: https://github.com/idiosyncratic-code/editorconfig-php/pull/14

**Comment by sabbelasichon** [comment]
Well done

**Comment by TomasVotruba** [comment]
Closing as fixed in https://github.com/idiosyncratic-code/editorconfig-php/pull/14
