### ISSUE TITLE
Cannot upgrade to rector ^0.11

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#6466]
# Bug Report
`
Cannot autowire service "Rector\Symfony\Composer\ComposerNamespaceMatcher": argument "$smartFileSystem" of method "__construct()" has type "Symplify\SmartFileSystem\SmartFileSystem" but this class was not found.
`

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5             |

I want to upgrade from `0.10.`to `0.11`

## Minimal PHP Code Causing Issue

The error happens when executing `vendor/bin/rector --version`

## Expected Behaviour

No error

### My composer infos

```
rector/rector                          0.11.3    Prefixed and PHP 7.1 downgraded version of rector/rector
rector/rector-phpunit                  0.11.1    Rector upgrades rules for PHPUnit
rector/rector-symfony                  0.11.2    Rector upgrades rules for Symfony Framework
```

Anything else I can do?

**Comment by TomasVotruba** [comment]
The rector-* should be removed, as they are part of rector/rector. See `composer.json`

**Comment by OskarStark** [comment]
Thanks will try tomorrow 👍🏻

**Comment by sabbelasichon** [comment]
@OskarStark Did it work for you?

**Comment by OskarStark** [comment]
Yes thanks
