### ISSUE TITLE
Special cases with ParamTypeDeclarationRector on Symfony

### ISSUE THREAD

**Issue by nicolas-grekas** [rectorphp/rector#6467]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

I'm trying to use the `ParamTypeDeclarationRector` on Symfony, branch `6.0`.

I'm noting a few things that should be improved:

This generated patch should replace the `self` return type by `static:
```diff
     /**
      * Creates a cookie copy with SameSite attribute.
-     *
-     * @return static
      */
     public function withSameSite(?string $sameSite): self
     {
```

This generated patch breaks the code:
```diff
      */
-    protected function dispatchMessage($message, array $stamps = []): Envelope
+    protected function dispatchMessage(object|\Symfony\Component\Messenger\Envelope $message, array $stamps = []): Envelope
     {
```

This one should dedup:
```diff
      */
-    public function depth($levels)
+    public function depth(string|int|array|array $levels)
     {
```

The tool looks nice btw :)

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need a failing test case in a pull-request tighted to specific Rector rule that is causing the error, so we have it covered in Rector.
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by nicolas-grekas** [comment]
I'm sorry I won't be able to do so in the near future, too busy [patching Symfony 6.0](https://github.com/symfony/symfony/pull/41424) :)

**Comment by TomasVotruba** [comment]
No worries 👍 if you find time, feel free to reopen with PR.
