### ISSUE TITLE
Allow skipping classes from global namespace in StringClassNameToClassConstantRector

### ISSUE THREAD

**Issue by JoyceBabu** [rectorphp/rector#6469]
# Feature Request

When running `StringClassNameToClassConstantRector`, the constant `SendGrid` was replaced with `SendGrid::class`. It also happened with a few legacy classes in the project I am currently working on.

I understand that it is possible to add them to the `StringClassNameToClassConstantRector::CLASSES_TO_SKIP` option. But since this issue is most likely to happen for global namespace classes, would it be possible to add a new option to ignore the rector for all global namespace classes?

**Comment by TomasVotruba** [comment]
Hi, it is possible. It would require to make rule configurable.

**Comment by TomasVotruba** [comment]
Closing as not an issue and suggestion is accepted. To keep focus on relevant and opened issues.

Feel free to send PR :+1:
