### ISSUE TITLE
Rector not running rules in the configuration order

### ISSUE THREAD

**Issue by rajyan** [rectorphp/rector#6472]
# Bug Report (maybe a feature request)

We are writing custom rector rules for framework migration. First of all, thank you very much to rector for automating about 90% of the code modifications!

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  v0.10.20           |

From this document https://github.com/rectorphp/rector/blob/main/docs/how_it_works.md#221-order-of-rectors
I expected rector running in the order of ARector -> BRector, but it's running in BRector -> ARector.

I finally found this https://github.com/rectorphp/rector/issues/5962#issuecomment-804959594 and understood the behavior, but still believing this is a bug.

## Minimal PHP Code Causing Issue

ARector.php
```php
<?php

namespace ASTDemo\Rector;

use PhpParser\Node;
use PhpParser\Node\Name;
use Rector\Core\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

class ARector extends AbstractRector
{
    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('rename method call to renamed', [
            new CodeSample(
                '->foo()',
                '->renamed()'
            )
        ]);
    }

    /**
     * @return string[]
     */
    public function getNodeTypes(): array
    {
        return [Node\Expr\MethodCall::class];
    }

    /**
     * @param Node\Expr\MethodCall $node
     * @return Node|null
     */
    public function refactor(Node $node): ?Node
    {
        // rename
        $node->name = new Name('renamed');

        return $node;
    }
}
```

Brector.php
```php
<?php

namespace ASTDemo\Rector;

use PhpParser\Node;
use Rector\Core\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

class BRector extends AbstractRector
{
    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('change assign var to MethodCall', [
            new CodeSample(
                '$foo = ',
                '$foo = $bar->baz()'
            )
        ]);
    }

    /**
     * @return string[]
     */
    public function getNodeTypes(): array
    {
        return [Node\Expr\Assign::class];
    }

    /**
     * @param Node\Expr\Assign $node
     * @return Node|null
     */
    public function refactor(Node $node): ?Node
    {
        // create MethodCall
        $node->expr = new Node\Expr\MethodCall(
            new Node\Expr\Variable('bar'),
            new Node\Name('baz')
        );

        return $node;
    }
}
```

rector.php
```php
<?php

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(\ASTDemo\Rector\ARector::class);
    $services->set(\ASTDemo\Rector\BRector::class);
};
```

test.php
```php
<?php

$foo = bar();
```

rector output
```diff

1 file with changes
===================

1) src/Demo/test.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php

-$foo = bar();
+$foo = $bar->renamed();
    ----------- end diff -----------

Applied rules:
 * ARector
 * BRector
```

## Expected Behaviour

Running in the order of ARector->Brector, ARector changing nothing.
or
Adding a notation about the node traversing order in  https://github.com/rectorphp/rector/blob/main/docs/how_it_works.md#221-order-of-rectors.

**Comment by TomasVotruba** [comment]
Hi, glad you find Rector useful for your project :)

This is a basically how any node traversing works, based on php-parser. Traversing happens from the top-most node. E.g. if you remove a whole `Class_` node, then rename method inside them, the latter won't happen.

Your case is correct. When you first replace assign with assign to method call, then traverse further, the method call rule is invoked.

> Adding a notation about the node traversing order in https://github.com/rectorphp/rector/blob/main/docs/how_it_works.md#221-order-of-rectors.

Good idea :+1: Could send PR to add this?


P.S. Be sure to upgrade to Rector 0.11. The linked version is quite old and contains bugs that were already fixed.

**Comment by rajyan** [comment]
Thank you very much for your detailed explanation.

> In your case the problem is making rule not idempotent. That's a bad practise for any automated rules, not just Rector. Shameless plug: we write about this in depth in Rector book.

Sorry, this was just a minimal code example to explain the issue. Although I think each rules are idempotent, as you are saying, a rule set of BRector->ARector is not idempotent.

> Good idea 👍 Could send PR to add this?

Of course! 👍 

> P.S. Be sure to upgrade to Rector 0.11. The linked version is quite old and contains bugs that were already fixed.

Thanks for your attention!

**Comment by TomasVotruba** [comment]
Glad to help :+1: 

I would love to see how you use Rector for migrating custom framework. That's a great use case :)

**Comment by rajyan** [comment]
We are migrating from FuelPHP to Laravel. I wrote about 50 rector rules to migrate. (It only took one month or so!)

for example a rector rule to 
```
\DB::update('table name')->set($array)->where($whereParams)->execute('DB name');
```
to
```
\DB::connection('DB name')->table('table name')->where($whereParams)->update($array);
```

The great thing is that we can run the migration and other projects in parallel.

**Comment by rajyan** [comment]
I thinking of writing a blog after finishing this project :) (In Japanese at first, in English if possible...)

**Comment by TomasVotruba** [comment]
> I wrote about 50 rector rules to migrate. (It only took one month or so!)

Wow, that's awesome work! I think PHP devs would benefit from it. We alredy have similar set for Nette → Symfony (and more is comming, as there is lot of these legacy projects):
https://github.com/rectorphp/rector-nette-to-symfony

Would you be open to open-source these on your own or under Rector umbrella? I would help to tidy it up :)

**Comment by TomasVotruba** [comment]
> I am thinking of writing a blog after finishing this project :) (In Japanese at first, in English if possible...)

Amazing! We can publish it on Rector blog too https://getrector.org/blog

**Comment by rajyan** [comment]
> Would you be open to open-source these on your own or under Rector umbrella? I would help to tidy it up :)

I'll ask to the legal department about that!

> Amazing! 😃 We can publish it on Rector blog too

Thanks! I'll contact you after writing a blog.
