### ISSUE TITLE
Build scoped error on named arguments downgrade

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6473]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

On latest build, it got error :
 
 ```bash
 Parse error: rector-prefixed-downgraded/vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php:23
102
    21|     public function __construct(string $name = null, array $attributes = [])
103
    22|     {
104
  > 23|         parent::__construct(tags: [[$name ?? 0 => $attributes]]);
105
    24|     }
106
    25| }
 ```
 
 at https://github.com/rectorphp/rector-src/runs/2710700928#step:11:101 on parallel-lint process. I tried direct downgrade and it seems not affected:
 
 ```bash
 bin/rector process vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php --dry-run -c config/set/downgrade-php80.php --dry-run
 
 [OK] Rector is done!                                                                                                   
 ```
 
 @TomasVotruba is there any specific rule that already handle it?

**Comment by TomasVotruba** [comment]
We don't have such rule yet: https://github.com/rectorphp/rector/blob/main/config/set/downgrade-php80.php
