### ISSUE TITLE
Incorrect behavior of TypedPropertyRector - redundant initialize value for property

### ISSUE THREAD

**Issue by andrew-demb** [rectorphp/rector#6474]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.11.7      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/58d0f940-462e-4f56-b4d4-45b7966c4ce9

```php
<?php

final class DemoFile
{
    private $result;
    
    public function __construct(?array $result) {
        $this->result = $result;
    }
    
    public function getResult(): ?array
    {
        return $this->result;
    }
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

Added type hint to property without a default value as it is always filled in contructor.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
