### ISSUE TITLE
Incorrect behavior of DoctrineAnnotationClassToAttributeRector

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6475]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/67af2e1b-1158-4f26-a8d0-ef12fc93b4ca

```php
<?php

declare(strict_types=1);

namespace App\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 * @Target({"PROPERTY"})
 */
final class RectorConfiguration extends Constraint
{
    public string $message = 'This {{ configuration }} is not a valid configuration';
}
```

### Responsible rules

* `DoctrineAnnotationClassToAttributeRector`

## Expected Behavior

The @Target({"PROPERTY"}) is not converted to  (Attribute::TARGET_PROPERTY)

**Comment by TomasVotruba** [comment]
I've just added a test and then I found out... the FQN class name is missing for Target.
Then it works, see https://getrector.org/demo/00cd27f1-9548-4fb7-a32a-add09ed46147
