### ISSUE TITLE
Make RenamePropertyToMatchTypeRector skip collection from Doctrine assign

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6476]
`$rectorRuns` is converted to `Collection`, that should be skipped

![image](https://user-images.githubusercontent.com/924196/120392633-0df66f00-c331-11eb-9bc7-3c271556e5ed.png)

**Comment by samsonasik** [comment]
It seems already implemented at https://github.com/rectorphp/rector-src/blob/main/rules-tests/Naming/Rector/Class_/RenamePropertyToMatchTypeRector/FixturePhp74/skip_doctrine_collection.php.inc ?

**Comment by TomasVotruba** [comment]
I used a never Rector version than the one you linked from March. It was still broken.
But the fixture I provided is not very helpful. I'll fix it right away next time :)
