### ISSUE TITLE
Alternate file extensions

### ISSUE THREAD

**Issue by ahardylaniertech** [rectorphp/rector#6478]
I am working to convert an old application that utilized alternate extensions (not file.php).  I'm working to edit rector to edit those files to convert from phpexcel to phpspreadsheet.  

In vendor/bin/rector I changed line 14 to the extension I needed. Are there other files that would need to be altered?

**Comment by sabbelasichon** [comment]
There should be an option for it.

```php
$parameters->set(Option::FILE_EXTENSIONS, ['inc', 'php']);
```

**Comment by sabbelasichon** [comment]
@ahardylaniertech I don´t think you need other files to change regarding the suffix.
