### ISSUE TITLE
Parser error after using `EncapsedStringsToSprintfRector` with `RemoveDeadInstanceOfRector`

### ISSUE THREAD

**Issue by Androbin** [rectorphp/rector#6481]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master (v0.11.7) |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/d9fc01ee-0d96-4fcd-8a4f-bdd8da3a3a56

```php
<?php
class Foo {
    public function bar(): void {
        $lorem = new \DateTime();
        $ipsum = "";

        if ($lorem instanceof \DateTime) {
            echo "$ipsum";
        }
    }
}
```

### Responsible rules

* `EncapsedStringsToSprintfRector`
* `RemoveDeadInstanceOfRector`

## Expected Behaviour

```php
<?php
class Foo {
    public function bar(): void {
        $lorem = new \DateTime();
        $ipsum = "";

        echo sprintf('%s', $ipsum);
    }
}
```

```


 [OK] Rector is done!


```

## Actual Behaviour

`Foo.php` is left unchanged

```
PHP Notice: Undefined offset: -1 in ./vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205


 [OK] Rector is done!


```

**Comment by sabbelasichon** [comment]
Thanks. But, could you provide more context. I am running it without a change and without a notice.
We need minimal configuration and code to investigate.

**Comment by Androbin** [comment]
Here is a minimal reproducing example file:
```php
<?php
class Foo {
    public function foo(): void {
        $time = new \DateTime();

        if ($time instanceof \DateTime) {
            $foo->bar("$key");
        }
    }
}
```

**Comment by Androbin** [comment]
https://github.com/nikic/PHP-Parser/issues/780

**Comment by Androbin** [comment]
Might also be related to #6480

**Comment by Androbin** [comment]
@sabbelasichon I added minimal configuration and code

**Comment by Androbin** [comment]
@sabbelasichon @TomasVotruba PTAL
