### ISSUE TITLE
Migration PHPExcel > PHPSpreadsheet not working to me

### ISSUE THREAD

**Issue by yoelcode** [rectorphp/rector#6482]
# Question

Hello,

I am trying to use the rector migration from PHPExcel to PHPSpreadsheet but it is not working.

The problem is that is not detecting any changes to do, when obviously i am using code that should be refactored.

It is saying "[OK] Rector is done!", but without changes.

![Code_XSDMML8QkS](https://user-images.githubusercontent.com/27638953/120618017-f1565600-c45a-11eb-8b48-d2881dc29abf.png)

I followed the guide from getrector.org, that talks about do this migration in 30 minutes.

But i did a change in the rector.php, because the code took from getrector.org complains with that -> The "sets" parameter is deprecated. Use $containerConfigurator->import(<set>); instead in ...

Actually my rector.php is this one:

`<?php

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(SetList::PHPEXCEL_TO_PHPSPREADSHEET);
};`

If you could take a look i will be very gratefull, because i do not know if i am doing something bad or it is not working correctly.

I used rector with another rector.php rules and worked to me, but in this case of PHPExcel to PHPSpreadsheet is not working :(

Thanks in advance.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by yoelcode** [comment]
Hi Tomas, 

I was trying to understand how to add a test but i found it a bit confusing, i can not find the folder FinalizeClassesWithoutChildrenRector. 

Anyway, for example if i want to refactor this code is not working: 

`
<?php
	function exportPHPExcel($sheetname,$format) {
		global $FILETYPEPATH;
		$filename=$FILETYPEPATH["tempdata"].$this->idTable."_".time();
		switch ($format) {
			case "Excel2007": $filename.=".xlsx";break;
			case "Excel5": $filename.=".xls";break;
			case "OOCalc": $filename.=".ods";break;
		}
		// settings
		$cachemethod=PHPExcel_CachedObjectStorageFactory::cache_in_memory_gzip;
		PHPExcel_Settings::setCacheStorageMethod($cachemethod);
		// create excel object
		$objPHPExcel=new PHPExcel();
		// first page
		$objPHPExcel->setActiveSheetIndex(0);
		// page title
		$sheet=$objPHPExcel->getActiveSheet();
		$sheet->setTitle(utf8_encode($sheetname));

		$this->exportPHPExcelSheet($sheet,0,1);
		// file creation
		$objWriter=PHPExcel_IOFactory::createWriter($objPHPExcel,$format);
		$objWriter->save($filename);
		downloadFile($filename,true);
	}

?>

`

But for example this simple snippet is working: 

`
<?php
	function exportPHPExcel($sheetname,$format) {
		$objPHPExcel=new PHPExcel();
		// first page
		$objPHPExcel->setActiveSheetIndex(0);
	}

?>
`

Rector is refactoring to this: 

![image](https://user-images.githubusercontent.com/27638953/120675016-fa641900-c494-11eb-9c35-e9d9247f2197.png)

I saw too that the refactoring of this snippet is wrong:

`
<?php
	function exportPHPExcel($sheetname,$format) {
		// settings
		$cachemethod=PHPExcel_CachedObjectStorageFactory::cache_in_memory_gzip;
		PHPExcel_Settings::setCacheStorageMethod($cachemethod);
	}

?>
`
![image](https://user-images.githubusercontent.com/27638953/120675397-5038c100-c495-11eb-80d0-1849788cd56e.png)

For CellsFactory the constant cache_in_memory_gzip does not exist:

![image](https://user-images.githubusercontent.com/27638953/120675741-a4dc3c00-c495-11eb-9429-5e92a5662501.png)

Obviously when i am trying to pass a path to migrate rector is saying again, Rector is done! But without changes to do, is just working in codes with few lines.

I hope you can fix this problems that stop me to do this migration with Rector.

**Comment by sabbelasichon** [comment]
@yoelcode Hi thanks for the detailed report. If Rector is saying done, it could also mean: An error has occured. Run the process command with -vvv and you will get a detailed output and with possible errors. In your case i have found the culprit for the first problem.

Will try to come up with a solution to solve also the problem with the wrong transformed constant.

**Comment by sabbelasichon** [comment]
@yoelcode The problem with the constant is not solvable, because the whole caching is totally different. Have a look at: 
https://github.com/PHPOffice/PhpSpreadsheet/blob/50d78ce7898ee3a540cefd9693085b3636e578e6/docs/topics/migration-from-PHPExcel.md 
You have to come up with a PSR-16 cache implementation.
See also: https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Settings.php#L155
