### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector

### ISSUE THREAD

**Issue by romainallanot** [rectorphp/rector#6484]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.11.8      |
| Installed as   | composer dependency  |

Quotes in arrays are not removed. 

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/df58f840-a218-4f37-bd1a-f48771bed3bc

```php
<?php

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * Book.
 *
 * @ApiResource(collectionOperations={}, itemOperations={
 *     "get",
 *     "get_by_isbn"={"method"="GET", "path"="/books/by_isbn/{isbn}.{_format}", "requirements"={"isbn"=".+"}, "identifiers"="isbn"}
 * })
 * @ORM\Entity
 */
class Book
{}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

Remove quotes in arrays as below
```php
#[ApiResource(collectionOperations: [], itemOperations: ['get', 'get_by_isbn' => ['method' => 'GET', 'path' => '/books/by_isbn/{isbn}.{_format}', 'requirements' => ['isbn' => '.+'], 'identifiers' => 'isbn']])]
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by romainallanot** [comment]
@TomasVotruba I have a fix if you want, I can send it tomorrow.

**Comment by samsonasik** [comment]
@romainallanot Thank you for the fix
