### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6485]
In order to get rid of the globally defined rules from typo3-rector create a new release. These rules are not defined globally anymore.

**Comment by TomasVotruba** [comment]
Sure :slightly_smiling_face:  There you go https://github.com/rectorphp/rector-src/releases/tag/0.11.9

@samsonasik The doctrine set is now included :+1:

**Comment by samsonasik** [comment]
@TomasVotruba thank you 👍
