### ISSUE TITLE
Weird RouteName.php file been created from nowhere

### ISSUE THREAD

**Issue by bitgandtter** [rectorphp/rector#6487]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |   2344fdb6e4898084622d62ba2a88e77d32d4fed2           |

After execute rector i end up with a new file at src/Controller/src/ValueObject/Routing/RouteName.php with the following content

```
<?php

namespace App\ValueObject\Routing;

final class RouteName
{
}
```

## Expected Behaviour

This file should not be created

**Comment by sabbelasichon** [comment]
@bitgandtter Thanks for reporting, it seems that you are using the SYMFONY_CODE_QUALITY set. Behind the scenes the rule ExtractAttributeRouteNameConstantsRector is defined within this set. This rule deliberately creates this file. What you could do is skipping this rule, if you don´t like it.
Have a look at: https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md

**Comment by TomasVotruba** [comment]
Agree with @sabbelasichon :+1: 

I've added check for at least some itmes, to avoid empty `RouteName` class
https://github.com/rectorphp/rector-symfony/commit/9cb6595e25899dc01a4641816ffadc4c8e9a14f1
