### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#6489]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/84e2d162-bd1a-4fdc-98b0-17c4ffa00496

```php
<?php

final class DemoFile
{
    /**
    * @ApiPlatform\Core\Annotation\ApiFilter(SearchFilter::class)
	*/
    public string $foo;
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

The argument(s) should not be removed.

**Comment by samsonasik** [comment]
It seems already fixed. Please try latest 0.11.20.

**Comment by stephanvierkant** [comment]
Thanks! Can't test it in my project because of #6495, but thanks for fixing this one! :)
