### ISSUE TITLE
Feature Request: Simplify `isset(...)` / `!empty(...)` chains

### ISSUE THREAD

**Issue by Androbin** [rectorphp/rector#6493]
# Feature Request
 
I encountered lots of code like after getting assigned to another project.
The backend code is extremely cautious about the JSON data passed to the API.

## Diff

```diff
-if (isset($foo) && isset($foo->bar))
+if (isset($foo->bar))
```

```diff
-if (isset($foo) && isset($foo["bar"]))
+if (isset($foo["bar"]))
```

```diff
-if (isset($foo->bar) && !empty($foo->bar))
+if (!empty($foo->bar))
```

```diff
-if (isset($foo["bar"]) && !empty($foo["bar"]))
+if (!empty($foo["bar"]))
```

```diff
-if (isset($foo) && isset($foo->bar) && !empty($foo->bar))
+if (!empty($foo->bar))
```

```diff
-if (isset($foo) && isset($foo["bar"]) && !empty($foo["bar"]))
+if (!empty($foo["bar"]))
```

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion.
We won't have time to work on this, but you can create such rule yourself and contribute to "code quality" set.

Here is how: https://github.com/rectorphp/rector/blob/main/docs/create_own_rule.md
