### ISSUE TITLE
Incorrect behavior of `RemoveUnusedVariableAssignRector`

### ISSUE THREAD

**Issue by Androbin** [rectorphp/rector#6494]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master (v0.11.14) |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/68325483-921e-4f1e-b290-1b1f252e98f1

```php
<?php
class Foo {
    public function bar(string $text, bool $flag): string {
        $text = str_replace('a', 'b', $text);
        $text = str_replace('c', 'd', $text);
        if ($flag) {
            $text = str_replace('d', 'e', $text);
        }
        else {
            $text = str_replace('d', 'f', $text);
        }

        return $text;
    }
}
```

### Responsible rules

* `RemoveUnusedVariableAssignRector`

## Expected Behavior

Rector should skip it

## Actual Behavior

```diff
 class Foo {
     public function bar(string $text, bool $flag): string {
         $text = str_replace('a', 'b', $text);
-        $text = str_replace('c', 'd', $text);
         if ($flag) {
             $text = str_replace('d', 'e', $text);
         }
         else {
             $text = str_replace('d', 'f', $text);
         }

         return $text;
     }
 }
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting! Looks valid.

Could you send PR with the blue button under your code on demo page?

**Comment by Androbin** [comment]
See https://github.com/rectorphp/rector-src/pull/173

**Comment by Androbin** [comment]
@TomasVotruba See https://github.com/rectorphp/rector-src/pull/173
