### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#6495]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f71d0b74-74b9-4fcc-89b0-65a206173867

```php
<?php

use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Table;
use App\Repository\FooRepository;
use App\EntityListener\FooListener;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @UniqueEntity(
 *     fields={"parent", "code"},
 *     errorPath="code",
 *     message="Already exists!",
 *     ignoreNull=false,
 *     groups={"default", "update"}
 * )
 */
#[Table('Foo')]
#[Entity]
class Foo
{}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

It removes `@UniqueEntity` and adds a `\Doctrine\ORM\Mapping\Entity` entry, while it shouldn't.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

Tip: there is a button on demo page that should make this super easy :)

**Comment by samsonasik** [comment]
It seems already fixed, ref https://github.com/rectorphp/rector-src/pull/225
