### ISSUE TITLE
ReplaceSensioRouteAnnotationWithSymfonyRector and IMPORT_DOC_BLOCKS

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#6496]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/79c3193f-0201-4f5c-b4e2-d6f3496c2356

```php
<?php

use Sensio\Bundle\FrameworkExtraBundle\Configuration as FEB;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @FEB\Route("/someUrl")
 */
class SomeController extends Controller
{
}
```

### Responsible rules

* `ReplaceSensioRouteAnnotationWithSymfonyRector`

## Expected Behavior

Based on my understanding of the config, Rector should be replacing the full Symfony Route name in the annotation with a use statement and a short name.

**Comment by TomasVotruba** [comment]
Thanks for reporting Timmy, I'm looking into this

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector-src/pull/264
