### ISSUE TITLE
PreslashSimpleFunctionRector is too preslashy

### ISSUE THREAD

**Issue by JoosuaKoskinen** [rectorphp/rector#6497]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.8 (invoke `vendor/bin/rector --version`)             |

PreslashSimpleFunctionRector is too preslashy, it preslashes functions that are not part of global namespace.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/5e635aa1-8ea5-4f86-b484-b84eac55d1b4 (Rectored code results in fatal error)

## Expected Behaviour

Expected to not have all functions preslashed.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
