### ISSUE TITLE
[DeadCode] RemoveUnusedPrivateMethodRector removes methods in case casing mismatches

### ISSUE THREAD

**Issue by petski** [rectorphp/rector#6499]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `a54d7eece452cc28345046b613643495ae5469c7`             |

RemoveUnusedPrivateMethodRector removes methods in case casing mismatches

PHP is case-insensitive for function names. See https://www.php.net/manual/en/functions.user-defined.php ; grep "case-insensitive"

## Minimal PHP Code Causing Issue

https://getrector.org/demo/51f02143-9720-4fc2-b75a-d2deb9b7f6a8

To copy:

``` php
<?php

class Customer
{
    private $id;

    public static function create($id)
    {
        $customer = new self();
        // Note the casing: Id
        $customer->setId($id);

        return $customer;
    }

    // Note the casing: ID vs Id
    private function setID($id)
    {
        $this->id = $id;
    }
}
```

## Expected Behaviour

A. Don't remove the method _OR_
B. Introduce a new rector "rule" that finds the casing-mismatches and fixes those.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!


Hi, thanks for reporting. The A is definitely a corret approach.
Could you send failing test case to cover this?

Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by petski** [comment]
Thanks Tomas, I added a test case at https://github.com/petski/rector-src/commit/d5f8ca23421cf3699aae0d7b905fbc6bf31406fd. Hope this is sufficient, if not, please let me know.

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Could you create a PR to this repository from that?

**Comment by petski** [comment]
I've created https://github.com/rectorphp/rector-src/pull/194
