### ISSUE TITLE
Incorrect behavior of MoveOutMethodCallInsideIfConditionRector

### ISSUE THREAD

**Issue by freiondrej-economia** [rectorphp/rector#6502]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.11.16      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/abf4e493-b4d4-4fc7-9bb7-9d1c714dc9ff

```php
<?php

use function Symfony\Component\String\s;

final class DemoFile
{
    public function run()
    {
        if (s($newRelativeNamespace)->endsWith('\\')) {
   			return true;
        }

        return false;
    }
}
```

### Responsible rules

* `MoveOutMethodCallInsideIfConditionRector`

## Expected Behavior

The resulting variable name contains "\\" and thus is not a valid PHP identifier.

**Comment by samsonasik** [comment]
@freiondrej-economia could you provide a patch for it? Here is the steps:

1. fork the repo 
2. create new fixture to https://github.com/rectorphp/rector-src/tree/75056429bee6b35f2080a9e637f61de8f27bc07c/rules-tests/CodeQualityStrict/Rector/If_/MoveOutMethodCallInsideIfConditionRector/Fixture

3. patch the rule code, it possibly at this part:

https://github.com/rectorphp/rector-src/blob/75056429bee6b35f2080a9e637f61de8f27bc07c/rules/CodeQualityStrict/Rector/If_/MoveOutMethodCallInsideIfConditionRector.php#L115-L118

that pointed to:

https://github.com/rectorphp/rector-src/blob/75056429bee6b35f2080a9e637f61de8f27bc07c/rules/CodeQuality/Naming/MethodCallToVariableNameResolver.php#L52-L69

4. run test : 

```bash
vendor/bin/phpunit rules-tests/CodeQualityStrict/Rector/If_/MoveOutMethodCallInsideIfConditionRector
```

with ensure all green.

5. create PR to https://github.com/rectorphp/rector-src

The doc for contributing can be read at https://github.com/rectorphp/rector/blob/main/CONTRIBUTING.md
