### ISSUE TITLE
Incorrect behavior of ChangeAndIfToEarlyReturnRector

### ISSUE THREAD

**Issue by kreexzoi** [rectorphp/rector#6503]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/24100aa2-a91b-4f1f-b277-a18c2b9399ee

```php
<?php

Text::make(___('Type'), function () {
                if ($this->_fieldType_ === 'wire' && $this->users->getRole() === 'correct-role') {
                    return ___('Fond');
                }

                return Arr::get(Purses::getOptions(), $this->_fieldType_) ?? $this->_fieldType_;
            });
```

### Responsible rules

* `ChangeAndIfToEarlyReturnRector`

## Expected Behavior

```php
Text::make(___('Type'), function () {
    if ($this->_fieldType_ !== 'wire') {
        return ___('Fond');
    }
    if ($this->users->getRole() !== 'correct-role') {
        return ___('Fond');
    }
    return Arr::get(Purses::getOptions(), $this->_fieldType_) ?? $this->_fieldType_;;
});
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
