### ISSUE TITLE
Incorrect behavior of OptionalParametersAfterRequiredRector with variadic params

### ISSUE THREAD

**Issue by lptn** [rectorphp/rector#6506]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/6728fde1-4c0c-4f7d-bb89-ac1e2d806c92

```php
<?php

final class Cart
{
    public static function create(string $name = 'default', Product ...$product)
    {
        return 5;

        // we never get here
        return 10;
    }
}

$cart = Cart::create('trial', new Product('A'), new Product('B'));
```

### Responsible rules

* `OptionalParametersAfterRequiredRector`

## Expected Behavior

variadic param is optional in PHP (at least in PHP 8), so OptionalParametersAfterRequiredRector should treat  it just as another optional param and thus do not propose any changes

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link! It seems the "expected behavior" is missing

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by lptn** [comment]
>Thank you for your report and demo link! It seems the "expected behavior" is missing



sorry, i've just updated initial message.


>Could you send a failing test case in a pull-request, so we have it covered in Rector?

sure, I'll do it tomorrow! (PS: nice strategy to invoice more people to contribute to the project :) )

**Comment by TomasVotruba** [comment]
Thanks :+1: 

<br>

There is also one more hack for lazy people like me :) 

![image](https://user-images.githubusercontent.com/924196/122130743-613fe580-ce38-11eb-82b3-0e00653206bf.png)
