### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector

### ISSUE THREAD

**Issue by rodion-k** [rectorphp/rector#6509]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/c401ecf0-909b-4fa1-a659-64b73198f0dd

```php
<?php

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Company\CompanyRepository")
 */
class Company
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="NONE")
     * @ORM\Column(type="guid")
     */
    private string $uuid;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $enabled;

    public function __construct()
    {
        $this->uuid = Uuid::uuid4()->toString();
        $this->enabled = true;
    }
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

    New lines between properties and methods don't remove

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. This is expected behavior.
Use coding standards to fix it
https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by rodion-k** [comment]
> https://github.com/rectorphp/rector#how-to-apply-coding-standards
Looks like the link to the ECS setup in the referenced paragraph is broken.

Thanks for the help.

**Comment by TomasVotruba** [comment]
Indeed, thanks for pointing it out :+1: 

Fixed: https://github.com/rectorphp/rector-src/commit/5e6a01145feda29e844606d161ff278c2297fa8f
