### ISSUE TITLE
FYI, rector file path lengths are starting to climb up to Windows path 260 character limit

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#6510]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.20              |

Example: 209 characters already gave me a problem: vendor\composer\6aacca99\rectorphp-rector-03e6aa4\rules\code-quality\tests\Rector\If_\MoveOutMethodCallInsideIfConditionRector\Fixture\if_condition_method_call_with_arg_class_constant_with_class_suffix.php.inc: The system cannot find the specified path. (os error 3)

When this happens, rector also doesn't start with `[ERROR] Undefined class constant 'DEAD_CLASSES'`.

Some of this is that I have the source code under a folder in my Windows user directory.

And of course I can [set LongPathsEnabled](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later). But that leaves some parts of Windows (e.g. Explorer, the file manager) incompatible. Unsure if PHP will just work.

Maybe I should open an issue at Composer as well, since they can in principle see the path length issue and give some advice.

## Minimal PHP Code Causing Issue

Not a PHP code problem.

## Expected Behaviour

Not sure what you need to do, except tell me to create a super short base path for the project, or set LongPathsEnabled.

But be aware that this is an issue in 2021.

----

Edit: LongPathsEnabled doesn't make 7z, nor PHP's (7.2 \*sigh\*) built-in ZipArchive, long path aware. Even though PHP 7.1+ should be long path aware.

----

Edit2: Moving the base directory to C:\H\\<project_name>\ did help. So it is in fact the path length issue (Windows doesn't explicitly say so).

**Comment by TomasVotruba** [comment]
Hi, thanks for the note. The `if_condition_method_call_with_arg_class_constant_with_class_suffix` has way too detailed naming indeed :)

Could you shorten the files that are way too long in PR so Rector works without any file length troubles?

**Comment by TomasVotruba** [comment]
Closing as not an issue and suggestion is accepted. To keep focus on relevant and opened issues.

Feel free to send PR +1
