### ISSUE TITLE
Incorrect behavior of TypedPropertyRector

### ISSUE THREAD

**Issue by rodion-k** [rectorphp/rector#6511]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/036638e4-36d5-4f32-abdd-f8997a5e0009

```php
<?php

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Company\CompanyRepository")
 */
class Company
{
    /**
     * @var string
     *
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="NONE")
     * @ORM\Column(type="guid")
     */
    private $uuid;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function __construct()
    {
        $this->uuid = Uuid::uuid4()->toString();
    }
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

Rector should set string type for property uuid also.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector-src/pull/242#issuecomment-873259853
