### ISSUE TITLE
Incorrect behavior of CountOnNullRector

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#6515]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/056df761-9013-4fbe-b72b-22b05eded31b

```php
<?php

final class DemoFile
{
    public function hasMXRecords()
    {
        $mxrecords = [];

        getmxrr('getrector.org', $mxrecords);

        return count($mxrecords) === 0;
    }
}
```

### Responsible rules

* `CountOnNullRector`

## Expected Behavior

`$mxrecords` is initiated as an array and the `&$hosts` variable in `getmxrr` is an array as well: https://www.php.net/manual/en/function.getmxrr.php

I think the code is fine, so the added `is_countable` isn't needed.

(and yes, this kind of passing by reference are a pain in the ass)

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by TomasVotruba** [comment]
Thanks for reporting, this must be fixed in PHPStan correctly first.

See https://github.com/rectorphp/rector-src/pull/262#issuecomment-866804060

**Comment by stephanvierkant** [comment]
Should we create an issue on PHPstan's side?

**Comment by TomasVotruba** [comment]
Even better fix it, I think PHPStan has list of functions that adds references variables specific type

**Comment by stephanvierkant** [comment]
Never looked into the internals of PHPstan, but I'll try it!
