### ISSUE TITLE
TwigSetList::TWIG_UNDERSCORE_TO_NAMESPACE does not affect Twig_TemplateWrapper

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#6517]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 5e57bb61bcae1bb015819d2e3f47bbc9bbdaab5c             |

## Minimal PHP Code Causing Issue

```php
/**
 * @param $templateFile
 * @param string $pageTitle
 * @return Twig_TemplateWrapper
 */
function getTemplate($templateFile, $pageTitle = '')
{
}
```

## Expected Behaviour

```php
/**
 * @param $templateFile
 * @param string $pageTitle
 * @return \Twig\TemplateWrapper
 */
function getTemplate($templateFile, $pageTitle = '')
{
}
```

**Comment by HenkPoley** [comment]
Slightly off-topic, but it would be nice if the bot pointed me to:

https://github.com/rectorphp/rector-symfony/blob/main/config/sets/twig/twig-underscore-to-namespace.php

Or: https://github.com/rectorphp/rector-symfony/

**Comment by TomasVotruba** [comment]
> Slightly off-topic, but it would be nice if the pull-request closer bot pointed me to:



Good idea! :+1: 

I don't know if the action allows it conditional text, but if you can find a way, here is the config for it:
https://github.com/rectorphp/rector/blob/main/.github/workflows/auto_closer.yaml

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector-symfony/pull/20

Btw, tip for automated closing on GitHub: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

E.g.

```
Closes https://github.com/rectorphp/rector/issues/6517
```

↓

*Closes https://github.com/rectorphp/rector/issues/6517*

That would save us this manual work after the PR is merged :+1:

**Comment by HenkPoley** [comment]
🤔 it appears [close-pull-request](https://github.com/superbrothers/close-pull-request) can't do that.

But maybe some [jql](https://github.com/yamafaktory/jql) on the packages.lock could surface `packages.source.{name,source.url}` (imaginary query)

**Comment by TomasVotruba** [comment]
Maybe the static text could be updated to mention the split repositories. Would that help you to find them fsater? :+1:

**Comment by HenkPoley** [comment]
Sure a document could be maintained manually 🤭.

It is possible automate it with [`jq`](https://stedolan.github.io/jq/), which is "a tad bit" slower than `jql` I mentioned before.

```shell
jq '[.packages[]|{name:.name, source: .source.url}]' composer.lock
```

---

Not needed, but..

Not sure how to combine these two `jql` queries into 1 JSON output:
```shell
jql '\"packages\"|\"name\"' .\composer.lock
jql '\"packages\"|\"source\".\"url\"' .\composer.lock
```
Could be under your [non-Power]shell you don't need to escape double-quotes.

**Comment by TomasVotruba** [comment]
I'll leave the setup to you :+1: send PR when ready, I'll check it

**Comment by HenkPoley** [comment]
Nice, but then it will probably not happen, as I have no idea how to run Github actions, and this is already way too much time I spent on it 😅

Even better `jq` query to just extract the `vendor/*rector*` package

```shell
jq '.packages[] | select(.name | contains(\"rector\")) | {name:.name, source: .source.url}' composer.lock
```
