### ISSUE TITLE
Class 'Rector\Arguments\Rector\ClassMethod\ArgumentDefaultValueReplacerRector' not found

### ISSUE THREAD

**Issue by pierredup** [rectorphp/rector#6521]
# Bug Report

| Subject        | Details        |
| :------------- | :--------------|
| Rector version | >= 0.11.17     |

When using the Symfony 4.2 setlist, the following error occurs:

```
[ERROR] Class 'Rector\Arguments\Rector\ClassMethod\ArgumentDefaultValueReplacerRector' not found
```

This happens when using Rector >= 0.11.17. Downgrading to version 0.11.16, the error then doesn't appear.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/183d382f-8dfc-4fa7-a1d7-3118d2dc5333

```php
<?php

// rector.php

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Symfony\Set\SymfonySetList;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(SymfonySetList::SYMFONY_42);
};
```

## Expected Behaviour

No errors

**Comment by TomasVotruba** [comment]
Thanks for reporting!

We've just released new Symfony package, that fixes this
