### ISSUE TITLE
Typed property and use statement

### ISSUE THREAD

**Issue by mremi** [rectorphp/rector#6522]
# Question
Hi,

Is there any way using Rector to add a use statement with the TypedPropertyRector rule?

Currently I get something like that:

```php
namespace App;

class Foo
{
-    private $bar;
+    private \App\Other\Bar $bar;
}
```

and I'd like:
```php
namespace App;

+ use App\Other\Bar;

class Foo
{
-    private $bar;
+    private Bar $bar;
}
```

Thanks

**Comment by samsonasik** [comment]
You can use `$parameters->set(Option::AUTO_IMPORT_NAMES, true);` option, you can check the example here:

https://github.com/rectorphp/rector-src/blob/4631ae6b9e9cbdf321f128463ed3e4512cf5a27d/rules-tests/Php74/Rector/Property/TypedPropertyRector/config/imported_type.php#L11

to make result like the following:

https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php74/Rector/Property/TypedPropertyRector/FixtureImported/already_imported_short_name.php.inc

**Comment by mremi** [comment]
Nice, thanks for the quick answer
