### ISSUE TITLE
Migration from PHP 7.4 to 8.0 does not work as expected

### ISSUE THREAD

**Issue by vincentchalamon** [rectorphp/rector#6523]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.23 (_tested on v0.10.\* and v0.11.\*_) |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebd4f18-acf6-6154-a3ee-1fd4f6df4ea2

## Expected Behaviour

I tried to follow [this tutorial](https://getrector.org/blog/2020/11/30/smooth-upgrade-to-php-8-in-diffs) to upgrade my PHP 7.4 project to PHP 8.0. To ensure everything is working well, I set a fake controller (cf. link above). Only 1 rule has been applied ([ClassOnObjectRector](https://wiki.php.net/rfc/class_name_literal_on_object)), but I expected the following rules to be applied too:
- Symfony Annotations to Attributes
- Replace Null Checks with Null Safe Calls
- From switch() to match()

Many other rules have been skipped too.

**Comment by samsonasik** [comment]
- for symfony annotation to attributes, you need to configure yourself, ref 

https://github.com/rectorphp/rector-src/blob/328b5b4a02df62bcfed9af0f7c2aabc9db5178a1/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php#L22

- your example doesn't match null safe criteria as there is no other call.

- switch to match conversion won't work on direct echo, it will work on assign/return, ref https://getrector.org/demo/1ebd4f2f-bc8f-66da-a82e-9d758891c1ad
