### ISSUE TITLE
MakeCommandLazyRector: description can be lazy too

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#6524]
# Feature Request

`\Rector\Symfony\Rector\Class_\MakeCommandLazyRector` makes command lazy by setting the name of command as a property. As of Symfony 5.3, commands description can be lazy too:

https://symfony.com/blog/new-in-symfony-5-3-lazy-command-description

It'd be great if this rector also makes the description a static property.

**Comment by TomasVotruba** [comment]
Thanks for suggestion!

We're quit busy with other features now,
but if you'd like to contribute this, we'll help you with the process :+1:
