### ISSUE TITLE
AddDefaultValueForUndefinedVariableRector incorrectly duplicating a variable that already exists

### ISSUE THREAD

**Issue by rafaelbernard** [rectorphp/rector#6525]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | > v0.11.3  |
| Installed as | Running on docker            |

This is the same behaviour as the issue #3828. The difference I see is that this is being running on docker.

Notes: Started on version 0.11.3. (version 0.11.2 is working fine)
```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ @@
     {
                $previous_testid = null;
+               $previous_testid = null;
                $input = [];
                $current_test = [];
                $test_total = [];
    ----------- end diff -----------

Applied rules:
 * AddDefaultValueForUndefinedVariableRector (https://github.com/vimeo/psalm/blob/29b70442b11e3e66113935a2ee22e165a70c74a4/docs/fixing_code.md#possiblyundefinedvariable)
```

## Minimal PHP Code Causing Issue

I was not able to reproduce on the demo site without using try/error to remove sensitive code.
Rector config: https://getrector.org/demo/1ebd51bc-6b79-6680-ae77-97ab2e7ffe41

## Expected Behaviour

Rector should not be duplicating a variable that is already present

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
Rector is currently version 0.11.23, what actual version currently you're using?

**Comment by rafaelbernard** [comment]
> Thank you for your report and demo link!
> 
> Could you send a failing test case in a pull-request, so we have it covered in Rector?
> Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

Thank you for the response. And for the awesome work with rector.

I will do it as soon as possible.

**Comment by rafaelbernard** [comment]
> Rector is currently version 0.11.23, what actual version currently you're using?

@samsonasik The project is running PHP 5.6, so I am running inside docker. Until version 0.11.2 this is working fine. But >0.11.2 and <=0.11.20 are failing.

**Comment by rafaelbernard** [comment]
It seems that another class or file is impacting on rector process because I cannot simulate the issue when isolating the changed file. I am trying to identify what is the culprit.

**Comment by rafaelbernard** [comment]
I cannot isolate the single class that has been affected, so I can confirm that another code is affecting this. I will close it. Temporarily, I am ignoring that single class for this single rule. I will re-open if I find how to reproduce it.
