### ISSUE TITLE
`@see` annotation at test-suites

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6526]
wouldn't it also make sense to have a `@see` annoation above the test-case classes, like we have at the rector classes to the tests atm?

when starting from a failing test-case one need to "find" the actual rector involved via IDE/by-hand, while a proper `@see` annoation could just navigation with a single click.

example: we have a link from rector to its test

![grafik](https://user-images.githubusercontent.com/120441/123410731-eb621980-d5af-11eb-8022-0bbe1eab2dd9.png)

but not the other way arround:

![grafik](https://user-images.githubusercontent.com/120441/123410761-f3ba5480-d5af-11eb-92d5-3c1ffbfa91d8.png)

**Comment by TomasVotruba** [comment]
I came across similar frustration, when this works just one direction.
So yes, this would be welcomed :+1:

**Comment by staabm** [comment]
Related rector is https://github.com/rectorphp/rector-phpunit/blob/main/src/Rector/Class_/AddSeeTestAnnotationRector.php

**Comment by TomasVotruba** [comment]
New rule would be better as it will require higher complexity

**Comment by TomasVotruba** [comment]
Closing as not an issue and accepted to narrow focus :+1: 

Feel free to send PR
