### ISSUE TITLE
unexpected token error

### ISSUE THREAD

**Issue by sdonmt** [rectorphp/rector#6528]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector 328b5b4a02df62bcfed9af0f7c2aabc9db5178a1 |

I'm getting:
`[ERROR] Unexpected token "", expected ')' at offset 578`

## Minimal PHP Code Causing Issue

That's what I would like to know! The error tells me nothing and I don't even know what file

## Expected Behaviour

[ERROR] Unexpected token "", expected ')' at /path/to/somewhere/where/that/happens.php on line 123 at offset 578

Could you anyhow refactor that message accordingly?

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by sdonmt** [comment]
well I just used the option -vvv and posted the contents of the last listed file to the demo page.
That might be the one https://getrector.org/demo/1ebd7ec3-a03d-65cc-9771-5d818f32be4e

**Comment by TomasVotruba** [comment]
This is very hard to read. We need a smaller demo like 5-10 lines that causes the issue.

Feel free to improve the error message :+1:

**Comment by TomasVotruba** [comment]
Closing for lack of narrow feedback.
