### ISSUE TITLE
Incorrect behavior of RemoveUnusedVariableAssignRector

### ISSUE THREAD

**Issue by wdoug** [rectorphp/rector#6529]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

I tried several versions of simplifying this example but couldn't find a variation that continued to fail for some reason.

See https://getrector.org/demo/1ebd611b-480b-6482-8760-6735874a79e7

```php
<?php

namespace CJCodes\TwoFactorBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritDoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder('cj_codes_two_factor');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
            ->scalarNode('example')->end()
            ->scalarNode('example')->end()
            ->scalarNode('example')->end()
            ->scalarNode('example')->end()
            ->arrayNode('example')
                ->prototype('example')->end()
            ->end()
            ->arrayNode('example')
                ->children()
                    ->scalarNode('example')->end()
                    ->scalarNode('example')->end()
                ->end()
            ->end()
            ->arrayNode('example')
                ->children()
                    ->scalarNode('example')->end()
                    ->scalarNode('example')->end()
                ->end()
            ->end()
            ->scalarNode('example')
                ->defaultValue('example')
                ->end()
            ->scalarNode('example')
                ->defaultValue(3)
                ->end()
            ->end();

        return $treeBuilder;
    }
}
```

### Responsible rules

* `RemoveUnusedVariableAssignRector`

## Expected Behavior

The `RemoveUnusedVariableAssignRector` Rector should not remove any code as there is nothing here that is not used.

What is actually happening is that the rule is removing the definition of `$rootNode` even though it is being used on the very next line.

**Comment by samsonasik** [comment]
Could you create PR for new faiilng fixture for it at https://github.com/rectorphp/rector-src/tree/main/rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture ? Thank you.

**Comment by rajyan** [comment]
@wdoug 
The method chain is ignored because the default `NESTED_CHAIN_METHOD_CALL_LIMIT` is 30.

You can fix it by configuring this option to a larger value than the chain.
https://getrector.org/demo/1ebd6c08-8f38-654c-a3a7-73f1eff43d6b

**Comment by wdoug** [comment]
Interesting. Thank you.

What is the purpose of that limit? Is there a way that if that limit is reached it Rector could spit out a warning instead of just silently outputting invalid code?

**Comment by TomasVotruba** [comment]
Mostly performance. It might be better now, but 2 years back PHPStan had troubles analyzing the nested calls.


But it might have changed since :) 
We can increase the limit to double and see what happens.

**Comment by TomasVotruba** [comment]
Closing as answered. Feel free to send PR with constant update :+1:

**Comment by samsonasik** [comment]
It seems already updated 

https://github.com/rectorphp/rector-src/blob/ced0b7e5ddf68238412188da27ff825edb2c07bd/config/parameters.php#L25
