### ISSUE TITLE
Incorrect behavior of TypedPropertyRector

### ISSUE THREAD

**Issue by lukasluecke** [rectorphp/rector#6533]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebd8009-33ac-65e2-9b25-233cafd1fd75

```php
<?php

namespace App\Enum;


class MyEnum
{

    public const STARTING      = 'starting';
    public const NOT_RUNNING   = 'notRunning';
    public const RUNNING       = 'running'; // some comment

    /**
     * @var array
     */
    protected static $values = [
        self::STARTING      => 'Starting',
        self::NOT_RUNNING   => 'Not running',
        self::RUNNING       => 'Running',
    ];

    public static function getRunningStates(): array
    {
        return [
            static::RUNNING,
        ];
    }

    public static function isRunningState(string $state): bool
    {
        return in_array($state, static::getRunningStates(), true);
    }
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

Should preserve the comment and whitespace preceding the typed property.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. This is limit of AST tree. The comments are attached to node that follow it. Such approach will cause you troubles in any rule and is impossible to fix as we only build on AST.

The fix is it place comments above:
https://getrector.org/demo/1ebd800e-41ca-623c-aa4b-57b21ffd20a7

**Comment by lukasluecke** [comment]
@TomasVotruba Ah okay, no worries 🙂
