### ISSUE TITLE
`AUTO_IMPORT_NAMES` option breaks annotations

### ISSUE THREAD

**Issue by wryk** [rectorphp/rector#6534]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | ea11625cfb69e7f5a0438ef8391dc9177fdb7f1d from rector --version, 0.11.21 from composer show |

I just stumbled on a issue when using `AUTO_IMPORT_NAMES` option on a code base with doctrine annotations.
When this option is enabled Rector mess up imported annotations,  for non-nested annotations its only add a useless namespace import but with nested ones its partially remove them therefore breaking the code.

## Minimal PHP Code Causing Issue
Non-nested annotations : https://getrector.org/demo/1ebd82e5-18e0-67e8-bca7-5dd9dea16e76
Nested annotations : https://getrector.org/demo/1ebd82e6-95e4-63a6-afce-2bac95e308d2

Slightly similar cases with Rector not doing any change
Non imported annotations : https://getrector.org/demo/1ebd82e8-0cee-6982-9ad3-917367a4bfc0
PHP 8 attributes instead of annotations : https://getrector.org/demo/1ebd82ed-ee84-618a-9a07-a5f1cc74e723

## Expected Behaviour

I don't know what behavior Rector should use but at least not breaking the code with nested annotations seems the correct option.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting and exact simple examples where the rule breaks!

We've fixed something similar in `0.11.28` (not on demo yet, as it's updated once a 3 days). 
Could you check if the bug is still there?

**Comment by wryk** [comment]
Upgraded to 0.11.28 and the issue is gone. Sorry for the already fixed bug report

**Comment by TomasVotruba** [comment]
No troubles, it might have been something else.

Thank for confirmation :+1:
