### ISSUE TITLE
ClassPropertyAssignToConstructorPromotionRector must skip callable properties

### ISSUE THREAD

**Issue by slepic** [rectorphp/rector#6535]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.28 (invoke `vendor/bin/rector --version`)             |

Rector `\Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector` tries to refactor constructor promotion when property has no typehint and the constructor argument has callable typehint.

This cannot be converted to constructor promotion because `callable` is not allowed for properties.

The following constructor is not valid PHP 8.0 syntax:

```
public function __construct(protected ?callable $cb) {}
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebd8e50-729d-67b0-8084-bb39b9e16aed

## Expected Behaviour

No change

**Comment by slepic** [comment]
PS: the argument being nullable and the protected visibility should be irrelevant, but those are the case that I encountered in my use-case...

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by tugmaks** [comment]
Same issue, small patch here - https://github.com/rectorphp/rector-src/pull/338
