### ISSUE TITLE
PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider::hasClass(): Argument #1 ($className) must be of type string, int given

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#6540]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.32             |

PHP Fatal error:  Uncaught TypeError: PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider::hasClass(): Argument #1 ($className) must be of type string, int given, called in vendor/rector/rector/packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php on line 112 and defined in phar:///home/{snap}/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php:25

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebdd6d7-d305-6bfa-aa66-e9270fcce247

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by stephanvierkant** [comment]
Any idea where I should add it? Since I got a fatal error, I don't know which rule is relevant.

**Comment by samsonasik** [comment]
You can run rector locally with `--debug` option to see what nearest rules that cause the error.

**Comment by stephanvierkant** [comment]
I failed to reproduce this issue in the rector-src repo. Can someone help me reproducing this issue?
