### ISSUE TITLE
Invalid static return produced by ReturnTypeDeclarationRector

### ISSUE THREAD

**Issue by joskfg** [rectorphp/rector#6541]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.10.17            |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebdb255-b34c-6cba-9fa6-49a1dce494b7

## Expected Behaviour

```
 final class DemoFile
 {
-    public function run()
+    public function run(): static
     {
         return new static();
     }
 }
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
@joskfg returns `static` type in php 8 seems fine, while it will got error in php <= 7.4, ref https://3v4l.org/daBZ0 . The handling may be need handle php 8 and php <= 7.4.

Could you create failing fixture under the following 2 places?

- https://github.com/rectorphp/rector-src/tree/main/rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureInheritance or https://github.com/rectorphp/rector-src/tree/main/rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture php <= 7.4 check

- https://github.com/rectorphp/rector-src/tree/main/rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp80 for php >= 8.0 check..

**Comment by joskfg** [comment]
Yes, the issue with PHP 8 seems to be related to `\static`, no `static`. I'll try to create the failing fixture.
