### ISSUE TITLE
`InfiniteLoopTraversingException` when applying `LogicalToBooleanRector`

### ISSUE THREAD

**Issue by wryk** [rectorphp/rector#6542]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.32 - 8733e7335f381c3b426f01d0fa3f24f18522cf8e |

I got a `Rector\Core\Exception\NodeTraverser\InfiniteLoopTraversingException` from `Rector\Core\Validation\InfiniteLoopValidator` when applying `https://getrector.org/demo/1ebdb556-8dab-66d8-a2c9-6728d549b4eb`.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebdb62f-3829-6b72-9e9c-d9708fd7ad4e

## Expected Behaviour

Not a unhanded exception. The validator could allow a few tries before raising it.

---

I'll PR a test case whenever I can

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Feel free to re-open with test case PR
