### ISSUE TITLE
Rector 0.11.33 error StreamOutput

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6543]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.33             |

@TomasVotruba it seems there is error in 0.11.33 : 

```bash
PHP Fatal error:  Declaration of RectorPrefix20210702\Symfony\Component\Console\Output\StreamOutput::doWrite($message, $newline) must be compatible with RectorPrefix20210702\Symfony\Component\Console\Output\Output::doWrite(string $message, bool $newline) in /home/runner/work/rector/rector/vendor/symfony/console/Output/StreamOutput.php on line 28
```

ref : 
- https://github.com/rectorphp/rector/runs/2976476070#step:4:4
- https://github.com/rectorphp/getrector.org/pull/396/checks?check_run_id=2976654787#step:5:5

**Comment by samsonasik** [comment]
It seems the error is on `ContainerInterface` as well https://github.com/rectorphp/rector/runs/2976476174#step:7:4 

```bash
PHP Fatal error:  Declaration of RectorPrefix20210702\Symfony\Component\DependencyInjection\Container::get(string $id, int $invalidBehavior = 1) must be compatible with RectorPrefix20210702\Symfony\Component\DependencyInjection\ContainerInterface::get($id, $invalidBehavior = self::EXCEPTION_ON_INVALID_REFERENCE) in /home/runner/work/rector/rector/standalone/vendor/rector/rector/vendor/symfony/dependency-injection/Container.php on line 202
```

**Comment by samsonasik** [comment]
The error seems start from https://github.com/rectorphp/rector-src/pull/362

![Screen Shot 2021-07-03 at 16 56 06](https://user-images.githubusercontent.com/459648/124350570-93668b00-dc1f-11eb-858e-308344cbbebb.png)

**Comment by RikudouSage** [comment]
Same problem for me: https://github.com/RikudouSage/UnleashSDK/runs/2979602418?check_suite_focus=true

**Comment by samsonasik** [comment]
@RikudouSage you can temporary pin to 0.11.32 in composer.json

**Comment by samsonasik** [comment]
0.11.34 seems got error:

```bash
PHP Fatal error:  Declaration of RectorPrefix20210704\Symfony\Component\Console\Style\SymfonyStyle::ask(string $question, ?string $default = NULL, $validator = NULL) must be compatible with RectorPrefix20210704\Symfony\Component\Console\Style\StyleInterface::ask(string $question, ?string $default = NULL, ?callable $validator = NULL) in /home/runner/work/rector/rector/vendor/symfony/console/Style/SymfonyStyle.php on line 34

**Comment by andrew-demb** [comment]
The same for https://github.com/rectorphp/rector/blob/c7d260ee84ddcf6f9091165cbb03fdaa099be1c1/vendor/doctrine/inflector/lib/Doctrine/Inflector/LanguageInflectorFactory.php#L17 and https://github.com/rectorphp/rector/blob/c7d260ee84ddcf6f9091165cbb03fdaa099be1c1/vendor/doctrine/inflector/lib/Doctrine/Inflector/GenericLanguageInflectorFactory.php#L23

> PHP Fatal error:  Declaration of RectorPrefix20210704\Doctrine\Inflector\GenericLanguageInflectorFactory::withSingularRules(?RectorPrefix20210704\Doctrine\Inflector\Rules\Ruleset $singularRules, bool $reset = false): RectorPrefix20210704\Doctrine\Inflector\GenericLanguageInflectorFactory must be compatible with RectorPrefix20210704\Doctrine\Inflector\LanguageInflectorFactory::withSingularRules($singularRules, bool $reset = false) in /home/lalshe/php/libraries/platform-rector-rules/vendor/rector/rector/vendor/doctrine/inflector/lib/Doctrine/Inflector/GenericLanguageInflectorFactory.php on line 23

**Comment by TomasVotruba** [comment]
I've got some good news. After 3 days of work, Rector has been restored for PHP 8, 7.4, 7.3 and 7.2.

One more to go - PHP 7.1 - to make build fully green. Thank you all for patience

<br>

![image](https://user-images.githubusercontent.com/924196/124492455-c68e5300-ddb4-11eb-9e6a-62fe9129d6c4.png)

**Comment by TomasVotruba** [comment]
Phew, 3 days long work streak :) We've just released https://github.com/rectorphp/rector/releases/tag/0.11.35

Could you test it and verify if the code base is downgraded correctly?

**Comment by samsonasik** [comment]
@TomasVotruba it seems working ok now 🎉🎉🎉 , thank you 👍
