### ISSUE TITLE
Downgrading array spread operator doesn't check if iterable is array

### ISSUE THREAD

**Issue by RikudouSage** [rectorphp/rector#6544]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.32            |

Having a function that accepts iterable and then using the array spread operator causes an error because it gets transformed to `iterator_to_array()` call which doesn't work on arrays.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebdc1bc-54be-62ae-bb7e-e7ae571c9e5f

```php
<?php

final class DemoFile
{
    public function test(iterable $something): array
    {
        return [...$something];
    }
}
```

## Expected Behaviour

```php
<?php

final class DemoFile
{
    public function test(iterable $something): array
    {
        return array_merge(is_array($something) ? $something : iterator_to_array($something));
    }
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
