### ISSUE TITLE
PHP 8 downgrade doesn't handle throw now being an expression, not statement

### ISSUE THREAD

**Issue by RikudouSage** [rectorphp/rector#6545]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.32           |

Not sure if this should be filed as bug or feature request. The downgrade should handle using `throw` in expressions, currently it does nothing.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebdc1d3-5b54-6480-bf4c-d914c8eab97b

```php
<?php

final class DemoFile
{
    public function run()
    {
        $id = $somethingNonexistent ?? throw new RuntimeException();
    }
}
```

## Expected Behaviour

Something like this:

```php
<?php

final class DemoFile
{
    public function run()
    {
        if (!isset($somethingNonexistent)) {
            throw new RuntimeException();
        }
        $id = $somethingNonexistent;
    }
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by RikudouSage** [comment]
Not sure how to do it as there doesn't seem to be any rector rule for downgrading this.

**Comment by TomasVotruba** [comment]
What about `DowngradeNullCoalesceRector`?

**Comment by RikudouSage** [comment]
That probably wouldn't help as it concerns also stuff like this, I'm afraid that it will have to be a rule on its own (also sorry for mislabeling it as a bug):

```php
<?php

$a = throw new Exception();
```

**Comment by TomasVotruba** [comment]
I see, new rule is needed then.
