### ISSUE TITLE
PHP 8 downgrade named arguments

### ISSUE THREAD

**Issue by RikudouSage** [rectorphp/rector#6547]
# Feature Request

Add support for downgrading named arguments.
 
## Diff 

```diff
- json_decode('{}', associative: true, flags: JSON_THROW_ON_ERROR);
+ json_decode('{}', true, 512, JSON_THROW_ON_ERROR);
```

**Comment by TomasVotruba** [comment]
Hi, thanks for the suggestion.

Rector already has such a rule - `DowngradeNamedArgumentRector`, but I guess you're tried it and it's not working for you correctly :)

Could you add a test fixture to `DowngradeNamedArgumentRectorTest` to show your issue?

**Comment by samsonasik** [comment]
I tried it, It missing `FuncCall` in node types definition, and it seems not possible due PHPStan `PHPStan\Reflection\Native\NativeParameterReflection` can't get default value of function parameter, eg: 512 for "depth" key.

**Comment by samsonasik** [comment]
We possibly need to use native PHP's ReflectionParameter ref https://3v4l.org/9kEnk

**Comment by TomasVotruba** [comment]
> We possibly need to use native PHP's ReflectionParameter ref 3v4l.org/9kEnk

I think that's the only way here. Another more complicated way, but with static reflection, would be to use static `AstResolver` to parse the parameter and then get the value from `Param->default` AST node
