### ISSUE TITLE
StrEndsWithRector does not fix hardcoded suffix

### ISSUE THREAD

**Issue by Tobion** [rectorphp/rector#6549]
# Feature Request

StrEndsWithRector  can correctly improve a snippet like `substr($test, -\strlen($file)) === $file)`
But I does not fix the more common case of looking for a hardcoded value like `'Bundle' === substr($string, -6)` which should be rewritten to `str_ends_with($string, 'Bundle')`. Negation like `'Bundle' !== substr($string, -6)` should be handled as well.

This missing feature makes StrEndsWithRector not that useful at the moment as hardcoded value is much more common, see example https://github.com/symfony/symfony/pull/41973/files
 
Failing Demo: https://getrector.org/demo/1ebdcee5-8ff8-6988-9650-4bfbd6624c45

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md
