### ISSUE TITLE
Fatal Error: GenericLanguageInflectorFactory::withSingularRules

### ISSUE THREAD

**Issue by 50bhan** [rectorphp/rector#6550]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.34|

Hello @TomasVotruba. I'm running the Rector against the `PhpInsights` code base. I faced an issue on CI.

You can find the CI failure here: https://github.com/nunomaduro/phpinsights/pull/509/checks?check_run_id=2985011861

**Comment by samsonasik** [comment]
You can temporary pin 0.11.32 for now in composer.json

**Comment by 50bhan** [comment]
@samsonasik Problem still remains at 0.11.32

**Comment by samsonasik** [comment]
You need to remove the `^`, just pin the exact version `"rector/rector": "0.11.32"`

**Comment by 50bhan** [comment]
@samsonasik Hah! Thanks. Fixed now.
