### ISSUE TITLE
DoctrineAnnotationClassToAttributeRector not changing any code

### ISSUE THREAD

**Issue by TNAJanssen** [rectorphp/rector#6553]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |0.11.32             |

On a Symfony project using Doctrine 2.9.3 it will not rewrite annotations to attributes.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebdd6a1-2d80-685a-a9b1-27b9c87a0ef5

## Expected Behaviour

I expect it to replace the annotations with attributes.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
This rule does something different. It changes annotation class itself, see https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#doctrineannotationclasstoattributerector


You're probably looking for:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#annotationtoattributerector

Check sets in rector-doctrine project, they're preconfigured to save your time

**Comment by TNAJanssen** [comment]
Got it, sorry my bad!
