### ISSUE TITLE
DiscriminatorMap values are removed

### ISSUE THREAD

**Issue by TNAJanssen** [rectorphp/rector#6554]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.32             |

It removes all but one DiscriminatorMapping value

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebdd728-308a-614a-9189-0996221634a7

## Expected Behaviour

I expect all DiscriminatorMap values to be there after conversion.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by TNAJanssen** [comment]
@TomasVotruba thanks for the quick reply, i added a failing test in the doctrine repository :)

**Comment by TomasVotruba** [comment]
Closing for lack of feedback for last month, so we can better focus on active bugs.
 
This issues might have been already fixed, as we've added many contributions in attribute land. If not feel free to re-open in  https://github.com/rectorphp/rector-src/pull/386 if so.
