### ISSUE TITLE
`ChangeLocalPropertyToVariableRector` skips classes with constructors

### ISSUE THREAD

**Issue by matt-allan** [rectorphp/rector#6559]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.21 (ea11625cfb69e7f5a0438ef8391dc9177fdb7f1d             |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebde924-775b-60ac-b9ff-a126a12d5ab0

## Expected Behaviour

The property is replaced with a local variable

## Actual behavior

Rector skips any classes with constructors

## Notes

This appears to happen because `PropertyFetchByMethodAnalyzer::collectPropertyFetchByMethods` [returns early when it finds a constructor](https://github.com/rectorphp/rector/blob/41844a92f351cdad441a968beb650231ac27be47/rules/Privatization/NodeAnalyzer/PropertyFetchByMethodAnalyzer.php#L57). Shouldn't that be `continue` instead of `return []`?

**Comment by samsonasik** [comment]
Could you try with latest rector 0.11.35 ?

**Comment by matt-allan** [comment]
@samsonasik I confirmed the issue still exists with 0.11.35

**Comment by samsonasik** [comment]
Thank you, could you provide a patch for it? Thank you.
