### ISSUE TITLE
Incorrect behavior of AddRemovedDefaultValuesRector, CellStaticToCoordinateRector, ChangePdfWriterRector, RenameClassRector

### ISSUE THREAD

**Issue by AlbertDIGI** [rectorphp/rector#6562]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebdfe6d-5af5-6cb0-89a8-b5ea6238adc4

```php
<?php

final class DemoFile
{
    public function run()
    {
        $worksheet = new \PHPExcel_Worksheet();
        $sheet = $objPHPExcel->getActiveSheet();
        $sheet->setCellValue('A1', 'Firstname');        
	$sheet->setCellValue('B1', 'Lastname');
	$sheet->setCellValue('C1', 'Date');
	$sheet->setCellValue('D1', 'Time');
	$sheet->setCellValue('E1', 'Price');
        PHPExcel_Cell::absoluteCoordinate();
        return 10;
    }
}
```

### Responsible rules

* `AddRemovedDefaultValuesRector`

* `CellStaticToCoordinateRector`

* `ChangePdfWriterRector`

* `RenameClassRector`

## Expected Behavior

change setCellValue to getCell('B1')->setValue('Lastname')

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
Using `setCellValue()` on activesheet still works on phpspreadsheet.It call from the activesheet like the code example in the documentation:

https://phpspreadsheet.readthedocs.io/en/latest/topics/accessing-cells/#setting-a-cell-value-by-coordinate

I am closing it.
