### ISSUE TITLE
AnnotationToAttributeRector doesn't preserve import aliases

### ISSUE THREAD

**Issue by adrianguenter** [rectorphp/rector#6565]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebe1a55-ad24-63c0-a88d-8b9629cb1791

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class DemoEntity
{
    public int $id;
}
```
Results in:

```php
 <?php
 
use Doctrine\ORM\Mapping as ORM;
 
#[\Doctrine\ORM\Mapping\Entity]
class DemoEntity
{
    public int $id;
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

The attribute should maintain the alias:

```php
<?php

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
class DemoEntity
{
    public int $id;
}
```

The current behavior either uses the FQCN or an import (depending upon `Option::AUTO_IMPORT_NAMES`) and leaves the existing aliased import's `use` statement dangling.

**Comment by TomasVotruba** [comment]
Hi, we don't support aliases by design. They're leftover from annotation times, that is not needed in attributes.
You can implement your own rule based on the native one, if you need it.

The unused aliases should be handled by your coding standard. See https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by adrianguenter** [comment]
@TomasVotruba I don't think I understand your reasoning here. Aliases have nothing to do with annotations. It was always possible to use an import or fully-qualified name with annotations (e.g. `/** @Entity */` or `/** @\Doctrine\ORM\Mapping\Entity */`. Did I completely misunderstand what you were trying to say, or...?

I like using the `Doctrine\ORM\Mapping` namespace as `ORM` instead of having multiple imports for every class I wish to use within that namespace. It's a matter of personal preference and I'd be very surprised to find I'm the only one who wishes to preserve the ORM alias when converting to attributes.

**Comment by TomasVotruba** [comment]
At the moment Rector does not support it, for simplicity and maintainability reasons.

We might accept such contribution, if it is thoroughly covered by tests.

**Comment by adrianguenter** [comment]
Now *that* is totally understandable. :)

If this continues to be a pain point for me I will look into implementing and creating a PR. Thanks.

**Comment by TomasVotruba** [comment]
Good news everyone :hugs: 
While working on PHP 8.1 nested attributes, we've added also support for keeping original aliases :+1: 

See https://github.com/rectorphp/rector-src/pull/1278

**Comment by adrianguenter** [comment]
Very good news indeed...thank you!!
