### ISSUE TITLE
AnnotationToAttributeRector doesn't support promoted properties

### ISSUE THREAD

**Issue by adrianguenter** [rectorphp/rector#6566]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebe1ace-8ebf-6ea6-9517-4b02d8c44417

```php
<?php

use Doctrine\ORM\Mapping\Column;

class DemoEntity
{
    /** @Column */
    private string $normalProperty;
    
    public function __construct(
        /** @Column */
        private string $promotedProperty,
    ) {
    }
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

`$promotedProperty` should also have its annotation replaced with an attribute.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by calvera** [comment]
see https://github.com/rectorphp/rector-src/pull/425

**Comment by samsonasik** [comment]
Closing as fixed at https://github.com/rectorphp/rector-src/pull/425
