### ISSUE TITLE
Incorrect behavior of AddArrayParamDocTypeRector

### ISSUE THREAD

**Issue by Androbin** [rectorphp/rector#6567]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebe342e-0c71-646c-a841-fb613cac70c0

```php
<?php
class Foo
{
    public bool $bar;

    public function setBar(?bool $bar): void
    {
        $this->bar = $bar;
    }
}
```

### Responsible rules

* `AddArrayParamDocTypeRector`

## Expected Behavior

Rector should skip it

## Actual Behavior

```php
<?php
class Foo
{
    public bool $bar;

    /**
     * @param bool $bar
     */
    public function setBar(?bool $bar): void
    {
        $this->bar = $bar;
    }
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by Androbin** [comment]
See https://github.com/rectorphp/rector-src/pull/451
