### ISSUE TITLE
Incorrect behavior of TokenGetAllToObjectRector

### ISSUE THREAD

**Issue by dhrrgn** [rectorphp/rector#6569]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebe3bc1-4911-6bfc-95d0-5d18556be22c

```php
<?php

final class DemoFile
{
    public function run()
    {
        $code = '<?php echo "Hello world"; ?>';

        $tokens = token_get_all($code);

        return $tokens;
    }
}
```

### Responsible rules

* `TokenGetAllToObjectRector`

## Expected Behavior

In PHP 8.0 RC4, the `PhpToken::getAll` method was renamed to `PhpToken::tokenize`. Therefore, `token_get_all` should be replaced with `PhpToken::tokenize`:

```php
<?php

final class DemoFile
{
    public function run()
    {
        $code = '<?php echo "Hello world"; ?>';

        $tokens = \PhpToken::tokenize($code);

        return $tokens;
    }
}
```

## Actual Behavior

```php
<?php

final class DemoFile
{
    public function run()
    {
        $code = '<?php echo "Hello world"; ?>';

        // Causes: Fatal error: Uncaught Error: Call to undefined method PhpToken::getAll()
        $tokens = \PhpToken::getAll($code);

        return $tokens;
    }
}
```

**Comment by samsonasik** [comment]
Could you create a patch for it? the patch location for references:

- https://github.com/rectorphp/rector-src/blob/f7eeebaa7bdb96a6bc7311b1fa4a4e8a19789b35/rules/Php80/Rector/FuncCall/TokenGetAllToObjectRector.php#L96

- also fixture files https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/FuncCall/TokenGetAllToObjectRector/Fixture

**Comment by dhrrgn** [comment]
@samsonasik Yup, no problem. https://github.com/rectorphp/rector-src/pull/431
