### ISSUE TITLE
backwards breaking change in StaticTypeMapper

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#6570]
# Bug Report

in https://github.com/rectorphp/rector-src/pull/373/files#diff-68b1c6c0d127e79348022f8a877dbf8c38ea03e3ec4d0addc0636716bf41afa5

a previously optional parameter was changed to be required, which breaks BC.

was this intentional?

![image](https://user-images.githubusercontent.com/47448731/125807742-3039543d-635a-414f-a218-beebe4929091.png)

**Comment by clxmstaab** [comment]
just realized that its even a change from `string` to a `TypeKind` which is another BC break

**Comment by TomasVotruba** [comment]
Hi, 

this is intentional, to use enum with explicit values, instead of only `string`.
