### ISSUE TITLE
slow feedback loop with github actions

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6574]
I guess you are already aware of it, but nevertheless:

contributing to rector recently get a lot harder, because the CI just need literally hours to complete.
feedback for a commit gets reported back ~6-7h after the commit.

the more people work on this repo and the more commits are pushed the longer the queue gets and the longer the feedback loop.

I would want to propose using https://github.com/styfle/cancel-workflow-action (never used it myself yet) which claims to cancel actions which are not yet completed, when new commits are pushed into a pull request.

that way we should at least get a smaller queue as a first measure to improve the feedback loop.

wdyt?

**Comment by staabm** [comment]
in  https://github.com/rectorphp/rector-src/actions?page=3 you can see jobs, which are still queued even though commits are already 9+ hours old:

![grafik](https://user-images.githubusercontent.com/120441/125914093-28c96aed-6204-485c-8f0d-aceaa6a914fe.png)

**Comment by TomasVotruba** [comment]
This is due to infinite loop we had 3 days ago. I asked Github for restart yesterday, but no response yet

**Comment by staabm** [comment]
> This is due to infinite loop we had 3 days ago. I asked Github for restart yesterday, but no response yet

ok cool, what do you think about setting the max-execution timeout for github action jobs to a lower value? 
per default this value is 6h which is pretty high and in case of endless loops gets a larger problem.

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

**Comment by TomasVotruba** [comment]
> can you forsee a good timeout value which can be applied to all jobs, e.g. 30min or similar?

Sounds good :+1:
