### ISSUE TITLE
Configure applied Coding Standards

### ISSUE THREAD

**Issue by hwaxman** [rectorphp/rector#6577]
# Question
As I understand it, once Rector makes the desired changes, it applies it's own coding style fixer to clean up the formatting.

How are we able to configure the rules used by that fixer?

Currently it is adding a new line to the end of each file that it parses; even those that have _no other refactoring applied_.

I will eventually add these new lines to my codebase, but for the time being I only want to apply **NonVariableToVariableOnFunctionCallRector**.

I have also installed ECS and configured it accordingly but Rector does not seem to use this file for instruction.

Thanks

**Comment by TomasVotruba** [comment]
Hi, this extra space is done by convention in standard printer. You can improve it, but I don't its worth it, as your coding standard would handle it anyway.

**Comment by hwaxman** [comment]
Thanks for your reply.

Can you point me in the direction of that printer? Is it using the ECS LineEndingFixer or a specific formatter within Rector?

The codebase is old and this is currently adding new lines to 6000+ files instead of just updating the ~300 that are needed.

**Comment by TomasVotruba** [comment]
> Can you point me in the direction of that printer? 

Yes, that's this part of Rector:

https://github.com/rectorphp/rector/blob/fcdb8020922bf2de475921d18dae4928233cad6c/src/PhpParser/Printer/BetterStandardPrinter.php#L120-L125

Check git blame on that line to find out why we had this `PHP_EOL`. Possibly to keep one standard for all files. The other option is not to add newline anywhere, but that's IMO bad practise.
