### ISSUE TITLE
NodeNameResolver's method getName() returns null for MethodCall when its name is Identifier 

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#6579]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main            |

Rector\NodeNameResolver\NodeNameResolver::getName returns null for MethodCall when its name is Identifier.

## Minimal PHP Code Causing Issue

Failing test case added https://github.com/rectorphp/rector-src/pull/458

## Expected Behaviour

Return name of method call like it does for $methodCall->name

**Comment by TomasVotruba** [comment]
Closing as this behavior is desired :+1: Let's continue in https://github.com/rectorphp/rector-src/pull/458
