### ISSUE TITLE
[DeadCode] Trait inheritance and removing unused promoted properties

### ISSUE THREAD

**Issue by annuh** [rectorphp/rector#6581]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.36             |

`RemoveUnusedPromotedPropertyRector` removes private properties that are being used in a trait. I think this broke in a recent version of Rector, since Rector didn't apply this change before.
Similar to this issue: https://github.com/rectorphp/rector/issues/2549.

## Minimal PHP Code Causing Issue

```php
<?php

namespace Rector\Tests\DeadCode\Rector\ClassMethod\RemoveUnusedPromotedPropertyRector\Fixture;

trait TraitA
{
    public function foo()
    {
        echo $this->usedDependency;
    }
}

class SomeClass
{
    use TraitA;

    public function __construct(
        private $usedDependency
    ) {
    }
}

?>
```

Now results in this diff:
```diff
 {
     use TraitA;
 
-    public function __construct(
-        private $usedDependency
-    ) {
+    public function __construct()
+    {
     }
 }
```

## Expected Behaviour

Rector should skip this.

**Comment by TomasVotruba** [comment]
Thank you for your report!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by annuh** [comment]
Done https://github.com/rectorphp/rector-src/pull/467 🙂
