### ISSUE TITLE
[PHP 8.1] Add final constants

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6583]
* Now supported in php-parser 4.12 - https://github.com/nikic/PHP-Parser/releases/tag/v4.12.0

**Comment by lptn** [comment]
hey @TomasVotruba 
In your opinion, should final classes have final modifiers for it's constants? 

`FinalizePublicClassConstantRector` ads `final` keyword for consts, but by default Rector (PHP_7* + PHP8* rules) doesn't add `final` keyword for class' properties (what is inconsistency, if I have not missed anything).

**Comment by TomasVotruba** [comment]
Hi, thanks for the question.
I do not connect the `final` on class constant/method/property to class definition at all, because it's 2 separate points of focus.

So if element should not change, make it `final`, whatever it is.
