### ISSUE TITLE
Run composer docs error: The process has been signaled with signal "11".

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6584]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | main             |

Running `composer docs` in rector-src got the following error:

```bash
The process has been signaled with signal "11".
```

ref https://github.com/rectorphp/rector-src/runs/3095293844?check_suite_focus=true#step:5:499

**Comment by TomasVotruba** [comment]
Any ideas what rule does this cause?

**Comment by samsonasik** [comment]
On debugging, it seems happen after rules: https://github.com/rectorphp/rector-src/blob/main/rules/CodeQuality/Rector/Equal/UseIdenticalOverEqualWithSameTypeRector.php

On 68 loop, still works:

![Screen Shot 2021-07-23 at 00 23 03](https://user-images.githubusercontent.com/459648/126682044-42cf786e-dce1-4e2e-975a-d9dc2a7b1e12.png)

On 69 Loops, got segmentation fault:

![Screen Shot 2021-07-23 at 00 23 25](https://user-images.githubusercontent.com/459648/126682096-33b1b37d-f2e6-49aa-8ca1-cdaf73e1b952.png)

**Comment by TomasVotruba** [comment]
I'll check it, thanks :+1:

**Comment by TomasVotruba** [comment]
I've just run:

```bash
composer docs
```

on latest `dev-main` and it runs ok :+1: 

Any idea why it's different for you locally? Maybe remove `/vendor` and `composer.lock` and run `composer update`?

**Comment by samsonasik** [comment]
I tried that, also update to latest composer and latest php 8.0.8. If I disable xdebug, I got error:

```bash
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /Users/samsonasik/www/rector-src/vendor/symplify/php-config-printer/src/NodeFactory/NewValueObjectFactory.php on line 33

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /Users/samsonasik/www/rector-src/vendor/symplify/php-config-printer/src/NodeFactory/NewValueObjectFactory.php on line 33
```

even the memory_limit increased to 4096MB, it still error.

**Comment by samsonasik** [comment]
It seems can be solved by skip the `Enum` class at 

https://github.com/symplify/symplify/blob/212c6c881b4e7d55ed2a927b716786b611a587bf/packages/php-config-printer/src/NodeFactory/NewValueObjectFactory.php#L35-L37

like:

```php
    private function resolvePropertyValuesFromValueObject(string $valueObjectClass, object $valueObject): array
    {
        if ($valueObjectClass === 'Rector\CodingStyle\Enum\PreferenceSelfThis') {
            return [];
        }
        
        // OR 
        if (str_contains($valueObjectClass, 'Enum')) {
            return [];
        }
```

**Comment by samsonasik** [comment]
The issue is, after skip that, the docs generated is invalid for it:

```diff
-- [Php81](#php81) (2)
+- [Php81](#php81) (4)
 
 - [PhpSpecToPHPUnit](#phpspectophpunit) (7)
 
@@ -2278,7 +2280,7 @@ return static function (ContainerConfigurator $containerConfigurator): void {
     $services->set(PreferThisOrSelfMethodCallRector::class)
         ->call('configure', [[
             PreferThisOrSelfMethodCallRector::TYPE_TO_PREFERENCE => ValueObjectInliner::inline([
-                PreferenceSelfThis::PREFER_SELF(),
+                new PreferenceSelfThis(),
             ]),
         ]]);
```

**Comment by TomasVotruba** [comment]
I see. I think the `resolvePropertyValuesFromValueObject` must work for `Enum` too. 
There is possibly some circular reference.

**Comment by samsonasik** [comment]
It seems can be solved with the following handling:

```diff
    public function create(object $valueObject): New_ | StaticCall
    {
        $valueObjectClass = $valueObject::class;

+        if (str_contains($valueObjectClass, 'Enum')) {
+            $constants = (new ReflectionClass($valueObjectClass))->getConstants();
+            foreach (array_keys($constants) as $key) {
+                if ($key === $valueObject->getKey()) {
+                    return new StaticCall(new Name($valueObjectClass), $key);
+                }
+            }
+        }

        $propertyValues = $this->resolvePropertyValuesFromValueObject($valueObjectClass, $valueObject);
        $args = $this->createArgs($propertyValues);

        return new New_(new FullyQualified($valueObjectClass), $args);
    }
```

but that will remove the `use` statement, while still correct if no namespace in the config:

```diff
-use Rector\CodingStyle\Enum\PreferenceSelfThis;
 use Rector\CodingStyle\Rector\MethodCall\PreferThisOrSelfMethodCallRector;
 use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
 use Symplify\SymfonyPhpConfig\ValueObjectInliner;
@@ -2280,7 +2279,7 @@ return static function (ContainerConfigurator $containerConfigurator): void {
     $services->set(PreferThisOrSelfMethodCallRector::class)
         ->call('configure', [[
             PreferThisOrSelfMethodCallRector::TYPE_TO_PREFERENCE => ValueObjectInliner::inline([
-                PreferenceSelfThis::PREFER_SELF(),
+                Rector\CodingStyle\Enum\PreferenceSelfThis::PREFER_SELF(),
             ]),
         ]]);
```

**Comment by samsonasik** [comment]
Using `FullyQualified` seems solve it 🎉 

![Screen Shot 2021-07-24 at 12 29 48](https://user-images.githubusercontent.com/459648/126858450-fe199818-4ea5-4687-a6e8-405bf5761016.png)

**Comment by samsonasik** [comment]
Just realized it already handled at 

https://github.com/symplify/symplify/blob/a9a4a2d89c19e99f90b7d1329bf661c52c28ed98/packages/php-config-printer/src/NodeFactory/NewValueObjectFactory.php#L22-L24

It seems needs a new release of `symplify/php-config-printer`, current `9.4.22` seems still not has the handling:

https://github.com/symplify/php-config-printer/blob/220e0a26625c1beb97d907700b61ec92bf600e25/src/NodeFactory/NewValueObjectFactory.php#L16-L23

**Comment by TomasVotruba** [comment]
The 9.4.23 https://packagist.org/packages/symplify/php-config-printer is now relased, if this helps here

**Comment by samsonasik** [comment]
Thank you 👍 , I confirm that it solved now.
