### ISSUE TITLE
PHP version warning using DEAD_CODE list after v0.11.38

### ISSUE THREAD

**Issue by fox91** [rectorphp/rector#6587]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `v0.11.38`             |
| PHP version | `7.4.21`             |

Rector show me this warning:

```
./vendor/bin/rector --no-ansi process --dry-run --no-progress-bar

 [WARNING] Your project requires min PHP version "7.4".10 Rectors require higher PHP version and will not run,          
           to avoid breaking your codebase.                                                                             

 ! [NOTE] Do you want to run them? Make "require" > "php" in `composer.json` higher,                                    
 !        or add "Option::PHP_VERSION_FEATURES" parameter to your `rector.php`.                                         

...
```

If I add this line to the rector config the warning is also shown:

```php
$parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);
```

## Composer config

```json
{
    ...
    "require": {
        "php": "^7.4"
    },
    "require-dev": {
        "rector/rector": "0.11.38"
    }
    ...
}
```

## Minimal PHP Code Causing Issue

No code needed.

## Expected Behaviour

No warning for the PHP version.

**Comment by samsonasik** [comment]
Have you add use statement in the config?

```php
use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
```

**Comment by fox91** [comment]
> Have you add use statement in the config?
> 
> ```
> use Rector\Core\Configuration\Option;
> use Rector\Core\ValueObject\PhpVersion;
> ```

Yes, without there is an error.

**Comment by samsonasik** [comment]
Could you create repository with github action running rector for it to show the error? Thank you.

**Comment by fox91** [comment]
> Could you create repository with github action running rector for it to show the error? Thank you.

Simple:

`composer.json`:

```json
{
    "require-dev": {
        "rector/rector": "^0.11.38"
    },
    "require": {
        "php": "^7.4"
    }
}
```

No warning:

```php
<?php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void
{
    $paths = [
        __DIR__.'/rector.php',
    ];

    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, $paths);
};
```

Warning:

```php
<?php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void
{
    $paths = [
        __DIR__.'/rector.php',
    ];

    $containerConfigurator->import(SetList::DEAD_CODE);

    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, $paths);
};
```

---

The warning seems related to the use of

```php
$containerConfigurator->import(SetList::DEAD_CODE);
```

**Comment by samsonasik** [comment]
That's seems due `RemoveUnusedPromotedPropertyRector` registered in `DEAD_CODE` set list, you can skip that in rector.php

```php
use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPromotedPropertyRector;

//...
    $parameters->set(Option::SKIP, [
        RemoveUnusedPromotedPropertyRector::class,
    ]);
```

**Comment by fox91** [comment]
> That's seems due `RemoveUnusedPromotedPropertyRector` registered in `DEAD_CODE` set list, you can skip that in rector.php
> 
> ```
> use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPromotedPropertyRector;
> 
> //...
>     $parameters->set(Option::SKIP, [
>         RemoveUnusedPromotedPropertyRector::class,
>     ]);
> ```

Yes, I confirm that work fine with this skip.

**Comment by fox91** [comment]
@samsonasik but I don't think that skipping `RemoveUnusedPromotedPropertyRector` is a bugfix.
Why the code worked fine until now?

**Comment by samsonasik** [comment]
That's just a warning as far as I know, show you that the specific rule may not run if the requirement not met.

**Comment by fox91** [comment]
Ok, thanks.
Actually I think that the warning must be rewritten to say that.

**Comment by samsonasik** [comment]
Feel free to create PR for that to https://github.com/rectorphp/rector-src 👍
