### ISSUE TITLE
Rector rules for `moneyphp/money`

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector#6588]
# Feature Request

Since [`moneyphp/money`](https://github.com/moneyphp/money) is a widely used library for operating with money values it would be great if Rector could help with upgrading code that uses it. Between 3.* and 4.* versions there's a BC break that require manual work and in large codebases it can be hard to upgrade by hand.
 
## Diff 

```diff
-$result = Money::EUR(800)->multiply(2.5);
-$result = Money::EUR(800)->divide(2.5);
+$result = Money::EUR(800)->multiply(sprintf('%.2F', 2.5));
+$result = Money::EUR(800)->divide(sprintf('%.2F', 2.5));
```

The tricky part is `sprintf`'s precision, maybe it could be configurable.

**Comment by TomasVotruba** [comment]
Hi,

thanks for clear description. We create new rules for groups that Rector itself uses (like PHP or Symfony), the rest depends on support for private projects. Despite that, this rule might be useful to generic community and we would love to have it here.

Would you like you contribute it?

**Comment by Wirone** [comment]
I really would like to, but currently I barely have free time (family affairs) and I don't know if I could do this as part of my work. If you could provide some checklist what should be considered (ruleset, naming convention, file structure etc.) it would be easier to implement, by me or anyone else 🙂

**Comment by TomasVotruba** [comment]
Understood :)

* Docs on how to make a rule is here: https://github.com/rectorphp/rector/blob/main/docs/create_own_rule.md
* The lazy devs like me use rule generator: https://github.com/rectorphp/rector-generator#rector-generator
* As for conventions, just follow the coding style of another rule. PHPStan and Rector will guide you in the CI :+1: 

Closing as resolved. The best way to learn Rector is to dive in :) so feel free re-open with a PR even if the rule is not finished yet :+1:

**Comment by Wirone** [comment]
@TomasVotruba FYI: I've created [`codito/rector-money`](https://packagist.org/packages/codito/rector-money) that handles automatic refactor using Rector so it can quickly make code compatible with `moneyphp/money` v4 🙂 It's tagged as `1.0.0-RC1` as of now, but it's considered as stable and working, I just wanted to get some feedback before tagging stable release.

If you like it, consider adding it in `suggests` section or advertise it in a different way 😉

**Comment by TomasVotruba** [comment]
Hi @Wirone , that's great news. Thanks for sharing and making the upgrade set open :+1: 

What about adding a "Projects using Rector" section directly to `README.md`? If you agree, send PR with link to [rector/rector-src](https://github.com/rectorphp/rector-src).
