### ISSUE TITLE
Customize DOCTRINE_ORM_29 to prevent deleted blank lines ?

### ISSUE THREAD

**Issue by bastien70** [rectorphp/rector#6589]
# Question

Using DOCTRINE_ORM_29, it will automatically remove all blank lines from files, example:

```php
$containerConfigurator->import(\Rector\Doctrine\Set\DoctrineSetList::DOCTRINE_ORM_29);
```

This

```php
    public function getA()
    {
        //..
    }

    public function getB()
    {
        //..
    }

    public function getC()
    {
        //..
    }
```

Will be transformed into

```php
    public function getA()
    {
        //..
    }
    public function getB()
    {
        //..
    }
    public function getC()
    {
        //..
    }
  ```
    
 How to prevent this ?

**Comment by TomasVotruba** [comment]
Hi, you came across unfortunate drawback of AST.

If some parent node is changes, there is a risk of loosing all it's spaces. This can fixed via coding standard
https://github.com/rectorphp/rector#how-to-apply-coding-standards or directly in php-parser. Nothing we can do here

**Comment by samsonasik** [comment]
I created PR for it to ensure add new line after registered statements on new rule `NewlineAfterStatementRector` https://github.com/rectorphp/rector-src/pull/787
