### ISSUE TITLE
Group PHP 8 attributes

### ISSUE THREAD

**Issue by bastien70** [rectorphp/rector#6590]
# Feature Request

The goal will be to group all PHP 8 attributes
 
## From 

```php
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Assert\NotBlank]
    private string $name;
```

## To

```php
    #[
        ORM\Id,
        ORM\GeneratedValue,
        ORM\Column(type: 'integer'),
        Assert\NotBlank
    ]
    private string $name;
```
Do you think that it's possible ?

**Comment by TomasVotruba** [comment]
Hi, this is possible. We don't support it to keep rules as simple as possible. It easier to work with AST that respect convention of single attribute per attribute group.

Yet, you can make it happen yourself. Basically you need to create a custom Rector rule that will merge all `attrGroups` to one.

```php
$attributes = [];

foreach ($node->attrGroups as $attrGroup) {
    foreach ($attrGroup->attrs as $attribute) {
        $attributes[] = $attribute;
    }
}

$node->attrGroups = [new AttributeGroup($attributes)];
```

:+1:
