### ISSUE TITLE
NullsafeOperatorRector bug

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6592]
Well looks like Rector is still cursed for me. Tried it according to readme and immediately ran into a fatal bug which is impossible to reproduce on your website. Can you please confirm that if Rector crashes on https://getrector.org/demo/ then the error is shown? It says "// no change" which is technically correct - if it crashed then it didn't change anything of course.

# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | a5d59dab8bd712261c5f0c56be070d7c15487265 (latest stable = 0.11.40) |

```
 [ERROR] Could not process                                                                                              
         "src/Module/Accounting/Policy/AccountingOrganization/AddContactCardTypesWhenAccountingOrganizationRegisteredPol
         icy.php" file, due to:                                                                                         
         "PhpParser\Node\Expr\Assign::__construct(): Argument #2 ($expr) must be of type PhpParser\Node\Expr, null      
         given, called in vendor/rector/rector/rules/Php80/Rector/If_/NullsafeOperatorRector.php:145". On line: 20      

```

## Minimal PHP Code Causing Issue

Unable to reproduce the issue on https://getrector.org/demo/ but here is the file and config: https://getrector.org/demo/1ebeea70-c9fd-60aa-9755-7963feac4da8

Of course I got the error many times on many different files. But so far none I tried reproduced the issue on rector demo.

## Expected Behaviour

No error.

**Comment by TomasVotruba** [comment]
Thanks! :+1: 

I'll see how to fix the demo to show the error

**Comment by TomasVotruba** [comment]
Re-opening to fix the DEMO form to show the error

**Comment by enumag** [comment]
You should have fixed the demo first. The test committed to the repo should contain a minimal reproducer, not the file from my project.

**Comment by TomasVotruba** [comment]
I work provided fixture only, feel free to update it :+1:

**Comment by TomasVotruba** [comment]
Now it's better :) 

https://getrector.org/demo/1ebef93c-5207-6b4c-916c-7f59b6b9d81a

**Comment by enumag** [comment]
https://github.com/rectorphp/rector-src/pull/534

**Comment by enumag** [comment]
@TomasVotruba Thanks for resolving this so quickly! Guess I'll give Rector another chance. :smile:

**Comment by TomasVotruba** [comment]
Glad to hear that 🤗

Thanks for great report. I appreciate you took the effort to find the rule and the single isolated file it failed on.
Thank to this great input it was a matter of 5 minutes then.
