### ISSUE TITLE
symfony http-kernel runs in debug mode, which is bad for performance

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#6594]
running `blackfire run --ignore-exit-status .\vendor\bin\phpunit .\rules-tests\CodeQuality\` on windows leads to the following blackfire profile:

![image](https://user-images.githubusercontent.com/47448731/127179928-b4be3ba2-bbfe-418e-8e29-00e420fc32fe.png)

here we can see a partly-hot path within the symfony kernel and its config cache.
a lot of IO happens to check whether the ConfigCache is fresh.

looking up symfonys' `ConfigCache->isFresh()` leads us to

![image](https://user-images.githubusercontent.com/47448731/127180167-34b3fc4b-0e37-4505-af0a-bce3df73fff7.png)

which tells me, that we run with DEBUG=true and this cost us time.
Is there a reason why we run the symfony kernel in debug-mode?

The `RectorKernel` gets the `debug` parameter via `__construct()`, but I don't know where this value is passed from.
for testing purposes I set the debug switch to `true`, which leads to blackfire profiles, which no longer are dominated by `ConfigCache->isFresh()` calls.

Could the debug-paramter be set to `false` by default? if so, where?

**Comment by TomasVotruba** [comment]
Hi, this is actually design rule from Symfony. The container is cached there, unless you call a config. This is problematic for nested imports configs of 3rd party packages.

Having cached container lead to missing rule, when you registered service it in `rector.php` and it was not found.

> The RectorKernel gets the debug parameter via __construct(),

Look for `new RectorKernel()`

**Comment by clxmstaab** [comment]
thx for the insights.

does this means we could deactivate the debug-mode in CI, since it starts from scratch?

**Comment by TomasVotruba** [comment]
This can be definitely improved, so if you find a way, I'd be very grateful for it :+1: 

The goal is to have ability to change `rector.php` and rebuild container cache based-on it (and it's included files).

> does this mean we could deactivate the debug-mode in CI, since it starts from scratch?

It depends on the implementation around `new RectorKernel()`. Symfony uses ENVs for this:

https://github.com/symfony/demo/blob/c109bb504cd9c3779f925dab75343a8eeb6f928f/bin/console#L14

**Comment by samsonasik** [comment]
I am closing it as the PR for it is closed at https://github.com/rectorphp/rector-src/pull/550
