### ISSUE TITLE
Incorrect behavior of ReturnTypeFromReturnNewRector

### ISSUE THREAD

**Issue by CoeusCC** [rectorphp/rector#6595]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.11.40      |
| Installed as   | "rector/rector": "^0.11.40"  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebef269-093c-6afe-9c29-afdc8959befb

```php
<?php

final class DemoFile
{
    public function run()
    {
        return new self();
    }
}
```

### Responsible rules

* `ReturnTypeFromReturnNewRector`

## Expected Behavior

The return type should either be:

```php
public function run(): self {}
```

...without the leading slash (global namespace), or the name of the class. I'm uncertain what the implications of choosing for the user would be as inheritance may come into play.

**Comment by samsonasik** [comment]
Could you create PR for faling fixture to https://github.com/rectorphp/rector-src/tree/main/rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromReturnNewRector/Fixture ? Thank you.

**Comment by CoeusCC** [comment]
I'd be happy to. Is there some documentation for this? This is my first interaction with this repository, and I'm not familiar with the failing fixtures concept. I'm sure it's quite simple, but I'm uninitiated.

**Comment by samsonasik** [comment]
You can click "Create a test" button at https://getrector.org/demo/1ebef269-093c-6afe-9c29-afdc8959befb

**Comment by CoeusCC** [comment]
Ah, wonderful. I'll do just that.
