### ISSUE TITLE
AnnotationToAttributeRector messes up 2 space indentation

### ISSUE THREAD

**Issue by pableu** [rectorphp/rector#6596]
# Bug Report

We have a codebase using 2 space indentation, but otherwise pretty much following PSR-12. Rector works pretty great, but the AnnotationToAttributeRector changes the output _partially_ to 4 space indentation.

In the resulting code from the demo, the class scope is indented with 4 spaces, but the method only with 2. I think it changes the indentation of the scope right under the annotation it rewrites to an attribute.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebef307-9375-6f9c-9625-558131060d23

```php
<?php
declare(strict_types=1);

namespace App\Controller\Plain;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/http-status/{status}", requirements={"status":"\d*"})
 */
class HttpStatusController
{
  public function __invoke(int $status = Response::HTTP_NOT_FOUND): Response
  {
    return new Response('', $status);
  }
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

```php
<?php
declare(strict_types=1);

namespace App\Controller\Plain;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/http-status/{status}', requirements: ['status' => '\d*'])]
class HttpStatusController
{
  public function __invoke(int $status = Response::HTTP_NOT_FOUND): Response
  {
    return new Response('', $status);
  }
}
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
Rector actually had a mechanism to guess if the code is using 2 spaces or 4, but it was very unreliable. It parsed the file and looked for minimal left indents, e.g. if 2 spaces found, it assumed it's a 2 space file. But it was not always the case. It caused more harm than good, as Rector is not a .coding standard tool

There is a better way, using your own coding standard that handles this by defined configuration:
https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by pableu** [comment]
Thanks Tomas. So I would first run rector and then ECS, or is it somehow integrated?

**Comment by TomasVotruba** [comment]
> I would first run rector and then ECS

Yes, or any other coding standard tool you prefer.

It's 2 separated tools, to avoid mixing concens.
