### ISSUE TITLE
NullsafeOperatorRector runs into parse error on null check

### ISSUE THREAD

**Issue by pableu** [rectorphp/rector#6598]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

Running rector on the blow code with the NullsafeOperatorRector throws this parse error: 

`PhpParser\Node\Expr\Assign::__construct(): Argument #2 ($expr) must be of type PhpParser\Node\Expr, null given, called in rector/rector/rules/Php80/Rector/If_/NullsafeOperatorRector.php on line 145`

See https://getrector.org/demo/1ebef95e-bfab-671c-a315-aba2f8df5fa8.

This _might_ be a duplicate of #6592, but I'm unsure. At least there's a minimal example here.

## Minimal PHP Code Causing Issue

```
<?php

class foo
{

    public function bar(string $language = null)
    {
        $criteria = [];
        
        if ($language !== null) {
            $criteria['lang'] = $language;
        }

        return $criteria;
    }

}
```

## Expected Behaviour

No Change. No Error.

**Comment by samsonasik** [comment]
@pableu could you try use

```json
 "rector/rector": "dev-main"
```

 in your composer.json and run: 
 
 ```bash
 composer update
 vendor/bin/rector process --clear-cache
 ```
 
 and verify if it is already fixed ? Thank you.

**Comment by pableu** [comment]
Doesn't the demo use `dev-main`?

**Comment by samsonasik** [comment]
No, demo run latest release.

**Comment by pableu** [comment]
Oh, that's good to know :-) 

I just tested it with dev-main, and it **does not happen anymore**. So this issue is obsolete.

Thanks for the clarification, and sorry for the hassle :-)
