### ISSUE TITLE
Incorrect config of PreferThisOrSelfMethodCallRector in rector_rules_overview.md

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/rector#6599]
# Bug Report
In the code example, the option `PreferThisOrSelfMethodCallRector::TYPE_TO_PREFERENCE` has a key `PHPUnit\\Framework\\TestCase`.
https://github.com/rectorphp/rector/blob/398f8f8197ea293163b3af426b425111745a3bfc/rules/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php#L52-L55
But in the `rector_rules_overview.md`, the key `PHPUnit\\Framework\\TestCase` disappeared.
https://github.com/rectorphp/rector/blob/398f8f8197ea293163b3af426b425111745a3bfc/docs/rector_rules_overview.md#L2280-L2285

**Comment by TomasVotruba** [comment]
Hi, thank for reporting. We use Rule Doc Generator from Symplify here, so the right place to report it is:
https://github.com/symplify/symplify

Could you move it there?

**Comment by zingimmick** [comment]
> Hi, thank for reporting. We use Rule Doc Generator from Symplify here, so the right place to report it is:
> https://github.com/symplify/symplify
> 
> Could you move it there?

@TomasVotruba symplify/symplify#3441
