### ISSUE TITLE
[PHP80] Implementing \Stringable via extended class triggers error

### ISSUE THREAD

**Issue by annuh** [rectorphp/rector#6601]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 9953c4f59cd3ac1122d9d50461324e338cee725a          |

Please see the failing test here: https://github.com/rectorphp/rector-src/pull/541

Using `__toString()` in a class that implements `\Stringable` via a parent class triggers an error

```php
interface InterfaceClass extends \Stringable {
}

class SomeClass implements InterfaceClass
{
    public function __toString()
    {
        return 'I can stringz';
    }
}
```

https://getrector.org/demo/1ebf0593-2363-6a30-98d3-cd5737b4e205

## Expected Behaviour

This PHP code should be accepted AFAIK.

**Comment by TomasVotruba** [comment]
Thank you for great test case! :+1: 

I've added it in https://github.com/rectorphp/rector-src/pull/542
