### ISSUE TITLE
Give warning if Option::SKIP'd classes are not imported

### ISSUE THREAD

**Issue by NotionCommotion** [rectorphp/rector#6604]
# Feature Request

After Rector failed to ignore some rules after I configured it to do so, I initially thought it bug but then found it was purely user error on my part as I failed to import the classes.  Not a big deal, but it would have been nice to see some warning when running rector.

```php
    $parameters->set(Option::SKIP, [
        //https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md
        // Causes issues with Doctrine.
        FinalizeClassesWithoutChildrenRector::class => [
            __DIR__ . '/src/Entity',
        ],
        PrivatizeFinalClassPropertyRector::class => [
            __DIR__ . '/src/Entity',
        ],
    ]);
```
 
## Diff 

```diff
Attempted to load class "FinalizeClassesWithoutChildrenRector" from namespace "RectorPrefix20210725".
Did you forget a "use" statement for "Rector\Privatization\Rector\Class_\FinalizeClassesWithoutChildrenRector"?
```

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion.
This is actually external package from @symplify called skipper: https://github.com/symplify/symplify/tree/main/packages/skipper

Please open the issue there or even better the PR.
