### ISSUE TITLE
Add UpgradeStrictTypeDeclarationRector

### ISSUE THREAD

**Issue by NotionCommotion** [rectorphp/rector#6605]
# Feature Request

Add a new rector which performs the opposite of [downgradestricttypedeclarationrector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#downgradestricttypedeclarationrector).

 
## Diff 

```diff
+declare(strict_types=1);
```

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion. Seems ok to me, please send PR so we can have it in the core.

**Comment by NotionCommotion** [comment]
Would the appropriate place to locate it be to create a directory `Declare_` in https://github.com/rectorphp/rector/tree/main/rules/Php70/Rector and call the file StrictTypeDeclarationRector.php?

Any recommendations of existing code to follow or is https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp70/Rector/Declare_/DowngradeStrictTypeDeclarationRector.php as good as any?

**Comment by samsonasik** [comment]
I am not in front of PC, but I think you can use `FileWithoutNamespace` and `Namespace_` since it need to be in very first statement, check if first statement is Declare strict types, if no, add it.

**Comment by samsonasik** [comment]
@ NotionCommotion you can check this rule for reference for nodes to be used https://github.com/rectorphp/rector-src/blob/294bea2d1850fb65aca43119b7692932846f2d86/rules/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector.php#L76

**Comment by TomasVotruba** [comment]
> Any recommendations of existing code to follow or is https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp70/Rector/Declare_/DowngradeStrictTypeDeclarationRector.php as good as any?

I would use it as inspiration, just invert the logic.

Thne I'd follow @samsonasik suggestions :+1:

**Comment by sabbelasichon** [comment]
Rector is not PHP-CS-Fixer and vice versa. But as i am using PHP-CS-Fixer in every project either directly or behind the scenes with ecs, there is already a rule for that as far as i know.

**Comment by TomasVotruba** [comment]
Closing as feature is accepted, so we can focus on bugs and generic feature.

@NotionCommotion Feel free to send pull-reques to https://github.com/rectorphp/rector-src, we can review and add it to core :+1:
