### ISSUE TITLE
Syntax error unexpected 'a' (T_STRING)

### ISSUE THREAD

**Issue by artatum** [rectorphp/rector#6606]
# Question
Hello.
Win 10/Docker/Drupal 9
As said in the title when I run  
   rector process modules/custom/xxx --dry-run
 I get : 
Syntax error unexpected 'a' (T_STRING). I didn't find anything about this on Google, or here.
It's the first time I use rector, it's on a fresh install.
Any idea welcome.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
What is the output for `--debug`? 

We'll need the exact file this crashes on.

**Comment by artatum** [comment]
Nothing more.

**Comment by TomasVotruba** [comment]
We'll need a file to reproduce. We cannot do any fix without it.

**Comment by artatum** [comment]
Could you tell me what to do then ?

**Comment by TomasVotruba** [comment]
I'll try. I don't use Docker, so I can only help with default composer install.

```bash
composer require rector/rector --dev
vendor/bin/rector process src --debug
```

Then try to narrow scope it down to single diretory, where the error happens:

```bash
vendor/bin/rector process src/FirstDir --debug
vendor/bin/rector process src/SecondDir --debug
```

Then narrow scope it down to single file:

```bash
vendor/bin/rector process src/FirstDir/FirstFile.php --debug
vendor/bin/rector process src/FirstDir/SecondFile.php --debug
```

Then try to keep as few lines as possible in file - basically comment code in that file:

```php
vendor/bin/rector process src/FirstDir/FirstFile.php
```

Until the error disappears. When the errors disappears, it's in the commented line. That single line is what we look for.

**Comment by artatum** [comment]
Ok. I will do that. Thx for the steps.

**Comment by artatum** [comment]
I created one file called info.php, into /docroot containing 
<?php
phpinfo();
drupal_set_message("done");

I stil get [ERROR] syntax error, unexpected 'a' (T_STRING)
:(

**Comment by artatum** [comment]
Bingo ! It was my fault. :( 
A typo in rector.php. 
So I perfectly got 
[OK] Rector is done!
on my dummy file.
Thx for your help, precious. Have a great day.

**Comment by artatum** [comment]
Well, things changed : I just moved to another branch, went back, and rector doesn't work anymore.
I now get :  [ERROR] Unable to write in the "cache" directory (/tmp/rector/cache).
I created those directories, set them to 777. But it doesn't work.

**Comment by TomasVotruba** [comment]
> A typo in rector.php.

Congrats. Just curious, what was the typo? :)

> Unable to write in the "cache" directory (/tmp/rector/cache).

That seems like filesystem and Rector are running under different user. Try to use the same one.

**Comment by artatum** [comment]
A stupid comment (//) deleted on the wrong line.

**Comment by TomasVotruba** [comment]
> A stupid comment (//) deleted on the wrong line.

I see :+1: That happens, I've been there :). Maybe it would be helpful to have https://getrector.org/demo link next time. It's easier to spot these by somebody else.

> I'm under docker : how can I set the same user for both please ?

I'm not using Rector with Docker, so I'm not sure. This would be generic Docker issue IMO, unrelated to Rector.

Based on feedback from few issue reports, it might save you hours to use composer version over Docker one. It has much better support and I'm thinking of promoting it better. In the end Rector should be part of your project for long-term maintenance, same way PHPUnit is.

**Comment by artatum** [comment]
Sorry, I dont understand what you mean by  'use composer version over Docker one'. I'm using a global composer installed on my Win 10. Any action is mirrored into the container.

**Comment by TomasVotruba** [comment]
> 'use composer version over Docker one'.

No problem. I meant like this: https://github.com/rectorphp/rector#install

> I dont understand why it was working this morning, though.

That's one the toughest questoins :) access rights, cache and Windows can change very quickly...
Maybe @staabm might helps. Are you running Rector on Windows too?

**Comment by artatum** [comment]
I destroyed and rebuilt the container : everything is back !
I ran a first command and got a warning :  [WARNING] Your project requires min PHP version "7.4". Rector rules defined in your configuration require higher PHP version and will not run. Which php version is required for rector, and how can I set it plz ?

**Comment by staabm** [comment]
Sorry, I have no experince with docket

**Comment by samsonasik** [comment]
@artatum the warning is fine, that's just show you that some rector rules are require higher php version, you can try latest rector for more verbose warning message, and suggest to use `-vvv` to see what rules that require higher php version:

![Screen Shot 2021-08-02 at 21 30 47](https://user-images.githubusercontent.com/459648/127877934-0b4f13f4-2f89-4ead-b8b7-4117e12debd8.png)

see https://github.com/rectorphp/rector-src/pull/574

**Comment by artatum** [comment]
Is it this ? 
 * [8.0] RemoveUnusedPromotedPropertyRector

**Comment by samsonasik** [comment]
No need, or if you don't want to see the warning, you can include in the skip option:

```php
use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPromotedPropertyRector;

//...
    $parameters->set(Option::SKIP, [
        RemoveUnusedPromotedPropertyRector::class,
    ]);
```

**Comment by artatum** [comment]
do you mean edit rector.php ?

**Comment by samsonasik** [comment]
Yes. You can read the docs for it https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md

**Comment by samsonasik** [comment]
I am closing it as resolved.
