### ISSUE TITLE
Rector requires phpstan 0.12.93

### ISSUE THREAD

**Issue by devbanana** [rectorphp/rector#6608]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.42             |

I have phpstan 0.12.94 installed. However, when I attempt to install rector/rector with composer, it complains because it will not accept anything higher than phpstan 0.12.93. I've tried this on multiple projects.

## Minimal PHP Code Causing Issue

With phpstan 0.12.94 installed, running:

`composer require rector/rector —dev`

throws an error.

## Expected Behaviour

I should be able to install the package successfully.

**Comment by TomasVotruba** [comment]
Hi, this is expected, see `composer.json`: https://github.com/rectorphp/rector/blob/3bcd73b480947aad39a832578fa95dc039206dac/composer.json#L10

First, Rector needs to be tested and upgraded to newer PHPStan. In the past we had this version opened and it started to crash on PHPStan BC break. Now we got the safer way, to keep our users stable :)

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-src/pull/585

**Comment by enumag** [comment]
In case someone finds this issue later, it's still possible to force installation of newer phpstan than rector allows at the given moment. For instance at the time of writing latest rector requires phpstan 0.12.96 while the latest is 0.12.98. Yet I was still able to force it using this trick in composer.json:

```
        "phpstan/phpstan": "0.12.98 as 0.12.96",
        "rector/rector": "^0.11.52",
```

**Comment by enumag** [comment]
@TomasVotruba This might possibly be worth mentioning in the readme, what do you think?

On a side note do you think phpstan version might be open again after phpstan 1.0 is out which should hopefully be more stable and not cause bc breaks anymore?

**Comment by devbanana** [comment]
This is useful, thanks for sharing.

**Comment by TomasVotruba** [comment]
The issue is conflict in shared non-prefixed PHPParser namespace. Each project has their own, so it's a race condition issue.

**Comment by enumag** [comment]
@TomasVotruba Not sure I understand. You mean there is one PHPParser installed normally as phpstan dependency and another one bundled into rector? If that's the case then why does Rector contain a copy when the parser will be there as a dependency anyway? :thinking:

**Comment by enumag** [comment]
Ah yeah... rector's [vendor directory](https://github.com/rectorphp/rector/tree/main/vendor) contains non-prefixed nikic/php-parser as well as phpstan while also requiring them *again* as dependency... I understand that you need to require them in composer.json in order to prevent incompatible versions but imo they shouldn't be in the vendor directory.

**Comment by TomasVotruba** [comment]
That's does not solve the problem.

**Comment by TomasVotruba** [comment]
Ideal solution is to unpack PHPStan and merge it's `composer.json` to Rector's. That way their dependencies are shared. Still requires version lock.
