### ISSUE TITLE
Argument type declaration unnecessarily removed

### ISSUE THREAD

**Issue by devbanana** [rectorphp/rector#6611]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.42             |

I'm having an odd bug which I have been able to reproduce. If I enable Option::AUTO_IMPORT_NAMES, then enable the sets DowngradeTypedPropertyRector and DowngradeMixedTypeDeclarationRector, function arguments with the same type declaration as a property will be stripped of their typed declaration, and an `@param` will be added with type `mixed`.

See code example for more clarity.

## Minimal PHP Code Causing Issue

In `test.php`:

``` php
<?php
namespace First;
class SomeClass {}

namespace Second;
use First\SomeClass;

class AnotherClass
{
    private SomeClass $foo;

    public function bar(SomeClass $baz)
    {
    }
}

```

In `rector.php`:

``` php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\DowngradePhp74\Rector\Property\DowngradeTypedPropertyRector;
use Rector\DowngradePhp80\Rector\FunctionLike\DowngradeMixedTypeDeclarationRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::AUTO_IMPORT_NAMES, true);

    $services = $containerConfigurator->services();
    $services->set(DowngradeTypedPropertyRector::class);
    $services->set(DowngradeMixedTypeDeclarationRector::class);
};

```

Running command:

`vendor/bin/rector process test.php`

Gives output:

``` php
<?php
namespace First;
class SomeClass {}

namespace Second;
use First\SomeClass;

class AnotherClass
{
    /**
     * @var SomeClass
     */
    private $foo;

    /**
     * @param mixed $baz
     */
    public function bar($baz)
    {
    }
}

```

## Expected Behaviour

It should strip the property of its type declaration, but not the function argument.

So the output should be:

``` php
<?php
namespace First;
class SomeClass {}

namespace Second;
use First\SomeClass;

class AnotherClass
{
    /**
     * @var SomeClass
     */
    private $foo;

    public function bar(SomeClass $baz)
    {
    }
}
```

**Comment by samsonasik** [comment]
Could you create failing fixture PR for it? For multiple rules issue, you can create under https://github.com/rectorphp/rector-src/tree/main/tests/Issues

Thank you.
