### ISSUE TITLE
Different content preload.php between rector-src and rector prefixed

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6612]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main            |

@TomasVotruba it seems the `preload.php` are different between rector-src and rector prefixed, ref 

https://github.com/rectorphp/rector-src/blob/9d37638fce3f3c31b69196a41c1ab205d3d9a6ab/preload.php

vs 

https://github.com/rectorphp/rector/blob/92318a40f2f0921638996cc1c1212870d386748c/preload.php

is `preload.php` should be copied instead of re-run on 

https://github.com/rectorphp/rector-src/blob/9d37638fce3f3c31b69196a41c1ab205d3d9a6ab/build/build-rector-scoped.sh#L46

?

**Comment by samsonasik** [comment]
It possibly run from my local dev is different result with run in Github Action, if that correct, than next week the automated PR will make the `preload.php` same as run via Github Action.

**Comment by TomasVotruba** [comment]
You're right, they should be identical :+1: 

Originally this file was generated on release, but we started to use it in `rector/rector-src` in packages (e.g. `rector/rector-symfony`) for testing, where preload was needed too.
