### ISSUE TITLE
CountOnNullRector has very awkward syntax

### ISSUE THREAD

**Issue by devbanana** [rectorphp/rector#6616]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.43             |

Not entirely sure if this is a bug or not. But CountOnNullRector sometimes generates very awkward syntax.

The documentation says it'll turn `count($a)` into `count((array) $a)`, and this seems fine. But I'm running into something else.

## Minimal PHP Code Causing Issue

``` php
<?php

class Foo
{
    /**
     * @var string[]
     */
    private $bar;

    public function baz(int $count): bool
    {
        if (!isset($this->bar['something'])) {
            return false;
        }

        return count($this->bar['something']) === $count;
    }
}

```

## Expected Behaviour

[Here's a demo link](https://getrector.org/demo/1ebf59d9-e029-665c-ae6d-d7f414516252)

Note this only seems to happen on PHP 7.2.

``` diff
@@ -1,18 +1,18 @@
 <?php
 
 class Foo
 {
     /**
      * @var string[]
      */
     private $bar;
 
     public function baz(int $count): bool
     {
         if (!isset($this->bar['something'])) {
             return false;
         }
 
-        return (is_array($this->bar['something']) || $this->bar['something'] instanceof \Countable ? count($this->bar['something']) : 0) === $count;
+        return count((array) $this->bar['something']) === $count;
     }
 }

```

The expected result seems a lot cleaner, and indeed if I manually add the array cast, then CountOnNullRector doesn't execute.

**Comment by samsonasik** [comment]
iirc `@var string[]` means collection of string as non-associative array structure, so this rule needs to know if result is an array or countable to allow `count()` usage.

If you really sure that `$this->bar['something']` is an array, you can the property with `[][]`

```php
    /**
     * @var string[][]
     */
    private $bar;
```

see https://getrector.org/demo/1ebf59de-7448-6c30-aed4-dfbb49976de4

**Comment by devbanana** [comment]
> iirc `@var string[]` means collection of string as non-associative array structure, so this rule needs to know if result is an array or countable to allow `count()` usage.

Interesting, never knew that. I'm new to static typing.

But regardless, unfortunately that's not possible here. My array is actually mixed, having elements of different types. So it's not just an array of arrays.

I just think that generating this sort of one-line check is awkward. Also, if I already check for the existence of the element and therefore already know it is set, it shouldn't fire.

Even if I check like this:

``` php
        if (!isset($this->bar['something']) || !is_array($this->bar['something'])) {
            return false;
        }

        return count($this->bar['something']) === $count;
```

It still generates the same syntax.

**Comment by samsonasik** [comment]
The rule is checking to make it as safe as possible for the mixed typed you mentioned.

You can skip it if you think it is too much for your use case see https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md

**Comment by samsonasik** [comment]
closing as not an issue.
