### ISSUE TITLE
Rector converting long -> short array syntax does not generate a diff

### ISSUE THREAD

**Issue by gerritdrost** [rectorphp/rector#6618]
# Question
Hesitant to file this as a bug report because I just started learning rector and it might be pebkac. I couldn't find a rule that converts the long array-syntax (`array(1, 2, 3)`) to the short one (`[1, 2, 3]`), so I thought I'd give building a rector for it a try to get a better understanding of how rector works. So I wrote the rector, set up `rector.php` to include it, and made a file `test.php` containing code it should convert. When I run it, the rector modifies the relevant nodes, but then there is no diff.

#### Rector debug output
```
$ vendor/bin/rector process test.php --debug --clear-cache --dry-run
[parsing] test.php
[refactoring] test.php
    [applying] Utils\Rector\ArrayRector
[post rectors] test.php
[print] test.php
[print] test.php

                                                                                                                        
 [OK] Rector is done!  
```

#### Version info
```
$ php -v
PHP 7.4.22 (cli) (built: Jul 30 2021 01:42:53) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$ composer show | grep rector
rector/rector                        0.11.43   Prefixed and PHP 7.1 downgraded version of rector/rector
```

#### rector.php

```php
<?php

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Utils\Rector\ArrayRector;

return static function (ContainerConfigurator $containerConfigurator): void {
     $services = $containerConfigurator->services();
     $services->set(ArrayRector::class);
};
```

#### test.php

```php
<?php

$long = array(1, 2, 3);
$short = [1, 2, 3];
```

#### ArrayRector.php

```php
<?php

namespace Utils\Rector;

use PhpParser\Node;
use PhpParser\Node\Expr\Array_;
use Rector\Core\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

class ArrayRector extends AbstractRector
{
    /**
     * @return array<class-string<Node>>
     */
    public function getNodeTypes(): array
    {
        return [Array_::class];
    }

    /**
     * @param Array_ $node
     */
    public function refactor(Node $node): ?Node
    {
        if ($node->getAttribute('kind') !== Array_::KIND_SHORT) {
            $node->setAttribute('kind', Array_::KIND_SHORT);
            return $node;
        }

        return null;
    }

    /**
     * This method helps other to understand the rule and to generate documentation.
     */
    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition(
            'Change long array syntax to short array syntax.', [
                new CodeSample('array(1, 2, 3)', '[1, 2, 3]'),
            ]
        );
    }
}
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. You've just came across one of rules of php-parser.
It only checks for changed nodes and properties, not for attributes. Mainly for performance issues:

To let your rule know that something has changed, you can force php-parser to re-print it by setting original node to `null`:

```php
$node->setAttribute('origNode', null);
```

**Comment by gerritdrost** [comment]
Ah, that works. Thanks for the rapid response!

**Comment by TomasVotruba** [comment]
You're welcomed :+1:

**Comment by ivoba** [comment]
@gerritdrost do you have a final version of this Long to Short array Rector?
Would be awesome to have this in the Rules Overview.

**Comment by TomasVotruba** [comment]
Some cases are better handled on token level, like this one.

The rule to handle is via conding standard, resp. `ArraySyntaxFixer`: https://github.com/symplify/easy-coding-standard/blob/8c948c3a8a48e30a5ae7a8faa7c7fecdc8ec3336/config/set/common/array.php#L29

**Comment by TomasVotruba** [comment]
https://github.com/symplify/easy-coding-standard/blob/8c948c3a8a48e30a5ae7a8faa7c7fecdc8ec3336/config/set/common/array.php#L29
