### ISSUE TITLE
Implement DowngradeAbstractPrivateMethodInTrait for PHP8.0 downgrade (set)

### ISSUE THREAD

**Issue by Bl00D4NGEL** [rectorphp/rector#6619]
# Feature Request

Given that PHP 8.0 provides the possibility to make a private function of a trait abstract (to enforce implementation in "using" classes) we should consider this in our downgrading in the PHP 8.0 set.

Here's an example: [https://getrector.org/demo/1ebf775a-eb45-6f4c-9bfa-23266db0c3b9](https://getrector.org/demo/1ebf775a-eb45-6f4c-9bfa-23266db0c3b9)
 
## Diff 
I would be expecting to have an "empty" function instead when downgrading like so:
```diff
-abstract private function foobar();
+private function foobar() {};
```

It might be important to note, that the non-abstract function must have a function body to be syntactically correct, while the abstract-version must not.

The idea originates from [this](https://github.com/rectorphp/rector/issues/6613) issue.

**Comment by TomasVotruba** [comment]
Closed in https://github.com/rectorphp/rector-src/pull/615
