### ISSUE TITLE
Incorrect behavior of DowngradeSelfTypeDeclarationRector

### ISSUE THREAD

**Issue by devbanana** [rectorphp/rector#6620]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebf7a50-60d7-6c04-8880-e1714318ce44

```php
<?php

final class DemoFile
{
    public function run(): self
    {
        return $this;
    }
}
```

### Responsible rules

* `DowngradeSelfTypeDeclarationRector` within `DowngradeSetList::PHP_74`

## Expected Behavior

self as return type is supported since PHP 7.0. Indeed, if I use ReturnTypeDeclarationRector from PHP 7.0+, it adds self. See this link:

https://getrector.org/demo/1ebf7a3e-c776-68aa-abbe-8fb99fc0811f

So this leads to a certain kind of inconsistency. if I run ReturnTypeDeclarationRector on PHP 7.3 code, it adds self. if then I happen to run the PHP7.4 downgrade set list, which includes DowngradeSelfTypeDeclarationRector, it removes self again.

**Comment by samsonasik** [comment]
I think it can be moved to DowngradePhp70 then, could you create PR for it? Thank you.

**Comment by devbanana** [comment]
Hi @samsonasik , I certainly can, but currently it is under the namespace `Rector\DowngradePhp74`. For consistency it'd then need to be in `Rector\DowngradePhp70`, which would break backwards compatibility. How would you handle that? Unless we keep a copy within PHP74 and deprecate it.

**Comment by samsonasik** [comment]
I think keep it under `DowngradePhp74` is incorrect as it is a bug, rector will show that class not exists for it so user can find and locate to the correct service if using individual service:

https://github.com/rectorphp/rector-src/blob/a8b01f217b9702f7dd6e485f84fe46a6dabe0d86/src/DependencyInjection/CompilerPass/VerifyRectorServiceExistsCompilerPass.php#L30

**Comment by TomasVotruba** [comment]
Closed in https://github.com/rectorphp/rector-src/pull/623
