### ISSUE TITLE
CompleteDynamicPropertiesRector plus RenamePropertyToMatchTypeRector while using constructor property promotion results in spurious public property

### ISSUE THREAD

**Issue by devbanana** [rectorphp/rector#6621]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebf8869-75b8-6a34-a0bb-ab4b7d002017

```php
<?php

final class DemoFile
{
    public function __construct(private \DateTimeImmutable $date)
    {
    }

    public function run(): string
    {
        return $this->date->format('l, F j, Y');
    }
}
```

### Responsible rules

* `CompleteDynamicPropertiesRector`
* `RenamePropertyToMatchTypeRector`

## Expected Behavior

Property should not be made public.

**Comment by samsonasik** [comment]
Could you create failing fixture PR for it? For multiple rules issue, you can create under https://github.com/rectorphp/rector-src/tree/main/tests/Issues

Thank you.
