### ISSUE TITLE
PHP tags being added to blade files

### ISSUE THREAD

**Issue by jessarcher** [rectorphp/rector#6622]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.37 to current (0.11.45)                                   |

Since version 0.11.37, Rector is adding unnecessary PHP tags (`<?php ?>`) when writing Blade files (`*.blade.php`). This seems to apply to all Rector tasks, as long as they make a change to the file.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebf8f66-caa7-619a-ba58-0ba12154890e

```php
@extends('layout')

<?php 
// Some code to trigger rector to write the file
echo isset($value) ? $value : 10;
?>

@section('content')
    Test
@endsection
```

After running `TernaryToNullCoalescingRector`:

```php
<?php

?>
@extends('layout')

<?php 
// Some code to trigger rector to write the file
echo $value ?? 10;
?>

@section('content')
    Test
@endsection
<?php 
```

## Expected Behaviour

```php
@extends('layout')

<?php 
// Some code to trigger rector to write the file
echo $value ?? 10;
?>

@section('content')
    Test
@endsection
```

**Comment by jessarcher** [comment]
Another scenario where things get mixed up is when the short echo tag is used, even when the code inside the tag is not being refactored.

See https://getrector.org/demo/1ebf8f80-cd30-6938-9b73-5949e6e64f28


```php
@extends('layout')

<?php 
// Some code to trigger rector to write the file
echo isset($value) ? $value : 10;
?>

@section('content')
    The value is <?= $something ?>
@endsection
```

Result:

```php
<?php

?>
@extends('layout')

<?php 
// Some code to trigger rector to write the file
echo $value ?? 10;
?>

@section('content')
    The value is <?php 
<?= $something ?>

?>
@endsection
<?php 
```

This also worked fine in 0.11.36 but broke in v0.11.37 onward.

**Comment by samsonasik** [comment]
Could you create failing fixture PR for it? For non-specific rules issue, you can create under https://github.com/rectorphp/rector-src/tree/main/tests/Issues

Thank you.

**Comment by jessarcher** [comment]
@samsonasik, sure thing! I've created a PR at https://github.com/rectorphp/rector-src/pull/629

Problem is, my test passes! For some reason it's not replicating the above issue. Any ideas?

**Comment by samsonasik** [comment]
The demo site is a released version, could you try `dev-main` version?
