### ISSUE TITLE
Add AbstractTypoScriptRector.php to downgrade config 

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6624]
Related issue https://github.com/sabbelasichon/typo3-rector/issues/2510

**Comment by samsonasik** [comment]
@sabbelasichon re-open as it seems still not yet resolved:

https://github.com/rectorphp/rector/blob/33fe0e38c0d2eba9227a5d6a5448fa10085f46a6/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php#L23

vs

https://github.com/rectorphp/rector/blob/33fe0e38c0d2eba9227a5d6a5448fa10085f46a6/vendor/helmich/typo3-typoscript-parser/src/Parser/Traverser/Visitor.php#L19
