### ISSUE TITLE
CI Usage & Baseline Functionality

### ISSUE THREAD

**Issue by AlexandruGG** [rectorphp/rector#6626]
# Question
Hello @TomasVotruba,

I am trying to figure out if Rector is designed to be used in CI with the `--dry-run` option so as to "guard against" the need for future refactoring. For example, applying the `SetList::DEAD_CODE` and refactoring the code once is fine, but nothing prevents someone from introducing _new_ "dead code" in a project.

I'm aware there are other tools which might be potentially better for enforcing these things, like PHP CodeSniffer, php-cs-fixer, simplify/easy-coding-standard etc. However, I am just curious if you think Rector is also a viable option with the dry run flag.

One of the main things that would prevent its usage as such in some projects is lack of a **"baseline" functionality** (as far as I can see). Do you think this would be something feasible to implement for Rector? To clarify what I'm referring to, it would work similarly to the [PHPStan Baseline](https://phpstan.org/user-guide/baseline): the file would contain changes that Rector should not try to apply or suggest.

**Comment by TomasVotruba** [comment]
Hi, thanks for deep question like this 👍 

2 notes that comes to my head:

* Rector is change-only tool; if the code is wrong but there are 2+ ways to fix it, its jobs for static analysis 
* https://getrector.org/blog/2020/10/05/how-to-make-rector-contribute-your-pull-requests-every-day

 I have couple of answers ready, depending on your exact goal. Could you share minimal example how would you like to Rector help you in CI? Real and small PHP code example is the best.

**Comment by AlexandruGG** [comment]
Thank you for the quick response!

Your first point makes sense, I suspected that was the case.

The article was helpful, it gave me an idea of how to do what I want. Event though I won't want the CI to automatically make a commit for me, I'm thinking I could set up a workflow which only runs Rector on the files changed (git diff) in that PR, with the "dry run" option. Then as the developer I can see apply the proposed changes if appropriate.

I will give that a shot and see how it goes, thanks for the help!

**Comment by TomasVotruba** [comment]
> Then as the developer I can see apply the proposed changes if appropriate.

This is a matter of habbit. I understand it feels weird that some tools is writing code. When we run Rector first on our code base, I was a bit affraid that it will change code the way it will pass tests silently and crash on production :)

~2 years later, we have 261 rules that run on very commits in CI that we never have to worry again. Thanks to delegating "best practise coding" to Rector, I actually learned to think about design and logic than specific imlementation. I simply create code that works and Rector turns it into best form possible.

Good luck!
