### ISSUE TITLE
Incorrect behavior of RemoveUselessParamTagRector, RemoveUselessReturnTagRector

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6627]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebfb51c-9f0b-6da2-9550-351019fc2ba8

```php
<?php

class X {
	/**
	 * @param Closure(Identity): bool $filter
	 *
	 * @return mixed[]|null
	 */
	public function test(Closure $filter): ?array {
    }
}
```

### Responsible rules

* `RemoveUselessParamTagRector`

* `RemoveUselessReturnTagRector`

## Expected Behavior

no change

**Comment by TomasVotruba** [comment]
This is feature, not a bug. From PHPStan point of view these types are quivalent.

**Comment by enumag** [comment]
No they aren't.

For the array PHPStan reports this if the type is not specified:

```
Method X::test() return type has no value type specified in iterable type array.
```

For the closure if I remove the annotation then PHPStan cannot properly validate the parameters to report issues such as this:

```
Parameter #1 $ of closure expects DateTimeImmutable, string given.
```

Compare
https://phpstan.org/r/e6a166d5-4d50-4d14-aa42-e0f2ee22f614
and
https://phpstan.org/r/3b395d02-68a5-4748-a23c-279a3bc6c455

**Comment by TomasVotruba** [comment]
Not sure what what the closure is for.

**Comment by TomasVotruba** [comment]
Not sure what what the closure is for.

**Comment by enumag** [comment]
Okay let me give you a more real world example. Check this code on PHPStan:

https://phpstan.org/r/fcf58568-970b-4b29-af59-2e34090d1d36

It correctly reports that the Closure I passed has wrong type.

Now I put the same code into rector:

https://getrector.org/demo/1ebfb58f-bb7c-61b2-95b9-a1dd32a8b9c0

No idea why it highlights unchanged lines in the diff, but that's a separate issue. As you can see Rector decided it's alright to remove the phpdoc specifying the closure type.

So now I pass the "fixed" code back into PHPStan:

https://phpstan.org/r/da12f0fc-9752-4f4b-b100-f01702d500e7

But now even though the code is still wrong PHPStan doesn't report the problem because the closure is not annotated anymore.

**Comment by TomasVotruba** [comment]
That does not help much. I'm checking return array but your pasting closure as param. Those are 2 different rules.

**Comment by enumag** [comment]
No it doesn't appear only on the specific combination. Alright I'll create two separate issues then.

**Comment by enumag** [comment]
Separated as #6628 and #6629. ;-)
