### ISSUE TITLE
Incorrect behavior of RemoveUselessParamTagRector

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6628]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebfb5ad-f7dc-6256-9a30-e306f3eb8c49

```php
<?php

declare(strict_types = 1);

class X {
	/**
	 * @param int[] $list
	 * @param Closure(int): bool $filter
	 *
	 * @return int[]
	 */
	static function filterNumbers(array $list, Closure $filter): array {
		$result = [];
		foreach ($list as $value) {
			if ($filter($value)) {
				$result[] = $value;
			}
		}

		return $result;
	}
}

X::filterNumbers([1], fn (string $x) => $x > 0);
```

### Responsible rules

* `RemoveUselessParamTagRector`

## Expected Behavior

No change. The code is in fact bugged - on the last line I'm passing a closure with wrong typehint. Thanks to the annotation PHPStan correctly reports the bug:

https://phpstan.org/r/dc85c026-6ed6-4db0-9fff-c280b27da648

However if I remove the annotation as Rector suggests then PHPStan is unable to detect the bug:

https://phpstan.org/r/ee6491f5-19a4-4a5c-959b-93b4e5b77f27

**Comment by TomasVotruba** [comment]
The first parameter is relevant to this or it can be removed?

**Comment by enumag** [comment]
I see. Here is a simplified version: https://getrector.org/demo/1ebfb5f9-a1f1-6412-b1e0-b75ba4616957

**Comment by TomasVotruba** [comment]
Thanks :+1: We'll need a test case PR

**Comment by TomasVotruba** [comment]
@enumag Thanks :+1: 

I think it should be more visible. It's been there around 6 months and people still prefer to write long reports manually instead of using it  :D

**Comment by enumag** [comment]
In my case it was a matter of not being completely sure if you would agree it's a bug so I wanted to open an issue to discuss it first. And in case of the isset I was pretty sure the behavior was wrong but wasn't too sure what's correct.

Perhaps you might want to just remove the create issue button and push ppl to always immediately create a PR with a test or making it clear there that you prefer for them to create the test immediately rather than an issue even if it's not entirely correct at first?

**Comment by TomasVotruba** [comment]
> Perhaps you might want to just remove the create issue button and push ppl to always immediately create a PR with a test or making it clear there that you prefer for them to create the test immediately rather than an issue even if it's not entirely correct at first?

Sounds like a very good idea :+1: Why I didn't thought of it before? Thanks!

Not everytime it's possible to create a test case in the right location (e.g. when there is combination of 2+ rules), but if there is an option, it should be the default choice.
