### ISSUE TITLE
Incorrect behavior of RemoveUselessReturnTagRector

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6629]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebfb5b9-2751-6e90-a531-931835850793

```php
<?php

class X {
	/**
	 * @return mixed[]|null
	 */
	public function test(Closure $filter): ?array {
        return [];
    }
}
```

### Responsible rules

* `RemoveUselessReturnTagRector`

## Expected Behavior

No change. If the annotation is removed PHPStan starts to complain:

https://phpstan.org/r/16ec5e3f-9292-49ee-a0dd-dc8648485e07

**Comment by TomasVotruba** [comment]
This is the one I though you talked about :). These are identical, just PHPStan rule is looking for docs comparison

**Comment by TomasVotruba** [comment]
I'm aware, thanks. We have this ignored, because using docblock to add already present type forces devs to write useless code.

**Comment by enumag** [comment]
All good. :-) I just realized I can change my annotations to use `array<string, mixed>` instead which makes PHPStan happy and Rector leaves it there. So I'll change them in my code tomorrow.
