### ISSUE TITLE
Incorrect behavior of IssetOnPropertyObjectToPropertyExistsRector

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6630]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebfb663-df6b-697c-ac22-45396c070a76

```php
<?php

declare(strict_types = 1);

function x(stdClass $x) {
	if (isset($x->property)) {
        
    }
}
```

### Responsible rules

* `IssetOnPropertyObjectToPropertyExistsRector`

## Expected Behavior

The "fixed" code will trigger 

```
PHP Notice:  Undefined property: stdClass::$property in ...
```

if the property doesn't exist.

**Comment by TomasVotruba** [comment]
Thanks :+1: We'll need a failing fixture for this rule.

Hint: try "create a test" button on demo link
