### ISSUE TITLE
Incorrect behavior of FixClassCaseSensitivityNameRector

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6631]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebfb65a-6f97-6fd2-8302-49f3956ff581

```php
<?php

declare(strict_types = 1);

namespace X {
    class Y {
    }

    function y() {
        echo 'test';
    }
}

namespace Test {
	use function \X\y;
    
    y();
}
```

### Responsible rules

* `FixClassCaseSensitivityNameRector`

## Expected Behavior

No change expected. I'm not using the class but the function.

**Comment by enumag** [comment]
And yes there is a real library with such case:
https://github.com/amphp/postgres/blob/02d367fb2a8c8d870a0af9c5a767ce6752542658/src/Pool.php#L17
https://github.com/amphp/postgres/blob/02d367fb2a8c8d870a0af9c5a767ce6752542658/src/functions.php#L56

**Comment by TomasVotruba** [comment]
Thanks, this should indeed work :+1: 
We'll need a test case PR with this fixture.
