### ISSUE TITLE
`NullsafeOperatorRector` crash

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#6632]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.47   |

When having the following code the `NullsafeOperatorRector` crashes. I am not exactly sure why, but left a demo to show it.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebfc1d2-6817-6c7a-9757-fbafc5b16667

## Expected Behaviour

That it doesn't crash 👍

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by olivernybroe** [comment]
Yeah, just got a bit lazy after creating two other bug reports for this one 😅 

I'll do it later 👍
