### ISSUE TITLE
`RenameReturnTypeClass` and `RenameParameterTypeClass` rectors

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#6633]
# Feature Request
I suggest the addition of two new rectors.
One for migrating return types of a class into another class and another one for doing the same, but with parameters.

The reason for this is, sometimes you might have a class which implements an interface and you would like every method to return this interface instead of the implementation or use it as the parameters.

I suggest the following config
```php
$services->set(RenameReturnTypeClass::class)
    ->call('configure', [[
        RenameReturnTypeClass::OLD_TO_NEW_CLASSES => [
            'App\MyClass' => 'App\MyClassInterface',

        ],
]]);
```

 
## Diff 

```diff
-function works(): MyClass
+function works(): MyClassInterface
{
	return new MyClass();
}
```

```diff
-function works(MyClass $param): void
+function works(MyClassInterface $param): void
{
}
```

**Comment by TomasVotruba** [comment]
Hi, this is already covered by rename class Rector.

If you need to limit this only to param/return types, we might accept it to "Transform" rules.

**Comment by olivernybroe** [comment]
@TomasVotruba Yeah so the issue with rename class is that it renames the class everywhere, however in my situation I wanna rename the class to the interface, so that of course cannot work inside the body of the method.

So yes, I guess it more belongs under `Transform` rules.

**Comment by TomasVotruba** [comment]
> Yeah so the issue with rename class is that it renames the class everywhere, however in my situation I wanna rename the class to the interface, so that of course cannot work inside the body of the method.

I think interfaces are protected. So this should not happen:

```diff
-new SomeClass()
+new SomeInterface()
```

If it does, it's a bug

**Comment by olivernybroe** [comment]
@TomasVotruba Ah nope you are totally right, that solves my issue, thanks man!

**Comment by TomasVotruba** [comment]
>  Ah nope you are totally right, that solves my issue, thanks man!

Glad it works :+1: 

Let me know if there are some edge-cases we forgot to cover :hugs:
