### ISSUE TITLE
Ternary to nullsafe

### ISSUE THREAD

**Issue by raoz** [rectorphp/rector#6634]
# Feature Request

Currently NullsafeOperatorRector converts things to nullsafe operator in the case of `if`, but a common pattern is to use ternary
(in fact, the downgrade rector downgrades nullsafe operator to a ternary.

The ternary case should also be handled.

 
## Diff 

```diff
- $b = $a !== null ? $a->getB() : null;
+ $b = $a?->getB();
```

**Comment by samsonasik** [comment]
Could you create a PR for it? Thank you.
