### ISSUE TITLE
noRector annotation conflict with PhpdocToCommentFixer

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6638]
There is a drawback with using the `@noRector` annotation which I'd like to show you and discuss. Not quite sure what is the best solution but I think you should be aware of this.

Basically I need to ignore a specific rector on one specific line. So according to the [documentation](https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md#in-a-file) I added this just above the line:

```
/** @noRector RectorClassName */
```

Now however when I run ECS, the `PhpCsFixer\Fixer\Phpdoc\PhpdocToCommentFixer` changes this to:

```
/* @noRector RectorClassName */
```

Which doesn't work for rector. I also tried changing it to this but rector doesn't recognize it either:

```
// @noRector RectorClassName
```

Would you be willing to make some change to not conflict with this fixer?

**Comment by enumag** [comment]
I also tried moving the annotation to the docblock of the method but that doesn't seem to work either.

**Comment by TomasVotruba** [comment]
This looks like a bug in `PhpdocToCommentFixer` fixer.

> Would you be willing to make some change to not conflict with this fixer?

Any improvement is welcomed :+1:

**Comment by enumag** [comment]
> This looks like a bug in PhpdocToCommentFixer fixer.

It isn't. The problem was discussed in [this issue](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3611) and the resolution is that docblocks (commens beginning with `/**`) should only appear on structural elements and this behavior is intentional.

By the way for comparison PHPStan allows `// @phpstan-ignore-next-line`.

**Comment by TomasVotruba** [comment]
Any improvement is welcomed :+1:

**Comment by enumag** [comment]
Thanks for solving the phpstan issue and merging it! :+1: 

I think this wraps up the series of issues I encountered with Rector for now. Can I nag you for a release with all the fixes? :-P

**Comment by TomasVotruba** [comment]
Sure :) should be in next 1-3 days.
