### ISSUE TITLE
Second run is not any faster

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6639]
# Question

So PHPStan, Psalm and ECS all have this cool feature where the results are cached and a second run only analyzes the files that were changed since the previous run. This helps a lot because the first run of any of these tools can easily take a few minutes to finish but the second run is very fast. (If nothing changed at all then second run only takes a few seconds for all 3 tools.)

What I'm surprised to see is that this isn't the case with Rector. First run of Rector (after deleting it's cache directory) took 5 and a half minutes on my project. Then I tried running it again (leaving it's cache directory intact) and it took roughly the same amount of time (a few seconds more than the first run).

I can think of three possible reasons:
1. Somehow this feature isn't possible with Rector.
2. This feature is possible, just not implemented.
3. This feature is implemented but is broken (for me at least) due to a bug.

Which one is correct? :thinking: I kind of suspect it's the third but can't be certain.

**Comment by TomasVotruba** [comment]
Hi, currently there is no cache except for kernel build. The 2) is the closest.

For every test there is a new kernel build. This can be seen on tests, that take ~6 mins or first run, then ~1-2 minutes on second run.

**Comment by enumag** [comment]
I see. That's a quite large drawback and in fact makes me a reluctant from adding Rector to my CI since everything else there is quite fast (mainly due to such caches) and Rector would be by far the slowest job in the pipeline. Well consider it a feature request then. Unfortunately this sounds like a relatively large task so I can't contribute a solution.

**Comment by TomasVotruba** [comment]
Indeed, caching is hard :+1:

**Comment by enumag** [comment]
You clearly have previous experience with this from ECS though. I believe this would massively improve the DX of Rector. Even more so than parallel run in fact and I suspect this is in fact easier than parallel. ;-)

**Comment by TomasVotruba** [comment]
If I knew the way, it would be done :) it's rather complex to work with AST caching

**Comment by enumag** [comment]
I believe PHPStan had the same complication so I used git blame to find the commit where PHPStan first added this feature: https://github.com/phpstan/phpstan-src/commit/b0f8d3fbc35f6f1288291cdec61c2f365ab201ab

It seems that the key is that AnalyserResult also returns an array of all the dependencies. The actual collecting of the dependencies was later moved out to separate class called [DependencyResolver](https://github.com/phpstan/phpstan-src/blob/f7250dbe9b23415f02961edc5f34e3f084e2b659/src/Dependency/DependencyResolver.php) and is indeed rather complex. Although perhaps you might be able to reuse the code from PHPStan since you're using it internally anyway?

**Comment by TomasVotruba** [comment]
Yes, I've used the very same approach, but could not make it to useful result.

**Comment by enumag** [comment]
What was the issue in your case? The cache invalidation was unreliable? In PHPStan works well from my experience. Perhaps it will help you if you ever try solving this.

**Comment by TomasVotruba** [comment]
I don't remember exactly, it's been ~6 months since I last looked into this.

**Comment by mssimi** [comment]
@enumag I have tried to solve not working cache, I have found what is causing that, provided failing test, provided implementation, still for @TomasVotruba, that was not enough, so I gave up and patched that in vendor.

Here you can find out more https://github.com/rectorphp/rector-src/pull/346

**Comment by enumag** [comment]
@mssimi Yeah have to agree with you there. Being requested to write tests when there are no tests for the original implementation really sucks. Can't blame you for using a patch instead. Thanks for linking the issue.

**Comment by enumag** [comment]
@mssimi The one thing I find kinda odd about your PR is that it only removes code without adding any. I think this is why @TomasVotruba got suspicious of it and wasn't willing to merge it. A proper failing test PR should just modify an existing test case or add a new one without changing anything in the codebase outside of tests. :thinking:

**Comment by mssimi** [comment]
@enumag I have provided failing test only, after that I was asked to implemented and since I actually removed faulty method, I had to also remove that test.

**Comment by mssimi** [comment]
And since I squashed commits, it is not present in that MR anymore.
