### ISSUE TITLE
DateTimeToDateTimeInterfaceRector should work only on PHP-native DateTime classes

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector#6641]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.47 |

`DateTimeToDateTimeInterfaceRector` breaks contracts for `DateTime` child classes.

## Minimal PHP Code Causing Issue

Imagine you use [`nesbot/carbon`](https://packagist.org/packages/nesbot/carbon) and have custom `DateTime` class:

```
class DateTime extends Carbon
{
    public function getDateTimeDBFormat(): ?string
    {
        return $this->format('Y-m-d H:i:s');
    }
}
```

then you use it somewhere:

```
class Foo
{
    public static function bar(?DateTime $datetime)
    {
        // ...
    }
}
```

Rector proposes such changes:

```diff
 class Foo
 {
-    public static function bar(?DateTime $datetime)
+    /**
+     * @param \DateTime|\DateTimeImmutable|null $datetime
+     */
+    public static function bar(?\DateTimeInterface $datetime)
     {
         // ...
     }
 }
```

which is not correct since `DateTimeInterface` does not satisfy `DateTime::getDateTimeDBFormat()` contract.

## Expected Behaviour

`DateTimeToDateTimeInterfaceRector` should refactor signatures only if argument's type is `\DateTime`, not its sub-class which might have wider API than `DateTimeInterface`.

Let me know if you need reproducer repo, but I think example above is clear enough.

**Comment by TomasVotruba** [comment]
Thank you for your report!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by Wirone** [comment]
@TomasVotruba I've created test case nad provided fix, but I need confirmation if it's OK. Time to sleep 😴

**Comment by Wirone** [comment]
@TomasVotruba is it possible to release new version with this fix? We're also interested in #6642 and since we're on code review stage it would allow us to update Rector and re-enable 2 currently disabled rectors 🙂

**Comment by TomasVotruba** [comment]
Sure, it's one the way: https://github.com/rectorphp/rector-src/releases/tag/0.11.48

**Comment by vinceAmstoutz** [comment]
Sorry for the digging but after several searches I couldn't find which rule to activate on rector to change `DateTime `to `DateTimeImmutable ` on my project, e.g. :

```php
-    public static function bar(?DateTime $datetime)
+    public static function bar(?\DateTimeInterface $datetime)
     {
         // ...
     }
 }
```
