### ISSUE TITLE
Incorrect behavior of IssetOnPropertyObjectToPropertyExistsRector

### ISSUE THREAD

**Issue by puniserv** [rectorphp/rector#6642]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebfeb0e-9d03-6a82-bb3e-7540d34765b1

```php
<?php

final class DemoFile
{
    public function getName(\stdClass $result): Name
    {
        if (!isset($result->name) || !is_string($result->name)) {
            throw new \RuntimeException('name is mising/invalid');
        }
        return new Name(
            $result->name
        );
    }
}
```

### Responsible rules

* `IssetOnPropertyObjectToPropertyExistsRector`

## Expected Behavior

isset on stdClass unknown property is required to avoid NOTICE error.

**Comment by samsonasik** [comment]
it should already fixed by https://github.com/rectorphp/rector-src/pull/659

Please try latest "rector/rector": "dev-main"

**Comment by puniserv** [comment]
Now it's working.

**Comment by Wirone** [comment]
@samsonasik @TomasVotruba on a side note - what's the purpose of `IssetOnPropertyObjectToPropertyExistsRector`? What problem does it solve? Because rector's PHPDoc points to https://3v4l.org/TI8XL which compares two different things (`isset()` checks it if exists and is not `null` while `property_exists()` only checks property's presence). I don't see the real value of this particular rector, code after refactorization is less readable 🤔

**Comment by TomasVotruba** [comment]
Basically narrow scope. Property exists check if property exists, the isset checks much more

**Comment by TomasVotruba** [comment]
The linked 3v4l.org example on known public property should be changed to not null compare, as you say.

**Comment by Wirone** [comment]
@TomasVotruba yeah, but this rector changes `isset($this->x)` to `property_exists($this, 'x') && $this->x !== null` which is basically the same, but less readable. Other null-like values (empty string, 0) are [handled in the same way](https://3v4l.org/mpa6n). So IMO this rector does not simplify or improve the code, but makes it more complicated.

**Comment by TomasVotruba** [comment]
That's should be improved, agreed.
