### ISSUE TITLE
Incorrect behavior of ForeachItemsAssignToEmptyArrayToAssignRector, RemoveDoubleAssignRector

### ISSUE THREAD

**Issue by puniserv** [rectorphp/rector#6643]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebfeb2a-ee84-6d9a-95af-1dfef4365940

```php
<?php

final class DemoFile implements \IteratorAggregate
{
    private array $items;
    
    public function __construct()
    {
        $this->items = [new \stdClass()];
    }
 
    public function getIterator(): \ArrayIterator
    {
        return new \ArrayIterator($this->items);
    }
    
    public function getItems(): array
    {
        $items = [];
        foreach($this as $item) {
        	$items[] = $item;
        }
        return $items;
    }
}
```

### Responsible rules

* `ForeachItemsAssignToEmptyArrayToAssignRector`

* `RemoveDoubleAssignRector`

## Expected Behavior

This inspection should be skipped on Iterator|IteratorAggregate classes

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
For multiple rules issue, you can create test case under https://github.com/rectorphp/rector-src/tree/main/tests/Issues
