### ISSUE TITLE
Incorrect behavior of RemoveParentCallWithoutParentRector when using @mixin

### ISSUE THREAD

**Issue by devbanana** [rectorphp/rector#6650]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

This is a very odd issue. But basically, phpstan has the ability to “mix in” some class into another class. It supports the `@mixin` annotation. [See documentation.](https://phpstan.org/writing-php-code/phpdocs-basics#mixins)

But if I use a class that uses this feature, into another class that extends some parent, it removes the parent call. Yes, I tracked it down to this `@mixin` annotation.

Unfortunately I can't reproduce it in the rector-src repository, but I can in the demo site.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec00fd8-c437-693e-ab69-6b0f3408746f

```php
<?php

declare(strict_types=1);

abstract class ParentClass
{
    public function doSomething(): void
    {
        echo "I am doing something\n";
    }
}

final class Foo extends ParentClass
{
    public function doSomething(): void
    {
        echo "I am doing more things\n";
        parent::doSomething();
    }

    public function doSomethingElse(): void
    {
        new Bar();
    }
}

/**
 * @mixin \stdClass
 */
class Bar
{
}
```

### Responsible rules

* `RemoveParentCallWithoutParentRector`

## Expected Behavior

Should be unchanged.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by devbanana** [comment]
Hi @TomasVotruba , I'd love to but like I said in the issue, I can't reproduce it in rector-src, only on the demo site and in my local repository. I wonder if it has something to do with how Rector is downgraded from PHP 8 on release.

**Comment by samsonasik** [comment]
possibly already fixed at https://github.com/rectorphp/rector-src/pull/711 . Please try "rector/rector": "dev-main"

**Comment by devbanana** [comment]
Thanks, I think that did the trick.
