### ISSUE TITLE
Scoper build error

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6652]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

After PR https://github.com/rectorphp/rector-src/pull/721  scoper rector got error:

```bash
PHP Fatal error:  Declaration of RectorPrefix20210820\Doctrine\Inflector\GenericLanguageInflectorFactory::withSingularRules($singularRules, $reset = false) must be compatible with RectorPrefix20210820\Doctrine\Inflector\LanguageInflectorFactory::withSingularRules($singularRules, $reset = false): RectorPrefix20210820\Doctrine\Inflector\LanguageInflectorFactory in /home/runner/work/rector/rector/standalone/vendor/rector/rector/vendor/doctrine/inflector/lib/Doctrine/Inflector/GenericLanguageInflectorFactory.php on line 8
5
Fatal error: Declaration of RectorPrefix20210820\Doctrine\Inflector\GenericLanguageInflectorFactory::withSingularRules($singularRules, $reset = false) must be compatible with RectorPrefix20210820\Doctrine\Inflector\LanguageInflectorFactory::withSingularRules($singularRules, $reset = false): RectorPrefix20210820\Doctrine\Inflector\LanguageInflectorFactory in /home/runner/work/rector/rector/standalone/vendor/rector/rector/vendor/doctrine/inflector/lib/Doctrine/Inflector/GenericLanguageInflectorFactory.php on line 8
```

It seems multi rules usage.

**Comment by samsonasik** [comment]
The `LanguageInflectorFactory` has `self` back: 

https://github.com/rectorphp/rector/blob/0ff3bb0f7283ff87074b291af8e9bb57cf76f7ab/vendor/doctrine/inflector/lib/Doctrine/Inflector/LanguageInflectorFactory.php#L17

but its children doesn't have it:

https://github.com/rectorphp/rector/blob/0ff3bb0f7283ff87074b291af8e9bb57cf76f7ab/vendor/doctrine/inflector/lib/Doctrine/Inflector/GenericLanguageInflectorFactory.php#L27

possibly due the children originally returns `LanguageInflectorFactory` class name, not `self`.

**Comment by samsonasik** [comment]
@TomasVotruba I tried to remove `self` return when child already has no return type at https://github.com/rectorphp/rector-src/pull/725 but still error.

I tried both rules:

```
- Rector\DowngradePhp74\Rector\ClassMethod\DowngradeCovariantReturnTypeRector
- Rector\DowngradePhp80\Rector\ClassMethod\DowngradeStaticTypeDeclarationRector
```

but it is working it doesn't remove child's return:

![Screen Shot 2021-08-20 at 23 07 38](https://user-images.githubusercontent.com/459648/130262068-4984919f-8616-4ef7-bf90-6f82422a876e.png)

Do you think the solution is exclude vendor for it?

**Comment by samsonasik** [comment]
Try running directly on the vendor source seems got the following output:

```diff
-    final public function withPluralRules(?Ruleset $pluralRules, bool $reset = false) : LanguageInflectorFactory
+    /**
+     * @param \Doctrine\Inflector\Rules\Ruleset|null $pluralRules
+     * @param bool $reset
+     */
+    final public function withPluralRules($pluralRules, $reset = false)
     {
         if ($reset) {
             $this->pluralRulesets = [];
    ----------- end diff -----------

Applied rules:
 * DowngradeParameterTypeWideningRector (https://www.php.net/manual/en/migration72.new-features.php#migration72.new-features.param-type-widening)
 * DowngradeCovariantReturnTypeRector (https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.type-variance)
 * DowngradeAttributeToAnnotationRector (https://php.watch/articles/php-attributes#syntax)
 * DowngradeMixedTypeDeclarationRector
 * RemoveInterfacesRector
```

It seems due collection of applied rules above.

**Comment by samsonasik** [comment]
should be fixed by https://github.com/rectorphp/rector-src/pull/726 that keep return type in child when parent is return ThisType:

![Screen Shot 2021-08-21 at 00 01 47](https://user-images.githubusercontent.com/459648/130268570-a30408f8-ea3e-4307-b6e2-19d16f2bd9a8.png)

**Comment by samsonasik** [comment]
Re-open, get another error: 

```
 php bin/rector list --ansi
Rector fd3101cd2d1dac7e9f5023eaf75ce697d4c76fa7
Usage:
  command [options] [arguments]

PHP Fatal error:  Declaration of RectorPrefix20210820\Symfony\Component\String\AbstractUnicodeString::camel() must be compatible with RectorPrefix20210820\Symfony\Component\String\AbstractString::camel(): RectorPrefix20210820\Symfony\Component\String\AbstractString in /home/runner/work/rector/rector/vendor/symfony/string/AbstractUnicodeString.php on line 27

Fatal error: Declaration of RectorPrefix20210820\Symfony\Component\String\AbstractUnicodeString::camel() must be compatible with RectorPrefix20210820\Symfony\Component\String\AbstractString::camel(): RectorPrefix20210820\Symfony\Component\String\AbstractString in /home/runner/work/rector/rector/vendor/symfony/string/AbstractUnicodeString.php on line 27
```

https://github.com/rectorphp/rector/runs/3384275493#step:5:7

**Comment by samsonasik** [comment]
Finally fixed 🎉 🎉 🎉 

![Screen Shot 2021-08-21 at 00 59 26](https://user-images.githubusercontent.com/459648/130274813-cb40f026-d5ad-4c60-92ca-728373f2104f.png)

https://github.com/rectorphp/rector/commit/056fee1788d653f5ed87d1771c88650c66a9d3a2

**Comment by TomasVotruba** [comment]
Thank you :hugs:
