### ISSUE TITLE
Does rector/rector:php7.4 has been removed on Docker hub?

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector#6653]
Hello

I can't download anymore `rector/rector:php7.4` from Docker hub and, indeed, I don't see it anymore.

Can you provide a few information's on how to use `docker pull rector/getrector.org` and force the use of PHP 7.4 (like you did here https://github.com/rectorphp/rector/blob/main/docs/how_to_run_rector_in_docker.md#multiple-php-versions-supported)

Thanks !

**Comment by TomasVotruba** [comment]
Hi,

we're not supporting Docker anymore, as it proven to be buggy for simple use and unmaintained.
See https://github.com/rectorphp/rector/issues/6647 for the answers

Use composer instead. Since version 0.11 it works across PHP 7.1 to 8.0 platforms :+1: 

```bash
composer require rector/rector --dev
```

**Comment by cavo789** [comment]
Sorry Tomas, I forgot to thank you. Thank you for your always so lightning answers; thank you for Rector! 👍
