### ISSUE TITLE
Incorrect behavior of SimplifyIfElseToTernaryRector, RemoveUnusedAssignVariableRector

### ISSUE THREAD

**Issue by jelovac** [rectorphp/rector#6655]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

Something really weird is happening when combining these rectors.

See https://getrector.org/demo/1ec04ea5-b6da-6d02-aede-25eb23f0b3b2

```php
<?php

final class DemoFile
{
    private ?float $a;
    private ?float $b;
    
    public function getA():?float {
    	return $this->a;
    }
    
    public function getB():?float {
    	return $this->b;
    }
    
    public function getRes(): string
    {
        $a = round($this->getA() ?? 0, 2);
        $b = round($this->getB() ?? 0, 2);

        if ($this->a !== $this->b) {
            $res = "$a ($b)";
        } else {
            $res = "$a";
        }

        return $res;
    }
}
```

### Responsible rules

* `SimplifyIfElseToTernaryRector`

* `RemoveUnusedAssignVariableRector`

* ~~`RestoreDefaultNullToNullableTypePropertyRector`~~ 

## Expected Behavior

```php
<?php

final class DemoFile
{
    private ?float $a = null;
    private ?float $b = null;
    
    public function getA():?float {
    	return $this->a;
    }
    
    public function getB():?float {
    	return $this->b;
    }
    
    public function getRes(): string
    {
        $a = round($this->getA() ?? 0, 2);
        $b = round($this->getB() ?? 0, 2);

        $res = ($this->a !== $this->b) ? "$a ($b)" : "$a";

        return $res;
    }
}
```

**Comment by jelovac** [comment]
New test case: https://getrector.org/demo/1ec04ec0-f095-6cfc-96a2-5bda56f16e09

We can exclude rule RestoreDefaultNullToNullableTypePropertyRector. The issue is between SimplifyIfElseToTernaryRector and RemoveUnusedAssignVariableRector.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
For multiple rules issue usage, you can create test case under https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by jelovac** [comment]
OK, will be done some time during this week as I do not have spare time at the moment.
