### ISSUE TITLE
Rector\Removing\Rector\ClassMethod\ArgumentRemoverRector::isArgumentValueMatch(): Argument #2 ($values) must be of type array, string given

### ISSUE THREAD

**Issue by DanielSiepmann** [rectorphp/rector#6657]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | rector/rector                              0.11.49   Prefixed and PHP 7.1 downgraded version of rector/rector (invoke `vendor/bin/rector --version` -> `Rector 7eb5e75cda2e0dc95198ec3841084792fac844fb`)             |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec056fc-11d4-6902-afc3-7bd57d99d6ca

## Expected Behaviour

No error, as the example follows the docs. But the `'true'` has to be `['true']`. That at least removes the error, but keeps the original call. So I'm not able to configure the rule to actually remove the last argument.
I'm reporting this as bug instead of PR, as I expect tests to cover that, so something might be broken somewhere?

**Comment by TomasVotruba** [comment]
Hi, seems the fix is already clear:
https://github.com/rectorphp/rector/pull/6656/files

**Comment by DanielSiepmann** [comment]
Yeah I've opened that as PR first, but noticed it is coming from docs.
But then I thought the docs are actually used to generate tests somehow?

I also encountered that adding `[]` still doesn't remove the argument as expected … So I still miss something important.

**Comment by DanielSiepmann** [comment]
https://getrector.org/demo/1ec0570b-d66d-6fca-9e3a-cb9f01fd3936 results in no change, where I would expect last argument `true` to be removed.

**Comment by TomasVotruba** [comment]
Maybe `'true'` vs `true`?

**Comment by DanielSiepmann** [comment]
Will provide a PR. Thanks for instant help. Dump me :)
