### ISSUE TITLE
Is it possible to preserve annotation aliases when using AnnotationToAttributeRector?

### ISSUE THREAD

**Issue by jelovac** [rectorphp/rector#6659]
As the title says when using the AnnotationToAttributeRector rule is it possible to preserve annotation aliases?

For example I have:

```php
<?php

declare(strict_types=1);

use Doctrine\ORM\Mapping as ORM;

final class Test {

    /**
     * @ORM\Column(name="name", type="string", length=255)
     */
    protected string $name = '';

}
```

When running rector using the following configuration:

```php
    $services->set(AnnotationToAttributeRector::class)
        ->call('configure', [[
            AnnotationToAttributeRector::ANNOTATION_TO_ATTRIBUTE => ValueObjectInliner::inline([
                new AnnotationToAttribute(\Doctrine\ORM\Mapping\Column::class, null),
            ]),
        ]]);
```

I get the following:

```php
<?php

declare(strict_types=1);

use Doctrine\ORM\Mapping as ORM;

final class Test {

     #[\Doctrine\ORM\Mapping\Column(name: 'name', type: 'string', length: 255)]
    protected string $name = '';

}
```

And I want instead `#[ORM\Column(name: 'name', type: 'string', length: 255)]`

**Comment by jelovac** [comment]
Posted the question in the Discussion-s section as I did not see it earlier. So closing this issue.

**Comment by TomasVotruba** [comment]
Good news everyone :hugs: 
While working on PHP 8.1 nested attributes, we've added also support for keeping original aliases :+1: 

See https://github.com/rectorphp/rector-src/pull/1278
