### ISSUE TITLE
Error from LogicalToBooleanRector

### ISSUE THREAD

**Issue by puniserv** [rectorphp/rector#6667]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec0752b-2937-6f66-b2f8-774e3fee2a52

```php
<?php

final class DemoFile
{
    public function run($val1, $val2, $val3, $val4)
    {
        if (
           (
              1 === $val1 and
              1 === $val2 and
              1 === $val3 and
              1 === $val4
           )
       ) {
           //code
       }
    }
}
```

```
Rector could not run due to error:
Rector\CodeQuality\Rector\LogicalAnd\LogicalToBooleanRector
```
### Responsible rules

* `LogicalToBooleanRector`

## Expected Behavior

No error ;)

**Comment by Bl00D4NGEL** [comment]
The problem seems to be related to the `and`. If you replace the `and`s with `&&` it doesn't change anything and doesn't error out.

**Comment by TomasVotruba** [comment]
There will be also some problem with counter. With 4 cases it crashes, with 3 it does not
