### ISSUE TITLE
Missing rector to downgrade Closure::fromCallable (PHP 7.1)

### ISSUE THREAD

**Issue by bobab12** [rectorphp/rector#6671]
# Feature Request

There should be a rector rule to be able to downgrade `Closure::fromCallable` (PHP 7.1), see https://www.php.net/manual/en/closure.fromcallable.php.

## Diff 

```diff
-\Closure::fromCallable('strtolower');
+$callable = 'strtolower';
+function () use ($callable) {
+    return $callable(...func_get_args());
+};
```

**Comment by TomasVotruba** [comment]
Hi, we don't plan to add such rule at the moment, as our main focus is improving DX and bug-fixes on upgrade. See https://getrector.org/blog/rector-for-php56-native

Would you like to contribute it?

**Comment by bobab12** [comment]
> Hi, we don't plan to add such rule at the moment, as our main focus is improving DX and bug-fixes on upgrade. See https://getrector.org/blog/rector-for-php56-native
> 
> Would you like to contribute it?

I could give it a shot. :-) Let me get back to you whenever I have some spare time to work on this.

**Comment by TomasVotruba** [comment]
Thank you :+1: :muscle:  If you need some help, just ping me in the PR  :)
