### ISSUE TITLE
Rector doesn't find files on repeated run

### ISSUE THREAD

**Issue by ThomasLandauer** [rectorphp/rector#6673]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 130b634b5e348554c3349ed3b3f52fa3d08bfb6e             |

* I started with:
```bash
vendor/bin/rector process src --dry-run
```
Output:
> 9/9 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

This is OK.

* Then I did:
```bash
vendor/bin/rector process src/Entity --dry-run
```
Output:
> 0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

This is not OK, since I have 1 entity in there.

* Then I did this again:
```bash
vendor/bin/rector process src --dry-run
```
Output:
> 0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

WTF??

**Comment by samsonasik** [comment]
You can use Doctrine ORM 2.9 Set:

https://github.com/rectorphp/rector-doctrine/blob/281fc94511cebc608726715ff0c1de60d0d254b5/src/Set/DoctrineSetList.php#L59

```php
use Rector\Doctrine\Set\DoctrineSetList;

return static function (ContainerConfigurator $containerConfigurator): void {
      // ...
      $containerConfigurator->import(DoctrineSetList::DOCTRINE_ORM_29);
      // ...
};
```

**Comment by ThomasLandauer** [comment]
OK, closing here in favor of https://github.com/rectorphp/rector/issues/6674
