### ISSUE TITLE
Does `AnnotationToAttributeRector` refactor Doctrine entity mapping annotations too?

### ISSUE THREAD

**Issue by ThomasLandauer** [rectorphp/rector#6674]
Example:
```php
/**
 * @ORM\Id
 * @ORM\GeneratedValue
 * @ORM\Column(type="integer")
 */
```
* If yes, it should be mentioned at https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#annotationtoattributerector - cause the example there just shows routes.
* If no, the introduction paragraph at https://tomasvotruba.com/blog/how-to-refactor-custom-doctrine-annotations-to-attributes/ is wrong.

Due to https://github.com/rectorphp/rector/issues/6673 I can't figure it out myself right now ;-)

**Comment by samsonasik** [comment]
You can use Doctrine ORM 2.9 Set:

https://github.com/rectorphp/rector-doctrine/blob/281fc94511cebc608726715ff0c1de60d0d254b5/src/Set/DoctrineSetList.php#L59

```php
use Rector\Doctrine\Set\DoctrineSetList;

return static function (ContainerConfigurator $containerConfigurator): void {
      // ...
      $containerConfigurator->import(DoctrineSetList::DOCTRINE_ORM_29);
      // ...
};
```

**Comment by ThomasLandauer** [comment]
OK, this works, and the output says:
> Applied rules:
> * AnnotationToAttributeRector (https://wiki.php.net/rfc/attributes_v2)

However, when I change `rector.php` back to:
```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $services = $containerConfigurator->services();
    $services->set(AnnotationToAttributeRector::class);
};
```
... then there's no file shown for change:

> 9/9 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
> [OK] Rector is done!

**Comment by samsonasik** [comment]
thats because you need to configure the classes that need to be migrated to attributes, see doctrine orm set config from the list of classes

https://github.com/rectorphp/rector-doctrine/blob/281fc94511cebc608726715ff0c1de60d0d254b5/config/sets/doctrine-annotations-to-attributes.php
