### ISSUE TITLE
Incorrect behavior of DateTimeToDateTimeInterfaceRector, RemoveCodeAfterReturnRector, MysqlFuncCallToMysqliRector, RemoveFuncCallArgRector, RenameFunctionRector, ReturnTypeDeclarationRector

### ISSUE THREAD

**Issue by mirhunter** [rectorphp/rector#6675]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec0b689-93a2-66f4-9b37-15df3343862f

```php
<?php
$db = mysql_connect("server","user","password","database");
echo mysql_error();
```

### Responsible rules

* `MysqlFuncCallToMysqliRector`

## Expected Behavior

MysqlFuncCallToMysqliRector does not catch mysql_error()
https://www.php.net/manual/en/function.mysql-error.php

**Comment by samsonasik** [comment]
please create failing test case PR for it, for multiple rules usage, you can create under tests/Issues https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by mirhunter** [comment]
I updated the bug report to be more specific as to the rule. and removed demo code...

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by mirhunter** [comment]
I will be happy to once I return to work tomarrow...
Allen

**Comment by samsonasik** [comment]
@mirhunter I created PR https://github.com/rectorphp/rector-src/pull/884 for it.
