### ISSUE TITLE
Incorrect behavior of DowngradeNamedArgumentRector

### ISSUE THREAD

**Issue by bobab12** [rectorphp/rector#6677]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | cc69e35e53efe59e2858f75fd339e4d94211a54c             |

While downgrading the following error occurs:

PHP Warning:  Attempt to read property "name" on null in /workdir/rector-src/rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php on line 120

## Minimal PHP Code Causing Issue

The error can be reproduced by requiring "brick/math" using composer in an empty project, e.g.:

```
{
    "name": "test/test",
    "type": "project",
    "require": {
        "brick/math": "^0.9.3"
    }
}
```

Use the following rector.php:

```php
<?php declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\DowngradeSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(DowngradeSetList::PHP_80);
    $containerConfigurator->import(DowngradeSetList::PHP_74);
    $containerConfigurator->import(DowngradeSetList::PHP_73);
    $containerConfigurator->import(DowngradeSetList::PHP_72);
    $containerConfigurator->import(DowngradeSetList::PHP_71);

    $parameters = $containerConfigurator->parameters();
    $parameters
        ->set(Option::PATHS, [
            __DIR__ . '/vendor',
        ])
    ;
};
```

## Expected Behaviour

There should not be any PHP warnings.

**Comment by samsonasik** [comment]
Could you create failing test case for it? You can debug with `--debug` to see the possible code that cause it. Thank you.

**Comment by bobab12** [comment]
> Could you create failing test case for it? You can debug with `--debug` to see the possible code that cause it. Thank you.

I was not able to reproduce the error with a test case just for DowngradeNamedArgumentRector, as it appears to be occurring only when used in combination with SymmetricArrayDestructuringToListRector. Added a test case for this specific issue instead.
