### ISSUE TITLE
NullsafeOperatorRector tries to fix code that should be left alone

### ISSUE THREAD

**Issue by echo511** [rectorphp/rector#6680]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.52   130b634b5e348554c3349ed3b3f52fa3d08bfb6e             |

NullsafeOperatorRector tries to fix code that should be left alone. Example below.

## Minimal PHP Code Causing Issue
```php
public function getValue(\Entity $entity)
{
    $value = $this->baseField->getValue($entity);

    if ($value === null) {
        return null;
    }

    return $this->baseField->select($value);
}
```

## Current Behaviour
```php
public function getValue(\Entity $entity)
{
    return $this->baseField->getValue($entity)?->select($value);
}
```

## Expected Behaviour

Should be left as is.

**Comment by samsonasik** [comment]
Could you create failing test case for it, you can create under https://github.com/rectorphp/rector-src/tree/479df50e71997ffcc081fa4818a859ee4712ac4f/rules-tests/Php74/Rector/Assign/NullCoalescingOperatorRector/Fixture

**Comment by echo511** [comment]
Test case and fix created in enclosed PR.
