### ISSUE TITLE
Files Being Skipped While Processing

### ISSUE THREAD

**Issue by theoaks** [rectorphp/rector#6681]
I have a number of rules set in my rector.php file. However, I noticed that the processor skips a large number of files. But, when I copy the same set of fields I need changed to other files, the fields get updated and rector works very fine.

I would like to know if there's a log file where I can get any information on why the files are being skipped. No information is displayed on the console whenever this happens and there're limited resources online to help point out what's really happening under the hood.

**Comment by TomasVotruba** [comment]
Hi, you could try `--debug` option. 
Rector should skip only files that were processed with no change.

**Comment by theoaks** [comment]
> Hi, you could try `--debug` option.
> Rector should skip only files that were processed with no change.

No useful information was displayed. Just this:

[parsing] file.php
[refactoring] file.php
    [applying] Rector\Php80\Rector\Class_\AnnotationToAttributeRector
[post rectors] file.php
[print] file.php

**Comment by TomasVotruba** [comment]
That's all we have :) 

Could you make reproducible repository?

**Comment by theoaks** [comment]
> That's all we have :)
> 
> Could you make reproducible repository so we could achieve same results?

That'll be difficult. All the Annotations I'm trying to refactor to attributes are custom. There appears to be no particular pattern to how it's happening. The same set of annotations work in  other files. But don't work in others and there's no traceable pattern to it.

**Comment by TomasVotruba** [comment]
Without reproducible example we're not able to fix it.

**Comment by theoaks** [comment]
I've been able to recreate the issue. It happens when the the imports are grouped. As in the code below

```
use namespace\Path\{Annotation1,
    Annotation2,
    More\Annotation3,
    More\Annotation4,
};
```

When I separated the imports, the files were worked on

```
use namespace\Path\Annotation1;
use namespace\Path\Annotation2;
use namespace\Path\More\Annotation3;
use namespace\Path\More\Annotation4;
```

**Comment by TomasVotruba** [comment]
We still need test in our CI or reproducible repository, to make sure the problem was fixed.
