### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: PHPStan\Type\Constant\ConstantIntegerType::__construct(): Argument #1 ($value) must be of type int, string given

### ISSUE THREAD

**Issue by Danielss89** [rectorphp/rector#6683]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main#55734abb9a9c8abbde235468cf6f63a235465794             |

I am getting the following error while running rector:
`PHP Fatal error:  Uncaught TypeError: PHPStan\Type\Constant\ConstantIntegerType::__construct(): Argument #1 ($value) must be of type int, string given, called in .composer/vendor/rector/rector/packages/NodeTypeResolver/NodeTypeResolver/ScalarTypeResolver.php on line 41 and defined in phar://.composer/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/Constant/ConstantIntegerType.php:24`

Gist with stacktrace: https://gist.github.com/Danielss89/941a39954b26f3fce4eb20b08b7bb443

Config:
```
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(SetList::PHP_56);
    $containerConfigurator->import(SetList::PHP_70);
    $containerConfigurator->import(SetList::PHP_71);
    $containerConfigurator->import(SetList::PHP_72);
    $containerConfigurator->import(SetList::PHP_73);
    $containerConfigurator->import(SetList::PHP_74);
    $containerConfigurator->import(SetList::PHP_80);

    // get parameters
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::PHP_VERSION_FEATURES, 80000);

    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__ . '/app',
        __DIR__ . '/vendor',
    ]);

    $parameters->set(Option::SKIP, [
        __DIR__ . '*/test/*',
        __DIR__ . '*/views/*',
    ]);
};
```

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by samsonasik** [comment]
@Danielss89 looking at the stacktrace, that seems caused on rule `BreakNotInLoopOrSwitchToReturnRector`, you may can use one or two last rules, eg:

```php
<?php

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(\Rector\Php70\Rector\Break_\BreakNotInLoopOrSwitchToReturnRector::class);
    $services->set(\Rector\Php71\Rector\BinaryOp\BinaryOpBetweenNumberAndStringRector::class);
};
```

then try if that cause the issue. If you found it, you can : 

1. create a demo link to http://getrector.org/demo with the config that cause the issue provided.
2. create failing test case for it will be great, you can create under rules-tests, eg: https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php70/Rector/Break_/BreakNotInLoopOrSwitchToReturnRector/Fixture
3. for multiple rules usage, you can create under `tests/Issues`: https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by samsonasik** [comment]
I am closing it, feel free to create failing test case PR if you have reproducible code for it with steps in my previous comment.

**Comment by jtojnar** [comment]
I can still reproduce it with 0.14.2 but it appears to be fixed in dev-main (1ebe5f).
