### ISSUE TITLE
Incorrect behavior of TypedPropertyRector

### ISSUE THREAD

**Issue by Gabb1995** [rectorphp/rector#6686]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec11465-563f-68f4-bf3e-a99909f4aeb7

```php
<?php

final class DemoFile
{
    /** @var string */
    private $prop1;
    
    public function getProp1(): string
    {
    	return $this->prop1;    
    }
    
    public function setProp1(string $prop1): self
    {
    	$this->prop1 = $prop1;
        
        return $this;
    }
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

```php
<?php

final class DemoFile
{
    private string $prop1;
    
    public function getProp1(): string
    {
    	return $this->prop1;    
    }
    
    public function setProp1(string $prop1): self
    {
    	$this->prop1 = $prop1;
        
        return $this;
    }
}
```

## Actual Behaviour

```php
<?php

final class DemoFile
{
    private ?string $prop1 = null;
    
    public function getProp1(): string
    {
    	return $this->prop1;    
    }
    
    public function setProp1(string $prop1): self
    {
    	$this->prop1 = $prop1;
        
        return $this;
    }
}
```

## Comment
Not sure why if I have var string it makes it nullable, and even if it does make it nullable then maybe it should also update the getter return type to be nullable?

**Comment by samsonasik** [comment]
You need to combine with `ReturnTypeDeclarationRector` for that, with run rector twice for that, once the code has property nullable, it will return nullable, see https://getrector.org/demo/1ec1253c-47bd-62a8-9834-b11b56dd520c

**Comment by Gabb1995** [comment]
Ok understood and whats the reasoning behind adding null? I assume because of unintialized state, but we use for example JMS Serializer to populate the object, in a way we never access a property when its uninitialized even if there is no constructor.

**Comment by samsonasik** [comment]
there are many edge cases for setter injection, I suggest to use constructor injection instead if you want to use stricker typed.

**Comment by samsonasik** [comment]
I am closing it as the solution provided.

**Comment by Gabb1995** [comment]
Sorry to reopen, but is there a way to just follow the comment?

So if I have `@var string` it only adds string as strict type and not nullable?

Or do I need custom code for this? maybe a custom rule?

**Comment by samsonasik** [comment]
You can ignore rule for specific use case, see https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md
