### ISSUE TITLE
`ChangeSwitchToMatchRector` gets run against PHP 7.4

### ISSUE THREAD

**Issue by leighman** [rectorphp/rector#6687]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 130b634b5e348554c3349ed3b3f52fa3d08bfb6e         |

Using `SetList::PHP_80` with `"php": "7.4.23"`.
`ChangesSwitchToMatchRector` and `RemoveUnusedVariableInCatchRector` both run and make breaking changes to the code

**Comment by TomasVotruba** [comment]
Thanks for report.

In that case both rules need to implement `MinPhpVersionInterface` with min required version. Could you send a fix?

**Comment by leighman** [comment]
@sabbelasichon saw you've assigned it but thought I'd have a go
https://github.com/rectorphp/rector-src/pull/906

**Comment by sabbelasichon** [comment]
@leighman Oh, i see. I have done it also here: https://github.com/rectorphp/rector-src/pull/907

**Comment by leighman** [comment]
I put both in `PhpVersionFeature` which I think is nice but yours looks like a better job :wink:

**Comment by sabbelasichon** [comment]
@leighman Combined is the best. That´s what we are doing right now.
