### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivatePropertyRector, NullsafeOperatorRector

### ISSUE THREAD

**Issue by Gabb1995** [rectorphp/rector#6689]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec15510-faa7-686a-9983-c1103a3e4abc

```php
<?php

final class DemoFile
{
    private $myService;
    
    public function run($prop1, $prop2)
    {
        $prop3 = $this->getProp3($prop1);

        if (null === $prop3) {
            return null;
        }

        return $this->myService->myMethod($prop1, $prop2, $prop3);
    }
}
```

### Responsible rules

* `RemoveUnusedPrivatePropertyRector`

* `NullsafeOperatorRector`

## Expected Behavior

Rector should skip this.

**Comment by samsonasik** [comment]
Please create failing test case PR for it, for multiple rules, you can create under tests/Issues https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by Gabb1995** [comment]
> Please create failing test case PR for it, for multiple rules, you can create under tests/Issues https://github.com/rectorphp/rector-src/tree/main/tests/Issues

Done: https://github.com/rectorphp/rector-src/pull/880
