### ISSUE TITLE
Rector could not run due to error:  PhpParser\Node\Expr\StaticPropertyFetch

### ISSUE THREAD

**Issue by Gabb1995** [rectorphp/rector#6690]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | using demo on the site             |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec15684-49ec-6ed8-a805-f5f422b8c766

For more info in cmdline I get:
```
 [ERROR] Could not process "src/Demo.php" file, due to:                           
         "PhpParser\Node\Expr\StaticPropertyFetch". On line: 33   
```
## Expected Behaviour

Should be able to process it normally.

**Comment by samsonasik** [comment]
Could you run with `-vvv` or `--debug` locally and check if there is rule that cause it?

**Comment by Gabb1995** [comment]
Yes seems its this one:

Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector

**Comment by samsonasik** [comment]
Thank you, could you create a faling test case PR for it?

**Comment by Gabb1995** [comment]
> Thank you, could you create a faling test case PR for it?

done https://github.com/rectorphp/rector-src/pull/882
