### ISSUE TITLE
NullsafeOperatorRector PHP warnings

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#6695]
```
  209/2892 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   7%PHP Warning:  Undefined property: PhpParser\Node\Expr\BinaryOp\Concat::$name in /app/vendor/rector/rector/rules/Php80/Rector/If_/NullsafeOperatorRector.php on line 262
Warning: Undefined property: PhpParser\Node\Expr\BinaryOp\Concat::$name in /app/vendor/rector/rector/rules/Php80/Rector/If_/NullsafeOperatorRector.php on line 262
  573/2892 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  19%PHP Warning:  Undefined property: PhpParser\Node\Expr\New_::$name in /app/vendor/rector/rector/rules/Php80/Rector/If_/NullsafeOperatorRector.php on line 262
Warning: Undefined property: PhpParser\Node\Expr\New_::$name in /app/vendor/rector/rector/rules/Php80/Rector/If_/NullsafeOperatorRector.php on line 262
```

https://github.com/rectorphp/rector/blob/1257466608b64aa29fb0d70d7485063e2727eb4f/rules/Php80/Rector/If_/NullsafeOperatorRector.php#L262

I don't have a reproducer since it didn't tell me which file caused this issue. But there is certainly some issue here.

**Comment by enumag** [comment]
https://getrector.org/demo/1ec16fa6-17c2-6986-9de6-09216fad3b17

**Comment by enumag** [comment]
@TomasVotruba Suggestion: when the code ends up with en error like in this case, I think it would be nice to have the "create test" button shown.

**Comment by samsonasik** [comment]
@enumag I created PR https://github.com/rectorphp/rector-src/pull/895 to fix it.

**Comment by TomasVotruba** [comment]
> @TomasVotruba Suggestion: when the code ends up with an error like in this case, I think it would be nice to have the "create test" button shown.

:+1: 

It probably needs this to update https://github.com/rectorphp/getrector.org/blob/7b247a0aad4840c7538e2c9be741c2f3d15b5593/templates/demo/demo.twig#L49
