### ISSUE TITLE
[ERROR] Undefined class constant 'SETS'

### ISSUE THREAD

**Issue by zmorris** [rectorphp/rector#6696]
Hi I'm following the most basic instructions I could find to downgrade code from php 7.4 to php 7.2 at:

https://github.com/rectorphp/rector#install
https://blog.logrocket.com/transpiling-php-code-from-8-0-to-7-x-via-rector/
https://blog.logrocket.com/coding-in-php-7-4-and-deploying-to-7-1-via-rector-and-github-actions/

And a similar issue to what I'm doing:

https://github.com/rectorphp/rector/issues/4421

Here is my `rector.php`:

```
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src'
    ]);

    $parameters->set(Option::SETS, [
        SetList::DOWNGRADE_PHP72,
    ]);

    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_72);

    // Define what rule sets will be applied
    $containerConfigurator->import(SetList::CODE_QUALITY);

    // get services (needed for register a single rule)
    // $services = $containerConfigurator->services();

    // register a single rule
    // $services->set(TypedPropertyRector::class);
};
```

But when I run it, I get:

```
[ERROR] Undefined class constant 'SETS'
```

I'm running php 7.2 on Mac OS 10.15.7:

```
php -v
PHP 7.2.34 (cli) (built: May 14 2021 14:29:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34, Copyright (c) 1999-2018, by Zend Technologies
```

Feeling frustrated because the very first thing I tried for one of the most common use cases didn't work. I just want to make sure that I output php 7.2 code without having to manually copy over all of the rules in PhpVersion::PHP_72. What am I doing wrong?

Also, I'd recommend including a sample project within the repo that does at least one of these primary use cases. Either that, or a set of commands we can run in one shot that sets up a sample project up for us.

Thanks!

**Comment by TomasVotruba** [comment]
Hi, the `SETS` constant was deprecated and removed 4 months ago in https://github.com/rectorphp/rector-src/commit/8f9e234b4a59b4769fb63afc13a9700ec3866052

Use specific `*SetList` class instead in `import()` method.

E.g. https://github.com/rectorphp/rector-src/blob/74386d2bf051645eb8908b66c8a2ebf37bf33d93/rector.php#L24-L39

**Comment by zmorris** [comment]
Thank you very much for your quick reply! Getting closer now:

```
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src'
    ]);

    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);

    // here we can define, what sets of rules will be applied
    // tip: use "SetList" class to autocomplete sets
    $containerConfigurator->import(SetList::CODE_QUALITY);
    $containerConfigurator->import(SetList::PHP_74);
    $containerConfigurator->import(SetList::PHP_72);

    // register single rule
    $services = $containerConfigurator->services();
    $services->set(TypedPropertyRector::class);
};
```

But no matter what I try, I can't get it to downgrade the spread operator `...` to a standard array concatenation, I think it's this:

https://github.com/rectorphp/rector/blob/main/config/set/downgrade-php74.php#L30

I seem to be missing something fundamental. If I use `$parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_72);`, I get:

```
vendor/bin/rector process src     


                                                                                                                        
 [WARNING] Your project requires min PHP version "7.2".                                                                 
                                                                                                                        
           6 Rector rules defined in your configuration require higher PHP version and will not run,                    
           to avoid breaking your codebase, use -vvv for detailed info.                                                 
                                                                                                                        

 ! [NOTE] Do you want to run them? Make "require" > "php" in `composer.json` higher,                                    
 !        or add "Option::PHP_VERSION_FEATURES" parameter to your `rector.php`.                                         

    0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]                                                                                                                        
 [OK] Rector is done!                                                                                                   
```

All I'm trying to do is convert this:

```
$x = [1, 2];
$y = [...$x, 3];
```

To something like:

```
$x = [1, 2];
$y = array_merge($x, [3]);
```

So I'm still stuck at this point, unable to downgrade from php 7.4 to 7.2 :-/

Do I need to have php 7.4 installed on my machine? I'd prefer not to, as the projects I'm working on still use php 7.2.

**Comment by zmorris** [comment]
I finally managed to stumble upon a pure-shell solution that works: 🎉

```shell
vendor/bin/rector process src --config=vendor/rector/rector/config/set/downgrade-php74.php
```

This skips `rector.php` entirely and downgrades to `PHP_73`. Unfortunately multiple `--config` can't be specified, but we can do it sequentially to end up at `PHP_72`:

```shell
vendor/bin/rector process src --config=vendor/rector/rector/config/set/downgrade-php74.php
vendor/bin/rector process src --config=vendor/rector/rector/config/set/downgrade-php73.php
```

I'd recommend doing it this way anyway since declarative and data-driven solutions are almost always preferable to code.

Command to create a fresh project:
```shell
mkdir downgrader && cd downgrader
mkdir src
composer require rector/rector --dev
{
cat << 'EOF'
<?php

$x = [1, 2];
$y = [...$x, 3];
EOF
} > src/src/example.php
```

After running the pure-shell solution, `src/example.php` becomes:

```php
<?php

$x = [1, 2];
$y = array_merge($x, [3]);
```

***

Notes:

* I finally got the spread operator to downgrade with this `rector.php`:
```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src'
    ]);

//     $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);

    // here we can define, what sets of rules will be applied
    // tip: use "SetList" class to autocomplete sets
//     $containerConfigurator->import(SetList::CODE_QUALITY);
//     $containerConfigurator->import(SetList::PHP_74);
//     $containerConfigurator->import(SetList::PHP_72);

    // register single rule
    $services = $containerConfigurator->services();
    $services->set(TypedPropertyRector::class);
    $services->set(\Rector\DowngradePhp74\Rector\Array_\DowngradeArraySpreadRector::class);
};
```
* But was unable to apply `SetList::PHP_74` in its entirety. There must be some command to do that, but I've been staring at this too long and can't see it. I'd have to dig into the internals of the code to figure out how to import https://github.com/rectorphp/rector/blob/main/config/set/downgrade-php74.php which indicates a failure of the documentation. If someone has an example, it will save others time.
* I didn't have to specify the php version in composer.json:
```php
{
    "require-dev": {
        "rector/rector": "^0.11.53"
    }
}
```
* I didn't have to change my php version, and was able to downgrade a PHP_74  to PHP_72 under php 7.2. If you need them, these commands worked on Mac OS 10.15 to quickly switch (older versions sometimes need additional libs like tidy-html5 specified):
```
# change php version
# 7.4:
brew reinstall php@7.4 && brew link php@7.4
# 7.2:
brew reinstall php@7.2 tidy-html5 && brew link php@7.2
```

This project is awesome and I wish I had time to contribute, but as it stand now, the README.md documentation isn't enough for new users for this use case. I'd recommend starting a wiki instead.

I always forget about GitHub discussions and consider them largely useless since they don't show up in search engine results or auto-populate the issues section. But the time I lost today can probably be avoided by others here:

https://github.com/rectorphp/rector/discussions
