### ISSUE TITLE
Duplicate Doctrine Collection init in constructor

### ISSUE THREAD

**Issue by Thomas-Negrault** [rectorphp/rector#6697]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec17b54-1220-6b86-98d0-9f37d4756830

```php
<?php

namespace Domain\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="articles")
 * @ORM\Entity(repositoryClass="Domain\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @var string|null
     *
     * @ORM\Column(name="id", type="guid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    protected $id;

    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    protected ?\DateTimeInterface $createdAt;

    /**
     * @var Collection|Category[]
     *
     * @ORM\ManyToMany(targetEntity="Category", cascade={"persist", "merge"})
     * @ORM\JoinTable(name="articles_categories")
     */
    private Collection $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }
    
}
```

### Responsible rules

* `InitializeDefaultEntityCollectionRector`

* `MoveCurrentDateTimeDefaultInEntityToConstructorRector`

* `RemoveRedundantDefaultClassAnnotationValuesRector`

* `RemoveRedundantDefaultPropertyAnnotationValuesRector`

* `RestoreDefaultNullToNullableTypePropertyRector`

## Expected Behavior

It should only add
`$this->createdAt = new \DateTime(null);`
And not duplicate  `$this->categories = new ArrayCollection();` multiple times like it does:

```
     public function __construct()
     {
-        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->categories = new ArrayCollection();
+        $this->createdAt = new \DateTime(null);
     }
```
It seems to be solved if I remove one of:
```
    $parameters->set(Option::AUTO_IMPORT_NAMES, true); //Do not use fully qualified class names
    $parameters->set(Option::IMPORT_SHORT_CLASSES, false); //Do not import classes like \DateTime
```

**Comment by samsonasik** [comment]
Could you create failing test case PR for it? For multipe rules usage ,you can create under https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by samsonasik** [comment]
I think the rules applied are the following rules:

```php
    $services->set(\Rector\Doctrine\Rector\Class_\InitializeDefaultEntityCollectionRector::class);
    $services->set(\Rector\Doctrine\Rector\Class_\MoveCurrentDateTimeDefaultInEntityToConstructorRector::class);
```

see https://getrector.org/demo/1ec17d1b-4131-6308-815a-e7c6139bf843

It may need to be fixed at rector-doctrine repo https://github.com/rectorphp/rector-doctrine

**Comment by samsonasik** [comment]
It seems `InitializeDefaultEntityCollectionRector` already can make duplicate assign https://getrector.org/demo/1ec1823a-d5cf-634c-85b6-c50a66042928

**Comment by samsonasik** [comment]
The issue seems from the method `StmtsManipulator::filterOutExistingStmts()`

https://github.com/rectorphp/rector-src/blob/1e3e5dff59b05d497580f52e9a7491a2afa6bd29/src/NodeManipulator/StmtsManipulator.php#L41-L58

**Comment by samsonasik** [comment]
@Thomas-Negrault I created PR https://github.com/rectorphp/rector-doctrine/pull/28 for it.
