### ISSUE TITLE
[DX] Add PHPStan rule to check the PHP-X are registered in the sets

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6699]
In https://github.com/rectorphp/rector-src/pull/900 I've noticed the rule for PHP 8.0 upgrade was added, but never actually registered in PHP 8.0 set. This could be avoided.

There should be custom PHPStan rule to check that the PHPx + PHPx-downgrade rules are part of the config that is in their namespace.

@samsonasik Could you check this one?

**Comment by samsonasik** [comment]
Do you mean create new PHPStan rule at https://github.com/rectorphp/phpstan-rules/tree/main/src/Rule ?

**Comment by TomasVotruba** [comment]
İt can be added here locally, as it doesn't make sense anywhere else

**Comment by samsonasik** [comment]
Ok, I will try
