### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivatePropertyRector

### ISSUE THREAD

**Issue by Blazik** [rectorphp/rector#6701]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec1c508-1238-688c-b65c-21cb6bd9ece9

```php
<?php

class UnusedPrivatePropertyBug
{

    public stdClass $someUsedProperty;

    private string $unusedPropertyName;

    public function someMethod()
    {
        $this->someUsedProperty->unusedPropertyName = 'text';
    }

}
```

### Responsible rules

* `RemoveUnusedPrivatePropertyRector`

## Expected Behavior

Rector should remove only `private string $unusedPropertyName;`. 

Seems like rector is also removing this `$this->someUsedProperty->unusedPropertyName = 'text';` because that name of property created on stdClass has the same name as the unused private property of UnusedPrivatePropertyBug class. (That type `stdClass` is irrelevant, this bug is caused even on another similar types.)

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by Blazik** [comment]
Pull request: https://github.com/rectorphp/rector-src/pull/915
