### ISSUE TITLE
RenameClassRector does not remove old import

### ISSUE THREAD

**Issue by Spea** [rectorphp/rector#6704]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.53 (installed via composer)            |

I want to use the `RenameClassRector` to replace the class `Rhumsaa\Uuid\Uuid` with `Ramsey\Uuid\Uuid` via this configuration:

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Renaming\Rector\Name\RenameClassRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::AUTO_IMPORT_NAMES, true);

    $services = $containerConfigurator->services();
    $services->set(RenameClassRector::class)
        ->call('configure', [[
            RenameClassRector::OLD_TO_NEW_CLASSES => [
                'Rhumsaa\Uuid\Uuid' => 'Ramsey\Uuid\Uuid',
            ],]]);
};
```

but for some reason it does not remove the old import, so now I have two imports with the same class (but different namespaces) which obviously fails with the following error:

```
Cannot use Rhumsaa\Uuid\Uuid as Uuid because the name is already in use
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec1d50f-cbdb-6e94-9cac-bbde4011c6aa

## Expected Behaviour

The old import should be removed.

**Comment by samsonasik** [comment]
Please try "rector/rector": "dev-main", if still happen, please create failing fixture PR to https://github.com/rectorphp/rector-src/tree/main/rules-tests/Renaming/Rector/Name/RenameClassRector/FixtureAutoImportNames

With register class to rename to config after

https://github.com/rectorphp/rector-src/blob/49314dc3d4918988d83270ab104e347a97e46d46/rules-tests/Renaming/Rector/Name/RenameClassRector/config/auto_import_names.php#L22

**Comment by Spea** [comment]
@samsonasik thank you for picking this up and fixing it so quickly, highly appreciated
@TomasVotruba and thank you for creating this awesome tool!

**Comment by TomasVotruba** [comment]
@Spea Thank you for kind words :hugs:
