### ISSUE TITLE
Downgrade are not present in setlist

### ISSUE THREAD

**Issue by euberdeveloper** [rectorphp/rector#6705]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.53 (invoke `vendor/bin/rector --version`)             |

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Set\ValueObject\SetList;

return static function (ContainerConfigurator $containerConfigurator): void {
  // get parameters
  $parameters = $containerConfigurator->parameters();
  $containerConfigurator->import(SetList::DOWNGRADE_PHP74);
};
```

[link for reproduction](https://getrector.org/demo/1ec1e486-4bcc-62d6-b78c-9139218718ca)

## Expected Behaviour

The downgrade php should exist

**Comment by euberdeveloper** [comment]
For now I used: 

```php
$containerConfigurator->import(__DIR__ . '/vendor/rector/rector/config/set/downgrade-php53.php');
```

**Comment by samsonasik** [comment]
You can use `\Rector\Set\ValueObject\DowngradeSetList::PHP_74` value object, see https://getrector.org/demo/1ec1e4ca-e45f-6112-aa7d-3b608238bcdc

**Comment by euberdeveloper** [comment]
Thank you, I did not find it in the docs

**Comment by samsonasik** [comment]
Feel free to create PR to improve the docs at https://github.com/rectorphp/rector-src/blob/main/build/target-repository/docs/how_to_register_custom_setlist_constant.md , thank you.
