### ISSUE TITLE
[addNodeBeforeNode issue] Incorrect behavior of DowngradeArraySpreadRector, DowngradeMatchToSwitchRector

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#6708]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec2025b-f2a5-6a74-a597-07a8d2703655

```php
<?php
class WithMultipleFunctionInSwitch
{
    function getArray(): array
    {
        return ['apple', 'pear'];
    }

    public function run($operation)
    {
        return match ($operation) {
            'fruits' => ['banana', 'orange', ...$this->getArray()],
        };
    }
}
```

### Responsible rules

* `DowngradeArraySpreadRector`

* `DowngradeMatchToSwitchRector`

## Expected Behavior

When running `DowngradeMatchToSwitchRector` alone it works well.

When running `DowngradeArraySpreadRector` alone it works well.

But when running `DowngradeMatchToSwitchRector` and `DowngradeArraySpreadRector` together it fails.

The error is that code `$item2Unpacked = $this->getArray()` should be printed, but it is not:

 ```diff
public function run($operation)
{
    switch ($operation) {
        case 'fruits':
-            $item2Unpacked = $this->getArray();
            return array_merge(['banana', 'orange'], $item2Unpacked);
    }
}
```

Then, `$item2Unpacked` has no value.

Debugging, I saw that function `createVariableFromNonVariable` in `DowngradeArraySpreadRector` does generate the variable `$item2Unpacked` correctly, however it is not added to the response.

So I guess this line is not working:

```php
$this->nodesToAddCollector->addNodeBeforeNode(new Assign($newVariable, $arrayItem->value), $array);
```

I assume `$array` is a new node, which was created by the previous rule `DowngradeMatchToSwitchRector`, and then somehow it fails at adding a node before it.

**Comment by samsonasik** [comment]
Could you create failing test case for it, for multiple rules, you can create under https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by leoloso** [comment]
Ok, done here: https://github.com/rectorphp/rector-src/pull/927
