### ISSUE TITLE
`ReturnTypeFromStrictTypedCallRector` should not use `false` as return type

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#6711]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec210d0-8d54-6ed0-9e71-813569ff2a89

```php
<?php

function foo($foo) { $foo(); }

foo(static fn() => 1 == 1 ? false : null);
```

### Responsible rules

* `ReturnTypeFromStrictTypedCallRector`

## Expected Behavior

Rector changes the last line to `foo(static fn(User $user): ?false => 1 == 1 ? false : null);` which causes a fatal error in runtime `False can not be used as a standalone type`

I think Rector needs to change it to `?bool` instead of `?false`

**Comment by samsonasik** [comment]
Could you create failing test case for it? You can click "Create a Test" button

**Comment by canvural** [comment]
@samsonasik I tried to create it in https://github.com/rectorphp/rector-src/pull/931
