### ISSUE TITLE
Incorrect behavior of TypedPropertyRector

### ISSUE THREAD

**Issue by simonschaufi** [rectorphp/rector#6713]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec21ee3-f729-6920-88b0-3345de624f09

```php
<?php

class ParentClass
{
    /**
     * @var bool
     */
    protected $active = false;
}

class ChildClass extends ParentClass
{
    /**
     * @var bool
     */
    protected $active = true;
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

The child's property MUST be in sync with the parent's one, otherwise it leads to a PHP error.

**Comment by samsonasik** [comment]
Please create failing test case for it, You can click "Create a Test" button in the demo page.

**Comment by simonschaufi** [comment]
see https://github.com/rectorphp/rector-src/pull/935
