### ISSUE TITLE
Phpunit fails on Test classes

### ISSUE THREAD

**Issue by Gabb1995** [rectorphp/rector#6714]
```
bin/phpunit tests/Rector/Rule/RemoveUnusedPrivatePropertyRector/RemoveUnusedPrivatePropertyRectorTest.php
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Testing Utilities\Tests\Rector\Rule\RemoveUnusedPrivatePropertyRector\RemoveUnusedPrivatePropertyRectorTest
PHP Fatal error:  Cannot declare interface PhpParser\Parser, because the name is already in use in /srv/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Parser.php on line 6

Fatal error: Cannot declare interface PhpParser\Parser, because the name is already in use in /srv/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Parser.php on line 6
make: *** [Makefile:26: app.phpunit] Error 255
```

I see that there was a bug fix for something like this yesterday I am on 0.11.56 with this issue.

see https://github.com/rectorphp/rector/issues/6709

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

As described there, the cause for this can be in many places. We'll need a reproducible repository to find out where it happens in your project. Thanks :+1:

**Comment by Gabb1995** [comment]
Just some more info:

```
"The autoloader expected class "Composer\InstalledVersions" to be defined in file "/srv/vendor/rector/rector/vendor/composer/../composer/InstalledVersions.php". The file was found but the class was not in it, the class name or namespace probably has a typo."
```

This is when I run all unit tests vs when I run just rector unit tests.

**Comment by Gabb1995** [comment]
see https://github.com/Gabb1995/rector-phpunit-bug

**Comment by TomasVotruba** [comment]
@Gabb1995 Thanks :+1:  I see some wrapper around PHPUnit. That might be causing some troubles.
We'll need to remove it and use directly PHPUnit, to avoid debugging 3rd party layer.

**Comment by Gabb1995** [comment]
Seems it works without https://symfony.com/doc/current/components/phpunit_bridge.html, so it is only reproducible with this package, could there be some conflicts?

**Comment by TomasVotruba** [comment]
Great :+1: I don't use that package, but there is some autoload magic that hacks around composer one probably.

I recommend using normal PHPUnit, as Symfony is mostly designed to hack around their complex releases.

**Comment by Gabb1995** [comment]
It works when I remove 
`require_once __DIR__ . '/vendor/nikic/php-parser/lib/PhpParser/Parser.php';`
from preload.php, any clue if I can override this as it won't be possible to switch to normal phpunit.

**Comment by Gabb1995** [comment]
Went with your suggestion to use PHPUnit, seems its not recommended anymore to use symfony phpunit bridge.
