### ISSUE TITLE
Ability to configure how `BreakingVariableRenameGuard` handles suffixes

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector#6715]
# Feature Request

In #6710 I asked about rector for renaming hungarian notation but following your response and info from #6709 I am working on custom rule. I was almost done, but when I added some additional fixtures for skipping I hit the wall created in `BreakingVariableRenameGuard::shouldSkipVariable()` - there is condition that checks if expected variable name is a suffix of existing variable name and in terms of Hungarian notation it does not make sense because it will be always true, so guard will prevent renaming.

Because it would be the best to use this class because it has full logic for determining conflicts (other variables, function/method arguments, closures' `use` etc.) I am asking if it would be possible to add new argument to that method signature:

```php
final class BreakingVariableRenameGuard
    public function shouldSkipVariable(
        string $currentName,
        string $expectedName,
        $functionLike,
        \PhpParser\Node\Expr\Variable $variable,
        bool $skipOnSuffix = true // <--- backward compatibility
    ) : bool;
}
```

and use it in mentioned condition. It would be possible then to skip suffix condition and check the rest.

If not, what's the workaround? I've tried to clone that guard class into my namespace, removing that suffix condition but without luck, I have problems with DI (`ArgumentCountError: Too few arguments to function Foo\BreakingVariableRenameGuard::__construct(), 0 passed in ... and exactly 6 expected`). Of course it's possible to inject the same services as `BreakingVariableRenameGuard` uses into my rector class and create the same logic there, but I don't like it (there's too many dependencies and too many conditions, it would be better to keep it in external service).
 
## Diff 

In the end I would like to make such changes:

```diff
-$pSomething = true;
+$something = true;
```

-----

PS. Is that suffix condition really needed? If anyone is willing to rename `$myWeirdlyNamedUserFactory` to `$userFactory` it won't be possible because of that condition. I find it weird.

**Comment by Wirone** [comment]
For reference, this is the fixture for skipping renaming:

```php
class Foo {
    private $pFoo;
    private $foo;

    public function bar()
    {
        $pBaz = true;
        $baz = false;
    }

    public function baz($baz = false)
    {
        $pBaz = true;
    }
}

$foo = null;
array_map([], function () use ($foo) {
    $pFoo = false;
});
```

No property nor variable should be renamed because there are conflicts with other variables/arguments. With current implementation of `BreakingVariableRenameGuard` it gives false-positive result because renaming is skipped because of suffix match, not because of expected name conflict. When I comment out suffix condition I get:

```diff
--- Expected
+++ Actual
@@ @@

     public function baz($baz = false)
     {
-        $pBaz = true;
+        $baz = true;
     }
 }
```

which is also weird (bug?), but much better from my perspective (I know that most of conflicts were determined and renaming was skipped).

**Comment by TomasVotruba** [comment]
Hey, I'm not sure what exactly the bug is. Could you send failing fixture for that service?

**Comment by Wirone** [comment]
@TomasVotruba I don't know how to deliver it since I would need to create rector rule that is conflict with your current approach. I don't see unit tests for `BreakingVariableRenameGuard` so I can't add failing case either.

I'll try to explain. Imagine you have common variable notation `$xyzSomething` in the project and you want to refactor it, so you want to create custom rule. You write rule, you use `BreakingVariableRenameGuard` for renaming e.g. `$xyzUser` to `$user` because you want ensure there's no conflict and variable can be renamed safely. Unfortunately that guard won't allow it because of:

```php
$expectedNameCamelCase = \ucfirst($expectedName);
if (\substr_compare($currentName, $expectedNameCamelCase, -\strlen($expectedNameCamelCase)) === 0) {
    return \true;
}
```

since expected name `$user` is a "suffix" of `$xyzUser`. Hungarian notation is an example for that, because you explicitly want to get rid of prefixes, leaving only suffixes. And that guard blocks it 🙂

**Comment by TomasVotruba** [comment]
>  I would need to create rector rule that is conflict with your current approach

I mean only the failing fixture for variable name changes. 

> I don't see unit tests for BreakingVariableRenameGuard so I can't add failing case either.

The test does not exist yet, because it was not breaking much. Now it seems is the time when we need it :) test should be created in mirror location to its source with `BreakingVariableRenameGuardTest` name.

Based on the failing test, we can extend current behavior to allow it.

**Comment by Wirone** [comment]
I think I'll pass this time. First of all I don't know how to prepare proper test case for `BreakingVariableRenameGuardTest::shouldSkipVariable()` since it has so many correct paths going through private methods.. Mocking/providing `$functionLike` and `$variable` won't be easy here and I don't have time to learn whole flow. Second, even if I introduce new argument as proposed (`bool $skipOnSuffix = true`) and I go further into this method's logic, my fixture ([provided above](#issuecomment-931765060)) won't pass anyway because of `$protectedNames = $this->arrayFilter->filterWithAtLeastTwoOccurences($protectedNames);` in `Rector\Naming\Naming\ConflictingNameResolver::resolveConflictingVariableNamesForNew()` - it does not make sense IMO, but again I don't have time for improving it.

I think I'll reproduce similar logic in mu custom rector and will determine names from arguments, defined variables and variables from `use` statement, should be good enough.

**Comment by TomasVotruba** [comment]
> I think I'll reproduce similar logic in mu custom rector and will determine names from arguments, defined variables and variables from use statement, should be good enough.

I think that makes sense :+1:
