### ISSUE TITLE
 use Import statements instead of FQ Namespace in Symfony Route Attribute

### ISSUE THREAD

**Issue by tacman** [rectorphp/rector#6716]
# Help Request: Import statements

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec22556-0285-6df0-b466-854761014158

```php
<?php

namespace App\Controller;

use App\Entity\Location;
use Bordeux\Bundle\GeoNameBundle\Entity\GeoName;
use Doctrine\ORM\QueryBuilder;
use Survos\BaseBundle\Traits\JsonResponseTrait;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class AppController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     */
    public function index()
    {
        return $this->render('app/index.html.twig', [
            'controller_name' => 'AppController',
        ]);
    }
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

> See https://github.com/rectorphp/rector#import-use-statements

Since this link no longer works, can you point me in the right direction?

```php
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/logout', name: 'app_logout')]
```

instead of 
```php
#[\Symfony\Component\Routing\Annotation\Route(path: '/logout', name: 'app_logout')]
```

It is likely that this is a code style rule, but I can't figure out how to call it.  I stumbled across this thread: https://github.com/rectorphp/rector/issues/1117 but am still stuck.  Thanks.

**Comment by samsonasik** [comment]
You can use auto import option, see https://getrector.org/demo/1ec22575-fc49-69e4-b9a8-1765ecd8d305

**Comment by tacman** [comment]
me: an hour of hacking, cursing, and hair pulling.
@samsonasik: 15 seconds to point me to a working example.

Thanks.
