### ISSUE TITLE
ArrayCallableMethodMatcher: PHPStan\Reflection\ClassReflection::getMethod(): Argument #2 ($scope) must be of type ClassMemberAccessAnswerer

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#6718]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.53-0.11.56             |

I'm still working on a reproducible example, I'll update my issue when I have one.

I've got this error:

```
 [ERROR] Could not process "src/Entity/Organisation.php" file, due to:                                       
         "PHPStan\Reflection\ClassReflection::getMethod(): Argument #2 ($scope) must be of type                         
         PHPStan\Reflection\ClassMemberAccessAnswerer, null given, called in                                            
         vendor/rector/rector/packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php:146". On line: 308  
```

I think this line causes the problem:

    #[UniqueEntity('code', entityClass: Organisation::class)]

or 

    #[UniqueEntity('code', entityClass: self::class)]

The issue is introduced in `0.11.53`.

Sorry for not having a clear reproducible example yet, I'm still working on it.

**Comment by samsonasik** [comment]
@stephanvierkant I created PR https://github.com/rectorphp/rector-src/pull/947 for it, please verify if that fixes the issue.
