### ISSUE TITLE
[DX] Warn about registering configurable rule without configuration

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6719]
We've noticed that some rules like `AnnotationToAttributeRector` are registered, run and do not change anything. Used is confused and thinks the rule is broken.

That's because this rule requires explicit registration of rules that should be changed. User should be warned about this by some exception or warning mesage to avoid WTF :)

**Comment by samsonasik** [comment]
I think this should only apply when the default assigned property fetch is empty array, eg:

```php
    /**
     * @var AnnotationToAttribute[]
     */
    private array $annotationsToAttributes = [];
```

On https://github.com/rectorphp/rector-src/blob/6bfe0133002f30d16489deb9ef6028efdbbaa795/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php#L62

which it need to be loop the array data.

For other default, eg: `false`, it can be excluded as the implementation is it will run fine without configuring it, eg in `TypedPropertyRector`:

```php
    /**
     * Useful for refactoring of huge applications. Taking types first narrows scope
     */
    private bool $classLikeTypeOnly = false;
```

On https://github.com/rectorphp/rector-src/blob/6bfe0133002f30d16489deb9ef6028efdbbaa795/rules/Php74/Rector/Property/TypedPropertyRector.php#L55-L64
