### ISSUE TITLE
Incorrect behavior of ReturnTypeDeclarationRector after v0.11.41

### ISSUE THREAD

**Issue by fox91** [rectorphp/rector#6720]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | `0.11.41` to `0.11.56` and last `dev-master`     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec246f1-41e8-68f0-b0be-b31bea934547

```php
<?php
declare(strict_types=1);

/** @return array<array{a: int, b: float}>|null */
function foo3(int $a, float $b): ?array
{
    $bar = null;

    if ($a > 0) {
        for ($i = 0; $i < $a; $i++) {
            $bar[] = [
                'a' => $a,
                'b' => $b,
            ];
        }
    }

    return $bar;
}
```

### Responsible rules

* `ReturnTypeDeclarationRector`

## Expected Behavior

Like these other cases (https://getrector.org/demo/1ec246f1-8642-6cf8-bdd8-f79e81bd2780 and https://getrector.org/demo/1ec246f0-528b-6668-94b0-6bee5244da69) there aren't errors to fix.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by samsonasik** [comment]
You can click "Create a Test" button in demo page
