### ISSUE TITLE
DisallowedEmptyRuleFixerRector misbehaves, it converts !empty(string|null $foo) to $foo !== null

### ISSUE THREAD

**Issue by janedbal** [rectorphp/rector#6724]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

DisallowedEmptyRuleFixerRector is making dangerous non-equivalent changes. See snippet below.

## Minimal PHP Code Causing Issue

```php
class Bug {
	public function get(): ?string {
		return null;
	}

	public function example(): void {
		if (!empty($this->get())) {
			
		}
	}
}
// gets converted to
class Bug {
	public function get(): ?string {
		return null;
	}

	public function example(): void {
		if ($this->get() !== null) {
			
		}
	}
}
```

## Expected Behaviour

```php
// should be converted to
class Bug {
	public function get(): ?string {
		return null;
	}

	public function example(): void {
		if ($this->get() !== null && $this->get() !== '') {
			
		}
	}
}
```

**Comment by janedbal** [comment]
Other strict rules have similar issue. E.g.

```php
public function example(?string $foo): void {
    if ($foo) {} // gets converted to $foo !== null
}
```

**Comment by TomasVotruba** [comment]
Issue is better, thanks :+1: 

Ref https://twitter.com/janedbal/status/1445342334036725762
Makes sense!

**Comment by TomasVotruba** [comment]
Fixed with opt-in empty scalars in https://github.com/rectorphp/rector-src/pull/956
