### ISSUE TITLE
Incorrect behavior of TypedPropertyRector

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#6728]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec268b3-2907-6ca8-bcc6-6b3c81c27495

```php
<?php

trait MaterializedPathEntity
{
    /** @var self */
    protected $parent;
    
    public function setParent(self $parent = null) : static
    {
        $this->parent = $parent;

        return $this;
    }
    
    public function getParent() : static
    {
        return $this->parent;
    }
}

final class DemoFile
{
    use MaterializedPathEntity;
    
    public function run()
    {
        return $this->getParent();
    }
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

`DummyTraitClass` shouldn't be used

**Comment by samsonasik** [comment]
Please create failing test case, you can click "Create a Test" button at demo page
