### ISSUE TITLE
Invalid Value issue on line number that doesn't exist, process stops on file.

### ISSUE THREAD

**Issue by eguerin-ucsf** [rectorphp/rector#6732]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

vendor/bin/rector --version
Rector d4cb2395dc729e4c77e9b0e4a99677d9acb6d1b8

I get the following while using drupal-rector to process things with rector.    Some rector analysis will stop do so an error.

vendor/bin/rector process docroot/modules/contrib/applenews/ --dry-run

 [ERROR] Could not process "docroot/modules/contrib/applenews/src/Commands/ApplenewsCommands.php" file, due to:         
 "Invalid value". On line: 212        

I will look inside the code and there is never a line 212, there is also no indication of what the invalid value might be.  This has happened on a couple of files, it is always line 212.  

## Minimal PHP Code Causing Issue

The code test is against this module running in a Drupal 8 installation (latest drupal 8)
https://www.drupal.org/project/applenews

## Expected Behaviour

Rector stops all together, would be nice if the file was just skipped and the processing continued, but this stopped the whole validation process.   Also would be good to know where the line 212 is actually coming from because its not the file that is suggested.

**Comment by TomasVotruba** [comment]
Hi, first hint, try to run with `--debug` option
