### ISSUE TITLE
config: php-version-features doesn't work

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6734]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. d4cb2395dc729e4c77e9b0e4a99677d9acb6d1b8             |

when using

```
$parameters->set(Option::PHP_VERSION_FEATURES, '7.2');
```

rector starts with this warning

```
                                                                                                                        
 [WARNING] Your project requires min PHP version "0.0.7".                                                               
                                                                                                                        
           1 Rector rules defined in your configuration require higher PHP version and will not run,                    
           to avoid breaking your codebase, use -vvv for detailed info.                                                 
                                                                                                                        

```

debugging the `PhpVersionProvider` reveals that 
`$phpVersionFeatures = $this->parameterProvider->provideIntParameter(\Rector\Core\Configuration\Option::PHP_VERSION_FEATURES);`

will just return a `7`?

running on windows11x64 with php 8.0.10

## Expected Behaviour

something sane ;-). not sure whether its a bug, that 7 is returned, but maybe the user-configured value should be validated somehow to give more usefull advice regarding the source of the error.

the warning which came up was pretty misleading, since both points mentioned were not true

**Comment by ian-zunderdorp** [comment]
Just in case that you didn't know yet (and for people seeking assistance): I think that the recommended way to set this parameter currently is:
```php
$parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_72);
```

**Comment by TomasVotruba** [comment]
@ian-zunderdorp Thanks, that's the way. We should valide this input. 

Could you check where it should be validated and throw exception there?

**Comment by TomasVotruba** [comment]
Sure :+1:

**Comment by sabbelasichon** [comment]
I didn't mean you.
