### ISSUE TITLE
AddVoidReturnTypeWhereNoReturnRector: support `@void` phpdoc instead of native `:void`

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6735]
# Feature Request

adding native return types can cause major breakage because it changes the method signature and therefore causes a bc break.

when in contrast a `@void` phpdoc-return type could be added instead, the codebase beeing changed would get the additional typeinformation (e.g. for better future static code analysis) without the risk of adding breaking changes.

especially when building libraries in which you don't have control about who might have subclassed your implementations (or you intentionally let them be subclassed) this is a major pain.

IMO the AddVoidReturnTypeWhereNoReturnRector could still be usefull in this cases if it would support adding phpdoc-based return types instead of native-return types (maybe a config option switch?)

**Comment by staabm** [comment]
> The package must provide rector upgrade path too, to fix BC breaks caused by any change.

I am not sure what you mean by that. could you elaborate?

> Feel free to open a PR



I am working on it

**Comment by TomasVotruba** [comment]
> I am not sure what you mean by that. could you elaborate?


Sure. If you add `void` to your package and it would break compatibility, you should provide upgrade `rector.php` config for your package users to fix it in their code.

Same way PHPUnit should have added upgrade config for adding `void` in their code:

```diff
-public function setUp()
+public function setUp(): void
 {
 }
```
