### ISSUE TITLE
Add the standard Rector test() to AbstractRectorTestCase

### ISSUE THREAD

**Issue by matthiasnoback** [rectorphp/rector#6736]
Creating many single-use Rector rules as part of a big refactoring project I feel there is some copy/pasting involved that isn't really necessary. Every Rector rule test has the same setup: a config file, a single test method, a dataProvider based on the Fixtures directory. For me it's okay to copy the config file, and create an empty Test class, but to copy/paste these same two methods every time shouldn't be necessary. We can just have these as default implementations in the `AbstractRectorTestCase`, thereby automatically enforcing the convention for Rector rule tests and its directories as well. What are your thoughts?

**Comment by matthiasnoback** [comment]
Of course, I added an example here: https://github.com/rectorphp/rector-src/pull/1005

**Comment by TomasVotruba** [comment]
Closing as prototype is needed, ref https://github.com/rectorphp/rector-src/pull/1005#issuecomment-988141261
