### ISSUE TITLE
Add --github-action-report option

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6742]
# Feature Request

I talked with @Ocramius today, it seems we need to add `--github-action-report` option to only show diff in github action diff format so the CI will still green, just give suggestion about the changes.

ref https://github.com/vimeo/psalm/blob/e7cd2eac0af45ec53e09e5f744894b41214449b3/src/Psalm/Report/GithubActionsReport.php

**Comment by TomasVotruba** [comment]
Closing as not priority on our feature list to keep tracker focus on active issues/bugs that needs our attention.

Feel free to send PR with it :+1:
