### ISSUE TITLE
Fatal Error due to incompatibilities with PHPStan method PHPStan\Type\Type::isSuperTypeOf()

### ISSUE THREAD

**Issue by akserikawa** [rectorphp/rector#6746]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.58  ( `bbc67f8089f688051a57b777d11c28ea55ff8fff` )|
| PHPStan version | v0.12.99|

I'm running PHP 7.1 on a Symfony 2.8 project and want to upgrade it to v3.4. This is my rector.php file:

```php
<?php

declare(strict_types=1);

use Rector\Set\ValueObject\SetList;
use Rector\Core\Configuration\Option;
use Rector\Symfony\Set\SymfonySetList;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $containerConfigurator->import(SymfonySetList::SYMFONY_30);

    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/app',
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);
};

```
 
However, when executing `bin/rector process src --dry-run` I get this fatal error:

```bash
   11/2526 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
Fatal error: Declaration of Rector\StaticTypeMapper\ValueObject\Type\ShortenedObjectType::isSuperTypeOf($type): PHPStan\TrinaryLogic must be compatible with PHPStan\Type\Type::isSuperTypeOf(PHPStan\Type\Type $type): PHPStan\TrinaryLogic in /var/www/html/vendor/rector/rector/packages/StaticTypeMapper/ValueObject/Type/ShortenedObjectType.php on line 42
```

**Fatal error: Declaration of Rector\StaticTypeMapper\ValueObject\Type\ShortenedObjectType::isSuperTypeOf($type) must be compatible with PHPStan\Type\Type::isSuperTypeOf(PHPStan\Type\Type $type): PHPStan\TrinaryLogic in /var/www/html/vendor/rector/rector/packages/StaticTypeMapper/ValueObject/Type/ShortenedObjectType.php on line 42**

Is there a fix to this? Scrolled through a lot of past issues but could not find any solution. 

Any help on this would be great, as I'm trying Rector for the first time and really have high hopes for it!

## Expected Behaviour

`--dry-run` option should output the code diff

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting and the proposed fix.

The src is development repository, see:
https://getrector.org/blog/2021/03/22/rector-010-released-with-php71-support

It is downgraded and code is removed incorrectly, then pushed to rector/rector repository.

The correct approach is to exclude the parent Type class in downgrade config for Rector: 
https://github.com/rectorphp/rector-src/blob/main/build/config/config-downgrade.php#L44

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/1009 :+1:
