### ISSUE TITLE
Incorrect behavior of RenameForeachValueVariableToMatchMethodCallReturnTypeRector

### ISSUE THREAD

**Issue by liarco** [rectorphp/rector#6753]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec30378-1191-6ad2-94f7-fb70201f17c3

```php
<?php

final class MyCollection implements \Countable, \IteratorAggregate, \ArrayAccess
{
    public function getIterator(): void
    {
        // TODO: Implement getIterator() method.
    }

    public function offsetExists($offset): void
    {
        // TODO: Implement offsetExists() method.
    }

    public function offsetGet($offset): void
    {
        // TODO: Implement offsetGet() method.
    }

    public function offsetSet($offset, $value): void
    {
        // TODO: Implement offsetSet() method.
    }

    public function offsetUnset($offset): void
    {
        // TODO: Implement offsetUnset() method.
    }

    public function count(): void
    {
        // TODO: Implement count() method.
    }
}

final class MyObject {
    private MyCollection $books;

    public function __construct()
    {
        $this->books = new MyCollection();
    }

    public function getBooks(): MyCollection
    {
        return $this->books;
    }
}

final class DemoFile
{
    public function run(): void
    {
        $myObject = new MyObject();

        foreach ($myObject->getBooks() as $book) {
            var_dump($book);
        }
    }
}
```

### Responsible rules

* `RenameForeachValueVariableToMatchMethodCallReturnTypeRector`

## Expected Behavior

In version `0.11.57` and lower the foreach variable can be called `$book`, from version `0.11.58` I'm forced to use `$myCollection`.

I'm having this issue while dealing with `Collection`s from Doctrine or `Finder` objects from `symfony/finder`.

Was this change intentional?

Thank you for your time.

**Comment by samsonasik** [comment]
You can do the following steps:

1. create new Fixture directory under https://github.com/rectorphp/rector-src/tree/600a3e9be177fa8642f3b249249ab56a85ee2e6e/rules-tests/Naming/Rector/Foreach_/RenameForeachValueVariableToMatchMethodCallReturnTypeRector, eg: `FixtureDisallowIterator`

2. create new config file under https://github.com/rectorphp/rector-src/tree/600a3e9be177fa8642f3b249249ab56a85ee2e6e/rules-tests/Naming/Rector/Foreach_/RenameForeachValueVariableToMatchMethodCallReturnTypeRector/config, eg: `configurable_disallow_iterator.php`

3. create a test file under https://github.com/rectorphp/rector-src/tree/600a3e9be177fa8642f3b249249ab56a85ee2e6e/rules-tests/Naming/Rector/Foreach_/RenameForeachValueVariableToMatchMethodCallReturnTypeRector that pointed to new `FixtureDisallowIterator` and `configurable_disallow_iterator.php` config

4. Update the code:
  a. Make rule implements ConfigurableRectorInterface, you can check example at https://github.com/rectorphp/rector-src/blob/600a3e9be177fa8642f3b249249ab56a85ee2e6e/rules/Php74/Rector/Property/TypedPropertyRector.php#L44
  b. Update sample code getRuleDefinition() to return ConfiguredCodeSample with default value
  c. Add new constant that relate with new property, eg:
        - private const ALLOW_ITERATOR = 'allowIterator';
        - private bool $allowIterator = true;
   d. update configure() method to set fallback to true value https://github.com/rectorphp/rector-src/blob/600a3e9be177fa8642f3b249249ab56a85ee2e6e/rules/Php74/Rector/Property/TypedPropertyRector.php#L177-L181
   e. make it work, check if return type is Object Type that IteratorAggregate is the super type, then skip eg:

```
$type = new \PHPStan\Type\ObjectType('IteratorAggregate');
if ($type->isSuperTypeOf($varType)->yes() && ! $this->allowIterator) {
     return null;
}
```

Possible services that can be used:

- NodeTypeResolver->getType()
