### ISSUE TITLE
Incorrect behavior of ExplicitMethodCallOverMagicGetSetRector

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#6754]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec30bf5-bb01-6362-b2ce-6f40bffcdac3

```php
<?php

final class DemoFile
{
    private $prop = [];
    
    public function __get($propName) {
        return $this->{$propName};
    }
    function __set($propName, $value) {
        return $this->{$propName} = $value;
    }
    public function getProp() {
        return $this->prop;
    }
    public function setProp(mixed $prop) {
        $this->prop = $prop;
    }
}
```

![image](https://user-images.githubusercontent.com/11526270/137883943-b53e4e4e-405f-4931-95ad-dfd4d00fcfae.png)

### Responsible rules

* `ExplicitMethodCallOverMagicGetSetRector`

## Expected Behavior

The assignment in setProp should not use the getter. That will result in "Can't use method return value in write context".
Also changing the property usage to calling the getter in the getter creates a circulair call to the same method.

**Comment by samsonasik** [comment]
Please try latest `"rector/rector": "dev-main"`, should already fixed at https://github.com/rectorphp/rector-src/pull/999
