### ISSUE TITLE
[BUG] DateTimeToDateTimeInterfaceRector

### ISSUE THREAD

**Issue by Gabb1995** [rectorphp/rector#6759]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.60             |

DateTimeToDateTimeInterfaceRector adding docblock even if there is a type, also in getters and setters.

## Minimal PHP Code Causing Issue

```
+     * @var DateTime|DateTimeImmutable
      */
-    private DateTime $processedAt;
+    private DateTimeInterface $processedAt;

-    public function getProcessedAt(): DateTime
+    /**
+     * @return DateTime|DateTimeImmutable
+     */
+    public function getProcessedAt(): DateTimeInterface
````

## Expected Behaviour

```
-    private DateTime $processedAt;
+    private DateTimeInterface $processedAt;

-    public function getProcessedAt(): DateTime
+    public function getProcessedAt(): DateTimeInterface
```

**Comment by samsonasik** [comment]
That's expected to avoid error: `Call to an undefined method DateTimeInterface::createFromFormat().` PHPStan notice see https://phpstan.org/r/6475aa0c-5fd5-4101-9a61-d7e50b0b71c9
