### ISSUE TITLE
Option::AUTO_IMPORT_NAMES degrades performance by ~300%

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#6768]
It seems that enabling `Option::AUTO_IMPORT_NAMES` slows down Rector by a disproportionate amount, making runs take about 3x longer than usual. I don't know how PHP-CS-Fixer does it, but running their refactoring tool with 100 rules takes about 10% of the time it takes Rector to run with just `AUTO_IMPORT_NAMES` enabled, which leaves me wondering if this can be optimized somehow?

**Comment by samsonasik** [comment]
@Bilge I created PR https://github.com/rectorphp/rector-src/pull/1233 to improve it, feel free to create another PR if you found part that need improvement for performance.
