### ISSUE TITLE
Replace qualifier with an import

### ISSUE THREAD

**Issue by Lenny4** [rectorphp/rector#6781]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.60              |

Rector force me to use the full namespace for the qualifier.

## Minimal PHP Code Causing Issue

```bash
$ vendor/bin/rector process src --dry-run
15) src/Entity/Spot/SpotQrcode.php:31

    ---------- begin diff ----------
@@ @@

-    #[ORM\Column(type: Types::INTEGER)]
+    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER)]
     private ?int $id = null;

     /**
    ----------- end diff -----------
```
In `SpotQrcode.php` I import: `Doctrine\DBAL\Types\Types`

```php
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types; // <-- imported here

#[ORM\Entity()]
class SpotQrcode
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;
```

## Expected Behaviour

Rector should not force me to use the full namespace of `Doctrine\DBAL\Types\Types` and either:
- `#[ORM\Column(type: Types::INTEGER)]`
- `#[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER)]`

Should be accepted.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by samsonasik** [comment]
You can use AUTO_IMPORT_NAMES option for that, see the doc for its usage https://github.com/rectorphp/rector/blob/main/docs/auto_import_names.md
