### ISSUE TITLE
Strange behavior of AddArrayParamDocTypeRector, ReturnTypeDeclarationRector

### ISSUE THREAD

**Issue by liarco** [rectorphp/rector#6789]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec3fd9f-56fc-6a82-ba5b-87a217df06b1

```php
<?php

class DemoFile
{
    private ?self $parent = null;
    
    private string $name;

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }
    
    public function setName(string $name): self
    {
        $this->name = $name;
        
        return $this;
    }
}
```

### Responsible rules

* `AddArrayParamDocTypeRector`

* `ReturnTypeDeclarationRector`

## Expected Behavior

Why isn't `self` allowed for `setParent()` and `getParent()` while it is for `setName()`? I found that setting the class as `final` allows the use of `self`, but there are situations (e.g. Doctrine entities) that do not allow `final` classes.

Also, why  is rector adding this comment:
```diff
+    /**
+     * @param \DemoFile|null $parent
+     */
    public function setParent(?self $parent): self
```

Instead of changing to:
```diff
-    public function setParent(?self $parent): self
+    public function setParent(?\DemoFile $parent): ?\DemoFile
```

Is everything working as intended?

I'm having this issue when using some SetLists in my project, but I would like to understand the logic behind this before overriding it in my config.

Thank you for your time.

**Comment by TomasVotruba** [comment]
This looks like self override bug.
Is the name property/methods needed for the bug reproduce? It would be easier to review the minimal code only.

Could you create 2 serarate demo links for each rule?
Then Rector demo will offer you to "create a test" with one click fixture test adding :)

**Comment by liarco** [comment]
Hi Tomas, thank you for your reply.

The name property is just needed to show the inconsistent behavior, but I can omit it.

What do you think about these examples?
1. https://getrector.org/demo/1ec3fe09-f75d-6f66-8b0b-73ca8e804aa7
2. https://getrector.org/demo/1ec3fe0a-4d37-63f6-a486-899a21bb210b

If they are ok I'm gonna add the tests to a new PR. ;)

**Comment by liarco** [comment]
@TomasVotruba I hope I did it right. If you need me to change anything just ask!

Thank you.

**Comment by TomasVotruba** [comment]
Looks good :) go for it 😉

**Comment by liarco** [comment]
Sorry @TomasVotruba I forgot to mention in my previous comment that I've already added the tests [here](https://github.com/rectorphp/rector-src/pull/1182) to speed up the process.
