### ISSUE TITLE
Allow to set property name in MethodCallToMethodCallRector

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#6790]
# Feature Request

Allow to set the `$propertyName` for oldType and newType in `MethodCallToMethod`:

This would look like:

```php

    $services->set(MethodCallToMethodCallRector::class)
        ->call('configure', [[
            MethodCallToMethodCallRector::METHOD_CALLS_TO_METHOD_CALLS => ValueObjectInliner::inline([
                new MethodCallToMethodCall(
                    'Sulu\\Bundle\\MediaBundle\\Media\\Manager\\MediaManagerInterface',
                    'save',
                    'Symfony\\Component\\Messenger\\MessageBusInterface $suluMessageBus',  // <-- new $suluMessageBus
                    'dispatch'
                ),
            ]),
        ]]);
```

This is inspired by the Symfony bind configuration where you can also bind a service specific to Class/Interface and the specific name: https://symfony.com/doc/5.3/service_container.html#binding-arguments-by-name-or-type. See `Psr\Log\LoggerInterface $requestLogger` in there example.
 
## Diff 

Currently following is happening:

```diff
-    public function __construct(private MediaManagerInterface $mediaManager)
+    public function __construct(private \Symfony\Component\Messenger\MessageBusInterface $suluMessageBus $messageBusInterface $suluMessageBus)
```

Expected:

```diff
-    public function __construct(private MediaManagerInterface $mediaManager)
+    public function __construct(private \Symfony\Component\Messenger\MessageBusInterface $suluMessageBus
```

**Comment by TomasVotruba** [comment]
Hi, it seems legit 👍 
Could you send PR with you proposal?

**Comment by TomasVotruba** [comment]
Closing as not an issue and suggestion is accepted. To keep focus on relevant and opened issues.

Feel free to send PR +1

**Comment by alexander-schranz** [comment]
Sure 👍  I will try to send a pull request if I'm working again on creating upgrades for @sulu.
