### ISSUE TITLE
[PHP 8.1] Add rules to cover upgrades

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6792]
See https://stitcher.io/blog/php-81-in-8-code-blocks

**Comment by Bl00D4NGEL** [comment]
I would love to help with implementing the "Array unpacking also supports string keys" addition and create a rector for it.
My current assumption is that I could replace all usages of array_merge with the array spread operator like so:
```php
$foo = ['bar' => 'baz'];
$bar = ['baz' => 'bay'];
$baz = array_merge($foo, $bar);
``` 
which would turn into
```php
$foo = ['bar' => 'baz'];
$bar = ['baz' => 'bay'];
$baz = [...$foo, ...$bar];
```

And should I either:
- add this to the [ArraySpreadInsteadOfArrayMergeRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#arrayspreadinsteadofarraymergerector) and make it automatically do the string merging if PHP version is >= 8.1 or
- add this as a configuration to that rector or
- create a new rector for it?

**Comment by TomasVotruba** [comment]
> add this to the ArraySpreadInsteadOfArrayMergeRector and make it automatically do the string merging if PHP version is >= 8.1 or

Thanks for suggestion. This seem as a the best option, as all except the key type would be  shared :+1:

**Comment by stephanvierkant** [comment]
I'm looking forward to Enum support!

**Comment by TomasVotruba** [comment]
Closing as known PHP 8.1 features are covered now.
