### ISSUE TITLE
Low - RenameForeachValueVariableToMatchExprVariableRector is removing too much "s" letter

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector#6796]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | ` 07736c1ab4d45d348d5054625499f10f97d671be` |

## Minimal PHP Code Causing Issue

```diff
@@ @@
-        foreach ($this->hasFilters as $hasFilter) {
-            $response->assertFiltersInclude($hasFilter);
+        foreach ($this->hasFilters as $haFilter) {
+            $response->assertFiltersInclude($haFilter);
         }
     }
```

Applied rules:
 * RenameForeachValueVariableToMatchExprVariableRector

## Expected Behaviour

As you can see in the example here above; the new expected variable name should be `$hasFilter` i.e. the final `s` should be removed and only the final one.

(Once again, many thanks to make Rector so amazing)

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

Could you add test fixture into responsible class? Here it is:
https://github.com/rectorphp/rector-src/blob/main/tests/Naming/ExpectedNameResolver/InflectorSingularResolverTest.php

What has to be changed there?

**Comment by cavo789** [comment]
Thanks Tomas, I'll try to understand what I need to do (if you've some sample, don't hesitate). I'll do it asap (probably tomorrow)

**Comment by samsonasik** [comment]
fixed at https://github.com/rectorphp/rector-src/pull/1222

**Comment by cavo789** [comment]
That's really great... I'm enjoying a long week-end, my idea was to look what I can do Monday without knowing exactly how to start... That's nice and cool that it's already solved. 

Thanks
