### ISSUE TITLE
Call to undefined function RectorPrefix20211109\Symfony\Component\DependencyInjection\Compiler\trigger_deprecation on extending test on 0.12

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6797]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

https://github.com/laminas/laminas-servicemanager-migration/runs/4154013167?check_suite_focus=true#step:3:385

it should correctly working or display correct error. The current error show that it produce invalid namespaced function.

**Comment by TomasVotruba** [comment]
Would including the file in `preoload.php` help? Other functions are loaded this way

**Comment by samsonasik** [comment]
I tried register into preload.php

```php
require_once __DIR__ . '/vendor/symfony/contracts/Deprecation/function.php';
```

but still error. 

On changing manually with remove namespace in the function declaration:

```diff
-namespace RectorPrefix20211109;

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
-if (!\function_exists('RectorPrefix20211109\\trigger_deprecation')) {
+if (!\function_exists('trigger_deprecation')) {
```

it seems solve it, I think on rector scoping, when namespace is only root "RectorPrefix20211109", which it originally doesn't has namespace, we can remove the namespace prefix.
