### ISSUE TITLE
Call to undefined function RectorPrefix20211109\Symfony\Component\DependencyInjection\Compiler\trigger_deprecation

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6798]
# Bug Report
updating to latest rector in CI I get the error
```
Error: Call to undefined function RectorPrefix20211109\Symfony\Component\DependencyInjection\Compiler\trigger_deprecation()

/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:60
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:47
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:77
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:45
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:86
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:45
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:77
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:45
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:42
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:29
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/Compiler/Compiler.php:87
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php:648
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/src/Kernel/RectorKernel.php:54
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/packages/Testing/PHPUnit/AbstractTestCase.php:36
/home/runner/work/rector-view-scope/rector-view-scope/vendor/rector/rector/packages/Testing/PHPUnit/AbstractRectorTestCase.php:63
```

see https://github.com/staabm/rector-view-scope/runs/4163906151?check_suite_focus=true

I guess its some kind of prefixing bug

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-src/pull/1199

Please try `"rector/rector": "dev-main"`

**Comment by TomasVotruba** [comment]
I'll relase 0.12.2

**Comment by staabm** [comment]
Thank you guys 🙏

**Comment by staabm** [comment]
fix confirmed, thx a lot

**Comment by TomasVotruba** [comment]
Thanks for confirmation :+1:

**Comment by TomasVotruba** [comment]
@samsonasik We're using the latest Rector in Symplify, it crashes PHPStan as the function is now not prefixed:
https://github.com/symplify/symplify/runs/4166694086?check_suite_focus=true

Do you have any clues?

**Comment by TomasVotruba** [comment]
@staabm This fix created another bug, so I'm trying to fix it Could try the latest `dev-main` if that still work for you?

If not, could you pass the reproducible steps?

**Comment by staabm** [comment]
using `"rector/rector": "^0.12@dev"` I am getting the errors back, which I initially reported.

see https://github.com/staabm/rector-view-scope/runs/4168102960?check_suite_focus=true

**Comment by samsonasik** [comment]
The possible solution  is remove both namespace i the namespace stmt and under function_exists.

Current latest dev-main will broke again as namespace re-added, while the caller not, even if it is in the preload

https://github.com/rectorphp/rector/commit/ebe23068dc4c3ad8e725fbb2ae46d60de3c6f713#diff-483138b478ec7484778bb7500356c1eac1109abbb27a6ecb2ebe65c6104d8a5b

**Comment by TomasVotruba** [comment]
Could you share reproducible steps so I can see the error?

**Comment by TomasVotruba** [comment]
@staabm I see it, thanks. I'm going home, I will try in tube 😊

**Comment by TomasVotruba** [comment]
The https://github.com/rectorphp/rector/commit/8566f586c9faf3ad6fb33f2698a868e7a871b428 fix looks good :+1: 

@staabm I tried it on the PR branch and passes. Could you confirm? Just run `composer update` and `vendor/bin/phpunit`

![image](https://user-images.githubusercontent.com/924196/141172564-a4612f92-bbf0-49c4-838f-42b284e5f632.png)

**Comment by samsonasik** [comment]
I confirm that it fixed it now:

![Screen Shot 2021-11-11 at 01 40 36](https://user-images.githubusercontent.com/459648/141173710-5bcec5d0-d04f-44db-98d0-f58748384685.png)

@TomasVotruba thank you.

**Comment by TomasVotruba** [comment]
Thanks! Let's :ship:  it

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector-src/commit/cd217264b75e2b7ace93c46f346d32916e2d9809

**Comment by staabm** [comment]
fix confirmed, thx again
