### ISSUE TITLE
Incorrect behavior of ImproveDoctrineCollectionDocTypeInEntityRector

### ISSUE THREAD

**Issue by mavolkmer** [rectorphp/rector#6802]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.3     |
| Installed as   | composer dependency  |

rector tries to refactor phpdoc of adder-methods with already set typehint like that:
```
@@ -26,6 +26,9 @@
         return $this->organizers;
     }
 
+    /**
+     * @param \App\Entity\Organizer[]|\Doctrine\Common\Collections\Collection<int, \App\Entity\Organizer> $organizer
+     */
     public function addOrganizer(Organizer $organizer): self
     {
```
## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec42f47-50b9-67ae-976d-a39026359381

```php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Location
{
    /**
     * @ORM\OneToMany(targetEntity=Organizer::class, mappedBy="location")
     *
     * @var Organizer[]|Collection<int, Organizer>
     */
    private Collection $organizers;


    /**
     * @return Collection<int, Organizer>|Organizer[]
     */
    public function getOrganizers(): Collection
    {
        return $this->organizers;
    }

    public function addOrganizer(Organizer $organizer): self
    {
        if (!$this->organizers->contains($organizer)) {
            $this->organizers[] = $organizer;
            $organizer->setLocation($this);
        }

        return $this;
    }

    public function removeOrganizer(Organizer $organizer): self
    {
        if ($this->organizers->contains($organizer)) {
            $this->organizers->removeElement($organizer);
            if ($organizer->getLocation() === $this) {
                $organizer->setLocation(null);
            }
        }

        return $this;
    }
}
```

### Responsible rules

* `ImproveDoctrineCollectionDocTypeInEntityRector`

## Expected Behavior

rector should just pass that rule

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?

This woud be the responsible test case:
https://github.com/rectorphp/rector-doctrine/blob/main/tests/Rector/Property/ImproveDoctrineCollectionDocTypeInEntityRector/ImproveDoctrineCollectionDocTypeInEntityRectorTest.php

**Comment by mavolkmer** [comment]
Thank you for your awesome work and your quick response; will have a look later

**Comment by TomasVotruba** [comment]
Thank you :hugs:
