### ISSUE TITLE
PHP Fatal Error: Cannot redeclare trigger_deprecation()

### ISSUE THREAD

**Issue by freiondrej-lmc** [rectorphp/rector#6807]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.60             |

Hello, when loading rector (in v0.11.60), there's a bad check in this file: https://github.com/rectorphp/rector/blob/0.11.60/vendor/symfony/deprecation-contracts/function.php It should have the namespace RectorPrefix20211020, but it has none. I checked issues here and it is probably fixed in v 0.12, but we cannot upgrade to it now as it uses newer phpstan.
It conflicts with symfony/contracts in our project.
Could you please release a patch version for this?

**Comment by TomasVotruba** [comment]
The best way is to upgrade, as we don't provide support for older version. It's pretty easy and I believe the PHPStan will be fixed soon 👍
