### ISSUE TITLE
DoctrineAnnotationClassToAttributeRector doesn't do anything at all

### ISSUE THREAD

**Issue by mennovanhout** [rectorphp/rector#6811]
# Bug Report

| Subject        | Details                                                         |
| :Doctrine annotations to attributes is not working | :I'm trying to change doctrine annotations in attributes|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

I'm trying to upgrade my doctrine annoations to attributes in the latest version of symfony/api-platofrm/php8.0.2

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec486fb-62f3-60d0-bde7-fbe7811d18f3

## Expected Behaviour

The files are not chaning

```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_80);

    $services->set(DoctrineAnnotationClassToAttributeRector::class)
        ->call('configure', [[
            DoctrineAnnotationClassToAttributeRector::REMOVE_ANNOTATIONS => true,
        ]]);
};
```

Config

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Company
 *
 * @ORM\Table(name="company", indexes={@ORM\Index(name="company_fi_e84825", columns={"parent_id"})})
 * @ORM\Entity
 */
class Company
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    private $name;
```

php file

` vendor/bin/rector process src/Entity/Company.php --clear-cache --debug -vvv --dry-run`

command

```
bash-5.1# vendor/bin/rector process src/Entity/Company.php --clear-cache --debug -vvv --dry-run
[parsing] src/Entity/Company.php
[refactoring] src/Entity/Company.php
    [applying] Rector\Php80\Rector\Class_\DoctrineAnnotationClassToAttributeRector
[post rectors] src/Entity/Company.php
    [post rector] Rector\PostRector\Rector\NodeToReplacePostRector
    [post rector] Rector\PostRector\Rector\NodeAddingPostRector
    [post rector] Rector\PostRector\Rector\PropertyAddingPostRector
    [post rector] Ssch\TYPO3Rector\Rector\PostRector\FullQualifiedNamePostRector
    [post rector] Rector\PostRector\Rector\NodeRemovingPostRector
    [post rector] Rector\PostRector\Rector\ClassRenamingPostRector
    [post rector] Rector\PostRector\Rector\NameImportingPostRector
    [post rector] Rector\PostRector\Rector\UseAddingPostRector
[print] src/Entity/Company.php
```

output

**Comment by samsonasik** [comment]
You may looking for `Rector\Doctrine\Set\DoctrineSetList::DOCTRINE_ORM_29` set list, ref https://getrector.org/demo/1ec491e7-0a7e-65d4-a2be-993eca619007

**Comment by OskarStark** [comment]
https://getrector.org/demo/1ec4aa59-cbbf-6e70-a4a2-f3753516aeef

I updated the example because K had this issue a week ago.

I migrated to Attributes, but the EntityListeners were not converted to an Attribute, the stay as an annotation which will not be used afterwards... and resulted in a bug on production.

Maybe you can double check @samsonasik ?

**Comment by TomasVotruba** [comment]
The `EntityListener` is missing in the config. See https://github.com/rectorphp/rector-doctrine/blob/00cfc4346a95f9f976647c921138ac550331e06c/config/sets/doctrine-annotations-to-attributes.php#L15

**Comment by OskarStark** [comment]
Thank you @TomasVotruba 

I was on a phone 📱

**Comment by TomasVotruba** [comment]
No problem :)

Could you send PR to complete it?

**Comment by OskarStark** [comment]
Will do tomorrow 👍🏻
