### ISSUE TITLE
Issues while upgrade from 7.3 to 7.4

### ISSUE THREAD

**Issue by livinglegend13** [rectorphp/rector#6815]
I am trying to use this package for the first time. I want to upgrade my codebase from PHP 7.3 to 7.4 with Laravel Set 80

Here is my rector.php

$containerConfigurator->import(LaravelSetList::LARAVEL_80);
   $containerConfigurator->import(SetList::PHP_74);

   // $containerConfigurator->import(SetList::CODE_QUALITY);
   $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_73);

When I run the rector process it throws me error message 👍 
[WARNING] Your project requires min PHP version "7.3".                                                                 
                                                                                                                        
           14 Rector rules defined in your configuration require higher PHP version and will not run,                   
           to avoid breaking your codebase, use -vvv for detailed info.    

I tried updating composer.json file PHP require to 7.4 from 7.3. And when I run the rector process dry run it does nothing although the warning goes away and says rector is done.

Still cant figure out what I am doing wrong here.

**Comment by samsonasik** [comment]
You need to set php version feature to php 7.4:

```php
$parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);
```

**Comment by livinglegend13** [comment]
> You need to set php version feature to php 7.4:
> 
> ```
> $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);
> ```

I actually did that and the output is [OK] Rector is done.  It does not do any changes. Do I have to run it by registering and iterating through single rule or is there any other thing I need to add?

**Comment by samsonasik** [comment]
You may missing the path config:

```
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [__DIR__ . '/src']);
```

or you can manually run into target directory:

```bash
vendor/bin/rector process src
```

Feel free to create failing test case or reproducible repository if you found a bug.

**Comment by livinglegend13** [comment]
I do have this too. I will create a bug report. my current rector.php file contains:

<?php

declare(strict_types=1);
use Rector\Laravel\Set\LaravelSetList;
use Rector\Core\ValueObject\PhpVersion;

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src'
    ]);

    // Define what rule sets will be applied
//    $containerConfigurator->import(SetList::DEAD_CODE);

$containerConfigurator->import(LaravelSetList::LARAVEL_80);
   $containerConfigurator->import(SetList::PHP_74);

   // $containerConfigurator->import(SetList::CODE_QUALITY);
   $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);


};
