### ISSUE TITLE
Incorrect behavior of ChangeReadOnlyVariableWithDefaultValueToConstantRector

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector#6818]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | eaf1f250031db227ef2c623c16753a3642bfa2bb      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec49451-df66-6316-9733-3b3eb9ff18b0

```php
<?php

final class DemoFile
{
    public function run(string $id): array
    {
        $data                = [
            'url' => "/$id.pdf",
        ];

        return $data;
    }
}
```

### Responsible rules

* `ChangeReadOnlyVariableWithDefaultValueToConstantRector`

## Expected Behavior

As you can see, the `$data` variable in the `run()` function is using the parameter `$id`.  The array shouldn't be considered, here, as a constant.

The proposed code break the code.

```diff
+    /**
+     * @var array<string, string>
+     */
+    private const DATA = [
+        'url' => "/$id.pdf",
+    ];
```

For information, I also use `\Rector\CodingStyle\Rector\Encapsed\EncapsedStringsToSprintfRector::class` and then the result is even worst: the `sprintf()` has been used ... in a constant which is not correct syntactically.

```diff
+    /**
+     * @var array<string, string>
+     */
+    private const DATA = [
+        'url' => sprintf('/%d.pdf', $id),
+    ];
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by cavo789** [comment]
Hello Tomas,

Can you confirm if https://github.com/rectorphp/rector-src/pull/1282 is what you were asking for?

Thanks!
