### ISSUE TITLE
[Symfony 5.4] Make sure nested attributes are avialable since 

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6820]
Should not run on a lower version. We might add somthing similar to `PhpVersionProvider`, e.g. `PackageVersionProvider` and check if the project has at least `symfony/*` 5.4 in the `composer.json`

See https://twitter.com/wouterjnl/status/1462039339840507914

**Comment by samsonasik** [comment]
it seems duplicate with https://github.com/rectorphp/rector/issues/6821, I am closing it.
