### ISSUE TITLE
Change one Annotation to another Annotation

### ISSUE THREAD

**Issue by rvanlaak** [rectorphp/rector#6824]
First of all, thanks for the talk at PHPWVL!

# Feature Request

The wild idea; allowing "zero-effort" switching from Psalm to PHPStan (or the other way around). A start for achieving this would be by being able to rewrite one annotation to another.
 
## Diff 

```diff
-/* @phpstan-ignore-line */
+/* @psalm-suppress ... */
```

**Comment by TomasVotruba** [comment]
Thank you :+1: 

The most value and fun comes from great questions, thanks for one of those :)

I was checking the existing rules, what about this one?
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renameannotationrector

**Comment by rvanlaak** [comment]
Yes, the rename Rector would be perfect. Does it also allow hooking in an anonymous function to alter the data related to the annotation?

**Comment by TomasVotruba** [comment]
I'm not sure, could you try it?

**Comment by rvanlaak** [comment]
It does not allow hooking into renaming process, it only allows configuring `renamed_annotations_in_types`: https://github.com/rectorphp/rector/blob/main/rules/Renaming/Rector/ClassMethod/RenameAnnotationRector.php

In addition it seems renaming is limited annotations within a certain class type: https://github.com/rectorphp/rector/blob/main/rules/Renaming/ValueObject/RenameAnnotation.php

**Comment by TomasVotruba** [comment]
The Rector philosophy is close to Unix one. Many speciliazed rules connected together. In first case, you can use one rule to rename annotation, then create another to handle next change.

In 2nd case, the rule can be modified to support simple annotation renaming.

**Comment by TomasVotruba** [comment]
I've extended the annotation rename in https://github.com/rectorphp/rector-src/pull/1341

**Comment by rvanlaak** [comment]
Great! If I have time I will start experimenting whether having such an `psalm <--> phpstan` script would be feasable.
