### ISSUE TITLE
[PHP8.0] FinalPrivateToPrivateVisibilityRector does not run on PHP7 codebase

### ISSUE THREAD

**Issue by fsok** [rectorphp/rector#6828]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |ebd553fe45184cefec5844e075a0af35ab3a9375|

FinalPrivateToPrivateVisibilityRector won't run when the PHP version is not set to at least PHP 8.0.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec4d028-bc46-6508-8b64-7f4ab4c51fcd

fails with a syntax error in demo, but fails with this message at my machine:

```
[WARNING] Your project requires min PHP version "7.4".                                                                 
                                                                                                                        
           1 Rector rules defined in your configuration require higher PHP version and will not run,                    
           to avoid breaking your codebase, use -vvv for detailed info.       
```

## Expected Behaviour

Because removing the final modifier is not a feature that can't be used in PHP versions < 8 the rule should be processed.

**Comment by samsonasik** [comment]
`FinalPrivateToPrivateVisibilityRector` is part of PHP 8.0 setlist, your project require php 7.4, so it won't run. In PHP 7.x, it will be ok to have `final` in private method, so it skipped there https://3v4l.org/5bPIg.
