### ISSUE TITLE
Incorrect behavior of ChangeMethodVisibilityRector

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#6829]
Just started using `SymfonyLevelSetList::UP_TO_SYMFONY_54` so I missed something in Symfony 4.2 :)

# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec4d133-d311-68a8-84ae-fb813cd6e506

```php
<?php

declare(strict_types=1);

namespace App\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class DateTimeTypeExtension extends AbstractTypeExtension
{
    public function configureOptions(OptionsResolver $resolver) : void
    {
        $resolver->setDefaults([
            'date_widget' => 'single_text',
            'time_widget' => 'single_text',
            'html5' => true,
        ]);
    }

    static function getExtendedTypes() : iterable
    {
        yield DateTimeType::class;
    }
}
```

### Responsible rules

* `ChangeMethodVisibilityRector`

## Expected Behavior

`getExtendedTypes` was a public method and it should stay like that. For what it's worth, `\Symfony\Component\Form\FormTypeExtensionInterface::getExtendedTypes` (used by `AbstractTypeExtension`) is a **public static** method.

**Comment by TomasVotruba** [comment]
Hi, thanks for sharing the issue.

From the demo I see there is `public` completed, so nothing really changed. Could you maybe share minimal diff what is happening now and what you expect to happen?

**Comment by TomasVotruba** [comment]
Interesting. Which of these rules is responsible?
Could you create a test case for it so we have it covered?
