### ISSUE TITLE
Auto-importing classes imports them in the wrong spot

### ISSUE THREAD

**Issue by tchin25** [rectorphp/rector#6833]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.5           |

## Minimal PHP Code Causing Issue

See: https://getrector.org/demo/1ec4d711-41f9-68a0-ae8c-59eb58bb67e4

Runing Rector with AUTO_IMPORT_NAMES enabled, this:
```php
<?php
/**
 * License
 */

use Foobar\A;

/**
 * Docblock
 */
final class DemoFile
{
    public function run()
    {
        new A();
        new Foobar\B();
    }
}
```
Turns into:

```php
<?php
use Foobar\B;
/**
 * License
 */

use Foobar\A;

/**
 * Docblock
 */
final class DemoFile
{
    public function run()
    {
        new A();
        new B();
    }
}

```

See #6831 where I described the same problem with a different output when on Rector v0.11.60

## Expected Behaviour

Should insert new import statement below top level doc block with the other imports.

```php
<?php
/**
 * License
 */

use Foobar\A;
use Foobar\B;

/**
 * Docblock
 */
final class DemoFile
{
    public function run()
    {
        new A();
        new B();
    }
}
```

**Comment by tchin25** [comment]
HI! Thank you for doing this. I really appreciate it. However, I did find an edge case that I feel like should be addressed:

The test fixtures are namespaced to their specific issue, which would be fine in most cases, but I saw that the patch relies on the namespace statement to detect where to put the use statements, so files in the global namespace would still fail.
```php
/**
 * License Header
 */

/**
 * Docblock
 */
class DemoFile 
{
    public function run()
    {
        new Foobar\A();
    }
}
```
Would still fail like:
```php
use Foobar\A;
/**
 * License Header
 */

/**
 * Docblock
 */
class DemoFile 
{
    public function run()
    {
        new A();
    }
}
```
And this:
```php
/**
 * License Header
 */

use Foobar\A;

/**
 * Docblock
 */
class DemoFile 
{
    public function run()
    {
        new A();
        new Foobar\B();
    }
}
```
Would still fail like:
```php
use Foobar\B;
/**
 * License Header
 */

use Foobar\A;

/**
 * Docblock
 */
class DemoFile 
{
    public function run()
    {
        new A();
        new B();
    }
}
```

**Comment by TomasVotruba** [comment]
I'm not sure this is worth optimizing, as there is no standard to follow about file docs. That's why php-parser is putting them ro random places :)

I recommend using comments bound only to specific PHP line and use namespaces. That's the only way I found php-parser can locate them correctly 👍
