### ISSUE TITLE
[DeadCode] Remove private method unused param + args

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6834]
See https://github.com/rectorphp/rector-src/pull/1308/commits/b924e1ea891edb0ad0f77bc81c2185d96cc0c778

**Comment by samsonasik** [comment]
@TomasVotruba there is `RemoveUnusedPrivateMethodParameterRector` rule for it https://github.com/rectorphp/rector-src/blob/main/rules/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector.php that currently doesn't cover in between

https://github.com/rectorphp/rector-src/blob/9f7b0e3f5cfc4b73c76dbec1489e8ca135e4e5c1/rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/Fixture/in_between_parameter.php.inc#L5

I think the rule can be improved for it so it remove its parameter, and its in the caller as method call as well.
