### ISSUE TITLE
Incorrect behavior of RenameClassRector for Generics

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#6835]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

I'm replacing a Interface with a class the following way:

See https://getrector.org/demo/1ec4e139-393d-60fe-b6b0-a9721663c5de

```php
<?php

declare(strict_types=1);

namespace App\Discount\Domain\Repository;

use App\Discount\Domain\Model\SynchronizeBridgeInterface;

/**
 * @template T of SynchronizeBridgeInterface
 */
interface SynchronizeBridgeRepositoryInterface
{
    /**
     * @param T $bridge
     */
    public function add(SynchronizeBridgeInterface $bridge): void;

    /**
     * @param array{
     *     source: string,
     *     sourceId: string,
     * } $filters
     *
     * @return T|null
     */
    public function findOneBy(array $filters): ?SynchronizeBridgeInterface;
}
```

### Responsible rules

* `RenameClassRector`

## Expected Behavior

The generic:

```php
/**
 * @template T of SynchronizeBridgeInterface
 */
```
 
Should also be refrectored to:

```php
/**
 * @template T of SynchronizeBridge
 */
```

Same does happen for:

```
/**
 * @extends SynchronizeBridgeRepositoryInterface<SynchronizeCashbackBridgeInterface>
 */
```

when try to refractor `SynchronizeCashbackBridgeInterface` -> `SynchronizeCashbackBridge`

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by alexander-schranz** [comment]
Added here: https://github.com/rectorphp/rector-src/pull/1309
