### ISSUE TITLE
rector adding php open/close tags in view files

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6836]
given a view file with contents
```php
	<div>
	<?php echo check_box($auktion, 'skipnetzprovider', '1', "class=checkbox onclick=\"getAngebotHTML($('angebot').value);\""); ?>
	<b class="caption">Provider und Netz nicht anzeigen</b> (Im gesamten Template)
	<br><br>
	</div>
```

running rector over it produces "unnecessary" changes.
rector adds php starting/ending tags in this files.

this unnecessary changes create noise in bigger PRs

I created a [repo which reproduces this case](https://github.com/staabm/rector-repro1)

Steps
-----

- `gh repo clone staabm/rector-repro1`
- `composer install`
- `vendor/bin/rector process -n`

**expected result**
- rector might change whitespaces / intentation.. AFAIK its technically hard to keep all whitespaces -> thats fine
- rector should not add `<?php ?>` at the beginning of the file
- rector should not add a trailling `<?php`

**actual result**

```diff
+<?php
+
+?>

        <div>
-       <?php echo check_box($auktion, 'skipnetzprovider', '1', "class=checkbox onclick=\"getAngebotHTML($('angebot').value);\""); ?>
+       <?php
+echo check_box($auktion, 'skipnetzprovider', '1', "class=checkbox onclick=\"getAngebotHTML($('angebot').value);\"");
+?>
        <b class="caption">Provider und Netz nicht anzeigen</b> (Im gesamten Template)
        <br><br>
-       </div>
+       </div><?php
```

**Comment by staabm** [comment]
In case someone could give me some pointers on where to start analyzing, I could try tominvestigate myself

**Comment by TomasVotruba** [comment]
Class responsible for printing code back is `BetterStandardPrinter`. It will be in one of its methods.

Tip: Analyse just one file, it will make debugging much easier:

```bash
vendor/bin/rector process src/SingleFile.php --debug
```

**Comment by staabm** [comment]
just leaving some notes here of my ongoing analysis

php-parser already contains code, which should prevent the php tags which are added in the repro case
https://github.com/nikic/PHP-Parser/blob/f09f22760ef1b292c3312105532c8e84e80cce19/lib/PhpParser/PrettyPrinterAbstract.php#L228-L235

it seems this code is only used in the pretty-print case and rector is using formatPreserving printing.
