### ISSUE TITLE
Analyze error: Class was not found - a library class alias using class_alias()

### ISSUE THREAD

**Issue by FluffyDiscord** [rectorphp/rector#6841]
# Question
Hello, I am using a PHP library which adds class aliases such as
```php
class_exists('hQuery_Element', false) or class_alias('duzun\\hQuery\\Element', 'hQuery_Element', false);
```
and whenever I run rector I get the following error
```php
[ERROR] Could not process "src/myFile.php" file, due to:                             
         "Analyze error: "Class duzun\hQuery\hQuery_Element was not found while trying to analyse it -    
         discovering symbols is probably not configured properly.". Include your files in                 
         "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" or "$parameters->set(Option::BOOTSTRAP_FILES, 
         [...]);" in "rector.php" config.  
```
I am not sure what I should do is my situation. I am not using these aliases, but the library does and it breaks file analyzing.

**Comment by TomasVotruba** [comment]
Hi, thanks for sharing your issue.
Could you create minimal repository with failing example?

**Comment by FluffyDiscord** [comment]
> Hi, thanks for sharing your issue. Could you create minimal repository with failing example?

Sure, here it is: https://github.com/FluffyDiscord/example-repo
Steps to reproduce:
1. `git clone https://github.com/FluffyDiscord/example-repo`
2. `cd example-repo`
2. make sure you are running php 8.0.9 or greater
3. `composer install`
4. `vendor/bin/rector process src`

I have left the `rector.php` exactly as I have it in my project and took one command from it and simplified it so only the important failing part is left.

**Comment by FluffyDiscord** [comment]
Can I somehow ignore this error ? Like, option to ignore the class imports of that library so the rest of my class gets reformated ?

**Comment by TomasVotruba** [comment]
From the top of my head, you can create local mock of this class and add it to `BOOTSTRAP_FILES` option.

**Comment by samsonasik** [comment]
@FluffyDiscord other alternative is by tweak with `"files"` config in your composer.json:

```bash
    "autoload-dev": {
        "files": [
            "vendor/duzun/hquery/src/hQuery/Element.php"
        ]
    }
```

then run: 

```bash
 composer update
```

then finally run rector: 

```bash
vendor/bin/rector process src
```

I tried that and that seems working ok (deprecated notice is unrelated to rector):

![Screen Shot 2021-12-12 at 22 12 42](https://user-images.githubusercontent.com/459648/145717971-f42a9dfa-cad2-4bfc-9227-d2533f4eb740.png)
