### ISSUE TITLE
Option::SKIP not skipping

### ISSUE THREAD

**Issue by gander** [rectorphp/rector#6842]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.5          |
| Installed as      | composer dependency |

App code is located in `/www/localhost`, and directory `/www/localhost/.dev` must be excluded. That happend:

```
In RecursiveDirectoryIterator.php line 93:
                                                                                                                         
  RecursiveDirectoryIterator::__construct(/www/localhost/.dev/mysql/mig/sys): failed to open dir: Permission denied  
                                                                                                                         

In RecursiveDirectoryIterator.php line 42:
                                                                                                                         
  RecursiveDirectoryIterator::__construct(/www/localhost/.dev/mysql/mig/sys): failed to open dir: Permission denied  
```

## Minimal PHP Code Causing Issue
```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);
    $parameters->set(Option::PATHS, [__DIR__]);
    $parameters->set(Option::SKIP, [
        __DIR__ . '/.dev/',
        __DIR__ . '/.dev/*',
        __DIR__ . '/.dev/**',
    ]);

    $containerConfigurator->import(LaravelSetList::LARAVEL_60);
};
```

## Expected Behaviour

Should be doing its job

**Comment by TomasVotruba** [comment]
The SKIP option is not even activated, as it the finder fails on incorrect access rights. Probably Docker/another container metadata.

That's because of the global value. The `$parameters->set(Option::PATHS, [__DIR__]);` is not a good idea, as it includes everything globally. Hidden files, directories, vendor etc. Instead use specific directories.

```php
$parameters->set(Option::PATHS, [
    __DIR__ . '/src',
    __DIR__ . '/packages',
]);
```
