### ISSUE TITLE
ReadOnlyPropertyRector should not add readonly keyword to class properties which do not have native type in parent

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#6844]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.5             |

If a class has property without a native type, any child class can't declare the native type. PHP doesn't allow it. Also `readonly` is not allowed without native type. So Rector should not try to add `readonly` to child class property.

## Minimal PHP Code Causing Issue

```php
<?php

class Foo
{
    /** @var array */
	public $foo;
}

class Bar extends Foo
{
    /** @var array */
	public $foo = ['foo', 'bar'];
}
```

## Expected Behaviour
Rector should not add `readonly` to `foo` property in class Bar.

**Note:** Demo site seems to run on PHP 8.0 still. So I couldn't manage to run the rector there. In any case this is the link: https://getrector.org/demo/1ec51e77-1a28-6c06-9386-1f9089bacc07

**Comment by canvural** [comment]
Also maybe a separate bug, `readonly` keyword should not be added if the property has a default value.

**Comment by samsonasik** [comment]
it seems already solved now, feel free to provide failing test case if you found other issue, thank you.
