### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector

### ISSUE THREAD

**Issue by burned42** [rectorphp/rector#6846]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.5      |
| Installed as   | composer dependency  |

The rule `ReadOnlyPropertyRector` adds `readonly` to a property that has a default value which results in this error:

> PHP Fatal error:  Readonly property DemoFile::$test cannot have default value in /var/www/html/src/DemoFile.php on line 5

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec54eaf-4da0-64ea-bf92-f110ddee1f10

```php
<?php

final class DemoFile
{
    public ?string $test = null;
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

I'd expect rector to not break the code, so I guess the rule should skip such properties, right?

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-src/pull/1355, please try latest `"rector/rector": "dev-main"`

**Comment by burned42** [comment]
@samsonasik yes, indeed it looks like this is already solved but just not released with a version tag yet :+1: 

waiting for the next release then, thanks :)
