### ISSUE TITLE
PHP 8.0: Incompatible method signatures not fixed

### ISSUE THREAD

**Issue by norgeindian** [rectorphp/rector#6851]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12.5 (invoke `vendor/bin/rector --version`)             |

I would like to update some legacy code from PHP 7.4 to PHP 8.0. To do this, I chose the set list for PHP 8.0 and ran it on my code base. As PHP 8.0 now [generates fatal errors for incompatible method signatures](https://wiki.php.net/rfc/lsp_errors) (in PHP 7 that was silently ignored) I would have expected, that issues like this are found and solved. But unfortunately they are not handled at all.

## Minimal PHP Code Causing Issue

```
class A {
    public function execute($foo)
    {
        // original code
    }
}
class B extends A{
    public function execute()
    {
    // adapted code
    }
}
```

## Expected Behaviour

I would expect, that Rector changes this and adds the argument from the parent class, instead it's completely skipped.

**Comment by TomasVotruba** [comment]
Thank you. Could you share RFC from PHP 8.0 that is related to this? Ideally with 3v4l.org example

**Comment by norgeindian** [comment]
@TomasVotruba , I linked it in the description (https://wiki.php.net/rfc/lsp_errors) or do you mean something else?
And here is your example https://3v4l.org/r3PZP#v8.0.13
As you can see, this was just a warning in PHP 7: https://3v4l.org/r3PZP#v7.4.26

Please let me know, if you need further information.

**Comment by norgeindian** [comment]
@TomasVotruba , thanks a lot for this quick fix. Awesome support here.
I just tested it and unfortunately I found an issue, which leads to an error.
If the parent argument has a default value, you get the following error:
```
%PHP Notice:  Undefined offset: -1 in /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 218
Notice: Undefined offset: -1 in /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 218
PHP Fatal error:  Uncaught TypeError: Return value of PhpParser\Internal\TokenStream::getIndentationBefore() must be of the type int, null returned in /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:218
Stack trace:
#0 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(523): PhpParser\Internal\TokenStream->getIndentationBefore()
#1 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(21): PhpParser\PrettyPrinterAbstract->p()
#2 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(483): PhpParser\PrettyPrinter\Standard->pParam()
#3 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(504): PhpParser\PrettyPrinterAbstract->pFallback()
#4 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(827): PhpParser\PrettyPrinterAbstract->p()
#5 /vendor/rector/re in /var/www/mw/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 218
Fatal error: Uncaught TypeError: Return value of PhpParser\Internal\TokenStream::getIndentationBefore() must be of the type int, null returned in /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:218
Stack trace:
#0 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(523): PhpParser\Internal\TokenStream->getIndentationBefore()
#1 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(21): PhpParser\PrettyPrinterAbstract->p()
#2 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(483): PhpParser\PrettyPrinter\Standard->pParam()
#3 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(504): PhpParser\PrettyPrinterAbstract->pFallback()
#4 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(827): PhpParser\PrettyPrinterAbstract->p()
#5 /vendor/rector/re in /var/www/mw/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 218
```
So please be so kind and check again with the following code example:
```
class A {
    public function execute($foo = true)
    {
        // original code
    }
}
class B extends A{
    public function execute()
    {
    // adapted code
    }
}
```
Sorry, did not know, that this might make a difference, that's why I did not include it in my initial request.
As soon as I remove the default value, the check does exactly what it should do. Thanks again

**Comment by samsonasik** [comment]
Please add failing fixture at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector/Fixture for it, you can check other fixture for copy paste behavior of fixture.

**Comment by norgeindian** [comment]
@samsonasik , please be so kind and take a look at my fixture and source file at https://github.com/rectorphp/rector-src/pull/1450.
Is that okay like this or shall I adapt something?
