### ISSUE TITLE
DowngradeUseFunctionRector with AUTO_IMPORT_NAMES

### ISSUE THREAD

**Issue by Hakihiro** [rectorphp/rector#6853]
# Question
Is there a way to disable AUTO_IMPORT_NAMES for function?

If i enable AUTO_IMPORT_NAMES (that's what I want): 

```php
Sentry\captureMessage();
```

Is always set to:
```php
use function Sentry\captureMessage;
captureMessage();
```
even if i add the `$services->set(DowngradeUseFunctionRector::class);`

Is there a way to do this actually?

Or maybe a new option like : `$parameters->set(Option::IMPORT_SHORT_FUNCTION, false);` ?

**Comment by TomasVotruba** [comment]
Hi, thanks for question.

That's not possible ATM. Currently you can choose imports FQN, imports docs and imports short class names.

See the docs:
https://github.com/rectorphp/rector/blob/main/docs/auto_import_names.md
