### ISSUE TITLE
Annotation parsing issue

### ISSUE THREAD

**Issue by oojacoboo** [rectorphp/rector#6859]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | f068fd98590a7ece4bee280ebb13224562b6cff3             |

When running rector, the following exception is thrown.  However, it's important to note that version 1.2.0 of `phpstan` does not produce any errors on this class.  Also, a single quote `'` doesn't fix the parsing issue.

Why is `FROM` being passed as a "token" to the `phpdoc-parser` `TokenIterator`?  But even still, the parser isn't properly handling the syntax.

```
Fatal error: Uncaught PHPStan\PhpDocParser\Parser\ParserException: Unexpected token "FROM", expected ')' at offset 104 in phar:///./app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php:141
```

The following annotation is added on a class declaration
```php
/**
 * @MultiTenancy(filters={
 *      @MultiTenancy\Filter(
 *          filter="$this.unit_id IN(
 *              SELECT id
 *              FROM unit
 *              WHERE company_id = {companyId}
 *          ) OR $this.legal_entity_id IN(
 *              SELECT id
 *              FROM legal_entity
 *              WHERE company_id = {companyId}
 *          ) OR $this.payment_profile_id IN(
 *              SELECT id
 *              FROM payment_profile
 *              WHERE user_id = {userId}
 *          )"
 *      )
 * })
 */
```

## Expected Behaviour

The parsing of the annotation is incorrect.  The `Filter` property should be treated as a string.

**Comment by samsonasik** [comment]
Please provide failing test case for it, You can create under 

https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector

with update config at 

https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php

**Comment by oojacoboo** [comment]
@samsonasik https://github.com/rectorphp/rector-src/pull/1515
