### ISSUE TITLE
In Finder.php line 598:    The "src" directory does not exist.

### ISSUE THREAD

**Issue by awesome1128** [rectorphp/rector#6860]
Hi nice to meet you.

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |
Rector f068fd98590a7ece4bee280ebb13224562b6cff3

I have old CakePHP code, I think it's running on CakePHP 2.x and PHP 5, so I am going to upgrade it using rector. Just before, I found your repository on google.
But when I try to run "vendor/bin/rector process src --dry-run", I get an error below.

In Finder.php line 598:    The "src" directory does not exist.
Please help me.
Thank you.

**Comment by samsonasik** [comment]
"src" is directory to be processed, if you don't have "src" directory, you may need to run into other directory that exists, eg:

```
vendor/bin/rector proces app
```

You can configure paths to apply as well via rector.php config, please read the doc for Option::PATHS usage 

https://github.com/rectorphp/rector#configuration

**Comment by awesome1128** [comment]
![image](https://user-images.githubusercontent.com/56351793/145709412-9285a14f-3513-4da0-b53c-6bcf74c9ab0b.png)

**Comment by awesome1128** [comment]
It does not make sense. Do I need to clone this repository in the root directory of my project or not?
Please let me know.
Thanks.

**Comment by samsonasik** [comment]
You can require rector inside cakephp application, and run inside it.

If you have rector outside project, you may point to project dir, but may need to add project autoload file, eg:

```bash
vendor/bin/rector process ../project/app -a ../project/vendor/autoload.php --dry-run
```

**Comment by awesome1128** [comment]
Ah, I see.
I will try to do like that and let you know.
I have one question. As I said, I have an old CakePHP application(I think PHP version is 5), so I want to upgrade it with PHP 7.4
Is it possible with this rector app?
Thank you.

**Comment by samsonasik** [comment]
Please try yourself, and come back to us with the specific reproducible issue / repository / failing test case if you found it.

**Comment by awesome1128** [comment]
Sure, I am trying now, but I am just wondering if it's possible.
---------------------------
I have one question. As I said, I have an old CakePHP application(I think PHP version is 5), so I want to upgrade it with PHP 7.4
Is it possible with this rector app?

**Comment by samsonasik** [comment]
Rector has config set that can upgrade from php 5.2 into php 8.1, see https://github.com/rectorphp/rector-src/blob/main/config/set/php52.php.

Technically, if you run rector on php >=7.1, that's theoritically will works:

```php
<?php

declare(strict_types=1);

use Rector\Set\ValueObject\LevelSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(LevelSetList::UP_TO_PHP_74);

    // other config
};
```


Try with `--dry-run` first to see if the diff correct, try without `--dry-run` to apply change.

You can learn more from the docs https://github.com/rectorphp/rector/tree/main/docs

I am closing this as answered. Please create issue with reproducible failing test case if you found it.
