### ISSUE TITLE
RenameClassRector problems when docblock followed by attribute

### ISSUE THREAD

**Issue by PhilETaylor** [rectorphp/rector#6861]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 77f2def080746f6d6d9a0dfc8d8a723d03c82f22          |
| PHP version | 8.1.0          |

Trying to do a simple rename of a deprecated class with 

```php
    $services->set(RenameClassRector::class)
        ->configure([
            // https://github.com/doctrine/dbal/blob/master/UPGRADE.md#deprecated-dbalexception
            'Doctrine\DBAL\DBALException' => 'Doctrine\DBAL\Exception'
        ]);
```

## Minimal PHP Code Causing Issue

The result is that you end up with a duplicated docblock 

https://getrector.org/demo/1ec5b954-5e90-66f0-8d07-efa05ffbaaf2

## Expected Behaviour

Rector is working correct and renaming the `@throws` tag in the docblock when there is no Attribute (in my case a Symfony Route Attribute, the second method in the demo class) - but DOESNT work correctly if there is an attribute following the docblock (the first method in the test case) 

The result is that you end up with a duplicated docblock

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by PhilETaylor** [comment]
The only button I see is "Process"? Even after pressing that I only see that button and no others?

**Comment by samsonasik** [comment]
@PhilETaylor you can add fixture at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture , see before and after by looking at other fixtures example, and add config for it at 
https://github.com/rectorphp/rector-src/blob/main/rules-tests/Renaming/Rector/Name/RenameClassRector/config/configured_rule.php

**Comment by TomasVotruba** [comment]
@PhilETaylor Ah, I see that too. It should be reported under `RenameClassRector` rule. I'll check what we can fix there, thanks :+1:

**Comment by PhilETaylor** [comment]
ok I think this is what you wanted - slightly different place, but it fails as a unit test for you https://github.com/rectorphp/rector-src/pull/1479
