### ISSUE TITLE
ConsistentPregDelimiterRector Break regex with carriage return

### ISSUE THREAD

**Issue by lahaxearnaud** [rectorphp/rector#6868]
First of all thank you for this amazing tool.

# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.7             |

After executing `Rector\CodingStyle\Rector\FuncCall\ConsistentPregDelimiterRector` rules all regex wil `\n` or `\r` pattern are broken.
This is what I get:

```php
            $parts = preg_split("#(
|
|
){2}#", $content);
```

## Minimal PHP Code Causing Issue

````
            $content = 'some texte';
            $parts = preg_split("/(\r\n|\n|\r){2}/", $content);
````

### The rector file

````
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src'
    ]);
    $services = $containerConfigurator->services();

    $services->set(\Rector\CodingStyle\Rector\FuncCall\ConsistentPregDelimiterRector::class);
};

````

## Expected Behaviour

````
            $parts = preg_split("#(\r\n|\n|\r){2}#", $content);
````

**Comment by samsonasik** [comment]
@lahaxearnaud the solution I found is by skip it, I created PR https://github.com/rectorphp/rector-src/pull/1506 for it.

**Comment by lahaxearnaud** [comment]
thanks
