### ISSUE TITLE
Wrong documentation regarding intersection types

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#6870]
You name the following in your docs:
<img width="1120" alt="CleanShot 2021-12-14 at 10 29 34@2x" src="https://user-images.githubusercontent.com/995707/145971192-c62f39dd-e671-4db4-b327-dbc89c2de42d.png">

AFAIK the used intersection type is invalid:
<img width="820" alt="CleanShot 2021-12-14 at 10 27 18@2x" src="https://user-images.githubusercontent.com/995707/145971246-c4a3b1c6-7d62-4477-a548-ffaae5cef114.png">

It will result in a fatal error.

`Foo&Bar`

should be used in the example.
If you agree I will create a PR

EDIT, it looks like they talk about a intersection types, but use `|` instead of `&` in the second screenshot, but a property cannot be `int` *and* `string` at the same time 🤔

**Comment by TomasVotruba** [comment]
Thank you for the reasearch! I learned something new. 

Btw, it seems the screenshot also contains bug, `string|int $val` is union type, not intersection type.

> If you agree I will create a PR

:+1: 

Could you send failing test case to the rule as well, so we have it covered?

**Comment by OskarStark** [comment]
> Btw, it seems the screenshot (could you share link?) also contains bug, string|int $val is union type, not intersection type.

Yes, see my edit in my post :-) 

I will fix the doc, but currently no time to add a failing TestCase, sorry :-(

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/1495
