### ISSUE TITLE
Add new namespaced rules under "BcBreak" namespace

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6872]
# Feature Request

I think we can create new namespace, eg: "BcBreak" that can contains collection of rules that can make BC Break application, eg on framework to upgrade to major version.

The use case can be extended of TypedPropertyRector that allow BC Break without need check of modifiers.

**Comment by samsonasik** [comment]
I think it should be by option in command instead of extending existing rules, eg:

```
vendor/bin/rector process --allow-bc-break
```

So we can add check in the rules.

**Comment by TomasVotruba** [comment]
Closing in favor of https://github.com/rectorphp/rector-src/pull/1744#issuecomment-1027759010
