### ISSUE TITLE
Get  leaveNode() returned invalid value of type integer error, if parent class does not exist

### ISSUE THREAD

**Issue by norgeindian** [rectorphp/rector#6873]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.8           |

If a class is extending another class, which does not exist, one gets the error message ``

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec5cca2-63b0-66e2-be36-43146ba5c048

## Expected Behaviour

To be honest, I don't know what the best behavior would be in this case, but I think it would be a good start to show a more detailed error message and make sure, that the scan does not stop.

**Comment by samsonasik** [comment]
It seems it because of `\Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector::class`

https://getrector.org/demo/1ec5ea88-7992-6844-8bda-c97b783fb347

when test locally, it will get:

```bash

1) Rector\Tests\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector\Php74Test::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
LogicException: leaveNode() returned invalid value of type integer

```
