### ISSUE TITLE
TypedPropertyRector throws PHPStan\ShouldNotHappenException: Cannot create PHPStan\Type\UnionType

### ISSUE THREAD

**Issue by Tobion** [rectorphp/rector#6875]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12.8            |

> PHP Fatal error:  Uncaught PHPStan\ShouldNotHappenException: Cannot create PHPStan\Type\UnionType with: string|null, string|null in phar:///usr/src/app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/UnionType.php:33
Stack trace:
#0 phar:///usr/src/app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/UnionType.php(47): PHPStan\Type\UnionType::PHPStan\Type\{closure}()
#1 /usr/src/app/vendor/rector/rector/rules/TypeDeclaration/TypeInferer/PropertyTypeInferer/GetterPropertyTypeInferer.php(94): PHPStan\Type\UnionType->__construct(Array)
#2 /usr/src/app/vendor/rector/rector/rules/TypeDeclaration/TypeInferer/PropertyTypeInferer.php(101): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer\GetterPropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#3 /usr/src/app/vendor/rector/rector/rules/TypeDeclaration/TypeInferer/PropertyTypeInferer.php(73): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer->getResolvedTypes(Object(PhpParser\Node\Stmt\Property))
#4 /usr/src/app/vendor in phar:///usr/src/app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/UnionType.php on line 33

TypedPropertyRector throws this exception when there is a property that has several getters. In our case the property is serialized differently for different versions using different getters.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec5de4d-8241-6310-8403-2d68574ebfd1

## Expected Behaviour

It should not fail. Maybe the union types should be merged?

**Comment by TomasVotruba** [comment]
Hi, thanks for clear report 👍 

> It should not fail. Maybe the union types should be merged?

That would be the fix. Maybe using PHPStan Union helper class to handle the merge.

Could you add failing test case to `TypedPropertyRector` so we have it covered?

**Comment by samsonasik** [comment]
@Tobion could you try `"rector/rector": "dev-main"` ? I tried and it seems it is applied ok now:

```diff
-       /**
-     * @var string|null
-     */
-    private $prop;
+       private ?string $prop;
```

**Comment by samsonasik** [comment]
I am closing as the issue answered as possibly resolved at `"rector/rector": "dev-main"` already as pointed in my previous comment https://github.com/rectorphp/rector/issues/6875#issuecomment-995497369

Feel free to create failing test case if you found a bug.
