### ISSUE TITLE
Describe how to configure a rule that is in a set

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#6876]
# Feature Request
 Describe how to configure a rule that is in a set.
When configuring a rule according to the documentation it is unclear that it redefines the rule if it was in a set already.

If I'm correct a rule that already is in a set (or already configured) should be further configured using something like this:
```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(SetList::CODE_QUALITY); // contains RenameFunctionRector

    $services = $containerConfigurator->services();
    /**
     * __ is not properly covered by larastan
     */
    $services->get(RenameFunctionRector::class)->call('configure', [[RenameFunctionRector::OLD_FUNCTION_TO_NEW_FUNCTION => [
        '__' => 'trans',
    ]]]);
};
```

**Comment by TomasVotruba** [comment]
Hi, thanks for the report.

The standard way to configure rule multiple time is using `configure()` method:

```php
// ...

$services->set(RenameFunctionRector::class)
    ->configure([
        '__' => 'trans',
    ]);
```

What happens when you use it this way?

**Comment by gisostallenberg** [comment]
I opened this issue because I had an error while running rector and found configuring the rule in another way solved it. That made me think this was not well documented. I cannot reproduce the issue. 
Thanks for your time.
