### ISSUE TITLE
Switch to match incorrect values

### ISSUE THREAD

**Issue by alexchuin** [rectorphp/rector#6880]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.8             |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec61847-6868-655e-aa37-7778e608b8d5

## Expected Behaviour

Don't break conditions or use the right default value ?

Thanks,
Alex

**Comment by samsonasik** [comment]
Please create failing fixture for it, you can click "Create a Test" button at the demo page.
