### ISSUE TITLE
Incorrect behavior of TypedPropertyRector for static inherited properties on PHP 8.1

### ISSUE THREAD

**Issue by rvanlaak** [rectorphp/rector#6881]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

The Constraint class directly is derived from Symfony.

See https://getrector.org/demo/1ec619f0-1594-6314-a1e2-670a76228edf

```php
<?php

abstract class Constraint
{
    /**
     * @noRector
     */
    protected static $errorNames = [];
}

class CanBeFulfilledConstraint extends Constraint
{
    public const CAN_BE_FULFILLED_ERROR = 'f523be54-eab0-40a5-be9d-d65f3c61cfca';

    protected static $errorNames = [
        self::CAN_BE_FULFILLED_ERROR => 'CAN_BE_FULFILLED_ERROR',
    ];
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

`CanBeFulfilledConstraint::$errorNames` should not get array as suggestion, as it's parent class `Constraint` usually lives in the vendor folder.

**Comment by samsonasik** [comment]
Could you try `"rector/rector": "dev-main"` ? The `TypedPropertyRector` in `dev-main` now only apply for `protected` when class is final and no parent.

**Comment by rvanlaak** [comment]
Yes this seems resolved on `main`, thank you for your quick reply!

Could you point to the commit that fixes it? Given that I was trying to create a PR myself.

**Comment by samsonasik** [comment]
That's on https://github.com/rectorphp/rector-src/pull/1496
