### ISSUE TITLE
Let SimplifyBoolIdenticalTrueRector preserve explicit comparisons in statements

### ISSUE THREAD

**Issue by rvanlaak** [rectorphp/rector#6882]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec61a49-95cc-642e-8175-c520396996de

```php
<?php

$implements = array_reduce($node->implements, static function (bool $agg, Node\Name $interface) {
    if (
        is_a($interface->toCodeString(), SomeInterface::class, true)
    ) {
        $agg = true;
    }

    return $agg;
}, false);

if (true === $implements) {
    return [];
}
```

### Responsible rules

* `SimplifyBoolIdenticalTrueRector`

## Expected Behavior

The `SimplifyBoolIdenticalTrueRector` is part of the Code Quality set list. We see explicity checking boolean values as true (and yoda typed) as a way to improve readability.

Yes this rector can be skipped, but it's use-cases as documented are useful. Is there a way to solely skip it for if/else/switch/etc statements?

**Comment by samsonasik** [comment]
Could you create https://3v4l.org/ demo for possibly value is not boolean but truthy, and update https://getrector.org/demo demo page for it? 

Also, there is "Create a Test" button to provide failing test case PR for it.

**Comment by rvanlaak** [comment]
I'm not sure I understand what you are asking me.

`array_reduce` will always return a boolean, and that also is the expected behavior. The point here would be that for readability purposes the if-statement should stay as how it was.

**Comment by samsonasik** [comment]
Then that will be opiniated apply comparison `if (true === $var)` or use truthy `if ($var)`, you can skip the rule for it:

```php
    $parameters->set(Option::SKIP, [
        \Rector\CodeQuality\Rector\Identical\SimplifyBoolIdenticalTrueRector::class,
    ]);
```

**Comment by rvanlaak** [comment]
Yes, it is opinionated and I'm aware that we can easily skip the whole rule. 

The point is to discuss whether it would be feasible to solely skip the part where this rector does make changes in if-statements. All other changes that this Rector rule makes are great.

**Comment by samsonasik** [comment]
The purpose of this rule is to simplify bool comparison, so use it in if condition is on purpose. I am closing it as you may skip it if you want to use bool comparison instead.
