### ISSUE TITLE
Inlining constructor parameters too aggresively when implementing interface

### ISSUE THREAD

**Issue by rvanlaak** [rectorphp/rector#6883]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest tag and dev-main             |

For the PHP 8.1 setlist, the constructor properties get inlined too aggressively in combination with readonly.

## Minimal PHP Code Causing Issue

I can not reproduce this on the demo, as it does not seem to use the `dev-main` branch.

## Suggestion how to fix

Make sure to check if the parent is an interface before .

## Actual Behaviour

Cache warmup fails due to compilation error:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/2707563/146794096-37dc3d87-95b4-4303-beec-6a4670e9eecc.png">

## Diff that shows problem

* The promoted `DomainEventMetadata::fromArray([])` is no valid property instantiation. 
* Promotion of `$metadata` is not compatible with interface.
* Only `$occuredOn` should have been promoted.

```diff
diff --git a/api/src/Domain/Shared/Event/AbstractDomainEvent.php b/api/src/Domain/Shared/Event/AbstractDomainEvent.php
index 1ac3776d..35450925 100644
--- a/api/src/Domain/Shared/Event/AbstractDomainEvent.php
+++ b/api/src/Domain/Shared/Event/AbstractDomainEvent.php
@@ -20,19 +20,11 @@ use Domain\Shared\EventStore\StoredEvent;
  */
 abstract class AbstractDomainEvent implements DomainEventInterface
 {
-    private DomainEventMetadata $metadata;
-    private \DateTimeInterface $occurredOn;
-
     /**
      * @param T $aggregateRootId
      */
-    public function __construct(
-        private $aggregateRootId,
-        ?DomainEventMetadata $metadata = null,
-        ?\DateTimeInterface $occurredOn = null,
-    ) {
-        $this->metadata = $metadata ?? DomainEventMetadata::fromArray([]);
-        $this->occurredOn = $occurredOn ?? new \DateTimeImmutable();
+    public function __construct(private $aggregateRootId, private readonly DomainEventMetadata $metadata = DomainEventMetadata::fromArray([]), private readonly \DateTimeInterface $occurredOn = new \DateTimeImmutable())
+    {
     }

     /**
~
~
```

## Expected code

```php

    # ...

    private DomainEventMetadata $metadata;

    /**
     * @param T $aggregateRootId
     */
    public function __construct(
        private $aggregateRootId,
        ?DomainEventMetadata $metadata = null,
        private readonly \DateTimeInterface $occurredOn = new \DateTimeImmutable(),
    ) {
        $this->metadata = $metadata ?? DomainEventMetadata::fromArray([]);
    }

```

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

It seems the problem is in abstract class. It cannot contain promoted properties:

https://stitcher.io/blog/constructor-promotion-in-php-8#not-allowed-in-abstract-constructors

**Comment by samsonasik** [comment]
resolved at https://github.com/rectorphp/rector-src/pull/1581 , feel free to create failing test case if the issue persist.
