### ISSUE TITLE
Rector rule to move tests from Symfony Bundle/Tests to tests folder?

### ISSUE THREAD

**Issue by mente** [rectorphp/rector#6885]
# Question

I'm refining old Symfony 3.x codebase and updating it to latest coding standards. One of the things which have changed from Symfony 2.x to 3.x (or later?) is moving the tests from specific Bundle folders `Tests` next to `src` folder in root directory.
What is needed in the nutshell:

* detect classes with `Test` in the end (we're using PHPUnit)
* move this class to `tests` folder
* update namespace to reflect new structure (`tests` namespace starts with `Tests`)

Surprisingly I can't find any rector rule to do it. Am I blind? 

Thanks in advance!

**Comment by TomasVotruba** [comment]
Hi, thanks for the question. There is no such rule yet.
You can use logic from https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#psr4 that moves classes and updates namespaces to create a new rule to handle it

**Comment by mente** [comment]
Thanks, will give it a try. Should I close this ticket or leave it open for more questions from me?

**Comment by TomasVotruba** [comment]
Lets close as answered, so we can narrow focus on unresolved bugs.

Feel free to continue with questions here though
