### ISSUE TITLE
Incorrect behavior of ReturnTypeDeclarationRector

### ISSUE THREAD

**Issue by liarco** [rectorphp/rector#6887]
# Bug Report

Rector started asking me to add `?mixed` as type-hint, but it's invalid:
```
PHP Fatal error:  Type mixed cannot be marked as nullable since mixed already includes null in php shell code on line XYZ
```

I commented the example to explain some background of the issue.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec62733-cbde-64ee-a331-99942366a1a1

```php
<?php

/**
 * @template T
 */
final class DemoFile
{
    /**
     * Same signature as "findOneBy" by Doctrine (ObjectRepository).
     *
     * @psalm-return ?T
     * @return null|object
     */
    public function findOneBy()
    {
        return null;
    }
    
    /**
     * Rector suggests "?mixed" as type-hint, but it's invalid.
     */
    public function myOwnFunctionUsingADoctrineRepository() // Rector suggests adding ": ?mixed" here
    {
        return $this->findOneBy();
    }
}
```

### Responsible rules

* `ReturnTypeDeclarationRector`

## Expected Behavior

I would expect `?object`, but I may be mistaken...

Thank you for your time.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by liarco** [comment]
As @samsonasik pointed out in my PR, specifying a type for the template should fix the problem.
```
/**
 * @template T as object
 */
```

Thank you very much for your hellp.
