### ISSUE TITLE
Add old and new content to json output

### ISSUE THREAD

**Issue by LeoVie** [rectorphp/rector#6888]
# Feature Request

Hi, I'm working on a project which parses the json output of the rector process command. It would be nice, if the json output would not only contain the compiled diff, but also the original and the new content. 

For example, consider the following command call:
```bash
./vendor/bin/rector process tests/testdata/for_to_while/ --dry-run --output-format json
```

This produces the following json output:
```json
{
    "meta": {
        "config": null
    },
    "totals": {
        "changed_files": 1,
        "removed_and_added_files_count": 0,
        "removed_node_count": 0,
        "errors": 0
    },
    "file_diffs": [
        {
            "file": "tests/testdata/for_to_while/01.php",
            "diff": "--- Original\n+++ New\n@@ -1,7 +1,9 @@\n <?php\n \n $array = [1, 2, 3];\n-for ($i = 0; $i < count($array); $i++) {\n+$i = 0;\n+while ($i < count($array)) {\n     $x = $array[$i];\n     print($x);\n+    $i++;\n }\n",
            "applied_rectors": [],
            "applied_rectors_with_changelog": []
        }
    ],
    "changed_files": [
        "tests/testdata/for_to_while/01.php"
    ]
}
```

I'd like to get the following json output:
```json
{
    "meta": {
        "config": null
    },
    "totals": {
        "changed_files": 1,
        "removed_and_added_files_count": 0,
        "removed_node_count": 0,
        "errors": 0
    },
    "file_diffs": [
        {
            "file": "tests/testdata/for_to_while/01.php",
            "diff": "--- Original\n+++ New\n@@ -1,7 +1,9 @@\n <?php\n \n $array = [1, 2, 3];\n-for ($i = 0; $i < count($array); $i++) {\n+$i = 0;\n+while ($i < count($array)) {\n     $x = $array[$i];\n     print($x);\n+    $i++;\n }\n",
            "original_content": "<?php\n\n$array = [1, 2, 3];\nfor ($i = 0; $i < count($array); $i++) {\n    $x = $array[$i];\n    print($x);\n}\n",
            "new_content": "<?php\n\n$array = [1, 2, 3];\n$i = 0;\nwhile ($i < count($array)) {\n    $x = $array[$i];\n    print($x);\n    $i++;\n}\n",
            "applied_rectors": [],
            "applied_rectors_with_changelog": []
        }
    ],
    "changed_files": [
        "tests/testdata/for_to_while/01.php"
    ]
}
```
 
I would implement it by adding the properties `$originalContent` and `$newContent` to `\Rector\Core\ValueObject\Reporting\FileDiff` which then get used in `jsonSerialize()`.

What do you think about it? If you agree, that it could be helpful, I would like to implement it.

**Comment by TomasVotruba** [comment]
Hi, this would make JSON output extremely huge even on 1 line change. The goal of output formatter is to provide only Rector result related changes.

For you use case, you can implement own formatter that contains file content you need.

**Comment by LeoVie** [comment]
You're right. Adding it to the `jsonSerialize()` method would be quite overpowered. 

What do you think about adding the properties `$originalContent` and `$newContent` to `\Rector\Core\ValueObject\Reporting\FileDiff`? If these properties exist, I can implement an own formatter.

**Comment by TomasVotruba** [comment]
Adding these property there would have same overload effect. We're moving to parallel runs, where json must be as thins as possible.

You don't need to modfiy `FileDiff` actually. You can detect original file content from file path and the result after applying diff.
