### ISSUE TITLE
AddVoidReturnTypeWhereNoReturnRector does not update trait methods

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6891]
# Bug Report

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec63efe-9bca-65ae-a568-e7960a375c68

## Expected Behaviour

trait methods should be updated

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by staabm** [comment]
> You can click "Create a Test" button at demo page.

there is no such button :-)

I will do it manually

**Comment by TomasVotruba** [comment]
Ah, it's false positive that does not produce any result :) I see.
