### ISSUE TITLE
ConstructClassMethodToSetUpTestCaseRector and RemoveParentCallWithoutParentRector conflict in anonymous class

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#6893]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.9 |

When using an anonymous class in a test case the ConstructClassMethodToSetUpTestCaseRector conflicts with RemoveParentCallWithoutParentRector.

## Minimal PHP Code Causing Issue

```php
final class MyTest extends \PHPUnit\Framework\TestCase
{
    public function testSomething(): void
    {
        new class() extends \stdClass {
            public function __construct()
            {
            }
        };
    }
}
```
```php
    $services = $containerConfigurator->services();
    $services->set(\Rector\PHPUnit\Rector\Class_\ConstructClassMethodToSetUpTestCaseRector::class);
    $services->set(\Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector::class);
```

Results in an error:
```
Fatal error: Uncaught TypeError: Rector\NodeCollector\ScopeResolver\ParentClassScopeResolver::resolveParentClassReflection(): Argument #1 ($scope) must be of type PHPStan\Analyser\Scope, null given, called in /app/vendor/rector/rector/rules/DeadCode/Rector/StaticCall/RemoveParentCallWithoutParentRector.php on line 103 and defined in /app/vendor/rector/rector/packages/NodeCollector/ScopeResolver/ParentClassScopeResolver.php:18
Stack trace:
#0 /app/vendor/rector/rector/rules/DeadCode/Rector/StaticCall/RemoveParentCallWithoutParentRector.php(103): Rector\NodeCollector\ScopeResolver\ParentClassScopeResolver->resolveParentClassReflection(NULL)
#1 /app/vendor/rector/rector/src/Rector/AbstractRector.php(237): Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector->refactor(Object(PhpParser\Node\Expr\StaticCall))
```

## Expected Behaviour

No error 😆

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?

**Comment by gisostallenberg** [comment]
@TomasVotruba can you hint me on where to put what? In this repo? Or in https://github.com/rectorphp/rector-src?

**Comment by gisostallenberg** [comment]
In the demo playground I do not seem to get this error by the way...
https://getrector.org/demo/1ec67c2d-8407-6022-85cc-2fcfb44dc2e1

**Comment by TomasVotruba** [comment]
Thank you for demo link! Could you retry with `dev-main` version? It might be fixed already :) 

If it fails, the rector-src is the repository to go :+1:

**Comment by gisostallenberg** [comment]
It is not solved in `dev-main`, I'll look into creating a failing test-case.

**Comment by samsonasik** [comment]
It seems need to be solved in both `rector-src` and `rector-phpunit` one by one, start with `RemoveParentCallWithoutParentRector` as it look up `Scope` which resolve null, then after applied, next to `rector-phpunit`'s `ConstructClassMethodToSetUpTestCaseRector`
