### ISSUE TITLE
Rector removes valid version constraints in composer.json

### ISSUE THREAD

**Issue by sypets** [rectorphp/rector#6895]
reported this first in TYPO3 slack

# Bug Report

Using rector, I noticed a dependency was changed in one of my extensions from

`"georgringer/news": "^8.6.0 || ^9.0.0"`
to
`"georgringer/news": "^8.6.0"`

My project composer.json requires news ^9.0.0, so this causes problems after the change. 

## Minimal PHP Code Causing Issue

rector.php contains:

`$containerConfigurator->import(Typo3SetList::COMPOSER_PACKAGES_104_EXTENSIONS);`

## Expected Behaviour

georringer/news with version ^9.0.0 is valid for TYPO3 v10 and should not be changed in the extension.

## versions

* rector/rector: 0.11.60 
* TYPO3 v10

## further information

used is a list of extension versions (which is not up to date): 

* vendor/rector/rector/vendor/ssch/typo3-rector/config/composer/typo3-104-composer-packages-extensions.php 
* https://raw.githubusercontent.com/rectorphp/rector/main/vendor/ssch/typo3-rector/config/composer/typo3-104-composer-packages-extensions.php

**Comment by sabbelasichon** [comment]
@sypets Could open the issue on the ssch/typo3-rector project
