### ISSUE TITLE
`ReadOnlyPropertyRector` ignores clones on PHP 8.1

### ISSUE THREAD

**Issue by internalsystemerror** [rectorphp/rector#6898]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.9             |

When using `ReadOnlyPropertyRector` and PHP set to 8.1, clones are ignored when setting a property to read only.

## Minimal PHP Code Causing Issue

Demo: https://getrector.org/demo/1ec6928e-0476-6f48-83b7-b715ee287a41

## Expected Behaviour

Rector should not mark the property as read only.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by internalsystemerror** [comment]
I'm working on a PR for this now for at least the failing test. If I can figure out a fix I will include that but its early days still for me with rector.
