### ISSUE TITLE
[Parallel] System errors may contain strings

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/rector#6901]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.10            |

When running rector with parallel, sometimes the following error is thrown.

```
In Assert.php line 1591:
  Expected an instance of this class or to this class among his parents Rector\Core\ValueObject\Error\SystemError. Got: string                            
```

The string is '**Reached system errors count limit of 20, exiting...**', code position:
https://github.com/rectorphp/rector/blob/8c823197becb3905e42b9d7f7849f1174e8b47cf/packages/Parallel/Application/ParallelFileProcessor.php#L159

## Minimal PHP Code Causing Issue

Sometime happen when running rector with parallel.

## Expected Behaviour

No assertion errors should occur.

**Comment by zingimmick** [comment]
The location of the code whose data type is a string:

https://github.com/rectorphp/rector/blob/8c823197becb3905e42b9d7f7849f1174e8b47cf/packages/Parallel/Application/ParallelFileProcessor.php#L120
https://github.com/rectorphp/rector/blob/8c823197becb3905e42b9d7f7849f1174e8b47cf/packages/Parallel/Application/ParallelFileProcessor.php#L152
https://github.com/rectorphp/rector/blob/8c823197becb3905e42b9d7f7849f1174e8b47cf/packages/Parallel/Application/ParallelFileProcessor.php#L159

**Comment by Jean85** [comment]
For anyone stumbling (like me) on this same issue: you can get the proper error message to pop up by disabling parallel run with:
```php
    $parameters->set(Option::PARALLEL, false);
```

**Comment by TomasVotruba** [comment]
Could you retry latest version? It should be fixed
