### ISSUE TITLE
Native Function Invocation Fixer?

### ISSUE THREAD

**Issue by PhilETaylor** [rectorphp/rector#6905]
Forgive me if there is a Rule that I cannot find, I have spent time looking :) 

ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048

Since PHP 7.0, some functions are replaced by opcodes, producing much faster code.

Yet, for this to work, these functions need to be referenced in the root namespace at compile time:
Either there is no namespace, or they are prefixed by a \.

I cannot see a rector rule that would apply that? Could be a quick millisecond performance win... 

Is this s feature request or am I just a blind idiot? (the latter is always the case)

**Comment by PhilETaylor** [comment]
> PhilETaylor added the [bug] label now

haha automation for the win eh...

**Comment by TomasVotruba** [comment]
Hi, thanks for the question!

I think in this case the fixer handles it very well and should be used :+1:  

It's rather about tokens `\` and abstract syntax tree we use in Rector is too heavy weapon for it.

**Comment by PhilETaylor** [comment]
no worries ! Thanks
