### ISSUE TITLE
Internal error in symfony_60 rules

### ISSUE THREAD

**Issue by bazo** [rectorphp/rector#6906]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 9baf531477df018156d0c12019c16f8bf638af74             |

Internal error in                                                                                              
         /application/vendor/rector/rector/vendor/rector/rector-symfony/config/sets/symfony/symfony6/symfony-return-type
         s.php (which is being imported from                                                                            
         "/application/vendor/rector/rector/vendor/rector/rector-symfony/src/Set/../../config/sets/symfony/symfony60.php
         ").             
## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec6c77b-2114-6bf6-81bd-838d08efdcc9

## Expected Behaviour

should work :)

**Comment by TomasVotruba** [comment]
Should be fixed by https://github.com/rectorphp/rector-symfony/pull/93 and https://github.com/rectorphp/rector-src/pull/1624
