### ISSUE TITLE
[PHP 8.1] Add null to string in Function Call Arg: NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6910]
# Feature Request

There are function calls that previously allow null to be need as string, eg: `preg_split`, ref ref https://3v4l.org/lbPsJ

```php
preg_split("#a#", null);
``` 

Another use case is `preg_match`, ref https://3v4l.org/WQ1Pk

```php
preg_match('/(foo)(bar)(baz)/', null, $matches);
```

that will error on php 8.1

I think we need to have general FuncCall Rector for it, eg: `NullToStrictStringFuncCallArgRector` that can have collection of function call with args that need to be string.

**Comment by samsonasik** [comment]
Another function to have strict string arg in php 8.1, preg_match_all ref https://3v4l.org/AFWHB

**Comment by samsonasik** [comment]
Also on `explode` function https://3v4l.org/3FsLf

**Comment by samsonasik** [comment]
strlen as well https://3v4l.org/0s1Gs

**Comment by tigitz** [comment]
@samsonasik Not sure if it should be taken into account in this rector since the naming specifies `StrictString` but here are more functions where nullability has been deprecated.

**Comment by samsonasik** [comment]
@tigitz could you add PR to add that on https://github.com/rectorphp/rector-src/blob/77a4582d5044446b8da43ab91a09082fa0413a23/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php#L48 ? Also better to have a fixture updated for it at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/Fixture

**Comment by FlorinProfeanu** [comment]
Are there news about managing strtotime (on other similar functions)?

**Comment by samsonasik** [comment]
Feel free to create PR to register more functions into the list of it at https://github.com/rectorphp/rector-src/blob/992d1efc7596864c960b3a9837ebf8ee04eb159d/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php#L42-L49
