### ISSUE TITLE
Rector 0.12.10 taking too much memory

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#6913]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.10             |

I'm trying to upgrade to 0.12.10 to downgrade PHPStan's codebase (+ Nette and Symfony in the vendor directory). I'm not able to do it because  Rector crashes around 60 % on the Windows machines in GitHub Actions with "Out of memory" message. This isn't PHP's memory_limit setting - this is about the machine giving up and killing the process. The documentation says the machine has 7 GB RAM (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners).

I've tried to measure it locally on macOS. With Rector 0.12.5 it takes about 860 MB to downgrade vendor/nette + vendor/symfony. With 0.12.10 it takes around 1400 MB.

I've measured it by adding these lines to ConsoleOutputFormatter:

```php
$bytes = memory_get_peak_usage(true);
$megabytes = ceil($bytes / 1024 / 1024);
$this->outputStyle->writeln(sprintf('%d MB', $megabytes));
```

So something's off here. It might be even PHPStan's fault, because a lot changed between 1.2.0 and 1.3.0. But PHPStan itself consumes around the same amount of memory, so it might just be a configuration issue.

What mainly changed is that BetterReflection got updated from my own fork based on BR 4.3.x to my own fork based on BR 5.0.x. Classes like `ClassReflector`, `FunctionReflector`, `ConstantReflector` are now deprecated, and the backward compatibility layer is very inefficient (https://github.com/ondrejmirtes/BetterReflection/commit/fff586ee789dfd6a76678d6d759982356abb48d2#diff-12a85fa84b6882fbe20b86fadf269cb12bb1ce5cd040209dd947a747bf85dc57).

What should be used instead is typehinting `PHPStan\BetterReflection\Reflector\Reflector` everywhere, and get `MemoizingReflector` from PHPStan's DI container (https://github.com/phpstan/phpstan-src/blob/master/src/Reflection/BetterReflection/Reflector/MemoizingReflector.php) injected there.

That's the first thing I'd try. Otherwise I'm not sure what's happening...

**Comment by gander** [comment]
How does your RAM consumption look like when you use the `--no-diffs` option?

**Comment by ondrejmirtes** [comment]
@gander About the same, it makes no difference.

**Comment by TomasVotruba** [comment]
The only cases for `ClassReflector` are these 2: https://github.com/rectorphp/rector-src/search?q=ClassReflector

I tried to rename them here: https://github.com/rectorphp/rector-src/pull/1640, but constructor types changed somehow.

I've experienced similar performance htis in CI with BetterReflectoin 1/2. What else is difference between your fork and their version? That might help us spot the weak spots that can be seen in Rector.

**Comment by ondrejmirtes** [comment]
Instead of `new ClassReflector` you should have `new DefaultReflector`. But the problem is that with multiple `MemoizingReflector` instances some stuff will be memoized in memory multiple times. But I'm not sure if this is the reason for the increased memory consumption.

When I'm debugging memory leaks in PHPStan I'm using https://github.com/BitOne/php-meminfo but it's a long and tedious process.

**Comment by ondrejmirtes** [comment]
The fix: https://github.com/rectorphp/rector-src/pull/1643
