### ISSUE TITLE
FileNotFound when using phpstan with BleedingEdge include

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#6915]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | fee8a47d1a627b01bfba2d85293c84692715506a             |

## Minimal PHP Code Causing Issue

`$parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, getcwd() . '/phpstan.neon');`

```neon
includes:
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon
```

gives:

```
PHP Fatal error:  Uncaught _PHPStan_71572f9a1\Nette\FileNotFoundException: 
File 'phar://phpstan.phar/conf/bleedingEdge.neon' is missing or is not readable. in phar:///path/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php:29
```

**Comment by TomasVotruba** [comment]
This option is configurable to be flexible and work around configuration that is used in PHPStan but not in Rector.
Sometimes PHPStan extensions remove static reflection, e.g. Symfony extension, and Rector cannot include it as it needs complete static reflection.

In this case, create own custom `phpstan-for-rector.neon` or remove `vendor/phpstan/phpstan/conf/bleedingEdge.neon` from `phpstan.neon`. I guess first option is better.

In ideal state, the `phpstan-for-rector.neon` should only include extensions so Rector can analyse types better.

See our custom PHPStan config to get the idea: https://github.com/rectorphp/rector-src/blob/main/phpstan-for-rector.neon

**Comment by simPod** [comment]
@TomasVotruba so it also ignores extensions that are installed via https://github.com/phpstan/extension-installer?

**Comment by TomasVotruba** [comment]
Those should be included:
https://github.com/rectorphp/rector-src/blob/dd89737f2fcc3672e554048af30f96a5e3a3b941/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php#L122-L155
