### ISSUE TITLE
Undefined class constant 'PHPEXCEL_TO_PHPSPREADSHEET'

### ISSUE THREAD

**Issue by ionB2d6fAx** [rectorphp/rector#6919]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.11             |
| rector --version| Rector 49f1596404278c63a37841eb720aabf97601311e|
|PHP| 7.2.5|

## Description

Attempting to migrate from `PHPExcel` to `PHPSpreadsheet` following this article:
https://getrector.org/blog/2020/04/16/how-to-migrate-from-phpexcel-to-phpspreadsheet-with-rector-in-30-minutes

## Code Causing Issue

```
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(SetList::PHPEXCEL_TO_PHPSPREADSHEET);
};
```

## Demo

Reproduced using the demo site:
https://getrector.org/demo/1ec6fa9c-e348-6124-bc02-21145043166f

**Comment by samsonasik** [comment]
Please read latest readme at https://github.com/rectorphp/rector-phpoffice#use-sets for its usage.

**Comment by TomasVotruba** [comment]
@ionB2d6fAx Thanks for reporting. The post contains old set name, that was moved to own repository.

This is the correct set name:
https://github.com/rectorphp/getrector.org/pull/478
