### ISSUE TITLE
error migrating from phpexcel to phpspreadsheet with dry-run

### ISSUE THREAD

**Issue by sukrosono** [rectorphp/rector#6922]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12.12 (invoke `vendor/bin/rector --version`)             |

php framework used is codeigniter 3. php 7.4, this is happening when targeting application/helpers/ directory
error thrown on cli : 
```
./vendor/bin/rector process -n
PHP Notice:  RectorPrefix20220107\Nette\Utils\Strings::toAscii(): it is recommended to enable PHP extensions 'intl'. in /srv/http/caraka/application/third_party/vendor/rector/rector/vendor/nette/utils/src/Utils/Strings.php on line 124
Notice: RectorPrefix20220107\Nette\Utils\Strings::toAscii(): it is recommended to enable PHP extensions 'intl'. in /srv/http/caraka/application/third_party/vendor/rector/rector/vendor/nette/utils/src/Utils/Strings.php on line 124
 110/169 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  65%

In BreakingRemovalGuard.php line 25:
                                                                                                                                                                                          
  Node "PhpParser\Node\Expr\FuncCall" on line 79 is child of "PhpParser\Node\Expr\Assign", so it cannot be removed as it would break PHP code. Change or remove the parent node instead.  
                                                                                                                                                                                          

```
side note: I am not able to see and result when passing the path via cli, I am editing on initiated rector.php file.
## Minimal PHP Code Causing Issue
I am not sure I am new user on rector

## Expected Behaviour
the dry run result

**Comment by TomasVotruba** [comment]
Hi, please run command with `--debug`.
What is the minimal code in src causing this error?

**Comment by sukrosono** [comment]
Ok, thanks.
Anyways I think it's an invalid bug report, sorry for this.
I got dompdf directory, so basically, my src contains some code that does not need to be scanned for migration.
It's working great, I do targeting a single file for now.
Have a good day.

**Comment by TomasVotruba** [comment]
I see, thanks for letting us know
