### ISSUE TITLE
Convert `null` checks in `if` condtion to null safe operator if possible

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#6923]
# Feature Request

I'm not sure if there is already an existing Rector for this. So I opened this as a feature request.

For the following code:
```php
<?php

final class Foo
{
    public function run(): void
    {
        // ...
    }
}

$foo = rand(0,1) === 0 ? new Foo : null;

if ($foo !== null) {
	$foo->run();
}
```

it'd be cool if Rector could convert the if condition to null safe operator instead. Of course if the method call is the only statement in the `if` body it should happen. Otherwise it should be skipped.
 
## Diff 

```diff
<?php

final class Foo
{
    public function run(): void
    {
        // ...
    }
}

$foo = rand(0,1) === 0 ? new Foo : null;

-if ($foo !== null) {
-	$foo->run();
-}
+$foo?->run();
```

Demo link: https://getrector.org/demo/1ec71f50-c57c-6fc2-b32c-5326d9b5f9ae

**Comment by samsonasik** [comment]
We had it https://github.com/rectorphp/rector/pull/4557 but we removed it at https://github.com/rectorphp/rector-src/pull/900 as it often breaking.
