### ISSUE TITLE
RectorServiceConfigurator is too strict about ensuring that class is configurable

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#6926]
# Bug Report
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e33afe6434a9707374815bb977cff09b6e57c199             |

https://getrector.org/demo/1ec72680-b7a0-6e58-a574-05b0dc0d6e56

## Expected Behaviour
accept the configuration as it is.

**Comment by sabbelasichon** [comment]
@TomasVotruba I am gonna provide a patch for that.

**Comment by TomasVotruba** [comment]
Hi, thanks for the fix.
Could you share a test case, so we have it covered for the future?

**Comment by sabbelasichon** [comment]
@TomasVotruba Test is added. I am still not sure why PHPStan is complaining about the instanceof and how to surpress it

**Comment by TomasVotruba** [comment]
Thanks for the test fixure. The `->set('...string...')` should never be needed and `->set(SomeRector::class)` should be used.
The `configure()` calls are merged.

Where do you need it?

**Comment by sabbelasichon** [comment]
I see. Thought it is necessary if you have multiple configs with the same service but different configurations. I was expecting that the last one wins. But if it gets merged, everything should be fine. I remember a time when this was an issue with the Symfony DI in typo3-rector. But maybe it is different after introducing Rector´s own configuration service.

**Comment by sabbelasichon** [comment]
Nevertheless if someone else is configuring the Service Container that way, it would still be nice if Rector could handle this behind the scenes and is not exiting with an error.

**Comment by sabbelasichon** [comment]
@TomasVotruba I am gonna change this in my config files as you suggested.

**Comment by TomasVotruba** [comment]
> Nevertheless if someone else is configuring the Service Container that way, it would still be nice if Rector could handle this behind the scenes and is not exiting with an error.

Agreed, IMO it should throw error, as this behavior is undesired in Rector scope.

---

> @TomasVotruba I am gonna change this in my config files as you suggested.

Thanks :+1:  If there are some buggy cases, let me know
