### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector

### ISSUE THREAD

**Issue by marcosemplici** [rectorphp/rector#6928]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec72cab-b010-69f0-9785-0f4103e3217a

```php
<?php
use ApiPlatform\Core\Annotation\ApiFilter;

/**
 * @ApiFilter(SearchFilter::class,
 *     properties={
 *     "id": "exact",
 *     ActivationRequest::FIRSTNAME : "ipartial",
 * })
 */
class ActivationRequest
{
    public const FIRSTNAME ='firstName';
}
```

### Responsible rules

* `AnnotationToAttributeRector`

**Comment by marcosemplici** [comment]
RECTOR CHANGED:  
  
use ApiPlatform\\Core\\Annotation\\ApiFilter;  
  
#\[ApiFilter(SearchFilter::class, properties: \['id' => 'exact', 0 => ActivationRequest::FIRSTNAME\])\]  
class ActivationRequest  
{  
    public const FIRSTNAME ='firstName';  
}  
  
EXPECTED:  
  
use ApiPlatform\\Core\\Annotation\\ApiFilter;  
  
#\[ApiFilter(SearchFilter::class, properties: \['id' => 'exact',  ActivationRequest::FIRSTNAME => 'ipartial'\])\]  
class ActivationRequest  
{  
    public const FIRSTNAME ='firstName';  
}

**Comment by TomasVotruba** [comment]
Thanks fore reporting. Could you check this fix if it fits your use case?
https://github.com/rectorphp/rector-src/pull/1659

**Comment by marcosemplici** [comment]
Yes it fixs. But there's similar use case...  
https://getrector.org/demo/1ec72f1d-35ed-671c-8788-a18acc9c9cfc

**Comment by TomasVotruba** [comment]
I see. Could you add test fixture with that code in the `/Fixture` directory?
You can copy this one, just replace class name and nested items:

**Comment by Jean85** [comment]
I tried to do it in https://github.com/rectorphp/rector-src/pull/1661

**Comment by samsonasik** [comment]
I am closing it as resolved at https://github.com/rectorphp/rector-src/pull/1661
