### ISSUE TITLE
preg_match to str_starts_with

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6929]
# Feature Request

Today saw this great tweet about a phpstorm quick fix

https://twitter.com/wiifm/status/1480457070323265537?s=20

Sounds like a good rector to have
 
## Diff 

```diff
-$value = preg_match('@^http://@', $str);
+$value = str_starts_with($str, 'http://');
```

Same for `strpos($this->url, 'https://') === 0;`

**Comment by TomasVotruba** [comment]
That would be great addition to code quality set 👍

**Comment by samsonasik** [comment]
It seems it may cause issue that never exists before, as we need to validate string start with `^`, and after that, only literal string or regex itself, which validate regex with regex, which may be regex marked as regex or literal string.

**Comment by samsonasik** [comment]
I am closing it as it seems may cause a bug that never exists before for regex or non-regex detection, the string functions are there on purpose, the regex function are there too on purpose.
