### ISSUE TITLE
Downgrade to PHP 7.2 and json_encode doesn't work well with JSON_THROW_ON_ERROR

### ISSUE THREAD

**Issue by rs-ubaldi** [rectorphp/rector#6931]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e33afe6434a9707374815bb977cff09b6e57c199 |

There is no support for JsonException and JSON_THROW_ON_ERROR in PHP 7.2 and Rector does no conversion whatsoever on these calls, rendering refactored code inoperative

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec73a9a-c6e9-69fe-99d3-57903e2998e7

## Expected Behaviour

JSON_THROW_ON_ERROR flasg should be dropped and JsonException replaced with Exception eventually.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

I'm checking the downgrade set https://github.com/rectorphp/rector-src/blob/main/config/set/downgrade-php72.php and there is no such rule.

The inversion of the upgrade rule needs to be added first:
https://github.com/rectorphp/rector-src/blob/main/rules/Php73/Rector/FuncCall/JsonThrowOnErrorRector.php

**Comment by rs-ubaldi** [comment]
@TomasVotruba thanks for your kind reply, I am a newbie to rector and will try to find a solution to this. Meanwhile I am installing the source to pinpoint your tips.

**Comment by rs-ubaldi** [comment]
I can't manage to get the rector-src running : 

**docker-compose run php composer install** will not succeed

- Applying patches for symfony/dependency-injection
    https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/symfony-dependency-injection.patch (0)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/symfony-dependency-injection.patch

  - Applying patches for helmich/typo3-typoscript-parser
    https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/helmich-typo3-typoscript-parser-parser-tokenstream-php.patch (0)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/helmich-typo3-typoscript-parser-parser-tokenstream-php.patch

**Comment by TomasVotruba** [comment]
We use direct PHP to develop Rector, so I'm not sure how vendor patches behave inside Docker. Can you try without Docker?

**Comment by rs-ubaldi** [comment]
I have managed to code something that works directly outside of the Rector source : 

```php
<?php

/*****************************************************************************
 * @file        DowngradeJsonEncodeDecodeJsonThrowOnError.php
 * @author      Radu Stoichita
 * @date        14/01/2022
 *****************************************************************************/

namespace UbaldiRector;

use PhpParser\Node;
use PhpParser\Node\Expr\FuncCall;
use PhpParser\NodeDumper;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitorAbstract;
use Rector\Core\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

class DowngradeJsonEncodeDecodeJsonThrowOnError extends AbstractRector
{
    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('Remove JSON_THROW_ON_ERROR', [new CodeSample(<<<'CODE_SAMPLE'
json_decode("[1,2,3]", JSON_THROW_ON_ERROR)
json_decode("[1,2,3]", true, 512, JSON_THROW_ON_ERROR)
json_encode("[1,2,3]", JSON_THROW_ON_ERROR | JSON_INVALID_UTF8_IGNORE)
json_decode("[1,2,3]", true, 512, JSON_THROW_ON_ERROR | JSON_BIGINT_AS_STRING | JSON_OBJECT_AS_ARRAY | JSON_ERROR_NONE))
CODE_SAMPLE
            , <<<'CODE_SAMPLE'
json_decode("[1,2,3]")
json_decode("[1,2,3]", true, 512)
json_encode("[1,2,3]", JSON_INVALID_UTF8_IGNORE)
json_decode("[1,2,3]", true, 512, JSON_BIGINT_AS_STRING | JSON_OBJECT_AS_ARRAY | JSON_ERROR_NONE))
CODE_SAMPLE
        )]);
    }

    public function getNodeTypes(): array
    {
        return [FuncCall::class];
    }

    /**
     * @param FuncCall $node
     */
    public function refactor(Node $node): ?FuncCall
    {
        if ($this->shouldSkip($node)) {
            return null;
        }

        if ($this->isName($node, 'json_decode')) {
            return $this->refactorJsonEncodeDecode($node, 3);
        }

        if ($this->isName($node, 'json_encode')) {
            return $this->refactorJsonEncodeDecode($node, 1);
        }

        return null;
    }

    private function shouldSkip(FuncCall $funcCall) : bool
    {
        if (!$this->isNames($funcCall, ['json_decode', 'json_encode'])) {
            return true;
        }

        return false;
    }

    private function refactorJsonEncodeDecode(FuncCall $funcCall, int $flagsPos): ?FuncCall
    {
        // Third argument not set
        if (!isset($funcCall->args[$flagsPos])) {
            return null;
        }
        $flagsArg = $funcCall->args[$flagsPos];

        // Single flag
        // Support for json_decode("[1,2,3]", JSON_THROW_ON_ERROR)
        // Support for json_decode("[1,2,3]", true, 512, JSON_THROW_ON_ERROR)
        if ($flagsArg->value instanceof Node\Expr\ConstFetch
            && $flagsArg->value->name->parts[0] === 'JSON_THROW_ON_ERROR') {
            unset($funcCall->args[$flagsPos]);
            return $funcCall;
        }

        // Multiple flags (using bitwise expr)
        // Support for json_encode("[1,2,3]", JSON_THROW_ON_ERROR | JSON_INVALID_UTF8_IGNORE)
        // Support for json_decode("[1,2,3]", true, 512, JSON_THROW_ON_ERROR | JSON_BIGINT_AS_STRING | JSON_OBJECT_AS_ARRAY | JSON_ERROR_NONE))
        $traverser = new NodeTraverser();
        $traverser->addVisitor(new class extends NodeVisitorAbstract {
            public function leaveNode(Node $node)
            {
                if ($node instanceof Node\Expr\BinaryOp) {
                    if ($node->left instanceof Node\Expr\ConstFetch && $node->left->name->parts[0] === 'JSON_THROW_ON_ERROR') {
                        return $node->right;
                    }
                    if ($node->right instanceof Node\Expr\ConstFetch && $node->right->name->parts[0] === 'JSON_THROW_ON_ERROR') {
                        return $node->left;
                    }
                }

                return null;
            }
        });
        $traverser->traverse([$flagsArg]);

        return null;
    }
}

```

**Comment by rs-ubaldi** [comment]
Now just remains to convert JsonException to normal Exception, is there any rule I could use already in place ?

**Comment by rs-ubaldi** [comment]
@TomasVotruba thanks very much, yes it works great for me for now and I will use it as is outside of the rector package.
Please feel free to include this in your future release, I don't have much time to make the dev platform work. Have a nice day !
