### ISSUE TITLE
NewInInitializerRector tries to move static method calls to the constructor

### ISSUE THREAD

**Issue by WesleyKlop** [rectorphp/rector#6934]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12.12 (e33afe6434a9707374815bb977cff09b6e57c199)             |

When using a static method to initialize a property in the constructor, `NewInInitializerRector` tries to move the static method call in the constructor parameters.

## Minimal PHP Code Causing Issue

It does look like another rector is involved, because when I don't import the LevelSetList the bug does not seem to occur. It also only happens in a specific situation shown in the demo

https://getrector.org/demo/1ec74728-4ee6-6e8a-936b-53d3c31e3d8c

## Expected Behaviour

Rector should skip that situation _or_ convert it to the untouched version shown in the demo.

**Comment by samsonasik** [comment]
It seems it because of `NewInInitializerRector` in dev-main, but somehow can't show in getrector.org/demo for only apply `NewInInitializerRector` as getrector.org/demo use 0.12.12 instead of dev-main
