### ISSUE TITLE
`IfToSpaceshipRector` has an unintentional side effect

### ISSUE THREAD

**Issue by johnbillion** [rectorphp/rector#6937]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec752ab-a40c-6098-9d2c-b5dbbc58e450

```php
<?php

class HelloWorld {

	public static function get_query_type( $sql ) {
		if ( 0 === strpos( $sql, '/*' ) ) {
			$sql = preg_replace( '|^/\*[^\*/]+\*/|', '', $sql );
		}

		$words = preg_split( '/\b/', trim( $sql ), 2, PREG_SPLIT_NO_EMPTY );
		return $words[0] ?? 'Unknown';
	}

	private static function rsort( $a, $b ) {
		if ( $a['foo'] === $b['foo'] ) {
			return 0;
		} else {
			return ( $a['foo'] > $b['foo'] ) ? -1 : 1;
		}
	}

}
```

### Responsible rules

* `IfToSpaceshipRector`

## Expected Behavior

With the code above, the sorting logic is correctly replaced with a spaceship operator, but a side effect is also triggered: line 10 is completely removed.

The cause appears to be a combination of the characters in the `if` statement and regexes above it, possibly something internal is getting confused by the `/*` string.

**Comment by samsonasik** [comment]
Could you create PR for failing fixture at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php70/Rector/If_/IfToSpaceshipRector/Fixture for it ? Thank you.
