### ISSUE TITLE
`IfToSpaceshipRector` doesn't refactor reverse sorting

### ISSUE THREAD

**Issue by johnbillion** [rectorphp/rector#6938]
# Bug Report

`IfToSpaceshipRector` correctly refactors a sorting method when the test result is `1 : -1` but it does not refactor a test when the result is `-1 : 1`. This should be possible by reversing the order of the comparison during refactoring.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec752c4-31d3-6968-a239-c97530bbb5fa

```php
<?php

class HelloWorld {

	private static function _rsort( $a, $b ) {
		if ( $a['foo'] === $b['foo'] ) {
			return 0;
		} else {
			return ( $a['foo'] > $b['foo'] ) ? -1 : 1;
		}
	}

	private static function _sort( $a, $b ) {
		if ( $a['foo'] === $b['foo'] ) {
			return 0;
		} else {
			return ( $a['foo'] > $b['foo'] ) ? 1 : -1;
		}
	}

}
```

### Responsible rules

* `IfToSpaceshipRector`

## Expected Behavior

I would expect the `_sort()` method to be refactored to the following (note the swapped order of `$a` and `$b`):

```php
return $b['foo'] <=> $a['foo'];
```

**Comment by samsonasik** [comment]
Could you create PR for failing fixture at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php70/Rector/If_/IfToSpaceshipRector/Fixture for it ? Thank you.
