### ISSUE TITLE
UnSpreadOperatorRector should not rector calls to methods out of scope

### ISSUE THREAD

**Issue by froemken** [rectorphp/rector#6940]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.12                                                          |

Using Rector with rule UnSpreadOperatorRector generates invalid PHP code

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec754f0-5c0e-660a-a645-e552eb098b9f

## Expected Behaviour

2 possibilities:

* Do not update
* Or use `...['uid', 'pos_index', 'latitude', 'longitude']`

**Comment by sabbelasichon** [comment]
i have a suspicion that your vendor directory is named / configured differently than "vendor". Which is the default for composer based installations. Can you confirm this?

**Comment by froemken** [comment]
Sorry, my fault. TYPO3 has its own QueryBuilder in
`$fileName = '/var/www/html/public/typo3/sysext/core/Classes/Database/Query/QueryBuilder.php'`

So, it's not a "vendor" problem...it's a missing Option::SKIP for `typo3` directory.

**Comment by momocode-de** [comment]
Not sure if it is the same problem, but I have also a problem with the `UnSpreadOperatorRector` rule. I have this function signature:

```
public function addRepositories(EntityRepositoryInterface ...$repositories): void
```

And Rector wants do replace it by this:

```
public function addRepositories(array $repositories = []): void
```

But it's not meant to provide an array as parameter, but to provide as many `EntityRepositoryInterface` parameters as you want. So if I call `addRepositories($repositoryA, $repositoryB)` my code is working, but the code from Rector will not work. In my case I'm not calling the function in my PHP code, but in my symfony service definition:

```
<call method="addRepositories">
                <argument type="service" id="product.repository" />
                <argument type="service" id="product_cross_selling.repository" />
</call>
```

**Comment by samsonasik** [comment]
You may need to skip for that edge case, I skip `UnSpreadOperatorRector` too in my module https://github.com/samsonasik/ErrorHeroModule/blob/f11f7dfc7241712c98234d161d1a88ef0ef678fb/rector.php#L36
