### ISSUE TITLE
Report dead @noRector

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#6943]
# Feature Request

Consider I have placed `/** @noRector \Rector\DeadCode\Rector\Plus\RemoveDeadZeroAndOneOperationRector */` into my code to suppress refactoring.

After a while the code changes and refactoring rule no longer applies but the @noRector rule is forgotten in the code.

Rector does not complain about having `@noRector` while no refactoring is done now.

**Comment by TomasVotruba** [comment]
That could be useful :+1:  Would you like to contribute?

**Comment by simPod** [comment]
@TomasVotruba not sure what to touch, do you have any pointers where I should look at?

**Comment by TomasVotruba** [comment]
This is the service responsible for skipping: https://github.com/rectorphp/rector-src/blob/fc10fce13dcf9767f54e4202b509020fed338645/src/Exclusion/ExclusionManager.php
Then adding a check to `ProcessCommand::execute()` might do.

**Comment by simPod** [comment]
While the feature looks nice the effort for me seems not adequate to the outcome value. I'll not pursue this issue.

**Comment by TomasVotruba** [comment]
I agree. Thanks for feedback :+1:

**Comment by maciej-laskowski** [comment]
That would be similar to PHPStan [default behaviour](https://phpstan.org/user-guide/ignoring-errors#reporting-unused-ignores) which I find very useful.

I believe this feature is worth the effort but sadly probably above my paygrade.
