### ISSUE TITLE
Could Rector break-down large functions into smallest one?

### ISSUE THREAD

**Issue by francescobianco** [rectorphp/rector#6944]
# Could Rector break-down large functions into smallest one?

On my client's project we have many large functions (more then 1000 LOC). Can we use Rector to automatic break-down functions into smallest piece of code?

**Comment by TomasVotruba** [comment]
Hi, that's an interesting question :) 

Do you have some minimal example of what you mean? Ideally under 10 lines of code, so we can the diff

**Comment by francescobianco** [comment]
Yes! As example look at this file https://github.com/javanile/vtiger-core/blob/7.2.0/data/CRMEntity.php#L252

The method `insertIntoCrmEntity()` is large and could be split into two trunk base on the following IF

```php
if ($this->mode == 'edit') {
```

I image something that automagic create two sub-methods called 

- `insertIntoCrmEntityModeEdit()`
- `indertIntoCrmEntituNotModeEdit()`

than replace the IF stamentent into `insertIntoCrmEntity()` with

```php
public insertIntoCrmEntity(...) 
{
   // ... CODE ...
   
   if ($this->mode == 'edit') {
     $this->insertIntoCrmEntityModeEdit(); 
   } else {
     $this->insertIntoCrmEntityNotModeEdit();
   }  
}
```

**Comment by TomasVotruba** [comment]
I see. You can create custom rule that would target the `Class_` node.
Then iterate all class method and use `NodeFinder` to find `If_` nodes.
Then extract local methods based on `if (...-><property_name> === $<value>)` logic.

**Comment by samsonasik** [comment]
I am closing it as the solution provided.
