### ISSUE TITLE
Global Execution Bugs

### ISSUE THREAD

**Issue by MGatner** [rectorphp/rector#6945]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| PHP Versions | 7.4 and 8.1 at least |
| Rector Version | `0.12.13`             |
| Execution  | Global |

Using the tool globally causes unexpected differences in behavior. Documented examples include:
1. Errors during verbose output (https://github.com/rectorphp/rector/issues/6903#issuecomment-1013741544)
2. Differing detection of parent class methods (https://github.com/codeigniter4/devkit/pull/8#issuecomment-1014630719)

The docs contain a single buried reference to global execution (https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#call-command-with--a-option) stating it is "not recommended as autoload may overlapped".

## Minimal PHP Code Causing Issue

*See example repo with steps to reproduce at https://github.com/MGatner/rector-error.*

## Expected Behaviour

Two options in my mind:
1. Global and local execution should result in identical results. The likely resolution is for `autoloadProjectAutoloaderFile()` to be made more robust at detecting the correct autoload file (see https://github.com/rectorphp/rector-src/pull/1683, but even better)
2. Remove support for global execution, or make one of the workarounds (https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#dealing-with-class--was-not-found-while-trying-to-analyse-it) mandatory. Rector should not "guess" at an autoload during global execution. This unannounced behavior is the source of the very confusing behavior noted above.

I have a strong preference for option 1). I believe static analysis tools that are not actual dependency should not be declared as such. That said, I don't have time to learn the Rector codebase to implement this solution, nor the institutional knowledge to declare it "best for the project".

I do not want to influence the decision about what is best, but should the team decide to go with option 1) I put forth a $40 bounty on its execution to go toward supporting this project.

## References

* Initial resolution attempt: https://github.com/rectorphp/rector-src/pull/1683
* Reversion of the first attempt: https://github.com/rectorphp/rector-src/pull/1685
* Repo demonstrating Problem 1: https://github.com/MGatner/rector-error
* Repo/conversation demonstrating Problem 2: https://github.com/codeigniter4/devkit/pull/8
* Tagging @PhilETaylor

**Comment by samsonasik** [comment]
@MGatner could you verify if add this check works https://github.com/rectorphp/rector-src/pull/1692/commits/ef574ac21095ca5b4f5db4d8267f2c0a271edd9b at PR https://github.com/rectorphp/rector-src/pull/1692 ?

**Comment by MGatner** [comment]
Looking good so far! Definitely solves the "Class not found." I'm going to test it in a fresh environment with different PHP version and get back.

**Comment by PhilETaylor** [comment]
Basically the same change I made but with a safety check first 👍

**Comment by MGatner** [comment]
Seems to fix part 1 ("Class not found...") but not part 2 (parent method removal) https://github.com/rectorphp/rector-src/pull/1692#issuecomment-1014699836

**Comment by MGatner** [comment]
> Basically the same change I made but with a safety check first 👍

Yes for sure credit due on tracing that down and implementing a fix. I expect there may still be similar e2e failures like yours.

**Comment by PhilETaylor** [comment]
@MGatner do you have different PHPUnit versions globally and locally?

**Comment by MGatner** [comment]
I don't have PHPUnit installed globally. The second environment I spun up specifically just to test this (PHP 8.1, Ubuntu 20.04, Rector branch from the PR):
```bash
~/.config/composer$ composer info
phpstan/phpstan 1.4.0   PHPStan - PHP Static Analysis Tool
rector/rector   0.12.13 Prefixed and PHP 7.1 downgraded version of rector/rector
```

**Comment by PhilETaylor** [comment]
but those files having the lines removed are PHPUnit tests right? maybe its removing the lines because it cannot find PHPUnit? Im just guessing while mobile...

**Comment by MGatner** [comment]
@PhilETaylor Sorry to be unclear! PHPUnit is installed *locally* in the project - just not globally. Here's the project in question: https://github.com/tattersoftware/codeigniter4-handlers

If you want to try to recreate the issue:
1. Clone the repo
2. Open **rector.php** and remove the following lines (my workaround): https://github.com/tattersoftware/codeigniter4-handlers/blob/35658e56cc0b5f07ab1b2a19b8f46d9d138c90ac/rector.php#L81-L84
3. Run Rector from your global installation, e.g.: `~/.config/composer/vendor/bin/rector process`

The result should be the removal of those method calls even though they exist multiple parents up. Try the same thing with local Rector, it leaves them alone.

**Comment by samsonasik** [comment]
@PhilETaylor @MGatner could you verify if latest change solve it https://github.com/rectorphp/rector-src/commit/465550308797b3716dc66f695d701fc6107db921 at PR https://github.com/rectorphp/rector-src/pull/1692 ?

**Comment by PhilETaylor** [comment]
that works for me on the "could not process" error
<img width="1602" alt="Screenshot 2022-01-18 at 03 48 25" src="https://user-images.githubusercontent.com/400092/149867751-5c2c7f35-cefd-4d6f-899a-fecde3a5381e.png">

**Comment by MGatner** [comment]
I will check in desktop, 1.5 hours.

**Comment by samsonasik** [comment]
@MGatner it should be resolved now at latest `"rector/rector": "dev-main"`:

Please try latest dev-main with `--clear-cache`:

```bash
composer global require --dev rector/rector:dev-main

rector process --clear-cache
```

**Comment by MGatner** [comment]
I tested with `dev-main` and both problems appear to be resolved! I will do some more thorough experimenting once this is released.

**Comment by MGatner** [comment]
🥳 On the release! Bounty sent via sponsorship.
