### ISSUE TITLE
\Doctrine\Common\Collections\Collection mistakes?

### ISSUE THREAD

**Issue by PhilETaylor** [rectorphp/rector#6947]
Between rector/rector-src@bf2f6dd0e9a4b0abccdc345e588f1f713452848b and rector/rector-src@654b5861ca943231ffd6430062cc06d2a6f956e5 (The last day or two of changes)

something changed that now is changing all public properties to \Doctrine\Common\Collections\Collection type hinted?
<img width="683" alt="Screenshot 2022-01-18 at 04 05 58" src="https://user-images.githubusercontent.com/400092/149869201-65c72448-aa96-4d89-872e-a7beebdabbe4.png">

**Comment by PhilETaylor** [comment]
Here is an example, a Symfony Command file, that gets changed with TypedPropertyFromToManyRelationTypeRector even though this is nothing to do with a doctrine entity or relationship
<img width="1111" alt="Screenshot 2022-01-18 at 04 29 06" src="https://user-images.githubusercontent.com/400092/149871230-131af8ac-d87d-4153-801c-9cfe821c726b.png">

**Comment by samsonasik** [comment]
@PhilETaylor could you create failing test case PR for it? Thank you.

**Comment by PhilETaylor** [comment]
Yeah sorry, was on my todo list, but it was 3am and I needed sleep.

The PR is here in rector-doctrine as that's where the source is https://github.com/rectorphp/rector-doctrine/pull/76

Hope that helps.

**Comment by TomasVotruba** [comment]
Thanks for the test case :+1: I was working on it yestereday, so it seems I broke it. I'll check the test and fix it

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-doctrine/pull/77 :+1:

**Comment by PhilETaylor** [comment]
Awesome - thanks.
