### ISSUE TITLE
Documentation: StringClassNameToClassConstantRector configuration outdated

### ISSUE THREAD

**Issue by wernerkrauss** [rectorphp/rector#6948]
# Bug Report

See [documentation](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#stringclassnametoclassconstantrector)

It seems, the documentation about configuring this rector is outdated. It shows how to define aliasses, but in currentRector 0.12 it automatically replaces all strings, which is sometimes not wanted for unnamespaced classes.

## Expected Behaviour

Documentation should show how to configure classes to skip, e.g. like

```
    $services->set(StringClassNameToClassConstantRector::class)
        ->configure([StringClassNameToClassConstantRector::CLASSES_TO_SKIP => ['SkipOne', 'SkipTwo]]);
```

**Comment by sabbelasichon** [comment]
Could you create PR for that? Thank you.

**Comment by samsonasik** [comment]
The `CLASSES_TO_SKIP` constant is deprecated, so the existing documentation is correct.

ref https://github.com/rectorphp/rector/blob/361d8f4a2fdd89508f0ca5487a93b3a84b95122c/rules/Php55/Rector/String_/StringClassNameToClassConstantRector.php#L31__
