### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by berezuev** [rectorphp/rector#6949]
# Bug Report

Hi! Thanks for your work.

Found this bug:
If I use **UP_TO_PHP_80** and **ANNOTATIONS_TO_ATTRIBUTES** (no matter SymfonySet or DoctrineSet) rules at the same time, rector deletes annotation, but it shouldn't.
When I comment one one the rules, rector works properly.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec791b9-a03d-67f8-9c5f-591c1ce23882

```php
<?php

use OpenApi\Annotations as OA;

class TestResponse
{
    /**
     * @OA\Property(
     *     type="array",
     *     @OA\Items(ref=@Model(type=TestItem::class))
     * )
     */
    public array $items;

    public function __construct(array $items = [])
    {
        $this->items = $items;
    }
}
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

To keep `@OA\Property` annotation.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by berezuev** [comment]
@TomasVotruba https://github.com/rectorphp/rector-src/pull/1702
