### ISSUE TITLE
Support for thecodingmachine/safe v2?

### ISSUE THREAD

**Issue by Knallcharge** [rectorphp/rector#6956]
# Question
After updating to thecodingmachine/safe version 2, rector wants me to use safe-functions (e.g. sprintf oder array_flip) that have been removed from the safe-library. Applied rule is "RenameFunctionRector"
I'm not sure if rector is causing this or some plugin? (phpstan works fine and "knows" that the missing functions don't need to be replaced)

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. I'm not sure what exactly is the issue.  We don't have a set for safe package functions, they handle it on their own.

Could you share minimal `rector.php` setup and minimal code that behaves incorrectly?
The https://getrector.org/demo link with such setup would be useful.

**Comment by Knallcharge** [comment]
Hi, thanks for getting back! Here's a code example that will produce the result:
https://getrector.org/demo/1ec7ab6e-6cd5-68a6-83aa-497f51f82d7f

The behaviour is correct for safe <v2 and wrong for safe >=v2

**Comment by TomasVotruba** [comment]
Thanks for sharing.
I think that's related to version 0.7. This config should not be in your rector.php unless you're using version safe 0.7. 

I realize it might be confusing, this set is rather legacy and not maintained. Instead use explicit RenameFunctionRector with own configuration.

**Comment by Knallcharge** [comment]
Got it, thanks!
