### ISSUE TITLE
CountOnNullRector Converting Known Array

### ISSUE THREAD

**Issue by MGatner** [rectorphp/rector#6961]
# Bug Report

OS: Ubuntu 20.04
PHP: 7.4.11
Rector: dev-main
Install: Global

Rector keeps trying to check `is_countable()` on what is definitely an array:
```diff
-            log_message('debug', 'Merged ' . count($chunks) . ' chunks to ' . $path);
+            log_message('debug', 'Merged ' . (is_countable($chunks) ? count($chunks) : 0) . ' chunks to ' . $path);
```

## Minimal PHP Code Causing Issue

I've tried to recreate this. I don't know if it is an issue with me, different Rector versions, or the actual code and config. Here's my latest (failed) attempt: https://getrector.org/demo/1ec7c946-5f44-6b9c-80b3-dfab2a5e5b19

This is happening "live" here: https://github.com/tattersoftware/codeigniter4-files/tree/devkit
Here is the code: https://github.com/tattersoftware/codeigniter4-files/blob/31d4fbea62773d23ec2fde7094b0a495bd3cf1da/src/Controllers/Files.php#L375-L389
 And proof that `get_filenames()` always returns an array: https://github.com/codeigniter4/CodeIgniter4/blob/203d038536817f28075d897ce373cece493a5a50/system/Helpers/filesystem_helper.php#L198

## Expected Behaviour

Rector should skip this line since `$chunks` is always an array.
<img width="836" alt="Screen Shot 2022-01-23 at 4 36 32 PM" src="https://user-images.githubusercontent.com/17572847/150699017-8f1a619a-8786-4397-baef-166910db1a64.png">

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by MGatner** [comment]
I will try, but it won't be that easy because these are on different versions. I still have to run `dev-main` locally because of https://github.com/rectorphp/rector/issues/6903, which still causes failures under GitHub Actions (https://github.com/tattersoftware/codeigniter4-files/runs/4914919040?check_suite_focus=true#step:7:72) so the incorrect refactor doesn't happen there. I will try to recreate the versioning under a GitHub Action to see if I can get it to show.

**Comment by MGatner** [comment]
Or if you have an ETA on the next release I can circle back to this after that is posted 🤗

**Comment by MGatner** [comment]
@TomasVotruba I was able to capture it live in a GitHub Action run: https://github.com/tattersoftware/codeigniter4-files/runs/4915964172?check_suite_focus=true

Note that this is forcing the global install to `dev-main`.

**Comment by MGatner** [comment]
I've tried to recreate this again in Demo but it won't run - no error or anything, hitting "Process" just reloads the page. Latest attempt: https://getrector.org/demo/1ec7cb3f-4415-668c-a312-5f938340e651

**Comment by samsonasik** [comment]
@MGatner that's due to dynamic load scan dir helper, you can use phpstan as rector path config, eg:

```php
$parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, __DIR__ . '/phpstan.neon.dist');
```

so the scan dirs in phpstan config will be included.

I created PR https://github.com/tattersoftware/codeigniter4-files/pull/39 for it.
