### ISSUE TITLE
Incorrect behavior of DowngradeCovariantReturnTypeRector

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#6962]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec7ce44-7797-6048-a79e-8f3e2411f1cf

```php
<?php

class ParentClass
{
}

class ChildClass extends ParentClass
{
}

interface AnotherContainerInterface
{
    public function get(): ParentClass;
}

final class YetAnotherContainer implements AnotherContainerInterface
{
    use AnotherServiceLocatorTrait;
}

trait AnotherServiceLocatorTrait
{
    public function get(): ChildClass
    {
    }
}
```

### Responsible rules

* `DowngradeCovariantReturnTypeRector`

## Expected Behavior

The rule should be applied within the trait (but currently it is not):

```diff
trait AnotherServiceLocatorTrait
{
-    public function get(): ChildClass
+    public function get(): \ParentClass
    {
    }
}
```

Outside of the trait, the rule works well, as in this example: https://getrector.org/demo/1ec7ce25-8e11-64b4-b1f7-f9a087cf185b

I understand that modifying the code inside a trait is risky, since some other class could be using the trait, which is not expecting the change. However, this same behavior has been applied for `DowngradeParameterTypeWideningRector`, where code inside a trait is being replaced. Check this example:

https://getrector.org/demo/1ec7ce1a-17bd-6624-8e24-9d57bb209bad

Then, to keep the behavior consistent, `DowngradeCovariantReturnTypeRector` should also be applied within traits.

**Comment by leoloso** [comment]
Since the PR has been closed, I replicate here the last comments I added there.

[Comment #1](https://github.com/rectorphp/rector-src/pull/1717#issuecomment-1024872677):

I've tried for some time now, but I am not able to crack it. For what I can see, `DowngradeParameterTypeWideningRector` works because it always removes the parameter type:

```php
    private function removeParamTypeFromMethod(ClassMethod $classMethod, int $paramPosition): void
    {
        $param = $classMethod->params[$paramPosition] ?? null;
        if (! $param instanceof Param) {
            return;
        }

        // Add the current type in the PHPDoc
        $this->nativeParamToPhpDocDecorator->decorate($classMethod, $param);
        $param->type = null;
    }
```

Setting `$param->type = null;` presents no problem, since there is no need to coordinate traits, classes and interfaces.

`DowngradeCovariantReturnTypeRector` is different: it is attempting to change the type, from `ChildClass` to `ParentClass`, where `ParentClass` is in the interface implemented by the class that uses the trait. Then, I don't know how to reach from the trait to that interface, more taking into account that many classes may implement the trait. It looks quite complex, and I'm intimidated by it.

I can see the following options:

1. Try to retrieve `ParentClass` from the Class (or Classes) that uses that Trait, and then change it on the Trait. (Someone else than me, this development is out of my depth)
2. Always remove the return type, everywhere that is affected (Traits, Classes and Interfaces), similar to `DowngradeParameterTypeWideningRector`
3. Do not execute `DowngradeCovariantReturnTypeRector` on Traits, and create another rule to manually change the type on the affected trait by configuration. I tried doing this with `AddReturnTypeDeclarationRector` but it didn't work on the Trait. So either modify this rule to also work on Traits, or create a similar rule for Traits.

Btw, in the 2nd case, I wonder if the 2 rules, `DowngradeParameterTypeWideningRector` and `DowngradeCovariantReturnTypeRector`, could reuse the same logic, just changing the action to take. In the 1st one, remove the param type; in the 2nd, remove the return type. All the previous code (`refactor`, `shouldSkip`, etc) is the same that's already implemented in `DowngradeParameterTypeWideningRector`.

[Comment #2](https://github.com/rectorphp/rector-src/pull/1717#issuecomment-1024875563):

Just to make sure: is `DowngradeParameterTypeWideningRector` checking if the param type of the Class and the Trait are different? Or does it just set it to `null` no matter what (as I said in my comment above)? Tbh I don't fully understand the code, so I'm not reliable in my judgement.

If it is, then this could be a solution:

> Btw, in the 2nd case, I wonder if the 2 rules, `DowngradeParameterTypeWideningRector` and `DowngradeCovariantReturnTypeRector`, could reuse the same logic, just changing the action to take. In the 1st one, remove the param type; in the 2nd, remove the return type. All the previous code (`refactor`, `shouldSkip`, etc) is the same that's already implemented in `DowngradeParameterTypeWideningRector`.

**Comment by TomasVotruba** [comment]
The trait limitations are defined by language. We don't know where the trait is used, so we cannot downgrade for sure. The PHPStan we run on parses classes one by another, so we never have a full scope.

If you find a way to deal with this issue, please send PR :+1:
