### ISSUE TITLE
Incorrect behavior of FinalizePublicClassConstantRector

### ISSUE THREAD

**Issue by algorun77** [rectorphp/rector#6963]
# Bug Report

Hello, I found an issue with the FinalizePublicClassConstantRector rule.

## For test case
| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## In my own project
| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | f09e54b79cdc481f2033482fd206f6308642b2e0 (0.12.13)   |
| Installed as   | composer dependency  |
| PHP version | 8.1.1 |
| PHP_CodeSniffer | version 3.6.2 |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec7cf00-4e01-655a-af8f-631be22a338f

```php
<?php

class DemoFile
{
    public const MY_CONSTANT = "Hello world!";
    
    public function __construct()
    {
    }
}
```

### Responsible rules

* `FinalizePublicClassConstantRector`

## Expected Behavior

The rule is correct by adding the `final` keyword in the constant declaration, by as stated in the PHP documentation ([https://www.php.net/manual/en/language.oop5.final.php](https://www.php.net/manual/en/language.oop5.final.php)), in example 3, the `final` keyword should be the first of the line. So, instead of :
```diff
-    public const MY_CONSTANT = "Hello world!";
+    public final const MY_CONSTANT = "Hello world!";
```

We should have :
```diff
-    public const MY_CONSTANT = "Hello world!";
+    final public const MY_CONSTANT = "Hello world!";
```
I want to note that I'm using PHPCS in my project and it triggers a warning with the actual rule (public final), but none when I apply my correction (final public). The warning being :
**phpcs: warning - Visibility must be declared on all constants if your project supports PHP 7.1 or later**

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by algorun77** [comment]
> Thank you for your report and demo link!
> 
> Could you send a failing test case in a pull-request, so we have it covered in Rector? You can click "Create a Test" button at demo page.

Hello,

I'll try to do it this week-end, but I'm not very familiar with test cases... yet! I'll come back when it's done

**Comment by Bl00D4NGEL** [comment]
The underlying problem actually happens in the PhpParser packege because that one is responsible for printing the file (afaik, anyway). I think the function that is causing this is https://github.com/nikic/PHP-Parser/blob/a6e34665fd6a2bcefc924cb5fd73788767ae510e/lib/PhpParser/PrettyPrinterAbstract.php#L1075. If we change the order in which the flags are printed it could fix this problem.

**Comment by TomasVotruba** [comment]
> If we change the order in which the flags are printed it could fix this problem.

It would be better to change directly in php-parser IMO.

**Comment by TomasVotruba** [comment]
Closing as issue moved to https://github.com/nikic/PHP-Parser/pull/826
