### ISSUE TITLE
[FinalizePublicClassConstantRector] Ignore final classes

### ISSUE THREAD

**Issue by Bl00D4NGEL** [rectorphp/rector#6964]
# Feature Request

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec7d0d7-7bb2-68cc-b5e0-11dedf8f8668

```php
<?php

final class DemoFile
{
    public const TEST_CONSTANT = 'test';
}
```

### Responsible rules

* `FinalizePublicClassConstantRector`

## Expected Behavior

The rector should ignore classes that are marked as final as the class cannot be extended anyway, thus making the constants final is redundant. 

I expect the rector to not change the file at all if it is final.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

This is quite easypick. Would you like to contribute this feature to Rector code?

**Comment by Bl00D4NGEL** [comment]
> Thank you for your report and demo link!
> 
> Could you send a failing test case in a pull-request, so we have it covered in Rector? You can click "Create a Test" button at demo page.
> 
> This is ideal easypick issue. Would you like to contribute this feature to Rector code?

Done, see https://github.com/rectorphp/rector-src/pull/1720. As I'm already quite familiar with the code I'll leave it open to new contributors willing to help :)

**Comment by TomasVotruba** [comment]
Could you send fix as well, so we can merge it?

**Comment by reypm** [comment]
@TomasVotruba I was running into the same issue and tried to contribute but I am not familiar with the codebase perhaps with some guidance from your side I would be able to send a PR for this

**Comment by Bl00D4NGEL** [comment]
@reypm You will need to modify the `\Rector\Php81\Rector\ClassConst\FinalizePublicClassConstantRector` class and find the parent class node of the constant. 

You can probably do that by using the `BetterNodeFinder` that is already a property of the AbstractRector class. There is a function called `findParentByTypes` which could be used to get the `\PhpParser\Node\Stmt\Class_` node (parent class).
On that you could check whether or not that one has a final flag or not (a Class_ node has a `isFinal` function) and if it is final you could early return from the rector (similar to how it is done if the constant is private, protected or already final)

**Comment by reypm** [comment]
@Bl00D4NGEL perfect! will try to get a fix for this ASAP, thank you!

**Comment by TomasVotruba** [comment]
@reypm This docs might be useful for adding the test - https://github.com/rectorphp/rector/blob/main/docs/how_to_add_test_for_rector_rule.md#4-find-the-rector-test-case

**Comment by reypm** [comment]
@TomasVotruba @samsonasik @Bl00D4NGEL now that we have this fixed should we create a Rule to remove the final from the already modified classes? 🤔  ie:
```php
// before
final class A {
    final public const AC = 'const';
}

// after
final class A {
    public const AC = 'const';
}
```
Having the const as `final` does not harm anyone and code still works but when you use another static analysis tools https://github.com/nunomaduro/phpinsightslike you start getting "errors" like:

> ::error file=/var/www/ACL/Add.php,line=11::* [Unnecessary final modifier] Unnecessary FINAL modifier in FINAL class

**Comment by samsonasik** [comment]
@reypm feel free to create new rector rule PR for that, should be in `DeadCode` or `CodingStyle` namespace I think

**Comment by reypm** [comment]
@samsonasik I'm working in the PR but something is not working as it should be for me, where I can ask for support help? I don't want to hijack this thread but I am not sure if a new one with the PR code should be opened for this purpose. Any help?

**Comment by samsonasik** [comment]
You can start with create a draft PR to see what that's not working
