### ISSUE TITLE
Skipping IsCountableRector

### ISSUE THREAD

**Issue by mhabibi** [rectorphp/rector#6968]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.13   |
| PHP version | 7.4.27   |

## Minimal PHP Code Causing Issue

see [here](https://getrector.org/demo/1ec7dbc3-29fb-6226-a49a-bffe159a7bdd)

### problem
Running rector with default settings causes this change:
```diff
-        if (count($rawMessages) === 0) {
+        if ((is_countable($rawMessages) ? count($rawMessages) : 0) === 0) {
```
But when I skip the related rule, it still do the changes.

## Expected Behaviour
If the rule is skipped, the change doesn't happen.

Here is my rector.php:

```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src',
    ]);

    $parameters->set(Option::SKIP, [
        IsCountableRector::class,
    ]);

    // Define what rule sets will be applied
    $containerConfigurator->import(LevelSetList::UP_TO_PHP_74);
};
```

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by mhabibi** [comment]
@TomasVotruba Hello Tomas

Here you go https://getrector.org/demo/1ec7dbc3-29fb-6226-a49a-bffe159a7bdd

**Comment by mhabibi** [comment]
Actually the applied rule is CountOnNullRector. I misunderstood the rule I should skip. This can be closed I think.

**Comment by samsonasik** [comment]
Ok, I am closing it as you found the solution
