### ISSUE TITLE
\DirectoryNotFoundException: The "worker" directory does not exist.

### ISSUE THREAD

**Issue by PhilETaylor** [rectorphp/rector#6971]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 745312279397f8b6797e28e15c569130a486e33d           |

using local command `vendor/bin/rector process` with parallel = true. 

Strange one today, this project has been working well for parallel for some time - thanks to your great work - but today two different projects on my Mac are giving this exception.

I have tried downgrading rector to the revision every night 
e5ed2372b9551e9b10a7fad5fc9dbd85a54d5d88
42a0272cc51c23ff90054540abae3cb1cdc80a8b
62081a03cccf860e701ae2819afe7c61b191c643
1725b8b7fd82f8bec63b6f237778f4b3e9ebc609
5021de4148d14996780ea9332bb6e83a6d2a8d2a
333852550dba389576cc4dd8e38515b932f5bcf0

which is about 3 days of revisions... and the problem exists in all of them HOWEVER I know for a fact this was working less than an hour ago with 745312279397f8b6797e28e15c569130a486e33d (The latest dev-main) 

So, the problem is obviously not with Rector but my Mac... but Im not specifying a Worker dir: 

`->set(Option::PATHS, [__DIR__.'/src',__DIR__.'/tests',__DIR__.'/config',__DIR__.'/bin'])`

and the problem DOESN'T exist if I disable parallel with `->set(Option::PARALLEL, false)` so its related to parallel mode, and therefore I assume the "worker" directory is the client processes ? 

So I thought I would report it anyway, as I know you are working hard on getting Parallel working well. 

Im going to reboot my Mac now (a rare thing, maybe once every three months I reboot, leaving the Mac on 24/7!) and see if there is some kind of stuck process released... 

Thoughts?

```
[ERROR] Could not process some files, due to:
         "Child process error: PHP Fatal error:  Uncaught
         RectorPrefix20220118\Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "worker" directory does
         not exist. in vendor/rector/rector/vendor/symfony/finder/Finder.php:591
         Stack trace:
         #0 vendor/rector/rector/src/FileSystem/FilesFinder.php(89):
         RectorPrefix20220118\Symfony\Component\Finder\Finder->in(Array)
         #1 vendor/rector/rector/src/FileSystem/FilesFinder.php(77):
         Rector\Core\FileSystem\FilesFinder->findInDirectories(Array, Array)
         #2 vendor/rector/rector/src/FileSystem/PhpFilesFinder.php(33):
         Rector\Core\FileSystem\FilesFinder->findInDirectoriesAndFiles(Array)
         #3 vendor/rector/rector/src/StaticReflection/DynamicSourceLocatorDecorator.php(48):
         Rector\Core\FileSystem\PhpFilesFinder->findInPaths(Array)
         #4 vendor/rector/rector/src/Console/Command/ProcessCommand.php(132):
         Rector\Core\StaticReflection\DynamicSourceLocatorDecorator->addPaths(Array)
         #5 vendor/rector/rector/vendor/symfony/console/Command/Command.php(282):
         Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220118\Symfony\Component\Console\Input
         \ArgvInput), Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #6 vendor/rector/rector/vendor/symfony/console/Application.php(853):
         RectorPrefix20220118\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220118\Symfony\Compone
         nt\Console\Input\ArgvInput), Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #7 vendor/rector/rector/vendor/symfony/console/Application.php(289):
         RectorPrefix20220118\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Pro
         cessCommand), Object(RectorPrefix20220118\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #8 vendor/rector/rector/src/Console/ConsoleApplication.php(67):
         RectorPrefix20220118\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220118\Symfony\Component
         \Console\Input\ArgvInput), Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #9 vendor/rector/rector/vendor/symfony/console/Application.php(187):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220118\Symfony\Component\Console\Input\ArgvI
         nput), Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #10 vendor/rector/rector/bin/rector.php(57): RectorPrefix20220118\Symfony\Component\Console\Application->run()
         #11 vendor/rector/rector/bin/rector(5): require_once('/Users/phil/Sit...')
         #12 vendor/bin/rector(117): include('/Users/phil/Sit...')
         #13 {main}
           thrown in vendor/rector/rector/vendor/symfony/finder/Finder.php:591
         Fatal error: Uncaught RectorPrefix20220118\Symfony\Component\Finder\Exception\DirectoryNotFoundException: The
         "worker" directory does not exist. in vendor/rector/rector/vendor/symfony/finder/Finder.php:591
         Stack trace:
         #0 vendor/rector/rector/src/FileSystem/FilesFinder.php(89):
         RectorPrefix20220118\Symfony\Component\Finder\Finder->in(Array)
         #1 vendor/rector/rector/src/FileSystem/FilesFinder.php(77):
         Rector\Core\FileSystem\FilesFinder->findInDirectories(Array, Array)
         #2 vendor/rector/rector/src/FileSystem/PhpFilesFinder.php(33):
         Rector\Core\FileSystem\FilesFinder->findInDirectoriesAndFiles(Array)
         #3 vendor/rector/rector/src/StaticReflection/DynamicSourceLocatorDecorator.php(48):
         Rector\Core\FileSystem\PhpFilesFinder->findInPaths(Array)
         #4 vendor/rector/rector/src/Console/Command/ProcessCommand.php(132):
         Rector\Core\StaticReflection\DynamicSourceLocatorDecorator->addPaths(Array)
         #5 vendor/rector/rector/vendor/symfony/console/Command/Command.php(282):
         Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220118\Symfony\Component\Console\Input
         \ArgvInput), Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #6 vendor/rector/rector/vendor/symfony/console/Application.php(853):
         RectorPrefix20220118\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220118\Symfony\Compone
         nt\Console\Input\ArgvInput), Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #7 vendor/rector/rector/vendor/symfony/console/Application.php(289):
         RectorPrefix20220118\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Pro
         cessCommand), Object(RectorPrefix20220118\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #8 vendor/rector/rector/src/Console/ConsoleApplication.php(67):
         RectorPrefix20220118\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220118\Symfony\Component
         \Console\Input\ArgvInput), Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #9 vendor/rector/rector/vendor/symfony/console/Application.php(187):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220118\Symfony\Component\Console\Input\ArgvI
         nput), Object(RectorPrefix20220118\Symfony\Component\Console\Output\ConsoleOutput))
         #10 vendor/rector/rector/bin/rector.php(57): RectorPrefix20220118\Symfony\Component\Console\Application->run()
         #11 vendor/rector/rector/bin/rector(5): require_once('/Users/phil/Sit...')
         #12 vendor/bin/rector(117): include('/Users/phil/Sit...')
         #13 {main}
           thrown in vendor/rector/rector/vendor/symfony/finder/Finder.php:591
```

**Comment by PhilETaylor** [comment]
and as expected, a reboot of the Mac fixed this issue. 

However, Im guessing that's not the right fix, and that something can be done in rector to catch such issues?

**Comment by TomasVotruba** [comment]
> and as expected, a reboot of the Mac fixed this issue.

Great :+1:  Does it happen again? It will be cache issue probably.

It look like path issue, as "worker" is name of command, not directory.

If it happens again, please share the reproducible repository.

**Comment by PhilETaylor** [comment]
I cannot reproduce on demand so cannot provide a  reproducible repository sorry 

Happened again today.

I ran rector, ecs, rector rector and then it broke... 

<img width="954" alt="Screenshot 2022-02-03 at 15 50 39" src="https://user-images.githubusercontent.com/400092/152377899-30acfee7-5e2f-423d-82cf-62c7e98cea09.png">

**Comment by TomasVotruba** [comment]
I'm sorry to hear that. We'll need the reproducer, as it didn't happen to any Rector contributor nor on CI for past ~4 months we are working with parallel.

**Comment by PhilETaylor** [comment]
yeah I understand that... 

I think it might have something to do with docker and large amounts of file changes... 

I have to reboot the Mac to get it to work again after this.

**Comment by TomasVotruba** [comment]
Maybe there is a better solution. What is the reason using Rector in Docker on repeated-basis? 
Usually use case is to put such tool in CI and let composer handle it.

Unless you're project runs on PHP 7.0 and bellow. But even then we usually use CI with higher PHP version and let Rector have our back there.

**Comment by PhilETaylor** [comment]
Dont worry - not looking for help and support :) 

Im not actually running the rector command *IN* the docker containers. 

I was cleaning up a legacy client project but I had containers also running which mounted those folders.I use PHP 8.1.2 command line on the Mac - outside of docker - even though this customers project I inherited is PHP 5.5 in the docker containers :( dont ask.....

Docker for Mac is a clusterfuck of file sync issues... its well known for being unperformant on Mac, and Im suspecting this. 

I have time over the weekend to try and break it, if I can break it repeatedly then I'll let you know. There is obviously "something" wrong, but at the moment I have no idea what. 

Im also running MacOS 12.3 Beta... so that also could be an issue

I note I get 2-3 hangs a day at the moment, always when Time Machine is trying to backup too... so again could be that.

Im not worried, and only logged it here for information and if others have the same issue then at least they will not feel alone and we can try and pool ideas on what's causing it.
