### ISSUE TITLE
Incorrect behavior of FinalizePublicClassConstantRector

### ISSUE THREAD

**Issue by trandbert37** [rectorphp/rector#6973]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.15      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec7f537-6973-6358-8246-11db50a94ec6

```php
<?php

abstract class ParentClass
{
    public const TEST_CONSTANT = 'value1';
}

class ChildClass extends ParentClass
{
    public const TEST_CONSTANT = 'value2';
}
```

### Responsible rules

* `FinalizePublicClassConstantRector`

## Expected Behavior

I think "final" should not be added. Because we want to be able to override the constant in this case.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.
