### ISSUE TITLE
How to keep the permissions of the files

### ISSUE THREAD

**Issue by mhabibi** [rectorphp/rector#6974]
# Question
I am using rector inside the container and run it with this:

`docker-compose exec -T my_app_name vendor/bin/rector process --ansi path/to/file.php`

What it does is that it changes the file permissions as below:

```diff
- -rw-rw-r-- 1 my_user my_user 2173 Jan 27 15:41 path/to/file.php
+ -rw-rw-r-- 1 root root 2173 Jan 27 15:41 path/to/file.php
```

I would like to keep the permissions of the files as they are. How can I achieve that?

I am using an Ubuntu 20.04 LTS in my host machine.

**Comment by ian-zunderdorp** [comment]
This is a docker issue and not a rector user. When you're running it through docker-compose, most images and docker-compose configurations will be using the root user within the container. You'll have to configure it to use your host user id & group id instead.

Useful resources:
* https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf
* https://jtreminio.com/blog/running-docker-containers-as-current-host-user/
