### ISSUE TITLE
Programmatic invocation of Rector

### ISSUE THREAD

**Issue by ryangjchandler** [rectorphp/rector#6975]
# Question

Is it possible to trigger/invoke Rector programatically - I'm looking to provide the configuration this way too, including the target/source directory that Rector should act on.

**Comment by TomasVotruba** [comment]
Hi, the best way is to use CLI. You can also re-create to container with Rector\Core\DependencyInjection\RectorContainerFactory.

**Comment by TomasVotruba** [comment]
What exactly is your goal?

**Comment by TomasVotruba** [comment]
Good choice!
İ use it same way for specific detection tasks :) mostly in @symplify/easy-ci
