### ISSUE TITLE
@inheritDoc ignored by PropertyTypeDeclarationRector

### ISSUE THREAD

**Issue by oprypkhantc** [rectorphp/rector#6977]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e33afe6434a9707374815bb977cff09b6e57c199 (0.12.12)             |

`PropertyTypeDeclarationRector` rector (and likely others that from type declarations set too) ignores the `@inheritDoc` PHPDoc tag.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec82cad-b930-6c3a-9497-076a0a25b40d

## Expected Behaviour

Rector should skip adding a property type declaration if it has an `@inheritdoc` tag declared.

**Comment by TomasVotruba** [comment]
Hi, thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by oprypkhantc** [comment]
Sure thing, here you go: https://github.com/rectorphp/rector-src/pull/1752

**Comment by samsonasik** [comment]
resolved at https://github.com/rectorphp/rector-src/pull/1752
