### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivateMethodParameterRector

### ISSUE THREAD

**Issue by adoy** [rectorphp/rector#6979]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec83cc2-6cb0-6a48-ac80-6141ca2d3a71

```php
<?php

declare(strict_types=1);

namespace YourAppNamespace\Configuration;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class ConfigDefinition implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('app');
        $rootNode = $treeBuilder->getRootNode();
        $this->buildConfigTree($rootNode);
        return $treeBuilder;
    }

    private function buildConfigTree($rootNode): void
    {
        $rootNode
            ->children()
                ->arrayNode('logger')
                    ->isRequired()
                    ->children()
                    ->end()
                ->end()
                ->arrayNode('pod')
                    ->isRequired()
                    ->children()
                        ->scalarNode('cluster')->isRequired()->cannotBeEmpty()->end()
                        ->scalarNode('name')->isRequired()->cannotBeEmpty()->end()
                        ->scalarNode('namespace')->isRequired()->cannotBeEmpty()->end()
                        ->scalarNode('image_id')->isRequired()->cannotBeEmpty()->end()
                    ->end()
                ->end()
                ->arrayNode('messaging')
                    ->isRequired()
                    ->children()
                        ->scalarNode('host')->isRequired()->cannotBeEmpty()->end()
                        ->integerNode('port')->defaultValue(5672)->end()
                        ->scalarNode('user')->isRequired()->cannotBeEmpty()->end()
                        ->scalarNode('password')->isRequired()->cannotBeEmpty()->end()
                        ->scalarNode('vhost')->isRequired()->cannotBeEmpty()->end()
                        ->scalarNode('dsn')->isRequired()->cannotBeEmpty()->end()
                    ->end()
                ->end()
                ->arrayNode('app')
                    ->isRequired()
                    ->children()
                        ->scalarNode('secret')->isRequired()->cannotBeEmpty()->end()
                    ->end()
                ->end()
            ->end();
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodParameterRector`

## Expected Behavior

It should do nothing

**Comment by samsonasik** [comment]
You can handle it by increase `Option::NESTED_CHAIN_METHOD_CALL_LIMIT` in the rector config, ref 

https://getrector.org/demo/1ec83f3e-4f7a-6aae-b3a7-4f64c0be322f

**Comment by adoy** [comment]
@samsonasik @TomasVotruba Thanks for the answer. 

Although, I think the problem here is the deep chain method calls being removed silently. It would be nice to get some kind of warnings that will trigger users attention on this specific class/method.

What do you think ? Is this something that could easily be added ?

**Comment by TomasVotruba** [comment]
> What do you think ? Is this something that could easily be added ?

You're right. I would not be against such a improvement :+1:

**Comment by adoy** [comment]
@TomasVotruba I can have a try, but I have no knowledge of rector's internal. Is there already some mechanism in place to do this kind of things ? Could you give me some hints on how you would implement it ?

**Comment by TomasVotruba** [comment]
I'm not aware on such mechanism, but I'd start looking in the place where "NESTED_CHAIN_METHOD_CALL_LIMIT" is used.
That might be right spot to add such notification message. Probably by adding to some error collector service.

**Comment by adoy** [comment]
Yep I found the place where it is used, but I need to look at how to collect this warning and display it in user terminal at the end.
Missing piece is the error collector service ! I'll take some time to read some parts of the code to find if there is already such a thing !

Thanks

**Comment by TomasVotruba** [comment]
It looks like you're on the right track :wink:  Thank you :clap:
