### ISSUE TITLE
Symfony Route annotation with default null is converted into string

### ISSUE THREAD

**Issue by jokaorgua** [rectorphp/rector#6983]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 75c0b27d37ee34844b0eb5faf35742c6631d5ab2             |

When a route has a parameter and it is set to null as default the null is converted into 'null' string

## Minimal PHP Code Causing Issue

```php
Route("/route/with/some/parameter/{parameter}", name="some.route", methods={"GET"}, defaults={"parameter": null})
```

is converted into

```php
[Route(path: '"/route/with/some/parameter/{parameter}"', name: 'some.route', defaults: ['title' => 'null'], methods: ['GET'])]
```

## Expected Behaviour
```php
[Route(path: '"/route/with/some/parameter/{parameter}"', name: 'some.route', defaults: ['title' => null], methods: ['GET'])]
```

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by jokaorgua** [comment]
@TomasVotruba 

https://getrector.org/demo/1ec84dbc-774c-6294-bd5f-d1f4b7babf86

**Comment by TomasVotruba** [comment]
Minimal example: https://getrector.org/demo/1ec84ddf-fac4-6590-b7e1-a30857517a67

Thanks :+1: 

Could you send a test case PR?

**Comment by jokaorgua** [comment]
@TomasVotruba sorry, don't have time for PR. Maybe in couple of weeks

**Comment by TomasVotruba** [comment]
You can click "Create a Test" button at demo page to speed up the process significantly.

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-src/pull/1766
