### ISSUE TITLE
Allow to configure excluded targets for ExplicitMethodCallOverMagicGetSetRector

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#6984]
# Feature Request

The issue is also described in https://github.com/rectorphp/rector/issues/6980:
> I found this issue because of a Laravel issue with models on which I would also suggest another change to `ExplicitMethodCallOverMagicGetSetRector`.
> We have a model with an attribute 'relation'. Because the `HasRelationships`-trait has a method `setRelation` assigning a value to the relation-property is fixed to calling `setRelation`, which is not what we want. At the moment it is possible to skip applying rules to certain files, but normally in this case the rule should be skipped for a certain target. In a normal case we handle the model outside of the models directory. So we want to say "do not apply rule when the handled class is an instance of Model". Could the `ExplicitMethodCallOverMagicGetSetRector` be configured to skip certain classes?

In case we have a class (or a certain set of classes) that is/are meant to be 'magic' using `__get` and/or `__set`, it is currently not possible to exclude the **usage** of this classes from the ExplicitMethodCallOverMagicGetSetRector rule in a generic way.

I suggest to make it possible to configure exclusions (targets) from this rule.

An abstract from Laravel Eloquent shows more detail on the problem:
```php
abstract class Model {
   private array $attributes = [];
   private array $relations = [];
    /**
     * Dynamically set attributes on the model.
     */
    public function __set($key, $value)
    {
        $this->setAttribute($key, $value);
    }

    /**
     * Set a given attribute on the model.
     */
    public function setAttribute($key, $value)
    {
        // do some internals, but in general result in:
       $this->attributes[$key] = $value;
    }

    /**
     * Set the given relationship on the model.
     */
    public function setRelation($relation, $value)
    {
        $this->relations[$relation] = $value;

        return $this;
    }
}

/**
 * @property ?string $relation
 */
class MyModel extends Model {
}

$myModel = new MyModel();
$myModel->relation = 'foo'; // at the moment this will get fixed to $myModel->setRelation('foo');
```

After https://github.com/rectorphp/rector-src/pull/1763 the chance that this kind of setters will be fixed is much lower, but for instance the rule could be fixing to `setDateFormat` in Laravel for example. It is clear that the `__set` here is meant to fill values in the attributes property and not to be setting properties directly on the instance.

I suggest to make it possible to exclude classes (and child classes) from this rule.

```php
    $services->set(ExplicitMethodCallOverMagicGetSetRector::class)
        ->configure([new ExcludedClasses([Model::class])]);
```

**Comment by TomasVotruba** [comment]
The config option makes sense 👍 

Could you add i

**Comment by samsonasik** [comment]
@gisostallenberg you can make the rule implements `Rector\Core\Contract\Rector\AllowEmptyConfigurableRectorInterface`

**Comment by TomasVotruba** [comment]
Your suggestion is accepted and welcomed. Closing to keep focus on active buggy issues.

Feel free to send PR +1

Thank you
