### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector

### ISSUE THREAD

**Issue by niji-mneute** [rectorphp/rector#6985]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

When a constant is used to define an array key inside an annotation, Rector wraps it with quotes when converting to attributes (ie: `AbstractObjectNormalizer::SKIP_NULL_VALUES` becomes `'AbstractObjectNormalizer::SKIP_NULL_VALUES'`).

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec85a79-2b52-641e-89af-8128ec1e3b09

```php
<?php

use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer;

/**
 * @ApiResource(
 *     itemOperations={
 *         "get" = {
 *             "normalization_context" =  {
 *                 AbstractObjectNormalizer::SKIP_NULL_VALUES = true
 *             }
 *         }
 *     }
 * )
 */
final class DemoClass
{
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

The constant used as an array key is kept as is.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by niji-mneute** [comment]
Like this https://github.com/rectorphp/rector-src/pull/1764 ?

**Comment by TomasVotruba** [comment]
Yes, that's correct. It should be as simple as possible though. E.g. with one nesting. It will make test better isolated and easier to fix.

**Comment by TomasVotruba** [comment]
Related with https://github.com/rectorphp/rector-src/pull/1661/files

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-src/pull/1766
