### ISSUE TITLE
Nette 2.4 rules remove extends class_name

### ISSUE THREAD

**Issue by Koricz** [rectorphp/rector#6986]
Hi,

I am trying update very old project to Nette 2,4 and then to Nette 3.0. I am using this configuration https://github.com/rectorphp/rector-nette#use-sets

This rule set always remove `extends class_name`, ` implements` is kept on place.

Example diff from run:

Expected update:

```
-class UpdatePasswordFormFactory extends \Nette\Object   
+class UpdatePasswordFormFactory                         
 {                                                       
+       use \Nette\SmartObject;                          
      
       ----------- end diff -----------                     
Applied rules:                                           
 * ParentClassToTraitsRector    
```                         

Not expected, parent class should not be removed

```    

-abstract class BaseCrudControl extends \Nette\Application\UI\Control 
+abstract class BaseCrudControl                                       
 {                                                                    
+       use \Nette\SmartObject;                                       
        
    ----------- end diff ----------- 
Applied rules:
 * ParentClassToTraitsRector    
```                             
Not sure if something else is missing in configuration or it is a bug...

**Comment by TomasVotruba** [comment]
Thank you for the demo repository :+1: 

I made a fix for it https://github.com/rectorphp/rector-src/pull/1774

**Comment by Koricz** [comment]
That was quick! Thank you 👍

**Comment by TomasVotruba** [comment]
You're welcome :+1: 
The repository was very clear and minimalistic. Thanks
