### ISSUE TITLE
DOCTRINE_CODE_QUALITY - Annotation over the Doctrine property

### ISSUE THREAD

**Issue by Maxell92** [rectorphp/rector#6988]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.15             |

Rector wants to change annotation over the Doctrine property:

```
        /**
-	 * @var Collection<int, CountryRef>
+	 * @var CountryRef[]|Collection<int, CountryRef>
 	 */
 	#[ORM\OneToMany(mappedBy: 'country', targetEntity: CountryRef::class, cascade: ['persist'])]
 	private Collection $countryRefs;
```

`$containerConfigurator->import(DoctrineSetList::DOCTRINE_CODE_QUALITY);` cause this issue

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec89ad3-5258-6186-ae92-27d47c908361 (updated)

## Expected Behaviour

Rector should skip this

Also, there is no rule in the console I can put to ignore list:

![Screenshot 2022-02-09 at 14 38 53](https://user-images.githubusercontent.com/1649279/153212498-913601a4-89a3-4252-8103-aa8689be4868.png)

**Comment by Maxell92** [comment]
Hi, sorry, my fault :) Here is the better example: https://getrector.org/demo/1ec89ad3-5258-6186-ae92-27d47c908361

Thank you!

**Comment by Maxell92** [comment]
Any advice on how can we at least ignore this error?

**Comment by TomasVotruba** [comment]
It should be fixed. We need the minimal test case first.

**Comment by samsonasik** [comment]
should be fixed at https://github.com/rectorphp/rector-doctrine/pull/81
