### ISSUE TITLE
ReturnTypeDeclarationRector is converting Generator to Iterator

### ISSUE THREAD

**Issue by yann-eugone** [rectorphp/rector#6989]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec89bdc-a24f-68ce-b1af-894c7ad7ac39

```php
<?php

final class DemoFile
{
    /**
     * @return Generator<int>
     **/
    public function generator()
    {
        yield 5;
    }
}
```

### Responsible rules

* `ReturnTypeDeclarationRector`

## Expected Behavior

I was expecting the Rector to add `Generator` as return type

```diff
<?php

final class DemoFile
{
    /**
     * @return Generator<int>
     **/
-    public function generator()
+    public function generator(): Generator
    {
        yield 5;
    }
}
```

But for some reason it prefers `Iterator`

```diff
<?php

final class DemoFile
{
    /**
     * @return Generator<int>
     **/
-    public function generator()
+    public function generator(): \Iterator
    {
        yield 5;
    }
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.
