### ISSUE TITLE
`MethodCallToPropertyFetchRector` cannot be restricted to dedicated class

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#6990]
# Question

I use `PropertyFetchToMethodCallRector` like this:
```php
    $services->set(PropertyFetchToMethodCallRector::class)
        ->configure([
            new PropertyFetchToMethodCall(Generator::class, 'boolean', 'boolean'),
        ]);
```

Change `->boolean` to `->boolean()` on class `Generator::class`. It works like a charm.

However, after upgrading to PHP 8.1 (using rector), I have a lot of `private readonly string $foo`. And I don't need the `getFoo()` method anymore.

My plan was to use `MethodCallToPropertyFetchRector` (the opposite), but I realized, that based on the docs (https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#methodcalltopropertyfetchrector), I am not able to restrict this method call to a certain class.

Thanks for your help.

**Comment by TomasVotruba** [comment]
Hi, when I check the `MethodCallToPropertyFetchRector`, is has `configure()` method. So it should be configurable. How did you use it?

**Comment by OskarStark** [comment]
Yes it is, but you cannot register  it like 

Foo::class someMethod fooProperty
Bar::class someMethod barProperty

You get what I mean? Otherwise I will provide a more detailed examples later when back at the computer.

I am currently on a phone 📱 

Cheers

**Comment by TomasVotruba** [comment]
I'm not sure what do you mean. Demo example with configure rule would be better. Thank you 👍

**Comment by OskarStark** [comment]
```php
class Foo {
    public readonly string $foo = 'string';
    public function getValue(): string
    {
        return $this->foo;
    }
}

class Bar {
    public readonly string $bar = 'string';
    public function getValue(): string
    {
        return $this->bar;
    }
}
```

I know want to configure it like:
```php
    $services->set(PropertyFetchToMethodCallRector::class)
        ->configure([
            new PropertyFetchToMethodCall(Foo::class, 'getValue', 'foo'),
            new PropertyFetchToMethodCall(Bar::class, 'getValue', 'bar'),
        ]);
```

I hope it is more clear now

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Could you use the demo form? https://getrector.org/demo

**Comment by OskarStark** [comment]
Sure, looks like the demo page does not support `readonly` now.
<img width="1072" alt="CleanShot 2022-02-10 at 13 41 06@2x" src="https://user-images.githubusercontent.com/995707/153410883-61b57d7a-d5b4-41c9-ad61-1ecc16d4f176.png">

However, as this is not really important for my example, I removed the `readonly` keyword:
https://getrector.org/demo/1ec8a6f3-75d6-6c76-ba2d-eff19fcd9783

Cheers

**Comment by samsonasik** [comment]
@OskarStark rector demo is still using rector 0.12.15 as far as I know as no deployment yet for latest 0.12.16

**Comment by samsonasik** [comment]
@TomasVotruba seems temporary remove the deployment CI on getrector.org repository due to upgrade to using bref https://github.com/rectorphp/getrector.org/pull/493

**Comment by samsonasik** [comment]
@OskarStark could you create failing test case? Thank you.

**Comment by TomasVotruba** [comment]
> > @OskarStark could you create failing test case? Thank you.
> 
> I am not sure how, as `MethodToPropertyFetchCall` is not available, but so `PropertyFetchToMethodCall`... 🤔

I'm a bit a lost now. The `MethodCallToPropertyFetchRector` is available.
In the demo there is a button to create test, that makes it easy.

**Comment by TomasVotruba** [comment]
@OskarStark I see. It's rather forgotten use import :)
Btw, if you can share new comment with link it would be easier to follow. Updating past comment can be pretty confusing.

**Comment by OskarStark** [comment]
> I'm a bit a lost now. The MethodCallToPropertyFetchRector is available.

@TomasVotruba It is available yes, but not so the value object. I updated the demo and added "a/the" missing use statement, but the class does not exist:

https://getrector.org/demo/1ec8a8f3-320d-6790-bdf8-75f55ed5b048

**Comment by OskarStark** [comment]
In m initial code Block i can replace the call on Generator::class, but this is not possible to do with method to property fetch... 

I can only configure replace ALL ->getValue() by ->foo, but this would break calls on Bar::class

**Comment by TomasVotruba** [comment]
> However if this is not the case, how would you achieve my task then?

You can modify the rule to be 1:1 behavior with the opposite one and send PR to Rector. I'd expect the same behavior as you mention.

**Comment by TomasVotruba** [comment]
I'm looking into this...
