### ISSUE TITLE
Error:  Mixed can only be used as a standalone type

### ISSUE THREAD

**Issue by connerbw** [rectorphp/rector#6991]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.16             |

I ran rector on a project and according to the console output the rule named **_TypedPropertyRector_** was responsible for changing:

```php
/** @var Foo|mixed|MockObject */
private $x;
```

To:

```php
private mixed|\PHPUnit\Framework\MockObject\MockObject|\App\Services\Foo $x = null;
```

This change creates a fatal error: **Mixed can only be used as a standalone type**

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec8a2b5-0221-6fc0-ae53-e3ff0cc295bf

## Expected Behaviour

I can stop this from happening by editing the `rules/Php74/TypeAnalyzer/ObjectTypeAnalyzer.php isSpecial` function:

```php
foreach ($types as $type) {
    if ($type instanceof \PHPStan\Type\MixedType && count($types) > 1) {
        return true;
    }
```

But, a better solution would be to convert it to:

```php
/** @var Foo|MockObject */
private mixed $x;
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.
