### ISSUE TITLE
mysql_to_mysqli doesn't seem to update every mysql_* functions 

### ISSUE THREAD

**Issue by Looouuu** [rectorphp/rector#6998]
Hello !

# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | bc0eac36f4eece9f824efdb71c55ae59355d6a09 (seems to be 0.12.16), also happens on dev-master according to the demo tool           |

I'm currently upgrading an old codebase to php 8 . I'm trying to run the mysql_to_mysqli set, but it seems to only convert some functions but not others.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec8c4b6-b9f8-6a54-9977-c3e1f4c40fa4

```php
<?php

	if (mysql_num_rows(mysql_query('select * from bogusQuery')) > 0) // mysql_query not updated
	{
		// this is a test
	} 

	$anotherQuery = "SELECT * FROM anotherOutdatedQuery";
	$thisIsATest = mysql_query($anotherQuery); // not updated
	if (mysql_errno()) { // not updated
		echo 'it crashed i\'m sad';
	}else{			
		if (mysql_num_rows($thisIsATest)==1) {
			echo 'I hate this codebase';
		}
	}
```
## Expected Behaviour

It should update mysql_query as well. 

Thanks for this amazing tool !

**Comment by samsonasik** [comment]
duplicated with https://github.com/rectorphp/rector/issues/6917
