### ISSUE TITLE
Is upgrading code without exclusive version features possible?

### ISSUE THREAD

**Issue by andrei-dascalu** [rectorphp/rector#7002]
# Question

I'm sorry if this was asked before, I've tried looking for this in the resolved issue but haven't found something obviously related.

I have some code running currently with PHP 7.4
I would like to ensure compatibility with up to PHP 8.1, but without using exclusive version features (eg: non-capturing catch blocks).

I've tried using this as configuration

```php
$parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);
$containerConfigurator->import(LevelSetList::UP_TO_PHP_81);
```

believing that features would be used as per 7.4, while the code would be updated against 8.1

However, even so, I've had code changed to remove the capture exception variable from catch blocks, thus breaking compatibility with my current version.

Is this the way this configuration settings are expected to do things?

Thanks

**Comment by TomasVotruba** [comment]
Hi,

when you check the `LevelSetList::UP_TO_PHP_81`: https://github.com/rectorphp/rector/blob/20133c8832d6109320bce408d981d50108ce6ec1/config/set/level/up-to-php81.php#L16
you'll see the parameter is set there to PHP 8.1.

What you want should be possible, just add the parameter in your config *after* the up-to set import.

**Comment by andrei-dascalu** [comment]
@TomasVotruba excellent, thanks. So the other is important to avoid breaking stuff.
