### ISSUE TITLE
AddSeeTestAnnotationRector not applied when cache exists

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#7005]
# Bug Report

I have to look into a way tor reproduce this, but wanted to start reporting the issue.
When I run rector it does not always apply AddSeeTestAnnotationRector because of a cache that exists. Then when our CI runs (without cache) it fails, because AddSeeTestAnnotationRector gets applied.

Maybe you instantly know where to look for this issue, otherwise I will try to add a description of how to reproduce later.

**Comment by TomasVotruba** [comment]
This rule depends on composer class map, that is not always build. The run without cache is the only solution in this case.

**Comment by gisostallenberg** [comment]
@TomasVotruba Would this also be solved when I run `composer dump-autoload` before running rector?

**Comment by TomasVotruba** [comment]
Not sure, but it might help. How are your results?

**Comment by gisostallenberg** [comment]
I tried this:
- remove a test class
- remove the corresponding @see 
- remove the cache
- composer dump-autoload
- restore the test class (not the @see)
- run rector, result: no fix
- composer dump-autoload
- run rector, result: no fix (unfortunately)

So this is no fix either, but makes me think: Is the classmap also cached? Because that means this can only be resolved by removing `/tmp/rector_cached_files/`, which IMO is a poor solution.
Could you think of any other way to test this, and maybe another solution besides removing the cached files?

**Comment by TomasVotruba** [comment]
We usually handle these automatically with Rector in PRs: https://github.com/rectorphp/rector-src/blob/main/.github/workflows/rector.yaml
There is no cache and run is full.
Running Rector manually for repetetive tasks kind of kills the point of using it.

**Comment by gisostallenberg** [comment]
Strictly this does not answer my question, but I agree that having rector automated would be the way to go. Unfortunately (and understandably) rector is not flawless, especially when run against the magic Laravel provides. I will resolve to split up the rules in 'risky ones' (for my codebase) and rules that can always run, and add automation for that rules.
Would you be interested in a feature which makes it possible to 'tag' rules and an option to the process command to filter on these tags, or should I use some kind of CI-detection myself in the config?

**Comment by TomasVotruba** [comment]
This is the best and only way I'm aware of :)

For different setup, use 2 different configs. It's common practice among CI tools.

**Comment by gisostallenberg** [comment]
Thanks and thanks for your time spent in answering questions!

**Comment by gisostallenberg** [comment]
@TomasVotruba could this be fixed with the new PHPStan collectors?

**Comment by TomasVotruba** [comment]
Hi, I'm not sure how would you integrate it with Rector.
