### ISSUE TITLE
Trying to convert `Collection<int, object>` into old style `object[]|\Doctrine\Common\Collections\Collection<int, object>`

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7006]
# Bug Report

Rector tries to make the generic type hint worse
```diff
-    /**
-     * @var Collection<int, object>
-     */
+    /**
+     * @var \Oi\oi\object[]|\Doctrine\Common\Collections\Collection<int, \Oi\oi\object>
+     */
```

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.16             |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec8e65d-247f-6310-a394-71de59721608

## Expected Behaviour

No change.

**Comment by samsonasik** [comment]
It seems `ImproveDoctrineCollectionDocTypeInEntityRector` cause it https://getrector.org/demo/1ec8e91d-aba3-67ca-bc6e-4fe4dd4d032f
