### ISSUE TITLE
Incorrect behavior of TypedPropertyFromAssignsRector

### ISSUE THREAD

**Issue by xorik** [rectorphp/rector#7007]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec8f727-0af1-6508-bfc1-2fa5d8f64cf9

```php
<?php

final class DemoFile
{
    private $a;
    
    /**
     * @param int $a
     */
    public function __constructor($a)
    {
        $this->a = $a;
    }
}
```

### Responsible rules

* `TypedPropertyFromAssignsRector`

## Expected Behavior

Type `?int` was added based on doctype. But actually it might be incorrect. It would be nice if doctype-based types can be ignored to safely use this rule.

P.S.
I did some debug and found a workaround: https://twitter.com/xorik_dev/status/1494041577001521156
PHPStan can see both property type and phpdoc type, but in case of mixed property type, doctype type is chosen.

**Comment by samsonasik** [comment]
The example should use `__construct()` instead of `__constructor()` so it be `int`, not `?int`, while I understand the expected result.

https://getrector.org/demo/1ec8fafd-f186-69a8-9748-af02887ad283

**Comment by xorik** [comment]
@samsonasik yes you're right!
Sorry, I can't type outside of IDE without mistakes :)
