### ISSUE TITLE
False positive in ExplicitBoolCompareRector

### ISSUE THREAD

**Issue by rajyan** [rectorphp/rector#7008]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec8f958-96c5-6650-8257-fd28361f8358

```php
<?php

/**
* @return int
*/
function test()
{
    return '';
}

if (test()) {}
```

### Responsible rules

* `ExplicitBoolCompareRector`

## Expected Behavior

Want rector to handle return type ignoring PHPDoc (strictly), or skip.

https://github.com/rectorphp/rector/issues/7007
seems related.

Maybe adding a configure like `AddVoidReturnTypeWhereNoReturnRector ` for all rules to use PHPDoc or not when handling types is useful.
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#addvoidreturntypewherenoreturnrector

**Comment by rajyan** [comment]
Same issue for [RecastingRemovalRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#recastingremovalrector)
https://getrector.org/demo/1ec8facc-7ae1-6fa4-bacf-b3706afb5415

**Comment by rajyan** [comment]
Created failing test cases for each demo
https://github.com/rectorphp/rector-src/pull/1827
https://github.com/rectorphp/rector-src/pull/1828

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector-src/pull/1828#issuecomment-1048834130
