### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector

### ISSUE THREAD

**Issue by kadet1090** [rectorphp/rector#7012]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1e2cb1b3-8dd5-46fc-925b-1df01d0b73c0

```php
<?php

final class DemoFile
{
    public function __construct(private Converter $converter)
    {
        if ($this->converter instanceof CacheableConverter) {
            $this->converter = clone $this->converter;
            $this->converter->reset();
        }
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

Rector should skip it as the `converter` parameter is conditionally changed inside the constructor code.

**Comment by samsonasik** [comment]
Could you create failing test case PR for it? You can click "Create a Test" button at the demo page

**Comment by kadet1090** [comment]
Sure. Hope that this test is properly written. Also it seems that this issue may be because Rector allows writes to property in the constructor when only one write is allowed, additional example:

https://getrector.org/demo/18503fd8-a66a-44c8-83f4-cffa6e92bc0d

I could also add the test for that case, but I think that it won't add anything new.
