### ISSUE TITLE
Scoping is broken for symfony string component

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector#7017]
The scoping for the Symfony string component is in some places broken.

I.e. on that line https://github.com/rectorphp/rector/blob/main/vendor/symfony/string/ByteString.php#L342 the prefix is part of the preg_replace replacement which leads to unexpected results when using this method

**Comment by sabbelasichon** [comment]
The line should be the same as the old one: https://github.com/symfony/string/blob/5.4/ByteString.php#L367

**Comment by TomasVotruba** [comment]
3v4l testing https://3v4l.org/AWkOL

**Comment by TomasVotruba** [comment]
Should be ok now: https://github.com/rectorphp/rector/commit/520fbeb9473ec0fe376db21e00277b1f0f51a470#diff-9ebd365b05e7019c1e109f910efb636361c9b3302806ce520a66c8c8da909ed3

Could you check?
