### ISSUE TITLE
DateTimeToDateTimeInterfaceRector may break Symfonys ParamConverter-Feature

### ISSUE THREAD

**Issue by mkrauser** [rectorphp/rector#7019]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.16 (bc0eac36f4eece9f824efdb71c55ae59355d6a09)           |

## Minimal PHP Code Causing Issue

Is know, that this is kind of an edge-case. Rector changes the Type of the DateTime-Parameter. But this breaks the Symfony Param-Converter, since it only works with \DateTime and not DateTimeInterface:

[Demo](https://getrector.org/demo/ca9d27c9-e637-4d87-9030-6e164c847a11)

## Expected Behaviour

I would be great, if Rector can skip DateTime-Params in Symfony Controller-Actions. 
But I understand that this might be a "wont-fix".

**Comment by TomasVotruba** [comment]
Thanks for repoting.

I'd expect this to work on Symfony side for both types, as it's best practise to use `DateTimeInterface` contract over `DateTime` specific object.

Feel free to extend Symfony behavior, which would be better for DX.

You can also extend this rule to skip Controllers. We can merge it.

**Comment by mkrauser** [comment]
For everyone who has the same issue. You can disable the DateTimeToDateTimeInterfaceRector for Controllers like this.

```
    $parameters->set(Option::SKIP, [
        DateTimeToDateTimeInterfaceRector::class => [
            __DIR__ . '/src/Controller/*'
        ],
    ]);
```

**Comment by mkrauser** [comment]
> I'd expect this to work on Symfony side for both types, as it's best practise to use `DateTimeInterface` contract over `DateTime` specific object.
> 
> Feel free to extend Symfony behavior, which would be better for DX.

I agree. I'll try to fix that on Symfony-Side, when I have time.

**Comment by TomasVotruba** [comment]
Thank you for sharing quick solution :+1:
