### ISSUE TITLE
Twig extension classes not being updated properly

### ISSUE THREAD

**Issue by brandonkelly** [rectorphp/rector#7036]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `dev-main` (8b3037c2dd1f729bf59dedbb74bf67adbdf929ff)             |

`Rector\Symfony\Set\TwigSetList::TWIG_UNDERSCORE_TO_NAMESPACE` isn’t upgrading the code properly. It appears from the source code that it’s _trying_ to do the right thing (e.g. `\Twig_extension` → `\Twig\Extension\AbstractExtension`), however it’s not working as (it seems) intended.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/a021cc7d-e3ce-406b-80d1-36cd21da43ce

## Expected Behaviour

```diff
 <?php
 
-class MyExt extends \Twig_Extension
+class MyExt extends \Twig\Extension\AbstractExtension
 {
 }
```

## Actual Behavior

```diff
 <?php
 
-class MyExt extends \Twig_Extension
+class MyExt extends \Twig\Extension
 {
 }
```

**Comment by TomasVotruba** [comment]
I'm checking this one...

**Comment by TomasVotruba** [comment]
Fix in https://github.com/rectorphp/rector-symfony/pull/116

**Comment by brandonkelly** [comment]
Thanks!!
