### ISSUE TITLE
Standalone Rector extensions can't have custom namespace

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector#7038]
# Bug Report

I'm working on Rector extension for `moneyphp/money` and I wanted to use my own namespace for it, but after changing namespace [tests fail](https://github.com/CoditoNet/rector-money/actions/runs/1922326458) with:

```
RectorPrefix20220209\Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Expected to find class "Rector\Money\MoneySetList" in file "/home/runner/work/rector-money/rector-money/src/MoneySetList.php" while importing services from resource "/home/runner/work/rector-money/rector-money/config/../src", but it was not found! Check the namespace prefix used with the resource.
```

Actual namespace defined for autoloading is `Codito\Rector\*` and IMHO it's totally fine since it represents actual vendor of the package (`Codito`), some kind of category (`Rector`) and other more specific details. All other QA tools work well with it.

## Minimal PHP Code Causing Issue

[This package](https://github.com/CoditoNet/rector-money/tree/5c9b4c8a75bc07a861b57cafe2c980f8593f5bf7).

## Expected Behaviour

It's possible to create custom Rector rules under vendor-specific namespace.

**Comment by TomasVotruba** [comment]
The imported namespace must be identical to real one: https://github.com/CoditoNet/rector-money/pull/1/files

Not sure what the other issue is.

**Comment by Wirone** [comment]
Jeeeez, I've overlooked that one 😩 😳 

Thank you very much!

**Comment by TomasVotruba** [comment]
It happens, strings cannot be trusted.
I wish we had constants for namespaces :)
