### ISSUE TITLE
Configuring a rule breaks the process. Probably related to Prefixing.

### ISSUE THREAD

**Issue by SelrahcD** [rectorphp/rector#7041]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 07736c1ab4d45d348d5054625499f10f97d671be            |

Hi!

I'm facing a strange bug. When I try to configure a rule I get the following error message:

```
[ERROR] Call to undefined method
         "RectorPrefix20211020\Symfony\Component\DependencyInjection\Loader\Configurator\ServiceConfigurator::configure(
         )".
```

As far as I understood the issue, the `configure` method doesn't actually exists and is expected to go through `ServiceConfigurator::__call`. 

I don't understand how the prefixing system work and I'm a bit lost to dig deeper.

## Minimal PHP Code Causing Issue

This is the config file that cause the issue.

```php
<?php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Symfony\Rector\MethodCall\GetToConstructorInjectionRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::PATHS, [__DIR__ . '/src', __DIR__ . '/tests']);

    $services = $containerConfigurator->services();
    $services->set(GetToConstructorInjectionRector::class)->configure(
        [GetToConstructorInjectionRector::GET_METHOD_AWARE_TYPES => [\Symfony\Bundle\FrameworkBundle\Controller\AbstractController::class]]
    );
};
```

## Expected Behaviour

It should configure the rule.

Let me know if I can share more info to find the cause of the problem!

**Comment by SelrahcD** [comment]
I just wanted to make sure I didn't do something strange and tried it with a fresh install of Rector on an empty project.
In the newer version I don't have the issue but the `GetToConstructorInjectionRector` can't be configured anymore. 

Maybe this issue can be closed?

**Comment by TomasVotruba** [comment]
Thanks for reaching back.
The rule should handle all known Symfony classes, so we added it here https://github.com/rectorphp/rector-symfony/pull/46

If all works for you, let's close then 👍
