### ISSUE TITLE
Incorrect behavior of RenameClassRector

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#7042]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e072b617-d827-485c-87dd-2263f8bc0b20

```php
<?php

class Base {
}

class Inserted extends Base {
}

class Child extends Base
{
}
```

### Responsible rules

* `RenameClassRector`

## Expected Behavior
When using `RenameClassRector` to insert a class in a stack the inserted class becomes an extend of itself, this is unexpected.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
This is actually on purpose, as the Rector is upgrade tool, to make your code compatible with vendor and PHP. In short, to keep up with external changes.

The change you describe is desired for just in time refactoring. Better use PHPStorm and rename method there.

**Comment by gisostallenberg** [comment]
Do you have a rule available to ensure a certain base class is used instead of another one?
To be specific: I want to make sure all authors of code in our code base use App/Model as a base for their models and not directly use the Eloquent one.

**Comment by TomasVotruba** [comment]
That sounds like a job for custom PHPStan rule :) 

Good idea! We use something similar to recommend different class over Symfony default one for repository: https://github.com/symplify/phpstan-rules/blob/main/docs/rules_overview.md#preferredclassrule
