### ISSUE TITLE
Rename namespace rector doesn't update absolute references in PHPDoc's

### ISSUE THREAD

**Issue by jelovac** [rectorphp/rector#7045]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.17             |

The rule `Rector\Renaming\Rector\Namespace_\RenameNamespaceRector`  doesn't update absolute class references.

For example:

I want rename namespace App\Entity to App\Entity\OrmEntity.

Running the below rector rule:

```
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Renaming\Rector\Namespace_\RenameNamespaceRector;
use Rector\Set\ValueObject\LevelSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__.'/src',
        __DIR__.'/tests',
    ]);

    // Define what rule sets will be applied
//    $containerConfigurator->import(LevelSetList::UP_TO_PHP_81);

    // get services (needed for register a single rule)
    $services = $containerConfigurator->services();

    // register a single rule
    // $services->set(TypedPropertyRector::class);

    $services->set(RenameNamespaceRector::class)
        ->configure([
            'App\\Entity' => 'App\\Entity\\OrmEntity',
        ]);
};

```

Will not update references which are absolute in PHPDocs.

For example class \App\Entity\Book will not be renamed to \App\Entity\OrmEntity\Book.

**Comment by TomasVotruba** [comment]
Hi, thanks for the report.

We'll need minimal demo link from https://getrector.org/demo with reproducible code

**Comment by jelovac** [comment]
Hi @TomasVotruba,

Here is the demo: https://getrector.org/demo/d35fb0d8-dd48-41a0-8a7d-f630ffd2e512

**Comment by samsonasik** [comment]
`RenameNamespaceRector` is not updating docblock, only Node's name of `Namespace_`, `Use_`, and `Name`, you may need to use `RenameClassRector` for that:

```php
    $services->set(\Rector\Renaming\Rector\Name\RenameClassRector::class)
        ->configure([
            'App\Entity\Book' => 'App\Entity\OrmEntity\Book',
        ]);
```

This is possibly a possible improvement for `RenameClassRector` instead, to make support of `*` value usage, eg:

```php
    $services->set(\Rector\Renaming\Rector\Name\RenameClassRector::class)
        ->configure([
            'App\Entity\*' => 'App\Entity\OrmEntity\*',
        ]);
```
