### ISSUE TITLE
Incorrect !isset() transformation

### ISSUE THREAD

**Issue by odziomkova-brackets** [rectorphp/rector#7048]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.17             |

## Minimal PHP Code Causing Issue
8.1

## Expected Behaviour

`if (!isset($rfi->date_of_supply)) {`
got changed into
`if (!(property_exists($rfi, 'date_of_supply') && $rfi->date_of_supply !== null)) {`
while it should be
`if (!(property_exists($rfi, 'date_of_supply') || $rfi->date_of_supply === null)) {`

Not sure which Rule it is, I used the `SetList::CODE_QUALITY`

**Comment by samsonasik** [comment]
The change is correct, using `||` will make error when property never exists, ref https://3v4l.org/9Xv93

**Comment by odziomkova-brackets** [comment]
Sorry, I was looking at the parenthesis nesting wrong. You are of course correct.

My problem therefore was in the fact, that in my Laravel project for some reason `property_exists` returns false even if the property exists on the Eloquent model, that's why my tests started failing. So I reverted back to using isset. Rest of the `SetList::CODE_QUALITY` rules seems to be working okay for me 👍

**Comment by samsonasik** [comment]
You can skip the rule for that use case, I guess you're using `\Rector\CodeQuality\Rector\Isset_\IssetOnPropertyObjectToPropertyExistsRector`, 

```php
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Core\Configuration\Option;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $containerConfigurator->import(SetList::CODE_QUALITY);
    $services = $containerConfigurator->services();
    
	$parameters->set(Option::SKIP, [
        \Rector\CodeQuality\Rector\Isset_\IssetOnPropertyObjectToPropertyExistsRector::class
    ]);
};
```

ref:

https://getrector.org/demo/bb57bd5f-cb2a-479e-9878-bb12aa2b4545
