### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector: tries to set static property to readonly

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7050]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/8cef18b3-c224-49f6-872e-128119d4855b

```php
<?php

declare(strict_types=1);

final class A
{
    private static stdClass $x;

    public function __construct(stdClass $x)
    {
        self::$x = $x;
    }

    public static function x(): stdClass
    {
        return self::$x;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

no change

**Comment by samsonasik** [comment]
The change seems correct, the `x()` method only return StaticPropertyFetch `self::$x`. It will be skipped if `self::$x` re-assigned, ref https://getrector.org/demo/e05beb1e-0374-4034-8e5c-79923c2bfa28

**Comment by simPod** [comment]
But static properties cannot be readonly

**Comment by samsonasik** [comment]
ok, re-open then, could you try provide a patch for it? Thank you.
