### ISSUE TITLE
PHPDoc Annotation not changed to imported class

### ISSUE THREAD

**Issue by dahaupt** [rectorphp/rector#7051]
### Discussed in https://github.com/rectorphp/rector/discussions/7049

<div type='discussions-op-text'>

<sup>Originally posted by **dahaupt** March 14, 2022</sup>
I've noticed a different behavior after updating to v0.12.17.

Rector adds a new use statement:
```diff
+use TYPO3\CMS\Extbase\Annotation\Validate;
```

But does not change the related PHPDoc annotation:
```php
/**
* @TYPO3\CMS\Extbase\Annotation\Validate
*/
public function method(){}
```

PHP-CS-Fixer afterwards removes the unused import. 

I am not sure if this is specific to TYPO3 or a configuration mistake of myself. Thankful for any help!</div>

---

Reproduction repository: https://github.com/dahaupt/rector-annotation-import

**Comment by samsonasik** [comment]
I am looking at it at https://github.com/rectorphp/rector-src/pull/1973, feel free to provide a patch if you found the solution first.
