### ISSUE TITLE
Add annotation to attribute Rector to JMS set

### ISSUE THREAD

**Issue by Jean85** [rectorphp/rector#7052]
# Feature Request
I'm using Rector to migrate all annotations in my project to attributes. All is well regarding Symfony, but I also use JMS Serializer, which has added attribute support (and has it enabled by default) since 3.14, see https://github.com/schmittjoh/serializer/pull/1338

For now, I've applied a classic `AnnotationToAttributeRector` Rector, but it would be great to have a prepared set that updates them, since there are a lot: https://github.com/schmittjoh/serializer/tree/master/src/Annotation

I tried to do it by myself but there's no structure in https://github.com/rectorphp/rector-symfony from which to start..

**Comment by TomasVotruba** [comment]
Hi,

you can add the class in here to particular set: https://github.com/rectorphp/rector-symfony/tree/main/config/sets

**Comment by Jean85** [comment]
I've opened https://github.com/rectorphp/rector-symfony/pull/132 but I don't know how to add tests about this.

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector-symfony/pull/132
