### ISSUE TITLE
Fnmatch problem when skipping single file

### ISSUE THREAD

**Issue by freiondrej-lmc** [rectorphp/rector#7053]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.17 |

Hello,
when using 
```php
$parameters->set(Option::SKIP, [
   __DIR__ .'/../src'
]);
```
, it works properly. However, when that same path is moved to just exclude a particular rule, the exclusion does not work:
```
$parameters->set(Option::SKIP, [
   SomeRuleRector::class => [
      __DIR__ .'/../src'
   ]
]);
```
I traced the problem to probably occur due to the relative path '/../', because it works as expected when rewritten as this:
```
$parameters->set(Option::SKIP, [
   SomeRuleRector::class => [
      dirname(__DIR__) .'/src'
   ]
]);
```

**Comment by samsonasik** [comment]
On what use case it needs to run `src` in parent directory? Could you provide sample repository for it? Thank you.

**Comment by freiondrej-lmc** [comment]
@samsonasik this was just a simplified example. But my setup is that rector is a special directory called "rector", so there is a "src" dir and next to it a "rector" one. When trying to access the src dir, I do `__DIR__ . "/../src"`, which causes the problem as well.
Hopefully this describes the problem well enough; if not, I'll try to prepare the sample repository, but I'm not sure when I get some time to do that.
When tracing the problem, I found \RectorPrefix20220303\Symplify\SmartFileSystem\SmartFileInfo::doesFnmatch(), which then basically performs `fnmatch('*/srv/www/project/rector/../src/*/Entity/*', '/srv/www/project/src/App/Bundle/Entity/TestEntity.php')` and the only problem is in the presence of `'/../'` for the fnmatch - hope that makes sense.

**Comment by freiondrej-lmc** [comment]
@samsonasik https://github.com/freiondrej-lmc/rector_issue_7053 :)

**Comment by samsonasik** [comment]
Thank you, it seems remove `*` at the end of `src/` fix it:

```diff
-            __DIR__ . '/../src/*', 
+            __DIR__ . '/../src/', 
```

I verified locally and it seems working ok by removing `*` at the end of `src/`.

The code for it seems at symplify/smart-file-system https://github.com/symplify/symplify/blob/a910be03dd0bb7f94ca8b2b9cd57eece5fd83e30/packages/smart-file-system/src/SmartFileInfo.php#L131 which cover start with `*/`, so possibly ends with `*` make uncover.

**Comment by freiondrej-lmc** [comment]
@samsonasik I see. So you don't think it's a bug, but rather a feature? 
[The documentation](https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md) says the `*` should work:
```php
        SimplifyIfReturnBoolRector::class => [
            // single file
            __DIR__ . '/src/ComplicatedFile.php',
            // or directory
            __DIR__ . '/src',
            // or fnmatch
            __DIR__ . '/src/*/Tests/*',
        ],
```
Also when the same string `__DIR__ . '/../src/*'` is applied globally instead of for one rule only (see https://github.com/freiondrej-lmc/rector_issue_7053/blob/skip-applied-globally/rector/config.php), the skip works as expected. So the behavior is inconsistent in this way.
Maybe worth noting this in the documentation? :)

**Comment by samsonasik** [comment]
I am not sure, I tried some debugging and  can't get the reason why `__DIR__ . '/../src/*'` not work inside per-rule definition yet.

For now, feel free to provide a PR to documentation for this kind of use case.

**Comment by freiondrej-lmc** [comment]
I'll also try to do some debugging when I catch some time. Thank you for your effort so far!

**Comment by samsonasik** [comment]
Ok, I am closing it for now as the alternative working solution provided and verified ok.

Feel free to provide a PR to documentation for this kind of use case.

**Comment by freiondrej-lmc** [comment]
@samsonasik do you think this is maybe more of a simplify/smart-file-system issue than a rector one?

**Comment by samsonasik** [comment]
That's should be. My tip: even the alternative solution is currently working, I suggest to move the rector.php to the root of project, looking for parent dir like that will eventually make autoload conflict or inconsistency eventually, sooner or later.
