### ISSUE TITLE
Using custom extension with Nette 3.0 set throws error "Cannot autowire service"

### ISSUE THREAD

**Issue by markoph** [rectorphp/rector#7054]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 77a4582d5044446b8da43ab91a09082fa0413a23 |

Using `NetteSetList::NETTE_30` with custom extension throws error:

```shell
 [ERROR] Cannot autowire service "Rector\Nette\Rector\ClassMethod\RemoveParentAndNameFromComponentConstructorRector":   
         argument "$paramFinder" of method "__construct()" references class "Rector\Nette\NodeFinder\ParamFinder" but no
         such service exists.
```

I am not sure if this is caused by something in [rectorphp/rector-nette](https://github.com/rectorphp/rector-nette) or it's some misconfiguration on my side. But removing two rules (classes) in Nette rule set allows Rector to continue.

## Minimal PHP Code Causing Issue

```php
    $containerConfigurator->import(\Example\Utils\Rector\Set\ExampleSetList::EXAMPLE_1_0);
    $containerConfigurator->import(\Rector\Nette\Set\NetteSetList::NETTE_30);
```

Repository with minimal PHP code: [markoph/rector-broken-extension](https://github.com/markoph/rector-broken-extension).
Rector extension is in subdirectory (installed as symlink): [rector-example-extension](https://github.com/markoph/rector-broken-extension/tree/master/utils/rector-example-extension).

Commands to reproduce it:

```shell
git clone git@github.com:markoph/rector-broken-extension.git rector-broken-extension
composer install
# processing throws error
vendor/bin/rector process
# also --version throws error
vendor/bin/rector --version
```

## Expected Behaviour

Rector should run both rule sets without error.

## Note

Commenting out `RemoveParentAndNameFromComponentConstructorRector::class` and `MoveFinalGetUserToCheckRequirementsClassMethodRector::class` in [`nette-30.php:69-70`](https://github.com/rectorphp/rector/blob/16633831b8c045799fd3ac555c02c05ab6d360c9/vendor/rector/rector-nette/config/sets/nette-30.php#L69-L70) allows to both sets complete code changes.

```php
    $services->set(\Rector\Nette\Rector\MethodCall\RequestGetCookieDefaultArgumentToCoalesceRector::class);
//    $services->set(\Rector\Nette\Rector\ClassMethod\RemoveParentAndNameFromComponentConstructorRector::class);
//    $services->set(\Rector\Nette\Rector\Class_\MoveFinalGetUserToCheckRequirementsClassMethodRector::class);
    $services->set(\Rector\Nette\Rector\MethodCall\ConvertAddUploadWithThirdArgumentTrueToAddMultiUploadRector::class);
```

**Comment by TomasVotruba** [comment]
Hi, thanks for sharing exact repository. That's very helpful :+1: 

I don't see Rector in the dev dependencies there: https://github.com/markoph/rector-broken-extension/blob/b9b05193c2749be285093f011a06ea5c744a4c5f/composer.json#L32-L36
Without that, it cannot run the extension and install configs propperly.

**Comment by markoph** [comment]
Nothing changes, same error.

_(We have it in our project's root composer; I just forgot to add it in example. Sorry. It is requirement of extension so it got installed anyway.)_

**Comment by markoph** [comment]
I commited it just to be sure :) https://github.com/markoph/rector-broken-extension/blob/5e547324d9aa0ef9831adcb7e62556f7142f529d/composer.json#L36

**Comment by TomasVotruba** [comment]
Thanks :+1: 

It seems the `"rector/extension-installer"` in the `/utils` causes the problem. This package is already part of `rector/rector` no-prefixed in newer version, so it being duplicated crashes.

Try to remove it :)

**Comment by TomasVotruba** [comment]
We use this composer plugin to install vendor packages to rector core. It should not be used outside it.

**Comment by markoph** [comment]
:facepalm: I though it is requirement for extensions. I didn't even try to remove it when debugging.

Sorry for bug report and big thank you for helping me.

**Comment by TomasVotruba** [comment]
Not a problem, glad to help :+1:
