### ISSUE TITLE
Incorrect behavior with Doctrine ManyToMany and nested joinColumns and inversedJoinColumns

### ISSUE THREAD

**Issue by jtexier** [rectorphp/rector#7060]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

Already mentionned in this closed ticket :
https://github.com/rectorphp/rector/issues/6982

Doctrine annotation ManyToMany with nested joinColumns and inversedJoinColumns are not well handled.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/99721051-8f16-4d68-bb66-ce6cd4c7d4ae

```php
<?php
use Doctrine\ORM\Mapping as ORM;

class Post
{
  /**
   * @ORM\ManyToMany(targetEntity="Tag")
   * @ORM\JoinTable(name="post_tags",
   *   joinColumns={
   *     @ORM\JoinColumn(name="post_id", referencedColumnName="id")
   *   },
   *   inverseJoinColumns={
   *     @ORM\JoinColumn(name="tag_id", referencedColumnName="id")
   *   }
   * )
   */
   public Collection $tags; 
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

```
class Post
{
  #[ORM\ManyToMany(targetEntity: Tag::class)]
  #[ORM\JoinTable(name: "post_tags")]
  #[ORM\JoinColumn(name: "post_id", referencedColumnName: "id")]
  #[ORM\InverseJoinColumn(name: "tag_id", referencedColumnName: "id")]
  public Collection $tags;
}
```

**Comment by samsonasik** [comment]
In `rector/rector:dev-main`, it transformed to :

```diff
-  /**
-   * @ORM\ManyToMany(targetEntity="Tag")
-   * @ORM\JoinTable(name="post_tags",
-   *   joinColumns={
-   *     @ORM\JoinColumn(name="post_id", referencedColumnName="id")
-   *   },
-   *   inverseJoinColumns={
-   *     @ORM\JoinColumn(name="tag_id", referencedColumnName="id")
-   *   }
-   * )
-   */
+  #[ORM\ManyToMany(targetEntity: 'Tag')]
+   #[ORM\JoinTable(name: 'post_tags', joinColumns: [], inverseJoinColumns: [])]
+   #[ORM\JoinColumn(name: 'post_id', referencedColumnName: 'id')]
+   #[ORM\JoinColumn(name: 'tag_id', referencedColumnName: 'id')]
```

is that already expected? If you found a bug on above transformation, feel free to provide failing test case to 

https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/Doctrine

with add more config when needed at 

https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php

**Comment by jtexier** [comment]
Hello, as mentioned before, the expected result should be something : 
```
class Post
{
  #[ORM\ManyToMany(targetEntity: Tag::class)]
  #[ORM\JoinTable(name: "post_tags")]
  #[ORM\JoinColumn(name: "post_id", referencedColumnName: "id")]
  #[ORM\InverseJoinColumn(name: "tag_id", referencedColumnName: "id")]
  public Collection $tags;
}
```

The second JoinColumn on your example should be an InverseJoinColumn.
Having two JoinColumn makes Doctrine producing incorrect SQL queries to add FK constraints.

**Comment by samsonasik** [comment]
Feel free to provide failing test case PR

**Comment by Lenny4** [comment]
@samsonasik I think you can close this issue.

The "expected behaviour" provided by @jtexier is not the expected behaviour.

**Comment by samsonasik** [comment]
Ok, I am closing it ;). Feel free to create failing test case PR if you still have issue with it. Thank you.

**Comment by jtexier** [comment]
Hello, @Lenny4 what should be the correct behaviour then ?

I'm still thinking there's a bug here, the actual result is incorrect for Doctrine because **InverseJoinColumn** defintion is lost and having 2 **JoinColumn** leads to a collision.

**Comment by Lenny4** [comment]
@jtexier 

look here: https://getrector.org/demo/30ebdb5b-4911-4a46-a841-7520fd644509

Maybe when you created this issue rector didn't work well but now it perfectly convert annotation to attribute. (at least for your case)
