### ISSUE TITLE
Incorrect support of ParameterConverter annotation to attribute

### ISSUE THREAD

**Issue by jtexier** [rectorphp/rector#7061]
# Bug Report

Rector\Symfony\Set\SensiolabsSetList doesn't support correctly transformation of ParameterConverter annotation in loosing key parameter

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/b883c5d7-3878-498c-8955-cb03f92ed532

```php
<?php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Routing\Annotation\Route;


class Controller {
/**
 * @Route("/blog/{date}/{slug}/comments/{comment_slug}")
 * @ParamConverter("post", options={"mapping": {"date": "date", "slug": "slug"}})
 * @ParamConverter("comment", options={"mapping": {"comment_slug": "slug"}})
 */
public function showComment(Post $post, Comment $comment)
{
}
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

```
+#[ParamConverter('post', options: ['mapping' => ['date' => 'date', 'slug' => 'slug']])]
+#[ParamConverter('comment', options: ['mapping' => ['comment_slug' => 'slug']])]
```

**Comment by samsonasik** [comment]
It seems already resolved in latest dev-main: 

```diff
- * @ParamConverter("post", options={"mapping": {"date": "date", "slug": "slug"}})
- * @ParamConverter("comment", options={"mapping": {"comment_slug": "slug"}})
  */
+#[ParamConverter('post', options: ['mapping' => ['date' => 'date', 'slug' => 'slug']])]
+#[ParamConverter('comment', options: ['mapping' => ['comment_slug' => 'slug']])]
```

 You can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer update rector/rector:dev-main
```

**Comment by jtexier** [comment]
Hello,

did you take a look to the provided demo link : https://getrector.org/demo/b883c5d7-3878-498c-8955-cb03f92ed532 ?
Result is incorrect and I think it was produced by latest dev-master code, isn't it ?

**Comment by samsonasik** [comment]
Demo page is not using dev-main, that's using latest 0.12.17
