### ISSUE TITLE
AnnotationToAttributeRector breaks code formatting

### ISSUE THREAD

**Issue by jgrygierek** [rectorphp/rector#7062]
In my rector config I have:

```php
$services = $containerConfigurator->services();
$services
    ->set(AnnotationToAttributeRector::class)
    ->configure([new AnnotationToAttribute('Symfony\Component\Routing\Annotation\Route')]);
```

When I run it, rector breaks my code formatting:
![obraz](https://user-images.githubusercontent.com/3065409/159186239-ac1005f3-aa7a-424b-8d60-e26711115d6e.png)

Blank lines are removed and whitespace is added before `:` in return type.

**Comment by samsonasik** [comment]
You can use NewlineAfterStatementRector for it https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#newlineafterstatementrector

**Comment by jgrygierek** [comment]
But it breaks more thing like changing method arguments from multiline into single line.

**Comment by samsonasik** [comment]
The NewlineAfterStatementRector mostly solve that, other than that, that's coding standard job, ref https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by andyexeter** [comment]
The `AnnotationToAttributeRector` shouldn't be touching code inside method bodies, so using another rector (`NewlineAfterStatementRector`) isn't the right solution here.

Reproducer: https://getrector.org/demo/c08d314d-b81f-4103-85e1-23c30e47e934

The `AnnotationToAttributeRector` should only change:

```php
    /**
     * @Route("/", name="home")
     */
```

to:

```php
    #[Route(path: '/', name: 'home']
```

Nothing else in the method should be modified.

**Comment by TomasVotruba** [comment]
Yes, this is how php-parser handles new stmts from the top of node.  Because of new attributes, the token numbers of new code are shifted, and original formatting is lost.

The responsible code in its printer: https://github.com/nikic/PHP-Parser/blob/0201a7ee3f86c856eb009e1393fdd654b9667684/lib/PhpParser/PrettyPrinterAbstract.php#L564-L576

If it is fixed there e.g. by off-setting number of tokens in new nodes, that would inheritly resolve this issue.

**Comment by TomasVotruba** [comment]
On second thought, we might have look into this. 

If we're lucky the token shifting should be doable with a php-parser patch and the inner content should keep spaces :slightly_smiling_face:

**Comment by TomasVotruba** [comment]
I made a PR with test to php-parser: https://github.com/nikic/PHP-Parser/pull/880/files

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/2903 :partying_face:
