### ISSUE TITLE
Incorrect behavior of ChangeSwitchToMatchRector

### ISSUE THREAD

**Issue by mkrauser** [rectorphp/rector#7063]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/35645d39-abe8-43b8-a9ae-fa496eb9a5ec

```php
<?php

final class DemoFile
{
    public function run($value)
    {
        if(strlen($value) < 3) {
            switch($value) {
                case 'A':
                case 'B':
                    return 'AB';
                case 'C':
                    return 'D';

            }
        }
        
        return $value;
    }
}
```

### Responsible rules

* `ChangeSwitchToMatchRector`

## Expected Behavior

If the switch does not include a default case, the the transformed match-construct may not be exhaustive. But this is required by the php itself ("A match expression must be exhaustive.", see https://www.php.net/manual/de/control-structures.match.php)

**Comment by samsonasik** [comment]
It seems for no default, it needs to be skipped to avoid UnhandledMatchError https://3v4l.org/DGtdl

**Comment by samsonasik** [comment]
Another solution is add `default => $value` inside match, ref https://3v4l.org/Oi0oE
