### ISSUE TITLE
PHPUnit\Framework\TestCase stub can replace the real class

### ISSUE THREAD

**Issue by fancyweb** [rectorphp/rector#7064]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.18             |

https://github.com/rectorphp/rector-src/pull/1924 stub can replace the real `TestCase` class if it's declared (directly or indirectly) after Rector bootstrap.

I'm encountering this issue with PHPStan where `TestCase` is normally declared by one of my `bootstrapFiles`. The stub is actually used, so it generates thousands of errors.

**Comment by samsonasik** [comment]
@TomasVotruba I think we need a repository sample to show the error, because autoload overlap may happen in any use case

**Comment by fancyweb** [comment]
Thanks for the fast replies. I created https://github.com/fancyweb/rector-7064/tree/master. Launching phpstan fails like in my project.

**Comment by samsonasik** [comment]
@fancyweb I tried your repo and it seems the phpunit is not in the vendor

```
composer install

vendor/bin/phpstan analyze            

Note: Using configuration file /Users/samsonasik/www/rector-7064/phpstan.neon.
Bootstrap file /Users/samsonasik/www/rector-7064/vendor/bin/.phpunit/phpunit-9.5-0/vendor/autoload.php does not exist.

```

**Comment by lugosium** [comment]
You should first run one time simple-phpunit, it will download necessary phpunit:

`./vendor/bin/simple-phpunit`

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-src/pull/1954 for it.

**Comment by samsonasik** [comment]
Fixed.

**Comment by fancyweb** [comment]
Thank you very much :clap:

**Comment by lugosium** [comment]
Thank you 👍
