### ISSUE TITLE
PSA: PHPStan is dropping PHP 7.1 support in PHPStan 1.5.0

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#7068]
In the current version under development (PHPStan 1.5.0), I'll be dropping PHP 7.1 support (https://twitter.com/OndrejMirtes/status/1506194568626245635). This likely means that Rector will have to drop PHP 7.1 support too.

**Comment by TomasVotruba** [comment]
Thanks for heads up! I've missed the tweet. We'll get ready :)
