### ISSUE TITLE
"[OK] Rector is done!" no matter what

### ISSUE THREAD

**Issue by sylbru** [rectorphp/rector#7069]
# Question

Hi! Trying to setup my custom rule here. I started with the method call rename example, and at first it didn’t report anything. Then I just added a line in my index.php file and suddenly a ton of changes were reported in that file.

→ Is there a cache somewhere that might not be updated as I update my rector.php or my custom rector file?

Then I moved on to implementing my own transformation, and now I can’t get anything to be reported. I have no clue whether I am in the right direction or not. 

→ Is there a way to print information about nodes in the console? What should I use `$this->print(...)` with? 

Here is the code of the rector I’m working on:

    public function getNodeTypes(): array
    {
        return [ClassConstFetch::class];
    }

    public function refactor(Node $node): ?Node
    {
        $constName = $this->getName($node->name);
        $newConstName = preg_replace("/^HTTP_/", "STATUS_", $constName);

        $node->class = new Name("\Fig\Http\Message\StatusCodeInterface");
        $node->name = new Identifier($newConstName);

        return $node;
    }

**Comment by markoph** [comment]
- To clear cache, try `vendor/bin/rector process --clear-cache`. 
- To print nodes, try `print_node($node)` or `dump_node($node)`. See https://github.com/rectorphp/rector#debugging

**Comment by samsonasik** [comment]
For `ClassConstFetch`, you may need to check both `class` and `name`'s name, return null if not match, eg:

```php
<?php

declare(strict_types=1);

namespace Utils\Rector\ClassConstFetch;

use PhpParser\Node;
use Rector\Core\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

class ChangeHttpStatusRector extends AbstractRector
{
    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('change http status', []);
    }

    public function getNodeTypes(): array
    {
        return [
            Node\Expr\ClassConstFetch::class
        ];
    }

    /**
     * @param Node\Expr\ClassConstFetch $node
     */
    public function refactor(Node $node): ?Node
    {
        $classConstName = $this->getName($node->class);
        $constName = $this->getName($node->name);

        if ($classConstName !== 'SomeClass') {
            return null;
        }

        if (! preg_match('#^HTTP_#', $constName)) {
            return null;
        }

        $newConstName = preg_replace('#^HTTP_#', 'STATUS_', $constName);
        $node->class = new Node\Name\FullyQualified(
            "\Fig\Http\Message\StatusCodeInterface"
        );
        $node->name = new Node\Identifier($newConstName);

        return $node;
    }
}
```

Then, register custom rector class to `rector.php` via `$services->set()`:

```php
<?php

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Utils\Rector\ClassConstFetch\ChangeHttpStatusRector;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(ChangeHttpStatusRector::class);
};
```

![Screen Shot 2022-03-24 at 01 42 01](https://user-images.githubusercontent.com/459648/159772853-540468fa-e13c-4d71-8d24-055244f9e263.png)

**Comment by sylbru** [comment]
Thanks @markoph, just discovered`--clear-cache`, curious why it’s necessary to use it every time apparently, I’d expect any changes to the rector config to invalidate the cache, but maybe I’m missing something. `print_node`/`dump_node` is great, missed that in the docs somehow! :+1: 

@samsonasik Awesome, managed to get it working! Thanks for your help!
