### ISSUE TITLE
TypeCombinator throws internal error

### ISSUE THREAD

**Issue by althaus** [rectorphp/rector#7071]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest             |

I'm trying to rector PHP 8.1 deprecations (aka adding missing return types to built-in interfaces like ArrayAccess or Iterator). For `RecursiveIterator->getChildren()` I want to add `?\RecursiveIterator` using `TypeCombinator::addNull()`.

This fails with an internal error.

~~~php
    $services->set(AddReturnTypeDeclarationRector::class)
        ->configure([
            // Fix RecursiveIterator (here faked as Demo)
            new AddReturnTypeDeclaration(Demo::class, 'hasChildren', new \PHPStan\Type\BooleanType()),
            // These 2 fail
            new AddReturnTypeDeclaration(Demo::class, 'getChildren', \PHPStan\Type\TypeCombinator::addNull(new \PHPStan\Type\ObjectType(Demo::class))),
            new AddReturnTypeDeclaration(Demo::class, 'getChildren', \PHPStan\Type\TypeCombinator::union(new \PHPStan\Type\ObjectType(Demo::class), new \PHPStan\Type\NullType())),
            // This works
            new AddReturnTypeDeclaration(Demo::class, 'getChildren', new \PHPStan\Type\UnionType([new \PHPStan\Type\ObjectType(Demo::class), new \PHPStan\Type\NullType()])),
        ])
    ;
~~~

## Minimal PHP Code Causing Issue

https://getrector.org/demo/0ace1bb8-b7f4-4206-91f5-c8c88f89fa87

## Expected Behaviour

The TypeCombinator should not fail?

Kind regards
Matthias

**Comment by TomasVotruba** [comment]
Hi, some Type value objects from PHPStan depend on services.
For configuration there are only simple value objects available.

The `UnionType` is way to go :+1:

**Comment by althaus** [comment]
Thanks for clearing this up! 🎉
