### ISSUE TITLE
Rector ignores PHPUnit's TestCase and crashes

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7073]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12.19 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

https://github.com/simPod/rector-repro

```
composer install
vendor/bin/rector --dry-run
```

```
PHP Fatal error:  Class My\Ns\Tests\SomeTest contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (My\Ns\Tests\SomeTest::getName) in /Users/user/Work/CDN77/oi/tests/SomeTest.php on line 10
```

## Expected Behaviour

No fail.

There's a trait in test that requires `getName` method that exists in PHPUnit TestCase class. However, rector thinks it's not there. I guess it somehow overloads phpunit

**Comment by samsonasik** [comment]
@simPod  you need to use `files` config in composer.json for that use case, like this:

```
       "autoload-dev": {
          "files": [
              "vendor/phpunit/phpunit/src/Framework/TestCase.php"
          ]
        }
```

and run:

```
composer dump-autoload
```

so you are ensure has the `vendor/phpunit/phpunit/src/Framework/TestCase.php` very early.

**Comment by simPod** [comment]
I believe the PR fixed it? Because nobody wants to define files autoloading like that but I guess it's not relevant anymore (?)

**Comment by samsonasik** [comment]
should be fixed now, please try `"rector/rector": "dev-main"`
