### ISSUE TITLE
PHP Fatal error:  During class fetch: Uncaught ReflectionException

### ISSUE THREAD

**Issue by Garfield-fr** [rectorphp/rector#7074]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12.19 (invoke `vendor/bin/rector --version`)             |
| php version | 8.1.3 |             |
| symfony | 4.4 |

## Minimal PHP Code Causing Issue

When I run the command `./vendor/bin/rector process`, I get an error. Here is the message:

`PHP Fatal error:  During class fetch: Uncaught ReflectionException: Method PHPUnit\Framework\TestCase::tearDown() does not exist in /var/www/vendor/symfony/framework-bundle/Test/ForwardCompatTestTrait.php:18`

if i downgrade to version v0.12.18, i no longer have this error.

**Comment by Wirone** [comment]
Yeah, from one problem for us to another one 😉 [0.12.19 fixed Codeception problem](https://github.com/rectorphp/rector-src/commit/8f86f525f767f26787126265c158e8b9e77c4c0a#commitcomment-69350805), but Rector itself stopped working and we did not find it out 😩 Fortunately we have CI job that allows failures, so it does not block our work.

**Comment by samsonasik** [comment]
@Garfield-fr you need to require --dev phpunit/phpunit and use `files` config in composer.json for that use case, like this:

```
       "autoload-dev": {
          "files": [
              "vendor/phpunit/phpunit/src/Framework/TestCase.php"
          ]
        }
```

so you are ensure has the `vendor/phpunit/phpunit/src/Framework/TestCase.php` very early.

**Comment by samsonasik** [comment]
should be resolved by https://github.com/rectorphp/rector-src/pull/1960

**Comment by Wirone** [comment]
FYI: I've tested `dev-main ec76745` and it looks like it's working (both Codeception and Rector).

**Comment by Wirone** [comment]
@TomasVotruba any chances for the release?
