### ISSUE TITLE
ArrayShapeFromConstantArrayReturnRector generating unquoted array-keys

### ISSUE THREAD

**Issue by janedbal** [rectorphp/rector#7077]
# Bug Report

The generated phpdoc is invalid for PHPStorm and even slevomat/coding-standard.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/5f1fd96b-aad3-4016-bc21-b5f44407a9df

```php
<?php

final class DemoFile
{

    private function getDefaultContext(): array
    {
        return [
            'string with.dot' => '',
        ];
    }
}
```

### Responsible rules

* `ArrayShapeFromConstantArrayReturnRector`

## Expected Behavior

Proper PHPDoc **with quotes**.

```php
   /**
     * @return array{'string with.dot': string}
     */
```

**Comment by samsonasik** [comment]
Please try latest `"rector/rector": "dev-main"`, it should currently skipped due to printing is not add quote, so use regex `#\W#u` for skip any non word.
