### ISSUE TITLE
Invalid PrivatizeFinalClassMethodRector refactoring.

### ISSUE THREAD

**Issue by alanbem** [rectorphp/rector#7079]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.19            |

Sometime between `0.12.18` and `0.12.19` change was introduced which resulted in a bug. 
It looks like main culprit is `PrivatizeFinalClassMethodRector` 

## Minimal PHP Code Causing Issue

![image](https://user-images.githubusercontent.com/320410/160589960-717de0c6-85f5-4d92-ac4e-37bb760d8277.png)

All protected `setUp()` methods in my tests were turned into `private`.

## Expected Behaviour

It's invalid refactoring, because parent method `PHPUnit\Framework\TestCase::setUp()` is `protected` and child methods should stay that way.

**Comment by samsonasik** [comment]
@alanbem could you try latest `"rector/rector": "dev-main"` ? I tried create test for it and it seems working ok:

![Screen Shot 2022-03-29 at 17 24 20](https://user-images.githubusercontent.com/459648/160591295-894a2615-0a9e-4ce0-b8d9-051f08ed3d3e.png)

If the issue persists, could you create sample repository with its setup for it ? Thank you.

**Comment by alanbem** [comment]
`dev-main` works as expected

**Comment by alanbem** [comment]
Do you have any idea what could have caused this bug? 

FYI we also use analyse codebase with `phpstan` and have `rector` pointed at its `phpstan.neon` config.

**Comment by alanbem** [comment]
I would recommend to run your test on `0.12.19` and check if bug is there.

It would mean that there is no existing test for that in `dev-main`.

**Comment by samsonasik** [comment]
there is kind of test for it https://github.com/rectorphp/rector-src/blob/edcd91a29f7db89d0e478f6028a9d750317a1b42/rules-tests/Privatization/Rector/ClassMethod/PrivatizeFinalClassMethodRector/Fixture/keep_parent_protected_method.php.inc
