### ISSUE TITLE
Symfony support is missing

### ISSUE THREAD

**Issue by lyrixx** [rectorphp/rector#7082]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `Rector cbefb243e25ad213b187a55e5e50ec34b627b547`, (0.12.19 via `composer show`)             |

The packages on my computer miss the `SymfonySetList` class.
It states in https://github.com/rectorphp/rector-symfony that the packages is already included here, but I cannot find the class (on my computer, nor on github)

More over, the [composer.json](https://github.com/rectorphp/rector/blob/ed06366a1d56bf5709ddc854d0fea043513ac5ac/composer.json#L25) tells us that it conflict with `rectorphp/rector-symfony` (it should be a replaced BTW?)

Did I missed something?

**Comment by TomasVotruba** [comment]
Hi, could you share minimal repository on Github? The `SymfonySetList` is included in the shipped version:
https://github.com/rectorphp/rector/blob/0.12.19/vendor/rector/rector-symfony/src/Set/SymfonySetList.php

**Comment by lyrixx** [comment]
Here you go: https://github.com/lyrixx/test/tree/rector

**Comment by lyrixx** [comment]
OK, found it. My IDE cannot detect the class because it's in a vendor. Sorry for the noise

**Comment by TomasVotruba** [comment]
What IDE do you use? My PHPStorm detects it correctly. The vendor classes should be autocompleted too anyway.

**Comment by lyrixx** [comment]
I use code, but I [ignore](https://github.com/lyrixx/dotfiles/blob/master/vscode/settings.json#L16) vendor in vendor because I contribute quite often, and so I run composer install in vendor, and I don't want to find double vendored file 😂. But in this case 💥 

It's not so common to version vendor :) It would be easier to let composer does the job, but I'm sure you did that on purpose :)

**Comment by TomasVotruba** [comment]
I see :) yea, when 2 edge cases meet, world colapses :laughing: 

In prefixed/phared tools like PHPUnit, Rector or PHPStan it's default behavior. Just mostly the vendor is hidden in the phar. We make it open here, so any work with legacy code and Rector can be tuned manually.

Here is explained how to use it: https://getrector.org/blog/2020/12/28/rector-09-released#debuggable-rector-prefixed

**Comment by featuriz** [comment]
Hello @lyrixx :: I face same problem vscode. How to solve this? Do I have to update composer.json file or some changes in config?

Also, @TomasVotruba  your link is 404
