### ISSUE TITLE
Rector does not detect correclty my PHP version

### ISSUE THREAD

**Issue by lyrixx** [rectorphp/rector#7083]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector cbefb243e25ad213b187a55e5e50ec34b627b547|

## Minimal PHP Code Causing Issue

https://github.com/lyrixx/test/tree/rector

![image](https://user-images.githubusercontent.com/408368/160835122-fc2ec93f-4c96-44ef-8f08-2d21f62623af.png)

## Expected Behaviour

Rector should detect I'm using PHP 8.1 and the composer.json ask for 8.0
So the following error does not make sens to me: 

```
                                                                                                                        
 [WARNING] Your project requires min PHP version "7.4".                                                                 
                                                                                                                        
           1 Rector rules defined in your configuration require higher PHP version and will not run,                    
           to avoid breaking your codebase, use -vvv for detailed info.                                                 
                                                                                                                        

```

---

BTW, even if I add 

```
$parameters->set(Option::PHP_VERSION_FEATURES, \Rector\Core\ValueObject\PhpVersion::PHP_81);
```

I get this message

**Comment by TomasVotruba** [comment]
Could you share full `rector.php`? The will be probably some set import that overrides this value.

**Comment by lyrixx** [comment]
Sure, it's already in the repo : https://github.com/lyrixx/test/blob/rector/rector.php

**Comment by TomasVotruba** [comment]
See the:

https://github.com/lyrixx/test/blob/ccc8b34d21ece5fb8d167c98df186f83aff48d0f/rector.php?rgh-link-date=2022-03-30T12%3A47%3A35Z#L19

If you open this set, you'll see it adds the PHP 7.4 versoin too.

This is a Symfony config, so to override it, add parameter bellow this line.

**Comment by lyrixx** [comment]
Oh, Got it. thanks.
