### ISSUE TITLE
Call to a member function getClassReflection() on null

### ISSUE THREAD

**Issue by xpavp03** [rectorphp/rector#7086]
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.19
| vendor/bin/rector --version | Rector cbefb243e25ad213b187a55e5e50ec34b627b547
| PHP | 8.1.3, Docker

I couldn't reproduce the error with https://getrector.org/demo/

rector-fail/UserPresenter.php
```
<?php
namespace App\AdminModule\Presenters;

use Nette\Security\Passwords;

class TestPresenter extends BasePresenter
{

	public function actionTest()
	{
		Passwords::hash('test');
	}

}


abstract class BasePresenter extends \Nette\Application\UI\Presenter
{
}
```

```
<?php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Nette\Set\NetteSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
	$parameters = $containerConfigurator->parameters();
	$parameters->set(Option::PATHS, [
		__DIR__ . '/rector-fail',
	]);

	// must be NETTE_REMOVE_INJECT + NETTE_30
	// either of them alone won't trigger the error

	$containerConfigurator->import(NetteSetList::NETTE_REMOVE_INJECT);
	$containerConfigurator->import(NetteSetList::NETTE_30);
};
```

```
# ./vendor/bin/rector -vvv --clear-cache --debug process --dry-run
```

Throws:
```
rector-fail/UserPresenter.php
Fatal error: Uncaught Error: Call to a member function getClassReflection() on null in /var/www/app/vendor/rector/rector/vendor/rector/rector-nette/src/NodeAnalyzer/NetteInjectPropertyAnalyzer.php:32
Stack trace:
#0 /var/www/app/vendor/rector/rector/vendor/rector/rector-nette/src/Rector/Property/NetteInjectToConstructorInjectionRector.php(104): Rector\Nette\NodeAnalyzer\NetteInjectPropertyAnalyzer->canBeRefactored(Object(PhpParser\Node\Stmt\Property), Object(Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo))
#1 /var/www/app/vendor/rector/rector/src/Rector/AbstractRector.php(239): Rector\Nette\Rector\Property\NetteInjectToConstructorInjectionRector->refactor(Object(PhpParser\Node\Stmt\Property))
#2 /var/www/app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Property))
#3 /var/www/app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#4 /var/www/app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#5 /var/www/app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#6 /var/www/app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#7 /var/www/app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#8 /var/www/app/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(56): PhpParser\NodeTraverser->traverse(Array)
#9 /var/www/app/vendor/rector/rector/src/Application/FileProcessor.php(54): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#10 /var/www/app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#11 /var/www/app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#12 /var/www/app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#13 /var/www/app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#14 /var/www/app/vendor/rector/rector/src/Console/Command/ProcessCommand.php(147): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220323\Symfony\Component\Console\Input\ArgvInput))
#15 /var/www/app/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220323\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220323\Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/app/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220323\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220323\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220323\Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/app/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220323\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220323\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220323\Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/app/vendor/rector/rector/src/Console/ConsoleApplication.php(66): RectorPrefix20220323\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220323\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220323\Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/app/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220323\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220323\Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/app/vendor/rector/rector/bin/rector.php(57): RectorPrefix20220323\Symfony\Component\Console\Application->run()
#21 /var/www/app/vendor/rector/rector/bin/rector(5): require_once('/var/www/app/ve...')
#22 /var/www/app/vendor/bin/rector(117): include('/var/www/app/ve...')
#23 {main}
  thrown in /var/www/app/vendor/rector/rector/vendor/rector/rector-nette/src/NodeAnalyzer/NetteInjectPropertyAnalyzer.php on line 32
```

**Comment by xpavp03** [comment]
Please let me know if there's anything else I can add.

Thank you for your hard work!

**Comment by TomasVotruba** [comment]
Hi Peter,

thanks for great report!

I assume the fix would be to check this line for `$scope instanceof Scope`:
https://github.com/rectorphp/rector-nette/blob/main/src/NodeAnalyzer/NetteInjectPropertyAnalyzer.php#L30


Good luck tomorrow with the job :+1:

**Comment by xpavp03** [comment]
I forgot to mention that the error isn't triggered when cache is enabled. (Sorry.)
The only way to trigger it was either by clearing the cache directory with `rm -rf` (when I determined it with Option::CACHE_DIR) or by calling Rector with `--clear-cache`.

This probably explains why I couldn't reproduce it with https://getrector.org/demo/

The error also doesn't occur without the BasePresenter.

This made me believe that the root of the problem is in fact elsewhere. Even if your suggested solution worked, it would be dealing with a symptom and not the real problem.

I tried XDebugging the NetteInjectPropertyAnalyzer.php and the call stack for some time but I was stumbling in the dark without deeper knowledge of the inner workings of Rector.

> Good luck tomorrow with the job +1

:smiley: :heart:

**Comment by samsonasik** [comment]
@xpavp03 that's cache + autoload issue sometime happen, and that's possibly due to internal PHPStan cache or autoload cache, so possibly not testable.

If you run on CI, that's may need to run twice. I created PR https://github.com/rectorphp/rector-nette/pull/61 for it.

**Comment by xpavp03** [comment]
@samsonasik Actually, for me it happens consistently every time.

At the time of the error
```
        $scope = $property->getAttribute(\Rector\NodeTypeResolver\Node\AttributeKey::SCOPE);
        $classReflection = $scope->getClassReflection();
```
$classReflection === null
$property->type->parts
```
Array
(
    [0] => Nette
    [1] => Security
    [2] => Passwords
)
```
I tried putting Passwords.php into the directory with UserPresenter. It gets loaded first but the error is still triggered. In other words, I believe Rector knows about Nette\Security\Passwords when trying to get the class reflection.

This property doesn't exist in the original source code. I believe it was added by StaticCallToMethodCallRector from NETTE_30. But the script is dying in NetteInjectToConstructorInjectionRector which I thought was meant to run first.

I wonder if somehow one rule didn't leave incomplete information in memory for the next rule. This information is probably saved in cache but we're not using it at the moment.

**Comment by xpavp03** [comment]
Another piece of information:
When I run Rector for real (not in dry mode), with just NETTE_30 and then run it again for NETTE_REMOVE_INJECT (and then for a good measure, again with NETTE_30), it doesn't die.

And it seems NETTE_REMOVE_INJECT is not applied:
```
<?php
namespace App\AdminModule\Presenters;

use Nette\Security\Passwords;

class TestPresenter extends BasePresenter
{

	/**
	 * @inject
	 */
	public \Nette\Security\Passwords $passwords;
	public function actionTest()
	{
		$this->passwords->hash('test');
	}

}


abstract class BasePresenter extends \Nette\Application\UI\Presenter
{
}

```

**Comment by samsonasik** [comment]
@xpavp03 could you try latest `"rector/rector": "dev-main"` ? If the issue persist, could you create a repository that show the issue and expected output? Thank you.

**Comment by xpavp03** [comment]
I confirm that the error no longer shows.

```
  - Upgrading rector/rector (0.12.19 => dev-main d991c5d): Extracting archive
```

```
# ./rector.sh process --dry-run --clear-cache
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================

1) rector-fail/UserPresenter.php:5

    ---------- begin diff ----------
@@ @@
 class TestPresenter extends BasePresenter
 {

+	/**
+	 * @inject
+	 */
+	public \Nette\Security\Passwords $passwords;
 	public function actionTest()
 	{
-		Passwords::hash('test');
+		$this->passwords->hash('test');
 	}

 }
    ----------- end diff -----------

Applied rules:
 * PropertyAddingPostRector
 * StaticCallToMethodCallRector
 * FormerNullableArgumentToScalarTypedRector

                                                                                                                       
 [OK] 1 file would have changed (dry-run) by Rector                                                                     
```

**Comment by xpavp03** [comment]
However, I still feel that this is just covering up the real problem that lies elsewhere https://github.com/rectorphp/rector/issues/7086#issuecomment-1085519265
But I absolutely don't know how to look for it, nor I have the time. So I understand if you don't either. Probably worth leaving this ticket open?

**Comment by xpavp03** [comment]
Also, notice that `@inject` is not replaced with `public function __construct(private \Nette\Security\Passwords $passwords)`.

Interestingly, your demo does.

The `@inject` is not replaced regardless of whether I use --clear-cache or not.

Do you want me to file a separate ticket for it?

**Comment by samsonasik** [comment]
Please create failing test case PR or new issue with repository sample when possible, thank you.

**Comment by xpavp03** [comment]
> Please create failing test case PR or new issue with repository sample when possible, thank you.

I understand that you mean adding a failing test to https://github.com/rectorphp/rector-nette/tree/main/tests

Where can I find instructions on how to run these tests?

**Comment by xpavp03** [comment]
@TomasVotruba told me just to run `phpunit` - yeah, but rector-nette alone doesn't have Rector. 
I git cloned nette-rector and when I run `composer install` I get:
```
 Problem 1
    - Root composer.json requires rector/rector-src dev-main -> satisfiable by rector/rector-src[dev-main].
    - rector/rector-src dev-main requires rector/rector-nette dev-main -> found rector/rector-nette[1.0.0+no-version-set] but it does not match the constraint. See https://getcomposer.org/dep-on-root for details and assistance.
```

I don't mind helping with the failing test but I don't have time to stumble through how to make the tests run in the first place.

Could you please add some 1-2-3 instructions to the Contributing page?
https://github.com/rectorphp/rector/blob/main/CONTRIBUTING.md

**Comment by TomasVotruba** [comment]
The PHPUnit is there: https://github.com/rectorphp/rector-nette/blob/main/composer.json#L16

I always run `composer update` for packages, as there is no lock.

**Comment by TomasVotruba** [comment]
To avoid more wasted time on your side with installing, maybe it's easier to a have a minimal reproducible repository on Github.
That usually brings the fastest solution and we'll work with same code :)

**Comment by Wirone** [comment]
@TomasVotruba @xpavp03 On Docker runtime there's no need to set `COMPOSER_ROOT_VERSION` explicitly because it's defined in `docker-compose.yml` so it's set as an environment variable inside container. I don't know how @xpavp03 was running `composer update`, but it just works:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/600668/175822653-877a12ff-b187-4dd0-a475-56ea64fb591e.png">

Most probably it was executed improperly.
