### ISSUE TITLE
PHPStan 1.6.0 with bleedingEdge will remove previous/next/parent node attributes

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#7088]
# Feature Request

Just to let you know - I'm currently fighting with memory leaks in PHPStan and I have some impressive results. I don't know yet when PHPStan 1.6.0 will be released as there's lot more work to be done, but one thing I know for sure now is that I no longer want to be using `PhpParser\NodeVisitor\NodeConnectingVisitor`.

By default nothing will break in PHPStan 1.6.0, but users can opt-in for new and potentially breaking features: https://phpstan.org/blog/what-is-bleeding-edge

So users with bleedingEdge included in their config would probably have broken Rector.

What you can do: the easy fix is to add these lines to Rector's PHPStan config:

```neon
services:
	-
		class: PhpParser\NodeVisitor\NodeConnectingVisitor
		tags:
			- phpstan.parser.richParserNodeVisitor
```

But obviously this leaks memory and is very inefficient. What I do instead in PHPStan core is to adapt rules not to use 'parent' node attribute, but instead write different visitors for different scenarios.

Check this PR to see what I mean: https://github.com/phpstan/phpstan-src/pull/1175

There's a bunch of new visitors there: ArrayFilterArgVisitor, ArrayMapArgVisitor, NewAssignedToPropertyVisitor, ParentStmtTypesVisitor, TryCatchTypeVisitor

And the assigned attributes are read in places where `'parent'` was used instead.

**Comment by TomasVotruba** [comment]
Hi Ondra, thanks for heads up :+1: 

> What I do instead in PHPStan core is to adapt rules not to use 'parent' node attribute, but instead write different visitors for different scenarios.

That could be way to go here too. We'll have to investigate each rule if we can modify it that way.

Do you have some PRs of such "moving away from parent" in PHPStan? We could inspire there.

**Comment by ondrejmirtes** [comment]
I did all the work in PHPStan itself in this PR: https://github.com/phpstan/phpstan-src/pull/1175

**Comment by samsonasik** [comment]
@ondrejmirtes `$node->getAttribute('parentStmtTypes')` returns array of types instead of `Nodes` ? How to get `parent' Node?

**Comment by ondrejmirtes** [comment]
You don't. You need to write a visitor that gathers the specific data and sets it to attributes. Check my PR.

**Comment by samsonasik** [comment]
I am not sure about specific data, as it can be anything in single upper to be checked after found, or up until very first Node or collections.

**Comment by ondrejmirtes** [comment]
Exactly - you need to write a different visitor for each use case and gather specific data.

**Comment by samsonasik** [comment]
resolved at https://github.com/rectorphp/rector-src/pull/2014 with compatibility config, we may can update to use specific visitor when possible in the future.
