### ISSUE TITLE
[Bug] TypedPropertyFromStrictConstructorRector refactor wrong code

### ISSUE THREAD

**Issue by rajan-parmar** [rectorphp/rector#7090]
# Bug Report

We are facing an issue with the `TypedPropertyFromStrictConstructorRector` rector class.

It is removing the default value of the class property unnecessarily.

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.19             |
 
## Minimal PHP Code Causing Issue

https://getrector.org/demo/441ea125-33dc-45ef-a92e-e32d81aa792b

## Expected Behavior

I think it is happening because we are setting the value of the property in the constructor conditionally.
In fact, we want to keep the default value and change it only in some cases.

**Comment by TomasVotruba** [comment]
The value is set as string or is default by string. There is no other change, so it is correct :+1:

**Comment by rajan-parmar** [comment]
Thanks @TomasVotruba for quick solution +1

**Comment by TomasVotruba** [comment]
Thank to @samsonasik :clap:
