### ISSUE TITLE
Cannot autowire service "Rector\Doctrine\NodeAnalyzer\MethodCallNameOnTypeResolver"

### ISSUE THREAD

**Issue by icanhazstring** [rectorphp/rector#7092]
# Bug Report
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12.19 (invoke `vendor/bin/rector --version`)             |

Running any command for rector produces the following error:
```
bin/php vendor/bin/rector --version

                                                                                                                        
 [ERROR] Cannot autowire service "Rector\Doctrine\NodeAnalyzer\MethodCallNameOnTypeResolver": argument                  
         "$simpleCallableNodeTraverser" of method "__construct()" references class                                      
         "Symplify\Astral\NodeTraverser\SimpleCallableNodeTraverser" but no such service exists.
```

## Minimal PHP Code Causing Issue
Running a symfony 5.4 application with php8.1 using composer-bin-plugin composer 2.3.3

## Expected Behaviour

Rector should work

**Comment by samsonasik** [comment]
Could you provide sample repository that reproduce it? Thank you.

**Comment by TomasVotruba** [comment]
I think this is bug in case of "composer-bin-plugin", as Rector requires composer plugin to work in `/vendor` directory.
See https://github.com/rectorphp/extension-installer

**Comment by TomasVotruba** [comment]
Let me know if there is something wrong. Unless you have PHP 7.0 and bellow, this is default way to go :)

**Comment by icanhazstring** [comment]
Can confirm. Using direct dependency or phar is working as expected :)

**Comment by ygarris-sevensenders** [comment]
Hi here!
Issue with autowiring is caused my extention-installer:
```
$ mkdir tmp-rector-dir && cd tmp-rector-dir
$ composer require --dev rector/rector
...
Using version ^0.15.2 for rector/rector

$ ./vendor/bin/rector --version
Rector 0.15.2

$ composer require --dev rector/extension-installer
...
Using version ^0.11.2 for rector/extension-installer

$ ./vendor/bin/rector --version
[ERROR] Cannot autowire service "Rector\DeadCode\Comparator\Parameter\ParameterDefaultsComparator": argument
"$defaultParameterValueResolver" of method "__construct()" references class
"Rector\DowngradePhp80\Reflection\DefaultParameterValueResolver" but no such service exists.
```

any idea what's wrong?

**Comment by ygarris-sevensenders** [comment]
Hey @TomasVotruba, could you please check my comment above?
Thank you!

**Comment by TomasVotruba** [comment]
The `rector/extension-installer` is part of core project only. It should not be installed extra/again.

**Comment by ygarris-sevensenders** [comment]
Oh, I see, that was not clear from `rector/extension-installer` README.md.
Thanx a lot!

**Comment by TomasVotruba** [comment]
I see :+1:  

Could you send a PR to fit it what you expect? It would help other devs
