### ISSUE TITLE
Invalid path provided in PHPSTAN_FOR_RECTOR_PATH not reported

### ISSUE THREAD

**Issue by janedbal** [rectorphp/rector#7093]
# Bug Report

Missing validation of phpstan for rector path. Tested version: 0.12.19 

## Minimal PHP Code Causing Issue

```php
<?php declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(\Rector\Core\Configuration\Option::PHPSTAN_FOR_RECTOR_PATH,  '/not-existing.neon');
};
```

## Expected Behaviour

Error produced.

**Comment by TomasVotruba** [comment]
This can done in PHPStan factory: https://github.com/rectorphp/rector-src/blob/be530c5e2f56190f5fe1813ae4344cdaf3f75d7f/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php#L37

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector-src/pull/2043
