### ISSUE TITLE
Feature request: add missing class method visibility

### ISSUE THREAD

**Issue by Firehed** [rectorphp/rector#7098]
# Feature Request

Nearly identical to `Rector\Php71\Rector\ClassConst\PublicConstantVisibilityRector`: it would be a great addition to have a rule to add missing visibility declarations to class methods.

Note: I was able to achieve this locally by changing the aforementioned class's `getNodeTypes()` to include `\PhpParser\Node\Stmt\ClassMethod::class`. That alone seemed to be sufficient, and I didn't get any false-positives with global functions or closures.

## Diff 

```diff
 class Foo
 {
-    function bar()
+    public function bar()
     {
```

**Comment by TomasVotruba** [comment]
Hi,
this could be quite easy to implement. Would you like to contribute this rule?

**Comment by Firehed** [comment]
I'm happy to look into it!

A couple questions before getting started:

New rule or extend existing one to have broader scope?

If new:
- Any naming preference for the new class?
- Should it extend the existing rule (currently declared final), copy-paste most of the internals, or compose the existing one in as a proxy of sorts?

If existing:
- Should the behavior be configurable? Should it default to the current, constant-only scope?

Thanks!

**Comment by TomasVotruba** [comment]
New rule that extends `AbstractRector` class would be the way to go.

Name like "ImplicitPublicClassMethodRector" sounds clear.
