### ISSUE TITLE
Incorrect behavior of AddDoesNotPerformAssertionToNonAssertingTestRector

### ISSUE THREAD

**Issue by b-durand** [rectorphp/rector#7101]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.20      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/930ff0e2-e1d7-4f89-9459-427c97a4915e

```php
<?php

use PHPUnit\Framework\TestCase;

final class MyTest extends TestCase
{
    public function testSomething()
    {
    }

    public function testOutput()
    {
        $this->expectOutputString('Hello world!');
    }
}
```

### Responsible rules

* `AddDoesNotPerformAssertionToNonAssertingTestRector`

## Expected Behavior

`expectOutputString` is an assertion.
```php
<?php

use PHPUnit\Framework\TestCase;

final class MyTest extends TestCase
{
    /**
     * @doesNotPerformAssertions
     */
    public function testSomething()
    {
    }

    public function testOutput()
    {
        $this->expectOutputString('Hello world!');
    }
}
```

**Comment by samsonasik** [comment]
Could you create failing test case PR to https://github.com/rectorphp/rector-phpunit/tree/main/tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture ? Thank you.
