### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivateMethodRector

### ISSUE THREAD

**Issue by b-durand** [rectorphp/rector#7102]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.20      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/2ffdac7e-3c0f-447e-96c7-14fcdc47d5a1

```php
<?php

final class DemoFile
{
    public function run(string $name)
    {
        return $this->{'do' . $name}();
    }

    private function doFoo()
    {
        return 5;
    }

    private function doBar()
    {
        return 4;
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior

Rector should skip to remove private methods with $this->{'do' . $name} call.

**Comment by samsonasik** [comment]
Could you create failing test case PR to https://github.com/rectorphp/rector-src/tree/main/rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture ? Thank you.
