### ISSUE TITLE
Rules not applied 

### ISSUE THREAD

**Issue by maki10** [rectorphp/rector#7103]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  v0.12.20 (be530c5e2f56190f5fe1813ae4344cdaf3f75d7f) |
| PHP version |  v7.4.27 |
| OS |  MacOS Monterey (M1) |

After fresh installation of the Rector, php rules look like been ignored. Tried on simple file, and only one rule are applied `ReturnTypeDeclarationRector`

## Minimal PHP Code Causing Issue

[Issue gist](https://gist.github.com/maki10/c1d9e06cce56bfe657fef5a776c371d4)

## Expected Behaviour

Rector should look at docs blocks and apply `Type Properties` on them.

**Comment by TomasVotruba** [comment]
Hi, please share a demo link with minimal config:
https://getrector.org/demo

And what is the expected change.

**Comment by maki10** [comment]
Oh, this is handy :)

Init setup: https://getrector.org/demo/5b0f07c4-b568-4fe5-a7df-c6eee2bcdf82
Should be resulted as https://getrector.org/demo/f3b6c017-2c46-43c4-9038-152148eff9de
