### ISSUE TITLE
e2e/attributes  dev-main error 

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7108]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main            |

@TomasVotruba it seems latest rector dev-main e2e/attributes  dev-main got error.

Even on PHP 7.2.34 Setup, ref https://github.com/rectorphp/rector/runs/5992116181?check_suite_focus=true#step:5:22, it possibly due to config update?

https://github.com/rectorphp/rector/blob/071d7cb7880579b2279aeff3b377d81c94d0836c/e2e/attributes/rector.php#L12

```bash
1s
Run ../../bin/rector process --dry-run --ansi


1 file with changes
===================

1) src/route.php:3

    ---------- begin diff ----------
@@ @@

 class SomeController
 {
-    /**
-     * @Route()
-     */
+    #[Route]
     public function someMethod()
     {
     }
    ----------- end diff -----------

Applied rules:
 * AnnotationToAttributeRector (https://wiki.php.net/rfc/attributes_v2)
 * RenamePropertyRector


                                                                                
 [OK] 1 file would have changed (dry-run) by Rector                             
```

**Comment by TomasVotruba** [comment]
Thanks for sharing. At the first sight, the test is correct. The value should be changed.
Probably the `--dry-run` should be removed there.

I'll investigate

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/2066
