### ISSUE TITLE
Incorrect behavior of TypedPropertyFromStrictConstructorRector

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#7113]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/7d1e7ebc-b431-4fb9-93b8-854e35d35fc2

```php
<?php

class DemoFile
{
    /**
     * @var string
     */
    public $public;
    
    /**
     * @var string
     */
    protected $protected;
    
    /**
     * @var string
     */
    private $private;
    
	public function __construct(string $public, string $protected, string $private) {
    	$this->public = $public;
        $this->protected = $protected;
        $this->private = $private;
    }
    
    public function setPrivate(int $private) {
    	$this->private = $private;
    }
}
```

### Responsible rules

* `TypedPropertyFromStrictConstructorRector`

## Expected Behavior
TypedPropertyFromStrictConstructorRector should not add TH when property is written outside the `__construct()` method. In my example the `$private` property is written also inside `setPrivate()` method which is type hinted with `int` (not typed parameter should also be considered as "other" (unknown) type).
Right now this rector does not deliver instant upgrade because every class has to be checked manually. Of course one can use PHPStan to detect cases with incompatible type assignment but it cannot detect the other case I've mentioned i.e. untyped method parameter that is then assigned to class property (I reported this problem to PHPStan project yesterday https://github.com/phpstan/phpstan/issues/7039).

I can work on a pull request to extend TypedPropertyFromStrictConstructorRector features but first I will await some feedback.

**Comment by samsonasik** [comment]
`TypedPropertyFromStrictConstructorRector` is part of type declaration strict, which assumpsion, the type is already consistent before upgrading, you can however, handle it by provide `TypedPropertyFromAssignsRector` first before:

```php
    $services->set(\Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector::class);
    $services->set(\Rector\TypeDeclaration\Rector\Property\TypedPropertyFromStrictConstructorRector::class);
```

 so it will be result UnionType `string|int`, ref https://getrector.org/demo/5e85d599-9773-457c-82af-6c1b0b96673d

**Comment by javaDeveloperKid** [comment]
@samsonasik I would be grateful not to close the issue until all the participants are satisfied with the answer/solution.

**Comment by javaDeveloperKid** [comment]
> `TypedPropertyFromStrictConstructorRector` is part of type declaration strict, which assumpsion, the type is already consistent before upgrading

Ok, that make thinks better but not ideal. The problem with untyped param in some setter still exists because it can be everything.

**Comment by samsonasik** [comment]
Well, if the code base is not typed yet, even without doc type, using type-declaration-strict is not the way to go. 

Upgrading old code base is not 1 way to go, it need step by step. Let say, you're upgrading php 5.5 code, you can start with `LevelSetList::UP_TO_PHP_56`, if still working, continue until `LevelSetList::UP_TO_PHP_81`, next, try another SetList, and so on, that will be better checked automatically with Continues Integration with unit test running to verify it.

**Comment by javaDeveloperKid** [comment]
I can see that when `int` param type is removed the `@var` annotation gets `mixed` part. I think I can use this information it to detect such cases and then omit such properties for now by reverting modification with some nice regexp.

**Comment by TomasVotruba** [comment]
This case should be skipped by this rule, as it does not meet the condition to be 100 % sure.

> I can work on a pull request to extend TypedPropertyFromStrictConstructorRector features but first I will await some feedback

That would be very helpful, thanks 🙏

**Comment by javaDeveloperKid** [comment]
Thank you for your answer @TomasVotruba. 
I wonder what way we want to go. Do we want this rector to add TH only when property is only written inside constructor and nowhere else or do we want add TH when assignments in other methods are 100% known (and the same as in constructor?) ? The first solution could be handled by extending configuration in TypedPropertyFromAssignsRector, e.g. `'constructor_only_assigns' => true`, because we already have collected information about every assignment in the class in this rector. 
The second solution makes me thing that maybe we need a new rector (or merge some rectors into one) that would deliver a functionality described as __"add TH only when 100% sure"__. Generally, the problem I described in this bug report happens also in TypedPropertyFromStrictGetterMethodReturnTypeRector (see https://getrector.org/demo/263c26b3-702c-4156-85f7-c3cab54b2812). It adds TH but there are other assignmens in the class.

What do you think?

**Comment by samsonasik** [comment]
The `strict` word is there for a reason, "strictly based on defined". It was started from `TypedPropertyRector` if I remember correctly, which handle too many things, so it extracted to various rules for smaller task/specific task to `typedecaration` sets. 

In `dev-main` version, there is a patch on `TypedPropertyRector` which mostly handle nullable default value on typed by `@var`, which closely related to `TypedPropertyFromAssignsRector` (which not marked as strict), see PRs:

- https://github.com/rectorphp/rector-src/pull/2029
- https://github.com/rectorphp/rector-src/pull/2050

You can start with `TypedPropertyRector`, then `TypedPropertyFromAssignsRector`, then the rest should be more handled.

For more safe usage, you can sort the list by LevelUpTo first, then TypeDeclaration, then TypeDeclaration-Strict for example:

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_80,
        SetList::TYPE_DECLARATION,
        SetList::TYPE_DECLARATION_STRICT,
    ]);

    $rectorConfig->paths([_DIR__ . '/src']);
};
```

Above example is using `RectorConfig` usage, you can use on `dev-main` version:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by javaDeveloperKid** [comment]
> You can start with TypedPropertyRector

Unfortunately I can't use this rector as it uses docblocks and my project has many falsy annotations and I have to ignore them :(. I will try to find a way to somehow mix Rector help, IDE help and regexp help to get very high confidence level of correctness.

**Comment by samsonasik** [comment]
You can start with `TypedPropertyFromAssignsRector`, that more precise as that's check the assignment values type. You can register:

```php
    $services->set(\Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector::class);
```

**Comment by samsonasik** [comment]
@javaDeveloperKid I created PR https://github.com/rectorphp/rector-src/pull/2128 for it.
