### ISSUE TITLE
IfToSpaceshipRector sorts ASC instead of DESC

### ISSUE THREAD

**Issue by peterlupu** [rectorphp/rector#7118]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.21             |
| PHP Version | PHP 7.4.27 (cli) (built: Dec 16 2021 18:14:46) ( NTS ) |

The original code sorts an array descending by count() of members. After running rector (see demo), the new code sorts the array in ascending order.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/d641f20a-4f8c-4824-be19-9e51bd4885d0

## Expected Behaviour

```php
usort($arr, function($a, $b) {
    if (count($a) === count($b)) {
        return 0;
    }

    return count($a) > count($b) ? -1 : 1;
});
```

turns into

```php
usort($arr, fn($a, $b) => count($a) <=> count($b));
```

but it should be

```php
usort($arr, fn($a, $b) => count($b) <=> count($a));
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. Seems you're right. 
Would you like to fix it?

**Comment by peterlupu** [comment]
> Hi, thanks for reporting. Seems you're right. Would you like to fix it?

Hi. I just installed rector this morning so I'm a bit unfamiliar with it. But will try to later today and see if I can manage.

**Comment by peterlupu** [comment]
> Hi, thanks for reporting. Seems you're right. Would you like to fix it?

Could you please review https://github.com/rectorphp/rector-src/pull/2097 ?
