### ISSUE TITLE
Allow overriding/customizing cache

### ISSUE THREAD

**Issue by freiondrej-lmc** [rectorphp/rector#7119]
# Feature Request

Hello, I'm currently debugging Rector cache, because we don't understand its behavior in our CI/CD pipeline. I wanted to create a LoggingCache decorating \Rector\Caching\Cache, which would be created using \RectorDebug\LoggingCacheFactory (decorating \Rector\Caching\CacheFactory). 
However, since \Rector\Caching\Detector\ChangedFilesDetector::__construct() requires exactly \Rector\Caching\Cache, I cannot do that. Another possibility that I explored was to decorate \Rector\Caching\ValueObject\Storage\FileCacheStorage, but that's also not possible to do by container modification, since it is instantiated in \Rector\Caching\CacheFactory::create() and not retrieved from DIC as a service. Futhermore, I found a configuration parameter \Rector\Core\Configuration\Option::CACHE_CLASS, but it seems to allow just \Rector\Caching\ValueObject\Storage\FileCacheStorage or \Rector\Caching\ValueObject\Storage\MemoryCacheStorage, nothing custom.

Of course it's possible that I just lack some Symfony DIC knowledge on how to do this.

EDIT: I managed to add a LoggingFileCacheStorage by setting a custom Factory for \Rector\Caching\Cache - the custom Factory does not decorate \Rector\Caching\CacheFactory, but instead it creates a `new \Rector\Caching\Cache(new \RectorDebug\LoggingFileCacheStorage($cacheDirectory, $this->smartFileSystem))`. However, this feels a bit cumbersome and makes me think if there could be another possibility to do this, e.g. leveraging the \Rector\Core\Configuration\Option::CACHE_CLASS parameter.

**Comment by CodeCasterNL** [comment]
@freiondrej-lmc see https://github.com/rectorphp/rector/issues/7341, is that what you mean?
