### ISSUE TITLE
FinalizeClassesWithoutChildrenRector with Option::PARALLEL

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#7120]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.20             |

When using `FinalizeClassesWithoutChildrenRector` rule and setting parallel to true some classes are made final while they shouldn't. Without using parallel they are not made final.

## Minimal PHP Code Causing Issue

I'm not sure how to create reproduction code. Maybe you can suggest a way?

## Expected Behaviour

Rector should not make classes final that are inherited.

**Comment by samsonasik** [comment]
Overlapped autoload, even on non-parallel can happen, that's troubleshooting documented at https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#troubleshooting
