### ISSUE TITLE
Demo: impossible to create an issue from the demo

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#7122]
Try to create an issue from this demo:

https://getrector.org/demo/15a1c103-5d3a-473a-9ca2-c23cecee5ca3

You will get an error as the URL is too long.

Don't know if it can be fixed...

**Comment by TomasVotruba** [comment]
Hi, that's limit of Github API.

But you can see the code snippet is really huge. It should be narrowed to the minimal problem. Most code fixtures should be 10-30 lines. The same limit we apply for test fixtures.
