### ISSUE TITLE
Please add Releases link to GitHub repo homepage

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#7124]
# Feature Request

It's driving me crazy it isn't there :) This is what you need to do:

https://user-images.githubusercontent.com/104888/164552148-8fac7e84-e04c-42b4-bba6-7d0d3758b6d0.mov

**Comment by samsonasik** [comment]
@ondrejmirtes implemented 👍

**Comment by ondrejmirtes** [comment]
Awesome, thank you :)
