### ISSUE TITLE
Replace nesting and parent calls with simple foreach with over all stmts

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#7126]
Follow up to https://github.com/rectorphp/rector/issues/7088

For some time we have custom node visitors that connect each stmts, previous expression and next expression. These visitors were here to ease finding nearest child. Yet, it allow us to create complex rule, that hook into specific stmt, then traverse back and forth to detect if parent stmts meets some condition.

Instead, we can do simple foreach of specific stmts and have full context available right in the node. Then we can drop such visitors and get better performance and lower memory load. Which leads to easier to write rule :+1:

**Comment by TomasVotruba** [comment]
These are current users of the `PREVIOUS_STATEMENT` constant at the moment:

![Screenshot from 2022-04-22 17-08-28](https://user-images.githubusercontent.com/924196/164742833-68e0ff83-bcd4-46cc-acf9-1d41e7bfe251.png)

**Comment by samsonasik** [comment]
Loop over stmts logic can be repetitive in many rules? I don't understand how it works yet, how about using like `FunctionLikeVisitor`, `IfVisitor`, etc ? 

/cc @ondrejmirtes if you have opinion about it.

**Comment by TomasVotruba** [comment]
We can use a constant with array of these nodes. The goal is to get rid of any visitors at all and work only with active node context.

**Comment by samsonasik** [comment]
@TomasVotruba I tried the updated `dev-main` usage in `spiral` framework at PR https://github.com/spiral/framework/pull/656, it cause various invalid result, one of them is value from non typed param https://github.com/rectorphp/rector-src/pull/2130 and on usage of previously while ( I still need to check how to reproduce ), but it happen only after update to the last dev-main of loop over stmts usage.

Step to reproduce:

```
git clone https://github.com/samsonasik/framework-2/tree/update-rector-re-run
composer update rector/rector:dev-main
vendor/bin/rector
```

it will remove various stmts, which previously working ok, and now removed.

**Comment by samsonasik** [comment]
@TomasVotruba I creted PR https://github.com/rectorphp/rector-src/pull/2131 to revert implementation of `RemoveUnreachableStatementRector` to original as make invalid results on 2 frameworks (spiral, CodeIgniter4) I tried already

**Comment by TomasVotruba** [comment]
Closing as resolved :+1:
