### ISSUE TITLE
[BUG] Property $name was not found in reflection of class in appropriate model

### ISSUE THREAD

**Issue by misusonu18** [rectorphp/rector#7127]
In the `HandleInertiaRequests.php` File I have the code and then I'm running the rector I'm getting the issue in the below image that is the error I'm getting
![rectorerror](https://user-images.githubusercontent.com/52093984/164882586-46bfb4ae-b624-4986-9fe0-fc13d376d52f.png)

you can regenerate using [repo](https://github.com/misusonu18/rector-issue)

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
What is the output for run with `--debug`?

**Comment by misusonu18** [comment]
> Hi, thanks for reporting. What is the output for run with `--debug`?

![rector-output](https://user-images.githubusercontent.com/52093984/164887709-77b29689-e64d-46f5-a0b2-f52d3e5b46e5.png)

**Comment by misusonu18** [comment]
@TomasVotruba When it will be released?

**Comment by TomasVotruba** [comment]
We usually do bi-weekly releases to collect more bugfixes and features together.
In the meantime, you can use `dev-main` version locked to a commit.

**Comment by misusonu18** [comment]
okay!!, Thanks
