### ISSUE TITLE
ChangeSwitchToMatchRector rule unexpectedly modifies implementation behaviour/results

### ISSUE THREAD

**Issue by jrstanley** [rectorphp/rector#7128]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main 2d91dd0a11debbf3cedb0b0ccf56824c10ef255f            |

The `ChangeSwitchToMatchRector` rule can change the behaviour of code. This is due to [`match` arms being compared strictly ](https://www.php.net/match#:~:text=A%20match%20arm%20compares%20values%20strictly%20(%3D%3D%3D)%20instead%20of%20loosely%20as%20the%20switch%20statement%20does.) (`===`) vs. [`switch` arms being compared loosely](https://www.php.net/manual/en/control-structures.switch.php#:~:text=Note%20that%20switch/case%20does%20loose%20comparison.) `(==)`.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/cd552b41-4466-4473-bf31-c86cc32e540f

## Current Behaviour

Using the code in the example above;

```php
switch(1) {
    case '1':
        $a = 1;
        break;
    case 1:
        $a = 2;
        break;
    default:
        $a = 3;
}

echo $a;
```

[When executed as a `switch`](https://3v4l.org/QtcnM) outputs: 1

[Applying the `ChangeSwitchToMatchRector` rule](https://getrector.org/demo/cd552b41-4466-4473-bf31-c86cc32e540f) produces;

```php
$a = match (1) {
    '1' => 1,
    1 => 2,
    default => 3,
};
```

[When executed as a `match`](https://3v4l.org/o3doJ) outputs: 2

## Expected Behaviour

Should the `ChangeSwitchToMatchRector` rule exist, given that the comparison is fundamentally different? My expectation would be that the behaviour of the original code is prioritised.

Although we could check for switch arms that have loose equality and skip the rule, however given that we do not know the input it would not be possible to identify if a single switch arm would loosely match a given value.

It would be possible to change the `match` expression to handle loose equality checks [as detailed in the PHP docs](https://www.php.net/match#:~:text=Using%20match%20expressions%20to%20handle%20non%20identity%20checks), e.g.;

```php
$subject = 1;
$a = match (true) {
    $subject == '1' => 1,
    $subject == 1 => 2,
    default => 3,
};
```

_https://3v4l.org/LqXfd_

This approach does produce the expected results, however IMO it may be preferable to retain the use of `switch`.

**Comment by samsonasik** [comment]
I think different type cases can be skipped, I created PR https://github.com/rectorphp/rector-src/pull/2147 for it.

**Comment by jrstanley** [comment]
Thanks @samsonasik! Do you have any thoughts on `switch` implementations that rely on a loose equality check, but don't have mixed types in cases?

```php
switch (2) {
   case '2':
      $res = 'str 2';
      break;
   default:
      $res = 'default';
      break;
}
echo $res; // 'str 2'
```
Outputs 'str 2', however the `match` equivalent outputs 'default';

```php
$res = match (2) {
   '2' => 'str 2',
   default => 'default',
};

echo $res; // 'default'
```

**Comment by samsonasik** [comment]
@jrstanley that should be skipped as well, feel free to create failing test case PR or patch when you have a chance, thank you.

**Comment by jrstanley** [comment]
@samsonasik Without knowing what is being checked by the switch/match, I'm unsure how to tell when the rule should be skipped here? I think there would always be a risk given that `switch` and `match` check for equality differently (loose vs strict respectively?).

**Comment by samsonasik** [comment]
I think that's probably edge case for user write switch with only 1 case, and 1 default, with check string only, and pass number, we may need more use case of course to make that covered just in case that's happen, you can crete failing test case PR, and/or also a patch for it.

Also, there is skip option that can be used in case you have a very specific use case:

```php
$rectorRule->skip([
    \Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector::class
]);
```
