### ISSUE TITLE
Refactoring an expression to a statement

### ISSUE THREAD

**Issue by jrstanley** [rectorphp/rector#7129]
# Question
Is it possible to refactor an expression to a statement?

Namely I am looking to change a `PhpParser\Node\Expr\Match_` to a `PhpParser\Node\Stmt\Switch_`.

Examples of code to refactor might include:

```php
match ($value) {
    default => 'some value',
};
```

or;

```php
echo match ($value) {
    default => 'some value',
};
```

My current attempts are throwing an exception

> LogicException: Trying to replace expression (Expr_Match) with statement (Stmt_Switch)

**Comment by TomasVotruba** [comment]
Hi, thanks for great question. The exception is about PHP language syntax. The same way we can't replace this:

```diff
-foreach ($items as $item)
+foreach (switch()... as $item)
 {
 }
```
