### ISSUE TITLE
Incorrect behavior of ReturnTypeDeclarationRector

### ISSUE THREAD

**Issue by hirenkeraliya** [rectorphp/rector#7130]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.21      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/334c2b76-df14-4169-8334-ce924f3637fd

```php
<?php

final class DemoFile
{
    public function run(): closure
    {
        return function ($query) {
            $query->where('id', 1);
        };
    }
}
```

### Responsible rules

* `ReturnTypeDeclarationRector`

## Expected Behavior

It should be skipped for the closure.

I don't know if it's right or wrong. But, in my application, I need to ignore this whole application. I am using the laravel 9.9 version. and it will expect closure instead of callable. But, This class converts it into the callable.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting :+1: 

I've dropped the dead code set to make config more narrow:
https://getrector.org/demo/51944043-1b80-4f1f-910b-3e577cdeb6f2

This is definitely a bug. Could you send a failing test fixture?

**Comment by hirenkeraliya** [comment]
@TomasVotruba I tried to run tests on my local and there are 100+ tests that are failing so that's why I created a [gist](https://gist.github.com/hirenkeraliya/d8648e5434244f62d90a897e22853971) for it.
