### ISSUE TITLE
Combine .php files

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector#7131]
# Feature Request

How should I configure Rector to combine files (containing functions only)?
Taking care of

- opening PHP tags
- namespaces
- imports

Thank you!

**Comment by TomasVotruba** [comment]
Hi,

it seem you'll need to re-use `FileWithoutNamespace` and `Namespace_` nodes, with printing the file in some service before the printing.

**Comment by szepeviktor** [comment]
Thank you.
