### ISSUE TITLE
Rector fails with `Class Symfony\Component\BrowserKit\AbstractBrowser not found`

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector#7135]
# Bug Report

| Subject        | Details      |
| :------------- | :--------|
| Rector version | 0.12.21 |

When we run analysis with `vendor/bin/rector process --no-progress-bar <file_paths> --dry-run` (in CI, but I was able to reproduce it locally too), we get:

```
In RuntimeReflectionProvider.php line 185:

  Class Symfony\Component\BrowserKit\AbstractBrowser not found.
```

It's weird, because we don't use `AbstractBrowser` anywhere in our codebase, the only occurrences are in `vendor` dir.

Let me know if I can check something to help you with finding the root cause.

## Minimal PHP Code Causing Issue

I can't reproduce it on demo site, it is probably strictly related to our app, its dependencies and the way how we run Rector.

## Expected Behaviour

To not fail 😉

**Comment by Wirone** [comment]
@samsonasik Not possible most probably, our app is too big and too complex, I just can't extract anything minimal from it because I don't even know what is causing the issue 🙂 And while it's proprietary, I can't share it as-is. I'll try to debug it anyway on my own, but it would be great to hear what to check.

**Comment by Wirone** [comment]
FYI: when I disable `LiteralGetToRequestClassConstantRector` in `rector.php` it does not result with fail for the same file that previously couldn't be analysed.

**Comment by TomasVotruba** [comment]
What is the exact Symfony package version? I'll see how it looks.

**Comment by Wirone** [comment]
@TomasVotruba do you mean PHPStan's Symfony extension (1.1.8)? Or Symfony components (some 4.4, some 5.4)?

**Comment by TomasVotruba** [comment]
@Wirone The reported `http-kernel/Client.php`: 

```bash
spl_autoload_call() at /app/vendor/symfony/http-kernel/Client.php:31
```

I expected there will be some magic. What is the patch version of that file?

**Comment by Wirone** [comment]
@TomasVotruba we have `symfony/http-kernel` in `v4.4.40` and unfortunately it's not easy to bump it to `5.*` because there are some internal wrapper packages for kernel, request, response etc (we don't have regular Symfony app, rather custom one built on  components)... I'm on a mission to upgrade all Symfony components to 5.4 but had hard time with this one. I hope at some point we will be able to upgrade 😉

**Comment by Wirone** [comment]
FYI: tested on 0.12.22 and it fails too.

**Comment by TomasVotruba** [comment]
The `Client` class for reference: https://github.com/symfony/http-kernel/blob/v4.4.40/Client.php

The `AbstractBrwoser` of 4.4.37 https://github.com/symfony/browser-kit/blob/v4.4.37/AbstractBrowser.php

This might be related: https://github.com/symfony/browser-kit/commit/3fa7d8cbd2e5006038a09b8ef93f3859a89b627e

**Comment by samsonasik** [comment]
@Wirone could you verify if latest dev-main https://github.com/rectorphp/rector/commit/79315b7df208e62a263c0d56ff0e9daee652c9e6#diff-d11e2b9e464a2d6711842693ee58d997e7d238e803fbbe33cea332ece518159e resolve it? Thank you.

**Comment by Wirone** [comment]
@samsonasik Tested on `dev-main 476869e` and issue remains (PHPStan 1.6.5 with bleeding edge enabled) 😢

**Comment by samsonasik** [comment]
Rector has overlapped autoload to use phpstan prefixed vendor, ref issue 

- https://github.com/rectorphp/rector/issues/7141

The dev-main has been re-generated for phpstan 1.6.5 which has tweak autoload, ref:

- https://github.com/rectorphp/rector/commit/770e1b0adcfd0e6e2f61de41becffc763a600bde#diff-134cdda2651140171fadec5357839abe6bf05d517ce78dafc69476f024bf6b6a
- https://github.com/phpstan/phpstan-src/commit/46f51e71c32b79313e36e6fd26fba94e6e8c70db
- https://github.com/rectorphp/rector-src/commit/1c828eea13161f5db8936cd21484dced04325449#commitcomment-72846710

 Please try again.

**Comment by Wirone** [comment]
Tested with `dev-main 770e1b0` and unfortunately the error is still there. It's related to `Symfony\Component\HttpKernel\Client` since it fails [here](https://github.com/rectorphp/rector-symfony/blob/504967432047b632438de54518618a1dadefd164/src/Rector/MethodCall/LiteralGetToRequestClassConstantRector.php#L76) (did some dump-driven-development 😉). I can't dig deeper right now.

**Comment by ondrejmirtes** [comment]
Please test if the problem appears with the latest PHPStan 1.7.x-dev commit. For one, PHPStan now has fully static reflection (no RuntimeReflectionProvider involved anymore), and for 2nd, I made some fixes to make more symbols discoverable even if they shouldn't be :) https://github.com/phpstan/phpstan-src/commit/e40474b3fcd27e5a2b37b8f6add8e7ad906db019

**Comment by Wirone** [comment]
@ondrejmirtes Still the same error.

```
$ composer info | grep -E 'rector|phpstan|symfony'
jangregor/phpstan-prophecy                     1.0.0
phpstan/extension-installer                    1.1.0
phpstan/phpstan                                1.7.x-dev 21ef03f
phpstan/phpstan-symfony                        1.1.8
rector/rector                                  dev-main 770e1b0
symfony/cache                                  v4.4.41
symfony/cache-contracts                        v2.5.1
symfony/config                                 v4.4.41
symfony/console                                v4.4.41
symfony/css-selector                           v5.4.3
symfony/debug                                  v4.4.41
symfony/dependency-injection                   v4.4.41
symfony/deprecation-contracts                  v2.5.1
symfony/dotenv                                 v4.4.37
symfony/error-handler                          v4.4.41
symfony/event-dispatcher                       v4.4.37
symfony/event-dispatcher-contracts             v1.1.12
symfony/expression-language                    v4.4.41
symfony/filesystem                             v4.4.39
symfony/finder                                 v4.4.41
symfony/flex                                   v1.18.6
symfony/framework-bundle                       v4.4.41
symfony/http-client-contracts                  v2.5.1
symfony/http-foundation                        v4.4.41
symfony/http-kernel                            v4.4.41
symfony/lock                                   v5.4.5
symfony/mailer                                 v5.4.5
symfony/mime                                   v5.4.8
symfony/options-resolver                       v5.4.3
symfony/polyfill-intl-grapheme                 v1.25.0
symfony/polyfill-intl-idn                      v1.25.0
symfony/polyfill-intl-normalizer               v1.25.0
symfony/polyfill-php72                         v1.25.0
symfony/polyfill-php73                         v1.25.0
symfony/polyfill-php80                         v1.25.0
symfony/polyfill-php81                         v1.25.0
symfony/polyfill-uuid                          v1.25.0
symfony/process                                v4.4.37
symfony/property-access                        v5.4.8
symfony/property-info                          v5.4.7
symfony/proxy-manager-bridge                   v4.4.39
symfony/psr-http-message-bridge                v2.1.2
symfony/routing                                v4.4.41
symfony/serializer                             v5.4.6
symfony/service-contracts                      v2.5.1
symfony/string                                 v5.4.8
symfony/translation                            v4.4.37
symfony/translation-contracts                  v2.5.1
symfony/var-dumper                             v5.4.8
symfony/var-exporter                           v5.4.8
symfony/yaml                                   v4.4.37
timeweb/phpstan-enum                           v3.0.0
```

I'll try to prepare reproducer, but it's not that easy.

But looking at it, it's because `symfony/http-kernel` requires `symfony/browser-kit` only in `require-dev`, while `Symfony\Component\HttpKernel\Client` (which is deprecated anyway) extends `Symfony\Component\BrowserKit\AbstractBrowser` which in fact is not installed:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/600668/166715053-8271a510-a9c3-40e2-864f-d161cbb996ef.png">

So it fails when Rector is trying to analyse that file with broken dependencies.

**Comment by TomasVotruba** [comment]
This is a bug in your dependency on a code that is provided by your vendor.
The best fix would be in Symfony, but I don't think they support such an old branch :)

**Comment by Wirone** [comment]
From @wouterj on Symfony Slack:

> Symfony uses optional dependencies for a lot of things. In this case, HttpKernel can be used without using the Client class. We don't want to complicate the dependency tree and we don't want to install unused packages. In this case, if you use Client, you must require the optional dependency manually

I too think it should be fixed in Symfony (soft dependency that causes invalid class), alternatively it could be fixed in Rector to handle `Symfony\Component\HttpKernel\Client` without `symfony/browser-kit` (common fix for many people in one place), but it will eventually end up as workaround and additional, not needed dependency in our app 😉

**Comment by TomasVotruba** [comment]
I think PHPStan is unable to analyse a class that is missing parent type, that's be design.

**Comment by TomasVotruba** [comment]
I think we can add workaround for this one as it's just one class. I hope rules don't need to analyse its method signatures. Let's see how it works for the future :)

**Comment by Wirone** [comment]
Thank you @TomasVotruba, I'll test it when it comes out 🙂
