### ISSUE TITLE
Remove @var annotation when type already declared

### ISSUE THREAD

**Issue by Lenny4** [rectorphp/rector#7136]
# Feature Request

Since php 7.4 we can [type property](https://www.php.net/manual/en/migration74.new-features.php).

It would be nice if rector automatically delete the annotation `@var` if the typed property match the `@var` property
 
## Diff 

```diff
-/**
- * @var string|null
- */
private ?string $someString = null;
```

What do you think ?

### Edit

Link to [TypeDeclaration](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#typedeclaration)

**Comment by samsonasik** [comment]
There is already `RemoveUselessVarTagRector` for it 

https://github.com/rectorphp/rector-src/blob/aa89fde52b66924e3b52ab7a106396c2b2aeb850/rules/DeadCode/Rector/Property/RemoveUselessVarTagRector.php#L17
