### ISSUE TITLE
Add removeRule to new config class

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#7139]
# Feature Request

Sometimes a set offers mainly all rules except for one rule in it. The old way to configure such case was:
```php
$containerConfigurator->import(SetList::PHP_81);
$services = $containerConfigurator->services();
$services->remove(ReadOnlyPropertyRector::class);
```
With the new config class this is still possible:
```php
$rectorConfig->sets([
    // ....
   SetList::PHP_81,
]);
$services = $rectorConfig->services();
$services->remove(ReadOnlyPropertyRector::class);
```

But because RectorConfig offers a `rule` method it only seems logical to add a `removeRule` method as a counterpart.

**Comment by samsonasik** [comment]
you should can use `->skip()` method:

```php
$rectorConfig->skip([
   ReadOnlyPropertyRector::class,
]);
```

**Comment by gisostallenberg** [comment]
Although that works it sets **one** option: `\Rector\Core\Configuration\Option::SKIP`. Calling skip twice results in the last criteria being set. Removing a rule is very different from that.
I like to configure in blocks that belong together (as in adding a set and right after that remove one or more rules), so it is clear that removing the rule belongs to adding the set.

An alternative could be to add a method `addSkip`, which extends the skip option instead of overwriting it...

**Comment by TomasVotruba** [comment]
The parameters should be merged, but there we depend on Symfony container behavior, which prevents this https://github.com/symfony/symfony/issues/26713

Generally the skip should be in your main `rector.php` config, also not to hide any configuration into the imports.
