### ISSUE TITLE
Interactive refractor rules

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#7140]
# Feature Request

I'm currently updating sulu to Symfony 6. And got an error that I need to change the `setDeprecated` method. See https://github.com/sulu/sulu/pull/6567/files as example.

This is something which I think is not possible for an automated rule as it does not know the value ('sulu/sulu', '1.2') to be inputted. But maybe it would be possible to implement some kind of interactive rules. Which ask the user when doing process which value they want to input in that case and so would help todo this kind of upgrades.

**Comment by TomasVotruba** [comment]
Hi, I'm not sure Rector can remove parts of configs. Could you share a diff of what should happen with what file based on specific inpurt configuration?

**Comment by alexander-schranz** [comment]
In that specific case the current thing is something like:

```php
->setDeprecated(
    'The "sulu_document_manager.slugifier" configuration is not used anymore since 2.1 and will be removed in 3.0.'
)
```

So to fix the case it would need 2 additional paraemter:

```php
->setDeprecated(
    '',
    '',
    'The "sulu_document_manager.slugifier" configuration is not used anymore since 2.1 and will be removed in 3.0.'
)
```

Basically it could be achieved via [`ArgumentAdderRector`](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#argumentadderrector)

But as the value 0 and 1 can not be known by rector it would be nice to use interactive way to ask the user via symfony console what value they want to input:

```php
$ui = new SymfonyStyle($input, $output);

$ui->write($codelines);

$ui->write('');
$argument0 = $ui->ask('Argument 0', '');
$argument1 = $ui->ask('Argument 1', '');
```

If it is run in a none interactive way it will automatically fallback to the default values.

Something like:

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(
        ArgumentAdderRector::class,
        [new ArgumentAdder('SomeExampleClass', 'someMethod', 0, new InteractiveArgument('Argument 0', ''), true, new ObjectType('SomeType'))]
    );
};
```

The question should be asked for every appereance, as the value can be different from case to case.

**Comment by TomasVotruba** [comment]
I see. Adding interaction would create a huge complexity and is out of our scope. The best job for Re for is to automate A to B migrations.

In this situation it's better to use manual upgrade tool like PHPStorm.

Another option is to code your project with linear BC breaks.

**Comment by alexander-schranz** [comment]
I understand that it would be add some complexity. And understand that this kind of migrations are out of scope of rector. Still thx for your quick responses and sharing your thoughts on this topic.
