### ISSUE TITLE
AddArrayDefaultToArrayPropertyRector - adds default value when it should not (readonly)

### ISSUE THREAD

**Issue by pionl** [rectorphp/rector#7142]
# Bug Report

🙌

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.12.212          |

`AddArrayDefaultToArrayPropertyRector` forces default `array` value to a `readonly` properties causing a PHP to fail when the
property is initialized in the constructor.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/0cb77e6c-9502-44fa-9ecd-e4d46838e7a2

## Expected Behaviour

Rector should leave `readonly` properties as they are.

Thanks!

**Comment by pionl** [comment]
@samsonasik sorry, I've included it in the issue but it was hidden (pasted it incorrectly :( )

**Comment by TomasVotruba** [comment]
@pionl Thanks 🙏 could you create a test fixture too? The "create test" button on demo helps with that

**Comment by pionl** [comment]
@TomasVotruba och, cool feature! https://github.com/rectorphp/rector-src/pull/2195

**Comment by pionl** [comment]
Thank you for the fix, have a great weekend
