### ISSUE TITLE
Again PHP Fatal Error: Cannot redeclare Functional\*

### ISSUE THREAD

**Issue by thomasvargiu** [rectorphp/rector#7146]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `0.12.23`            |

Same problem of #3383.

**Comment by TomasVotruba** [comment]
We'll need a reproducable repository.

**Comment by samsonasik** [comment]
I can't reproduce in latest dev-main, feel free to provide sample reproduced repository for it. Thank you.

**Comment by samsonasik** [comment]
I am closing it, we can't provide a solution for issue that not reproducible. Feel free to provide a sample repository when you have a chance.
