### ISSUE TITLE
[ERROR] Rector\Core\Console\Command\ShowCommand

### ISSUE THREAD

**Issue by guelosuperstart** [rectorphp/rector#7148]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.23           |
| php version | 8.0.17          |
| phpstan version | 1.6.4         |
| docker (mac) version |     20.10.13, build a224086     |

when i launch rector : 

```sh
 vendor/bin/rector process src tests --dry-run
```

i have this error : 

```
[ERROR] Expected to find class "Rector\Core\Console\Command\ShowCommand" in file                                       
"/var/www/app/api/vendor/rector/rector/src/Console/Command/ShowCommand.php" 
while importing  services from resource "/var/www/app/api/vendor/rector/rector/config/../src", 
but it was not found! Check the namespace prefix used with the resource in  /var/www/app/api/vendor/rector/rector/config/services.php
(which is being imported from "/var/www/app/api/vendor/rector/rector/src/Kernel/../../config/config.php"). 
```

<details>
  <summary>tree rector/rector/src </summary>
  
  ├── Application
│   ├── ApplicationFileProcessor.php
│   ├── FileDecorator
│   │   └── FileDiffFileDecorator.php
│   ├── FileProcessor
│   │   └── PhpFileProcessor.php
│   ├── FileProcessor.php
│   ├── FileSystem
│   │   ├── RemovedAndAddedFilesCollector.php
│   │   └── RemovedAndAddedFilesProcessor.php
│   └── VersionResolver.php
├── Autoloading
│   ├── AdditionalAutoloader.php
│   └── BootstrapFilesIncluder.php
├── Bootstrap
│   ├── ExtensionConfigResolver.php
│   └── RectorConfigsResolver.php
├── Config
│   └── Loader
│       └── ConfigureCallMergingLoaderFactory.php
├── Configuration
│   ├── ConfigurationFactory.php
│   ├── CurrentNodeProvider.php
│   ├── Option.php
│   ├── RectorConfigProvider.php
│   ├── RenamedClassesDataCollector.php
│   └── ValueObjectInliner.php
├── Console
│   ├── Command
│   │   ├── AbstractProcessCommand.php
│   │   ├── InitCommand.php
│   │   ├── ProcessCommand.php
│   │   ├── ShowCommand.php
│   │   └── WorkerCommand.php
│   ├── ConsoleApplication.php
│   ├── Output
│   │   ├── OutputFormatterCollector.php
│   │   └── RectorOutputStyle.php
│   └── Style
│       ├── RectorConsoleOutputStyle.php
│       ├── RectorConsoleOutputStyleFactory.php
│       └── SymfonyStyleFactory.php
├── Contract
│   ├── Application
│   │   └── FileDecoratorInterface.php
│   ├── Console
│   │   └── OutputStyleInterface.php
│   ├── PHPStan
│   │   └── Reflection
│   │       └── TypeToCallReflectionResolver
│   │           └── TypeToCallReflectionResolverInterface.php
│   ├── PhpParser
│   │   └── NodePrinterInterface.php
│   ├── Processor
│   │   └── FileProcessorInterface.php
│   ├── Rector
│   │   ├── AllowEmptyConfigurableRectorInterface.php
│   │   ├── ConfigurableRectorInterface.php
│   │   ├── NonPhpRectorInterface.php
│   │   ├── PhpRectorInterface.php
│   │   └── RectorInterface.php
│   └── Template
│       └── TemplateResolverInterface.php
├── DependencyInjection
│   ├── Collector
│   │   └── ConfigureCallValuesCollector.php
│   ├── CompilerPass
│   │   ├── MakeRectorsPublicCompilerPass.php
│   │   ├── MergeImportedRectorConfigureCallValuesCompilerPass.php
│   │   ├── RemoveSkippedRectorsCompilerPass.php
│   │   └── VerifyRectorServiceExistsCompilerPass.php
│   ├── Loader
│   │   ├── ConfigurableCallValuesCollectingPhpFileLoader.php
│   │   └── Configurator
│   │       └── RectorServiceConfigurator.php
│   └── RectorContainerFactory.php
├── Differ
│   └── DefaultDiffer.php
├── Enum
│   ├── ApplicationPhase.php
│   └── ObjectReference.php
├── Error
│   └── ExceptionCorrector.php
├── Exception
│   ├── Cache
│   │   └── CachingException.php
│   ├── Configuration
│   │   └── InvalidConfigurationException.php
│   ├── NotImplementedYetException.php
│   ├── ShouldNotHappenException.php
│   ├── Template
│   │   └── TemplateTypeNotFoundException.php
│   └── VersionException.php
├── Exclusion
│   └── ExclusionManager.php
├── FileSystem
│   ├── FilesFinder.php
│   ├── FilesystemTweaker.php
│   └── PhpFilesFinder.php
├── Kernel
│   └── RectorKernel.php
├── Logging
│   └── CurrentRectorProvider.php
├── NodeAnalyzer
│   ├── ArgsAnalyzer.php
│   ├── CallAnalyzer.php
│   ├── ChangedNodeAnalyzer.php
│   ├── ClassAnalyzer.php
│   ├── CoalesceAnalyzer.php
│   ├── CompactFuncCallAnalyzer.php
│   ├── ConstFetchAnalyzer.php
│   ├── EnumAnalyzer.php
│   ├── ExprAnalyzer.php
│   ├── InlineHTMLAnalyzer.php
│   ├── ParamAnalyzer.php
│   ├── PromotedPropertyParamCleaner.php
│   ├── PropertyAnalyzer.php
│   ├── PropertyFetchAnalyzer.php
│   ├── PropertyPresenceChecker.php
│   ├── VariableAnalyzer.php
│   └── VariadicAnalyzer.php
├── NodeDecorator
│   ├── CreatedByRuleDecorator.php
│   ├── NamespacedNameDecorator.php
│   └── PropertyTypeDecorator.php
├── NodeManipulator
│   ├── ArrayDestructVariableFilter.php
│   ├── ArrayManipulator.php
│   ├── AssignManipulator.php
│   ├── BinaryOpManipulator.php
│   ├── ClassConstManipulator.php
│   ├── ClassDependencyManipulator.php
│   ├── ClassInsertManipulator.php
│   ├── ClassManipulator.php
│   ├── ClassMethodAssignManipulator.php
│   ├── ClassMethodManipulator.php
│   ├── ClassMethodPropertyFetchManipulator.php
│   ├── Dependency
│   │   └── DependencyClassMethodDecorator.php
│   ├── ForeachManipulator.php
│   ├── FuncCallManipulator.php
│   ├── FunctionLikeManipulator.php
│   ├── IfManipulator.php
│   ├── MagicPropertyFetchAnalyzer.php
│   ├── MethodCallManipulator.php
│   ├── PropertyFetchAssignManipulator.php
│   ├── PropertyManipulator.php
│   ├── StmtsManipulator.php
│   └── VariableManipulator.php
├── NonPhpFile
│   ├── NonPhpFileProcessor.php
│   └── Rector
│       └── RenameClassNonPhpRector.php
├── PHPStan
│   └── Reflection
│       └── TypeToCallReflectionResolver
│           ├── ClosureTypeToCallReflectionResolver.php
│           ├── ConstantArrayTypeToCallReflectionResolver.php
│           ├── ConstantStringTypeToCallReflectionResolver.php
│           ├── ObjectTypeToCallReflectionResolver.php
│           └── TypeToCallReflectionResolverRegistry.php
├── Php
│   ├── PhpVersionProvider.php
│   ├── PhpVersionResolver
│   │   └── ProjectComposerJsonPhpVersionResolver.php
│   ├── Regex
│   │   └── RegexPatternArgumentManipulator.php
│   ├── ReservedKeywordAnalyzer.php
│   └── TypeAnalyzer.php
├── PhpParser
│   ├── AstResolver.php
│   ├── ClassLikeAstResolver.php
│   ├── Comparing
│   │   ├── ConditionSearcher.php
│   │   └── NodeComparator.php
│   ├── Node
│   │   ├── AssignAndBinaryMap.php
│   │   ├── BetterNodeFinder.php
│   │   ├── CustomNode
│   │   │   └── FileWithoutNamespace.php
│   │   ├── NamedVariableFactory.php
│   │   ├── NodeFactory.php
│   │   └── Value
│   │       ├── TernaryBracketWrapper.php
│   │       └── ValueResolver.php
│   ├── NodeFinder
│   │   ├── LocalConstantFinder.php
│   │   ├── LocalMethodCallFinder.php
│   │   └── PropertyFetchFinder.php
│   ├── NodeTransformer.php
│   ├── NodeTraverser
│   │   ├── FileWithoutNamespaceNodeTraverser.php
│   │   └── RectorNodeTraverser.php
│   ├── Parser
│   │   ├── InlineCodeParser.php
│   │   ├── RectorParser.php
│   │   └── SimplePhpParser.php
│   ├── Printer
│   │   ├── BetterStandardPrinter.php
│   │   ├── FormatPerservingPrinter.php
│   │   ├── NodesWithFileDestinationPrinter.php
│   │   └── Whitespace
│   │       └── IndentCharacterDetector.php
│   └── ValueObject
│       └── StmtsAndTokens.php
├── ProcessAnalyzer
│   └── RectifiedAnalyzer.php
├── Provider
│   └── CurrentFileProvider.php
├── Rector
│   └── AbstractRector.php
├── Reflection
│   └── ReflectionResolver.php
├── Reporting
│   └── MissingRectorRulesReporter.php
├── StaticReflection
│   ├── DynamicSourceLocatorDecorator.php
│   └── SourceLocator
│       ├── ParentAttributeSourceLocator.php
│       └── RenamedClassesSourceLocator.php
├── Stubs
│   └── PHPStanStubLoader.php
├── Template
│   └── DefaultResolver.php
├── Util
│   ├── MemoryLimiter.php
│   ├── PhpVersionFactory.php
│   ├── StaticRectorStrings.php
│   └── StringUtils.php
├── Validation
│   ├── Collector
│   │   └── EmptyConfigurableRectorCollector.php
│   ├── EmptyConfigurableRectorChecker.php
│   ├── InfiniteLoopValidator.php
│   └── RectorAssert.php
├── ValueObject
│   ├── Application
│   │   ├── File.php
│   │   └── MovedFile.php
│   ├── Bootstrap
│   │   └── BootstrapConfigs.php
│   ├── Configuration.php
│   ├── Error
│   │   └── SystemError.php
│   ├── FrameworkName.php
│   ├── MethodName.php
│   ├── PhpVersion.php
│   ├── PhpVersionFeature.php
│   ├── ProcessResult.php
│   ├── RectifiedNode.php
│   ├── Reporting
│   │   └── FileDiff.php
│   ├── SprintfStringAndArgs.php
│   ├── StaticNonPhpFileSuffixes.php
│   └── Visibility.php
├── ValueObjectFactory
│   ├── Application
│   │   └── FileFactory.php
│   └── ProcessResultFactory.php
├── constants.php
└── functions
    └── node_helper.php
</details>

**Comment by TomasVotruba** [comment]
Hi, this command was deprecated and removed couple months ago.
Could you clear the cache of your Docker? It will probably help.
