### ISSUE TITLE
[DX][FR] Improve resolving aliased grouped imports with UseImportsResolver

### ISSUE THREAD

**Issue by dritter** [rectorphp/rector#7150]
Hi there!

While working on [rector-src/pull/2177](https://github.com/rectorphp/rector-src/pull/2177), I stumbled upon grouped and aliased imports (`use Some\Namespace\{FirstClass as ClassA, SecondClass as ClassB}`. The culprit is that [UseImportsResolver#34](https://github.com/rectorphp/rector-src/blob/74b404e1d1f0d11d09c16eb542c951bc9d8078df/rules/Naming/Naming/UseImportsResolver.php#L34) filters for `Use_` Statements only. I suggest that the `GroupUse` Statements are handled (expanded) as `Use_` Statements. Regular aliases (non-grouped) `use Some\Namespace\FirstClass as ClassA` are handled correctly.
That way, no rule needs to handle this case. Otherwise every rule that deals with imports has to handle this case.

Disclaimer: There might be another way of resolving imports that I am not aware of, that handle Grouped Imports.

Thanks

**Comment by TomasVotruba** [comment]
Hi,

thanks for suggestion. I think that would be useful to have covered. Could you propose a PR with test fixture that is currently failing?

**Comment by dritter** [comment]
Sure. Will do in the next few days. :)

**Comment by samsonasik** [comment]
aliased import is part of Use_, you need to get via its UseUse

**Comment by samsonasik** [comment]
resolved at https://github.com/rectorphp/rector-src/pull/2348
