### ISSUE TITLE
Error RenameMethodRector for symfony

### ISSUE THREAD

**Issue by Lenny4** [rectorphp/rector#7155]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

## Minimal PHP Code Causing Issue

Rector rename the function `getUsername` to `getUserIdentifier` while it should not:

```php
<?php

use Symfony\Component\Security\Core\User\UserInterface;

class User implements UserInterface
{
    private ?string $username = null;
    private ?array $roles = [];

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): void
    {
        $this->username = $username;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(?array $roles): void
    {
        $this->roles = $roles;
    }

    public function eraseCredentials(): void
    {
        // do nothing
    }

    public function getUserIdentifier(): string
    {
        return 'somethingElse';
    }
}

class UserUtils
{
    public static function updateIdentifier(User $user): void
    {
        if (!empty($user->getUsername())) {
            // something
        }
    }
}
```
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Symfony\Set\SymfonySetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        SymfonySetList::SYMFONY_60,
    ]);
};

```
Output:
```
    ---------- begin diff ----------
@@ @@
 {
     public static function updateIdentifier(User $user): void
     {
-        if (!empty($user->getUsername())) {
+        if (!empty($user->getUserIdentifier())) {
             // something
         }
     }
    ----------- end diff -----------

Applied rules:
 * RenameMethodRector
 * AddParamTypeDeclarationRector
 * AddReturnTypeDeclarationRector
```

I couldn't reproduce the error on https://getrector.org/demo as the error occur only when the class implements `Symfony\Component\Security\Core\User\UserInterface`.

I created this repository to reproduce: https://github.com/Lenny4/RenameMethodRectorError

```bash
git clone git@github.com:Lenny4/RenameMethodRectorError.git
composer install
vendor/bin/rector process src --dry-run
```

## Expected Behaviour

The function `getUsername` should not be rename.

**Comment by TomasVotruba** [comment]
That seems expected. See https://github.com/rectorphp/rector-symfony/pull/158

**Comment by Lenny4** [comment]
@TomasVotruba how am I supposed to get the `username` of my `User` then ?

Because in my project the `userIdentifier` is NOT the `username` of the `User`

**Comment by samsonasik** [comment]
@TomasVotruba PR https://github.com/rectorphp/rector-symfony/pull/158 handle `loadUserByUsername()`, not `getUserIdentifier()`, also, the issue here seems because the `getUsername()` exists in the existing `User` class, which the other method `getUserIdentifier()` also exists.

**Comment by samsonasik** [comment]
so, the issue seems when both source and target method to be renamed exists, it should be skipped on `RenameMethodRector`
