### ISSUE TITLE
[PHP 8.2] Add readonly classes support

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#7160]
This feature should upgrade all read-only ctors to modifier on a `class` level.

```diff
-final class Book
+final readonly class Book
 {
     public function __construct()
     {
         // would this be the desired upgrade?
-        private readonly string $title
+       private string $title
     )
 } 
```

* RFC: https://wiki.php.net/rfc/readonly_classes
* php-src PR https://github.com/php/php-src/pull/7305/files

**Comment by samsonasik** [comment]
various note for implementation:

- should be skipiped on class has `#[AllowDynamicProperties]`
- should be skipped if there is other property that not readonly, eg: defined outside __construct.

```php
class A
{
    public $b;
    
    public function __construct(private readonly string $c) {}
}
```
