### ISSUE TITLE
Get ready for PHPStan 1.7.0

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#7161]
# Bug Report

Latest PHPStan 1.7.x-dev reports this problem in your code:

```php
 ------ --------------------------------------------------------------------------------------------------------
  Line   rules/DowngradePhp80/NodeAnalyzer/NamedToUnnamedArgs.php
 ------ --------------------------------------------------------------------------------------------------------
  97     Class PHPStan\Reflection\Php\PhpParameterReflection constructor invoked with 3 parameters, 4 required.
  98     Parameter #1 $initializerExprTypeResolver of class PHPStan\Reflection\Php\PhpParameterReflection
         constructor expects PHPStan\Reflection\InitializerExprTypeResolver, ReflectionParameter given.
  99     Parameter #2 $reflection of class PHPStan\Reflection\Php\PhpParameterReflection constructor expects
         PHPStan\BetterReflection\Reflection\Adapter\ReflectionParameter, null given.
 ------ --------------------------------------------------------------------------------------------------------
```

Please note that PhpParameterReflection class constructor isn't covered by backward compatibility promise as per https://phpstan.org/developing-extensions/backward-compatibility-promise. When analysing Rector's sources with PHPStan, it would tell you about it thanks to custom rule. But you have that ignored: https://github.com/rectorphp/rector-src/blob/e88903f64e4075478882f15443cdffa7c16f3003/phpstan.neon#L366-L368

In this case you should implement `PHPStan\Reflection\ParameterReflection` by yourself (even if you just copy the current PhpParameterReflection class from 1.6.x) instead of using the class from PHPStan internals that can change at any moment.

**Comment by TomasVotruba** [comment]
Thanks for sharing. I'm trying to copy-paste and it's quite heavy work with big code chunks. It seems the  `PhpParameterReflection` parameter is changing quite often:
https://github.com/phpstan/phpstan-src/commits/1.7.x/src/Reflection/Php/PhpParameterReflection.php

We've taken this way to ensure the code is compatible with PHPStan. By copying we would make the rule happy, but we would miss all the class changes that our following code uses. Saying that, we'll updating constructor is easier for maintenance.

Is there some constant from PHPStan with version we can use to support both?

**Comment by TomasVotruba** [comment]
Related commit and file: https://github.com/phpstan/phpstan-src/commit/c8b3926f005d008178d6d8c62aaca0200a6359a2#diff-ce65c81a2653b1f53bc416082582e248f629d65c066440d9c4edc5005d16af32

**Comment by ondrejmirtes** [comment]
If you look at those changes they don't have anything to do with functionality. And there's very few of them - I scroll a bit and I'm already in 2018.

The point is - implement ParameterReflection in your own class. The interface is stable and you're not going to need to change it at all.

**Comment by TomasVotruba** [comment]
This change seems important and we would have to explore what exactly it does and why it changed: 
https://github.com/phpstan/phpstan-src/commit/c8b3926f005d008178d6d8c62aaca0200a6359a2#diff-ce65c81a2653b1f53bc416082582e248f629d65c066440d9c4edc5005d16af32R105

With own class this would be missed and discovered much later by unrelated bug. 
If there is a service to resolve type from parameter, then it would make sense to implement own interface.

**Comment by samsonasik** [comment]
resolved at https://github.com/rectorphp/rector-src/pull/2336
