### ISSUE TITLE
 The "--set" option does not exist.

### ISSUE THREAD

**Issue by Dragon321123** [rectorphp/rector#7162]
I'm trying to move from the library to phpexcel on phpspreadsheet.
`vendor/bin/rector process /src/ --set phpexcel-to-phpspreadsheet`
Gives an error message 'The "--set" option does not exist.'
I understood that you turned off the option "--set".
But I did not find which option should be added in
` $rectorConfig->sets([
        SetList::CODE_QUALITY
  ]);`

**Comment by samsonasik** [comment]
You can define:

```php
use Rector\PHPOffice\Set\PHPOfficeSetList;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        PHPOfficeSetList::PHPEXCEL_TO_PHPSPREADSHEET
    ]);
};
```

ref https://github.com/rectorphp/rector-phpoffice#use-sets

**Comment by TomasVotruba** [comment]
Hi, try to type hint `SetList` in the `rector.php`. It will show you all available classes.

![Peek 2022-05-12 19-38](https://user-images.githubusercontent.com/924196/168135647-109a74bd-2209-48c8-a9a5-29f889047ee6.gif)

**Comment by linaori** [comment]
I'm running into the same issue. I've got that specific config in rector.php:
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\PHPOffice\Set\PHPOfficeSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        PHPOfficeSetList::PHPEXCEL_TO_PHPSPREADSHEET
    ]);
};
```

When I then run `vendor/rector/rector/bin/rector process src --set phpexcel-to-phpspreadsheet` I get: The "--set" option does not exist. This is a fresh rector install, and I've done the init. 

In addition to that it seems to process rules I don't want it to process. I _only_ want it to process the phpexcel -> spreadsheet changes, but it's touching things like unused arguments. Yes I need to fix them, but another time.

**Comment by samsonasik** [comment]
Unused argument removal is depends on version you're using, which on purpose due to different version usage, see https://github.com/rectorphp/rector/issues/7072

**Comment by linaori** [comment]
Different guides saying different things, joy :(

Any idea how to limit it to just that one list? It's making thousands of changes I did not configure.

Example
```
Applied rules:
 * AddRemovedDefaultValuesRector (https://github.com/PHPOffice/PhpSpreadsheet/commit/033a4bdad56340795a5bf7ec3c8a2fde005cda24 https://github.com/PHPOffice/PhpSpreadsheet/blob/master/docs/topics/migration-from-PHPExcel.md#removed-default-values)
 * ChangePdfWriterRector (https://github.com/PHPOffice/PhpSpreadsheet/blob/master/docs/topics/migration-from-PHPExcel.md#writing-pdf)
 * RemoveExtraParametersRector (https://www.reddit.com/r/PHP/comments/a1ie7g/is_there_a_linter_for_argumentcounterror_for_php/)
```

**Comment by linaori** [comment]
I came here following directions from the spreadsheet repository, I don't think I've found any guides that reference it incorrectly, just differently:
https://github.com/PHPOffice/PhpSpreadsheet/issues/1445
https://phpspreadsheet.readthedocs.io/en/latest/topics/migration-from-PHPExcel/

**Comment by TomasVotruba** [comment]
@linaori Thanks!
I've send update PR and updated the issue: https://github.com/PHPOffice/PhpSpreadsheet/pull/2861/files

**Comment by TomasVotruba** [comment]
@linaori You've done correct way already: https://github.com/rectorphp/rector/issues/7162#issuecomment-1142098309
Only the sets that you include in the config are run. I can see just 1 set and it's correct one.

The set is group of rules. If you want to run only 1 rule from the set, you can cherry pick them manually from the set:
https://github.com/rectorphp/rector-phpoffice/blob/e00fa9187605c28af79a0ac6c4b13080363ed24e/config/sets/phpexcel-to-phpspreadsheet.php#L30-L306

**Comment by linaori** [comment]
Oh, a bit odd that this specific set is doing more than. Would it make sense to reduce this to the bare minimum required for the migration? Not arguing that these changes aren't good, but if I run this over my code-base I get thousands of changes which _will_ break things 😅 

Thanks for the pointers, I'll be cherry picking the rules and will try again!

**Comment by samsonasik** [comment]
You can increase timeout seconds with something like this:

```php
$rectorConfig->parallel(200);
```

for very large codebase.

**Comment by linaori** [comment]
Here's an example where I run in a directory where I don't have a single reference to PHPExcel for example:
```
1) src/Domain/Stock/Reservation/RevokeStockReservationHandler.php:118

    ---------- begin diff ----------
@@ @@

     private static function logInfo($message, $context = []): void
     {
-        Logger::getLogger(static::class)->getMonolog()->info($message, $context);
+        Logger::getLogger()->getMonolog()->info($message, $context);
     }
 }
    ----------- end diff -----------

Applied rules:
 * AddRemovedDefaultValuesRector (https://github.com/PHPOffice/PhpSpreadsheet/commit/033a4bdad56340795a5bf7ec3c8a2fde005cda24 https://github.com/PHPOffice/PhpSpreadsheet/blob/master/docs/topics/migration-from-PHPExcel.md#removed-default-values)
 * ChangePdfWriterRector (https://github.com/PHPOffice/PhpSpreadsheet/blob/master/docs/topics/migration-from-PHPExcel.md#writing-pdf)
 * RemoveExtraParametersRector (https://www.reddit.com/r/PHP/comments/a1ie7g/is_there_a_linter_for_argumentcounterror_for_php/)
```

I'm also experiencing some serious memory issues, every time I run the script, it crashes my chrome and intellij 😂

**Comment by TomasVotruba** [comment]
That's probably job of `RemoveExtraParametersRector`. The only generic rule. It was meant to be to remove unneded parameters in a smart way, but I see it's making more problems.

Skip it in `->skip()` option.

> I'm also experiencing some serious memory issues, every time I run the script, it crashes my chrome and intellij joy

That could be caused by something like mpdf. Try to narrow refactoring to narrow scope.

**Comment by linaori** [comment]
Yeah I think I'm going to set up a limit to only process the files that contain a reference to PHPExcel, because this codebase is an absolute mess with embedded dependencies, thanks again for the pointers!

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-phpoffice/pull/18 to ensure show "Applied rules" only when changed for 

- AddRemovedDefaultValuesRector
- ChangePdfWriterRecto
