### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#7167]
# Bug Report

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renamenamespacerector

The example looks weird.

**Comment by TomasVotruba** [comment]
Seems like should be nested one more array in `getRuleDefinition()` config

**Comment by samsonasik** [comment]
@TomasVotruba other example seems invalid as well https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renamefunctionrector

it seems direct string key inside array instead of value object is changed to ConstFetch on doc generation.

**Comment by samsonasik** [comment]
I created PR https://github.com/symplify/symplify/pull/4072 for it.

**Comment by samsonasik** [comment]
Should be resolved in next 5.5 hours from now on weekly doc generation. I am closing it.
