### ISSUE TITLE
Better rector rule overview

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#7169]
# Feature Request

Hey,

It would be nice to have a better overview of all prebuilt rector rules. I am searching always serval minutes for the right one

Maybe filtering would help more like:

- Node Type
- What it does like (Adding, Removing, Changing)

Also make consequent names like parameter, argument => parameter or so.

**Comment by TomasVotruba** [comment]
Hi, sounds good. 
How would you create such content? Where we can put it?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Feel free to re-open with proposal.
