### ISSUE TITLE
Incorrect behavior of ChangeSwitchToMatchRector in fluent setter

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#7174]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

`ChangeSwitchToMatchRector` adds an invalid `default => $this` in a fluent setter scenario.

PS: excuse the code sample which does not respects current gender fluidity societal standards #legacycode :pray: 

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/a394abdb-61f0-40f3-82c7-5b5d53bb66e2

```php
<?php

final class Person
{
    /** 
     * @var int
     */
    private $gender;

    /**
     * @param string $gender
     *
     * @return Person
     */
    public function setGender($gender)
    {
        switch (strtolower($gender)) {
            case 'm':
                $this->gender = 0;
                break;
            case 'f':
                $this->gender = 1;
                break;
        }

        return $this;
    }
}
```

### Responsible rules

* `ChangeSwitchToMatchRector`

## Expected Behavior

I would except the rule to ignore this code sample (leave the switch as-is), as it cannot rewrite the exact same logic with a match.

As a temporary workaround, I've rewritten the code this way so this Rector does not change it : 

```php
$gender = strtolower($this->gender);
if ('m' === $gender) {
    $this->gender = 0;
} elseif ('f' === $gender) {
    $this->gender = 1;
}

return $this;
```

**Comment by samsonasik** [comment]
When no default value, it should not be processed actually, as it may cause:

```php
Fatal error: Uncaught UnhandledMatchError: Unhandled match case
```
