### ISSUE TITLE
Incorrect behavior of ChangeSwitchToMatchRector with variable with default value defined before switch

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#7175]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

If a variable is defined with a default value, and then a switch changes it for specific cases, then the default value is not added in the match().

PS: excuse the code sample which does not respects current gender fluidity societal standards #legacycode :pray: 

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1045857c-9208-4d6b-a813-7406dc51d833

```php
<?php

final class SomeClass
{
    /**
     * @array array{civility: string} $person
     */
    public function someFunction(array $person)
    {
        $sexe = '';
        switch ($person['civility']) {
            case 'Madame':
            case 'Mademoiselle':
                $sexe = 0;
                break;
            case 'Monsieur':
                $sexe = 1;
                break;
        }
    }
}
```

### Responsible rules

* `ChangeSwitchToMatchRector`

## Expected Behavior

There should be a `default => ''` branch to `match()`.

**Comment by samsonasik** [comment]
it seems it because of the variable is not used in next switch stmt, if it used, it got valid result https://getrector.org/demo/82d4c642-88eb-4f0d-9400-7a7e97009478
