### ISSUE TITLE
Incorrect behavior of ChangeReadOnlyVariableWithDefaultValueToConstantRector

### ISSUE THREAD

**Issue by ttomdewit** [rectorphp/rector#7178]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | Rector 0.13.0      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/0410034d-fb5b-4d17-bbcd-9c90959cc9e7

```php
<?php

final class SomethingToTest
{
    public function __construct(private string $name)
    {}
    
    public function getName(): string
    {
        return $this->name;
    }
}

final class DemoFile
{
    public function run()
    {
        // Given
        $name = 'Name';
        
        // When
        $object = new SomethingToTest($name);
        
        // Then
        assert($name === $object->getName());
    }
}
```

### Responsible rules

* `ChangeReadOnlyVariableWithDefaultValueToConstantRector`

## Expected Behavior

I'm not sure what can be expected here, but in this particular case the `// GIVEN` comment should not be moved with the new CONST value.

Thank you for all your hard work! ❤️

**Comment by ttomdewit** [comment]
Can I just say that http://getrector.org/demo is just perfect

**Comment by samsonasik** [comment]
The mirror comment is expected to avoid important comment is gone during transformation, if you have specific use case like that, you can skip it via ->skip() method, something like this:

```php
<?php

use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->skip([
        \Rector\Privatization\Rector\Class_\ChangeReadOnlyVariableWithDefaultValueToConstantRector::class => [
        	__DIR__ . '/tests'    
        ]
    ]);
};
```
