### ISSUE TITLE
uncaught missing method from reflection exception

### ISSUE THREAD

**Issue by hirenkeraliya** [rectorphp/rector#7181]
# Bug Report

| Subject        | Details                                                               |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.0                                                          |
| PHP version | v8.1                                                                  |
| Laravel version | v9.13.0                                                        |

After the upgrade `0.12.22` to `0.13.0` version, it will throw an error.

## Minimal PHP Code Causing Issue

I tried to reproduce this in the demo rector but it will not. And, I am using the https://spatie.be/docs/laravel-data/v1/introduction package.

Firstly I ran with the parallel and I got this error.
![Screenshot from 2022-05-24 11-21-32](https://user-images.githubusercontent.com/22992703/169975116-a2b85d09-6fbe-474b-8018-a154f2c09584.png)

Then I ran it without parallel and I got this error.
![Screenshot from 2022-05-24 12-55-30](https://user-images.githubusercontent.com/22992703/169975122-2c9656f5-fa7d-405c-b200-8823dbd1a9bc.png)

**Comment by samsonasik** [comment]
That's possibly due to phpstan 1.7.0, Could you try temporary pin phpstan to 1.6.9 in composer.json:

```json
    "phpstan/phpstan": "1.6.9"
```

and run composer update and verify if that works?
