### ISSUE TITLE
Incorrect behavior of RemoveUnreachableStatementRector

### ISSUE THREAD

**Issue by bonaslam** [rectorphp/rector#7185]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/29156fe2-c181-48fb-8405-5d264205a9c7

```php
<?php

final class DemoFile
{
    public function run()
    {
        return 5;

        // we never get here
        return 10;
    }
}
```

### Responsible rules

* `RemoveUnreachableStatementRector`

**Comment by samsonasik** [comment]
That is expected at the return is after return.
