### ISSUE TITLE
Concatenate more than 2 elements w/o parenthesis

### ISSUE THREAD

**Issue by claudiu-cristea** [rectorphp/rector#7188]
# Question

I want concatenate 3 elements:

```
new Node\Expr\BinaryOp\Concat(new Node\Expr\BinaryOp\Concat(a, b), c)
```

This ^ produces `(a . b) . c`, but I don’t want the parenthesis, I want simply: `a . b . c`. How to achieve that?

**Comment by TomasVotruba** [comment]
This is related with explicit priority: https://wiki.php.net/rfc/concatenation_precedence

Your code specifies different than default priority. `a . b . c` would probably look like:

```php
new Node\Expr\BinaryOp\Concat('a', new Node\Expr\BinaryOp\Concat(b, c))
```

**Comment by claudiu-cristea** [comment]
Your example produces `a . (b . c)`. I want no parenthesis, which is the left-to-right precedence

**Comment by claudiu-cristea** [comment]
Maybe Concat should take an array of parts (same as Encapsed) and only add parenthesis on a part if the part it's itself a Concat

**Comment by TomasVotruba** [comment]
That is dangerous, as priority is implicit and changes in different PHP versions.

If you really need it and you know the risk, you can implement your own printer:
https://github.com/nikic/PHP-Parser/blob/678ccbe0720549c51d30b76d094a117eac819e9e/lib/PhpParser/PrettyPrinter/Standard.php#L315-L317

**Comment by claudiu-cristea** [comment]
> That is dangerous, as priority is implicit and changes in different PHP versions

@TomasVotruba, this is new to me. I'm doing such concatenations since PHP 3 and never had any problem. The precedence was always from left to right, as is expected and as it works for other operators

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/issues/7188#issuecomment-1136918693

**Comment by claudiu-cristea** [comment]
@TomasVotruba, yes, I read https://wiki.php.net/rfc/concatenation_precedence but it's something different. It's about precedence of 2 different operators. On one hand plus or minus (+/-) combined with string concatenation (.). That makes total sense. But `$a . $b . $c` is like `1 + 2 + 3`. You don't need `(1 + 2) +3`, do you?

**Comment by TomasVotruba** [comment]
That's all I know about this. You'll have to try ask in php-parser or php-src
