### ISSUE TITLE
Add Yaml to annotations metadata Doctrine

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#719]
- https://github.com/symfony/symfony-docs/issues/9401

**Comment by TomasVotruba** [comment]
https://wildlyinaccurate.com/useful-doctrine-2-console-commands/

**Comment by TomasVotruba** [comment]
Not a priority ATM

**Comment by TomasVotruba** [comment]
Be sure to follow my Twitter accounts, we got it already :)

https://github.com/rectorphp/rector-doctrine/blob/main/docs/rector_rules_overview.md#yamltoattributedoctrinemappingrector

**Comment by vasilvestre** [comment]
> Be sure to follow my Twitter accounts, we got it already :)
> 
> https://github.com/rectorphp/rector-doctrine/blob/main/docs/rector_rules_overview.md#yamltoattributedoctrinemappingrector

I wasted so many hours doing it with the doctrine package then rector shoot!

I've tried the rector rule only to compare my work, it seems like Indexes are not supported and Rector does not respect my PHP version.

Example :

```
#[\Doctrine\ORM\Mapping\ManyToOne(targetEntity: \App\Doctrine\Entity\Sylius\ShippingCategory::class, joinColumn: ['name' => 'shipping_category_id', 'referencedColumName' => 'id'])]
```

Lead to `joinColumn`, I have to use two attributes in my application.

```
#[ORM\JoinColumn(name: 'shipping_category_id', referencedColumnName: 'id')]
#[ORM\ManyToOne(targetEntity: ShippingCategory::class)]
```

If you want me to create a reproducer I think it's possible.

**Comment by TomasVotruba** [comment]
Yes, please. Send a failing test fixture via PR to the rule. 
We'll look into it :+1:

**Comment by cbeyer** [comment]
@vasilvestre could you post your Rector config ?

**Comment by cbeyer** [comment]
Up @vasilvestre please🙏

**Comment by vasilvestre** [comment]
I do not have the configuration anymore, it was a one time run. I do not have time to send a fixture test lately sorry.

Important information : I use Symfony 4.4
