### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivatePropertyRector

### ISSUE THREAD

**Issue by annuh** [rectorphp/rector#7190]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

We are using the Symfony Validation component to validate entities. This results in some incorrect 'unused code' issues. I tried to skip this check via `@noRector` annotations, but it doesn't' seem to work. 

Adding `@noRector \Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector` as a class annotation **does work:** https://getrector.org/demo/ca869a5f-579f-4b98-86c0-a769080c75d5

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/ac527a0c-5ebb-4fea-a8d8-7ab2bfb4cb5e

```php
<?php

namespace App\Rector;

use Symfony\Component\Validator\Constraints as Assert;

class NoRectorDebug
{
    /**
     * @Assert\EqualTo(0)
     * @noRector
     */
    private int $varUsedByAssert;

    public function __construct()
    {
        /** @noRector */
        $this->varUsedByAssert = 1; // This will be checked by Symfony Validator compoent
    }
}
```

### Responsible rules

* `RemoveUnusedPrivatePropertyRector`

## Expected Behavior

I expected Rector to skip this check, because of the `@noRector` annotations.

**Comment by TomasVotruba** [comment]
Hi, the private property is checked on the class.

This ignore actually disables everything on that node, which is not what you want to do.
It's better to ignore specific rule in the config in `->skip()` call.
