### ISSUE TITLE
0.13.1: Bootstrap no longer working

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7191]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.1            |

## Minimal PHP Code Causing Issue

Reproduced in my module

https://github.com/samsonasik/ci4-album/pull/11

via Github action https://github.com/samsonasik/ci4-album/pull/11

## Expected Behaviour

It shoudl work as same with 0.13.0

**Comment by samsonasik** [comment]
I am looking at it, it seems `spl_autoload_register()` no longer triggered.

**Comment by samsonasik** [comment]
The following : 

```php
    // load prefixed or native class, e.g. for running tests
    if (strpos($class, 'RectorPrefix') === 0 || strpos($class, 'Rector\\') === 0) {
```

seems never met

**Comment by samsonasik** [comment]
it seems it because of : 

```php
if (defined('__RECTOR_RUNNING__')) {
    return;
}
```

always returned early.

**Comment by samsonasik** [comment]
The `BootstrapFilesIncluder` is too late to load

https://github.com/rectorphp/rector/blob/efe571aff55c79cd5dcbbc360e4b529afd4e5fcb/src/Autoloading/BootstrapFilesIncluder.php#L33

**Comment by samsonasik** [comment]
Moving check to `RectorContainerFactory` seems make stubs loaded, but custom bootstrap seems not applied 

- https://github.com/rectorphp/rector-src/pull/2382

**Comment by samsonasik** [comment]
Pinning back to PHPStan 1.7.1 still not working

- https://github.com/rectorphp/rector-src/pull/2383

ref https://github.com/samsonasik/ci4-album/runs/6631694665?check_suite_focus=true#step:10:22

**Comment by TomasVotruba** [comment]
This removal has probably caused this: https://github.com/rectorphp/rector-src/pull/2249

**Comment by samsonasik** [comment]
No, not this one, the custom bootstrap is different issue, which working ok on 0.13, which the dedicated class already applied.

**Comment by samsonasik** [comment]
@TomasVotruba step to reproduce locally:

```bash
git clone git@github.com:samsonasik/ci4-album.git
cd ci4-album && git checkout try-rector-dev-main
composer install
vendor/bin/rector
```

**Comment by TomasVotruba** [comment]
Closing as this is related with magical autoload.

The class should be included manually:
https://github.com/samsonasik/ci4-album/pull/12#issuecomment-1140054894

There is probably a regression from PHPStan 1.7.0 - https://github.com/phpstan/phpstan/releases/tag/1.7.0, "truly static regression" now leaves some classes.

**Comment by samsonasik** [comment]
@TomasVotruba I think 0.13.2 is needed for stub load fix.

**Comment by TomasVotruba** [comment]
Already tagged :)
