### ISSUE TITLE
Proper init file for PHP7.4 to 8.1 upgrade

### ISSUE THREAD

**Issue by zonehun** [rectorphp/rector#7192]
Hi, I like to check my legacy codebase to PHP 8.1 rules. I try to figure it out, but I don't know this is the config what I need.

```
<?php
declare(strict_type=1);

use Rector\Core\Configuration\Option;
use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {

    $parameter = $rectorConfig->parameters();

    $rectorConfig->paths([
        __DIR__.'/os'
    ]);

    $rectorConfig->phpVersion(PhpVersion::PHP_74);

    // define sets of rules
        $rectorConfig->sets([
            LevelSetList::UP_TO_PHP_81
        ]);

    $parameter->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);

};
?>
```

The code above do the PHP8.1 compatibility checking for me?

Thanks

**Comment by samsonasik** [comment]
The `LevelSetList::UP_TO_PHP_81` already cover php version, so no need to define php version, if you set php version 7.4 parameter after the setting like your example, you will get until php 7.4 feature.

If the legacy code is too large, you may need to narrow until php 7.x, eg

`LevelSetList::UP_TO_PHP_72`

and verify the change and increase level until up to php 8.1.

If you have a composer.json with php version in require section, you can init file with run:

```
vendor/bin/rector init
```

**Comment by zonehun** [comment]
> The `LevelSetList::UP_TO_PHP_81` already cover php version, so no need to define php version, if you set php version 7.4 parameter after the setting like your example, you will get until php 7.4 feature.

I like to comaptible with 8.1 but the code needs to be run on 7.4 as well (since the code base is large and I have to do the code upgrade process step by step meanwhile the code is working). So for example I do not want to change all strpos to str_contains.

In this case do I need this line?

```
$parameter->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_74);
```

**Comment by TomasVotruba** [comment]
If your project would crash with PHP 8.0 syntax, there should be "up to PHP 7.4" set.

**Comment by zonehun** [comment]
How can I define it exactly? Sorry, but I'm totally new to rector and despite watching some youtube videos and googling for such a scenario I couldn't find a specific simple example. 7.4 -> 8.1 but code can be run on 7.4 as well. 

I'm checking my code in docker where I installed rector and using it from command line with --dry-run (eg. vendor/bin/rector process os/base_test/calendarFuncs --dry-run). Then I rewrite my code based on rector findings.

Sorry for my confusion...

**Comment by TomasVotruba** [comment]
> . 7.4 -> 8.1 but code can be run on 7.4 as well.

That is not technically possible. `readonly` properties would fail on PHP 7.4 and some BC breaks would not work on PHP 8.0. That's why it's a major bump. 

In your case, use upgrade to the minimal version you support in `composer.json`. In `rector.php`:

```php
  $rectorConfig->sets([
            LevelSetList::UP_TO_PHP_74
        ]);
```

**Comment by zonehun** [comment]
I haven't got readonly properties. I'm not using composer.json. It is really a legacy code without OOP :) - the OOP part is small in this project so I can check that manually.

I like to pre-check that wether the code will be broken on PHP 8.1 or not. I like to use rector for this use case if possible.

**Comment by TomasVotruba** [comment]
I see :). Rector is an automated upgrade tool. It changes code to target version of your PHP or framework.

For analysing of future compatibility you can use: https://github.com/PHPCompatibility/PHPCompatibility

**Comment by zonehun** [comment]
Thank you for the clarification. 

PHPCompatibility is not fully supporting the 8.0 nor 8.1 yet. Rector is a great tool and I saw that it can help somehow for the code check as well with dry-run. I ran it and it produced a lot of seems-to-be-good recommendation.
