### ISSUE TITLE
Use phpstan extensions to have more precise type information

### ISSUE THREAD

**Issue by pscheit** [rectorphp/rector#7197]
# Feature Request

I don't know if i missed in the docs:
E.g. when we use webmozart/assert and there is usually a phpstan extension used (like phpstan-webmozart-assert) then the assertions will get see by phpstan and will work like normal assert(xxx) function calls.
 
I find myself ignoring lots of rector rules, when these assertions are used. For now I decided to go back to the classic assertions, but maybe there are more usecases where extensions would help rector to do better refactorings.

So far rector is calling phpstan to do the analysis, correct?

**Comment by TomasVotruba** [comment]
> So far rector is calling phpstan to do the analysis, correct?

Yes, that's the case 👍
I'm not I understand your proposal. Could you share some sample with code?

**Comment by pscheit** [comment]
Alright, i try to construct one:

```php
use Webmozart\Assert\Assert;

class MyRectorExample {
    public function addThumbnailMeta(stdClass $thumbnailMeta): void
    {
        Assert::integer($thumbnailMeta->width);
        Assert::integer($thumbnailMeta->height);
        Assert::string($thumbnailMeta->name);
        $this->thumbnailsSizes[$thumbnailMeta->name] = [$thumbnailMeta->width, $thumbnailMeta->height];
    }
}
```

now when I run rector or phpstan without the extension: https://github.com/phpstan/phpstan-webmozart-assert

phpstan/rector will see as types:

```php
$this->thumbnailsSizes[mixed] = [mixed, mixed]
```
right?

it does work with:
```php
use Webmozart\Assert\Assert;

class MyRectorExample {
    public function addThumbnailMeta(stdClass $thumbnailMeta): void
    {
        assert(is_integer($thumbnailMeta->width));
        assert(is_integer(($thumbnailMeta->height));
        assert(is_string($thumbnailMeta->name));
        $this->thumbnailsSizes[$thumbnailMeta->name] = [$thumbnailMeta->width, $thumbnailMeta->height];
    }
}
```

phpstan/rector sees: 
```php
$this->thumbnailsSizes[string] = [string, string]
```

depending on the rector rule i run, this might refactor a method, that is statically typed in my app (with webmozart/assert) but rector does not get it right

**Comment by pscheit** [comment]
using the extension with the first code example, does produce the exact same result as using the classical assert()s

**Comment by TomasVotruba** [comment]
This is how you can add them:
https://github.com/rectorphp/rector-src/commit/424697fdc4110ab40be313b701334afd1cefdec1

The default extension of PHPStan are not used, because sometimes they added dynamical code and crashed:
https://github.com/phpstan/phpstan-doctrine#configuration

This way you have the config under control and modify whatever you need.

**Comment by pscheit** [comment]
aaah! I see. This is what I didnt see in the docs. Thanks
