### ISSUE TITLE
Normalizer class not found error since upgrade

### ISSUE THREAD

**Issue by webmaster777** [rectorphp/rector#7199]
My CI pipeline failed on a dependabot upgrade between 0.13.2 and 0.13.3. This looks like a regression due to upgraded internal dependencies? Also, it looks like it is erroring while outputting an error, but not sure what the underlying error should be.

```
$ vendor/bin/rector --dry-run
Fatal error: Uncaught Error: Class 'Normalizer' not found in /builds/iuvenelis/scan-document-api/vendor/rector/rector/vendor/symfony/console/Helper/Helper.php:45
Stack trace:
#0 /builds/iuvenelis/scan-document-api/vendor/rector/rector/vendor/symfony/console/Style/SymfonyStyle.php(401): RectorPrefix20220531\Symfony\Component\Console\Helper\Helper::width(' ')
#1 /builds/iuvenelis/scan-document-api/vendor/rector/rector/vendor/symfony/console/Style/SymfonyStyle.php(64): RectorPrefix20220531\Symfony\Component\Console\Style\SymfonyStyle->createBlock(Array, 'ERROR', 'fg=white;bg=red', ' ', true, true)
#2 /builds/iuvenelis/scan-document-api/vendor/rector/rector/vendor/symfony/console/Style/SymfonyStyle.php(131): RectorPrefix20220531\Symfony\Component\Console\Style\SymfonyStyle->block(Array, 'ERROR', 'fg=white;bg=red', ' ', true)
#3 /builds/iuvenelis/scan-document-api/vendor/rector/rector/bin/rector.php(123): RectorPrefix20220531\Symfony\Component\Console\Style\SymfonyStyle->error('Class 'Normaliz...')
#4 /builds/iuvenelis/scan-do in /builds/iuvenelis/scan-document-api/vendor/rector/rector/vendor/symfony/console/Helper/Helper.php on line 45
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. 
The intl extension missing would right call. We removed the Symfony intl-polyfill, as part of cleanup of the polyfills we don't use.

It is used somewhere along these lines probably: https://github.com/rectorphp/rector/blob/5bd6035138ef9fbd7441fdba0dc37dc1a27ec5a5/vendor/symfony/console/Helper/Helper.php#L44-L50

**Comment by webmaster777** [comment]
Can confirm that the difference between CI and local dev environment is that the CI environment doesn't have the `intl` module, which is also not required by `composer.json`. I can workaround this by installing the intl module on the CI, but then it should be a requirement of this package too?

**Comment by webmaster777** [comment]
The `Normalizer` class is used in the `\RectorPrefix20220601\Symfony\Component\String\UnicodeString` class. I think this triggers the autoloading of the class somewhere in that code.

**Comment by TomasVotruba** [comment]
Agred, it is silent dependency of Symfony, that depends on polyfills. I think we can return it back for better DX

**Comment by TomasVotruba** [comment]
It should be deployed on this commit: https://github.com/rectorphp/rector/commit/f63cc42a7ab352766c37140821fa0b01feacac9d

Could you confirm?

**Comment by samsonasik** [comment]
You can try dev-main with:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by webmaster777** [comment]
Yes, the `main` version works (tested with 4d8282a)
