### ISSUE TITLE
Running Rector on CWD with space does not work

### ISSUE THREAD

**Issue by brunogaspar** [rectorphp/rector#7202]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.3  |

Running `vendor/bin/rector process` inside a project where the CWD contains a space, yields fatal errors.

Example `/users/bruno/my projects/some-project/`

## Minimal PHP Code Causing Issue

Just have a project where the CWD contains a space.

## Expected Behaviour

Some versions ago, it was working but i was not able to pinpoint which version started to cause this issue.

**Comment by samsonasik** [comment]
it seems due to parallel process, I tried it and it shows:

```
➜  with space vendor/bin/rector --dry-run
{"fatal_errors":["File \"/Users/samsonasik/www/with\" was not found"]}
                                                                                                                        
 [ERROR] Could not process some files, due to:                                                                          
         "Child process error: ".      
```

You can disable parallel for this use case for now:

```php
$rectorConfig->disableParallel();
```

**Comment by brunogaspar** [comment]
Thank you @samsonasik that seems a good workaround for now!
