### ISSUE TITLE
[PHP 8.0]`ClassPropertyAssignToConstructorPromotionRector`: Promoted parameters may only occur inside non-abstract constructors.

### ISSUE THREAD

**Issue by ghostwriter** [rectorphp/rector#7204]
# Bug Report

First, I'd like to thank @TomasVotruba, @samsonasik, and all other contributors for your time and all the work you've done on this project.

Thank you!

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `v0.12.x` & `v0.13.x`  |

> Promoted parameters may only occur inside non-abstract constructors.
> https://wiki.php.net/rfc/constructor_promotion

## Minimal PHP Code Causing Issue

```diff
 abstract class AbstractCommand extends Command
 {
-    protected DispatcherInterface $dispatcher;
-
-    protected SymfonyStyle $output;
-
-    public function __construct(DispatcherInterface $dispatcher, SymfonyStyle $output)
+    public function __construct(protected DispatcherInterface $dispatcher, protected SymfonyStyle $symfonyStyle)
     {
         parent::__construct(self::getDefaultName());
-        $this->output = $output;
-        $this->dispatcher = $dispatcher;
     }
}
```
## Expected Behaviour

Rector should skip it.

**Comment by samsonasik** [comment]
That's seems only when `__construct()` method doesn't has body (abstract method). For non-abstract method, that seems fine, could you show when it goes error with https://3v4l.org/ ?

**Comment by ghostwriter** [comment]
@samsonasik You're absolutely right, an oversight on my part.

For some reason, I'm getting this error message when this Rule runs. 

```
System error: "Class Symfony\Contracts\EventDispatcher\Event not      
         found."                                                                
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new
```

1. `symfony/event-dispatcher` is not used anywhere in the code base or even installed/required.
2. Running Rector with the "--debug" option does not output any report, just shows the same error message.

Thank you for the quick response, I'll try to debug this another time.

Have a great weekend!
