### ISSUE TITLE
RenameClassRector does not replace custom aliased classes

### ISSUE THREAD

**Issue by eigan** [rectorphp/rector#7205]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.4            |

When using `use SomeClass as SomeClassWithPostfix;` will RenameClassRector ignore replacing `SomeClass`.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/7e3b4a5e-2972-4bc1-8f17-9df2d4d98092

## Expected Behaviour

```diff
- use \Request as RequestFacade;
+ use \Illuminate\Support\Facades\Request as RequestFacade;
```

**Comment by samsonasik** [comment]
RenameClassRector is not replacing existing use statement with alias, it adds when possible, and use fqcn when conflict,  it will make too fragile as we dealing with docblock as well to verify with alias, so the change is expected.
