### ISSUE TITLE
Apply ReturnTypeDeclarationRector where really backwards-compatible

### ISSUE THREAD

**Issue by greg0ire** [rectorphp/rector#7207]
# Question

The documentation about that rule says it is applied where backwards compatible, yet it introduced BC-breaks for extending classes. Is there a way to apply it on methods that are final/part of final classes exclusively?

**Comment by TomasVotruba** [comment]
Hi, thanks for the question. 
Could you share a snippet of code of what you mean?

**Comment by greg0ire** [comment]
Sure, here is a demonstration: https://getrector.org/demo/50d28209-e2db-481f-88a1-6e8dddf77f67

Here, if the user extends the class but provides no return type, it will mean a crash: https://3v4l.org/CdAU8

**Comment by TomasVotruba** [comment]
I see. This rule scope assumes you own the code. E.g. when you upgrade your codebase to new Symfony 6 return types.

Do you own both classes but only one of them gets updated?

**Comment by greg0ire** [comment]
I don't own the second class, and I'm just assuming its existence. In `doctrine/orm`, many classes were not marked as final, and since it's so widely used, I'm trying to avoid any BC-breaks.

**Comment by greg0ire** [comment]
Basically I'm trying to do this: https://github.com/doctrine/dbal/pull/4986 , but on the ORM (or check that is fully done already).

**Comment by TomasVotruba** [comment]
Frameworks and OS libs are special use case. 
In that case the BC break is expected in every class and you should provide an upgrade config for the Doctrine users.

**Comment by TomasVotruba** [comment]
See Symfony 6 upgrade set for inspiration: https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony6/symfony-return-types.php

**Comment by TomasVotruba** [comment]
What return type would not be a BC break in this case? Maybe there is another rule you can use now :slightly_smiling_face:

**Comment by greg0ire** [comment]
> See Symfony 6 upgrade set for inspiration: https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony6/symfony-return-types.php

This seems to be about adding return types inside an application, based on the future return type of Symfony classes. Isn't that a different case?

> What return type would not be a BC break in this case? Maybe there is another rule you can use now slightly_smiling_face

If the method is private, or final, or belongs to a final class, then adding the return type is not a BC break.

**Comment by TomasVotruba** [comment]
> This seems to be about adding return types inside an application, based on the future return type of Symfony classes. Isn't that a different use case?

Yes. That's the config you should provide to Doctrine users to help with upgrade.

> If the method is private, or final, or belongs to a final class, then adding the return type is not a BC break.

I see. Could you share few couple from the Doctrine package that would comply with this and how they should be changed?

**Comment by greg0ire** [comment]
I remember doing that manually in the past, but luckily, I missed 2 spots, so here are 2 examples:

1. this method is final, it's OK to add a return type: https://github.com/doctrine/orm/blob/67d82cdf722af84b41152553be8bfb35dd025796/lib/Doctrine/ORM/Query/Filter/SQLFilter.php#L113
2. this method is private, it's OK to add a return type: https://github.com/doctrine/orm/blob/67d82cdf722af84b41152553be8bfb35dd025796/lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php#L455
