### ISSUE TITLE
RenameClassRector replaces wrong class via docblock

### ISSUE THREAD

**Issue by eigan** [rectorphp/rector#7209]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main  abaf44e           |

Sometimes RenameClassRector replaces the wrong class.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/62073155-09f5-4e8e-b7b5-94757ae5ea15

### Some notes
- Using php types: `protected Storage $storage;` gives expected behaviour _(no replacement)_. So it seems connected to docblocks.
- While the method `foo` seems unnecessary. Removing it in `dev-main` was not triggering the replacement bug. However, removing it in the demo seems to still trigger replacement. So it seems partially fixed between demo and dev-main(?)
- Removing the `\Log::` gives expected behaviour. So there is a connection here somehow.

## Expected Behaviour

No replacement.

**Comment by eigan** [comment]
Not giving you any time to rest @samsonasik 😉

**Comment by samsonasik** [comment]
that's seems expected by looking at demo page, feel free to create failing test case for it so we can verify.

demo page updated per sunday-wednesday-friday so it possibly different with local.

**Comment by eigan** [comment]
Could you clarify. I want to replace \Storage, rector replaces Storage inside Company namespace. Look at the import.

**Comment by samsonasik** [comment]
could you create failing test case PR for it? Thank you.
