### ISSUE TITLE
Tab character in file causes unexpected indention in docblock

### ISSUE THREAD

**Issue by eigan** [rectorphp/rector#7210]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main 07acf208            |

Some wild guess would be that rector assumes we use tab and then choose tabs for the docblock.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/3a219f06-7de7-419e-877c-5a20577d2629

## Expected Behaviour

The docblock uses space as the rest of the file and docblock uses.

**Comment by samsonasik** [comment]
that's known drawback https://github.com/rectorphp/rector#known-drawbacks . You can use coding standard tool to tidify that.

**Comment by TomasVotruba** [comment]
The tab is actually not at the start line, but inside the code. So it should be ignored.

I'm working on configurable solution in: https://github.com/rectorphp/rector-src/pull/2442
