### ISSUE TITLE
Generic return type is used as native [ReturnTypeDeclarationRector]

### ISSUE THREAD

**Issue by FrancoisPog** [rectorphp/rector#7213]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  v0.13.4              |
| Installed as | Composer dependency  |
 

The generic return type from phpdoc is used for the native return type, `\T` which does not exist.

## Minimal PHP Code Causing Issue

Demo: https://getrector.org/demo/5a20665a-b61f-4923-8b9a-aa9cb5c3a8ea

### Responsible rules

* `ReturnTypeDeclarationRector`

### Failing test

https://github.com/rectorphp/rector-src/compare/main...FrancoisPog:patch-1
https://github.com/rectorphp/rector-src/pull/2454

```diff
<?php

class AbstractController 
{
    private readonly UseCaseBusInterface $useCaseBus;

    /**
     * @template T
     *
     * @param UseCaseInterface<T> $useCase
     *
     * @return T
     */
-  protected function execute(UseCaseInterface $useCase): mixed
+  protected function execute(UseCaseInterface $useCase): \T
    {
        return $this->useCaseBus->execute($useCase);
    }
}
```

### N.B.

This similar example works correctly : https://getrector.org/demo/1faeadb8-431b-43d4-83e6-b74c1cd408bd;

```diff
<?php

interface UseCaseBusInterface
{
    /**
     * @template T
     *
     * @param UseCaseInterface<T> $useCase
     *
     * @return T
     */
    public function execute(UseCaseInterface $useCase): mixed; // no change
}
```

## Expected Behaviour

The return type should not be changed IMHO :thinking: 

## Thanks

By the way, thanks for this awesome tool, what a fantastic job ! :100:

**Comment by samsonasik** [comment]
Could you create failing test case PR for it? You can click "Create Test" button at the demo page

**Comment by FrancoisPog** [comment]
> Could you create failing test case PR for it? You can click "Create a Test" button at the demo page

It's done, tell me if I did something wrong or if there is something more I can do.

https://github.com/rectorphp/rector-src/compare/main...FrancoisPog:patch-1

**Comment by samsonasik** [comment]
You can click "Create pull request" button for it, better to rename fixture class with something like `SkipGeneric` with file name renamed to `skip_generic.php.inc`
