### ISSUE TITLE
Custom phpstan types are ignored

### ISSUE THREAD

**Issue by internalsystemerror** [rectorphp/rector#7215]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.4             |

When setting a custom phpstan type (e.g. setting a reusable array shape), this is ignored by rector.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/87f196eb-c31b-468a-9e52-f16491dee9df

In the above demo, a few issues present themselves, however it is my intention that only 1 is addressed by this particular github issue.

1) The `@return InputSpecification` is removed from `InputInterface`, which does not occur for me when these are in separate files, so I would think that issue can be ignored.
2) The `@var non-empty-string` annotation is replaced by `@var string`, but there is an open (and possibly already fixed) issue for that here: https://github.com/rectorphp/rector/issues/7214.
3) The `@return InputSpecification` is removed from `UriInput`. This is the issue I wish to address here.

## Expected Behaviour

I'm certain this will be a complicated issue to address/fix, so I'm unsure what the expected behaviour should be, however personally I would expect that the custom type is read and if valid, no change would be made.

**Comment by samsonasik** [comment]
it seems reproduced with `ArrayShapeFromConstantArrayReturnRector` https://getrector.org/demo/924b34e1-b126-474e-acd8-f55d7f5cc674

**Comment by samsonasik** [comment]
when on linear usage, it seems got ok https://getrector.org/demo/9c0af9c6-f3f3-464d-affb-b2960241eb61

**Comment by samsonasik** [comment]
Ok, the rule is actually `AddArrayReturnDocTypeRector` https://getrector.org/demo/e051d1b8-6590-425e-926a-b5315808eea7
