### ISSUE TITLE
Error in Php55\Rector\FuncCall\PregReplaceEModifierRector 

### ISSUE THREAD

**Issue by ThibaultAndreis** [rectorphp/rector#7221]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  v0.13.2              |

when you have a preg replace with the e modifier AND you use a variable inside the modifier string you got an error
last rule called `Rector\Php55\Rector\FuncCall\PregReplaceEModifierRector`

```
$test = 'become : ';
$string  ='string';
echo preg_replace("#([a-z]*)#e", "'".$test."' . strtoupper('\\1')", $string);
```

will throw an error

## Minimal PHP Code Causing Issue

https://getrector.org/demo/24318130-43ef-49d9-b5a1-a5ca7de4ea7d

## Expected Behaviour

It should ouput something like this

```
$test = 'become :  ';
$string  ='string';
echo preg_replace_callback('#([a-z]*)#', fn($matches) => $test . strtoupper($matches[1]), $string);
```
Sorry to add such a strange case, I'm working with some odd, old code

**Comment by samsonasik** [comment]
Could you create failing test case PR at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php55/Rector/FuncCall/PregReplaceEModifierRector/Fixture for it ? Thank you.
