### ISSUE TITLE
Rector 0.13 removes @var annotation

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#7222]
<img width="1074" alt="CleanShot 2022-06-09 at 13 45 17@2x" src="https://user-images.githubusercontent.com/995707/172839125-4dde0a6f-e7db-465c-8a7d-ffff36a6781a.png">

`ExtendendGenerator` should be kept in this context as it is more precise

cc @mvhirsch

**Comment by samsonasik** [comment]
could you provide what rule that cause it via https://getrector.org/demo or failing test case or reproducible repository with github action enabled? thank you.

**Comment by OskarStark** [comment]
I can give you access if you want

**Comment by samsonasik** [comment]
better to have minimum reproducible code

**Comment by samsonasik** [comment]
could you try rector dev-main, you can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by OskarStark** [comment]
Edit:
https://getrector.org/demo/1d8024b6-51e2-499b-8cc5-87e8d2116505

**Comment by OskarStark** [comment]
`dev-main` can only be used with `RectorConfig`?

**Comment by samsonasik** [comment]
Yes, but you can pin to before deprecation https://github.com/rectorphp/rector/commit/f188888181d3ba92beb061bc51c95033a9b04077

so, you may can try `dev-main#bfad5344a55687e9865ec8c589d4bb21df680f47`

**Comment by OskarStark** [comment]
With dev-main it does NOT remove the annotations, which is fine

**Comment by samsonasik** [comment]
thank you for verify 👍 , I am closing it then ;)
