### ISSUE TITLE
Don't add parentheses to nested short-hand ternary / Elvis operators ($a ?: $b ?: $c)

### ISSUE THREAD

**Issue by IMSoP** [rectorphp/rector#7223]
# Feature Request

Although it's sort of the same operator as the notoriously wrongly-associative ternary operator, the `?:` ("Elvis") operator can safely be chained without parentheses.

For instance, regardless of whether you write `foo() ?: bar() ?: baz()` or `( foo() ?: bar() ) ?: baz()`  or `foo() ?: ( bar() ?: baz() )`  the chain will short-cut on the first non-empty value, just as it would with `||` See demo: https://3v4l.org/oDN1e

However, Rector's current output treats it as non-associative, so always adds extra parentheses. They're not *wrong*, so I can't really call this a bug; they're just rather *ugly*, so it would be nice not to have them.
 
## Minimal Example

See https://getrector.org/demo/4213d6ec-b3ae-4ab4-80e8-2ff388fcead2

```php
<?php

 function elvis()
 {
    $value = (foo() ? foo() : false)
        ? (foo() ? foo() : false)
        : true;
 }
```

### Responsible rules

* `TernaryToElvisRector`
* Any other rule that can generate Ternary nodes - I actually encountered this while writing a custom rule

## Current Output

```php
  function elvis()
  {
     $value = (foo() ?: false) ?: true;
  }
```

## Desired Output

```php
  function elvis()
  {
     $value = foo() ?: false ?: true;
  }
```

**Comment by IMSoP** [comment]
Two rather ugly ways this can be achieved in `BetterStandardPrinter` (not thoroughly tested):

1) Add a version of `pInfixOp` with a special case:

```
    protected function pInfixOp(string $class, \PhpParser\Node $leftNode, string $operatorString, \PhpParser\Node $rightNode) : string
    {
        list($precedence, $associativity) = $this->precedenceMap[$class];
        if ( $class === Ternary::class && $operatorString === ' ?: ' ) {
            $associativity = -1;
        }
        return $this->pPrec($leftNode, $precedence, $associativity, -1) . $operatorString . $this->pPrec($rightNode, $precedence, $associativity, 1);
    }
```

2) Implement the special-case directly in `pExpr_Ternary` (which already has an over-ride):

```
    protected function pExpr_Ternary(Ternary $ternary) : string
    {
        if ($ternary->if === null) {
            $precedence = $this->precedenceMap[Ternary::class][0];
            $associativity = -1;

            $pExprTernary = $this->pPrec($ternary->cond, $precedence, $associativity, -1)
                . ' ?: '
                . $this->pPrec($ternary->else, $precedence, $associativity, 1);
        }
        else {
             $pExprTernary = parent::pExpr_Ternary($ternary);
        }

        $kind = $ternary->getAttribute(AttributeKey::KIND);
        if ($kind === 'wrapped_with_brackets') {
            return '(' . $pExprTernary . ')';
        }

        return $pExprTernary;
    }
```

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion. This should be handled directly in php-parser printer, as we tend to inherit its behavior.

**Comment by IMSoP** [comment]
Hi. :)

> This should be handled directly in php-parser printer, as we tend to inherit its behavior.

I wasn't sure, because there's already a lot in the `BetterStandardPrinter` class, and it's not obvious at a glance what makes something belong there, so I thought I'd ask here first. Shall I move my request to https://github.com/nikic/PHP-Parser/issues ?

> For me personally, explicit priority is better than implicit, because RFC can change it for specific cases.

I'm not sure what you mean by that. I can't think of any scenario where `($a ?: $b) ?: $c` would mean anything different from `$a ?: ($b ?: $c)` so it feels natural to write it without parentheses, just as I would `$a || $b || $c` or `$a ?? $b ?? $c`. But maybe there's a difference that I'm missing, or some reason this might change in future?

**Comment by TomasVotruba** [comment]
> Shall I move my request to [https://github.com/nikic/PHP-Parser/issues](https://github.com/nikic/PHP-Parser/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

First, you should try to print the same with this printer and with `Standard`. Test case here and there will also help to isolate the case.

> I'm not sure what you mean by that. 

E.g. this RFC https://wiki.php.net/rfc/concatenation_precedence

**Comment by IMSoP** [comment]
> First, you should try to print the same with this printer and with Standard. Test case here and there will also help to isolate the case.

OK, I'll see if I can make a more directed test case. If I can, I'll include some other cases for comparison to make my suggestion clearer.

> E.g. this RFC changed default precedence https://wiki.php.net/rfc/concatenation_precedence

Right, but that's precedence between *different* operators; I'm only talking about associativity *within a single operator*. That RFC doesn't change the meaning of `$a . $b . $c` or `$a + $b + $c`, neither of which would be output with parentheses, because they would make no difference to the result. The same is true for the majority of operators, including `??`; I think `?:` is only different because it's treated as a "shorthand ternary" rather than a binary operator in its own right.

**Comment by TomasVotruba** [comment]
The idea is not about exact operator, but rather about change of order or priority in general. PHP is known to change order, make something more strict or cleanup of old ambiguous syntax:

* https://wiki.php.net/rfc/engine_warnings
* https://wiki.php.net/rfc/stricter_implicit_boolean_coercions

Using explicit priority makes the code future proof and saves from random error without breaking BC in the future.

**Comment by TomasVotruba** [comment]
To your topic, there is also RFC about change of this priority of exact ternary operator:

* https://wiki.php.net/rfc/ternary_associativity

**Comment by IMSoP** [comment]
Sorry to labour the point, but I think we're still not understanding each other well.

> To your topic, there is also RFC about change of this priority of exact ternary operator:

That is *not* the operator I am talking about, and I think that's part of the confusion here. The name "short-hand ternary operator" is an unfortunate one, because there is nothing "ternary" about `$a ?: $b`; instead, think of it as the "false-coalescing operator", like its younger sibling the "null-coalescing operator".

Another way to think of `?:` is as a version of `||` which returns the original value instead of casting to boolean. In fact, JavaScript's `||` operator does the same thing as PHP's `?:` operator. There is no ambiguity in `$a || $b || $c`, and so there is no ambiguity in `$a ?: $b ?: $c`.

The pretty-printer already has associativity rules for `||` and `??` which skip parentheses:

```
new BooleanOr(
	new BooleanOr(new Variable('a'), new Variable('b')),
	new Variable('c')
);
// rendered as $a || $b || $c

new Coalesce(
	new Variable('a'),
	new Coalesce(new Variable('b'), new Variable('c'))
);
// rendered as $a ?? $b ?? $c
```

But right now, there is no way to get the same rendering with `?:` even though it would be completely unambiguous:

```
return new Ternary(
	new Ternary(new Variable('a'), null, new Variable('b')),
	null,
	new Variable('c')
);
// rendered as ($a ?: $b) ?: $c

return new Ternary(
	new Variable('a'),
	null,
	new Ternary(new Variable('b'), null, new Variable('c'))
);
// rendered as $a ?: ($b ?: $c)
```
