### ISSUE TITLE
[CodeQuality] Add rule to move attributes under comment 

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#7225]
The attributes are part of code, while docblock is comment above them. The other order will crash.

This was addressed in PHP FIG Per coding style:
https://github.com/php-fig/per-coding-style/issues/8

And php-parser: https://github.com/nikic/PHP-Parser/issues/762

<br>

Looking at code sample, maybe we could deal with this mess with Rector rule :) 

```diff
-#[Attribute]
 /**
  * @property-read $name 
  */
+#[Attribute]
 class SomeClass
 {
 }
```

**Comment by samsonasik** [comment]
Stmts/Exprs that have `attrGroups`:

```php
\PhpParser\Internal\PrintableNewAnonClassNode;
\PhpParser\Node\Param;
\PhpParser\Node\Expr\ArrowFunction;
\PhpParser\Node\Expr\Closure;
\PhpParser\Node\Expr\ClassConst;
\PhpParser\Node\Expr\ClassLike;
\PhpParser\Node\Expr\ClassMethod;
\PhpParser\Node\Expr\EnumCase;
\PhpParser\Node\Expr\Function_;
\PhpParser\Node\Expr\Property;
```

it seems `PrintableNewAnonClassNode` is for internal `PhpParser`.

**Comment by TomasVotruba** [comment]
After some reasearch and experiment, it's clera the php-parser resolves these correctly, even if separated by comment:
https://github.com/rectorphp/rector-src/pull/2474#issuecomment-1190228993

So there is no need for such rule.
