### ISSUE TITLE
Broken migration config in RectorConfig blogpost

### ISSUE THREAD

**Issue by jtojnar** [rectorphp/rector#7228]
# Bug Report
In https://getrector.org/blog/new-in-rector-012-introducing-rector-config-with-autocomplete, `SetList::RectorConfig` should be `SetList::RECTOR_CONFIG`.

**Comment by TomasVotruba** [comment]
Thanks 👍
Could you send PR to update?

**Comment by jtojnar** [comment]
I was not able to find the source code repo for the blog.

**Comment by TomasVotruba** [comment]
Should be here: https://github.com/rectorphp/getrector.org/tree/main/data/blog/posts

**Comment by jtojnar** [comment]
Weird, even though the search on https://github.com/rectorphp is incremental, it only seems to do full word search so it shows nothing for “web”, I need to type “website”.
