### ISSUE TITLE
Incorrect behavior of CountOnNullRector

### ISSUE THREAD

**Issue by brondibur** [rectorphp/rector#7229]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See [https://getrector.org/demo/3be70b11-6e9a-45a4-b3f7-d46494ccf07e](https://getrector.org/demo/3be70b11-6e9a-45a4-b3f7-d46494ccf07e)

```php
<?php

final class DemoFile
{
    public function run()
    {
        $my_var= "abc";
        if (strlen("There is a condition that is true only sometimes") == rand(5, 50)) {
            $my_var= [1,2];
        }
        $count = count($my_var);
        if ($count) {
            echo $count . " items found";
        } else {
            echo "No items found";
        }
    }
}
```

### Responsible rules

* `CountOnNullRector`

## Observed Behaviour
```
-        $count = count($my_var);
+        $count = is_countable($my_var) ? count($my_var) : 0;
```

## What's going wrong
[Prior to PHP 8, if `count` was called with a parameter that wasn't an array, or an object that implemented the Countable interface, it would return 1.](https://www.php.net/manual/en/function.count.php#:~:text=Prior%20to%20PHP%208.0.0%2C%20if%20the%20parameter%20was%20neither%20an%20array%20nor%20an%20object%20that%20implements%20the%20Countable%20interface%2C%201%20would%20be%20returned%2C%20unless%20value%20was%20null%2C%20in%20which%20case%200%20would%20be%20returned)
This results in a change in the value of `$count` when `$my_var` it is a string:
```
Prior to PHP 8 (with no rector changes):
$count = 1

After PHP 8 (with no rector changes):
$count = Error

With rector changes:
$count = 0
```

## Expected Behavior
`$count` should be `1`, when `$my_var` it is a string

**Note**: I know that this is a PHP 7.1 rector, but since there is no new rector to fix this, I'm using this rector to report the bug.

Since the change by rector only takes into account arrays/Countables/null, if a non-Countable is passed, 0 will be returned now. This changes the behaviour/logic of legacy code. 

The solution/correct change would be:
```
-        $count = count($my_var);
+        $count = is_countable($my_var) ? count($my_var) : (is_null($my_var) ? 0 : 1);
```

**Comment by TomasVotruba** [comment]
From what I see, the main difference is this rule applies on PHP 7.1, but you're upgrade PHP 8. 

The later PHP 8 version must be used after the upgrade to PHP 7.1. Even if there is code in PHP 9 that handles count differently, this rule does not now about it now, it's outside its scope. We cannot backport new features, as it's not their scope and range of usage.

The way to upgrade is one minor version by another - with one Rector set after another:

* PHP 7.1 ↓
* PHP 7.2 ↓
* PHP 7.3
