### ISSUE TITLE
Incorrect behavior of StringClassNameToClassConstantRector

### ISSUE THREAD

**Issue by VincentLanglet** [rectorphp/rector#7234]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/8ba6c179-29cb-4f28-9b99-d73b3d744cf2

```php
<?php

final class DemoFile
{
    public function run()
    {
        return '\DateTime';
    }
}
```

### Responsible rules

* `StringClassNameToClassConstantRector`

## Expected Behavior

Prior to the change the string was `\DateTime`, now it's `DateTime`. I would expect to keep the same string, so
```
'\\' . DateTime::class
```
is an acceptable solution.

**Comment by TomasVotruba** [comment]
This behavior is correct, as these pre-slashes are omitted in expression like is_a, and upgrade to class is the goal.

What is your reason to keep the slash?

**Comment by VincentLanglet** [comment]
> What is your reason to keep the slash?

I'm coding a tool which are generating php code.
I sometime want to generate `\DateTime` string, which the slash (because no use was done in the generated file). Or check that the string generating is the class with the slash (to have specific behavior for specific classes).

I tried to run rector with
```
$rectorConfig->ruleWithConfiguration(
        StringClassNameToClassConstantRector::class,
        ['\DateTime']
    );
```
but it still change `'\DateTime'` to `DateTime::class`.

I need to use the config
```
$rectorConfig->ruleWithConfiguration(
        StringClassNameToClassConstantRector::class,
        ['DateTime']
    );
```
but this doesn't give me exactly what I want since I'd like rector to change
- `'DateTime'` to `DateTime::class`
- Do not touch `\DateTime`.

**Comment by TomasVotruba** [comment]
This is special case, as from PHP type point of view, these are same types.

In your case, use the skip option to avoid change in this file. 

Better solution would be to use php-parser nodes in your tool.
There you can use `new FullyQualified(DateTime::class)` that keeps the context of your value.

**Comment by TomasVotruba** [comment]
I mean the "skip()" method in `rector.php`, see https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md

**Comment by VincentLanglet** [comment]
Indeed
