### ISSUE TITLE
Incorrect behavior of `AddReturnTypeDeclarationRector`

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#7235]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/912bde23-17a2-40f9-a990-c9c23b490d30

```php
<?php

namespace Symfony\Component\Form;

interface DataTransformerInterface
{
    /**
     * @return mixed
     */
    public function transform();
}

final class MyDataTransformer implements DataTransformerInterface
{
    public function transform(): string
    {
        return 'foo';
    }
}
```

### Responsible rules

* `AddReturnTypeDeclarationRector`

## Expected Behavior

As my return type is more explicit, it should be kept. Same occurs for Symfony normalizers

**Comment by OskarStark** [comment]
any idea @samsonasik ?

**Comment by samsonasik** [comment]
AddReturnTypeDeclarationRector will add return type, not remove, so it possibly caused by different rule, could you narrow it down to the specific rule that cause it? Thank you.

**Comment by OskarStark** [comment]
But the rector demo is telling me that only this rule is executed/applied. Maybe it's buggy?

**Comment by samsonasik** [comment]
probably, feel free to provide a patch as well if you found something :), try narrow down sets half by half, reduce until specific rule.

**Comment by mvhirsch** [comment]
> try narrow down sets half by half, reduce until specific rule.

MVP: https://getrector.org/demo/40ba1f77-30bd-413f-97ed-33d2fe6b4189

It's still a problem with `AddReturnTypeDeclarationRector`. Debugging it shows, that `$classMethod->returnType === null` at this point https://github.com/rectorphp/rector/blob/0.13.5/rules/TypeDeclaration/Rector/ClassMethod/AddReturnTypeDeclarationRector.php#L113

Next it tries to read the type via PHPStans, but for reasons I still don't understand (as I'm not digging deep enough into `TypeMappers`) it return `null` on this line: https://github.com/rectorphp/rector/blob/0.13.5/rules/TypeDeclaration/Rector/ClassMethod/AddReturnTypeDeclarationRector.php#L119

After that, it changes the return type, resulting in a deletion of the set ReturnType. Looks like a bug to me, too.
