### ISSUE TITLE
ReadOnlyPropertyRector rule cause an error

### ISSUE THREAD

**Issue by koekaverna** [rectorphp/rector#7237]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.23             |

After adding `ReadOnlyPropertyRector` rule rector has an error. I'm using [redis ](https://pecl.php.net/get/redis) extension and it cause this error.

<details>
<summary>
Fatal error: Uncaught PHPStan\ShouldNotHappenException: Multiple variants - use selectFromArgs() instead. in phar:///builds/company/my-project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ParametersAcceptorSelector.php:45
</summary>
<code>
Stack trace:
#0 /builds/company/my-project/vendor/rector/rector/src/NodeManipulator/PropertyManipulator.php(332): PHPStan\Reflection\ParametersAcceptorSelector::selectSingle(Array)
#1 /builds/company/my-project/vendor/rector/rector/src/NodeManipulator/PropertyManipulator.php(315): Rector\Core\NodeManipulator\PropertyManipulator->isFoundByRefParam(Object(PhpParser\Node\Expr\MethodCall))
#2 /builds/company/my-project/vendor/rector/rector/src/NodeManipulator/PropertyManipulator.php(218): Rector\Core\NodeManipulator\PropertyManipulator->isChangeableContext(Object(PhpParser\Node\Expr\PropertyFetch))
#3 /builds/company/my-project/vendor/rector/rector/rules/Php81/Rector/Property/ReadOnlyPropertyRector.php(144): Rector\Core\NodeManipulator\PropertyManipulator->isPropertyChangeableExceptConstructor(Object(PhpParser\Node\Param))
#4 /builds/company/my-project/vendor/rector/rector/rules/Php81/Rector/Property/ReadOnlyPropertyRector.php(93): Rector\Php81\Rector\Property\ReadOnlyPropertyRector->refactorParam(Object(PhpParser\Node\Param))
#5 /builds/company/my-project/vendor/rector/rector/src/Rector/AbstractRector.php(207): Rector\Php81\Rector\Property\ReadOnlyPropertyRector->refactor(Object(PhpParser\Node\Param))
#6 /builds/company/my-project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Param))
#7 /builds/company/my-project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#8 /builds/company/my-project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#9 /builds/company/my-project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#10 /builds/company/my-project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#11 /builds/company/my-project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#12 /builds/company/my-project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#13 /builds/company/my-project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#14 /builds/company/my-project/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#15 /builds/company/my-project/vendor/rector/rector/src/Application/FileProcessor.php(61): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#16 /builds/company/my-project/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#17 /builds/company/my-project/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#18 /builds/company/my-project/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#19 /builds/company/my-project/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#20 /builds/company/my-project/vendor/rector/rector/src/Console/Command/ProcessCommand.php(129): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput))
#21 /builds/company/my-project/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#22 /builds/company/my-project/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220501\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#23 /builds/company/my-project/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220501\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#24 /builds/company/my-project/vendor/rector/rector/src/Console/ConsoleApplication.php(66): RectorPrefix20220501\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#25 /builds/company/my-project/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#26 /builds/company/my-project/vendor/rector/rector/bin/rector.php(57): RectorPrefix20220501\Symfony\Component\Console\Application->run()
#27 /builds/company/my-project/vendor/rector/rector/bin/rector(5): require_once('/builds/company/...')
#28 /builds/company/my-project/vendor/bin/rector(117): include('/builds/company/...')
#29 {main}
  thrown in phar:///builds/company/my-project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ParametersAcceptorSelector.php on line 45
</code>
</details>

## Minimal PHP Code Causing Issue
```php
final class RedisTokenManager
{
    public function __construct(
        private \Redis $redis,
        private int $ttl
    ) {
    }

    public function save(): void
    {
        $this->redis->set(
            'key',
            'value',
            $this->ttl
        );
    }
}
```

**Comment by samsonasik** [comment]
Rector is already version 0.13.5 now, could you try latest version or dev-main ? If the issue persist , could you create faling repository with github action enabled? Thank you.

**Comment by koekaverna** [comment]
> Rector is already version 0.13.5 now, could you try latest version or dev-main ? 

I did tested with 0.13.5 and dev-main. The same issue.
> If the issue persist , could you create faling repository with github action enabled? Thank you.

https://github.com/koekaverna/symfony-rector
https://github.com/koekaverna/symfony-rector/runs/6896075175?check_suite_focus=true

**Comment by samsonasik** [comment]
it seems reproduced at https://getrector.org/demo/4b9d3f15-f2f2-44cd-b34d-89d1aa7b1c04
