### ISSUE TITLE
Problem with `MyCLabsClassToEnumRector` or `MyCLabsMethodCallToEnumConstRector`

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#7240]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

https://getrector.org/demo/187f61e9-86df-47f6-a0c1-fa56bfea821f

This should be refactored to an enum, which works locally, but not in the demo. I want to showcase an example which makes problems.

Can you please help me to get the demo working?

## Minimal PHP Code Causing Issue

later

## Expected Behaviour

later

## Reproducer

https://github.com/datana-gmbh/reproducer-rector-7240

**Comment by OskarStark** [comment]
Ah maybe because `Enum` class is used but not known in this context. How can I add many classes with different namespaces in the rector demo?

**Comment by OskarStark** [comment]
Ok I got it working, but it is a bit confusing, because it removes the base `Enum` class, which is ok and not necessary for my example:

https://getrector.org/demo/9c83b576-2463-42f5-8ee4-9766888b63d0

The problem is, that `MyDemoFile` is not touched, while it should result in the following diff:

```diff
final class MyDemoFile
{
    public function male(): Gender
    {
-    	return Gender::MALE();
+    	return Gender::MALE;
    }
    
    public function maleAsString(): string
    {
-    	return Gender::MALE()->getValue();
+    	return Gender::MALE->value;
    }
}
```

Shouldn't this be the job of `\Rector\Php81\Rector\MethodCall\MyCLabsMethodCallToEnumConstRector::class`? This one is not applied in the demo 🤷‍♂️

**Comment by OskarStark** [comment]
cc @mvhirsch @silasjoisten

**Comment by TomasVotruba** [comment]
In this case there might be more co-related conditions that happen at once.
Could you create minimal reproducer repository on Github?

**Comment by OskarStark** [comment]
Hmm I guess the Problem could be that once the first Rector `MyCLabsClassToEnumRector` was done, the second one (MyCLabsMethodCallToEnumConstRector) does not know anymore about `MyClabs\Enum\Enum` namespace, as the extended class was removed by the first one.

I am not sure how a reproducer should show anything else than provided in the demo in https://github.com/rectorphp/rector/issues/7240#issuecomment-1157986268 🤷‍♂️

**Comment by TomasVotruba** [comment]
The goal of reproducer is to have verifiable content that is objectively failing the CI. Only then we can see what is minimal code that causes the bug and fix it.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by OskarStark** [comment]
Here you go @TomasVotruba https://github.com/datana-gmbh/reproducer-rector-7240/tree/master#reproducer-rector-7240

**Comment by OskarStark** [comment]
Did the reproducer help?

**Comment by TomasVotruba** [comment]
I didn't get to it yet. First step will be detect Github Action that fails on the repository. Then moving the reproducer to Rector tests here.

**Comment by OskarStark** [comment]
Shall I create a failing github action in the reproducer repo?

**Comment by TomasVotruba** [comment]
:+1: If you create reproducer test here, that would be even better.
