### ISSUE TITLE
Incorrect behavior of ConsoleExecuteReturnIntRector

### ISSUE THREAD

**Issue by Tygygygydyk** [rectorphp/rector#7242]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/abc0a212-c797-4e0c-94ec-3540347a0190

```php
<?php

final class DemoFile  extends Symfony\Component\Console\Command\Command
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        try {
            $this->service->foo();
            return self::SUCCESS;
        } catch (\Throwable $exception) {
            return self::FAILURE;
        }
    }
}
```

### Responsible rules

* `ConsoleExecuteReturnIntRector`

## Expected Behavior

Third `return` is not needed.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
It is resolved with rector/rector dev-main with combination with `\Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector`:

```diff
<?php

use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rule(Rector\Symfony\Rector\ClassMethod\ConsoleExecuteReturnIntRector::class);
+    $rectorConfig->rule(\Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector::class);
};
```

You can try latest `rector/rector:dev-main`:

```bash
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```
```
