### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector, RenameClassRector

### ISSUE THREAD

**Issue by tacman** [rectorphp/rector#7244]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/cf8dde9c-e93c-444b-974b-4906e04c2859

```php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\FooRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FooRepository::class)
 * @ApiResource()
 */
class Foo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}
```

### Responsible rules

* `AnnotationToAttributeRector`

* `RenameClassRector`

## Expected Behavior

Should convert to 

    #[ApiResource]

**Comment by tacman** [comment]
regarding the question "Where is the ApiResource configured in rector.php?" 

I don't know.  Does ApiResource (API Platform) have a separate rule for converting annotations?

**Comment by samsonasik** [comment]
You can configure it in your rector.php, ref https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#annotationtoattributerector

**Comment by tacman** [comment]
Can you reopen this please?  I don't think it works.  

It's working great for doctrine entities and symfony routes, but not for ApiPlatform annotations.

**Comment by TomasVotruba** [comment]
:+1: 

It depends how ApiPlatform handles upgrade in general. I recall they have their own tool to handle upgrades. I recommend to ask there.

**Comment by tacman** [comment]
Routes and doctrine annotations -> attributes work.  But not ApiPlatform.

How do I configure it?

**Comment by TomasVotruba** [comment]
This would be way to go with Rector: https://github.com/rectorphp/rector/issues/7244#issuecomment-1158909359

But again, the ApiPlatform has own upgrade script, so this question belongs there.
