### ISSUE TITLE
MethodCallToMethodCall doesn't replace method call from current class

### ISSUE THREAD

**Issue by SelrahcD** [rectorphp/rector#7245]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.13.15        |

Hi!

I expected the MethodCallToMethodCall rector to be able to perform the following transformation but it doesn't work.
[Apparently](https://twitter.com/rectorphp/status/1538128594261708801) it's supposed to work.

```php
<?php

class AClass {

    public function run()
    {
        $this->methodFromAClass();
    }
}

?>
-----
<?php

class AClass
{
    public function __construct(
            private AnotherClass $anotherClass
    )
    {
    }

    public function run()
    {
        $this->anotherClass->methodFromAnotherClass();
    }
}

?>
```

## Minimal PHP Code Causing Issue

I made [a repo reproducing the issue](https://github.com/SelrahcD/rector-issue-with-MethodCallToMethodCall).

https://getrector.org/demo/b581db03-ec42-4a3e-b6a8-0a0966a95667

## Expected Behaviour

See above.

## Possible cause

I believe the issue comes from a [check made at the start of the refactor method](https://github.com/rectorphp/rector-src/blob/main/rules/Transform/Rector/MethodCall/MethodCallToMethodCallRector.php#L95-L97) ensuring only method calls made on property are replaced.

There is probably a good reason for this check. Maybe replacing a method in the class is not as "easy" at it seems at first sight.

**Comment by TomasVotruba** [comment]
The original method must exist in the code. Could you add namespace to ensure the autoloading is not conflicting global classes?

**Comment by SelrahcD** [comment]
Wooow, you're so fast.

I made some changes. Not sure if this is what you need. Let me know :)

**Comment by TomasVotruba** [comment]
I'm just around :)

Looks legit. Could you add the test case to `MethodCallToMethodCallRectorTest`, so we have covered here?

**Comment by SelrahcD** [comment]
I don't think I get what you mean. I don't have a fix yet, and not sure I can find one. I'm fairly new to Rector and I try to see how to use it with some kata-like exercises. 

I'm looking at the code and I believe the [check at the start of the rule](https://github.com/rectorphp/rector-src/blob/main/rules/Transform/Rector/MethodCall/MethodCallToMethodCallRector.php#L95-L97) (Shouldn't it be outside of the loop, btw ?) is needed because later, the rule [tries to get a variable from the expected property fetch](https://github.com/rectorphp/rector-src/blob/main/rules/Transform/Rector/MethodCall/MethodCallToMethodCallRector.php#L121).

Do you want me to create a PR with that test on the rector-src repo ?

**Comment by TomasVotruba** [comment]
> Do you want me to create a PR with that test on the rector-src repo ?

Yes, exactly :+1:  The `MethodCallToMethodCallRectorTest` is place to go.

**Comment by SelrahcD** [comment]
Done :)
