### ISSUE TITLE
Incorrect behavior of RemoveReferenceFromCallRector

### ISSUE THREAD

**Issue by balbertho** [rectorphp/rector#7247]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f93d497b-c4f0-4eff-897b-32a3f4df0137

```php
<?php

final class DemoFile
{
    public function displayVar() {
        $num = 12;
        echo troubleFunction(&$num);
        echo $this->troubleFunction(&$num);
    }

    public function troubleFunction(&$num) {
        return;
    }
}
```
The line " echo troubleFunction(&$num)" successfully changed to "echo troubleFunction($num)", but the line with "$this->" (i.e. "echo $this->troubleFunction(&$num)" failed to receive any changes.

### Responsible rules

* `RemoveReferenceFromCallRector`

## Expected Behavior

```php
<?php

final class DemoFile
{
    public function displayVar() {
        $num = 12;
        echo troubleFunction($num);
        echo $this->troubleFunction($num);
    }

    public function troubleFunction(&$num) {
        return;
    }
}
```

**Comment by samsonasik** [comment]
The current applied Node is FuncCall:

https://github.com/rectorphp/rector/blob/1e1549f2d5b504adbf3009c7583dfb308deaa9d5/rules/Php54/Rector/FuncCall/RemoveReferenceFromCallRector.php#L50

Could you try add `MethodCall` and `StaticCall` for it? You can add test to the following locations:

1. Code

https://github.com/rectorphp/rector-src/blob/f4a9b50187a20ff3573a3f2b55859545a06157a6/rules/Php54/Rector/FuncCall/RemoveReferenceFromCallRector.php#L58

2. Test Fixture
https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php54/Rector/FuncCall/RemoveReferenceFromCallRector/Fixture
