### ISSUE TITLE
Error on process: Invalid identifier name "[]"

### ISSUE THREAD

**Issue by ItsReddi** [rectorphp/rector#7249]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.5             |

Rector crashing with `Invalid identifier name "[]"`

## Minimal PHP Code Causing Issue
https://getrector.org/demo/0b747a8c-bbd8-43f1-bf96-ecb362ef2bc3
Works fine.

Code is seen in demo.

Non Demo:
![grafik](https://user-images.githubusercontent.com/3147888/174831472-9e9b834c-534f-4a13-b995-a9c1802ac009.png)

**Comment by samsonasik** [comment]
Could you try latest dev-main?

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

If the issue persist, please create reproducible repository with Github action running, thank you.

**Comment by TomasVotruba** [comment]
I'll release new Rector today to fix it :+1:

**Comment by samsonasik** [comment]
Thank you for verify. I am closing it then ;)
