### ISSUE TITLE
System error: "Scope not available on "PhpParser\Node\Expr\Array_" node with parent node of "" ...

### ISSUE THREAD

**Issue by mrunkel** [rectorphp/rector#7251]
I'm getting the same error message on three files. Here is one example:

     [ERROR] Could not process "src/Service/Hasher.php" file, due to:                                                       
             "System error: "Scope not available on "PhpParser\Node\Expr\Array_" node with parent node of "", but is        
             required by a refactorWithScope() method of                                                                    
             "Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector" rule. Fix scope refresh on       
             changed nodes first"                                                                                           
             Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
             line: 23

The class itself is pretty simple:

    <?php
    
    
    namespace App\Service;
    
    use Hashids\Hashids;
    
    class Hasher
    {
    
        private string $baseUrl;
    
        private Hashids $hasher;
    
        public function __construct(string $hashSalt, string $baseUrl = '', int $minHashLength = 4)
        {
            $this->hasher  = new Hashids($hashSalt, $minHashLength);
            $this->baseUrl = $baseUrl;
        }
    
        /**
         * Hash the passed ID and return the value
         *
         * @param int $id ID to be hashed
         *
         * @return string
         */
        public function encode(int $id): string
        {
            return $this->hasher->encode($id);
        }
    
        /**
         * Return an array of values for a passed hash
         *
         * @param string $hash hash to decode
         *
         * @return array
         */
        public function decode(string $hash): array
        {
            return $this->hasher->decode($hash);
        }
    
        /**
         * Return the first value for a particular hash
         *
         * @param string $hash hash to decode
         *
         * @return int|null
         */
        public function decodeOne(string $hash): ?int
        {
            $values = $this->decode($hash);
            if (count($values) === 0) {
                return null;
            }
    
            return $values[0];
        }
    
        /**
         * For a given ID and URL, return a formatted URL.
         * $url is optional, if not given, the baseUrl property will be used.
         * $url can also contain a %s to place the hash in the middle of the url
         * otherwise it is appended to the end.
         *
         * @param int $id ID to be hashed
         * @param string $url URL to be returned (optional)
         *
         * @return string
         */
    
        public function getUrl(int $id, string $url = ''): string
        {
            $hash = $this->encode($id);
            if (!$url) {
                $url = $this->baseUrl;
            }
            if (strpos($url, '%s') !== false) {
                return sprintf($url, $hash);
            }
    
            return $url . '$hash';
        }
    
        /**
         * @param string $baseUrl
         */
        public function setBaseUrl(string $baseUrl): void
        {
            $this->baseUrl = $baseUrl;
        }
    }

The rector version is Rector 0.13.6

And here is my rector.php file

    <?php
    
    declare(strict_types=1);
    
    use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
    use Rector\Config\RectorConfig;
    use Rector\Doctrine\Set\DoctrineSetList;
    use Rector\Set\ValueObject\LevelSetList;
    use Rector\Set\ValueObject\SetList;
    use Rector\Symfony\Set\SymfonySetList;
    
    return static function (RectorConfig $rectorConfig): void {
        $rectorConfig->paths([
            __DIR__ . '/src'
        ]);
    
        $rectorConfig->symfonyContainerXml(__DIR__ . '/var/cache/dev/App_KernelDevDebugContainer.xml');
    
        $rectorConfig->sets([
            LevelSetList::UP_TO_PHP_80,  // adjust based on project PHP version!
            SetList::DEAD_CODE,
            SetList::CODE_QUALITY,
            SymfonySetList::SYMFONY_54, // adjust based on project symfony version
            SymfonySetList::SYMFONY_CODE_QUALITY,
            SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,
            DoctrineSetList::DOCTRINE_CODE_QUALITY
        ]);
    
        $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);
    };

I ran rector with --debug and have attached the file [rector.txt](https://github.com/rectorphp/rector/files/8956247/rector.txt) with the output.

**Comment by samsonasik** [comment]
It seems reproduced with the 2 rules applied:

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {

    $rectorConfig->rules([
        \Rector\CodingStyle\Rector\FuncCall\CountArrayToEmptyArrayComparisonRector::class,
        \Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector::class,
    ]);

};
```

ref https://getrector.org/demo/0e681343-b6a2-4245-9b06-88c721ada1fc

I will look into it, for now, you can skip the `CallableThisArrayToAnonymousFunctionRector`:

```php
    $rectorConfig->skip([
        \Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector::class,
    ]);
```
