### ISSUE TITLE
`AddReturnTypeDeclaration` in `SymfonySetList::SYMFONY_60` removes my stricter method return type

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7253]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.6             |

I'm using the `SymfonySetList::SYMFONY_60`. But it kinda weakens my definition of the `FormTypeInterface::getParent()`.

Say I'm implementing that interface using this:

```php
// my type

public function getParent(): string
{
    return ChoiceType::class;
}
```

rector will replace the method signature by this:
```
public function getParent(): ?string
```

I explicitly return a string, not a `null|string`. 

It's related to https://github.com/rectorphp/rector/issues/7235 (already ignoring `MixedType` if I'm typing an explicit return type). 

## Minimal PHP Code Causing Issue

https://getrector.org/demo/77038c39-315d-4807-81b7-915116e935a5

## Expected Behaviour

Rector should skip it, as I'm already set my return type.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by mvhirsch** [comment]
Here we go: https://github.com/rectorphp/rector-src/pull/2557
