### ISSUE TITLE
support for big string numbers

### ISSUE THREAD

**Issue by dvdknaap** [rectorphp/rector#7255]
# Bug Report
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.6           |

In crypto they use big numbers like 1000000000 and higher, phpstan is converting them to string like "1_000_000_000"  which cause an error because it's parsed as an \PhpParser\Node\Scalar\LNumber $node and then thrown to ConstantIntegerType but this is expecting an int not an string

## Minimal PHP Code Causing Issue

Create an php file with the number 1000000000 in it

## Expected Behaviour

To fix it for me i made the following changes in:
`vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:211
```diff
            } else {
+                if ($node instanceof \PhpParser\Node\Scalar\LNumber) {
+                   if (!is_int($node->value)) {
+                        $node->value = (int)str_replace('_', '', $node->value);
+                   }
+              }
                $node->setAttribute(AttributeKey::SCOPE, $mutatingScope);
            }
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
Could you send failing test case so we have this covered?

**Comment by samsonasik** [comment]
Could you provide example code and config that caused it? It seems working ok on demo page https://getrector.org/demo/8f8cf56f-b7db-4fe0-9dd0-9478ab5c10ef

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. We're narrowing issues to keep focus on active and engaging contributor to keep project growing. Thank you for understanding.

Feel free to re-open with failing test case.
