### ISSUE TITLE
ArrayThisCallToThisMethodCallRector: System error: "Invalid value"

### ISSUE THREAD

**Issue by edsrzf** [rectorphp/rector#7256]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.6             |

The `ArrayThisCallToThisMethodCallRector` rule fails to run with a system error when a method with parameters is referenced.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/ce8623be-aeb7-45f4-9bf3-ed307cae7e85

This code is almost identical to the sample code for this rule, except for the `$arg` parameter to `giveMeMore`. If I remove the parameter, the error does not occur.

## Expected Behaviour

I expect no error and for the code to remain unmodified. (I have to admit I don't really understand the purpose of this rule, but I think that's a separate issue.)

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting and demo link. That should not happen.
What PHP version do you use?

**Comment by edsrzf** [comment]
PHP 8.1.6. `php --version` says:

```
PHP 8.1.6 (cli) (built: May 12 2022 23:30:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.6, Copyright (c), by Zend Technologies
```

**Comment by edsrzf** [comment]
Amazing, thanks for your help. Easily the fastest resolution I've seen in an open source project!

**Comment by TomasVotruba** [comment]
Thank you for clear reporting :clap:
