### ISSUE TITLE
Incorrect behavior of SplitGroupedUseImportsRector

### ISSUE THREAD

**Issue by xenon87** [rectorphp/rector#7257]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

Deuplicate semicolon is inserted at the end of last generated use statement. 

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/42d44e92-67f2-4e32-b8b3-77f13326ce0d

```php
<?php

    namespace App\Command;

    use App\Entity\Order;
    use Symfony\Component\Console\{Command\Command, Style\SymfonyStyle, Input\InputInterface, Output\OutputInterface};
    use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;

    class StatusControllerUpdateCommand
    {
    }
```

### Responsible rules

* `SplitGroupedUseImportsRector`

## Expected Behavior

The output should place a single semicolon on the end of the last namespace. 

```php
<?php

    namespace App\Command;

    use App\Entity\Order;
    use Symfony\Component\Console\Command\Command;
    use Symfony\Component\Console\Style\SymfonyStyle;
    use Symfony\Component\Console\Input\InputInterface;
    use Symfony\Component\Console\Output\OutputInterface;
    use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;

    class StatusControllerUpdateCommand
    {
    }
```

**Comment by samsonasik** [comment]
For missing semicolon, usually solvable by re-print the Node, eg:

```php
$node->setAttribute(Attributekey::ORIGINAL_NODE, null);
```

For additional semicolon, that possibly the php-parser bug. You can use cs tool for it

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
Closing per https://github.com/rectorphp/rector-src/pull/2580#issuecomment-1179546246
