### ISSUE TITLE
Rector makes whitespace changes even when no rules are run

### ISSUE THREAD

**Issue by edsrzf** [rectorphp/rector#7258]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.6             |

Rector sometimes modifies whitespace in files that are not affected by any rules.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f49f5775-2295-4708-8e8c-c4ac1c4b4123

There are no rules configured at all, but still a whitespace modification is made.

## Expected Behaviour

A configuration with no rules added should be a no-op. Rector should not touch code that is not affected by any rules. This behavior adds extra noise to diffs that should be preventable.

Ideally it should not change whitespace or formatting at all unless asked, but I recognize that this is a very difficult problem in general. This particular case seems solvable though.

**Comment by samsonasik** [comment]
That is expected right now, see e2e test for it:

https://github.com/rectorphp/rector-src/blob/0a644b148b39ee4adfde45519622b7cd9e4ef0d6/e2e/plain-views/src/view.php

https://github.com/rectorphp/rector-src/blob/0a644b148b39ee4adfde45519622b7cd9e4ef0d6/e2e/plain-views/expected-output.diff

That's possibly require many tweak in case want to be applied.

On other note, actually, having a space before any code can cause some issue, eg: buffer output, issue on session header, etc.

You can exclude the file from touched by rector via `$rectorConfig->skip()` in case the space before code is actually needed.

```php
$rectorConfig->skip([
   __DIR__ . '/views',
]);
```

**Comment by edsrzf** [comment]
That makes some sense. I probably chose a poor way to minimize this case.

In the actual code I'm dealing with, there is space in the middle of the file which Rector modifies. It's more like this: https://getrector.org/demo/39070d3f-84dd-41a2-a260-21e2d67f13bb

The comment seems to be relevant. The code is pretty weird, for sure; I won't defend it.

**Comment by samsonasik** [comment]
That's due to mixing with inline html, which php-parser limitation https://github.com/rectorphp/rector#how-to-apply-coding-standards .

You possibly need to:

- skip it
- or run cs tools againt it after run rector to it.

**Comment by TomasVotruba** [comment]
Could you create a minimal reproducible repository? There might be some rule that tries to make change and then file is reprinted.

**Comment by samsonasik** [comment]
@TomasVotruba there is already e2e test for it, it run without rule, and it remove space before code:

config: https://github.com/rectorphp/rector-src/blob/89a684f2b79f746464051f751e7291e5a2591ce2/e2e/plain-views/rector.php

file: https://github.com/rectorphp/rector-src/blob/89a684f2b79f746464051f751e7291e5a2591ce2/e2e/plain-views/src/view.php

expected output: https://github.com/rectorphp/rector-src/blob/89a684f2b79f746464051f751e7291e5a2591ce2/e2e/plain-views/expected-output.diff

**Comment by TomasVotruba** [comment]
@samsonasik I see.

@edsrzf In this case, we already cover with test and list it as known issue. The problem is the php-parser, that cannot handle all the edge cases of spacing properly, see: https://github.com/nikic/PHP-Parser/issues/344
HTML and PHP spacing in AST tree is hard :) 

In your case it would be easier to skip it as @samsonasik suggest or use cs tool to keep your expcting formatting.
