### ISSUE TITLE
Internal error in Rector\DeadCode\Rector\StmtsAwareInterface\RemoveJustPropertyFetchRector

### ISSUE THREAD

**Issue by kick-the-bucket** [rectorphp/rector#7263]
# Bug Report

| Subject        | Details  |
| :------------- | :-----------|
| Rector version | v0.13.5 |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/05195c1f-810d-4cc6-baf7-c9f130b49ebf

## Expected Behaviour

If the anonymous function is static - rector should skip it.
If the function is not static - variable can be inlined and `use` removed.
```php
<?php

final class DemoFile
{
    private SomeClass $someObj;

    public function run(array $array)
    {
        return array_map(function ($item) {
            return $this->someObj->someMethod($item);
        }, $array);
    }
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by TomasVotruba** [comment]
@samsonasik Thanks, miss cick

**Comment by kick-the-bucket** [comment]
At first I thought this is a phpstan bug, but writing a test-case there I could not reproduce the issue.
Must have something to do with the version of PhpParser used in here or the custom patches?

**Comment by kick-the-bucket** [comment]
With `rector-src#main` I'm getting an instance of `\PhpParser\Node\Expr\PropertyFetch` for the anonymous function use, but with `phpstan-src#1.8.x` I'm getting an instance of `\PhpParser\Node\Expr\Variable` for the same use

**Comment by kick-the-bucket** [comment]
Phpstan's `\PHPStan\Analyser\MutatingScope::enterAnonymousFunctionWithoutReflection` expects the use name to be a string, but `PropertyFetch::name` is an instance of `\PhpParser\Node\Identifier`

**Comment by kick-the-bucket** [comment]
Found a way not to crash phpstan and even fixed one of the test cases (skip usages in static anonymous functions), will try to fix the non-static one as well.
