### ISSUE TITLE
RenameVariableToMatchMethodCallReturnTypeRector produces breaking code with arrow function

### ISSUE THREAD

**Issue by marvinschroeder** [rectorphp/rector#7266]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.6             |

For context: we were in a Laravel project (v8).

We were using the `SetList::NAMING` set and this line:

```php
use App\Customer;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

$query = Customer::with(['parentUsers' => fn (BelongsToMany $query) => $query->hasContactPersonOriginNr()]);
```

was changed to this:

```php
use App\Customer;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

$builder = Customer::with(['parentUsers' => fn (BelongsToMany $query) => $builder->hasContactPersonOriginNr()]);
```

But the changed $query variable inside the arrow function should not change, because this breaks the code.
For context: the `$query->hasContactPersonOriginNr()` returns the `Illuminate\Database\Eloquent\Builder` class, so the name $builder is indeed correct.

## Minimal PHP Code Causing Issue

I cannot reproduce this error in the "demo" tool, because the Laravel classes were missing. 

## Expected Behaviour

For my understanding it should have changed the line to this:

```php
use App\Customer;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

$builder = Customer::with(['parentUsers' => fn (BelongsToMany $query) => $query->hasContactPersonOriginNr()]);
```

## Rector config

```php
$rectorConfig->sets([
  SetList::CODE_QUALITY,
  SetList::DEAD_CODE,
  SetList::EARLY_RETURN,
  SetList::UNWRAP_COMPAT,
  SetList::CODING_STYLE,
  SetList::NAMING,
  LevelSetList::UP_TO_PHP_74,
  LaravelLevelSetList::UP_TO_LARAVEL_80,
  PHPUnitLevelSetList::UP_TO_PHPUNIT_90,
]);
```

**Comment by samsonasik** [comment]
Could you create reproducible simple repository? Better with github action enabled to show the error. Thank you.

**Comment by marvinschroeder** [comment]
Here you go: https://github.com/marvinschroeder/rector-example
The action shows what rector wants to change.

**Comment by samsonasik** [comment]
it seems caused by : 

```
\Rector\Naming\Rector\Assign\RenameVariableToMatchMethodCallReturnTypeRector::class
```

Not sure how to reproduce it in minimal code yet. You can skip it for now:

```php
    $rectorConfig->skip([
        \Rector\Naming\Rector\Assign\RenameVariableToMatchMethodCallReturnTypeRector::class,
    ]);
```

**Comment by samsonasik** [comment]
Ok, I can reproduce it https://getrector.org/demo/51eb0eef-900a-4571-95a1-a6daa9a348bb
