### ISSUE TITLE
Rector playground to long URL

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#7270]
On https://getrector.org/demo when I have very long example and click "Create issue" or "Create test"
 I receive
```
Whoa there!
Your request URL is too long.
```

**Comment by TomasVotruba** [comment]
That is expected, as the URL is limited by GitHub.
Try to make the code-snippet example shorter. It is also needed to get minimal reproducer, not the whole 1:1 in your code base. Test must show only the broken part.
