### ISSUE TITLE
Invalid AnnotationToAttributeRector behaviour

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#7271]
https://getrector.org/demo/60757e9c-19af-4dd7-a443-f77bcca6ef80

Found when migrating Api Platform annotations.
The `put` key should be inside `itemOperations` but is one level up. Here I past pretty formatted version for attribute:
```php
#[ApiResource(
    shortName: 'MyResource', 
    collectionOperations: [
        'post' => [
            'denormalization_context' => [
                'groups' => [
                    'resource.field'
                ]
            ], 
            'normalization_context' => [
                'groups' => [
                    'resource.field'
                ]
            ]
        ]
    ],
    itemOperations: [
        'get' => [
            'denormalization_context' => [
                'groups' => [
                    'resource.field'
                ]
            ], 
            'normalization_context' => [
                'groups' => [
                    'resource.field'
                ]
            ]
        ]
    ],
    put: ['denormalization_context' => ['groups' => ['resource.field']], 'normalization_context' => ['groups' => ['resource.field']]])]
```

**Comment by TomasVotruba** [comment]
We'll need a minimal reproducer that causes it.

**Comment by javaDeveloperKid** [comment]
Hmm, it looks like in the annotation version the comma before `put` is on the separate line. When I move the comma to the previous line just after the closing curly brace and run Rector then the attribute looks fine.

**Comment by javaDeveloperKid** [comment]
> We'll need a minimal reproducer that causes it.

The reproducer is in the demo link.

**Comment by TomasVotruba** [comment]
That's not minimal reproducer, we'll need as small as ~10 lines long.

**Comment by javaDeveloperKid** [comment]
I've reported the bug. That's all I can do for now.

**Comment by TomasVotruba** [comment]
It's unclear what is the input as I stated. Closing for lack of information.

**Comment by javaDeveloperKid** [comment]
Ok, I can see that this project will not fix its bugs unless a reporter does not provide a reproducer.

**Comment by javaDeveloperKid** [comment]
Ok, I can see that this project will not fix its bugs until reporter provides a reproducer.
