### ISSUE TITLE
First-class callable rule is missing "..."

### ISSUE THREAD

**Issue by Spomky** [rectorphp/rector#7274]
# Bug Report

| Subject        | Details                           |
| :------------- | :-------------------------|
| Rector version | Rector 0.13.7             |

The first-class callable syntax rule [#2544](https://github.com/rectorphp/rector-src/pull/2544) does not convert the callable as it should be. The three dots `...` are missing.

## Minimal PHP Code Causing Issue

```php
new TwigFunction('app_seo_title', [$this, 'getTitle'], [
    'is_safe' => ['html'],
]),
```

```php
new TwigFunction('app_seo_title', $this->getTitle(), [
    'is_safe' => ['html'],
]),
```

## Expected Behaviour

```php
new TwigFunction('app_seo_title', $this->getTitle(...), [
    'is_safe' => ['html'],
]),
```

**Comment by samsonasik** [comment]
Could you create failing test case PR for it? Thank you.

**Comment by Spomky** [comment]
Hi @samsonasik,

Please find attached a simple example: [rector.zip](https://github.com/rectorphp/rector/files/9034841/rector.zip).
* Unzip the file,
* Run `composer install` (locked to ` 0.13.7`)
* And run `vendor/bin/rector process`

You will see that the class `App\SeoExtension` will be updated:

```sh
1 file with changes
===================

1) SeoExtension.php:11

    ---------- begin diff ----------
@@ @@
     public function getFunctions(): array
     {
         return [
-            new TwigFunction('app_seo_title', [$this, 'getTitle'], [
+            new TwigFunction('app_seo_title', $this->getTitle(), [
                 'is_safe' => ['html'],
             ]),
         ];
    ----------- end diff -----------

Applied rules:
 * MoveCurrentDateTimeDefaultInEntityToConstructorRector
 * RemoveRedundantDefaultClassAnnotationValuesRector
 * RemoveExtraParametersRector (https://www.reddit.com/r/PHP/comments/a1ie7g/is_there_a_linter_for_argumentcounterror_for_php/)
 * FirstClassCallableRector (https://php.watch/versions/8.1/first-class-callable-syntax)
 * ArgumentRemoverRector
 * RenamePropertyRector
 * WrapReturnRector
 * ServiceGetterToConstructorInjectionRector
 * ChangeMethodVisibilityRector


                                                                                                                        
 [OK] 1 file has been changed by Rector                                                                                 
                                            
```

But the correct modification at line 15 of `SeoExtension.php` is incorrect.
Note that if the line is changed into the expected behavior `new TwigFunction('app_seo_title', $this->getTitle(...), [`, Rector will revert the change back to the incorrect call

```sh
1 file with changes
===================

1) SeoExtension.php:11

    ---------- begin diff ----------
@@ @@
     public function getFunctions(): array
     {
         return [
-            new TwigFunction('app_seo_title', $this->getTitle(...), [
+            new TwigFunction('app_seo_title', $this->getTitle(), [
                 'is_safe' => ['html'],
             ]),
         ];
    ----------- end diff -----------

Applied rules:
 * MoveCurrentDateTimeDefaultInEntityToConstructorRector
 * RemoveRedundantDefaultClassAnnotationValuesRector
 * RemoveExtraParametersRector (https://www.reddit.com/r/PHP/comments/a1ie7g/is_there_a_linter_for_argumentcounterror_for_php/)
 * ArgumentRemoverRector
 * RenamePropertyRector
 * WrapReturnRector
 * ServiceGetterToConstructorInjectionRector
 * ChangeMethodVisibilityRector


                                                                                                                        
 [OK] 1 file has been changed by Rector                                                                                 
                                             
```

**Comment by Spomky** [comment]
> **Note** The issue seems to be related to the `RemoveExtraParametersRector` rule.
> That rule `RemoveExtraParametersRector` should distinguish between callbacks and real extra parameters.
> In my `rector.php` file,  setting `$config->services()->remove(RemoveExtraParametersRector::class);` solves the problem, but I actually have no reason to remove this rule.

**Comment by samsonasik** [comment]
Could you provide minimal code at https://getrector.org/demo ? Better to set only rules applied. You can collect possible latest rules applied with `--debug`

**Comment by Spomky** [comment]
> Could you provide minimal code at https://getrector.org/demo ?

Please see https://getrector.org/demo/4c0dc393-aad7-4b22-9c37-60b57f11a28f

> Better to set only rules applied.

I applied the only the rules I need i.e. for code migration to PHP8.1 and Symfony 6.

**Comment by samsonasik** [comment]
Ok, it seems reproduced with only RemoveExtraParametersRector https://getrector.org/demo/75494ac5-6917-4edd-8683-f0b5b05efe89

**Comment by Spomky** [comment]
Excellent!
What a fast bug fix. Many thanks.
