### ISSUE TITLE
Is it possible to get a report only on deprecated functions?

### ISSUE THREAD

**Issue by KrasilnikovKB** [rectorphp/rector#7275]
Hi!

We plan to up PHP-version, and we want to know all the places in the code with ONLY deprecated functions. not codestyle, not new style, etc..

it is possible ?

In the config, we specify through the SetList all versions of PHP from the current to the version we are interested in and want to see all deprecated-functions for each version

```
    $rectorConfig->sets([
        SetList::PHP_73,
        SetList::PHP_74,
    ]);
```

**Comment by TomasVotruba** [comment]
Hi, the PHP sets contains the full upgraded, including new DX features.
You'd have to cherry pick the rules from set yourself, to meet your needs.

What is the reason to avoid new features like promoted properties? They save so much time on writing and make code more robust.

**Comment by KrasilnikovKB** [comment]
Thanks for quik reply.

Transition to the new version should be smooth

Current code works on the old version, it may need to be refactored to migrate to the new version. and when this transition takes place, then we will apply all the new features
