### ISSUE TITLE
Ability to access first line, ability to access newlines

### ISSUE THREAD

**Issue by jissereitsma** [rectorphp/rector#7276]
As a learning exercise to know more about Rector, I've set myself some missions to fix with a custom rule. I'm bumping into issues here, have uploaded all my code for reference https://github.com/yireo/rector-php-extensions but need some help to get on the right path. Hopefully somebody is able to provide some pointers. (As I see it, I might have bumped into some limitations of `PhpParser`, not Rector.)

0) Mission "Add an empty line at the end of a PHP file": This was a success. I was able to create a rule for this (https://github.com/yireo/rector-php-extensions/blob/master/Rule/AddEmptyLineAtEndOfFile.php)  which cleanly adds a new node `PhpParser\Node\Stmt\Nop` at the end of a file.

1) Mission "Remove duplicate lines": This is a failure as I see it. Or at least with a rule. I've created a File Processor (https://github.com/yireo/rector-php-extensions/blob/master/FileProcessor/RemoveDuplicateNewLinesProcessor.php) that does this job though correctly. Unfortunately, when it is run in non-dry mode, it modifies the file but it is not reporting a diff, like with a rule. I've played around with returning a diff, but no improvement. And if I try to convert this to a rule, I bump into the issue that none of the nodes called via `refactor(Node $node)` are `Nop`. It almost seems as if the parser allows you to insert an `Nop` without issues (see mission 0) but while parsing the file, there are no newlines turned into nodes. The only I found to actually do something here, is to modify the file (`$this->file`) directly.

2) Mission "Guarantee that declare(strict_types=1) occurs on the first line": This is similar failure as mission 1. Again, I'm able to build a File Processor for this, which simply replaces lines in the actual file. But with a rule, the opening statement (`<?php`) on line 1 is not a node. And when inserting nodes, I'm unable to specify the line numbers for them.

Hopefully somebody is able to something smart here.

PS: I know that I could have created a simple shell script to fix this. But my goal is to learn more about Rector :)

**Comment by TomasVotruba** [comment]
Hi @jissereitsma ,

welcome to the club of the laziest PHP devs :)

<br>

I'll try to answer briefly to your questions, so you can continue digging :wink: 

<br>

0. + 1. While Rector can modify your code, it's main focus is not space/chars. This part is handled on the [printer level of php-parser](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/PrettyPrinter/Standard.php). 
 
These space are better handled by coding standard tools that operate on token level. I wrote more about it here:
https://tomasvotruba.com/blog/2018/10/25/why-ast-fixes-your-coding-standard-better-than-tokens/

In short, use ECS oneliner setup to deal with those: https://github.com/rectorphp/rector-src/blob/a70d0e5518260479d055a0d5a90e28e43cad58f7/ecs.php#L18

<br>

2. I see you're hooking into declare node: https://github.com/yireo/rector-php-extensions/blob/31ef665b134b324e9b93cc51acbfca36bb43e36d/Rule/DeclareStrictTypesOnOpeningLine.php#L36. That means you can only modify the node and bellow, e.g. change name and value to `declare_foo=100`.

To modify it's position in the nodes, you have to hook into parent node. That's how AST works. 
Rule of the thumb: "Don't touch your parents, only touch your children."

This one too would be probably handled by coding standard rule.

**Comment by jissereitsma** [comment]
Wow, this is really helpful. Halfway of working through the rules, I realized that Rector is less about coding styles and more about the functional workings of the code - but this is perfect to have confirmation on this! :) I've dived into PHP_CodeSniffer tokenization before, worked with PHP Reflection, and will add ECS and AST to my todo list :)

Thanks!

**Comment by jissereitsma** [comment]
Yes, I noticed the book. Definitely going to buy it!
