### ISSUE TITLE
Incorrect behavior of ChangeSwitchToMatchRector

### ISSUE THREAD

**Issue by chapa** [rectorphp/rector#7277]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/d7130268-f1fa-4ab0-842e-2c88390c1287

```php
<?php

function foo(string $var): void {
    switch ($var) {
        case 'hey':
            $var = 'oh';
            break;
        case 'foo':
        case 'bar':
            $var = "baz";
            break;
    }

    dump($var);
}
```

### Responsible rules

* `ChangeSwitchToMatchRector`

## Expected Behavior

Leave the code as is, or add a `default => $var` branch

## Additional notes

The behavior is correct (code is not modified) if `$var` is not used after the switch.

**Comment by samsonasik** [comment]
it seems due to case collection:

```php
        case 'foo':
        case 'bar':
```

it seems skipped without case collection https://getrector.org/demo/8c4defdb-8c95-4792-a469-495066d67e9d
