### ISSUE TITLE
Incorrect behavior of CountOnNullRector

### ISSUE THREAD

**Issue by tomas-telum** [rectorphp/rector#7283]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

[https://getrector.org/demo/9fe50c16-38ac-4a78-9dc8-194ad8089b91](https://getrector.org/demo/388fea77-b7a9-4a28-8122-2a2254e89103)

```php
<?php

function getData(): mixed { return ['meh']; }

/** array[] $array */
$array = [];
$array['blah'] = getData();
count($array['blah']);

/** array{blah: array} $array */
$array = [];
$array['blah'] = getData();
count($array['blah']);
```

### Responsible rules

* `CountOnNullRector`

## Expected Behavior

Rector should trust the type annotations and not change anything in these examples.

**Comment by samsonasik** [comment]
The  `@var` is overwritten with next assign `getData()` actually return typed declaration `mixed`, so it detected as `mixed`.

You can set `@var` after assigned:

```php
function getData(): mixed { return ['meh']; }

$array2 = [];
$array2['blah'] = getData();

/** @var array{blah: array} $array2 */
count($array2['blah']);
```

ref https://getrector.org/demo/ab3410e4-69ad-4248-b83e-765bbf481452

**Comment by samsonasik** [comment]
I am closing it as the solution provided above.
