### ISSUE TITLE
Should it be possible to add same ruleWithConfiguration with different configs?

### ISSUE THREAD

**Issue by MartinMystikJonas** [rectorphp/rector#7288]
# Question

I just encountered strange problem that rector did not made some expected changes. After some experimentation it seems that cause is multiple uses of ruleWithConfiguration (specifically RenameClassRector) with different sets parameters (result of cherry picking rules from existing sets). Only last parameters (replacement list) are used and previous are ignored/overwritten.

Is this expected behaviour? Some error on my side? Or did I just encountered bug?

**Comment by TomasVotruba** [comment]
Different configs should be merged. In the same config add the rule just once.

**Comment by MartinMystikJonas** [comment]
OK. I will combine all rules of same type to single one. But it would be nice to show warning when existing rule configuration is overwritten this way. I think this could happen to other users when they creates their customised rector config by combining parts of existing sets.

**Comment by TomasVotruba** [comment]
This is rather Symfony know-how, as we only use its DI.
You would not registering same controller twice with different parameters and same route :)

**Comment by MartinMystikJonas** [comment]
Well I was thinking about some safeguard on RectorConfig level. When ruleWithConfiguration is valled remember with what rule and if rule is already in use show warning. Or something like that. I can draft a PR with it if you like. It could be simple.

**Comment by TomasVotruba** [comment]
> I can draft a PR with it if you like. It could be simple.

That would be great :+1:

**Comment by MartinMystikJonas** [comment]
@TomasVotruba Drfated PR #2653

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector-src/pull/2653#issuecomment-1180907147
