### ISSUE TITLE
Possibly incorrect example for ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by yevsid** [rectorphp/rector#7293]
I came across [ClassPropertyAssignToConstructorPromotionRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#classpropertyassigntoconstructorpromotionrector), and an example shows changed public property to private promoted.

Is it a mistake in documentation, or it really works like this?

**Comment by TomasVotruba** [comment]
Thanks for checking. Seems like docs issue :) could you update it in the rule itself?

**Comment by samsonasik** [comment]
@yevsid you can create a PR with update this:

https://github.com/rectorphp/rector-src/blob/b1ae9a141523ee35af1f63aab39d945e8df03275/rules/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector.php#L73

and then run `composer docs` so doc updated.

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-src/pull/2711
