### ISSUE TITLE
Question: How to debug different results on Win 11 and WSL

### ISSUE THREAD

**Issue by arueckauer** [rectorphp/rector#7295]
When processing the same project under Windows 11 (PHP 8.1.8) and WSL Ubuntu 22.04 LTS (PHP 8.1.2), Rector spits out different results.

WSL Ubuntu result:

> [OK] Rector is done!

Windows 11 result:

> [ERROR] Could not process some files, due to:
>        "Child process error: ".
> 
> 
> 
> [ERROR] Could not process some files, due to:
>        "Child process error: ".
> 
> 
> 
> [ERROR] Could not process some files, due to:
>        "Child process error: ".
> 
> 
> 
> [ERROR] Could not process some files, due to:
>        "Child process error: ".

## Rector configuration

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . DIRECTORY_SEPARATOR . 'application',
    ]);

    $rectorConfig->parallel();

    $rectorConfig->skip([
        __DIR__ . '/application/classes/FOO_Service_SAP_REST.php',
        __DIR__ . '/application/classes/FOO_Service_SAP_SOAP_MATERIAL_IN_PLANTS.php',
        __DIR__ . '/application/classes/FOO_Service_SAP_SOAP_MATERIAL_META.php',
        __DIR__ . '/application/classes/System/HealthCheck/SapSoapCheckFactory.php',
    ]);

    // define sets of rules
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_74,
    ]);
};

```

## What is causing the error

I am not sure, what is causing the errors and would appreciate some help in finding out. With `--debug` Rector generates a huge output, from first sight I could not find a helpful information. What would be a good way to get to the root cause? Now I am not sure, if it is OS-specific, the PHP version or a rule that is misbehaving.

## Performance

The process command takes a very long time. 938 files take 5m53s on WSL and 3m04s on Win 11. There are a few large files (~3000 LOC). Is there something that could be improved on my side?

**Comment by samsonasik** [comment]
That's seems parallel process, could you try with disable parallel:

```php
$rectorConfig->disableParallel();
```

and see if it is working? 

I don't have windows11 at my local dev, so can't test the exact environment. 

We need the exact step by step to reproduce the issue, (the file, the config, the command that run), better to use Github repository with github action running.

You may can create reproducible repository with Github action with windows for it https://github.blog/changelog/2022-01-11-github-actions-jobs-running-on-windows-latest-are-now-running-on-windows-server-2022/

**Comment by arueckauer** [comment]
> How did you install Rector?

```bash
composer require rector/rector --dev
```


> That's seems parallel process, could you try with disable parallel ... and see if it is working?

Disabling parallel process seems to work, interesting.

Thank you both for you prompt responses. 🙏🏻

Is there also a way to get more information on the long running process? Besides running with `--debug` and manually viewing where it is taking long, is there another/better option?

**Comment by samsonasik** [comment]
`-vvv` should show the rules

**Comment by arueckauer** [comment]
`-vvv` did not give any more insight. To narrow it down, I believe I have to run each rule and/or file separately to see if it throws the same error. I will have a look at it, when I got more time on my hand. Closing this issue for now.

Thanks for your help so far. I appreciate it.
