### ISSUE TITLE
Rector freezes/cannot find process when StaticCallToFuncCallRector is added

### ISSUE THREAD

**Issue by MartinMystikJonas** [rectorphp/rector#7298]
# Bug Report

Rector version 

When I add this to Rector config:
```
$rectorConfig->ruleWithConfiguration(StaticCallToFuncCallRector::class, [
        new StaticCallToFuncCall('Metis\\Utils\\PhpType', 'describe', 'get_debug_type'),
    ]);
```

Without --debug it outputs:
```
 140/246 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  56%
In ProcessPool.php line 28:

  Process "lx8d551ldg" not found.  
```

With --debug it ends on:
```
[file] src/Metis/Schema/SchemaAnnotationParser.php
[rule] Rector\Transform\Rector\StaticCall\StaticCallToFuncCallRector
```
And freezes.

## Minimal PHP Code Causing Issue

Cannot reproduce it on rector demo. Maybe it is in conflict with another rule we use? I do not know how to debug it on local to get more detailed info.

## Expected Behaviour

Do changes without error.

**Comment by samsonasik** [comment]
You may need to narrow down the rules to see what rule that cause it, `-vvv` should help.

**Comment by MartinMystikJonas** [comment]
`-vvv` is more verbose than `--debug`?

It only happens when `StaticCallToFuncCallRector` is present bit maybe in combination with something else. I will try to narrow it down.

**Comment by MartinMystikJonas** [comment]
Ok weird enough. Today it does not happens anymore.
