### ISSUE TITLE
[PHP 8.0] Add inline mixed type rule

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#7301]
Since PHP 8.0, the mixed type can be easily inlined. Apart the parent contract method from interface/abstract class, this cannot be BC break, as type declaration accepts any type:

* RFC: https://wiki.php.net/rfc/mixed_type_v2

```diff
-/**
- * @param mixed $element
- */
-private function isRectorClass($element): bool
+private function isRectorClass(mixed $element): bool
 {
 }
```

**Comment by samsonasik** [comment]
use case to be skipped:

- has child with narrowed type: https://3v4l.org/B9vvP

**Comment by TomasVotruba** [comment]
I've found 2 cases, that needs check/coverage too. What do you think?

![Screenshot from 2023-12-06 13-20-37](https://github.com/rectorphp/rector/assets/924196/03153446-8d15-4f77-9b37-9523ae126380)


![Screenshot from 2023-12-06 13-21-18](https://github.com/rectorphp/rector/assets/924196/dcb98b59-e2c9-4e94-a00f-25d62c9e66d4)


@samsonasik Could you look at it?

**Comment by samsonasik** [comment]
Do you mean remove `@return mixed` ?

**Comment by TomasVotruba** [comment]
Yes yes, as it has no value and is in conflict with type declaration :+1:
