### ISSUE TITLE
Incorrect behavior of LongArrayToShortArrayRector

### ISSUE THREAD

**Issue by steamboatid** [rectorphp/rector#7304]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/af199ed5-37ac-4a1c-b1cd-88e53dc97650

```php
<?php
function a(){
return array(
'dependencies' => array( 'lodash', 'moment', 'react', 'react-dom', 'wc-components', 'wc-csv', 'wc-currency', 'wc-customer-effort-score', 'wc-date', 'wc-experimental', 'wc-explat', 'wc-navigation', 'wc-notices', 'wc-number', 'wc-settings', 'wc-store-data', 'wc-tracks', 'wp-a11y', 'wp-api-fetch', 'wp-components', 'wp-compose', 'wp-data', 'wp-data-controls', 'wp-date', 'wp-deprecated', 'wp-dom', 'wp-element', 'wp-hooks', 'wp-html-entities', 'wp-i18n', 'wp-keycodes', 'wp-notices', 'wp-plugins', 'wp-primitives', 'wp-url', 'wp-warning' ),
'version'      => '70f93d4745dfa01f57bfb086ea19da12',
);
}
```

### Responsible rules

* `LongArrayToShortArrayRector`

**Comment by samsonasik** [comment]
That's seems correct. You can use coding standard tool in case you want to tidy up the result.

**Comment by steamboatid** [comment]
> That's seems correct. You can use coding standard tool in case you want to tidy up the result.

i already use LongArrayToShortArrayRector at the **skip**
it seem rector ignore the **skip** parts?

**Comment by samsonasik** [comment]
That's strange, it seems correctly skipped with manual register the rule and then skip it https://getrector.org/demo/394e49c7-e88c-4eb2-95e3-94be4e5fc826

On other use case, it is working, register `LevelSetList` and then skip one of the rule https://getrector.org/demo/0b19b84b-d3c3-482a-9702-adf085c86a85

Could you create failing test case PR for it? You may create under https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by steamboatid** [comment]
> On other use case, it is working, register `LevelSetList` and then skip one of the rule https://getrector.org/demo/0b19b84b-d3c3-482a-9702-adf085c86a85

the input code not contain any array var

**Comment by samsonasik** [comment]
@steamboatid ok, it seems due to use statement:

```php
use Rector\Php81\Rector;
```

which make it not lookup different class as it read from the `Rector` suffix, so these config:

```php
		Rector\Php54\Rector\Array_\LongArrayToShortArrayRector::class,
```

will be read as:

```php
		Rector\Php81\Rector\Php54\Rector\Array_\LongArrayToShortArrayRector::class,
```

which invalid.

You can either make it fqcn:

```diff
	$rectorConfig->skip([
-		Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector::class,
+		\Rector\Php54\Rector\Array_\LongArrayToShortArrayRector::class,
-		Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector::class,
+		\Rector\Php54\Rector\Array_\LongArrayToShortArrayRector::class,
	]);
```

or ensure it is correctly not applied to use statmenet. I am closing it as it resolved with cleaned up the config 

https://getrector.org/demo/b77adc1e-ce84-4cd3-838c-854a0a2a6c2f

or

**Comment by steamboatid** [comment]
@samsonasik terima kasih (thank you)
