### ISSUE TITLE
[Symfony60] Incorrect behavior of AddReturnTypeDeclarationRector for method getRouteCollection

### ISSUE THREAD

**Issue by tomas-telum** [rectorphp/rector#7308]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/0f293984-3200-4061-83b5-9871b338fc02

```php
<?php

use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\Routing\RouteCollection;

class CachingRouter extends Router
{
    public function getRouteCollection(): RouteCollection
    {
        static $cache;
        if (!$cache) {
            $cache = parent::getRouteCollection();
        }

        return $cache;
    }
}
```

### Responsible rules

* `AddReturnTypeDeclarationRector`

## Expected Behavior

Return type should be `Symfony\Component\Routing\RouteCollection` instead of `Symfony\Component\Routing\RouteCollection\RouteCollection`

**Comment by TomasVotruba** [comment]
Could you share `parent::getRouteCollection();` signature from Symfony?

**Comment by tomas-telum** [comment]
@TomasVotruba The namespace in the config was just wrong
https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/Routing/RouteCollection.php

**Comment by TomasVotruba** [comment]
Thanks. I can't find the `getRouteCollection()` method there. Could you link exactly the method body?

**Comment by tomas-telum** [comment]
The method would be one of these:
* https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/Routing/RouterInterface.php#L34
* https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/Routing/Router.php#L180
* https://github.com/symfony/symfony/blob/6.0/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L65

**Comment by TomasVotruba** [comment]
Got it, thanks for the fix :+1:
