### ISSUE TITLE
[BUG] ExplicitMethodCallOverMagicGetSetRector class transform to unrelated method

### ISSUE THREAD

**Issue by hirenkeraliya** [rectorphp/rector#7309]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.8            |

In the Laravel, there is a Carbon package for the DateTime. when we try to do `now()->dayOfWeek` then `ExplicitMethodCallOverMagicGetSetRector` class changed it to the `now()->isDayOfWeek()`.

`now()->dayOfWeek` returns the day of the current week. And, `now()->isDayOfWeek()` is checked for the day and we need to pass the day of the week then it returns a boolean.

## Minimal PHP Code Causing Issue

Steps to reproduce the bug.

Step: 1 - Install the fresh Laravel.
Step: 2 - install the rector. And, add the `SetList::CODE_QUALITY` set.

I tried to reproduce it in your demo but it's not.

## Expected Behaviour

Rector should keep this.

**Comment by samsonasik** [comment]
probably already resolved at https://github.com/rectorphp/rector-src/pull/2667 ? Could you try 

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

and verify if that already resolved?

**Comment by hirenkeraliya** [comment]
This issue will be solved when I install the `dev-main`. @samsonasik When the new release will be out for [#2667](https://github.com/rectorphp/rector-src/pull/2667)?

**Comment by samsonasik** [comment]
Already released https://github.com/rectorphp/rector/releases/tag/0.13.9
