### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by trsteel88** [rectorphp/rector#7313]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.9             |

After updating, I'm seeing the following error:

```
$ ./vendor/bin/rector --dry-run
                                                                                                              
 [ERROR] "Symfony\Component\PropertyAccess\PropertyAccess" is not a valid method name in                      
         /usr/local/var/www/vendor/rector/rector/vendor/rector/rector-symfony/src/Set/..
         /../config/sets/symfony/symfony30.php (which is being imported from                                  
         "/usr/local/var/www/vendor/rector/rector/vendor/rector/rector-symfony/src/Set/.
         ./../config/sets/symfony/level/up-to-symfony-30.php").                                               
```

The site is running Symfony 6 and does include the \Rector\Symfony\Set\SymfonyLevelSetList::UP_TO_SYMFONY_60 set.

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

That seems like order bug in config: https://github.com/rectorphp/rector-symfony/blob/5e47d42f01d06f73e090c0c9377380c57697be79/config/sets/symfony/symfony30.php#L139-L143

**Comment by samsonasik** [comment]
@trsteel88 could you create a patch for it? Basically, you need to switch order 2nd arg to 1st arg on https://github.com/rectorphp/rector-symfony/blob/5e47d42f01d06f73e090c0c9377380c57697be79/config/sets/symfony/symfony30.php#L139-L143

**Comment by trsteel88** [comment]
@TomasVotruba @samsonasik done - https://github.com/rectorphp/rector-symfony/pull/209

**Comment by alexander-schranz** [comment]
Thx for fixing did run into the same in [sulu/skeleton](https://github.com/sulu/skeleton/runs/7496480260?check_suite_focus=true).

**Comment by trsteel88** [comment]
Will there be a release for this fix @TomasVotruba?

**Comment by TomasVotruba** [comment]
We usually do releases once a 1-2 weeks during holidays. We need time to rest and collect more bugfixes before release  :)

**Comment by trsteel88** [comment]
No worries, I just updated my composer requirement. Here it is if anyone else needs it:

```json
"rector/rector": "^0.13, !=0.13.9"
```
