### ISSUE TITLE
System error: "Node "...StaticCall" with parent of "...ArrayItem" is missing scope required for scope refresh.

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#7314]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.9             |

Error thrown:

```
 [ERROR] Could not process "layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/src/PluginInitializationConfiguration.php"
         file, due to:                                                                                                  
         "System error: "Node "PhpParser\Node\Expr\StaticCall" with parent of "PhpParser\Node\Expr\ArrayItem" is missing
         scope required for scope refresh."                                                                             
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 88   
```

Minimal PHP code:

```php
<?php

final class DemoFile
{
    /**
     * @return array<callable>
     */
    public function getCallables(): array
    {
        return [
            $this->opposite(...),
        ];
    }
    
    public function opposite(bool $value): bool
    {
        return !$value;
    }
}
```

Config:

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\DowngradeLevelSetList;

return static function (RectorConfig $rectorConfig): void {
    // A. run whole set
    $rectorConfig->sets([
        DowngradeLevelSetList::DOWN_TO_PHP_71,
    ]);
};
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/182231e7-5b1f-4df3-a74e-f6f733f1ebe0

## Expected Behaviour

Not throw an error

**Comment by leoloso** [comment]
When returning `callable` instead of `array<callable>` there is no problem:

https://getrector.org/demo/4195f90d-0dee-4fc4-8a22-8e4c33bc1325

**Comment by leoloso** [comment]
Replacing `$this->opposite(...)` with `[$this, 'opposite']` or `Closure::fromCallable([$this, 'opposite'])` also works well:

- https://getrector.org/demo/000a9d61-7fa8-4a49-93ab-76520113ea02
- https://getrector.org/demo/917e2d64-5a5b-4264-abc5-371f4f79eb48

So the issue seems to be with the first-class callable syntax `(...)`

**Comment by samsonasik** [comment]
it seems reproduced by `DowngradeFirstClassCallableSyntaxRector` https://getrector.org/demo/65ef846b-a970-4b92-8d14-021f9886e3c6
