### ISSUE TITLE
php crypt function involve Rector failure

### ISSUE THREAD

**Issue by frederic100** [rectorphp/rector#7316]
In the demo you can see it :

https://getrector.org/demo/3b56a300-6cd9-4177-821b-f16667cb071c

[report.txt](https://github.com/rectorphp/rector/files/9183092/report.txt)

**Comment by samsonasik** [comment]
It seems because you only pass 1 arg  to `crypt` function call,  while it requires 2 arg instead of 1, passing 2 args seems working ok https://getrector.org/demo/ad768a00-204d-4014-b737-79c9b417e5c3

ref for only 1 arg https://3v4l.org/tqiNo
ref for 2 args https://3v4l.org/WSCeP

**Comment by samsonasik** [comment]
I am closing it as the solution provided.
