### ISSUE TITLE
Incorrect behavior of InlineConstructorDefaultToPropertyRector: readonly property cannot have default value

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7318]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.13.9    |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/8edc487f-21bc-4226-afbf-6fc5ec8970a5

```php
<?php

declare(strict_types=1);

namespace Hi;

use JsonSerializable;

final class A implements JsonSerializable
{
    private readonly string $source;

    public function __construct()
    {
        $this->source = 'field';
    }
}
```

### Responsible rules

* `InlineConstructorDefaultToPropertyRector`

## Expected Behavior

Don't touch

**Comment by samsonasik** [comment]
@simPod could you try provide a patch for it? Get property and verify `$property->isReadonly()` should handle it.

**Comment by samsonasik** [comment]
resolved at https://github.com/rectorphp/rector-src/pull/2720
