### ISSUE TITLE
Incorrect behavior of InlineConstructorDefaultToPropertyRector: do not inline conditional values

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7319]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.13.9      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/a2abb0f1-85f0-437a-9ab0-d6d240928307

```php
<?php

final class A
{
    public bool $foo = false;

    /** @param string[] $tags */
    public function __construct(
        private readonly DateTimeImmutable|null $to = null
    ) {
        if ($this->to === null) {
            return;
        }

        $this->foo = true;
    }
}
```

### Responsible rules

* `InlineConstructorDefaultToPropertyRector`

## Expected Behavior

Do not touch the property since the value is set conditionally (not in every path).

**Comment by samsonasik** [comment]
@simPod could you try provide a patch for it? Using VisiblityManipulator should can handle it

https://github.com/rectorphp/rector-src/blob/ce22a82f851781d39fb89479800d15a98b7f453b/rules/Privatization/NodeManipulator/VisibilityManipulator.php#L137

**Comment by samsonasik** [comment]
Oh, it seems because of not inline assign, checked with if early, you can verify the stmts if it has non-Expression Stmt.

**Comment by simPod** [comment]
@samsonasik I decided not to contribute to rector some time ago. I had usually spent more than few minutes, rather up to few hours on previous PRs and it was not worth the time since I actually don't use rector.

Rector runs in my CI from time to time (scheduled runs) and it discovers those issues I report here as my bot updates rector automatically in the project. But I'm much faster with regex find&replace refactoring and don't work with legacy code bases anyway.  
So that's the explanation why I have no use for it. Even though it's a great product overall and is undoubtedly priceless for other teams, it's not worth my billable time as it adds no value in my environment. 

Also, I'm not very familiar with phpstan api so I prefer to dedicate my OSS time on projects I do know better or have a stake in.
