### ISSUE TITLE
Combine path and skip options in config

### ISSUE THREAD

**Issue by ottschoNaud** [rectorphp/rector#7328]
I have a PHP Symfony project with much vendor and other sub dir files which should not bee touched by rector. So I setup the path variable to only check files within a specific folder tree. That works fine.

    return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/plugins/*',
    ]);
But since this folder contains plugins which may have their own vendor & test directories, I want to skip these. Regarding the docs https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md skip with wildcards is possible, but these skip rules will be ignored totally.

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/plugins/*',
    ]);

    $rectorConfig->skip([
        __DIR__ . '/plugins/**/tests',
        __DIR__ . '/plugins/**/vendor',
    ]);
What could be wrong with my config? Or does rector not allow to combine these options? The documentation doesn't provide such a case.

**Comment by samsonasik** [comment]
You should can use double asterisk `**` for that, you can see this example:

https://github.com/rectorphp/rector-src/blob/ec291c4358636e29c026f2d42d575470cde25c76/rector.php#L63

so should be something like: 

```php
$rectorConfig->skip([
    __DIR__ . '/plugins/**/tests',
    __DIR__ . '/plugins/**/vendor',
]);

```

You can skip specific extension as well, eg

https://github.com/KejawenLab/SemartApiSkeleton/blob/bd568c615d80993f6d27c0f56d9955f41f353ca7/rector.php#L39

**Comment by ottschoNaud** [comment]
ty for the quick response! You are right, it should be double asterisk, but unfortunately it still process plugins/Test/vendor/ directory

**Comment by samsonasik** [comment]
The path seems case sensitive, as `Test` !== `test`. For more general, it should be something like this:

```php
$rectorConfig->paths([
    __DIR__ . '/plugins',
]);

$rectorConfig->skip([
    '**/Test/*',
    '**/test/*',
    '**/vendor/*',
]);
```

**Comment by ottschoNaud** [comment]
ah now I got it, it skips files not directories

plugins/**/vendor/**/* 

did it for me, thx for the push in the right direction!
