### ISSUE TITLE
Error on SymfonyLevelSetList (Symfony30 and above) on rector v0.13.9

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7332]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.9              |

Running `rector process` while using `SymfonyLevelSetList::UP_TO_SYMFONY_60` is broken:

```
[ERROR] "Symfony\Component\PropertyAccess\PropertyAccess" is not a valid method name in /home/meh/projects/datana/lama/vendor/rector/rector/vendor/rector/rector-symfony/src/Set/../../config/sets/symfony/symfony30.php (which is being imported from "/home/meh/projects/datana/lama/vendor/rector/rector/vendor/rector/rector-symfony/src/Set/../../config/sets/symfony/level/up-to-symfony-30.php")
```
Using a **previous version of rector like 0.13.8** fixes this problem.

## Minimal PHP Code Causing Issue

Just define SymfonyLevelSetList (any above 30) and run `rector process`.

```php
    $rectorConfig->sets([
        SymfonyLevelSetList::UP_TO_SYMFONY_60,
    ]);
```

## Expected Behaviour

See no error.

**Comment by mvhirsch** [comment]
Issue is already fixed in main branch: https://github.com/rectorphp/rector/commit/fad0b9018037a1b8859cb3892960560a9630290a#diff-b99023a837c5b45edf47722a62cc23ab715ff201bc4549a59744074d93ad958d

**Comment by samsonasik** [comment]
Rector 0.13.10 released https://github.com/rectorphp/rector/releases/tag/0.13.10
