### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#7333]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

See also:

- https://github.com/rectorphp/rector/issues/6927
- https://github.com/rectorphp/rector/discussions/6838
- https://github.com/rectorphp/rector-src/pull/1712

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/5095e79e-efa1-4df8-aeff-134a170c75b3

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Order;
use App\Repository\ReminderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReminderRepository::class)
 * @ORM\Table(name="reminders")
 */
class Reminder
{
    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="reminders")
     * @ORM\JoinColumn(name="for_order")
     */
    private Order $forOrder;

    public function __construct(Order $forOrder)
    {
        $this->forOrder = $forOrder;
    }
}
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

Entity property is not promoted in constructor breaking the Doctrine's mapping.

**Comment by samsonasik** [comment]
@Aerendir there is test case for it 

https://github.com/rectorphp/rector-src/blob/5ec4cff203f68d9578719b54ce3a145efb32bc79/rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/with_doctrine_annotations.php.inc

Could you point to the doctrine documentation that show that promoted property with `@ORM\Column` it is not allowed to avoid flip flop roll back? Thank you.

**Comment by Aerendir** [comment]
I don't know where it is in the documentation: I can say, anyway, that after doing it the `symfony console doctrine:schema:validate` command doesn't work anymore.

**Comment by samsonasik** [comment]
That's seems not everything need to be skipped, as for `Doctrine\ORM\Mapping\Id`, moving to `__construct()` is expected per original issue by @greg0ire:

- https://github.com/rectorphp/rector/issues/7198 

with handled at:

- https://github.com/rectorphp/rector-src/pull/2410

**Comment by Aerendir** [comment]
I'm sorry, but I've just retried and all works as expected: maybe yesterday night was too late and I applied too many rectors at the same time: something should have gone wrong due to other changes...

Thank you for your time and forgive me. I'm going to close this issue.
