### ISSUE TITLE
How to use CommandPropertyToAttributeRector

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#7336]
# Question
I've configured all sets of Symfony, but the rector `CommandPropertyToAttributeRector` is not applied.

I've digged in the rector configuration files and it seems the recotr is not referenced in set lists: am I missing something or it is really not used by sets?

Obviously, it is applied if I add it through `$rectorConfig->rule(\Rector\Symfony\Rector\Class_\CommandPropertyToAttributeRector::class);`.

**Comment by samsonasik** [comment]
Yes, that's seems not part of the set list, you can add it by `$ruleConfig->rule()` for it.

**Comment by TomasVotruba** [comment]
This rule is optional, as there are ~4 various preferences to handle command names.
To change your code knowingly, the rule must be registered manually.

**Comment by Aerendir** [comment]
I can see only this:

https://github.com/rectorphp/rector-symfony/blob/main/docs/rector_rules_overview.md#commandpropertytoattributerector

What am I missing?
