### ISSUE TITLE
Incorrect behavior of ClosureToArrowFunctionRector with comments

### ISSUE THREAD

**Issue by VincentLanglet** [rectorphp/rector#7337]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/3466d5cd-729b-4ad2-9f08-689d533d0b1c

```php
<?php

final class DemoFile
{
    public function run()
    {
        $vatServiceMock
             ->method('computeTTC')
             ->willReturnCallback(function (Store $store, float $price) {
                 // VAT 20% pour prendre HT
                 return round($price * 1.20, 2);
             });
    }
}
```

### Responsible rules

* `ClosureToArrowFunctionRector`

## Expected Behavior

To me the change 
```
->willReturnCallback(fn(Store $store, float $price) => // VAT 20% pour prendre HT
round($price * 1.20, 2));
```
is wrong and will fail a lot of linter (for indentation reason).

So I would say the code shouldn't be changed

**Comment by samsonasik** [comment]
That's keep on start comment on current line is on purpose to avoid make creating a tab spaces which will fail on compare, see PR:

- https://github.com/rectorphp/rector-src/pull/1677

on comment https://github.com/rectorphp/rector-src/pull/1677#discussion_r784938711

You need coding standard tool to tidify it.

**Comment by VincentLanglet** [comment]
I manually fixed to
```
->willReturnCallback(fn(Store $store, float $price) => round($price * 1.20, 2)); // VAT 20% pour prendre HT
```

To me the purpose of `fn` was to be single line.
But if it's made on purpose there is no issue.

**Comment by samsonasik** [comment]
Moving to next stmt will make other static analytic erorr, eg: psalm:

```php
function() {
    /** @psalm-suppress UndefinedFunction */
    return ff();
};
```

which to keep it working, should be kept as is to:

```php
fn() => /** @psalm-suppress UndefinedFunction */
ff();
```

like in PR https://github.com/rectorphp/rector-src/pull/1677
