### ISSUE TITLE
Rector is messing with the `default` case in in switch/case

### ISSUE THREAD

**Issue by VincentLanglet** [rectorphp/rector#7338]
# Bug Report

Done on the website 

## Minimal PHP Code Causing Issue

https://getrector.org/demo/298f3a61-2e01-47e9-baf4-46ca00a890f4

## Expected Behaviour

it shouldn't be changed or at least it should be 
```
case 1:
default:
                $a = 1;
                return $a;
```

**Comment by samsonasik** [comment]
it seems reproduced by using `ChangeSwitchToMatchRector` https://getrector.org/demo/468ad5e2-d3d1-4ef1-b037-dcf7d0a967db
