### ISSUE TITLE
Rector is not processing other PHP files having different extensions

### ISSUE THREAD

**Issue by Supreetam09** [rectorphp/rector#7348]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| 0.13.10 | Rector is not processing other PHP files having different extensions |

## Problem
I am trying to run Rector in a Drupal project and it is running fine. But I noticed that its only running for files having PHP extensions. In Drupal, we have multiple PHP files having different extensions like `.module`, `.install`, `.inc` etc. All normal PHP files are getting validated using rector but these PHP files having different extensions are not getting processed even though there are fixable errors there.

I know Rector does not support Drupal open-source as of now but it should be able to process all PHP files regardless of extensions.

I am not sure if this an issue that its not working OR there is a configuration I am missing in my `rector.php` file to include them for processing OR is it something Rector does not support yet i.e. new feature request in that case.

## Expected Behaviour

Rector should process all PHP files regardless of file extensions.

**Comment by TomasVotruba** [comment]
Hi,

what about this option?

```php
$rectorConfig->fileExtensions([...]);
```

**Comment by Supreetam09** [comment]
Awesome @TomasVotruba. I missed to check this in the rector config. I added the config and now other file types are getting picked up for processing. Thanks for your prompt help. Closing this now.

**Comment by TomasVotruba** [comment]
Glad it worked :+1: 
I have a little trick to find all the options without checkind the docs. I'm very lazy :) 

I hit an IDE autocomplete and all the options are there (the bold ones):

![Peek 2022-08-06 23-26](https://user-images.githubusercontent.com/924196/183266529-dcee02db-80c7-48d4-9b2e-a9f9fb49eb5e.gif)
