### ISSUE TITLE
`AnnotationToAttributeRector` fails when used with other sets

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#7349]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10             |

When using a big set of rules, an error occurs on various classes when have to be applied rules that use `AnnotationToAttributeRector`.

The error is reproduced in the demo.

Debugging the problem (activating sets one by one 😅🙅😫), I found the error may be caused by `AnnotationToAttributeRector`.

If the sets that use this class are removed from the configuration, Rector runs without errors.

If all sets are removed but the ones that use this class, Rector runs without errors and correctly changes the code base.

But if all sets are run together, then Rector crashes.

Honestly I don't know why, but I know this is the entry point to understand the problem.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/e4d999f2-425d-474d-af32-f8c5f7081c2f

## Expected Behaviour

Rector runs without errors.

**Comment by samsonasik** [comment]
It seems reproduced due to combination of rules `LongArrayToShortArrayRector` and `AnnotationToAttributeRector`:

```php
<?php

declare (strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Php54\Rector\Array_\LongArrayToShortArrayRector;
use Rector\Php80\Rector\Class_\AnnotationToAttributeRector;
use Rector\Php80\ValueObject\AnnotationToAttribute;

return static function (RectorConfig $rectorConfig) : void {
    $rectorConfig->rule(LongArrayToShortArrayRector::class);
    
    $rectorConfig->ruleWithConfiguration(AnnotationToAttributeRector::class, [
        new AnnotationToAttribute('Doctrine\ORM\Mapping\ManyToOne'),
    ]);
};
```

ref https://getrector.org/demo/64742756-004e-432f-ad7f-a0ba50647644

**Comment by Aerendir** [comment]
I really have no idea: the best I could understand is that `AnnotationToAttributeRector` is involved in the error.

But the class I proposed as example is very simple and has no arrays with long syntax: why would `LongArrayToShortArrayRector` be applied? Ot just the analysis is sufficient to break the code?

**Comment by samsonasik** [comment]
The array is exists in the Attribute:

```diff
         */
+        #[ORM\ManyToOne(targetEntity: OfferPrice::class, inversedBy: 'myEntities', cascade: ['persist'])] private OfferPrice $offerPrice
     )
     {
```
