### ISSUE TITLE
Incorrect behavior of ForeachItemsAssignToEmptyArrayToAssignRector

### ISSUE THREAD

**Issue by ossinkine** [rectorphp/rector#7350]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/8b7aa594-cfa5-4308-ade5-98d9f47f5c9c

```php
<?php

final class DemoFile
{
    public function run(): array
    {
        $items = [];
        foreach ($this->getArray() as $item) {
            $items[] = $item;
        }
        
        return $items;
    }
    
    private function getArray(): iterable
    {
        yield 123;
    }
}
```

### Responsible rules

* `ForeachItemsAssignToEmptyArrayToAssignRector`

## Expected Behavior

This is rule should be applied if array is iterated only and should not be applied if Traversable object is iterated.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.
