### ISSUE TITLE
AnnotationToAttributeRector for ParamConverter is buggy

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#7352]
AnnotationToAttributeRector for SensioFrameworkExtraBundle's ParamConverter is buggy.

This is what happens to me
```diff
- @ParamConverter(name="parametername", class="App\Entity\MyEntity", options={"id"="identifier"})
+ #[ParamConverter(name: 'parametername', class: 'App\Entity\MyEntity', options: ['id' => 'identifier'])]  
``` 
The Symfony docs https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/converters.html#usage say it should be
```diff
+ #[ParamConverter('parametername', class: 'App\Entity\MyEntity', options: ['id' => 'identifier'])]
```

**Comment by TomasVotruba** [comment]
Hi, what is the buggy part? I preserves original parameter names, that is correct.

**Comment by TomasVotruba** [comment]
How does it break the code? Could you share the reference to param converter class and the errors you get?

**Comment by TomasVotruba** [comment]
How could it work with `name` in annotation? I don't see it there.

**Comment by TomasVotruba** [comment]
I see, the magic is back again :) 

Do other Symfony/Sensio annotation have such implicit behavior? So we can deal with it at once.

**Comment by TomasVotruba** [comment]
We have no clear direction about that yet. What would you suggest?

**Comment by TomasVotruba** [comment]
> I would measure the work needed for both scenarios and then pick the optimal one.

In the `ParamConverter` case, the factory could detect the class, then `foreach()` args and remove named arg with value of "name" to `null`. It could be 5-lines solution.
