### ISSUE TITLE
Incorrect behavior of RegexDashEscapeRector

### ISSUE THREAD

**Issue by ebrigham1** [rectorphp/rector#7356]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f7c15ce4-8dbe-4f79-bd1e-88c7a9d10c3c

```php
<?php

preg_match('/[\-\w]/');
```

### Responsible rules

* `RegexDashEscapeRector`

## Expected Behavior

Rector should skip updating this code

## Regex101.com interpretation of code
**Pre-change PCRE:**
![pre_change_pcre](https://user-images.githubusercontent.com/7337543/183924508-f1690f68-f3f8-4b5f-9069-17cf1f736152.png)
**Pre-change PCRE2:**
![pre_change_pcre2](https://user-images.githubusercontent.com/7337543/183924570-90e7f90c-63e1-4501-80ff-37342d4fc669.png)
**Post-change PCRE:**
![post_change_pcre](https://user-images.githubusercontent.com/7337543/183924655-04b972a7-eb3c-48d1-93e7-9a3994d87c5b.png)
**Post-change PCRE2:**
![post_change_pcre2](https://user-images.githubusercontent.com/7337543/183924712-322b2666-d1a9-455c-bf5e-a4d1143cd25b.png)

**Comment by TomasVotruba** [comment]
Hi, thank you for your detailed report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by ebrigham1** [comment]
@TomasVotruba done https://github.com/rectorphp/rector-src/pull/2753
