### ISSUE TITLE
Cannot autowire service "Rector\BetterPhpDocParser\PhpDocNodeMapper"

### ISSUE THREAD

**Issue by crazyhl** [rectorphp/rector#7360]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.9             |
| PHP version | 7.4.27   |

## Minimal PHP Code Causing Issue
when i run any command start with  `vendor/bin/rector` , it always has error.

```
 [ERROR] Cannot autowire service "Rector\BetterPhpDocParser\PhpDocNodeMapper": argument "$phpDocNodeVisitors" of method
         "__construct()" is type-hinted "array", you should configure its value explicitly.
```

<img width="876" alt="image" src="https://user-images.githubusercontent.com/5474833/184267762-f54561bd-be26-4621-be40-71b3fe266883.png">

**Comment by samsonasik** [comment]
I can't reproduce, how you reproduce it: step install - and config? Could you provide minimal sample reproduced repository for it?

**Comment by crazyhl** [comment]
i run a helloworld project ,it  run ok. i closed issue. check my real project first.
