### ISSUE TITLE
`IsCountableRector` won't do on all files

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7362]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.7             |
| PHP version | 7.2.24 |

I just ran `IsCountableRector` over a legacy code base (currently preparing for update to php81 - using rector. awesome! :heart: ). My code does provide `symfony/polyfill-php73`, so a `is_countable` is registered and fully functioning. After running rector, many files got updated. But I just found some, which don't.

## Minimal PHP Code Causing Issue

Reproducible by demo: https://getrector.org/demo/c4072829-a320-4aef-a647-182210010d0c

Running rector with above configuration and `--debug` states in (reduced lines for simplicity): 

```bash
$> vendor/bin/rector process src/SubtitleBundle/Service/ --debug -vvv
src/SubtitleBundle/Service/SubtitleImporterService.php
[file] src/SubtitleBundle/Service/SubtitleImporterService.php
[rule] Rector\Php73\Rector\BooleanOr\IsCountableRector

[file] src/SubtitleBundle/Service/SubtitleImporterService.php
[rule] Rector\Php73\Rector\BooleanOr\IsCountableRector

src/SubtitleBundle/Service/SubtitleProcessorService.php

                                                                                                                        
 [OK] Rector is done! 
```

It definitely does something, but results in no code change on these files. I don't know why.

## Expected Behaviour

Replaced the lines like: 

```php
$updatesCount = is_array($this->processor->getUpdates()) || $this->processor->getUpdates() instanceof \Countable ? count($this->processor->getUpdates()) : 0;
```

with 

```php
$updatesCount = is_countable($this->processor->getUpdates() ? count($this->processor->getUpdates()) : 0;
```

so I don't have to ;-)

**Comment by samsonasik** [comment]
Looking at the code, it seems check against Variable:

https://github.com/rectorphp/rector-src/blob/da9fab1810dd4985b2071b3ffc34c88f665856cb/rules/Php71/IsArrayAndDualCheckToAble.php#L66

verify against method call seems disabled due to can possibly cause side effect.
