### ISSUE TITLE
Incorrect behavior of PreferThisOrSelfMethodCallRector

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7363]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.13.7     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/0c8e9f4c-916f-43fb-962e-e50c6b290f95

```php
<?php

use PHPUnit\Framework\TestCase;

final class DemoFile extends TestCase
{
    /**
     * @test
     */
    public function sourcesWithoutRight()
    {
        $episode = new Episode();
        self::assertSame(
            ["hls" => [], "hds" => [], "smooth" => [], "dash" => [], "progressive_download" => []], 
            $this->sources->getSourcesByEpisode($episode)
        );
    }
}
```

### Responsible rules

* `PreferThisOrSelfMethodCallRector`

## Expected Behavior

I'm currently upgrading a legacy project which still uses a "max line length of 120" (PSR2 is ... old? wow). I do not want to sacrifice this rule, because there is ongoing development on this project - so I want to use best of both worlds. 

Rector should just skip it. There is effectively no change, since it's already "self".

Btw.: great job. I :heart: rector.

**Comment by mvhirsch** [comment]
Can reproduce with rector _0.13.10_, too.

**Comment by samsonasik** [comment]
Before and after seems equal, it seems because the method call reprinted return Node in the rule so it got single lined.
