### ISSUE TITLE
System error: \"PhpParser\\Internal\\TokenStream::getIndentationBefore(): Return value must be of type int, null returned

### ISSUE THREAD

**Issue by alejomoreira** [rectorphp/rector#7364]
# Bug Report

| Subject        | Details   |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.10  |
| Installed as | composer dependency |

Hey guys!, I'm trying to upgrade and refactor a Legacy Code written in PHP 7.4 but I'm getting severals errors, this is one of them.

## Minimal PHP Code Causing Issue

for ($i = 0; $i < sizeof($psychiatry); $i++) {
	$psychiatry[$i]["sufficient_cancellation_notice"] = $s->isSufficientNoticeToCancel($psychiatry[$i]) ? 1 : 0;
}

for ($i = 0; $i < sizeof($psychotherapy); $i++) {
	$psychotherapy[$i]["sufficient_cancellation_notice"] = $s->isSufficientNoticeToCancel($psychotherapy[$i]) ? 1 : 0;
}

https://getrector.org/demo/168046d0-bb76-4c4b-b480-8a104e3e2ed9

## Expected Behaviour
Refactor the code to improve code quality and make compatible with PHP8.1

## Responsible Set of Rules
CODE_QUALITY

**Comment by TomasVotruba** [comment]
Hi, thanks for the report. 
We'll need a minimal code and rule that is causing the issue.
Could you narrow it down to ~5 lines? It's always something small.

**Comment by alejomoreira** [comment]
Hey, thanks for your quick answer, I've updated with the minimal code causing the issue, Idk the specific rule but the set of rules causing the problem is CODE_QUALITY, I'm new using Rector so let me know if I'm making a mistake with something. Thanks!

**Comment by TomasVotruba** [comment]
Thanks for the update :+1: 
The demo links still points to the old code. Could you update that one?

It might be 1 or 2 rules from the code quality set. The only way seem to [narrow the scope](https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/) by cutting down the rules manually.

**Comment by alejomoreira** [comment]
Okay, I think it's updated now, it looks like return error when I use LevelSetList::UP_TO_PHP_81 and SetList::CODE_QUALITY together.

**Comment by TomasVotruba** [comment]
It seems there is ~500 lines in the code snippet:
https://getrector.org/demo/168046d0-bb76-4c4b-b480-8a104e3e2ed9

Could you share the new link here? Mabye the description is not updated on my side :)

**Comment by alejomoreira** [comment]
Yeah, sorry it's a new one https://getrector.org/demo/8db61b1f-5745-46ae-a365-ad67d87c01f4

**Comment by TomasVotruba** [comment]
Awesome :+1:  Thanks

**Comment by samsonasik** [comment]
Re-open, it seems still has crash on different use case https://getrector.org/demo/bf704c11-3154-4dcd-8517-568565b250d8
