### ISSUE TITLE
Add run command by rule

### ISSUE THREAD

**Issue by Myks92** [rectorphp/rector#7366]
# Feature Request

Please add the launch of the rule check. For example, the `vendor/bin/rector src process --dry-run --rule=InvokableControllerRector,TernaryToElvisRector`. This can be useful when there are a lot of vector errors in the project and I would like to fix each one gradually.

In addition, you can add ignoring the rules:
`vendor/bin/rector src process --dry-run —exclude-rule=InvokableControllerRector,TernaryToElvisRector`

**Comment by TomasVotruba** [comment]
Hi, we actually had this feature few years ago. It was breaking very often as the rules discovery by short class name requires full autoload of all classes. Also you have to make sure there are no 2 short classes. 
Due to that design, it caused more confusion than value, so we removed it.

If you'd contribute this feature, what design would you choose to resolve the rules safely?
If it makes sense, we can accept it.

**Comment by Myks92** [comment]
I started using rector not long ago and I don’t know its internals, so I can’t tell you how best to implement it.

Perhaps one solution would be to create a rule registry class, where the key would be the rule and the value would be the rule class. Conflict resolution will be in one class by key. Keys must be unique.

The idea came from Psalm. There you can run certain rules in approximately the same way as I described.

When can it be useful? Now in rector it lists all rules applied to the class. To see what exactly changes a particular rule in the file, you will have to disable all unnecessary rules in the config, and then return them. and using this option, it could be done directly in the console.

It is also convenient to refactor according to certain rules, and not the whole bunch at once. In this case, git commits will contain more specific changes (Refactoring final class, Migrate Invokallable Controller, Migrate PHP82, Migrate Doctrine annotation, etc...) rather than general ones (Refactoring). In this way, you can implement a gradual fixation of changes.

We can also fix rules that we don't have yet without changing the configuration. commit them to the git repository, and when the refactoring is complete, calmly add a rule to the rector config for control on CI / CD.

I think this is a welcome feature and worth considering to address implementation issues. maybe in future versions, not right away. It is also worth updating the documentation immediately with the possible use of these options. Thanks to them, you can do gradual (deferred) refactoring.

**Comment by TomasVotruba** [comment]
The same can be achieved witch config with full IDE autocomplete. The short string have to be copy pasted, there can be typos etc. Saying that, we won't add such feature ourselves.

If there is a community extension first and it proves to be working and used, we'll reconsider 👍 

Thanks for understanding.
