### ISSUE TITLE
AnnotationToAttributeRector for JMS\AccesorOrder is buggy

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#7369]
Before: 
`@JMS\AccessorOrder("custom", custom = {"id"})`
After
`#[JMS\AccessorOrder('custom', custom: ['id'])]`

Should be:
`#[JMS\AccessorOrder(order: 'custom', custom: ['id'])]`

**Comment by TomasVotruba** [comment]
This will be similar case as https://github.com/rectorphp/rector/issues/7352

**Comment by TomasVotruba** [comment]
Exactly. Check for specific class then changing the 1st arg to named/unnamed.

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector-src/pull/2895 :)

**Comment by TomasVotruba** [comment]
Thanks for reporting. It helped us to make such changes easy 👍
