### ISSUE TITLE
Cannot process backed Enums - "Not implemented"

### ISSUE THREAD

**Issue by bradjones1** [rectorphp/rector#7370]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10 |

Rector fails with `Could not process "[file]" file, due to: "System error: "Not implemented"` in the case of a backed enum.

I believe this is because the fork of better-reflection used by phpstan is out of date from upstream.

See https://github.com/ondrejmirtes/BetterReflection/blob/5.3.x/src/Reflection/Adapter/ReflectionClassConstant.php#L47 (forked) compared to https://github.com/Roave/BetterReflection/blob/5.8.x/src/Reflection/Adapter/ReflectionClassConstant.php#L41 (upstream.)

## Minimal PHP Code Causing Issue

https://getrector.org/demo/3872d465-cf35-420e-8907-128b13ac6969

## Expected Behaviour

Rector need not change this code but should be able to analyze and ignore it.

**Comment by ondrejmirtes** [comment]
That's expected in PHPStan, that's why there's this above the method:

```
    /**
     * @deprecated Use getValueExpr()
     */
```

**Comment by ondrejmirtes** [comment]
You should really use https://github.com/phpstan/phpstan-deprecation-rules in rector-src to be aware of such things :)

**Comment by bradjones1** [comment]
> That's expected in PHPStan...

@ondrejmirtes Thanks for the reply and help here, and for pointing out what should have struck out at me if I weren't so focused on the line in question! Oops. I _did_, however, look to try and find some documentation in the phpstan codebase/README about the justification for and maintenance of the fork. And particularly as regards this method, `::getValueExpr()` isn't in the 5.8.x branch upstream, so I'm curious if changing to that is the correct solution long-term? I certainly don't want people to have to bug you personally when things like this come up, so for someone new to both these projects, I'm curious how I could learn more about why and how to interact with the vendored copy of BetterReflection?

Or, tl;dr, is changing Rector's call to be `::getValueExpr()` going to break at some point?

**Comment by ondrejmirtes** [comment]
PHPStan uses my own fork `ondrejmirtes/better-reflection` that adds some methods that PHPStan needs and Rector can use too. That's why you can't find it in `roave/better-reflection` 5.8.x.

PHPStan heavily relies on these `getValueExpr` methods, I don't plan to remove them. They're used together with InitializerExprTypeResolver to get the `Type` from `Expr`.

**Comment by samsonasik** [comment]
@ondrejmirtes thank you
@TomasVotruba the usage of `ReflectionClassConstant->getValue()` seems are at 'vendor/` part:

- vendor/symplify/astral/src/NodeValue/NodeValueResolver/ClassConstFetchValueResolver.php
- vendor/symplify/easy-ci/vendor/symplify/astral/src/NodeValue/NodeValueResolver/ClassConstFetchValueResolver.php

**Comment by samsonasik** [comment]
it seems `ReflectionClassConstant` in vendor/ seems native php class, not from `BetterReflection`

**Comment by bradjones1** [comment]
It's from the vendored copy, as I understand it. Now that I know what the alternative function call should be I may be able to whip up a PR when I circle back on this.

**Comment by TomasVotruba** [comment]
@bradjones1 Thanks for the report :+1: 

Could you narrow it down to single Rector rule that breaks it? The full stack trace might also help. That could quickly lead to the place the method is called and should be changed :)

**Comment by bradjones1** [comment]
Ugh sorry for the lined PR spam, apparently I forgot how to open pull requests. Found the offending call, should be a 1-liner.

**Comment by bradjones1** [comment]
Looks like a single test failure, at https://github.com/rectorphp/rector-src/runs/7912419290?check_suite_focus=true#step:5:173

Which is related to a constant, which is in the ballpark of this change, but I'm not super familiar with the particular rule in question to give an informed answer as to why it might have regressed.

I think also this issue reveals a lack of test coverage for Enums? Or at least the specific flavor of Enum that raised this error to begin with?
