### ISSUE TITLE
System error: "Call to a member function getAttribute() on null

### ISSUE THREAD

**Issue by alejomoreira** [rectorphp/rector#7374]
# Bug Report

Hey guys! it's me again, with another bug, great work on fixing the last bug.

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main       |

Stack trace:                                                                                                   
         #0 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3458):       
         PHPStan\Reflection\ParametersAcceptorSelector::selectFromArgs(Object(PHPStan\Analyser\MutatingScope), Array, Array)
         #1 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1389):       
         PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ThisType), 'displayTree',             
         Object(PhpParser\Node\Expr\MethodCall))                                                                        
         #2 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1395):       
         PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()                                                   
         #3 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556):        
         PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))                            
         #4 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1383):   
         PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))                                
         #5 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(526):    
         PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\MethodCall),           
         Object(PHPStan\Analyser\MutatingScope))                                                                        
         #6 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(332):    
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression),                    
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))                                                       
         #7 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(490):    
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array,           
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))                                                       
         #8 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(302):    
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),                   
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))                                                       
         #9 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(299):             
         PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
         #10 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(213):            
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles(Object(RectorPrefix20220
         8\Symplify\SmartFileSystem\SmartFileInfo), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))     
         #11 vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(99):                                    
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array,                            
         Object(RectorPrefix202208\Symplify\SmartFileSystem\SmartFileInfo), Object(PHPStan\Analyser\MutatingScope))     
         #12 vendor/rector/rector/src/Rector/AbstractRector.php(237):                                                   
         Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Stmt\ClassMethod),            
         Object(PHPStan\Analyser\MutatingScope), Object(RectorPrefix202208\Symplify\SmartFileSystem\SmartFileInfo))     
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                         
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))                          
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))      
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #19 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #20 vendor/rector/rector/src/Application/FileProcessor.php(61):                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #21 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126):                              
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #22 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93):                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Applica
         tion\File), Object(Rector\Core\ValueObject\Configuration))                                                     
         #23 vendor/rector/rector/packages/Parallel/WorkerRunner.php(99):                                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #24 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #25 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):                                        
         RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)                                                 
         #26 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202208\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #27 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202208\Evenement\EventEmitter->emit('data',
         Array)                                                                                                         
         #28 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202208\React\Stream\Util::RectorPrefix202208\React\Stream\{closure}('{"action":"main...')          
         #29 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)                                                 
         #30 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202208\React\Stream\DuplexResourceStream->handleData(Resource id #2752)                            
         #31 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202208\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #32 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202208\React\EventLoop\StreamSelectLoop->run()                                                     
         #33 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                   
         #34 vendor/rector/rector/vendor/symfony/console/Application.php(891):                                          
         RectorPrefix202208\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202208\Symfony\Component\Console\I
         nput\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                    
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(310):                                          
         RectorPrefix202208\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\WorkerCommand
         ), Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),                                       
         Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #36 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202208\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Inp
         ut\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                      
         #37 vendor/rector/rector/vendor/symfony/console/Application.php(208):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #38 vendor/rector/rector/bin/rector.php(128): RectorPrefix202208\Symfony\Component\Console\Application->run()  
         #39 vendor/rector/rector/bin/rector(4): require_once('/Users/alejo/Do...')                                     
         #40 vendor/bin/rector(112): include('/Users/alejo/Do...')                                                      
         #41 {main}". On line: 58                                         

**Minimal PHP Code Causing Issue**

``

    class R extends Reports
    {

    private function displayTree($name, $data, $other = null) {
        if (empty($data)) return false;
    }
    
    public function action($params, $server) {

        $bb = new BusibooksBusinesses();
              
        $this->displayTree("Equity", $equity, array(
            array("name" => "NET INCOME", "amount" => $net_income),
            array("name" => "RETAINED EARNINGS", "amount" => $retained_earnings)
        ));
        }
    }

``

https://getrector.org/demo/f33a08d7-602c-4fa8-a677-ade4d86ac1d8

Only happens when I used this 2 sets together 
 SetList::DEAD_CODE,
 SetList::NAMING
and it looks the rules that generates the problem is "RemoveUnusedPrivateMethodParameterRector" inside rules sets dead-code.php

**Comment by samsonasik** [comment]
Could you narrow down to specific rules, then submit a failing test case for it? You can submit to https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by alejomoreira** [comment]
Yeah, no problem, here are the specific rules and code.

https://getrector.org/demo/5479c7db-a155-4a85-b4eb-f60876ba3011

**Comment by samsonasik** [comment]
Could you create PR to  https://github.com/rectorphp/rector-src/tree/main/tests/Issues ? You can copy one of them, and modify

**Comment by alejomoreira** [comment]
I think I did, let me know if is okay.

**Comment by samsonasik** [comment]
Thank you, feel free to provide a patch as well if you found solution early ;)

**Comment by TomasVotruba** [comment]
I've made few fixes based on your test fixture: https://github.com/rectorphp/rector-src/pull/2770

Could you retry rector `dev-main` and see what has changed in your case? :slightly_smiling_face: Thanks

**Comment by alejomoreira** [comment]
Hey! it looks good now! thanks!

**Comment by TomasVotruba** [comment]
Thanks for confirmation :wink:
