### ISSUE TITLE
SetList::PRIVATIZATION causes error

### ISSUE THREAD

**Issue by MenschLennart** [rectorphp/rector#7375]
Using SetList::PRIVATIZATION is causing this error:

[ERROR] Could not process "src/**/**/Controller/**/Rest/ApplicationController.php" file, due to:   
         "System error: "PHPStan\Type\Constant\ConstantIntegerType::__construct(): Argument #1 ($value) must be of type int,
         string given, called in                                                                                        
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/InitializerExprTypeResolver.php:104"
                                                                                                                        
         Stack trace:                                                                                                   
         #0 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/InitializerExprTypeResolver.php(104):
         PHPStan\Type\Constant\ConstantIntegerType->__construct('214_680_000')                                          
         #1 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(909):        
         PHPStan\Reflection\InitializerExprTypeResolver->getType(Object(PhpParser\Node\Scalar\LNumber),                 
         Object(PHPStan\Reflection\InitializerExprContext))                                                             
         #2 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556):        
         PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Scalar\LNumber))                             
         #3 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1168):       
         PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Scalar\LNumber))                                 
         #4 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/InitializerExprTypeResolver.php(400):
         PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Scalar\LNumber))              
         #5 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1169):       
         PHPStan\Reflection\InitializerExprTypeResolver->getArrayType(Object(PhpParser\Node\Expr\Array_), Object(Closure))
         #6 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556):        
         PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Array_))                                
         #7 vendor/rector/rector/packages/NodeTypeResolver/NodeTypeResolver.php(208):                                   
         PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Array_))                                    
         #8 vendor/rector/rector/src/Rector/AbstractRector.php(279):                                                    
         Rector\NodeTypeResolver\NodeTypeResolver->getType(Object(PhpParser\Node\Expr\Array_))                          
         #9 vendor/rector/rector/rules/CodingStyle/Rector/ClassConst/VarConstantCommentRector.php(83):                  
         Rector\Core\Rector\AbstractRector->getType(Object(PhpParser\Node\Expr\Array_))                                 
         #10 vendor/rector/rector/src/Rector/AbstractRector.php(204):                                                   
         Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector->refactor(Object(PhpParser\Node\Stmt\ClassConst))
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                         
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassConst))                           
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #17 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #18 vendor/rector/rector/src/Application/FileProcessor.php(61):                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #19 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126):                              
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #20 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93):                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Applica
         tion\File), Object(Rector\Core\ValueObject\Configuration))                                                     
         #21 vendor/rector/rector/packages/Parallel/WorkerRunner.php(99):                                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #22 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #23 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):                                        
         RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)                                                 
         #24 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202208\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #25 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202208\Evenement\EventEmitter->emit('data',
         Array)                                                                                                         
         #26 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202208\React\Stream\Util::RectorPrefix202208\React\Stream\{closure}('{"action":"main...')          
         #27 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)                                                 
         #28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202208\React\Stream\DuplexResourceStream->handleData(Resource id #3052)                            
         #29 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202208\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202208\React\EventLoop\StreamSelectLoop->run()                                                     
         #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                   
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(891):                                          
         RectorPrefix202208\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202208\Symfony\Component\Console\I
         nput\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                    
         #33 vendor/rector/rector/vendor/symfony/console/Application.php(310):                                          
         RectorPrefix202208\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\WorkerCommand
         ), Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),                                       
         Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #34 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202208\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Inp
         ut\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                      
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(208):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #36 vendor/rector/rector/bin/rector.php(128): RectorPrefix202208\Symfony\Component\Console\Application->run()  
         #37 vendor/rector/rector/bin/rector(5): require_once('/Users/lenni/De...')                                     
         #38 {main}". On line: 27

**Comment by samsonasik** [comment]
Could you narrow down to specific rules, then submit a failing test case for it? You can submit to https://github.com/rectorphp/rector-src/tree/main/tests/Issues

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:
