### ISSUE TITLE
System error: \"PhpParser\\Internal\\TokenStream::getIndentationBefore(): Return value must be of type int, null returned

### ISSUE THREAD

**Issue by alejomoreira** [rectorphp/rector#7376]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main            |

Hey guys, I'm getting another error in many of the legacy files. 

## Minimal PHP Code Causing Issue

```php
class R extends Reports {  

  public function search(&$rates, $type, $cpt) {
    for ($i = 0; $i < sizeof($rates); $i++) {
      if ($rates[$i]["code"] == $cpt) {
        switch ($type) {
          case "md": return $rates[$i]["md_amt"];
          case "np": return $rates[$i]["np_amt"];
          case "phd": return $rates[$i]["phd_amt"];
          case "ma": return $rates[$i]["ma_amt"];
          default: return 0.0;
        }
      }
    }

    return 0.0;
  }

}
```

https://getrector.org/demo/d48494eb-2ec6-40b8-96a9-e977187b3884

**Comment by samsonasik** [comment]
Could you create failing test case for it, you should can continue add fixture in this directory https://github.com/rectorphp/rector-src/tree/main/tests/Issues/IndentationCrash/Fixture

**Comment by alejomoreira** [comment]
Done!
