### ISSUE TITLE
NodeFactory->createArray doesn't support boolean Node elements

### ISSUE THREAD

**Issue by xorik** [rectorphp/rector#7378]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.2             |

## Minimal PHP Code Causing Issue
```php
<?php

class MyRule extends AbstractRector
{
    public function getNodeTypes(): array
    {
        return [Node\Expr\MethodCall::class];
    }

    public function refactor(Node $node)
    {
        // String works!
//        return $this->nodeFactory->createArray([new Node\Scalar\String_('hello')]);

        // Boolean isn't :(
        return $this->nodeFactory->createArray([$this->nodeFactory->createTrue()]);

        return null;
    }

    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('', []);
    }
}
```

## Expected Behaviour
It generates a node with array `[true]`

## Actual

Exception:
```
In NodeFactory.php line 517:
                                                                               
  Not implemented yet. Go to "Rector\Core\PhpParser\Node\NodeFactory::createArrayItem()" and add check for "PhpParser\Node\Expr\ConstFetch" node.     
```

**Comment by samsonasik** [comment]
You should can just pass true to that:

```php
$this->nodeFactory->createArray([true]);
```

**Comment by xorik** [comment]
BTW `null` in arrays also isn't implememted

```
return $this->nodeFactory->createArray([$this->nodeFactory->createTrue()]);
```

**Comment by xorik** [comment]
@samsonasik unfortunately I cannot do it, because I don't create array from scratch, I parse method arguments as Nodes, and convert them to array.
```php
$this->method('string', true, null);
// will become
$this->method(['string', true, null]);
```

**Comment by samsonasik** [comment]
Could you add failing test case and possibly make it implemented? You can start with add more tests at https://github.com/rectorphp/rector-src/blob/27b891b219cc9bfed6540a6abfbfa762e1cc2aaf/tests/PhpParser/Node/NodeFactoryTest.php#L40
