### ISSUE TITLE
ORM\AssociationOverrides and ORM\AttributeOverrides are not converted to attributes

### ISSUE THREAD

**Issue by annuh** [rectorphp/rector#7379]
# Bug Report

Hi! While converting our Doctrine annotations to attributes, I found a few missing annotations: `AssociationOverrides` and `AttributeOverrides`.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.13.10      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/ae123c34-f863-4665-a146-f2b8835ba608

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/** 
 * @ORM\Entity()
 * @ORM\Table()
 * @ORM\AssociationOverrides({
 *     @ORM\AssociationOverride(name="propertyA", inversedBy="propertyB")
 * }) 
 * @ORM\AttributeOverrides(
 *     @ORM\AttributeOverride(name="id", column=@ORM\Column(type="integer"))
 * )
 **/
class Entity
{
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

```php
<?php

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table]
#[ORM\AssociationOverrides([
	new ORM\AssociationOverride(name: "propertyA", inversedBy="propertyB"),
])
#[ORM\AttributeOverrides([
	new ORM\AttributeOverride(name: "id", column: new ORM\Column(type: "integer")),
])
class Entity
{
}
```

As a work-around, I used the following config:
```php
return static function (RectorConfig $rectorConfig): void {

    $rectorConfig->ruleWithConfiguration(AnnotationToAttributeRector::class, [
        new AnnotationToAttribute(\Doctrine\ORM\Mapping\AssociationOverrides::class),
        new AnnotationToAttribute(\Doctrine\ORM\Mapping\AssociationOverride::class),
        new AnnotationToAttribute(\Doctrine\ORM\Mapping\AttributeOverrides::class),
        new AnnotationToAttribute(\Doctrine\ORM\Mapping\AttributeOverride::class), // this did NOT work, it created an empty AttributeOverrides attribute
    ]);
}
```

**Comment by TomasVotruba** [comment]
Thanks for the report and perfect solution :+1: 

> As a work-around, I used the following config:

That exact code must be added to the set you're using. Could you send us the PR so it works out of the box? :)

**Comment by TomasVotruba** [comment]
This is the exact file to change: https://github.com/rectorphp/rector-doctrine/blob/main/config/sets/doctrine-annotations-to-attributes.php

**Comment by annuh** [comment]
Thanks for hints, I've prepared a PR: https://github.com/rectorphp/rector-doctrine/pull/124
But I'm still having issues with the `AttributeOverride` annotation. Do you maybe have another suggestion where to take a look? To me the `AssociationOverride` and `AttributeOverride` annotations/attributes look the same from Rector's perspective.
