### ISSUE TITLE
Rector with github actions

### ISSUE THREAD

**Issue by trsteel88** [rectorphp/rector#7380]
# Question

I use rector with github actions and given there is no cache available, it takes a long time for some projects to run. Is anyone familiar with creating a cache that can be persisted for a project?

**Comment by mvhirsch** [comment]
> [...], it takes a long time for some projects to run.

True. 

There is a feature request especially for github workflows here: https://github.com/rectorphp/rector/issues/7341

**Comment by TomasVotruba** [comment]
@mvhirsch Thanks for the link!

Closing in favor of  #7341, let's continue in one place there :slightly_smiling_face:
