### ISSUE TITLE
Renaming property to match type in anonymous functions

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7382]
# Question

I'm renaming `$payment` to `$transaction` in my project. Not exactly sure if it's a bug, or I'm missing something. rector is currently ignoring my anonymous function like this:

```php
$function = static fn (Transaction $payment): bool => $payment->isPaid();
```

I've used the follwing rules:

```php
    $rectorConfig->phpVersion(PhpVersion::PHP_81);
    $rectorConfig->rule(\Rector\Naming\Rector\ClassMethod\RenameVariableToMatchNewTypeRector::class);
    $rectorConfig->rule(\Rector\Naming\Rector\ClassMethod\RenameParamToMatchTypeRector::class);
```

Demo: https://getrector.org/demo/73cee153-26f0-4028-8c71-dbe14bec54e5

I expected the param to be renamed to `Transaction $transaction`, but nothing changed. Is `RenameParamToMatchTypeRector` the right one?

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?

**Comment by mvhirsch** [comment]
So my guess was correct: it's a bug/missing behavior :-)

Will send a PR!

**Comment by mvhirsch** [comment]
Thank you!
