### ISSUE TITLE
PHP parser issue: method calls with a long anon function inside becomes "Nop" node

### ISSUE THREAD

**Issue by xorik** [rectorphp/rector#7383]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | reproducible in the online demo (latest probably)            |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/a49f0b4a-1d0d-4190-a245-8e70b1e1c2fc

## Expected Behaviour

The second method call in the "register" method is always ignored, doesn't matter which rule to choose.
As I understood inside the "register" method (`\PhpParser\Node\Stmt\ClassMethod` node) it can see the first method call, but second becomes a `\PhpParser\Node\Stmt\Nop` node:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/347044/185342479-5e3f0ba6-0203-489e-9adf-5cbb172faba6.png">

**Comment by TomasVotruba** [comment]
This is not a bug but a feature :) the huge nestings sometimes broke the running, as for every nested node, the whole tree must be kept in memory.

Try increasing the limit value from default `60` to higher one:

```php
$rectorConfig->nestedChainMethodCallLimit(60);
```

**Comment by xorik** [comment]
Ah, cool, increasing the limit helped!
Thanks a lot!
