### ISSUE TITLE
Incorrect behavior of SimplifyForeachInstanceOfRector

### ISSUE THREAD

**Issue by tmvpobeda** [rectorphp/rector#7385]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/3b72ccf8-5c5a-414f-855a-3e417c06e515

```php
<?php

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

final class DemoTest extends WebTestCase
{
    public function test()
    {
        $actualProviders = [
        	'provider_key' => new \StdClass(),
        ];
        $expectedProviders = [
        	'provider_key' => \StdClass::class,
        ];
        foreach ($actualProviders as $key => $provider) {
            $this->assertInstanceOf($expectedProviders[$key], $provider, sprintf('"%s" instanceof "%s"', $provider::class, $expectedProviders[$key]));
        }
    }
}
```

### Responsible rules

* `SimplifyForeachInstanceOfRector`

## Expected Behavior

Rector should skip this code.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by tmvpobeda** [comment]
https://github.com/rectorphp/rector-phpunit/pull/99

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-phpunit/pull/100
