### ISSUE TITLE
Incorrect behavior of UnusedForeachValueToArrayKeysRector

### ISSUE THREAD

**Issue by alexey-rus** [rectorphp/rector#7386]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/31798164-0307-4bc3-89e7-247e5ac57078

```php
<?php

final class DemoFile
{
    public function run()
    {
       $calls = [['method', ['event', 'callback']]];
        foreach ($calls as $i => [$method, $arguments]) {
            [$event, $callback] = $arguments;  
        }
    }
}
```

### Responsible rules

* `UnusedForeachValueToArrayKeysRector`

## Expected Behavior

Rector should skip this code.

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/2779
