### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector for DiscriminatorMap annotation with string values

### ISSUE THREAD

**Issue by annuh** [rectorphp/rector#7387]
# Bug Report

A `Doctrine\ORM\Mapping\DiscriminatorMap` annotation  with string values are converted to attributes with constant values. 

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.13.10      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

In this example I used a discriminator with 2 mappings:

- string-based: `"some_string::a" --> "ClassA"` (incorrect)
- constant-based `Class::CONSTANT_B --> "ClassB"` (works correctly!)

The string-based mapping should be converted like:
```
-#[ORM\DiscriminatorMap([some_string::a => 'ClassA'])]
+#[ORM\DiscriminatorMap(['some_string::a' => 'ClassA'])]
```

See https://getrector.org/demo/a0409588-1196-4fc9-a054-adbd0894e009

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\DiscriminatorMap({
 *     "some_string::a"="ClassA",
 *	   Class::CONSTANT_B="ClassB"
 * })
 */
class DiscriminatorEntity
{
}
```

### Responsible rules

* `AnnotationToAttributeRector` for `Doctrine\ORM\Mapping\DiscriminatorMap` annotations

## Expected Behavior

```diff
-/**
- * @ORM\DiscriminatorMap({
- *     "some_string::a"="ClassA",
- *	   Class::CONSTANT_B="ClassB"
- * })
- */
-class DiscriminatorEntity
-{
+#[ORM\DiscriminatorMap(['some_string::a' => 'ClassA', Class::CONSTANT_B => 'ClassB'])]
```

**Comment by annuh** [comment]
I created a test-case for this issue: https://github.com/rectorphp/rector-src/compare/main...annuh:rector-src:patch-1

**Comment by samsonasik** [comment]
You can click "Create Pull Request" button
