### ISSUE TITLE
Incorrect behavior of ChangeSwitchToMatchRector

### ISSUE THREAD

**Issue by burkun-sergey** [rectorphp/rector#7390]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f5be2e04-f419-487b-8ab5-11c5f156fb5f

```php
<?php
final class SwitchToMatch
{
    public function getErrorResponse(int $errorCode): Response
    {
        switch ($errorCode) {
            case 1:
                $content = 'BAD REQUEST';
                break;
            case 2:
                $content = 'CHANGE STATUS FAILED';
                break;
            case 3:
                $content = 'NOT FOUND';
                break;
            default:
                $content = 'FAILED';
        }

        return new Response($content, 400);
    }
}
```

### Responsible rules

* `ChangeSwitchToMatchRector`

## Expected Behavior

```php
final class SwitchToMatch
{
    public function getErrorResponse(int $errorCode): Response
    {
        $content = match ($errorCode) {
            1 => 'BAD REQUEST',
            2 => 'CHANGE STATUS FAILED',
            3 => 'NOT FOUND',
            default => 'FAILED',
        }

        return new Response($content, 400);
    }
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request to `ChangeSwitchToMatchRectorTest`, so we have it covered in Rector? 
Then we can check it and see what needs to be done :)

**Comment by burkun-sergey** [comment]
Done. https://github.com/rectorphp/rector-src/pull/2796

**Comment by TomasVotruba** [comment]
Thank you :+1:
