### ISSUE TITLE
Incorrect behavior of `RemoveParentCallWithoutParentRector` when grandparent has method

### ISSUE THREAD

**Issue by bradjones1** [rectorphp/rector#7391]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://github.com/rectorphp/rector-src/pull/2799 for failing test.

```
1) Rector\Tests\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector\RemoveParentCallWithoutParentRectorTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/DeadCode/Rector/StaticCall/RemoveParentCallWithoutParentRector/Fixture/parent_same_namespace_aliased_parent.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 class ParentSameNamespaceAliasedParent extends ParentSameNamespaceAliasedParentParentClass {
 
-    public function theMethod() {
-        parent::theMethod();
+    public function theMethod()
+    {
     }
 
 }

/home/bradj/www/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:167
/home/bradj/www/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:128
/home/bradj/www/rector-src/rules-tests/DeadCode/Rector/StaticCall/RemoveParentCallWithoutParentRector/RemoveParentCallWithoutParentRectorTest.php:18
```

### Responsible rules

* `RemoveParentCallWithoutParentRector`

Worth noting that the docs for this rule seem to indicate that it will remove calls to a non-existent parent, but the rule appears to (also?) look for the method on the immediate parent, instead of seeing if it is present in the ancestry of the class?

## Expected Behavior

The static call to `parent::doSomething()` is left intact as it is inherited from `A`.

**Comment by bradjones1** [comment]
Ughhh, this bug is intermittent locally and also on my CI and the demo site. I'll re-open if I can get it to consistently happen here.

**Comment by TomasVotruba** [comment]
Hi, maybe it would help to a add test fixture to `RemoveParentCallWithoutParentRectorTest` with all 3 classes.
Then we could narrow it down and isolate the issue. Could you send PR with the test fixture?

**Comment by bradjones1** [comment]
I'm shocked I got it working on the first try, but I will say the instructions were :100:!

https://github.com/rectorphp/rector-src/pull/2799

**Comment by samsonasik** [comment]
I am closing it as it is due to autoload per https://github.com/rectorphp/rector-src/pull/2799#discussion_r950072522 discussion.
