### ISSUE TITLE
TypedPropertyRector does not recognize generics in intersetction types

### ISSUE THREAD

**Issue by Khartir** [rectorphp/rector#7392]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

If an `@var` annotation describes a property containing a specified generic, `TypedPropertyRector` correctly sets the (non-generic) native type and keeps the annotation to preserve the generic: https://getrector.org/demo/4ef0c761-6023-405f-aded-e3451acb8f6a

However if the annotation also contains an intersection type, the annotation is removed regardless.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/11a51282-5112-4293-a854-fe2b6c2a6960

```php
<?php

final class DemoFile
{
    /**
      * @var MockObject&ObjectRepository<ItemCountry>
      */
    private $itemCountryRepo;
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

if an `@var` annotation contains a generic, the annotation is always preserved.

**Comment by TomasVotruba** [comment]
Hi, thanks for the report. 
It seems like a bug, the annotation should be kept untouched  :+1: 

Could you send a failing testcase via PR to `TypedPropertyRectorTest`?
