### ISSUE TITLE
RemoveNonExistingVarAnnotationRector removes useful comments

### ISSUE THREAD

**Issue by annuh** [rectorphp/rector#7393]
# Bug Report

Rector removes some useful `@var` comments, which were added to make static analysis tools like Psalm and PHPStan happy.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.14.0      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/b8211831-e437-4bd9-a844-266787f6d95f

```php
<?php

final class DemoFile
{
    public function run()
    {
        /** @var object{foo: string} $json */
        $json = json_decode('{"foo": "bar"}', false);
    }
}
```

### Responsible rules

* `RemoveNonExistingVarAnnotationRector`

## Expected Behavior

Rector should not remove this comment, because it's useful for static analysis tools.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.
