### ISSUE TITLE
Rector plugin developer's API

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector#7394]
# Background

The problem was initially reported [here](https://twitter.com/_Codito_/status/1551696130735480832), @samsonasik gave feedback that it's caused by rectorphp/rector-src#2589 and I should create custom bootstrap or solve it somehow on my side. So I did some [hack](https://github.com/CoditoNet/rector-money/commit/8505738d5e51639096e3ac4be3ec9f09bf2ca0b0) by using Rector's prefixed version of `SmartFileInfo`. 

FYI: In the meantime I've contributed with symplify/symplify#4292 and rectorphp/rector-src#2732 which improved types used in Rector's methods. I don't think it is strictly related to the problem, because the issue with `SmartFileInfo` occurred earlier. I'm just mentioning it as a part of background for my proposal 🙂

# Problem

The problem with current approach, from Rector plugin's developer point of view, is that it's not clear how to hook into Rector's flow with custom rules, especially in terms of testing. To satisfy PHPStan I had to use prefixed version of bundled class, which is not good solution because prefix is date-based, so in the future build namespace will change and I will have to change imports on my side after upgrading Rector.

Even if I install `symplify/smart-file-system`, it can't be used because of type mismatch:

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/600668/185613962-be9bd939-ab38-4fe4-bc99-b17dc4d57c7f.png">

# Feature Request

I would like to ask you for creating full Plugin Development API, that would be possible to use in external projects. What I mean is that `AbstractRectorTestCase` and all other classes required for plugin development (passed into and returned from Rector), should use non-prefixed contracts. Since abstract test case is in `Rector\Testing\PHPUnit` namespace, it is stable contract for use in custom rector rules. But `yieldFilesFromDirectory()` and `yieldFilesWithPathnameFromDirectory()` operates on prefixed classes, leading to unstable API.

Maybe it should be aliased or extended by some class - I don't have exact solution, but only idea that these methods should operate on something like `Rector\Testing\Contract\FixtureFileInfo`. This would allow plugin developers to use this contracts without worry that namespace will change at some point.

**Comment by TomasVotruba** [comment]
Thanks for the summar of whole process :+1: 

I wonder, is the some reason not to pass simple file path now? :) That would remove the whole complexity and let us use files as simple file paths.

**Comment by Wirone** [comment]
Simple file path would be enough technically, but would be very limited and would require changes in `doTestFileInfo()` too, since it now expects prefixed `SmartFileInfo` instance (or such instance had to be created in test between yield and calling `doTestFileInfo()` which would end up with the exact same problem - prefixed class should be used).

Of course, if we think from KISS perspective, we shouldn't think about possible future improvements. But introducing simple contract would do the trick too, with ability to extend it when needed, without breaking compatibility. For example such contract could allow to check fixture's last modification time, check if there's result cache for it (if Rector has it 😉) etc. Just thinking out loud 🙂

Currently there's alias defined:

```
\class_alias('RectorPrefix202208\\Symplify\\SmartFileSystem\\SmartFileInfo', 'Symplify\\SmartFileSystem\\SmartFileInfo', \false);
```

But it's error prone since ECS registers the same alias, but for ECS-prefixed class... The only way to achieve "stable" contract is custom bootstrap that would load this class and registered alias before running tests. But I'm not even sure if it would work properly (didn't test it).

**Comment by Wirone** [comment]
As I said - it technically would solve the main issue, but may lead to another problems in the future 🙂 

As far as I see, [`AbstractCheckerTestCase`](https://github.com/symplify/symplify/blob/main/packages/easy-coding-standard/src/Testing/PHPUnit/AbstractCheckerTestCase.php) also uses `SmartFileInfo`. But this issue most probably does not occur there since ECS wraps CodeSniffer/CSFixer, so if anyone is writing custom sniffs/fixers, most probably uses original tool for testing them, not ECS. In terms of Rector, the tool itself provides the only testing environment, but its API (SDK?) is not stable enough at this point.

How other plugins handle this 🤔?

* [`palantirnet/drupal-rector`](https://github.com/palantirnet/drupal-rector) does not use ECS
* [`craftcms/rector`](https://github.com/craftcms/rector) uses Rector 0.12, so `SmartFileInfo` is in bootstrap
* [`FriendsOfShopware/shopware-rector`](https://github.com/FriendsOfShopware/shopware-rector) uses Rector 0.13.4 (lock file), so like above
* [`sabbelasichon/typo3-rector`](https://github.com/sabbelasichon/typo3-rector) load prefixed class in [bootstrap](https://github.com/sabbelasichon/typo3-rector/blob/main/tests/bootstrap-phpstan.php#L8) 
* [`sulu/sulu-rector`](https://github.com/sulu/sulu-rector) doesn't use ECS
* [`efabrica-team/rector-nette`](https://github.com/efabrica-team/rector-nette) loads [scoper autoload](https://github.com/efabrica-team/rector-nette/blob/0617f6aa78c730ffe14c5721f5a49656b22cc577/phpstan.neon#L31) in PHPStan config
* [Sylius/SyliusRector](https://github.com/Sylius/SyliusRector) can't find 😅 
* [`laminas/laminas-servicemanager-migration`](https://github.com/laminas/laminas-servicemanager-migration) doesn't use ECS

As you can see each plugin repo must hack it in some way, some of them doesn't even know about it because they're on too old versions of Rector or don't use ECS 😉 It would be good to solve it on Rector's side and deliver stable API/SDK.

CC: @mglaman, @brandonkelly, @sabbelasichon, @alexander-schranz, @lulco, @jakubtobiasz

**Comment by TomasVotruba** [comment]
I agree :wink:  Removing object would resolve the autoloading. We can do that in both Rector and ECS. Unless there is a reason to require them.

**Comment by lulco** [comment]
In my package https://github.com/efabrica-team/rector-tomaj-nette-api I even didn’t realize there is some alias because I didn’t have any problem (don’t use ecs). I am Ok with replacing SmartFileInfo with path

**Comment by mglaman** [comment]
+1 string versus smart file info. It also helps reduce dependencies, and the API is ever shifting with Rector.

**Comment by TomasVotruba** [comment]
> +1 string versus smart file info

So which one do you prefer? :)

**Comment by mglaman** [comment]
Sorry, that was meant to be a +1 to using `string` path over the `SmartfileInfo`.

**Comment by Wirone** [comment]
> +1 string versus smart file info. It also helps reduce dependencies, and the API is ever shifting with Rector.

It won't reduce dependencies, it would just don't allow them to go outside (public API). At least I think `symplify/smart-file-system` still would be used inside, @TomasVotruba correct me if I'm wrong 🙂

**Comment by mglaman** [comment]
> It won't reduce dependencies

Poor wording on my end. It removes a dependency-specific class from the public API (it's not a Rector object, it's a Simplify object.) That's more of what I meant – it's not a dependency removal in Rector, but a soft-dependency on Rector integrations consuming the API.

**Comment by TomasVotruba** [comment]
@mglaman Exactly :+1: I think that's the point here, to remove the public dependency and use common file path type :)

**Comment by Wirone** [comment]
> I think that's the point here, to remove the public dependency and use common file path type :)

Not exactly - the point here is to make some stable contract for public Rector API/SDK, file path as string is one of the options 🙂 

I think we can all agree that Rector shouldn't expose non-Rector classes and prefixed ones. Only native PHP types and Rector namespace is allowed.

Decision to be made: use regular `string` for paths (simplest choice, but not extendable in the future without BC) or some Rector-namespace interface/class representing fixture file (more work now, but easily extendable in the future) 🙂

**Comment by TomasVotruba** [comment]
> use regular string for paths (simplest choice, but not extendable in the future without BC) 

That's the only way to go :slightly_smiling_face: Anything else will prefix other classes and cause different kinds of bugs.

**Comment by Wirone** [comment]
I don't know how prefixing works in practice (never dug it), but I thought it only prefixes vendors bundled in the downgraded release? So if there was some class in `Rector\Testing*` that would be used in `AbstractRectorTestCase`, would it be prefixed? 🤔 I think not, so it would work as stable contract.

**Comment by TomasVotruba** [comment]
The question is still the same as I asked in the start - why is the object needed?

**Comment by Wirone** [comment]
I was thinking about ability to provide some meta info along with the fixture's file path, like fixture folder path, currently run test etc, but now as I think of it maybe it's not needed since it would be already in test's context (custom rector based on abstract rector), so these kind of information already would be there 🤔 So the only thing I can think of right now would be ability to pass relative AND absolute path at the same time, I don't know if it's required though. I don't want to force object here, I just don't want situation when at some point additional info would be required and BC should be introduced (change `string` to some object). But @TomasVotruba you have final word here, so if you want `string`, let's do it 👍 

I could work on it, but I need one extra info: `AbstractRectorTestCase::doTestFileInfo()`'s signature must be change too, to support `string` path, so should it be converted into `SmartFileInfo` again inside of this method just to be passed deeper? Because if not, there must be a lot more changes 😉

**Comment by samsonasik** [comment]
@Wirone `SmartFileInfo` is added back to `bootstrap.php` https://github.com/rectorphp/rector-src/pull/2846, could you try latest `rector/rector:dev-main` ?

**Comment by Wirone** [comment]
@samsonasik It does not solve the main problem here - it still does not offer stable API since it only loads the prefixed class which defines alias for `Symplify\SmartFileSystem\SmartFileInfo`. But the same alias is created in ECS so it depends on the autoloading order. We need to get rid of this `SmartFileInfo` types in the signatures or introduce stable, non-prefixed class that could work as public API.

**Comment by samsonasik** [comment]
@Wirone the `SmartFileInfo` no longer exists now in `rector/rector:dev-main`, you can use the following method, for example in test, the usage can be:

```php
use Iterator;
use Rector\Testing\PHPUnit\AbstractRectorTestCase;

final class Sometest extends AbstractRectorTestCase
{
    /**
     * @dataProvider provideData()
     */
    public function test(string $filePath): void
    {
        $this->doTestFile($filePath);
    }

    public function provideData(): Iterator
    {
        return $this->yieldFilePathsFromDirectory(__DIR__ . '/Fixture');
    }

    public function provideConfigFilePath(): string
    {
        return __DIR__ . '/config/configured_rule.php';
    }
}
```

**Comment by Wirone** [comment]
@samsonasik I know, I saw rectorphp/rector-src#2876 and Tomas' tweet 😉 But thanks anyway! I'll close this now since it looks like problem is solved (for now 😛).
