### ISSUE TITLE
EncapsedStringsToSprintfRector: support gettext's _()

### ISSUE THREAD

**Issue by SantosSi** [rectorphp/rector#7399]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.10                               |

EncapsedStringsToSprintfRector does not respect gettext's _() translation function. It also changes the string to be re-translated, but the functions are called in the wrong order.

## Minimal PHP Code Causing Issue

(https://getrector.org/demo/c693e8db-6a7a-4103-9b02-ff7d2f28a5e5)
Changes the code to: 
`echo _(sprintf('We have %d apples.', $amount));`

## Expected Behaviour
`echo sprintf(_('We have %d apples.'), $amount));`

1. Either change to match the expected behavior. Then the string has to be re-translated.
2. Or else leave it as it is when the string is processed by _() or its [variants](https://www.php.net/manual/de/ref.gettext.php), like gettext(), ngettext, etc.

If possible, make this rector configurable to give the dev team the option to keep the translations intact (leave the code as is) or not (run the rector), e.g. depending on the effort required to translate, which can be quite high with many strings and/or languages involved.

**Comment by TomasVotruba** [comment]
Thanks for reporting. The translation should not be broken by this one, you're right.

> Or else leave it as it is when the string is processed by _() or its [variants](https://www.php.net/manual/de/ref.gettext.php), like gettext(), ngettext, etc.

This option makes sense to me :+1:

**Comment by samsonasik** [comment]
@SantosSi could you write down list of gettext's function and the usage that can be skipped other than `_` here so we can check like the following:

```php
if ($node instanceof FuncCall && $this->isNames($node, ['_', 'gettext', ....])) {
```


? Thank you.

**Comment by SantosSi** [comment]
@samsonasik The hyperlink [variants](https://www.php.net/manual/de/ref.gettext.php) I provided above lists the following functions translating texts one way or another, copied here for your convenience:
[dcgettext](https://www.php.net/manual/de/function.dcgettext.php)
[dcngettext](https://www.php.net/manual/de/function.dcngettext.php)
[dgettext](https://www.php.net/manual/de/function.dgettext.php)
[dngettext](https://www.php.net/manual/de/function.dngettext.php)
[gettext](https://www.php.net/manual/de/function.gettext.php)
[ngettext](https://www.php.net/manual/de/function.ngettext.php)
Please review my opinion for confirmation.

**Comment by samsonasik** [comment]
Thank you, I created PR https://github.com/rectorphp/rector-src/pull/2809 for it.

**Comment by SantosSi** [comment]
Wow guys, impressive debugging speed!
