### ISSUE TITLE
__ConfigurationProperties__ please remove this

### ISSUE THREAD

**Issue by LocalHeroPro** [rectorphp/rector#7402]
Please cleanup that class:
![image](https://user-images.githubusercontent.com/42643563/185755082-30d12cfa-e4e0-4050-9ae8-504c29f9cf7c.png)
It's located in
![image](https://user-images.githubusercontent.com/42643563/185755119-932e30f9-64cb-4db5-8f40-b9e699352858.png)

**Comment by TomasVotruba** [comment]
This is a template file for Rector generator :)

**Comment by LocalHeroPro** [comment]
Because of that I can't run
```bash
$ php artisan opcache:compile --force
```
I get:
![image](https://user-images.githubusercontent.com/42643563/185756648-9cfb53f0-d857-4752-b12b-c8417bd39a49.png)

**Comment by samsonasik** [comment]
You may need to consult to laravel-opcache repository issue instead.

**Comment by LocalHeroPro** [comment]
Don't think so.
Another issue because of rector:
![image](https://user-images.githubusercontent.com/42643563/185757083-bd54dd0f-e1ef-4f44-8957-6d404799d1e7.png)

**Comment by samsonasik** [comment]
You can install rector globally for last resort:

```
composer global require --dev rector/rector
composer remove rector/rector
```

On run rector, you may need to specify the autoload:

```
rector process src -a vendor/autoload.php
```

**Comment by LocalHeroPro** [comment]
It's only workaround what we don't need.
That don't remove main reason of issues, so debt will still be present in that package.

**Comment by samsonasik** [comment]
The issue is by another package, so it is not rector responsibility

**Comment by LocalHeroPro** [comment]
;)
Even PhpStorm highlight issue in syntax ... eh

**Comment by samsonasik** [comment]
Hm..., the solution probably make extension to be changed, eg: .php.tpl , that will may need extra steps check in reading/writing

**Comment by LocalHeroPro** [comment]
So please open that thread.

**Comment by samsonasik** [comment]
Feel free to create feature Pull Request for it :)

**Comment by LocalHeroPro** [comment]
At least, open it.

**Comment by TomasVotruba** [comment]
Similar issues are usually opened for many months with no action, as they're created by bystander with no will to actually contribute.
Then those issues clutter other issues with high priority like bugfixes of PHP version upgrade.

To keep organization simpler, we close those. Thanks for understanding.

Locking to avoid bikeshedding.
