### ISSUE TITLE
RenameParamToMatchTypeRector must ignore vendor classes & interfaces

### ISSUE THREAD

**Issue by badmansan** [rectorphp/rector#7407]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.14.0 (latest)             |

## Problem code

```php
// vendor class & interface
class Param {}

interface SomeInterface
{
    public function foo(Param $beer);
}

// my class
class MyClass implements SomeInterface
{
    public function foo(Param $beer)
    {
    }
}
```

## Expected Behaviour
No Rector errors

In fact, we get
```
-    public function foo(Param $beer)
+    public function foo(Param $param)
```
which is wrong. Rector should skip parameter name, if it come from parent vendor class

**Comment by TomasVotruba** [comment]
Hi, this change is correct. Its a param name, not type.
Why do you see it as issue?

**Comment by badmansan** [comment]
I think we should use the same names as in the parent class. Phpstorm underline those renamed names and suggests renaming them back to original. How do you think?

**Comment by TomasVotruba** [comment]
Do you know why?

**Comment by samsonasik** [comment]
@TomasVotruba that's possibly to avoid used with named argument with dynamic object, for example: 

```php
<?php

class A
{
    public function run(string $x){}
}

class B extends A
{
   public function run(string $y){
        echo $y;
   }
}

$obj = new B();

if ($obj instanceof A) {
    $obj->run(x: 'word');

}

```

Ref https://3v4l.org/fqiHH

**Comment by TomasVotruba** [comment]
That would not affect only vendor class, but every param, right?

The condition for this rule is not to use named parameters. If someone does, and this rule causes some errors, it should be excluded.

**Comment by samsonasik** [comment]
Yes, I think exclude rule is the way to go if it is going to be used for named args
