### ISSUE TITLE
Incorrect behavior of StringClassNameToClassConstantRector

### ISSUE THREAD

**Issue by Synchro** [rectorphp/rector#7408]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

I have a namespaced model named "Value" that has a `BelongsTo` Eloquent relation to another namespaced model called "Attribute". I'm referencing it from a Laravel Nova resource field, which expects a string name of a relation (the param type is actually `mixed`, and it might not be an exact match for a class name as it can contain spaces and different capitalisation), not a class reference. Rector is converting the string name to a top-level PHP Attribute class reference, which is incorrect.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/bf7b87d9-eaee-46d7-8f64-462d9383cd77

```php
<?php

/**
 * @method static static make(mixed $name, string|null $attribute = null, string|null $resource = null)
 */
class BelongsTo {}

final class DemoFile
{
    public function run()
    {
                return [
            BelongsTo::make('Attribute')
        ];

    }
}
```

### Responsible rules

* `StringClassNameToClassConstantRector`

## Expected Behavior

This code should be left untouched. I don't expect a `mixed` param to be unconditionally converted into a class reference, even if its name happens to match a known class name.

**Comment by samsonasik** [comment]
You can exclude 'Attribute' class for it with : 

```php
   // B. or single rule
    $rectorConfig->ruleWithConfiguration(StringClassNameToClassConstantRector::class,
              ['Attribute']
    );
```

ref https://getrector.org/demo/8c49cef7-21a4-47eb-9413-80d251ae4212

**Comment by Synchro** [comment]
That's good to know, but I don't want to have to trawl through every instance to spot this type of anomaly. I don't see why you would ever want this behaviour as it's illogical (to me) and is likely to cause more issues than it solves.

**Comment by gregor-tb** [comment]
Maybe I can add something here. `class_exists()` should be ignored as well by default, it never can be resolved when missing (so the best case is the auto loader stops execution before I pass trash).

```
if (!\class_exists('IntlDateFormatter')) {
      throw new RuntimeException('The intl extension is needed.');
}
if (!\class_exists(\IntlDateFormatter::class)) {
      throw new RuntimeException('The intl extension is needed.');
}
```

See https://getrector.org/demo/a8aa64e9-3817-4595-a876-50fc71de08e5

**Comment by TomasVotruba** [comment]
@Synchro This rule picks up known class-like strings. The `Attribute` is known class-like, so it will be processed.

There is no way to automatically detect if your domain uses `Attribute` as a class or domain string, so the this default path is taken.

The correct way is to exclude those classes in config, like @samsonasik showed

**Comment by Synchro** [comment]
Just FYI, the links to the rector demo above are throwing 500s

**Comment by samsonasik** [comment]
@Synchro the old db got refreshed due was too big

**Comment by Jimbolino** [comment]
https://getrector.org/demo/86d2a3ae-db20-4483-8c55-ddb1c911f297

Maybe in the past it was useful to include all classes in the root namespace, but i think nowadays it would be better to exclude them all. And only use classes that are in an actual namespace.

The built in php classes in the root namespace generate some false positives. You could select some and add them to [the build in list](https://github.com/rectorphp/rector/blob/main/rules/Php55/Rector/String_/StringClassNameToClassConstantRector.php#L35). 

But since most people will use this rule when upgrading a legacy codebase, it's not uncommon to find some legacy classes in the root namespace. 

For example we had `@deprecated` classes like: `Base`, `CLI`, `Notification`, `Path`, `Status`, `User`. But they were used to replace non related strings.

**Comment by TomasVotruba** [comment]
@Jimbolino Agreed 👍 I have the same experience
