### ISSUE TITLE
Incorrect behavior of ChangeNestedIfsToEarlyReturnRector

### ISSUE THREAD

**Issue by kasus** [rectorphp/rector#7409]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/d240e54e-2931-46c4-9911-029ce8245868

```php
<?php

class A 
{
	public function foo()
        {
    	    return rand(0,100);
        }
}

final class B extends A 
{
	public function foo()
        {
            $value = parent::foo();
        
            if(true) {
                if ($value > 50) {
        	    	return 100;
        	}
            }
        
           return $value;
        }
}
```

### Responsible rules

* `ChangeNestedIfsToEarlyReturnRector`

## Expected Behavior

`$value = parent::foo()` must not be removed.

**Comment by samsonasik** [comment]
Please create failing test PR for it, you can click "Create a Test" button at demo page

**Comment by kasus** [comment]
@samsonasik https://github.com/rectorphp/rector-src/pull/2819
