### ISSUE TITLE
StaticArrowFunctionRector removes formatting

### ISSUE THREAD

**Issue by gregor-tb** [rectorphp/rector#7411]
# Bug Report

Applying the StaticArrowFunctionRector, removes the space between `fn` and `(`

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.14      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/2bb01a32-e616-457a-b799-9b1e365a1092

### Responsible rules

* `StaticArrowFunctionRector`

## Expected Behavior

it should changed as in the corresponding code sample

```
<<<'CODE_SAMPLE'
fn (): string => 'test';
CODE_SAMPLE
, <<<'CODE_SAMPLE'
static fn (): string => 'test';
CODE_SAMPLE
```

**Comment by samsonasik** [comment]
That's known drawback ref https://github.com/rectorphp/rector#known-drawbacks

You may need to use coding standard tool for that as pointed in the doc.

**Comment by gregor-tb** [comment]
Sorry, I missed that.
