### ISSUE TITLE
Incorrect behavior of InlineConstructorDefaultToPropertyRector

### ISSUE THREAD

**Issue by gregor-tb** [rectorphp/rector#7415]
# Bug Report

'static::' is not allowed in compile-time constants

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/0254bb0e-0e7e-4d4d-85ed-70b16a9dc751

```php
<?php

final class DemoFile
{
    private string $currentClassName;
    
    public function __construct()
    {
        $this->currentClassName = static::class;
    }
}
```

becomes

```php
<?php

final class DemoFile
{
    private string $currentClassName = static::class;
}
```

### Responsible rules

* `InlineConstructorDefaultToPropertyRector`

## Expected Behavior

Should ignore static:: and parent:: assignments.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
For `parent::class` , it seems same result, ref https://3v4l.org/VRcS0 vs https://3v4l.org/D9vqX, what your use case? Could you create failing test case for it? Thank you.
