### ISSUE TITLE
Allow adding new line after adding a trait use statement.

### ISSUE THREAD

**Issue by mglaman** [rectorphp/rector#7416]
# Feature Request

AddProphecyTraitRector adds the ProphectTrait at the beginning of a class, but does add a newline. This can prevent a new line from appearing before the doc block of a property or method.

See https://www.drupal.org/project/rector/issues/3301487

Maybe \Rector\Core\NodeManipulator\ClassInsertManipulator::addTraitUse needs a param for adding a ` new Node\Stmt\Nop()` after the trait? Which could be difficult if `addAsFirstTrait` tries to add it before any other trait.
 
## Diff 

```diff
+++ b/tests/src/Kernel/AdminUIHandlerTest.php
@@ -11,6 +17,7 @@ use Drupal\KernelTests\KernelTestBase;
 class AdminUIHandlerTest extends KernelTestBase {
 
+  use ProphecyTrait;
   /**
    * Modules to enable.
    *
```

**Comment by samsonasik** [comment]
I think you can implement your own custom rector rule for that, or use coding standard tool for it, as different project usually has different cs rule.

Just in case you want the existing common new line after stmt rector rule, you can try `NewlineAfterStatementRector`, that's doesn't solve your requirement, but that's a common usage to tidify the code after running rector

https://github.com/rectorphp/rector/blob/d94a78124e59fb7b6f61e9dee0176a304c695788/rules/CodingStyle/Rector/Stmt/NewlineAfterStatementRector.php#L36

**Comment by TomasVotruba** [comment]
> Maybe \Rector\Core\NodeManipulator\ClassInsertManipulator::addTraitUse needs a param for adding a new Node\Stmt\Nop() after the trait? Which could be difficult if addAsFirstTrait tries to add it before any other trait.

What is there is already a trait and people coding standard stacks them up?

```diff
+use NewTrait;

 use ExistingTrait;
 use AnotherExistingTrait;
```

Then we have inversed problem of "how not to add the space" :)

That's why you should always run your own coding standard after Rector run.

**Comment by mglaman** [comment]
I think I might just implement a post-rector for drupal-rector to do this, if it has been added. we're trying to distribute automated patches to all projects (10,000+) and we don't run phpcs/phpcbf to reduce number of changes. so I'm thinking a post-rector would be easiest for an isolated fix. 

Thanks! It's a specific ask, but wanted to see.

**Comment by TomasVotruba** [comment]
I see. In that case the PostRector seems best way to go :+1:
