### ISSUE TITLE
Ignoring files when using --config flag

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7420]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14             |

`rector --config /some/dir/rector.php /part/of/my/project`

in rector.php `__DIR__` refers to the path of the config file (https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md)

There is currently no (reliable) way I found to get the path of the "src" `/part/of/my/project` inside the rector.php via `$rectorConfig`.
A workaround is to use `$_SERVER['argv']` in it, but since "src" does not have a flag (e.g. `--src`) it is not reliable to get the path (it works in most cases, but it's hacky and error prone if someone passes and superfluous args)

**Comment by TomasVotruba** [comment]
If you have config in different paths, and Rector in different paths and your project in another path, these errors will keep hapenning naturally. 

The best practise is to keep `rector.php` in root of your project along with installed Rector dependency. This way you'll avoid more problems with path juggling.

**Comment by kkmuffme** [comment]
They won't. Every tool (psalm, phpstan, phpcs) work perfectly fine in this exact scenario (been using them for years in this config, just recently found rector)

>The best practise is to keep rector.php in root of your project along with installed Rector dependency. This way you'll avoid more problems with path juggling.

- I don't want to create tons of duplicate rector.php files when I have 53 projects and a copy of rector.php in every one. This is a nightmare to maintain.
- I can't pollute the project root of every project with random code style config files.
- this exact problem also happens when rector.php is in the project root:

project/
- rector.php
- someDir/
- otherDir/

`vendor/bin/rector process otherDir`

How would I be able to know if we run rector for "someDir" or "otherDir" in rector.php? (since `__DIR__` is `/project` in rector.php)

**Comment by TomasVotruba** [comment]
You can check the skipper component, maybe there is a way to handle your files.

**Comment by kkmuffme** [comment]
You mean $rectorConfig->skip? That's exactly what I want to use, but I need to know "src" which is not reliable to get atm.

**Comment by TomasVotruba** [comment]
I'd try debugging it, if there is a way to use relative path, or end suffix.

We use it even in here: https://github.com/rectorphp/rector-src/blob/main/rector.php#L60

**Comment by kkmuffme** [comment]
Yes, that's what I ended up doing now. It has some small performance penalties, but alas...

**Comment by lucidprojects** [comment]
What was the solution here?   I am having a similar issue where rector is skipping files but all of mine are in the same root dir.

this is my cmd
`vendor/bin/rector process --config rectorMYSQLI_ONLY.php lib/classes/bp_class.php --dry-run`

Where bp_class.php has changes that need to be made but they are skipped.

The config file is a slightly modified version of this:  config/set/mysql-to-mysqli.php

**Comment by lucidprojects** [comment]
Apologies.  I see I need `--config=` I was missing the "=".  Sorry to clog the stream
