### ISSUE TITLE
Incorrect behavior of AddDoesNotPerformAssertionToNonAssertingTestRector when calling abstract function

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector#7421]
# Bug Report
When using `AddDoesNotPerformAssertionToNonAssertingTestRector` it will add a `@doesNotPerformAssertions` to my test function `testTrue` while it does preform assertions in `handleAssert`. But because i'm calling a abstract function it wont see that and adds the `@doesNotPerformAssertions`

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/058d70b8-e8a8-471d-bbb1-bf51798924e2

```php
<?php

declare(strict_types=1);

namespace App\Tests\Unit;

use Exception;
use PHPUnit\Framework\TestCase;

class CustomTestCase extends TestCase
{
    /**
     * Refresh test fixtures.
     */
    abstract protected function refreshFixtures(): void;
}

final class TrueTest extends CustomTestCase
{
    /**
     * @dataProvider trueProvider
     */
    public function testTrue(bool $bool): void
    {
        $this->refreshFixtures();
        $bool = $this->findBoolean($bool);

        $this->handleAssert($bool);
    }

    /**
     * @return bool[]
     */
    public function trueProvider(): array
    {
        return [
            [true],
        ];
    }

    /**
     * @thorws \Exception
     */
    private function findBoolean(bool $bool): bool
    {
        if (false === $bool) {
            throw new Exception('we want true.');
        }

        return $bool;
    }

    private function handleAssert(bool $bool): void
    {
        // some generic function that can be used for multiple test to do the same assertions.
        self::assertTrue($bool);
    }

    protected function refreshFixtures(): void
    {
        // TODO: Implement refreshFixtures() method.
    }
}
```

### Responsible rules

* `AddDoesNotPerformAssertionToNonAssertingTestRector`

## Expected Behavior

I would expect `@doesNotPerformAssertions` not to be added as is is performing assertions in function call

**Comment by samsonasik** [comment]
the test is calling another method, that's why it is not detected, I think you can just skip it with : 

```php
$rectorConfig->skip([
   \Rector\PHPUnit\Rector\ClassMethod\AddDoesNotPerformAssertionToNonAssertingTestRector::class
]);
```

for it.

**Comment by JohJohan** [comment]
> the test is calling another method, that's why it is not detected, I think you can just skip it with :
> 
> ```
> $rectorConfig->skip([
>    \Rector\PHPUnit\Rector\ClassMethod\AddDoesNotPerformAssertionToNonAssertingTestRector::class
> ]);
> ```
> 
> for it.

@samsonasik that is not the problem as you can see here https://getrector.org/demo/c76191be-7df3-4c38-bcd7-0324544ae6c2 it didn't make the changes.

I think it has something to do with the abstract function. And i would like to use the rule. I think there is a bug as i'm doing assertions and rector is appling `@doesNotPerformAssertions`.

Also i think this issue should be moved to https://github.com/rectorphp/rector-phpunit as it has to do with phpunit.

**Comment by samsonasik** [comment]
In your last case, the `refreshFixtures()` method never exists, that's why it is skipped.

When calling different method, eg from different class, it will be dynamic as is, that's why it apply it.

If the assertion is only verify bool, you don't need to call other method `$this->handleAssert($bool);`, if you just call directly `self::assertTrue($bool);`, it will be skipped, ref https://getrector.org/demo/d72d6526-25e2-4786-b941-058451ae28e6

**Comment by JohJohan** [comment]
@samsonasik correct, i should have linked to the original demo url: https://getrector.org/demo/058d70b8-e8a8-471d-bbb1-bf51798924e2 here the function exists.

I know i can simplfy my code its just example code. The case i have is that i have multiple tests that use a function like `handleAssert` so i dont have duplicate asserts. Problem is if i run rector iit will add the anotation and when i run phpunit it will metion it has a param `@doesNotPerformAssertions ` which is invalid because the function does make assertions

**Comment by samsonasik** [comment]
Feel free to create feature PR for that, you can loop the stmts if that Expression, check if Expression expr is MethodCall/StaticCall, get the source ClassMethod, loop the Expression, check if there is assert method there.

You may use AstResolver for that https://github.com/rectorphp/rector-src/blob/a75e56071aaf22d6751d2501b30272e7185e4873/src/PhpParser/AstResolver.php#L133

**Comment by JohJohan** [comment]
@samsonasik i had a look and came to this code: https://github.com/rectorphp/rector-phpunit/pull/110/files i dont know why the max limit is now on 3 but increasing it fixes my bug maybe we should ask @TomasVotruba why it was set to 3 and not for example 255 or something?

**Comment by TomasVotruba** [comment]
@JohJohan In a project we tested this rule on this lead to infinity loops, as some asserts jumped in circles. But that was ~3 years ago and this are got lot of improvements.

I think it's safe to go to 5. Could you send a PR?

**Comment by JohJohan** [comment]
@TomasVotruba sounds good! Thanks for quick reply
