### ISSUE TITLE
Pass paths via CLI

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7422]
Is there a best practice on how to use rector in CI?

There seems to be no way to pass a file/list of files/directories to rector via CLI directly - always has to go through rector.php, which is a PITA to set up in CI to run for specific files only depending on conditions available in CI (but not passable to rector.php)

I don't want to run rector on a whole directory (performance...), I only want to check/fix files modified in the current branch as part of CI/PR checks.

**Comment by TomasVotruba** [comment]
Always run Rector on the whole project. Otherwise it can detect some method as unused and removed.

See https://phpstan.org/blog/why-you-should-always-analyse-whole-project

**Comment by kkmuffme** [comment]
I have stubs for everything I don't want to run on (for phpstan/psalm)
e.g. for phpstan compare how much slower it is for running it for a whole, big project compared to only specified files + rest is stubbed (with blackfire/tideways) If you have multiple teams of developers, running phpstan (or probably rector too, not benchmarked yet) on the whole project for every CI run you probably need twice the amount of CI time/servers you currently have. This is cost prohibitive (and a huge waste of electricity)

**Comment by TomasVotruba** [comment]
I'd only repeat the post. We run on top of PHPStan and inherits its workflow.
