### ISSUE TITLE
Incorrect behavior of DowngradeTrailingCommasInParamUseRector + DowngradeParameterTypeWideningRector

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#7423]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/03929096-8d31-4b8c-b0d1-2de10e4f19f9

```php
<?php

class ParentClass
{
    public function execute(
        string $param, // This code must be downgraded with 2 rules
    ): void {
    }
}

class ChildClass extends ParentClass
{
    public function execute(
        $param
    ): void {
    }
}
```

### Responsible rules

* `DowngradeTrailingCommasInParamUseRector`
* `DowngradeParameterTypeWideningRector`

## Expected Behavior

The PHP code `string $param,` above contains two features to downgrade:

- Removing the trailing comma
- Removing the `string` type

When running `DowngradeTrailingCommasInParamUseRector` alone, it works well (https://getrector.org/demo/c420a192-6e01-40ca-a7ac-a47a7bdc7c09).

When running `DowngradeParameterTypeWideningRector` alone, it works well (https://getrector.org/demo/89118419-e522-460b-8477-f219dd522a21).

But when running both `DowngradeTrailingCommasInParamUseRector` and `DowngradeParameterTypeWideningRector`, only `DowngradeTrailingCommasInParamUseRector` is applied (https://getrector.org/demo/8e7337b5-c0d4-49dd-8f3b-3491850a5d5f).

This is the diff with how the result should be:

```diff
class ParentClass
{
-    public function execute(string $param): void {
+    public function execute($param): void {
    }
}

class ChildClass extends ParentClass
{
    public function execute($param): void {
    }
}
```

**Comment by samsonasik** [comment]
it seems working when the order is flipped

```php
    $rectorConfig->rule(DowngradeParameterTypeWideningRector::class);
    $rectorConfig->rule(DowngradeTrailingCommasInParamUseRector::class);
```

ref https://getrector.org/demo/89c9d3e8-87a4-41af-a0d3-d5aeeeadef56

**Comment by leoloso** [comment]
To mention: The error happens when executing the set `DowngradeLevelSetList::DOWN_TO_PHP_71` (I don't know how the order there is computed)

**Comment by TomasVotruba** [comment]
> it seems working when the order is flipped

The order should not be relevant here as user cannot possibly think about it.
The design of `DowngradeTrailingCommasInParamUseRector` somehow removes the type information.

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-src/pull/2843 for it.
