### ISSUE TITLE
Incorrect behavior of AddDoesNotPerformAssertionToNonAssertingTestRector

### ISSUE THREAD

**Issue by tmvpobeda** [rectorphp/rector#7425]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/b6cb8b47-5d15-4dac-9b09-d59a918919ff

```php
<?php

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class Factory
{
    public function create(): \stdClass
    {
        return new \stdClass();
    }
}

final class DemoTest extends WebTestCase
{
    public function testCreate(): void
    {
        $this->expectNotToPerformAssertions();
        
        $factory = new Factory();

        $factory->create();
    }
}
```

### Responsible rules

* `AddDoesNotPerformAssertionToNonAssertingTestRector`

## Expected Behavior

```php
final class DemoTest extends WebTestCase
{
    /**
     * @doesNotPerformAssertions
     */
    public function testCreate(): void
    {
        $factory = new Factory();

        $factory->create();
    }
}
```

**Comment by samsonasik** [comment]
I never use the `expectNotToPerformAssertions()` iirc, is the docblock superior over method call? If no, it should be skipped as already applied the expected result.
