### ISSUE TITLE
Make RenameParamToMatchTypeRector configurable to exempt classes

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7427]
# Feature Request

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renameparamtomatchtyperector

A configurable rule would be great to exempt some classes.
Why? I would like to exempt `stdClass` from this rule, as the code might become less readable if variable is changed to `$stdClass` (vs `$purchaseData`)

EDIT: the example with the stdClass might be a bit dumb, but it's the most general one I came up with. In reality it's more about class names from libraries that have a variety of issues (spelling, bad naming,...)

**Comment by samsonasik** [comment]
stdClass is already skipped, ref https://getrector.org/demo/37675422-ad0f-45aa-93f0-da8657ee7689

**Comment by kkmuffme** [comment]
I know, that's why my EDIT: on the OP.
It's more about adding lib classes to that list
