### ISSUE TITLE
RenamePropertyToMatchTypeRector variable name options

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7428]
# Feature Request

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renamepropertytomatchtyperector

Would it be possible to make this configurable to not use camelCase variable names but underscore?
This is required for WordPress coding standards https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#naming-conventions

Code would look something like:

```php
$variable = preg_replace_callback( 
	'/(^|[a-z0-9])([A-Z])/', 
	function ( $match ) {
		$new_variable = empty( $match[1] ) ? '' : $match[1] . '_';
		
		return $new_variable . strtolower( $match[2] );
	},
	$variable
);
```

**Comment by samsonasik** [comment]
You can create your own custom Rector rule for that.

**Comment by kkmuffme** [comment]
I could, however this is a general issue that everybody using rector with WordPress (and codeiginiter,...) has and not something specific to my codebase.

I stumbled upon rector via a blog post that talked about upgrading WP for compatibility with new PHP versions with rector, therefore I thought it might make sense to have this rule configurable so it actually works for WordPress.

**Comment by TomasVotruba** [comment]
The best way is to create WordPress Rector rules maintained by WordPress community 👍 

That way you can build up rule set specific and benefiting to your group.
