### ISSUE TITLE
Is it an unless array casting?

### ISSUE THREAD

**Issue by maidmaid** [rectorphp/rector#743]
```
➜  vendor/bin/rector process src --dry-run --level php71
...
    ---------- begin diff ----------
--- Original
+++ New
@@ -45,6 +45,7 @@
         $result = array();
         foreach ($nodes as $node) {
+            $result = (array) $result;
             $result[] = array(
                 'children' => $node->hasChildren(),
                 'id' => $node['id'],
    ----------- end diff -----------
```

**Comment by TomasVotruba** [comment]
That should not happen. Could you provide more context of the file?

I tried running this snippet only and it passes without error.

**Comment by maidmaid** [comment]
Even with a minimal example, I have this problem :
```diff
 <?php

 $a = [];
+$a = (array) $a;
 $a[] = 1;
```

**Comment by TomasVotruba** [comment]
I can simulate it now too.

**I wonder, is the file autoloaded?**

It a required so PHPStan can analyse it and know it's already an `array` type.

**Comment by maidmaid** [comment]
If it's more complicated as expected, should we remove temporarily this rule from the php71 level ?

**Comment by TomasVotruba** [comment]
No, just autoload the file. Rector won't work without access to files and classes.

**Comment by maidmaid** [comment]
I'm not sure to understand your answer. If I do ``vendor/bin/rector process test.php --level php71 --autoload-file test.php``, it's the same result.

**Comment by TomasVotruba** [comment]
Yes, that's what I meant and should work. I'll investigate.

What version of `phpstan/phpstan` do you have installed?

```
composer show phpstan/phpstan
```

**Comment by maidmaid** [comment]
0.10.5 (c6a8cd1fe08a23b9d101a55ffa9ff6b91d71ef5d)
Thanks for your help :)
