### ISSUE TITLE
PHP 8.1 notices 

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7430]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.14              |

## Minimal PHP Code Causing Issue

- all rules enabled
- run rector with PHP 8.1 CLI

```
Constant FILE_TEXT is deprecated
phar:.../vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubs/CachingVisitor.php on line 162
Constant FILE_BINARY is deprecated
File: phar:.../vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubs/CachingVisitor.php on line 162

Since symfony/console 6.1: Relying on the static property $defaultName for setting a command name is deprecated. Add the RectorPrefix202208/Symfony/Component/Console/Attribute/AsCommand attribute to the RectorPrefix202208/Symfony/Component/Console/Command/DumpCompletionCommand class instead.
File: .../vendor/rector/rector/vendor/symfony/contracts/Deprecation/function.php on line 26
Since symfony/console 6.1: Relying on the static property $defaultDescription for setting a command description is deprecated. Add the RectorPrefix202208/Symfony/Component/Console/Attribute/AsCommand attribute to the RectorPrefix202208/Symfony/Component/Console/Command/DumpCompletionCommand class instead.
File: .../vendor/rector/rector/vendor/symfony/contracts/Deprecation/function.php on line 26
```

There may be more, I just grabbed the first I saw. Since they are in dependencies inside of rector I thought I report it here then upstream

**Comment by samsonasik** [comment]
Could you narrow it down to specific rules and the code that cause it? For multiple rules applied, you can create failing test case PR to
https://github.com/rectorphp/rector-src/tree/main/tests/Issues

You can copy and modify on of the tests

**Comment by TomasVotruba** [comment]
This has to be solved in the project themselves. We only use those here :)

**Comment by kkmuffme** [comment]
The phpstan dependency one I reported there, but the symfony is a bug in rector itself bc it seems rector uses symfony in a deprecated way:

```
Since symfony/console 6.1: Relying on the static property $defaultDescription for setting a command description is deprecated. Add the RectorPrefix202208\Symfony\Component\Console\Attribute\AsCommand attribute to the RectorPrefix202208\Symfony\Component\Console\Command\DumpCompletionCommand class instead.
File: .../vendor/rector/rector/vendor/symfony/contracts/Deprecation/function.php on line 26
CLI Argv
Array(
  [0] => .../vendor/bin/rector
  [1] => process
  [2] => --config
  [3] => .../rector.php
  [4] => /project/src
)
Trace:
#0 .../vendor/rector/rector/vendor/symfony/contracts/Deprecation/function.php (26): trigger_error( $message = Since symfony/console 6.1: Relying on the static property $defaultDescription for setting a command description is deprecated. Add the RectorPrefix202208\Symfony\Component\Console\Attr... TRUNCATED, $error_level = 16384 )
#1 .../vendor/rector/rector/vendor/symfony/console/Command/Command.php (129): RectorPrefix202208\trigger_deprecation( $package = symfony/console, $version = 6.1, $message = Relying on the static property $defaultDescription for setting a command description is deprecated. Add the %s attribute to the %s class instead., $args = RectorPrefix202208\Symfony\Component\Console\Attribute\AsCommand, RectorPrefix202208\Symfony\Component\Console\Command\DumpCompletionCommand )
#2 .../vendor/rector/rector/vendor/symfony/console/Command/Command.php (152): RectorPrefix202208\Symfony\Component\Console\Command\Command::getDefaultDescription()
#3 .../vendor/rector/rector/vendor/symfony/console/Application.php (945): RectorPrefix202208\Symfony\Component\Console\Command\Command->__construct()
#4 .../vendor/rector/rector/vendor/symfony/console/Application.php (1090): RectorPrefix202208\Symfony\Component\Console\Application->getDefaultCommands()
#5 .../vendor/rector/rector/vendor/symfony/console/Application.php (481): RectorPrefix202208\Symfony\Component\Console\Application->init()
#6 .../vendor/rector/rector/vendor/symfony/console/Application.php (468): RectorPrefix202208\Symfony\Component\Console\Application->add( $command = Rector\RectorGenerator\Command\GenerateCommand Object )
#7 .../vendor/rector/rector/src/Console/ConsoleApplication.php (28): RectorPrefix202208\Symfony\Component\Console\Application->addCommands( $commands =
Array(
  [0] => Rector\RectorGenerator\Command\GenerateCommand Object
  [1] => Rector\RectorGenerator\Command\InitRecipeCommand Object
  [2] => Rector\Core\Console\Command\InitCommand Object
  [3] => Rector\Core\Console\Command\ProcessCommand Object
  [4] => Rector\Core\Console\Command\WorkerCommand... TRUNCATED
)
#8 [callback of next frame] (-1): Rector\Core\Console\ConsoleApplication->__construct( $commands =
Array(
  [0] => Rector\RectorGenerator\Command\GenerateCommand Object
  [1] => Rector\RectorGenerator\Command\InitRecipeCommand Object
  [2] => Rector\Core\Console\Command\InitCommand Object
  [3] => Rector\Core\Console\Command\ProcessCommand Object
  [4] => Rector\Core\Console\Command\WorkerCommand... TRUNCATED
)
#9 .../vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php (894): ReflectionClass->newInstanceArgs( $args =
Array(
  [0] => Array(
      [0] => Rector\RectorGenerator\Command\GenerateCommand Object
      [1] => Rector\RectorGenerator\Command\InitRecipeCommand Object
      [2] => Rector\Core\Console\Command\InitCommand Object
      [3] => Rector\Core\Console\Command\ProcessCommand Object
      [4] => Recto... TRUNCATED
)
#10 .../vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php (490): RectorPrefix202208\Symfony\Component\DependencyInjection\ContainerBuilder->createService( $definition = RectorPrefix202208\Symfony\Component\DependencyInjection\Definition Object, $inlineServices =
Array(
  [Rector\RectorGenerator\TemplateFactory] => Rector\RectorGenerator\TemplateFactory Object
  [Rector\RectorGenerator\FileSystem\ConfigFilesystem] => Rector\RectorGenerator\FileSystem\ConfigFilesystem Object
  [RectorPrefix202208\Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory] => R... TRUNCATED
, $isConstructorArgument = TRUE (bool), $id = Rector\Core\Console\ConsoleApplication )
#11 .../vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php (441): RectorPrefix202208\Symfony\Component\DependencyInjection\ContainerBuilder->doGet( $id = Rector\Core\Console\ConsoleApplication, $invalidBehavior = 1 )
#12 .../vendor/rector/rector/bin/rector.php (127): RectorPrefix202208\Symfony\Component\DependencyInjection\ContainerBuilder->get( $id = Rector\Core\Console\ConsoleApplication )
#13 .../vendor/rector/rector/bin/rector (5): require_once( .../vendor/rector/rector/bin/rector.php )
#14 .../vendor/bin/rector (120): include( .../vendor/rector/rector/bin/rector )
```

**Comment by TomasVotruba** [comment]
The `DumpCompletionCommand` is a Symfony command.

**Comment by kkmuffme** [comment]
Thanks, I reported both. 
For the moment this means Rector is not compatible with PHP8.1 though, as even the most minimalistic config (any rule) has PHP notices.

3 line rector.php for confirming this issue:

```php
return static function (\Rector\Config\RectorConfig $rectorConfig): void {
    $rectorConfig->rule(\Rector\CodeQuality\Rector\Include_\AbsolutizeRequireAndIncludePathRector::class);
};
```

**Comment by stof** [comment]
In Symfony, the attribute is there: https://github.com/symfony/symfony/blob/ddaedd28bd2e4fc22b64567753cf934fe9d68c4c/src/Symfony/Component/Console/Command/DumpCompletionCommand.php#L27

**Comment by TomasVotruba** [comment]
So is in Rector: https://github.com/rectorphp/rector/blob/main/vendor/symfony/console/Command/DumpCompletionCommand.php#L25

But Symfony checks the static property that is being downgraded to PHP 7.2. That's side effect of downgrade.

What can we do about it here?

**Comment by TomasVotruba** [comment]
> For the moment this means Rector is not compatible with PHP8.1 though, as even the most minimalistic config (any rule) has PHP notices.

It is :). The deprecation on framework side is false positive here.

**Comment by TomasVotruba** [comment]
@kkmuffme How does it change if you comment this line?
 
https://github.com/rectorphp/rector/blob/1d28ca109ca536e8034c3c756ee61c65e6e63c8a/vendor/symfony/contracts/Deprecation/function.php#L26

We do not really need to bubble up Symfony deprecations to Rector release, so removing this function seems the way to go.

**Comment by kkmuffme** [comment]
@TomasVotruba yes, then that notice is gone for symfony. 
Could you please reopen this issue?

===

phpstan notice:
the line numbers don't match up with the latest phpstan version at all, is rector on the latest phpstan version? (as the issue might be fixed there already)

===

There are 2 phpstan.phar in rector, is this on purpose?
rector/vendor/bin/phpstan.phar
rector/vendor/phpstan/phpstan/phpstan.phar

**Comment by TomasVotruba** [comment]
Could you create a new issue with the Symfony notice only? To keep it clean

**Comment by stof** [comment]
@TomasVotruba if you want to support PHP 7.2, why not using the Symfony 5.4 LTS which supports PHP 7.2 and so does not deprecate features that are necessary when using PHP 8- due to not being able to use attributes ?

**Comment by kkmuffme** [comment]
@TomasVotruba phpstan issue is also fixed:
https://github.com/phpstan/phpstan/issues/7873

Does rector use a custom error handler that picks this up despite snoozed/@ ?

**Comment by TomasVotruba** [comment]
@stof Because we run on Symfony 6 with most of the deps already. It's easier for us to the use latest deps in general.

**Comment by TomasVotruba** [comment]
@kkmuffme That would be here https://github.com/rectorphp/rector-src/blob/58a577c5b3d34cc70ba6ea713e7a6c7bbe66354e/src/Application/ApplicationFileProcessor.php#L192

**Comment by TomasVotruba** [comment]
@kkmuffme > There are 2 phpstan.phar in rector, is this on purpose? 

The `vendor/bin/` in composer is usually simlinked bin files from the package itself.

**Comment by kkmuffme** [comment]
@TomasVotruba https://github.com/rectorphp/rector/issues/7430#issuecomment-1230239681 What's your suggestion?
rector will throw 100s of notices with PHP 8.1 due to this

>This has to be solved in the project themselves. We only use those here :)

😁

**Comment by TomasVotruba** [comment]
@kkmuffme I'd try to debug the error handler, why it passed your notices :)

They seems skipped: https://github.com/rectorphp/rector-src/blob/58a577c5b3d34cc70ba6ea713e7a6c7bbe66354e/src/Application/ApplicationFileProcessor.php#L183
