### ISSUE TITLE
Nested ternary expressions are depreceted since 7.4

### ISSUE THREAD

**Issue by fruitl00p** [rectorphp/rector#7432]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12            |

We're trying to upgrade  a project from PHP 7.4 to 8.1 and came across a nested ternary expression which will error out in later PHP versions (8.0+)

## Minimal PHP Code Causing Issue
```php
    function nested_ternary()
    {
      $a = 1;
      $b = 2
      $value = $a ? $b : $a ?: null;
   }
```
## Expected Behaviour

Since the interpreter used to have some sort of handling it. It might be right to assume the previous working and give some sort of notice to recheck it manually? but also change it according to the previous handling (by adding parathesis RTL):
```php
    function nested_ternary()
    {
      $a = 1;
      $b = 2
      $value = ($a ? $b : $a) ?: null;
   }
```

**Comment by kkmuffme** [comment]
I guess it much rather not be a ternary here whatsoever for readability

**Comment by fruitl00p** [comment]
> I guess it much rather not be a ternary here whatsoever for readability

Thats a whole other story. The given example is a bit contrived, but it works in 7.4 and fatals in 8... Thus I would've expected Rector to atleast give me notice on this specific issue when running with the `LevelSetList::UP_TO_PHP_81` config...

**Comment by samsonasik** [comment]
For that, that's seems need new php 7.4 rector rule, eg: `ParenthesizeNestedTernaryRector`, will you create new rule PR for it? thank you.

For token check, you may need to create tokenizer service to detect if it already parentheses exists, ref https://github.com/rectorphp/rector-src/blob/58a577c5b3d34cc70ba6ea713e7a6c7bbe66354e/rules/Php74/Tokenizer/FollowedByCurlyBracketAnalyzer.php#L10
