### ISSUE TITLE
PHP 8.1 Symfony notice

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7434]
```
Since symfony/console 6.1: Relying on the static property $defaultName for setting a command name is deprecated. Add the RectorPrefix202208/Symfony/Component/Console/Attribute/AsCommand attribute to the RectorPrefix202208/Symfony/Component/Console/Command/DumpCompletionCommand class instead.
File: .../vendor/rector/rector/vendor/symfony/contracts/Deprecation/function.php on line 26
Since symfony/console 6.1: Relying on the static property $defaultDescription for setting a command description is deprecated. Add the RectorPrefix202208/Symfony/Component/Console/Attribute/AsCommand attribute to the RectorPrefix202208/Symfony/Component/Console/Command/DumpCompletionCommand class instead.
File: .../vendor/rector/rector/vendor/symfony/contracts/Deprecation/function.php on line 26
```

See https://github.com/rectorphp/rector/issues/7430#issuecomment-1229921696

**Comment by TomasVotruba** [comment]
The goal of new issue is not to jump back and forth. Now it's unclear if where the discussion goes. 

Could you form an issolate issue with exact steps to solve?

**Comment by kkmuffme** [comment]
https://github.com/rectorphp/rector/blob/1d28ca109ca536e8034c3c756ee61c65e6e63c8a/vendor/symfony/contracts/Deprecation/function.php#L26

We do not really need to bubble up Symfony deprecations to Rector release, so removing this function seems the way to go.

Comment this line/empty this function will fix (= ignore) this issue.

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector/commit/19fe61ce3e920eeb2fec6d2c3704814866592649
