### ISSUE TITLE
SplitDoubleAssignRector creates bad code

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7435]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.14             |

## Minimal PHP Code Causing Issue

SplitDoubleAssignRector
https://getrector.org/demo/29717998-4b0e-4cde-bfaf-e73fa0de3593

```
$foo = $bar = $hello = $world = '';
```

After having to run x times until "Rector is done", rector has created this 😂

```
$foo = '';
$world = '';
$hello = '';
$world = '';
$bar = '';
$world = '';
$hello = '';
$world = '';
```

## Expected Behaviour

```
$foo = '';
$bar = '';
$hello = '';
$world = '';
```

This rule atm works exactly for 1 case, where you have exactly 2 variables:
https://getrector.org/demo/22e389bd-4614-4635-929d-59d9f03e3bf6

**Comment by TomasVotruba** [comment]
Thanks :clap: 

Could you add test fixture to `SplitDoubleAssignRectorTest` with the 1st demo link?

**Comment by kkmuffme** [comment]
Not atm, as I have too many pending PRs with psalm I should fix first and don't have time to fork rector and create it right now.

**Comment by TomasVotruba** [comment]
Take your time :+1:

**Comment by kkmuffme** [comment]
Just realized we don't need this rule at all, since there's a phpcs/phpcbf rule that works and does exactly that in one run internally, correctly already.
