### ISSUE TITLE
Errors only partially fixed

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7436]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14             |

NewlineAfterStatementRector
=> the newline is only applied to changes done by rector on the next run in some (?) cases.

## Expected Behaviour

All other auto-fix tools (phpcbf, psalter) will rerun internally until all fixable issues are fixed. Perhaps this is something rector wants to do?

If not, it would be nice if you could at least document this somewhere prominently - that rector will/may not fix all errors in 1 run, but might need multiple runs.

Related https://github.com/rectorphp/rector/issues/7435, which also requires tons of reruns in some cases (even though it could be made to work in 1 go)

**Comment by TomasVotruba** [comment]
I don't understand what this means. This definitely requires a test fixture or a reproducible repository on Github. It would require investment of your time, we're unable to do anything now.

Let's get back to this when you're free :+1:

**Comment by kkmuffme** [comment]
I already have a workaround in CI, I don't care if you fix this issue for other users.

**Comment by TomasVotruba** [comment]
We use this rule in Rector CI and don't experience this at all. That's why the reproducer is needed.
