### ISSUE TITLE
Unexpected token "", expected '*/' at offset 3

### ISSUE THREAD

**Issue by velkony** [rectorphp/rector#744]
Hi,
after I started rector I got the following error:
`[ERROR] Could not process "/var/www/...php" file, due to: "Unexpected token "", expected '*/' at offset 3". `

What this error means?

**Comment by TomasVotruba** [comment]
Hi, the file has probably invalid syntax or a syntax Rector can't process now.

What's the file content?

**Comment by TomasVotruba** [comment]
Closing for missing code sample causing this

**Comment by LeonidasJP** [comment]
For people landing on this issue: I received this error while refactoring my Symfony 2.8-application to 3.4, and the PhpDoc Parser seems to be struggling when you have HTML embedded in the DocBlock.

Eg, this gets parsed properly:

```
/**
 * Just a regular DocBlock
 */
```

But this doesnt:
```
/**
 * Just a regular DocBlock <strong>with some formatting for some ApiDoc-generator</strong>
 */
```
