### ISSUE TITLE
Incorrect behavior of RemoveAlwaysTrueIfConditionRector

### ISSUE THREAD

**Issue by Lenny4** [rectorphp/rector#7440]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |
| PHP version   | 8.1  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/52d9f84d-3203-44ee-9295-b7e2dc909b02

```php
<?php

class FDocentete
{
    public function __construct(private string $doPiece)
    {
    }

    public function getDoPiece(): ?string
    {
        return $this->doPiece;
    }

    public function setDoPiece(?string $doPiece): self
    {
        $this->doPiece = $doPiece;
        return $this;
    }
}

class GetFDocentetesController
{
    public static function test()
    {
        $fDoclignes = [
            ['doPiece' => '1']
        ];
        $fDocentetes = [
            new FDocentete('1'),
            new FDocentete('2'),
        ];
        /** @var FDocentete $currentFDocentete */
        $currentFDocentete = null;
        foreach ($fDoclignes as $fDocligne) {
            if (is_null($currentFDocentete) || $currentFDocentete->getDoPiece() !== $fDocligne['doPiece']) {
                if (!is_null($currentFDocentete)) {
                    echo 'I echo here';
                }
                $currentFDocentete = current(array_filter($fDocentetes, static fn(FDocentete $fDocentete) => $fDocentete->getDoPiece() === $fDocligne['doPiece']));
            }
        }
    }
}

GetFDocentetesController::test();
```

### Responsible rules

* `RemoveAlwaysTrueIfConditionRector`

## Expected Behavior

Rector should not remove this if condition.

I have created 2 tests:
- the first one with the if condition
- the second without the if condition

In the first test I have no output: https://onlinephp.io/c/0cbc3

In the second test I have an output: https://onlinephp.io/c/57c42

**Comment by samsonasik** [comment]
Please create failing test PR for it, you can click "Create a Test" button at demo page

**Comment by Lenny4** [comment]
@samsonasik 
Here is the PR: https://github.com/rectorphp/rector-src/pull/2863
