### ISSUE TITLE
Incorrect behavior of RemoveAlwaysElseRector

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7441]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/eb0f5c8f-86e3-40ed-bb38-86675496f0c8

```php
<?php

final class DemoFile
{
    public function run()
    {
        if ( rand( 0, 5 ) > 2 ) {
 	       return;
		} else { ?>
			this is <?php echo "hello"; ?> world
		<?php }
    }
}
```

### Responsible rules

* `RemoveAlwaysElseRector`

## Expected Behavior

Not create a fatal error

**Comment by samsonasik** [comment]
Please create failing test PR for it, you can click "Create a Test" button at demo page
