### ISSUE TITLE
RenameForeachValueVariableToMatchExprVariableRector does not regard iteration variable outside the loop

### ISSUE THREAD

**Issue by SantosSi** [rectorphp/rector#7442]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/90da132c-f8ba-499a-9aaf-7e23a2d807e7

```php
<?php

final class DemoFile
{
    public function run()
    {
        $numbers = ['one', 'two'];
        foreach ($numbers as $txt) {
            echo "This is number ".$txt;
        }
        unset($txt);
    }
}
```

### Responsible rules

* `RenameForeachValueVariableToMatchExprVariableRector`

## Expected Behavior

Should have changed $txt unset($txt) to unset($number). It should change that var name everywhere within the scope,

**Comment by samsonasik** [comment]
Please create failing test PR for it, you can click "Create a Test" button at demo page

**Comment by samsonasik** [comment]
it should be skipped instead.
