### ISSUE TITLE
AnnotationToAttributeRector with multiple annotations in one line

### ISSUE THREAD

**Issue by derrabus** [rectorphp/rector#7443]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  0.14.0 |

## Minimal PHP Code Causing Issue

In a codebase I'd like to modernize, several Doctrine entities contain annotated properties that look like this:

```php
/** @ORM\Id @ORM\Column(type = "integer", options = {"unsigned": true}) @ORM\GeneratedValue(strategy="AUTO") */
private $id;
```

If I run Rector with the `DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES` ruleset, those are changed to this:

```php
#[ORM\Id]
private $id;
```

Apparently, only the first annotation in that line is recognized and the others are ignored. However, if I manually change the docblock so that each annotation starts in its own line…

```php
/**
 * @ORM\Id
 * @ORM\Column(type = "integer", options = {"unsigned": true})
 * @ORM\GeneratedValue(strategy="AUTO") 
 */
private $id;
```

… the code is migrated correctly:

```php
#[ORM\Id]
#[ORM\Column(type: 'integer', options: ['unsigned' => true])]
#[ORM\GeneratedValue(strategy: 'AUTO')]
private $id;
```

## Expected Behaviour

The two code snippets (single-line and multi-line annotations) should be considered equal and yield the same result.

**Comment by samsonasik** [comment]
Annotation detection is by `PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTagNode` so I think it should be resolved in https://github.com/phpstan/phpdoc-parser instead.

**Comment by TomasVotruba** [comment]
Missl-ink :)

**Comment by derrabus** [comment]
I'm not sure that PHPStan's PHPDoc parser is the right choice here. Is is built for parsing PHPDoc-style annotations which work fundamentaly different than Doctrine-style annotations. The proper parser for the latter is `doctrine/annotations`. If there's something the Doctrine project can do to make this library usable for Rector, please tell me.

**Comment by TomasVotruba** [comment]
> The proper parser for the latter is doctrine/annotations. If there's something the Doctrine project can do to make this library usable for Rector, please tell me.

We used that before, but the parser is actually interpretter in one. It translates constants, autoloads classes and more.
We need static analysis, that's why the phpdoc-parser is the best choice :+1: 

Personally I'd replace the "}) @" with newlined version, as the code is very non-standard. It's first time I see such code. Most likely not worth to be supported. For these reasons, closing as won't fix.

**Comment by derrabus** [comment]
> We used that before, but the parser is actually interpretter in one. It translates constants, autoloads classes and more.

Okay, that's probably already the answer I was looking for. So the goal would be to expose an API that can be used for static analysis, without runtime reflection and without creating instances of the annotation classes.

> Personally I'd replace the "}) @" with newlined version,

On this particular codebase, I can very much do this. As far as I can tell, only four entities in total are affected. However, Symfony and Doctrine both have an interest in moving away from Doctrine Annotations and right now Rector is our best option for a migration path. This bug looks like an obstacle that we could get out of the way with the right parser.

**Comment by TomasVotruba** [comment]
> So the goal would be to expose an API that can be used for static analysis, without runtime reflection and without creating instances of the annotation classes.

That's first condition. The next one is to have ability replace any part of the docblock, e.g. true with false, and print back the content. Also the printer must have format preserving feature, to keep spaces, single/double quotes, newlines etc. That's the layer we have added in Rector above phpdoc/parser.

As the obstacle, understood. You can try to suggest such parsing in the package itself, but as I said, I think it will be declained as not worth the effort.

**Comment by derrabus** [comment]
> That's first condition. The next one is to have ability replace any part of the docblock, e.g. true with false, and print back the content. Also the printer must have format preserving feature, to keep spaces, single/double quotes, newlines etc. That's the layer we have added in Rector above phpdoc/parser.

Thanks, that helps a lot. :-)

> Personally I use php-cs-fixer rule set to keep the Doctrine annotations space in standard, so this is handled by the better fit tool.

PHP CS Fixer understands multiple annotations in a single line, but unfortunately it does not fix them to a multiline block. But maybe it's easier to contribute such a rule to PHP CS Fixer than to fix the parser.

**Comment by TomasVotruba** [comment]
> Thanks, that helps a lot. :-)

Glad it's more clear now :+1: 

> But maybe it's easier to contribute such a rule to PHP CS Fixer than to fix the parser.

Agreed, that's what I meant. It should be part of some standard set as of  PHP 8+.
