### ISSUE TITLE
AddInterfaceByTraitRector should not add an interface if already implemented

### ISSUE THREAD

**Issue by buffcode** [rectorphp/rector#7444]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.60            |

## Minimal PHP Code Causing Issue

- https://getrector.org/demo/fa13b771-ddad-4738-afda-8d891c313ccc
- Result with PHP 7.3: https://onlinephp.io?s=s7EvyCjg5eLlyswrSS1KS0xOVXDLz_eEc6p5uWpRpZ0SixDSqRUlqXkpxdj1lBQlZpaApELADJhwck5icTHIGIXM3IKc1NzUvJJiFFN1FGLQzVMAgtLiVLhh1kCzAA%2C%2C&v=7.3.33

## Expected Behaviour

Do not add interface if the class already implements that interface somehow (or make this behaviour configurable).

Up until PHP 7.3 this produces a fatal error: https://bugs.php.net/bug.php?id=63816

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.
