### ISSUE TITLE
Demo: Display "Create test case"/"Create issue" in "No changes" case

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7445]
# Feature Request

https://getrector.org/demo/20ec9b69-7b6a-4393-963e-7e0dc602ce65

It would make creating test case PRs for some bugs much easier, if it would show the "Create issue"/"Create test case" button in the case where it shows "No changes needed" too.

I want to create a test case for this (as there should be a change given the config/rule), but the button isn't there (and the button would make it much faster)

**Comment by samsonasik** [comment]
You're missing `<?php` open tag, if you add it, it will show the button, see https://getrector.org/demo/8acec504-37d5-46ba-9a5e-69465a405000

**Comment by TomasVotruba** [comment]
@samsonasik  I think the goal is to offer "Create "test" even in case of no change, e.g. here:
https://getrector.org/demo/3d4d81a3-f159-44f0-aaf0-2db5a95989b2

**Comment by samsonasik** [comment]
Oh, I see, re-open then.

**Comment by samsonasik** [comment]
@TomasVotruba creating an issue/test require applied rules, if no rules applied, then it doesn't know which rule to create issue/test.

**Comment by TomasVotruba** [comment]
I see :) in that case it's impossible to guess the rule. Anythign else would kill the simplicity and required manuall PR with test.

Thanks for verification :+1:
