### ISSUE TITLE
Supporting multiple PHP versions

### ISSUE THREAD

**Issue by davidwindell** [rectorphp/rector#7446]
# Question

Is it possible to use `LevelSetList::UP_TO_PHP_81` whilst only applying rules that are compatible with PHP 7.4?

We want to benefit from things like NullToStrictStringFuncCallArgRector whilst supporting PHP 7.4+ in our library.

Thanks!

**Comment by TomasVotruba** [comment]
Hi, for that, use the `LevelSetList::UP_TO_PHP_74`.

Or set PHP Version in config to PHP 7.4: https://github.com/rectorphp/rector#configuration

**Comment by davidwindell** [comment]
@TomasVotruba but that doesn't give us support for PHP 8, for example NullToStrictStringFuncCallArgRector is compatible with both PHP 7.4 and PHP 8.1 but it only seems to be applied with `LevelSetList::UP_TO_PHP_81`

**Comment by TomasVotruba** [comment]
The sets are organized in a idempotent way so they do not overlap. 
You can register the `NullToStrictStringFuncCallArgRector` manually if you want to run it earlier.

**Comment by davidwindell** [comment]
Thanks, @TomasVotruba. We will go through the sets and manually pick out which bits we need. That being said, I don't see why `NullToStrictStringFuncCallArgRector` (for example) couldn't be included in an earlier set as it would allow projects that support both PHP7.4 and 8.1 to work whilst avoiding exceptions in PHP 8.1 (unless I am missing something)

**Comment by TomasVotruba** [comment]
You're right. It could and should be. The configuration should be from the outside: https://github.com/rectorphp/rector-src/blob/f230e5463ae1bfd9e1d6070935def31ae493109e/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php#L42

And handled per PHP version.
