### ISSUE TITLE
Combine multiple configuration files

### ISSUE THREAD

**Issue by internalsystemerror** [rectorphp/rector#7447]
# Question

I have a monorepo that contains many git submodules each with their own versioning (i.e. not the standard symplify/monorepo-builder approach).

e.g.

- apps/
  - client-name/
    - app-name/
- libs/
  - client-name/
    - shared-lib/
  - common/
    - shared-lib

CI checks are run within each submodule (e.g. apps/client-name/app-name, libs/client-name/shared-lib, libs/common/shared-lib).

I'm currently running rector at the top level only, (which may be preferable and/or required) however, what I would like to do is to be able to run a rector CI check within each submodule .

In order to not duplicate configuration, would it possible to import `rector.php` configurations from all the submodule into the top level `rector.php`? This may be a complicated question in terms of scope, however I wish the resultant top level `rector.php` to simply be as if I had typed everything from the submodule `rector.php` files into the top level configuration.

What would be the ideal way to accomplish this? Or should this be strictly avoided? I was thinking that I could pass the top level `$rectorConfig` to the submodule static functions returned from their respective `rector.php` files, but I wanted to ask whether this is ideal before rolling this out.

**Comment by TomasVotruba** [comment]
Hi, 

I'm not sure what exactly is your issue or question, so I'm only guessing :)


To avoid configuration, you can import configuration with the `import()` method:

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->import(__DIR__ . '/directory/config.php');
}
```

**Comment by internalsystemerror** [comment]
If I have multiple packages, each with their own `rector.php` containing configuration that allows me to run rector on each package standalone, and then I want to merge all those into 1 uber `rector.php` configuration to run against the entire monorepo, would `$rectorConfig->import()` be correct for this?

e.g.

- apps/
  - client-name/
    - app-name/
      - rector.php <- allows rector to be run just on this submodule
- libs/
  - client-name/
    - shared-lib/
      - rector.php <- allows rector to be run just on this submodule
  - common/
    - shared-lib
      - rector.php <- allows rector to be run just on this submodule
- rector.php <- combines all submodule configurations to allow rector to be run on the entire monorepo

**Comment by TomasVotruba** [comment]
That looks fine 👍 

Personally I run single config of any tool per project. 
This would be too complex and lead to weird behavior.
