### ISSUE TITLE
A unit test with mock expectations is incorrectly considered by rector to not perform assertions

### ISSUE THREAD

**Issue by internalsystemerror** [rectorphp/rector#7448]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.0           |

A unit test that contains a mock with expectations (method calls, return values) is considered by PHPUnit to perform assertions. Rector is adding `@doesNotPerformAssertions` to these tests, however. With these added comments, PHPUnit marks these tests as risky.
- https://github.com/sebastianbergmann/phpunit/issues/2958

## Minimal PHP Code Causing Issue

~~The following demo should be enough reproducible code, however I am getting a `Could not write data to cache file` error.
https://getrector.org/demo/8309cb67-c10c-4889-9fd4-1d365fd509a0~~
https://getrector.org/demo/17e60282-2c25-4daa-bf6f-e39aa35428b1

## Expected Behaviour

No comment should be added to this method, allowing PHPUnit to continue to consider it as OK.

**Comment by samsonasik** [comment]
I cleared the PHPStan cache, and re-clicked submit, it now show the diff https://getrector.org/demo/17e60282-2c25-4daa-bf6f-e39aa35428b1 that add the comment

**Comment by internalsystemerror** [comment]
@samsonasik thank you!

**Comment by samsonasik** [comment]
Could you create failing test PR for it, you can click "Create a Test" button at demo page
