### ISSUE TITLE
CallUserFuncRector rector is missing

### ISSUE THREAD

**Issue by frazjp65** [rectorphp/rector#745]
With a fresh install of rector (v0.3.16), I get the error below when I run `rector process src/ --level php70 --dry-run`. 

>   Class "Rector\Php\Rector\FuncCall\CallUserFuncRector" was not found while loading "vendor/rector/rector/config/level/php/php70.yml" file. Are you sure it is correctly spelled?

**Comment by frazjp65** [comment]
It looks like it broke with ecbf96a9ed9dbd41f62d21fd12b9f47946eea957. They call it "Func", but name it "Method".

**Comment by TomasVotruba** [comment]
Closed by #746
