### ISSUE TITLE
Incorrect behavior of DowngradeTrailingCommasInParamUseRector

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#7452]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/4dd5142b-fac1-4cb7-9641-a4ea3b941e70

```php
<?php

class ParentClass
{
    public function resolveValue(
        ObjectTypeResolverInterface $objectTypeResolver,
        object $object,
    ): mixed {
        return true;
    }
}

class ChildClass extends ParentClass
{
    public function resolveValue(
        ObjectTypeResolverInterface $objectTypeResolver,
        object $object,
    ): mixed {
        return false;
    }
}
```

### Responsible rules

* `DowngradeTrailingCommasInParamUseRector`

## Expected Behavior

Please notice the tests are executing `DowngradeLevelSetList::DOWN_TO_PHP_71`.

This issue possibly follows issue #7423. After upgrading Rector to v0.14.2, downgrading my project is still not working as expected, so I assume that `DowngradeTrailingCommasInParamUseRector` still has problems.

Check out the [result of downgrading this code](https://getrector.org/demo/d58ff963-5805-4e1d-a9dd-18d1f93d38b0), where there is no trailing comma after `object $object`:

```php
<?php

class ParentClass
{
    public function resolveValue(
        ObjectTypeResolverInterface $objectTypeResolver,
        object $object // There is no trailing comma here
    ): mixed {
        return true;
    }
}

class ChildClass extends ParentClass
{
    public function resolveValue(
        ObjectTypeResolverInterface $objectTypeResolver,
        object $object
    ): mixed {
        return false;
    }
}
```

The applied rules were:

- `DowngradeParameterTypeWideningRector`
- `DowngradeObjectTypeDeclarationRector`
- `DowngradeMixedTypeDeclarationRector`

Next, let's add a `,` after `object $object`:

```php
<?php

class ParentClass
{
    public function resolveValue(
        ObjectTypeResolverInterface $objectTypeResolver,
        object $object, // There is a trailing comma here!
    ): mixed {
        return true;
    }
}

class ChildClass extends ParentClass
{
    public function resolveValue(
        ObjectTypeResolverInterface $objectTypeResolver,
        object $object,
    ): mixed {
        return false;
    }
}
```

The expectation is to execute the same rules as above + `DowngradeTrailingCommasInParamUseRector`. However, [only these 2 rules are now applied](https://getrector.org/demo/4dd5142b-fac1-4cb7-9641-a4ea3b941e70):

- `DowngradeTrailingCommasInParamUseRector`
- `DowngradeMixedTypeDeclarationRector`

For some reason, when `DowngradeTrailingCommasInParamUseRector` is applied, `DowngradeParameterTypeWideningRector` and  `DowngradeObjectTypeDeclarationRector` did not get applied.

**Comment by leoloso** [comment]
Btw, clicking on the demo links from #7423 produces a 500 error: https://getrector.org/demo/8e7337b5-c0d4-49dd-8f3b-3491850a5d5f

**Comment by samsonasik** [comment]
@leoloso old demo database was refreshed as got too big, new failing fixture tests should can be added to https://github.com/rectorphp/rector-src/tree/76ee84cedfe4dedd612ee3c478d9ece4191a01cb/tests/Issues/IssueDowngradeParamType/Fixture for continue on it.
