### ISSUE TITLE
AnnotationToAttribute doesn't work if there s an existing attribute above annotations

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#7453]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.2    |

When using `DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES`, entities with attributes above annotations will fail to transform the annotationa to attributes.

If the `ApiResource` attributes are removed, then the Doctrine annotations are correctly converted.

## Minimal PHP Code Causing Issue

```php
<?php

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource(
    operations: [
        new Get(),
        new GetCollection(),
    ],
    normalizationContext: ['groups' => ['policy-notice:read']],
)]
/**
 * @ORM\Entity()
 * @ORM\Table(name="policies_notices")
 */
class PolicyNotice
{}
```

## Expected Behaviour

all the Annotations become Attributes!

**Comment by TomasVotruba** [comment]
We'll need an isolated failing demo link from: http://getrector.org/demo, from that create failing test case pull-request.

**Comment by bendavies** [comment]
https://getrector.org/demo/a4a70f22-e7ce-4928-9e2b-b346be078bff

**Comment by TomasVotruba** [comment]
Seems like the way php-parser resolve this: https://github.com/nikic/PHP-Parser/pull/887

**Comment by TomasVotruba** [comment]
We discussed it and the way is to flip those with e.g. fixer.

See https://github.com/nikic/PHP-Parser/pull/887#issuecomment-1237291322

**Comment by bendavies** [comment]
related previous discussion
https://github.com/rectorphp/rector/issues/7225

**Comment by TomasVotruba** [comment]
@bendavies That's why the PHP CS Fixer is needed

**Comment by bendavies** [comment]
indeed, but note your last comment on that ticket
> So there is no need for such rule.

but now we think there is :)

**Comment by TomasVotruba** [comment]
It was a different scope indeed.
