### ISSUE TITLE
Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator::__construct          (): Argument #1 ($container) must be of type                                                          Symfony\Component\DependencyInjection\ContainerBuilder,                                               RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder given, called in            /var/www/php-application/vendor/rector/rector/vendor/symfony/dependency-injection/Loader/Php          FileLoader.php on line 67 

### ISSUE THREAD

**Issue by ahmedesa** [rectorphp/rector#7455]
# Bug Report

| Rector version | 0.14.2
| php version | 8.1.9
| phpstan version | 1.8.3

when run : vendor/bin/rector p --ansi

error :

 [ERROR] Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator::__construct
         (): Argument #1 ($container) must be of type                                                
         Symfony\Component\DependencyInjection\ContainerBuilder,                                     
         RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder given, called in  
         /var/www/php-application/vendor/rector/rector/vendor/symfony/dependency-injection/Loader/Php
         FileLoader.php on line 67

**Comment by TomasVotruba** [comment]
How does your `rector.php` look like?
It should use a`RectorConfig` class

**Comment by ahmedesa** [comment]
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::AUTO_IMPORT_NAMES, true);
    $parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, __DIR__ . './phpstan.neon');
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src',
        __DIR__ . '/tests'
    ]);

    // Define what rule sets will be applied, run one by one, commit each time, makes reverting changes a lot easier
    $containerConfigurator->import(SetList::CODE_QUALITY);
    $containerConfigurator->import(SetList::PHP_80);
    $containerConfigurator->import(SetList::DEAD_CODE);
    $containerConfigurator->import(SetList::TYPE_DECLARATION);

};

**Comment by ahmedesa** [comment]
`<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::AUTO_IMPORT_NAMES, true);
    $parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, __DIR__ . './phpstan.neon');
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src',
        __DIR__ . '/tests'
    ]);

    // Define what rule sets will be applied, run one by one, commit each time, makes reverting changes a lot easier
    $containerConfigurator->import(SetList::CODE_QUALITY);
    $containerConfigurator->import(SetList::PHP_80);
    $containerConfigurator->import(SetList::DEAD_CODE);
    $containerConfigurator->import(SetList::TYPE_DECLARATION);

};
`

**Comment by samsonasik** [comment]
You need to update config to use `RectorConfig` class:

```php
<?php

declare(strict_types=1);

use Rector\Set\ValueObject\SetList;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->importNames();
    $rectorConfig->phpstanConfig(__DIR__ . './phpstan.neon');
    $rectorConfig->paths([
        __DIR__ . '/src',
        __DIR__ . '/tests',        
    ]);

    $rectorConfig->sets([
        SetList::CODE_QUALITY,
        SetList::PHP_80,
        SetList::DEAD_CODE,
        SetList::TYPE_DECLARATION
    ]);
};
```
