### ISSUE TITLE
Incorrect behavior of TypedPropertyFromStrictConstructorRector

### ISSUE THREAD

**Issue by Wohlie** [rectorphp/rector#7457]
# Bug Report
Hi, first thanks for this wonderful tool, it outdoes my expectations, but also breaks my code. :grinning:
</body>
</html>

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `0.14.2`             |

I try to migrate some source code that is related to Magento, and the rule `TypedPropertyFromStrictConstructorRector` currently breaks my code.

## Minimal PHP Code Causing Issue
```php
class Test
{
    /** @var \Magento\Checkout\Model\Session */
    protected $checkoutSession;

    /**
     * @param \Magento\Checkout\Model\Session $checkoutSession
     */
    public function __construct(\Magento\Checkout\Model\Session $checkoutSession)
    {
        $this->checkoutSession = $checkoutSession;
    }
}
```

Leads to the following result

```php
<?php
class Test
{
    /** @var \Magento\Checkout\Model\Session */
    protected Magento\Checkout\Model\Session $checkoutSession;

    /**
     * @param \Magento\Checkout\Model\Session $checkoutSession
     */
    public function __construct(\Magento\Checkout\Model\Session $checkoutSession)
    {
        $this->checkoutSession = $checkoutSession;
    }
}
```

## Expected Behaviour
The property class definition must start with `\` like the constructor definition. 
```php
<?php
class Test
{
    /** @var \Magento\Checkout\Model\Session */
    protected \Magento\Checkout\Model\Session $checkoutSession;

    /**
     * @param \Magento\Checkout\Model\Session $checkoutSession
     */
    public function __construct(\Magento\Checkout\Model\Session $checkoutSession)
    {
        $this->checkoutSession = $checkoutSession;
    }
}
```

**Comment by Wohlie** [comment]
Hi @samsonasik, I have created the test: https://github.com/rectorphp/rector-src/pull/2915

**Comment by Wohlie** [comment]
Thanks @samsonasik, I found my issue.

I have the following folder structure
```
project/
├── src/
│   ├── app
│   ├── vendor
├── rector.php
```

So I added the following code to my `rector.php`
```
$rectorConfig->bootstrapFiles([
    __DIR__ . '/src/vendor/autoload.php',
]);
```
which will fix the unexpected behavior.

But how can I notice that autoloading is currently not used?

**Comment by samsonasik** [comment]
`rector.php` should has inlined with `vendor` that the class source of the project located to avoid path juggling.

**Comment by Wohlie** [comment]
@samsonasik Thanks for your advice, but I currently have no chance to keep `rector.php` right next to the `vendor` folder, so I need to use `bootstrapFiles`.
