### ISSUE TITLE
Plan to upgrade to PHP-Parser 5.0

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#7458]
# Question

As of today there's [alpha 1 of nikic/php-parser 5.0](https://github.com/nikic/PHP-Parser/releases/tag/v5.0.0alpha1). PHP-Parser is the single most important foundation building block of PHPStan which Rector is dependent upon.

I wrote my thoughts and plans about upgrading PHPStan to PHP-Parser 5.0: https://github.com/phpstan/phpstan/issues/7943

Can you please check them out and let me know if you agree with them? I'd like to make sure you're happy with this plan and you can wait with the upgrade to PHP-Parser 5.0 until PHPStan 2.0 is out.

Thanks.

**Comment by samsonasik** [comment]
Ref https://github.com/rectorphp/rector-src/pull/2916 for starter

**Comment by samsonasik** [comment]
`RenameClassRector` seems can be used for Node names movement, for example, for `ArrayItem` ref https://getrector.org/demo/70ad3d97-671c-435f-9bc4-dd37b1b57874

Configurable config set for that can be added to https://github.com/rectorphp/rector-php-parser

**Comment by samsonasik** [comment]
@ondrejmirtes @TomasVotruba I start adding rector set list for upgrade deprecated class to php-parser 5.0 https://github.com/rectorphp/rector-php-parser/pull/2

**Comment by samsonasik** [comment]
php-parser 5.0.0-alpha2 released https://github.com/nikic/PHP-Parser/releases/tag/v5.0.0alpha2

**Comment by TomasVotruba** [comment]
It might take years after php-parser 5.0 is released, as it's API is not prefixed. Closing as this is not in our focus now. 

Let's reopen when this becomes a valuable feature :)
