### ISSUE TITLE
[Documentation Request] Path-specific rule sets configuration

### ISSUE THREAD

**Issue by bkuhl** [rectorphp/rector#7464]
# Feature Request

Seems like I've seen this somewhere in my rector exploration but I can't find it.  I'd like to have different rule sets run on different paths (e.g. tests vs application code).  If this is possible, can an example be added to the README or something to demonstrate the ideal approach to this?

**Comment by TomasVotruba** [comment]
Hi, this is not possible.
For different setup on different paths, you can have multiple configs, but it's not recommend as it creates ambiguous code.
