### ISSUE TITLE
InlineConstructorDefaultToPropertyRector example different than execution

### ISSUE THREAD

**Issue by simbig** [rectorphp/rector#7465]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.2      |

## Expected Behaviour

In https://github.com/rectorphp/rector/blob/e3b535f364359c36e4aefe3be5e0cf0b31f56df3/rules/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector.php the example shows that the constructor will be deleted if there is no logic happeing within it any more.

Right now I observed that the constructor will not be deleted but will stay as an empty constructor. Either the example or the implementation should be changed accordingly

**Comment by samsonasik** [comment]
There is [RemoveEmptyClassMethodRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#removeemptyclassmethodrector) for removing empty class method.

The `CodeSample`  need to be updated, could you create PR to update it? Thank you.

You can update to https://github.com/rectorphp/rector-src/blob/2975a1bb0cc1a9e76c4cf09ad9b32494ac90d4e0/rules/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector.php#L44, after updated, you can run:

```
composer update
composer docs
``` 

so the documentation will be re-generated.
