### ISSUE TITLE
RenameParamToMatchTypeRector not skipped

### ISSUE THREAD

**Issue by AlexOstrovsky** [rectorphp/rector#7467]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.2             |

From version 0.14.2 RenameParamToMatchTypeRector::class, $rectorConfig->skip is not working when processing single file.

config:
    $rectorConfig->skip([
        RenameParamToMatchTypeRector::class => [\_\_DIR\_\_ . '/Tests'],
    ]);

```
class Test
{
    public function test(UnitTester $I): void
    {
    }
}
```
vendor/bin/rector process --clear-cache --dry-run Tests/Test.php:

```
 class TransitionHelperCest
 {
-    public function test(UnitTester $I): void
+    public function test(UnitTester $unitTester): void
     {
     }
 }
```

**Comment by AlexOstrovsky** [comment]
@TomasVotruba yeah sorry I was combining response from my real code to example code. In 0.14.0 all works correct with no erros but on 0.14.2 the skip is ignored.

**Comment by samsonasik** [comment]
Please create sample reproducible repository for that, better with github action running, for example, there will be various setup that cause different result: different rector.php against root project and vendor, path juggling, etc.

For note, we are using PHPStan, so analyze whole project is recommended https://phpstan.org/blog/why-you-should-always-analyse-whole-project

**Comment by AlexOstrovsky** [comment]
Hi @samsonasik I created a repo: https://github.com/AlexOstrovsky/rector-problem. This is the problem: 
![image](https://user-images.githubusercontent.com/8947035/189366666-998c6e09-09c5-44ad-a345-c4d9bf26e862.png)

**Comment by samsonasik** [comment]
@TomasVotruba the issue seems introduced in 0.14.1 when introducing `Rector\Skipper\FnMatcher` class at PR: 

- https://github.com/rectorphp/rector-src/pull/2877

so relative path with direct to file path no longer working

**Comment by samsonasik** [comment]
The `FnMatcher` seems need to be checked before return `fnmatch()`:

```diff
diff --git a/packages/Skipper/Fnmatcher.php b/packages/Skipper/Fnmatcher.php
index 455f0fdc70..ac0801ac24 100644
--- a/packages/Skipper/Fnmatcher.php
+++ b/packages/Skipper/Fnmatcher.php
@@ -14,6 +14,13 @@ final class Fnmatcher
             return \true;
         }
 
+        $realPathMatchingPath = realpath($normalizedMatchingPath);
+        $realpathNormalizedPath = realpath($normalizedFilePath);
+
+        if (is_string($realPathMatchingPath) && is_string($realpathNormalizedPath)) {
+            return str_starts_with($realpathNormalizedPath, $realPathMatchingPath);
+        }
+
         // in case of relative compare
         return \fnmatch('*/' . $normalizedMatchingPath, $normalizedFilePath);
```

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/2921
