### ISSUE TITLE
Incorrect behavior of AddVoidReturnTypeWhereNoReturnRector

### ISSUE THREAD

**Issue by ThoWi-de** [rectorphp/rector#7468]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/779fedef-a6ed-4181-9e1f-f13ffa7e2b54

```php
<?php

Class A
{
    public function test(): void
    {
        return;
    }
}

Class B extends A
{
    public function test()
    {
        return;
    }
}

Class C
{
    public function test()
    {
        return;
    }
}

Class D extends C
{
    public function test()
    {
        return;
    }
}
```

### Responsible rules

* `AddVoidReturnTypeWhereNoReturnRector`

## Expected Behavior

I expected that Rector add void as return type to function B::test():
For classes C and D it is working well.

**Comment by samsonasik** [comment]
The code is already error from the beginning, even with only class A and class B, if parent already has void, the child will error see https://3v4l.org/W3QK8

Clean up the void early in class A is the way to go, so all will be applied with void return, see https://getrector.org/demo/a5588339-2b74-4d7f-a5b2-f64d5db5db9f

**Comment by ThoWi-de** [comment]
I am working on a project with a large number of classes with different dependencies. Since a processing of all classes was not successfully brought to an end, a situation like with the classes A and B has arisen. When I restarted the project to process the remaining classes, the errors that occurred in classes A and B were not corrected.

**Comment by Wohlie** [comment]
You can also add the rule `AddReturnTypeDeclarationBasedOnParentClassMethodRector`.
https://getrector.org/demo/5ad096f0-f052-4de2-9529-f3d8c542953a

**Comment by samsonasik** [comment]
I agree with @Wohlie solution above, add `AddReturnTypeDeclarationBasedOnParentClassMethodRector` can be the solution. @ThoWi-de if that's fix your use case, please close the issue. Thank you.

**Comment by ThoWi-de** [comment]
Many thanks to @Wohlie. This solves the problem described in this ticket. Unfortunately, it does not solve my current problem. I will continue to look for the reasons here. But the ticket so such is solved.
