### ISSUE TITLE
PHP 7.4 to 8.1 code conversion stuck at symfony 5.4 project controller class

### ISSUE THREAD

**Issue by Chapter2-AS** [rectorphp/rector#7473]
Hi,

i ran your awesome script but it somehow got stuck when reaching the controller files. Removing the `ImportController.php` didn't solve the problem. The error references to phpstan, whose only depency is rector in this project.

I use this rectorConfig:
```
$rectorConfig->sets([
    LevelSetList::UP_TO_PHP_81,
    DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
    SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES,
    SensiolabsSetList::FRAMEWORK_EXTRA_61,
]);
```

[error-stacktrace.txt](https://github.com/rectorphp/rector/files/9551446/error-stacktrace.txt)

**Comment by samsonasik** [comment]
That’s should already solved in dev-main at https://github.com/rectorphp/rector-src/pull/2913, you can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by Chapter2-AS** [comment]
Thanks, that worked.

I ran into several error messages but the cli memory_limit of 1024M was just too low.
```
 [ERROR] Could not process some files, due to:                                                                          
         "Child process error: ".                  
```

**Comment by samsonasik** [comment]
Thank you for verify. Running in large project will load more memory, that's expected
