### ISSUE TITLE
CONTRIBUTING.md meantions some scripts that dont exits anymore

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector#7477]
CONTRIBUTING.md meantions some scripts that dont exits anymore like `composer complete-check` and `composer fix-cs` but these scripts aren't in `composer.json` anymore since: https://github.com/rectorphp/rector/commit/d56e7982d04a8ed2d1c66609061b2b6152048bb7

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

Could you send PR to fix it?

**Comment by JohJohan** [comment]
Can be closed see: https://github.com/rectorphp/rector-src/pull/2927#discussion_r969669868

**Comment by TomasVotruba** [comment]
@JohJohan I see :+1: 
Thanks for verification, I though you talk about the contributor repository already, so I gave you wrong answer.
My appologies.
