### ISSUE TITLE
RenamePropertyToMatchTypeRector: respect leading _ for private properties

### ISSUE THREAD

**Issue by SantosSi** [rectorphp/rector#7481]
# Bug Report
PHP Code Sniffer (phpcs) requires a leading underscore for private properties. This should be respected by rector.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e2f55bef-9d70-41bb-9d6b-1aab1d4a8b0e

```php
<?php

final class DemoFile
{
    // php code sniffer (phpcs) requires the leading underscore
    /**
     * Database object
     *
     * @var \PDO|null PDO object
     */
    private ?\PDO $_pdo = null;
}
```

### Responsible rules

* `RenamePropertyToMatchTypeRector`

## Expected Behavior
Accept the property name named after the type, but with a leading underscore.

**Comment by samsonasik** [comment]
You can skip the rule if you already have a coding standard tool for it https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md

**Comment by SantosSi** [comment]
My goal is a different one: to combine both tools having a completely different way of working and also set of checks: phpunit works by reporting and suggesting,
