### ISSUE TITLE
Incorrect result of the rule ExplicitPublicClassMethodRector

### ISSUE THREAD

**Issue by Goral64** [rectorphp/rector#7483]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.2             |

## Minimal PHP Code Causing Issue
 ```
class SomeClass
 {
-    abstract function foo();
+    public static function foo();
 }
```
## Expected Behaviour

 ```
class SomeClass
 {
-    abstract function foo();
+    public abstract function foo();
 }
```

**Comment by samsonasik** [comment]
@Goral64 it seems bug on `VisibilityManipulator::replaceVisibilityFlag()`, could you try to provide a patch for it? You can do the following steps:

1. Add failing fixture at https://github.com/rectorphp/rector-src/tree/73aa7e3d68d74fc0b9b26fc543bf1207cfc8d0dd/rules-tests/Visibility/Rector/ClassMethod/ExplicitPublicClassMethodRector/Fixture

2. Run test:

```bash
vendor/bin/phpunit rules-tests/Visibility/Rector/ClassMethod/ExplicitPublicClassMethodRector/ExplicitPublicClassMethodRectorTest.php
```

3. Provide a patch, that seems on `VisibilityManipulator::replaceVisibilityFlag()` https://github.com/rectorphp/rector-src/blob/73aa7e3d68d74fc0b9b26fc543bf1207cfc8d0dd/rules/Privatization/NodeManipulator/VisibilityManipulator.php#L164

**Comment by Goral64** [comment]
I did a PR :)

**Comment by JohJohan** [comment]
See https://github.com/rectorphp/rector-src/pull/2930
