### ISSUE TITLE
Could not resolve argument

### ISSUE THREAD

**Issue by Vatia13** [rectorphp/rector#7487]
Hello,
after I'm running `vendor/bin/rector process src --dry-run` it returns an error
Could not resolve argument "Rector\Config\RectorConfig $rectorConfig"

**Comment by TomasVotruba** [comment]
Hi,
be sure to use the latest version.

Also check `rector.php` config for the new syntax:
https://getrector.org/blog/new-in-rector-012-introducing-rector-config-with-autocomplete

**Comment by samsonasik** [comment]
RectorConfig exist since 0.12, update to latest
