### ISSUE TITLE
Rector adds the same return type hint three times (`array&array&array`)

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#7488]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.2             |

Rector adds the same return type hint three times:

```diff
1) src/DependencyInjection/Configuration.php:251

    ---------- begin diff ----------
@@ @@
         ***
     ***

-    private function processTree(array $tree): array
+    private function processTree(array $tree): array&array&array
     ***
         // Process oauth
         foreach ($tree[self::OAUTH] as $consumer => $oAuth) ***
    ----------- end diff -----------

Applied rules:
 * ArgumentRemoverRector
 * RenamePropertyRector
 * WrapReturnRector
 * StaticCallToNewRector (https://github.com/symfony/symfony/pull/35[30](https://github.com/SerendipityHQ/bundle-remotes/actions/runs/3073794470/jobs/4966149289#step:6:31)8)
 * ReturnTypeDeclarationRector (https://wiki.php.net/rfc/scalar_type_hints_v5)
```

## Minimal PHP Code Causing Issue

Impossible to reproduce in the demo.

https://github.com/SerendipityHQ/bundle-remotes/actions/runs/3073794470/jobs/4966149289#step:6:24

## Expected Behaviour

The code is not changed.

**Comment by samsonasik** [comment]
The repository is not accessible, please create sample reproducible repository with minimal sample code with github action running.

**Comment by Aerendir** [comment]
You are right, my fault 🤦

I cannot create a sample repository as I don't know what is causing the error.

If you agrre, I could add you to the repo, so you can check the code: WDYT?

**Comment by samsonasik** [comment]
You may need to narrow down rules to get the exact rules combination that cause the error, after that, you can reduce code until most simplified code that cause the bug, ref https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by thomasschiet** [comment]
I reproduced it here https://getrector.org/demo/dc4f7af3-6bd9-4937-a493-74affedac91c
