### ISSUE TITLE
Upgrade API Platform Extensions to v3

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#7491]
# Feature Request

I'm upgrading to API Platform v3 and there is a great [upgrade command](https://github.com/api-platform/core/blob/2.7/src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php), but it only modifies the entities. But there's a lot more to do.

I'm trying to upgrade my Doctrine ORM Extensions. This is something that should be easy to automate, as far as I can see. What I need:
* Change an interface (remove `Core\Bridge` from namespace)
* Change the parameter type of an argument (again: remove `Core\Bridge` from namespace)
* Add an argument to a method (add `array $context = []` to `QueryCollectionExtensionInterface::applyToCollection`

Are there any plans to create rules for upgrading to API Platform v3? I can try to create some rules, but I don't know where to start. Any ideas?

## Diff 

```diff
- use ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\QueryCollectionExtensionInterface;
+ use ApiPlatform\Doctrine\Orm\Extension\QueryCollectionExtensionInterface;

final class UserItemExtension implements QueryCollectionExtensionInterface
{
    public function applyToCollection(
        QueryBuilder $queryBuilder,
-        \ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface $queryNameGenerator,
+        \ApiPlatform\Doctrine\Orm\Util\QueryNameGeneratorInterface $queryNameGenerator,
        string $resourceClass,
-        ?string $operationName = null,
+       \ApiPlatform\Metadata\Operation|null $operationName = null,
+       array $context = [],
    ) : void {
        $this->addWhere($queryBuilder, $resourceClass);
    }
}
```

**Comment by TomasVotruba** [comment]
Hi, 

there used to be a Rector set maintained by the api platform, but they switched to custom upgrade tool. 
It's fully in control of the project.

You can requirest feature there or create your custom ruleset, that's also a way.

As where to start, check Symfony Rector sets. They will handle similar changes.
