### ISSUE TITLE
Confusing cache behaviour

### ISSUE THREAD

**Issue by tuupola** [rectorphp/rector#7499]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.14.2                                                   |

I am not sure if this is a bug or a feature, but I find cache behavior bit confusing. If you run two consecutive dry runs the second one claims there is nothing to do unless you clear the cache between them.

Same thing also applies for the actual processing. If you first do a dry run and then a process run, the process run wont do anything unless you clear the cache between them.

## Minimal PHP Code Causing Issue

You can find a minimal setup and console log in this repository.

https://github.com/tuupola/rector-cache-test

## Expected Behaviour

I would expect both second dry run and the process after first dry run to work without manually clearing the cache.

**Comment by tchapuis** [comment]
I've got the same issue, happening since version 0.14.1. It's working on version 0.14.0 and earlier

**Comment by TomasVotruba** [comment]
Thank you for reporting! 
It would be very helpful to know the exact commit when this broke.

**Comment by tchapuis** [comment]
After bisecting between tags 0.14.0 and 0.14.1, I found commit 6c20d257e334db6982a19e93fb376701dcdbead9 to be the first bad commit.

**Comment by samsonasik** [comment]
@TomasVotruba the source commit seems on direct commit to main on rector-src https://github.com/rectorphp/rector-src/commit/d3d18d442c8f2ca64f5ebef5c7a7541938fa1e2a
