### ISSUE TITLE
0 rules in PHPParser?

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#7505]
I saw the announcement for Rector 0.14.3:

> Add rector/rector-php-parser - https://github.com/rectorphp/rector-php-parser

But clicking on the available [PHPParser rules](https://github.com/rectorphp/rector-php-parser/blob/main/docs/rector_rules_overview.md) shows 0 rules:

<img width="905" alt="Screenshot 2022-09-24 at 2 20 57 PM" src="https://user-images.githubusercontent.com/1981996/192083202-f0ca9136-ed33-4ab3-bc89-23feedb166ec.png">

Bug?

**Comment by samsonasik** [comment]
It uses set list which utilize configurable RenameClassRector, the usage is via config set

https://github.com/rectorphp/rector-php-parser#use-sets
