### ISSUE TITLE
OrderAttributesRector duplicates docblocks

### ISSUE THREAD

**Issue by HypeMC** [rectorphp/rector#7506]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.3

In certain cases the docblock gets duplicated when using the `OrderAttributesRector`.

https://getrector.org/demo/8f441764-9570-468b-a879-160bf1f6addb

## Minimal PHP Code Causing Issue

```php
<?php

namespace Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Fixture;

use Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Source\AAttribute;
use Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Source\BAttribute;

/**
 * Some comment
 */
#[BAttribute]
#[AAttribute]
class Someclass
{
}

?>
```

## Expected Behaviour

```php
<?php

namespace Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Fixture;

use Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Source\AAttribute;
use Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Source\BAttribute;

/**
 * Some comment
 */
#[AAttribute]
#[BAttribute]
class Someclass
{
}

?>
```

## Actual Behaviour

```php
<?php

namespace Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Fixture;

use Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Source\AAttribute;
use Rector\Tests\CodingStyle\Rector\ClassMethod\OrderAttributesRector\AlphabeticallOrder\Source\BAttribute;

/**
 * Some comment
 */
#[AAttribute]
/**
 * Some comment
 */
#[BAttribute]
class Someclass
{
}

?>
```

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1:  I'm on iit

**Comment by TomasVotruba** [comment]
In the end, this rule seems like a coding stadnard and ordering by A-Z does not make really sense. The attributes should be ordered by priority of value. E.g. framework and object manipulation first, then less relevant ones. Making a rule for would focus on too much detail where is not needed. Let devs decide how they want to handle these :)

After all, attributes are mostly convered from the doblocks anyway.

**Comment by lyrixx** [comment]
Oh, too bad. I used this rule with a custom configuration, and it was perfect!

**Comment by TomasVotruba** [comment]
Sorry to hear that.

I'd recommend to check folks in php-cs-fixer and get it in there. I think it will be more than welcomed :+1:

**Comment by HypeMC** [comment]
If anybody needs this functionality, a rule was added to [php-cs-fixer v3.55](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.55.0).
