### ISSUE TITLE
Custom Rector rules error "Cannot autowire service, no such service exists"

### ISSUE THREAD

**Issue by Hembi** [rectorphp/rector#7507]
# Question

I would like to create a custom rector rule. Followed the guide: https://github.com/rectorphp/rector/blob/main/docs/create_own_rule.md

I created a copy of RenameForeachValueVariableToMatchExprVariableRector Naming rule, I tried to change the regex inside the InflectorSingularResolver class to fix a prefix name change what I do not want to rename.
So I copied the RenameForeachValueVariableToMatchExprVariableRector rule and the InflectorSingularResolver class file to utils/rector dir.
Set the PSR-4 namespace in composer.json then changed the copied class name and inside the rule changed the InflectorSingularResolver to the custom one I modified.

`public function __construct(**CustomInflectorSingularResolver** $inflectorSingularResolver, ForeachAnalyzer $foreachAnalyzer, PropertyFetchAnalyzer $propertyFetchAnalyzer)`

Without change to the custom resolver in the rule, the custom rule runs properly, but if I tried to use the custom one I got the following error message:
`Cannot autowire service "CustomRectorRules\CustomForEachVariableNameChanger": argument
         "$inflectorSingularResolver" of method "__construct()" references class
         "CustomRectorRules\CustomInflectorSingularResolver" but no such service exists.`

I would like to ask a suggestion to solve how to use a custom class with the same namespace inside the custom rule.

**Comment by samsonasik** [comment]
If you want to autowire your own service, you can configure in your rector.php or your own included config, something like this

https://github.com/rectorphp/rector-phpunit/blob/963c24df5d7c459b4fb9b82f2e7c59644f66b306/config/config.php#L7-L14

**Comment by Hembi** [comment]
Thank you for your answer. It helped me a lot.

If anyone needs:
`$services = $rectorConfig->services();
    $services->defaults()
        ->public()
        ->autowire()
        ->autoconfigure();

    $services->load('CustomRectorRules\\', 'utils/rector/src');`
