### ISSUE TITLE
Deprecation visibility on overview documentation page

### ISSUE THREAD

**Issue by DvDty** [rectorphp/rector#7508]
I was testing the library on a fresh laravel installation and playing with some of the rules, one of them being the [param type declaration](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#paramtypedeclarationrector). It actually gave me breaking changes:

```diff
// app/Http/Middleware/Authenticate.php

use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
-    * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
-    protected function redirectTo($request)
+    protected function redirectTo(\Illuminate\Http\Request $request)
      {
          if (! $request->expectsJson()) {
              return route('login');
          }
      }
}
```

```php
namespace Illuminate\Auth\Middleware;

class Authenticate implements AuthenticatesRequests
{
      /**
       * Get the path the user should be redirected to when they are not authenticated.
       *
       * @param  \Illuminate\Http\Request  $request
       * @return string|null
       */
      protected function redirectTo($request)
      {
          //
      }
}
```

This change results with an error since the declaration in not compatible with its parent. (https://3v4l.org/qQHsO)

I looked deeper and noticed that the rule is [deprecated](https://github.com/rectorphp/rector/blob/main/rules/TypeDeclaration/Rector/FunctionLike/ParamTypeDeclarationRector.php#L37). It would be great if the rule overview page mentioned that, with some type of ⚠ warning.

**Comment by TomasVotruba** [comment]
This should not be happening. 
We'll need a demo link and failing test case for param type rule.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback.
Feel free to reopen with a test case PR. Thank you
