### ISSUE TITLE
The processing on a large codebase is stopped while the execution, without information

### ISSUE THREAD

**Issue by maidmaid** [rectorphp/rector#751]
```
➜  vendor/bin/rector process . --autoload-file bootstrap.inc.php --dry-run -vvv

7 Loaded Rectors
================

 - Rector\Php\Rector\BinaryOp\IsIterableRector
 - Rector\Php\Rector\Name\ReservedObjectRector
 - Rector\Php\Rector\TryCatch\MultiExceptionCatchRector
 - Rector\Php\Rector\Each\WhileEachToForeachRector
 - Rector\Php\Rector\Each\ListEachRector
 - Rector\Php\Rector\Unset_\UnsetCastRector
 - Rector\Php\Rector\ConstFetch\BarewordStringRector

Processing 1531 files
=====================

  836/1531 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  54%%       
➜ (code 0)
```

**Comment by TomasVotruba** [comment]
Could you isolate the file?

**Comment by maidmaid** [comment]
Any suggestion to do it ?

**Comment by carusogabriel** [comment]
> Could you isolate the file it stopped on?

@TomasVotruba It should be Rector's work, shouldn't it?

**Comment by TomasVotruba** [comment]
> Any suggestion to do it ?
> @TomasVotruba It should be Rector's work, shouldn't it?

Any ideas to automate it? e.g. with `-vvv` option?

**Comment by TomasVotruba** [comment]
#758 I've added feature to `-v` option to display current file.

Released in Rector v0.3.17. Try to find file now.

**Comment by TomasVotruba** [comment]
Any updates?

**Comment by TomasVotruba** [comment]
This PR will help with performance stucks in overall - https://github.com/rectorphp/rector/pull/767/files

- 1. disables xdebug when on
- 2. skips deeps chains calls that PHPStan has trouble to analyze - even 5-10 seconds on 30 chain method call
