### ISSUE TITLE
PHP fatal error thrown in TokenStream.php when rector use printFormatPreserving

### ISSUE THREAD

**Issue by Hembi** [rectorphp/rector#7512]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.3             |

Seems there is some cases when the getIndentationBefore() function of php parser gets not valid $pos argument and type check of return value thrown an error.
After run rector on a quite large legacy project I got the following errors:
```
PHP Fatal error: Uncaught TypeError: Return value of PhpParser\Internal\TokenStream::getIndentationBefore() must be of the type int, null returned in vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:205
Stack trace:
#0 vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(523): PhpParser\Internal\TokenStream->getIndentationBefore()
```

In my case the getIndentationBefore function got "-1" start position value as argument and try to return a non integer value (not exists pos).
The problem seems that Rector use printFormatPreserving function from nikic\php-parser and the startTokenPos and endTokenPos is not set in usedAttributes params of Emulative instance of Lexer as mentioned in nikic\php-parser in PrettyPrinterAbstract.php: "The startTokenPos and endTokenPos attributes in the lexer must be enabled." (to use printFormatPreserving() function).
**So seems there is missing configuration in the vendor\rector\rector\packages\PhpDocParser\PhpParser\SmartPhpParserFactory.php when creating the Emulative instance.**

This is related to some closed issues:
https://github.com/rectorphp/rector/issues/7376
https://github.com/rectorphp/rector/issues/7364
https://github.com/rectorphp/rector/issues/3201
https://github.com/rectorphp/rector/issues/1408

One case when error thrown when AddParamBasedOnParentClassMethodRector rule is used on a class which extends mysqli and has a function with same name that exists in parent class.

## Minimal PHP Code Causing Issue
https://getrector.org/demo/db0e9b48-9c85-4451-a710-e123b90124ec

**Comment by TomasVotruba** [comment]
This is due to [`mysqli` class](https://www.php.net/manual/en/class.mysqli.php) that is probably being parsed incorrectly.

We'll need a failing test case PR for this one.

**Comment by TomasVotruba** [comment]
Missclick :)
