### ISSUE TITLE
`ClassPropertyAssignToConstructorPromotionRector`  should put properties on separate lines when max line length exceeded

### ISSUE THREAD

**Issue by arogachev** [rectorphp/rector#7514]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main@149764 released at 2022-09-27 22:23:29           |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/83c06ae1-e29d-4f6f-a2a4-8966d63df6ab

## Expected Behaviour

```php
public function __construct(
    private AbstractConnection $connection, 
    private QueueSettingsInterface $queueSettings,
    private ?ExchangeSettingsInterface $exchangeSettings = null
)
```

**Comment by TomasVotruba** [comment]
This is outside of Rector scope.
Use coding standard tool for an that:
https://github.com/rectorphp/rector#how-to-apply-coding-standards

**Comment by arogachev** [comment]
OK. Thanks for explanation.
