### ISSUE TITLE
Incorrect behavior of MakeTypedPropertyNullableIfCheckedRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#7515]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/174145ce-5db2-42d8-acfc-071a4b9f160e

```php
<?php

class DemoFile {
    private bool $bool;

    public function __construct(bool $bool) {
        $this->bool = $bool;
    }

    public function notBool(): bool {
        return !$this->bool;
    }
}
```

### Responsible rules

* `MakeTypedPropertyNullableIfCheckedRector`

## Expected Behavior

The property should not be made nullable.

**Comment by jlherren** [comment]
I believe the intent of this rule is to check typed properties where the type is an *object-type* (always truthy), and it's missing the nullability. However, it is currently having an undesired effect on *non-object-types* which may already potentially be falsy.

Given this example: https://getrector.org/demo/3f4b02c1-5fb5-4145-8400-acfaf65c25bc I would argue that rector should do nothing at all. It is completely valid code.

**Comment by samsonasik** [comment]
Second example seems not valid, as that will cause accessed before initialization, see https://3v4l.org/i0o9Z , so make nullable with default value is the way to go.

**Comment by jlherren** [comment]
Sorry, my example was too much simplified to be clear. Here's a better example: https://getrector.org/demo/284fe012-032e-4712-97ec-da45bcb617c6

**Comment by samsonasik** [comment]
Could you try provide a patch? It seems can utilize ConstructorAsssignDetector, ref for sample usage:

https://github.com/rectorphp/rector-src/blob/5a6be73baf8c5293e0395a74264335f1e6a02655/rules/CodingStyle/Rector/Property/AddFalseDefaultToBoolPropertyRector.php#L91
