### ISSUE TITLE
AddVoidReturnTypeWhereNoReturnRector is not adding void

### ISSUE THREAD

**Issue by sylfabre** [rectorphp/rector#7516]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main@4dfccb released at 2022-09-29 18:06:39            |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/20a2f3b0-35bd-442e-983c-ab0fd0b92875

## Expected Behaviour

I expect Rector to add the `void` return type hint to the `__invoke()` method

**Comment by samsonasik** [comment]
That's expected as magic method, mostly magic method should not be changed. If you want to apply it, you may can use `AddReturnTypeDeclarationRector` which can add based on type and method, see https://getrector.org/demo/e70deecb-c441-46b9-b298-b728f6ca9a31
