### ISSUE TITLE
Possibly incorrect behavior of BooleanInBooleanNotRuleFixerRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#7517]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1382ed42-5fb5-4610-a9a4-d014f256c7be

```php
<?php

final class DemoFile {
    public function run(bool $bool): bool {
        return !$bool;
    }
}
```

### Responsible rules

* `BooleanInBooleanNotRuleFixerRector`

## Expected Behavior

No changes should be done to the code, because the code does not trigger PHPStan's rule, see https://phpstan.org/r/e5ca7d0c-9fa0-4da2-8009-bbd9ebcf73ac

I understand that this is possibly debatable, but the description claims that this rule is specifically for that PHPStan rule, so they probably should be consistent with each other.

**Comment by TomasVotruba** [comment]
The PHPStan rules was only isnpiration, it's not  the exact remover of the phpstan error.

This rule changes the negated values with `!` to explicit compare with `=== false`-
