### ISSUE TITLE
Incorrect behavior of DisallowedEmptyRuleFixerRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#7518]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1c504bfb-05ff-43de-a6f7-6ce1af1f6e86

```php
<?php

final class DemoFile {
    public function run(array|string $value): bool {
        return !empty($value);
    }
}
```

### Responsible rules

* `DisallowedEmptyRuleFixerRector`

## Expected Behavior

The correct way to fix this code is:

    -        return !empty($value);
    +        return $value !== '' && $value !== [];

**Comment by johanadivare** [comment]
@jlherren does `&&` make a different then `||` other than making it more explicit which is a good point to change is in my opinion.

**Comment by jlherren** [comment]
I don't really mind whether the rule transforms the code to `!($value === '' || $value === [])` or to `$value !== '' && $value !== []`, since both of these expressions are equivalent.

The bug I'm pointing out is that the rule is currently changing the semantics of the code. In fact, the expression `$value !== '' || $value !== []` is always `true` for all values of `$value`.

**Comment by jlherren** [comment]
I started diving into the code. It seems broken in more ways than previously thought, this example is just insane: https://getrector.org/demo/d602e5be-bde4-4b9d-902f-2e1ce1f24370

If time allows it, I will try to provide a fix.

**Comment by johanadivare** [comment]
You can also add some new test fixtures like these for `DisallowedEmptyRuleFixerRectorTest` and after that a fix can be created
