### ISSUE TITLE
?scalar type throws error

### ISSUE THREAD

**Issue by vudaltsov** [rectorphp/rector#7523]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.5             |

`?scalar` throws "System error: "Cannot create PHPStan\Type\UnionType with: null, bool|float|int|string"

## Minimal PHP Code Causing Issue

https://getrector.org/demo/96aa7d1d-5491-43f0-aadb-7b7227b31358

**Comment by samsonasik** [comment]
It seems bug on MixedTypeRector ref https://getrector.org/demo/546b8667-9e91-4806-8f51-776f45b7ac50
