### ISSUE TITLE
Incorrect behavior of LongArrayToShortArrayRector, AddDefaultValueForUndefinedVariableRector

### ISSUE THREAD

**Issue by fredericgboutin-yapla** [rectorphp/rector#7524]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/b3fcdb0b-82a4-479f-8371-dcb0ef65fd2b

```php
<?php

final class DemoFile
{
    public function run()
    {
		$variableIAlreadyHave = 123; // PLEASE NOTICE THE USAGE OF TABS FOR INDENTATION HERE
        $ok['ok'] = 'ok!';
    }
}
```

### Responsible rules

* `LongArrayToShortArrayRector`

* `AddDefaultValueForUndefinedVariableRector`

## Expected Behavior

Should produce something like,

```php
     public function run()
     {
		$ok = [];
		$variableIAlreadyHave = 123;
		$ok['ok'] = 'ok!';
     }
```

**Comment by samsonasik** [comment]
You can configure indentation to something like this:

```php
$rectorConfig->indent("\t", 4);
```

ref https://getrector.org/demo/ada47a4d-5318-4820-b5c7-7d4fcbd05848

**Comment by fredericgboutin-yapla** [comment]
I confirm it solves everything on my side. Thanks!
