### ISSUE TITLE
Incorrect behavior of LongArrayToShortArrayRector

### ISSUE THREAD

**Issue by fredericgboutin-yapla** [rectorphp/rector#7525]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/a321e992-8685-4a92-ad80-7eb54bf5fa98

```php
<?php

final class DemoFile
{
    public function run()
    {
        return array(
            'fancy' => 'array',
            'yeah' => 'multi-lines!!!'
        );
    }
}
```

### Responsible rules

* `LongArrayToShortArrayRector`

## Expected Behavior

```php
<?php

final class DemoFile
{
    public function run()
    {
        return [
            'fancy' => 'array',
            'yeah' => 'multi-lines!!!'
        ];
    }
}
```

**Comment by samsonasik** [comment]
That's expected as the long array require re-print to get short array. You need coding standard tool for that https://github.com/rectorphp/rector#how-to-apply-coding-standards
