### ISSUE TITLE
Merge SKIP option within sets

### ISSUE THREAD

**Issue by dmitryuk** [rectorphp/rector#7530]
I have common company-level rector config set, which contains some other sets and **several skips**. It's all located in separated composer package.
In my project I do import of my set and extend it with Symfony set like it:
```
$rectorConfig->sets([
        SymfonySetList::SYMFONY_44,
        SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,
// COMPANY_SET contains skipped rules
        MyCompany\CodeAnalyzeTools\Rector\SetList::COMPANY_SET,
    ]);
## add  extra skip here
    $rectorConfig->skip([
GetToConstructorInjectionRector::class
    ]);

```

Finally config doesn't contain skipped rules, defined in set of COMPANY_SET, because `skip` method overrides previously defined rules
```
public function skip(array $criteria) : void
    {
        $parameters = $this->parameters();
        $parameters->set(Option::SKIP, $criteria);
    }
```

Can I extend skipped rules instead of overriding?

**Comment by samsonasik** [comment]
That's seems not possible. 

I tried to provide a way for merging config in the past, as @TomasVotruba said, the config merging must be resolved in Symfony Level https://github.com/rectorphp/rector-src/pull/2656#issuecomment-1181747763

**Comment by dmitryuk** [comment]
Is it possible to get `ContainerBuilder $container` variable from `RectorConfig`? So I can read/get current value of Options::Skip and do merging it with my rules.

**Comment by TomasVotruba** [comment]
The `skip()` method itself could fetch the old parameter and merge it with current new value.
Yet we decided to keep the Symfony way, as once you skip something, it would be impossible to unskip it.
