### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by RafaelLinux** [rectorphp/rector#7532]
Despite I use php 8.1, rector can't upgrade my project:

composer require rector/rector:*       
 Problem 1
    - fzaninotto/faker is locked to version v1.7.1 and an update of this package was not requested.
    - fzaninotto/faker v1.7.1 requires php ^5.3.3 || ^7.0 -> your php version (8.1.11) does not satisfy that requirement.
  Problem 2
    - filp/whoops is locked to version 2.1.14 and an update of this package was not requested.
    - filp/whoops 2.1.14 requires php ^5.5.9 || ^7.0 -> your php version (8.1.11) does not satisfy that requirement.
  Problem 3
    - phpunit/phpunit is locked to version 6.5.4 and an update of this package was not requested.
    - phpunit/phpunit 6.5.4 requires php ^7.0 -> your php version (8.1.11) does not satisfy that requirement.
  Problem 4
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your php version (8.1.11) does not satisfy that requirement.
    - laravel/framework v5.5.25 requires doctrine/inflector ~1.1 -> satisfiable by doctrine/inflector[v1.2.0].
    - laravel/framework is locked to version v5.5.25 and an update of this package was not requested.

**Comment by TomasVotruba** [comment]
Your dependencies require PHP 7, so you can't install any package:

```bash
- fzaninotto/faker v1.7.1 requires php ^5.3.3 || ^7.0 -> your php version (8.1.11) does not satisfy that requirement.
```

Fix that first :)
