### ISSUE TITLE
Add rule to migrate from `$snake_case` to `$camelCase`

### ISSUE THREAD

**Issue by VincentLanglet** [rectorphp/rector#7534]
# Feature Request

Hi, we are migrating some code with old standards to a new one.
Some of the code is written in snakeCase when new one is in camelCase.

I was wondering how hard would it be for rector to implements a Rule which
change every variable names in snake case to the same in camel case ?
 
## Diff 

```diff
-$my_foo = 5;
+$myFoo = 5;
```

Thanks

**Comment by TomasVotruba** [comment]
Hi, we had similar rules, but the were mostly breaking the code in unexpected places, so we removed them and avoid them.
See: https://github.com/rectorphp/rector/issues/6739#issuecomment-939418124

If you want, you can implement those yourself.
Naming package would be great contribution to the community :+1:

**Comment by samsonasik** [comment]
You can see the rule in CodeIgniter4 for this, see https://github.com/codeigniter4/CodeIgniter4/blob/4887c2ad8044a162434ef9d8895c9dbc003c6854/utils/Rector/UnderscoreToCamelCaseVariableNameRector.php
