### ISSUE TITLE
System error 

### ISSUE THREAD

**Issue by mollux** [rectorphp/rector#7536]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.5 and dev-main@ed0b84            |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/91b3ab20-7a06-4aff-939a-b4881f9329b5

## Expected Behaviour

```
<?php

use Symfony\Component\Form\FormInterface;

class PocClass
{
    private function pocMethod(FormInterface $childType, FormInterface $parentType)
    {
        $parentType->add(
           $childType->methodA(),
           $childType->methodB()::class
        );
    }
}
```

**Comment by samsonasik** [comment]
It seems reproduced with combination:

```
    $rectorConfig->rule(\Rector\Php80\Rector\FuncCall\ClassOnObjectRector::class);
    $rectorConfig->rule(\Rector\Symfony\Rector\MethodCall\ChangeStringCollectionOptionToConstantRector::class);
```

ref https://getrector.org/demo/ebc94c71-d3ee-493f-8eb2-cbf49713535a

**Comment by samsonasik** [comment]
Ok, reproduced with just `ChangeStringCollectionOptionToConstantRector`, ref https://getrector.org/demo/b3dfde48-a332-4ec2-a061-a36acebbb13e
