### ISSUE TITLE
CountOnNullRector touches an array type

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#7537]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.5             |

Rector applied this change, however `arrayParam` returns an array (`array<mixed>`). I have tried to reproduce this in demo but in demo any rule haven't applied.

```
         $sortParam = $params->arrayParam('sort');

-        if (count($sortParam) !== 1) {
+        if ((is_array($sortParam) || $sortParam instanceof \Countable ? count($sortParam) : 0) !== 1) {
             throw new DomainException();
         }
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/d45a3739-551b-4166-be91-3f0b50830be4 - but here works as expected

## Expected Behaviour

No fix

**Comment by samsonasik** [comment]
@snapshotpl you seems using Rector 0.11.  Latest rector version is 0.14.5, could you try latest rector/rector:0.14.5 or rector/rector:dev-main ?

**Comment by snapshotpl** [comment]
I'm using newest version. Same on dev-main

**Comment by samsonasik** [comment]
That's strange, could you create reproduced repository for that, better with github action running, you can use https://github.com/samsonasik/rector-issue-php74 as template.

**Comment by snapshotpl** [comment]
I have found. Type of `$params` comes from stub and probably rector doesn't read it. Right?

**Comment by samsonasik** [comment]
Rector read php file, if the stubs are needed, you may need to include to autoload or bootstrap, ref https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#include-files

You can have phpstan and rector to have same bootstrap when needed, for example:

PHPStan config: https://github.com/codeigniter4/CodeIgniter4/blob/a3eedf4055c1a2895051b654c49311641dd2975f/phpstan.neon.dist#L27-L28

Rector config: https://github.com/codeigniter4/CodeIgniter4/blob/a3eedf4055c1a2895051b654c49311641dd2975f/rector.php#L73

**Comment by samsonasik** [comment]
I am going to close it as the solution provided.
