### ISSUE TITLE
Incorrect behavior of InlineConstructorDefaultToPropertyRector

### ISSUE THREAD

**Issue by paulhennell** [rectorphp/rector#7541]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

```php
<?php

final class DemoFile
{
    private $thing1, $thing2, $thing3;
    
    public function __construct()
    {
        $this->thing1 = 1;
        $this->thing2 = 2;
        $this->thing3 = 3;
    }
}
```

See https://getrector.org/demo/cdfb2192-cb53-4dda-891f-056fc92a43ac for what happens

### Responsible rules

* `InlineConstructorDefaultToPropertyRector`

## Expected Behavior

I guess changing it to `private $thing1 = 1, $thing2 = 2, $thing3 = 3;` would be the smallest end code change, although my preference (and I think the more common standard) would be to put each property on their own lines. Either way the code should probably work at the end! 😉

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1:
