### ISSUE TITLE
Incorrect behavior of ForRepeatedCountToOwnVariableRector

### ISSUE THREAD

**Issue by SmitSanghvi94** [rectorphp/rector#7542]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e20e8427-51d8-4f79-8e29-321eece1a482

```php
<?php

class SomeClass
{
    public function run($items)
    {

        $itemsCount = count($items);
        for ($i = 5; $i <= count($items); $i++) {
             echo $items[$i];
        }
    }
}
```

### Responsible rules

* `ForRepeatedCountToOwnVariableRector`

## Expected Behavior

```php
class SomeClass
{
    public function run($items)
    {

        $itemsCount = count($items);
        for ($i = 5; $i <= $itemsCount; $i++) {
             echo $items[$i];
        }
    }
}
```

**Comment by samsonasik** [comment]
That's expected, using existing variable assign will require check variable never unset or modified after assign, that can make a buggy transformation on usage in loop.

**Comment by SmitSanghvi94** [comment]
> That's expected, using existing variable assign will require check variable never unset or modified after assign, that can make a buggy transformation on usage in loop.

I understand that checking for modification would be needed before and during the loop, but how will this cause a buggy transformation?

**Comment by samsonasik** [comment]
There are many ways that the ` $itemsCount` will be modified, that can be on purpose based on developer needs, eg: `$itemsCount++`, `$itemsCount--`, etc.

That variable then used on loop, or after loop, the result will be different.
