### ISSUE TITLE
importNames doesn't use fqn when already class imported

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector#7544]
# Bug Report

When you already use a class then rector will still use fully qualified namespace see example: https://getrector.org/demo/82ff7f68-5947-496b-ac17-e82a6f87b555 i expect the `\DateTime` to change to `DateTime

## Minimal PHP Code Causing Issue
https://getrector.org/demo/82ff7f68-5947-496b-ac17-e82a6f87b555

## Expected Behaviour

```diff
<?php

use DateTime;

final class DemoFile
{
    public function run()
    {
-       return new \DateTime();
+       return new DateTime();
    }
}
```

**Comment by samsonasik** [comment]
The bug seems only happen on short class name https://getrector.org/demo/3535f801-a26b-4ff6-a5e9-27552f5a94ec
