### ISSUE TITLE
Rector wrongly removes private modifier from contructor param

### ISSUE THREAD

**Issue by ktogias** [rectorphp/rector#7545]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.6           |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/9976db04-262a-43e9-97c4-5e2e3870f360

```diff
- public function __construct(private Manager $manager)
+ public function __construct(Manager $manager)
    {
        $this->repository = $manager->getRepository(Program::class);
        $this->beneficiaryRepository = $manager->getRepository(Beneficiary::class);
    }
```

## Expected Behaviour

Rector should not change the code

**Comment by TomasVotruba** [comment]
Thank you :+1: 

Could you narrow it down to single rule and ~5 lines of PHP code that causes this issue?

**Comment by XhmikosR** [comment]
@TomasVotruba `RemoveUnusedPromotedPropertyRector` seems to be the culprit.

I tried to narrow it down, I hope it helps: https://getrector.org/demo/7def20ce-baf8-419d-b0ec-0589269f1ab5

**Comment by CodeCasterNL** [comment]
Well it's unused in the rest of your class, so it's demoted to a regular constructor parameter which gets used and discarded.
