### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivateMethodRector

### ISSUE THREAD

**Issue by alcohol** [rectorphp/rector#7547]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/ed9a3a77-ec36-4654-ad47-d8dd8f4c73ba

```php
<?php

final class DemoFile
{
    public function run(): array
    {
        return array_map(
            static fn (string $bar): string => self::returnFoo(),
            ['bar']
        );
    }
    
    private static function returnFoo(): string
    {
        return 'foo';
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior

I would not expect the static method to be removed, but it is.

**Comment by samsonasik** [comment]
It seems because it used in ArrowFunction, directly call seems not removed https://getrector.org/demo/87ee34dc-7bfd-4d09-9950-54e8f6a09e66

**Comment by samsonasik** [comment]
It seems caused by multiple rules applied, tried using only `RemoveUnusedPrivateMethodRector` seems working ok https://getrector.org/demo/a7f2f91c-f791-4585-a48b-5079059cb765

**Comment by samsonasik** [comment]
It seems due to combination rules:

```
Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector;
Rector\DeadCode\Rector\FunctionLike\RemoveDuplicatedIfReturnRector;
```

ref https://getrector.org/demo/66d03737-04b4-4345-89e5-074046ba496c
