### ISSUE TITLE
CountOnNullRector shouldn't touch Enum::cases()

### ISSUE THREAD

**Issue by b1rdex** [rectorphp/rector#7550]
# Bug Report

```
enum AbTestGroup: string
{
    case A = 'a';
}
```

```
1) ../src/Service/User/AbTest/AbTestGroupRandomizer.php:8

    ---------- begin diff ----------
@@ @@
     public function getRandomGroup(int $countGroups): AbTestGroup
     {
         $enums = AbTestGroup::cases();
-        if ($countGroups > \count($enums)) {
+        if ($countGroups > (is_countable($enums) ? \count($enums) : 0)) {
             throw new \InvalidArgumentException('This amount of groups is too big');
         }
    ----------- end diff -----------

Applied rules:
 * CountOnNullRector (https://3v4l.org/Bndc9)
```

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.6             |

**Comment by samsonasik** [comment]
That's possibly due to `AbTestGroup` enum is not autoloaded, it cannot be reproduced in https://getrector.org/demo/dc58708e-ad72-4e8b-bc3f-cfabe8bb556b

See the doc for how to troubleshoot on autoload handling https://github.com/rectorphp/rector/blob/e8603ff6cbd4e4428238ce6fd2b84fcf3ef68b23/docs/static_reflection_and_autoload.md

**Comment by b1rdex** [comment]
Hmm, that is strange, because I have PSR-4 with one namespace, and it's autoloaded in the app. May the issue be related to having rector in subdirectory?

/rector
    composer.json (has only one dep: rector/rector, and `"scripts": {"rector": ["@php vendor/bin/rector"]}`)
    rector.php (config, `$rectorConfig->paths([__DIR__ . '/../src']);`)
/src (app files)
composer.json (`"autoload": {"psr-4": {"App\\": "src/"}`)

And I run it like this: `composer -d rector install && composer -d rector run rector`

**Comment by b1rdex** [comment]
The issue isn't reproducible for me now too 😕 It fixed itself 😁
