### ISSUE TITLE
Naming convention of "generated" variables.

### ISSUE THREAD

**Issue by BrekiTomasson** [rectorphp/rector#7552]
When I run Rector using the rulesets I've defined, it renames a number of variables to fit their typehint, stuff like Exceptions and the variables used in `foreach` statements. The problem, however, is that it renames them using `camelCase`, while the naming convention that I use for variables is `snake_case`. I've been looking around and can't find any place to adjust the settings for how these variables are named; is there anything like this or should I just disable this rule so that it doesn't break my naming convention?

**Comment by TomasVotruba** [comment]
Hi, basically we had to pick one default naming convention to produce variable names.
Same we do with FQN class names, to keep every rule in standard output.

The variable naming must be handled by coding standard tool and its rules. The same way it would handle same issue produced by human.

**Comment by BrekiTomasson** [comment]
Correct me if I'm wrong, but even if it isn't declared to be such in PSR, isn't it fairly standard practice in PHP that:

- Classes and Namespaces are named using `PascalCase`,
- Class properties are named using `camelCase`,
- Class methods are named using `camelCase`,
- Method arguments are named using `$camelCase`
- Global functions are named using `snake_case()`,
- Scoped variables are named using `$snake_case`,

Here's a (horribly contrived) example of each that should explain what I mean.

```php
<?php

namespace Application\NameSpace\SubDirectory;

class ThingThatDoesStuff extends OtherClassWithStuff
{
    use Application\Common\ExtremelyUsefulTrait;

    protected string $commonName;

    protected string $officialName;

    public function setNames(string $common, $string official = null): void
    {
        if (passes_criteria($common)) {
            $this->commonName = $common;

            if ($official !== null) {
                $temporary_variable = clean_contents($official);

                if (isset($temporary_variable) && $temporary_variable !== $common)) {
                    $this->officialName = $official;
                }
            }
        }
    }

}
```

I understand that it might be too complex to give users the ability to define which naming scheme they want to use for individual rules (even though that would definitely be preferred), but shouldn't you at least try to stick to the standards as they are used by the wider PHP Community?

**Comment by TomasVotruba** [comment]
Standard are unique per team. That's why we keep the coding standrad on the tools that were build to handle them :)
E.g. we use PSR-12 running on ECS.

**Comment by BrekiTomasson** [comment]
Gotcha. :)
