### ISSUE TITLE
Bitbucket pipe

### ISSUE THREAD

**Issue by collisiondetection** [rectorphp/rector#7553]
Would it be possible for you to make a bitbucket pipe ?   https://support.atlassian.com/bitbucket-cloud/docs/use-pipes-in-bitbucket-pipelines/

**Comment by TomasVotruba** [comment]
Sure, Rector can be used in any CI service :+1:

**Comment by collisiondetection** [comment]
Do you have an example for bitbucket please ?

**Comment by TomasVotruba** [comment]
Not really, but it's the same as any CI script.

Try:
https://support.atlassian.com/bitbucket-cloud/docs/get-started-with-bitbucket-pipelines/
