### ISSUE TITLE
Participation in Hacktoberfest

### ISSUE THREAD

**Issue by lermontex** [rectorphp/rector#7554]
Previously, you participated (#4360), but then the "hacktoberfest" topic was removed, so PRs will not be accepted :(

Contributors will see the following error:

> Your PR/MR was submitted to a repository that is not participating in Hacktoberfest. Maintainers need to add the <code>hacktoberfest</code> topic to the repository, or add the <code>hacktoberfest-accepted</code> label to your PR/MR.

The rectorphp repositories do not appear in this list:
https://github.com/topics/hacktoberfest

Rules:
> Your PR/MRs must be in a repo tagged with the “**hacktoberfest**” topic, or have the “**hacktoberfest-accepted**” label.
> Hacktoberfest is now opt-in for maintainers, so only contribute to projects that indicate they’re looking for Hacktoberfest PR/MRs.
> Once your PR/MR has passed this check, we won’t check this again (unless your PR/MR fails a check before this, such as it being marked as spammy).

> Your PR/MRs must be merged, have the “**hacktoberfest-accepted**” label, or have an overall approving review.
> Your PR/MR must not be a draft to be considered accepted.
> If your PR/MR is being accepted for Hacktoberfest via an overall approving review it must also not be closed.

https://hacktoberfest.com/participation/#pr-mr-details

**Comment by mrsamirr** [comment]
Previously, you participated (#4360), but then the "hacktoberfest" topic was removed, so PRs will not be accepted :(

Contributors will see the following error:

Your PR/MR was submitted to a repository that is not participating in Hacktoberfest. Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR/MR.

The rectorphp repositories do not appear in this list:
https://github.com/topics/hacktoberfest

Rules:

Your PR/MRs must be in a repo tagged with the “hacktoberfest” topic, or have the “hacktoberfest-accepted” label.
Hacktoberfest is now opt-in for maintainers, so only contribute to projects that indicate they’re looking for Hacktoberfest PR/MRs.
Once your PR/MR has passed this check, we won’t check this again (unless your PR/MR fails a check before this, such as it being marked as spammy).

Your PR/MRs must be merged, have the “hacktoberfest-accepted” label, or have an overall approving review.
Your PR/MR must not be a draft to be considered accepted.
If your PR/MR is being accepted for Hacktoberfest via an overall approving review it must also not be closed.

https://hacktoberfest.com/participation/#pr-mr-details @mrsamirr``

**Comment by TomasVotruba** [comment]
> Hacktoberfest is now opt-in for maintainers, so only contribute to projects that indicate they’re looking for Hacktoberfest PR/MRs.

Thanks for clarifing this. We're not looking for such contributions, because we prefer long-term Rector developers who try to solve and contribute their own ideas :)

**Comment by lermontex** [comment]
@TomasVotruba 

"River starts from a small stream"

All you need to do is add a "hacktoberfest" topic. You would be able to receive contributions, and contributors would be rewarded by the organizers of Hacktoberfest

Hacktoberfest is an annual worldwide event held during the month of October. The event encourages open-source developers to contribute to repositories through pull requests (PR).

I hope you will think of and support this wonderful initiative :)

Thank you!
