### ISSUE TITLE
Update deprecated set-output to GITHUB_OUTPUT

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7555]
# Feature Request

Currently, scoped build is using deprecated set-output

https://github.com/rectorphp/rector-src/blob/b4c0637b1f59b5110a41205df6af51105bee7520/.github/workflows/build_scoped_rector.yaml#L108

Ref

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

 it should be updated

**Comment by rez1dent3** [comment]
The set-* methods of github actions are not used in this project.
You can close the issue.

@samsonasik @TomasVotruba FYI

**Comment by rez1dent3** [comment]
Ah, I didn't see it. There is a separate repository

**Comment by rez1dent3** [comment]
@TomasVotruba @samsonasik  PR done^
