### ISSUE TITLE
PHPstorm  intergration and adoption. It intergrates fairly well  but missing chevrons >>

### ISSUE THREAD

**Issue by collisiondetection** [rectorphp/rector#7560]
Can you guys upvote this PHPstorm feature  request? It will help the adoption of Rector by making it easier to use in phpstorm. 

Basically, they are missing chevrons  in the rector output to make line by line changes easier. : 

You can upvote it here : https://youtrack.jetbrains.com/issue/WI-66699/Rector-checkboxes-for-each-change-in-a-file

**Comment by TomasVotruba** [comment]
Sure, thanks for sharing :+1:
