### ISSUE TITLE
Missing create_function?

### ISSUE THREAD

**Issue by tablatronix** [rectorphp/rector#7561]
# Question

```php
$allowargs = array(
  'depth' => create_function('$input', 'return filter_var(intval($input), FILTER_VALIDATE_INT, array(1,6));' ),
  'class' => create_function('$input', 'return filter_var($input, FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW);'),
  'asc'   => create_function('$input', 'return true;'),
  'abs'   => create_function('$input', 'return true;'),
  'ul'    => create_function('$input', 'return true;'),
  'ol'    => create_function('$input', 'return true;'),
  'notoc' => create_function('$input', 'return true;'),
  'debug' => create_function('$input', 'return true;'),
  'demo'  => create_function('$input', 'return true;'),
);
```
rector is not finding this deprecated/removed, I tried php 74 and 80

Do I need a special config? or is this a bug?

**Comment by TomasVotruba** [comment]
When in doubts, check the rules overview to find out about all rules: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md

The one you're looking for is in PHP 7.2:
https://github.com/rectorphp/rector-src/blob/main/rules/Php72/Rector/FuncCall/CreateFunctionToAnonymousFunctionRector.php

**Comment by TomasVotruba** [comment]
> I guess I need to use a different set list, like UP TO

Exactly :) the upgrade sets are idempotent and independent on each other.
See: https://getrector.org/blog/new-in-rector-012-the-latest-php-in-a-single-import

**Comment by tablatronix** [comment]
FYI, i could not find any thing in readme or docs about `LevelSetList` only on the blog entry.
Either I missed something obvious or it might not be documented
