### ISSUE TITLE
Rector creates Collection&iterable as return type

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#7562]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.6             |

I've got a problem with a Doctrine entity in my Symfony application. Unfortunately, I haven't found a way to create a simple reproducible example, so I need some help.

## Minimal PHP Code Causing Issue
```
    /** @var \Doctrine\Common\Collections\Collection<\App\Entity\User\UserSocialAccount> */
    #[OneToMany('user', targetEntity: UserSocialAccount::class)]
    private Collection $socialAccounts;

-    public function getMemberships() : Collection
+    public function getMemberships() : \Doctrine\Common\Collections\Collection&iterable
     {
         return $this->memberships;
     }

Applied rules:
 * ReturnTypeDeclarationRector (https://wiki.php.net/rfc/scalar_type_hints_v5)

```

This creates a `Type 'iterable' cannot be part of an intersection type` error.

Any idea?

**Comment by samsonasik** [comment]
Please create reproducible code at https://getrector.org/demo or reproducible repository with github action running.

You can narrow down rules half by half until it found the rule(s) that cause it https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

Thank you

**Comment by stephanvierkant** [comment]
I've tried to create a reproducible example, but failed. I've got a (working) example here: https://getrector.org/demo/37b2a95f-079d-44f7-be8e-d2448aa32817

But when I try this file and config locally, it adds a `&iterable` to my method. I'm using PHP 8.1.11.

**Comment by samsonasik** [comment]
That can probably already solved in dev-main, you can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

If the issue persist, reproducible repository with github action running is needed.

**Comment by stephanvierkant** [comment]
https://github.com/stephanvierkant/rector-iterable/actions/runs/3346475343/jobs/5543330133

**Comment by samsonasik** [comment]
It seems due to `Doctrine\Common\Collections\Collection` implements `\IteratorAggregate` that make it `iterable`.
