### ISSUE TITLE
FunctionArgumentDefaultValueReplacerRector shouldn't mess up formatting when not changing anything

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7563]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.6            |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f7049595-91da-4a30-a552-04b830d10da0

## Expected Behaviour

No change by rector.

Suggestion:
maybe rector shouldn't change anything, if it's a pure whitespace change? Bc in most cases a whitespace-only change is a bug in rector I guess? (unless the rule is specifically for whitespace changes, which FunctionArgumentDefaultValueReplacerRector is not)

**Comment by TomasVotruba** [comment]
The mix of PHP and HTML is not well supported in php-parser itself, see: https://github.com/nikic/PHP-Parser/commit/b0edd4c41111042d43bb45c6c657b2e0db367d9e

So this is a feature :)
