### ISSUE TITLE
Don't apply fix, if the only change is whitespace

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7564]
# Feature Request

https://github.com/rectorphp/rector/issues/7563

When a rector fix changes only whitespace, it should not apply the fix, as 
a) it's wrong
b) it makes rector much slower (about twice as slow when a whitespace fix is applied vs when not). Given the fact that you have to run rector again to get the "[OK]" result, it's about 3x as slow as it could be, if whitespace only changes were not applied.

**Comment by TomasVotruba** [comment]
Hi, this is not Rector itself, but feature of AST tree in php-parser that we use here, see: https://github.com/rectorphp/rector#how-to-apply-coding-standards

If you can come up with exact improvement, we'd be happy to merge it :)

**Comment by Kontrael** [comment]
Hi, disabling the string "mbstring.func_overload=2" helped me
