### ISSUE TITLE
Incorrect behavior of FirstClassCallableRector

### ISSUE THREAD

**Issue by alexey-rus** [rectorphp/rector#7565]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/d88e0aa7-1e19-4877-98c0-b6a6feab8aec

```php
<?php

final class DemoFile
{
    public function provideListenerPriority(): array
    {          
         return [
             'listener' => [
                 [SessionListener::class, 'onKernelRequest'],
             ],       
         ];
    }
}
class SessionListener
{
    public function onKernelRequest(RequestEvent $event)
    {  
    }
}
```

### Responsible rules

* `FirstClassCallableRector`

## Expected Behavior

Skip this case

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.
