### ISSUE TITLE
Incorrect behavior of NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by eliashaeussler** [rectorphp/rector#7566]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1c428b9f-9393-4f16-85e8-c0f75da182e5

```php
<?php

trait HeadlineTrait
{
    protected string $headline = '';
    
    public function setHeadline(string $headline): void
    {
        $this->headline = $headline;
    }
    
    public function getHeadline(): string
    {
        return $this->headline;
    }
    
    public function hasHeadline(): bool
    {
        return '' !== trim($this->headline);
    }
}
```

### Responsible rules

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

Since `$headline` must always be a `string`, the suggested type cast has no effect.

**Comment by samsonasik** [comment]
checking property inside trait from property fetch is not possible right now.

Also, trait require context, so it changeable via class consumer, so cast to string is expected.

You can skip the rule via `rectorConfig->skip()` config
 
https://github.com/rectorphp/rector/blob/main/docs/how_to_ignore_rule_or_paths.md

**Comment by eliashaeussler** [comment]
Alright, thanks @samsonasik.
