### ISSUE TITLE
Rector\Renaming\Rector\Name\RenameClassRector is running more than once per file

### ISSUE THREAD

**Issue by ArchitectNate** [rectorphp/rector#7567]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.6            |

When I run rector, it is running the same rule multiple times on a file. For a single file, that's not a major issue, but at scale, it starts to become a major problem, especially in CI with limited resources.

### Class
```
<?php
declare(strict_types=1);

class RectorTest
{
}
```

### Config
```
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Symfony\Set\SymfonySetList;

return static function (RectorConfig $rectorConfig): void {

    $rectorConfig->sets([
        SymfonySetList::SYMFONY_60,
    ]);
};
```

### Command and Output
```
rector process src/RectorTest.php --debug --clear-cache

src/RectorTest.php
[file] src/RectorTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/RectorTest.php
[rule] Rector\Php80\Rector\Class_\AnnotationToAttributeRector

[file] src/RectorTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

                                                                                                                        
 [OK] Rector is done!                                                                                                   
```
## Expected Behaviour

`Rector\Renaming\Rector\Name\RenameClassRector` should only run once

This still happens if we do` $rectorConfig->disableParallel();`
This happens locally and in CI.

On larger files, `` is running many more times, sometimes once per every other rule out there. There are also a handful of other rules that seem to be duplicating also, but this is the simplest to replicate (at least on our end).

# Quick Example of how it grows
## File
```
<?php
declare(strict_types=1);

class RectorTest
{
    public int $attribute = 23;
    public int $otherAttribute = 45;
}
```

## Command / Output
```
rector process src/RectorTest.php --debug --config=rector.php
src/RectorTest.php
[file] src/RectorTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/RectorTest.php
[rule] Rector\Php80\Rector\Class_\AnnotationToAttributeRector

[file] src/RectorTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/RectorTest.php
[rule] Rector\Php80\Rector\Class_\AnnotationToAttributeRector

[file] src/RectorTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/RectorTest.php
[rule] Rector\Php80\Rector\Class_\AnnotationToAttributeRector

[file] src/RectorTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

                                                                                                                        
 [OK] Rector is done!                                                                                                   
 ```
 
 As you can see, it's running rename 4 times here, on very large files, it runs 40 times.

**Comment by samsonasik** [comment]
You're running a set list:

```php
SymfonySetList::SYMFONY_60
```

which consists of multiple rules, after another rule applied, the same rule need to be runs again to verify if another rule  make change same node with the current rule node was applied.

so, it is expected.

**Comment by ArchitectNate** [comment]
Ah, I see, would running specific rules not have that effect?

Because it is taking over an hour for rector to run in CI

**Comment by samsonasik** [comment]
For multiple rules, it will check same node again to verify until nothing changed.

That will depends of project size, bigger project will be longest to process, ensure that you only run on non-vendor part:

```php
$rectorConfig->paths([__DIR__ . '/src', __DIR__ . '/tests']);
```

 you can run dir by dir to find the slow parts:

```
vendor/bin/rector process src/Commands
vendor/bin/rector process src/Entity
```

**Comment by ArchitectNate** [comment]
Alright fair enough. We already define paths, I'll have to do it piece by piece to see where it's slow.

Closing as it's not a bug
