### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector

### ISSUE THREAD

**Issue by eliashaeussler** [rectorphp/rector#7568]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/ff71cd05-d65f-4bbe-a63f-3064a9dbfd0b

```php
<?php

final class Vcs
{
    public function __construct(
        private readonly string $accessToken,
        private readonly string $repository,
    ) {
    }
    
    public function getAccessToken(): string
    {
        return $this->accessToken;
    }
    
    public function getRepository(): string
    {
        return $this->repository;
    }
}

final class DemoFile
{
    public function __construct(
        private ?string $accessToken = null,
        private ?string $owner = null,
        private ?string $name = null,
    ) {
    }
    
    public function withVcs(Vcs $vcs): static
    {
        $clone = clone $this;
        $clone->accessToken = $vcs->getAccessToken();
        [$clone->owner, $clone->name] = explode('/', $vcs->getRepository(), 2);
        
        return $clone;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

The `$owner` and `$name` properties must not be `readonly`, since they may be overwritten within the `withVcs` method.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a PR with failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by eliashaeussler** [comment]
@TomasVotruba Thanks for taking care 🙂 Here we go: https://github.com/rectorphp/rector-src/pull/3029
