### ISSUE TITLE
Incorrect behaviour of `AddDefaultValueForUndefinedVariableRector`

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7569]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.14.6       |

Rector adds a default value, but I do not know why. I can reproduce it everytime on my local machine, but not on the demo. I've identified the rule and re-configured it like in the demo. But [demo says "no change"](https://getrector.org/demo/8515caaa-ad00-401e-8596-20459ec61b1c), whereas my local machine (with exact same config) will always add it. 

## Minimal PHP Code Causing Issue

Like in demo: https://getrector.org/demo/8515caaa-ad00-401e-8596-20459ec61b1c

```php
// test.php
<?php

declare(strict_types=1);

final class DemoFile
{
    public function __construct(
        private readonly float $value,
    ) {
    }

    public function run(): int
    {
        $float = $this->value;
        bcscale(20);
        $current = bcsub((string) $float, (string) floor($float));

        for ($decimals = 0; ceil((float) $current); ++$decimals) {
            $leftSide = bcmul((string) $float, bcpow('10', (string) ($decimals + 1)));
            $rightSide = (string) floor((float) bcmul((string) $float, bcpow('10', (string) ($decimals + 1))));
            $current = bcsub($leftSide, $rightSide);
        }

        return $decimals;
    }
}
```

```php
// rector.php

use Rector\Config\RectorConfig;
use Rector\Core\ValueObject\PhpVersion;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->phpVersion(PhpVersion::PHP_81);
    $rectorConfig->importNames();
    $rectorConfig->importShortClasses(false);

    $rectorConfig->rules([
        \Rector\Php56\Rector\FunctionLike\AddDefaultValueForUndefinedVariableRector::class
    ]);
}
```

```
$> symfony php vendor/bin/rector process --config rector.php src/Domain/Value/test.php
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================

1) src/Domain/Value/test.php:10

    ---------- begin diff ----------
@@ @@

     public function run(): int
     {
+        $decimals = null;
         $float = $this->value;
         bcscale(20);
         $current = bcsub((string) $float, (string) floor($float));
    ----------- end diff -----------

Applied rules:
 * AddDefaultValueForUndefinedVariableRector (https://github.com/vimeo/psalm/blob/29b70442b11e3e66113935a2ee22e165a70c74a4/docs/fixing_code.md#possiblyundefinedvariable)
```

## Expected Behaviour

Rector should skip it.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.

**Comment by samsonasik** [comment]
That may possobly already resolved in latest dev-main, you can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by mvhirsch** [comment]
> That may possibly already resolved in latest dev-main, you can try:

Thanks! I tried, same result. :-(

excerpt composer stdout: 
```
- Upgrading rector/rector (0.14.6 => dev-main ecee0c4): Extracting archive
```

**Comment by samsonasik** [comment]
Failing test case PR is needed then

**Comment by samsonasik** [comment]
I am going to close it as it can't be reproduced in demo page ike in yours, You may use old Rector version, try latest version, if you still have issue, feel free to create failing fixture PR if you found a use case for it.

**Comment by mvhirsch** [comment]
I'm still able to reproduce it in my project using v0.15.0. Unless I'm able to reproduce this, keep it closed. :+1:
