### ISSUE TITLE
Incorrect behavior of SimplifyForeachToArrayFilterRector

### ISSUE THREAD

**Issue by P3gucka** [rectorphp/rector#7570]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e6253027-77ca-4230-97ee-7eaa5740ac01

```php
<?php

final class DemoFile
{
    public function run(array $params)
    {
        $result = [];
        foreach ($params as $key => $value) {
            if (preg_match('/reg/', $key) > 0) {
                $result[$key] = $value;
            }
        }

        return $result;
    }
}
```

### Responsible rules

* `SimplifyForeachToArrayFilterRector`

* `SimplifyUselessVariableRector`

* `RemoveDoubleAssignRector`

## Expected Behavior

```php
<?php

final class DemoFile
{
    public function run(array $params)
    {
        return array_filter($params, fn($key) => preg_match('/reg/', $key) > 0, ARRAY_FILTER_USE_KEY);
    }
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need failing test case in a pull-request, so we have it covered in Rector.

**Comment by samsonasik** [comment]
Already resolved by PR:

- https://github.com/rectorphp/rector-src/pull/3100

Ref https://getrector.org/demo/4bb04398-7d21-4f73-b434-16513c2c6c7c
