### ISSUE TITLE
Incorrect behavior of SwapFuncCallArgumentsRector

### ISSUE THREAD

**Issue by raveren** [rectorphp/rector#7572]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/67de1160-041b-4aa3-a318-2d3d4ae1e8ff

```php
<?php

final class DemoFile
{
    public function run()
    {
        return transLoc(
                $one,
                $two,
                $three
            );
    }
}
```

with
```php
    $rectorConfig->ruleWithConfiguration(
        SwapFuncCallArgumentsRector::class,
        [new SwapFuncCallArguments('transLoc', [1, 2])]
    );
```

### Responsible rules

* `SwapFuncCallArgumentsRector`

## Expected Behavior

```php
<?php

final class DemoFile
{
    public function run()
    {
        return transLoc(
                $one,
                $three,
                $two
            );
    }
}
```

The rule only works for swapping the first two arguments.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by raveren** [comment]
> You can click "Create a Test" button at demo page.

If I click it I get 
![image](https://user-images.githubusercontent.com/364220/199814448-e89f9ea5-0f31-43bf-b319-04ce92d01513.png)
is that the correct path? I don't think so, what should it be? 

Please don't force me to check out Rector locally, because this is my first attempt to use the library, and it failed. I did what I intended with PHPStorm in minutes...

**Comment by raveren** [comment]
is this okay:

https://github.com/rectorphp/rector-src/pull/3032

neat setup, Tomas!
