### ISSUE TITLE
Allow removal of rules from RectorConfig

### ISSUE THREAD

**Issue by gjuric** [rectorphp/rector#7575]
# Feature Request

Allow removal of configuration rules. This would allow one to use predefined SetLists but remove some of the rules.
 
## Code 

```diff
final class RectorConfig extends ContainerConfigurator

+    public function removeRule(string $rectorClass) : void
+    {
+        $services = $this->services();
+        $services->remove($rectorClass);
+    }
```

**Comment by samsonasik** [comment]
I think you can use `skip()` method : 

```php
$rectorConfig->skip([
    SomeRector::class,
]);

**Comment by xvilo** [comment]
That's quite unintuitive, as it is also used to skip certain directories. Wouldn't have guessed this, and wanted to create the same issue. Why not add a specific method for this?
