### ISSUE TITLE
Update from EndBug/add-and-commit to stefanzweifel/git-auto-commit-action

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7579]
# Feature Request

For rectify auto-commit, we currently only can use `EndBug/add-and-commit@v7.5.0` due to error after v8+

In current used version, it seems show notice:

```bash
Run EndBug/add-and-commit@v7.5.0
  
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

We seems possibly can update to use stefanzweifel/git-auto-commit-action https://github.com/stefanzweifel/git-auto-commit-action which seems there is already handle for it:

- https://github.com/stefanzweifel/git-auto-commit-action/pull/252

**Comment by TomasVotruba** [comment]
Let's stick with current action/workflow, as it works well and this is not easy plug in/play :+1:

**Comment by samsonasik** [comment]
Ok, for note: it won't work on next year `31st May 2023` as `set-output` will be fully disabled https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
