### ISSUE TITLE
Incorrect behavior of RemoveUnusedVariableInCatchRector

### ISSUE THREAD

**Issue by Jimbolino** [rectorphp/rector#7580]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/bf3a0177-740f-479c-a8bc-a8cb964e1833

```php
<?php

class DemoFile
{
    public function check()
    {
        try {
            $test = $this->test1();
        } catch (Exception $unusedException) {
            return false;
        }

        try {
            $test2 = $this->test2();
        } catch (Exception $unusedException) {
            return false;
        }
    }
}
```

### Responsible rules

* `RemoveUnusedVariableInCatchRector`

## Expected Behavior

It should remove both unused variables.
For some reason, if you combine it with another some other rule, this works as expected:
https://getrector.org/demo/eeb92110-78bc-4a7f-9a09-f16d88ac819f

**Comment by samsonasik** [comment]
@Jimbolino could you try provide a patch for it? You can do with the following steps:

1. Add failing fixture under https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/Catch_/RemoveUnusedVariableInCatchRector/Fixture

2. Run unit test

```bash
vendor/bin/phpunit rules-tests/Php80/Rector/Catch_/RemoveUnusedVariableInCatchRector
```

3. Provide a patch, it seems you can check variable used in next node which verify parent attribute is not a Catch_ node:

```php
! $node->getAttribute(\Rector\NodeTypeResolver\Node\AttributeKey::PARENT) instanceof Catch_

```

at https://github.com/rectorphp/rector-src/blob/64d0a8375814c9da2fe93036e4c0fa5fbf06aa25/rules/Php80/Rector/Catch_/RemoveUnusedVariableInCatchRector.php#L111

**Comment by samsonasik** [comment]
It resolved in latest dev-main as prev and next nodes are immediatelly connected after node transformed see https://getrector.org/demo/fc86c995-f75f-49b3-bf9e-36fcd89d5e19

By PR:

- https://github.com/rectorphp/rector-src/pull/3079

On commit https://github.com/rectorphp/rector/commit/a5406b6411db5d6255ba6e0096dba8fc4a0edbfa
