### ISSUE TITLE
Diff should include name of Rector that caused it

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#7587]
# Feature Request

It's particularly difficult to track down which rule caused a change if many rules are available. It would be useful if, like [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), the name of the rule causing the diff to be printed was emitted.

It would also be useful if the set name could be emitted, too, when this applies. I realise that would take some additional work since the notion of sets is completely unknown to the Rector runtime itself.
 
## Diff 

```
1 file with changes
===================

1) ProductsBundle/Resources/config/services.yml:14
```

```diff
@@ @@
   ProductsBundle\Service\DataProvider:
     arguments:
-      - '@Symfony\Component\Translation\TranslatorInterface'
+      - '@Symfony\Component\Translation\TranslatorBagInterfaceInterface'
```

```php
use Symfony\Component\Translation\TranslatorInterface;

class DataProvider
{
    public function __construct(
        TranslatorInterface $translator,
    ) {}
}
```

In this case, it seems this is also a bug because `TranslatorBagInterfaceInterface` does not exist (`InterfaceInterface`?). As far as I can tell, it is caused by the `RenameClassRector` in the Symfony30 set.

**Comment by TomasVotruba** [comment]
The diffs actually includes such a list. It might be due to `yml` suffix scope.

We'll need a failing test case for the `RenameClassRector`.

**Comment by samsonasik** [comment]
The `$this->file->addRectorClassWithLine()` usage seems needes in NonPhp Rector

**Comment by TomasVotruba** [comment]
Closing as accepted to avoid keep issue tracker focus on unclear issues that needs our attention.
Feel free to send PR with it :+1:
