### ISSUE TITLE
RectorConfig::symfonyContainerXml does not validate file path

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#7588]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.7         |

`RectorConfig::symfonyContainerXml` allows any string to be set and never complains if the string does not point to a readable file, much less a valid Symfony container definition.

## Minimal PHP Code Causing Issue

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->symfonyContainerXml('lol');
};
```

## Expected Behaviour

If the file does not exist, an error should be displayed.

**Comment by TomasVotruba** [comment]
Thanks for suggestion. Could add file validation to the method?

**Comment by Bilge** [comment]
We could, and I have added such a check directly to my config for now, but shouldn't something else deeper within Rector fail when it tries to read a file that does not exist? That is, even if it doesn't fail to set the option, due to lack of explicit check, how does this not cause an error later in the process?

**Comment by TomasVotruba** [comment]
Validation is good enough here, as its input door to the life cycle of whole runner 👍

Feel free to send PR.
