### ISSUE TITLE
Incorrect behavior of MakeTypedPropertyNullableIfCheckedRector

### ISSUE THREAD

**Issue by Wohlie** [rectorphp/rector#7589]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/41f7e7dc-d188-43c3-b6af-180fc00f1fcb

```php
<?php

class Message
{
    private string $message;

    public function __construct()
    {
        $this->message = 'foo';
    }

    private function getMessage(): ?string
    {
        if (!$this->message) {
            return null;
        }

        return $this->message;
    }
}
```

### Responsible rules

* `MakeTypedPropertyNullableIfCheckedRector`

## Expected Behavior

The property `message` is directly initialized in the constructor, so the property should not be nullable.

**Comment by samsonasik** [comment]
Duplicate with https://github.com/rectorphp/rector/issues/7515 , @Wohlie could you try provide a patch? It seems can utilize ConstructorAsssignDetector, ref for sample usage:

https://github.com/rectorphp/rector-src/blob/5a6be73baf8c5293e0395a74264335f1e6a02655/rules/CodingStyle/Rector/Property/AddFalseDefaultToBoolPropertyRector.php#L91

**Comment by Wohlie** [comment]
Ah ok, thank you for the hint. Yes, I can take a look in the next week. I have some bugs I would currently report first.
