### ISSUE TITLE
Incorrect behavior of StringifyStrNeedlesRector

### ISSUE THREAD

**Issue by Wohlie** [rectorphp/rector#7591]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f15b91de-9b9e-40c9-b42d-e8dafd948704

```php
<?php

class SkipConstString
{
    public const VALUE = 'N/A';

    private function filterValues()
    {
        return \stripos('bar', static::VALUE);
    }
}
```

### Responsible rules

* `StringifyStrNeedlesRector`

## Expected Behavior

The string cast of `static::VALUE` is not required.

**Comment by samsonasik** [comment]
it seems due to `static` usage and class is not final, which can be used by child, changing to `self` or make class final  seems solve that, see 

- https://getrector.org/demo/60e4e744-5ee2-4566-90cf-30b5748e95ba
- https://getrector.org/demo/eb8b6d61-2914-4b55-b23a-5eb77401657b

Yes, the constant class is overrideable, see https://3v4l.org/sKEfX#v7.4.33

**Comment by Wohlie** [comment]
Hm, I think even with your provided example https://3v4l.org/sKEfX#v7.4.33 the types could be clearly resolved in `SkipConstString` and `SomeChild`.

Even with a private constant, I get a string cast: https://getrector.org/demo/e4f746cf-6dca-4aa3-8acd-ca6fb8fc7b4c

Do you know if this is a limitation in Rector or in type resolving logic of PHPStan?

**Comment by samsonasik** [comment]
I don't know yet, that's probably PHPStan limitation for detecting it, also, private thing is accessible via Reflection, so using static will broke child class, see https://3v4l.org/6cOed

it probably need tweak check if class has child via:

```php
$this->familyRelationsAnalyzer->getChildrenOfClassReflection($classReflection) === []
```

You can get classReflection object via:

```php
$this->ReflectionResolver->resolveClassReflection($node);
```

**Comment by samsonasik** [comment]
I am closing it as it is the nature of `static` and non final class usage, per previous explanations.
