### ISSUE TITLE
Incorrect behavior of SimplifyForeachToArrayFilterRector

### ISSUE THREAD

**Issue by Wohlie** [rectorphp/rector#7592]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/3ae03387-fdc2-469b-9e0c-b0d888a155f1

```php
<?php

class DataFilter
{
    public function filter(array $data): array
    {
        $filteredData = [];
        foreach ($data as $key => $value) {
            if ($key) {
                $filteredData[$key] = $value;
            }
        }

        return $filteredData;
    }
}
```

### Responsible rules

* `SimplifyForeachToArrayFilterRector`

## Expected Behavior

The refactored code miss the definition of `$key` for the callback, as second parameter.

**Comment by samsonasik** [comment]
Duplicate with https://github.com/rectorphp/rector/issues/7570, @Wohlie could you try provide a patch for it, it should just be skipped, by verify foreach key is exists.

**Comment by Wohlie** [comment]
Yes, probably next week I will have some time for that.
