### ISSUE TITLE
Incorrect behavior of SimplifyForeachToCoalescingRector

### ISSUE THREAD

**Issue by Wohlie** [rectorphp/rector#7593]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f9798778-4ed8-46c7-8d25-c4aa36358e82

```php
<?php

class Labels
{
    public function transform(array $data): array
    {
        $namedData = [];
        foreach ($data as $key => $value) {
            if ($key === 0) {
                $namedData['default'] = $value;
            } elseif (!\is_int($key)) {
                $namedData[$key] = $value;
            }
        }

        return $namedData;
    }
}
```

### Responsible rules

* `SimplifyForeachToCoalescingRector`

## Expected Behavior

Rector should not change the code. The changed code will not perform the same logic as the original: https://3v4l.org/fAaY5

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.
