### ISSUE TITLE
Incorrect behavior of SimplifyForeachToArrayFilterRector

### ISSUE THREAD

**Issue by Wohlie** [rectorphp/rector#7594]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |
| PHP | 7.3 |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/91353eb4-621a-42a9-89f2-a45f7605b514

```php
<?php

class FilterDefaultValue
{
    public function filter(array $records, $defaultValue): array
    {
        $nonDefault = [];
        foreach ($records as $key => $value) {
            if ($defaultValue !== $value) {
                $nonDefault[$key] = $value;
            }
        }

        return $nonDefault;
    }
}
```

### Responsible rules

* `SimplifyForeachToArrayFilterRector`

## Expected Behavior

The refactored code will work with PHP >= 7.4
https://3v4l.org/CHTtV

But for PHP 7.3, which don't support arrow function, the use statement for `$defaultValue` is missing
https://3v4l.org/1ORPl

**Comment by samsonasik** [comment]
creating Closure or ArrowFunction is checked early with:

```php
if ($this->phpVersionProvider->isAtLeastPhpVersion(PhpVersionFeature::ARROW_FUNCTION)) {
```

in `ArrayFilterFactory`, so it possibly due to php detection on your CLI which pointed to php 7.4 instead of 7.3, you may need to set php version feature in rector.php:

```php
$rectorConfig->phpVersion(\Rector\Core\ValueObject\PhpVersion::PHP_73);
```

ref https://github.com/rectorphp/rector#configuration

**Comment by Wohlie** [comment]
I have changed the example by using `phpVersion` but the result also misses the `use` of `$defaultValue`.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
@Wohlie you can more fixture under `FixturePhp73` directory at https://github.com/rectorphp/rector-src/tree/23c2282d9aecc36c9123656be3b39dc8edca795e/rules-tests/CodeQuality/Rector/Foreach_/SimplifyForeachToArrayFilterRector/FixturePhp73
