### ISSUE TITLE
[Bug] RemoveAlwaysTrueIfConditionRector with `is_subclass_of` in a trait

### ISSUE THREAD

**Issue by nikophil** [rectorphp/rector#7595]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.7            |

## Minimal PHP Code Causing Issue

Hello, I was trying to run rector on https://github.com/zenstruck/foundry and I detected this bug:
https://getrector.org/demo/83866b66-43f5-4530-9e66-331c1bc67ba3

FTR rector removes this lines :
https://github.com/zenstruck/foundry/blob/51f1bc0c1b8016d4a1b711ca2e265f0255ef25e0/src/Test/Factories.php#L22-L26

## Expected Behaviour

Since the trait is used in both of the classes, it should not remove the condition

thanks!

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by nikophil** [comment]
Hi @TomasVotruba 

sorry for the delay, I have not seen the notification...

here is the PR : https://github.com/rectorphp/rector-src/pull/3091

cheers!

**Comment by samsonasik** [comment]
I am closing it as the solution provided at https://github.com/rectorphp/rector-src/pull/3091#issuecomment-1337146505
