### ISSUE TITLE
Cache presence precludes fixing files

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#7596]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.7            |

Run Rector in dry-run mode.

>\> rector process --config=config/rector.php frontend/src '--dry-run'
 954/954 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
30 files with changes

Immediately run Rector without dry-run mode afterwards.

>\> rector process --config=config/rector.php frontend/src
 363/363 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
>
>
> [OK] Rector is done!

> git status
On branch main
Your branch is up to date with 'origin/main'.
>    
>nothing to commit, working tree clean

Have to force cache ignore to actually get it to change the files.
>\> rector process --config=config/rector.php frontend/src '--clear-cache'
 954/954 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
30 files with changes

## Expected Behaviour

Running without the dry-run mode should always change files, whether there is a cache or not.

**Comment by TomasVotruba** [comment]
Thanks for reporting.
We already discuss it in https://github.com/rectorphp/rector/issues/7499

IMO it will be related to real path changes.
