### ISSUE TITLE
instanceof *Type bugs

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#7597]
# Bug Report

at phpstan-src we are in the process of a bigger refactoring, see https://github.com/phpstan/phpstan/issues/8311
the motivation can be seen in the linked issue.

rector seem to also use a lot of `instanceof .*Type` checks on a rough scan thru the codebase.
I fixed one spot with https://github.com/rectorphp/rector-src/pull/3055

with this issue I just want to make you aware that `instanceof .*Type` most of the time are the wrong thing todo and rector could make use of the newly added methods on the Type interface of the latest (and upcoming) releases 

see e.g.

<img width="806" alt="grafik" src="https://user-images.githubusercontent.com/120441/201468696-fe46738e-26e4-4290-b80f-608bc8e014ed.png">

**Comment by TomasVotruba** [comment]
I don't think it's a bug, but rather a new feature that could be improved.
I like the https://github.com/rectorphp/rector-src/pull/3055, feel free to keep them comming :)

**Comment by staabm** [comment]
yeah its kind of a hybrid. 

in phpstan-src we often see bugs fixed (we didn't know existed or we didn't expect to be fixed) by such changes.

**Comment by staabm** [comment]
looking thru the codebase I was stubling over this:

https://github.com/rectorphp/rector-src/blob/f094438f26f1795a0c4c991aaeaeda37389aff8c/packages/NodeTypeResolver/TypeComparator/ScalarTypeComparator.php#L19-L71

what stand out is, that these 2 method do not handle types like [string accessory-types](https://github.com/phpstan/phpstan-src/tree/1.9.x/src/Type/Accessory)

**Comment by staabm** [comment]
When phpstan finished the refactoring it will ship rules which pinpoint the code which needs adjuszments.
