### ISSUE TITLE
Multipass processing

### ISSUE THREAD

**Issue by rulatir** [rectorphp/rector#7599]
# Question

Is there any kind of built-in support for multipass refactoring, where several passes collect information from the AST and the final pass applies changes, possibly in different places than those from which information had been collected?

**Comment by TomasVotruba** [comment]
Hi, not sure what exacly do you mean. Could you share very simple example?

**Comment by rulatir** [comment]
The need for this arises in complicated scenarios that cannot be reduced to a "very simple example", so I'm going to have to plead with you to forego that requirement. Additionally, I am reluctant to give specific examples, very simple or not, as doing so tends to invite answers with specific workarounds instead of a general solution (or indeed a clear yes-or-no answer, which is all I asked for). That said, here we go. I need to do a refactoring that will simultaneously:

 - replace certain annotations with attributes, but **emphatically** not 1:1
 - while annotations are currently on getters and setters, attributes will have to be preferentially on properties where applicable (some properties are virtual/computed and they are only realized as getters), necessitating a pass that will match properties with their getters/setters and store the association in some kind of map for further passes to look up
 - many simple "boolean" annotations should be replaced by a single class attribute that will take a list of tags (i.e. not 1:1)
 - I want e.g. `#Serialize('reference','expand')` in my code, not `#\Vendor\Library\Annotations\Serialize('reference','expand')`, so I will also need to insert `use` statements at file level

Knowing more about the specific problem than I could briefly summarise above, I reached the informed conclusion that multipass processing is the only way. Is there built-in support for multipass refactoring in Rector?

**Comment by TomasVotruba** [comment]
Rector handles the use imports via importNames() config.
By design AST can change code A only to B, so only 1:1 with exact specification.

**Comment by rulatir** [comment]
Thank you. Follow-up Q: do you use the AST from the Nikic parser more or less directly, or do you wrap it in some significant enhancements/decorators to allow exact reconstructibility (e.g. to preserve original whitespace surrounding nodes etc.)? I remember that was an issue with the vanilla Nikic parser a few years ago. If you have an enhanced parser, how hard or easy do you think it would be to reuse it from Rector and write my own multipass traverser on top of it?

**Comment by TomasVotruba** [comment]
There is lot of custom logive above php-parser, also we patch the classes to fit advanced needs: https://github.com/rectorphp/rector-src/blob/f094438f26f1795a0c4c991aaeaeda37389aff8c/composer.json#L139-L160

You can try to use own php-parser, but you'll end up writing most of the Rector code base again.

**Comment by TomasVotruba** [comment]
I understand that need. Good luck and let me know how it goes, I'm really curious :)

**Comment by rulatir** [comment]
Could you explain why you decided to replace `NodeTraverser`'s more expressive preorder/postorder traversal (`enterNode()` / `leaveNode()`) with single inorder traversal (`refactor()`)?

**Comment by TomasVotruba** [comment]
To isolate API with custom method.
