### ISSUE TITLE
keep memory under control

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [rectorphp/rector#7600]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.7             |
| PHP version | 8.1.12             |

i have a fairly huge codebase with lots of legacycode 

![image](https://user-images.githubusercontent.com/1136869/201479999-4556ceb2-61cd-4e36-bd93-fcab3bcfc010.png)

with phpstan i tend to limit memory consumption to 2 GB but with rector i did not found any solution by now.
the memory use spikes up until my system crashes.

## Expected Behaviour

keeping memory within a reasonable limit :)

any recommendations?

**Comment by samsonasik** [comment]
You may need to configure parallel config, something like:

```php
$rectorConfig->parallel(240, 8, 1);
```

You can decrease job size, eg until 1 if you have file with many lines.

You can read how to troubleshoot it here https://github.com/rectorphp/rector/blob/main/docs/how_to_troubleshoot_parallel_issues.md

There is also `--memory-limit` option if you want to try, something like:

```
vendor/bin/rector --memory-limit=2G
```

On other note, you can run dir by dir to see which one that has high memory consumsion, like:

```
vendor/bin/rector process src/Entity
vendor/bin/rector process src/Controller
```

**Comment by samsonasik** [comment]
I am closing it as there are already various performance improvement, crash handling, and infinite loop handling in recent releases.

Feel free to provide another performance improvement PR when you can :)
