### ISSUE TITLE
Rector initialization ignores alternative config file path

### ISSUE THREAD

**Issue by rolf-kraemer-camao-one** [rectorphp/rector#7601]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.7             |

Initializing Rector config with a given config file path doesn't seem to work.

In my case, running
   `vendor/bin/rector init --config=config/packages/dev/rector.php` 
gives me an error when the file doesn't exist. If I create an empty file in the desired location and run the init command again, the given file path gets ignored and rector.php is being created in the default location (project root)

## Minimal PHP Code Causing Issue
`vendor/bin/rector init --config=config/packages/dev/rector.php`

## Expected Behaviour
According to `vendor/bin/rector init --help` I should be able to provide an alternative config file location.

**Comment by TomasVotruba** [comment]
Hi, this is not supported. 
The init command is intended to create basic `rector.php` in the root.

**Comment by rolf-kraemer-camao-one** [comment]
Thanks for the quick reply.

Meanwhile I figured out the file location is being considered when running `rector process`, so I can hide the config file from production code, and still keep it in my repo
