### ISSUE TITLE
Incorrect behavior of FinalizePublicClassConstantRector

### ISSUE THREAD

**Issue by burkun-sergey** [rectorphp/rector#7602]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

This error can be reproduced if parent and child classes are located in separate files only. This error cannot be reproduced on demo page - https://getrector.org/demo/.

AbstractParent.php:
```php
<?php

class AbstractParent
{
    public const CODE_OK = 'OK';
    public const CODE_NOT_OK = 'ERROR';
}
```

Child.php:
```php
<?php

class Child extends AbstractParent
{
    public const CODE_OK = 'SUCCESS';
}
```

After processing by the rule FinalizePublicClassConstantRector files looks like this:

AbstractParent.php:
```php
<?php

class AbstractParent
{
    final public const CODE_OK = 'OK';
    final public const CODE_NOT_OK = 'ERROR';
}
```

Child.php:
```php
<?php

class Child extends AbstractParent
{
    final public const CODE_OK = 'SUCCESS';
}
```
So changes in Child class leads to the error "cannot override final constant".

Demo page processing has expected correct behaviour. See https://getrector.org/demo/83c7f78b-5380-4ef7-ab02-d5587d34179f

```php
<?php

class AbstractParent
{
    public const CODE_OK = 'OK';
    public const CODE_NOT_OK = 'ERROR';
}

class Child extends AbstractParent
{
    public const CODE_OK = 'SUCCESS';
}
```

### Responsible rules

* `FinalizePublicClassConstantRector`

## Expected Behavior

```php
<?php

class AbstractParent
{
    public const CODE_OK = 'OK';
    public const CODE_NOT_OK = 'ERROR';
}

class Child extends AbstractParent
{
    final public const CODE_OK = 'SUCCESS';
}
```

**Comment by samsonasik** [comment]
That can happen due to autoload overlapped, you can read the doc to troubleshoot it https://github.com/rectorphp/rector/blob/46ee9a173a2b2645ca92a75ffc17460139fa226e/docs/static_reflection_and_autoload.md#troubleshooting

**Comment by burkun-sergey** [comment]
> That can happen due to autoload overlapped, you can read the doc to troubleshoot it https://github.com/rectorphp/rector/blob/46ee9a173a2b2645ca92a75ffc17460139fa226e/docs/static_reflection_and_autoload.md#troubleshooting

Thank you. Skipping the rule does the trick.

**Comment by burkun-sergey** [comment]
> That can happen due to autoload overlapped, you can read the doc to troubleshoot it https://github.com/rectorphp/rector/blob/46ee9a173a2b2645ca92a75ffc17460139fa226e/docs/static_reflection_and_autoload.md#troubleshooting

We've find out that files processing sequence is the key for successful result of rule FinalizePublicClassConstantRector action. 
This command `rector process --clear-cache Child.php AbstractParent.php` remains both files untouched (that is correct).
While the other filename order in command `rector process --clear-cache AbstractParent.php Child.php` produces incorrect result - appending `final` word to constants in both files.
Can you clear this out how command `composer dump-autoload -o` can help to achieve same success result but with incorrect files order processing?

Also we have found that method FamilyRelationsAnalyzer::getChildrenOfClassReflection() is responsible for getting children  reflection classes of the desired class. Is there any way to fill property `reflectionProvider::classes` with all children reflections properly without setting right order of files processing, making `dump-autoload -o` or skipping those parent classes for that rule?

**Comment by samsonasik** [comment]
We use `PHPStan`'s `ReflectionProvider` to load the `classes` so class order is based on that.

Most of the time, the `composer dump-autoload -o` should solve that, as all files will be at `vendor/composer/autoload_classmap.php`, but probably some cache issue can cause that.

Make a `cache` basically should fill all `classes` data first, you should can run:

```bash
# here, cache should filled for "classes" data
vendor/bin/rector --dry-run 

vendor/bin/rector
```

but run 2 times just to fill the cache probably not what you want, so skip the rule for specific file can be the way to go for last resort.

**Comment by ossinkine** [comment]
@samsonasik could you please describe how exactly `vendor/composer/autoload_classmap.php` is used to fill all `classes`? I want to understand is it possible or not to warm up `classes` on `rector` bootstrap to avoid run `rector` twice.

**Comment by samsonasik** [comment]
My knowledge is limited as is mostly internal PHPStan resolver, you may need to lookup how PHPStan load the classes



https://github.com/phpstan/phpstan-src
