### ISSUE TITLE
Sets contain arbitrary unrelated rules

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7605]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.14.8             |

## Minimal PHP Code Causing Issue

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#php80

From the docs one thinks that using the PHP 8.0 set (`\Rector\Set\ValueObject\SetList::PHP_80`) will enable the rules listed here for PHP 8.0

When checking the actual set in rector source code, it contains all kinds of other, arbitrary rules. E.g. `$rectorConfig->rule(RemoveParentCallWithoutParentRector::class);`

## Expected Behaviour

The publically documented PHP version sets, should ONLY include the rules that are listed in the docs. 
Especially, no rules that are unrelated to the PHP version at all.

**Comment by samsonasik** [comment]
The rules documentation overview show "categories", not "set" which fine to consume different category under set list.

**Comment by TomasVotruba** [comment]
All of these rules are on the right place, closing.
