### ISSUE TITLE
Incorrect behavior of RemoveEmptyClassMethodRector, RemoveParentCallWithoutParentRector, TernaryToNullCoalescingRector

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7606]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/890de6d3-5f25-4af6-914d-ea12104709a8

```php
<?php
class FooBar extends Foo {
	public function __construct() {
		parent::__construct( 'x', 'y' );
	}

	public function run( $instance ) {
		$data = isset( $instance['data'] ) ? $instance['data'] : '';

		echo $data;
	}
}
```

### Responsible rules

* `RemoveEmptyClassMethodRector`

* `RemoveParentCallWithoutParentRector`

* `TernaryToNullCoalescingRector`

## Expected Behavior

Only `TernaryToNullCoalescingRector` should give an error.
When I remove `TernaryToNullCoalescingRector`, the other 2 rules don't give an error either: https://getrector.org/demo/b3539acd-8f45-4923-87a7-e0c7849d1f13

This issue only happens when using `$rectorConfig->importNames();`

**Comment by samsonasik** [comment]
`class Foo` need to exists to make that valid fixture, when check using `isset(), changing to null coalescing is correct, see https://getrector.org/demo/fd3e4a16-fbbf-419f-98c3-64e5956bdcae

**Comment by samsonasik** [comment]
Probably a bug on `importNames()` on name resolution, feel free to provide a patch :)

Actually, mostly the bug can be resolved by make all classes autoloadable.

**Comment by samsonasik** [comment]
I am closing it as the solution is provided with ensure class autoloaded.

Feel free to provide a patch on importNames() for the naming resolution when you can.

**Comment by samsonasik** [comment]
The solution is provided, if you have autoload fixed, it will auto-resolved. 

You can load stubs from phpstan config and pointed from rector from rectorConfig:

```php
$rectorConfig->phpstanConfig(__DIR__ . '/phpstan-for-rector.neon');
```

Feel free to create PR for improvement if you found a bug to fix :)
