### ISSUE TITLE
How can I introduce nullsafe arguments?

### ISSUE THREAD

**Issue by maldarol** [rectorphp/rector#7609]
# Question
I am trying to update my php 5.6 code to php 7.1 with Rector 0.14.5 which worked great except for functions with arguments that has a null as default value. What I would like to achieve is nullsafe arguments with the `?` operator.

My config file looks like this:

```php
<?php

declare(strict_types=1);
use Rector\Core\ValueObject\PhpVersion;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->parallel();
    $rectorConfig->bootstrapFiles([
        __DIR__ . '\vendor\autoload.php',
    ]);
    $rectorConfig->phpVersion(PhpVersion::PHP_56);

    // define sets of rules
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_71,
    ]);
};
```

A simple example code for the problem:

```php
<?php
class Optional
{

    protected $name;
    protected $parent;
    protected $var;
    public function __construct($name, $parent = null)
    {
        $this->name = $name;
        $this->parent = $parent;
    }

    //I should achive this turns into ?$param
    public function tesztTeszt($param = null)
    {
        $this->var = $param;
        return abs(1234);
    }
}
```

I do not know if I made a mistake in the configuration or I need to create my own rule for this case.

**Comment by samsonasik** [comment]
param with default null value is no need to have nullable flag, as one it has more param, it will cause error:

```
Optional parameter $param declared before required parameter $v is implicitly treated as a required parameter
```

see https://3v4l.org/O8jIU4

You can use `ParamTypeDeclarationRector` if no default value, the param type need to have information type from of param, eg: from docblock: `@param null|int $param`

see https://getrector.org/demo/52c2afba-04ae-4ab4-84de-057d095c99ef
