### ISSUE TITLE
AddArrowFunctionReturnTypeRector wants to add illegal :void

### ISSUE THREAD

**Issue by gregor-tb** [rectorphp/rector#7615]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.8            |

AddArrowFunctionReturnTypeRector rule adds return type ": void" to some arrow functions, but (at least in php 8.0) this is not valid.

See https://getrector.org/demo/baa80f25-d170-4a67-a78d-54ff1f1c0e6f

## Expected Behaviour

Ignore void, add only valid types.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.
