### ISSUE TITLE
Wrong line numbers in console output

### ISSUE THREAD

**Issue by gregor-tb** [rectorphp/rector#7616]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.8             |

All line numbers printed in console (file.php:%line%) have an offset of -4.

I'm only using dry-run.

**Comment by TomasVotruba** [comment]
We'll need a demo link and test case for this.

**Comment by samsonasik** [comment]
@gregor-tb yes, it seems reproduced, below, the changed part in console is line 11, while it actually changed line 15

![Screen Shot 2023-03-02 at 05 20 31](https://user-images.githubusercontent.com/459648/222278596-f079a82a-5e86-423c-8198-8674398bc43d.png)

```
utils/ChangelogGenerator/Changelog/ChangelogContentsFactory.php:11
```

**Comment by samsonasik** [comment]
@gregor-tb looking at the code, it seems used on purpose to ensure go to the first line before next change, as the change possibly just removed or on docblock part. 

This can be used as pointer so it clickable on IDE terminal, not as the exact file line number that changed.

https://github.com/rectorphp/rector-src/blob/4bd93ba93ddde14444c7635b77007ee523a760f3/src/ValueObject/Reporting/FileDiff.php#L78

**Comment by samsonasik** [comment]
I am closing it as commented above, that it is on purpose to go to the first line before next change, as pointer to be clickable on IDE terminal. Changing can be right in the node or its docblock, so it go to previous line.
