### ISSUE TITLE
Incorrect behavior of AddClosureReturnTypeRector

### ISSUE THREAD

**Issue by spartak791** [rectorphp/rector#7619]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/d56a9d1b-46e2-4c7f-a082-5a41754939eb

```php
<?php

final class DemoFile
{
    public function run()
    {
        return [
            function (mixed $value) {
                return $value;
            },
            function ($value) {
                return $value;
            },
            function () {
                return;
            },

        ];
    }
}
```

### Responsible rules

* `AddClosureReturnTypeRector`

## Expected Behavior
```php
<?php

final class DemoFile
{
    public function run()
    {
        return [
            function (mixed $value): mixed {
                return $value;
            },
            function ($value): mixed {
                return $value;
            },
            function (): void {
                return;
            },

        ];
    }
}
```

**Comment by samsonasik** [comment]
We currently don't apply mixed return type, only for param and only with `@param` tag due to potential BC break, see https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#mixedtyperector

**Comment by spartak791** [comment]
> We currently don't apply mixed return type, only for param and only with `@param` tag due to potential BC break, see https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#mixedtyperector

Do I understand  correctly that 'BC break'  related to PHP version?

We are using PHP 8 and are not interested in backwards compatibility.
Is it possible to use mixed return type?

**Comment by samsonasik** [comment]
On lib in general, it wil cause BC break, as many things need to be checked, eg: extendable class method return, it cause error:

```
Fatal error: Declaration of B::run() must be compatible with A::run(): mixed in /in/nfZoer on line 12
```

https://3v4l.org/nfZoer

**Comment by spartak791** [comment]
This example doesn't fit for AddClosureReturnTypeRector rule.
Closures can't be extendable.

**Comment by samsonasik** [comment]
mixed return can be anything as we need to look many possible use cases, eg: how `@return mixed` not marked as `mixed` if there is no return stmt or just return without expr.

That's why we currently don't support its transformation, thank you for understanding.

**Comment by TomasVotruba** [comment]
Closing as we don't support implicit mixed type as explained.
