### ISSUE TITLE
[ERROR] Unable to process file

### ISSUE THREAD

**Issue by chumylee** [rectorphp/rector#7620]
Using rector to fix deprecations for symfony upgrade but i get error below when i run `bin/rector process src` 

```
 [ERROR] Could not process "../TestFile.php"
         file, due to:                                                                                                  
         "System error: "Unable to read file 'var/cache/dev/App_KernelDevDebugContainer.xml'. failed to open stream: No 
         such file or directory" 
```

**Comment by samsonasik** [comment]
The error is clear, file not found, you probably missing `/` prefix

**Comment by chumylee** [comment]
> The error is clear, file not found, you probably missing `/` prefix

i think the problem is there is no App_KernelDevDebugContainer.xml on my project, and i dont seems to know how to generate it. can you help?

**Comment by BobMali** [comment]
> > The error is clear, file not found, you probably missing `/` prefix
> 
> 
> 
> i think the problem is that there is no `App_KernelDevDebugContainer.xml` on my project, and i don`t seems to know how to generate it. can you help?

That file will be created once you call `bin/console cache:clear`.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:
