### ISSUE TITLE
Incorrect behavior of ChangeSwitchToMatchRector

### ISSUE THREAD

**Issue by VincentLanglet** [rectorphp/rector#7621]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/b0968c60-f99e-4b57-9d41-2676a4b6c423

```php
<?php

final class DemoFile
{
    public function run(): string
    {
        $url = '';
        switch ($foo) {
            case 1:
                $url .= '1';
                break;
            case 2:
                $url .= '2';
                break;
        }

		return $url;
    }
}
```

Another example is
https://getrector.org/demo/f04068ec-1688-4b73-bd39-c736d3fb6e5a

### Responsible rules

* `ChangeSwitchToMatchRector`

## Expected Behavior

The method shouldn't loose the `return` values.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by VincentLanglet** [comment]
> We'll need a failing test case in a pull-request, so we have it covered in Rector. You can click "Create a Test" button at demo page.

I'm not sure how 
```
switch ($foo) {
     case 1:
         $url .= '1';
         break;
     case 2:
         $url .= '2';
         break;
}

return $url;
```
should be updated with match.

Same for 
```
switch ($data->getValue()) {
    case ProductService::SPECIAL_GESTION_CAPSULE:
        $proxyQuery->getQueryBuilder()->andWhere($alias . '.collectionCapsule = true');
        break;
    case ProductService::SPECIAL_GESTION_PRESTIGE:
        $proxyQuery->getQueryBuilder()->andWhere($alias . '.editionPrestige = true');
        break;
    case ProductService::SPECIAL_GESTION_MARGIN:
        $proxyQuery->getQueryBuilder()->andWhere($alias . '.criticalMargin = true');
        break;
}

return tue;
```

Do you think the best would be simply
```
match ($foo) {
     1 => $url .= '1';
     2 => $url .= '2';
}

return $url;
```
and
```
switch ($data->getValue()) {
    ProductService::SPECIAL_GESTION_CAPSULE =>
        $proxyQuery->getQueryBuilder()->andWhere($alias . '.collectionCapsule = true');
    ProductService::SPECIAL_GESTION_PRESTIGE =>
        $proxyQuery->getQueryBuilder()->andWhere($alias . '.editionPrestige = true');
    ProductService::SPECIAL_GESTION_MARGIN =>
        $proxyQuery->getQueryBuilder()->andWhere($alias . '.criticalMargin = true');
}

return tue;
```
?

**Comment by VincentLanglet** [comment]
Based on the fact that
https://getrector.org/demo/f58b9638-4387-4da6-bc01-e18e926b196c is untouched,

I would say that 
https://getrector.org/demo/f04068ec-1688-4b73-bd39-c736d3fb6e5a should be too.

**Comment by VincentLanglet** [comment]
I added a failing test @TomasVotruba https://github.com/rectorphp/rector-src/pull/3176

**Comment by TomasVotruba** [comment]
Thanks Vincent, could you handle the fix as well?

**Comment by VincentLanglet** [comment]
> Thanks Vincent, could you handle the fix as well?

Not sure about it. I'll see when I'll have time but I never worked on this project.

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/3188 :)

**Comment by VincentLanglet** [comment]
I can confirm it also fix https://getrector.org/demo/d5a019fb-3c6a-48b4-9a36-38ac3abd9cd5
