### ISSUE TITLE
Incorrect behavior of AssertFalseStrposToContainsRector

### ISSUE THREAD

**Issue by ghispi** [rectorphp/rector#7625]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/6d0e8f3d-1981-4a8c-8cc7-219e0c166c22

```php
<?php

namespace Demo;

use PHPUnit\Framework\TestCase;

class DemoTest extends TestCase
{
    public function testDemo(): void
    {
        $body = 'Content-Length: 13' . PHP_EOL . PHP_EOL . 'some_contents';
        $this->assertNotFalse(strpos($body, 'Content-Length: 13'));
        $this->assertNotFalse(strpos($body, 'some_contents'));
    }
}
```

### Responsible rules

* `AssertFalseStrposToContainsRector`

## Expected Behavior

I would expect `assertStringContainsString` instread of `assertContains` which is for iterables.

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-phpunit/pull/173/files
