### ISSUE TITLE
Incorrect behavior of AssertTrueFalseToSpecificMethodRector

### ISSUE THREAD

**Issue by ghispi** [rectorphp/rector#7626]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/c283d1a6-15c4-4684-b2e8-274aa7755a95

```php
<?php

namespace Demo;

use PHPUnit\Framework\TestCase;

class DemoTest extends TestCase
{
    public function testDemo(): void
    {
        $this->assertFalse(file_exists('/tmp/demo.txt'));
    }
}
```

### Responsible rules

* `AssertTrueFalseToSpecificMethodRector`

## Expected Behavior

`assertFileDoesNotExist` instead of `assertFileNotExists` - https://github.com/sebastianbergmann/phpunit/issues/4077

**Comment by samsonasik** [comment]
@ghispi could you try provide a patch for it? it seems can be resolved by update the following list:

https://github.com/rectorphp/rector-phpunit/blob/e646c56c4847d941eb656d18c8a047c9441b2de6/src/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector.php#L39

then update test expectation:

https://github.com/rectorphp/rector-phpunit/blob/e646c56c4847d941eb656d18c8a047c9441b2de6/tests/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector/Fixture/fixture.php.inc#L49

then try run test to ensure all green:

```
vendor/bin/phpunit
```

After that, create PR to https://github.com/rectorphp/rector-phpunit

**Comment by samsonasik** [comment]
Just for note, if deprecation start from phpunit 9.1, it should be phpunit 9.1 config sets to avoid break old phpunit usage 

https://github.com/rectorphp/rector-phpunit/blob/main/config/sets/phpunit91.php

**Comment by samsonasik** [comment]
Per discussion with @GeniJaho at PR https://github.com/rectorphp/rector-phpunit/pull/144, the method rename already in phpunit91 config set list

https://github.com/rectorphp/rector-phpunit/blob/main/config/sets/phpunit91.php#L19

You can include : 

```php
use Rector\PHPUnit\Set\PHPUnitSetList;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        PHPUnitSetList::PHPUNIT_91,
    ]);
};
```

for it.
