### ISSUE TITLE
Incorrect behavior of ChangeBigIntEntityPropertyToIntTypeRector

### ISSUE THREAD

**Issue by ghispi** [rectorphp/rector#7628]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/ac61ec99-a4e4-47b3-a04c-05813543fbef

```php
<?php

namespace Demo;

use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Embeddable;

/**
 * @Embeddable
 */
class Money
{
    /**
     * @var int|null
     *
     * @Column(type="bigint", nullable=true, name="value")
     */
    private ?int $amount;

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(?int $amount): Money
    {
        $this->amount = $amount;

        return $this;
    }
}
```

### Responsible rules

* `ChangeBigIntEntityPropertyToIntTypeRector`

## Expected Behavior

Not sure if this is bug or intended functionality scope. It is very limited and causes problems (ie phpstan).
It only changes docblock, doesn't change actual property type, its setter or getter.

**Comment by samsonasik** [comment]
The rule description itself show: `Change database type "bigint" for @var/type declaration to string`, so this is expected. You can actually remove the docblock `@var` if not needed with combine with `RemoveUselessVarTagRector`, see

https://getrector.org/demo/0b2b74a2-0b59-4121-9aa2-43b11fffbadf

**Comment by ghispi** [comment]
That is correct but it doesn't change the quirkiness of this rector.
https://getrector.org/demo/91a2e2ad-7e87-46d2-83e7-3e8f0c6a0a14

I'm not gonna argue, it can be closed if it is agreed and expected behavior.

**Comment by ghispi** [comment]
That is correct but it doesn't change the quirkiness of this rector.
https://getrector.org/demo/91a2e2ad-7e87-46d2-83e7-3e8f0c6a0a14

I'm not gonna argue, it can be closed if it is agreed and expected behavior.

**Comment by samsonasik** [comment]
Looking at doctrine doc https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/types.html#bigint the value retrieved always string, so it possibly the reason the rule created.

**Comment by samsonasik** [comment]
I am closing it as this is expected per doctrine documentation mentioned above.
