### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Mirko-Tebaldi** [rectorphp/rector#7631]
I tried a PR but it's not the right way

See this diff

https://github.com/rectorphp/rector/pull/7630/commits/e5a9cfff982a688bacba8053b3829b201fc8ed35

In the doc you suggest to use isName with $node->name, but it accepts a Node, not a string

**Comment by samsonasik** [comment]
That's depend on what Node you want to verify, on doc example, it check MethodCall, which name is Identifier or Expr, so the documentation is valid, ref

https://github.com/nikic/PHP-Parser/blob/1df465cd901414affcf9a04ef041cf3aedad73b1/lib/PhpParser/Node/Expr/MethodCall.php#L14

**Comment by realtebo** [comment]
The source file AbstractRector.php  require it 

 protected function isName(Node $node, string $name) : bool
    {
        return $this->nodeNameResolver->isName($node, $name);
    }

first argument MUST be a node.

**Comment by samsonasik** [comment]
Identifier and Expr is a Node :)

**Comment by realtebo** [comment]
But in a rule $node->name is a string.

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by samsonasik** [comment]
It is not, the Node that verified is `PhpParser\Node\Expr\MethodCall` defined in   `getNodeTypes()` method, which its `name` property is `Identifier` or `Expr`, which both are `Node`.

**Comment by samsonasik** [comment]
You can't blindly use any `Node` and pass to it, check the Method source for what Node that can be passed to it https://github.com/rectorphp/rector-src/blob/64c03bdd16b666a482a27fad2086b1539b7d557c/packages/NodeNameResolver/NodeNameResolver.php#L54-L73

The way you can learn on it is be slow.

Thank you for understanding.
