### ISSUE TITLE
Incorrect behavior of RemoveEmptyClassMethodRector, Php4ConstructorRector, ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by craigpipeandpiper** [rectorphp/rector#7634]
# Bug Report

When running this test code from the website demo, with the ruleset to update to PHP 8.2, the constructor is removed and the member variable along with it from the test class below. The getter remains, which would reference an undefined class member if called.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1a7859fc-05c0-46fd-804b-8b0433279170

```php
<?php

class DemoFile
{
    var $foo;
    
    function DemoFile($_foo)
    {
        $this->foo = $_foo;
    }
    
    function getFoo() {
        return $this->foo;
    }
}
```

### Responsible rules

* `RemoveEmptyClassMethodRector`

* `Php4ConstructorRector`

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

The constructor and member variable should not be removed, should be preserved as it is used by the getter. I would expect $foo to be upgraded to use constructor promotion and possibly also readonly.

**Comment by samsonasik** [comment]
That's because php 5.2 Rector rules not yet included in level set list, should be resolved at PR:

- https://github.com/rectorphp/rector-src/pull/3139

while wait for merge,you can do:

```php
SetList::PHP_52,
```

to config, see https://getrector.org/demo/37851243-d0d1-48a2-9cf9-97f85a4bb93f
