### ISSUE TITLE
System error: "Syntax error, unexpected ':', expecting ',' or ']' or ')':1"

### ISSUE THREAD

**Issue by themrwilliams** [rectorphp/rector#7635]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.8|

## Minimal PHP Code Causing Issue

https://getrector.org/demo/84d4b4d6-0565-44fc-8354-639bfc5631a7

## Expected Behaviour

I honestly have no idea.

**Comment by samsonasik** [comment]
That's seems due to `PregReplaceEModifierRector`, ref https://getrector.org/demo/d1c86304-9f2a-4614-b636-f9bb1ebdaa16

You can skip the rule for that case for now:

```php
return static function (RectorConfig $rectorConfig): void {
    // other config ...

    $rectorConfig->skip([
          \Rector\Php55\Rector\FuncCall\PregReplaceEModifierRector::class => [
                 __DIR__ . '/path/to/file.php' 
          ]
    ]);
};
```

**Comment by themrwilliams** [comment]
Thanks for the fast fix @samsonasik !  Confirmed it works for me.
