### ISSUE TITLE
0.15.0 Regression on SimplifyIfElseWithSameContentRector PHP notice

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7638]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.0             |

Rector fails and creates a PHP notice internally 
Worked before 0.15.0

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1d6243b2-ab0c-4002-814c-86f36b465412

## Expected Behaviour

No error

**Comment by samsonasik** [comment]
@TomasVotruba it probably due to `->indent()` change PR:

- https://github.com/rectorphp/rector-src/pull/3145

**Comment by samsonasik** [comment]
@kkmuffme you can configure with set indent count to 4 for now:

```php
$rectorConfig->indent( "\t", 4 );
```

Ref https://getrector.org/demo/f7376e0b-44a3-4f87-9069-aa502a06e0f2

**Comment by samsonasik** [comment]
Yes, you can try dev-main for now.
