### ISSUE TITLE
[Feature] ParentClassToTraitsRector support new parent type

### ISSUE THREAD

**Issue by jaapio** [rectorphp/rector#7639]
# Feature Request

The ParentClassToTraitsRector should have support for a new parent. This becomes useful when parent classes are changed into traits but have a base class that needs to be extended.  I see two options for this:

1. replace the parent by it's parent automatically. Given this class:
```
class IntegrationTest extends TestCase {}
```

```diff
-class MyTestCase extends IntegrationTest
+class MyTestCase extends TestCase
+{
+   use IntegrationTestTrait;
```

And in this situation
```
class IntegrationTest {}
```

```diff
-class MyTestCase extends IntegrationTest
+class MyTestCase
+{
+   use IntegrationTestTrait;
```

TBD: should this be configurable?

2. Make the new parent class a configuration option. 

## Diff 

```diff
-class MyTestCase extends IntegrationTest
+class MyTestCase extends TestCase
+{
+   use IntegrationTestTrait;
```

**Comment by TomasVotruba** [comment]
Hi, this is a different operation, so it should be handled by own rule.
