### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector with SensitiveParameter attribute

### ISSUE THREAD

**Issue by mbabker** [rectorphp/rector#7644]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.15.0      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/cd6191ec-6e65-4c8c-882f-7e69c3ed6808

```php
<?php

final class ApiClient
{
    private readonly string $apiKey;

    public function __construct(
        #[\SensitiveParameter] string $apiKey,
    ) {
        $this->apiKey = $apiKey;
    }
}
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

The `SensitiveParameter` attribute only targets parameters, so constructor arguments with this attribute should not use property promotion.

**Comment by samsonasik** [comment]
Per-discussion on https://github.com/rectorphp/rector-src/pull/3165#issuecomment-1343336049

I re-open it as the actual bug is the attribute group should be kept during converting to property promotion.
