### ISSUE TITLE
Incorrect behavior of TypedPropertyFromAssignsRector

### ISSUE THREAD

**Issue by bds-viktoras** [rectorphp/rector#7645]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/29451cd1-2f23-4efb-ba79-5867930c84c3

```php
<?php

namespace Admin\Services;

use Symfony\Component\Translation\TranslatorInterface;
use Admin\Services\Reporting as AdminReporting;

class FooBar
{
    private $translator;
    private $reportingService;
    
    public function __construct(
        TranslatorInterface $translator,
        AdminReporting $reportingService
    ) {
        $this->translator = $translator;
        $this->reportingService = $reportingService;
    }
}
```

### Responsible rules

* `TypedPropertyFromAssignsRector`

## Expected Behavior

    private TranslatorInterface $translator;
    private AdminReporting $reportingService;

### last dev-version result
    private $translator;
    private AdminReporting $reportingService;

### v0.15 result
    private \Symfony\Component\Translation\TranslatorInterface $translator;
    private AdminReporting $reportingService;

**Comment by samsonasik** [comment]
You need to ensure the interface autoloaded, see 

https://getrector.org/demo/8cc987b7-a4de-4552-8cf7-527f21ed0f97

Ref documentation for it 

https://getrector.org/documentation/static-reflection-and-autoload

**Comment by bds-viktoras** [comment]
I wasn't aware of this requirement for the demo, thanks for letting me know. 

Nevertheless, why FQN for `private \Symfony\Component\Translation\TranslatorInterface $translator;` is used, instead of the `private TranslatorInterface $translator;`? The class is imported via `use`, already used in the short form in __construct() params, and is defined in phpdoc (not in the demo, but in the actual code).

> You need to ensure the interface autoloaded, see
> 
> https://getrector.org/demo/8cc987b7-a4de-4552-8cf7-527f21ed0f97
> 
> Ref documentation for it
> 
> https://getrector.org/documentation/static-reflection-and-autoload

**Comment by samsonasik** [comment]
You can use `$rectorConfig->importNames();` config for that:

```php
$rectorConfig->importNames();
```

The auto import will only works on single namespace in single file, so it not shown in demo page as multi namespace there :)

But when you have 1 namespace per-file, the auto import will pick it up.
