### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector, ReadOnlyClassRector

### ISSUE THREAD

**Issue by Yoann-TYT** [rectorphp/rector#7646]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/9b44dfe4-8825-4ab9-a516-d3907f7e5a09

```php
class A
{
}

final class B extends A
{
    public function __construct(private readonly int $foo)
    {
    }

    public function compute(): int
    {
        return $this->foo * 3;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

* `ReadOnlyClassRector`

## Expected Behavior

class B should not be defined as readonly because parent class is not.

This generate the following error 

```
PHP Fatal error:  Readonly class B cannot extend non-readonly class A in
```

**Comment by samsonasik** [comment]
Could you try provide a patch for it? You can loop parent class reflection and verify if there is non-readonly class, something like this:

```php
        $classReflection = $this->reflectionResolver->resolveClassReflection($node);
        if (! $classReflection instanceof ClassReflection) {
            return null;
        }

        $parents = $classReflection->getParents();
        foreach ($parents as $parent) {
            if (! $parent->isReadOnly()) {
                return null;
            }
        }
``` 

Thank you.
