### ISSUE TITLE
Incorrect behavior of RemoveUnusedVariableAssignRector, RemoveUnreachableStatementRector

### ISSUE THREAD

**Issue by fredams** [rectorphp/rector#7648]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/52a4b156-4d59-4f34-95eb-85dac1889b79

```php
<?php

final class DemoFile
{
    public $x;
    
    public function run()
    {
        $x = new stdClass();
        
        return 5;

        // we never get here
        return 10;
    }
}
```

### Responsible rules

* `RemoveUnusedVariableAssignRector`

* `RemoveUnreachableStatementRector`

## Expected Behavior

`new stdClass(); ` must be deleted

**Comment by samsonasik** [comment]
That's on purpose as `CallLike` may cause side effect, so left to user to delete it or not :)

**Comment by samsonasik** [comment]
I am closing it as the result is expected.
