### ISSUE TITLE
Rector hangs on a particular file

### ISSUE THREAD

**Issue by rcmcdonald91** [rectorphp/rector#7649]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.15 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

https://github.com/pfsense/pfsense/blob/master/src/etc/inc/priv.defs.inc

This file is one that is automatically generated, so it is skipped during normal Rector passes. However, this file is problematic for Rector. Rector just hangs processing this file and I haven't been able to work out why that is

## Expected Behaviour

Rector should not hang

**Comment by samsonasik** [comment]
Looking at your rector config, it seems you are using custom rector rule

https://github.com/pfsense/pfsense/blob/63a0efce7eb90ddea102e79a6750d4c19605f1cf/rector.php#L39

The bug may be in logic in your rule, you can debug with rector-debugging https://github.com/rectorphp/rector-debugging or other tools with `-vvv` command.

Also try using other existing rector rule, if the issue persist, that can be something todo:

- Reduce file size and verify if it works on small array structure
- troubleshoot parallel config https://getrector.org/documentation/troubleshooting-parallel
- debug and find if there is bug in rector somewhere, and try to provide a patch if you can :)
-

**Comment by staabm** [comment]
you are right that this might get faster with the linked PR.

the file itself looks like it would not benefit from using phpstan/rector on it, therefore I think it should be put on the ignore path for both tools though

**Comment by samsonasik** [comment]
Ok 👍 , based on @staabm suggestion, ignore the file is the way to go, as the file itself is autogenerated.

I am closing it then ;)
