### ISSUE TITLE
`System error: "PhpParser\Internal\TokenStream::getIndentationBefore(): Return value must be of type int, null  returned`

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#7652]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.0 and `dev-main`            |

## Minimal PHP Code Causing Issue

Error only happens if `SetList::CODE_QUALITY` and `SetList::CODING_STYLE` used together.

`SetList::CODE_QUALITY` tries to change `'App\Foo'` to `\App\Foo::class` and ``SetList::CODING_STYLE`` tries to change the `if` to just `return str_starts_with...` and these both changes conflict somehow.

https://getrector.org/demo/8e224945-cba6-4800-a490-a74ac4398b0e
## Expected Behaviour

No error.

**Comment by samsonasik** [comment]
it seems due to combination between these rules:

```php
        SimplifyIfReturnBoolRector::class,
        NewlineAfterStatementRector::class,
        StringClassNameToClassConstantRector::class,
```

Ref https://getrector.org/demo/de26d5f5-5c00-43e9-847f-c7b37605906e
