### ISSUE TITLE
Incorrect behavior of CommandConstantReturnCodeRector, ConsoleExecuteReturnIntRector, CommandPropertyToAttributeRector

### ISSUE THREAD

**Issue by thePanz** [rectorphp/rector#7653]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/fb8864a6-1f8f-4304-ac5f-d2047471425a

```php
<?php

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;

#[AsCommand(
    name: 'demo:status',
    description: 'Some description here',
)]
class CieffeStatusRemoteSyncCommand extends Command
{
     protected function execute(InputInterface $input, OutputInterface $output): int
    {
            $output->writeln('hi');
     }
}
```

### Responsible rules

* `CommandConstantReturnCodeRector`

* `ConsoleExecuteReturnIntRector`

* `CommandPropertyToAttributeRector`

## Expected Behavior

The `description` of the `#[AsCommand]` attribute should not be removed

**Comment by samsonasik** [comment]
It already reported https://github.com/rectorphp/rector-symfony/pull/305

**Comment by TomasVotruba** [comment]
@samsonasik Thanks :+1: 

Closing as duplicate of  https://github.com/rectorphp/rector-symfony/pull/305

**Comment by thePanz** [comment]
Thansk @samsonasik and @TomasVotruba
