### ISSUE TITLE
System error: "PhpParser\Node\Stmt\Foreach_::__construct(): Argument #2 ($valueVar) must be of type PhpParser\Node\Expr, null given

### ISSUE THREAD

**Issue by scottybcoder** [rectorphp/rector#7654]
# Bug Report

 [ERROR] Could not process "/home/dev4/public_html/modules/Forums/viewtopic.php" file, due to:
         "System error: "PhpParser\Node\Stmt\Foreach_::__construct(): Argument #2 ($valueVar) must
         be of type PhpParser\Node\Expr, null given, called in
         vendor/rector/rector/rules/Php72/Rector/While_/WhileEachToForeachRector.php:97"
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 31

## Minimal PHP Code Causing Issue

# Mod: XData v1.0.3 START

          reset($poster_xd);
          while(list($code_name,) = each($poster_xd))
		  {
             /*$poster_xd[$code_name] = str_replace('\"', '"', substr(preg_replace('#(\>(((?>([^><]+|(?R)))*)\<))#se', 
		     "preg_replace(\$orig_word, \$replacement_word, '\\0')", '>' . $poster_xd[$code_name] . '<'), 1, -1));*/
		    $poster_xd[$code_name] = preg_replace($orig_word, $replacement_word, $poster_xd[$code_name]);
		  }
# Mod: XData v1.0.3 END

## Expected Behaviour

Convert to foreach,,,

**Comment by samsonasik** [comment]
It seems reproduced at https://getrector.org/demo/68c74646-9414-4da0-a70c-e62df628c513 on `WhileEachToForeachRector`

**Comment by scottybcoder** [comment]
> It seems reproduced at https://getrector.org/demo/68c74646-9414-4da0-a70c-e62df628c513 on `WhileEachToForeachRector`

Thank you I will give that a try.
