### ISSUE TITLE
RECTOR MISS - Unsupported operand types: string + float when working with gmdate and upgrading to PHP8.1

### ISSUE THREAD

**Issue by scottybcoder** [rectorphp/rector#7655]
# Bug Report
https://getrector.org/demo/d4744b1b-e8c3-4ea4-9754-72ceaab6b165

https://stackoverflow.com/questions/74759715/rector-miss-unsupported-operand-types-string-float-when-working-with-gmdate

I guess I was expecting it to modify the code for PHP 8.1

I posted it to the stack.

Rector just skipped right over it.

It seems on many occasions it missed the foreach conversion as well in different various files. It seems it will miss in variations of syntax or nested whiles.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by scottybcoder** [comment]
> Thank you for your report!
> 
> We'll need an isolated failing demo link from: http://getrector.org/demo, that way we can reproduce the bug.

I added the demo.

**Comment by scottybcoder** [comment]
> Thank you for your report!
> 
> We'll need an isolated failing demo link from: http://getrector.org/demo, that way we can reproduce the bug.

I also am using MariaDB and var_dump has been taken out. Is there another command to use in MariaDB?

**Comment by TomasVotruba** [comment]
The demo works correctly :+1:

**Comment by scottybcoder** [comment]
> The demo works correctly 👍

Yes, it appears to be but the code will not work in PHP 8.1 - unsupported operand types string+float on this line:

**Comment by scottybcoder** [comment]
> The demo works correctly 👍

FIXED: Removed error control - PHP 8.1 does not support @

Warning

Prior to PHP 8.0.0, the error_reporting() called inside the custom error handler always returned 0 if the error was suppressed by the @ operator.

As of PHP 8.0.0, it returns the value E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR | E_PARSE.

If you could when it refactors remove the @ as it is not supported in PHP 8 and 8.x Thanx ScottyBcoder

**Comment by TomasVotruba** [comment]
Thanks for sharing you've solved your case :+1: 

> If you could when it refactors remove the @ as it is not supported in PHP 8 and 8.x Thanx ScottyBcoder

That would require a new rule. Feel free to contribute one :pray:
