### ISSUE TITLE
ReadOnlyClassRector should ignore classes extending non-readonly classes

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#7656]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.0             |

## Minimal PHP Code Causing Issue
```
use Symfony\Component\Console\Command\Command;

final class NotificationCommand extends Command
{
    public function __construct(private readonly EntityManagerInterface $entityManager)
    {
    }
}

```
## Expected Behaviour
```

-final class NotificationCommand extends Command
+final readonly class NotificationCommand extends Command

```

> Readonly class `App\Command\NotificationCommand` cannot extend non-readonly class

I'd like to create a bug report using the demo website, but I wasn't able to create a reproducer on the website. When I add `use Symfony\Component\Console\Command\Command;` to the top of the example, it works as expected. But without, Rector doesn't know about that `Command` class and has no reason to prevent it from adding `readonly`.

How to tell the demo website or the test suite what the Symfony class (Controller, FormType, Command, ConstraintValidator) what it's like?

**Comment by samsonasik** [comment]
That's already resolved in `dev-main`, see PR:

- https://github.com/rectorphp/rector-src/pull/3169

you can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer update rector/rector:dev-main
```

**Comment by TomasVotruba** [comment]
Closed as solved :+1:
