### ISSUE TITLE
`sysctl: command not found` when using rector on MacOS

### ISSUE THREAD

**Issue by boesing** [rectorphp/rector#7657]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.0 |

Hey there, when I run `rector`, I do get `sysctl: command not found` error due to the execution of `sysctl` on my Mac which does not exist.

## Minimal PHP Code Causing Issue

No PHP code necessary.

## Expected Behaviour

I'd expect that the CPU count is detected properly on whatever OS the developer is using.
I've seen that some other tools are switching to https://github.com/theofidry/cpu-core-counter as it provides multiple ways to detect the CPU core counter. Thats also the case for https://github.com/symplify/easy-parallel which is used in this tool.

Sadly, the easy-parallel component which implemented the theofidry/cpu-core-counter does only support PHP 8.1+ and thus it might become a problem to actually fix that problem for MacOS users.

**Comment by samsonasik** [comment]
Rector is build based on rector-src which shipped as downgraded to php 7.2 compatible code https://github.com/rectorphp/rector. 

When next easy-parallel released, the `rector-src` will include it, and then will be compatible php 7.2 code under scoped `vendor/` at https://github.com/rectorphp/rector/tree/main/vendor

I used macOS as well, and I can't reproduce it. is disable parallel working ? Here step by step to troubleshoot it https://getrector.org/documentation/troubleshooting-parallel

**Comment by samsonasik** [comment]
I use macOS 12.6.1 and it seems working ok on latest 0.15.0 and dev-main. 

Yes, that should will be on downgraded vendor code.

**Comment by boesing** [comment]
My path does not include sbin and thus it might be the problem. 

Will see if that fixes this issue.

**Comment by samsonasik** [comment]
rector/rector:dev-main already use latest [symplify/easy-parallel](https://github.com/symplify/easy-parallel) that uses [theofidry/cpu-core-counter](https://github.com/theofidry/cpu-core-counter), could you try and verify if it works ?

**Comment by boesing** [comment]
I fixed my `PATH` variable meanwhile and thus, issue does not exist anymore. 
In case rector `dev-main` includes latest `theofidry/cpu-core-counter`, I am pretty sure that this is fixed as I could find multiple methods which would detect the CPU core-count for MacOS even tho the PATH does not include `*/sbin` directories for non-superusers.

**Comment by samsonasik** [comment]
Thank you for verify 👍
