### ISSUE TITLE
Allow readonly properties again on Doctrine entities

### ISSUE THREAD

**Issue by darthf1** [rectorphp/rector#7659]
# Feature Request

Doctrine entities are excluded from the [ReadonlyPropertyRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#readonlypropertyrector)

https://github.com/rectorphp/rector/blob/d2059134fe865511a13033c4d05b82cfe2bc84aa/src/NodeManipulator/PropertyManipulator.php#L57

Since `Doctrine ORM 2.11` (with PHP 8.1), readonly properties are [supported](https://www.doctrine-project.org/2022/01/11/orm-2.11.html).

It would be great if Doctrine entites will only be excluded, if Doctrine ORM < `2.11`.

**Comment by samsonasik** [comment]
That will be new special rule at `rector-doctrine` to be registered at `doctrine-dbal-211` config set list I guess:

https://github.com/rectorphp/rector-doctrine/blob/main/config/sets/doctrine-dbal-211.php

since that only can happen on doctrine >= 2.11.

Feel free to create feature PR for it ;)

**Comment by darthf1** [comment]
Should it not be the other way around?

Now, theres an exclusion defined in `PropertyManipulator.php`, outside the normal rules. Shouldn't:
- the exclusion be removed so the "regular" `ReadonlyPropertyRector` can do its work
- logic be added ReadonlyPropertyRector is skipped on Doctrine entities when ORM < 2.11

Or simpler:
- make changes so the current exclusion criteria in `PropertyManipulator` is only checked if ORM < 2.11

**Comment by samsonasik** [comment]
No, as user may directly use `ReadonlyPropertyRector` in any code and then it got replaced to readonly.

Current skip is the safest, and the specific condition will need in rector-doctrine on rector 2.11 setlist.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer to Doctrine Rector extension: 
https://github.com/rectorphp/rector-doctrine


Thank you for understanding :slightly_smiling_face:
