### ISSUE TITLE
Child non-readonly class doesnt refactor it into readonly when the parent was readonly class

### ISSUE THREAD

**Issue by kevariable** [rectorphp/rector#7665]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.0             |
| PHP Version | v8.2             |

i had issue when i extends the readonly class which child class doesnt have readonly

```php
readonly abstract class Action
{
}
```

child

```php
class Something extends Action
{
}
```

## Expected Behaviour

i expect this is will automatically add the readonly when the parent was readonly

```php
readonly abstract class Action
{
}
```

child

```php
readonly class Something extends Action
{
}
```

**Comment by samsonasik** [comment]
Fixed in Rector 0.15.1, please update :)

**Comment by kevariable** [comment]
@samsonasik Hi,

it didnt work after up into 0.15.1, here my config

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->parallel();

    $rectorConfig->sets([SetList::PHP_82, LevelSetList::UP_TO_PHP_81]);

    $rectorConfig->phpVersion(PhpVersion::PHP_82);
    
    $rectorConfig->paths([
        __DIR__ . '/src',
    ]);
};
```

**Comment by samsonasik** [comment]
I see, that's expected, the child of your class is not final class, that's why readonly is forbidden. 

You can try `FinalizeClassesWithoutChildrenRector` rule for that to finalize class without children.

**Comment by samsonasik** [comment]
Ok, I just retried, even class is not final, if the class extends readonly class, it must be readonly too, ref https://3v4l.org/D9N7A

Re-open then ;)
