### ISSUE TITLE
Unexpected behavior with JoinStringConcatRector rule

### ISSUE THREAD

**Issue by vralle** [rectorphp/rector#7667]
# Bug Report

| Subject | Details |
| :--------| :--------|
| Rector  | v0.15.0  |
| PHP      | v8.1.0    |

## Minimal PHP Code Causing Issue
`rector --dry-run` in terminal of VS Code:
```php
protected function isGzipped(string $content): bool
     {
-        return mb_strpos($content, "\x1f" . "\x8b" . "\x08") === 0; // phpcs:ignore Generic.Strings.UnnecessaryStringConcat.Found
+        return mb_strpos($content, ') === 0; // phpcs:ignore Generic.Strings.UnnecessaryStringConcat.Found
     }
```
It is not entirely clear whether the Rector breaks the code, or whether these are output features in the terminal. The changes look unusable, so no action has been taken.

## Expected Behaviour
Multibyte characters must remain unchanged in the code and for display in the terminal.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by vralle** [comment]
https://getrector.org/demo/c45a8322-f461-424f-8794-3291c1291bff

The result is different, but also looks strange.

**Comment by vralle** [comment]
One of the problems is how Rector displays multibyte characters. Such characters have disappeared from the VS Code terminal. In Rector Try the characters look different, but are also invalid for accepting changes.

**Comment by TomasVotruba** [comment]
Thank you for the demo link.

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
It possibly bug on php-parser on printing content, just compare it, it got the following diff:

```diff
-return mb_strpos($content, "\x1f" . "\x8b" . "\x08") === 0;
+return mb_strpos($content, '\x1F‹\x08') === 0;
```
