### ISSUE TITLE
Incorrect behavior of CommandPropertyToAttributeRector

### ISSUE THREAD

**Issue by SiMoeBoe** [rectorphp/rector#7669]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/4a492ce4-200c-409d-9711-fbb6da2e701f

```php
<?php

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;

#[AsCommand('my:command', 'My command description')]
class CleanupPortfolioFilesCommand extends Command
{

}
```

### Responsible rules

* `CommandPropertyToAttributeRector`

## Expected Behavior

Rector should skip this code. But instead of skipping it adds the namespace inside the attribute and remove the command description from the attribute. Rector should recognize, that the Command has the correct attribute and skip.

**Comment by samsonasik** [comment]
Already reported at https://github.com/rectorphp/rector-symfony/pull/305

**Comment by TomasVotruba** [comment]
Closing as duplicate mentioned by @samsonasik
