### ISSUE TITLE
[ERROR] Failed to create "/tmp/rector_cached_files/26": mkdir(): Permission denied

### ISSUE THREAD

**Issue by scottybcoder** [rectorphp/rector#7670]
# Question

Same server rector runs fine on php-nuke-titanium.86it.us

I get [ERROR] Failed to create "/tmp/rector_cached_files/26": mkdir(): Permission denied on rector.86it.us same config?

What can I do to make this where it is able to create the tmp dir??

Thanks

**Comment by scottybcoder** [comment]
> # Question
> 
> Same server rector runs fine on php-nuke-titanium.86it.us
> 
> I get [ERROR] Failed to create "/tmp/rector_cached_files/26": mkdir(): Permission denied on rector.86it.us same config?
> 
> What can I do to make this where it is able to create the tmp dir??
> 
> Thanks

The answer to this question can be fond here:
https://stackoverflow.com/questions/74815545/rector-failed-to-create-tmp-rector-cached-files-26-mkdir-permission-denie/74816753#74816753

**Comment by samsonasik** [comment]
It seems you found the solution, I am closing it then ;)
