### ISSUE TITLE
Incorrect behavior of RenamePropertyToMatchTypeRector

### ISSUE THREAD

**Issue by atesca09** [rectorphp/rector#7672]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/4d56e655-adbd-4793-ad19-efdb46fdee80

```php
<?php

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

final class SkipDoctrineCollection
{
    /**
     * @var Collection<int, Checkbox>
     */
    private Collection $checkboxes;

    public function __construct()
    {
        $this->checkboxes = new ArrayCollection();
    }

    public function getCheckboxes(): Collection
    {
        return $this->checkboxes;
    }
}
```

but there no changes if the property is public

See https://getrector.org/demo/a907458f-45dc-4467-b879-f9862575f1c3

```php
<?php

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

final class SkipDoctrineCollection
{
    /**
     * @var Collection<int, Checkbox>
     */
    public Collection $checkboxes;

    public function __construct()
    {
        $this->checkboxes = new ArrayCollection();
    }

    public function getCheckboxes(): Collection
    {
        return $this->checkboxes;
    }
}
```

and no changes if there are 2 private Collections

See https://getrector.org/demo/460b439c-6dcc-4ec9-8c98-64f1c4e218f4

```php
<?php

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

final class SkipDoctrineCollection
{
    /**
     * @var Collection<int, Checkbox>
     */
    private Collection $checkboxes;

    /**
     * @var Collection<int, Radiobox>
     */
    private Collection $radioboxes;

    public function __construct()
    {
        $this->checkboxes = new ArrayCollection();
        $this->radioboxes = new ArrayCollection();
    }

    public function getCheckboxes(): Collection
    {
        return $this->checkboxes;
    }

    public function getRadioboxes(): Collection
    {
        return $this->radioboxes;
    }
}
```

### Responsible rules

* `RenamePropertyToMatchTypeRector`

## Expected Behavior

No changes

**Comment by samsonasik** [comment]
That's seems expected if public property not changed, as that mean BC break. 

For at least 2 Occurences, that skipped, as naming properties `$collection1` and `$collection2` will missleading.

**Comment by atesca09** [comment]
True, but I think Doctrine Collections should be skipped while renaming properties.

Especially since there's already a test for that scenario.
See: https://github.com/rectorphp/rector-src/blob/5a4111e518e866379e5cdce1d9b3b282dfccaa3d/rules-tests/Naming/Rector/Class_/RenamePropertyToMatchTypeRector/Fixture/skip_doctrine_collection.php.inc

If it's not renamed because it is public the test is useless

**Comment by samsonasik** [comment]
You need to have `Doctrine\Common\Collections\Collection` autoloaded, on rector-src, thats on stubs

https://github.com/rectorphp/rector-src/blob/main/stubs/Doctrine/Common/Collections/Collection.php

Please read documentation for autoload troubleshooting https://getrector.org/documentation/static-reflection-and-autoload

**Comment by samsonasik** [comment]
Ok, it seems a bug, introduced by PR match type:

- https://github.com/rectorphp/rector-src/pull/3189


/cc @TomasVotruba
