### ISSUE TITLE
Incorrect behavior of AddClosureReturnTypeRector

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#7673]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.15.1      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e6017a60-ae16-4033-8134-e484cd368eb4

```php
<?php
final class DemoFile
{
    public function someFunction(string $type): array
    {
        return collect($this->types, static function (SomeClass $parameterType, int $index) use ($type) {
            if ($parameterType::class === $type) {
                yield $index;
            }
        });
    }
}
```

### Responsible rules

* `AddClosureReturnTypeRector`

## Expected Behavior

It should add "iterable" as the return type instead of "void".

**Comment by samsonasik** [comment]
It should be skipped, as it can return yield or not return at all, could you try provide a patch? Thank you.

**Comment by gnutix** [comment]
Sorry, but I don't have any more time to dedicate to this. Hopefully someone can.
