### ISSUE TITLE
Fix php8-related "array key undefined" issues with rector?

### ISSUE THREAD

**Issue by Defcon0** [rectorphp/rector#7674]
Hello,

at first a major thanks for the awesome work you do with rector! I used it for some modules and it worked great so far.

Only one thing I couldn't fix with it so far. I suspect, it's explained with logical issues, but we'll see ;-)

In php8 undefined array keys became warnings instead of notices which produces much code not being used in dev mode anymore.

So far I could't find a way to automatically fix these issues with some change like

```
if ($array['index']) { ... } => if ($array['index'] ?? null) { ... }
```

Is there anything, rector can do about that?

Thanks in advance!

Bye Defcon0

**Comment by samsonasik** [comment]
I think that's phpstan job to verify as the logic to handle that may be vary, eg: handle with isset vs handle with error handler on php warning ref https://phpstan.org/r/52a229e3-9d7e-43b7-9d5b-0156465a3fb7

**Comment by samsonasik** [comment]
I am closing it, as rector is not error handler, use phpstan job as the right tool to get there, and decide what need to do in the code ( check isset, use error handler to trap the error and send to log, etc) :)
