### ISSUE TITLE
RECTOR does not fix the Array to string conversion...

### ISSUE THREAD

**Issue by scottybcoder** [rectorphp/rector#7675]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue
function get_request_string($mode='request') 
 {
   $ST_POST = ($mode == 'request') ? $_REQUEST : ( ($mode == 'post') ? $_POST : $_GET );
   $ignore = ['message', 'subject', 'bodytext', 'hometext', 'add_title', 'add_content', 'title', 'content', 'notes'];
   $poststring = "";

   foreach ($ST_POST as $postkey => $postvalue):
 	if(!in_array(strtolower($postkey),$ignore)) 
	$poststring .= (empty($poststring) ? "" : "&") .$postkey."=".$postvalue; <--- this line throws Array to string error
   endforeach;
   return str_replace("%09", "%20", $poststring);
 }

RECTOR DOES NOTHING

## Expected Behaviour

RECTOR should fix the array to string conversion

**Comment by samsonasik** [comment]
Same with https://github.com/rectorphp/rector/issues/7674, that's phpstan job to verify  as the logic to handle that may be vary, eg: handle with is_array, is_string, or just remove the code :), that will depends of the usage you want.

ref https://phpstan.org/r/2717751a-0da2-47ac-86eb-a63999ca7523

**Comment by samsonasik** [comment]
I am closing it, as rector is not error handler, use phpstan job as the right tool to get there, and decide what need to do in the code ( check is_array,is_string, or just remove the code, etc) :)
