### ISSUE TITLE
Allow removal of rector rules in config

### ISSUE THREAD

**Issue by xvilo** [rectorphp/rector#7676]
As of v0.15 the methods `RectorConfig` exposes are more and more specific. However, we don't have active access any more to the parameters and services getters. I used these to remove certain rules from larger RuleSets. Instead of adding all the rules specifically, I can just remove a couple. This makes maintenance of the config file a lot easier. 

This was already asked in https://github.com/rectorphp/rector/issues/7575 and the answer given was to use the `skip()` method. I've applied this on our project, with 0.15.0. However, it seems these rules still got applied. See these 2 screenshots:

Snippet of config:
<img width="512" alt="Screenshot 2022-12-19 at 09 20 58" src="https://user-images.githubusercontent.com/390769/208380386-12f608f0-a7bf-4bb7-82fb-19ba470f35f5.png">

Applied rules output:
<img width="749" alt="Screenshot 2022-12-19 at 09 21 01" src="https://user-images.githubusercontent.com/390769/208380769-4e7d0a21-43d7-4f79-b816-3ebce6e2eaf9.png">

As you can see, both `UnionTypesRector` and `FinalizePublicClassConstantRector` are added as “skipped” rule. Unfortunately, they do get applied. It would be great if this could be a feature again. 

For reference, our config file looked similar to this:
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Php80\Rector\FunctionLike\UnionTypesRector;
use Rector\Php81\Rector\ClassConst\FinalizePublicClassConstantRector;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rector): void {
    // here we can define, what sets of rules will be applied
    // tip: use "SetList" class to autocomplete sets
    $rector->import(LevelSetList::UP_TO_PHP_82);

    // Disable rules from SetLists we (currently) don't want
    $services = $rector->services();
    $services->remove(FinalizePublicClassConstantRector::class)
        ->remove(UnionTypesRector::class)
        ->remove(AddLiteralSeparatorToNumberRector::class)
        ->remove(TypedPropertyRector::class);

    $rector->parallel(240);
    $rector->importNames();
    $rector->phpVersion(PhpVersion::PHP_81);
    $rector->paths([
        __DIR__ . '/public',
        __DIR__ . '/src',
    ]);
    $rector->skip([
        __DIR__ . '/some/php/file.php',
        __DIR__ . '/another_directory_to_skip'
    ]);

    $runsInGitlabCi = \getenv('GITLAB_CI');
    if ($runsInGitlabCi !== \false) {
        $rector->cacheDirectory(__DIR__ . '/.rector/cache');
    }
};
```

**Comment by samsonasik** [comment]
Are you sure you use pointed to correct class, eg: add `Rector\Php80\Rector\FunctionLike\UnionTypesRector` in use statements?

we may need a sample reproducible repository for it with github action running.

**Comment by xvilo** [comment]
@samsonasik I just edited the issue while you were commenting, does that help with the config file? Otherwise I can see if I can create a test repo here on GH

**Comment by samsonasik** [comment]
That seems can't be reproduced in getrector.org/demo

- not skipped (applied as expected) https://getrector.org/demo/5cc09a0a-70f0-494b-9bf1-5b1bff107e50
- skipped (skipped as expected) https://getrector.org/demo/6a8c77d9-ffc6-454b-9b5e-0189e5a3ff67

**Comment by samsonasik** [comment]
I am closing it as it can't be reproduced via `skip()` like stated in previous comment.

Feel free to open new issue with provide a sample reproducible repository for it with github action running.
