### ISSUE TITLE
Incorrect behavior of InlineConstructorDefaultToPropertyRector

### ISSUE THREAD

**Issue by stefantalen** [rectorphp/rector#7677]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/7ce64c07-ecc3-4676-9e55-c68112ce63bf

```php
<?php

final class DemoFile
{
    /**
     * @string
     */
    private $url;
    
    public function __construct()
    {
        $this->url = 'https://website.tld';
    }
    
    public function getUrl() {
        return $this->url;
    }
}
```

### Responsible rules

* `InlineConstructorDefaultToPropertyRector`
*  `TypedPropertyFromStrictConstructorRector`

## Expected Behavior
When using both rules, the order seems to matter.

1. InlineConstructorDefaultToPropertyRector
2. TypedPropertyFromStrictConstructorRector

Results in
```diff
-    private $url;
+    private string $url;
```
however the other way around it sets the correct value for the property.
```diff
-    private $url;
+    private string $url = 'https://website.tld';
```

Both rules are being import from a set:
```php
$rectorConfig->sets([
        SetList::CODE_QUALITY,
        SetList::TYPE_DECLARATION,
]);
```

**Comment by samsonasik** [comment]
Could you try provide a patch? For multi rules applied, you can add test under 

https://github.com/rectorphp/rector-src/tree/main/tests/Issues

Then, run test, then apply patch, then send a PR

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-src/pull/3225
