### ISSUE TITLE
Paths with spaces not supported on command line

### ISSUE THREAD

**Issue by joelvh** [rectorphp/rector#7690]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.8             |

Passing paths with spaces to the command line causes an error indicating the path does not exist.

## Minimal PHP Code Causing Issue

The command `rector process -- '/my files/file.php'` throws the error `The "files/file.php" directory does not exist.`.

## Expected Behaviour

Expected the command to analyze the file specified as an argument.

I identified that [`Rector\Core\Configuration\ConfigurationFactory::resolvePaths(...)`](https://github.com/rectorphp/rector/blob/main/src/Configuration/ConfigurationFactory.php#L75) splits paths on spaces. When I disable that, the command line works.

Changing from this:

```php
if ($commandLinePaths !== []) {
    return $this->correctBashSpacePaths($commandLinePaths);
}
```

to this:

```php
if ($commandLinePaths !== []) {
    return $commandLinePaths;
}
```

...fixes the issue, but of course this must be here for some reason. However, it breaks for me (on Mac).

I should also note that when I specify multiple files in the command line, the logic in [`resolvePaths`](https://github.com/rectorphp/rector/blob/main/src/Configuration/ConfigurationFactory.php#L75) will replace all paths with the first path found with a space and uses the split values as the new list of source files. That logic is also wrong.

**Comment by samsonasik** [comment]
Handle path with spaces will require e2e test, like this PR:

-  #https://github.com/rectorphp/rector-src/pull/2421

Feel free to provide new e2e test for it, as well as the patch 👍

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

This might be related to the Symfony Console we use here, so please check this feature works there first.

Thank you for understanding :slightly_smiling_face:
