### ISSUE TITLE
TypedPropertyFromAssignsRector - intersection types PHP 7.4.30

### ISSUE THREAD

**Issue by puniserv** [rectorphp/rector#7692]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.1          |
| PHP version | 7.4.30         |
| Applied rules |  RenameClassRector, TypedPropertyFromAssignsRector|

```
<?php

declare(strict_types=1);

namespace Tests;

use DateTime;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    /**
     * @var DateTime&MockObject
     */
    private $property;

    public function testExample(): void
    {
        $this->property = $this->createMock(DateTime::class);
        $this->property->expects(self::once())->method('format');
        $this->property->format('Y');
    }
}

```

## Current modification
```
-    /**
-     * @var DateTime&MockObject
-     */
-    private $property;
+    private ?MockObject $property = null;
```

## Expected Behaviour

Rector should not change this file with this rules

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by puniserv** [comment]
@TomasVotruba How can I set PHP version in demo?

**Comment by puniserv** [comment]
Ok, got it:
https://getrector.org/demo/5fdba762-22c2-4e66-8da3-6668531d2de3

**Comment by samsonasik** [comment]
The behaviour is correct, it actually `MockObject` or `null` as there is not initiated at `setUp()`

The one that need to be kept is the docblock.

**Comment by puniserv** [comment]
Nope, This is MockObject&DateTime (or (MockObject&DateTime)|null). Take a look at the PHP8 version:
https://getrector.org/demo/a27b897d-007e-4ae8-9870-cb46f7b41a9f

**Comment by samsonasik** [comment]
If you initialize in setUp() method, it will not be nullable, and do not remove the docblock

https://getrector.org/demo/90dc597e-d231-42f2-9005-b02ac9dcc24a

**Comment by puniserv** [comment]
@samsonasik You got it wrong. In PHP74 version intersection type is dropped.

**Comment by samsonasik** [comment]
I see, could you try provide a failing fixture, as well as the fix?

**Comment by puniserv** [comment]
https://github.com/rectorphp/rector-src/pull/3244

I might be able to fix it, but no promises

**Comment by VincentLanglet** [comment]
Personally I have the following behavior
```
    /**
      * @var AuditManagerInterface&MockObject
      */
-    private $auditManager;
+    private MockObject $auditManager;
```
And I keep the same PHPdoc, but I feel like the type selected is not the right one.

When doing
```
    protected function setUp(): void
    {
        $this->auditManager = $this->createMock(AuditManagerInterface::class);
    }
```
You'll later pass the `auditManager` to constructor/method which require an AuditManagerInterface. And you're less concerned about the MockObject part ; this is more true when using `createStub`.

Maybe one day, you'll change to a real object,
```
    protected function setUp(): void
    {
        $this->auditManager = new AuditManagerInterface();
    }
```
And not changing the PHP type would be useful.

Also, I wonder if rector will be able to change to
```
-   /**
-    * @var AuditManagerInterface&MockObject
-     */
-    private $auditManager;
+    private AuditManagerInterface&MockObject $auditManager;
```
on the right PHP version.
