### ISSUE TITLE
Incorrect behavior of IntvalToTypeCastRector, LongArrayToShortArrayRector, TernaryToNullCoalescingRector, ListToArrayDestructRector, ReplaceEachAssignmentWithKeyCurrentRector, NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by scottybcoder** [rectorphp/rector#7697]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/63e67a74-5e27-442a-98b7-4b396e3c642a

```php
<?php

// function block
function get_topic_id($topic)
{
    global $db;
    $topic_id = 0;

    // is this a direct value ?
    $num_topic = intval($topic);
    if ($topic == "$num_topic")
    {
        $topic_id = intval($topic);
    }

    // is it an url with topic id or post id ?
    else
    {
        $name = explode('?', $topic);
        $parms = ( isset($name[1]) ) ? $name[1] : $name[0];
        parse_str($parms, $parm);
        $found = false;
        $topic_id = 0;
        while ((list($key, $val) = each($parm)) && !$found):
        
            $vals = explode('#', $val);
            $val = $vals[0];
            if (empty($val)) $val = 0;
            switch($key)
            {
                case POST_POST_URL:
                    $sql = "SELECT topic_id FROM " . POSTS_TABLE . " WHERE post_id=$val";
                    if ( !($result = $db->sql_query($sql)) ) message_die(GENERAL_ERROR, 'Could not get post informations', '', __LINE__, __FILE__, $sql);
                    if ($row = $db->sql_fetchrow($result))
                    {
                        $val = $row['topic_id'];
                        $found = true;
                    }
                    break;
                case POST_TOPIC_URL:
                    $found = true;
                    break;
            }
            if ($found)
            {
                $topic_id = intval($val);
            }
        endwhile;
    }

    return $topic_id;
}
```

### Responsible rules

* `IntvalToTypeCastRector`

* `LongArrayToShortArrayRector`

* `TernaryToNullCoalescingRector`

* `ListToArrayDestructRector`

* `ReplaceEachAssignmentWithKeyCurrentRector`

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

I should not get the following error after it modifies my code
syntax error, unexpected token ")", expecting "="

**Comment by samsonasik** [comment]
We need reproducible code and config with minimal lines and single or two rules that cause it.

You can narrow down rules half by half until it found the rule(s) that cause it https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by scottybcoder** [comment]
I am using all the rules - the error was being in my code after the conversion when I ran the code.

The following code is what was suppose to be malformed...

        (list($key, $val))[1] = current($parm);
        (list($key, $val))['value'] = current($parm);
        (list($key, $val))[0] = key($parm);
        (list($key, $val))['key'] = key($parm);

**Comment by scottybcoder** [comment]
Message:
syntax error, unexpected token ")", expecting "="
File:
/home/rector/public_html/modules/Forums/merge.php
Line:
110
Stack Trace:

Kine 110 of mu code is (list($key, $val))[1] = current($parm);

**Comment by scottybcoder** [comment]
This is what it converted my code into:

// function block
function get_topic_id($topic)
{
    global $db;
    $topic_id = 0;

    // is this a direct value ?
    $num_topic = (int) $topic;
    if ($topic == "$num_topic")
    {
        $topic_id = (int) $topic;
    }

    // is it an url with topic id or post id ?
    else
    {
#       $name = explode('?', $topic);
#       $parms = ( isset($name[1]) ) ? $name[1] : $name[0];
        $name = explode('?', (string) $topic);
        $parms = $name[1] ?? $name[0];
        parse_str($parms, $parm);
        $found = false;
        $topic_id = 0;
        //while ((list($key, $val) = @each($parm)) && !$found):
		while (!$found):
        
          # $vals = explode('#', $val);
			$vals = explode('#', (string) $val);
            $val = $vals[0];
            if (empty($val)) $val = 0;
            switch($key)
            {
                case POST_POST_URL:
                    $sql = "SELECT topic_id FROM " . POSTS_TABLE . " WHERE post_id=$val";
                    if ( !($result = $db->sql_query($sql)) ) message_die(GENERAL_ERROR, 'Could not get post informations', '', __LINE__, __FILE__, $sql);
                    if ($row = $db->sql_fetchrow($result))
                    {
                        $val = $row['topic_id'];
                        $found = true;
                    }
                    break;
                case POST_TOPIC_URL:
                    $found = true;
                    break;
            }
            if ($found)
            {
              # $topic_id = intval($val);
				$topic_id = (int) $val;
            }
        endwhile;
        (list($key, $val))[1] = current($parm);
        (list($key, $val))['value'] = current($parm);
        (list($key, $val))[0] = key($parm);
        (list($key, $val))['key'] = key($parm);
        next($parm);
    }

    return $topic_id;
}

**Comment by samsonasik** [comment]
We need reproducible code and config with:

- minimal lines 
- single or two rules that cause it.

You need to invest time to narrow down rules half by half until it found the minimal rule(s) that cause it, and the expected output 

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

I am closing it as it won't go anywere unless it has above requirement provided.
