### ISSUE TITLE
ArrayKeysAndInArrayToArrayKeyExistsRector revmoves variables that are used later

### ISSUE THREAD

**Issue by sreichel** [rectorphp/rector#7699]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.2             |
| Rule | ArrayKeysAndInArrayToArrayKeyExistsRector              |

Variables that are used later are ignored.

For example below phpstan now complains about ...

```
249    Undefined variable: $tableAliases                
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/85d78e6e-df97-485e-9412-e90550777ee5

## Expected Behaviour

Skip it. (in this case)

**Comment by samsonasik** [comment]
I am closing it as the rule no longer exists.
