### ISSUE TITLE
Incorrect behavior of TypedPropertyFromColumnTypeRector

### ISSUE THREAD

**Issue by ary-modulor** [rectorphp/rector#7701]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/ccfe081e-19db-43fb-a8f2-cf09e7e74e16

```php
<?php

use Doctrine\ORM\Mapping as ORM;

final class DemoFile
{
    /** @ORM\Column(type="string") */
	private $field;
}
```

### Responsible rules

* `TypedPropertyFromColumnTypeRector`

## Expected Behavior

Doctrine columns are by default not nullable when `nullable` attribute in annotation is missing (see https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/reference/annotations-reference.html#column).

Expected outcome:
```php
<?php

use Doctrine\ORM\Mapping as ORM;

final class DemoFile
{
    /** @ORM\Column(type="string") */
	private string $field;
}

```

**Comment by samsonasik** [comment]
Duplicated with https://github.com/rectorphp/rector/issues/7459, Except an #[ORM\Id] which can be auto, it will be nullable except assigned in constructor

It is expected change without set initialization in constructor.

**Comment by ary-modulor** [comment]
I'm sorry for not seeing #7459 (I was looking in https://github.com/rectorphp/rector-doctrine/issues list).

For a better understanding: You dont want to take the `nullable=false` default for `#[ORM\Column]` since `#[ORM\Id]` requiers a nullable class property?

**Comment by samsonasik** [comment]
nullable=false already taken into account https://getrector.org/demo/b8eb76b0-3ee4-4ea2-8f11-882b9c779015

**Comment by ary-modulor** [comment]
This is great.
I just wonder since doctrine states `nullable` as optional with default `false`:
https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/reference/basic-mapping.html#property-mapping

I'm considering adding everywhere `nullable=false`.

**Comment by samsonasik** [comment]
That's will be dangerous to mark as non-nullable by default, as that rely on third party functionality, which subject to change.

Changing non-typed to typed may break the app unless it stated, eg: strictly defined `nullable=false`.
