### ISSUE TITLE
AddParamBasedOnParentClassMethodRector adds a default value to variadic parameter

### ISSUE THREAD

**Issue by thomasschiet** [rectorphp/rector#7702]
# Bug Report
`AddParamBasedOnParentClassMethodRector` adds `null` as a default value to a variadic parameter, which is invalid PHP code.

## Minimal PHP Code Causing Issue
https://getrector.org/demo/933daa27-1a24-4f6c-9785-52b897de3780

## Expected Behaviour
Doesn't add `null` default value to variadic parameter.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.
