### ISSUE TITLE
Incorrect PHP code is generated with commented-out <?php tags

### ISSUE THREAD

**Issue by DCoderLT** [rectorphp/rector#7703]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main@71448a |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/06f6b4b3-883a-4f6d-9528-246001d66734

```php
<div class="price-box">
    <?php if (($_min = $this->getMinAmount()) && ($_max = $this->getMaxAmount()) && ($_min == $_max)): ?>
        <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
            <?php echo Mage::helper('core')->currency($_min, true, false) ?>
        </span>
    <?php elseif (($_min = $this->getMinAmount()) && $_min != 0): ?>
        <span class="label"><?php echo Mage::helper('brainvire_giftcard')->__('From') ?></span>
        <span class="price" id="min-product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
            <?php echo Mage::helper('core')->currency($_min,true,false) ?>
        </span>
    <?php /*elseif ($_max = $this->getMaxAmount()): ?>
        <span class="label"><?php echo Mage::helper('brainvire_giftcard')->__('Up To') ?></span>
        <span class="price" id="max-product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
            <?php echo Mage::helper('core')->currency($_max,true,false) ?>
        </span>
    <?php */endif; ?>
</div>
```

## Expected Behaviour

When Rector reaches this `endif`, it duplicates the `<?php` tag and the block comment it saw just before, and _introduces a syntax error_ . This should not happen.

**Comment by samsonasik** [comment]
The bug seems only happen on VB-style syntax: with `:` and `endif` usage, when using curly braces `{`, `}`, it seems working ok, ref https://getrector.com/demo/5552773d-c9ac-4a0a-85a8-a877a11c8e48

**Comment by samsonasik** [comment]
This issue is on php-parser itself as it duplicated comment just by printing, I created failing test case PR to nikic/PHP-Parser repository:

- https://github.com/nikic/PHP-Parser/pull/914
