### ISSUE TITLE
Could not open input file

### ISSUE THREAD

**Issue by koeZionCMS** [rectorphp/rector#7704]
Hello,

I installed the component using the command:
`composer require rector/rector --dev`

I then ran:
`vendor/bin/rector init`

The following error is displayed:
`Could not open input file: I\AppData\Local\Temp\70BC.tmp`

I'm in PHP8.1.1 and Symfony 6.2.4

Thanks for help

**Comment by CGNDev2021** [comment]
Hi,

I've the same problem on windows. It seems that the separation of commands and arguments doesn't work correctly, specialy when _spaces_ are in the directory like "C:\users\firstname surname\project".

I'm looking for the source to generate the command-lines.
Sugesstions..?

thx boris

**Comment by samsonasik** [comment]
same with https://github.com/rectorphp/rector/issues/7690, Handle path with spaces will require e2e test to avoid regression, like this PR:

-  https://github.com/rectorphp/rector-src/pull/2421

Feel free to provide new e2e test for it, as well as the patch 👍

**Comment by TomasVotruba** [comment]
Closing for lack of feedback and possible duplicate of https://github.com/rectorphp/rector-src/pull/2421
