### ISSUE TITLE
PHP error - Undefined property: PhpParser\Node\Stmt\Enum_::$extends in AddParamTypeDeclarationRector.php

### ISSUE THREAD

**Issue by Maxell92** [rectorphp/rector#7707]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.4            |

Rector fails on our CI with the following error:

```
 [ERROR] Could not process some files, due to:                                  
         "Child process error: PHP Warning:  Uninitialized string offset -1 in  
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Typ
         e/Constant/ConstantStringType.php281                                   
         Warning: Uninitialized string offset -1 in                             
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Typ
         e/Constant/ConstantStringType.php281                                   
         PHP Warning:  Uninitialized string offset -1 in                        
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Typ
         e/Constant/ConstantStringType.php281                                   
         Warning: Uninitialized string offset -1 in                             
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Typ
         e/Constant/ConstantStringType.php281                                   
         PHP Warning:  Uninitialized string offset -1 in                        
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Typ
         e/Constant/ConstantStringType.php281                                   
         Warning: Uninitialized string offset -1 in                             
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Typ
         e/Constant/ConstantStringType.php281                                   
         Killed                                                                 
         ".                                                                     
Script ./vendor/bin/rector process --dry-run handling the rector event returned with error code 1
```

## Minimal PHP Code Causing Issue

I cannot reproduce this error on my local or in any other project. We upgraded several other projects from 0.14 to 0.15 and they work fine. I also tried to clear the cache, but still nothing.

**Comment by samsonasik** [comment]
Please create simple reproducible repo for that, thank you.

**Comment by Maxell92** [comment]
Well, I will try, but not sure, how to do that. Our main component is a big project and other works fine. I am also not able to reproduce this error on my local, Rector fails only in CI. This is strange, we use the same Docker container. Is there any other option except `--clear-cache` that I should try on local?

**Comment by samsonasik** [comment]
You can narrow down rules half by half until it found the rule(s) that cause it https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

After that, if it can't be reproducible in demo site, it possibly the class/service used is not autoload, we may need reproducible repository for that

**Comment by Maxell92** [comment]
I found the issue and the reason, why it is difficult to reproduce. Our original Rector config:

```
	$rectorConfig->paths([
		__DIR__ . '/src',
		__DIR__ . '/tests',
		__DIR__ . '/migrations',
	]);
```

Once I remove paths and run 2 jobs instead of one (`bin/rector process src --dry-run` and `bin/rector process tests migrations --dry-run`), everything works. Seems it could be caused by memory consumption.
