### ISSUE TITLE
Incorrect behavior of RemoveAlwaysTrueIfConditionRector

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector#7708]
# Bug Report

RemoveAlwaysTrueIfConditionRector removes a valid if clause.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/8b5c6405-457d-4c88-9dfc-74552ce4005b

```php
<?php

namespace App\Controller;

use App\Entity\Payment;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

final class Controller extends AbstractController
{
    #[Route(path: '/payment/handle/{id}', methods: 'GET')]
    public function handle(ManagerRegistry $doctrine, Test $payment)
    {
        if (null === $payment->getProcessedAt()) {
            // We should sleep, and check again if the payment is processed.
            sleep(5);

            // Refresh payment to get latest results
            $doctrine->getManager()->refresh($payment);

            // If we don't have payment, even after a second. We can throw the exception.
            if (null === $payment->getProcessedAt()) {
                throw new \Exception();
            }
        }
    }
}


class Test
{
    public function getProcessedAt(): ?string
    {
        return null;
    }
}
```

### Responsible rules

* `RemoveAlwaysTrueIfConditionRector`

## Expected Behavior

I think the if case after the sleep/refresh function should stay as the `refresh` function would fetch the entity from the db again and in after the 5 second sleep the `getProcessedAt` could return a value other then `null`.

Of course in this example not as `Test` is not a valid Entity from Symfony. Is this something we could change or would that be to complicated or to project specific as refresh is part of Symfony/doctrine.

**Comment by samsonasik** [comment]
You may need to refactor into `do { while }` usage for that so that make sense for retry usage https://getrector.com/demo/71aa1c35-6650-4b64-8741-08c0eb10b113 which the rule is skipped on loop usage.

**Comment by samsonasik** [comment]
I am closing, as per-previous comment, this can be handled by change logic to `do ... while`
