### ISSUE TITLE
Doctrine | TypedPropertyFromColumnTypeRector incorrectly marking properties as nullable

### ISSUE THREAD

**Issue by glennmcewan** [rectorphp/rector#7709]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | [0.15.4](https://github.com/rectorphp/rector/releases/tag/0.15.4) / https://github.com/rectorphp/rector/commit/1dcdf54ebf502d9f7cf9b5f89df613da1774d050 |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/5ce30a97-6291-40ce-b68e-fb01d7b6b10e

```php
<?php

use Doctrine\ORM\Mapping as ORM;

class Pizza
{
    /**
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;
}
```

### Responsible rules

* `TypedPropertyFromColumnTypeRector`

## Expected Behavior
When running the `TypedPropertyFromColumnTypeRector` to set PHP types for Doctrine columns, Rector appears to set the property as nullable when no `nullable` attribute is defined in the Doctrine column. By default, if `nullable` is omitted, it should be considered `false` -- I would expect Rector then to define the property as a non-nullable string in my example.

Rector returns:
```php
private ?string $name = null;
```

I would expect:
```php
private string $name;
```

https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/annotations-reference.html#column

When explicitly setting `nullable` to `false`, Rector will correctly mark the property as a string. Equally when `nullable` is explicitly set to `true`, Rector will mark the property as a nullable string with a `null` default value.

I'm not quite sure but I don't think the [NullabilityColumnPropertyTypeResolver](https://github.com/rectorphp/rector-doctrine/blob/0.14.1/src/NodeManipulator/NullabilityColumnPropertyTypeResolver.php) class is catering for nullable=false being the default when no `nullable` attribute is present.

**Comment by samsonasik** [comment]
Duplicate with closed issues https://github.com/rectorphp/rector/issues?q=is%3Aissue+TypedPropertyFromColumnTypeRector+is%3Aclosed, except for #[ORM\Id] which can be auto, the `nullable=false` need for that.

The rule is not tied to specific doctrine version, so nullable=false default is subject to change, make it typed without nullable can cause BC break.

**Comment by glennmcewan** [comment]
@samsonasik my mistake, I searched for that bug in the rectorphp/rector-doctrine repo rather than this one! Thanks for getting back to me so quickly.

It seems to conflict a little with the paradigm of this Rector rule, which removes redundant annotation attributes, such as `nullable=false`:
https://github.com/rectorphp/rector-doctrine/blob/0.14.1/src/Rector/Property/RemoveRedundantDefaultPropertyAnnotationValuesRector.php#L39

Would it make sense to allow the TypedPropertyFromColumTypeRector to be configurable with a default value for nullable if it is omitted? I can raise a PR at some point if that's worthwhile, otherwise I'll just patch Rector locally for my use case.

**Comment by TomasVotruba** [comment]
Hi, this is due to fact that property is not set in a the constructor. So it is nullable and setter to `string` type would break.

That's often disliked feature of Doctrine ORM :) it must be handled in the architecture first.
