### ISSUE TITLE
Rector times out but doesn't stop running

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7711]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.4 (but issue has been present with earlier versions too)             |

In my rector config I have set a time limit of 600 like: (my project I am checking only has 30 files)
>$rectorConfig->parallel( 600, 16, 2 );

```
php -d max_execution_time=660 vendor/bin/rector process --no-progress-bar --no-diffs --config my-config my-project/ > output.log 2> error.log
```

In output.log I get:

> [ERROR] Could not process                                                      
         "/.../vendor/rector/rector/vendor/symplify/easy-parallel/src/V
         alueObject/ParallelProcess.php" file, due to:                          
         "Child process timed out after 600 seconds". On line: 103              
>[ERROR] Could not process some files, due to:                                  
         "Reached system errors count limit of 50, exiting...".         

However rector doesn't exit even then. When I check with `ps aux` I see the parent rector process + 1 child process it spawned and they stay there for eternity (= until I force kill them manually)

I remember some time ago (I guess v0.14 and before) I didn't have this issue, as rector just stopped as it should

**Comment by TomasVotruba** [comment]
Hi we'll need a reproducible repository, to be able to fix it.
It's possibly some system setup or rule + file combination.
