### ISSUE TITLE
Simplify debugging timeouts by listing how often a rule was applied

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7712]
# Feature Request

Sometimes rector times out bc it got itself into a loop, due to a bug somewhere.
It would be incredibly helpful if:
a) same rector rule is applied a specific number of times in a file
b) timeout is reached

rector would print how often each check/rule was applied, so it's easy to identify which rules are working "against" each other and creating an infinite loop.
Atm I have to remove rules and test for hours to find which rules create a timeout bc they mess each other up.

**Comment by TomasVotruba** [comment]
Hi, to be honest, I'm not sure how this would be technically possible. 

If you find a way,  send us a PR please. This could be enabled on a `--debug` or `-vvv` option :+1:

**Comment by yguedidi** [comment]
@kkmuffme you may want to have a look at https://github.com/rectorphp/rector-src/pull/3785
