### ISSUE TITLE
RectorConfig::importNames produces invalid code

### ISSUE THREAD

**Issue by r-simlinger** [rectorphp/rector#7714]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.4          |

For files where the PHP open tag is not in the first line the \Rector\Config\RectorConfig::importNames() config will produce invalid code:

## Minimal PHP Code Causing Issue
```
#!/usr/local/bin/php -q

<?php

require(__DIR__ . '/../../vendor/autoload.php');

$dotenv = \Dotenv\Dotenv::createUnsafeMutable(__DIR__ . '/../../');
$dotenv->load();
// ... more code ...

```

## Current Behaviour
```
    ---------- begin diff ----------
@@ @@
+use Dotenv\Dotenv;
 #!/usr/local/bin/php -q

 <?php
@@ @@

 require(__DIR__ . '/../../vendor/autoload.php');

-$dotenv = \Dotenv\Dotenv::createUnsafeMutable(__DIR__ . '/../../');
+$dotenv = Dotenv::createUnsafeMutable(__DIR__ . '/../../');
 $dotenv->load();
 // ... more code ...
    ----------- end diff -----------
```

## Expected Behaviour

```
#!/usr/local/bin/php -q

<?php

use Dotenv\Dotenv;

require(__DIR__ . '/../../vendor/autoload.php');

$dotenv = Dotenv::createUnsafeMutable(__DIR__ . '/../../');
$dotenv->load();
// ... more code ...

```

**Comment by samsonasik** [comment]
For shebang, the following line:

```
#!/usr/local/bin/php -q
```

marked as HTML, so I guess you can just skip it by remove `.php` suffix so it will not be touched by rector, make it 2 files instead:

```
bin/executable.php
bin/executable
```

the `bin/executable.php`, you can fill with php code only:

```php
<?php

require(__DIR__ . '/../../vendor/autoload.php');

$dotenv = \Dotenv\Dotenv::createUnsafeMutable(__DIR__ . '/../../');
$dotenv->load();
```

Then, for `bin/executable`, you can fill with include it:

```
#!/usr/local/bin/php -q

<?php

require_once __DIR__ . '/executable.php';
```
