### ISSUE TITLE
use full path class instead import use

### ISSUE THREAD

**Issue by SocolaDaiCa** [rectorphp/rector#7716]
# Question
![image](https://user-images.githubusercontent.com/18243451/212520031-2ce5d5ad-65c8-4e4c-9c02-95ec98152e27.png)

rector alway replace fullpath class to import use
But I want keep full path class
How to do that?

Thanks

**Comment by samsonasik** [comment]
You can disable import name by pass `false, false` to `importNames()` config:

```php
$rectorConfig->importNames(false, false);
```
