### ISSUE TITLE
Does any option exist for avoiding code reformat?

### ISSUE THREAD

**Issue by Yoskaldyr** [rectorphp/rector#7720]
# Question
I just want to upgrade for using in the latest php versions some legacy code with non standard code formatting using rector.
But because rector reformats all code it's almost impossible to find what exactly was changed.
Is it possible to skip code formatting in rector?

**Comment by samsonasik** [comment]
That's know drawbacks https://github.com/rectorphp/rector#known-drawbacks , you need to use coding-standard tool for that.
