### ISSUE TITLE
Incorrect behavior of NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7721]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.15.7      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/27e9eb3f-2954-4ec2-8609-b41ea236b4f4

```php
<?php

use function Symfony\Component\String\u;

final class DemoFile
{
    public function run()
    {
        $value = u($value)
            ->replace('Ä', 'Ae')
            ->replace('Ü', 'Ue')
            ->replace('Ö', 'Oe')
            ->replace('ä', 'ae')
            ->replace('ü', 'ue')
            ->replace('ö', 'oe')
            ->replace('ß', 'ss')
            ->ascii()
            ->trim()
            ->toString();

        if (str_contains($value, '.')) {
            // do something
        }
    }
}
```

Please note, that my code also got `symfony/string` installed as well as my rectorConfig knows about my phpstan configuration.
While the Rector is true in above example, it basically should look like this (seen by rector): https://getrector.org/demo/590d4a66-c383-465a-b3ad-9900874f6b91

I can't provide a live-example online, since there is no possibility to add a phpstan configuration as well as other dependencies. So I just simulated it in second example by mocking a UnicodeString (like provided by `symfony/string`).

Main reason why I'm reporting this, is because of phpstan is reporting an "do not cast something, that's already string"-error (which I'm content with).

### Responsible rules

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

Do not string-cast $value, since it's already a string.

**Comment by samsonasik** [comment]
That's may be due to overlapped autoload, you can add file at composer autoload files for that, ref

https://github.com/samsonasik/ErrorHeroModule/blob/master/composer.json#L110

See the documentation for this use case https://getrector.com/documentation/static-reflection-and-autoload

**Comment by mvhirsch** [comment]
Thank you for your answer, @samsonasik.

Sadly I don't understand what I should do to fix the problem. I've read through the documentation and checked your example, but I do not override any autoload in composer. I don't even have any custom bootstrapping (beside composer's autoload), so there shouldn't be any problem with mismatch at all.

My composer.json won't override any autoload (it's just a simple symfony project):

```json
   "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
```

I even tried `composer dump-autoload -o` as suggested in the docs, but this didn't solve the problem. Heck, I'm even more confused, since the docs tell rector won't use composer's autoload... Probably that's just meant for PHPStan, but again: PHPStan is confident about the type already.

Any ideas, what's going on?

**Comment by mvhirsch** [comment]
I've added

```diff
git diff composer.json
diff --git a/composer.json b/composer.json
index 5d28a76a..49f9fa25 100644
--- a/composer.json
+++ b/composer.json
@@ -159,7 +159,10 @@
     "autoload-dev": {
         "psr-4": {
             "App\\Tests\\": "tests/"
-        }
+        },
+        "files": [
+            "vendor/symfony/string/Resources/functions.php"
+        ]
     },
     "config": {
         "allow-plugins": {
```

It now skips it. Thank you @samsonasik !

One more question: why is PHPStan able to correctly map the same project, while rector does not? Isn't the symbol lookup the very same technique?

**Comment by samsonasik** [comment]
My knowledge is limited for it as is mostly internal PHPStan resolver, you may need to lookup how PHPStan load the classes

https://github.com/phpstan/phpstan-src
