### ISSUE TITLE
Incorrect behavior of ChangeReadOnlyVariableWithDefaultValueToConstantRector

### ISSUE THREAD

**Issue by la-magra** [rectorphp/rector#7722]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ea823ec-ef3d-448e-b890-eefc87a0e286

```php
<?php declare(strict_types=1);

final class ThingClient {
    private $client;

    public function __construct(int $timeout = 5) {
        $wsdl = 'https://pathtowsdl?wsdl';
        $opts = [
            'connection_timeout' => $timeout,
        ];
        try {
            $this->client = new \SOAPClient($wsdl, $opts);
        } catch (\Exception $e) {
        }
    }

    private function normalize(string $thing): string {
        $opts = [
            'A' => 'Z',
            'B' => 'Y',
        ];

        return $opts[$thing];
    }
}
```

### Responsible rules

* `ChangeReadOnlyVariableWithDefaultValueToConstantRector`

## Expected Behavior

`$opts` in the constructor cannot be changed to `self::OPTS`.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. I'm on the fix :+1:

**Comment by la-magra** [comment]
Wonderful, thank you.
