### ISSUE TITLE
Incorrect behavior of RenameClassRector

### ISSUE THREAD

**Issue by Naugrimm** [rectorphp/rector#7725]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/09b4c824-aac1-44fd-a4ce-b4409bb38c6f

```php
<?php

namespace App;

class User {}
```

### Responsible rules

* `RenameClassRector`

## Expected Behavior

The namespace should not be changed by `RenameClassRector`.

The error occurred as I followed the instructions in [this blog post](https://getrector.com/blog/2020/12/07/laravel-facades-to-constructor-injection-replace-facade-aliases-with-full-classes-in-2-hours) to use the full class names instead of the aliases.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.
