### ISSUE TITLE
documentation bug with OptionalParametersAfterRequiredRector

### ISSUE THREAD

**Issue by bosepchuk** [rectorphp/rector#7733]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.15.10 (invoke `vendor/bin/rector --version`)             |

Description of the rector is: "Move required parameters after optional ones"

## Expected Behaviour

Documentation probably should read: "Move optional parameters after required ones"

**Comment by TomasVotruba** [comment]
Thanks :+1:  Could you send PR to fix it?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:
