### ISSUE TITLE
Incorrect behavior of `ReadOnlyClassRector`

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7734]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.15.7+   |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

Tested with 0.15.7, 0.15.10 (different projects) and online.

See https://getrector.com/demo/bfd6ec7c-7c61-46b0-8915-967c4cc0b646

```php
<?php

#[Route('/statistiken/bundesland', name: AdminRoutes::STATISTICS_IMMOBILIE_BUNDESLAND)]
final class BundeslandStatisticsController
{
    public function __construct(
        private readonly Responder $responder,
        private readonly RepositoryInterface $repository,
    ) {
    }
}
```

As you can see it inlines my annotation and class-spec.

### Responsible rules

* `ReadOnlyClassRector`

## Expected Behavior

Rector should add `readonly` to this class, but respect the newline before `final class`.

**Comment by TomasVotruba** [comment]
Just looking into it. This is a bug in php-parser in formatPreservingPrinter. The input here is valid and class node itself is printed correctly, if the orig node is made null.

I've added a workaround to reprint the whole Class_ from scratch, but php-parser fix is needed.
