### ISSUE TITLE
Is delegation of Rector rules possible?

### ISSUE THREAD

**Issue by zeriyoshi** [rectorphp/rector#7740]
# Question

It is always convenient for us. Thank you.

Now I am thinking of applying Rector to my huge codebase. What I am trying to apply is one of the rules bundled with Rector. However, because of the size and complexity of the codebase, I am only going to apply the rules when the complex requirements are met.

So I decided to create a custom rule and apply the existing rule only when I am sure that the code in question meets the requirements. Since all Rector rules are declared final class, they cannot be inherited. However, I thought it was possible to delegate them because of constructor injection.

When I actually performed the delegate using the `new`, I realized that it was not possible. The bundled rules do not work properly because the properties set by the autowire() method are not set.

I have read through the codebase and could not find any examples of calling a Rector rule from a Rector rule. Is this possible? Or is it intentionally restricted so that such usage is not possible?

**Comment by samsonasik** [comment]
If you want to autowire your own service, you can configure in your rector.php or your own included config, something like this

https://github.com/rectorphp/rector-phpunit/blob/963c24df5d7c459b4fb9b82f2e7c59644f66b306/config/config.php#L7-L14

**Comment by zeriyoshi** [comment]
@samsonasik 
Thanks, it worked fine by doing the following:

```php
return static function (RectorConfig $rectorConfig): void {
    $services = $rectorConfig->services();
    $services->load('RULE_NAMESPACE', 'RULE_DIRECTORY');
    $services->set(RequireDelegateBundledRuleRector::class);
};
```

```php
final class RequireDelegateBundledRuleRector extends AbstractRector
{
    private RectorInterface $rule;
    public function __construct(BundledRuleRector $delegateRule) {
        $this->rule = $delegateRule;
    }
    public function refactor(Node $node): ?Node
    {
        /* brah brah brah.... */
        return $this->rule($node);
    }
}
```

However, this seems very difficult to use. Especially having to specify the path to the bundled classes is difficult considering that the rules are distributed as a Composer package.

Personally, I feel that rule delegation could be made easier. (For example, by providing a service like RuleDelegator)

Is this an intentional design? Or is it simply not implemented?

**Comment by samsonasik** [comment]
You can copy paste existing rule, and override as your needs, that's you have less worry about bc break.

You can read here why final class is needed https://ocramius.github.io/blog/when-to-declare-classes-final/

**Comment by zeriyoshi** [comment]
Yes, I agree with making it final.

> that's you have less worry about bc break.

While I agree, I have some doubts. The rules bundled with Rector are certainly maintained and kept up to date with the latest PHP changes.

Copy-and-paste derived Rector rules may not be able to keep up with these changes properly. Of course, you could then import the diffs, but this is obviously inefficient.

If there is no reason why we should not be able to delegate Rector rules, I would like to work on making it possible.

**Comment by TomasVotruba** [comment]
You can add the if condition to the PHP config itself and register rule only if conditions are met :+1:

**Comment by zeriyoshi** [comment]
@TomasVotruba 
If one wanted to determine the applicability of the bundled rules based on the results of static analysis with the Rector rules, it would be difficult to do so.

If I were to submit a PR for a rule delegation implementation, is there any chance it would be accepted?

**Comment by TomasVotruba** [comment]
That can be done in the config now and it would make architecture much harder to maintain. Sorry, but I would not take it in, as there is a way to do it already.

**Comment by zeriyoshi** [comment]
@TomasVotruba 
I understand. Thanks!
