### ISSUE TITLE
Incorrect behavior of LongArrayToShortArrayRector

### ISSUE THREAD

**Issue by TeLiXj** [rectorphp/rector#7741]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/fe2978d5-c66a-4b39-a62b-ec005b71544d

```php
<?php

final class DemoFile
{
    public function run()
    {
	$ok = array(
            'ok' => 'ok!',
            'KO' => 'KO!'
        );
    }
}
```

### Responsible rules

* `LongArrayToShortArrayRector`

## Expected Behavior

The array was changed to a single line 
```php
$ok = ['ok' => 'ok!', "KO" => "KO!"];
```
instead of keeping the structure
```php
$ok = [
        'ok' => 'ok!',
        'KO' => 'KO!'
];
```

**Comment by samsonasik** [comment]
That's expected as the long array require re-print to get short array. You need coding standard tool for that https://github.com/rectorphp/rector#how-to-apply-coding-standards
