### ISSUE TITLE
Is PhpSpreadsheet Documentation Still Accurate?

### ISSUE THREAD

**Issue by oleibman** [rectorphp/rector#7742]
You upgraded the PhpSpreadsheet documentation for how to use Rector on May 31 last year (https://github.com/PHPOffice/PhpSpreadsheet/pull/2861). In December, a user said the documentation is outdated (https://github.com/PHPOffice/PhpSpreadsheet/issues/1699#issuecomment-1362020159). Is it in need of a change, and, if so, might you be able to submit another PR for it?

**Comment by TomasVotruba** [comment]
Yes, the new separate package is needed now.
