### ISSUE TITLE
Incorrect behavior of `RenameClassNonPhpRector`

### ISSUE THREAD

**Issue by grandmaster44** [rectorphp/rector#7743]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.0+ |

Rector is trying to rename class in yaml file to an interface:

![obraz](https://user-images.githubusercontent.com/23462753/215055710-fb0b4011-f82a-4ed5-a6f6-434d6c616339.png)

## Minimal PHP Code Causing Issue

( I'm changing yaml file, so I can't prepare a demo )

`#services.yml`
```yaml
services:
    custom_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [ custom_logger ]
```

`#rector.php`
```php
<?php

use Rector\Config\RectorConfig;
use Rector\Core\ValueObject\PhpVersion;

return static function (RectorConfig $rectorConfig): void {
  $rectorConfig->ruleWithConfiguration(RenameClassRector::class, [
       'Symfony\\Bridge\\Monolog\\Logger' => 'Psr\\Log\\LoggerInterface', // taken from rector/rector-symfony/config/sets/symfony/symfony30.php
  ]);
};
```

`command`
`php bin/rector process services.yml`

## Expected Behaviour

Rector should skip rename class to an interface in yaml.

**Comment by samsonasik** [comment]
@grandmaster44 the solution seems add `RenameClassNonPhpRector::class` to `ClassRenamingPostRector::getRectorDependencies()`

https://github.com/rectorphp/rector-src/blob/9e321a11ac21440a33abef87add34945a1490b8f/packages/PostRector/Rector/ClassRenamingPostRector.php#L35

```diff
    public function getRectorDependencies(): array
    {
-        return [RenameClassRector::class];
+        return [RenameClassRector::class, RenameClassNonPhpRector::class];
    }
```

as it share the usage of rename class data collector:

```php
$this->renamedClassesDataCollector->getOldToNewClasses()
```

Then, after that, you can add it to `skip()` config:

```php
 $rectorConfig->skip(RenameClassNonPhpRector::class, [
         __DIR__ . '/config/services.yml'
  ]);
```

That's make `RenameClassNonPhpRector` skippable. 

Could you try create PR for it? Thank you.

**Comment by grandmaster44** [comment]
@samsonasik done: https://github.com/rectorphp/rector-src/pull/3360

**Comment by samsonasik** [comment]
Ok, failing fixture is needed then

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:
