### ISSUE TITLE
Undefined type 'RectorSymfonySet\SymfonySetList'>

### ISSUE THREAD

**Issue by ALHAN710** [rectorphp/rector#7745]
# Question
Hi, 
I migrated my symfony 5.1 project to 5.4, I want to use now rector to update the deprecated code parts. I proceeded to install rector as follows:
- composer require rector/rector --dev
- ./vendor/bin/rector init

When modifying the rector.php file generated by the init command to the one in the rector-symfony documentation below, I have the error <<Undefined type 'RectorSymfonySet\SymfonySetList'>> on my ide

`<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Symfony\Set\SymfonySetList;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/config',
        __DIR__ . '/public',
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);

    $rectorConfig->symfonyContainerXml(__DIR__ . '/var/cache/dev/App_KernelDevDebugContainer.xml');

    $rectorConfig->sets([
        SymfonySetList::SYMFONY_62,
        SymfonySetList::SYMFONY_CODE_QUALITY,
        SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,
    ]);

    // register a single rule
    // $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    // define sets of rules
    //    $rectorConfig->sets([
    //        LevelSetList::UP_TO_PHP_81
    //    ]);
};
`
So I can't access SYMFONY_54 and other constants of the SymfonySetList class
Someone can help me to understand what is wrong and fix it please ?

**My Workspace Environment :** 
OS: Windows 11
composer: v2.5.1
php: v8.1.10
Ide: vscode v1.71.2

**Comment by samsonasik** [comment]
Error notice in IDE is fine, as the `vendor/rector/rector/vendor/rector/rector-symfony` is prefixed so it vscode may can't autoload it.

Anyway, there is no `RectorSymfonySet` namespace, you need to pull SetList from `Rector\Symfony\Set` instead.

**Comment by samsonasik** [comment]
I am closing it as it is due to your IDE constant resolving to prefixed vendor, which unrelated with functionality.

**Comment by playmono** [comment]
rector/rector is not coming with rector/rector-symfony anymore, therefore your IDE cannot find anything. You should also install this package.

**Comment by samsonasik** [comment]
@playmono that's depends on what IDE you're using, the `SymfonySetList` is already there when you install:

```
composer require --dev rector/rector
```

![Screen Shot 2023-08-10 at 17 51 13](https://github.com/rectorphp/rector/assets/459648/056228dd-021e-44ae-8e27-6a8ab7183a9c)

IDE is unrelated with functionality, you may need to setup your IDE to cover that if you don't use PhpStorm.

**Comment by playmono** [comment]
You are right.

Thank you!
