### ISSUE TITLE
Can we revert file changes if no rules applied?

### ISSUE THREAD

**Issue by realtebo** [rectorphp/rector#7748]
# Question

I know that, due to AST, there is a small subset of files where lines are trimmed. 

This is not a problem if project is small and not if there are other changes in the file.

But I'm facing a huge >20k file project. Running a simple custom rule to do a name change to fix a typo,  I got over 2400 files changed, but only 24 with the fix applied.

So, I am asking if there is something like a 'postFileProcessing' hook where to count file changes, or verify if any rules applied, and then ask rector to simply NOT save the file. 

This avoid the problem of "useless" trimming of files. 

I also known is an already spoken question, but I'm posing it in a different way, to eventually ipotize a different solution.

Also, an hook fired after each file processed could be very usefull for A LOT of automations

**Comment by realtebo** [comment]
I add a context to understand why I think it could and should be possible.

Run this demo 

https://getrector.com/demo/7654277d-ee5d-45ae-8867-9ca746ea12a4

And this demo

https://getrector.com/demo/483fe7d3-671f-49fd-9cf7-29190694bfad

The first one has NO rules applied, the second has one rule applied.

Your demo code is able to recnognize the first case from second case because it's not proposing to create a test and/or an issue.

So I can think it's possible in some way to distinguish files changed by rules from changed by AST only or similar

**Comment by mvhirsch** [comment]
Not exactly what you're asking for, but using `git` you can:

```
git diff --ignore-blank-lines --ignore-all-space
```

You could just apply patches to stage without whitespace/newline changes.

**Comment by realtebo** [comment]
this seems working ... but I got a list of 2300 files to commit.  So I must anyway find one-by-one to add. 
I will try to give the diff list (with some pretty print, only file names) piped to git checkout . to auto-rollback white space only files.

But I am sure that this behaviour, while due to technical reason, is a big disvantage for everyone working with a very old and big and legacy and shitty code base. 

I am not able to find in the source code where is the loop of single file parsed, so I can evaluate a patch to check the diff and eventually rollback immediately

I am pretty sure the code can check if NO RULE is applied and so AVOID to resave the file

**Comment by mvhirsch** [comment]
> But I am sure that this behaviour, while due to technical reason, is a big disvantage for everyone working with a very old and big and legacy and shitty code base.

Totally! 

----

To get you helped now, this works on your examples given above:

```bash
git diff --ignore-blank-lines --ignore-all-space -U0 -w --no-color | git apply --cached --unidiff-zero -
```

On an example [like yours here](https://getrector.com/demo/483fe7d3-671f-49fd-9cf7-29190694bfad) will only stage the removal of the code lines, ignoring whitespace changes. 

```diff
diff --git a/test.php b/test.php
index 8ec062df..6e86e12e 100644
--- a/test.php
+++ b/test.php
@@ -12,3 +9,0 @@ final class DemoFile
-
-        // we never get here
-        return 10;

```


Afterwards a 

```
git checkout .
```

Will remove the changes made on whitespace/newline changes.

**Comment by realtebo** [comment]
I got only 

    error: cannot apply binary patch to 'admin/mailer/language/phpmailer.lang-ja.php' without full index line

**Comment by TomasVotruba** [comment]
Changed files should not be reprinted. Could you share a reproducible git repository with single file that is causing this?

**Comment by realtebo** [comment]
it's not important, for me, to solve git issues, but I really would like to know if there is a way to intercept end of file parsing, detect if no role applied, and so avoid to save a uselessy modified file.

**Comment by samsonasik** [comment]
The change may happen by `PostRector` (eg: auto import) which currently not detected directly in `BetterStandardPrinter` immediatelly, so that may overlapped, checking `$currentFile->getFileDiff() instanceof FileDiff` can't detect that as that change is too late.

For FileWithoutNamespace, could you try remove `ltrim()` in BetterstandardPrinter::pFileWithoutNamespace()` method and verify if that works removing space before open tag?

```diff
    public function pFileWithoutNamespace(FileWithoutNamespace $fileWithoutNamespace): string
    {
+       return $this->pStmts($fileWithoutNamespace->stmts, false);
-        $content = $this->pStmts($fileWithoutNamespace->stmts, false);

-      return ltrim($content);
    }
```

**Comment by realtebo** [comment]
> Un-changed files should not be reprinted. Could you share a reproducible git repository with single file that is causing this?

Files are being 'trimmed' for extra white space by AST (I think, by AST). 
So even if no rules applied, file are being changed.

**I'll try to post a minimal repository.** in a day or two, I promise

But in this specific case, a repo with over 2000 files, I got a few hundreds file changed only for whitespaces.. and it's annoying.

**Comment by realtebo** [comment]
> The change may happen by `PostRector` (eg: auto import) which currently not detected directly in `BetterStandardPrinter` immediatelly, so that may overlapped, checking `$currentFile->getFileDiff() instanceof FileDiff` can't detect that as that change is too late.
> 
> For FileWithoutNamespace, could you try remove `ltrim()` in BetterstandardPrinter::pFileWithoutNamespace()` method and verify if that works removing space before open tag?
> 
> ```diff
>     public function pFileWithoutNamespace(FileWithoutNamespace $fileWithoutNamespace): string
>     {
> +       return $this->pStmts($fileWithoutNamespace->stmts, false);
> -        $content = $this->pStmts($fileWithoutNamespace->stmts, false);
> 
> -      return ltrim($content);
>     }
> ```

I'll try it soon

**Comment by Mirko-Tebaldi** [comment]
> `BetterStandardPrinter`

Nope.
Removing this ltrim doesn't change the behaviour.

**Comment by samsonasik** [comment]
We need simple reproducible repository for it, better with github action running so it fixable, try narrow rules half by half

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by samsonasik** [comment]
Re-open, and it only work on `--dry-run`

**Comment by samsonasik** [comment]
Re-open as it caused a bug when PostRector may not be printed again. I will revert the change.

**Comment by samsonasik** [comment]
I found the `ltrim()` exists in nikic/php-parser's `PrettyPrinterAbstract` https://github.com/nikic/PHP-Parser/blob/570e980a201d8ed0236b0a62ddf2c9cbb2034039/lib/PhpParser/PrettyPrinterAbstract.php#L501

so it need compare before and after ltrim-ed with `$file->getOriginalFileContent()`.

**Comment by Mirko-Tebaldi** [comment]
how can I try this modification until next release?

**Comment by samsonasik** [comment]
Rector 0.15.19 released for it https://github.com/rectorphp/rector/releases/tag/0.15.19

**Comment by Mirko-Tebaldi** [comment]
Thanks, but I have no good news.

File are changed to trim useless spaces in the lines even if no rules applied

You should simply try to create a PHP file with a lot of lines with ONLY white spaces.

If no rule applied, the file is still changed because all spaces-only lines are trimmed. 

What I would like is to NOT SAVE the file at all if no rule are applied. 

Sorry for this bad news. I am really gracefull for your help and for this tool.

**Comment by samsonasik** [comment]
we need failing test case PR for that then :)

**Comment by samsonasik** [comment]
You can start with demo page https://getrector.com/demo , you can read the doc https://getrector.com/documentation/reporting-issue-with-rector
