### ISSUE TITLE
Incorrect behavior of SwapFuncCallArgumentsRector

### ISSUE THREAD

**Issue by realtebo** [rectorphp/rector#7749]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | Rector 0.14.8     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/27901df6-0014-4db7-b7f1-5bea19dd48c9

```php
<?php
$result_a=mysql_query($query_a, $link_b);
$result_b=mysql_query($query_b, $link_b) or die("impossibile eseguire query: ".$query);
```

### Responsible rules

* `SwapFuncCallArgumentsRector`

## Expected Behavior

I was expecting a simple swap 

```
<?php
$result_a=mysql_query($link_b, $query_a);
$result_b=mysql_query($link_b, $query_b) or die("impossibile eseguire query: ".$query);
```

**Comment by realtebo** [comment]
I actively debugged and found the cause in another rule

    $rectorConfig->rule(MysqlQueryMysqlErrorWithLinkRector::class);

See this demo: https://getrector.com/demo/42c8bf7b-d7e1-45ed-9d09-50445e1effc6

**Comment by realtebo** [comment]
I verified that this mod will fix that wrong behaviours

Here: vendor/rector/rector/config/set/mysql-to-mysqli.php 

change row 

    $rectorConfig->ruleWithConfiguration(RenameFunctionRector::class, ['mysql_connect' => 'mysqli_connect', 'mysql_data_seek' => 'mysqli_data_seek', 'mysql_fetch_array' => 'mysqli_fetch_array', 'mysql_fetch_assoc' => 'mysqli_fetch_assoc', 'mysql_fetch_lengths' => 'mysqli_fetch_lengths', 'mysql_fetch_object' => 'mysqli_fetch_object', 'mysql_fetch_row' => 'mysqli_fetch_row', 'mysql_field_seek' => 'mysqli_field_seek', 'mysql_free_result' => 'mysqli_free_result', 'mysql_get_client_info' => 'mysqli_get_client_info', 'mysql_num_fields' => 'mysqli_num_fields', 'mysql_numfields' => 'mysqli_num_fields', 'mysql_num_rows' => 'mysqli_num_rows', 'mysql_numrows' => 'mysqli_num_rows']);

to (note I added `'mysql_query' => 'mysqli_query',`);

    $rectorConfig->ruleWithConfiguration(RenameFunctionRector::class, ['mysql_query' => 'mysqli_query', 'mysql_connect' => 'mysqli_connect', 'mysql_data_seek' => 'mysqli_data_seek', 'mysql_fetch_array' => 'mysqli_fetch_array', 'mysql_fetch_assoc' => 'mysqli_fetch_assoc', 'mysql_fetch_lengths' => 'mysqli_fetch_lengths', 'mysql_fetch_object' => 'mysqli_fetch_object', 'mysql_fetch_row' => 'mysqli_fetch_row', 'mysql_field_seek' => 'mysqli_field_seek', 'mysql_free_result' => 'mysqli_free_result', 'mysql_get_client_info' => 'mysqli_get_client_info', 'mysql_num_fields' => 'mysqli_num_fields', 'mysql_numfields' => 'mysqli_num_fields', 'mysql_num_rows' => 'mysqli_num_rows', 'mysql_numrows' => 'mysqli_num_rows']);

**Comment by samsonasik** [comment]
`SetList::MYSQL_TO_MYSQLI` is now deprecated on PR:

- https://github.com/rectorphp/rector-src/pull/4448
