### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector, NestedAnnotationToAttributeRector

### ISSUE THREAD

**Issue by AlexeyKosov** [rectorphp/rector#7750]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/8103081f-6829-4a6e-b599-f5c7884f3b92

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use SimpleThings\EntityAudit\Mapping\Annotation as Audit;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="products", indexes={
 *     @ORM\Index(columns={"updated_at"})
 * }))
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @Serializer\ExclusionPolicy("ALL")
 * @Audit\Auditable()
 */
class TestEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id()
     * @Serializer\SerializedName("id")
     * @Serializer\Type("integer")
     * @Assert\NotBlank()
     */
    protected $id;
}
```

### Responsible rules

* `AnnotationToAttributeRector`

* `NestedAnnotationToAttributeRector`

## Expected Behavior

It should not have removed these annotations:
```
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @Serializer\ExclusionPolicy("ALL")
 * @Audit\Auditable()
```

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by AlexeyKosov** [comment]
@TomasVotruba , Done! Hope it helps

**Comment by AlexeyKosov** [comment]
It turned out to be a typo in the `@ORM\Table` annotation - a redundant closing brace at the end.

```
 * @ORM\Table(name="products", indexes={
 *     @ORM\Index(columns={"updated_at"})
 * }) -->)<--
```

The doctrine annotations parser did not complain about it so it slipped through the cracks.
After fixing the docblock, it started to work properly.
Not sure if Rector's parser should support such cases. If no, feel free to turn down the [PR](https://github.com/rectorphp/rector-src/pull/3467)

**Comment by TomasVotruba** [comment]
I see, I'm sorry to hear that it was such a detail.

In Rector we can only work with valid PHP and valid input structures. This should be handled only in Doctrine itself, as a bug, or by a php-cs-fixer rule, that can work with more detailed tokens.
