### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by cwang22** [rectorphp/rector#7751]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/50e42109-9747-458b-bbad-cf105d3dc1d3

```php
<?php

class Test
{
    public $a;

    public function __construct(string $a = null)
    {
        $this->a = $a;
    }
}
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

 either skip it or make the string type nullable so it not causing an error

**Comment by samsonasik** [comment]
The bug seems only happen when `INLINE_PUBLIC` config applied on public property, when on private property with disable inline public (default), it applied nullable correctly, ref https://getrector.com/demo/cde346b3-d989-40ae-ae7e-0cc1a90faaab

**Comment by samsonasik** [comment]
On public property, it seems goes MixedType, while on private property, it got UnionType.

```
^ PHPStan\Type\UnionType^ {#14004
  -sortedTypes: false
  -cachedDescriptions: []
  -types: array:2 [
    0 => PHPStan\Type\StringType^ {#13996}
    1 => PHPStan\Type\NullType^ {#14006}
  ]
  -normalized: true
}
```
