### ISSUE TITLE
composer fix-cs and composer docs no longer working on markdown on rector-src

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7752]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

## Minimal PHP Code Causing Issue

On rector-src, running both command got `1` status which make CI failure in case run:

```bash
composer fix-cs
composer docs
```

It is due to "check-markdown" now deprecated.

## Expected Behaviour

It should work or there will need a replacement for it.

**Comment by TomasVotruba** [comment]
The command should be removed, the php-printer should work out of the box now.

**Comment by samsonasik** [comment]
any php-printer command that can be used? I tried using:

```
vendor/bin/ecs check build/target-repository/docs/rector_rules_overview.md --fix
```

And it seems hang

**Comment by TomasVotruba** [comment]
This should be removed completelly
