### ISSUE TITLE
conflict between NewlineAfterStatementRector and PhpCsFixer\Fixer\Whitespace

### ISSUE THREAD

**Issue by scollovati** [rectorphp/rector#7754]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.10            |
|symplify/easy-coding-standard|11.2.7|

## Minimal PHP Code Causing Issue
symplify/easy-coding-standard configuration: 

```php
    $ecsConfig->sets([
        // run and fix, one by one
        SetList::SPACES,
        SetList::ARRAY,
        SetList::DOCBLOCK,
        SetList::NAMESPACES,
        SetList::COMMENTS,
        SetList::PSR_12,
    ]);
```

Rector configuration
```php
    $rectorConfig->sets([
        // run and fix, one by one
        SetList::PHP_74,
        SetList::DEAD_CODE,
        SetList::CODE_QUALITY,
        SetList::CODING_STYLE,
        SetList::EARLY_RETURN,
        SetList::TYPE_DECLARATION,
    ]);
```

They have rules that clash about how to manage some new lines:
- `NewlineAfterStatementRector`
- `PhpCsFixer\Fixer\Whitespace\LineEndingFixer` and `PhpCsFixer\Fixer\Whitespace\NoWhitespaceInBlankLineFixer`

This create an endless loop of fixes between the two.

**Comment by TomasVotruba** [comment]
Thanks for reporting.

What exactly happens there? Seem 2 tools have different configuration.

**Comment by scollovati** [comment]
The issue it not about line endings, but about having or not a new line after a statement. Check this our with this dummy class:
```php
<?php

namespace App;

class DemoClass
{
    public function __construct()
    {
        echo "hello";
    }
}
```

Rector with the above configs wants a new line after the `echo` statement, instead ECS is fine with the above format.

**Comment by samsonasik** [comment]
`Echo_` is not part of statement that will have new line on `NewlineAfterStatementRector`, see 

https://github.com/rectorphp/rector-src/blob/1fd38073d08dff31e7b6f5fecdfc0df8f6e897b0/rules/CodingStyle/Rector/Stmt/NewlineAfterStatementRector.php#L43-L59

We need simple reproducible repository for it, better with github action running so it fixable, try narrow rules half by half

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by scollovati** [comment]
Hi @samsonasik sorry for the confusion. After a deeper testing I think that @TomasVotruba was right, there may be an issue in end of lines. Actually, by testing it better I found an issue in ECS (different rule executed between call with `--fix` and not).
