### ISSUE TITLE
What is the meaning of PARALLEL_MAX_NUMBER_OF_PROCESSES and PARALLEL_JOB_SIZE ?

### ISSUE THREAD

**Issue by realtebo** [rectorphp/rector#7755]
# Question

In the source code I can see

```
    public function parallel(int $seconds = 120, int $maxNumberOfProcess = 16, int $jobSize = 20) : void
    {
        $parameters = $this->parameters();
        $parameters->set(Option::PARALLEL, \true);
        $parameters->set(Option::PARALLEL_TIMEOUT_IN_SECONDS, $seconds);
        $parameters->set(Option::PARALLEL_MAX_NUMBER_OF_PROCESSES, $maxNumberOfProcess);
        $parameters->set(Option::PARALLEL_JOB_SIZE, $jobSize);
    }
```

I cannot find a single place where these option are used, but probably I am wrong.

Anyway, what's the meaning of 
- PARALLEL_MAX_NUMBER_OF_PROCESSES
and 
- PARALLEL_JOB_SIZE
?

I am asking this because I'm facing an error about child killed for out of memory when only 20 file are remaining to be scanned.

I am trying to understand how to run rector using a bit less memory (I've 32 GB and nothing running while "rectoring") without sacrifice too much the performance. 

I am working with a 20757 php file project and it's taking > 1.5 hour/run.

It's already 'a lot'

**Comment by samsonasik** [comment]
I am closing it as answered.

**Comment by realtebo** [comment]
Sorry but documentation do not answer to my question. Number of parallelo processes ok. But what Is the job size?

**Comment by samsonasik** [comment]
As far as i know, jobSize used to collect how many files will be processed per-parallel, for example, you have defined jobSize = 2, on 100 files, you have 50 collection of files. When you define 8 process, then it require 7 (or 3 times on multi thread) each processor to take on next collection of files until goes to 50. Smaller number of jobsize means less file to process by each processor. 

see https://3v4l.org/b4XmX

On most use case, as far as I know, the existing default configuration passed on `parallel()` already just works, but if you found issue, you may need to tweak the config.

For very huge file, you may need to extract the rector to per-directory:

```
vendor/bin/rector process app/Controllers
vendor/bin/rector process app/Models
```

Then, when you can verify which source of file(s) that take long time to process.
