### ISSUE TITLE
PHP Notice: 

### ISSUE THREAD

**Issue by MarcoGoeli** [rectorphp/rector#7761]
Since the update of rector php and composer today, the following PHP message appears when I run rector php:

`PHP Notice:  RectorPrefix202302\Nette\Utils\Strings::toAscii(): it is recommended to enable PHP extensions 'intl'. in C:\Users\marco\PhpstormProjects\rector\vendor\rector\rector\vendor\nette\utils\src\Utils\Strings.php on line 125
Notice: RectorPrefix202302\Nette\Utils\Strings::toAscii(): it is recommended to enable PHP extensions 'intl'. in C:\Users\marco\PhpstormProjects\rector\vendor\rector\rector\vendor\nette\utils\src\Utils\Strings.php on line 125
`
Line 125

`\trigger_error(__METHOD__ . "(): it is recommended to enable PHP extensions 'intl'.", \E_USER_NOTICE);`

rector-php version 0.15.13
composer version 2.5.2

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by MarcoGoeli** [comment]
The error is gone when I change the php.ini of PHP 8.2.2

`;extension=intl`
change to
`extension=intl`

Just delete the semicolon in front of it.

**Comment by mhaendler** [comment]
I just stumbled upon this issue. 

@TomasVotruba  wouldn't it be wise to say "intl" is a requirement in rector? you could apply
this requirement in the composer file or we "nette/utils" need to add it, as it's the component which
recommends to use "intl"?

not sure about the right approach here

**Comment by samsonasik** [comment]
Looking at the latest scoped vendor nette/utils/Strings, it seems it check `Translitetator` class.

There is a proposed polyfill component on symfony repo for it:

- https://github.com/symfony/polyfill/pull/192

you may need to enable intl meanwhile

**Comment by TomasVotruba** [comment]
@mhaendler Where exactly is this function used? Maybe we could work around it in a better way.

**Comment by mhaendler** [comment]
@TomasVotruba  I couldn't repredoduce the error myself, but the callstack should be something like this:

In the RectorContainerFactory (src\DependencyInjection\RectorContainerFactory.php). 
```
RectorContainerFactory->createFromBootstrapConfigs
          /** @var ChangedFilesDetector $changedFilesDetector */
          $changedFilesDetector = $container->get(ChangedFilesDetector::class);
          $changedFilesDetector->setFirstResolvedConfigFileInfo($mainConfigFile);
```

The ChangedFilesDetector.php (packages\Caching\Detector\ChangedFilesDetector.php)
```
public function setFirstResolvedConfigFileInfo(string $filePath) : void
    {
        // the first config is core to all → if it was changed, just invalidate it
        $configHash = $this->fileHashComputer->compute($filePath);
        $this->storeConfigurationDataHash($filePath, $configHash);
    }
    
        private function storeConfigurationDataHash(string $filePath, string $configurationHash) : void
    {
        $key = CacheKey::CONFIGURATION_HASH_KEY . '_' . Strings::webalize($filePath);
        $this->invalidateCacheIfConfigurationChanged($key, $configurationHash);
        $this->cache->save($key, CacheKey::CONFIGURATION_HASH_KEY, $configurationHash);
    }
````

The Function "Strings::webalize" get's called. This function calls 
```
$s = self::toAscii($s);
````

That's where the notice get's thrown. 

I hope i could narrow the problem down. I just found rector today and wanted to give it a try in a couple of hours, didn't even had time to clone the repository.

**Comment by samsonasik** [comment]
We may need a replacement of usage Strings::webalize at

https://github.com/rectorphp/rector-src/blob/7f873f0311679c23feacabd3089c8185b9a93c74/packages/Caching/Detector/ChangedFilesDetector.php#L116

**Comment by TomasVotruba** [comment]
@mhaendler Thanks for checking this, that's very helpful :+1: 

<br>

@samsonasik Let's do that! What do you suggest? I think we can use some simple hashing function like sha1 or something.

**Comment by samsonasik** [comment]
sha1 seems can be used, for note, the consecutive run check --dry-run need to be check, like in:

- https://github.com/rectorphp/rector-src/pull/3060

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-src/pull/3356 for it.
