### ISSUE TITLE
DOWN_TO_PHP_74 removes trailing commas in function calls

### ISSUE THREAD

**Issue by smichaelsen** [rectorphp/rector#7765]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.15.5  |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/f2439f54-298e-4c21-951b-7bdd456d0dd8

```php
<?php

final class DemoFile
{
    public function run()
    {
        $foo = sprintf(
          '%s%s',
          'foo',
          'bar',
        );
        return $foo;
    }
}
```

### Responsible rules

* `DowngradeTrailingCommasInParamUseRector`

## Expected Behavior

The rector rule probably is fine, but it should not be included in the `DOWN_TO_PHP_74` set. Having trailing commas in function calls is supported since 7.3. Maybe there is a confusion with trailing commas in the closure use parameter list, which is supported since PHP 8.0.

**Comment by samsonasik** [comment]
The DowngradeTrailingCommasInParamUseRector seems should not remove trailing comma in args, only in params, which seems these lines can be removed:

https://github.com/rectorphp/rector-downgrade-php/blob/b9bfc7810187570f97d68ee3e51881952cc887d5/rules/DowngradePhp80/Rector/ClassMethod/DowngradeTrailingCommasInParamUseRector.php#L101-L108

Ref for demo:

param: - https://3v4l.org/Vv3bP#v7.4.33 Error as expected in php 7.4 as param has trailing comma
args:    - https://3v4l.org/Bd2jh#v7.4.33 working ok as expected in php 7.4 as trailing comma in args is allowed

Could you try provide a patch by remove above lines and update the tests for it ? Thank you.
