### ISSUE TITLE
Is Rector supposed to delete files that it renames?

### ISSUE THREAD

**Issue by arderyp** [rectorphp/rector#7767]
I am running `PHPUnitSetList::PHPUNIT_100`. As part of this process, any abstract PHPUnit test classes whose class/file name ends in `Test` is renamed to end in `TestCase`.  I am new to rector, so maybe I am missing something, but the ruleset seems to simply copy abstract `*Test` files/classes to `*TestCase` files/classes.  It renames the class in _both_ files. 

I'm wondering why the original file is not deleted after being copied, or perhaps why it isn't moved instead of being copied. Since I am new to rector, I'm not sure if this is some safeguard, and I need to pass some flag/argument/config to tell rector to "go ahead and delete source files when renaming classes". If not, I'm wondering if this is a bug with the specific `PHPUnitSetList::PHPUNIT_100` ruleset, or Rector itself.

I am happy to provide any further info that might be helpful in debugging. Since I am new to the system, I am not sure how to debug myself.

**Comment by samsonasik** [comment]
That seems a bug, after all references renamed, the original file should be removed after this line:

https://github.com/rectorphp/rector-phpunit/blob/ee461b14551189faca960058ef4fb1146755f8ca/src/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector.php#L100

should be doable with something like this:

```php
$this->removedAndAddedFilesCollector->removeFile($this->file->getFilePath());
```

Try to inject `Rector\Core\Application\FileSystem\RemovedAndAddedFilesCollector` in `__construct()` and it should work, will you try provide a patch for it ? Thank you.

**Comment by arderyp** [comment]
@samsonasik https://github.com/rectorphp/rector-phpunit/pull/159
