### ISSUE TITLE
Incorrect behavior of DowngradeCovariantReturnTypeRector, DowngradeTypedPropertyRector, DowngradePropertyPromotionRector, DowngradeReadonlyPropertyRector

### ISSUE THREAD

**Issue by defunctl** [rectorphp/rector#7768]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/739ecdac-6940-478c-9122-91142a387224

```php
<?php

/**
 * @template TArray of array
 */
interface Response
{
    /**
     * Returns the array representation of the Response.
     *
     * @return TArray
     */
    public function toArray(): array;
}

/**
 * @implements Response<array{id: string}>
 */
final class TempResponse implements \Response
{
    private function __construct(
		public readonly string $id
	) {
    }

    public function toArray(): array {
        return [
            'id' => $this->id,
        ];
    }

    /**
     * @param array{id: string} $params
     *
     * @return static
     */
    public static function from(array $params): self {
        return new self(
            $params['id']
        );
    }
}

/**
 * @template T of Response
 */
abstract class Handler
{
    /**
     * @return T
     */
    abstract protected function set(): Response;

    /**
     * @return T
     */
    public function get(): Response {
        return $this->set();
    }
}

/**
 * @extends \Handler<\TempResponse>
 */
final class TempHandler extends \Handler
{
    protected function set(): Response {
        return TempResponse::from( [
            'id' => 'test',
        ] );
    }
}
```

### Responsible rules

* `DowngradeCovariantReturnTypeRector`

* `DowngradeTypedPropertyRector`

* `DowngradePropertyPromotionRector`

* `DowngradeReadonlyPropertyRector`

## Expected Behavior

When Rector changes the child classes's `TempHandler::set()` return type from the interface to the concrete implementation, this breaks in PHP7.2/PHP7.3, and in this case, should leave the interface as the return type to keep the contract compatible with the Handler parent/abstract.

![image](https://user-images.githubusercontent.com/1066195/217953297-bcb35fbc-7e7e-4b7c-ba6c-44178d156017.png)

PHP7.2 will throw a fatal such as:

```
Fatal error: Declaration of TempHandler::set(): TempResponse must be compatible with Handler::set(): Response in file.php on line XX
```

**Comment by samsonasik** [comment]
It seems due to ` DowngradeCovariantReturnTypeRector ` ref https://getrector.com/demo/ee938750-d216-44f7-8754-5007ba37bd58

**Comment by samsonasik** [comment]
It seems due to combination usage of `@template T of Response` on `Handler` interface and `@extends \Handler<\TempResponse>` on `TempHandler` class, ref https://getrector.com/demo/4a0fb529-6599-4f90-9d53-f03657c8c02b

**Comment by samsonasik** [comment]
Reduced code example:

- demo https://getrector.com/demo/ed600eac-983e-4599-a6a2-e44b98007ccb
- 3v4l https://3v4l.org/7p7bI#v7.3.4

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-downgrade-php/pull/46 for it.
