### ISSUE TITLE
is there a way to run coding standards/sniff after Rector rule set transformations?

### ISSUE THREAD

**Issue by arderyp** [rectorphp/rector#7769]
The `README` mentions:

> Rector uses [nikic/php-parser](https://github.com/nikic/PHP-Parser/), built on technology called an abstract syntax tree (AST). An AST doesn't know about spaces and when written to a file it produces poorly formatted code in both PHP and docblock annotations. That's why your project needs to have a coding standard tool and a set of formatting rules, so it can make Rector's output code nice and shiny again.
>
> We're using [ECS](https://github.com/symplify/easy-coding-standard) with [this setup](https://github.com/rectorphp/rector-src/blob/main/ecs.php).

Can the example config set be modified to automatically run the `ecs.php` after `SetList::CODE_QUALITY`?

```
$rectorConfig->sets([
      SetList::CODE_QUALITY
  ]);
```

Or do we have to manually run our ECS/linting command after running the rector command (or otherwise script it)?

**Comment by samsonasik** [comment]
You can create script for that, eg: in composer.json

```json
    "scripts": {
        "rector-and-ecs": [
            "rector process --clear-cache",
            "ecs check --fix"
        ]
     }
```

and you can run:

```
composer rector-and-ecs
```

**Comment by arderyp** [comment]
very cool, thanks!
