### ISSUE TITLE
Rector appears to be caching files before they've finished processing.

### ISSUE THREAD

**Issue by aboyton** [rectorphp/rector#7770]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.13             |

When running Rector for some reason I have a file that is failing to process, with an error very similar to #7586. If there are files which work they pass and then Rector hangs when it gets to the problematic file. If I just try process the problematic file then I get no output whatsoever.

This issue though isn't about _that_ bug, this issue is about incorrect caching of files when Rector hangs.

When Rector does hang, if I quit rector with `Ctrl + C` and then run again it appears as those the file that was problematic has been marked as processed and so running Rector succeeds the second time.

If I run with `vendor/bin/rector process --clear-cache` then I get stuck on the problematic file again, or if I change the list of files to process (which appears to reset the cache) it fails the first run and succeeds the second.

## Minimal PHP Code Causing Issue

Unfortunately I don't have that as the code that is breaking things appears to work on https://getrector.org/demo/ :(

I've set `$rectorConfig->parallel(seconds: 600, maxNumberOfProcess: 1);` to make things easier to debug, but the issue occurs with parallel processes as well.

## Expected Behaviour

When a file is processed it should only be added to the cache when it has successfully finished processing.

**Comment by yguedidi** [comment]
@aboyton maybe you would like to test latest master of rector now that https://github.com/rectorphp/rector-src/pull/3604 is merge?
It should fixes the caching issue

**Comment by samsonasik** [comment]
There is no master branch, you probably mean `main` as `dev-main` in composer

**Comment by yguedidi** [comment]
Thanks @samsonasik I thought about that when I thought about writing this comment, but when actually writing... 😓

**Comment by samsonasik** [comment]
Re-open, @yguedidi I need to revert your change as I found double `--dry-run` no longer working after PR:

- https://github.com/rectorphp/rector-src/pull/3604

![Screen Shot 2023-04-11 at 15 17 59](https://user-images.githubusercontent.com/459648/231100502-105a52a5-a8ed-4619-a2a6-6d2e5427408c.png)

**Comment by samsonasik** [comment]
Reverting it at https://github.com/rectorphp/rector-src/pull/3607

**Comment by yguedidi** [comment]
@samsonasik thank you for catching this! looks like all my contributions introduce regressions... 😅 
Will work on a fix when I have time

**Comment by yguedidi** [comment]
@aboyton in next release you'll be able to enjoy a reliable cache! 🎉

**Comment by aboyton** [comment]
Thanks. That's awesome. I'll have to try it out once the next release is released.

Any idea why `rector --clear-cache` can take 10+ minutes to run? Hopefully I won't need this going forth but the slowness is frustrating.

**Comment by yguedidi** [comment]
> Any idea why `rector --clear-cache` can take 10+ minutes to run? Hopefully I won't need this going forth but the slowness is frustrating.

10+ minutes on which project?

**Comment by aboyton** [comment]
> > Any idea why `rector --clear-cache` can take 10+ minutes to run? Hopefully I won't need this going forth but the slowness is frustrating.
> 
> 10+ minutes on which project?

Internal work repository of 1M+ lines of code.

**Comment by yguedidi** [comment]
@aboyton depending on your project and enabled rectors, but I'd say that 10minutes for such a big project looks OK when running without cache :)
