### ISSUE TITLE
Is there a progress "bar" compatible with CI ?

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#7771]
# Question

GItlab CI do not show the progress bar in a single line, see picture linked. Is there another progress bar as cs-fixer does with dot ?
![image](https://user-images.githubusercontent.com/17164385/218443236-95638a59-6cb4-44b8-b54a-0a11638bfb21.png)

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
This should not happen.

Is this correctly picked up by your CI?
https://github.com/rectorphp/rector-src/blob/7f9704010043e95a107d2a5fd5112fcfc2c2990b/src/Console/Style/RectorConsoleOutputStyle.php#L70

**Comment by vasilvestre** [comment]
> 

How could I try it is picked up ?

**Comment by TomasVotruba** [comment]
> It also runs in a docker so it may be why the CI detector does not work

Bingo :+1:

**Comment by vasilvestre** [comment]
> > It also runs in a docker so it may be why the CI detector does not work
> 
> Bingo +1 that's your solution. You should propagate env variable to container as well. Also, unless you run on PHP 7.1 and bellow, Docker will only complicate Rector run.

Thank you, I try to find the workaround for this now.
