### ISSUE TITLE
How can ignore a especific rule in a specific line?

### ISSUE THREAD

**Issue by marioquartz** [rectorphp/rector#7772]
I know that I can set a list of ignored paths (but ignore all lines of that file) and I know that I can set a list of rules (but the rules are ignored in all files). But I need ignore one rule (adding JSON_THROW_ON_ERROR in json_decode) in one specific line in one specific file. The reason is that a request maked to an external API can return a string with the file content or a json with error information. If json_decode return null that means that there are no problems and is a normal file. But if I can not ignore that line, I can not use rector in that file. Three lines below that line there are other json_decode and in that line is very convenient that flag.

**Comment by TomasVotruba** [comment]
Hi,

that is ont possible, as this poluted the code and hide unnecessry skips. These are vailable options:
https://getrector.com/documentation/ignoring-rules-or-paths

In this case, it would be better to require exception everywhere, ideally in a dedicated method call, and handle the exceptoin in try/catch for this particular line.
