### ISSUE TITLE
DoWhileBreakFalseToIfElseRector missing?

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7773]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.13             |

Rule \Rector\CodeQuality\Rector\Do_\DoWhileBreakFalseToIfElseRector does not exist anymore, but isn't mentioned in the changelog as removed (as tested on https://getrector.com/)?

**Comment by samsonasik** [comment]
That's removed by PR:

- https://github.com/rectorphp/rector-src/pull/3367

should be mentioned in next rector release page.
