### ISSUE TITLE
Incorrect behavior of SimplifyUselessVariableRector

### ISSUE THREAD

**Issue by Andi-aboalarm** [rectorphp/rector#7775]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/3adaf502-2201-47e4-aaa2-33984f3bfdfd

```php
<?php

final class DemoFile
{
    public function run()
    {
        $foo = null;
        $bar = strlen($foo);
        return $bar;
    }
}
```

### Responsible rules

* `SimplifyUselessVariableRector`

## Expected Behavior

```php
<?php

final class DemoFile
{
    public function run()
    {
        $foo = null;
        return strlen($foo ?? '');
    }
}
```

**Comment by Andi-aboalarm** [comment]
null coalescing operator needed to avoid null in strlen to avoid deprecation warning

**Comment by samsonasik** [comment]
`SimplifyUselessVariableRector` is unrelated with null coalescing transformation. 

Also, Rector is not error handler, use phpstan job as the right tool to get there, and decide what need to do in the code ( check is_null, ,is_string, or just remove the code, etc) :)

**Comment by samsonasik** [comment]
Actually, if you have possibly null value for `strlen()` on php 8.1, you can use ` NullToStrictStringFuncCallArgRector ` that included in `LevelSetList::UP_TO_PHP_81` so it converted with cast (string) https://getrector.com/demo/054ffe95-48fc-497d-94c1-a1d76a92538e

**Comment by samsonasik** [comment]
Re-open, I created PR https://github.com/rectorphp/rector-src/pull/3385 for it to handle `$variable = null` early defined before passed as arg.
