### ISSUE TITLE
Unresolvable loop causes incorrect behavior of `AddDefaultValueForUndefinedVariableRector`

### ISSUE THREAD

**Issue by jackbentley** [rectorphp/rector#7777]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e1b4cf4e-c34f-466d-ac1a-4ecdbffca61c

```php
<?php

final class DemoFile
{   
    public function run(Item $yes)
    {
        while (true !== false) {
        }
        
        $a = [];
        
        if ($b = $yes) {
            $a[] = 'test';
        }
        
        return $a;
    }
}
```

More real-world example:

See https://getrector.com/demo/c74cd93b-9c55-41d6-b831-24f952405737

```php
<?php

final class Item
{
    private $parent;
    
    /**
     * @return Item
     */
    public function getParent()
    {
        return $this->parent;
    }    
}

final class DemoFile
{
    private function create()
    {
        return [];
    }
    
    public function run(Item $yes)
    {
        while (($yes = $yes->getParent()) !== null) {
        }
        
        $a = $this->create();
        
        if ($b = $yes) {
            $a[] = 'test';
        }
        
        return $a;
    }
}
```

### Responsible rules

* `AddDefaultValueForUndefinedVariableRector`

## Expected Behavior

Rector shouldn't "fix" this. The variable is always set. Removing the `while` makes Rector think the code is correct.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.
