### ISSUE TITLE
"System error: "Undefined constant PHPStan\PhpDocParser\Ast\Type\GenericTypeNode::VARIANCE_INVARIANT" 

### ISSUE THREAD

**Issue by ahmedesa** [rectorphp/rector#7778]
Could not process " " file, due to:                    
         "System error: "Undefined constant PHPStan\PhpDocParser\Ast\Type\GenericTypeNode::VARIANCE_INVARIANT"          
         Run Rector with the "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 369   

version
"rector/rector": "^0.13.10",

**Comment by samsonasik** [comment]
Rector is now version 0.15.6, please try latest version.

**Comment by samsonasik** [comment]
I am closing it as the constant exists in latest rector version.
