### ISSUE TITLE
Ignoring paths with pattern

### ISSUE THREAD

**Issue by grandmaster44** [rectorphp/rector#7780]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.15+ (invoke `vendor/bin/rector --version`)             |

Rector is changing skipped files when processing a single file.

## Minimal PHP Code Causing Issue

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
    ]);

    $rectorConfig->skip([
        RemoveUnreachableStatementRector::class => [
            __DIR__ . '/app/*',
        ],
    ]);

    // A. run whole set
    $rectorConfig->sets(
        [
            SetList::DEAD_CODE,
        ]
    );

    // B. or single rule
    $rectorConfig->rule(TypedPropertyFromAssignsRector::class);
};
```

I have a file in `app` directory:

```
// app/demo.php
<?php

final class DemoFile
{
    public function run()
    {
        return 5;

        // we never get here
        return 10;
    }
}

```

when I run rector with `bin/rector process --dry-run app/demo.php` - it's changing the file:
![obraz](https://user-images.githubusercontent.com/23462753/219371941-e867c5b1-f55f-4100-b9b4-690f1aba7fcf.png)

## Expected Behaviour

Rector should not change the file when it should be skipped.

**Comment by TomasVotruba** [comment]
This feature would be welcomed :+1: 
It will need an update of fnmatches, that is missing absolute paths now.

**Comment by samsonasik** [comment]
@grandmaster44 you should can use `'**/app/*'` for now.

**Comment by TomasVotruba** [comment]
Closing as accepted to avoid keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with it :+1:
