### ISSUE TITLE
Add Rector rule to clean up nullsafe checks on returns that dont return null values

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector#7781]
# Feature Request
With php 8 nullsafe operator was introduced more info: https://stitcher.io/blog/php-8-nullsafe-operator
I would like a rule that cleans up nullsafe checks on returns that dont return null
## Diff 

```diff

class HelloWorld {
    public function getString(): string
    {
         return 'hello world';
    }
}

public function get(): HelloWorld
{
     return new HelloWorld();
}

-echo $this->get()?->getHelloWorld();
+echo $this->get()->getHelloWorld();
```

**Comment by TomasVotruba** [comment]
Looks good 👍😊

**Comment by samsonasik** [comment]
@johanadivare for note, real native return type (instead of `@return` ) need to be checked to ensure that return type not nullable, something like in https://github.com/rectorphp/rector-downgrade-php/pull/46/files#diff-4529196d193b3f63505293cef1a30dd3226e4b5d63e665ec135fef895ce3a96f

**Comment by johanadivare** [comment]
See https://github.com/rectorphp/rector-src/pull/3400
