### ISSUE TITLE
Incorrect behavior of ChangeSwitchToMatchRector

### ISSUE THREAD

**Issue by jnoordsij** [rectorphp/rector#7782]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/ab671fa0-5f74-4495-b6f6-e8918d8b5f1a

```php
<?php

switch ($file['type']) {
    case StorageAttributes::TYPE_DIRECTORY:
        $root['folders'][] = $file;
        break;
    case StorageAttributes::TYPE_FILE:
        $root['files'][] = $file;
        break;
    default:
        $root['unknown'][] = $file;
}
```

### Responsible rules

* `ChangeSwitchToMatchRector`

## Expected Behavior

Code should be skipped: assignment is applied to different variables (or more specifically: different array keys), so should not be converted to a `match` case.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.
