### ISSUE TITLE
Incorrect behavior of CompleteDynamicPropertiesRector

### ISSUE THREAD

**Issue by gav-** [rectorphp/rector#7783]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/c69d029f-a68b-4c18-872d-fffc5b87e9c5

```php
<?php

class NormalClass extends BaseClass
{   
    public function run()
    {
        $this->test = true;
    }
}
```

### Responsible rules

* `CompleteDynamicPropertiesRector`

## Expected Behavior

If BaseClass contains "protected bool $test" in the same php file as NormalClass is defined, Rector correctly suggests no change as seen here:  https://getrector.com/demo/e44b832a-0d2b-46f4-9b18-d273b5c7a050

However in this bug example, if BaseClass still contains "protected bool $test", but it is defined in a different php file to NormalClass, then Rector incorrectly suggests that NormalClass needs "public $test".

**Comment by gav-** [comment]
Cleared the Rector cache, and the problem went away. Sorry for the trouble.

**Comment by samsonasik** [comment]
Awesome, I am closing then ;)
