### ISSUE TITLE
Avoid to count files to speed up startup

### ISSUE THREAD

**Issue by realtebo** [rectorphp/rector#7785]
# Feature Request

I am here to ask if it's possible to avoid the count of all files before starting rector parsing.

I've a project with  more of 20k file, (no vendors !!!!, all project files :) ) 

At every run, on my i7 with  12core rector takes up to 15-20min to start parsing and modifying the files.

I suppose we can do without the file count with an option.
So instead of a progress bar it could only show a file count progression

Could be done?

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
Is seems there is some infinity loop :)

Rector takes 2-5 seconds to start on ~1500 files.
Could you try narrow the directories down? I assume one of them will contain the looping code.

**Comment by staabm** [comment]
Could you provide a reproducer in a example repo?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:
