### ISSUE TITLE
Rector stalls slowly consumes memory until machine dies

### ISSUE THREAD

**Issue by turtle0x1** [rectorphp/rector#7787]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.7  & v0.15.0 |

Using rector for the first time so apologies if I did something wrong.

Got a basic rector config setup and set the target sets to `LevelSetList::UP_TO_PHP_80`.

Running the tool over the files with `--debug` I could see it stalling at the same file each time, so I added an exclude to my rector config. Ran it again, same thing, ran it 75 more times (adding the exclusions) and now I have a long lists of exclusions and it still doesn't complete (i'm growing concerned ill just end up manually adding all the files so ill stop here).

There doesn't appear to be any commonality between the files, some external dependencies, some do not.

If I run rector or just the files that cause the stalling, it doesn't stall and completes as expected.

Im running this on a folder I have called "Services", If run the same config on my `Controllers` and `Models` folders, 0 problems  on those and it completes as expected.

Also `--memory-limit` doesn't work as expected in this case, it will just keep growing until its using 100% of memory+swap and the machine dies.

I have tried adding some minimal print statements in an attempt to debug rector but I haven't had much luck, any tips where can I poke to try to fix / create a reliable reproducer? 

I have 16GB of RAM and a 8 core CPU Ryzen CPU if that matters :smile: 

## Minimal PHP Code Causing Issue

Cant reproduce on one file only seems to be an issue when its running on a "large" number of files and not just one

## Expected Behaviour

It doesn't stall and outputs as expected.

**Comment by samsonasik** [comment]
Instead of using directly `LevelSetList::UP_TO_PHP_80` which consist all php level set list start from 5.2 to 8.0, you can try per-setlist approach, eg:

```php
$rectorConfig->sets([
    \Rector\Set\ValueObject\SetList::PHP_52,
]);
```

Then repeat until it got error, so we can get the source of the error and it fixable. You can read how to narrow down rules at https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by turtle0x1** [comment]
Thanks, so I ran the suggested config up from 52 to 82 and cleared up the errors.

Now can run the following config without error.

```php
$rectorConfig->sets([
    LevelSetList::UP_TO_PHP_82
]);
```

But is it expected that when running `UP_TO_PHP_82` more errors are uncovered when compared to manually running the set lists individually?

**Comment by samsonasik** [comment]
For legacy projects, that's usually the best way, start with something small (rule by rule or set list by set list), that will easy to review the changed code as well.

**Comment by samsonasik** [comment]
I am closing it as the solution provided.
