### ISSUE TITLE
Rector hang up with the rule IfToSpaceshipRector

### ISSUE THREAD

**Issue by Freespacer** [rectorphp/rector#7788]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.13            |

Under certain circumstances Rector hangs up during refactoring of the rule "IfToSpaceshipRector".

## Minimal PHP Code Causing Issue

The Rector demo page does not work too. 

Hang up example 1:
https://getrector.com/demo/b0b4b1b4-dfd3-4034-a2c7-402b618f56d2

Hang up example 2:
https://getrector.com/demo/46f17241-3a36-4dc1-9ac2-5052c7a05116

Working example 1:
https://getrector.com/demo/2e029aa4-67b2-4e0d-856f-f91d27ab2ef9

Working example 2:
https://getrector.com/demo/db2a2abc-b0f7-4255-a788-e94152c8c978

## Expected Behaviour

The expected behavior is that Rector runs through without hangs. Please note the comment in code examples for expected refactored code.

**Comment by samsonasik** [comment]
Using only `IfToSpaceshipRector` seems working ok https://getrector.com/demo/bd2d2298-d0e9-44f2-acaf-7f6f0619e7c4

So it seems due to various rule combination, could you narrow down the rules 

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by Freespacer** [comment]
@samsonasik Thanks for pointing out that any rules might be in conflict with `IfToSpaceshipRector`. I tracked it down and found the responsible rule.

`AddDefaultValueForUndefinedVariableRector` in combination with `IfToSpaceshipRector`.

Please look into this example:
https://getrector.com/demo/d67d5149-19d6-4a90-9290-15c7ebb8434d

Thanks

**Comment by samsonasik** [comment]
Thank you, I will look into it.
