### ISSUE TITLE
Incorrect behavior of RemoveDeadStmtRector (and others?) with short echo tags

### ISSUE THREAD

**Issue by bananastalktome** [rectorphp/rector#7789]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a7122f39-c255-4c56-908c-6f412f696ec4

```php
<?php
$args;
?>
<img src="<?= esc_url($image_src); ?>" alt="">
```

Additionally, from https://getrector.com/demo/f3d8ac7d-212b-4cff-86bd-5939a2ee338f ,

```php 
<?php
function test_callback() {
  // var_dump($output);
  ?>
  <div class="wrap">
    <img src="<?= escape('hi there'); ?>">
  </div>
  <?php
}
```

### Responsible rules

* `RemoveDeadStmtRector`
* No rules listed for second demo link

## Expected Behavior

For the first demo link, removing `$args;` and for the second either removing or ignoring the commented var_dump, but for both not also adding php open/close tags around otherwise functional short echo tag.

**Comment by samsonasik** [comment]
That's possibly php-parser bug itself, as just by printing itself got additional `<?php`, see:

https://getrector.com/demo/558b238e-b4d6-497c-918b-5b821c6b4e49

This also possibly related with issue:

- https://github.com/rectorphp/rector/issues/7703

which commented custom syntax on `if elseif` got duplicated comment. 

I sent failing test case PR to nikic/php-parser for duplicated comment:

- https://github.com/nikic/PHP-Parser/pull/914

for this use case, you may create another failing test case PR as well to https://github.com/nikic/PHP-Parser :)

**Comment by bananastalktome** [comment]
I'm not familiar with the details of PHP-Parser, but I cloned the repo and added a test locally:

```
<?php

function test()
{
    // var_dump('test');
    ?>
    <img src="<?= escape('Test'); ?>">
    <?php
}
-----
function test()
{
    // var_dump('test');
    ?>
    <img src="<?= escape('Test'); ?>">
    <?php
}
```

Though the test failed, it only changed the following:

```
-    <img src="<?= escape('Test'); ?>">
+    <img src="<?php
+    echo escape('Test');
+    ?>">
```

With rector, the same function (https://getrector.com/demo/9574e31f-3017-4d28-903b-490bcf416628) has a different replacement. PHP-Parser didn't appear to try and add `<?php` around the existing `<?=`, but replaced the short echo with the longer form, whereas rector did seem to want to mess with the php tags.

**Comment by samsonasik** [comment]
Demo page and local may have different addition `?>` , thats possibly due to php read php code on mix html+php on website.

You can try latest "rector/rector": "dev-main" locally

**Comment by bananastalktome** [comment]
> Demo page and local may have different addition `?>` , thats possibly due to php read php code on mix html+php on website.
> 
> You can try latest "rector/rector": "dev-main" locally

@samsonasik When run locally, though I no longer get the extra closing tag from the second example above, I still get the weird tag doubling:

```
-  <img src="<?= escape('Test'); ?>">
+  <img src="<?php <?= escape('Test'); ?>">
```

Are you thinking this is from PHP-Parser, though running tests through it as included above doesn't seem to result in doubling-up of php opening tags (rector turning `<?=` into `<?php <?=`)?

Thanks!

**Comment by bananastalktome** [comment]
@samsonasik Thanks for the continued advice! I ran it again locally, with `short_open_tag` enabled, but there was no difference (`<?=` isn't affected by `short_open_tag`, I don't think).

I am running with the rules

```php
$rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);
$rectorConfig->sets([
    LevelSetList::UP_TO_PHP_74
]);
```

nikic/php-parser does seem to handle parsing the code fine, and only changes `<?=` to `<?php echo` rather than rector changing it to `<?php <?=`. Where would this doubling up come from? Please let me know if there is any other debugging or testing I can do to help figure this out.

**Comment by samsonasik** [comment]
If unit test result is different with run on command, you may need to add `e2e/plain-views` test https://github.com/rectorphp/rector-src/tree/main/e2e with the following steps:

1. open e2e/plain-views
2. run composer install
3. run php ../e2eTestRunner.php

See the diff, and submit the pull request with expected output at https://github.com/rectorphp/rector-src/blob/main/e2e/plain-views/expected-output.diff 

then, create PR as failing test case PR, would be awesome if you can include the fix :)

**Comment by samsonasik** [comment]
I am looking into it at PR:

- https://github.com/rectorphp/rector-src/pull/3395
