### ISSUE TITLE
Call to undefined method PHPStan\Type\UnionType::getObjectClassNames()

### ISSUE THREAD

**Issue by koftikes** [rectorphp/rector#7797]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.15.17  |

./vendor/bin/rector process --clear-cache --dry-run

Could not process " .... " file, due to:  "System error: "Call to undefined method PHPStan\Type\UnionType::getObjectClassNames()"

**Comment by samsonasik** [comment]
Could you try dev-main? The scoped prefix include latest phpstan 1.10.1

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by koftikes** [comment]
> Could you try dev-main? The scoped prefix include latest phpstan 1.10.1

Yes with dev-main work as expected. When are new tag will be published?

**Comment by samsonasik** [comment]
Just released https://github.com/rectorphp/rector/releases/tag/0.15.18 👍
