### ISSUE TITLE
Code with inline comment is moved below.

### ISSUE THREAD

**Issue by 94noni** [rectorphp/rector#7799]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.15.17            |

Code with inline comment is moved below.

## Expected Behaviour

# before

```php
public const AUTHORISED = 'AUTHORISED'; // the payment authorisation was successfully completed
```

# after (buggy?)

```php
    /**
      * @var string
      */
     public const AUTHORISED = 'AUTHORISED';
     // the payment authorisation was successfully completed
```

# expected (correct)

```php
    /**
      * the payment authorisation was successfully completed
      * @var string
      */
     public const AUTHORISED = 'AUTHORISED';
```

-----------

❔Am I making things wrongly❔

Many thanks

**Comment by TomasVotruba** [comment]
Hi, this is feature of php-parser - https://github.com/nikic/PHP-Parser
It joins comment/docblocks above the element. Anything after belongs to next element.

There is simple solution. Use slevomat coding standard to move your comments above the element:

```diff
-public const AUTHORISED = 'AUTHORISED'; // the payment authorisation was successfully completed
+// the payment authorisation was successfully completed
+public const AUTHORISED = 'AUTHORISED'; 
```

**Comment by 94noni** [comment]
@TomasVotruba fair enough will see ho to swap this in our code base in global before running Rector
thx for stopping and answering

**Comment by TomasVotruba** [comment]
This rule handles it: https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentingdisallowcommentaftercode-

Use ECS to handle it for you:

````bash
composer require symplify/easy-coding-standard --dev
composer require slevomat/coding-standard --dev
```

Create config:

```php
// ecs.php
<?php

declare(strict_types=1);

use Symplify\EasyCodingStandard\Config\ECSConfig;
use SlevomatCodingStandard\Sniffs\Commenting\DisallowCommentAfterCodeSniff;

return function (ECSConfig $ecsConfig): void {
    $ecsConfig->paths([
        __DIR__ . '/src',
    ]);

    $ecsConfig->rule(DisallowCommentAfterCodeSniff::class);
};
```

```bash
vendor/bin/ecs --fix
```

**Comment by 94noni** [comment]
@TomasVotruba 

> Use ECS to handle it for you:

we are planing to use it instead of csfix directly
thx for detailing this
