### ISSUE TITLE
Is there a preset or rule for PSR-12? 

### ISSUE THREAD

**Issue by ali-sajjad-dev** [rectorphp/rector#7800]
# Question

I'm interested in using Rector for PSR-12, is there a rule set available for this?

https://www.php-fig.org/psr/psr-12/

**Comment by TomasVotruba** [comment]
Yes, but it's in different tool: EasyCodingStandard: 
https://github.com/easy-coding-standard/easy-coding-standard/blob/a120982e1ce8e80b5f66fc440a40225ddbe0fc13/src/ValueObject/Set/SetList.php#L13

**Comment by TomasVotruba** [comment]
```bash
composer require symplify/easy-coding-standard --dev
```

Generate `ecs.php` config for your project with 1st run:

```bash
vendor/bin/ecs
```

Add the `SetList::PSR_12` to sets() and run again:

```bash
vendor/bin/ecs --fix
```

**Comment by ali-sajjad-dev** [comment]
Thanks!
