### ISSUE TITLE
Incompatibility with new PHPStan

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#7803]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.17             |

After upgrading to PHPStan 1.10 and PHPStan strict-rules 1.5 I'm getting this error when trying to run Rector:

```
PHP Fatal error:  Uncaught _PHPStan_1f608dc6a\Nette\Schema\ValidationException: Unexpected item 'parameters › reportWrongPhpDocTypeInVarTag'. in phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/schema/src/Schema/Processor.php:75
```

[error.zip](https://github.com/rectorphp/rector/files/10825048/error.zip)

Downgrading to phpstan/phpstan-strict-rules 1.4.x can be used as a workaround for now.

**Comment by samsonasik** [comment]
You need to update to latest rector 0.15.18

**Comment by enumag** [comment]
Oh... I didn't realize there was an update 🤦 sorry
