### ISSUE TITLE
Annotations are case sensitive eg. `@testdox` vs `@testDox`

### ISSUE THREAD

**Issue by tarlepp** [rectorphp/rector#7804]
# Bug Report

Just used Rector to update my codebase test to use PHPUnit 10 attributes and I noticed that annotations `@testdox` was not converted to use attributes because within Rector it's case sensitive so if your codebase is not using `@testDox` annotation those are not converted to attributes correctly. 

And eg. PHPStorm autocomplete that to `@testdox` (note all is lowercase).
![image](https://user-images.githubusercontent.com/595561/221376107-baf09d42-7650-4835-9517-24212b1a2e6b.png)

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.18             |

## Minimal PHP Code Causing Issue
```php
class SomeTest extends KernelTestCase 
{
    /**
     * @testdox Test something
     */
    function testSomething(): void
    {
        ...
    }
}
```

## Expected Behaviour
```php
class SomeTest extends KernelTestCase 
{
    #[\PHPUnit\Framework\Attributes\TestDox('Test something')
    function testSomething(): void
    {
        ...
    }
}
```

**Comment by samsonasik** [comment]
Could you try provide a patch, add to config should can cover that

https://github.com/rectorphp/rector-phpunit/blob/13e842b8c9edc12c0aca1c6341d7860aab523fef/config/sets/annotations-to-attributes.php#L51

**Comment by tarlepp** [comment]
> Could you try provide a patch?, add to config should can cover that
> 
> https://github.com/rectorphp/rector-phpunit/blob/13e842b8c9edc12c0aca1c6341d7860aab523fef/config/sets/annotations-to-attributes.php#L51

Sure created PR about that https://github.com/rectorphp/rector-phpunit/pull/163

**Comment by tarlepp** [comment]
Did not look, if there is some test to change too to cover this, if there is some need for that just ping me on this issue and I'll take a closer look.
