### ISSUE TITLE
Incorrect behavior of TypedPropertyFromAssignsRector

### ISSUE THREAD

**Issue by koko236** [rectorphp/rector#7809]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/73c31adc-d79d-4f13-addc-56997d5b749a

```php
<?php

final class DemoFile
{
    /**
     * @var bool
     *
     * @ORM\Column(name="requires_signup", type="boolean")
     * @Groups("agenda:export")
     */
    private $requiresSignup = false;
}
```

### Responsible rules

* `TypedPropertyFromAssignsRector`

## Expected Behavior

I believe Rector should rather set type to bool following the @var (and ORM) definition. Instead it sets it to false type.

**Comment by samsonasik** [comment]
`TypedPropertyFromAssignsRector` is depends on assign, not `@var` so the bug is on default value on the property, ref https://getrector.com/demo/2b9d1a69-3d9d-4293-8a3d-c93f47560bf0

It seems the false to false mapper should verify the php version used at least php 8.2, ref https://3v4l.org/A6X8S

**Comment by koko236** [comment]
If I'm not mistaken the assign is result of another Rector rule that moved the assignement from constructor to var declaration.

**Comment by samsonasik** [comment]
that a bug on mapper, see https://github.com/rectorphp/rector-src/pull/3422
