### ISSUE TITLE
PublicConstantVisibilityRector not working on final constants

### ISSUE THREAD

**Issue by FabienLge** [rectorphp/rector#7812]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.19             |
| Rector rule | PublicConstantVisibilityRector             |

## The issue

I was simply trying to run the `PublicConstantVisibilityRector` rule on the whole project. Seeing nothing was happening, I tried using it on a specific class. Here is the result : 

Exemple of code : 

```php
class ExempleCommand extends Command
{
    const EXIT_OK = 0;
    final const EXIT_KO = 1;
    final const EXIT_NULL = 2;
}
```

Dry run from Rector : 

```text
---------- begin diff ----------
@@ @@
 {
-    const EXIT_OK = 0;
+    public const EXIT_OK = 0;
     final const EXIT_KO = 1;
     final const EXIT_FLUX_NULL = 2;
    ----------- end diff -----------
```

## Expected Behaviour

For me, the excepted behavior is to add the `public` visibility between `final` and `const`, like such :

```php
class ExempleCommand extends Command
{
    public const EXIT_OK = 0;
    final public const EXIT_KO = 1;
    final public const EXIT_NULL = 2;
}
```

I guess that's an issue since the `FinalizePublicClassConstantRector` rule adds the `final` keyword in front of constants defined as `public` such as the example above.

## Thanks

Thank you guys for keeping up this great library. I really enjoy using it and honestly without it we would be struggling pretty hard 👍

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by FabienLge** [comment]
Thanks for your quick answer !

[Here is a demo matching exactly the examples I gave in the issue explaination](https://getrector.com/demo/71cb8ea0-09ef-45fc-b3af-c9846e0d2f34)

**Comment by samsonasik** [comment]
That is expected, the class already final, there is no need to set constant final as it always final, per different rule: `FinalizePublicClassConstantRector`, see PR:

- https://github.com/rectorphp/rector-src/pull/1730

for original issue:

- https://github.com/rectorphp/rector/issues/6964

**Comment by FabienLge** [comment]
> That is expected, the class already final, there is no need to set constant final as it always final, per different rule: `FinalizePublicClassConstantRector`, see PR:
> 
> * [[FinalizePublicClassConstantRector] Ignore final classes rector-src#1730](https://github.com/rectorphp/rector-src/pull/1730)
> 
> for original issue:
> 
> * [[FinalizePublicClassConstantRector] Ignore final classes #6964](https://github.com/rectorphp/rector/issues/6964)

Hello ! 

Thanks for the answer, but as the code snippet shows, the class is not declared as `final` (see below).
I don't think that's correlated sadly.

Are you seeing it final ?

![Screenshot_1](https://user-images.githubusercontent.com/51742256/221930856-2205b395-20da-4a09-b4c4-3a3b19717770.png)

**Comment by samsonasik** [comment]
You can use for that FinalizePublicClassConstantRector for that, see:

https://getrector.com/demo/61147669-75c1-4246-8841-40c72d1ccdd2

**Comment by FabienLge** [comment]
For this special it works indeed, but in other cases you may want to extend the class, so making it final will make it impossible, but you may also want to make its constants final

**Comment by samsonasik** [comment]
Parent child class relation is depends on autoload, you can troubleshoot class with child for that that may  cause that https://getrector.com/documentation/static-reflection-and-autoload

**Comment by FabienLge** [comment]
I understand your point but I don't think that makes mine invalid. In my opinion, you should be able to make your classes constants final without having to make your entire class final for several reasons. 

> For this case it works indeed, but in other cases you may want to extend the class, so making it final will make it impossible, but you may also want to make its constants final
> 
> ```
> class Parent
> {
>     final public const CONSTANT = 0;
> 
>     public function method()
>     {
>         // ...
>     }
> }
> 
> class Child extends Parent
> {
>     public function method()
>     {
>          parent::method();
> 
>          //...
>     }
> }
> ```

Also for me it doesn't give an answer for the case I showcased here.

**Comment by samsonasik** [comment]
Different rule has different task.

- PublicConstantVisibilityRector make constant public
- FinalizePublicClassConstantRector finalize it

when you combine above rules, the class no need to be final, and constant will be public and final, see https://getrector.com/demo/d69cd1f6-73f1-4693-b057-dd050ed77f44

**Comment by FabienLge** [comment]
Yeah this combination works for a constant that's *only* tagged as `const`. But as we can see in your code snippet there other two constants were ignored by the `PublicConstantVisibilityRector` rule.

![image](https://user-images.githubusercontent.com/51742256/221936641-bf9efac9-2580-4a8f-8952-593acdc29396.png)

**Comment by samsonasik** [comment]
Oh, I see, could you create failing test case PR for it? You can click "Create a Test" button at demo page, thank you.
