### ISSUE TITLE
`GetToConstructorInjectionRector` doesn't implement parent constructor calls properly

### ISSUE THREAD

**Issue by jackbentley** [rectorphp/rector#7814]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

When the rector is run on two files which one inherits the other, the parent constructor call is not added.

## Minimal PHP Code Causing Issue

See rectorphp/rector-symfony#373

**Comment by samsonasik** [comment]
I am closing it as it can be resolved by using rule among with AddConstructorParentCallRector

- https://github.com/rectorphp/rector-src/pull/3430
