### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by 720720** [rectorphp/rector#7816]
rector 0.15.10

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;

use Ssch\TYPO3Rector\Set\Typo3LevelSetList;

return static function (RectorConfig $rectorConfig): void {

    $rectorConfig->sets([
        Typo3LevelSetList::UP_TO_TYPO3_11,
        LevelSetList::UP_TO_PHP_74,
        SetList::CODE_QUALITY,
        SetList::CODING_STYLE,
        SetList::DEAD_CODE,
    ]);

};
```

```php
<?php

class a {
    function a() {
        if (true)
        $a = 1;
        $b = 2;
    }
}
```

causes an out of memory error

**Comment by samsonasik** [comment]
Without `Typo3LevelSetList::UP_TO_TYPO3_11`, it seems working ok, see https://getrector.com/demo/bfc7190b-3d55-4eeb-bc1c-9c5e9974e729

The bug possibly on https://github.com/sabbelasichon/typo3-rector or on combination with that.

hint:

- try latest Rector 0.15.19
- if it still error, create reproducible repository, better with github action in combination with typo3-rector so it resolvable

**Comment by 720720** [comment]
rector 0.15.19 also runs out of memory

https://github.com/sabbelasichon/typo3-rector/issues/3244

**Comment by samsonasik** [comment]
Could you create reproducible repository? better with github action in combination with typo3-rector so it resolvable, thank you.

**Comment by samsonasik** [comment]
@720720 Ok, I tried latest rector dev-main with latest `sabbelasichon/typo3-rector` dev-main with alias:

```
{
    "require-dev": {
        "rector/rector": "dev-main as 0.15.10"
    },
    "require": {
        "ssch/typo3-rector": "dev-main as 1.13"
    }
}

```

and it seems no output but got error status code 11:

![Screen Shot 2023-03-02 at 06 18 22](https://user-images.githubusercontent.com/459648/222288786-464c6b6b-ad3b-4bca-b00b-820ddfe4bff2.png)


On debugging, the issue is when:

```php
SetList::DEAD_CODE,
```

is added on the list. On debugging, the issue seems due to usage of rule:

```php
# vendor/rector/rector/config/set/dead-code.php
        RemoveAlwaysTrueIfConditionRector::class,
```

**Comment by samsonasik** [comment]
Ok, the bug is actually on `NewlineAfterStatementRector`, which before add new line, current node and parent node need to be compared to verify that it has same parent node, I will create PR to fix it.
