### ISSUE TITLE
Implicit conversion from float Rector

### ISSUE THREAD

**Issue by scottybcoder** [rectorphp/rector#7820]
# Feature Request

Not sure how to even correct this for PHP 8.2 but it would be nice if we could.

```
function mix($a,$b,$c) {
  $a -= $b; $a -= $c; $a ^= (zeroFill($c,13));
  $b -= $c; $b -= $a; $b ^= ($a<<8);
  $c -= $a; $c -= $b; $c ^= (zeroFill($b,13));
  $a -= $b; $a -= $c; $a ^= (zeroFill($c,12));
  $b -= $c; $b -= $a; $b ^= ($a<<16);
  $c -= $a; $c -= $b; $c ^= (zeroFill($b,5));
  $a -= $b; $a -= $c; $a ^= (zeroFill($c,3));   
  $b -= $c; $b -= $a; $b ^= ($a<<10);
  $c -= $a; $c -= $b; $c ^= (zeroFill($b,15));
  return [$a, $b, $c];
}
```
Deprecated: Implicit conversion from float 1.596504209254618E+19 to int loses precision

**Comment by samsonasik** [comment]
It is really hard to understand the code and what the expected output. What `zeroFill()` function is? The code you provided itself got fatal error https://3v4l.org/sjAqq

I am going to close it. 

I suggest to make all things typed first (param, return type), then create things that not fatal error on the first place, and create a diff of the expected output of simple, clearer expectation.

On side note: Rector is not error handler, like issue https://github.com/rectorphp/rector/issues/7675, I think you can use phpstan job as the right tool to get there.
