### ISSUE TITLE
UnionTypesRector creates bool|false 

### ISSUE THREAD

**Issue by eugeniya-v** [rectorphp/rector#7821]
1. Redundant types are not allowed
2. False as a standalone type is allowed only in php8.2, but I'm using LevelSetList::UP_TO_PHP_81

@@ @@
      * @param bool|FALSE $user_id
      * @return array
      */
-    public function build_acl(bool $user_id = FALSE)
+    public function build_acl(bool|false $user_id = FALSE)

Applied rules:
 * UnionTypesRector

**Comment by samsonasik** [comment]
Reproduced at https://getrector.com/demo/cc7cc3b7-97db-4c62-b139-7ed08ea86669
Ref https://3v4l.org/XoZUa for `bool|false` as duplicate false type
