### ISSUE TITLE
UnionTypesRector introduce BC-break.

### ISSUE THREAD

**Issue by VincentLanglet** [rectorphp/rector#7823]
# Bug Report

Hi, multiple Rector rules are respecting BC policy.

I'm not sure about the whole Rector policy about BC, but I remember a similar issue was taken in account in order to avoid introducing BC break when adding typehints. https://github.com/rectorphp/rector/issues/7289

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/7bad0b3f-7963-47b9-8075-a15f577bf1b3

## Expected Behaviour

Rector shouldn't have return type (or param type) since the class is not final and the method is not private because this is breaking BC-policy.

**Comment by TomasVotruba** [comment]
Hi, 

you're right, this should not happen.

I wonder if Rector should even move the docblock to strict type declaration. 

It might be wrong in the first place. See: https://getrector.com/demo/54c2afae-2e7c-48ab-9744-b39b043c0b37

We already decoupled the param/return/property types to avoid docblock-based types, and only work with strict ones. We should follow the same direction here.
