### ISSUE TITLE
Incorrect behavior of RemoveDuplicatedArrayKeyRector

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7825]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a01101fa-8946-4d8f-806e-bcf715fa9949

```php
<?php

final class DemoFile
{
    public function run()
    {
        $index = 0;
        [
                 $index => 'Max',
                 ++$index => 'Max Ϙ',
                 ++$index => 'Last',
             ];
    }
}
```

### Responsible rules

* `RemoveDuplicatedArrayKeyRector`

## Expected Behavior

False positive, those keys are not the same

https://3v4l.org/tjmeN

**Comment by samsonasik** [comment]
Could you try provide a patch? Hint: exclude the following node as key:

- `PhpParser\Node\Expr\PostDec`
- `PhpParser\Node\Expr\PostInc`
- `PhpParser\Node\Expr\PreDec`
- `PhpParser\Node\Expr\PreInc`

**Comment by simPod** [comment]
@samsonasik not want to offend anyone but no, this still applies https://github.com/rectorphp/rector/issues/7319#issuecomment-1195444108
