### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivateMethodRector

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7826]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/40976257-dffb-460f-a6df-c53a10f860f5

```php
<?php

class Bar extends Foo {
}
abstract class Foo
{
    final public function bar(): void
    {
        if ($this instanceof Bar) {
            if ($this->foo()) {
            }
        }
    }

    private function foo(): bool
    {
		return true;
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior

`foo()` is used so should not be removed

**Comment by samsonasik** [comment]
You're using `SetList::DEAD_CODE` which collection of rules, try narrow down to rules half by half, and skip the rule that cause it, my guess is `RemoveDeadInstanceOfRector` or/and `RemoveAlwaysTrueIfConditionRector` which instanceof in abstract class will got falsy result.

**Comment by samsonasik** [comment]
You can change instanceof with is_a, see https://github.com/rectorphp/rector-src/pull/3091#issuecomment-1337146505

This is how used in AbstractRector as well https://github.com/rectorphp/rector-src/blob/4abcd4cde6f5e65232a6c14ef3fa88baba125e6b/src/Rector/AbstractRector.php#L375

**Comment by simPod** [comment]
I missed the notification.

`RemoveUnusedPrivateMethodRector` does that.

I can use `is_a` but it's still broken for `instanceof`. It effectively removes working code so there's a risk to someone who runs Rector and then misses such change.

`Foo` is not always `Bar`: https://getrector.com/demo/81a8193d-169b-457d-aa4f-b0c6090a5466
