### ISSUE TITLE
Symfony|EventDispatcher: Namespace change in service config to non-existing class

### ISSUE THREAD

**Issue by bicpi** [rectorphp/rector#7828]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.21             |
| PHP version | 8.1.13             |
| Symfony version | 6.2.7             |

Running Rector on a Symfony project cause this change in one of my service definitions in services.yml:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/301163/224327125-3b892429-3706-452c-a33a-96311072bc70.png">

The class `Symfony\Contracts\EventDispatcher\EventDispatcher` does not exist, the service cannot be loaded anymore.

I identified this line from the Symfony 4.3 set causing this change:
https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony43.php#L60

While it refers to a different class, the namespace prefix matches except of the last `Dispatcher` part.

Rector config for this Symfony 6.2 projects has:

```
SymfonyLevelSetList::UP_TO_SYMFONY_62
```

## Minimal Symfony service config Code Causing Issue

```
my_event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
```

## Expected Behaviour

The service definition is not changed - or a valid change is made, if any available.

**Comment by bicpi** [comment]
Skipping the file to ignore the issue temporarily does not work, it is changed nevertheless.

I was using either

```
    $rectorConfig->skip([
        RenameClassRector::class => [
            __DIR__.'/src/App/AppBundle/Resources/config/services.yml',
    ]);
```

Or with broader scope:

```
    $rectorConfig->skip([
        __DIR__.'/src/App/AppBundle/Resources/config/services.yml',
    ]);
```

**Comment by samsonasik** [comment]
You're using level set list, which may cause multiple level change from setlist from symfony 2.5 to 6.2 as the definition config is different with the changed diff.

You may need to check list by set list:

```php
use Rector\Symfony\Set\SymfonySetList;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    // ...
    $rectorConfig->sets([
        SymfonySetList::SYMFONY_25,
    ]);
};
```

until found the issue that cause it, and if you found a way to fix it, that will be great with PR for it 👍

**Comment by TomasVotruba** [comment]
Closing as related to the "up to set" conventions.

The best practise to upgrade is to use set level by level, and only use the "up to set" after your whole migration is finished. That way you will separate upgrade part and keeping the quality part.
