### ISSUE TITLE
Incorrect behavior of RemoveJustPropertyFetchRector - PHP Error Undefined Variable

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7831]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/f3235b55-796a-4828-af9d-5cbe0925fdc8

```php
<?php

final class DemoFile
{
    public function run( $arg )
    {
        $line = $arg->line;
        $total = $line->amount;
        $arg->line = $line;

        return $total;
    }
}
```

### Responsible rules

* `RemoveJustPropertyFetchRector`

## Expected Behavior

Not completely remove the variable and break the code (this is a pseudo example, in reality $line is adjusted before reassignment, but same issue)

I didn't create a test, because there is a 2nd, even worse case, which probably needs to be handled separately:
https://getrector.com/demo/951c5daa-d273-4d36-833c-a456871054ce

```php
<?php

final class DemoFile
{
    public function run( $arg, $foo )
    {
        $line = $arg->line;
        $total = $line->amount;
        $line->amount = $foo;
        $arg->line = $line;

        return $total;
    }
}
```

Since $line->amount is assigned, this rector shouldn't change this whatsoever (since not only is removing the variable wrong, but also when it wouldn't remove that variable and just assign $arg->line it would be completely wrong too)

**Comment by samsonasik** [comment]
Could you try provide a patch? Hint: skip variable used as property fetch in next stmt, thank you.
