### ISSUE TITLE
Parse error: syntax error, unexpected token "match"

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#7832]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.15.21 (invoke `vendor/bin/rector --version`)             |

the rector release contains a vendor lib `triun/longest-common-substring` which contains a class named `Match`.
since php 8 `match` is a reserved keyword and therefore doesn't allow such classes

https://3v4l.org/Ab3ic

<img width="1006" alt="grafik" src="https://user-images.githubusercontent.com/120441/224945123-135ce14a-5a78-4daa-a906-3cb6f4399df7.png">

I guess rector should not ship with a dependency which fatal errors on php8

**Comment by staabm** [comment]
it seems to be a dependency in https://github.com/rectorphp/rector-symfony/blob/ee203c96f524f2e1630d1bc45afe5f4bfb176011/composer.json#L10

**Comment by samsonasik** [comment]
it seems it used only in single service: https://github.com/rectorphp/rector-symfony/pull/343/files#diff-03d976f65e3da229866ac973aa59f5342ea8a01d31b3b1e622af1710a2851105 , equivalent code should be applied and remove `triun/longest-common-substring` dependency
