### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by AlexeyKosov** [rectorphp/rector#7833]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/804a2470-b92b-4e20-aece-770246e624ce

```php
<?php

/**
 * An example from 
 * https://symfony.com/doc/current/logging/channels_handlers.html#how-to-autowire-logger-channels
 */
class Foo {
    protected \Psr\Log\LoggerInterface $logger;

    public function __construct(\Psr\Log\LoggerInterface $fooBarLogger)
    {
        $this->logger = $fooBarLogger;
    }
}
```
turns into

```
<?php

class Foo {
    public function __construct(protected \Psr\Log\LoggerInterface $logger)
    {
    }
 }
```

The `$fooBarLogger` variable name disappeared, but it was important for the proper service autowiring in Symfony.

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

This change breaks the functionality that depends on the constructor var name, e.g. 
https://symfony.com/doc/current/logging/channels_handlers.html#how-to-autowire-logger-channels
since the original variable name gets lost.

Maybe it would worth adding a config option to disable promoting a property if the constructor var name and property name don't match?

**Comment by samsonasik** [comment]
that is expected for property to constructor promotion, you can skip the rule if you have the use case for that :)

**Comment by AlexeyKosov** [comment]
@samsonasik No, that would be expected if the variable names matched, but in this case, I would expect the rule to skip promoting the property. And I meant it would be great to add the ability to skip the rule **only** for such cases (name mismatch) but still use it for all other cases. That's what rule configuration is supposed to be for, isn't it?

**Comment by samsonasik** [comment]
Ok 👍 , re-open, feel free to create PR to make it configurable, make it implements `AllowEmptyConfigurableRectorInterface`

**Comment by TomasVotruba** [comment]
We've seen this reports before. Basically this is saint defaults. We could skip the cases if param and property have different names, and that would work for named cases like Symfony one. But it would also disable all the automatic upgrade for all the other cases, which is vast majority. So it would disable the point of rule in it's core.

Instead those cases should be alligned in Symfony configs first, then run Rector rule to upgrade.

Thanks for understanding :+1:
