### ISSUE TITLE
File passes after config cache when it should fail because of cache

### ISSUE THREAD

**Issue by jackbentley** [rectorphp/rector#7835]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 5db390cb7b67d3537acc34d3eabb04de1ef4b35a             |

If a file has been cached with a different config/ruleset, it will still pass when the ruleset changes even though the file should not pass.

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/da1a6029-6842-4ddb-a7fd-1be936e2cc80

Using this example file:

```php
<?php

final class DemoFile
{
    public function run()
    {
        return array();
    }
}
```

and this config:

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Php54\Rector\Array_\LongArrayToShortArrayRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_53,
    ]);
};
```

1. Run with the given config - ensure cache is created
2. Change config to be `UP_TO_PHP_54`
3. Re-run 
4. Notice no files changed
5. Re-run with `--cache-clear`
6. Notice 1 files changed

## Expected Behaviour

All cache should be invalidated upon config change.

PHPStan also invalidates cache on any config change and more https://phpstan.org/user-guide/result-cache

**Comment by jackbentley** [comment]
`0.11.5` is the example in your issue template.

I'm running 5db390cb7b67d3537acc34d3eabb04de1ef4b35a which is `0.15.21`.

**Comment by samsonasik** [comment]
I see, the issue is on`ChangedFilesDetector::invalidateCacheIfConfigurationChanged()`

https://github.com/rectorphp/rector-src/blob/c240c69f45c29685eeace5ad0737ef049dff5211/packages/Caching/Detector/ChangedFilesDetector.php#L121-L133

when the old data key still null, it should clear immediatelly so on next execution it can save.

```diff
    private function invalidateCacheIfConfigurationChanged(string $key, string $configurationHash): void
    {
        $oldCachedValue = $this->cache->load($key, CacheKey::CONFIGURATION_HASH_KEY);
-        if ($oldCachedValue === null) {
-            return;
-        }

        if ($oldCachedValue === $configurationHash) {
            return;
        }

        // should be unique per getcwd()
        $this->clear();
    }
```

somehow resolve it on my side, could you verify it?

**Comment by samsonasik** [comment]
On first run, `--clear-cache` is needed, then change to `LevelSetList::UP_TO_PHP_54` and run again, then back to `LevelSetList::UP_TO_PHP_53` and run, then back to `LevelSetList::UP_TO_PHP_54` on each run.

**Comment by jackbentley** [comment]
Ah, I see. It's still picking up the old cache key because it's already in the cache for me. Yes, that fix seems to work 👍
