### ISSUE TITLE
Incorrect behavior of EregToPregMatchRector

### ISSUE THREAD

**Issue by scottybcoder** [rectorphp/rector#7836]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/599714ec-8558-41c8-a4ce-54c0817d1da5

```php
<?php

if (extension_loaded('zlib')) {
      		$do_gzip_compress = true;
      		ob_start(array('ob_gzhandler',5));
      		ob_implicit_flush(0);
      		if (ereg("MSIE", $_SERVER['HTTP_USER_AGENT'])) {
				header('Content-Encoding: gzip');
      		}
    	}
```

### Responsible rules

* `EregToPregMatchRector`

## Expected Behavior

I am running PHP 8.2 - php-fpm - fastcgi

When i run 
vendor/bin/rector process --dry-run

On my server it does not refactor ereg or anything for that matter it merely says OK Rector is done and it does not see anything to change.

If I check with PHPStan it sees what is wrong...
vendor/bin/phpstan analyse ./mainfile.php

 ------ ---------------------------------------------------------------------
  Line   mainfile.php
 ------ ---------------------------------------------------------------------
  88     Function ereg not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  151    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  152    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  153    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  154    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  155    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  156    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  157    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  158    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  159    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  160    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  161    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  162    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  163    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  164    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  171    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  172    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  173    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  174    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  175    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  176    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  177    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  178    Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  205    Function sql_connect not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  475    Function OpenTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  477    Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  509    Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  621    Function OpenTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  627    Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  630    Function OpenTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  634    Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  637    Function OpenTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  643    Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  646    Function OpenTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  652    Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  655    Function OpenTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  661    Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  720    Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  747    Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  771    Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  780    Undefined variable: $querylang
  826    Undefined variable: $userrow
  858    Undefined variable: $CensorList
  862    Function eregi_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  866    Function eregi_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  870    Function eregi_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  934    Function eregi_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  936    Function eregi_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  938    Function eregi_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  940    Function eregi_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  943    Function ereg not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  943    Undefined variable: $reg
  944    Undefined variable: $reg
  945    Undefined variable: $reg
  946    Undefined variable: $reg
  946    Undefined variable: $reg
  947    Undefined variable: $reg
  949    Undefined variable: $reg
  950    Undefined variable: $reg
  953    Undefined variable: $reg
  1070   Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1090   Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1120   Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1134   Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1172   Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1194   Function ereg_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1195   Function ereg_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1196   Function ereg_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1197   Function ereg_replace not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1204   Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1228   Function themesidebox not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1258   Function ereg not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1258   Undefined variable: $date
  1259   Undefined variable: $date
  1259   Undefined variable: $date
  1259   Undefined variable: $date
  1260   Undefined variable: $date
  1260   Undefined variable: $date
  1260   Undefined variable: $date
  1260   Undefined variable: $date
  1297   Function OpenTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1299   Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1369   Undefined variable: $ThemeSelSave
  1394   Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1395   Function OpenTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1397   Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1525   Call to function unset() contains undefined variable $location.
  1539   Undefined variable: $location
  1540   Call to function unset() contains undefined variable $location.
  1545   Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1546   Function eregi not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1570   Function Opentable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  1577   Function CloseTable not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ ---------------------------------------------------------------------

Rector should do exactly what it does on your Try Rector  - It refactors with the exact setting I have on my server.

**Comment by samsonasik** [comment]
Please provide reproducible test case or repository (better with github action running), thank you.

**Comment by scottybcoder** [comment]
Simple shit right here, Stan checks the file creates the cache and Rector uses the cache to refactor. If Stan sees it and Rector does not then it is a cache issue. More than likely a shared VPS running PHP-FPM (fast-cgi) that uses **sys_get_temp_dir()** in a different fashion. Systems that are Virtual Private Servers  or shared host domain if you will, when more than one domain is setup will not allow scripts to use the mkdir() command. 

A PHP bug causes this when using sys_get_temp_dir() to set the paths for vendor scripts that need to make directories.

In this case Stan was able to read the file in question but more than likely did not create cache...

Nobody listens I have seen this problem over and over get ignored. Not Cool

**The fix is to create this function in vendor/composer/autoload_real.php**

**function sys_get_local_temp_dir(){
   $CachePath = __DIR__;
 return $CachePath;
}**

And then have a script globally replace **sys_get_temp_dir()** with **sys_get_local_temp_dir()** I see Nette has the same issue on php-fpm servers as well.

Out of all 3 Nette, Rector, and Stan only one is able to create directories and cache on a system running php-fpm with multiple domains and that is because it uses __DIR__ instead of get_sys_temp_dir(); It hasnt been fixed because someone could not reproduce the error? Horse Shit

**Comment by samsonasik** [comment]
You can configure cache class and cache dir for each prohect for that https://getrector.com/documentation/cache-in-ci

**Comment by samsonasik** [comment]
Beside on cache dir, the issue is probably the hard code usage of `sys_get_temp_dir()` on `PHPStanServicesFactory`

https://github.com/rectorphp/rector-src/blob/4abcd4cde6f5e65232a6c14ef3fa88baba125e6b/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php#L53

The possible solution is to create `container_cache` config to be configurable and used in `PHPStanServicesFactory`.

Duplicate with https://github.com/rectorphp/rector/issues/7700
