### ISSUE TITLE
Rector removes leading spaces before <?php endif; ?>

### ISSUE THREAD

**Issue by bigahuna** [rectorphp/rector#7841]
# Question

I use Rector 0.15.21, php 8.1.16 and the sets SetList::CODE_QUALITY and SetList::PHP_81

If I run rector on a file that contains the following structure or something similar:

``` 
<div>
    <h4>
        List of users
    </h4>
    <ul>
        <?php foreach ($users as $user): ?>
        <li>
            <?= $user['name'] ?>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
```

Rector always want's to remove the leading space before  `<?php endforeach; ?>` and shows a message similar to this

``` 
-            <?php endforeach; ?>
+<?php endforeach; ?> 
``` 

<img width="252" alt="endforeach" src="https://user-images.githubusercontent.com/13297945/225661283-53330ff4-ebd3-4a94-b13b-ca4b5fe0e1c4.png">

How can I disable this behaviour? Indentation is done by spaces, no tabs. 

It is the same behaviour for `<?php endif; ?>`. It always tells me to remove leading spaces before the endif or endforeach statement and therefore breaks existing indentation on the related files.

Regards
Mike

**Comment by bigahuna** [comment]
Thanks for the answer. I'm now able to reproduce it with all testet rector versions (even with the dev.main.

Just add a commented echo before the closing endforeach; like this:

https://getrector.com/demo/91b8fdfe-9828-47f9-8225-a94b4068df4d

``` 
<div>
    <h4>
        List of users
    </h4>
    <ul>
        <?php foreach ($users as $user): ?>
        <li>
            <?php 
            	echo $user['name'];
            	// echo "laskdjflaksdfjlsjf";
            ?>
        </li>
        <?php endforeach; ?>
    </ul>
</div> ```

Then you will get a change that removes the leading spaces.

<img width="434" alt="rector" src="https://user-images.githubusercontent.com/13297945/225738638-e8add49d-1799-4253-9af3-546cb43e1950.png">

Regards and thanks for all your work. Rector is a really helpful and appreciated tool that we use a lot. If I can help in any way, please let me know.

**Comment by samsonasik** [comment]
It seems the regex for open tag spaced regex need improvement for this, could you create fixture PR to: `e2e/plain-views/src` on `rector-src` 

https://github.com/rectorphp/rector-src/tree/main/e2e/plain-views/src

then, try run:

```
cd e2e/plain-views
composer install
php ../e2eTestRunner.php
```

Feel free to provide solution as well to cover it, it should be a regex handling on `PhpFileProcessor`

https://github.com/rectorphp/rector-src/blob/e1dd98dc51c214a743fe1785fd264d2ea27efd72/src/Application/FileProcessor/PhpFileProcessor.php#L34

Thank you.
