### ISSUE TITLE
cleanup release vendor dir

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#7842]
# Feature Request

the rector release contains a bunch of not-release relevant files from dependencies within its prefixed inner-`vendor/` dir

Examples:

<img width="329" alt="grafik" src="https://user-images.githubusercontent.com/120441/225761581-22f4f9ea-4cb2-43e4-8fbd-b595ecc4383e.png">

I think there are at least some
- doc
- docs
- tests
- examples
- templates

folders, which should be stripped while the release is build.

something like these bash commands would work:
```
            find vendor -name doc -type d -exec rm -r {} +
            find vendor -name docs -type d -exec rm -r {} +
            find vendor -name tests -type d -exec rm -r {} +
            find vendor -name examples -type d -exec rm -r {} +
            find vendor -name templates -type d -exec rm -r {} +
```

this would reduce filesize/filecount and reduce therefore installation and download/upload time via composer etc

**Comment by samsonasik** [comment]
`templates` is used for:

- init command https://getrector.com/documentation
- setup-ci command https://getrector.com/blog/new-setup-ci-command-to-let-rector-work-for-you

The left over directories can be removed from build ci https://github.com/rectorphp/rector-src/blob/e11572a6f1004d905766ae88ee7ce8f667009007/.github/workflows/build_scoped_rector.yaml#L61

**Comment by samsonasik** [comment]
docs directory also place for rules list overview so used:

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md

**Comment by staabm** [comment]
to clarify: the mentioned folders are useful in the main repo on github, but they should not be contained within the rector installation in a local project.

people don't search for docs in the local vendor/ usually and all files cointained in a release need to be downloaded/copied over hundreds and thousands of times in CI builds, deployments, dev-environments etc

**Comment by staabm** [comment]
another question. is 

- symplify/rule-doc-generator-contracts
- tracy/tracy

actually a dev-dependency and is not required within the final release?

**Comment by samsonasik** [comment]
tracy is used to be able to debug, see https://github.com/rectorphp/rector-src/pull/3354

**Comment by samsonasik** [comment]
rule doc generator implements contract, used to define rule example, the one that need to be required probably https://github.com/symplify/rule-doc-generator

**Comment by samsonasik** [comment]
Removing docs on installation only will require another process: post-install or pre-install

or register to .gitattributes

**Comment by stof** [comment]
> or register to .gitattributes

that's the way it should be done, to avoid downloading them (and avoiding the need to turn the package into a composer plugin to be able to run some post-install logic)

**Comment by TomasVotruba** [comment]
Feel free to send PR to handle this :+1:

**Comment by TomasVotruba** [comment]
Closing as accepted to avoid issue staling :+1:  Thanks for the suggestions and PRs are still welcomed :100:
