### ISSUE TITLE
Infinite loop/timeout DowngradePhp73JsonConstRector / DowngradeNullCoalescingOperatorRector

### ISSUE THREAD

**Issue by defunctl** [rectorphp/rector#7843]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d8a840ee-144a-42a2-a14a-bdae1557a8ad

```php
<?php

final class DemoFile
{
    public function run(?int $flags = null)
    {
        $flags ??= JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_PRESERVE_ZERO_FRACTION | JSON_THROW_ON_ERROR;
        
        json_encode([], $flags);
    }
}
```

### Responsible rules

* `DowngradeNullCoalescingOperatorRector`
* `DowngradePhp73JsonConstRector`

## Expected Behavior

It should not timeout and complete with:

```php
$flags = $flags ?? JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_PRESERVE_ZERO_FRACTION;
```

**Comment by samsonasik** [comment]
The bug seems on `JsonConstCleaner::hasDefinedCheck()` 

https://github.com/rectorphp/rector-downgrade-php/blob/b7d84923a099e4cf8cba027dcb447580e345d3e3/rules/DowngradePhp72/NodeManipulator/JsonConstCleaner.php#L41-L48
