### ISSUE TITLE
Indentation change in mixed HTML/PHP file that's unaffected by rule

### ISSUE THREAD

**Issue by schlndh** [rectorphp/rector#7845]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | [e11572](https://github.com/rectorphp/rector-src/commit/e11572) / v0.15.21            |

I tried rector on a project and I noticed that it made unnecessary indentation changes in a few mixed HTML/PHP files that were otherwise unaffected by the rules I applied. It's not a big deal for me (it only affected about 10-20 files out of a few thousand), just slightly annoying.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/98b16ff4-f832-4041-8e37-896e4575ce16

The cause seems to be the comment just before `?>`. If I replace it with a statement (e.g. `$v = 1;`), the it works correctly.

## Expected Behaviour

The file should remain as is.

**Comment by samsonasik** [comment]
It seems the regex for open tag spaced regex need improvement for this, could you create fixture PR to: `e2e/plain-views/src` on `rector-src` 

https://github.com/rectorphp/rector-src/tree/main/e2e/plain-views/src

then, try run:

```
cd e2e/plain-views
composer install
php ../e2eTestRunner.php
```

Feel free to provide solution as well to cover it, it should be a regex handling on `PhpFileProcessor`

https://github.com/rectorphp/rector-src/blob/e1dd98dc51c214a743fe1785fd264d2ea27efd72/src/Application/FileProcessor/PhpFileProcessor.php#L34

Thank you.
