### ISSUE TITLE
stuck on some code

### ISSUE THREAD

**Issue by pilot114** [rectorphp/rector#7846]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.17  |
| PHP version | 8.1.15 |

Code check takes an infinitely long time, even with the --dry-run option

## Minimal PHP Code Causing Issue

https://getrector.com/demo/73b798f8-7b03-48a7-a158-f29d96a7ae10

## Expected Behaviour

Expected any output to the console in a reasonable amount of time (for example, a message about recursion)

**Comment by samsonasik** [comment]
Reproduced by use single rule: `ReturnTypeFromStrictTypedCallRector` https://getrector.com/demo/c614233f-25d7-4eae-b00e-75d9168e56f9

**Comment by samsonasik** [comment]
The bug seems on recursive call called by 

```php
            $returnedExprType = $this->correctWithNestedType($returnedExprType, $localReturnNode, $functionLike);
```

https://github.com/rectorphp/rector-src/blob/e1dd98dc51c214a743fe1785fd264d2ea27efd72/rules/TypeDeclaration/TypeInferer/ReturnTypeInferer/ReturnedNodesReturnTypeInfererTypeInferer.php#L71


which call:

```php
return $this->inferFunctionLike($classMethod);
```

internally.
