### ISSUE TITLE
[DX] Improve node structure - remove next-node/prev-node

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#7849]
Remove next-node: https://github.com/search?q=repo%3Arectorphp%2Frector-src%20AttributeKey%3A%3ANEXT_NODE&type=code

**Comment by samsonasik** [comment]
For note, I think removing NEXT_NODE and/or PREVIOUS_NODE will require major release as it used in rector extensions, see in drupal-rector as example https://github.com/palantirnet/drupal-rector/blob/09d3dc6a422483de4c7c9b17692a48252b6b0af3/src/Rector/Deprecation/EntityManagerRector.php#L96

**Comment by TomasVotruba** [comment]
First, we have to clean our rules from these attribute. That will take some time :)

**Comment by samsonasik** [comment]
Ref for original issue comment to possibly need different visitor for specific use case https://github.com/rectorphp/rector/issues/7088#issuecomment-1087816689

**Comment by TomasVotruba** [comment]
> Ref for original issue comment to possibly need different visitor for specific use case https://github.com/rectorphp/rector/issues/7088#issuecomment-1087816689

In some cases yes :+1:

**Comment by samsonasik** [comment]
The `findFirstNext()` and `findfirstPrevious()` from `BetterNodeFinder` are hidden that use both prev and next usage

**Comment by TomasVotruba** [comment]
This part is now done for use. The node tree is shiny clean :partying_face:

**Comment by staabm** [comment]
🏎️
