### ISSUE TITLE
sa

### ISSUE THREAD

**Issue by mustafaeskin** [rectorphp/rector#7851]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/7d0aec25-9354-4269-bd5a-2893dcddee06

```php
<?php

final class DemoFile
{
    public function run()
    {
        return 5;

        // we never get here
        return 10;
    }
}
```

### Responsible rules

* `RemoveUnreachableStatementRector`

**Comment by samsonasik** [comment]
that's expected, code after return is unreachable.
