### ISSUE TITLE
Roadmap to Rector 1.0 :tada: 

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#7854]
## 1. Remove next/prev/stmts/node relations :heavy_check_mark: 

* [x] https://github.com/rectorphp/rector/issues/7849

<br>

## 2. Separate `@api` public methods from another packages

<br>

## 3. Remove global `Scope` attribute and pass it where needed

<br>

## 4. Remove removeNode() and addNodeBefore/After() :heavy_check_mark: 

* these methods are like scratching by your left foot behind your right ear - messy for no reason
* instead use direct node removal right in the rule
* same for adding nodes - return multiple nodes to return 

<br>

## 5. Remove cyclic dependencies in with `#[Required]`

* the cyclic dependency suggests design smell, that should be refactored to clear dependency tree or adjust the rules

<br>

## 6.  Remove HTML+PHP mix :heavy_check_mark: 

The HTML and PHP mix is not covered by php-parser well. That's why lot of refactoring handled by Rector and cut in the middle and crash in a weird mess, duplicated lines, open-tags, new lines in new places or missing part of PHP code. We've tried to improve this part, but untill it's included in php-parser itself, we only patch new wounds. To avoid breaking code in unexpected spaces and make Rector reliable, we'll avoid any HTML+PHP code mix in next version. Separate these files to template code and PHP file, to enjoy the full power of Rector.

<br>

**Comment by samsonasik** [comment]
Added new public method to resolve next or prev node:

- https://github.com/rectorphp/rector-src/pull/3896

**Comment by Wirone** [comment]
Just small technical question: wouldn't it be better to create milestone that would group all the issues required for Rector 1.0 in one place? This would be better than todo list within this issue 🙂.

**Comment by mbrodala** [comment]
Congratulations to the release of Rector 1.0.0! :tada:

**Comment by Wirone** [comment]
Congrats 🥳! What's weird is that I did not get any notification about it, even though I am subscribed on releases 🤔. And there's no release notes, so I think it's not completely official 😉.

**Comment by samsonasik** [comment]
@Wirone the release is not published yet, just tagged.

**Comment by penyaskito** [comment]
Congrats on the milestone!

I got a renovate PR, so after reading https://github.com/rectorphp/rector/issues/7854#issuecomment-1931591594  wondering if that wasn't supposed to happen?

**Comment by mbrodala** [comment]
Good question, the [Releases](https://github.com/rectorphp/rector/releases) page also misses the previous [0.19.8](https://github.com/rectorphp/rector/releases/tag/0.19.8) currently:

![image](https://github.com/rectorphp/rector/assets/5037116/de79add6-ee62-49d9-a409-1dbd4b9b30b7)

**Comment by Wirone** [comment]
> @Wirone the release is not published yet, just tagged.

Actually [_it's published_](https://packagist.org/packages/rector/rector#1.0.0), only does not have release notes 😉.

**Comment by TomasVotruba** [comment]
Closing as all planned features are done. Live release has beed done yesterday on Laracon Amsterdam :tada:  

Release notes are coming this week 😉
