### ISSUE TITLE
Incorrect behavior of NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by yguedidi** [rectorphp/rector#7855]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/b5d6c3b4-141b-4c6a-8e69-9c65d0f426d7

```php
<?php

trait MyTrait
{
    protected function getString(): string
    {
        return 'foo';
    }
    
    protected function useString(): bool
    {
        $string = $this->getString();
        
        return preg_match('/abc/', $preparedUrl, $match);
    }
}
```

### Responsible rules

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

As the native return type is string, Rector shouldn't do any change in this case

**Comment by samsonasik** [comment]
That's expected as due to trait usage

**Comment by RobinDev** [comment]
Without the `@RectorIgnore` how did you manage it to avoid static analysis and rector doing opposite job ? Are you skipping trait ?
