### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector

### ISSUE THREAD

**Issue by yguedidi** [rectorphp/rector#7856]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version: [0f0b93](https://github.com/rectorphp/rector-src/commit/0f0b93) - released at 2023-03-27 15:06             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/03e903e4-92b0-445a-9066-ff52a95ae876

```php
final class DemoFile
{
    private string|null $foo;
    
    public function _construct(string $string)
    {
        $this->foo = $string;
    }
    
    public function do(): void
    {
        $bar = '';
        
        if ($this->foo !== null) {
            $bar .= $this->foo;
        }
    }
}
```

## Expected Behaviour

The `$foo` property should be marked as readonly

**Comment by samsonasik** [comment]
For note: you wrote `_construct` instead of `__construct` which not equal.

The feature still valid :)

**Comment by samsonasik** [comment]
It seems skipped if not used in assign expr, if assign other than in `__construct` commented, it is work as expected https://getrector.com/demo/9a116247-c783-4d99-913e-74ee7a63ca55
