### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector with conditional assignment in constructor

### ISSUE THREAD

**Issue by yguedidi** [rectorphp/rector#7857]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version: [0f0b93](https://github.com/rectorphp/rector-src/commit/0f0b93) - released at 2023-03-27 15:06            |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/674bc158-9f21-481b-9c78-4ed12915a9f8

```php
final class DemoFile
{
    private string $env;
    
    public function __construct(bool $sandbox)
    {
        if ($sandbox) {
            $this->env = 'sandbox';
        } else {
            $this->env = 'prod';
        }
    }
}
```

## Expected Behaviour

The `$env` property should be marked as readonly

**Comment by samsonasik** [comment]
I am going to close this feature request as if else elseif assign will require a flag to verify inside and that will be too complex to handle, and will be buggy.

Thank you for understanding.
