### ISSUE TITLE
Third parameter in preg_match

### ISSUE THREAD

**Issue by tavy315** [rectorphp/rector#786]
Small question about third parameter in preg_match: documentation on php.net says that if present, it will return an array, so I was hust wondering why I get the suggestion to add is_array?

```
    ---------- begin diff ----------
--- Original
+++ New
@@ -23,7 +23,7 @@
     {
         \preg_match('#\d\.\d(\.\d)?(-?\S*)?#i', $version, $matches);

-        if (\count($matches) > 0) {
+        if ((is_array($matches) || $matches instanceof \Countable ? \count($matches) : 0) > 0) {
             $this->version = (string) $matches[0];
         }
     }
    ----------- end diff -----------

Applied rectors:

 * Rector\Php\Rector\FuncCall\CountOnNullRector
```

**Comment by carusogabriel** [comment]
@tavy315 Thanks for this bug report.

I think the `CountOnNullRector` need to be redesigned. It was created to update all `count` call, but, yes, some cases aren't necessary.

**Comment by TomasVotruba** [comment]
I suppose it's a bug in PHPStan analyzer, since we use it here to determine array or not.

**Comment by TomasVotruba** [comment]
Confirmed, see: https://phpstan.org/r/a882c0df-43b9-4d13-aa8f-2bc4fc0aebfd

**Comment by TomasVotruba** [comment]
@tavy315 Could you send failing test for `CountOnNullRectorTest` so we have this covered for the future?

**Comment by carusogabriel** [comment]
@TomasVotruba Also, we need to report this to PHPStan itself :)

**Comment by TomasVotruba** [comment]
@carusogabriel Please handle the PHPStan report as you work on it more closely than I do.

I've handled the fix for `preg_match` and `preg_match_all` cases in #816

**Comment by staabm** [comment]
I got this very same problem with a rector version installed today

run `rector process redaxo --level php71`
on https://github.com/redaxo/redaxo and you will get suggested changes like

![image](https://user-images.githubusercontent.com/120441/62420577-d0711e00-b694-11e9-8718-891fed5ffbdf.png)

**Comment by TomasVotruba** [comment]
Please add failing test case, so we can verfy it and fix it
