### ISSUE TITLE
Installing reactor and running `vendor/bin/rector process src` produces no output

### ISSUE THREAD

**Issue by somethingconcon** [rectorphp/rector#7861]
# Question
[for context]
My codebase currently runs on 7.3 and I'm looking to get up the upgrade chain as far as possible. To install the latest rector package I upgraded my local development environment to 8.3 and ran composer to install the rector package.
[the problem]
After installing rector running both `vendor/bin/rector process src --dry-run` and `vendor/bin/rector process src` do not change any files and produce no errors. The finish text of `[OK] Rector is done!` is visible in the green banner but no updates have been made.

**Comment by samsonasik** [comment]
I can't reproduce, please provide reproducible github repo for that, better with github action running. Thank you.

**Comment by somethingconcon** [comment]
Ok I have figured out this issue and it is not rector. Apologies. Closing.
