### ISSUE TITLE
Incorrect behavior of ArraySpreadInsteadOfArrayMergeRector

### ISSUE THREAD

**Issue by yguedidi** [rectorphp/rector#7865]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/33491afb-b0b3-4fac-aeb3-6354db4ccabd

```php
<?php

final class DemoFile
{
    public function run()
    {
        $array = ['foo' => 'bar'];
        
        return array_merge(['baz' => 'xxx'], $array);
    }
}
```

### Responsible rules

* `ArraySpreadInsteadOfArrayMergeRector`

## Expected Behavior

In this case shouldn't it become more: `return ['baz' => 'xxx', ...$array];`?

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by yguedidi** [comment]
Wanted to validate that ou agree with the expected result :)
Sure I'll create the failing test case

**Comment by yguedidi** [comment]
Done
