### ISSUE TITLE
Best way to extract code to other file

### ISSUE THREAD

**Issue by timmipetit** [rectorphp/rector#7866]
# Question

What's the best way to extract some code to a different file in a custom Rector? Since Rector acts on a per-file basis, this seems to be kinda hard. If you wanna move stuff around within a file (class), you can simply match on class type and do your magic from there. Is something like that possible for inter-file stuff as well?

Our use case is that we have some routing info that we want to move, but only if the controller matches certain conditions. But the same could be applied to extract a function to a different class for example

**Comment by samsonasik** [comment]
You may looking for NeigbourClassLikePrinter, something like https://github.com/rectorphp/rector-phpunit/blob/dfeb67c1b2950de2dbc093ed187fb6559a4ddf21/src/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector.php#L119

**Comment by timmipetit** [comment]
That definitely looks interesting thanks! If I understand correctly, this only can be used to print new files/classes, and not to amend an existing one?

**Comment by samsonasik** [comment]
That's apply:

```php
        $addedFileWithContent = new AddedFileWithContent($fileDestination, $printedFileContent);
        $this->removedAndAddedFilesCollector->addAddedFile($addedFileWithContent);
```

so that will add file with content.
