### ISSUE TITLE
Use StrContainsRector in a php7 + polyfill codebase

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#7867]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. [0.15.23](https://github.com/rectorphp/rector/releases/tag/0.15.23)             |

I want to appy the `StrContainsRector` rector on a php7 codebase.
since my appplication will ship with a symfony polyfill the method is available at runtime.

in my rector config I use `$rectorConfig->phpVersion(70200);` to make sure rectors will not produce invalid code.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/ce3be4b4-a9c5-445f-8739-1e4954817021

vs.

https://getrector.com/demo/d62d920f-835c-4869-975f-0f51de3e97c1

## Expected Behaviour

I search for way which allows me to apply `StrContainsRector` in tandem with `$rectorConfig->phpVersion(70200);` as I don't want other rules produce invalid php7 output

**Comment by yguedidi** [comment]
For a one shot refactoring, you can force phpVersion at a higher one, and run rector with a config containing onlyStrContainsRector I guess

**Comment by yguedidi** [comment]
For more details, see that this rule is limited to versions supporting str_contains: https://github.com/rectorphp/rector-src/blob/main/rules/Php80/Rector/NotIdentical/StrContainsRector.php#L38
And that version is 8.0: https://github.com/rectorphp/rector-src/blob/main/src/ValueObject/PhpVersionFeature.php#L491
There is no polyfill-based detection AFAICT

**Comment by staabm** [comment]
[I will use cs-fixer for it](https://cs.symfony.com/doc/rules/alias/modernize_strpos.html), as it does not make assumptions about min-php-version, which works better for my use-case.

thank you

**Comment by luigifab** [comment]
An option to add functions provided by **symfony/polyfill-phpxy** with this configuration would be great!

```php
$rectorConfig->import(SetList::PHP_52);
$rectorConfig->import(SetList::PHP_53);
$rectorConfig->import(SetList::PHP_54);
$rectorConfig->import(SetList::PHP_55);
$rectorConfig->import(SetList::PHP_56);
$rectorConfig->import(SetList::PHP_70);
$rectorConfig->import(SetList::PHP_71);
$rectorConfig->import(SetList::PHP_72);
$rectorConfig->import(SetList::PHP_73);
$rectorConfig->import(SetList::PHP_74);
$rectorConfig->import(SetList::PHP_80);
$rectorConfig->import(SetList::PHP_81);
$rectorConfig->import(SetList::PHP_82);
$rectorConfig->import(SetList::PHP_83);
$rectorConfig->import(LevelSetList::UP_TO_PHP_72);
$rectorConfig->import(Something::SYMFONY_POLYFILL_PHP);
```

To update codebase with: `str_contains`, `str_starts_with`, ...

https://packagist.org/packages/symfony/polyfill-php72
https://packagist.org/packages/symfony/polyfill-php73
https://packagist.org/packages/symfony/polyfill-php74
https://packagist.org/packages/symfony/polyfill-php80
https://packagist.org/packages/symfony/polyfill-php81
https://packagist.org/packages/symfony/polyfill-php82
https://packagist.org/packages/symfony/polyfill-php83

**Comment by TomasVotruba** [comment]
@luigifab Instead of all the php sets, you can use single set with:

```php
$rectorConfig->import(LevelSetList::UP_TO_PHP_83);
````

As for the polyfill package - I like your suggestion! 
Could you propose a PR with adding this option to `\Rector\Core\Php\PhpVersionProvider`?

**Comment by luigifab** [comment]
The idea of my config, is to Rector my codebase to PHP 8.3 but by keeping compatibility with PHP 7.2 with composer polyfill. I will check how to add it for a PR.
