### ISSUE TITLE
FileProcessorInterface in 0.15

### ISSUE THREAD

**Issue by CheapHasz** [rectorphp/rector#7870]
# Question

Hi, up until v 0.13, setting a service implementing FileProcessorInterface to the container worked and processed whatever was in the FileProcessorInterface

But when launched with v0.15, the `process` command prompts a `No "rector.php" config found. Should we generate it for you?`

I looked for documentation, it seems that at some point a documentation existed for this topic (https://github.com/rectorphp/rector/issues/6464), but it seems to have been removed. Is there something I am missing, or any pointer on how to upgrade my code ?

**Comment by samsonasik** [comment]
You may looking for `NonPhpFileProcessor` https://github.com/rectorphp/rector-src/blob/f8e3c7b0644e4e106e18e3177bcd5eb110e9ab31/src/NonPhpFile/NonPhpFileProcessor.php

For Rector rule that use it, you can see example of `RenameClassNonPhpRector` https://github.com/rectorphp/rector-src/blob/f8e3c7b0644e4e106e18e3177bcd5eb110e9ab31/src/NonPhpFile/Rector/RenameClassNonPhpRector.php

**Comment by CheapHasz** [comment]
Okay, I am not quite sure what I did wrong before, it seems that simply making my old FileProcessorInterface extend Rector\Core\Contract\Rector\RectorInterface and adding it as a rule instead of a service in my config was enough to make it work.

Thanks a lot for the pointers anyway
