### ISSUE TITLE
NewlineAfterStatementRector configuration

### ISSUE THREAD

**Issue by rela589n** [rectorphp/rector#7871]
# Feature Request

The `NewlineAfterStatementRector` has a constant `STMTS_TO_HAVE_NEXT_NEWLINE`, which is used to define which statements to refactor and which not. It would make sense to make this rule configurable, so that we can skip running this rule for class constants for example. Currently, the only way to skip constants refactor is to completely skip the rule.

**Comment by samsonasik** [comment]
Handle new line is hard to cover, make it configurable will make possible bug report we never seen before. You can create your own custom rule for that, or completely skip it.
