### ISSUE TITLE
Keep `#[CoversClass]` attribute on method, and don't move it to class scope

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#7873]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/1e66b3b8-2897-46f9-ab93-ec9315d586c7

```php
<?php

namespace Tests\Foo;

use PHPUnit\Framework\TestCase;

final class FooTest extends TestCase
{
    /**
     * @test
     * @covers App\Foo
     **/
    public function testFoo()
    {
        self::assertTrue(true);
    }
}
```

### Responsible rules

* `CoversAnnotationWithValueToAttributeRector`

* `AnnotationToAttributeRector`

## Expected Behavior

This is the output from rector:

```php
<?php
 
namespace Tests\Foo;
 
use PHPUnit\Framework\TestCase;
 
#[\PHPUnit\Framework\Attributes\CoversClass(App\Foo::class)]
final class FooTest extends TestCase
{
    #[\PHPUnit\Framework\Attributes\Test]
    public function testFoo()
    {
        self::assertTrue(true);
    }
}
```

but correct would be, that the covers annotation is kept on the method:
```diff
<?php
 
namespace Tests\Foo;
 
use PHPUnit\Framework\TestCase;
 
-#[\PHPUnit\Framework\Attributes\CoversClass(App\Foo::class)]
final class FooTest extends TestCase
{
    #[\PHPUnit\Framework\Attributes\Test]
+   #[\PHPUnit\Framework\Attributes\CoversClass(App\Foo::class)]
    public function testFoo()
    {
        self::assertTrue(true);
    }
}
```

cc @localheinz @mvhirsch @silasjoisten

**Comment by staabm** [comment]
when `@covers` is used on class-level it should stay there, right?

**Comment by OskarStark** [comment]
Yes

**Comment by staabm** [comment]
@OskarStark @localheinz are we sure about the reported problem?

sbergmann just got in contact and [reported that Code Coverage attributes are only valid at the class-level](https://phpc.social/@sebastian/110207757343597799).
the source also defines this annotation for the class-level: https://github.com/sebastianbergmann/phpunit/blob/da707f3748773fbffd20289ae039e5e667d6b3a6/src/Framework/Attributes/CoversClass.php#L19

I am not sure the initial report was/is valid?

**Comment by OskarStark** [comment]
Not sure TBH

We used them for functional tests. Calling an endpoint which uses a dedicated filter class internally. So we marked this one test covering the dedicated filter class.

cc @mvhirsch

**Comment by gisostallenberg** [comment]
@OskarStark and @TomasVotruba I think this is wrong and @staabm  is right,

I get this error reported when running tests after rector applied rules:
```
An error occurred inside PHPUnit.
Message:  Attribute "PHPUnit\Framework\Attributes\CoversClass" cannot target method (allowed targets: class)
Location: /builds/flux-flow/flux-flow/vendor/phpunit/phpunit/src/Metadata/Parser/AttributeParser.php:334
```

Also see https://github.com/sebastianbergmann/phpunit/blob/13799e7402deb1913897a0982324b4db46f963a3/src/Framework/Attributes/CoversClass.php#L19

**Comment by TomasVotruba** [comment]
We'll need a failing test fixture in tests here. Could you send it?

**Comment by gisostallenberg** [comment]
WDYM? This: https://getrector.com/demo/bd7cac95-a89d-4778-b1af-4b6d30c6cfba?

As you can see [here](https://github.com/sebastianbergmann/phpunit/blob/13799e7402deb1913897a0982324b4db46f963a3/src/Framework/Attributes/CoversClass.php#L19) `CoversClass` is an attribute for `Attribute::TARGET_CLASS` and not for a method.

Can I provide anything more for this to make this sense?

**Comment by TomasVotruba** [comment]
Yes, now please create a PR to test here, so we have failing CI.
