### ISSUE TITLE
Error when running `vendor\bin\rector process --dry-run`

### ISSUE THREAD

**Issue by daschws** [rectorphp/rector#7880]
If you need more, let me know...

  Environment:

  Laravel Version - 10.7.1
  PHP Version - 8.2.0
  Composer Version - 2.5.5
  OS - Windows 11 Home, Version 22H2

Included files:

[err_onscreen.txt](https://github.com/rectorphp/rector/files/11244978/err_onscreen.txt)
[composer.txt](https://github.com/rectorphp/rector/files/11244979/composer.txt)
[err.txt](https://github.com/rectorphp/rector/files/11244980/err.txt)
[helpers.php.txt](https://github.com/rectorphp/rector/files/11244982/helpers.php.txt)
[ResetSettings.php.txt](https://github.com/rectorphp/rector/files/11244987/ResetSettings.php.txt)

**Comment by daschws** [comment]
I found the issues with the errors. Yay...

If it was an issue on my part, thanks for catchinig it!

I attached the file fixederrors.txt with the solutions I implemented.

If you need any other information, please, let me know.

[fixederrors.txt](https://github.com/rectorphp/rector/files/11255892/fixederrors.txt)

**Comment by TomasVotruba** [comment]
Glad you've solved it 👍
