### ISSUE TITLE
Feature: Rename class/namespace with backward compatibility

### ISSUE THREAD

**Issue by icanhazstring** [rectorphp/rector#7882]
# Feature Request

Already been mentioned on Twitter: https://twitter.com/icanhazstring/status/1647880436087943168
Just to get some more insights on how to approach :)

## The Problem
The problem I am trying to solve is to rename defined class/interface symbols in a library to fit the new namespace.
This happens during a transition e.g. from organizational units.

## Where to place
I saw there are some "Naming" rules from rector itself. But digging through them seems like that `Renaming` rule sets might not fit
into the description. As these rules appear to be targeting "using symbols" not changing defined ones.

Or it seems like a combination of `Renaming\Rector\Namespace_\RenameNamespaceRector` and `Renaming\Rector\Name\RenameClassRector`. Where we need to fixture out of we completely move a namespace from `old` to `new` or only rename a certain class (also while renaming the filename)

Any suggestions? :)

## Diff
The produced diff might be 

```diff
// baz.php

<?php 
-namespace Fu;
+namespace Bar;

class Baz {}
```

```diff
// backward-compatibility.php

+<?php
+if (!class_exists('Fu\Baz')) {
+    class_alias(\Bar\Baz::class, 'Fu\Baz');
+}
```

```diff
// composer.json
{
  ...
  autoload": {
+   "files": [
+     "backward-compatibility.php"
+   ]
  },

**Comment by TomasVotruba** [comment]
Hi, I think this would be possible, but it would require few custom rules. But I don't think it would be useful to wider community and should be part of core.

Ideal candidate for community package that would help package developers 👍
