### ISSUE TITLE
we need a custom rule

### ISSUE THREAD

**Issue by manibalan7012** [rectorphp/rector#7883]
We need one rector rule to do overcome method overriding problem. In below I will give a example check this and give a solution.

Before Applying rule:
 public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('Description of your rule', [new CodeSample(<<<'CODE_SAMPLE'
class Animal {
    public function move() {
        echo "The animal is moving." . PHP_EOL;
    }
}

class Dog extends Animal {
    public function move() {
        echo "The dog is running." . PHP_EOL;
    }
}

$animal = new Animal();
$dog = new Dog();

$animal->move();
$dog->move();

After applying the rule change like below code:
class Animal {
    public function move() {
        echo "The animal is moving." . PHP_EOL;
    }
}

class Dog extends Animal {
    public function move_Dog() {
        echo "The dog is running." . PHP_EOL;
    }
}

$animal = new Animal();
$dog = new Dog();

$animal->move();
$dog->move_Dog();

**Comment by TomasVotruba** [comment]
Hi, I'm not sure what you mean by this issue, but we handle an open source package issues and rules here.

To get a custom-made rule, reach our private project support: https://getrector.com/hire-team

Thanks :+1:
