### ISSUE TITLE
Fatal error: Uncaught PhpParser\Error: Cannot use DateTime as DateTime because the name is already in use on line 49 in /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NameContext.php:58

### ISSUE THREAD

**Issue by sterichards** [rectorphp/rector#7884]
# Question

This error keep appearing when using rectorphp to upgrade a Symfony project codebase from PHP 7.4 to 8.1

I have posted the full stack trace here - https://pastebin.com/PhuUKw5H

I've added `--debug` to the output and inspected the file that was being processed before the error and there is no mention of DateTime within that file

Struggling to understand how I can solve this issue

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by sterichards** [comment]
This was caused by my CMD + C the rector process when it appeared to have paused

And by doing this, it had created multiple `use DateTime` statements in some files

Everything seems OK now
