### ISSUE TITLE
Incorrect behavior of SwitchTrueToIfRector

### ISSUE THREAD

**Issue by pgr-dS** [rectorphp/rector#7885]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/4ea2ecee-99f7-474e-b74e-a2db47a1e1eb

```php
<?php

final class DemoFile
{
    public function run(int $int): string
    {
        $str = 'error';
        switch (true) {
            case $int === 0:
                $str = 'zero';
                break;
            case $int%2 === 1:
                $str = 'odd';
                break;
            case $int%2 === 0:
                $str = 'even';
                break;
        }

        return $str;
    }
}
```

### Responsible rules

* `SwitchTrueToIfRector`

## Expected Behavior

Rector should not move the `break;`s into the method code, either by constructing an if-else chain or skipping the `switch`.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by pgr-dS** [comment]
added failing test PR: https://github.com/rectorphp/rector-src/pull/3632

I decided to go with skipping `switch(true)` with `break;` in the cases for the test for now as a mixture of cases with and without `break;` is quickly going to get complex
