### ISSUE TITLE
What is the reason for pre-installed phpstan packages in vendor folder?

### ISSUE THREAD

**Issue by bubasuma** [rectorphp/rector#7888]
# Question
I am facing an issue after running composer update. 
The outer phpstan package (project-dir/vendor/phpstan) is conflicting with pre-installed phpstan packages (project-dir/vendor/rector/phpstan)

Here is the exception i am getting when running unit test

`_PHPStan_532094bc1\Nette\DI\ServiceCreationException: Service of type PHPStan\PhpDocParser\Parser\TypeParser: Unable to pass specified arguments to TypeParser::__construct().`

**Comment by samsonasik** [comment]
Rector using scoped vendor on purpose, if you found unsynchronized latest version of phpstan package, usually because of changed parameter or added new config of newer phpstan, new rector release is needed. 

I can't reproduce the error, could you create a simple reproduced repo for it? Thank you.

**Comment by jakubtobiasz** [comment]
Hello, I've spotted the same error in our https://github.com/Sylius/SyliusRector repository. The error exists only in `phpstan/phpstan:1.10.14`, on `1.10.13` everything works.

It might be related to this change [phpstan/phpstan-src@`1.10.13...1.10.14`#diff-e4b571e8dc](https://github.com/phpstan/phpstan-src/compare/1.10.13...1.10.14#diff-e4b571e8dcdf42219808e950c92c6335fe4e140e4b0b2d01bc5b41b2f25f717eR564-R565) (I'm guessing it based on the error), but no sure :/.

If you want to reproduce the error, just download `Sylius/SyliusRector` install dependencies and run `./vendor/bin/phpunit`.

**Comment by samsonasik** [comment]
Could you try latest `"rector/rector": "dev-main"` ?

if that works, then new rector release is needed

**Comment by jakubtobiasz** [comment]
@samsonasik checked, and it seems to work :).

**Comment by bubasuma** [comment]
@samsonasik thanks for this release. 
I am still confused though why `rector/rector` package has dependency on `phpstan/phpstan` if it already has it in its code base? this is causing composer to install `phpstan/phpstan` as a separate package.
