### ISSUE TITLE
Incorrect behavior of SingleInArrayToCompareRector

### ISSUE THREAD

**Issue by raoz** [rectorphp/rector#7893]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/001ae62c-7857-4ce2-b4c1-8be77fd37568

```php
<?php

final class DemoFile
{
    public function run()
    {
        $a = ['a', 'b'];
        echo in_array('a', [...$a]);
    }
}
```

### Responsible rules

* `SingleInArrayToCompareRector`

## Expected Behavior
Either no change or
```php
<?php

final class DemoFile
{
    public function run()
    {
        $a = ['a', 'b'];
        echo in_array('a', $a);
    }
}
```

**Comment by samsonasik** [comment]
It should be skipped, should can be checked by if there is item is variadic, could you try provide a patch? Thank you.
