### ISSUE TITLE
Unexpected Removal of Code when trying to update part of Wordpress Code

### ISSUE THREAD

**Issue by glumb** [rectorphp/rector#7894]
# Question
I was trying out rector to update parts of a Wordpress application, but rector removed some of the necessary logic.

This is my config: 

```php
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/web',
    ]);

    // register a single rule
    // $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    // define sets of rules
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_82
    ]);
};
```
This is the change it made:
<img width="1757" alt="image" src="https://user-images.githubusercontent.com/3062564/233486117-f9caf3f1-4e65-412d-b37c-56b020b46a5f.png">

By removing all arguments from the àpply_filters`method the code does ofc not work anymore. What is causing this behavior?

**Comment by samsonasik** [comment]
`apply_filter()` function seems not autoloaded, or too late loaded, you can read the doc for how to solve it https://getrector.com/documentation/static-reflection-and-autoload

**Comment by samsonasik** [comment]
I am going to close it as the solution provided.

**Comment by chrillep** [comment]
@glumb please provide the code that fixes this

**Comment by samsonasik** [comment]
The solution is provided, you need to setup wordpress autoload correctly. Again, read the docs, slowly.
