### ISSUE TITLE
Incorrect behavior of SimplifyForeachToArrayFilterRector

### ISSUE THREAD

**Issue by raoz** [rectorphp/rector#7895]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/0c85f61d-5dab-46fb-ae9e-be5c32d5a3f3

```php
<?php
class Test {
    public function __construct(
    public int $a,
    public ?int $b) {       
    }
}

final class DemoFile
{
    public function run()
    {
        $a = new Test(3, null);
        
        $arr = [];
        foreach($a as $k => $v) {
			if($v !== null) {
				$arr[$k] = $v;
            }
        }
        echo json_encode($arr);
    }
}
```

### Responsible rules

* `SimplifyForeachToArrayFilterRector`

## Expected Behavior

Either leave unchanged or possibly something like
```php
$arr = array_filter(iterator_to_array(new \ArrayIterator($a)), fn($v) => $v !== null);
```

The problem is that array_filter only supports arrays, so the changed code does not run.

**Comment by samsonasik** [comment]
I think it can just be skipped, could you try provide a patch? Verify that foreach iterated data is only ArrayType
