### ISSUE TITLE
`VarConstantCommentRector` doesn't understand `positive-int` comment

### ISSUE THREAD

**Issue by internalsystemerror** [rectorphp/rector#7897]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.25 |

A PHPdoc typehint of `positive-int` gets changed to `int` whereas `int<1, max>` which is equivalent is left unaltered.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/0dae0e85-648c-4f64-bbfd-38a2effcb54a

## Expected Behaviour

Rector should treat `positive-int` as `int<1, max>` which is more specific than `int`.

**Comment by samsonasik** [comment]
@internalsystemerror could you try provide a patch? I think this can be handled by check ehen type is subtype of, then it should be skipped.

**Comment by samsonasik** [comment]
I am checking it ...
