### ISSUE TITLE
`--clear-cache` doesnt work

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#7898]
# Bug Report

I have the feeling on the current dev version the `--clear-cache` cli option does not clear the cache.

`bin/rector --version --clear-cache`

-> `ChangedFilesDetector->clear()` is not invoked (verified via xdebug)

**Comment by staabm** [comment]
same is true for e.g. `php bin/rector.php -c rector-test.php --dry-run  --clear-cache`

**Comment by staabm** [comment]
it seems to work when using the process command: `bin/rector process --clear-cache`

**Comment by staabm** [comment]
IMO it should work for all 3 above commands.

it seems someone at the rector team had the same impression, because cache clear is invoked like that:
https://github.com/rectorphp/rector-src/blob/d777f36ffced045951e856ab22ed71591582147b/full_build.sh#L24-L25

**Comment by samsonasik** [comment]
`--clear-cache` process is;

- clear cache
- run process command

so the cache always refill after, so after `--clear-cache`, another process command is read last cache

**Comment by TomasVotruba** [comment]
Hi, I think this is covered by e2e test already.
Feel free to remove some code, if there is a dead one 👍
