### ISSUE TITLE
Erron on process : Invalid identifier name """""

### ISSUE THREAD

**Issue by JainulMufafika** [rectorphp/rector#7905]
Migrating from php 7.4 to php 8.0 using rector
Rector crashing with error "  Invalid identifier name """""   "
Rector Version : 0.15.25

<img width="756" alt="Capture" src="https://user-images.githubusercontent.com/115683093/235059939-ce445b63-6190-470f-9633-779b0b11a2d1.PNG">

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by JainulMufafika** [comment]
The class is extending a class from different file, Which causing the issue. I attached the link below, 
Please resolve the invalid identifier name error
https://getrector.com/demo/51cbaf32-b82e-460f-8fa5-37f9b0997542

**Comment by samsonasik** [comment]
we need simple reproducible code for that that show error, with only 1 or 2 rules, you can provide reproducible github repo, better with github action running

**Comment by JainulMufafika** [comment]
Minimal php code causing issue
<?php
abstract class Basket extends Database {

    protected $aIndexDesc;
    protected $aReport;
    protected $currency;
    public $dateSelect;
  
    
    public function Basket() {
        $this->Database();
        $this->aReport = new ArrayBase();
        $this->deliveryRange = array();
        $this->deliveryList = array();
        $this->dateSelect = true; //FL21252
       $this->oDigitalDelivery= new stdClass();
    }
}

**Configuration**
<?php
use Rector\Config\RectorConfig;
use Rector\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector;
return static function (RectorConfig $rectorConfig): void {
 $rectorConfig->rule(AddParamBasedOnParentClassMethodRector::class);
    
};

**Comment by samsonasik** [comment]
Closing as not reproducible. You can come back with reproducible repo, better with github action running. Thank you.
