### ISSUE TITLE
The committed vendor folder should not include phpstan/phpstan

### ISSUE THREAD

**Issue by stof** [rectorphp/rector#7906]
phpstan/phpstan is not scoped through the scoper project and it is declared as a dependency of the `rector/rector` package. But the `phpstan/phpstan` package is still committed in https://github.com/rectorphp/rector/tree/9a8a2a24dd650317b66950330cb77072949d9454/vendor/phpstan

For IDEs that index the content of phars present in the vendor folder (which is good when using phpstan as it allows to know about its classes), this cause the IDE to detect duplicate class definitions for phpstan classes, as we have 2 phpstan phars in the vendor folder (the one coming from installing phpstan and the one bundled in rector).

**Comment by stof** [comment]
Side note: it looks like this folder also includes `phpstan/phpstan-phpunit` and `phpstan/phpdoc-parser` without scoping them. This looks bad to me. Either they should not be shipped at all (if they are dev deps snicking in) or they should be scoped or they should use dependencies, as done for `phpstan/phpstan`

**Comment by samsonasik** [comment]
We were trying to make PHPStan scoped, it took a loot of effort, and it failed, see these PRs I can found (there are many attempts actually):

- https://github.com/rectorphp/rector-src/pull/44
- https://github.com/rectorphp/rector-src/pull/50
- https://github.com/rectorphp/rector-src/pull/68

Rector is really tight to phpstan api, if there is different API, usually different method parameter or new parameters config, it will crash directly so Rector need a new release, and that will fix it.

Thank you for understanding.

**Comment by stof** [comment]
@samsonasik I'm fine with not scoping phpstan and using it as a dependency, as done today. But then, you should avoid committing the non-vendored phpstan codebase (that won't be used) in the bundled vendor folder containing the scoped packages.

**Comment by TomasVotruba** [comment]
@stof You're right, this directory should be empty in the Rector release: https://github.com/rectorphp/rector/tree/main/vendor/phpstan/phpstan

**Comment by stof** [comment]
@TomasVotruba what about phpstan/phpdoc-parser and phpstan/phpstan-phpunit which are also committed there without being scoped (and so without being autoloaded ?

**Comment by samsonasik** [comment]
`phpstan/phpdoc-parser` is used as part of `preload.php` https://github.com/rectorphp/rector/blob/1e2a0a621743a18b1dcb258f494b0e6d7356e346/preload.php#L256-L263

**Comment by samsonasik** [comment]
@TomasVotruba phpstan dir can't be empty, as it contains phpstan.phar that loaded via composer require

**Comment by TomasVotruba** [comment]
@samsonasik I see. We might have to redirect the phpstan composer require somehow.

**Comment by TomasVotruba** [comment]
@stof @samsonasik  Any ideas how to handle this? :)

**Comment by samsonasik** [comment]
see why phpdoc-parser part of preload https://github.com/rectorphp/rector-src/pull/2908#issuecomment-1236900068

**Comment by stof** [comment]
ah, I understand what confused me. The non-scoped files can still be autoloaded if a prefixed file is loaded before them, due to the way the bootstrap.php file works, which still registers the composer autoloader entirely, while delegating to it for prefixed classes.

**Comment by samsonasik** [comment]
`phpstan/phpstan-phpunit` is in "require" in `rector-src` for long time, I no longer can trace with git blame, so it possibly was used as some "stubbing" purpose.

https://github.com/rectorphp/rector-src/blob/8b48059c347d98d191478504da236c4c2ba1e667/composer.json#L24

I was thinking about use of post-install:

- https://github.com/rectorphp/rector/issues/7732

but it possibly create variuos sync problem due to preload and possible IO issues.

The current vendored phpstan is not best optimal usage, but it just working ok, I think nothing needs to be changed.

**Comment by stof** [comment]
It was added in their in https://github.com/rectorphp/rector-src/commit/9e090281fcd759740db9a0d380fa10f770f35215

**Comment by samsonasik** [comment]
@stof thank you for getting the exact commit, docker is not supported now in rector, but it can "works" or "not works", so I think it can just probably be kept as is

**Comment by stof** [comment]
The latest version of https://github.com/rectorphp/rector-src/blob/main/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php does not use the phpstan-phpunit config files anymore, so this might not be used anymore. Extensions are now loaded in a different way using the extensions installed in the project (and not hardcoding phpstan-phpunit)

**Comment by samsonasik** [comment]
Ok, let's give it a try

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/3734
