### ISSUE TITLE
Please add gitattributes

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/rector#791]
See https://github.com/cakephp/cakephp/blob/master/.gitattributes

This is useful for
- newline definitions

**Comment by TomasVotruba** [comment]
The better place for that is `.editorconfig`: https://github.com/Symplify/Symplify/blob/master/.editorconfig

**Comment by dereuromark** [comment]
No, spacing is editorconfig, this is about newlines in windows vs linux etc.
Very important to let git know about the type here in use.

**Comment by dereuromark** [comment]
Ah true
but the gitattributes also works directly on checkout, and also envs where there is no IDE plugin for editorconfig available (yet).

**Comment by TomasVotruba** [comment]
I see. Feel free to add it

**Comment by dereuromark** [comment]
Sure, if no one is faster I can do it this week.

**Comment by dereuromark** [comment]
PR open.
