### ISSUE TITLE
Skip white space only changes / changes with no applied rectors

### ISSUE THREAD

**Issue by di-rmarlow** [rectorphp/rector#7914]
# Question
When running Rector with `--dry-run`, in addition to the desired changes that match my rector rule, I also get several changes which are small edits to white space. When I run with the `--output-format=json` option, I can see that those white space edits are on items where the `applied_rectors` array is empty. Is there a flag or configuration option for Rector which will cause it to skip changes that are white space only, or changes where no rectors have been applied?

I can imagine a way to do this - do a dry run with json output, feed it into another script, parse it, select only the files where `applied_rectors` is empty, and run those files individually - but that sounds like a lot of extra work for what might be a small flag/config change.

**Comment by samsonasik** [comment]
e2e test is needed for it, you can add more source file on

https://github.com/rectorphp/rector-src/tree/main/e2e/plain-views

and verify:

```
cd e2e/plain-views
composer install
php ../e2eTestRunner.php
