### ISSUE TITLE
Order constructor array by asc

### ISSUE THREAD

**Issue by Lenny4** [rectorphp/rector#7916]
When using Symfony we often have entities like this:
```php
<?php

namespace App\Entity\Site;

use App\Traits\TimestampableTrait;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity()]
class SomenEntity
{
    use TimestampableTrait;

    #[ORM\Column(type: Types::INTEGER)]
    #[ORM\GeneratedValue]
    #[ORM\Id]
    #[Groups(['group1', 'group2', 'group3'])]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING)]
    #[Groups(['group3', 'group1', 'group2'])]
    private ?string $name = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    #[Groups(['group3', 'group2', 'group1'])]
    private ?bool $show = null;
    
    // getter and setters ...
}
```
Notice that the array of group in `Groups` are not always written in the same order.
Would you be interested with a rule like this ? A rule which order these groups by `ASC` or `DESC`

**Comment by TomasVotruba** [comment]
Hi, thanks for your offer. I think this is rather coding standard rule coupled only to Symfony.

It would be more suitable in a coding standard tool.

**Comment by Lenny4** [comment]
@TomasVotruba it is customable if see the PL. You can specify which class to include so it's not specific to symfony.

**Comment by TomasVotruba** [comment]
The `Symfony\Component\Serializer\Annotation\Groups` class is Symfony specific. Still it seems something better suited for php-cs-fixer or code sniffer

**Comment by Lenny4** [comment]
@TomasVotruba `Symfony\Component\Serializer\Annotation\Groups` is a Symfony specific but you can configure the rule to pass any class you want which why it's not specific to symfony

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(OrderArrayParamRector::class, [
        Groups::class => 'ASC', // or any other class, you can replace Groups::class by MyClass::class
    ]);
};
```

**Comment by TomasVotruba** [comment]
Yes, I do. Instead I'd like to see a community rules that would embrace such custom ones. I think there is much potential in creative people like you, to just put out the rules you use out there :pray: Many people can benefit from it, like from custom coding standard sets.
