### ISSUE TITLE
Warning: Undefined array key "af2556806654e7b9516ae5fc46d7980520e9324a" on latest dev-main

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7919]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. dev-main (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

When using `"rector/rector": "dev-main"` on `CodeIgniter4` project, it now got the following errors:

```bash
➜  CodeIgniter4 git:(develop) ✗ vendor/bin/rector process system --clear-cache
 140/426 [▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░]  32%
Warning: Undefined array key "af2556806654e7b9516ae5fc46d7980520e9324a" in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/Caching/Detector/ChangedFilesDetector.php on line 55

Warning: Undefined array key "c36194d5f93bdf4e23b2fddc87cfa64d0b35b7f1" in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/Caching/Detector/ChangedFilesDetector.php on line 55
```

## Expected Behaviour

It should not show the error.

Step to reproduce:

```bash
git clone git@github.com:codeigniter4/CodeIgniter4.git
composer update rector/rector:dev-main
vendor/bin/rector process system --clear-cache
```

@yguedidi could you check it? Thank you.

**Comment by samsonasik** [comment]
The `$this->dependentFiles[$filePathCacheKey]` seems may not exists

**Comment by samsonasik** [comment]
It seems I found the issue, I will take care of it :)

**Comment by yguedidi** [comment]
Thank you @samsonasik
