### ISSUE TITLE
FinalizePublicClassConstantRector makes constant final because of name Class starting the same

### ISSUE THREAD

**Issue by epitre** [rectorphp/rector#7920]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | tested with 0.15.25 && 0.16.0 |
| Rector Rule | FinalizePublicClassConstantRector |

## Minimal PHP Code Causing Issue

You need namespace to reproduce the problem. I created a repo : https://github.com/Shaurifr/rector-final  

> NB : It is not dockerized, sorry for that.

Just clone the repo and launch `vendor/bin/rector process` -> it will make the constant in `ComputeMetricsEasy` `final`, which is wrong, because `ComputeMiles` overrides it. 

The problem seems to happen because there is a `ComputeMetrics` class next to `ComputeMetricsEasy`.

## Expected Behaviour

Do not make the constant final in `ComputeMetricsEasy`.

**Comment by epitre** [comment]
BTW, you might have to use `--clear-cache` to see the problem all the time.

**Comment by epitre** [comment]
`composer dump-autoload -o` did not work :/

I'm skipping the rule.

If I understand correctly, It seems to happen from time to time. Maybe add a link here ( https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#finalizepublicclassconstantrector ) to the troubleshouting ?

**Comment by samsonasik** [comment]
Add both parent and child to "classmap" or "files" in composer config mentioned in documentation should work.

**Comment by epitre** [comment]
here, I add to files in autoload-dev : https://github.com/Shaurifr/rector-final/commit/251d2c9b532ccc3cc11457fcf0e9fce4d4880304

**Comment by epitre** [comment]
of course, I always do `composer dump-autoload` before running `vendor/bin/rector process --dry-run`

**Comment by samsonasik** [comment]
You may need to skip that in the end if still happen.

**Comment by epitre** [comment]
ok

**Comment by jg-development** [comment]
I can confirm, that this is an issue. we have that problem too.
In out case it was an abstract class with a public const, that is set to final.

parent class:
```bash
1) src/Infrastructure/Aws/DynamoDb/Provider/ValueObject/Type/AbstractValue.php:8

    ---------- begin diff ----------
@@ @@

 abstract class AbstractValue implements TypeValueObjectInterface
 {
-    public const TYPE = '';
+    final public const TYPE = '';

     public function getType(): AttributeTypeEnum
     {
    ----------- end diff -----------

Applied rules:
 * FinalizePublicClassConstantRector (https://php.watch/versions/8.1/final-class-const)


``
child class
```bash
   ---------- begin diff ----------
@@ @@

 class StringValue extends AbstractValue
 {
-    public const TYPE = ScalarAttributeType::S;
+    final public const TYPE = ScalarAttributeType::S;

     public function __construct(private readonly string $value)
     {
    ----------- end diff -----------

Applied rules:
 * FinalizePublicClassConstantRector (https://php.watch/versions/8.1/final-class-const)

```

and only the one rule is executed:
```php
$rectorConfig->rule(FinalizePublicClassConstantRector::class);
```

could somebody plz open this bug again?
