### ISSUE TITLE
ThisCallOnStaticMethodToStaticCallRector token parsing issue

### ISSUE THREAD

**Issue by pxpm** [rectorphp/rector#7921]
# Bug Report

> First, thank you for reporting a bug. That takes time and we appreciate that!

No, I thank you for such amazing tool @TomasVotruba 👍 

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.16.0             |

`ThisCallOnStaticMethodToStaticCallRector` rule somehow is confusing my `$macro` (**variable name**) with a static method `::macro()` and attempts (incorrectly) to refactor a working code. 

I think by this time you are familiar with Laravel since LaraconPT. (I am Pedro btw, we enjoyed a beer alongside the river with Patricio 🍻 ) 🥶 ❄️ 

So in Laravel there is a Trait you can add to your classes to make them `macroable`. This trait ships with a static method `macro()` https://laravel.com/api/10.x/Illuminate/Support/Traits/Macroable.html

So I am using that Trait in a class (let's say `User`, and added a macro to that class called `whateverName`), so that allows me to do `$user->whateverName()` or `Class\User::whateverName()` and that `whateverName()` method is proxied through the magic methods in the `Macroable` trait, and doesn't "phisically" exists in the `User` class file. 

Somewhere in my code I am dealing with an instance of the said class `User` and I have some custom code that checks the user attributes for the presence of the macros and call them. 

```php

        // $this refers to the current `User` object

        $macros = ['whateverName'];
        $attributes = ['attribute1' => 'test', 'whateverName' => 'macro code example'] // return of `$user->getAttributes()` for example.

        foreach (array_keys($macros) as $macro) {
            if (isset($attributes[$macro])) {
                is_array($attributes[$macro]) ? $this->{$macro}($attributes[$macro]) : $this->{$macro}([]);
                continue;
            }
        }
```
Rector is suggesting me the following refactor, that will completely break the funcionality:

![image](https://user-images.githubusercontent.com/7188159/236538611-34b327a0-3de3-4c6e-a5c3-8f74277d2638.png)

I think this can be due to a confusion between the `$macro` variable name and the `::macro` method, don't know enough of rector internals. Not sure how to proceed here, can you help me out ? 

Cheers

**Comment by samsonasik** [comment]
Could you provide reproducible test on https://getrector.com/demo/ ? I can't reproduce https://getrector.com/demo/7190261a-a100-4dc8-9c26-aceed919bf62

**Comment by pxpm** [comment]
Hello @samsonasik 

The Macroable has a static method `macro()`.

See here: https://getrector.com/demo/4c186a30-600c-406c-9db0-39d937cea000

Thanks for having a look at it!  

Cheers
