### ISSUE TITLE
Calls to parent methods are removed when class reflection fails for external Composer dependencies

### ISSUE THREAD

**Issue by andreaswolf** [rectorphp/rector#7923]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.25             |

## Minimal PHP Code Causing Issue

Rector is running in a separate Composer project, because it runs in a separate Gitlab CI pipeline (preparation for a larger, ongoing upgrade that must be kept separate from the main project).
The main project is included with `$rectorConfig->autoloadPaths()`, so this is a minimal rector.php:

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->autoloadPaths([
        __DIR__ . '/path-to-main-project/vendor/autoload.php',
    ]);

    // A. run whole set
    $rectorConfig->rule(\Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector::class);
};
```

Having this class in the main project triggers the error:

```php

namespace Test;

use SomeComposerDependency\SomeClassFromComposerDependency;

class Child extends SomeClassFromComposerDependency {
    public function __construct() {
        parent::__construct();
    }
    public function setUp() {
        parent::setUp();
    }
}
```

The package behind `SomeComposerDependency` is not included in the Rector project's composer.json, but only the main project's composer.json.

In this case, `\Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector::shouldSkip()` returns false, but the parent class's reflection resolves to null, and thus the call is removed.

It's not possible to reproduce this using getrector.org/demo/.

## Expected Behaviour

Either class reflection should work correctly for these external dependencies, since their autoload info is available. Or these calls should simply be skipped.

**Comment by samsonasik** [comment]
That's the issue for not scan whole project, see https://phpstan.org/blog/why-you-should-always-analyse-whole-project

You may looking for bootstrap instead of autoload, or make early "files" or "classmap" config in composer.json, see https://getrector.com/documentation/static-reflection-and-autoload
