### ISSUE TITLE
RemoveUselessParamTagRector removes positive-int annotation

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#7925]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/6830bb1d-4b6d-4fd2-9bcf-fa6dcd022b4a

```php
<?php

final class DemoFile {
    /**
     * @param positive-int $blockSize
     */
    public function write(int $blockSize) {
    }
}
```

### Responsible rules

* `RemoveUselessParamTagRector`

## Expected Behavior

The `@param` annotation is not useless.

**Comment by jlherren** [comment]
Actually, `RemoveUselessReturnTagRector` is also affected.

**Comment by mpesari** [comment]
If it helps, I noticed this also happens with `UnionTypesRector`
