### ISSUE TITLE
Slow rule-tests Testsuite

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#7930]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

I had a look into rules-tests performance because they are a lot slower then all other tests.

Most interessting when looking into the profiles is, that we spent most of the time in compiling the depenency injection containers.
The tests itself are not that slow:

![grafik](https://github.com/rectorphp/rector/assets/120441/009437da-638e-4e45-981b-4def162ffb22)

It seems these containers are dumped/compiled every time we run the test-suite.
I think it would be great if we could somehow only compile them once, as we don't add/remove underlying services in most commits.

do you think thats possible?

**Comment by TomasVotruba** [comment]
Hi Markus, great observation. Actually we had such approach before, but we sturggled with container setup invalidation.

Symfony container does not allow easy way to change configuration (parameters) and has to be rebuild. What we could do, is to add "current rule service on the fly" and work only with that one in any test, that registers bare rule and no other parameters.

Also, we could move away from Symfony container in the near future (or now? :)) and use some bare explicit container with our logic. That would allow us to handle these cases as we need without being limited by any framework.

**Comment by staabm** [comment]
I wonder why we need a container per AbstractRectorTest. 

Can't we use a single container for all tests?

In the rector release all rules need to work also with a single container, so I wonder why we have separate ones in the testsuite

**Comment by TomasVotruba** [comment]
> Can't we use a single container for all tests?

Yes :+1:  Last time the change of parameters in tests were problems, e.g. rename class rector with different configuration required fresh container. But maybe there is a better way.
