### ISSUE TITLE
Make some CI jobs required

### ISSUE THREAD

**Issue by yguedidi** [rectorphp/rector#7936]
@TomasVotruba some CI jobs were added recently, they may deserve to be marked as Required like others.

I'm thinking about:
- End to End tests / End to end test - e2e/multiple-class-psr4
- End to End tests / End to end test - e2e/removed-and-added-files-collector
- End to End tests with cache / End to end test - e2e/applied-rule-removed-node-with-cache
- End to End tests with cache / End to end test - e2e/timeout-file-not-cached
- End to End tests with consecutive changes / End to end test - e2e/consecutive-changes-with-cache
- Tests / PHP 8.1 tests for other-rules
- Tests / PHP 8.1 tests for php-rules
- Tests / PHP 8.1 tests for utils-tests

**Comment by TomasVotruba** [comment]
Thanks for the list :+1:  Just added
