### ISSUE TITLE
rector/rector:dev-main cause phpunit error test 

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7939]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

@staabm here a bug because of your PR:

- https://github.com/rectorphp/rector-src/pull/3809

## Minimal PHP Code Causing Issue

Shown in e2e test on this repo:

https://github.com/rectorphp/rector/actions/runs/4982533394/jobs/8918337344#step:6:17

```

Time: 00:00.045, Memory: 14.00 MB

There was 1 error:

1) Utils\Rector\Tests\Rector\RenameSimpleRector\RenameSimpleRectorTest::test with data set #0 ('/home/runner/work/rector/rect...hp.inc')
Error: Class 'RectorPrefix202305\Symplify\SmartFileSystem\SmartFileSystem' not found
```

## Expected Behaviour

It should be working. I tried in laminas-servicemanager-migration test as well and got same error:

```
git clone git@github.com:laminas/laminas-servicemanager-migration.git
cd laminas-servicemanager-migration
composer require rector/rector:dev-main
vendor/bin/phpunit
```

Got error:

```bash
➜  laminas-servicemanager-migration git:(1.13.x) ✗ vendor/bin/phpunit 
PHPUnit 9.6.8 by Sebastian Bergmann and contributors.

EEEEEEEEEEEEEEEEEEE                                               19 / 19 (100%)

Time: 00:00.039, Memory: 16.00 MB

There were 19 errors:

1) LaminasTest\ServiceManager\Migration\Rector\Class_\ImplementsFactoryInterfaceToPsrFactoryRector\AutoImportRenameUseTest::test with data set #0 ('/Users/samsonasik/www/laminas...hp.inc')
Error: Class "RectorPrefix202305\Symplify\SmartFileSystem\SmartFileSystem" not found

/Users/samsonasik/www/laminas/laminas-servicemanager-migration/vendor/rector/rector/src/Kernel/CachedContainerBuilder.php:40
/Users/samsonasik/www/laminas/laminas-servicemanager-migration/vendor/rector/rector/src/Kernel/RectorKernel.php:112
/Users/samsonasik/www/laminas/laminas-servicemanager-migration/vendor/rector/rector/src/Kernel/RectorKernel.php:55
/Users/samsonasik/www/laminas/laminas-servicemanager-migration/vendor/rector/rector/packages/Testing/PHPUnit/AbstractTestCase.php:38
/Users/samsonasik/www/laminas/laminas-servicemanager-migration/vendor/rector/rector/packages/Testing/PHPUnit/AbstractRectorTestCase.php:60
```

**Comment by samsonasik** [comment]
@staabm I created PR for it https://github.com/rectorphp/rector-src/pull/3865

**Comment by staabm** [comment]
hey @samsonasik 

thanks for looking into it.

> ```shell
> 1) LaminasTest\ServiceManager\Migration\Rector\Class_\ImplementsFactoryInterfaceToPsrFactoryRector\AutoImportRenameUseTest::test with data set #0 ('/Users/samsonasik/www/laminas...hp.inc')
> Error: Class "RectorPrefix202305\Symplify\SmartFileSystem\SmartFileSystem" not found
> ```

this error is strange. could it mean that, because of class-prefixing classes cannot be found?

**Comment by samsonasik** [comment]
it seems container can't pull prefixed class. I just disable container cache on scoper rector/rector with verify VersionResolver::PACKAGE_VERSION value  generated at PR:

- https://github.com/rectorphp/rector-src/pull/3865

**Comment by staabm** [comment]
since e2e tests are pretty fast, I think its fine to not use a dumped container for them
