### ISSUE TITLE
System error: "Return value of RectorPrefix202305\Nette\Utils\Reflection::getUseStatements() must be of the type array, null returned"

### ISSUE THREAD

**Issue by mega** [rectorphp/rector#7942]
Got this error by running rector with --debug on an Entity class using ApiPlatform resource class 

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;
use Rector\Symfony\Set\SymfonySetList;
use Rector\Doctrine\Set\DoctrineSetList;
use Rector\Core\ValueObject\PhpVersion;

return static function (RectorConfig $rectorConfig): void {
    // define sets of rules
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_82,
    ]);

    $rectorConfig->importNames();
    $rectorConfig->importShortClasses(false);
    $rectorConfig->phpVersion(PhpVersion::PHP_82);

    $rectorConfig->paths([
        __DIR__ . '/src',
    ]);

};
```
[error.txt](https://github.com/rectorphp/rector/files/11489169/error.txt)

```
entity-service:/srv/api$ php vendor/bin/rector --version
Rector 0.16.0
```

**Comment by samsonasik** [comment]
Could you provide reproducible test on https://getrector.com/demo/  , or we need simple reproducible code for that that show error, with only 1 or 2 rules, you can provide reproducible github repo, better with github action running

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by mega** [comment]
@samsonasik unfortunately, I am not sure I can, simply because I don't actually understand the error. I just followed the instructions on the error message and filed this bug report. 
What I can add is that I tried to run this rector script settings using smaller sets of directories from same project and got less errors like this, ie, it seems that some conflicts come from changes done by rector itself on other classes that might be dependencies of further along (in the tree) classes.
I understand it's difficult to check these issues with no more data, and I would totally understand there's nothing you can do to help.
