### ISSUE TITLE
Allow adding aliased imports again

### ISSUE THREAD

**Issue by jtojnar** [rectorphp/rector#7950]
# Feature Request

In the past, it was possible to pass `AliasedObjectType` to `UseNodesToAddCollector::addUseImport()` but it looks like it has been (possibly accidentally) removed in https://github.com/rectorphp/rector-src/pull/2672. Is there another way to do that or, if not, would you accept PRs adding the support back?

We are using it in our [custom rule for creating fixtures for golden tests](https://github.com/j0k3r/graby/blob/e1ec8caec254b52a30dda407c01b3f965da8c1c1/maintenance/Rector/MockGrabyResponseRector.php#L153-L155):

```php
$this->useNodesToAddCollector->addUseImport(
    new AliasedObjectType('HttpMockClient', 'Http\Mock\Client')
);
```

**Comment by jtojnar** [comment]
Do you mean doing something like `$this->useNodesToAddCollector->addUseImport(new FullyQualifiedObjectType('Replace\Me\With\Alias\HttpMockClient\Http\Mock\Client'))` and then having a second rule that would match on `Use_` and replace that?

**Comment by samsonasik** [comment]
Probably a dedicated rule for that, as use nodes to add collector is being processed on PostRector, and it possibly overlapped. You can add `beforeTraverse()` in a didicated rule to resolve root node:


```php
    private FileWithoutNamespace|Namespace_|null $rootNode = null;

    public function beforeTraverse(array $nodes): array
    {
        // ensure reset early on every run to avoid reuse existing value
        $this->rootNode = null;

        foreach ($nodes as $node) {
            if ($node instanceof FileWithoutNamespace || $node instanceof Namespace_) {
                $this->rootNode = $node;
                break;
            }
        }

        return $nodes;
    }
```

then `array_splice()` to insert `$this->rootNode->stmts` when found after namespace or before some specific stmt.

**Comment by jtojnar** [comment]
Thanks that sounds like it could be usable, will try it once I cycle back to PHP work. 

Thought it is still less ergonomic than `useNodesToAddCollector`. Just to be clear, is `useNodesToAddCollector` supporting `AliasedObjectType` not desired?

**Comment by samsonasik** [comment]
`AliasedObjectType` in use adder probably a feature that never used before in any rector-src code, or it actually used by rector-src extensions, just removed from the core so the code is left there "as marked" never used, so it got removed.

**Comment by TomasVotruba** [comment]
Closing as answered, better handle with custom rule as we won't add alias support at the moment.
