### ISSUE TITLE
Is there TypedPropertyRector somewhere or its alternative?

### ISSUE THREAD

**Issue by Ciki** [rectorphp/rector#7951]
# Question
Hi! I found this blog https://tomasvotruba.com/blog/2018/11/15/how-to-get-php-74-typed-properties-to-your-code-in-few-seconds where `TypedPropertyRector` is being used to convert phpDoc type to property type but I cannot find it anywhere now. Has it been removed? Is there an alternative for this use case?

Thanks!

**Comment by Ciki** [comment]
I've found more recent info https://getrector.com/blog/new-in-rector-015-complete-safe-and-known-type-declarations so I'm closing this here

**Comment by tacman** [comment]
Per @Ciki , this is what I use

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\ClassMethod\AddVoidReturnTypeWhereNoReturnRector;
use Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector;
use Rector\Set\ValueObject\SetList;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src'
    ])
    // uncomment to reach your current PHP version
    ->withPhpSets(php82: true)
    ->withSets([
        SetList::TYPE_DECLARATION,
    ])
    ->withRules([
        TypedPropertyFromAssignsRector::class,
        AddVoidReturnTypeWhereNoReturnRector::class,
    ]);

```

**Comment by joachim-n** [comment]
It's a real shame this has been removed.

I know that my `@var` declarations are correct, and I have test coverage which would catch any that aren't. So it would be really useful to be able to derive property types from the `@var` in the property docblock.

**Comment by dkonate** [comment]
@joachim-n by using the SetList::TYPE_DECLARATION, it worked. 
My ` @var`  are used by rector to typehint all properties of my classes.
The class have been removed but the constant do the same. Maybe i don't really get your issue :)
