### ISSUE TITLE
How to disable argument re-ordering?

### ISSUE THREAD

**Issue by NikolaSivkov** [rectorphp/rector#7952]
# Question

The code i'm trying convert has functions like this 

```php
private function is_class_method($class, $type = "public", $method)
```
```php
 public function __construct(
        $pName = null,
        PHPExcel_Worksheet $pWorksheet,
        $pRange = "A1",
        $pLocalOnly = false,
        $pScope = null
    )
```
```php
function post($url, $formvars = null, $request)
```
```php
public function addBundle($data = [], $return_id = false, $bg_id)
```

In these examples, the parameters don't follow the `required params first` convention, and Rector tries to re-order the params. 
And in all those cases, it gets stuck on those files changing the params back and forth in an infinite loop. 

Can someone guide me on which rule defines this behavior, and how to properly stop it? 
The code base i'm working on is ~5000 php files. So it would be best if parameters aren't re-ordered. 

The rector config i have in terms of rules is just this 

```php
 $rectorConfig->sets([LevelSetList::UP_TO_PHP_81]);
 ```

P.S. Meanwhile i'm working on a bug report with a reproducible sample.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by NikolaSivkov** [comment]
Still working on reproduction steps, but i managed to find the rule that re-orders the parameters and disable it. 
Once disabled, everything works as expected

```php
use Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector;
...
    $rectorConfig->skip([OptionalParametersAfterRequiredRector::class]);
    // define sets of rules
    $rectorConfig->sets([LevelSetList::UP_TO_PHP_81]);
```

**Comment by samsonasik** [comment]
It should already resolved at https://github.com/rectorphp/rector-src/pull/4484 , please try latest version 0.17.6
