### ISSUE TITLE
Use ReplaceArgumentDefaultValueRector with constructor

### ISSUE THREAD

**Issue by GromNaN** [rectorphp/rector#7956]
# Feature Request

I'd like to use [`ReplaceArgumentDefaultValueRector`](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#replaceargumentdefaultvaluerector) to make changes on `__construct` calls.

Given a class like this:
```php
class SomeClass
{
    public const CONSTANT = 'const_value';

    public function __construct(string $arg) { /* ... */ }
}
```

The rule with this config has no effect:

```php
$rectorConfig->ruleWithConfiguration(ReplaceArgumentDefaultValueRector::class, [
    new ReplaceArgumentDefaultValue('SomeClass', '__construct', 0, 'const_value', 'SomeClass::CONSTANT'),
]);
```

 
## Diff 

I'd like to make this change:

```diff
-$someObject = new SomeClass('const_value');
+$someObject = new SomeClass(SomeClass::CONSTANT);
```

**Comment by TomasVotruba** [comment]
Thanks for proposal, I'm looking into it :+1:
