### ISSUE TITLE
Incorrect behavior of RemoveUnreachableStatementRector

### ISSUE THREAD

**Issue by csicso1962** [rectorphp/rector#7957]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/75c05890-19ae-43c6-99af-23571522354d

```php
<?php

final class DemoFile
{
    public function run()
    {
        return 5;

        // we never get here
        return 10;
    }
}
```

### Responsible rules

* `RemoveUnreachableStatementRector`

**Comment by samsonasik** [comment]
That is expected. Return after return in unreachable stmt.
