### ISSUE TITLE
Take advantage of PHPStan\Type\Type::toPhpDocNode()

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#7959]
# Feature Request

Hello, I've added `Type::toPhpDocNode()` in PHPStan 1.10.14. You could use that instead of `TypeMapperInterface::mapToPHPStanPhpDocTypeNode()` and `PHPStanStaticTypeMapper::mapToPHPStanPhpDocTypeNode()` to convert `PHPStan\Type\Type` back into `phpstan/phpdoc-parser` AST node and be able to delete a bunch of your own code.

Of course, it's not going to be have exactly 1:1 as your code does now, but we can work out the differences together for the best outcome 👍 

The advantage of `PHPStan\Type\Type::toPhpDocNode()` is that it's trying to be as precise as possible, and will also work for any new added types in PHPStan in the future.

**Comment by TomasVotruba** [comment]
@ondrejmirtes Hi Ondra, I gave it a 2nd, now more successful try :slightly_smiling_face: 

I've converted most of our mappers to use the `$type->toPhpDocNode();` method and after few changes in the code, they work well.

There are 2 print issues that are spread and can be invoked in another `toPhpDocNode()` method:

1. The `UnionType` union type with extra spacing

```diff
-@param int|string
+@param ( int | string )
```

It's a standard to use X|Y syntax, unless part of some callbable or intersection etc. How can we make this nice? :) 

--

2. The `ObjectType` is always without FQN slash

```diff
namespace App\Controller;


...

-@ORM\OneToMany(targetEntity="\App\Entity\Product"
+@ORM\OneToMany(targetEntity="App\Entity\Product"
```

The slash removal looks like detail, but in the end this changes the FQN of class by automatically adding the namespace:

```diff
-App\Entity\Product
+App\Controller\App\Entity\Product
```

How can we invoke pre-slash by default?

<br>

Thanks for your help :+1:

**Comment by TomasVotruba** [comment]
You can see examples of those issues here: https://github.com/rectorphp/rector-src/actions/runs/5624461506/job/15241326621

![image](https://github.com/rectorphp/rector/assets/924196/6d6177e5-dc46-43a8-a126-e0feeed67062)

**Comment by ondrejmirtes** [comment]
You can get `int|string` from a union type using the `Printer::print()` method: https://phpstan.github.io/phpdoc-parser/PHPStan.PhpDocParser.Printer.Printer.html

The reason why `UnionTypeNode::__toString()` does `(int | string)` is because of backward compatibility.

The Printer also supports format-preserving printing the same way nikic/PHP-Parser does for PHP.

About the 2nd problem - ideally it should take into account the namespace and the use statements, right :) I imagine the `Printer::print()` method could have a 2nd parameter "context" with this information passed into it. I will have to think about it.

**Comment by TomasVotruba** [comment]
@ondrejmirtes I'm going to try the printer now, thanks :) 

Yeah, the namespace context would be great :+1: In Rector we basically print every class as FQN by default.

**Comment by TomasVotruba** [comment]
@ondrejmirtes I'm trying to use the printer from phpdoc-parser, but it seems used only inside each not. Not sure how to replace the printing in `UnionType` without using custom union type class.

I also tried replace our printer with phpdoc-parser, but diff keeps failing on some missing keys - https://github.com/rectorphp/rector-src/pull/4577/files

**Comment by ondrejmirtes** [comment]
Make sure to pass `$usedAttributes = ['lines' => true, 'indexes' => true];` everywhere, see the README of the project.

**Comment by samsonasik** [comment]
@ondrejmirtes FQCN we want is to not care about current namespace or use statements, just add `\` on the `ObjectType`, except special one: `self`, `parent`, `static`, `object`.

**Comment by samsonasik** [comment]
@TomasVotruba we may need to cover custom `AliasedObjectType` or `ShortenedObjectType` as special type without `\` prefix as well.

**Comment by samsonasik** [comment]
@TomasVotruba @ondrejmirtes the tweak on rector seems can replace the target object type identifier node to our custom fully qualified identifier node:

```php
        $typeNode = $type->toPhpDocNode();

        $phpDocNodeTraverser = new PhpDocNodeTraverser();
        $phpDocNodeTraverser->traverseWithCallable($typeNode, '', function (AstNode $astNode) {
            if (! $astNode instanceof IdentifierTypeNode) {
                return null;
            }

            if ($astNode->name !== 'Closure') {
                return null;
            }

            $astNode = new FullyQualifiedIdentifierTypeNode('Closure');
            return $astNode;
        });

        return $typeNode;
```

Ref https://github.com/rectorphp/rector-src/pull/4584/files#diff-ba5b419a44512b9e9623a0cd9e648f7e40c7a0d6afc73e790c9c96a31a95ace5

**Comment by ondrejmirtes** [comment]
I'm not sure about `FullyQualifiedIdentifierTypeNode`, the phpdoc-parser Printer class would most likely not be able to print that.

But I'd suggest you to do this instead: So you have `PHPStan\Type\Type` on which you want to call `toPhpDocNode()`. Before you call that, you should transform the Type with `TypeTraverser` like this:

```php
$type = TypeTraverser::map($type, static function (Type $type, callable $traverse): Type {
	if ($type instanceof ObjectType) {
		return new ObjectType('\\' . $type->getClassName());
	}
		
	return $traverse($type);
});
$type->toPhpDocNode(); // IdentifierTypeNode is FQN!
```

**Comment by samsonasik** [comment]
@ondrejmirtes `FullyQualifiedIdentifierTypeNode` is a class extends `IdentifierTypeNode`, it working ok on PR fqcnize closure type and printed correctly:

- https://github.com/rectorphp/rector-src/pull/4584

changing to use `TypeTraverser::map` which seems need to correspond with `templateTypeMap`, will cause invalid output:

```diff
 final class VarClosureAnnotationMissingNullPreferPrepend
 {
-    /** @var null|\Closure(string, int, \Closure(float): int): string */
+    /** @var null|\Closure */
     private ?Closure $tooltipGenerator = null;
```

**Comment by TomasVotruba** [comment]
We got the most out of this feature, so this is ready to close.

See https://github.com/rectorphp/rector-src/pull/4573#issuecomment-1720975174 for more
