### ISSUE TITLE
Create LTS 0.16.x branch

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7961]
# Feature Request

I think we need a branch that cherry-picked from 0.16.0 tag. The reason is sometime, PHPStan has new config and it just break the existing 0.* tag, and there is now way to resolve it except use previous PHPStan version, or bump to use `dev-main` of rector, while that certainly break consumer extensions per current code changes go to v1.

My idea is to :

- create a branch named 0.16.x in rector-src pulled from latest 0.16.0 tag, which can have separate prefix build script to build into rector/rector repository with same branch name.
- When new phpstan config added that broke 0.16 version, we can create new relaease base of that branch.

This also can have time for user to prepare to migrate to v1 when v1 ready.

**Comment by samsonasik** [comment]
This will require all rector-* extensions to have 0.16.x branch as well, we may need to find a pin point commit it started to if this need to be implemented.

**Comment by TomasVotruba** [comment]
What exact new phpstan config we talk about?

Next version will be 0.17 with BC breaks in parent/next/previous node. The 1.0 waits for couple more changes, some of them are listed in https://github.com/rectorphp/rector/issues/7854

**Comment by samsonasik** [comment]
That's to avoid error like this issue:

- https://github.com/rectorphp/rector/issues/7803

we usually do new release if there is phpstan config added.

**Comment by TomasVotruba** [comment]
That seems like 4 months old and solved. 
I think we should release a 0.17 with next/previous removed, so we have stepping stones for changes. We've done a lot of work and need feedback from community. There won't be much changes, as only few internal rules used the next/previous nodes.

The parent node removal will take time and should aim at 0.18 release.

**Comment by samsonasik** [comment]
Ok :+1:

**Comment by TomasVotruba** [comment]
Here we go :)

https://github.com/rectorphp/rector/releases/0.17.0

Now we collect feedback and fix what will come 😎
