### ISSUE TITLE
RemoveUnusedVariableAssignRector does not consider variables bound by reference

### ISSUE THREAD

**Issue by spawnia** [rectorphp/rector#7963]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.0             |

Rector is overly eager in removing variable assignments.
Even when the variable is not referenced after assignment, it may still be bound by reference.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/18574ffe-1c32-4d81-9d0d-9f41b9e1c193

## Expected Behaviour

Rector should not remove variable assignments when the variable is bound by reference.

**Comment by samsonasik** [comment]
`ByRefVariableNodeVisitor` may need to be refactored to cover inlined next after closure use usage (not inside)

https://github.com/rectorphp/rector-src/blob/501ce6f097e9788cdb19d10136591ff98c1febb3/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/ByRefReturnNodeVisitor.php#L17

**Comment by spawnia** [comment]
Thank you @samsonasik, nice work.
