### ISSUE TITLE
TypedPropertyRector was removed

### ISSUE THREAD

**Issue by shylux** [rectorphp/rector#7964]
# Question
Why was this rule removed in 0.15? Should it not be used anymore? https://github.com/rectorphp/rector/blob/0.14.8/rules/Php74/Rector/Property/TypedPropertyRector.php

**Comment by samsonasik** [comment]
It is removed, ref https://getrector.com/blog/new-in-rector-015-complete-safe-and-known-type-declarations

You can use `\Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector` instead for more reliable type.
