### ISSUE TITLE
Incorrect behavior of ForeachItemsAssignToEmptyArrayToAssignRector

### ISSUE THREAD

**Issue by mpesari** [rectorphp/rector#7966]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a3014949-2478-48ef-bb13-be09ff14abc4

```php
<?php

final class DemoFile
{
    private function getOtherValues(): array {
        return [];
    }

    public function getValues(bool $condition): array
    {
        $values = [];
        
        if ($condition) {
            $values[] = 'hello';
        }
        
        // Append other values to list.
        // FIXME: Rule changes code to overwrite 'hello'.
        foreach ($this->getOtherValues() as $value) {
            $values[] = $value;
        }
        
        return $values;
    }
}
```

### Responsible rules

* `ForeachItemsAssignToEmptyArrayToAssignRector`

## Expected Behavior

I guess in this case Rector should do nothing

**Comment by samsonasik** [comment]
Even without if, it seems still cause invalid result https://getrector.com/demo/7e14fa92-ade0-4f19-aca2-012adf6acc88

It seems only assigned with empty one need to be checked instead of multiple assign before append.
