### ISSUE TITLE
"Only variables should be passed by reference" with DowngradeTrailingCommasInFunctionCallsRector

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#7969]
I'm using getrector.org/demo to create an issue with `DowngradeTrailingCommasInFunctionCallsRector`, and somehow, with any simple test case including `sprintf` the output produces an error:

```json
{ "totals": { "changed_files": 0, "removed_and_added_files_count": 0, "removed_node_count": 0, "errors": 1 }, "errors": [ { "message": "System error: \"Only variables should be passed by reference\"\nRun Rector with \"--debug\" option and post the report here: https://github.com/rectorphp/rector/issues/new", "file": "/var/www/src/../storage/demo/ffsb1tn8xhkhjl4qruvy/rector_analyzed_file.php", "line": 71 } ] } 
```

Check: https://getrector.com/demo/e60bf8e6-ff43-49f1-92c4-11d53ed03089

Test code:

```php
<?php

final class DemoFile
{
    public function run()
    {
        return sprintf("%s", "1");
    }
}
```

config:

```php
<?php

use Rector\Config\RectorConfig;
use Rector\DowngradePhp73\Rector\FuncCall\DowngradeTrailingCommasInFunctionCallsRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rule(DowngradeTrailingCommasInFunctionCallsRector::class);
};
```

**Comment by leoloso** [comment]
Another example:

https://getrector.com/demo/5d2d4ad5-4540-42c5-9413-e89ce672464e

```php
<?php

final class DemoFile
{
    public function run()
    {
        return App::getState('query');
    }
}
```

**Comment by leoloso** [comment]
Btw, I just updated to `v0.17` and now running Rector produces a strange behavior. It may be connected to this issue... if it is not, I can create a separate issue.

You can check the issue in this CI run: https://github.com/leoloso/PoP/actions/runs/5151455504/jobs/9276650958

I run the DOWNGRADE_TO_PHP71 set on my code, and immediately after I run it again using `--dry-run`, to validate that there are no further downgrades needed. This second time, there should be no changes anymore... if there are, the run fails.

As you can see, there are changes, however these changes should not happen! The applied rule in those 10 cases is `DowngradeTrailingCommasInFunctionCallsRector`, however there's no actual change from this rule. Instead, the file has been updated by removing whitespaces, and `--dry-run` informs the code would be updated. This is not right.

I wonder if `DowngradeTrailingCommasInFunctionCallsRector` is producing a silent error (like the one I mentioned above in this issue?), and instead of failing, Rector still pushes ahead, and stores the file again, having formatted it. Or something like that...

Any idea?

**Comment by samsonasik** [comment]
Thank you for trying version 0.17, I will check one by one, you possibly need to separate issue for other use cases to avoid missed part.

For now, you can back to use 0.16

**Comment by leoloso** [comment]
> Thank you for trying version 0.17, I will check one by one, you possibly need to separate issue for other use cases to avoid missed part.

Alright. After you've checked the first issue, I'll then use the new code to check again if the 2nd issue still happens. Then I'll give you feedback about it, and create again an issue in GitHub if the problem persists.

**Comment by samsonasik** [comment]
This is strange that I can't reproduce in unit test:

![Screen Shot 2023-06-02 at 12 59 42](https://github.com/rectorphp/rector/assets/459648/9f6512ba-241b-4f63-995d-2136a128c3b8)

I will check next latest dev-main deploy today to website today.

**Comment by samsonasik** [comment]
@leoloso could you create a simple reproducible repo with only have simple file and the rule applied? Thank you.

**Comment by samsonasik** [comment]
@TomasVotruba it seems it is due to `getArgs()` replacement on PR:

- https://github.com/rectorphp/rector-downgrade-php/pull/55

That cause code downgraded as:

```php
        if ($node->getArgs() !== []) {
            \end($node->getArgs());
            $lastArgumentPosition = \key($node->getArgs());
            $last = $node->getArgs()[$lastArgumentPosition];
```

which make variable not passed by reference on `end()` usage.

https://github.com/rectorphp/rector/blob/633f1961502b4bcebc8f3e721535f94473a43ad8/vendor/rector/rector-downgrade-php/rules/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector.php#L70-L72

I will move to early variable assign for it.

**Comment by samsonasik** [comment]
@leoloso I created PR https://github.com/rectorphp/rector-downgrade-php/pull/85 for it to ensure save to variable first, 

There should be a dedicated handling for by reference of `end()` or `key()` argument, but that will require separate PR of `DowngradeArrayKeyFirstLastRector` usage :)

**Comment by leoloso** [comment]
Thanks @samsonasik you're the best! 💪

After you release a new Rector version, I'll test again. If the problem still happens, I'll then create the reproducible repo (I was on my way to do it now, when I saw your comment)

**Comment by samsonasik** [comment]
@leoloso could you try latest dev-main? Thank you.

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by leoloso** [comment]
Ok, doing it now, will keep you updated

**Comment by leoloso** [comment]
@samsonasik It worked perfectly https://github.com/leoloso/PoP/actions/runs/5153157555/jobs/9280054069

👏 Thanks!
