### ISSUE TITLE
Incorrect behavior of CountArrayToEmptyArrayComparisonRector

### ISSUE THREAD

**Issue by pauci** [rectorphp/rector#7971]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/4ffb788a-2744-46bc-8f09-56e20aa5b819

```php
<?php

final class DemoFile implements \Countable
{
    public function isNotEmpty(): bool
    {
        return 0 < \count($this);
    }
    
    public function count(): int
    {
        return 0;
    }
}
```

### Responsible rules

* `CountArrayToEmptyArrayComparisonRector`

## Expected Behavior

In this case rector should do nothing as counted value is not an array,

**Comment by samsonasik** [comment]
@staabm @yguedidi this probably a bug caused by usage : `isArray()->yes()` instead of direct instanceof ArrayType
