### ISSUE TITLE
Incorrect behavior of ConsecutiveNullCompareReturnsToNullCoalesceQueueRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#7976]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/8420e8f2-769b-453b-b2cb-b4289a8cb15c

```php
<?php

class MyClass {
    protected ?stdClass $prop1 = null;
    protected ?stdClass $prop2 = null;

    public function getProp(): stdClass {
        if ($this->prop1 !== null) {
            return $this->prop1;
        }
        if ($this->prop2 !== null) {
            return $this->prop2;
        }
        throw new RuntimeException('No prop is set');
    }
}
```

### Responsible rules

* `ConsecutiveNullCompareReturnsToNullCoalesceQueueRector`

## Expected Behavior

Desired behavior is either to do nothing at all, or transform to something like the following (throw expression requires PHP 8):

```php
    public function getProp(): stdClass {
        return $this->prop1 ?? $this->prop2 ?? throw new RuntimeException('No prop is set');
    }
```

**Comment by jlherren** [comment]
@samsonasik Thanks, that was fast! :)

However, I found two more cases that still fail (`main@fe33aa`). I can't use the demo site, because it hasn't been updated yet.

It creates two return statements here:

```php
--- Expected
+++ Actual
@@ @@
 
     public function getProp(): \stdClass
     {
-        if ($this->prop1 !== null) {
-            return $this->prop1;
-        }
-        if ($this->prop2 !== null) {
-            return $this->prop2;
-        }
         return new \stdClass();
+        return $this->prop1 ?? $this->prop2;
     }
 }
```

And ignores that there's a side effects here:

```php
     public function getProp(): ?\stdClass
     {
-        if ($this->prop1 !== null) {
-            return $this->prop1;
-        }
-        if ($this->prop2 !== null) {
-            return $this->prop2;
-        }
         echo "Hi!\n";
-        return null;
+        return $this->prop1 ?? $this->prop2;
     }
```

**Comment by samsonasik** [comment]
Ok, reopen, I will check when I have a chance. Feel free to provide a patch first if you can ;)
