### ISSUE TITLE
Rector cannot load class to run Rule

### ISSUE THREAD

**Issue by EdaCZ** [rectorphp/rector#7977]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.8  |
| [rector-nette](https://github.com/efabrica-team/rector-nette/tree/main) |  v0.14 | 

I am trying rector in combination with rector-nette. 

And I am not able to make it work. Its complaining, that some classes are not found, but I can see it in the code. Why it's not loading?

Have I done something wrong in config/usage? Is it bug in rector-nette? Is it bug in rector itself? As I am new to rector, I don't have a clue :-)

## Minimal PHP Code Causing Issue

Just run in terminal:

```bash
$ composer create-project nette/web-project rector-nette-test
$ cd rector-nette-test/
$ composer require efabrica/rector-nette:@dev --dev
$ vendor/bin/rector init
```

Then add in `rector.php` rule to run: 

```php
$rectorConfig->rule(NetteInjectToConstructorInjectionRector::class);
```

Now if I run rector, it crashes with this error:

```bash
$ vendor/bin/rector
```

```
[ERROR] Cannot autowire service "RectorNette\Rector\Property\NetteInjectToConstructorInjectionRector": argument        
         "$propertyUsageAnalyzer" of method "__construct()" references class                                            
         "RectorNette\NodeAnalyzer\PropertyUsageAnalyzer" but no such service exists.   
```
I tried to import composer autoload, to be sure Rector sees that class.

I also tried to add path to rector-nette via `$rectorConfig->autoloadPaths`, but with same restult.

## Expected Behaviour

I would expoect that there will be no error and rector runs the rule.

## Notes

I know that its not current version of Rector, but that rector-nette is not updated for newer ones.

Thanks for such a good tool Rector, it's awesome! :-)

**Comment by TomasVotruba** [comment]
The Nette extension is now standalone community extension, so its services are not loaded in Rector core.


You have to register the services from extensions too. Something like:

```php
// rector.php

$rectorConfig->import(__DIR__. '/vendor/efabrica-team/rector-nette/config/config.php');
```

**Comment by EdaCZ** [comment]
Cool, it works fine now, thanks!
