### ISSUE TITLE
Getting memory usage under control

### ISSUE THREAD

**Issue by raymondschouten** [rectorphp/rector#7980]
I'm using Rector 0.17.0 on my very large Symfony project (> 25.000 files), but I'm unable to get the memory usage under control. The application contains a fine share of legacy that pushes Rector to its limits, but even directories of simple and small PHP classes are impossible to process with Rector.

For every file Rector is processing, the memory usage increases, up until the point the OS is killing random processes. I'm not able to process more than 250 - 4000 files without pushing the memory limit over 16 GB. No matter what values I use for the parallel processing, or even when I'm not using parallel processing, the memory just keeps rising until it crashes the OS.

I've splitted up the work into 27 (!) pieces, but that causes the fixers not to fix all appropriate files, e.g. method argument changes are not reflected in the unit-tests if these files are in another "chunk", processed in another run.

Does 0.17.0 contain a memory leak, or is there something else that I don't understand? Or is there just so much information gathered by Rector that the memory just can't get released?

Any help is appreciated!
Raymond

**Comment by samsonasik** [comment]
This may same with issue https://github.com/rectorphp/rector/issues/7973 , could you try disable `AddDefaultValueForUndefinedVariableRector` ?

```php
$rectorConfig->skip([
     \Rector\Php56\Rector\FunctionLike\AddDefaultValueForUndefinedVariableRector::class,
]);
```

**Comment by samsonasik** [comment]
Please try latest dev-main:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

If the issue persist, please provide reproducible test on https://getrector.com/demo/  , or we need simple reproducible code for that that show error, with only 1 or 2 rules, you can provide reproducible github repo, better with github action running

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by raymondschouten** [comment]
@samsonasik, unfortunately neither offered solutions work, even on the `dev-main` branch I'm running out of 16 GB of memory at 3720 files.

**Comment by raymondschouten** [comment]
I've tried https://github.com/rectorphp/rector-src/pull/3722, and that actually works. All files were processed within 12 GB and roughly 20 minutes.

**Comment by samsonasik** [comment]
Thank you for trying, the PR still open, could you comment in that PR what you tried?
