### ISSUE TITLE
How to add arguments to method calls now that MethodCallToAnotherMethodCallWithArgumentsRector is gone

### ISSUE THREAD

**Issue by LordSimal** [rectorphp/rector#7982]
# Question

[MethodCallToAnotherMethodCallWithArgumentsRector was removed in 0.17](https://github.com/rectorphp/rector-src/pull/3777) and now I don't see any way how one can create a rule to do something like:

```
$obj = new \App\MyObject();
$obj->someFunc();
```
to
```
$obj = new \App\MyObject();
$obj->someFunc(1);
```

Or am I missing something?

**Comment by TomasVotruba** [comment]
Hi, your example is adding a new argument, not renaming class + name like the rule you refer.

To handle your use case, use this rule:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#argumentadderrector

**Comment by LordSimal** [comment]
Thanks for responding so quickly 🙇🏻 
Sorry, I didn't make my example clear enough.

To show the exact example we want to transform
https://github.com/cakephp/upgrade/blob/5.x/tests/test_apps/original/RectorCommand-testApplyChronos3Date/src/Chronos3.php
to
https://github.com/cakephp/upgrade/blob/5.x/tests/test_apps/upgraded/RectorCommand-testApplyChronos3Date/src/Chronos3.php

So in our case the method `date->addYear();` was removed and should be replaced with `date->addYears(1);`

The `addYears()` method already exists on the base class so I don't really wan to add/change that. Therefore I don't think the `ArgumentAdderRector` is the correct approach here.

I though I can first rename the method call via https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renamemethodrector and then just add a `1` to all those method calls but I may be going from the wrong direction.

**Comment by TomasVotruba** [comment]
I see. Thanks for explaning :+1: 

This rule was changin 3 elements at once, which was against the simple-generic rules we want to support. We're trying to make Rector as fast and  accessible as possible before landing 1.0.

Ideally create a new custom rule, to handle your use cases.

**Comment by LordSimal** [comment]
We will make a custom rule then. Thank you very much 🙇🏻
