### ISSUE TITLE
Unexpected output of RenameClassRector

### ISSUE THREAD

**Issue by 050dev** [rectorphp/rector#7986]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main (d3a95b)     |
| Installed as   | composer dependency  |

I was tracking down how to make RenameClassRector correctly rename an imported class in a docblock, when I encountered some unexpected things when playing around.

I have taken the literal example given at https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renameclassrector
and let it process. Later I modified it to my specific use case, see below.

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e01370d4-1c48-420b-860c-6fe2f9b663ca

```php
<?php
namespace App;

use SomeOldClass;

function someFunction(SomeOldClass $someOldClass): SomeOldClass
{
    if ($someOldClass instanceof SomeOldClass) {
        return new SomeOldClass;
    }
}
```

### Responsible rules

* `RenameClassRector`

## Expected Behavior

I expected the output to exactly match the example:

```diff
 namespace App;

-use SomeOldClass;
+use SomeNewClass;

-function someFunction(SomeOldClass $someOldClass): SomeOldClass
+function someFunction(SomeNewClass $someOldClass): SomeNewClass
 {
-    if ($someOldClass instanceof SomeOldClass) {
-        return new SomeOldClass;
+    if ($someOldClass instanceof SomeNewClass) {
+        return new SomeNewClass;
     }
 }
```
However, it produces "**// no change**".
After diving a bit deeper into it, no change actually seems correct, because I read this in the PHP documentation on imports:
> Note that for namespaced names ([..]), the leading backslash is unnecessary and not recommended, as import names must be fully qualified, and are not processed relative to the current namespace.

So the example seems to be using an incorrect import, or the wrong namespace for SomeOldClass.

Okay, but now the fun starts. When adding a docblock with the same old class, that **does** get changed: https://getrector.com/demo/68871302-6a14-4b36-a4d0-ba445313f3d1

And for my real use case/issue, when the old class is in the global namespace, the docblock does **not** get changed:
https://getrector.com/demo/800bad01-c6a7-4019-ad4c-a649ac18ee33
This is preventing me from using rector to upgrade our code for a library we use, which introduced namespaces in the new major version.

**Comment by 050dev** [comment]
@samsonasik That's what I said, the behaviour of rector is correct using the example input, but the example diff in the documentation is faulty and misleading.

You have not commented on the issues involving a docblock (the last two demo links show it), which in my opinion does seem like a bug. But I can file a new issue if you like, maybe I put too much information into this one.

**Comment by samsonasik** [comment]
Feel free to provide a PR to fix documentation on rector-src 

https://github.com/rectorphp/rector-src/blob/91cf7cc721c70ec8914c1bc4855a810bb85b640c/rules/Renaming/Rector/Name/RenameClassRector.php#L49-L62

Then run composer docs ;)
