### ISSUE TITLE
Incorrect behavior of SimplifyRegexPatternRector

### ISSUE THREAD

**Issue by kenjis** [rectorphp/rector#7993]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/0b4c127c-4159-4c99-93ac-92d6f97e5945

```php
<?php

final class DemoFile
{
    public function run()
    {
        echo '[0-9] and \d are a bit different.';
    }
}
```

```diff
@@ -4,6 +4,6 @@
 {
     public function run()
     {
-        echo '[0-9] and \d are a bit different.';
+        echo '\d and \d are a bit different.';
     }
 }
```

### Responsible rules

* `SimplifyRegexPatternRector`

## Expected Behavior

No change.

**Comment by staabm** [comment]
Could you provide a concrete example when \d and [0-9] are not equal - at best as a failing unit test

**Comment by samsonasik** [comment]
@staabm the example is normal string, so must be skipped, when writing tutorial, that will be invalid, also, even regex, /u will result different on unicode support https://3v4l.org/icdLl

**Comment by staabm** [comment]
Thx for the example. My question was about getting the real example of the OP, so we know his use case at hand.

Doing a fix for our own crafted examples might not fix the root problem of the OP

**Comment by samsonasik** [comment]
The Real example is SQL Query in Oracle, in CodeIgniter repo which support unicode https://github.com/codeigniter4/CodeIgniter4/pull/7578/files/f658272c7b06ead493a81ab39d5a49cdf21fdf76#diff-ce2a6b2a2ffc9e574759b96d86f71651654a6c03558008958af8db784d8d5ed5

**Comment by staabm** [comment]
If the OP provides a unit test, fixing it might be as easy as removing this line


https://github.com/rectorphp/rector-src/blob/a4096b224e7bed199991b87f4bdf88ccfbdb8cd9/rules/CodeQuality/Rector/FuncCall/SimplifyRegexPatternRector.php#L25

**Comment by samsonasik** [comment]
I prefer to copy some logic on `ConsistentPregDelimiterRector` that was removed at PR"

https://github.com/rectorphp/rector-src/pull/3797/files#diff-b52d5691f8efd8fdd8b301dd7b8110eb3048ca332e76619f030a6a89f5764278

That will more valid regex detection.

**Comment by TomasVotruba** [comment]
> That will more valid regex detection.

Sounds good :+1:

**Comment by kenjis** [comment]
As you all might know `[a-zA-Z0-9_]` and `\w`, `[\r\n\t\f\v ]` and `\s` are also a bit different in unicode (`/u`).
https://3v4l.org/BqrMK

**Comment by samsonasik** [comment]
@kenjis we may need to fix it one by one:

1. Ensure skip if it has "u" as part of regex identifier
2. Ensure it has correct delimiter

**Comment by samsonasik** [comment]
Ref https://github.com/rectorphp/rector-src/pull/4322 for detect regex string
