### ISSUE TITLE
 Undefined constant Rector\Set\ValueObject\SetList::PSR_4

### ISSUE THREAD

**Issue by mirolendy** [rectorphp/rector#7995]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| 0.17.1            |  came up when we updated from 0.17.0          |

```
> rector --ansi --no-progress-bar


 [ERROR] Undefined constant Rector\Set\ValueObject\SetList::PSR_4


Script rector --ansi --no-progress-bar handling the rector:fix event returned with error code 1
```

I tried running it with debug but error comes up immediately.

**Comment by samsonasik** [comment]
`SetList::PSR_4` is removed.

**Comment by mirolendy** [comment]
👍 I didn't expect a patch version to have BC change, will remove it from our rector sets

**Comment by TomasVotruba** [comment]
@mirolendy Understood. This was to avioid multiple minor releases in a row. 

We're working on getting to Rector 1.0 https://github.com/rectorphp/rector/issues/7854, that fix few design flaws and part of Rector that were never used or worker correctly or is much better handled by PHPStan. Expect more to come, but less and less as we get closer to stable version :) thanks for bearing with us :pray:
