### ISSUE TITLE
init command not found

### ISSUE THREAD

**Issue by tweidman-ispot** [rectorphp/rector#7997]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| init error | e.g. v0.17.1             |

The init command no longer functions.

## Expected Behaviour

init steps to create rector.php

**Comment by samsonasik** [comment]
I am on mobile, you should can just run `vendor/bin/rector` and it will ask to generate config if not defined, see

https://github.com/rectorphp/rector/blob/708954a81f66f92da14d0e353d3e348f13ec9730/src/Configuration/ConfigInitializer.php#L53-L54

**Comment by tweidman-ispot** [comment]
That doesn't work on 0.17.1; if I rollback to 0.17.0 it works :)

**Comment by tweidman-ispot** [comment]
Ah  that was it; old docs still mention using init.

**Comment by samsonasik** [comment]
Feel free to provide a PR patch to fix the docs at 

https://github.com/rectorphp/getrector-com/blob/main/resources/docs/introduction.md

**Comment by tweidman-ispot** [comment]
PR Opened https://github.com/rectorphp/getrector-com/pull/1410
