### ISSUE TITLE
Incorrect behavior of RestoreDefaultNullToNullableTypePropertyRector

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7998]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/492d4ef9-bfd2-4a66-9f64-376697f98ad2

```php
<?php

final readonly class A
{
    public B|null $display;

    public function __construct(
        string|null $display = null,
    ) {
        if ($display === null) {
            $this->display = null;
        } else {
            $this->display = $display;
        }
    }
}
```

### Responsible rules

* `RestoreDefaultNullToNullableTypePropertyRector`

## Expected Behavior

1) it shouldn't add default values to readonly properties https://3v4l.org/TLaUT#v8.2.7
2) The property is initialized in constructor so it should't try to add a default value

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
@simPod if you have time, could you try provide a patch? It should be a matter of check:

```php
        if ($node->isReadonly()) {
            return null;
        }
```

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-src/pull/4479
