### ISSUE TITLE
MSSQL Support

### ISSUE THREAD

**Issue by joaoribeiro-controlink** [rectorphp/rector#8002]
# Feature Request
I have a project in PHP5.6 using MSSQL extension, but with the time MSSQL Extension has been upgraded and no longer uses the same functions has mssql_query been removed on PHP 7.0 and now is sqlsrv_query with differents params I think.

It would be nice that Rector support the upgrade of this type of extension, is this already possible? If yes anyone know how to do it?

**Comment by TomasVotruba** [comment]
Hi, this would require a full custom set, like mysql to mysqli is. 
Feel free to contribute it :+1:  We can will guide you

**Comment by Fairydx** [comment]
> Hi, this would require a full custom set, like mysql to mysqli is. Feel free to contribute it 👍 We can will guide you

If you can help me how to do it I can try to create a custom set, i'm new using rector

**Comment by joaoribeiro-controlink** [comment]
@TomasVotruba, so how can I create a full custom set?

**Comment by TomasVotruba** [comment]
The best would be to mimic the idea behind mysql to mysqli set: https://github.com/rectorphp/rector-src/blob/main/config/set/mysql-to-mysqli.php

Here is the docs for creating a new rule: https://getrector.com/documentation/custom-rule

**Comment by Fairydx** [comment]
@TomasVotruba I'm not understanding what I need to do to create the set file, I forked rector-src but I dont understand what I need to do to create that set file

**Comment by Fairydx** [comment]
Hey @TomasVotruba ,
Can you give me some ligths on this?

**Comment by TomasVotruba** [comment]
Hey, the read of documentation is really needed before making any rule: https://github.com/rectorphp/rector/issues/8002#issuecomment-1596768417

It contains all important pieces to start. 
You can inspire at other projects like https://github.com/driftingly/rector-laravel


Closing as original issue is answered and this is rather community package that should be handled out of Rector core.
