### ISSUE TITLE
Rector is not showing any issues with file, but on https://getrector.com/demo/, it shows correct fix

### ISSUE THREAD

**Issue by 7thstorm** [rectorphp/rector#8003]
Rector version: Rector 0.17.1
Rules:

```
    <?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList; // added

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/latest-06-169-2023',
    ]);

    // Skip certain paths
   

    // configure parallel processing
    $rectorConfig->parallel(
        $seconds = 600,
        $maxNumberOfProcess = 10,
        $jobSize = 16
    );

    // register a single rule
    //$rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    // define sets of rules
    $rectorConfig->sets([
        SetList::PHP_74,
        SetList::PHP_80,
        SetList::PHP_81,
        SetList::PHP_82,
    ]);
};

```

command used: `php vendor\bin\rector process connect\mysql.php --dry-run -vvv --output-format=json > rector_output.txt`

Output file contents:
```
{
    "totals": {
        "changed_files": 0,
        "errors": 0
    }
}
```

Running it on 
https://getrector.com/demo/

correctly identifies the issue

`https://getrector.com/demo/001b7746-c2d7-4f44-8a92-bce7e8291aa9`

What am I doing wrong?

**Comment by samsonasik** [comment]
could you try latest dev-main in case it already resolved?

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

If the issue persist, please provide reproducible test on https://getrector.com/demo/ , or we need simple reproducible code for that that show error, with only 1 or 2 rules, you can provide reproducible github repo, better with github action running

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by 7thstorm** [comment]
OK, figured out the issue. The path to file was incorrect.
It would be better if rector reported "file not found" message, instead of reporting all was well

**Comment by staabm** [comment]
How did you pass the file-path to rector?

**Comment by 7thstorm** [comment]
I'm running this on windows 11 pro.
so I had my folder set in rector.php as:

```
    $rectorConfig->paths([
        __DIR__ . '/my-files',
    ]);
```
    
    I am running from a folder that has the 'my-files' folder as well as other folders
    
this is the command I originally used:
`php vendor\bin\rector process \subfolder1\index.php --dry-run -vvv --output-format=json > rector_output.txt`

I assumed that since I had the rector dir set, I would not have to use that in the path, but I was wrong. When I used the following, it worked:

`php vendor\bin\rector process \my-files\subfolder1\index.php --dry-run -vvv --output-format=json > rector_output.txt`

However, I think it makes sense for rector to let us know if the file or path was not found, instead of returning 
`[OK] Rector is done!`

It took me an hour of troubleshooting to realize it was not finding the file
