### ISSUE TITLE
Incorrect behavior of PreferPHPUnitThisCallRector

### ISSUE THREAD

**Issue by JohJohan** [rectorphp/rector#8008]
# Bug Report

self calls are also replaced in static functions and i get the message `Using '$this' when not in object context`

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/88b4fbae-1dc0-4d58-9f1e-42cee2efbaa2

```php
<?php

use PHPUnit\Framework\TestCase;

abstract class AbstractTestCase extends TestCase
{
    protected static function genericAssert(): void
    {
        self::assertTrue(true);
    }
}
```

### Responsible rules

* `PreferPHPUnitThisCallRector`

## Expected Behavior

I would expect it not to change because i get the following message `Using '$this' when not in object context`

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. Could you send a failing test fixture and a fix in there?

**Comment by samsonasik** [comment]
@JohJohan the `StaticCall` is always inside `FunctionLike`, whether it is a `ClassMethod`, `Closure`, so should be something like this:

```diff
+        $isStatic = false;
-        $this->traverseNodesWithCallable($node, function (Node $node) use (&$hasChanged): ?MethodCall {
+        $this->traverseNodesWithCallable($node, function (Node $node) use (&$hasChanged, &$isStatic): ?MethodCall {
+           $isStatic = ($node instanceof ClassMethod && $node->isStatic()) || ($node instanceof Closure && $node->static === true);
-            if (! $node instanceof StaticCall) {
+            if (! $node instanceof StaticCall || $isStatic) {
                return null;
            }
```

The reference variable `$isStatic` is followed to next found method.

**Comment by JohJohan** [comment]
I can work on this tomorrow, if someone want to pick up before feel free to do so.

**Comment by JohJohan** [comment]
See https://github.com/rectorphp/rector-phpunit/pull/194
