### ISSUE TITLE
Is rector-prefixed still maintained?

### ISSUE THREAD

**Issue by soullivaneuh** [rectorphp/rector#801]
It is indicated that release are automatic. But I see only one release and the master branch is way later than this one.

BTW, why asking to install the prefixed with dev-master version?

**Comment by Soullivaneuh** [comment]
I tried using `composer bin` to install rector, but I still have weird issues like this:

```
vendor/bin/rector process src src-dev tests --level php70 -vvv

Fatal error: Declaration of Rector\Php\Rector\FunctionLike\ExceptionHandlerTypehintRector::refactor(Rector\Php\Rector\FunctionLike\Node $node): ?Rector\Php\Rector\FunctionLike\Node must be compatible with Rector\Contract\Rector\PhpRectorInterface::refactor(PhpParser\Node $node): ?PhpParser\Node in /code/vendor-bin/rector/vendor/rector/rector/packages/Php/src/Rector/FunctionLike/ExceptionHandlerTypehintRector.php on line 72
```

**Comment by TomasVotruba** [comment]
It actually needs a maintainer who uses it and is able to fix that.

**Comment by Soullivaneuh** [comment]
Did you give a try to https://github.com/humbug/php-scoper ?

This allow you to provide a `.phar` with always auto-prefix without more maintenance.

See also https://github.com/sebastianbergmann/phpunit/issues/2015

**Comment by TomasVotruba** [comment]
Have you checked the link I sent? :) 

https://github.com/rectorphp/prefixer/blob/90e7e14ceef6763c062286f359817c985a1e2812/composer.json#L10

**Comment by Soullivaneuh** [comment]
I didn't, booh one me. :-(

**Comment by TomasVotruba** [comment]
Anyway, if you'd like to help with that, I'd prepare a README with what I know and how the build should work.

**Comment by Soullivaneuh** [comment]
I have to find some free-time. But in anyway, the documentation would be welcome for me or anyone else. :wink:

**Comment by TomasVotruba** [comment]
Of course, it would just increase motivation knowing it will be used right away :smile:

**Comment by TomasVotruba** [comment]
Closing as answered

**Comment by TomasVotruba** [comment]
We have working version now :+1: 

See https://github.com/rectorphp/rector-prefixed
