### ISSUE TITLE
Command "init" is not defined.

### ISSUE THREAD

**Issue by fredoh91** [rectorphp/rector#8010]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.17.1 |

## Minimal Code Causing Issue

When I enter the following command in a shell :

`vendor/bin/rector init`

I have the follow message and the rector.php file is not generated :

`Command "init" is not defined.`

## Expected Behaviour

generating the rector file

If I use rector v0.17.0 or v0.16.0, there is no problem with this functionality.

**Comment by samsonasik** [comment]
You no longer need `init`, you can run `vendor/bin/rector` and it will show question to generate rector.php, see the documentation  https://getrector.com/documentation

**Comment by TomasVotruba** [comment]
Hi, this rule has been deprecated in previous version, and its not needed anymore.

When you run Rector first time, it will generate the config for you :+1: 

```bash
vendor/bin/rector 
```

**Comment by fredoh91** [comment]
It is not a bug, I "bad-reading" the documentation : https://getrector.com/documentation#first-run

thank you

**Comment by bertramakers** [comment]
Ended up here because I ran into the same issue following the documentation in the README, that should probably be updated as well: https://github.com/rectorphp/rector#running-rector

**Comment by samsonasik** [comment]
@bertramakers could you create doc patch for it? You can create PR to rector-src build https://github.com/rectorphp/rector-src/blob/main/build/target-repository/README.md

Thank you.
