### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector

### ISSUE THREAD

**Issue by Spomky** [rectorphp/rector#8012]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.17.1      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/71ddafa6-c5f7-49b7-a33f-a80fdb945510

```php
<?php

final class DemoFile
{
    private string $env;
    
    public function __construct()
    {
        $this->env = 'default';
    }
    
    public function getEnv(): string
    {
        return $this->env;
    }
    
    public static function create(string $env): self
    {
        $object = new self();
        $object->env = 'not default';
        return $object;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

The property `$env` should not be considered as `readonly` as it is modified in a specific method.

**Comment by Jean85** [comment]
I got the same bug multiple times in my project, due to the heavy usage of named constructors.
I've created a fixture against this in #4356
