### ISSUE TITLE
Incorrect behavior of GetMockBuilderGetMockToCreateMockRector

### ISSUE THREAD

**Issue by JohJohan** [rectorphp/rector#8013]
# Bug Report

Should GetMockBuilderGetMockToCreateMockRector not replace `getMockBuilder` when calling `setMethods` then we can just replace to calling `onlyMethods`

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/277ff68b-0eed-4272-9d38-fbdd8c7fff67

```php
<?php

use PHPUnit\Framework\TestCase;

final class SomeTest extends TestCase
{
    public function testSome()
    {
        $builderIncorrect = $this
            ->getMockBuilder(ConstraintViolationBuilder::class)
            ->disableOriginalConstructor()
            ->setMethods(['addViolation'])
            ->getMock();
        
         $builderCorrect = $this
            ->getMockBuilder(ConstraintViolationBuilder::class)
            ->disableOriginalConstructor()
            ->onlyMethods(['addViolation'])
            ->getMock();
    }
}
```

### Responsible rules

* `GetMockBuilderGetMockToCreateMockRector`

## Expected Behavior
I think `$builderIncorrect` should be exactly the same as `$builderCorrect` after a rector run because then no deprecated function is called? Now my code broke because its not defining the correct functions and i get errors like: `Error: Call to a member function addViolation() on null`.

**Comment by samsonasik** [comment]
It seems duplicated with https://github.com/rectorphp/rector-phpunit/issues/86 ,the issue was still there.

**Comment by JohJohan** [comment]
Closing as its duplicated see https://github.com/rectorphp/rector-phpunit/issues/86
