### ISSUE TITLE
Incorrect behavior of Php4ConstructorRector

### ISSUE THREAD

**Issue by mpesari** [rectorphp/rector#8014]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/dfda03fb-f728-475b-b1ca-3492e9a82857

```php
<?php

trait Message
{
    /**
     * Trait method is incorrectly interpreted as PHP 4 style constructor
     */
    public function message(string $message): void
    {
        print $message;
    }
}

final class DemoFile
{
    use Message;
}
```

### Responsible rules

* `Php4ConstructorRector`

## Expected Behavior

I think Rector should do nothing here.

(Here is a slight variation where I think the rule should be applied: https://getrector.com/demo/5be1b020-c8f3-41f4-ac70-b8fa20316925)

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
@mpesari It seems `if (!$scope->isInClass()) {` check is not reliable when consumed from trait:

https://github.com/rectorphp/rector/blob/f8aedc65589d49a7b5b9d7897a93cca7e943998f/rules/Php70/Rector/ClassMethod/Php4ConstructorRector.php#L84

I think the best way is to just skip the trait, use `Class_` as node types instead, then loop the `$node->getMethods()`, you can use this for refererence

https://github.com/rectorphp/rector-src/blob/914e0e83543d2428d6eec6f49c800f9ed94c351a/rules/CodeQuality/Rector/ClassMethod/LocallyCalledStaticMethodToNonStaticRector.php#L88

Could you try provide a patch for it? Thank you.

**Comment by mpesari** [comment]
Thanks, I'll try to fix it.
