### ISSUE TITLE
Incorrect behavior of RemoveUnusedConstructorParamRector

### ISSUE THREAD

**Issue by mcampbell508** [rectorphp/rector#8015]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `v0.17.1`             |

The bug seems to occur when there is an unused parameter in the constructor but then the constructor has subsequent arguments that are used within the class.  

### Config

```
<?php

use Rector\Config\RectorConfig;
use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedConstructorParamRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rule(RemoveUnusedConstructorParamRector::class);
};
```

https://getrector.com/demo/c55a531d-b617-466a-b6be-8b698289d61e

## Expected Behaviour

I believe Rector should be removing all parameters, regardless of whether any subsequent used parameters exist in the constructor method. 

### Demo Result (no changes made)

```
<?php

final class DemoFile
{
    protected ExampleOne $paramOne;
    protected ExampleTwo $paramTwo;
    protected ExampleThree $paramThree;

    public function __construct(
        ExampleOne $paramOne,
        ExampleTwo $paramTwo,
        ExampleThree $paramThree
    ) {
        $this->paramOne = $paramOne;
        $this->paramThree = $paramThree;
    }
}
```

### Expectation of rule

```diff
<?php

final class DemoFile
{
    protected ExampleOne $paramOne;
    protected ExampleTwo $paramTwo; // this would remain but could be covered by other rules
    protected ExampleThree $paramThree;

    public function __construct(
        ExampleOne $paramOne,
-       ExampleTwo $paramTwo,
        ExampleThree $paramThree
    ) {
        $this->paramOne = $paramOne;
        $this->paramThree = $paramThree;
    }
}
```

## Pull Request

I can attempt to submit a pull request if I get some time to do so, but I have never contributed to the Rector code base before :-), so this may take time.

## Thanks

Rector looks like an awesome tool. Massive thank you to the author and contributors.

**Comment by samsonasik** [comment]
This is expected to avoid BC break caused by remove param in the middle.
