### ISSUE TITLE
Incorrect behavior of CountOnNullRector

### ISSUE THREAD

**Issue by markdorison** [rectorphp/rector#8016]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/4239ac15-dcf4-4803-a463-bfe14312e1f2

```php
<?php

trait SitesConfigTrait
{
    public function getAllSiteNames(): array
    {
        return array_keys($this->getAllSitesConfig());
    }

    public function getSitesCount(): int
    {
        return count($this->getAllSitesConfig());
    }

}
```

### Responsible rules

* `CountOnNullRector`

## Expected Behavior

I expect no issue on this line since the called method `getAllSiteNames()` specifies a return type of `array`, but rector is behaving as if it could return NULL.

**Comment by samsonasik** [comment]
First, there is no method named `getAllSitesConfig` in your code.

Second, i think you can just skip the rule, trait doesn't have context of `$this`

**Comment by markdorison** [comment]
Hey @samsonasik!

> First, there is no method named `getAllSitesConfig` in your code.

I stripped out a number of helper methods to get the most concise example that shows the issue.

> 
> Second, i think you can just skip the rule, trait doesn't have context of `$this`

Isn't it evaluated in the context of the class that uses the trait?

**Comment by samsonasik** [comment]
My knowledge is very limited on that area :) 

Rector uses PHPStan to detect type, `$this` can goes to never type on trait, even on phpstan usage itself, eg:

https://github.com/samsonasik/ErrorHeroModule/blob/925194ded4ceed5bac42007a058507d513a16bcc/phpstan-baseline.neon#L4-L6

Yes, I used trait in the past, and I don't recommend it :)

**Comment by TomasVotruba** [comment]
As @samsonasik stated: trait have no clue about their context in other code and should be used only with local context. 
Static analysis cannot know what the type is.

<br>

I've just added the skip for traits, as their values are unpredictable. But your code should be changed for local context or better composition, to avoid null errors that might happen there.
