### ISSUE TITLE
Try Rector behavior on error

### ISSUE THREAD

**Issue by Hembi** [rectorphp/rector#8023]
# Bug Report
https://getrector.com/demo
If I provide a wrong PHP code to the editor (by mistake while I copy or change it), it returns "Provide a valid PHP code" error message and reset the whole form to default. I have to start the whole process again.

## Expected Behaviour

Provide error message and keep the changes in textareas.

**Comment by samsonasik** [comment]
The site repo is on https://github.com/rectorphp/getrector-com

Feel free to provide improvement PR there ;)
