### ISSUE TITLE
Incorrect behavior of LongArrayToShortArrayRector

### ISSUE THREAD

**Issue by Hembi** [rectorphp/rector#8024]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/6c646d47-27a5-4acc-b6ab-5aef5db90d22

```php
<?php

final class DemoFile
{
    public $testarray = array(
            'A' => array(
                'name' => '{test}',
                'class' => 'btn btn-xs disabled'
            ) ,
            'B' => array(
                'name' => '{test2}',
                'class' => 'btn btn-xs disabled'
            ) ,
        );
}
```

### Responsible rules

* `LongArrayToShortArrayRector`

## Expected Behavior

Add/keep line breaks.
```php
public $testarray = [
            'A' => [
                'name' => '{test}',
                'class' => 'btn btn-xs disabled'
            ] ,
            'B' => [
                'name' => '{test2}',
                'class' => 'btn btn-xs disabled'
            ] ,
        ];
```

**Comment by samsonasik** [comment]
That's expected as array need to be reprinted to make short array syntax.

You can use coding standard tool for that.
