### ISSUE TITLE
`FluentChainMethodCallNodeAnalyzer` was removed in 0.17.1 - whats the replacement?

### ISSUE THREAD

**Issue by LordSimal** [rectorphp/rector#8027]
# Question

as can be seen in https://github.com/cakephp/upgrade/actions/runs/5317567018/jobs/9628220844?pr=239#step:9:25 we have rector rules which use `\Rector\Defluent\NodeAnalyzer\FluentChainMethodCallNodeAnalyzer` but this class has been removed in 0.17.1 as can be seen here: https://github.com/rectorphp/rector/compare/0.17.0...0.17.1#diff-1ab632537c0c79a31634cd3bafecb64343a98a8a0fc9170517efc4dc108ed37a

So my question would be: What's the recommended replacement?

**Comment by samsonasik** [comment]
I guess you can copy the class as service in your package.

**Comment by LordSimal** [comment]
Thanks for the quick answer. Then we will do exactly that 😁
