### ISSUE TITLE
[ERROR] Rector\Php80\ValueObject\NestedAnnotationToAttribute::__construct(): Argument #1 ($tag) must be of type string,          array given

### ISSUE THREAD

**Issue by bcag2** [rectorphp/rector#8030]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.2             |

Migration symfony project from v5 to v6.3.1. I first use rector to convert annotation to attribute on controller, worked fine, thanks.
Then I want to convert annotation to attribute on entities. So I copy code from https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#nestedannotationtoattributerector and try to run it with basic command `vendor/bin/rector process src --dry-run` and it returns `[ERROR] Rector\Php80\ValueObject\NestedAnnotationToAttribute::__construct(): Argument #1 ($tag) must be of type string,          array given`
If I edit vendor/rector/rector/rules/Php80/ValueObject/NestedAnnotationToAttribute.php file where class is define, I saw than first argument, $tag has String type, so it is coherent I have this error because call example with `new NestedAnnotationToAttribute([
                new AnnotationPropertyToAttributeClass` doesn't math.

**Comment by bcag2** [comment]
Hope it is enough :  
https://getrector.com/demo/9a734f58-5169-436a-9f14-0352b34f9ebb

**Comment by samsonasik** [comment]
Reproduced at https://getrector.com/demo/245a07d6-ad51-43df-8d33-4aaa050a8ac0

It seems documentation issue, which the arg should be string instead, see https://getrector.com/demo/7bd7c24c-ba49-4b97-8402-578a9cf9ce95

Could you create a documentation patch PR for it, should be at https://github.com/rectorphp/rector-src/blob/205df9013af5e05034441aa6088599532f5fef05/rules/Php80/Rector/Property/NestedAnnotationToAttributeRector.php#L86-L93

then, you can run `composer docs` to generate documentation;

**Comment by samsonasik** [comment]
@TomasVotruba the issue seems on documentation generation on the following sample code:

```php
                [
                    [
                        new NestedAnnotationToAttribute('Doctrine\ORM\Mapping\JoinTable', [
                            new AnnotationPropertyToAttributeClass('Doctrine\ORM\Mapping\JoinColumn', 'joinColumns'),
                            new AnnotationPropertyToAttributeClass(
                                'Doctrine\ORM\Mapping\InverseJoinColumn',
                                'inverseJoinColumns'
                            ),
                        ]),
                    ],
                ]
```

Got:

```php
    $rectorConfig->ruleWithConfiguration(NestedAnnotationToAttributeRector::class, [
        [
            new NestedAnnotationToAttribute([
                new AnnotationPropertyToAttributeClass('Doctrine\ORM\Mapping\JoinColumn', 'joinColumns', false),
                new AnnotationPropertyToAttributeClass('Doctrine\ORM\Mapping\InverseJoinColumn', 'inverseJoinColumns', false),
            ], 'Doctrine\ORM\Mapping\JoinTable', false),
        ],
    ]);
```

which should be:

```php
    $rectorConfig->ruleWithConfiguration(NestedAnnotationToAttributeRector::class, [
        [
            new NestedAnnotationToAttribute('Doctrine\ORM\Mapping\JoinTable', [
                            new AnnotationPropertyToAttributeClass('Doctrine\ORM\Mapping\JoinColumn', 'joinColumns'),
                            new AnnotationPropertyToAttributeClass(
                                'Doctrine\ORM\Mapping\InverseJoinColumn',
                                'inverseJoinColumns'
                            ),
                        ]),
    ]);
```

**Comment by samsonasik** [comment]
you probably missing use statement ? try this sample config:

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Php80\Rector\Property\NestedAnnotationToAttributeRector;
use Rector\Php80\ValueObject\AnnotationPropertyToAttributeClass;
use Rector\Php80\ValueObject\NestedAnnotationToAttribute;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(NestedAnnotationToAttributeRector::class, [
        /** @see https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/attributes-reference.html#joincolumn-inversejoincolumn */
        new NestedAnnotationToAttribute('Doctrine\ORM\Mapping\JoinTable', [
            new AnnotationPropertyToAttributeClass('Doctrine\ORM\Mapping\JoinColumn', 'joinColumns'),
            new AnnotationPropertyToAttributeClass(
                'Doctrine\ORM\Mapping\InverseJoinColumn',
                'inverseJoinColumns',
                true
            ),
        ]),

        new NestedAnnotationToAttribute('Doctrine\ORM\Mapping\Table', [
            new AnnotationPropertyToAttributeClass('Doctrine\ORM\Mapping\Index', 'indexes'),
            new AnnotationPropertyToAttributeClass('Doctrine\ORM\Mapping\UniqueConstraint', 'uniqueConstraints'),
        ]),

        /** @see https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#joincolumns */
        new NestedAnnotationToAttribute('Doctrine\ORM\Mapping\JoinColumns', [
            new AnnotationPropertyToAttributeClass('Doctrine\ORM\Mapping\JoinColumn'),
        ], true),
    ]);
};

```

**Comment by bcag2** [comment]
It was the missing _true_ after _'inverseJoinColumns'_   
no more errors but I was surprised that only one entity (src/Entity/User.php) should be modified, not all my entities !

**Comment by samsonasik** [comment]
we need failing fixture PR test for that at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/Property/NestedAnnotationToAttributeRector/Fixture

If there is specific config that failure, you can add at https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php80/Rector/Property/NestedAnnotationToAttributeRector/config/configured_rule.php

**Comment by bcag2** [comment]
By using https://symfonycasts.com/screencast/symfony6-upgrade/annotations-to-attributes sample :  
```php
<?php

declare(strict_types=1);
// https://symfonycasts.com/screencast/symfony6-upgrade/annotations-to-attributes
use Rector\Config\RectorConfig;
use Rector\Doctrine\Set\DoctrineSetList;
use Rector\Symfony\Set\SensiolabsSetList;
use Rector\Symfony\Set\SymfonySetList;

return function (RectorConfig $rectorConfig): void {
	$rectorConfig->paths([
		__DIR__ . '/src',
	]);
	$rectorConfig->sets([
		DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
		SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES
	]);
};
```
IT WORKS
I just removed line 16 `SensiolabsSetList::FRAMEWORK_EXTRA_61` which generate error :  
`[ERROR] Undefined constant Rector\Symfony\Set\SensiolabsSetList::FRAMEWORK_EXTRA_61`

**Comment by samsonasik** [comment]
That seems old post from symfony cast website. You may need to report there :)
