### ISSUE TITLE
Incorrect behavior of DowngradeAttributeToAnnotationRector

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#8032]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

(I copied the failing code from `symfony/dependency-injection`: https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/DependencyInjection/Attribute/When.php).

See https://getrector.com/demo/e8d8bbd8-ca7a-4206-9be8-8a303ea273a7

```php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\DependencyInjection\Attribute;

#[\Attribute]
class When
{
    public function __construct(
        public string $env,
    ) {
    }
}
```

### Responsible rules

* `DowngradeAttributeToAnnotationRector`

## Expected Behavior

The downgrade is not working: `#[\Attribute]` should be removed, but it is not.

This bug seems to happen only when the attribute class is `\Attribute` (i.e. `Attribute` in the global space). If I change it to `Attribute` (i.e. a class `Attribute` under namespace `Symfony\Component\DependencyInjection\Attribute`), or `\SomeAttribute`, then it works fine:

- https://getrector.com/demo/7ccd9ccf-4aab-440c-96b0-d355726be5d6
- https://getrector.com/demo/0e4ea461-a116-4687-a605-86f4afe643f7

**Comment by leoloso** [comment]
Btw, `symfony/polyfill-php80` polyfills the `Attribute` class:

[vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php](https://github.com/symfony/polyfill-php80/blob/main/Resources/stubs/Attribute.php)

(might this be useful?)

**Comment by leoloso** [comment]
@samsonasik Ok done

**Comment by TomasVotruba** [comment]
As @samsonasik explained https://github.com/rectorphp/rector-downgrade-php/pull/138#issuecomment-1614697055, 
this is valid on PHP 7.4-, as treated as comment: https://3v4l.org/EnckO#v7.4.26
