### ISSUE TITLE
Incorrect behavior of ReadOnlyClassRector

### ISSUE THREAD

**Issue by fsok** [rectorphp/rector#8037]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/97530d52-c91e-4dec-96e8-5e9dbd66e9c1

```php
<?php

final class DemoFile extends UnkownClass
{
    public function __construct(private readonly string $property)
    {
    }
    
    public function run()
    {
  		echo $this->property;
    }
}
```

### Responsible rules

* `ReadOnlyClassRector`

## Expected Behavior

If a parent class cannot be resolved by rector `ReadOnlyClassRector`should skipped, because it cannot be determined if the parent class is declared as readonly.

I am not sure why the class can't be resolved. I noticed this in controllers extending from [AbstractFOSRestController](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3.x/Controller/AbstractFOSRestController.php).

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by fsok** [comment]
> We'll need a failing test case in a pull-request, so we have it covered in Rector.

I created https://github.com/rectorphp/rector-src/pull/4407

**Comment by TomasVotruba** [comment]
Thank you @fsok :+1:
