### ISSUE TITLE
Incorrect behavior of DataProviderAnnotationToAttributeRector, CoversAnnotationWithValueToAttributeRector

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#8038]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/eca6abc7-ca07-4231-8419-0c42968e649d

```php
<?php

final class Testing extends \PHPUnit\Framework\TestCase
{
    /**
     * @covers SomeClass::method
     *
     * @dataProvider generatorInput
     */
    public function testSomething(mixed $expected)
    {
        $this->assertSame($expected, 'actual');
    }
}
```

### Responsible rules

* `DataProviderAnnotationToAttributeRector`

* `CoversAnnotationWithValueToAttributeRector`

## Expected Behavior
```diff
@@ -1,12 +1,9 @@
 <?php
 
 final class Testing extends \PHPUnit\Framework\TestCase
 {
-    /**
-     * @covers SomeClass::method
-     *
-     * @dataProvider generatorInput
-     */
+    #[\PHPUnit\Framework\Attributes\CoversClass(SomeClass::method)]
+    #[\PHPUnit\Framework\Attributes\DataProvider('generatorInput')]
     public function testSomething(mixed $expected)
     {
         $this->assertSame($expected, 'actual');
```

**Comment by gisostallenberg** [comment]
Apparently the order in which the rules are added matters.

**Comment by samsonasik** [comment]
It seems array_merge need to be used at

https://github.com/rectorphp/rector-phpunit/blob/c6bf48b06e04ad2eb4d9f5a3c808eb0bd09ff6f1/src/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php#L102

to avoid existing attrGroups replaced:

```diff
- $node->attrGroups = $coversAttributeGroups;
+ $node->attrGroups = array_merge($node->attrGroups, $coversAttributeGroups);
```

You can add fixture test for append existing attribute at 

https://github.com/rectorphp/rector-phpunit/tree/main/tests/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture

Could you try provide a patch for it? Thank you.

**Comment by TomasVotruba** [comment]
I was just checking this repository, so I took the liberty to fix it :)
