### ISSUE TITLE
Incorrect behavior of RemoveUnusedVariableAssignRector, RemoveAlwaysTrueIfConditionRector, RemoveUnusedPrivatePropertyRector

### ISSUE THREAD

**Issue by kenjis** [rectorphp/rector#8039]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/7ff8493e-7d57-455c-9160-61077d6d036e

```php
<?php

class Sample
{
    private array $segments = [];
    private array $params   = [];
    private ?int $paramPos  = 1;

    public function foo(string $uri)
    {
        $this->params   = [];
        $this->segments = $this->baz($uri);

        $this->bar();

        $params = $this->params;

        if ($params === []) {
            $this->paramPos = null;
        }

        var_dump($this->paramPos);
    }

    private function bar()
    {
        if (mt_rand(0, 1) === 0) {
            $this->params = $this->segments;
        }
    }

    private function baz(string $uri)
    {
        $segments = explode('/', $uri);
        $segments = array_filter($segments, static fn ($segment) => $segment !== '');

        return array_values($segments);
    }
}
```

### Responsible rules

* `RemoveUnusedVariableAssignRector`

* `RemoveAlwaysTrueIfConditionRector`

* `RemoveUnusedPrivatePropertyRector`

## Expected Behavior

No change.

**Comment by samsonasik** [comment]
@kenjis the `$this->bar()` seems the issue here, as it cause side effect that PHPStan can't detect. I think the solution is to add `@var` above it, something like:

```php
/** @var non-empty-array<int, string>|array<int, string> $params */
        $params = $this->params;
```


 see https://getrector.com/demo/93fe0739-0ee0-4587-9456-1c6901384da8

**Comment by samsonasik** [comment]
I am closing it as resolved with `@var` usage ;)
