### ISSUE TITLE
[Error] Cannot declare interface PhpParser\NodeVisitor, because the name is already in use

### ISSUE THREAD

**Issue by ERuban** [rectorphp/rector#8041]
# Question
Hey, Tomas!
We have [our own package with our own rector rule](https://github.com/eonx-com/easy-quality)s and tests for it. All works fine before I have tried to add `phpmetrics/phpmetrics` into it.
After installing this packages I got the error on executing rector rules tests:
```
Fatal error: Cannot declare interface PhpParser\NodeVisitor, because the name is already in use in [...]/easy-quality/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor.php on line 6
```

So, to reproduce it: 
- install `eonx-com/easy-quality` 
- `composer require phpmetrics/phpmetrics` 
- `vendor/bin/phpunit --testsuit Rector`

Do you have any ideas why it happens and how to fix it?

**Comment by samsonasik** [comment]
The `phpmetrics/phpmetrics` is using :

```php
"files": ["./src/functions.php"]
```

https://github.com/phpmetrics/PhpMetrics/blob/4b77140a11452e63c7a9b98e0648320bf6710090/composer.json#L31

in composer.json, which loaded too early as files already included. 

You may need to create PR to `phpmetrics/phpmetrics` to move to dedicated file to be loaded in PSR-4 based, or probably classmap at least.

**Comment by ERuban** [comment]
Oh, got it.
Thank you  @samsonasik

**Comment by samsonasik** [comment]
Ok, I am closing it as the solution provided ;)
