### ISSUE TITLE
`System error: "Trying to replace statement (Stmt_Return) with expression (Expr_BooleanNot). Are you missing a Stmt_Expression wrapper?`

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#8044]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.3            |

Not sure which rule it is exactly. But the following snippet causes an internal PHPParser error.

```php
<?php

namespace App;

use Illuminate\Support\Facades\Auth;
use User;

class Foo
{
    public function getUser(?User $user = null): ?User
    {
        return $user ?? (Auth::check() ? Auth::user() : null);
    }


    public function doFoo(
        ?User $user = null
    ): bool {
        $user = $this->getUser($user);

        if (!$user) {
            return false;
        }

        return $user->isFoo() || $user->isBar();
    }

}
```

Error: `System error: "Trying to replace statement (Stmt_Return) with expression (Expr_BooleanNot). Are you missing a Stmt_Expression wrapper?`

## Minimal PHP Code Causing Issue

https://getrector.com/demo/44c449cb-8ecf-420a-b7ef-00018292a101

## Expected Behaviour

No errors.

**Comment by samsonasik** [comment]
@TomasVotruba it seems due to removal of autowrap Expr to Stmt on PR:

- https://github.com/rectorphp/rector-src/pull/4466

**Comment by samsonasik** [comment]
Reproduced by combine 4 rules:

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\CodeQuality\Rector\Identical\FlipTypeControlToUseExclusiveTypeRector;
use Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector;
use Rector\EarlyReturn\Rector\Return_\PreparedValueToEarlyReturnRector;
use Rector\EarlyReturn\Rector\Return_\ReturnBinaryOrToEarlyReturnRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rules([
        ExplicitBoolCompareRector::class,
        FlipTypeControlToUseExclusiveTypeRector::class,
        PreparedValueToEarlyReturnRector::class,
        ReturnBinaryOrToEarlyReturnRector::class,
    ]);
};

```

ref https://getrector.com/demo/bd2a99e2-84d2-4f89-afc3-e1c59058e6ed
