### ISSUE TITLE
Timeout on LevelSetList::UP_TO_PHP_81

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#8046]
# Bug Report

I'm running into a timeout in a current bigger project when using `LevelSetList::UP_TO_PHP_81`. It works to `LevelSetList::UP_TO_PHP_74` but `LevelSetList::UP_TO_PHP_80` and `LevelSetList::UP_TO_PHP_81` seems let run into timeout.

## Minimal PHP Code Causing Issue

Currently I'm not yet sure which rules take that long that it ends in a timeout. Already parallel processing is disabled for better debugging.

#### Debugging in work ...

```bash
> @php vendor/bin/rector process --dry-run
    0/1050 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  105/1050 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%
  296/1050 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  28%
  315/1050 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30%
  412/1050 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  39%
  501/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]  47%
  560/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  53%
  614/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  58%
  685/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  65%
  796/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]  75%
  832/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  79%
  884/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░]  84%
  945/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  90%
  972/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  92%
  973/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  92%
  974/1050 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  92%Killed
Script @php vendor/bin/rector process --dry-run handling the lint-rector event returned with error code 137
```

Updated 2: Current breaking down by rules it must have todo with `LevelSetList::UP_TO_PHP_81`.

Slowly now increasing the rules:

```
 - LevelSetList::UP_TO_PHP_53: 3 minutes 55 seconds
 - LevelSetList::UP_TO_PHP_54: 3 minutes 43 seconds
 - LevelSetList::UP_TO_PHP_55: 3 minutes 20 seconds
 - LevelSetList::UP_TO_PHP_56: 3 minutes 48 seconds
 - LevelSetList::UP_TO_PHP_70: 3 minutes 53 seconds
 - LevelSetList::UP_TO_PHP_71: 3 minutes 36 seconds
 - LevelSetList::UP_TO_PHP_72: 4 minutes 5 seconds
 - LevelSetList::UP_TO_PHP_73: 4 minutes 10 seconds
 - LevelSetList::UP_TO_PHP_74: 4 minutes 23 seconds
 - LevelSetList::UP_TO_PHP_80: (killed) 9 minutes 33 seconds
 - LevelSetList::UP_TO_PHP_81: (killed) 17 minutes 20 seconds (timeout) 61 minutes 42 seconds
```

Looks like related to `LevelSetList::UP_TO_PHP_80` now go step by step through:

```
    $rectorConfig->sets([
        SetList::CODE_QUALITY,
        LevelSetList::UP_TO_PHP_74,
    ]);

    // PHP 8.0
    // A: $rectorConfig->rules([StrContainsRector::class, StrStartsWithRector::class, StrEndsWithRector::class, StringableForToStringRector::class, ClassOnObjectRector::class, GetDebugTypeRector::class, RemoveUnusedVariableInCatchRector::class, ClassPropertyAssignToConstructorPromotionRector::class, ChangeSwitchToMatchRector::class, RemoveParentCallWithoutParentRector::class, SetStateToStaticRector::class, FinalPrivateToPrivateVisibilityRector::class, AddParamBasedOnParentClassMethodRector::class, MixedTypeRector::class, ClassOnThisVariableObjectRector::class]);
    // B: $rectorConfig->ruleWithConfiguration(StaticCallToFuncCallRector::class, [new StaticCallToFuncCall('Nette\\Utils\\Strings', 'startsWith', 'str_starts_with'), new StaticCallToFuncCall('Nette\\Utils\\Strings', 'endsWith', 'str_ends_with'), new StaticCallToFuncCall('Nette\\Utils\\Strings', 'contains', 'str_contains')]);
    // nette\utils and Strings::replace()
    // C: $rectorConfig->ruleWithConfiguration(ArgumentAdderRector::class, [new ArgumentAdder('Nette\\Utils\\Strings', 'replace', 2, 'replacement', '')]);
    // @see https://php.watch/versions/8.0/pgsql-aliases-deprecated
    // D: $rectorConfig->ruleWithConfiguration(RenameFunctionRector::class, ['pg_clientencoding' => 'pg_client_encoding', 'pg_cmdtuples' => 'pg_affected_rows', 'pg_errormessage' => 'pg_last_error', 'pg_fieldisnull' => 'pg_field_is_null', 'pg_fieldname' => 'pg_field_name', 'pg_fieldnum' => 'pg_field_num', 'pg_fieldprtlen' => 'pg_field_prtlen', 'pg_fieldsize' => 'pg_field_size', 'pg_fieldtype' => 'pg_field_type', 'pg_freeresult' => 'pg_free_result', 'pg_getlastoid' => 'pg_last_oid', 'pg_loclose' => 'pg_lo_close', 'pg_locreate' => 'pg_lo_create', 'pg_loexport' => 'pg_lo_export', 'pg_loimport' => 'pg_lo_import', 'pg_loopen' => 'pg_lo_open', 'pg_loread' => 'pg_lo_read', 'pg_loreadall' => 'pg_lo_read_all', 'pg_lounlink' => 'pg_lo_unlink', 'pg_lowrite' => 'pg_lo_write', 'pg_numfields' => 'pg_num_fields', 'pg_numrows' => 'pg_num_rows', 'pg_result' => 'pg_fetch_result', 'pg_setclientencoding' => 'pg_set_client_encoding']);
    // E: $rectorConfig->rule(OptionalParametersAfterRequiredRector::class);
    // F: $rectorConfig->ruleWithConfiguration(FunctionArgumentDefaultValueReplacerRector::class, [new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, 'gte', 'ge'), new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, 'lte', 'le'), new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, '', '!='), new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, '!', '!='), new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, 'g', 'gt'), new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, 'l', 'lt'), new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, 'gte', 'ge'), new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, 'lte', 'le'), new ReplaceFuncCallArgumentDefaultValue('version_compare', 2, 'n', 'ne')]);
```

```
PHP 8.0 A: 3 minutes 51 seconds
PHP 8.0 B: 3 minutes 41 seconds
PHP 8.0 C: 3 minutes 58 seconds
PHP 8.0 D: 3 minutes 39 seconds
PHP 8.0 E: 4 minutes 11 seconds
PHP 8.0 F: 3 minutes 47 seconds
```

That seems not run into the timeout errors so the only difference now between the killed on `LevelSetList::UP_TO_PHP_80` and custom `LevelSetList::UP_TO_PHP_74` + PHP 8.0 rule is that I forgot to set `$rectorConfig->phpVersion(PhpVersion::PHP_80);` so rerun A-F again with that definition:

```
PHP 8.0 II:   3 minutes 43 seconds
PHP 8.0 II A: 11 minutes 31 seconds
PHP 8.0 II B-F: 4 minutes 23 seconds
```

So next update most of the time with `$rectorConfig->phpVersion(PhpVersion::PHP_80);` seems to be spend in part A of the ruleset which is:

```php
    $rectorConfig->sets([
        SetList::CODE_QUALITY,
        LevelSetList::UP_TO_PHP_74,
    ]);
    
    // PHP 8.0
    $rectorConfig->rules([
        // 1. StrContainsRector::class,
        // 2. StrStartsWithRector::class,
        // 3. StrEndsWithRector::class,
        // 4. StringableForToStringRector::class,
        // 5. ClassOnObjectRector::class,
        // 6. GetDebugTypeRector::class,
        // 7. RemoveUnusedVariableInCatchRector::class,
        // 8. ClassPropertyAssignToConstructorPromotionRector::class,
        // 9. ChangeSwitchToMatchRector::class,
        // 10. RemoveParentCallWithoutParentRector::class,
        // 11. SetStateToStaticRector::class,
        // 12. FinalPrivateToPrivateVisibilityRector::class,
        // 13. AddParamBasedOnParentClassMethodRector::class,
        // 14. MixedTypeRector::class,
        // 15. ClassOnThisVariableObjectRector::class,
    ]);
```

```
PHP 8.0 II A 1-3: 4 minutes 6 seconds
PHP 8.0 II A 4-8: 5 minutes 30 seconds
PHP 8.0 II A 9-12: 3 minutes 58 seconds
PHP 8.0 II A 13-15: 4 minutes 10 seconds
```

run more rules in same process:

```
PHP 8.0 II A 1-7: 4 minutes 44 seconds
PHP 8.0 II A 8-15: 4 minutes 24 seconds
```

So not sure now what is happening here 1-7 works without problems 8-15 also, maybe a combination problem of specific rules 🤔 

```
PHP 8.0 II A 6-15: 7 minutes 26 seconds
```

## Expected Behaviour

No Timeouts or Killed with LevelSetList::UP_TO_PHP_81.

**Comment by staabm** [comment]
not a actual solution, but you could try running rector with caching in CI

```
    if (getenv('GITHUB_ACTION') !== false) {
        $rectorConfig->cacheClass(FileCacheStorage::class);
        $rectorConfig->cacheDirectory('/tmp/rector');
    } 
```

you need to make sure that this `/tmp/rector` path is persisted between CI runs

**Comment by alexander-schranz** [comment]
Why using a cache for the tools. Seems to have big advantages for `.php-cs-fixer` skipping most of the files, but both `phpstan` and `rector` in case of ~1000 files project and a bigger PR ~50 edited files I did not see any improvements there I don't see any improvements.

Still for reference my config:

<details>
<summary>My configuraiton</summary>

`rector.php`:

```
    $rectorConfig->cacheClass(FileCacheStorage::class);
    $rectorConfig->cacheDirectory(__DIR__ . '/var/cache/tools/rector');
```

`phpstan.neon`:

```neon
parameters:
    tmpDir: %currentWorkingDirectory%/var/cache/tools/phpstan
```

`.php-cs-fixer.dist.php`:

```php
    ->setCacheFile(__DIR__ . '/var/cache/tools/php-cs-fixer/.php-cs-fixer.cache')
```

The whole `/var/cache/tools` is cached and the cache files are created here:

<img width="281" alt="Bildschirmfoto 2023-07-11 um 20 29 52" src="https://github.com/rectorphp/rector/assets/1698337/da929210-2a48-4bbd-b19b-fc77837023e9">

In my case gitlab is used via:

```
workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          variables:
              CACHE_POLICY: pull-push
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
          variables:
              CACHE_POLICY: pull

Lint PHP:
    stage: Test
    needs:
        - Install
    image: php:8.1.21-cli
    variables:
        RECTOR_DISABLE_PARALLEL: 1
    cache:
        - key: cache-lint-php
          policy: $CACHE_POLICY
          paths:
              - var/cache/tools
    script:
        - echo 'memory_limit=4096M' >> /usr/local/etc/php/conf.d/zz-custom.ini
        - php composer.phar lint
```

</details>

Even with the cache I did run now into (rector 0.17.4):

```
 1042/1115 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░]  93%Killed
Script @php vendor/bin/rector process --dry-run handling the lint-rector event returned with error code 137
```

**Comment by samsonasik** [comment]
@alexander-schranz if it works locally and not works on CI, you may probably need a solution from @Flyingmana on PR:

- https://github.com/rectorphp/rector-src/pull/3722

the part that missing on that PR is on showing 100% progress bar after done on many files that seems overlapped on that PR.

**Comment by samsonasik** [comment]
@alexander-schranz I patched progressbar overlap on PR:

- https://github.com/rectorphp/rector-src/pull/3722

that's wait on merge, hopefully the memory reduced after that merged :)

**Comment by alexander-schranz** [comment]
@samsonasik my naiv brain would say would it not be enought to call `$progressBar->finish();` before showing the sucess message?

**Comment by samsonasik** [comment]
Yes, that's the patch on https://github.com/rectorphp/rector-src/commit/88a755b19efbd249d9158a413a9f2db16b5129a3 should work, wait for merge to give a try :)

**Comment by alexander-schranz** [comment]
@samsonasik let me know when it is merged then I can give it also try on my project.

**Comment by TomasVotruba** [comment]
@alexander-schranz We'll need to figure out, which rule is the slowest on your project.

> PHP 8.0 II A 4-8: 5 minutes 30 seconds

That peaks high above the average. Could you give us numbers of those 5 rules?
Then we'll need narrow it down the exact file.

**Comment by samsonasik** [comment]
@alexander-schranz we reverted the regular terminate process impelementation as caused error on downgrade

**Comment by alexander-schranz** [comment]
> That peaks high above the average. Could you give us numbers of those 5 rules?
> Then we'll need narrow it down the exact file.

Will try to give some measures at end of the week about the specific rules.

**Comment by Flyingmana** [comment]
> @samsonasik my naiv brain would say would it not be enought to call `$progressBar->finish();` before showing the sucess message?

the thing with finish() is, it forces the 100%, but there likely is a reason why its not reaching it by itself, and there is a possibility (till proven otherwise) that the missing percent points also mean some diffs are missing

**Comment by samsonasik** [comment]
The force finish() has reverted as was invalid count filter files? See to filter early

https://github.com/rectorphp/rector-src/pull/4519

**Comment by samsonasik** [comment]
> The force finish() has reverted as was invalid count filter files? See to filter early
 
- https://github.com/rectorphp/rector-src/pull/4519

**Comment by samsonasik** [comment]
@alexander-schranz Rector 0.17.7 has various performance improvements, could you try it? Thank you.
