### ISSUE TITLE
Rector infinitly swapping arguments when argument with default value comes before argument without a default.

### ISSUE THREAD

**Issue by UnknownError235** [rectorphp/rector#8047]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.17.3            |

When running rector on this code, it swaps the argument order at the call and then infinitely keeps on swapping the arguments in the function definition. 

## Minimal PHP Code Causing Issue

test file:
```php
<?php

class Test
{
    function foo($a = 1, $b) { return 3; }
    function bar() { return self::foo(1, 2); }
}
```

rector.php:
```php
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
           LevelSetList::UP_TO_PHP_81
       ]);
};
```

https://getrector.com/demo/b4ce65cc-b53f-49ff-98c1-2a6d3541ce46

## Expected Behaviour

Rector should swap the arguments once and move on.

**Comment by samsonasik** [comment]
Reproduced by combine 2 rules: `RemoveUnusedVariableInCatchRector` and `OptionalParametersAfterRequiredRector`

https://getrector.com/demo/c6fc2b9e-4582-4261-9901-8e6b2778163c
