### ISSUE TITLE
[DEAD_CODE] `System error: "enterNode() returned invalid value of type array`

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#8049]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.3             |

Not sure which rule exactly causes it. But the snippet below triggers an internal PHPParser error.

## Minimal PHP Code Causing Issue

```php
<?php

namespace App;

/**
 * @property Document|Course|Book $target
 */
class SearchResultClickedResource
{
    protected function getProperties($request): array
    {
        return [
            'Type' => $this->getType(),
        ];
    }

    /**
     * @return 'document'|'course'|'book'|'unknown'
     */
    private function getType(): string
    {
        if ($this->target instanceof Document) {
            return 'document';
        }

        if ($this->target instanceof Course) {
            return 'course';
        }

        if ($this->target instanceof Book) {
            return 'book';
        }
        
        return 'unknown';
    }
}
```

https://getrector.com/demo/cd5d728b-575c-46a9-bf0d-b93ec9a2ca95

## Expected Behaviour

No errors.

**Comment by samsonasik** [comment]
Reproduced by single rule:

https://getrector.com/demo/046bc9b7-3c64-488d-89c8-e4fa6b7ef4ec

**Comment by samsonasik** [comment]
It seems due to property `target` not exists, if it exists, it seems working ok https://getrector.com/demo/496b52cf-aa30-4783-bdf0-d5145b750dbd
