### ISSUE TITLE
[UP_TO_PHP_81] `System error: "Undefined property: PhpParser\Node\Expr\Variable::$args`

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#8050]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.3             |

From the stacktrace it looks like it is related to `Rector\Php80\Rector\Ternary\GetDebugTypeRector` But if I run rector only with that rule, it doesn't crash. So must be some combination.

```php
<?php

final class DemoFile
{    
    /**
     * @param string|object $command
     * @param string $connection
     * @param string $data
     */
    public function push($command, $connection = '', $data = '')
    {
        if ($connection === '') {
            $connection = null;
        }

        $this->jobs[is_object($command) ? get_class($command) : $command][] = [
            'data' => $data,
            'job' => $command,
            'queue' => $connection,
            'id' => ++$this->pushedJobId,
        ];
    }
}

```

## Minimal PHP Code Causing Issue

https://getrector.com/demo/a3fbcbe0-98b2-4437-b45d-2bc5ffb7a37b

## Expected Behaviour

No errors.

**Comment by samsonasik** [comment]
Reproduced by 2 rules: `ClassOnObjectRector` and `GetDebugTypeRector` https://getrector.com/demo/5dc6879c-5d36-497f-a83e-bcc7b763ff16
