### ISSUE TITLE
MyCLabsClassToEnumRector: keeping methods in PHP Enums

### ISSUE THREAD

**Issue by K0nias** [rectorphp/rector#8051]
# Feature Request

It should be possible to keep class methods from classes extending \MyCLabs\Enum\Enum in native PHP Enumerations
 
Unfortunately I wasnt able to reproduce it in demo 
https://getrector.com/demo/048e2209-68e7-48b0-abba-0d31c854eaeb

_______
Just out of curisoity I added `$enum->stmts = array_merge($enum->stmts, $class->getMethods());` to `\Rector\Php81\NodeFactory\EnumFactory::createFromClass` method and It "worked". But I dont have such experience with Rector so I dont know if this is the right solution or not.

**Comment by samsonasik** [comment]
For multiple rules applied, you can add failing fixtures on `tests/Issues`, for example: https://github.com/rectorphp/rector-src/tree/main/tests/Issues/DoubleRun

then add a patch for that and ensure CI green
