### ISSUE TITLE
[ERROR] The given paths do not match any files

### ISSUE THREAD

**Issue by sathishocs** [rectorphp/rector#8052]
![image](https://github.com/rectorphp/rector/assets/117816064/30067def-37a9-4d2f-aec2-13ca3ab3b0e1)

I'm using Laravel 10 project. I updated the rector's new version, I get the "given paths do not match any files error" when rector command run.

Can you please suggest

**Comment by TomasVotruba** [comment]
Hi, it means there are no files found in path to process. There are 2 ways to provide paths:

* https://getrector.com/documentation/define-paths
 

How does your `rector.php` paths look like?

**Comment by sathishocs** [comment]
@TomasVotruba Oh ok, sorry i didn't added it. thanks
