### ISSUE TITLE
RemoveUnusedPrivatePropertyRector does not recognize access through ??=

### ISSUE THREAD

**Issue by spawnia** [rectorphp/rector#8054]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.4             |

Rector deletes private properties that are exclusively accessed through `??=`.

## Minimal PHP Code Causing Issue

Since https://getrector.org/demo is down:

```php
class Foo {
    private int $bar;

    public function bar(): int {
        return $this->bar ??= 3;
    }
}
```

## Expected Behaviour

Rector should recognize that `??=` accesses a property.

**Comment by samsonasik** [comment]
what the expected output? Could you create a test case PR for it? You can click "Create a Test" button at demo page

**Comment by spawnia** [comment]
Thanks for the hint, I created https://github.com/rectorphp/rector-src/pull/4490. I expect the code to stay the same.
