### ISSUE TITLE
Worker process files which do not match the configured fileextension

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8056]
# Question
I am in the process of debugging my way thru the rector codebase.

after adding some debug output, I was wondering - even if I have configured `$rectorConfig->fileExtensions(['php']);` in my config - I am seeing non-`.php` files beeing contained in `$json[Bridge::FILES]` when dumping it in [WorkerRunner.php#L79](https://github.com/rectorphp/rector-src/blob/706be908c5d96381785128ad94cc608814aa0f35/packages/Parallel/WorkerRunner.php#L79)

this indicates [rector is reading/processing files which don't contain the configured extension](https://github.com/rectorphp/rector-src/blob/706be908c5d96381785128ad94cc608814aa0f35/packages/Parallel/WorkerRunner.php#L91), which seems to be unnecessary work.

I can see rector reading files like `baseline.neon` (PHPStan baselines), `xml`-files which are part of my app and similar.

since I can see them in the `WorkerRunner` I guess this also means the JSON data which is used to communicate between the processes also contain unncessary information which adds overhead in the inter process communication.

I was expecting, the files list would have already been filtered against the configured file-extension before beeing communicated to the workers?

is this expected behaviour?

**Comment by samsonasik** [comment]
I can't reproduce, I tried with the following steps in rector-src:

1. Add `src/Util/foo.txt` with content "test"
2. Add simple ` dump($filePath);` before

https://github.com/rectorphp/rector-src/blob/706be908c5d96381785128ad94cc608814aa0f35/packages/Parallel/WorkerRunner.php#L91

got the following output:

```
➜  rector-src git:(main) bin/rector process src/Util --clear-cache
 0/7 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%"/Users/samsonasik/www/rector-src/src/Util/ArrayChecker.php"
"/Users/samsonasik/www/rector-src/src/Util/ArrayParametersMerger.php"
"/Users/samsonasik/www/rector-src/src/Util/FileHasher.php"
"/Users/samsonasik/www/rector-src/src/Util/MemoryLimiter.php"
"/Users/samsonasik/www/rector-src/src/Util/PhpVersionFactory.php"
"/Users/samsonasik/www/rector-src/src/Util/Reflection/PrivatesAccessor.php"
"/Users/samsonasik/www/rector-src/src/Util/StringUtils.php"
```

**Comment by staabm** [comment]
I have sent you an invitation to our "kunzmann" repository.

- clone the repo
- run `composer install`
- add `var_dump($filePaths);` into `vendor/rector/rector/packages/Parallel/WorkerRunner.php` right after `$filePaths = $json[Bridge::FILES] ?? [];`
- run `vendor/bin/rector process app/admin/ --debug | grep ".xml"`

-> see paths to xml files beeing processed by rector

**Comment by samsonasik** [comment]
It seems the filePaths needs to be filtered with by reference on `ApplicationFileProcessor::configurePHPStanNodeScopeResolver()`

```diff
-    public function configurePHPStanNodeScopeResolver(array $filePaths, Configuration $configuration) : void
+   public function configurePHPStanNodeScopeResolver(array &$filePaths, Configuration $configuration) : void
```

I will create a PR for it,
