### ISSUE TITLE
Xdebug doesn't work within custom rule's `refactor` method.

### ISSUE THREAD

**Issue by zangai** [rectorphp/rector#8060]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.4, 0.17.6 |

I am trying to create a custom rule, in which the xdebug breakpoint does get triggered in my custom rule's: `__construct` method, but not in the `refactor(...)` method.

## Minimal PHP Code Causing Issue

```
final class CustomRule extends AbstractRector
{
    public function __construct() {
         dump("__construct"); // This breakpoint triggers
    }

    /**
     * @return array
     * <class-string
     * <Node>>
     */
    public function getNodeTypes(): array
    {
        // what node types are we looking for?
        // pick any node from https://github.com/rectorphp/php-parser-nodes-docs/
        return [Node\Attribute::class];
    }

    /** @param Node\Attribute $node */
    public function refactor(Node $node): ?Node
    {
        dump("refactor()"); // This breakpoint does *not* trigger
        return $node;
    }
```

## Expected Behaviour

I would expect the breakpoint to be hit and execution paused.

**Comment by TomasVotruba** [comment]
Hi, the xdebug is disabled by default, to avoid performance hits from default "on".

To enable xdebug, add this option:
https://getrector.com/documentation/debugging

**Comment by zangai** [comment]
Actually, I already added that switch to the command line call. I expected that to be the reason that it did break on the line in my config file.

**Comment by TomasVotruba** [comment]
I see. In that case it's needed to debug xdebug itself.

This option is used from: https://github.com/composer/xdebug-handler

**Comment by zangai** [comment]
Can you reopen this ticket? It is an actual bug because the application does not work out-of-the-box with the provided documentation.
I did some digging myself, and I found out the the `ConsoleApplication::doRun` method does detect the options passed to the command, and therefore the (as I asume) worker-process xdebug connection does not get bootstrapped.
I tried adding a `$input->bind($this->getDefinition());` but that opened a whole other can of worms that I am sure the developers/maintainers of this tool are way more qualified to resolve.

**Comment by TomasVotruba** [comment]
We can re-open, but we'll need a test case to reproduce the `xdebug` option is not passed to verify.

**Comment by samsonasik** [comment]
@staabm this probably related with proc_open() downgrade bug on `XdebugHandler`:

- https://github.com/rectorphp/rector-downgrade-php/issues/198

that fixed at :

- https://github.com/rectorphp/rector-downgrade-php/pull/199

could you try latest `dev-main`, if this still an issue, that probably different issue than this, we need test case to reproduce that.

**Comment by samsonasik** [comment]
@zangai  this probably related with proc_open() downgrade bug on `XdebugHandler`:

- https://github.com/rectorphp/rector-downgrade-php/issues/198

that fixed at :

- https://github.com/rectorphp/rector-downgrade-php/pull/199

could you try latest `dev-main`, if this still an issue, that probably different issue than this, we need test case to reproduce that.

**Comment by deviantintegral** [comment]
I can confirm this is still an issue in main as of `59b8839`.

**Comment by MartinsRucevskis** [comment]
Seems that xdebug flag isn't being passed down as mentioned earlier. 
Quick workaround locally for anyone facing this issue is to add
`$_SERVER['argv'][] = '--xdebug';`
At the start of `Rector\Core\Bootstrap\RectorConfigsResolver::provide()`

**Comment by TomasVotruba** [comment]
@MartinsRucevskis Thanks for sharing this! Could you send a PR with this fix so we have in core? :pray:

**Comment by samsonasik** [comment]
I created a PR:

- https://github.com/rectorphp/rector-src/pull/5398

for it, could you guys verify it? Thank you.

**Comment by mattvb91** [comment]
Has this already been released? Im having the exact same issue as the original report. `"rector/rector": "0.19.5"`

**Comment by samsonasik** [comment]
Yes, the fix is included since december so it should already included, we may need a reproducible test case in case you still experience the problem, thank you.

**Comment by staabm** [comment]
it still doesn't work. debugging only works when parallel is inactive

**Comment by samsonasik** [comment]
that's strange, `--xdebug` is passed on `WorkerCommandLineFactoryTest`, which should then the `$input->hasParameterOption('--xdebug')` will be detected as truthy, feel free to provide a patch if you found there is something missing in between.

**Comment by staabm** [comment]
a few observations 

- the debugger halts in the main process even without the `--xdebug` flag (opposite of how PHPStan behaves)
- the debugger does **not** halt in the main process when `--xdebug` flag is passed (opposite of how PHPStan behaves)

**Comment by staabm** [comment]
@mattvb91 could you confirm the fix in https://github.com/rectorphp/rector-src/pull/5544 is working as expected?

**Comment by mattvb91** [comment]
@staabm servus Markus, I can confirm it works on the latest dev-main commit. Thank you guys for the quick fix!!
