### ISSUE TITLE
Apply analyzed files on non-splitted filePaths on parallel process

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#8061]
# Feature Request

Currently, the parallel process set PHPStan analyzed files on splitted files
 
https://github.com/rectorphp/rector/blob/8525cf1533a4ee4a26fb9c117495cb1e05a17f97/packages/Parallel/WorkerRunner.php#L100-L101

The filePaths is already splitted by jobs schedule, I think original filePaths from ApplicationFileProcessor should be used.

**Comment by staabm** [comment]
I am not sure I understand. Could you provide a failling test ?

**Comment by samsonasik** [comment]
@staabm I am not sure if it reproducible by failing test, as the `$filePaths` in parallel is depends on what `$jobs` is defined, eg: `20` then it process per-20 files, that may include/not include dependent files, but here is the flow:

First, all start from `ApplicationFileProcessor`, which define early the `$filePaths` as "ALL filtered" file paths, the `$filePaths` here is excluded by:

- skipped paths
- cached paths (if already cached, then no longer be processed)

https://github.com/rectorphp/rector/blob/13c57eb6496401aba4a83153a0ce345583a6df27/src/Application/ApplicationFileProcessor.php#L107-L109

Next, it processed under `if ($configuration->isParallel()) { ` check:

https://github.com/rectorphp/rector/blob/13c57eb6496401aba4a83153a0ce345583a6df27/src/Application/ApplicationFileProcessor.php#L115-L116

on parallel, including `$filePaths`, it call another process by `runParallel()` method, bring the `$filePaths` variable, it processed on schedule:

https://github.com/rectorphp/rector/blob/13c57eb6496401aba4a83153a0ce345583a6df27/src/Application/ApplicationFileProcessor.php#L230

so, the result is partial of the early defined `$filePaths`, then on `ParallelFileProcessor`, it used to run `WorkerRunner`:

https://github.com/rectorphp/rector/blob/13c57eb6496401aba4a83153a0ce345583a6df27/packages/Parallel/WorkerRunner.php#L64-L65

the `$filePaths` there is **NOT** original "ALL filtered" file paths, but only scheduled one, eg: 20 files per scheduled jobs.

What `analysed files` collections are used for? As I can see, it used on related files, and caching it:

https://github.com/rectorphp/rector/blob/13c57eb6496401aba4a83153a0ce345583a6df27/packages/Caching/FileSystem/DependencyResolver.php#L37-L42

that called from `PHPStanNodeScopeResolver` on

https://github.com/rectorphp/rector/blob/13c57eb6496401aba4a83153a0ce345583a6df27/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php#L424-L436

after processing `stmts`, the `ChangedFilesDetector` then detect file dependents:

https://github.com/rectorphp/rector/blob/13c57eb6496401aba4a83153a0ce345583a6df27/packages/Caching/Detector/ChangedFilesDetector.php#L49-L53

the `file dependents` are used by `UnchangedFilesFilter` to resolve join with dependent file infos:

https://github.com/rectorphp/rector/blob/13c57eb6496401aba4a83153a0ce345583a6df27/packages/Caching/UnchangedFilesFilter.php#L22-L36

what unchanged files filter used for? That used back on `ApplicationFileProcessor` to filter "ALL filtered" file paths excluded skipped files and cached files again on re-run rector.

That's the story. The issue here if we use "all initiated file paths", the cache may probably overlapped.

**Comment by samsonasik** [comment]
I am closing it for now ;)
