### ISSUE TITLE
warnings in output destroys json encoding

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8062]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. 0.17.2            |

when the analysis issues warnings like

![grafik](https://github.com/rectorphp/rector/assets/120441/699ced72-3718-4d45-b86b-f4f0e5409e71)

these scramble the json output when using `--format=json`

I think we should either send the output on stderr instead of stdout, or need a proper formatted error according to the used `--format`

**Comment by staabm** [comment]
https://symfony.com/doc/current/console/style.html#writing-to-the-error-output describes how to output on stderr

**Comment by TomasVotruba** [comment]
I'm looking into this...
