### ISSUE TITLE
Empty JSON outputs when processing individual files with --dry-run

### ISSUE THREAD

**Issue by AliasAPI** [rectorphp/rector#8066]
# Bug Report

Rector version: ^0.17.6

1. IF I run 
php <dir>/rector --config=<dir>/rector.php --output-format=json --dry-run <individual_file_path>
THEN the JSON output file for each individual file processed is as follows:
{
    "totals": {
        "changed_files": 0,
        "errors": 0
    }
}

2. IF I run the same command but use a directory rather than <individual_file_path>
THEN, the JSON output is as expected (complete with the rule, diff, filepaths, etc).

All of the code I'm using and the configuration can be seen here:
https://bitbucket.org/AliasAPI/micromanager/src/master/etc/rector/

I expect that when I run the command on individual files, the same JSON output will be created for each individual file.

**Comment by samsonasik** [comment]
You may looking up the config from differnt directory instead of same project root, I tried in rector-src with removing unuesd property, it seems working ok:

```
➜  rector-src git:(main) bin/rector process src/Application/VersionResolver.php --output-format=json --dry-run
{
    "totals": {
        "changed_files": 1,
        "errors": 0
    },
    "file_diffs": [
        {
            "file": "src/Application/VersionResolver.php",
            "diff": "--- Original\n+++ New\n@@ -17,8 +17,6 @@\n  */\n final class VersionResolver\n {\n-    private $unused;\n-\n     /**\n      * @api\n      * @var string\n",
            "applied_rectors": [
                "Rector\\DeadCode\\Rector\\Property\\RemoveUnusedPrivatePropertyRector",
                "Rector\\Strict\\Rector\\If_\\BooleanInIfConditionRuleFixerRector"
            ],
            "applied_rectors_with_changelog": []
        }
    ],
    "changed_files": [
        "src/Application/VersionResolver.php"
    ]
}
```

**Comment by samsonasik** [comment]
I am closing it as can't be reproduced, you may need to place the `rector.php` to root project so you have always have correct pointing location paths.
