### ISSUE TITLE
Adding a custom visitor without a custom traverser

### ISSUE THREAD

**Issue by bbrala** [rectorphp/rector#8069]
# Question
Since we are urged to use visitors in light of the parent/next/previous changes I want to explore using a visitor for a use case. But I can't find an easy way to add a custom visitor. Tried adding a service, tried adding it to rules. But no go.

What would the best way be to add a visitor to the parser?

**Comment by samsonasik** [comment]
@bbrala you should can create a visitor with implements ScopeResolverNodeVisitorInterface

Ref https://github.com/rectorphp/rector-src/blob/main/packages/NodeTypeResolver/PHPStan/Scope/Contract/NodeVisitor/ScopeResolverNodeVisitorInterface.php

It will automatically added by DI 

https://github.com/rectorphp/rector-src/blob/56068f8571e4b8325617fa72012e58783bd03d46/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php#L91

**Comment by bbrala** [comment]
Oh that's great, gonna try that right away.

**Comment by samsonasik** [comment]
Awesome, you may need to register the new visitor implements `ScopeResolverNodeVisitorInterface` to services, something like:

```php
$$rectorConfig->services()->set(MyNewVisitorImplementsScopeResolverNodeVisitorInterface::class);
```

**Comment by bbrala** [comment]
Yeah, but it seems you also need to tag it.

```
    $rectorConfig->services()->set(CommentingVisitor::class)->tag(ScopeResolverNodeVisitorInterface::class);
```

The iterator thing only looks for tags it seems.

**Comment by samsonasik** [comment]
That seems worth a documentation, could you try create a doc PR for it at 

https://github.com/rectorphp/getrector-com/tree/main/resources/docs

Thank you.

**Comment by bbrala** [comment]
Hmm, getting some weirdness though. Let me try and explain:

**Comment by bbrala** [comment]
Im adding an attribute to `Stmt\Expression` nodes by looking up the parent and adding a custom attribute. Unfortunately when i return those nodes, sometimes the attributes get completly cleared when i get back to the leavenode.

Is this because the statement has changed? 

```
    public function leaveNode(Node $node)
    {
        if(!($node instanceof Stmt\Expression)){
            return null;
        }

        if (!$node->hasAttribute(self::COMMENT_ATTRIBUTE)) {
            return null;
        }

        $node->setAttribute(AttributeKey::COMMENTS, $node->getAttribute(self::COMMENT_ATTRIBUTE));
        return $node;
    }

```

And the return for the rector that breaks:

```
return new Node\Expr\MethodCall($service, $methodName, $methodArgs);
```

Should i go another way and add a reference to the statement in the returning node, or perhaps in the expression and read that in the leaveNode method?

**Comment by bbrala** [comment]
> You may need to use enterNode() instead, and check against the Stmt is Expression on your use case.

Eh, wouldn't that mean I get there to earlie? Thought it just traversed down, so it might enter the `Stmt\Expression`, then move on into the children, then leave the expression? Or am i misunderstanding something there?

> Also, refactor() should return same type of Node, that mean you need to use Expression in your getNodeTypes() method.

These are both expressions right? And i'd assume things break if you dont :x

```
public function getNodeTypes(): array
    {
        return [
            Node\Expr\FuncCall::class,
        ];
    }

....

        return new Node\Expr\MethodCall($service, $methodName, $methodArgs);
```

**Comment by bbrala** [comment]
When I log the statement nodes on enternode, i end up with 2 nodes, the original node, and then replacement node. The original had the actual comment i want to add, but the replacement doesn't. So I think i might misunderstand something in how this flow should work.

![image](https://github.com/rectorphp/rector/assets/3294970/4f432c25-69d1-4d08-ab84-08ae912d6c00)

That is the result after adding: 

```php
    public function enterNode(Node $node)
    {
        if($node instanceof Stmt\Expression){
            $this->nodes[] = $node;
        }
    }
```

First one is the original expression, the second on is after the rector. Is this always a pair if i would push and pop from a stack?

**Comment by bbrala** [comment]
When I log the statement nodes on enternode, i end up with 2 nodes, the original node, and then replacement node. The original had the actual comment i want to add, but the replacement doesn't. So I think i might misunderstand something in how this flow should work.

![image](https://github.com/rectorphp/rector/assets/3294970/4f432c25-69d1-4d08-ab84-08ae912d6c00)

That is the result after adding: 

```php
    public function enterNode(Node $node)
    {
        if($node instanceof Stmt\Expression){
            $this->nodes[] = $node;
        }
    }
```

First one is the original expression, the second on is after the rector. Is this always a pair if i would push and pop from a stack?

**Comment by samsonasik** [comment]
`Node\Stmt\Expression` is Stmt above `Node\Expr`, which a `Node\Expr\FuncCall` on your use case. If you want to fill the `Expr` part, you need to fill the attribute in the `Expr` part instead:

```php
    public function enterNode(Node $node)
    {
        if(!($node instanceof Stmt\Expression)){
            return null;
        }

       if (! $node->expr instanceof FuncCall) {
            return null;
       }

        if (!$node->expr->hasAttribute(self::COMMENTS)) {
            return null;
        }

        $node->expr->setAttribute(self::COMMENTS, $node->getComments());
        return null;
    }
```

Here the example of usage:

```php
public function getNodeTypes()
{
    return [Node\Stmt\Expression::class];
}

public function refactor(Node $node)
{
    if (! $node->expr instanceof Node\Expr\FuncCall) {
        return null;
    }

    if ($node->expr->getAttribute('comments') !== []) {
          return nulll;
    }

    $node->expr = new Node\Expr\MethodCall($service, $methodName, $methodArgs);
    return $node;
}
```

**Comment by bbrala** [comment]
I reverted that change in my code by accident and adding that change back fixes it. Thanks. But then im not sure the visitor is really needed. The visitor was mostly to get around the problemen when i cannot target a statement easily. But i'll explore a little more before coming back here. Thanks for the help.

**Comment by samsonasik** [comment]
If you only need an attribute in specific rule, you can just use it in `beforeTraverse()` in the rule itself:

```php
class MyCustomRector extends AbstractRector
{
    public function beforeTraverse(array $nodes): ?array
    {
        parent::beforeTraverse($nodes);

        $this->traverseNodesWithCallable($nodes, function (Node $subNode) {
               // do fill the node attribute here...
        });
       
        return $nodes; 
    }
}
```

**Comment by bbrala** [comment]
Yeah but its an attribute i set in a rule which targets a function for example. Which then later needs to be applies to the Stmt above it, since it is a comment. 

Keep coming back to the fact i need to make the rectors target the statements and work from there if i want to make changes to those. Was hoping there was a way around that with a visitor.

**Comment by samsonasik** [comment]
we need real example of the usage of it so we can help, like before vs after the diff why it needed.
