### ISSUE TITLE
Incorrect behavior of GetMockBuilderGetMockToCreateMockRector

### ISSUE THREAD

**Issue by toastedghost** [rectorphp/rector#8070]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.17.6      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/0d3fffb0-7c28-4e37-a482-5de798e6c195

```php
<?php

use PHPUnit\Framework\MockObject\MockBuilder;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

abstract class AbstractMockFactory
{   
    public function __construct(protected TestCase $testCase)
    {
    }
    
    /*
     * Normaly this is declared here as abstract and must be implemented in child class
     */
    public function create(): MockObject
    {
        return $this->getMockBuilder(Service::class)->getMock();
    }
    
    protected function getMockBuilder(string $className): MockBuilder
    {
        return new MockBuilder($this->testCase, $className);
    }
}
```

### Responsible rules

* `GetMockBuilderGetMockToCreateMockRector`

## Expected Behavior

The call of getMockBuilder should stay untouched in method create because the class is no instance of \PHPUnit\Framework\TestCase

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector in https://github.com/rectorphp/rector-phpunit.
You can click "Create a Test" button at demo page.

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-phpunit/pull/238

Thanks for reporting :+1:
