### ISSUE TITLE
Class is not processed because of `Class not found` error

### ISSUE THREAD

**Issue by ondrab1** [rectorphp/rector#8071]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.6             |

We are trying to start using Rector to help us with code refactoring, upgrades etc... We created simple configuration to test behavior of Rector, but we end up with and error. 

In our project there exists legacy code, that is not loaded using composer autoloader, so I added this legacy code to `autoloadPaths`, but it looks like autoloadPaths are not working. Or is there any missconfiguration?

When we run Rector using `bin/rector process --dry-run --debug`, we end up with an error:
```bash
 [ERROR] Could not process                                                      
         "/app/src/bundles/AdminBundle/Util/ListExporte
         r.php" file, due to:                                                   
         "System error: "Class 'Frame' not found"    
```

## Minimal PHP Code Causing Issue
rector.php
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->cacheDirectory(__DIR__.'/data/tmp/rector');

    // autoload legacy class
    $rectorConfig->autoloadPaths([
        __DIR__.'/src/admin/class/class.Frame.php',
    ]);

    $rectorConfig->paths([
        __DIR__.'/src/bundles/AdminBundle/Util/ListExporter.php'
    ]);

    // here we can define, what sets of rules will be applied
    // tip: use "SetList" class to autocomplete sets with your IDE
    $rectorConfig->sets([
        SetList::CODE_QUALITY
    ]);
};
```

## Expected Behaviour

Class `Frame` will be loaded because it is set in `autoloadPaths`.

**Comment by samsonasik** [comment]
You may looking for bootstrap:

```php
 $rectorConfig->bootstrapFiles([
        __DIR__.'/src/admin/class/class.Frame.php',
    ]);
```

https://getrector.com/documentation/static-reflection-and-autoload
