### ISSUE TITLE
Is there a rule ready to replace split() with preg_split()?

### ISSUE THREAD

**Issue by realtebo** [rectorphp/rector#8073]
# Question

Is there a rule ready to replace split() with preg_split()?

I cannot see  in any default set?

**Comment by realtebo** [comment]
Trovato.. posso usare una cosa come 

        $rectorConfig->ruleWithConfiguration(RenameFunctionRector::class, [
            'split' => 'explode',
        ]);

Questo fa il rename puro.
Nel mio caso, tutte le 1230 occorrenze nel codice NON USAVANO REGEXP, per cui posso fare il rename semplice.

**Comment by samsonasik** [comment]
It seems you found it, I am closing it then ;)
