### ISSUE TITLE
How to suppress warnig about  InlineHTML ?

### ISSUE THREAD

**Issue by realtebo** [rectorphp/rector#8076]
# Question

How to suppress warnig about  InlineHTML ?

Like followings:

 [WARNING] File ../wp-content/plugins/wp-user-avatar/includes/class-wp-user-avatar.php has
           InlineHTML node, this may cause unexpected output, you may need to manually verify the changed file

I don't want to ignore files.
I want to suppress this warning

**Comment by samsonasik** [comment]
The file with HTML inside actually changed, but give warning to let you verify the changed file as may cause unexpected output:

https://github.com/rectorphp/rector/blob/b99d5e23736e336f1548aee7a18a8f62c8fb3701/src/Application/FileProcessor/PhpFileProcessor.php#L124-L126

**Comment by realtebo** [comment]
I understand, it's a good thing, but I need to suppress warnings.
Every changes will be checked manually later using git diff

**Comment by samsonasik** [comment]
@TomasVotruba we may need new config, eg:

```php
$rectorConfig->supressHTMLWarning(true);
```

with `false` as default value.

**Comment by TomasVotruba** [comment]
I've played with this before and it would require increase complexity of our error + diffs values passing around project. But Rector should not be a reporting tool. Soon we might report warning for all kinds of stuff and it will turn PHPStan :) 

Instead we should either drop this warning complety and put this into known drawbacks in README.md. The tool has to be used with cauting in general.
