### ISSUE TITLE
NameImportingPostRector is slow

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8077]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.17.6            |

when `$rectorConfig->importNames();` is enabled running rector across the otherwise identical codebase is 42% slower.

![grafik](https://github.com/rectorphp/rector/assets/120441/340f4e3a-75c6-42e7-9f7b-22d7b87bb1f8)

![grafik](https://github.com/rectorphp/rector/assets/120441/4ae1eac2-9e57-4c23-a442-ac40ce7c6797)

is it a known problem that `$rectorConfig->importNames()` is such a performance hit?

do we actually need `$rectorConfig->importNames()` in our projects when we run ECS right after we ran rector?

## Minimal PHP Code Causing Issue

my rector command on the [kunzmann private repo](https://github.com/complex-gmbh/kunzmann/pull/4453):

`blackfire run php vendor/bin/rector process app/admin --ansi --clear-cache` 

config
```
$rectorConfig->importNames();
$rectorConfig->disableParallel();
```

## Expected Behaviour

fast CI :)

**Comment by staabm** [comment]
another thing which makes me wonder: my rector run does not yield any required changes but it seems name importing is still slow?

sounds like rector does re-print files, even if no changes occurred?

**Comment by samsonasik** [comment]
ecs is only sorting use statements iirc, not make auto imports. 

Some rules require print in the rule itself, like curly variable check `{$f}`, that probably happen.

Auto imports is expected to be slower, as it check every Name node already in use statement and its a complex one, as it also verify in group use and aliased.

**Comment by staabm** [comment]
further investigation: it seems the static-type-mapping is the slowest part

![grafik](https://github.com/rectorphp/rector/assets/120441/4dc2a905-5e47-4e5c-8d5f-c32c485bcaa9)

**Comment by staabm** [comment]
@TomasVotruba do you think we can expect this type-mapping will go away when https://github.com/rectorphp/rector/issues/7959 is resolved?

**Comment by staabm** [comment]
> Auto imports is expected to be slower, as it check every Name node already in use statement and its a complex one, as it also verify in group use and aliased.

@samsonasik do you think it would work to run the auto-import after all rectors have been applied instead of mid-flight as a post rector between rules?

**Comment by staabm** [comment]
said differently: I have the feeling out of the default-post rectors

https://github.com/rectorphp/rector-src/blob/ff74e1000b87a53131af5957b69a635f6040ccc1/packages/PostRector/Application/PostFileProcessor.php#L37-L46

the `NameImportingPostRector` and `UnusedImportRemovingPostRector` rectors are those doing just "cosmetics" which are nice for the human reading the code, but should not be required for the rector rules themselfs?

**Comment by samsonasik** [comment]
PostRector is already run after all rules applied to the file object:

https://github.com/rectorphp/rector/blob/7f18bf8c2972caa646757acf69ddbbb72d6546da/src/Application/FileProcessor/PhpFileProcessor.php#L108-L110

It is in loop of while file still changed until no longer changed.

**Comment by staabm** [comment]
> ecs is only sorting use statements iirc, not make auto imports.

maybe I did not yet understand what a "auto import" is.

In my understand it means adding "use statements" for symbols which are fully-qualified within the source?
if so, maybe we could say this is a task for a code-style fixer (add this task to ECS) and remove it completly from rector?

> It is in loop of while file still changed until no longer changed.

yeah. my question is, whether we can move it after the loop, as it might not be necessary todo it within it?
(this does not apply for all post rectors but maybe for `NameImportingPostRector ` and `UnusedImportRemovingPostRector ` ?

**Comment by samsonasik** [comment]
Apply after loop is probably better, but that will make the `Name` node doesn't have target type early, eg: `AliasedObjectType` that maybe used on next rule, that make rector require double run to apply. 

We basically don't want to run multiple times, except it happen on consecutive rule execution, or reprint that require space change, that php-parser doesn't have information immediatelly after change the node.
