### ISSUE TITLE
ConstExprClassNameDecorator is slow

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8079]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.17.6 (invoke `vendor/bin/rector --version`)             |

when running rector across the whole kunzmann codebase, I can see `ConstExprClassNameDecorator`'`-traverseWithCallable`-calls are slow

![grafik](https://github.com/rectorphp/rector/assets/120441/2bd32cda-693c-47ee-8908-f2d53148539c)

maybe we can find some shortcuts to make it faster

**Comment by staabm** [comment]
I wonder why we need to resolve the FQCN eagerly in BetterPhpDocParser for all phpdoc we found while parsing.

wouldn't it be enough to only resolve the class when one of the rule actually asks for `RESOLVED_CLASS`?
why do we need to resolve it that early for every `ConstFetchNode` we find in the code-base instead of only when a rule asks for it?

**Comment by samsonasik** [comment]
`RESOLVED_CLASS` also used on PostRector UnusedImportRemovingPostRector.

**Comment by staabm** [comment]
@samsonasik thx for the investigation.

@TomasVotruba do you agree that removing unused imports should not be a rector concern (but instead a ECS/CS-Fixer thing)?

**Comment by samsonasik** [comment]
Remove unused imports is optional, so it won't executed when not enabled.

This can be improved by move pull `use statement resolve` once when possible, eg:

```diff
+      $uses = null;
        $this->phpDocNodeTraverser->traverseWithCallable($phpDocNode, '', function (Node $node) use (
            $phpNode,
+           &$uses,
        ): Node|null {
            if (! $node instanceof ConstFetchNode) {
                return null;
            }

+          if ($uses === null) {
+                 $uses = $this->useImportsResolver->resolve();
+          }

-           $className = $this->resolveFullyQualifiedClass($node, $phpNode);
+           $className = $this->resolveFullyQualifiedClass($node, $phpNode, $uses);
            $node->setAttribute(PhpDocAttributeKey::RESOLVED_CLASS, $className);

            return $node;
        });
```

and then, update to use nullable `$uses` params on the target method.

**Comment by staabm** [comment]
> Remove unused imports is optional, so it won't executed when not enabled.

my point is that we might can get rid of `RESOLVED_CLASS` and therefore `ConstExprClassNameDecorator ` if we agree that removing unused imports is not a important task for rector

**Comment by samsonasik** [comment]
instead of removing feature, I think we can improve the performance instead, like caching the pull uses statement, and only flush when CurrentRectorProvider rule instanceof PostRector.

**Comment by samsonasik** [comment]
@staabm the slowing part seems due to creation of `new NameScope()` multiple times, memory tweak like `gc_collect_cycle()` may probably needed to clean the object in memory as no longer used after creation.

**Comment by samsonasik** [comment]
@staabm the following change may probaby needed:

```diff
    private function resolveFullyQualifiedClass(ConstFetchNode $constFetchNode, PhpNode $phpNode): string
    {
        $nameScope = $this->nameScopeFactory->createNameScopeFromNodeWithoutTemplateTypes($phpNode);
-        return $nameScope->resolveStringName($constFetchNode->className);
+        $fullyQualifiedClass = $nameScope->resolveStringName($constFetchNode->className);
+
+        unset($nameScope);
+
+        return $fullyQualifiedClass;
    }
```
