### ISSUE TITLE
FinalizeClassesWithoutChildrenRector removed newline before `final` when class has Attributes

### ISSUE THREAD

**Issue by cngJo** [rectorphp/rector#8080]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.17.6            |

The `FinalizeClassesWithoutChildrenRector` rector removes newlines when the class has and attribute in the line above.

## Minimal PHP Code Causing Issue

```php
#[Attribute]
class Dummy
{
}
```

will get corrected to 

```
#[Attribute]final class Dummy
{
}
```

When I add the line break before `final` again and rerun rector, I get no changes, so it doesn't seem to have anything to do with e.g. the length of the lines.

## Expected Behaviour

I'd expect rector to not remove the line break before the `final` keyword.

Or "spoken" in PHP ;-)

```php
#[Attribute]
final class Dummy
{

}
```

**Comment by samsonasik** [comment]
@cngJo the class need re-print for that, could you try provide a patch?

First, Add test case, something like in https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php82/Rector/Class_/ReadOnlyClassRector/Fixture/class_with_attribute.php.inc

Then, provide a patch, check class has attribute, if has, reprint, something like in 

https://github.com/rectorphp/rector-src/blob/a7cd7eda65894aea11ca012cac8ea4a29fb0a051/rules/Php82/Rector/Class_/ReadOnlyClassRector.php#L104-L107

Thank you.

**Comment by cngJo** [comment]
@samsonasik, sure I will try. Thank you for the links. Will check them out and get to work ;)
