### ISSUE TITLE
`DoctrineTargetEntityStringToClassConstantRector` should keep `self::class`

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#8081]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.17.6              |

`self::class` should not be refactored

## Minimal PHP Code Causing Issue

I tried to reproduce the error in a demo here:
https://getrector.com/demo/f95978a5-496b-4e3a-bcfe-e8fe06141988

but it does not refactor anything, while in my code I see:
![CleanShot 2023-07-23 at 21 53 40](https://github.com/rectorphp/rector/assets/995707/5e6d2d02-345b-493b-9cce-9dbb099b0ed3)

## Expected Behaviour

self::class is valid and should be kept, because if this gets refactored to `App\Entity\Deadline`, my PHP-CS-Fixer comes and fixes it back to `self::class`, so I end up in an infinite loop.

I am unable to create a failing test case :-(

**Comment by TomasVotruba** [comment]
Hi, the screenshot shows 3 rules being active at the same time. Could you re-run your local `rector.php` with only `DoctrineTargetEntityStringToClassConstantRector`? What is the output?

I made a test fixture for only `DoctrineTargetEntityStringToClassConstantRector` but is passes, so it will be combination of rules causing this.

What your minimal `rector.php` setup causing this?

**Comment by OskarStark** [comment]
In the end I skipped this rule and everything is fine, even when skipping the other mentioned rules and activating only the `DoctrineTargetEntityStringToClassConstantRector`, I receive:
![CleanShot 2023-07-23 at 22 13 25](https://github.com/rectorphp/rector/assets/995707/a94f0185-4ac6-435e-bb39-c15e8eb8e3ea)

I enabled all the three rules here, but still no error:
https://getrector.com/demo/a916553a-9f8a-4bde-9b5a-05c12e924a3b

Not sure if the demo really gets, that it is a Doctrine entity class... 🤔

**Comment by TomasVotruba** [comment]
My test fixture is passing well, and demo is working the same :+1: 

---

Could you share minimal `rector.php` that is causing this? I think there will be missconfiguration in your autoloading.

**Comment by OskarStark** [comment]
I will try, but gave some more hints in
* https://github.com/rectorphp/rector-doctrine/pull/211

**Comment by samsonasik** [comment]
@TomasVotruba @OskarStark it already resolved in PR:

- https://github.com/rectorphp/rector-doctrine/pull/208

please use rector dev-main

**Comment by TomasVotruba** [comment]
Ah, I see :) I'll make a new release then. Thanks @samsonasik :+1:

**Comment by OskarStark** [comment]
Thanks 👏
