### ISSUE TITLE
[Idea] New rule `SwapStaticMethodCallArgumentsRector`

### ISSUE THREAD

**Issue by mcampbell508** [rectorphp/rector#8085]
# Feature Request

Hi.

Much like there are already rules for:

- SwapFuncCallArgumentsRector https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#swapfunccallargumentsrector
- SwapMethodCallArgumentsRector https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#swapmethodcallargumentsrector

and thinking about the rule [RenameStaticMethodRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renamestaticmethodrector) which is able to rename things like:

```diff
-SomeClass::oldStaticMethod();
+AnotherExampleClass::newStaticMethod();
```

## Proposal

Would there be any interest in creating a new Rector rule: `SwapStaticMethodCallArgumentsRector`

which would produce the following diff...

## Diff 

```diff
 final class AnotherClass
 {
     public function run()
     {
-        return SomeClass::newStaticMethod('one', 'two', 'three');
+        return SomeClass::newStaticMethod('three', 'two', 'one');
     }
 }
```

Potential config (which is very similar to https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#swapmethodcallargumentsrector):

```php
<?php

declare(strict_types=1);

use Rector\Arguments\Rector\MethodCall\SwapStaticMethodCallArgumentsRector;
use Rector\Arguments\ValueObject\SwapStaticMethodCallArguments;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(SwapStaticMethodCallArgumentsRector::class, [
        new SwapStaticMethodCallArguments('SomeClass', 'newStaticMethod', [
            2,
            1,
            0,
        ]),
    ]);
};
```

I can't see existing functionality which offers this, apologies if there is. Would this be something worth exploring? I am looking to explore Rector more and hopefully contribute as it is an interesting project.

Maybe there were drawbacks for such a thing as to why it wasn't implemented previously.

## Fallback proposal

Of course `SwapMethodCallArgumentsRector` could also be modified to handle static method calls, maybe...

## Thanks

Even if this idea is not taken up, thanks contributors and @TomasVotruba for such a cool tool / set of tools.

**Comment by samsonasik** [comment]
`SwapMethodCallArgumentsRector` itself removed at PR:

- https://github.com/rectorphp/rector-src/pull/4766

as only usefull when run once, running multiple time cause infinite change. as @TomasVotruba suggestion at 

https://github.com/rectorphp/rector-src/pull/4766#issue-1846556472

The custom rule should be used for that ;)
