### ISSUE TITLE
StaticArrowFunctionRector: Do not convert with Laravel macro usage

### ISSUE THREAD

**Issue by pionl** [rectorphp/rector#8087]
# Feature Request

Hi, if I use Laravel `macro` feature with closure rector will automatically add `static` keyword to a function due the fact I do not use `$this` within the closure. But Laravel internally binds the closure and runtime will fail.

## Error

```
Cannot bind an instance to a static closure
 /Users/pion/Work/LaraStrict/php-get-typed-value/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:121
```
 
## Current diff 

```diff
-FormRequest::macro('validate', fn () => $validator->validate());
+FormRequest::macro('validate', static fn () => $validator->validate());
```

Is it possible to add this exception in the rules? (StaticGuard class?

Thank you,
Martin

**Comment by TomasVotruba** [comment]
Hi, this is very specific case and I'm not sure it's worth the complexity to exclude it explicitly, as other cases might join.
Better ignore using `skip()` method for `StaticArrowFunctionRector` rule.

**Comment by pionl** [comment]
Make sense, just wanted to let u know. Already did use the skip method on the file :) Thank you!
