### ISSUE TITLE
Incorrect behavior of StrictArrayParamDimFetchRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8090]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a70df0ab-1453-4f55-a292-138b34ee8a8e

```php
<?php
class Test
{
    /** @param string $bytes */
    public function firstByte($bytes)
    {
        return $bytes[0];
    }
}
```

### Responsible rules

* `StrictArrayParamDimFetchRector`

## Expected Behavior

No change.

**Comment by samsonasik** [comment]
@jlherren could you try provide a patch? It should be check the type is `\PHPStan\Type\StringType` :

```php
$scope = $this->getType($someNode);
If ($scope->isString()->maybe()) { 
    return null;
}
```

I am on mobile so that's pseudo code, but you got the idea ;)

Thank you.

**Comment by samsonasik** [comment]
Could you create a failing test case PR? Thank you.
