### ISSUE TITLE
Incorrect behavior of ParamTypeByMethodCallTypeRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8091]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/097e4e5f-da4d-4ff8-807f-a0c4b3e3e224

```php
<?php

final class DemoFile
{
    /** @param int|stdClass $item */
    public function process($item) {
        $item = $this->resolve($item);
        $this->send($item);
    }
    
    /** @param int|stdClass $item */
    private function resolve($item): stdClass {
        if ($item instanceof stdClass) {
            return $item;
        }
        return new stdClass();
    }
    
    private function send(stdClass $item): void {
    }
}
```

### Responsible rules

* `ParamTypeByMethodCallTypeRector`

## Expected Behavior

No change.

(This can be worked around by assigning to a different variable.)

**Comment by samsonasik** [comment]
this may can be validated by `ExprAnalyzer`, eg:

```php
if ($this->exprAnalyzer->isNonTypedFromParam($variable)) {

}
```

could you try provide a failing test case, including patch for it? Thank you.

**Comment by samsonasik** [comment]
@jlherren I think for this case, the easy solution is by assign to different variable, see

https://getrector.com/demo/4e84a8d5-a737-4538-b6db-1fd2fa1a2201

**Comment by samsonasik** [comment]
This should can be tweaked by check param used as Arg in method body, like handling on StrictStringParamConcatRector, ref PR:

- https://github.com/rectorphp/rector-src/pull/4774#pullrequestreview-1574152579

we may need special guard form param used as Arg in method body so can be used on `Strict*ParamRector` rules.
