### ISSUE TITLE
ParentClassMethodTypeOverrideGuard bug

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8093]
# Bug Report

I think ParentClassMethodTypeOverrideGuard has a bug, as it allows method modifications when parent classes are unknown

see https://github.com/rectorphp/rector-src/blob/3a95b1436575815cfc442baf137a2a6a24100cdd/packages/VendorLocker/ParentClassMethodTypeOverrideGuard.php#L33-L36

when no class reflection can be found -> e.g. because the class used in a extends expression is not resolvable via autoloading the code [assumes we don't have a parent method](https://github.com/rectorphp/rector-src/blob/3a95b1436575815cfc442baf137a2a6a24100cdd/packages/VendorLocker/ParentClassMethodTypeOverrideGuard.php#L26-L29).

I think this can lead to errors when parent classes which are not known at rector runtime will have a method rector wasn't able to find via reflection and assumed it did not exist

**Comment by staabm** [comment]
I think we have a similar problem in https://github.com/rectorphp/rector-src/blob/3a95b1436575815cfc442baf137a2a6a24100cdd/packages/VendorLocker/NodeVendorLocker/ClassMethodParamVendorLockResolver.php#L30-L33 where we are optimistic about a class not beeing vendor-locked when not known

**Comment by samsonasik** [comment]
parent class not autoloaded can be checked by:

```php
$class->extends instanceof FullyQualified && ! $this->reflectionProvider->hasClass($node->extends->toString());
```

**Comment by staabm** [comment]
> parent class not autoloaded can be checked by

your example only works for the immediate parent. I think we would need something which also works, if the parent is autoloadable, but e.g. the grandparent (or one of the grandparent parents) is not autoloadable.

I did not yet find a way todo that

**Comment by samsonasik** [comment]
if you're using `ClassReflection`, that can actually be detected by `betterReflectionClass` -> `parentClassName` via privatesAccessor:

https://github.com/rectorphp/rector/blob/d9fb45c92e6b09506dab60563e7c9a951805311d/rules/Privatization/Guard/ParentPropertyLookupGuard.php#L74-L79

**Comment by staabm** [comment]
lets see whether we can get rid of this ulgy reflection hack with the help of https://github.com/Roave/BetterReflection/pull/1359

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-src/pull/4619
