### ISSUE TITLE
rector endless loop/segfault

### ISSUE THREAD

**Issue by mskoric** [rectorphp/rector#8094]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v. 017.7            |

Rector got stuck (macos 13.4.1) or segfaults (docker php-cli 8.1 image)

## Minimal PHP Code Causing Issue

https://getrector.com/demo/a286068e-5b27-436c-92a3-e6df24d2cc71

## Expected Behaviour

no segfault

**Comment by samsonasik** [comment]
Reproduced with 3 rules:

```
use Rector\CodeQuality\Rector\BooleanNot\SimplifyDeMorganBinaryRector;
use Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector;
use Rector\Strict\Rector\Empty_\DisallowedEmptyRuleFixerRector;
```

Ref https://getrector.com/demo/1a837c54-bbbc-4885-8a16-cac8caf7fdc1
