### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector

### ISSUE THREAD

**Issue by ChrisB9** [rectorphp/rector#8095]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/05da0364-f380-433e-b61c-06cd305d5f30

Non-final version:
https://getrector.com/demo/b6044ca3-5d01-4c37-a8ec-7e2f441282b4

```php
<?php

final class DemoFile
{
    private string $method;
    
    public static function create(int $a): static
    {
        $self = new static();
        $self->method = 'hi';
        $self->method = 'hello';
        return $self;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

https://3v4l.org/hv7TE#v8.2.7

This does not work. The rule should not transform the property to readonly, as it is being overwritten immediately.
The rule works properly if `new self()` instead of `new static()` is used.

**Comment by Bellardia** [comment]
I don't think this is knowable, there's no way to know what `static` will potentially resolve to

**Comment by samsonasik** [comment]
For final class, you should use `new self()` instead of `new static()` that make sure it goes to current class, ref https://getrector.com/demo/cf850647-ff8e-4b11-b3e4-c08b75197b57

**Comment by ChrisB9** [comment]
Exactly, because we dont know what static is going to do, and the file isnt final, this is a wrong behaviour. We are able to determine whether `new static` is used. If it is being used, readonly should not be applied.

**Comment by samsonasik** [comment]
Could you create failing test case PR? You can click "Create a Test" button at demo page

**Comment by ChrisB9** [comment]
This is the failing result: https://github.com/rectorphp/rector-src/actions/runs/5693431322/job/15432513817?pr=4616
