### ISSUE TITLE
Naive Conversion of Coalesce to UnionType

### ISSUE THREAD

**Issue by Bellardia** [rectorphp/rector#8097]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.17.7             |

## Minimal PHP Code Causing Issue

`NodeTypeResolver` resolves `Coalesce` Expressions by converting them to `UnionTypes`, but ignores the non-nullability property of the overall expression.

```
if ($node instanceof Coalesce) {
    $first = $this->getType($node->left);
    $second = $this->getType($node->right);
    if ($this->isUnionTypeable($first, $second)) {
        return new UnionType([$first, $second]);
    }
}
```

Consider a minimal function:
```
<?php

class MyClass {
    public function MyFunction(?string $string = null) {
        return strpos($string ?? '', 'search_string');
    }
}
```

With type detection on the `Coalesce` Expr:
```
public function refactor(Node $node): ?Node
{
    $type = $this->getType($argument);
    var_dump($type->isNull()->maybe());
}
```

Output:
```
bool(true)
```

The `left` side of `Coalesce` is nullable, but the `right` side isn't, so we know that the final expression here is for sure a non-nullable string. The net effect here is when detecting types at scale, many end up null poisoned.

## Expected Behaviour

The nullability of `left` side expressions should be ignored when constructing `UnionTypes` from `Coalesce`

**Comment by samsonasik** [comment]
@Bellardia could you porvide test case fixture on specific rules-tests, as well as the patch? Thank you.

**Comment by Bellardia** [comment]
I've yet to look at the development side of this library but if I can figure it out without too much fiddling I'd be happy to!
