### ISSUE TITLE
System error: "Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper::mapToPHPStanPhpDocTypeNode

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#8099]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest dev-main             |

Rector is producing this error:

```json
{
    "totals": {
        "changed_files": 0,
        "errors": 1
    },
    "errors": [
        {
            "message": "System error: \"Rector\\PHPStanStaticTypeMapper\\PHPStanStaticTypeMapper::mapToPHPStanPhpDocTypeNode for PHPStan\\Type\\ConditionalType\"\nRun Rector with \"--debug\" option and post the report here: https://github.com/rectorphp/rector/issues/new",
            "file": "/var/www/src/../storage/demo/nhiokqbj8b3in8kegccs/rector_analyzed_file.php",
            "line": 36
        }
    ]
}
```

## Minimal PHP Code Causing Issue

The error happens with the following phpdoc (from [class `ParameterBag` in Symfony DependencyInjection](https://github.com/symfony/symfony/blob/7c0b00c86148428c3d732802db3fb69380b057d5/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php#L171-L185)):

```php
<?php

namespace Symfony\Component\DependencyInjection\ParameterBag;

class ParameterBag
{
    /**
     * @template TValue of array<array|scalar>|scalar
     *
     * @param TValue $value
     *
     * @return (TValue is scalar ? array|scalar : array<array|scalar>)
     */
    public function resolveValue(mixed $value, array $resolving = []): mixed
    {
        return '';
    }
}
```

The problem happens with `DowngradeLevelSetList::DOWN_TO_PHP_74`:

https://getrector.com/demo/ccaae362-0585-4dfe-8136-02bd85684fc2

And it does not happen with `DowngradeLevelSetList::DOWN_TO_PHP_80`:

https://getrector.com/demo/a5718e52-8605-42c9-ac2a-2cc29fb9c870

I also checked in PHPStan, and it seems to work well there:

https://phpstan.org/r/718555a5-2550-4001-86e8-e55f5ee43670

**Comment by leoloso** [comment]
Removing `@param TValue $value` from the phpdoc still fails:

https://getrector.com/demo/81b8be31-65f2-49f5-99c2-68f9e44aa78d

**Comment by leoloso** [comment]
Removing any of the 2 remaining lines in the phpdoc will work well:

- https://getrector.com/demo/c8dadd49-7483-4d26-b5d9-9bae15ddaf3d
- https://getrector.com/demo/9fe6486e-a537-4eea-838a-789075fcfcea

Then the problem happens with those 2 lines are present:

```php
    /**
     * @template TValue of array<array|scalar>|scalar
     *
     * @return (TValue is scalar ? array|scalar : array<array|scalar>)
     */
```

**Comment by leoloso** [comment]
Returning `void` works well (https://getrector.com/demo/eb76ce70-87b5-4adb-89ec-6ed9b1ed8f6a):

```php
<?php

namespace Symfony\Component\DependencyInjection\ParameterBag;

class ParameterBag
{
    /**
     * @template TValue of array<array|scalar>|scalar
     *
     * @return (TValue is scalar ? array|scalar : array<array|scalar>)
     */
    public function resolveValue(): void
    {
    }
}
```

Returning `mixed` fails (https://getrector.com/demo/9c209e37-6e9c-4ba3-9a1d-93f166e4bacc):

```php
<?php

namespace Symfony\Component\DependencyInjection\ParameterBag;

class ParameterBag
{
    /**
     * @template TValue of array<array|scalar>|scalar
     *
     * @return (TValue is scalar ? array|scalar : array<array|scalar>)
     */
    public function resolveValue(): mixed
    {
    }
}
```

**Comment by leoloso** [comment]
I've narrowed down the issue to `DowngradeMixedTypeDeclarationRector` (https://getrector.com/demo/d1747578-c640-46a9-81ab-aee3f566d107):

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\DowngradePhp80\Rector\FunctionLike\DowngradeMixedTypeDeclarationRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rules([
        DowngradeMixedTypeDeclarationRector::class,
    ]);
};
```

**Comment by samsonasik** [comment]
new TypeMapper seems needed for ConditionalType on https://github.com/rectorphp/rector-src/tree/main/packages/PHPStanStaticTypeMapper/TypeMapper
