### ISSUE TITLE
Incorrect behavior of RemoveUselessParamTagRector

### ISSUE THREAD

**Issue by mkrauss** [rectorphp/rector#8101]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/ccf6adb1-c29a-46aa-97df-98fe051d5fd7

```php
<?php

final class DemoFile
{
    private string $env;
    
    /**
     * @ApiDoc(
     *   description = "Some Description"
     *
     * )
     *
     * @Route("/some/route")
     *
     * @param bool $sandbox
     */
    public function __construct(bool $sandbox)
    {
        if ($sandbox) {
            $this->env = 'sandbox';
        } else {
            $this->env = 'prod';
        }
    }
}
```

### Responsible rules

* `RemoveUselessParamTagRector`

## Expected Behavior

No extra changes should be made - the param annotation should be removed without additions.

The param annotation is correctly removed, however, in the case that there is another annotation tag in the same docblock, containing an extra blank line (perhaps to separate two parameters, but you can see in this example, even if it is just a dangling line), it also duplicates everything between that line and the end of the docblock.

**Comment by samsonasik** [comment]
Could you create failing fixture PR for it, you can click "Create a Test" button at the demo page, thank you.
