### ISSUE TITLE
Add FollowParentReturnTypeRector and FollowParentParamTypeRector

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#8104]
# Feature Request

 
## Diff 

```diff
class SomeParent
{
    public function run(): string {}
}

class SomeChild extends SomeParent
{
-    public function run
+    public function run: string
    {}
}
```

@TomasVotruba @staabm I think this rule can help upgrading app that the vendor already typed, so consumer app can match the return type to avoid error and manual verify.

Above is example for return type follow, param type should follow as well.

**Exclusion**:  `__construct()` is special, even for param, as `__construct()` can define different param or no param at all at child.

**Comment by staabm** [comment]
your example has a few typos, but I guess your point is to "copy" the native return type from a parent class?

**Comment by samsonasik** [comment]
Yes, something like that 👍

**Comment by TomasVotruba** [comment]
This looks good to me :+1:

**Comment by staabm** [comment]
a similar thing would be useful for properties, as I am currently running into things like https://3v4l.org/IonFf

**Comment by samsonasik** [comment]
For return type, it seems there is already `AddReturnTypeDeclarationBasedOnParentClassMethodRector`, just need to lower minimum php version to php 7.x

https://getrector.com/demo/ed7376e7-fd2a-41c2-a6a8-dbf76aa66eda

**Comment by samsonasik** [comment]
@staabm it seems no type in child is fine for direct usage for php 7.2+ https://3v4l.org/LuctN#v7.2.0 while error on php <=7.1 https://3v4l.org/LuctN#v7.1.33

I think for safer upgrade, the parent and child must be equal typed.

**Comment by samsonasik** [comment]
I think most of issue is happen when parent vs child have different type for both typed https://3v4l.org/R8AsX#v7.2.34

**Comment by samsonasik** [comment]
I think param is mostly safe to update only parent for php 7.2+, while error on PHPStan https://phpstan.org/r/e21f2c21-9ee6-47a1-8620-e23f0682da36

 except child is different type, but if that happen, that wil error on the first place https://3v4l.org/8jTDB#v7.2.34

**Comment by samsonasik** [comment]
Ok, PHPStan error seems "fine", as that not php error https://phpstan.org/r/e21f2c21-9ee6-47a1-8620-e23f0682da36 

When child has no type or mixed, it can use the param as anything, eg: "string" https://3v4l.org/XTiMJ or https://3v4l.org/DmKhU ,

 When adding type on child, it may cause error without usage of param context https://3v4l.org/7evZC

**Comment by staabm** [comment]
yeah, rule of thumb is

parameter need to be contravariant when defined
return types need to be covariant when defined
property types need to be invariant when defined

https://www.php.net/manual/en/language.oop5.variance.php

**Comment by samsonasik** [comment]
Ok, param seems mostly fine.

It is doable to be applied on property https://3v4l.org/CabBW

**Comment by TomasVotruba** [comment]
Any update on this one? I'd like to avoid staling here.

@samsonasik What rule would you like to implement to kick this one off and start testing in the wild?

**Comment by samsonasik** [comment]
@TomasVotruba I think we can close it for now, as it require check contravariant for param.

**Comment by TomasVotruba** [comment]
Agreed :+1:
