### ISSUE TITLE
Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in phpstan

### ISSUE THREAD

**Issue by mfleeson** [rectorphp/rector#8107]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |0.14.8             |

I'm trying to get https://github.com/mfleeson/joomla_com_upgrader (forked from original author who's let it lapse). It works through most of the files fine but then throws a 35 step stack trace, culminating in
Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in phar:///vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php:1040

## Expected Behaviour
It should move and rename files to fit in with Joomla 4 coding standards, unfortunately it crashes. 

I was wondering if I could get help in debugging it?
Thanks
Mark

**Comment by samsonasik** [comment]
Rector already 0.17.7, The `joomla_com_upgrader` still using `^0.14.4` which if you run composer update, you will only got latest `0.14.x` instaed of `0.17.x`, that's how `composer update` works on `0.x.y` version.

Try update to use latest rector `^0.17` and verify the compatiblity.

**Comment by mfleeson** [comment]
Thanks, that's helped move it on, I'm now getting the error:
[ERROR] Cannot autowire service "Rector\Naming\Rector\FileWithoutNamespace\JoomlaLegacyMVCToJ4Rector": argument
         "$removedAndAddedFilesCollector" of method "__construct()" has type
         "Rector\Core\Application\FileSystem\RemovedAndAddedFilesCollector" but this class was not found.
         
         I've searched for RemovedandAddedFilesCollector and found reference in github to a RemovedandAddedFilesProcessor but if I change Collector for Processor it says RemovedandAddedFilesProcessor not found either. Has this class been superceded and replaced?

**Comment by samsonasik** [comment]
Both services removed, you can use your own logic to add/remove file.

I am closing it then and let you resolve the compatibility ;)
