### ISSUE TITLE
Command vendor/bin/rector init is broken in new versions

### ISSUE THREAD

**Issue by nicolaspernot** [rectorphp/rector#8108]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.7             |

On version below I'm not able to execute the command `vendor/bin/rector init`. Doing so give me an error :
> Command "init" is not defined.

## Versions tested :
:red_circle: 0.17.7
:red_circle: 0.17.4
:red_circle: 0.17.2
:red_circle: 0.17.1
:green_circle: 0.17.0

## Steps :
```
mkdir test
cd test
composer init
composer require --dev rector/rector
vendor/bin/rector init
```
## More insights :
```
composer --version
Composer version 2.5.8 2023-06-09 17:13:21

php -v
PHP 8.1.21 (cli) (built: Jul  8 2023 07:09:57) (NTS)

vendor/bin/rector --version
Rector 0.17.7
```

Looks like this is broken from version 0.17.1.

## Expected Behaviour

Should create the rector.php file.

**Comment by samsonasik** [comment]
`init` no longer exists, you can just run:

```
vendor/bin/rector
```

and it will ask to generate rector.php for you, it already explained in documentation that init only exists on v < 0.17

```
For version 0.17.0 and lower specify the the init parameter.
```

https://getrector.com/documentation

**Comment by nicolaspernot** [comment]
Oh, my bad!
