### ISSUE TITLE
[DX] Add "setup-downgrade" to init easy downgrade builds, similar to "setup-ci"

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8109]
Rector is the only tool that can handle downgraded. Yet setting up the downgrade process is quite challenging when it comes to:

* path defintion
* scoper setup
* github action content
* /build directory logic including downgraded `composer.json`
* custom change in main `composer.json`, e.g. platform checks false etc.

Instead making this workflow available only to few who struggle through, there should be a helper command than handles this for users and make downgrading piede of cake :muscle: 

Note: make use of questiosn and link similar to `composer require` of a private package in composer. Ask for the token, and place it in the code for user themselves.

**Comment by samsonasik** [comment]
I will try

**Comment by TomasVotruba** [comment]
This issue is being stale and I realize there is no much need for it. The downgrade script can evolve as well, and it's safer to copy-paste it from most recent downgrade build, rather to create a dummy template that will get obsolete soon and will spread old outdated code :)

Closing as not needed
