### ISSUE TITLE
StrictStringParamConcatRector: support nullable string types

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8110]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/fb3aaeb1-d7bb-4cf3-af5f-43d0787f9b18

```php
<?php

final class DemoFile
{
    public static function getOrderBy($orderby, $direction = 'ASC', $default = '')
    {
        if (null !== $orderby && ! empty($orderby)) {
            return $orderby.' '.$direction;
        }

        return $default;
    }
}
```

### Responsible rules

* `StrictStringParamConcatRector`

## Expected Behavior

I think `StrictStringParamConcatRector` should add a nullable param type `?string` if the method body contains a `!== null` or `is_null()` check

**Comment by samsonasik** [comment]
Resolved by PR:

- https://github.com/rectorphp/rector-src/pull/4636

**Comment by staabm** [comment]
thanks
