### ISSUE TITLE
multiple users + [ERROR] Unable to create file ...

### ISSUE THREAD

**Issue by stefanides** [rectorphp/rector#8112]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.17.1            |

## Minimal PHP Code Causing Issue

Using rector with multiple users on the same machine (not reproducible on https://getrector.org/demo/)

## Expected Behaviour

Rector can be used by multiple users concurently on the same machine 

## Description

Hi, I am facing the same/similar like issue #8103 - when multiple users are using rector on the same machine, the cache files are shared on global `/tmp/` path allowing to create files there only to the first user. Others then see "Unable to create file..." because of wrong permissions on the "globally shared" location. 

Some cache paths can be configured, e.g. 
`$rectorConfig->cacheDirectory(__DIR__ . '/tmp/rector_cached_files');`

`php8.2 -d sys_temp_dir=./tmp ./vendor/bin/rector ...`

but even with this the aplication still wants write to `/tmp/cache/PHPStan`, `/tmp/cache/nette.configurator` and maybe more. Is there an (undocumented) way how to change ALL cache paths to some local directory or is it a bug that cache location cannot be changed to anything else than `/tmp`?

**Comment by samsonasik** [comment]
Hi, for run by multiple user, I gues you can configure the rector.php to set the temp dir by username in the config:

```php
return static function (RectorConfig $rectorConfig): void {
// ...
    $user = getenv('USERNAME') ?: getenv('USER');

    $rectorConfig->cacheDirectory(sys_get_temp_dir() . '/' . $user .  '/rector_cached_files');
    $rectorConfig->containerCacheDirectory(sys_get_temp_dir() . '/' . $user);
// ...
};
```

**Comment by TomasVotruba** [comment]
Closing as stale to avoid piling possible solved issue. Thanks for understanding :+1:
