### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivatePropertyRector

### ISSUE THREAD

**Issue by mkrauss** [rectorphp/rector#8113]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/4584b694-07c3-41c6-a015-9ee29ea9a781

```php
<?php

class Foo
{
    /** @var string */
    private $thing1;

    /** @var string */
    private $thing2;

    /** @var string */
    private $thing3;

    /** @var string */
    private $thing4;

    /** @var string */
    private $thing5;

    /** @var string */
    private $thing6;

    public function __construct(
        string $thing1,
        string $thing2,
        string $thing3,
        string $thing4,
        string $thing5,
        string $thing6
    ) {
        $this->thing1 = $thing1;
        $this->thing2 = $thing2;
        $this->thing3 = $thing3;
        $this->thing4 = $thing4;
        $this->thing5 = $thing5;
        $this->thing6 = $thing6;
    }

    public function doSomethings()
    {
        echo $this->thing3;
    }
}
```

### Responsible rules

* `RemoveUnusedPrivatePropertyRector`

## Expected Behavior

The constructor parameters for the unused and removed class attributes should also be removed. The only parameter remaining should be `$thing3`, just as it is the only class attribute, and the only constructor assignment remaining.

Note that, in various classes in our code base, I've seen cases where some parameters are removed, but not all - and with no discernible pattern to which ones. However, in trying to create a test case that works on the demo site, I've been unable to reproduce that. In this case, on my machine, parameter `$thing6` is removed (which is why there are so many parameters, to try to show that) but on the demo site, it is not. It seems like the attributes and assignments are removed very reliably, but the parameters are sketchy at best.

**Comment by samsonasik** [comment]
This is expected, that should be covered by RemoveUnusedConstructorParamRector, that limited to avoid remove before middle param to avoid bc break, if you found a bug on the RemoveUnusedConstructorParamRector, check the existing behaviour first 

https://github.com/rectorphp/rector-src/tree/main/rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedConstructorParamRector/Fixture
