### ISSUE TITLE
Incorrect behavior of AddMethodCallBasedStrictParamTypeRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8116]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/87060280-79c0-4bc6-b9de-30e2c749eae7

```php
<?php

/**
 * Clx_Model_Abstract.
 */

/**
 * Abstract model class
 * Accessable properties must be protected and must have Getter and Setter.
 *
 * @copyright  Copyright (c) 2011 Complex GmbH (http://www.complex-it.de)
 */
abstract class Clx_Model_Abstract
{
    /**
     * Return array of object for json use.
     *
     * @return array<string, mixed>
     */
    public function toJson()
    {
        return $this->toArray(true);
    }

    /**
     * Return string representation of object.
     *
     * @return string
     */
    public function __toString()
    {
        return implode(', ', $this->toArray());
    }
    
    /**
     * Returns array of object.
     *
     * @param bool|string[] $cols
     *
     * @return array<string, mixed>
     */
    final public function toArray($cols = false)
    {
        if ((! is_bool($cols)) && (! is_array($cols))) {
            throw new Exception('Invalid value cols');
        }
    }

}
```

### Responsible rules

* `AddMethodCallBasedStrictParamTypeRector`

## Expected Behavior

~~should be skipped because the method beeing worked on contains a `is_array()` check~~

hmm I think it should be skipped because its a `public` method

**Comment by samsonasik** [comment]
The usage is always bool since default is false (bool type) if no arg passed.

**Comment by samsonasik** [comment]
I think we can limit with:

- allow protected method on final class
- allow private method
- skip public method

**Comment by samsonasik** [comment]
Oh, protected should be skipped if has parent non-typed https://3v4l.org/i7Cb4

**Comment by samsonasik** [comment]
ParentClassMethodTypeOverrideGuard should cover has parent method protected

**Comment by staabm** [comment]
> I think we can limit with:

allow protected method on final class
allow private method
skip public method

This constraints only work as long as the rule in question does work on signatures, but not on call-sites. 

I think we need to skip everything but private, because we will likely not know all call-sites involved (e.g. because call sites might not be properly typed)

**Comment by samsonasik** [comment]
I see, we can limit for private method then 👍
