### ISSUE TITLE
Rector not scanning paths one level up

### ISSUE THREAD

**Issue by binaryfire** [rectorphp/rector#8117]
Thanks for your work on this great package!

I'm having a problem with Rector not being able to scan paths one directory up, eg `/../modules`

```
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/app',
        __DIR__ . '/config',
        __DIR__ . '/../modules',
        __DIR__ . '/test',
    ]);
```

It's not a permissions problem because I'm autoloading modules from this directory in Composer with no problems. I tried debugging like this:

```
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/app',
        __DIR__ . '/config',
        __DIR__ . '/../modules',
        __DIR__ . '/test',
    ]);

    $modulesPath = __DIR__ . '/../modules';
    echo 'Scanning path: ', realpath($modulesPath), PHP_EOL;
```

But the printed path is empty. When I use `$modulesPath = __DIR__ . '/app';` it prints the full path of `app` as expected

**Comment by samsonasik** [comment]
This is expected. Scan outside project path that different with rector autoload will cause autoload jugling. Instead, define rector.php per project root and use that config.
