### ISSUE TITLE
Incorrect functioning of ReturnTypeFromStrictTypedCallRector with cache and parallel execution

### ISSUE THREAD

**Issue by NikDevPHP** [rectorphp/rector#8124]
# Bug Report

Rector version 0.17.10. PHP 8.1.

1. Run rector with --dry-run
2. Issue was founded
![image](https://github.com/rectorphp/rector/assets/11384994/1de11390-93de-4971-9fdb-f8301dbfd92d)
3. Run rector without --dry-run
4. Issue has not been fixed

If delete the cache and run immediately without --dry-run flag, then it is fixed.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/1d666008-2a85-4475-ad60-6dae03df7678)

## Expected Behaviour

ReturnTypeFromStrictTypedCallRector

library/vendor/bin/rector process --config rector.php --dry-run

library/vendor/bin/rector process --config rector.php

The issue should to be fixed.

**Comment by samsonasik** [comment]
we need reproducer repo and step by step to reproduce bug, otherwise, we just shoting in the dark :)

**Comment by samsonasik** [comment]
I am closing it as it can't be reproduced, feel free to open new issue with include reproducible github repo, better with github action, or e2e tests for it so it can be solvable ;)
