### ISSUE TITLE
`get_headers` `$associative` changed type on php8

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#8125]
# Feature Request

Thank you very much for making rector. It simplifies my work :heart: 
 
I'm currently upgrading a legacy project to php8. I stumbled upon a use of `get_headers`, which rector isn't aware of it's changes parameter `$associative`.

https://www.php.net/manual/en/function.get-headers.php#refsect1-function.get-headers-changelog
https://getrector.com/demo/06beb867-accf-4a43-a749-442098f0938b

## Diff 

[](https://getrector.com/demo/06beb867-accf-4a43-a749-442098f0938b)

```diff
-get_headers($url, 1);
+get_headers($url, true);
```

**Comment by samsonasik** [comment]
Hi, this should be as simple as add new config in php80.php with 

```php
    $rectorConfig
        ->ruleWithConfiguration(FunctionArgumentDefaultValueReplacerRector::class, [
            new ReplaceFuncCallArgumentDefaultValue('get_headers', 1, 1, true),
        ]);
```

Ref https://getrector.com/demo/29028adb-9f42-42d8-8f33-616215b73475

Could you create PR to https://github.com/rectorphp/rector-src/blob/main/config/set/php80.php , thank you.
