### ISSUE TITLE
[0.17.11] Issue with Enums

### ISSUE THREAD

**Issue by rcerljenko** [rectorphp/rector#8126]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.11            |

After upgrading to latest Rector version I'm getting this error related to Enums that I have in my codebase:
```
Could not process "<file-name>" file, due to:
ReflectionEnum::$betterReflectionClass does not exist
```

## Minimal PHP Code Causing Issue

Just have any kind of Enum in scanned files...

**Comment by samsonasik** [comment]
Could you reproduced at https://getrector.com/demo ?

**Comment by KennedyTedesco** [comment]
The issue is on the `TYPE_DECLARATION` setlist.

```
$rectorConfig->import(SetList::TYPE_DECLARATION);
```

**Comment by samsonasik** [comment]
Reproduced with single rule https://getrector.com/demo/a1fd1e68-ba6b-4114-be3e-b2bd6932b018

`\Rector\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector::class`

You can skip for now while wait for the fix :)

**Comment by KennedyTedesco** [comment]
@samsonasik Another example:

https://getrector.com/demo/59b39c33-5eb8-4978-a962-1fdc878b6bbb

Even after suppressing the `AddParamBasedOnParentClassMethodRector`, the issue still occurs. So I'm suppressing both, including `SetList::TYPE_DECLARATION` for now.

**Comment by samsonasik** [comment]
@KennedyTedesco the `ParentClassMethodTypeOverrideGuard` is used in various rules, that's why it make crash in multiple rules, it should be resolved in latest dev-main, please try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main#fb1f63e38beba465ddd7c42c1b1e867d72a9faf8
```

**Comment by KennedyTedesco** [comment]
@samsonasik Awesome! I have tested it, and everything is working perfectly now. Thank you.

**Comment by TomasVotruba** [comment]
I'll make a new tag :+1: 

Thank for quick fix @samsonasik

**Comment by TomasVotruba** [comment]
The 0.17.12 is just baking... should be out in 5 mins :rocket:
