### ISSUE TITLE
"[ERROR] The given paths do not match any files" when using wildcards in the paths

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#8127]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.12            |

I'm using wildcards in the paths to process my files, such as:

```php
    $paths = [
            $this->rootDirectory . '/layers/Engine/packages/*/src/*',
            $this->rootDirectory . '/layers/Engine/packages/*/tests/*',
    ];
    $rectorConfig->paths($paths);
```

This had so far been supported by Rector, however now I get an error:

```
[ERROR] The given paths do not match any files
```

## Potential source of the issue

@staabm I assume the issue was introduced in this PR: https://github.com/rectorphp/rector-src/pull/4326

Checking the source code for method `addPaths` in `src/StaticReflection/DynamicSourceLocatorDecorator.php`:

```php
    public function addPaths(array $paths) : void
    {
        if ($paths === []) {
            return;
        }
        $files = $this->fileAndDirectoryFilter->filterFiles($paths);
        $this->dynamicSourceLocatorProvider->addFiles($files);
        $directories = $this->fileAndDirectoryFilter->filterDirectories($paths);
        foreach ($directories as $directory) {
            $filesInDirectory = $this->phpFilesFinder->findInPaths([$directory]);
            $this->dynamicSourceLocatorProvider->addFilesByDirectory($directory, $filesInDirectory);
        }
    }
```

and following to methods `filterDirectories` and `filterFiles` in `src/FileSystem/FileAndDirectoryFilter.php`, I can see that these do not support wildcards:

```php
    public function filterDirectories(array $filesAndDirectories) : array
    {
        $directories = \array_filter($filesAndDirectories, static function (string $path) : bool {
            return \is_dir($path);
        });
        return \array_values($directories);
    }

    public function filterFiles(array $filesAndDirectories) : array
    {
        $files = \array_filter($filesAndDirectories, static function (string $path) : bool {
            return \is_file($path);
        });
        return \array_values($files);
    }
```

**Comment by samsonasik** [comment]
@leoloso sound reasonable for me, it seems needs an fnmatch check usage with FilesystemTweaker

https://github.com/rectorphp/rector-src/blob/1659ca292848fc1722b4b084d9fd1625b21e69c9/src/FileSystem/FilesystemTweaker.php#L16

**Comment by staabm** [comment]
thanks for the report.

sounds like we are missing some test-coverage in this area. would be great you could cover a fix with a test

**Comment by samsonasik** [comment]
@staabm I created e2e test for that at PR:

- https://github.com/rectorphp/rector-src/pull/4765
