### ISSUE TITLE
Incorrect behavior of FuncCallToStaticCallRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8128]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/0e80986e-1e74-44a5-b14e-d9f3fb851eaf

```php
<?php

echo stylesheet_link_tag(
            '/css/style.css',
            '/css/cms.css',
            '/css/complex.css'
);
```

### Responsible rules

* `FuncCallToStaticCallRector`

## Expected Behavior

the newlines in the argument list should be preserved

```php
<?php

echo \rocket\helper\UrlHelper::stylesheet_link_tag(
            '/css/style.css',
            '/css/cms.css',
            '/css/complex.css'
);
```

**Comment by samsonasik** [comment]
That's expected as replace node with new node. That need to be handled by coding standard tool.
