### ISSUE TITLE
Incorrect behavior of RemoveUnusedVariableInCatchRector

### ISSUE THREAD

**Issue by marmichalski** [rectorphp/rector#8131]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/18be2f38-6db9-4d3b-a4da-db861dc424b4

```php
<?php

final class DemoFile
{
    public function run()
    {
        $triesLeft = 3;
        
        do {
            try {
                return 'method that might throw';
            } catch (\RuntimeException $failure) {
                continue;
            }
        } while ($triesLeft --> 0);
        
        throw $failure;
    }
}
```

### Responsible rules

* `RemoveUnusedVariableInCatchRector`

## Expected Behavior

Rector should not remove variable from the catch.

**Comment by samsonasik** [comment]
Hi, I think you can skip via `$rectorConfig->skip()` for that as that already out of current StmtsAware scope.

**Comment by marmichalski** [comment]
> Hi, I think you can skip via `$rectorConfig->skip()` for that as that already out of current StmtsAware scope.

I do, but I would not call that a solution, considering it used to work few versions back. 😸

**Comment by samsonasik** [comment]
You can refactor to add counter check inside do than throw that 

https://getrector.com/demo/1bfc069c-acb2-43c2-81d0-c33afd544c55

that's the variable will always on scope area and exists ;)

**Comment by samsonasik** [comment]
Ok, I am closing it, thank you for understanding ;)

**Comment by kunicmarko20** [comment]
Hey @samsonasik how is this not considered a bug?

**Comment by samsonasik** [comment]
as answered, because the usage is out of scope variable.

**Comment by AnrDaemon** [comment]
Sorry to ping the closed issue, but please consider the following code:

```php
        try {
            $res = hw_get($name);
        } catch (\RangeException $e) {
            // Nothing found - all ok'
        } finally {
            if (!isset($e)) {
                throw new PlatformException("Component named '$name' already exists", -1, $module, $action);
            }
        }
```

With this rule enabled, and with the change suggested, the code will no longer work as expected.

**Comment by samsonasik** [comment]
@AnrDaemon that already skipped for used under finally https://getrector.com/demo/6c4cae5d-a4b6-48fa-a002-4dbfc2104b05

**Comment by AnrDaemon** [comment]
I'm quoting an actual code from the latest rector run on a project, where suggested change was to remove `$e` from catch.
https://getrector.com/demo/eec9a1cb-2350-4fa8-a50d-0f23633ee9db

**Comment by samsonasik** [comment]
I see, that part of php 8.0 set, I thought it on deadCode set, I will check when I have a chance
