### ISSUE TITLE
[Rector 1.0] Introduce regex tool that will handle regex changes on non-php files, based on Rector json config

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8136]
To help out with configs, templates atd.

Provide file processor to allow easy extension.

Deal with needs from:

* https://github.com/rectorphp/rector-src/pull/4761

**Comment by samsonasik** [comment]
is existing `FileProcessorInterface` enough so user can implements and it will automatically cover run?

**Comment by TomasVotruba** [comment]
Related Twitter poll: https://twitter.com/VotrubaT/status/1698641666314322318

**Comment by TomasVotruba** [comment]
Closing for now, as not planned and outside PHP scope. This opens space for community package to handle these.
