### ISSUE TITLE
Add possibility of adding multiple phpstan neon files

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#8141]
# Feature Request

As mention in https://github.com/rectorphp/rector/issues/8140 it would be great to configure the phpstan extension from the rector.php file and not have additonal phpstan or change the own phpstan configuration for it.
 
## Diff 

```diff
-    $rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon');
+    $rectorConfig->phpstanConfigs([
+        '__DIR__ . '/phpstan.neon',
+        '__DIR__ . '/vendor/phpstan/phpstan-doctrine/extension.neon',
+        '__DIR__ . '/vendor/phpstan/phpstan-symfony/extension.neon',
+    ]);
```

I think it would make sense then deprecate `phpstanConfig` in favor of `phpstanConfigs`. In cases of `rector-symfony`, `rector-doctrine`, ... the docs should be mentioning configuring this. So rector works correctly on symfony services and doctrine entities, ...

**Comment by TomasVotruba** [comment]
Sounds good :+1:  Could you send a PR?

**Comment by staabm** [comment]
fyi, we will protoype a separate approach which can utilize the phpstan extension installer.

therefore maybe this change is not required..  we have an idea but did not yet have time to test it

**Comment by staabm** [comment]
> fyi, we will protoype a separate approach which can utilize the phpstan extension installer.

the idea is described here: https://github.com/phpstan/phpstan/issues/9770

my local testing suggests it works

**Comment by TomasVotruba** [comment]
> fyi, we will protoype a separate approach which can utilize the phpstan extension installer.

@staabm That would return the issue we had before. Some PHPStan extension require custom autoload, that require some autoload. I'd say none of the extension features except generics container/mocks etc. is used in Rector rules. That's why configs should be handled completely outside Rector scope.

**Comment by staabm** [comment]
my point is, that after the linked PHPStan issue is fixed, I could include a PHPStan config using
`$rectorConfig->phpstanConfig(__DIR__ . '/rector-phpstan.php');`
and from that config I would use the extension installer to auto discover the required .neon config files.

that means its a mean to easy auto-discovery for those who want it, but rector would not do it out-of-the-box.



> That would return the issue we had before. Some PHPStan extension require custom autoload, that require some including files right out of project container

if I get your point right, you mean we are registering more services then required (e.g. new PHPStan rules etc), but for rector only ReturnTypeExtensions etc. are usefull?

**Comment by TomasVotruba** [comment]
> I get your point right, you mean we are registering more services then required (e.g. new PHPStan rules etc), but for rector only ReturnTypeExtensions etc. are usefull?

Exactly. Maybe stubs on generics like  `$container->get(SomeType::class)`. But I haven't seen a project, where adding anything else would help Rector work better.

**Comment by OskarStark** [comment]
I agree with you @staabm 👍🏻

**Comment by TomasVotruba** [comment]
@staabm If this config would be build by PHPStan itself, I can be included by Rector with single line, the same we do with Symfony container to fetch services. But we won't return the container building internals so we don't leap into maintaining external tools.

**Comment by staabm** [comment]
> If this config would be build by PHPStan itself, I can be included by Rector with single line

I agree. thats what I try to achieve in https://github.com/phpstan/phpstan/issues/9770 :-)
