### ISSUE TITLE
`StaticClosureRector` removes empty lines in Closure

### ISSUE THREAD

**Issue by chescos** [rectorphp/rector#8142]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.0             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/cc564ae0-68c3-4df6-bbd9-1b72ce6a94ab

## Expected Behaviour

I would expect the `StaticClosureRector` rule to not remove any empty lines from the code within a Closure. It currently seems to remove all empty lines inside a Closure.

**Comment by samsonasik** [comment]
That should besolved in next php-parser 5.0, see:

- https://github.com/nikic/PHP-Parser/pull/891

php-parser currently still in v4.17.1 https://github.com/nikic/PHP-Parser/releases/tag/v4.17.1

The static printer preserving on Closure is on master branch which will only available on next php-parser 5, but we don't know when that released as that we need wait for integration in phpstan first too :)
