### ISSUE TITLE
TypedPropertyFromAssignsRector fails with PHP 7.4

### ISSUE THREAD

**Issue by buffcode** [rectorphp/rector#8145]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.0            |

## Minimal PHP Code Causing Issue

Error only comes up when running Rector with PHP 7.4! Using 8.1 and the online demo I could not reproduce the error.

https://getrector.com/demo/d1d800ab-53c8-4208-9e91-5dca6ba52d49

```php
<?php

class CurlSoapClient extends \SoapClient
{

    /**
     * Curl-Handle
     * @var resource|null
     */
    private $curl;

    public function __construct($wsdl, array $options = null)
    {
        parent::__construct($wsdl, $options);
    }
}
```

## Expected Behaviour

No change / error

## Current Behaviour

```
[file] CurlSoapClient.php
[rule] Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector

 [ERROR] Could not process "CurlSoapClient.php" file, due to:
         "System error: "Syntax error, unexpected T_FUNCTION, expecting T_VARIABLE479, Syntax error, unexpected
         T_FUNCTION, expecting T_VARIABLE714, Syntax error, unexpected T_FUNCTION, expecting T_VARIABLE799"
```

<details><summary>Stack trace</summary>
<p>

         Stack trace:
         #0 vendor/rector/rector/packages/PhpDocParser/PhpParser/SmartPhpParser.php(29):
         PHPStan\Parser\RichParser->parseFile('phar:///var/www...')
         #1 vendor/rector/rector/src/PhpParser/AstResolver.php(299):
         Rector\PhpDocParser\PhpParser\SmartPhpParser->parseFile('phar:///var/www...')
         #2 vendor/rector/rector/src/PhpParser/AstResolver.php(119):
         Rector\Core\PhpParser\AstResolver->parseFileNameToDecoratedNodes('phar:///var/www...')
         #3 vendor/rector/rector/src/PhpParser/AstResolver.php(188):
         Rector\Core\PhpParser\AstResolver->resolveClassMethodFromMethodReflection(Object(PHPStan\Reflection\Native\Nat
         iveMethodReflection))
         #4 vendor/rector/rector/src/PhpParser/AstResolver.php(207):
         Rector\Core\PhpParser\AstResolver->resolveClassMethod('SoapClient', '__construct')
         #5 vendor/rector/rector/src/NodeAnalyzer/PropertyFetchAnalyzer.php(142):
         Rector\Core\PhpParser\AstResolver->resolveClassMethodFromCall(Object(PhpParser\Node\Expr\StaticCall))
         #6 vendor/rector/rector/rules/TypeDeclaration/AlreadyAssignDetector/ConstructorAssignDetector.php(85):
         Rector\Core\NodeAnalyzer\PropertyFetchAnalyzer->isFilledViaMethodCallInConstructStmts(Object(PhpParser\Node\St
         mt\Class_), 'curl')
         #7 vendor/rector/rector/rules/TypeDeclaration/TypeInferer/AssignToPropertyTypeInferer.php(153):
         Rector\TypeDeclaration\AlreadyAssignDetector\ConstructorAssignDetector->isPropertyAssigned(Object(PhpParser\No
         de\Stmt\Class_), 'curl')
         #8 vendor/rector/rector/rules/TypeDeclaration/TypeInferer/AssignToPropertyTypeInferer.php(104):
         Rector\TypeDeclaration\TypeInferer\AssignToPropertyTypeInferer->shouldAddNullType(Object(PhpParser\Node\Stmt\C
         lass_), 'curl', Array)
         #9
         vendor/rector/rector/rules/TypeDeclaration/TypeInferer/PropertyTypeInferer/AllAssignNodePropertyTypeInferer.php
         (41):
         Rector\TypeDeclaration\TypeInferer\AssignToPropertyTypeInferer->inferPropertyInClassLike(Object(PhpParser\Node
         \Stmt\Property), 'curl', Object(PhpParser\Node\Stmt\Class_))
         #10 vendor/rector/rector/rules/TypeDeclaration/Rector/Property/TypedPropertyFromAssignsRector.php(142):
         Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer\AllAssignNodePropertyTypeInferer->inferProperty(Object(
         PhpParser\Node\Stmt\Property), Object(PHPStan\Reflection\ClassReflection))
         #11 vendor/rector/rector/src/Rector/AbstractRector.php(189):
         Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector->refactor(Object(PhpParser\Node\Stmt\Cla
         ss_))
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Class_))
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray(Array)
         #16 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):
         PhpParser\NodeTraverser->traverse(Array)
         #17 vendor/rector/rector/src/Application/FileProcessor.php(44):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #18 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(100):
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File))
         #19 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(178):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil
         e), Object(Rector\Core\ValueObject\Configuration))
         #20 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(152):
         Rector\Core\Application\ApplicationFileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File)
         , Array, Object(Rector\Core\ValueObject\Configuration))
         #21 vendor/rector/rector/packages/Parallel/WorkerRunner.php(56):
         Rector\Core\Application\ApplicationFileProcessor->processFiles(Array,
         Object(Rector\Core\ValueObject\Configuration))
         #22 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)
         #23 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202308\Evenement\EventEmitter->emit('data', Array)
         #24 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202308\Clue\React\NDJson\Decoder->handleData(Array)
         #25 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202308\Evenement\EventEmitter->emit('data', Array)
         #26 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202308\React\Stream\Util::RectorPrefix202308\React\Stream\{closure}('{"action":"main...')
         #27 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202308\Evenement\EventEmitter->emit('data', Array)
         #28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202308\React\Stream\DuplexResourceStream->handleData(Resource id #2202)
         #29 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202308\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(73):
         RectorPrefix202308\React\EventLoop\StreamSelectLoop->run()
         #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202308\Symfony\Component\Console\Input\A
         rgvInput), Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(944):
         RectorPrefix202308\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202308\Symfony\Component\
         Console\Input\ArgvInput), Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))
         #33 vendor/rector/rector/vendor/symfony/console/Application.php(326):
         RectorPrefix202308\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work
         erCommand), Object(RectorPrefix202308\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))
         #34 vendor/rector/rector/src/Console/ConsoleApplication.php(61):
         RectorPrefix202308\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202308\Symfony\Component\Co
         nsole\Input\ArgvInput), Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(212):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202308\Symfony\Component\Console\Input\ArgvIn
         put), Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))
         #36 vendor/rector/rector/bin/rector.php(132): RectorPrefix202308\Symfony\Component\Console\Application->run()
         #37 vendor/rector/rector/bin/rector(4): require_once('vendor...')
         #38 vendor/bin/rector(115): include('vendor...')
         #39 {main}". On line: 56

</p>
</details>

**Comment by buffcode** [comment]
@samsonasik As stated the actual runtime needs to be 7.4. The online demo is using 8.1.18.
It has nothing to to with rector's PHP compatibility setting.

I have tried the exact same file and config running 7.4 vs 8.1 and it only triggers on 7.4.

Is there any boilerplate for those kind of tests? Then I can provide such a test of course.

**Comment by samsonasik** [comment]
Ok, I can reproduce:

```
➜  www mkdir rector-issue-8145
➜  www cd rector-issue-8145
➜  rector-issue-8145 php74 /usr/local/bin/composer require --dev rector/rector
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been created
Running composer update rector/rector
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking phpstan/phpstan (1.10.29)
  - Locking rector/rector (0.18.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing phpstan/phpstan (1.10.29): Extracting archive
  - Installing rector/rector (0.18.0): Extracting archive
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
Using version ^0.18.0 for rector/rector
➜  rector-issue-8145 vim CurlSoapClient.php
➜  rector-issue-8145 vim rector.php                 
➜  rector-issue-8145 php74 vendor/bin/rector process CurlSoapClient.php 
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [ERROR] Could not process "CurlSoapClient.php" file, due to:                                                           
         "System error: "Syntax error, unexpected T_FUNCTION, expecting T_VARIABLE479, Syntax error, unexpected         
         T_FUNCTION, expecting T_VARIABLE714, Syntax error, unexpected T_FUNCTION, expecting T_VARIABLE799"             
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 56
```

@TomasVotruba it possibly related with php setting in config

https://github.com/rectorphp/rector/blob/ca844057bcb6c096d4380a4a1624914a90b7de4b/config/phpstan/parser.neon#L20

**Comment by samsonasik** [comment]
ok, so the issue seems because it extends `\SoapClient`, which it load from **Jetbrain** phpstorm stubs:

https://github.com/JetBrains/phpstorm-stubs/blob/1f3696c6951c58395bf70e985256255e901767e9/soap/soap.php#L15

It loaded from vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/../../../../../jetbrains/phpstorm-stubs/soap/soap.stub

@TomasVotruba we probably need special handling if the loaded ClassReflection is from phpstan.phar under 

vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/../../../../../jetbrains/phpstorm-stubs/

genereally, as it cause **different** issue as well like in : 

- https://github.com/rectorphp/rector-src/pull/4492

**Comment by samsonasik** [comment]
The error is on line php 8 syntax on **Jetbrain** soap stubs:

https://github.com/JetBrains/phpstorm-stubs/blob/1f3696c6951c58395bf70e985256255e901767e9/soap/soap.php#L465

which attribute is inlined so it not marked as "comment" so cause Fatal error on PHP 7.4:

https://3v4l.org/a5rpa#v7.4.33

My assumption is PHPStan has different mechanism of including jetbrain stubs as the code is not downgraded, as by looking at ` DowngradeAttributeToAnnotationRector`, it remove the attribute, so it should be downgraded as the attribute gone already:

https://getrector.com/demo/0fb3d058-cf32-4265-946a-cde368a3e398

/cc @ondrejmirtes

**Comment by ondrejmirtes** [comment]
PHPStan does not downgrade its vendor dependencies. It would break `jetbrains/phpstorm-stubs` as you can see.

PHPStan's dependencies work with PHP 7.2+ out of the box.

`jetbrains/phpstorm-stubs` stubs need to be parsed with PHP-Parser configured for PHP 8+. I vaguely remember Rector already had this problem once, and fixed it the same way PHPStan works with the tubs.

**Comment by samsonasik** [comment]
@ondrejmirtes thank you, we used configured php8parser but somehow it still error when called on php 7.4

https://github.com/rectorphp/rector/blob/ca844057bcb6c096d4380a4a1624914a90b7de4b/config/phpstan/parser.neon#L20

@TomasVotruba the issue is probably because we have multiple versions of parser:

https://github.com/rectorphp/rector/blob/ca844057bcb6c096d4380a4a1624914a90b7de4b/src/PhpParser/Parser/SimplePhpParser.php#L12-L26C5

https://github.com/rectorphp/rector/blob/ca844057bcb6c096d4380a4a1624914a90b7de4b/src/PhpParser/Parser/RectorParser.php#L10-L22

https://github.com/rectorphp/rector/blob/ca844057bcb6c096d4380a4a1624914a90b7de4b/packages/PhpDocParser/PhpParser/SmartPhpParser.php#L13-L20
