### ISSUE TITLE
be careful with deleting tags: 0.17.14 

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [rectorphp/rector#8146]
not really a bug report, but more an issue to be aware of.
you had a shortlived 0.17.14  which was pulled by our systems while it was beeing up and put into composer.lock

 we usually bump dependencies to avoid running with outdated stuff, so we ended up with a  `rector/rector ^0.17.14` constraint in our composer.json.

after you released 0.18.0 and deleted 0.17.14 that constraint would not allow to upgrade to 0.18.0 but also prevented a downgrade to 0.17.13 and gives us this error:

```
$composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rector/rector ^0.17.14, found rector/rector[dev-main, v0.1.0, ..., 0.18.0] but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one present in the lock file (rector/rector[0.17.14]).
```

and since i did not know yet, that you deleted that tag, that was rather confusing to resolve :)
better option would be to create a new tag `0.17.15` for the same commit as `0.17.13` was and leave `0.17.14` were it is.

but anyways, thank you for all your efforts with rector :heart:

**Comment by TomasVotruba** [comment]
I'm aware of this mistake and had to make descision after incorrectly tagging patch version, where should have been a minor one because of https://github.com/rectorphp/rector-src/pull/4698.
It was a 3 hours gap so I had to decide if break the BC for few early adopters or for the rest of them.

Thanks for pointing it out though :+1:

**Comment by verfriemelt-dot-org** [comment]
yeah, no worries, know i know a new thing to check for when having such weird issues. i think the update + bump is not too common, so it was most likely the right call. 

thanks you
