### ISSUE TITLE
Incorrect behavior of RemoveDeadInstanceOfRector

### ISSUE THREAD

**Issue by bloep** [rectorphp/rector#8147]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/fbf6cb49-df93-4675-a172-75f4f2f73ef6

```php
<?php

final class DemoFile
{
    private function complementArticleData(Iterator $articles): void
    {
        $result = [
            'artikel' => $articles,
            'farben' => null,
            'artikel_ids' => [],
        ];

        // collect article ids
        foreach ($result['artikel'] as $article) {
            $result['artikel_ids'][] = 1;
        }

        if ($result['artikel_ids'] !== []) {
            $result['farben'] = new stdClass();
        }

        // $result['farben'] might be also null
        if ($result['farben'] instanceof stdClass) {
            echo '123';
        }
    }
}
```

### Responsible rules

* `RemoveDeadInstanceOfRector`

## Expected Behavior

I think `RemoveDeadInstanceOfRector` shouldn't modify this code and skip it.

**Comment by samsonasik** [comment]
@bloep my current investigation, it probably a PHPStan bug on detecting type, on array, it skipped properly, see:

https://getrector.com/demo/4a02fd64-ffaf-4142-9746-6de2899c9f79

I think the proper way is currently add isset() check instead, see:

https://getrector.com/demo/9631117d-aa73-488e-a68a-8d5e12362b89

that the instanceof will always correct.

**Comment by samsonasik** [comment]
@bloep I created bug report issue on PHPStan https://github.com/phpstan/phpstan/issues/9784 on Iterator usage

**Comment by samsonasik** [comment]
It just resolved in PHPStan side https://github.com/phpstan/phpstan-src/commit/853a1e693eb18b9c1eef87f264c90b4d446db710

**Comment by bloep** [comment]
@samsonasik thanks for your speedy analysis and solution ❤️
