### ISSUE TITLE
Crash and Incorrect behavior of AddParamBasedOnParentClassMethodRector

### ISSUE THREAD

**Issue by klimslim** [rectorphp/rector#8149]
# Bug Report

Rector crashes with PHPStan exception

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e913f712-f893-4504-a26d-1e73c3892e0d

```php
<?php

class Foo{
    public function baz($default = []) {
        return implode('', $default);
    }
    
    public function boo($default = '') {
        return $default;
    }
}

class Bar extends Foo {
    public function baz() {
        echo parent::baz();
    }
    
    public function boo() {
        echo parent::boo();
    }
}
```

### Responsible rules

* `AddParamBasedOnParentClassMethodRector`

## Expected Behavior
It should not crash and should produce the following diff:
```diff
@@ -11,11 +11,11 @@
 }
 
 class Bar extends Foo {
-    public function baz() {
+    public function baz($default = []) {
         echo parent::baz();
     }
     
-    public function boo() {
+    public function boo($default = '') {
         echo parent::boo();
     }
 }
```

**Comment by klimslim** [comment]
I tried to debug it, but have no idea why '' and [] are treated as identifiers.

**Comment by klimslim** [comment]
Not sure if I need to create another bug, this seems to be related too:
See https://getrector.com/demo/1f6a4b0d-d977-44ca-8530-257bdbb71ccb

```php
<?php

class Foo{
    public function baz($default = array()) {
        return implode($default);
    }
}

class Bar extends Foo {
    public function baz() {
        return parent::baz();
    }
}
```

### Responsible rules

* `LongArrayToShortArrayRector`

* `SensitiveConstantNameRector`

* `AddParamBasedOnParentClassMethodRector`

## Expected Behavior


```diff
@@ -1,13 +1,13 @@
 <?php
 
 class Foo{
-    public function baz($default = array()) {
+    public function baz($default = []) {
         return implode($default);
     }
 }
 
 class Bar extends Foo {
-    public function baz() {
+    public function baz($default = []) {
         return parent::baz();
     }
 }
```
`SensitiveConstantNameRector` should not be invoked.

**Comment by samsonasik** [comment]
@klimslim let's focus on fixing crash first at PR:

- https://github.com/rectorphp/rector-src/pull/4833

For multiple rules usage invalid change, that's need separate issue :)
