### ISSUE TITLE
0.17.14

### ISSUE THREAD

**Issue by ro0NL** [rectorphp/rector#8152]
please dont remove tags :)

![image](https://github.com/rectorphp/rector/assets/1047696/6bed2011-3e2c-4f4a-a5aa-d8deac9f1d47)

it does more harm than good, comared to a new reversing tag

**Comment by TomasVotruba** [comment]
Noted :+1:  

It was less of 2 evils :) 
https://github.com/rectorphp/rector/issues/8146

**Comment by ro0NL** [comment]
@TomasVotruba sorry i didnt search :angel: 

thanks for noting :heart:
