### ISSUE TITLE
Incorrect behavior of EventDispatcherParentConstructRector

### ISSUE THREAD

**Issue by ossinkine** [rectorphp/rector#8159]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/1642ffab-ee1c-413b-9646-6c28b73fd198

```php
<?php

use Symfony\Component\EventDispatcher\EventDispatcherInterface;

final class SomeEventDispatcher implements EventDispatcherInterface
{
    public function __construct()
    {
        $value = 1000;
    }
}
```

### Responsible rules

* `EventDispatcherParentConstructRector`

## Expected Behavior

Looks like the rule should add parent constuctor call only on extending base event dispatcher but not on implementing interface.

**Comment by samsonasik** [comment]
@ossinkine could you try provide a patch for it, you can do the following steps:

- add failing fixture add

https://github.com/rectorphp/rector-symfony/tree/main/rules-tests/Symfony43/Rector/ClassMethod/EventDispatcherParentConstructRector/Fixture

- provide a patch, change `Symfony\Contracts\EventDispatcher\EventDispatcherInterface` to `Symfony\Component\EventDispatcher\EventDispatcher`

at 

https://github.com/rectorphp/rector-symfony/blob/bf21591f4d73aabdc8c6c39f73effd1d5ff8b076/rules/Symfony43/Rector/ClassMethod/EventDispatcherParentConstructRector.php#L81

**Comment by ossinkine** [comment]
@samsonasik I've created the fix, but your solution is not good because there are several implementations of `Symfony\Contracts\EventDispatcher\EventDispatcherInterface`, not only `Symfony\Component\EventDispatcher\EventDispatcher`, for example `Symfony\Component\EventDispatcher\ImmutableEventDispatcher`, so I've added a check for parent class
