### ISSUE TITLE
Incorrect behavior of ReturnTypeFromStrictNewArrayRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8161]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/9367ce33-2e2b-4041-bcb0-5a796586e723

```php
<?php

final class DemoFile
{
    public function angebotsBoxerList(array $angzList)
    {
        $boxes = [];
        foreach ($angzList as $angz2) {
            $boxes[$angz2->angzid] = $this->angebotsBoxer($angz2);
        }

        return $boxes;
    }
    
    /**
     * @return Angebotsboxer|null
     */
    public function angebotsBoxer(clxAngz $angz)
    {
    }
}
```

### Responsible rules

* `ReturnTypeFromStrictNewArrayRector`

## Expected Behavior

I think the inferred phpdoc should be `* @return array<Angebotsboxer|null>` instead of `* @return \Angebotsboxer[]|null[]`

**Comment by samsonasik** [comment]
It seems both are equal, so it mostly a preference, see https://phpstan.org/r/459a507f-df7f-41db-9f39-4b3fae29faea

**Comment by staabm** [comment]
I was not sure, how to read `null[]`. it feels unnatural.

maybe its even someting which can/could be fixed by ECS then instead

**Comment by TomasVotruba** [comment]
Indeed, those are the same as @samsonasik 

I don't think it's worth it the time to change those details, but if it seems worth it to you, feel free to propose a PR to adjust those union arrays :+1:
