### ISSUE TITLE
Hard time to get a unit test work

### ISSUE THREAD

**Issue by wernerkrauss** [rectorphp/rector#8162]
# Question
Hi team, sorry for spaming in issues...

today I started in https://github.com/wernerkrauss/silverstripe-rector/ with the first SetLists and wanted to test that configuration.

It works in a live project, but I cannot get the test green. I added stubs for this test, but somehow rector/phpstan doesn't recognise that.

Failing test: Netwerkstatt\SilverstripeRector\Tests\Set\CodeStyle\CodeStyleTest

```
--- Expected
+++ Actual
     {
-        $foo = $this->getOwner()->foo;
+        $foo = $this->owner->foo;
     }
 }
```

Any idea what I missed? Are stubs cached? Do I have to configure them somewhere?

Thanks for your support!

**Comment by samsonasik** [comment]
Hi @wernerkrauss,

The test error because of `SilverStripe\ORM\DataExtension` is missing in the config.

I created PR to your repo :)

- https://github.com/wernerkrauss/silverstripe-rector/pull/8

**Comment by wernerkrauss** [comment]
Thanks for your help. FYI updating rector from 0.18.0 to 0.18.1 fixed this for me.
