### ISSUE TITLE
Incorrect behavior of SensitiveConstantNameRector

### ISSUE THREAD

**Issue by alzozov** [rectorphp/rector#8164]
**I am migrating from the old php code where some string array indexes were used without quotes as in example bellow. I expect it should add '' or "" and instead it thinks it is a constant. 
Is there a way to do it with current rules or should I create my rule for it?**  

# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/4c7c62e2-e042-43ad-924c-eda2e08de6b5

```php
<?php

$n_razdel = $current_sub['Subdivision_Name'];
echo $current_sub[Subdivision_Name];
```

### Responsible rules

* `SensitiveConstantNameRector`

## Expected Behavior

echo $current_sub['Subdivision_Name'];

**Comment by samsonasik** [comment]
I think since constant may be included via "require" somewhere, it just guessing, so skip the rule seems better.

**Comment by alzozov** [comment]
> I think since constant may be included via "require" somewhere, it just guessing, so skip the rule seems better.

if I skip the rule then nothing changes and I have a code that does not work on php8+

**Comment by samsonasik** [comment]
I think phpstan is your friend for that, you can analyze the code to carefully verify the change

https://phpstan.org/r/e72b6682-0f08-4701-84e3-843eda2155a9

**Comment by alzozov** [comment]
Thanks...
The problem is I have a tone of code like that (it is hundreds of files of legacy code).
and they all have things like: 

- $current_sub[Subdivision_Name];
- $data[Tag_Text]
- if ($parent_sub_tree[1][Subdivision_ID]==808)
- $data[Country_Name]
- $data[City]

also a lot of them in the listQuery function 

and also all this City, Subdivision_ID, Tag_Text are not constants (all this worked in bellow versions but not  in php8+)

Example: 

```php

if ($tag && $sub==62) 
{
   $title_rus = listQuery("select Tag_Text from Tags_Data where Tag_ID in (".$tag.")", "\$data[Tag_Text]",", ");
   if ($title_rus!="") $title_rus=$title_rus." | Иудаизм и евреи на Толдот.ру";
  //"Тема — ".$title_rus;
}
if (!$message && !($tag && $sub==62))//описания заголовков разделов
{
 $title_rus = $current_sub[SectionTitle];

 if ($sub==1861) //Темы
 {
   $title_rus="Еврейские темы | Энциклопедия иудаизма онлайн на Толдот.ру";
 }
 
 //Магазин
 if ($sub==808) $title_rus="Магазин еврейской книги и атрибутики иудаизма";
 $n_razdel = $current_sub[Subdivision_Name];
 if ($parent_sub_tree[1][Subdivision_ID]==808) $title_rus="".strtoupper($n_razdel)." — купить онлайн на Толдот.ру | Магазин еврейской книги и атрибутики иудаизма";
 
 //Еврейские имена
 if ($sub == 429) $title_rus = $current_sub['SectionTitle'];
 if ($sub == 429 && ($razdel || $gender) ) $title_rus=($gender==2 ? "Женские" : "Мужские")." имена на букву «".(!$razdel ? "А" : $razdel)."» — еврейские имена | Иудаизм и евреи на Толдот.ру";
 

 // 
 if ($sub==1636 && $cemetery>0) $title_rus=listQuery("Select s.Country_Name,c.City,c.Cemetery_name from Message134 as c 
inner join Classificator_Country as s on s.Country_ID=c.Country where c.Message_ID=$cemetery","\$data[Country_Name], \$data[City], \$data[Cemetery_name] — еврейские кладбища | Иудаизм и евреи на Toldot.com");
 if ($author) 
 {
 if ($sub==357) $title_rus = listQuery("select concat_ws(' ',Prefix_rus,Fname_rus,Lname_rus,Suffix_rus) as name
 from Message66 where Message_ID=".(int)$author,"\$data[name] — слушать лекции раввина онлайн | Еврейские аудиоуроки на Толдот.ру");
 //вопросы раввину

```

**Comment by samsonasik** [comment]
If the usage is always on array, I think regex find and replace in IDE is better solution.

**Comment by alzozov** [comment]
Makes sense, thank you for your answer

**Comment by samsonasik** [comment]
thank you for understanding, I am closing it then ;)
