### ISSUE TITLE
importNames: keep qualified names

### ISSUE THREAD

**Issue by gharlan** [rectorphp/rector#8165]
# Feature Request

I want to use the `importNames` config, but only for fully qualified names. Qualified names should not be modified.
 
https://getrector.com/demo/a3e7f8cd-8595-4d28-9a25-0d3b918a6aee

The given code should not be changed.

**Comment by samsonasik** [comment]
`importNames()` is super complex process, detecting half part of uses in namespace will cause conflict check harder, so that import is expected.
