### ISSUE TITLE
[RandomFunctionRector] Do not replace mt_rand with random_int if mt_srand is used

### ISSUE THREAD

**Issue by buffcode** [rectorphp/rector#8166]
# Feature Request

Do not replace `mt_rand` with `random_int`  if `mt_srand` is used.

`random_int` does not support changing the seed value and returns cryptographically secure integers.
`mt_rand` on the other hand supports seed numbers, in order to create pseudo random number (of course not cryptographically secure).

Later case is especially useful if the application needs to create repeatable pseudo-random values based on a given seed.

Eg. in our use case we want to fake customer data and the seed is the customer number. Thus every customer gets his own pseudo-random data, but on consecutive runs, each customer get the same data again.
 
## Diff 

```diff
  mt_srand($seed = 1234);
- $val = mt_rand(20000, 29999):
+ $val = random_int(20000, 29999);
```

This modifies the result of the code.

## Workaround

Ignore the rector for the whole file (https://getrector.com/documentation/ignoring-rules-or-paths)

**Comment by samsonasik** [comment]
Hi, the rule need to be refactored with `StmtsAwareInterface` to accomodate that, similar to what `ArrayKeyFirstLastRector` do, that will allow to check prev or next stmt with function defined, see 

https://github.com/rectorphp/rector-src/blob/7b7b4fb61bc2a7088823e7cfabf8a29b4fec516c/rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php#L88

then check:

https://github.com/rectorphp/rector-src/blob/7b7b4fb61bc2a7088823e7cfabf8a29b4fec516c/rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php#L186-L204

on your use case, it should be simpler as the `mt_srand()` is in previous definition, so no need to check next loop of stmts, just check if `mt_srand()` is on the previous stmt.

could you try provide a feature PR? thank you.

**Comment by TomasVotruba** [comment]
Thanks for feedback :+1: 


I explore the origins of the `mt_rand()` and it was only copied from php-cs-fixer. I found no related PHP 7.0 deprecation.

Let's remove this function: https://github.com/rectorphp/rector-src/pull/5315
