### ISSUE TITLE
Circular reference when executing the command

### ISSUE THREAD

**Issue by geoffroyp** [rectorphp/rector#8167]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.8          |

as soon as I run rector by executing `vendor/bin/rector process src --dry-run`, I get the following error:

```
PHP Fatal error:  Uncaught _PHPStan_582a9cb8b\Nette\InvalidStateException: Circular reference detected for services: betterReflectionSourceLocator, 0278, 0272, 080, 079, fileFinderScan, fileExcluderScan, 0299, originalBetterReflectionReflector. in phar:///data/webs/apiroot/api/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Container.php:156
```

(I've removed the stack strace to avoir making a huge wall of text, but I can add it if needed)

I may add that I've cleared my cache and dumped the autoload, butthe result is still the same

## Minimal PHP Code Causing Issue

nothing to report here. But I should probably mention my version of PHP is 8.2.3

## Expected Behaviour

it should run :)

**Comment by samsonasik** [comment]
Rector already version 0.18.1, you're using 0.14.8, you probably need to update to latest version. If issue persist, please provide reproducible test / repo.
