### ISSUE TITLE
Incorrect behavior of AddParamTypeFromPropertyTypeRector

### ISSUE THREAD

**Issue by Celebrate-Reinhard** [rectorphp/rector#8168]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e8b2a468-764d-4031-9dc3-4f5bf587aefd

```php
<?php

final class DemoFile
{
    private array $elements;

    public function __construct(...$elements)
    {
        $this->elements = $elements;
    }
}
```

### Responsible rules

* `AddParamTypeFromPropertyTypeRector`

## Expected Behavior

Rector adds `array` as typehint which is not correct for splat/unpack operator. 

```php
-    public function __construct(...$elements)
+    public function __construct(array ...$elements)
```

It _would_ mean that each incoming item is an array. But it's not necessarily. It can be any type which is stored _inside_ of an array.

If the type would be `Foo` instead of `array`, Rector would not change anything (which is correct):

```php
final class DemoFile
{
    protected Foo $elements;

    public function __construct(...$elements)
    {
        $this->elements = $elements;
    }
}
```

**Comment by samsonasik** [comment]
Hi @Celebrate-Reinhard  , could you try provide a patch? Here is the step:

- Add failing fixture at 

https://github.com/rectorphp/rector-src/tree/main/rules-tests/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector/Fixture

- Provide a patch, it should be add `$param->variadic` check, something like:

```php
if ($param->variadic) {
    continue;
}
```

after:

https://github.com/rectorphp/rector-src/blob/5f52c69ae04c708be50552b165104b4a919a3ff0/rules/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector.php#L93-L96
