### ISSUE TITLE
Remove pass by reference for objects

### ISSUE THREAD

**Issue by splitbrain** [rectorphp/rector#8169]
# Feature Request

Objects are always passed by reference in PHP however some legacy code is still adding an `&` in the function declaration.

Would be great to have rule to fix this.
 
## Diff 

```diff
-function(SomeClass &$obj)
+function(SomeClass $obj)
```

**Comment by TomasVotruba** [comment]
Hi, I think this rule would fit code quality set :+1: 

Would you like to contribute it?

**Comment by TomasVotruba** [comment]
Closing as accepted to avoid keep issue tracker focus on unclear issues that needs our attention.
Feel free to send PR with it :+1:
