### ISSUE TITLE
try-online bug

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8170]
# Bug Report

code example is reported as "invalid" in the only try.

## Minimal PHP Code Causing Issue

add code into the online try

```
<?php

class BaseClass {
    public function find_object($conditions): ?self
    {
    }
}


final class DemoFile extends BaseClass
{
    public function findByCode($code):
    {
        if (false === $code) {
            return null;
        }
        return $this->find_object($code);
    }
}

```

and config is

```
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;
use Rector\TypeDeclaration\Rector\ClassMethod\ReturnUnionTypeRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rule(ReturnUnionTypeRector::class);
};

```

## Expected Behaviour

rector processes example and reports diff

## actual

![grafik](https://github.com/rectorphp/rector/assets/120441/5e974ffb-adde-4d26-ac04-f933ec5fb153)

**Comment by staabm** [comment]
hmm ok.. I see my bug now.

the online try should point me to my linting error instead of throwing all my input away :)

**Comment by samsonasik** [comment]
It syntax error https://3v4l.org/KMCZT

**Comment by TomasVotruba** [comment]
@staabm Indeed it's unclear what is wrong. The error message could be improved here https://github.com/rectorphp/getrector-com/blob/30b350850a55e59dcd6fdf0918a14bfc1b9ede91/app/Rules/ValidPhpSyntaxRule.php#L25

**Comment by staabm** [comment]
It would also be great that my input whould be persisted instead of beeing dropped

**Comment by samsonasik** [comment]
@staabm persist existing input will make too many invalid files content saved in server

Except, we are going to save in memory and not generate new URI with read "Flash Session" usage that read latest input.

**Comment by TomasVotruba** [comment]
Closing as this is not about Rector, but its website. Moved to https://github.com/rectorphp/getrector-com/pull/1637
