### ISSUE TITLE
Incorrect behavior of CountOnNullRector

### ISSUE THREAD

**Issue by wouter90** [rectorphp/rector#8171]
# Bug Report
CountOnNullRector is applied on if-statement that explicitly check on NULL before count function is executed.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.18.1      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/111ed7e6-9659-4792-ba2e-a03cad8fd75e

```php
<?php

final class Foo
{
    /**
     * @var array|null
     */
    public $hourTypePrices = [];
}

final class DemoFile
{
    public function run()
    {
        $foo = new Foo();
        if (null !== $foo->hourTypePrices && 0 !== \count($foo->hourTypePrices)) {
            echo 'foo';
        } else {
            echo 'bar';
        }
    }
}
```

### Responsible rules

* `CountOnNullRector`

## Expected Behavior

I expect no change here. Now inside count() the value is casted to array.

**Comment by wouter90** [comment]
The reason I created this report is because this changed when upgrading from 0.17.3 to 0.18.1. I agree we should type the property but in our code we need to have some changes first before we can do that.

**Comment by samsonasik** [comment]
Yes, we are moving from rely on docbock to native type, there is probably native type check bug on it. When you upgraded to php 7.4+, you can enable `RecastingRemovalRector`

**Comment by samsonasik** [comment]
I am closing it as `CountOnNullRector` is now deprecated.

**Comment by mbrodala** [comment]
For reference: https://github.com/rectorphp/rector-src/commit/3eb8e7d7a52ed8d45ca685e570fbfa0fd14e9be1#diff-4e67b3812a474a7a969b9551d8bfa78c34512c53bc1f367cadafb774c97f7816R59
