### ISSUE TITLE
Incorrect behavior of TypedPropertyFromStrictConstructorRector: phpdoc types instead of native types added

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8173]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/aea5e2a8-9498-4d45-92ac-10ed24b7c15c

```php
<?php

namespace entrypageparser\persistence;

use clxAngz;
use clxArtikel;
use clxTarif;

final class Angz3BoxerTarifArtikelTarif
{
    public $angzid;

    public $preis;

    public $providerPreis;

    public $handy;

    public $tarif;

    public $zusatzTarif;

    public function __construct(clxAngz $angebotszeile, clxArtikel $handy, clxTarif $tarif, clxTarif $zusatzTarif)
    {
        $this->angzid = $angebotszeile->angzid;

        $this->preis = $angebotszeile->eadavk;

        $price = $angebotszeile->providerpreis;
        $this->providerPreis = $price;

        $this->handy = $handy;

        $this->tarif = $tarif;

        $this->zusatzTarif = $zusatzTarif;
    }
}
```

### Responsible rules

* `TypedPropertyFromStrictConstructorRector`

## Expected Behavior

I wonder why the rule adds phpdoc types instead of native types?

**Comment by staabm** [comment]
ahh, I should make the class `@immutable` and use `TypedPropertyFromStrictConstructorReadonlyClassRector` instead

https://getrector.com/demo/1ff478fa-7008-4577-a5c2-cbf5a3488fa0

**Comment by staabm** [comment]
ok, looking at it again, I think there is room for improvement.

the result of running rector with the 2 rules depends on the order in which they are passed into the rector config.

see

https://getrector.com/demo/648e4e6e-ae65-4815-815c-f07aab1c9f08
vs.
https://getrector.com/demo/2cc959e5-9277-45c8-b47f-c635778fdc37

since `TypedPropertyFromStrictConstructorReadonlyClassRector` does not touch a property which has already a phpdoc type (which might be added by `TypedPropertyFromStrictConstructorRector`), I think we should prioritize `TypedPropertyFromStrictConstructorReadonlyClassRector` .. 

is there a way to make sure no matter in which order these 2 rules are defined `TypedPropertyFromStrictConstructorReadonlyClassRector` will be run before `TypedPropertyFromStrictConstructorRector`?

alternatively we might need to fix `TypedPropertyFromStrictConstructorReadonlyClassRector`  that it does not skip properties with a phpdoc type applied

**Comment by TomasVotruba** [comment]
Ideally these should be independent and not handle each other's work.
