### ISSUE TITLE
memory cycles

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8175]
Today I had a look at https://github.com/rectorphp/rector-src/commit/6d7cd13194264e8792a643d4ce88928f7ccc874b using https://github.com/arnaud-lb/php-memory-profiler

its a php extension which dumps the memory of a php process and using cachegrind we can look into this data:
(disclaimer: I am using this tool for the very first time.. my conclusions might not be accurate)

<img width="620" alt="grafik" src="https://github.com/rectorphp/rector/assets/120441/57822694-3bd8-43cd-8e5e-a4d388871243">

I find especially interessting the "cycle" nodes, which in my thinking represents memory which has reference cycles and therefore are hard to free for the garbage collector (or even un-collectable).

<img width="1173" alt="grafik" src="https://github.com/rectorphp/rector/assets/120441/27620ac6-4cac-4929-bb07-d0fec75ba4b4">

I am in the process of understanding what I see, but want to leave this things here for now, as inspiration for others.

**Comment by staabm** [comment]
`FileProcessor->parseFileInfoToLocalCache()` looks like a memory intensive node

<img width="1238" alt="grafik" src="https://github.com/rectorphp/rector/assets/120441/b9d4f854-4740-488d-aaa8-af34549c30cf">

**Comment by TomasVotruba** [comment]
Hi, the `parseFileInfoToLocalCache()` is heavy because it parses each PHP file to stmts.
Any improvement is welcomed, but I think that would propage to nikic/php-parser itself.

Feel free to improve any bottleneck you find :+1:

**Comment by staabm** [comment]
sure, I will just keep posting here with my findings.

----

after some fiddling I got a blackfire profile of a rector worker... I never had such profile before, as I was always running non-parallel because tooling did not easily allow otherwise.

memory consumption is clearly dominated by nette/pcre

<img width="1116" alt="grafik" src="https://github.com/rectorphp/rector/assets/120441/0f38a5a7-3a98-42d4-a9b7-bfd6a5ba1280">


here the memory focused call graph of the callers

<img width="499" alt="grafik" src="https://github.com/rectorphp/rector/assets/120441/32369976-2258-4ec1-952e-b34f2d0b21f3">

**Comment by TomasVotruba** [comment]
Not sure if that helps, but `\Rector\Core\Util\StringUtils::isMatch()` results could be cached :)
