### ISSUE TITLE
Incorrect behavior of TypedPropertyFromAssignsRector

### ISSUE THREAD

**Issue by franmomu** [rectorphp/rector#8177]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e9ab79bf-29b5-42a5-9db9-611cc7e671d3

```php
<?php

use Reader;
use OtherReader;

final class DemoFile
{
    /** @var Reader|OtherReader|null */
    private $reader;
    
    /** @return Reader|OtherReader|null */
    public function getReader()
    {
        return $this->$reader;
    }
    
    public function test(): void
    {
        $this->reader = $this->getDefaultReader();
    }
    
    public function getDefaultReader(): Reader
    {
        return new Reader();
    }
    
    /** @param Reader|OtherReader|null $reader */
    public function setReader($reader)
    {
        $this->reader = $reader;
    }
}
```

### Responsible rules

* `TypedPropertyFromAssignsRector`

## Expected Behavior

Rector should not add the `?Reader` type since it could be `Reader|OtherReader|null`.

**Comment by samsonasik** [comment]
That's expected, the rule doesn't read docblock, instead, it read the native type assigned.

You can change it to pass native union type instead

**Comment by franmomu** [comment]
Ok, thanks for clarifying.

> You can change it to pass native union type instead

Not really since we still need to support PHP 7.4, I'll skip the rule then.

**Comment by TomasVotruba** [comment]
@franmomu Correct approach is to have `ReaderInterface` that includes the both and strict type agains it in native PHP:

```php
final class DemoFile
{
    /** @var Reader|OtherReader|null */
    private ?RectrInterface $reader = null;
    
    /** @return Reader|OtherReader|null */
    public function getReader(): ?RectrInterface
    {
        return $this->$reader;
    }
    
    public function getDefaultReader(): Reader
    {
        return new Reader();
    }
    
    /** @param Reader|OtherReader|null $reader */
    public function setReader(?RectrInterface $reader)
    {
        $this->reader = $reader;
    }
}
```

This also enables dozen of Rector/PHPStan checks :+1:

**Comment by franmomu** [comment]
yeah, if there was a common interface would be easier, but it is not 😞 (third party library and not worth it create a new one since one of them is going to be unused)

**Comment by samsonasik** [comment]
I see, it seems mixing native + docblock assign should be skipped instead, not sure if it will be easy to resolve, but I will re-open :)
