### ISSUE TITLE
Incorrect behavior of RemoveAlwaysElseRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8178]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/2802bd41-f346-47c5-ae6f-256e83b3c471

```php
<?php

final class DemoFile
{
    public function run($a)
    {
        if ($a == 1) {
            return 1;
        } elseif ($a == 2) {
            return 2;
        } elseif ($a == 3) {
            return 3;
        } elseif ($a == 4) {
            return 4;
        } elseif ($a == 5) {
            return 5;
        }
        
        return 'more';
    }
}
```

### Responsible rules

* `RemoveAlwaysElseRector`

## Expected Behavior

I think rector should rewrite all the else-if cases in a single run.

atm I have to run rector 4 times to get this if-elseif structure be rewritten into 

```php
<?php

final class DemoFile
{
    public function run($a)
    {
        if ($a == 1) {
            return 1;
        }
        if ($a == 2) {
            return 2;
        } 
        if ($a == 3) {
            return 3;
        }
        if ($a == 4) {
            return 4;
        } 
        if ($a == 5) {
            return 5;
        }
        
        return 'more';
    }
}
```

**Comment by samsonasik** [comment]
I think it can be marked as feature
