### ISSUE TITLE
CountOnNullRector creates new problem

### ISSUE THREAD

**Issue by Kinany52** [rectorphp/rector#8180]
# Bug Report

Dear Rector Team,

| Subject : CountOnNullRector | Details : CountOnNullRector creates new problem                                                        |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector version 0.18.1 (latest as of now)            |

Tested in both PHP version 7.4.15 and PHP version 8.1.21 and Rector version 0.18.1 (latest as of now) and obtained the same output.
## Minimal PHP Code Causing Issue
//array_shift() is executed twice in the CountOnNullRector's modification.
$resultColumns = is_countable($result_vector[array_shift($r)]) ? count($result_vector[array_shift($r)]) : 0;

https://getrector.com/demo/eb00e2e1-ed77-4b72-b63f-23950f49a39d

## Expected Behaviour
Please check URL for the reproduced issue or see the attachment for a screenshot of the reporduction.

$a=array_shift($r);
$resultColumns = is_countable($result_vector[$a]) ? count($result_vector[$a]) : 0;

<img width="515" alt="RectorCap" src="https://github.com/rectorphp/rector/assets/79725439/1da3fea4-7915-4239-8a05-e12d0e1a1123">

Thank you in advance for fixing the issue :)

Best Regards,
Sarmad Al Kinany

**Comment by Kinany52** [comment]
Hi @samsonasik 

Thank you for pointing this out. 

The issue is now reproduced accurately in this URL:
https://getrector.com/demo/5439a172-0472-4cec-8a5e-ffefdedb7c4c

Thank you.

Best,
Sarmad

**Comment by samsonasik** [comment]
Again, Rector using PHPStan to detect type, make a tweak inside `count()` argument will cause another tweak, better to fix the PHPStan expectation first, then you can get it properly skipped :), or you can just skip the rule 

https://getrector.com/documentation/ignoring-rules-or-paths
