### ISSUE TITLE
return type not inferred

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8181]
# Feature Request

https://getrector.com/demo/905228f9-7d32-4aa3-9895-7071b3d6ff83

I wonder why rector is not able to infer the `string` return type

**Comment by samsonasik** [comment]
PHPStan seems detect variable `$style` in last rerun as error type, see https://phpstan.org/r/ea1c7a84-2be8-44bf-913d-f1b8e0db64dd

**Comment by samsonasik** [comment]
@staabm I created PHPStan issue at https://github.com/phpstan/phpstan/issues/9855

**Comment by staabm** [comment]
Thx. Seems its a autoloading issue then. I need to check class loading rules. 

But I still got an idea from this conversation. Maybe we can have a rector which replaces the variable return with a constant value return when phpstan is able to narrow the variable type to a single constant value?
