### ISSUE TITLE
Incorrect property assignment using ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by pkly** [rectorphp/rector#8184]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.1           |

Parameters are being changed even though their final name is different from the parameter in the constructor, causing breaks.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/50a754f6-5d5c-4535-9f01-814384177ffe

## Expected Behaviour

Parameter should be skipped, it should be as simple as checking if the argument name and parameter both match type and name.

I realized something broke because I tried applying it in our project (Symfony) with the following setup:

```php
private string $fsSubDirectory;

public function __construct(
    string $FILE_SUBDIRECTORY // injected via container
) {
    $this->fsSubDirectory = $FILE_SUBDIRECTORY;
}
```

This in turn broke container generation as it was expected that the parameter `$FILE_SUBDIRECTORY` exists within the constructor parameters and it was changed to be `$fsSubDirectory`

**Comment by samsonasik** [comment]
We have these reported for Framework specific needs in the past, I think you can just skip the rule, as it utilize for common use case, parameter from framework specific is rely on other file: config yaml which indirectly related to the file.

https://getrector.com/documentation/ignoring-rules-or-paths
