### ISSUE TITLE
ReturnTypeFromStrictNewArrayRector: missing array return type - part 2

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8185]
# Bug Report

similar to https://github.com/rectorphp/rector/issues/8183 I would expect rector to add a `array` return type in

https://getrector.com/demo/aed924b0-d4e6-4522-a0f2-d8a5034ca416

only difference is the added block

```
        if (count($offers) == 0) {
            return [];
        }
```

**Comment by staabm** [comment]
if we would widen the scope to 1 array return and n-constant returns, we could support the initial snippet and additionally things like https://getrector.com/demo/c74af6a5-bc6a-479d-8469-cb3a2e56dd5a

**Comment by samsonasik** [comment]
For union nullable, I think that can use https://getrector.com/demo/8154c1f5-8db4-4a8e-949a-b38b31042c9c

**Comment by staabm** [comment]
I don't mind which of the rules gets able to resolve my initial snippet :-) - getting support the mentioned cases would be awesome
