### ISSUE TITLE
Remove default numeric index keys on arrays

### ISSUE THREAD

**Issue by crazytonyi** [rectorphp/rector#8190]
# Feature Request

Given an array :

```
$example = [
  0 => 'alpha',
  1 => 'bravo',
  2 => 'charlie',
];
 ```
This could logically be re-written as : 

```
$example = [
  'alpha',
  'bravo',
  'charlie',
];
```
The two are equivalent but having no explicit index adds the benefit readability, potential logic errors based on ordering of items in an array, and having to re-number long array lists manually when inserting an item (in code) somewhere besides the top or bottom of that list.

Something to consider:

PHP's `var_export` forces an explicit numbering, like:

```
$exampleArray = ["alpha", "bravo", "charlie"];
var_export($exampleArray);

//output:

array (
  0 => 'alpha',
  1 => 'bravo',
  2 => 'charlie',
)
```

So it is reasonable to assume that there is code out there generated through this function that has number indexing out of connivence of not dealing with removing the imposed numbers, rather than through an intentional choice.

**Comment by TomasVotruba** [comment]
Sounds good to me :+1: 

Would you like to contribute it?

**Comment by samsonasik** [comment]
For note: removing key definition may need logic to ensure no "jump key" in the definition as that may depends on the usage, when user create" jump key" on purpose, which may still ok:

https://3v4l.org/VIRbc

**Comment by samsonasik** [comment]
I am closing it as

- it will require manual check after apply, eg: on many rows, define big array will have trouble on it.
- is the "jump key" a bug or on purpose, that will depends on what app is doing
- is there other key definition on purpose, eg: null or string, that also depends
- this mostly coding style that is "depends" on what developer style like
