### ISSUE TITLE
file not found errors

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8191]
# Bug Report

I somehow managed that rector immediately dies with a file-not-found error.

my guess is, that the laravel container sometime ago learnt about a config file.
this file was deleted after wards and the container since then didn't got invalidated.

it means rector immediately fails without me having a chance to recover from that state:

```
php ../rector-src/bin/rector.php --dry-run --no-progress-bar --no-diffs --clear-cache --debug -vvv

                                                                                                                        
 [ERROR] The file "/Users/staabm/workspace/rector-src/vendor/rector/rector-doctrine/config/config.php" does not exist.  
```

---

questions:
- how can I confirm my theses? could I somehow force rector to re-create a fresh container?
- should rector automatically refresh whatever cache is involved here in case of file-not-exist errors?
- how can I see from which point this file gets included?

**Comment by TomasVotruba** [comment]
What it the last working rector-src commit?

**Comment by TomasVotruba** [comment]
Ah, the composer extensions have cache, that is only triggered by `composer install`. Try that 🤞

**Comment by staabm** [comment]
it works again after a `composer update` - thanks.

not sure the error I have seen is something we need to fix and whether regular users can come into a similar situation

**Comment by TomasVotruba** [comment]
It's only limited to our rector extensions, that are included on build. Users are safe :)
