### ISSUE TITLE
Incorrect behavior of OrderByKeyToClassConstRector

### ISSUE THREAD

**Issue by bobvandevijver** [rectorphp/rector#8202]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.18.2, v0.18.3 & last dev-main      |
| Installed as   | composer dependency  |

Since v0.18.2 Rector tries to replace criteria strings with a constant (which is good), but it uses the internal `Criteria` class as replacement (which is bad).

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/3d878484-7d03-4017-ba76-94e48bb5369b

```php
<?php

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
class SomeEntity
{
    #[ORM\OrderBy(['name' => 'ASC'])]
    protected Collection $items;
}
```

### Responsible rules

* `OrderByKeyToClassConstRector`

## Expected Behavior

Rector should use the `Doctrine\Common\Collections\Criteria` class instead.

**Comment by samsonasik** [comment]
Could you try provide a patch? You can update the following code from `Criteria::class` to `"Doctrine\Common\Collections\Criteria"`

```diff
-Criteria::class,
+"Doctrine\Common\Collections\Criteria"
```

at https://github.com/rectorphp/rector-doctrine/blob/7f9e1329d06b0b90b36dd310b562a27cfd7b6aa6/rules/CodeQuality/Rector/Property/OrderByKeyToClassConstRector.php#L109

without quoted, it wil be prefixed on downgrade.

thank you.

**Comment by samsonasik** [comment]
Yes, except we want to exclude on scoper config in rector-src 

https://github.com/rectorphp/rector-src/blob/74df7741a7d0798888d2d9a3bf1020746b80ad8e/scoper.php#L34-L45

but directly there is enough :)
