### ISSUE TITLE
Incorrect behavior of ArrayKeyFirstLastRector

### ISSUE THREAD

**Issue by xknown** [rectorphp/rector#8203]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.18.3 dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/ed24d5ae-efa7-447a-884e-9e8b1ef04e84

```php
<?php

function a(array $arr) {
    reset($arr);
    while(true) {
        $key = key($arr);
        $value = current($arr);
        if ($key === null) {
            break;
        }
        echo $key . ": " . $value . PHP_EOL;
        next($arr);
    }
}
$arr = [1, 2, 3];
a($arr);
```

### Responsible rules

* `ArrayKeyFirstLastRector`

The proposed change creates an infinite loop.
## Expected Behavior

Rector should probably skip applying this rule if the `key()` function call is used in a loop context.

**Comment by samsonasik** [comment]
Hi, could you provide a patch? Here is the step:

- Add new fixture at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php73/Rector/FuncCall/ArrayKeyFirstLastRector/Fixture

- provide a patch, should be add "next" to be checked at 

https://github.com/rectorphp/rector-src/blob/935b2b47f5a8581117674f30ab1a725caa301494/rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php#L204

something like:

```php
if (! $this->isNames($subNode, ['prev', 'next'])) {
                        return false;
                    }
```
