### ISSUE TITLE
Incorrect StringToArrayArgumentProcessRector

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#8206]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main#2b177e80e2630c97653aa9d57ac87acbc1433524             |

## Minimal PHP Code Causing Issue

```diff
$router = self::getContainer()->get(RouterInterface::class);

-  $formTest = $router->generate('cluster_edit', [
+ $formTest = $router->generate(['cluster_edit'], [
```
Applied rules:
 * LongArrayToShortArrayRector
 * StringToArrayArgumentProcessRector (https://github.com/symfony/symfony/pull/27821/files)

## Expected Behaviour
Nothing wrong with that code. It shouldn't be changed. When adding `/** @var RouterInterface $router */` it works fine, so it doesn't recognize the right class when getting a service from the container in a test suite.

**Comment by samsonasik** [comment]
Could you try provide a patch? It should can be handle by skip instanceof `\PHPStan\Type\MixedType`.

Thank you.

**Comment by stephanvierkant** [comment]
I'll try, but I need some more explanation. Something should be changed in `\Rector\Symfony\Symfony42\Rector\New_\StringToArrayArgumentProcessRector`?

**Comment by samsonasik** [comment]
you can debug by eliminate collection of rules applied one by one and finally got rule that cause it.

**Comment by alexander-schranz** [comment]
It even does some strange things with `sprintf` currently:

```
-        $url = $uriSigner->sign(\sprintf('http://i3g.wip/static/%s/%s', $storageOptions['segment'], $storageOptions['fileName']));
+        $url = $uriSigner->sign(['http://i3g.wip/static/%s/%s']);
```

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.
