### ISSUE TITLE
New command to generate Rector rules

### ISSUE THREAD

**Issue by GeniJaho** [rectorphp/rector#8207]
# Feature Request

Hello team 👋 would you welcome a PR to add a new command to generate rules?

Currently, adding a new rule involves copying an existing rule, and their tests, and renaming the filenames, class names, etc.
It takes a lot of time and it is prone to errors.

I've made some progress on this new command and have a working solution that generates the rule, the test, config, and Fixture files. It supports different directories for storing the rules and tests, so Rector extensions and custom project rules can benefit from it.

Thank you.

**Comment by TomasVotruba** [comment]
Hi, you can use this package https://github.com/rectorphp/rector-generator, but it's at your own risk :)

It's made for us, so adding rules is easy in our specific directory structure though.

**Comment by GeniJaho** [comment]
In that case, is it ok to make a PR to that package to use it in other Rector extensions like https://github.com/driftingly/rector-laravel? All it needs is a bit more configuration for the directory of rules, tests, and main namespace (for example RectorLaravel).

I can just fork it but I think other packages might benefit a lot from this. And maybe a stable version of this generator package could have its place in the docs.

**Comment by TomasVotruba** [comment]
I'm a bit concerned about API complexity. I don't want to maintain this and make everything optional, as we had similar templates in the past.

If you can make it easy to use and maintain, we can give it a try though :) :+1:
