### ISSUE TITLE
Convert VOs / DTOs with getters to public readonly class / properties

### ISSUE THREAD

**Issue by JarJak** [rectorphp/rector#8209]
# Feature Request

Since PHP 8.1 (readonly properties) and 8.2 (readonly classes) we can finally get rid of getters, simplifying Value Object class code a lot, while keeping properties guarded from being mutable. I think it would be a good and common practice to transform exisiting VOs to use `public readonly`. And I believe Rector can help to do that :)

Of course Rector would apply this change only if there is no additional logic in getter.

Maybe it could be implemented as part of `ReadonlyPropertyRector` or `ReadonlyClassRector` or a separate one.
 
## Diff 

```diff
-class Foo
+readonly class Foo
{
-    public function __construct(private string $bar)
+    public function __construct(public string $bar)
     {
     }
-
-    public function getBar(): string
-    {
-        return $this->bar;
-    }
}

$foo = new Foo();
+$foo->bar;
-$foo->getBar();
```
 
## Related tickets

https://github.com/rectorphp/rector/issues/3095

**Comment by samsonasik** [comment]
Hi, I think you can create custom rule for that, since the change is introducing BC break for the class and its usage, and may only for specific project.

**Comment by JarJak** [comment]
@samsonasik what kind of BC break, that couldn't be handled by Rector, you see here?
