### ISSUE TITLE
MyCLabsMethodCallToEnumConstRector and SpatieEnumMethodCallToEnumConstRector are parsing dynamic classes incorrectly

### ISSUE THREAD

**Issue by duyphuongn** [rectorphp/rector#8210]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Using v0.18.3 but it happened starting from 0.18.2              |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/3adc23e4-4383-43ad-b6d2-423196e39568

```php
<?php
class BaseController extends ActiveController
{
    // They are intended to be inherited at child classes
    public object|string|null $controllerClass = null;
    public $modelClass;
    public object|string|null $modelClassSearch = null;

    public function actionDelete(): void
    {
        $model = $this->controllerClass::findModel($this->getParams());
        print_r($model);
    }
}
```

Configuration:

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_81,
    ]);
};
```

## Expected Behaviour

Rector should not complain about class not being found nor mistakenly change dynamic class calls to Enums.

## Actual Behavior

```
System error: "Class controllerClass was not found while trying to analyse it - discovering symbols is probably not configured properly."
```

## My investigation

- This didn't happen in Rector 0.18.1 or earlier version.
- This is not related to PHPStan.
- This comes from `MyCLabsMethodCallToEnumConstRector`, which was added to 0.18.2 in [pull request #4645](https://github.com/rectorphp/rector-src/pull/4645/files).
- If this rule is skipped, `SpatieEnumMethodCallToEnumConstRector` incorrectly converts dynamic class calls to Enums:

https://getrector.com/demo/e93de455-1513-43c8-8427-b79920033761

Configuration:

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_81,
    ]);
    $rectorConfig->skip([
        MyCLabsMethodCallToEnumConstRector::class
    ]);
};
```

Result:

```php
     public function actionDelete(): void
     {
-        $model = $this->controllerClass::findModel($this->getParams());
+        $model = \controllerClass::FINDMODEL;
         print_r($model);
     }
 }
```

- If these 2 rules are skipped, everything works fine again:

https://getrector.com/demo/9d549c52-63f2-4aff-9dfa-d9b5ea0d719a

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Php81\Rector\MethodCall\MyCLabsMethodCallToEnumConstRector;
use Rector\Php81\Rector\MethodCall\SpatieEnumMethodCallToEnumConstRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_81,
    ]);
    $rectorConfig->skip([
        MyCLabsMethodCallToEnumConstRector::class,
        SpatieEnumMethodCallToEnumConstRector::class,
    ]);
};
```

## Conclusion

I think, `MyCLabsMethodCallToEnumConstRector` and `SpatieEnumMethodCallToEnumConstRector` are not parsing dynamic classes correctly, which leads to this behavior.

**Comment by samsonasik** [comment]
You may need to configure the class to be loaded early, see documentation https://getrector.com/documentation/static-reflection-and-autoload
