### ISSUE TITLE
Incorrect behavior of PreparedValueToEarlyReturnRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8211]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/58b253de-d96e-4202-9d37-5ae48f9260b6

Rector is changing the code such that `$employees` is accessed before being assigned for the first time.

```php
<?php

final class DemoFile {
    public static function getEmployees() {
        $employees = mt_rand() ? [] : [1, 2, 3];
        if ($employees === []) {
            $departments = [];
            $employees = mt_rand() ? [] : [4, 5, 6];
        }
        if (mt_rand()) {
            $employees = [7, 8, 9];
        }
        return $employees;
    }
}
```

### Responsible rules

* `PreparedValueToEarlyReturnRector`

## Expected Behavior

The following would be an acceptable output, but anything has the same semantics is acceptable.

```
final class DemoFile {
    public static function getEmployees() {
        $employees = mt_rand() ? [] : [1, 2, 3];
        if ($employees === []) {
            $departments = [];
            $employees = mt_rand() ? [] : [4, 5, 6];
        }
        if (mt_rand()) {
            return [7, 8, 9];
        }
        return $employees;
    }
}
```

**Comment by jlherren** [comment]
Maybe related, here's another example where this rule alters the code's semantics: https://getrector.com/demo/e81e9b00-e29c-4bfd-a018-1e6858145669

In the original code, later code can overwrite `$icon`, which had been previously set.

**Comment by samsonasik** [comment]
I am closing it as if you have this use case, you can just skip the rule, or refactor to assign different variable first, as my above solution.
