### ISSUE TITLE
Rector injects prefixed code

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8212]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.18.3 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

here we can see it works like expected
https://getrector.com/demo/e5010b25-e812-4af0-849f-2bbf07bfb7e0

but the rector release on mautic leads

<img width="1152" alt="grafik" src="https://github.com/rectorphp/rector/assets/120441/63ac4ada-6db9-42f7-9f0d-aefa471dde63">

## Expected Behaviour

rector should not add rector-prefixed classes

**Comment by samsonasik** [comment]
Already resolved at PR:

- https://github.com/rectorphp/rector-doctrine/pull/227

you can use dev-main while wait for next release.

**Comment by staabm** [comment]
the fix is not covered by a test

**Comment by samsonasik** [comment]
It exists at https://github.com/rectorphp/rector-doctrine/blob/4b2518028cc5bf9266a9069b1f3e287d62a0012d/rules-tests/CodeQuality/Rector/Property/OrderByKeyToClassConstRector/Fixture/replace_order_by_asc_lower_with_class_constant.php.inc#L22

Prefixing is happen on scoped build.
