### ISSUE TITLE
Infer native return type

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8213]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.18.3  |

## Minimal PHP Code Causing Issue

I would expect one of the `SetList::TYPE_DECLARATION` rectors would be able to infer the native return type for `getPaginatorForPage`
https://getrector.com/demo/05f20a8b-09a6-4926-b4d0-fc5db36ade18

**Comment by samsonasik** [comment]
@staabm that seems due to static method, using method call is working ok

https://getrector.com/demo/200b1835-77ec-4478-8035-b74d7292591b

so the thing to do is apply to static method as well.

**Comment by staabm** [comment]
ok, thx. let me fix it in `ReturnTypeFromStrictTypedCallRector `

**Comment by staabm** [comment]
> @staabm that seems due to static method, using method call is working ok
> 
> [getrector.com/demo/200b1835-77ec-4478-8035-b74d7292591b](https://getrector.com/demo/200b1835-77ec-4478-8035-b74d7292591b)
> 
> so the thing to do is apply to static method as well.


hmm I think you changed the snippet too much. the actual problem is, the variable beeing returned.

this also doesn't work with non-static methods

**Comment by samsonasik** [comment]
I see, it seems another fallback on `ReturnTypeFromReturnNewRector` is needed

**Comment by staabm** [comment]
@samsonasik could you work on it?

**Comment by samsonasik** [comment]
I will try 👍

**Comment by samsonasik** [comment]
just trying in rector-src unit test, it seems working ok with `ReturnTypeFromReturnNewRector`, let's retry on next getrector.org build, should be on next 3 hours.

**Comment by staabm** [comment]
@samsonasik if it would be fixed, the corresponding change would show up in https://github.com/rectorphp/rector/issues/8213#issuecomment-1723093884

**Comment by samsonasik** [comment]
just deployed and it seems working ok https://getrector.com/demo/411c6f80-fe7c-455d-b51a-537a5c645a3b

the issue is probably on autoload or other thing

**Comment by staabm** [comment]
thanks!
