### ISSUE TITLE
Missing native return type

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8214]
# Feature Request

I think one of the rectors in `SetList::TYPE_DECLARATION` should be able to infer a return type for this method

https://getrector.com/demo/e32f094b-126b-4556-bd67-6a0fedc04781

**Comment by samsonasik** [comment]
The `InflowModel` already there, so it not re-add it, when not yet exists, it will add, see https://getrector.com/demo/cb02afb7-48ec-4d93-849d-229df28b59e6
