### ISSUE TITLE
Custom rule don't work

### ISSUE THREAD

**Issue by yusuke2930** [rectorphp/rector#8215]
# Question
I've looked at the official documentation and tried it. But custom rule don't work.
https://getrector.com/documentation/custom-rule

The following problems are occurring.
`Undefined type 'Symplify\RuleDocGenerator\ValueObject\RuleDefinition'.`

I can't seem to get `Symplify` to install.

# Development environment
（from composer.json）
- "php": "^8.1"
- "rector/rector": "^0.15.24"

**Comment by samsonasik** [comment]
The class is from prefixed vendor 

https://github.com/rectorphp/rector/blob/main/vendor/symplify/rule-doc-generator-contracts/src/ValueObject/RuleDefinition.php

you can ignore the notice on your IDE if your IDE don't detect it :)
