### ISSUE TITLE
RenameFunctionRector: Allow to add exceptions

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8216]
# Feature Request

I'm using `LevelSetList` which will register the rule `RenameFunctionRector` multiple times with varying configurations. All these configurations will be merged together as expected. However, I found no way to skip some of the renames.

I want to avoid renaming `split` to `explode` and `join` to `implode`, but still want to keep all other renames.

One possible way to implement this would be to allow `['split' => null]` in the configuration, so that the configuration merging would overwrite previous values and the rule would simply skip null values.

Another way would be something like `$rectorConfig->resetRuleConfiguration(RenameFunctionRector::class)` to reset only one configuration and then I have to reconfigure it manually with all the desired renames.

**Comment by staabm** [comment]
I don't think we should add such functionality.

would it work if you rename the 2 cases back into the previous form?
or maybe your CS tool of choice has a rule todo so?

**Comment by jlherren** [comment]
Oh well then. Renaming back and forth between two tools sounds like asking for troubles, so I will just have to disable the rule entirely.

**Comment by staabm** [comment]
The only thing which comes to my mind is separating this one rule which configures this big block auf renames into a separate setlist

https://github.com/rectorphp/rector-src/blob/d9d1fd27214af2c55612bfb852bc01b10663d1d6/config/set/code-quality.php#L87

but these are just my opinions.. I am not the person to decide this stuff :)

**Comment by TomasVotruba** [comment]
I think removing configuration would make whole point or pre-defined rules overly complex. I want to avoid this as we already have enouh options.

In your case, you can register your custom set, a custom rule to reverse or any other extra step. Personally I'd just go with defaults as it's really just naming detail.
