### ISSUE TITLE
Rector hangs indefinitely

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8220]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Current master (884a47)  |

The following example hangs indefinitely. However, it doesn't even seem like it is transforming the code back and forth.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/77ce4ebe-1776-4631-89c2-fec1d8773911

## Expected Behaviour

`BinarySwitchToIfElseRector` should convert the `switch` to `if-elseif`, then `RemoveAlwaysElseRector` should convert `elseif` to `if`. Then processing should end.

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

On a side note, I wonder how `BinarySwitchToIfElseRector` is useful, as those cases would be better refactored to match. What do you think?

**Comment by samsonasik** [comment]
@TomasVotruba it makes 3 check, it should convert into:

```php
        if (mt_rand() == 1) {
            return 10;
        } elseif (mt_rand() == 2) {
            return 20;
        }
        return 30;
```

converting from `elseif` to `if` should on next run, which ok on this case.

I am looking into it :)

**Comment by jlherren** [comment]
> On a side note, I wonder how `BinarySwitchToIfElseRector` is useful, as those cases would be better refactored to match. What do you think?

It's useful for the poor people still on PHP 7.
