### ISSUE TITLE
SimplifyEmptyCheckOnObjectRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8222]
# Feature Request

~~Similar to [SimplifyEmptyCheckOnEmptyArrayRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#simplifyemptycheckonemptyarrayrector) we should have a SimplifyEmptyCheckOnObjectRector~~

[better alternatives would be int or string](https://github.com/rectorphp/rector/issues/8222#issuecomment-1731073046) 

## Diff 

```diff

final class DemoFile
{
    public function run(MyObject $o)
    {
-        if (empty($o)) {
+        if ($o === null) {
        }
    }
}
```

**Comment by samsonasik** [comment]
object seems never empty on php 5+ https://3v4l.org/MBmZA

**Comment by staabm** [comment]
hmm you are right. more useful would be the same with `int`.

**Comment by staabm** [comment]
even better, we could utilize `non-falsy-string` to turn 

`empty($s)` into  `!== ''`

**Comment by staabm** [comment]
nice catch. its a pitty that our rector class names are so inconsistent. its pretty hard to discover this rules when they do so similar things but are so differently named

**Comment by TomasVotruba** [comment]
Closing as already covered in `DisallowedEmptyRuleFixerRector`.

Tip: Naming is hard and everyone has a different prefernce. What I do in Rector, PHPStan or cs rules is that I find the md page with all the rules, then I look for particular string that I'm interested in. E.g. "empty(". It works much faster than figuring out the package naming logic :) Hope that helps :pray:
