### ISSUE TITLE
`DoctrineAnnotationTagValueNode` - `resolved_class` attribute is wrong with namespace use import without alias

### ISSUE THREAD

**Issue by etshy** [rectorphp/rector#8224]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.3            |

With "namespace" use import without alias the `resolved_class` attribute of `DoctrineAnnotationTagValueNode` is wrong and doesn't contain full class

## Minimal PHP Code Causing Issue

As it involves namespace import I don't think I can reproduce on rector/demo, but here is an example

```php

use Symfony\Component\Validator\Constraints;
use Symfony\Component\Validator\Constraints as Test;

class MyClass
{
    /**
     * @var float
     *
     * @Test\GreaterThanOrEqual(value=10)
     * @Constraints\GreaterThanOrEqual(value=10)
     */
    private $property;
}

```

I noticed this bug while using `AnnotationToAttributesRector` (The `SymfonySetList::SYMFONY_52_VALIDATOR_ATTRIBUTES`) and saw that my `@Constraints\...` were not converted

In this context, `@Constraints\GreaterThanOrEqual(value=10)` won't have a proper `resolved_class` attribute.
From what I tried and dumped, it will be `"Symfony\Component\Validator\Constraints"`

While the statement `@Test\GreaterThanOrEqual(value=10)` will have proper  `resolved_class` attribute : `"Symfony\Component\Validator\Constraints\GreaterThanOrEqual"`

## Expected Behaviour

"namespace" use import (I don't know how to call it) without alias should be able to have a proper `resolved_class` attribute.

### Other

I noticed multiple classes that set that attribute I found 2 differents way to get the FQCN of the Annotation

`$this->classAnnotationMatcher->resolveTagFullyQualifiedName()` in `PlainValueParser` and `DoctrineAnnotationDecorator`

And

```php
$nameScope = $this->nameScopeFactory->createNameScopeFromNodeWithoutTemplateTypes($phpNode);
return $nameScope->resolveStringName($constFetchNode->className);
```
in `ConstExprClassNameDecorator`

The one being called in my case seems to be `$this->classAnnotationMatcher->resolveTagFullyQualifiedName()`

I will make more research on the FQN resolver and will post what I found.

**Comment by etshy** [comment]
Took a deeper look and dumped my way to the `UseImportNameMatcher::resolveName()` method.

I suggest this kind of fix

Before 'fix'
```php
    private function resolveName(string $prefix, string $tag, UseUse $useUse) : string
    {
        // useuse can be renamed on the fly, so just in case, use the original one
        $originalUseUseNode = $useUse->getAttribute(AttributeKey::ORIGINAL_NODE);
        if (!$originalUseUseNode instanceof UseUse) {
            throw new ShouldNotHappenException();
        }
        if (!$originalUseUseNode->alias instanceof Identifier) {
            return $prefix . $originalUseUseNode->name->toString();
        }
        $unaliasedShortClass = Strings::substring($tag, \strlen($originalUseUseNode->alias->toString()));
        if (\strncmp($unaliasedShortClass, '\\', \strlen('\\')) === 0) {
            return $prefix . $originalUseUseNode->name . $unaliasedShortClass;
        }
        return $prefix . $originalUseUseNode->name . '\\' . $unaliasedShortClass;
    }
```

After 'fix
```php
    private function resolveName(string $prefix, string $tag, UseUse $useUse) : string
    {
        // useuse can be renamed on the fly, so just in case, use the original one
        $originalUseUseNode = $useUse->getAttribute(AttributeKey::ORIGINAL_NODE);
        if (!$originalUseUseNode instanceof UseUse) {
            throw new ShouldNotHappenException();
        }
        if (!$originalUseUseNode->alias instanceof Identifier) {
            if (!class_exists($prefix . $originalUseUseNode->name->toString())) {
                //no alias and not a direct use import of a class, search the class
                $tagExploded = explode('\\', $tag);
                if (reset($tagExploded) === end($originalUseUseNode->name->parts)) {
                    $FQNClassArray = [$prefix, ...$originalUseUseNode->name->parts, ...$tagExploded];
                    $FQNClassArray = array_filter($FQNClassArray);
                    $FQNClassArray = array_unique($FQNClassArray);
                    $FQNClass = implode('\\', $FQNClassArray);
                    if (class_exists($FQNClass)){
                        return $FQNClass;
                    }
                }
            }
            return $prefix . $originalUseUseNode->name->toString();
        }
        $unaliasedShortClass = Strings::substring($tag, \strlen($originalUseUseNode->alias->toString()));
        if (\strncmp($unaliasedShortClass, '\\', \strlen('\\')) === 0) {
            return $prefix . $originalUseUseNode->name . $unaliasedShortClass;
        }
        return $prefix . $originalUseUseNode->name . '\\' . $unaliasedShortClass;
    }
```

I just tested it in my context of AnnotationToAttribute with the set `SymfonySetList::SYMFONY_52_VALIDATOR_ATTRIBUTES` but it seems to be working well.

**Comment by samsonasik** [comment]
`resolved_class` is no need to verify if the class/interface/trait exists iirc, just the FQCN provided

**Comment by etshy** [comment]
Sorry I don't understand clearly. You mean in my "fixed" code block ?
Isn't it better to check if the class exists before assigning it to `resolved_class` ?

The thing is I don't know how I can check we are in the condition 'namespace import without alias' apart from checking if the "resolved class" string is an existing class.

**Comment by samsonasik** [comment]
it should not, no need to deal with autoload, use namespaced fqcn based on scope namespace sync with the name provided instead.

**Comment by etshy** [comment]
Should I just check that the `end()` of the `$originalUseUseNode->name->toString()` match the end of the `$originalUseUseNode->name->parts` then ?

**Comment by samsonasik** [comment]
I think a PR would be more visible than discuss here so we know the exact failing test case and possible fix 👍

**Comment by etshy** [comment]
will make one soon then

**Comment by etshy** [comment]
Made the PR rectorphp/rector-src#5123
