### ISSUE TITLE
Remove ltrim() check FileProcessor when using nikic/PHP-Parser 5.0

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#8228]
# Feature Request

On current nikic/PHP-Parser 4.x, the `ltrim()` is used on `printFormatPreserving()`:

https://github.com/nikic/PHP-Parser/blob/a6303e50c90c355c7eeee2c4a8b27fe8dc8fef1d/lib/PhpParser/PrettyPrinterAbstract.php#L503

On latest `nikic/PHP-Parser` master branch, the `ltrim()` no longer used on `printFormatPreserving()`

https://github.com/nikic/PHP-Parser/blob/f5adbb5e3fa57d2ff7b9ea179b88bcd2ced153e0/lib/PhpParser/PrettyPrinterAbstract.php#L553

Once `nikic/PHP-Parser 5.0` released, I think `ltrim()` no longer needed on `FileProcessor`

https://github.com/rectorphp/rector/blob/6bcd7272d244af064d3a7a798b83ec7295274eb3/src/Application/FileProcessor.php#L177-L181

**Comment by TomasVotruba** [comment]
The php-parser 5.0 is far away and we'll probably make lot of changes at once when it happens, not necessary to document those in advance now.
