### ISSUE TITLE
Rector crashes with only `->importNames()` in config 

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#8230]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.17.14             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/4aaf415f-7454-46cc-8ee2-678a283d1d5b

## Expected Behaviour

No crash

**Comment by samsonasik** [comment]
You need to have at least 1 rule defined https://getrector.com/demo/5fd167a3-8de0-42b5-8380-39bd387fee9c

It probably bug on website, it actually show warning in cli:

```
➜  rector-src git:(main) ✗ bin/rector process src

                                                                                                                        
 [WARNING] Register rules or sets in your "rector.php" config
```

**Comment by simPod** [comment]
Yup, not a big deal but felt like it should be reported.

**Comment by samsonasik** [comment]
@TomasVotruba the website is crash instead of show warning, it is website bug

**Comment by TomasVotruba** [comment]
@samsonasik Indeed. Should be reported and fixe don website repository then.
