### ISSUE TITLE
inline unnecessary property

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8232]
# Feature Request

I think we should have a rule, which inlines private properties with constant values, which are never changed within a class.
 
## Diff 

https://getrector.com/demo/05d753f7-280f-4ff9-aff8-ead3ae2bde1e

```diff
final class DemoFile
{
-   private static array $supportedLanguages = ['de', 'en'];

    public static function getSupportedLanguages()
    {
-        return self::$supportedLanguages;
+        return ['de', 'en'];
    }
}
```

also for non-static case

```diff
final class DemoFile
{
-   private array $supportedLanguages = ['de', 'en'];

    public function getSupportedLanguages()
    {
-        return $this->supportedLanguages;
+        return ['de', 'en'];
    }
}
```

----

a case which should be skipped:

```php
final class SkipModifiedProperty
{
   private array $supportedLanguages = ['de', 'en'];

    public function getSupportedLanguages()
    {
        return $this->supportedLanguages;
    }

    public function learnFrench() {
      $this->supportedLanguages[] = 'fr';
    }
}

**Comment by TomasVotruba** [comment]
Thanks for proposal. In some cases, this could be nice to have.
 
Yet I think these should be optional, as someone would prefer constants, someones would like to have this outside the method as "working data". 

Having a core rule with all the options would be overly complex, so I'd recommend making a custom rule in your projects to handle this.
