### ISSUE TITLE
Add rule to remove methods that only call the parent

### ISSUE THREAD

**Issue by gisostallenberg** [rectorphp/rector#8234]
# Feature Request

A method that only calls the parent can simply be removed.
 
## Diff 
```diff
-    public function doSomething(): void
-    {
-        parent::doSomething();
-    }
```
or 
```diff
-    public function doSomething(): bool
-    {
-        return parent::doSomething();
-    }
```
or 
```diff
-    protected function doSomething(): void
-    {
-        parent::doSomething();
-    }
```

**Comment by TomasVotruba** [comment]
Hi, thanks for proposal. We actually had such rule before, but in some cases this is needed and it's hard to guess what those are.
Having false positives lead to back/forth config coding, so we won't add it again. Thanks for understanding

Instead it's better to use PHPStan to detect such cases and let user decide :+1:
