### ISSUE TITLE
 [ERROR] Could not process  xxx.php" file, due to:      "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node, but is required by a                         refactorWithScope() method of "Rector\Php71\Rector\FuncCall\CountOnNullRector" rule. Fix scope refresh on    changed nodes first"                   

### ISSUE THREAD

**Issue by gillboysimran** [rectorphp/rector#8238]
Stack trace:                                                                                                   
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(172):                                                    
         Rector\Core\Rector\AbstractScopeAwareRector->refactor(Object(PhpParser\Node\Expr\FuncCall))                    
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                          
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))                             
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))                                      
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Function_))                                   
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))      
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                           
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #9 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(50):                               
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #10 vendor/rector/rector/src/Application/FileProcessor.php(115):                                               
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #11 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):                                    
         Rector\Core\Application\FileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File),           
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #12 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):                                    
         Rector\Core\Application\ApplicationFileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File) 
         , Object(Rector\Core\ValueObject\Configuration))                                                               
         #13 vendor/rector/rector/src/Console/Command/WorkerCommand.php(132):                                           
         Rector\Core\Application\ApplicationFileProcessor->processFiles(Array,                                          
         Object(Rector\Core\ValueObject\Configuration), Object(Closure))                                                
         #14 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}(Array)                        
         #15 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202309\Evenement\EventEmitter->emit('data', Array)                                                 
         #16 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202309\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #17 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202309\Evenement\EventEmitter->emit('data', Array)                                                 
         #18 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202309\React\Stream\Util::RectorPrefix202309\React\Stream\{closure}('{"action":"main...')          
         #19 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202309\Evenement\EventEmitter->emit('data', Array)                                                 
         #20 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202309\React\Stream\DuplexResourceStream->handleData(Resource id #1817)                            
         #21 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202309\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #22 vendor/rector/rector/src/Console/Command/WorkerCommand.php(90):                                            
         RectorPrefix202309\React\EventLoop\StreamSelectLoop->run()                                                     
         #23 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202309\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))                          
         #24 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202309\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202309\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))           
         #25 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202309\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202309\Symfony\Component\Console\Input\ArgvInput),                              
         Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #26 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202309\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202309\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))             
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202309\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))                               
         #28 vendor/rector/rector/bin/rector.php(130): RectorPrefix202309\Symfony\Component\Console\Application->run()  
         #29 vendor/rector/rector/bin/rector(5): require_once('/Users/...')                                     
         #30 vendor/bin/rector(119): include('/Users/...')                                                      
         #31 {main}"

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by gillboysimran** [comment]
how can resolve that issue ? I am stuck this error  in 2 days and try many rules in rector config. 

Also try the debug command 

vendor/bin/rector process /phplib/phplist/lists/admin/xxx.php --debug

then arrive this above whole error.

**Comment by TomasVotruba** [comment]
We'll need an isolated failing demo link from: http://getrector.com/demo,
the way we can reproduce the bug. Otherwise there is nothing we can do.

**Comment by sanketgandhi876** [comment]
Hey @TomasVotruba,

I'm able to reproduce this issue - https://getrector.com/demo/ee59a4a1-ce96-4022-91e2-f0b6348a6344

Apparently, `$$` was present in the code.

**Comment by samsonasik** [comment]
@sanketgandhi876 the issue seems different with original reported, which a `CountOnNullRector` , your issue is reproduced with `OptionalParametersAfterRequiredRector`

https://getrector.com/demo/c6ba1f81-2d8e-4a96-9f4b-5d5def428ad3

**Comment by samsonasik** [comment]
I am closing as it probably already resolved at https://github.com/rectorphp/rector-src/pull/5089 while different rule.

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

Feel free to create new issue with reproducible code and config if the issue persist, otherwise, nothing we can do :)
