### ISSUE TITLE
Mutiline string value in annoation are not parsed correctly

### ISSUE THREAD

**Issue by etshy** [rectorphp/rector#8239]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.4            |

Multiline string value in annoation are not parsed correctly.

I have the following annotation
```php
 /**
     * @OA\QueryParameter(name="orderBy", @OA\Schema(type="string"), required=false, description="List of value:
     *  - <b>TRY</b>: To try
     *  - <b>TEST</b>: to test (Default if no parameters given)")
     */
    public function test()
    {}
```
And `description` value is set to `"ListOfValue`
see the following rector diff
```diff
-     * @OA\QueryParameter(name="orderBy", @OA\Schema(type="string"), required=false, description="List of value:
-     *   - <b>TRY</b>: To try
-     *   - <b>TEST</b>: to test (Default if no parameters given)")
+    #[OA\QueryParameter(name: 'orderBy', schema: new OA\Schema(type: 'string'), required: false, description: '"Listofvalue')]
```

## Minimal PHP Code Causing Issue

Will try to make a minimal repo reproduction later.

## Expected Behaviour

`description` parsed value is the same multiline value as the original annoation (minus the `*` and extra space due to annotation)

**Comment by etshy** [comment]
[here's](https://github.com/etshy/rector-8239) a repo that reproduce the issue

**Comment by etshy** [comment]
I could try, i need to understand the parse a bit more though.
I'll take a look this weekend.

**Comment by samsonasik** [comment]
Already resolved, ref 

- https://github.com/rectorphp/rector-src/pull/5147
- https://github.com/rectorphp/rector-src/pull/5317
