### ISSUE TITLE
Enable files without extension to be processed

### ISSUE THREAD

**Issue by AlexisJehan** [rectorphp/rector#8243]
As far as I know, _Rector_ is not able to process files without extension, such as PHP files in the `bin` directory with the `#!/usr/bin/env php` header.

Please add an option to enable processing those files, thanks!

**Comment by samsonasik** [comment]
Rector detect file with .php extension by default.

I am not sure if processing file without extension is ok, you can create 2 files for shebang usage

see 

https://github.com/rectorphp/rector/blob/main/bin/rector

that consume

https://github.com/rectorphp/rector/blob/main/bin/rector.php


or add file with .php extension directly:

You can, see https://getrector.com/demo/9fca61ae-8bfa-4304-a59e-87e743d29250

**Comment by AlexisJehan** [comment]
Thank you for your answer.

I was hoping for a solution that would work with my existing project, without having to rename files.

Because we have this:
```php
$rectorConfig->fileExtensions(['php', 'phtml']);
```

I would hope for an option, such as:
```php
$rectorConfig->enableFilesWithoutExtension();
```

It was already asked here:
https://github.com/rectorphp/rector/pull/1285#issuecomment-1046807699

**Comment by samsonasik** [comment]
Targetting file without extension is dangerous imo, it can be php file or file system so should be avoided, extract into 2 files, and it should be ok

**Comment by staabm** [comment]
I agree analyzing without extensions would be dangerous. 

The only thing I could think of is invoking rector to process a path like `recor process `/my/file-without-extension`

**Comment by samsonasik** [comment]
That will cause ambiguous usage, the `fileExtensions()` is defined to limit the usage to avoid dangerous action.

**Comment by AlexisJehan** [comment]
To avoid ambiguous or dangerous usages, and because we can't specify extensions by path with the current configuration, it would be possible with such an option:
```php
$rectorConfig->additionalFiles([
    'bin/command1',
    'bin/command2',
]);
```

**Comment by samsonasik** [comment]
I am closing it as I think rector should not add option for dangerous action.

File extensions filtering is set globally, add additional file config will make too many tricky to pull from that config :). 

The solution is you can create 2 files, one for shebang file, one is php file that include shebang file so you can get win-win solution.

Thank you for understanding.

**Comment by gharlan** [comment]
In php-cs-fixer config you can add files explicitly:

```php
$finder = (new PhpCsFixer\Finder())
    // within these dirs only .php files are fixed/checked
    ->in([
        __DIR__.'/src',
        __DIR__.'/public',
   ])
    // for these files extension is not checked:
    ->append([
        __DIR__.'/bin/my-script',
        __DIR__.'/bin/other-script',
    ])
;

return (new PhpCsFixer\Config())
    ->setFinder($finder)
    ->setRules([ /* ... */])
;
```

I think it is not dangerous if the files are listed explicitly.

**Comment by samsonasik** [comment]
@gharlan we use phpstan Aggregate source locator, which looking on ".php" file by default on its internal phpstan filefinder service, rector uses phpstan, while allow non-.php extension files, the ".php" file is used by phpstan internal locator to locate classes and type identifier definition as initialization and source of truth.

Allowing lookup file without extension will make false positive since type may not be detected, and that will make another unneeded challenge.

You can make 2 files, one is real ".php" file, and another with shebang as executable file that load ".php" file like rector does.
