### ISSUE TITLE
Support for PHP FIG PER Coding Style 2.0

### ISSUE THREAD

**Issue by kenguest** [rectorphp/rector#8245]
# Feature Request

Does rectorphp support the fig per-cs Coding Standards which replaces PSR-12? ( https://www.php-fig.org/per/coding-style/ )
If not, are there any plans to do so? What can people do to help?

total disclosure: I'm a member of the PHP FIG PER Coding Standard working group

**Comment by samsonasik** [comment]
Hi, you may looking for easy-coding-standard that consume php-cs-fixer ans phpcs rules, which the setlist possibly can based on them whenever exists

https://github.com/easy-coding-standard/easy-coding-standard/
