### ISSUE TITLE
Segfault error on 0.18.4 with self referencing phpdoc

### ISSUE THREAD

**Issue by VincentLanglet** [rectorphp/rector#8246]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.18.4             |

## Minimal PHP Code Causing Issue

Hi @TomasVotruba 

I had an issue with a PHPStan syntax reported here https://github.com/phpstan/phpstan/issues/9039.
Now, it's fixed on the PHPStan, but seems like the syntax is creating a Segfault error with rector.

## Expected Behaviour

I tried 0.18.4 and the error is still here.
Then I tried dev-main and there is no segfault error (maybe because rector bumped Phpstan ?).
So would it be possible to release a 0.18.5 version ?

Big thanks for this tool.

**Comment by samsonasik** [comment]
Yes, Rector 0.18.4 still load scoped phpstan vendor early. You can use dev-main for now while waiting for new Rector release :)

**Comment by staabm** [comment]
@VincentLanglet if the segfault is reproducible on a recent php version you should reduce it as far as possible and report a php-src issue with steps on how to reproduce

**Comment by samsonasik** [comment]
Rector 0.18.5 released https://github.com/rectorphp/rector/releases/tag/0.18.5
