### ISSUE TITLE
Nested Annotations without parameter name are prefixed by `0=`

### ISSUE THREAD

**Issue by etshy** [rectorphp/rector#8248]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.5           |

reprinting docblock without changes in it add a `0=` before nested annotation without param name.

```diff
-     * @OA\QueryParameter(name="property", @OA\Schema(type="string"), required=false)
+     * @OA\QueryParameter(name="property", 0=@OA\Schema(type="string"), required=false)
```

found this using a (really bad) custom Rector Rule that rename annotation (`@Mapping\` to `@ORM`, see: discussion #8195 )
I didn't find a better way to force the reprint than reprinting alwost everything at the time I made this Rule, so I have docBloxk that are reprinting themselves without changes, and found this bug (my Rule is working "fine" in rector 0.18.4).

## Minimal PHP Code Causing Issue

Will make a repo that reproduce the issue later on my free time.
But basically, my rule is changing the `start_and_end` attribute to null to force reprint and avoid old annotation to be retrieved in the `PhpDocInfoPrinter` during the call `$this->docBlockUpdater->updateRefactoredNodeWithPhpDocInfo($node);`

## Expected Behaviour

Nested Annotation without parameter name stays without parameter name.

```diff
-     * @OA\QueryParameter(name="property", @OA\Schema(type="string"), required=false)
+     * @OA\QueryParameter(name="property", @OA\Schema(type="string"), required=false)
```

**Comment by samsonasik** [comment]
this should already resolved at PR:

- https://github.com/rectorphp/rector-src/pull/5277/files#diff-a5a87557b1bec4188b996282f5a366696d0c9d79252d69cc32ae9416643abaa0

that if key is integer on print, it should not not add `key=`. Please try latest rector/rector:dev-main
