### ISSUE TITLE
Order of `implode` parameters when upgrading to PHP >= 8.0

### ISSUE THREAD

**Issue by rtnetlab** [rectorphp/rector#8249]
# Question

We are in the process of upgrading an old codebase to PHP 8, and we use Rector for this.

The code has a lot of these occurrences :

```php
$var = implode($array, ','); // Notice the separator is passed as a second argument
```

PHP 8.0 no longer supports passing the separator after the array (https://www.php.net/manual/en/function.implode.php#refsect1-function.implode-changelog).

We were surprised these occurrences were not caught by Rector when using `LevelSetList::UP_TO_PHP_82`. We also noticed a Rector exists for this (`ConsistentImplodeRector`), but it is in "Coding style".

We believe this should be in the PHP 8.0 set rules, but maybe we missed something ?

**Comment by TomasVotruba** [comment]
> We believe this should be in the PHP 8.0 set rules, but maybe we missed something ?

I think that's a good idea. Could you add it?

**Comment by giacomomasseron** [comment]
I would like to make this change, am I missing something or does the file just need to be moved from the CodingStyle folder to Php80?

**Comment by TomasVotruba** [comment]
Go for it :+1: 

I'd keep it at both places, as in coding style it will deliver on any PHP version, while PHP 8.0 is part of core requirement.

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-src/pull/5139
