### ISSUE TITLE
Ruleset DEAD_CODE original logic violation

### ISSUE THREAD

**Issue by ethernidee** [rectorphp/rector#8255]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.4             |

## Minimal PHP Code Causing Issue

```php
/**
 * Returns last key of any tranversable container.
 */
function lastKey ($container, $defKey = null) {
  $result = $defKey;

  foreach ($container as $result => $value) {
    // next
  }

  return $result;
}
```

## Expected Behaviour

Rector MUST NOT change `foreach ($container as $result => $value) {` into `foreach ($container as $value) {`. We lose `$result = next key` logic from FOR statement. Thus the code always returns default key. Dead code elimination MUST NOT change application logic and it seems to break it in many cases as I see.

**Comment by samsonasik** [comment]
It seems reproduced by ` RemoveUnusedForeachKeyRector ` when key used in next stmt 

https://getrector.com/demo/e35ca9fd-ee5b-4ed9-bc23-c1cc5e33970a
