### ISSUE TITLE
How do I add a comment / doccomment

### ISSUE THREAD

**Issue by HaaseIT** [rectorphp/rector#8257]
# Question

I tried to find a way for some time now.

One of the things I tried:

```
$doc = new Doc('/* FOO */');
$node->setDocComment($doc);
```

Is this possible at all to do with Rector?

We have some places in our code where we cannot automatically refactor, so we want to add comments there.

**Comment by samsonasik** [comment]
You can use `Node\Stmt\Expression` for that.

**Comment by HaaseIT** [comment]
Got it working now, thank you!
