### ISSUE TITLE
Incorrect behavior of SwapFuncCallArgumentsRector, MysqlQueryMysqlErrorWithLinkRector, RemoveFuncCallArgRector, RenameFunctionRector

### ISSUE THREAD

**Issue by szalek** [rectorphp/rector#8258]
# Bug Report

| Subject        | Details              |
| MYSQL_TO_MYSQLI |
this is an error that appears on the official website
LINK: https://getrector.com/demo/7e2988ea-8664-4bf3-8dd5-36c2c6ca3eea
Rector run Failed:

{"fatal_errors":["Undefined constant Rector\\Set\\ValueObject\\SetList::MYSQL_TO_MYSQLI"]}
How do you use this comend set? I have a problem using this in my project the recotra version is 0.18.5. When enhancing the code with your tool it changes the whole cod where there is only PHP but when there is a function with a query to MYSQL nothing changes. Is there any way to change this. apart from that, recotra does not change anything with the autoload function. I am upgrading the old PHP 5.6 code
|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/245c21af-da24-4ddf-a448-169126ed6e90

```php
<?php
	function sql_connect($db_user, $db_password, $db_host, $db_port = false)
	{
		$this->conn = mysql_connect($db_host, $db_user, $db_password, true);
		mysql_set_charset('UTF8', $this->conn);
		mysql_select_db($this->db_database, $this->conn);
    }
?>
```

### Responsible rules

* `SwapFuncCallArgumentsRector`

* `MysqlQueryMysqlErrorWithLinkRector`

* `RemoveFuncCallArgRector`

* `RenameFunctionRector`

**Comment by TomasVotruba** [comment]
Hi, we no longer support the mysql to mysqli set as it was breaking more than it helped :)

**Comment by szalek** [comment]
you have something to replace it?

**Comment by samsonasik** [comment]
see https://github.com/rectorphp/rector-src/pull/4448#issue-1795295628
