### ISSUE TITLE
Incorrect behavior of IssetOnPropertyObjectToPropertyExistsRector

### ISSUE THREAD

**Issue by necocen** [rectorphp/rector#8260]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.18.5      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/6e4565f9-b3a0-49d9-99ec-f545581af3c3

```php
<?php

class Foo
{
    public $x;
}

$f = new Foo();
$p = 'x';
isset($f->{$p});
```

### Responsible rules

* `IssetOnPropertyObjectToPropertyExistsRector`

## Expected Behavior

```php
<?php

class Foo
{
    public $x;
}

$f = new Foo();
$p = 'x';
property_exists($f, $p) && $f->{$p} !== null; // args of `property_exists` must be `$f` and `$p`, not `$f` and `'p'`
```

**Comment by samsonasik** [comment]
I think it should be skipped as value is magic.
