### ISSUE TITLE
SimplifyUselessVariableRector missing opportunity

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8262]
# Bug Report

I expected SimplifyUselessVariableRector  to cleanup this code

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/b2fd9fbe-1209-4cbb-a317-fdd49ad2f2b1

## Expected Behaviour

```diff
<?php

function apcInstalled(): bool
{
    $apcInstalled = false;
-   $apcInstalled = false;
    if (rand(0,1)) {
        return true;
    }

-    return $apcInstalled;
+    return false;
}
```

**Comment by samsonasik** [comment]
Since variable may be used in next call, the SideEffectNodeDetector and by-ref param may need to be used to verify.

**Comment by staabm** [comment]
Alternativly maybe there should be a rector which tests all return expression whether they just return a constant type and replace the return expression with said constant?

**Comment by samsonasik** [comment]
On method call or user defined function. it clearly should be skipped, as variable can be used via:

```
global $var;

++$var;
```

which change behavior, On native function, there is PureFunctionDetector service, that consumed by SideEffectNodeDetector

**Comment by samsonasik** [comment]
we were have `MoveVariableDeclarationNearReferenceRector` , removed at:

- https://github.com/rectorphp/rector-src/pull/1157

**Comment by samsonasik** [comment]
I checked the code, it seems the rule is designed to cover Assign in Expression, then use after that, which your use case is out of scope.

we had the `MoveVariableDeclarationNearReferenceRector`, and due to magical, removed at 

- https://github.com/rectorphp/rector-src/pull/587

on that reasoning, I am closing it :)
