### ISSUE TITLE
RemoveUnusedVariableAssignRector: calls with side-effects should not be removed

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8263]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a56b4a20-48c9-4a49-8316-ba6873ba3c76

```php
<?php

final class DemoFile
{
    public function run(bool $param)
    {
        $return = file_get_contents("http://example.com");
    }
}
```

### Responsible rules

RemoveUnusedVariableAssignRector

## Expected Behavior

calling `file_get_contents` has side-effects and therefore this line should not be removed, but just the assigned variable (or just leave the line as is)

**Comment by samsonasik** [comment]
What the side effect of `file_get_contents`?

Unless it used along with `ob_*` function call, it seems no side effect

**Comment by staabm** [comment]
one side-effect is, that it spawns a `$http_response_header` variable.

the call itself could trigger whatever side-effect at the system beeing called via the url.

**Comment by samsonasik** [comment]
I see, that seems need to be registered to PureFunctionDetector service, could you add it? Thank you.

**Comment by samsonasik** [comment]
After I re-check, it seems only spawn header when it called in singular process, not different process, because there is no next direct usage, after it is make `null` headers. Calling:

```

get_contents();
var_dump($http_response_header);
```

will get :

```
Undefined variable $http_response_header
```

except, we have real repository to test real use case for re-used after removed. 

Could you create a simple repo use case for it which header can be re-used?

**Comment by staabm** [comment]
in my testing, the example behaves identical to what is described on the php.net manual:

![grafik](https://github.com/rectorphp/rector/assets/120441/37090f31-fa15-4f0e-97e5-88985ddc8555)

**Comment by staabm** [comment]
> will get :

it seems you missed the point of the code example. I [just sent a php-docs improvement PR](https://github.com/php/doc-en/pull/2854) to make it more clear

**Comment by samsonasik** [comment]
no, that on singular process, the process must be:

```
call method via another method call which variable is only scoped there

var_dump($http_response_header)
```

eg:

```
call_method_that_call_has_inner_file_get_contents_inside_it();
var_dump($http_response_header);
```

**Comment by staabm** [comment]
> no, that on singular process, the process must be:

how did you came to this conclusion? I can't find anything in the docs which reads like what you describe

**Comment by samsonasik** [comment]
I see, I created PR https://github.com/rectorphp/rector-src/pull/5162 for it.
