### ISSUE TITLE
Incorrect behavior of RemoveUnusedNonEmptyArrayBeforeForeachRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8264]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/ce3bf51a-6f56-45c7-a044-8c90fdd59dec

```php
<?php

final class DemoFile
{
    public const DEFAULT_GROUP = 'default';
    
    /**
     * @var array<string, list<self>>
     */
    private static $groups = [];

    public static function getFootnotes($group = self::DEFAULT_GROUP): array
    {
        if (! empty(self::$groups[$group])) {
            foreach (self::$groups[$group] as $note) {
                echo "hello";
            }
        }

        return [];
    }
}
```

### Responsible rules

* `RemoveUnusedNonEmptyArrayBeforeForeachRector`

## Expected Behavior

the `if (! empty(self::$groups[$group])) {` block should not be removed, because we don't know whether `self::$groups[$group]` will be defined at runtime.

interessting effect: if we remove the phpdoc from the array-property, rector skips the snippet

**Comment by samsonasik** [comment]
I think for this case, you can use:

```php
$rectorConfig->skip();
```

the verification already too complex to handle that niche usage :), the static property itself defined as:

- has default array
- has docblock array
- used on loop

I know that static property is one and only in all object created, but user should use the one they defined :), on that reasoning, I am closing it ;)

**Comment by staabm** [comment]
Doesn't the change in behavior based on phpdoc indicate that we should do a getNativeType() somewhere, where we are doing a getType() atm?

**Comment by samsonasik** [comment]
I tried that, checking `empty()` is not that easy, it can be:

```php
function foo(?array $item)
{
   if (! empty($item)) ...
}
```

and various other use cases.

The private static property is ok to be changed outside object creation by other object from runtime, but that is very rare use case, since defined as array value, and used as loop.
