### ISSUE TITLE
Could you help me understand how to use RenameClassRector correctly please?

### ISSUE THREAD

**Issue by carlnewton** [rectorphp/rector#8269]
# Question

Hello,

Sorry if I'm misunderstanding this. I've just discovered Rector last week, and I appreciate that I might be misunderstanding the purpose of `RenameClassRector`. I've looked for other questions about this issue, but couldn't find any. Is this indended behaviour, and if so, could anyone point me in the right direction of which utility I should be using please?

Many thanks!

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/054db623-9af5-4817-83c0-fcacb00bbde7

```php
// rector.php
<?php

use Rector\Config\RectorConfig;
use Rector\Renaming\Rector\Name\RenameClassRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(RenameClassRector::class, [
        'Foods\Fruit' => 'Foods\Abstract\Fruit',
    ]);
};
```

```php
<?php
// src
use Foods\Fruit;
    
class Apple extends Fruit
{
    
}
```

### Responsible rules

* `RenameClassRector`

## Expected Behavior

```diff
-use Foods\Fruit;
+use Foods\Abstract\Fruit;
     
class Apple extends Fruit
 {
     
 }
```

## Actual Behavior

```diff
 use Foods\Fruit;
     
-class Apple extends Fruit
+class Apple extends \Foods\Abstract\Fruit
 {
     
 }
```

**Comment by staabm** [comment]
After running rector you should run a codestyle tool which achieves whatever style you prefer.

**Comment by TomasVotruba** [comment]
Also, you can use autoimport: https://getrector.com/documentation/import-names
