### ISSUE TITLE
Rector removes arguments that are passed to a function which uses func_get_args()

### ISSUE THREAD

**Issue by Waghabond** [rectorphp/rector#8270]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.4            |

Rector removes arguments that are passed to a function which uses func_get_args() to retrieve a dynamic list of arguments.
## Minimal PHP Code Causing Issue
```php
function addHeader()
{
    $args = func_get_args();
    if(!empty($args[1])){
        $this->_headers[$args[0]] = $args[1];
    }elseif (!empty($args[0]) && is_array($args[0])){
        $this->_headers = array_merge($this->_headers,$args[0]);
    }elseif (!empty($args[0])){
        $this->_headers[] = $args[0];
    }
}

function setContentTypeForFormat($format)
{
    if (!empty($format)) {
        $mime_type = Ak::mime_content_type('file.'.$format);
        if (!empty($mime_type)) {
            $this->addHeader('Content-Type', $mime_type);
        }
    }
}
```
gets refactored to the following (using LevelSetList::UP_TO_PHP_82)
```php
function addHeader()
{
    $args = func_get_args();
    if(!empty($args[1])){
        $this->_headers[$args[0]] = $args[1];
    }elseif (!empty($args[0]) && is_array($args[0])){
        $this->_headers = array_merge($this->_headers,$args[0]);
    }elseif (!empty($args[0])){
        $this->_headers[] = $args[0];
    }
}

function setContentTypeForFormat($format)
{
    if (!empty($format)) {
        $mime_type = Ak::mime_content_type('file.'.$format);
        if (!empty($mime_type)) {
            $this->addHeader();
        }
    }
}
```

## Expected Behaviour
func_get_args() should either be left alone or refactored to variadic function param, and the places where the function is called should be left as they are.

I found a good work around was to first run rector with the `FuncGetArgsToVariadicParamRector` rule only.
then run rector again with `LevelSetList::UP_TO_PHP_82`.
If the level set list could ensure that it runs the `FuncGetArgsToVariadicParamRector` before the rule that removes "unnecessary" function arguments, that might fix the issue.
I know the above code snippets are "bad code" but I'm just trying to upgrade a legacy codebase to php 8 :/

**Comment by samsonasik** [comment]
Could you provide reproducible code and config (better with only 1 or 2 rules applied) on https://getrector.com/demo ? Thank you.
