### ISSUE TITLE
Using rector with classes that use vendor code 

### ISSUE THREAD

**Issue by vinas8** [rectorphp/rector#8272]
# Question
when i try to use it in my project I get

 [ERROR] Could not process some files, due to:                                                                          
         "Child process error: Fatal error: Trait "Namespace\...\xx.php" not   
         found in src/.../yy.php "        
         
         
 the xx.php belongs to vendor directory
 
 Does'nt rector work with vendor files?

**Comment by vinas8** [comment]
@samsonasik 
I tried this docs but it did not work. I'm using Spryker framework and I still get 

```
 [ERROR] Could not process some files, due to:                                                                          
         "Child process error: Fatal error: Trait "Spryker\Zed\Kernel\Persistence\EntityManager\TransactionTrait" not   
         found in src/Pyz/Zed/CompanyPriceGroup/Business/Model/CompanyPriceGroup.php11                                  
         ompanyPriceGroup.php11                                                                                         
         ".        
```
Even If I add
```
    $rectorConfig->autoloadPaths([
        // the path to the exact class file
        __DIR__ . '/vendor/spryker/kernel/src/Spryker/Zed/Kernel/Persistence/EntityManager/TransactionTrait.php',
        // or you can specify a wider scope
    ]);
```
or if I run dump-autoload -i it does not help
           
 composer.json looks like this.
         
```
    "autoload": {
        "psr-4": {
            "Generated\\": "src/Generated/",
            "Orm\\": "src/Orm/",
            "Pyz\\": "src/Pyz/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "PyzTest\\": "tests/PyzTest/",
            "Acceptance\\Auth\\": "vendor/spryker/auth/tests/"
        },
        "files": [
            "test-autoload.php"
        ]
    },
```
if I fiddle around with it I get 
```
PHP Fatal error:  Uncaught Error: Call to a member function end() on null in /data/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php:120
```
which is not very informative also

**Comment by samsonasik** [comment]
@vinas8 it seems you removed the comment or github not show here? Could you re-type here? Thank you.

**Comment by samsonasik** [comment]
I am closing it as trait not found means it not autoloaded.

You can configure autoload/bootstrap to ensure trait is loaded.
