### ISSUE TITLE
SimplifyEmptyCheckOnEmptyArrayRector: missing opportunity

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8273]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/2ed50097-eecc-4431-97db-fd4fdd55d096

## Expected Behaviour

```diff
- if (! empty($valueArr)) {
+ if ($valueArr !== []) {
```

**Comment by samsonasik** [comment]
`preg_grep()` can return `array` or `false`, see https://www.php.net/manual/en/function.preg-grep.php so the skip is expected.
