### ISSUE TITLE
DowngradeParameterTypeWideningRector not behaving as expected

### ISSUE THREAD

**Issue by lucatume** [rectorphp/rector#8275]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.5            |
| PHP version | 8.2 |

I'm using the `DOWN_TO_PHP_71` set and am encountering issues with the `Rector\DowngradePhp72\Rector\ClassMethod\DowngradeParameterTypeWideningRector` rule.
Specifically, it ignores the configuration and applies the rule when I would not expect it to.
I'm not excluding I might be at fault here and missing how the rule should be configured.

## Minimal PHP Code Causing Issue

[Here I'm excluding the `Acme\Application\Command` class only.](https://getrector.com/demo/a247e0ca-82ee-44ca-8224-1d7d580d3f3d)
[Here I'm excluding both classes being targeted.](https://getrector.com/demo/664ec69b-8e64-4353-96ce-e6bf59f0867a)

## Expected Behaviour

I would expect Rector to skip the `Acme\Application\Command::execute` method as instructed by the configuration unless I do not understand the configuration.
I've tried to go through the code with XDebug to understand where the issue might lie, and it seems to lie [at this line](https://github.com/rectorphp/rector-downgrade-php/blob/2d20783f344dec1895e19d2797d4c3b903b4f3cb/rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php#L176); with my understanding being that "the method should be skipped if the type is not safe (to widen)"; changing the line to `return !$this->isSafeType($classReflection, $classMethod);` "fixes" the issue in my understanding of how the rule configuration should work.

Thank you for your work.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
@TomasVotruba it can't use `Create a Test` button since configuration skip with exact usage need to be provided in config test, so create a pull request with hand is needed

**Comment by samsonasik** [comment]
I am going to close it due lack of feedback.

For maintain perspective, php 7.1 support parameter type widening is hard with including skipping some of area, due to parent-child-trait comparison, my suggestion is bump your requirement to php 7.2, and latest composer itself require php 7.2.

However, feel free to create a failing fixture (and possible patch) to rector-downgrade-php repo when you have a chance.

Thank you for understanding.

**Comment by lucatume** [comment]
Thanks for your work and attention.
I've worked around the issue by rearranging the code to be refactored.
My use case does not allow me to drop PHP 7.1 support, but Rector is still making the work much easier.
