### ISSUE TITLE
ArraySpreadInsteadOfArrayMergeRector will make code performance slower

### ISSUE THREAD

**Issue by Yurunsoft** [rectorphp/rector#8276]
# Question

https://3v4l.org/2dGV8

Test code:

```php
<?php

declare(strict_types=1);

$arr1 = range(1, 100);
$arr2 = range(100, 200);

$time = microtime(true);
for ($i = 0; $i < 10000; ++$i)
{
    array_merge($arr1, $arr2);
}
var_dump(microtime(true) - $time);

$time = microtime(true);
for ($i = 0; $i < 10000; ++$i)
{
    [...$arr1, ...$arr2];
}
var_dump(microtime(true) - $time);
```

**Comment by samsonasik** [comment]
It seems not if using latest php master branch https://3v4l.org/2dGV8#vgit.master you can click after choose master branch.

On real world usage, that seems not really matter.

You can skip the rule by `$rectorConfig->skip()` if you don't want apply it.
