### ISSUE TITLE
Incorrect behavior of CountArrayToEmptyArrayComparisonRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8278]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/c04fb827-436f-4ad3-a657-8da58d9df6a1

```php
<?php
/**
 * @property Rechnung[]            $Rechnung
 */
class Auftrag 
{
}

class AuftragController
{

    /**
     * @var Auftrag
     */
    protected $auftrag;

    public function detail(): void
    {
            if ($this->auftrag->Rechnung && count($this->auftrag->Rechnung) > 0) {

            }
    }
}
```

### Responsible rules

* `CountArrayToEmptyArrayComparisonRector`

## Expected Behavior

`CountArrayToEmptyArrayComparisonRector` should not trust phpdoc

**Comment by staabm** [comment]
I tried reproducing it as a unit test, but did not succeed

**Comment by staabm** [comment]
another repro for the same problem: 

https://getrector.com/demo/83204d1d-f2b2-40d6-b506-2db83fc822ab

**Comment by samsonasik** [comment]
Resolved by https://github.com/rectorphp/rector-src/pull/5203
