### ISSUE TITLE
Incorrect behavior of IssetOnPropertyObjectToPropertyExistsRector

### ISSUE THREAD

**Issue by pedrobrazao** [rectorphp/rector#8280]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.6                                                                                |

## Minimal PHP Code Causing Issue

```php
@@ -4,10 +4,10 @@
 {
     public function run()
     {
-        if (isset($this->property)) {
+        if (property_exists($this, 'property') && $this->property !== null) {
             // do something
         }
-        if (!isset($this->property)) {
+        if (property_exists($this, 'property') && $this->property !== null) {
             // do another thing
         }
     }
```

Applied Rules:

- IssetOnPropertyObjectToPropertyExistsRector

## Expected Behaviour

The first change is correct.

The second chenge should be:

```php
-        if (!isset($this->property)) {
+        if (!property_exists($this, 'property') || $this->property === null) {
```

https://getrector.com/demo/9e386608-a02a-4a54-9854-36d2a0a05482

**Comment by samsonasik** [comment]
It seems due to property not exists, add property that exists will make change to compare null directly

https://getrector.com/demo/dc5b3334-702a-41ae-8d5e-5118cb00959e
