### ISSUE TITLE
Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a refactorWithScope() method of "Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector"

### ISSUE THREAD

**Issue by ToshY** [rectorphp/rector#8281]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `Rector 0.18.6`             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/e26f3815-644e-4f4d-b9d0-eeb5de4810f0

## Expected Behaviour

No error.

**Comment by samsonasik** [comment]
Reproduced with 2 rules: ThrowWithPreviousExceptionRector + OptionalParametersAfterRequiredRector

Ref https://getrector.com/demo/c1550151-fdcb-4870-87e9-ac4faa46e2cf
