### ISSUE TITLE
Incorrect behavior of FinalizeClassesWithoutChildrenRector

### ISSUE THREAD

**Issue by jprangenbergde** [rectorphp/rector#8283]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/095e913e-f92c-4174-81a4-06882790f2ea

```php
<?php

#[AutoWire]
class LeadConfirmationStatusFetcherService implements LeadConfirmationStatusFetcherInterface
{
    private const DAY_TIME_MINUTES_INTERVAL = 30;

    private const NIGHT_TIME_MINUTES_INTERVAL = 120;

    public function __construct(
        private readonly Clock $clock,
    ) {
    }
    
    public function foo(): void
    {
    }
}
```

### Responsible rules

* `FinalizeClassesWithoutChildrenRector`

## Expected Behavior

It should add final to the class, and do not remove any empty lines.

**Comment by samsonasik** [comment]
The removed line is expected due to reprint as class has attribute, without that, the attribute and final keyword will be on same line.

**Comment by jprangenbergde** [comment]
@samsonasik: 
Yeah, i have seen this in the rector code, but it will remove any empty line in the whole file. Don't think, that this should be correct?

**Comment by samsonasik** [comment]
You can use coding standard tool to resolve that.

For some cases new line after statement handling, that already covered at NewlineAfterStatementRector

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#newlineafterstatementrector

**Comment by samsonasik** [comment]
You need to run rector twice to ensure line is computed correctly for latest print.

If it still, you need to use coding standard tool for your use case then.
