### ISSUE TITLE
Incorrect behavior of TypedPropertyFromColumnTypeRector

### ISSUE THREAD

**Issue by ghispi** [rectorphp/rector#8286]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/5b27f435-f241-42f0-9366-4848cffd35c6

```php
<?php
use Doctrine\ORM\Mapping as ORM;

class Test
{
    #[ORM\Id]
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private $id;
}
```

### Responsible rules

* `TypedPropertyFromColumnTypeRector`

## Expected Behavior

I'd expect not nullable id since default value for the nullable in Column attribute is false.
https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/annotations-reference.html#annref_column

**Comment by samsonasik** [comment]
duplicated with https://github.com/rectorphp/rector/issues/7709 and there is PR for it https://github.com/rectorphp/rector-doctrine/pull/191
