### ISSUE TITLE
Problems/missing rule by downgrading substr if 3rd argument is null

### ISSUE THREAD

**Issue by malteschlueter** [rectorphp/rector#8287]
# Question

I'm currently trying to downgrade Symfony 6.3 for a plugin that should be available in PHP 7.4.

The downgrade is successful, but when I try to run the Symfony console, I get the error `Invalid service id: "App\".`. This is caused by the following line https://github.com/symfony/symfony/blob/5bff8c5d975de8099aec2238282e1f98391faad1/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php#L305. Specifically, the `substr` causes this because a `null` is given as the third parameter. In PHP >=8.0 this doesn't matter, it trims the string correctly. Before PHP 8.0 `substr` will return an empty string if the third parameter is `null`.

https://3v4l.org/KPFXP

My question is, is it possible to create a downgrade rule for this, or is there an easier way to solve this problem?
I've already created some rector rules but this feels very hard, especially as the `null` is only set by a condition.

**Comment by samsonasik** [comment]
what diff before vs after should be applied?

**Comment by malteschlueter** [comment]
https://3v4l.org/CmSUc

[Original](https://github.com/symfony/symfony/blob/5bff8c5d975de8099aec2238282e1f98391faad1/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php#L305): `$class = $namespace.ltrim(str_replace('/', '\\', substr($path, $prefixLen, str_ends_with($path, '.php') ? -4 : null)), '\\');`

After rector: `$class = $namespace.ltrim(str_replace('/', '\\', substr($path, $prefixLen, substr_compare($path, '.php', -strlen('.php')) === 0 ? -4 : null)), '\\');`

Possible solution: `$class = $namespace.ltrim(str_replace('/', '\\', substr($path, $prefixLen, substr_compare($path, '.php', -strlen('.php')) === 0 ? -4 : strlen($path))), '\\');`

**Comment by samsonasik** [comment]
You can use github `diff` for markdown

https://github.com/github-linguist/linguist/discussions/5758

to ease the show the different.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback to avoid keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the rule suggestion :+1: 

Try to keep diffs as simple as possible and using markdown diff syntax, so we can read it easily. Thanks or understanding :+1:
