### ISSUE TITLE
move ArraySpreadInsteadOfArrayMergeRector out of `LevelSetList::UP_TO_PHP_74`

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8292]
`ArraySpreadInsteadOfArrayMergeRector ` is a cosmetic rector, which is not necessary for 7.4 transition.

could it be removed from `LevelSetList::UP_TO_PHP_74`?

my personal feeling is, that it creates code which is less readable then a regular `array_merge()`

**Comment by TomasVotruba** [comment]
I had same experience before as not much added value, but rather confusing when/why is this rule used, so I'm :+1: for this
