### ISSUE TITLE
Incorrect behavior of TypedPropertyFromAssignsRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8296]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/9dae40b0-c632-4c38-a96c-4490c5b54f3c

```php
<?php

final class PaypalRepository
{
    /**
     * @var string
     */
    private $apiUrl;

    public function __construct()
    {
        if (rand(0,1)) {
            $this->apiUrl = 'https://example.com/';
        } else {
            $this->apiUrl = 'https://another.example.com/';
        }
    }
}
```

### Responsible rules

* `TypedPropertyFromAssignsRector`

## Expected Behavior

the created property type should be non-nullable and without a default value

**Comment by samsonasik** [comment]
A service to get type by if else only with same assignment single property seems needed.

For note: the implementation need to be carefully applied, eg, start with only assign 2 times in if and else in whole class inside first level statement of __construct.

I will look into it.

**Comment by TomasVotruba** [comment]
@samsonasik Could you add this one? Should be only simple if/else check, keep it simple

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
I created PR

- https://github.com/rectorphp/rector-src/pull/5314 

for it.

**Comment by staabm** [comment]
thanks
