### ISSUE TITLE
[CodeQuality] Create new rule to narrow duplicated switch cases 

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8298]
## Before

The identical values in switch should be grouped in a row of case:

```php
<?php

switch ($value) {
    case 1:
        echo 1;
        break;
    case 2:
		echo 2;
        break;
    // identical value to case 1
    case 3:
	    echo 1;
        break;
}
```

## After

```php
<?php

switch ($value) {
    case 1:
    case 3:
		echo 1;
        break;
    case 2:
		echo 2;
        break;
}
```

**Comment by TomasVotruba** [comment]
Similar to: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#removeduplicatedcaseinswitchrector

**Comment by TomasVotruba** [comment]
Hi @samsonasik , could you create this rule? It should be a new one or part of the existing

**Comment by samsonasik** [comment]
I will try
