### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector

### ISSUE THREAD

**Issue by olivier1980** [rectorphp/rector#8299]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/24483029-f257-4680-a8e9-0e84c95d5984

```php
<?php

namespace App\Entity\Embeds;

use App\Dossier\DossierFactory;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Embeddable()
 */
class LeningGegevens
{
    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Type("string")
     * @Serializer\Expose())
     * @Serializer\Groups({"create", "outbound", "import_api_mutable", "dossier_dump"})
     *
     * @Assert\Type("string")
     * @Assert\NotBlank()
     */
    private string $leningNummer;
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

Assert should be placed as attribute. Instead, it's being duplicated in the doc block.

The empty line in the doc block that contains just an asterisk seems to be the issue.

**Comment by TomasVotruba** [comment]
We use custom parser based on phpdoc-parser.
To make the conversion seamless, the input has to be valid syntax.

There is an extra `)` closing bracket:

```diff
-* @Serializer\Expose())
+* @Serializer\Expose()
```

See: https://getrector.com/demo/bbd416de-522c-4b54-bbd4-8cdc7c0baea7

Once removed, the conversion is correct. Make sure there is correct amount of brackets before running conversion:
