### ISSUE TITLE
StrContainsRector incorrectly replaces strpos() when $offset is defined

### ISSUE THREAD

**Issue by ikari7789** [rectorphp/rector#8303]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.6             |

## Minimal PHP Code Causing Issue

```php
$haystack = 'aba';
$needle = 'b';
$offset = 0;
while (strpos($haystack, $needle, $offset) !== false) {
    // do some stuff
    $offset++;
}
```

becomes the following, which will result in an endless loop

```php
$haystack = 'aba';
$needle = 'b';
$offset = 0;
while (str_contains($haystack, $needle)) {
    // do some stuff
    $offset++;
}
```

## Expected Behaviour

I think Rector should skip the change if offset is specified. This is a breaking change to the code as it completely erases the variable from being used.

**Comment by samsonasik** [comment]
@ikari7789 could you try provide a patch PR for it?

First, you can add failing fixture at

https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/NotIdentical/StrContainsRector/Fixture

then, provide ensure offset is not dynamic value:

https://github.com/rectorphp/rector-src/blob/caba1a00f6c66fe383ed38624087f6dd527808c6/rules/Php80/Rector/NotIdentical/StrContainsRector.php#L100

you should can verify with something like:

```php
if ($this->exprAnalyzer->isDynamicExpr($secondArg->value)) {
    return null;
}
```

for that

**Comment by ikari7789** [comment]
Will give it a try. Pretty busy this week and not too familiar with the rector codebase. May take me a bit to pick up. Thanks for the pointers!
