### ISSUE TITLE
AssertSameResponseCodeWithDebugContentsRector false positive

### ISSUE THREAD

**Issue by astronom** [rectorphp/rector#8304]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.18.7  |

This rule does not check that it should be Response

```php
$commandTester = new CommandTester($this->command);
$commandTester->execute();

$this->assertSame(64, $commandTester->getStatusCode());
```
Rector will be fix like this 

```diff
+        $this->assertSame(64, $commandTester->getStatusCode(), $commandTester->getContent());
```

## Expected Behaviour

Need to check that it is Response or smth else

**Comment by samsonasik** [comment]
@astronom could you try provide a patch? Using `isObjectType()` check on method call var seems can be used.

Thank you.
