### ISSUE TITLE
Wrong documentation on https://getrector.com/documentation/custom-rule

### ISSUE THREAD

**Issue by lyrixx** [rectorphp/rector#8305]
See https://getrector.com/documentation/custom-rule

there is a bug on the line: `if (! str_starts_with($methodCallName, 'set') {
` (missing `)`)

---

And I have a question, you said it's better to write test. Perfect. But how should I run them?

**Comment by samsonasik** [comment]
Could you provide a patch PR for it at https://github.com/rectorphp/getrector-com/blob/main/resources/docs/custom-rule.md ?

Thank you.

**Comment by lyrixx** [comment]
I don't know how to the fill the test files, and how to run them.  But I would if you tell me :)

**Comment by samsonasik** [comment]
docs seems don't have test there, so just a typo fix PR should work

**Comment by lyrixx** [comment]
It does: 
![image](https://github.com/rectorphp/rector/assets/408368/69e6a054-8c13-4250-8db4-739e9363ab5c)

**Comment by samsonasik** [comment]
I see, you ask about rule itself, if you create custom rule, you can create a test, the example can be something like this

https://github.com/rectorphp/rector-src/tree/main/rules-tests/CodeQuality/Rector/BooleanNot/ReplaceMultipleBooleanNotRector
