### ISSUE TITLE
Incorrect behavior of DisallowedEmptyRuleFixerRector with uninitialized properties

### ISSUE THREAD

**Issue by nerones** [rectorphp/rector#8306]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/7e222012-b871-4e3c-9b05-3a62017753f7

```php
<?php

final class DemoFile
{
    protected string $test;
    
    public function run()
    {
        return empty($this->test);
    }
}
```

### Responsible rules

* `DisallowedEmptyRuleFixerRector`

## Expected Behavior

The code must not change. 

The problem with this rule is that is not safe to compare against an empty string because the property it's not initialized. The empty function will also check for not initialized properties. The same thing will happen with other types.

**Comment by samsonasik** [comment]
`empty()` usage is not recommended on strict usage, see https://phpstan.org/r/e0c34868-f3b5-481d-821e-5499e6d0253d

I think the correct usage is to change with isset early on unitialized property:

```diff
-return empty($this->test);
+return ! isset($this->test) || $this->test === '':
```

**Comment by nerones** [comment]
You are right, what you propose is a better solution.

**Comment by TomasVotruba** [comment]
@samsonasik Could you handle this one? Thanks :+1:

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
Resolved at PR:

- https://github.com/rectorphp/rector-src/pull/5409
