### ISSUE TITLE
Incorrect behavior of NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by aivchen** [rectorphp/rector#8307]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.18.6      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/9659cfbb-7e06-4e76-920b-0f69e392a06a

```php
<?php

preg_match_all('#aaaaaa#', 'foo', $matches);

$match = $matches[1][0]??'';

var_dump(strpos($match, 'bar' ));
```

### Responsible rules

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

Rector should not add string typecast

**Comment by samsonasik** [comment]
`$matches[1][0]` is mixed, so cast to string is expected, see https://phpstan.org/r/580ab9a0-af9f-4164-b6bd-243ae62f4c29

If you're always sure that it got string, you can make `@var` usage for it, see https://getrector.com/demo/5c3f6e53-f0c1-45aa-8daa-45ee7907cbda
