### ISSUE TITLE
Incorrect behavior of LongArrayToShortArrayRector, AssignArrayToStringRector, RemoveExtraParametersRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8308]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/4cdcb23e-bd88-4bf0-8863-2876d9e5f40e

```php
<?php

final class DemoFile
{
    private function doFoo(): void
    {
        $condition = '';
        if (random_int(0,2)) {
            $condition = 'id NOT IN (123)';
        }
        $this->doFoo($condition);

        $condition = [];
        $condition['typ'] = 'select';
        if (random_int(0,1)) {
            $condition[] = 'id NOT IN (456)';
        }
        
        $this->doFoo($condition);
    }
    
    private function doFoo($x) {
        echo $x;
    }

}
```

### Responsible rules

* `LongArrayToShortArrayRector`

* `AssignArrayToStringRector`

* `RemoveExtraParametersRector`

## Expected Behavior

I think we have 2 issues here
- `RemoveExtraParametersRector ` strips a parameter even though it shouldn't
- `AssignArrayToStringRector`  turns a string variable into a array, even though the same named var is used with different types across the method

**Comment by samsonasik** [comment]
There is double `doFoo` definition, so that will error on the first place see https://3v4l.org/pJP2H

The better fixture is this https://getrector.com/demo/8d17d516-dd02-4408-bac7-24818ad9e2ee

**Comment by staabm** [comment]
Great catch. The adjusted fixture also shows the actual bug I saw in our project 🤣
