### ISSUE TITLE
Incorrect behavior of TernaryToNullCoalescingRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8309]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/6129e6f8-3726-4d26-b961-306b42af6be6

```php
<?php

use shop\product\business\ProductFilter;

class ProductController
{
    private function sharedProductFilter(): void
    {
        $page = isset($_REQUEST['page']) ? $_REQUEST['page'] : 1;

        $this->brands = Hersteller::getListForProducts(new \ProductFilter());
    }

}
```

### Responsible rules

* `TernaryToNullCoalescingRector`

## Expected Behavior

the fqcn should not be modified, since it after the change collides with a same named class already imported

**Comment by samsonasik** [comment]
Thank you, it seems only happen on ` TernaryToNullCoalescingRector `, I will look into it.
