### ISSUE TITLE
[PSR-4] Add PSR-0 to PSR-4 

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#831]
- https://laravelshift.com/upgrade-namespace-psr0-psr4
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2491
- https://www.facebook.com/pehapkari/videos/1002545313288246/

**Comment by TomasVotruba** [comment]
Closing as too vague to automate. This is better done manually, with human decission.

See #1170

**Comment by afilina** [comment]
It would be nice to have a rule where you can customize with configuration similar to how composer specifies PSR-0 autoloading: `"Namespace_Prefix_": "folder/"`. I have several thousand files to move and I'm not sure that a regex will cut it.

**Comment by TomasVotruba** [comment]
I use `composer.json` PSR-4 paths, that do the same job. Just setup `composer.json` to paths with desired namespaces and run Rector.

This one: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#normalizenamespacebypsr4composerautoloadfilesystemrector

**Comment by afilina** [comment]
I'm not sure how that solves the PSR-0 problem. This rector only normalizes the namespaces _if those are already defined_.

In almost all of my legacy projects, I have files organized into folders, no namespaces, and classnames are `TomasVotruba_Blog_Post`. I need to inject namespaces, then change the classnames and all references to them. That's what I mean by PSR-0 to PSR-4.

I'll just go ahead and write a rector.

**Comment by TomasVotruba** [comment]
> This rector only normalizes the namespaces if those are already defined.

Not only, it also adds them.

> I have files organized into folders

That's enough. Just setup `composer.json` and let Rector complete the namespaces.

**Comment by afilina** [comment]
meet.afilina.com

**Comment by TomasVotruba** [comment]
Based on our call, this is the rule you need. Is that so?

```diff
<?php

// src/SomeNamespace/SomeClass.php

+namespace App\SomeNamespace;

-class SomeInconsistentNamespace_SomeClass
+class SomeClass
 {
 }
```

```diff
<?php

// src/SomeNamespace/SomeClassFactory.php

+namespace App\SomeNamespace;

-class SomeNamespace_SomeClassFactory
+class SomeClassFactory
 {
     public function create()
 	 {
-        return new SomeInconsistentNamespace_SomeClass();
+        return new \App\SomeNamespace\SomeClass();
     }
 }
```

<br>

To define root namespace, the PSR-4 autoload has to be defined in `composer.json`:

```json
{
	"autoload": {
		"psr-4": {
			"App\\SomeNamespace\\": "src"
    	}
	}
}
```

**Comment by afilina** [comment]
Yes, that's the rule.

**Comment by afilina** [comment]
@TomasVotruba I'm working on it right now. I'll send a PR here once I'm done.

**Comment by TomasVotruba** [comment]
Mostly covered nowadays, see post 

https://tomasvotruba.com/blog/2020/07/06/cleaning-lady-notes-from-class-mess-to-psr4-step-by-step-with-confidence/
