### ISSUE TITLE
System error: "Scope not available on "PhpParser\Node\Expr\ConstFetch" node, but is required by a refactorWithScope() method of "Rector\Php73\Rector\ConstFetch\SensitiveConstantNameRector" rule. Fix scope

### ISSUE THREAD

**Issue by JorickPepin** [rectorphp/rector#8310]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.8             |

Hello, I'm new to Rector and I'm having the same problem as #8247 in an old codebase. I have minimized my file to make a reproducer available below. Thank's.

## Minimal PHP Code Causing Issue

Here is a reproducer for this issue : https://getrector.com/demo/bceda156-67b4-49c7-a8d7-e2126b142ec7

**Comment by samsonasik** [comment]
Reproduced with 2 rules applied:

```
    Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector::class;
    Rector\Php73\Rector\ConstFetch\SensitiveConstantNameRector::class;
```

Ref https://getrector.com/demo/b926c981-ecb6-4b67-9f6e-b792ce6a726f
