### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector, NestedAnnotationToAttributeRector

### ISSUE THREAD

**Issue by derpue** [rectorphp/rector#8315]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/0fe31c58-6813-46e1-8069-e40564d5523d

```php
<?php
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EntityRepository::class)
 * @ORM\Table(name="table_name",
 *     indexes={
 *          @ORM\Index(name="index1", columns={"entityField"}),
 *      })
 */
class Entity
{
    /**
     * This is a description what the property/field does, and thus should be keept
     *
     * This is the long description
     * More Text
     *
     * @ORM\OneToMany(targetEntity=SomeOtherEntity::class, mappedBy="reverseField")
     * 
     * This is another comment, this time below the annotation. May be this comment is 
     * at the wrong place, but shouldn't be deleted
     */
    private $entityField;
}
```

### Responsible rules

* `AnnotationToAttributeRector`

* `NestedAnnotationToAttributeRector`

## Expected Behavior

The Comments below the attribute should not be deleted but keept.

**Comment by samsonasik** [comment]
Comment below annotation seems part of annotation children, so it wiped, my suggestion for now is you can move to above annotation, so it will be kept.

**Comment by samsonasik** [comment]
I am closing it as comment below docblock is belong to docblock, so the removed is expected.
