### ISSUE TITLE
Rector is converting \SoapClient->__soapCall() to \SoapClient->soapCall()

### ISSUE THREAD

**Issue by nuryagdym** [rectorphp/rector#8318]
# Question
Rector is removing `__`.
The following code 
```php
        $client = new \SoapClient($url, $options);
        $result = $client->__soapCall('transaction', ['parameters' => ['request' => $contents]]);
```
is converted to:
```php
        $client = new \SoapClient($url, $options);
        $result = $client->soapCall('transaction', ['parameters' => ['request' => $contents]]);
```

The official PHP doc says that it should be `$client->__soapCall()`
https://www.php.net/manual/en/soapclient.soapcall.php

**Comment by samsonasik** [comment]
Hy, what rule you're used, could you reproduce at https://getrector.com/demo ?

**Comment by nuryagdym** [comment]
```
    $rectorConfig->sets([
        SetList::CODING_STYLE,
    ]);
```
This ruleset was calling, which contains `RemoveDoubleUnderscoreInMethodNameRector` rule. 
But I don't see this rule in this SetList anymore: https://github.com/rectorphp/rector/blob/main/config/set/coding-style.php

I had an older rector version where `SetList::CODING_STYLE` contained `RemoveDoubleUnderscoreInMethodNameRector` rule.

However [ObjectMagicMethods](https://github.com/rectorphp/rector/blob/main/rules/CodingStyle/ValueObject/ObjectMagicMethods.php) still does not contain __soapCall method, maybe it would be good to add it there

**Comment by samsonasik** [comment]
The rule seems no longer exists since May, see 

- https://github.com/rectorphp/rector-src/pull/3765

Please try latest version.
