### ISSUE TITLE
Downgrades: Error may be thrown when a method is inside an `if`, and its downgrade inserts code before it

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#8321]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.10            |

## Minimal PHP Code Causing Issue

This code is in [class `CacheItem` from `symfony/cache`](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Cache/CacheItem.php):

```php
<?php

namespace Symfony\Component\Cache;

final class CacheItem implements ItemInterface
{
    protected mixed $value = null;

    private function unpack(): bool
    {
        $v = $this->value;
        
        if (!\is_array($v) || 1 !== \count($v) || 10 !== \strlen($k = (string) array_key_first($v)) || "\x9D" !== $k[0] || "\0" !== $k[5] || "\x5F" !== $k[9]) {
            return false;
        }

        return true;
    }
}
```

The problem happens when downgrading `array_key_first` (downgrade to PHP 7.2), here:

```php
if (!\is_array($v) || 1 !== \count($v) || 10 !== \strlen($k = (string) array_key_first($v)) || "\x9D" !== $k[0] || "\0" !== $k[5] || "\x5F" !== $k[9]) {
```

The downgraded code will insert the `reset` method before that line:

```php
\reset($v);
if (!\is_array($v) || 1 !== \count($v) || 10 !== \strlen($k = (string) \key($v)) || "\x9d" !== $k[0] || "\x00" !== $k[5] || "_" !== $k[9]) {
    return \false;
}
```

This is a problem because `is_array` is in the same `if` statement as `array_key_first`, to make sure that `$v` is an array (it could also be `null` or a string), however now `reset` appears before `is_array`, throwing an exception when `$v` is not an array.

## Expected Behaviour

This is not just a problem with `array_key_first`, but with any method that inserts a statement before it (certainly it also happens with `array_key_last`).

So the solution must consider all possible cases.

I don't know what the solution is. As a temporary solution for my project, I am first running a custom [rule `ChangeIfOrReturnToEarlyReturnRector`](https://github.com/GatoGraphQL/GatoGraphQL/blob/b5f9188e2b605a19e67dbbb5c2dabf62de7a9509/src/Extensions/Rector/EarlyReturn/Rector/If_/ChangeIfOrReturnToEarlyReturnRector.php) (based on `ChangeOrIfContinueToMultiContinueRector`), that spreads all the statements inside the `if` as independent statements, becoming:

```php
if (!\is_array($v)) {
    return false;
}
if (1 !== \count($v)) {
    return false;
}
if (10 !== \strlen($k = (string) array_key_first($v))) {
    return false;
}
if ("\x9D" !== $k[0]) {
    return false;
}
if ("\0" !== $k[5]) {
    return false;
}
if ("\x5F" !== $k[9]) {
    return false;
}
```

Then, the downgraded code with `reset` will now appear after `is_array`:

```php
if (!\is_array($v)) {
    return \false;
}
if (1 !== \count($v)) {
    return \false;
}
\reset($v);
if (10 !== \strlen($k = (string) \key($v))) {
    return \false;
}
if ("\x9d" !== $k[0]) {
    return \false;
}
if ("\x00" !== $k[5]) {
    return \false;
}
if ("_" !== $k[9]) {
    return \false;
}
```

Thoughts?

**Comment by samsonasik** [comment]
I can see that symfony is going too modern and too cryptic at the same time on using latest php syntax, do you use the symfony/cache class? If not, I think it is fine to just ignore it via `$rectorConfig->skip()`

then you can ignore the syntax error check on downgrade on that part, for example:

https://github.com/rectorphp/rector-src/blob/b5f7a09fde1d6f9a22a877499c878bcdb553854b/.github/workflows/build_scoped_rector.yaml#L76

**Comment by leoloso** [comment]
I do use it (my plugin started throwing an exception), which is why I had to create that rule to find a solution for it. It is now working fine.

However, notice that this same situation could happen again and again. Actually, Symfony didn't update that code in a long time, so I don't know why it was not failing before. I have the impression that `reset` started failing (when it doesn't receive an array) only with one of the latest PHP versions (as that's the only thing that I have upgraded).

So anyway, feel free to close this issue, or to consider if the same error may be happening somewhere else, also in the Rector codebase as you're also downgrading to PHP 7.2.

**Comment by samsonasik** [comment]
I see, how about changing code to like this?

```diff
+if (is_array($v)) {
+    reset($v);
+}
if (!\is_array($v) || 1 !== \count($v) || 10 !== \strlen($k = (string) \key($v)) || "\x9d" !== $k[0] || "\x00" !== $k[5] || "_" !== $k[9]) {
    return \false;
}
```
The issue is probably because the value can be object as well, see on php manual https://www.php.net/manual/en/function.reset.php

so it can cause another bug when passed object instead of array, but not sure what the use case is

**Comment by samsonasik** [comment]
pass object to reset arg seems deprecated on php 8.1 https://3v4l.org/grViW#v8.1.24 , and `array_key_first()` is require array, so it seems add

```php
if (is_array($v)) {
    reset($v);
}
```

will be safer.

**Comment by leoloso** [comment]
Yes, that can work.

I guess you could also ask for `is_object`, to be on the safe side, there is no harm to it:

```php
if (is_array($v) || is_object($v)) {
    reset($v);
}
```

Then, you can do the same solution for `array_key_last`.

Are there cases? Rules that insert some statement before the code? And so, we need to check if that statement happens in an `if` after some other condition?

**Comment by samsonasik** [comment]
That's seems reasonable, but may need check type is not always an array or object, eg: 

```php
! ($type->isArray()->yes() || $type->isObject->yes())
```
