### ISSUE TITLE
Inconsistent class hierarchy refactoring with `OptionalParametersAfterRequiredRector`

### ISSUE THREAD

**Issue by eduard-sukharev** [rectorphp/rector#8322]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.10 |

When rector encounters hierarchy of classes where child class redefines a method to receive one of the parameters as optional (which obviously a bad idea and a rather pungent code smell, but still), it makes the optional parameter last in the child class, but keeps sibling classes and parent class intact, which leads to fatal error.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/96afac7f-bd7f-4809-b1dd-5fed5038fa8d

Here's a [demo repository](https://github.com/eduard-sukharev/rector-bug-report-nullable-argument-order) to showcase the issue.

## Expected Behaviour

Rector should either change the complete code hierarchy, skip the change (with warning), or make the optional parameter non-optional (with warning)

**Comment by samsonasik** [comment]
I think the solution is to remove default parameter value when it is before required field, and parent param doesn't have default value.

**Comment by TomasVotruba** [comment]
Closing as stale to avoid piling possible solved issue. Thanks for understanding 👍
