### ISSUE TITLE
Converting "WordPress" classes to PSR-4 classes

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector#8323]
# Bug Report

It was cancelled in https://github.com/rectorphp/rector/pull/1170
Rector's API changed since that PR!
Please help me rewrite that rule in modern Rector. I have projects with many-many files named `class-foo-lowercase.php`.

## Minimal PHP Code Causing Issue

https://github.com/szepeviktor/psr4-rector

## I need help with

- getting namespace + classname from existing files
- moving/renaming existing class files without content modification to a PSR-4 path

Thank you!

**Comment by TomasVotruba** [comment]
Hi, we no longer handle full file location changes as it was way out of our scope. 
But you can create with simple script with Symfony\Finder, move files around and rename the class value :+1:  We have similar internal tooling for legacy projects.
