### ISSUE TITLE
Ability to choose casing for specific sniffs

### ISSUE THREAD

**Issue by tobeycodes** [rectorphp/rector#8325]
# Feature Request

We use coding style that uses snake case rather than camel case. I prefer camel case but don't have the choice to change this for the project. We have a process where on pre-commit hooks and validation in ci we will run rector, then phpcbf, and then phpcs. The problem is Rector has some renaming rules that I want to enable but they get converted to camelCase. If we change them back to snake case the Rector rules will run again to convert back to camelCase. The rules themselves I would like to use because I think naming variables to match make sense but for now we have to disable them entirely so that rector and phpcs both will pass.

```
RenameVariableToMatchNewTypeRector::class,
RenamePropertyToMatchTypeRector::class,
RenameParamToMatchTypeRector::class,
```

I appreciate this is fairly unique to us but it would be grately useful if there was an option that could be used to say these sniffs will pass with snakecase and not try to alter the code.

**Comment by TomasVotruba** [comment]
Hi, thanks for the proposal. This is rather work for coding style. We're moving away from forcing or changing coding style, as coding standard tools already handle it well :+1: 

The best way to go here would be a custom Rector rule to fit your naming needs.
