### ISSUE TITLE
ParamTypeFromStrictTypedPropertyRector and AddParamTypeFromPropertyTypeRector seems similar, one should be removed

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#8328]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. dev-main (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

Both rules seems equal functionality:

ParamTypeFromStrictTypedPropertyRector:  https://getrector.com/demo/d316c71d-6f95-4454-a1bc-7171a9244b2e
AddParamTypeFromPropertyTypeRector: https://getrector.com/demo/f2361cb4-1bf8-40ba-81a9-9e813bebe8e0

## Expected Behaviour

One of them need to be removed to avoid maintain double similar feature.

**Comment by samsonasik** [comment]
I created PR for it 

- https://github.com/rectorphp/rector-src/pull/5293

**Comment by TomasVotruba** [comment]
Indeed :) :+1:
