### ISSUE TITLE
Incorrect `$ctorargs` added to `PDO::query` override

### ISSUE THREAD

**Issue by xPaw** [rectorphp/rector#8332]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/cca8497c-3bad-4547-92c5-3ffe994415c8

```php
<?php
declare(strict_types=1);

class LoggedPDO extends PDO
{
	public function query( string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs ) : PDOStatement|false
	{
		return parent::query( $query, $fetchMode, ...$fetchModeArgs );
	}
}
```

### Responsible rules

* `AddParamBasedOnParentClassMethodRector`

## Expected Behavior

`$ctorargs` is not in the php stub:
https://github.com/php/php-src/blob/e3de478f66b4d3e76aba92100cd77c4bbde07f78/ext/pdo/pdo_dbh.stub.php#L199-L200

And it doesn't work, because it gets added after the `...` param.

**Comment by samsonasik** [comment]
Duplicated with

- https://github.com/rectorphp/rector/issues/8053

There is draft PR for it:

- https://github.com/rectorphp/rector-src/pull/4492
