### ISSUE TITLE
[TypeDeclaratoin] MergeDateTimePropertyTypeDeclarationRectror

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8338]
During working on @mautic codebase, there came a need for date time interface vs date time types.

I always have to update the property type and remove the docblock manually. Much waste of time on 50+ properties, so we should have a rule for that :slightly_smiling_face: 

```diff
-/**
- * @var DateTimeInterface
- */
-private DateTime $dateTime;
+private DateTimeInterface $dateTime;
```

**Comment by TomasVotruba** [comment]
@samsonasik Could you add such a rule? :pray:

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
Note to myself:

- for protected has parent, ,should be skipped https://3v4l.org/oiq2W
- for protected has child, should be skipped https://3v4l.org/376IU

so I think we can apply on private property for safe implementation.

**Comment by TomasVotruba** [comment]
Yeah, let's start with `private` properties and test in the wild.

**Comment by samsonasik** [comment]
I created PR :

- https://github.com/rectorphp/rector-src/pull/5327

for it.
