### ISSUE TITLE
Question: How do you compile release notes?

### ISSUE THREAD

**Issue by martinssipenko** [rectorphp/rector#8340]
Hi,

I have a question that is not related to Rector itself but more about the release pipeline of Rector. I understand Rector development is being done in https://github.com/rectorphp/rector-src repository through Pull Requests. I also understand that once PR is merged there is [an automation](https://github.com/rectorphp/rector-src/actions/runs/7100770555/job/19327537227) that pushes the tip of main branch or tag to https://github.com/rectorphp/rector repo.

However, I'm unable to figure out how are releases of Rector in https://github.com/rectorphp/rector/releases repo being created. Do you do it manually? Additionally, I'm wondering how are release notes (changelog) in those relases compiled, do you do it manually or there is some script/automation that does it for you?

**Comment by martinssipenko** [comment]
@TomasVotruba maybe you can answer? 🙏

**Comment by TomasVotruba** [comment]
Hey, sure. We just run this script from previous tag hash to current one:
https://github.com/rectorphp/rector-src/blob/main/bin/generate-changelog.php

Inspired by PHPStan :+1:
