### ISSUE TITLE
Incorrect behavior of WhileEachToForeachRector

### ISSUE THREAD

**Issue by gitgitypete** [rectorphp/rector#8342]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/b6ce1777-6f67-474c-9be0-1e3c70a257eb

```php
<?php
reset($members);
while (list($key, $val) = each($members))
{
?>
      <tr>
        <td width="50%" align="center"><?php echo $key?></td>
        <td width="50%" align="center"><?php echo $val?></td>
      </tr>

<?php
}
?>
```

### Responsible rules

* `WhileEachToForeachRector`

## Expected Behavior

it adds too many / additional php closing tags

**Comment by samsonasik** [comment]
That's expected, rector can make unexpected output on mixed php+html, see https://github.com/rectorphp/rector#may-cause-unexpected-output-on-file-with-mixed-phphtml-content
