### ISSUE TITLE
Incorrect property type and default value in Doctrine Entity (Symfony)

### ISSUE THREAD

**Issue by jakubostalec** [rectorphp/rector#8343]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.12             |
| Symfony version | 6.3             |
| PHP version | 8.1 -> 8.2             |

Hello, I trying to upgrade my app to php8.2, so I use "UP_TO_PHP_82" set in my project in Symfony 6.3 (php8.1).
Rector are made default values for typed class property for Doctrine entity, which is not compatible with the database (Also i try with some doctrine sets with the same results).

## Minimal PHP Code Causing Issue

```
/** @var string */
#[ORM\Column(type: 'string', nullable: false)]
private $entityProperty;
```
## Current result
```
#[ORM\Column(type: 'string', nullable: false)]
private ?string $entityProperty = null;
```
that causes phpstan error:
`Property Entity::$property type mapping mismatch: property can contain string|null but database expects string.`

## Expected Behaviour

in my opinion in this case, the result should be like below (or not set?):
```
#[ORM\Column(type: 'string', nullable: false)]
private string $entityProperty = '';
```

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by samsonasik** [comment]
That's expected, unless ID that can be dynamic, if not assigned in __construct, it must be nullable.

For note, this duplicated:

https://github.com/rectorphp/rector/issues?q=is%3Aissue+TypedPropertyFromColumnTypeRector+is%3Aclosed

as noted at https://github.com/rectorphp/rector/issues/7709#issuecomment-1378912013

There is already PR for configurable rule for that at:

- https://github.com/rectorphp/rector-doctrine/pull/191
