### ISSUE TITLE
can't set a new parameter to have no default value

### ISSUE THREAD

**Issue by joachim-n** [rectorphp/rector#8350]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |0.18.12            |

## Minimal PHP Code Causing Issue

There doesn't seem to be a way to add a new method or function parameter without a default value. E.g.

```
    $rectorConfig->ruleWithConfiguration(
      ArgumentAdderRector::class,
      [
        new ArgumentAdder(
          $class,
          'addToGeneratorDefinition',
          0,
          'definition',
          NULL,
          new ObjectType(PropertyDefinition::class),
        ),
      ],
    );
```

produces this change:

```
-  public static function addToGeneratorDefinition(): PropertyDefinition {
+  public static function addToGeneratorDefinition(PropertyDefinition $definition = null): PropertyDefinition {
```

If I remove the type and the NULL like this:

```
    $rectorConfig->ruleWithConfiguration(
      ArgumentAdderRector::class,
      [
        new ArgumentAdder(
          $class,
          'addToGeneratorDefinition',
          0,
          'definition',
        ),
      ],
    );
```

 it still gets a default:

```
-  public static function addToGeneratorDefinition(): PropertyDefinition {
+  public static function addToGeneratorDefinition($definition = null): PropertyDefinition {
```

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by joachim-n** [comment]
Done: https://getrector.com/demo/17294f15-9968-450f-ad7f-f443fa4e26c6

**Comment by samsonasik** [comment]
I think to avoid ambiguosity, it need new value object: `ArgumentAdderWithoutDefaultValue`, so it will verify instanceof it, then don't add default value.
