### ISSUE TITLE
Documentation on rules is missing details on how to configure them

### ISSUE THREAD

**Issue by joachim-n** [rectorphp/rector#8352]
The Rules overview section of the online docs at https://getrector.com/documentation/rules-overview points to files in github, e.g. https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md

From there you can see individual rules, e.g. ArgumentAdderRector: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#argumentadderrector

There is sample code that shows *how* the rule will make changes. But there is nothing that shows you how to configure the rule in your rector.php file. There is text that says 'configure it!' but that's not a link, so I don't know what it refers to.

Looking at the source code for this rule -- https://github.com/rectorphp/rector/blob/d2dde21bd9969a48fe419e3ccff1bbcf0c0b08df/rules/Arguments/Rector/ClassMethod/ArgumentAdderRector.php#L96 -- there is a method call that's configuring the rule, but it's not easy to spot, and the absence of code comments means you have to guess what the parameters mean.

**Comment by samsonasik** [comment]
The configure sample in markdown is removed because of buggy, ref https://github.com/rectorphp/rector-doctrine/issues/238#issuecomment-1843041812

**Comment by TomasVotruba** [comment]
Hi, thanks for feedback. We had a configuration examples before, but it lead to miss-understandings, especially in the complex ones. Markdown generator can go wrong very easily.

The code is the documentaiton here. That's why we went with `configure()` method convention. Every configurable rule has such a method, more complex accepting value objects. Those are designed to be explored in the IDE directly while writing rule configuration :+1:

**Comment by joachim-n** [comment]
Code is no substitute for documentation. For example, looking at ArgumentAdder:

```
    public function __construct(string $class, string $method, int $position, ?string $argumentName = null, $argumentDefaultValue = null, ?\PHPStan\Type\Type $argumentType = null, ?string $scope = null)
    {
        $this->class = $class;
        $this->method = $method;
        $this->position = $position;
        $this->argumentName = $argumentName;
        $this->argumentDefaultValue = $argumentDefaultValue;
        $this->argumentType = $argumentType;
        $this->scope = $scope;
        RectorAssert::className($class);
    }
```

What does $scope do? What are the possible values?
What do you pass in for $argumentType?
Is $position 0- or 1-indexed?
How do you specify that there is no default value (turns out you can't -- I wasted time on that).
