### ISSUE TITLE
Incorrect behavior of SensitiveConstantNameRector, NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by cchriss11x** [rectorphp/rector#8353]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/54a8b3a7-142c-4484-bed7-b1f8f87b5004

```php
<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

   $temp[minpreis_24pz] = 224;
   $calc_preis = 1000;
   $calc_preisx1 = $calc_preis*100;
   $calc_preis_minimumx1 = $temp[minpreis_24pz]*100;
   $calc_preis = str_replace(".", ",", $calc_preis);
   $calc_preis_minimum = str_replace(".", ",", $temp[minpreis_24pz]);
   
  
        $zeile .= ''.$temp[ean].';';
        $zeile .= '100;';
        $zeile .= ''.$calc_preisx1.';';
        $zeile .= ''.$calc_preis.';';
        $zeile .= 'EUR;';
        $zeile .= '1;';
        $zeile .= ''.$temp[productModel].';';
        $zeile .= ''.$temp[quantity].';';
        $zeile .= ''.$calc_preis_minimumx1.';';
        $zeile .= ''.$calc_preis_minimum.';';
        $zeile .= ''.$shipping_gpr.';';
        
    $ausgabe_datei .= $zeile."\n";
    
    print_r($ausgabe_datei);
    echo "<b>test-added:</b>:".$temp[artnr].$temp[name]."<br />";
    
    
?>
```

### Responsible rules

* `SensitiveConstantNameRector`

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

Actually $temp[minpreis_24pz] = 224; for example $temp['minpreis_24pz'] = 224; - unfortunately he sets $temp[\MINPREIS_24PZ] = 224; a.

Thanks!

**Comment by samsonasik** [comment]
That's expected. I think since constant may be included via "require" somewhere, it just guessing, so skip the rule seems better.

If the usage is always on array, I think regex find and replace in IDE is better solution for you.

phpstan is your friend https://phpstan.org/r/e72b6682-0f08-4701-84e3-843eda2155a9
