### ISSUE TITLE
System error: "Scope not available on "PhpParser\Node\Expr\Array_" node, but is required by a refactorWithScope() method of "Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector

### ISSUE THREAD

**Issue by sanscript** [rectorphp/rector#8355]
[ERROR] Could not process "C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\process\Pipes\AbstractPipes.php"    

         "System error: "Scope not available on "PhpParser\Node\Expr\Array_" node, but is required by a
         refactorWithScope() method of "Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector"    

         #0 C:\xampp\htdocs\crm\vendor\rector\rector\src\Rector\AbstractRector.php(117):
         Rector\Core\Rector\AbstractScopeAwareRector->refactor(Object(PhpParser\Node\Expr\Array_))
         #1 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(113):      
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\Array_))
         #2 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(133):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\BinaryOp\Identical))
         #3 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ElseIf_))
         #4 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):      
         PhpParser\NodeTraverser->traverseArray(Array)
         #5 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
         #6 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):      
         PhpParser\NodeTraverser->traverseArray(Array)
         #7 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #8 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):      
         PhpParser\NodeTraverser->traverseArray(Array)
         #9 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #10 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):     
         PhpParser\NodeTraverser->traverseArray(Array)
         #11 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):     
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #12 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(85):      
         PhpParser\NodeTraverser->traverseArray(Array)
         #13 C:\xampp\htdocs\crm\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(34):
         PhpParser\NodeTraverser->traverse(Array)
         #14 C:\xampp\htdocs\crm\vendor\rector\rector\src\Application\FileProcessor.php(86):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #15 C:\xampp\htdocs\crm\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(159):
         Rector\Core\Application\FileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #16 C:\xampp\htdocs\crm\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(135):
         Rector\Core\Application\ApplicationFileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File) 
         , Object(Rector\Core\ValueObject\Configuration))
         #17 C:\xampp\htdocs\crm\vendor\rector\rector\src\Console\Command\WorkerCommand.php(120):
         Rector\Core\Application\ApplicationFileProcessor->processFiles(Array,
         Object(Rector\Core\ValueObject\Configuration), Object(Closure))
         #18 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):        
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}(Array)
         #19 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(108):
         RectorPrefix202312\Evenement\EventEmitter->emit('data', Array)
         #20 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(38):
         RectorPrefix202312\Clue\React\NDJson\Decoder->handleData(Array)
         #21 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):        
         RectorPrefix202312\Clue\React\NDJson\Decoder->RectorPrefix202312\Clue\React\NDJson\{closure}('{"action":"main. 
         ..')
         #22 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\react\stream\src\Util.php(62):
         RectorPrefix202312\Evenement\EventEmitter->emit('data', Array)
         #23 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):        
         RectorPrefix202312\React\Stream\Util::RectorPrefix202312\React\Stream\{closure}('{"action":"main...')
         #24 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\react\stream\src\DuplexResourceStream.php(154):
         RectorPrefix202312\Evenement\EventEmitter->emit('data', Array)
         #25 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(201):
         RectorPrefix202312\React\Stream\DuplexResourceStream->handleData(Resource id #1927)
         #26 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(173):
         RectorPrefix202312\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #27 C:\xampp\htdocs\crm\vendor\rector\rector\src\Console\Command\WorkerCommand.php(78):
         RectorPrefix202312\React\EventLoop\StreamSelectLoop->run()
         #28 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\console\Command\Command.php(327):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202312\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #29 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\console\Application.php(960):
         RectorPrefix202312\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202312\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #30 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\console\Application.php(333):
         RectorPrefix202312\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202312\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #31 C:\xampp\htdocs\crm\vendor\rector\rector\src\Console\ConsoleApplication.php(53):
         RectorPrefix202312\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202312\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #32 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\console\Application.php(216):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202312\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #33 C:\xampp\htdocs\crm\vendor\rector\rector\bin\rector.php(129):
         RectorPrefix202312\Symfony\Component\Console\Application->run()
         #34 C:\xampp\htdocs\crm\vendor\rector\rector\bin\rector(5): require_once('C:\\xampp\\htdocs...')
         #35 C:\xampp\htdocs\crm\vendor\bin\rector(119): include('C:\\xampp\\htdocs...')
         #36 {main}". On line: 25

**Comment by arnekolja** [comment]
Similar here:

```
Scope not available on "PhpParser\Node\Name\FullyQualified" node with parent node of "PhpParser\Node\Expr\StaticCall", but is required by a refactorWithScope() method of "R  
  ector\Renaming\Rector\Name\RenameClassRector" rule. Fix scope refresh on changed nodes first
```

**Comment by sanscript** [comment]
This error is showing after adding the following rule:

$rectorConfig->sets([
                      SetList::CODE_QUALITY,
       ]);

**Comment by samsonasik** [comment]
We need simple code and config reproducible at https://getrector.com/demo

**Comment by sanscript** [comment]
[ERROR] Could not process "C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\process\Pipes\AbstractPipes.php"    

         "System error: "Scope not available on "PhpParser\Node\Expr\Array_" node, but is required by a
         refactorWithScope() method of "Rector\Php81\Rector\Array_\FirstClassCallableRector" rule. Fix scope refresh on 



         #0 C:\xampp\htdocs\crm\vendor\rector\rector\src\Rector\AbstractRector.php(117):
         Rector\Core\Rector\AbstractScopeAwareRector->refactor(Object(PhpParser\Node\Expr\Array_))
         #1 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(113):      
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\Array_))
         #2 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(133):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\BinaryOp\Identical))
         #3 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ElseIf_))
         #4 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):      
         PhpParser\NodeTraverser->traverseArray(Array)
         #5 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
         #6 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):      
         PhpParser\NodeTraverser->traverseArray(Array)
         #7 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #8 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):      
         PhpParser\NodeTraverser->traverseArray(Array)
         #9 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):      
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #10 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):     
         PhpParser\NodeTraverser->traverseArray(Array)
         #11 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):     
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #12 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(85):      
         PhpParser\NodeTraverser->traverseArray(Array)
         #13 C:\xampp\htdocs\crm\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(34):
         PhpParser\NodeTraverser->traverse(Array)
         #14 C:\xampp\htdocs\crm\vendor\rector\rector\src\Application\FileProcessor.php(86):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #15 C:\xampp\htdocs\crm\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(159):
         Rector\Core\Application\FileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #16 C:\xampp\htdocs\crm\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(135):
         Rector\Core\Application\ApplicationFileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File) 
         , Object(Rector\Core\ValueObject\Configuration))
         #17 C:\xampp\htdocs\crm\vendor\rector\rector\src\Console\Command\WorkerCommand.php(120):
         Rector\Core\Application\ApplicationFileProcessor->processFiles(Array,
         Object(Rector\Core\ValueObject\Configuration), Object(Closure))
         #18 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):        
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}(Array)
         #19 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(108):
         RectorPrefix202312\Evenement\EventEmitter->emit('data', Array)
         #20 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(38):
         RectorPrefix202312\Clue\React\NDJson\Decoder->handleData(Array)
         #21 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):        
         RectorPrefix202312\Clue\React\NDJson\Decoder->RectorPrefix202312\Clue\React\NDJson\{closure}('{"action":"main. 
         ..')
         #22 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\react\stream\src\Util.php(62):
         RectorPrefix202312\Evenement\EventEmitter->emit('data', Array)
         #23 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):        
         RectorPrefix202312\React\Stream\Util::RectorPrefix202312\React\Stream\{closure}('{"action":"main...')
         #24 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\react\stream\src\DuplexResourceStream.php(154):
         RectorPrefix202312\Evenement\EventEmitter->emit('data', Array)
         #25 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(201):
         RectorPrefix202312\React\Stream\DuplexResourceStream->handleData(Resource id #2016)
         #26 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(173):
         RectorPrefix202312\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #27 C:\xampp\htdocs\crm\vendor\rector\rector\src\Console\Command\WorkerCommand.php(78):
         RectorPrefix202312\React\EventLoop\StreamSelectLoop->run()
         #28 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\console\Command\Command.php(327):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202312\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #29 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\console\Application.php(960):
         RectorPrefix202312\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202312\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #30 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\console\Application.php(333):
         RectorPrefix202312\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202312\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #31 C:\xampp\htdocs\crm\vendor\rector\rector\src\Console\ConsoleApplication.php(53):
         RectorPrefix202312\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202312\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #32 C:\xampp\htdocs\crm\vendor\rector\rector\vendor\symfony\console\Application.php(216):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202312\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202312\Symfony\Component\Console\Output\ConsoleOutput))
         #33 C:\xampp\htdocs\crm\vendor\rector\rector\bin\rector.php(129):
         RectorPrefix202312\Symfony\Component\Console\Application->run()
         #34 C:\xampp\htdocs\crm\vendor\rector\rector\bin\rector(5): require_once('C:\\xampp\\htdocs...')
         #35 C:\xampp\htdocs\crm\vendor\bin\rector(119): include('C:\\xampp\\htdocs...')
         #36 {main}". On line: 25

**Comment by samsonasik** [comment]
Error stack trace doesn't help here. You need to give us sample code and config that cause it, otherwise, nothing we can do.

Take your time, and create new issue with simple reproducible code (usually less than 10 lines) and config (usually 1-2 rules).
