### ISSUE TITLE
Wrong variable name replacement for `$this`

### ISSUE THREAD

**Issue by sreichel** [rectorphp/rector#8359]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.12             |
| Rule | RenameForeachValueVariableToMatchExprVariableRector              |

`$this` should be a protected name for this rule.

```
-        foreach ($this as $item) {
-            $resourcesPermissionsArray[$item->getResourceId()] = $item->getPermission();
+        foreach ($this as $thi) {
+            $resourcesPermissionsArray[$thi->getResourceId()] = $thi->getPermission();

```

## Minimal PHP Code Causing Issue

Demo code does not work.

## Expected Behaviour

Skip this.

**Comment by samsonasik** [comment]
Reproduced at https://getrector.com/demo/5867cc59-478e-4912-80a7-a97c27402d26

Could you create a patch for this? Should be add more value to be excluded like in PR:

- https://github.com/rectorphp/rector-src/pull/5294
