### ISSUE TITLE
Enum name in upper snake case instead of upper case [offering to help]

### ISSUE THREAD

**Issue by JoolsMcFly** [rectorphp/rector#8364]
# Feature Request

Hi guys.

I'd lke to contribute to `SpatieEnumClassToEnumRector` to either change the existing or add a configuration switch to choose between converting enum values to uppercase (current) or snake case.

For example if code is `* @method static self needsReview()` then right now it's converted to `case NEEDSREVIEW = 'needsReview';`

If we were to toggle `toSnakeCase` (or `snakeCaseEnum` or something else) switch to `true` then we'd get:
`case NEEDS_REVIEW = 'needsReview';`
which I found more readable (personal taste?).
 
## Diff 
Given the above input then toggling `toSnakeCase` would produce this diff compared to now:
```diff
-case NEEDSREVIEW = 'needsReview';
+case NEEDS_REVIEW = 'needsReview';
```

If we decided to add a switch then I would pass a boolean param to `\Rector\Php81\NodeFactory\EnumFactory::createFromSpatieClass` and change
```php
$enumName = strtoupper($nodeValue->methodName);
```

to something like

```php
$enumName = $toSnakeCase ? $this->toUpperSnakeCase($nodeValue->methodName) : strtoupper($nodeValue->methodName);
```

If I were to just change the existing code then I would just change
```php
$enumName = strtoupper($nodeValue->methodName);
```
to
```php
$enumName = $this->toUpperSnakeCase($nodeValue->methodName);
```

Before I get cracking on it I just wanted to know your opinion on this. 

Thanks!

**Comment by staabm** [comment]
Maybe thats something you CS tool of choice should fix after runnung rector?

**Comment by JoolsMcFly** [comment]
Hi Markus.

Yeah, it's going to be tough after refactoring to know where to insert `_` to split words.

I feel that upper snake case (`NEEDS_REVIEW`) is more readable than joined upper case (`NEEDSREVIEW`) so it could be the default behaviour. On the other hand if we introduced a switch then we'd give users more control on the output.

What do you guys think?

**Comment by TomasVotruba** [comment]
Hi, I think we can make the rule configurable to allow these. Could propose PR with this addition?

**Comment by JoolsMcFly** [comment]
Sure thing, @TomasVotruba. I'd be happy to give it a go in the upcoming weeks.

**Comment by JoolsMcFly** [comment]
Hi.

Took some time today to work on this. I've opened a [draft PR](https://github.com/rectorphp/rector-src/pull/5435).

Could you have a look at it please?

Thanks!

**Comment by JoolsMcFly** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/5435 so I'm closing this issue.
