### ISSUE TITLE
System error: Scope not available on PhpParser\Node\Expr\FuncCall node, but is required by a refactorWithScope() method

### ISSUE THREAD

**Issue by philo23** [rectorphp/rector#8366]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.18.12 |

When I try to process a file that has an exit() before defining a new function and then calling it rector fails with an error. 
It seems to be when rector is generating the diff views from a dry run, but also happens without a dry run.

Also I know this kind of code is very unusual but it is technically valid PHP. I've tried to reduce the example to the smallest possible number of lines that still reproduces it.

Also the exact error when I run Rector told me to also run it with the debug option, so I've attached the file below with the output of that.

Here's the exact error message:
```
Could not process "rector-issue.php" file, due to:
"System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node, but is required by a
refactorWithScope() method of "Rector\Php55\Rector\FuncCall\GetCalledClassToSelfClassRector" rule. Fix scope
refresh on changed nodes first"
Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 25
```

And the full output with the --debug option:
[rector-issue-debug.txt](https://github.com/rectorphp/rector/files/13698224/rector-issue-debug.txt)

## Minimal PHP Code Causing Issue

https://getrector.com/demo/dfd734eb-eec4-4a6a-ba63-578c7669427f

## Expected Behaviour

No error message about PhpParser nodes :)

**Comment by samsonasik** [comment]
Reproduced on single rule https://getrector.com/demo/2dc63d87-3ebf-4bb7-8a55-3a505e2b21ab
