### ISSUE TITLE
Incorrect behavior of DowngradeMatchToSwitchRector

### ISSUE THREAD

**Issue by ian-zunderdorp** [rectorphp/rector#8369]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/11faa533-739c-481c-ae31-dc7504b6f54b

```php
<?php

final class ValueObject
{
    public function __construct(public readonly DemoFile|\stdClass $value) {}
}

final class DemoFile
{
    public function run(bool $param)
    {
        return new ValueObject(
            match ($param) {
                true => new DemoFile(),
                false => new \stdClass(),
            },
        );
    }
}
```

### Responsible rules

* `DowngradeMatchToSwitchRector`

## Expected Behavior

The downgrade result entirely omits the `new ValueObject`, causing invalid behavior. I guess an IIFE would be the best here, e.g.:

```php
return new ValueObject(
  (function($param) {
    switch ($param) {
       case true: return new DemoFile();
       case false: return new \stdClass();
    })($param)
);
```

**Comment by samsonasik** [comment]
I think it should be assigned to variable first before new, then use variable as new arg

**Comment by ian-zunderdorp** [comment]
That's fine too
