### ISSUE TITLE
false positive wordpress noop.php RemoveExtraParametersRector

### ISSUE THREAD

**Issue by chrillep** [rectorphp/rector#8371]
# Question
when running rector in github ci after last update.
rector has started throwing false positives for RemoveExtraParametersRector

it wants to remove all the parameters for methods in noop.php
https://core.trac.wordpress.org/browser/tags/6.4.2/src/wp-admin/includes/noop.php#L18

when it should use
https://core.trac.wordpress.org/browser/tags/6.4.2/src/wp-includes/l10n.php#L399

take _x for example

```
- 'label' => _x('Header', 'acf', 'sage'),
+ 'label' => _x(),
...
Applied rules:
 * RemoveExtraParametersRector (https://www.reddit.com/r/PHP/comments/a1ie7g/is_there_a_linter_for_argumentcounterror_for_php/)
```

**Comment by samsonasik** [comment]
Duplicate with https://github.com/rectorphp/rector/issues/7894

function seems not autoloaded, or too late loaded, you can read the doc for how to solve it https://getrector.com/documentation/static-reflection-and-autoload

**Comment by chrillep** [comment]
> Duplicate with #7894
> 
> function seems not autoloaded, or too late loaded, you can read the doc for how to solve it https://getrector.com/documentation/static-reflection-and-autoload

they are in fact autoloaded

**Comment by chrillep** [comment]
but it is only happening in CI ?

**Comment by chrillep** [comment]
are you saying i should load all the files needed before the autoloading is done ?
for example l10n.php ?

**Comment by samsonasik** [comment]
Yes, functions need to be registered as files in composer, 

https://stackoverflow.com/questions/24171078/composer-psr-how-to-autoload-functions

On rector use case, you can place under autoload-dev

or you can define custom bootstrap for it.

**Comment by chrillep** [comment]
ill try but it still does not explain why it works locally :)

**Comment by chrillep** [comment]
if i get the time ill try and whip up a proof repo. This is really bugging me :)

**Comment by TomasVotruba** [comment]
@chrillep Thanks for provided files. This is really autoload issue with Wordpress, it loads this file first  https://core.trac.wordpress.org/browser/tags/6.4.2/src/wp-admin/includes/noop.php#L18 and then suggests Rector that this method has no arguments.

Not how Rector or PHPStan can be helpful at Wordpress if the autoload is providing false information. Could be dead end by Wordpress design.

Instead I'd suggest to skip rules like `RemoveExtraParametersRector` using `skip()` method in `rector.php`:
https://getrector.com/documentation/ignoring-rules-or-paths

**Comment by chrillep** [comment]
yeah, thank u. I used the RemoveExtraParametersRector class.
But for me and my colleagues, its still a conundrum as to why this works locally 
without RemoveExtraParametersRector and not in the ci.
Seeing as you are the creator of this repo, ill just use the RemoveExtraParametersRector :).

**Comment by TomasVotruba** [comment]
@chrillep That could be caused by autoload order. E.g. I know that Windows, Unix and OSx order same files differently. This is being used by Composer internals and could result in prioritizing one file over another.

**Comment by chrillep** [comment]
Aaah ok . Yeah we use OS X locally. And GitHub Ci is Ubuntu/ linux by default . 

Thank you for the Peace of mind 🙏

**Comment by chrillep** [comment]
@TomasVotruba sry for a late question! Can we exclude just the noop.php file? As i dont like disabling the great fix for all files iaf er font have to. ❤️


In so please provide full Code 😅
