### ISSUE TITLE
Incorrect behavior of RemoveConcatAutocastRector

### ISSUE THREAD

**Issue by JesusValera** [rectorphp/rector#8372]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/3d78e14d-8f0c-41dc-b7c8-1d88c51d282f

```php
<?php

final class DemoFile
{
     /**
     * @param resource $form
     */
    public function print(mixed $form): string
    {
        return '<Some resource:' . (string)$form . '>';
    }
}
```

### Responsible rules

* `RemoveConcatAutocastRector`

## Expected Behavior

It is an edge case, maybe I am wrong but I think Rector should not remove the casting in this case.

In Psalm the same code is working fine: https://psalm.dev/r/04d89a8fa5
In PHPStan both cases are supported: https://phpstan.org/r/4eb8509f-e879-4f2c-9c9f-1064b2d5f655

**Comment by samsonasik** [comment]
concat is always auto-cast, see https://3v4l.org/eWavM

could you add example of invalid use case for it that produce fatal error?

**Comment by JesusValera** [comment]
The error happened in the use case I already posted, but you are right, concat always auto-cast.
The error should be on the Psalm side 😄
