### ISSUE TITLE
Incorrect behavior of TypedPropertyFromStrictConstructorRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8374]
# Bug Report

looks like the `string` property-type inferred in the example is based on phpdocs.
I think the snippet should be skipped as rector should not trust the key/value phpdoc of the `getTokens` method

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/66bc449c-3160-4129-8ba1-e6e3a1378c15

```php
<?php

final class CsrfToken
{
    /**
     * @var string
     */
    private $token;

    /**
     * @var literal-string
     */
    private string $tokenid;

    /**
     * @param literal-string $formIdentifier
     */
    public function __construct(string $formIdentifier)
    {
        $activeTokens = self::getTokens();

        $this->tokenid = $formIdentifier;

        if (array_key_exists($this->tokenid, $activeTokens)) {
            $this->token = $activeTokens[$this->tokenid];
        } else {
            $this->token = $this->generateToken();
        }
    }

    /**
     * @return array<string, string>
     */
    private static function getTokens(): array
    {
        return $_SESSION[self::$sessionName] ?? [];
    }

    private function generateToken(): string
    {
        $randomPseudoBytes = openssl_random_pseudo_bytes(16);

        return bin2hex($randomPseudoBytes);
    }
}
```

### Responsible rules

* `TypedPropertyFromStrictConstructorRector`

**Comment by samsonasik** [comment]
I am not sure if this should be handled as that part of ArrayDimFetch definition, which by lookup of the whole class, should be used, and probably very rare of not follow the definition.

**Comment by staabm** [comment]
I am not sure I got your point.

my thinking was, that `getTokens()` returns a native array and we can't know its key or value types. therefore I think the `$activeTokens[$this->tokenid]` dim fetch returns a `mixed` (in native type world) and therefore we have 2 property assignments in __construct. one with `string` and one with `mixed` which should lead to skipping instead of adding a type.

**Comment by samsonasik** [comment]
The `getTokens()` define `@return array<string, string>` which it return typed array, so, array data should be `string`, yes, that can be wrong, but likely rare imo.

If that not always an array of string, the `$_SESSION[self::$sessionName]` can be not an array as well, so the definition should follow.

**Comment by staabm** [comment]
I think the lesson learned from a year ago was, that phpdoc are oftentimes wrong and we shouldn't trust them?

**Comment by samsonasik** [comment]
I see, but still, an `array<>` and `array{}` something that obvious, define by hand, and less copy paste error i guess, as that check by another assign and definition. 

If the definition is overlapped between property and assignment, phpstan already catch early.

Yes, that's not perfect, but imo, that seems a way to make it typed.

**Comment by samsonasik** [comment]
I am going to close it, the type is obvious looking by the whole class, with if else native data assigned.

PHP Array doesn't have native structured type, and writing correct `array{}` definition is another effort to be correct iterate definition in PHPStan, little wrong and it already catched by PHPStan, that after that, should be followed.
