### ISSUE TITLE
NamedArgumentRector

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#8378]
# Feature Request

`NamedArgumentRector` should analyse method calls whose earlier arguments just pass the defaults, remove them, and replace them with named arguments instead.
 
## Diff 

```diff
-new GuzzleHttp\Psr7\Response(200, [], 'foo')
+new GuzzleHttp\Psr7\Response(body: 'foo')
```

**Comment by TomasVotruba** [comment]
Hi, I think this would be a challange to decide what should be named args and what is explicit value despite the same as default.

Create a custom rule instead.

**Comment by Bilge** [comment]
It isn't difficult at all. All explicit literals that match the default must be removed. That's it. That's the rule.
