### ISSUE TITLE
Incorrect behavior of RemoveDeadConditionAboveReturnRector

### ISSUE THREAD

**Issue by noother** [rectorphp/rector#8381]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/193a2e1e-fd81-4aa9-9f8c-7dca1e538083

```php
<?php
$Entity = new Some\Super\Fancy\Framework\Entity();
saveMyEntity($Entity);

function saveMyEntity($Entity) {
        if($Entity->save()) {
                return true;
        }

        return true;
}
```

Rector changes:
```diff
 saveMyEntity($Entity);
 
 function saveMyEntity($Entity) {
-        if($Entity->save()) {
-                return true;
-        }
-
         return true;
 }
```

### Responsible rules

* `RemoveDeadConditionAboveReturnRector`

## Expected Behavior

Rector should not remove the if() condition containing the ->save() here - This breaks the logic.

Possible solutions:
- Ok solution: Don't remove if() conditions that contain a function call
- Better solution: Don't remove if() conditions that contain a function call that is not read-only-proven (e.g. `if(empty($foo)) { return true; } return true;` could be removed
- Perfect solution: Remove the if(), but transfer the function call outside the if() =>
```php
function saveMyEntity($Entity) {
        $Entity->save();
        return true;
}
```

**Comment by TomasVotruba** [comment]
> Better solution: Don't remove if() conditions that contain a function call that is not read-only-proven (e.g. if(empty($foo)) { return true; } return true; could be removed

I think this would be safest and good enough.
Could you send a failing test fixture?

**Comment by noother** [comment]
I added https://github.com/rectorphp/rector-src/pull/5423

**Comment by TomasVotruba** [comment]
Resolved in https://github.com/rectorphp/rector-src/pull/5424

**Comment by noother** [comment]
Wow - this was fast! Thanks & good job :)
