### ISSUE TITLE
Incorrect behavior of RemoveEmptyClassMethodRector

### ISSUE THREAD

**Issue by noother** [rectorphp/rector#8382]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/3a830c44-9fd0-4625-bb07-5b198cbc6eb5

```php
<?php

class Foo {
	public function bar() {
		$this->gaz();
	}

	private function gaz() {
	}
}

(new Foo())->bar();
```

Rector changes:
```diff
 	public function bar() {
 		$this->gaz();
 	}
-
-	private function gaz() {
-	}
 }
 
 (new Foo())->bar();
```

### Responsible rules

* `RemoveEmptyClassMethodRector`

## Expected Behavior

Rector should not remove the function gaz() which is called in bar() as this leads to a call to undefined method php error.
Or it should remove the $this->gaz() call as well.

This only happens if gaz() is declared private. If it's public or protected, rector doesn't remove it (which is good because it doesn't know if it might be called from somewhere else).

Or maybe I'm missing something and this only works correctly in combination with another rector which removes the $this->gaz() call because it calls an empty function? If so, this should be documented.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by noother** [comment]
I added https://github.com/rectorphp/rector-src/pull/5422

**Comment by TomasVotruba** [comment]
Thank you, I've cherry picked your fixture and added fix :+1:

**Comment by TomasVotruba** [comment]
Wrong issue number, let's reopen :). I'll look into this one soon

**Comment by noother** [comment]
Wow - this was fast! Thanks & good job :)
