### ISSUE TITLE
Cache rebuilding every time there is a change in the rector configuration

### ISSUE THREAD

**Issue by MetalArend** [rectorphp/rector#8383]
# Question

Every time I change something in the rector configuration, the cache is being completely ignored for the next run. Still, the only thing to be found in the cache seems to be file_hash entries, and the files themselves have not changed. Why is the cache being ignored in this case?

**Comment by samsonasik** [comment]
That is expected as for example, eg: you register new rule, other rule(s) can affect it. 

The cache then saved for next run.

**Comment by MetalArend** [comment]
If I have two rector config files, with two completely different configs, and I let them run one after the other, the other one is using the cache completely, even when it should be rescanning for completely different rules/rulesets. In that case, the cache seems to be used in a situation where it is completely wrong to use it.

The way I would expect the cache to work, is to have it keep track of the file_hash of a file, and have to rescan the entire file when the hash changes. And then have a separate per file per rule cache, that keeps track of the rule result for a file. If the file has changed, all rule caches for that file are invalidated. If a rule has been added, or the config of that rule has changed, the rule cache for that file is invalidated.

**Comment by samsonasik** [comment]
You can save cache to different location for each configs, see:

https://github.com/rectorphp/rector/blob/1daa932d00189e5e2b6161f2b5dd30febf49929e/config/config.php#L23-L24

**Comment by MetalArend** [comment]
As I was typing my second message while this question got closed, I think there's more to the cache than "this is expected". It feels like the cache has no real knowledge about the rules at all, am I correct in assuming that?

**Comment by samsonasik** [comment]
See my answer above https://github.com/rectorphp/rector/issues/8383#issuecomment-1874967683

**Comment by MetalArend** [comment]
Yes, I am setting the cache explicitly to the same directory, as it is scanning the same files. But that assumes that the cache is per rule as well, which seems not to be the case, right?

**Comment by samsonasik** [comment]
The rule can affect other rule, and applied files need to be clear once configuration changed.

**Comment by samsonasik** [comment]
If you look at phpstan works, change phpstan config will also clear cache :)
