### ISSUE TITLE
str_starts_with error on php 7.2 with phpstan 1.10.51

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#8387]
PHPStan 1.10.51 seems use own [ondrejmirtes/simple-downgrader](https://github.com/ondrejmirtes/simple-downgrader) that seems some code not downgraded, see

`str_starts_with`  error https://github.com/rectorphp/rector/actions/runs/7415392870/job/20178438892#step:7:9 , cc @ondrejmirtes

**Comment by samsonasik** [comment]
I reported the bug on phpstan itself as it part of phpstan.phar https://github.com/phpstan/phpstan/issues/10375

**Comment by ondrejmirtes** [comment]
Fixed in PHPStan 1.10.52: https://github.com/phpstan/phpstan/releases/tag/1.10.52

**Comment by samsonasik** [comment]
@ondrejmirtes thank you, I will bump phpstan req and verify it

**Comment by samsonasik** [comment]
@ondrejmirtes it seems working ok now, thank you 👍
