### ISSUE TITLE
System error

### ISSUE THREAD

**Issue by facido** [rectorphp/rector#8388]
Hi,

I am getting a system error processing one of my files. Please help!

Configurations: Windows 10 32 bit, PHP 7.4.32

Code processed:

    private function getHeaders(array $headers)
    {
        $str = '';
        foreach ($headers as $key => $value) {
            $str .= "{$key}: {$value}\r\n";     // Error occurs here! (This is line 56 where the error occurs)
        }

        return "--{$this->boundary}\r\n" . trim($str) . "\r\n\r\n";
    }

I am attaching the output file with debug setting on.
[output to report to Github.txt](https://github.com/rectorphp/rector/files/13838207/output.to.report.to.Github.txt)

I am also attaching the source file that was processed and gave the error.
[MultipartStream.zip](https://github.com/rectorphp/rector/files/13838253/MultipartStream.zip)

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by facido** [comment]
Hi,

The isolated failing demo link from https://getrector.com/demo is as follows:
https://getrector.com/demo/aca74932-09f8-4159-bb35-e64c79d9fe61

**Comment by samsonasik** [comment]
Reproduced with single rule: `SimplifyForeachToCoalescingRector` , ref https://getrector.com/demo/6aabe859-7793-4f31-af07-7b713df22b31
