### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector, NestedAnnotationToAttributeRector with @ORM\Index

### ISSUE THREAD

**Issue by gleb-shchavlev** [rectorphp/rector#8392]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/3f73f56d-e8a4-4b95-9b81-9ae841ef665c

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SegmentRepository")
 * @ORM\Table(
 *     name="segments",
 *
 *     indexes={
 *     @ORM\Index(name="sequence", columns={"sequence"}),
 *     @ORM\Index(name="status_channel_started_at", columns={"status", "channel", "started_at"}),
 *     @ORM\Index(name="representation_started_at", columns={"representation", "started_at"}),
 *     @ORM\Index(name="channel_started_at_status_representation_sequence", columns={"channel", "started_at", "status", "representation", "sequence"})
 * },
 *     uniqueConstraints={
 *     @ORM\UniqueConstraint(name="unique_channel_representation_started_at", columns={"channel", "representation", "started_at"})
 * }
 *     )
 */
class Segment
{
}
```

### Responsible rules

* `AnnotationToAttributeRector`

* `NestedAnnotationToAttributeRector`

## Expected Behavior

According to https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/attributes-reference.html#attrref_index we shoud have:
```php
#[ORM\Index(name: "sequence", columns: ["sequence"])]
#[ORM\Index(name: "status_channel_started_at", columns: ["status", "channel", "started_at"])]
#[ORM\Index(name: "representation_started_at", columns: ["representation", "started_at"])]
#[ORM\Index(name: "channel_started_at_status_representation_sequence", columns: ["channel", "started_at", "status", "representation", "sequence"])]

#[ORM\UniqueConstraint(name: "unique_channel_representation_started_at", columns: ["channel", "representation", "started_at"])]
```

**Comment by samsonasik** [comment]
That seems due to space new line before "indexes", I suggest to just remove the space, ref https://getrector.com/demo/8927fdcc-6212-468e-bb07-9a13bd51ec83

**Comment by gleb-shchavlev** [comment]
Thanks, it's working.

Maybe we should leave the issue open to fix the error with the extra line?

**Comment by samsonasik** [comment]
yes 👍

**Comment by TomasVotruba** [comment]
@samsonasik Could you check if we can fix it or its responsibility of phpdoc-parser? If the the first one and easy to fix, lets handle it.

**Comment by samsonasik** [comment]
I will try
