### ISSUE TITLE
upgrading my php to 8.1 in codeigniter3

### ISSUE THREAD

**Issue by Audace-maico** [rectorphp/rector#8394]
[ERROR] Rector\Config\RectorConfig::{closure}(): Argument #1 ($containerConfigurator) must be of type                  
         Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator, Rector\Config\RectorConfig    
         given, called in /var/www/html/lms/vendor/rector/rector/packages/Config/RectorConfig.php on line 204

**Comment by samsonasik** [comment]
We no longer use symfony symfony `ContainerConfigurator`, you probably refer to old reference, you can start with documentation https://getrector.com/documentation

ensure that you configure autoload correctly.
