### ISSUE TITLE
Rector incompatible with PHPstan v1.10.48 or newer version

### ISSUE THREAD

**Issue by Fabricio872** [rectorphp/rector#8398]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.25 |
| PHPstan version | v1.10.48 |

I am using both PHPstan and Rector and after upgrading PHPstan from v1.10.47 to 1.10.48 or newer I am getting this error: 
```
[ERROR] Interface "PHPStan\Type\ExpressionTypeResolverExtension" not found
```

## Minimal PHP Code Causing Issue

sadly I cannot provide runnable code but I have made an repository with minimal configuration to replicate the issue
https://github.com/Fabricio872/rector-error

## Expected Behaviour

code will be checked without an issue

## Actual Behaviour

[ERROR] Interface "PHPStan\Type\ExpressionTypeResolverExtension" not found

**Comment by samsonasik** [comment]
Could you try latest Rector 0.19.0? That should resolve it, ensure update latest phpstan 1.10.55 as well.

**Comment by Fabricio872** [comment]
I am so sorry i didnt noticed I have locked rector updated with "^0.15.0" config it is all good now I am closing the issue
