### ISSUE TITLE
Xdebug has detected a possible infinite loop (on Windows)

### ISSUE THREAD

**Issue by arueckauer** [rectorphp/rector#8400]
# Bug Report

| Subject        | Details |
| :------------- | :------ |
| Rector version | 0.19.0  |

After upgrading a project to PHP 8.2 and `rector/rector` to 0.19.0, rector fails on a specific file with the following error:

```
[ERROR] Could not process ".\backend\Hygraph\Dealer\Mutation\UpsertFactory.php" file, due to:

"System error: "Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of
'256' frames"
```

Rector is invoked with

```powershell
.\vendor\bin\rector process .\backend\Hygraph\Dealer\Mutation\UpsertFactory.php --debug --clear-cache
```

However, if `--xdebug` is used instead of `--debug`, the error is not thrown. The error is not reproducable on WSL.

See the full stack trace in the attachment ([rector-error.txt](https://github.com/rectorphp/rector/files/13916531/rector-error.txt)).

## Minimal PHP Code Causing Issue

Example works on demo. It contains the minimal code and configuration to reproduce it on Windows.

https://getrector.com/demo/18178975-aa7b-49c6-8c69-e1b5dd2490b9

## Expected Behaviour

I'd expect Rector to successfully process the file.

```powershell
 [OK] Rector is done!
```

**Comment by TomasVotruba** [comment]
Thanks for sharing 🙏

Could you narrow down exact rule causing this?

**Comment by arueckauer** [comment]
I'll do my best. Since I have never done this before, is there a good way to go about it or just go through rule by rule in the set?

**Comment by samsonasik** [comment]
you can create github repo with github action running, and register `windows-latest` to `os` config, remove rules half by half from register until found the rule that cause it, so you can define `$rectorConfig->rules()`...

**Comment by TomasVotruba** [comment]
@arueckauer Thank you :+1:  

I do cut rules by half, and taking the half that is breaking. Then repeat until it's breaking. In the end it's 99 % 2-3 rules combined.

I wrote in more detail here: https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by arueckauer** [comment]
Thank you both for the directions.

After creating a [repo](https://github.com/arueckauer/rector-issue-8400) in a minimal configuration to recreate the issue, I noticed the issue is not triggered by a specific rule, but by any active rule.

While failing locally, the workflow run was successfully. The first difference in the environments I checked, was Xdebug. Locally was Xdebug v3.2.2 installed. With an update to Xdebug v3.3.1 the issue is resolved. Previously the project ran on PHP 8.1.24 with Xdebug v3.2.2 and rector showed no issues.

I am not sure, if there are possibly other issues caused by the same error. I let it up to you to decide how you would like to proceed. For me this solves the issue. Thanks!

**Comment by samsonasik** [comment]
@arueckauer thank you, could you try upgrade xdebug locally to 3.3.1 and verify if that solve it, same like in CI?

**Comment by arueckauer** [comment]
Yes, that is what it fixed locally, too. Sorry, if that was not clear from my previous comment.

**Comment by samsonasik** [comment]
Thank you for verify, that seems the Xdebug bug, I am closing it then ;)
