### ISSUE TITLE
Incorrect behavior of SimplifyRegexPatternRector

### ISSUE THREAD

**Issue by gemal** [rectorphp/rector#8402]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/b9c4ad3a-97d7-406c-95d6-a2c7446d6c80

```php
<?php

$purln = preg_replace("/[^[a-zA-Z0-9_]/", "", "test");
```

### Responsible rules

* `SimplifyRegexPatternRector`

## Expected Behavior

it creates invalid code

**Comment by gemal** [comment]
```
-$purln = preg_replace("/[^[a-zA-Z0-9_]/", "", "test");
+$purln = preg_replace("/[^\\w/", "", "test");
```

`$purln = preg_replace("/[^\\w/", "", "test");`
s not valid

**Comment by TomasVotruba** [comment]
Seems legit. Could you send PR with a fix?

**Comment by pkvach** [comment]
Apologies for intervening, but I noticed that the original Regexp is invalid.
There is an extra opening square bracket in it.
`/[^[a-zA-Z0-9_]/`

It was probably intended to be like this:
`/[^a-zA-Z0-9_]/`

So I'm unsure if it's a bug in Rector.

**Comment by samsonasik** [comment]
@pkvach the original regex is correct, see https://3v4l.org/Y881D and https://regex101.com/r/I47eIK/1 . That's strange, but correct.

**Comment by pkvach** [comment]
@samsonasik 
Oh, I see, thank you.
Just noticed it didn't look right. And some Regex validation services are giving an error on it.

And `SimplifyRegexPatternRector` just replaces the pattern it finds in the original Regex.
https://github.com/rectorphp/rector/blob/72af333641496862b164641843693ec5166854fe/rules/CodeQuality/Rector/FuncCall/SimplifyRegexPatternRector.php#L28
