### ISSUE TITLE
Incorrect behavior of AddMethodCallBasedStrictParamTypeRector

### ISSUE THREAD

**Issue by RobertMe** [rectorphp/rector#8406]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.19      |
| Installed as   | composer dependency  |

The `AddMethodCallBasedStrictParamTypeRector` overrides existing parameter type hints, which is rather unexpected. The demo is a bit contrived (because the code actually won't work) but in my actual project I'm seeing the inverse, where a correct typehint is placed, but Rector replaces it with a type hint which wouldn't work (for example I've set `int|object`, and this Rector rule changes it into `string`). Or I've placed a `XInterface` typehint and this rule replaces it with `X` (obviously with `class X implements XInterface`), which is also unexpected (although I also can't cleanly reproduce this in the demo).

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/15976a83-6704-4f94-a61b-7bfccf855c98

```php
<?php
class Foo
{
}

class Bar
{
    private function run()
    {
        $foo = new Foo();
        $this->do($foo);
    }

    private function do(int $foo): void
    {}
}
```

### Responsible rules

* `AddMethodCallBasedStrictParamTypeRector`

## Expected Behavior
No change, there is a typehint, so there is no need to set / replace one. This also is what I believe most rules do, check if a param / property / return type hint is set, and if so just continue to the next param / property / function.

**Comment by RobertMe** [comment]
If accepted as a bug, and the proposed solution is accepted as well, I can also create a PR to fix this :).

**Comment by RobertMe** [comment]
Reproducer for the issue with inheritance I'm seeing: https://getrector.com/demo/f1bf72fb-736a-4f24-9cb9-acd28c0ade86

The `do(FooInterface $foo)` typehint is replaced here. This, most likely, because `FooInterface` doesn't accept a `MockObject` (based on reading the code for the rector there seems to be some logic in "only replace if the set typehint doesn't accept the passed in type), while in reality it would accept it. It obviously would be better for Rector to recognize this (it might do so with `phpstan/phpstan-phpunit` installed / enabled?), but I (also) think that it shouldn't replace typehints, and as stated, I think it doesn't do so for many rules (i.e.: it will leave type hints already in the code, even if they are wrong / lead to bugs).

**Comment by samsonasik** [comment]
I see, if param->type already a `\PhpParser\Node` instance, then it should be skipped. Feel free to create a PR for it 👍

**Comment by RobertMe** [comment]
I'll try to work on this over the weekend, and already had a quick look at the code when I created the ticket. But it seems there is a lot of logic involved to handle the "should param type be updated or not?" (i.e.: is the existing type compatible with the "new" / determined type). Which makes me wonder whether it wasn't intended as a feature to (sometimes) override the param type.

So I already have the basic change including a test written. But I think a lot of the existing code could / should be removed, which is this:
https://github.com/rectorphp/rector-src/blob/76714b95f240409a6fad92725ea19c870ed3ff14/rules/TypeDeclaration/NodeAnalyzer/ClassMethodParamTypeCompleter.php#L108-L132

Haven't tested that yet though (so see what the impact is on existing tests / behavior).

**Comment by samsonasik** [comment]
I see, in that case, that seems need check that existing type is inside narrowed type or its subtype, if that totally different, just skip it.

**Comment by RobertMe** [comment]
Or well, actually, in case of the intersection type I think the "is a" kinda test actually fails 🤔

When I have:
```php
interface FooInterface {}
class Foo implements FooInterface {}
```

Then some param type hinted with `FooInterface` will  always allow a value of type `Foo` (because "Foo is a FooInterface"). So it should / must also allow something which is `Foo&MockObject`, because the additional type doesn't matter. If I would have `class Foo implements FooInterface, MockObject` (/`class Foo extends MockObject implements FooInterface`) then it should (and might already) pass anyway. So when an intersection type is passed and the param type is a normal (singular / non compound) type it is enough to check whether one of the types of the intersection type are allowed by the set typehint.

So in the example where the determined type is `Foo&MockObject` and the actual typehint is `FooInterface` it should check "is a `Foo` allowed to be passed to a `FooInterface` param? Or is a `MockObject` allowed to be passed to a `FooInterface` param?". To which the answer of the first question is "yes", and thus the type shouldn't / mustn't be updated.

**Comment by samsonasik** [comment]
The stub is checked with `class_exists`, so that's seems fine. The fix can be in multiple PR steps, eg:

- first PR: skip totally different current type with narrowed type
- next PR: improve verify unnecessary union
- etc

**Comment by samsonasik** [comment]
Already typed param is now skipped at latest rector/rector:dev-main https://getrector.com/demo/cdd077c2-cdc9-40a3-b65f-5834bdcff7f8

I am closing it, feel free to create PR for another improvement you think it needs.
