### ISSUE TITLE
`StaticCallOnNonStaticToInstanceCallRector` does not replace `parent` calls when it should

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#8408]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.13 |

## Minimal PHP Code Causing Issue

```php
class A {
    public function __construct(
        private readonly UserRoleCollection $roles = new UserRoleCollection(),
    ) {}

    public function getRoleCollection(): UserRoleCollection
    {
        return $this->roles;
    }
}

class B extends A {
    final public function getOwnRoles(): array
    {
        $roles = clone parent::getRoleCollection();

        return $roles->toArray();
    }
}
```

## Expected Behaviour

Rector should understand that `A::getRoleCollection` is **not** a static method and replace the `parent::getRoleCollection()` call in `B` with `$this->getRoleCollection()` accordingly.

**Comment by RobertMe** [comment]
You mean that Rector should simply replace `parent::` with `$this`? That would change the semantics. This as `parent::` is quite explicit in that the _parent_'s class' method must be called. When replacing it with `$this` the "top" level method will be called.

So take this example:
```php
<?php
class A {
    public function __construct(
    ) {}

    public function do(): void
    {
        echo __METHOD__;
    }
}

class B extends A {
    public function runParent(): void
    {
        parent::do();
    }
    
    public function runThis(): void
    {
        $this->do();
    }
    
    public function do(): void
    {
        echo __METHOD__;
    }
}

$b = new B();
$b->runParent();
echo PHP_EOL;
$b->runThis();
```
Which outputs:
```
A::do
B::do
```

I.e.: changing `parent::` to `$this` changes the result / semantics when the method being called is overridden. So if Rector should / will support this it can only do so when the method being called is `final`, as in that case it's known it can't be overridden.

**Comment by samsonasik** [comment]
Using `parent::` is already the correct one, as this is special, `parent::` doesn't mean call "static", it means it call from parent.

I am closing it.
