### ISSUE TITLE
Could not process "/php/flatted.php" file due to System error on ClosureToArrowFunctionRector

### ISSUE THREAD

**Issue by HVSoftware** [rectorphp/rector#8410]
I have handled several code updates with rector. Only i'm getting the following error.

[ERROR] Could not process "/app/node_modules/flatted/php/flatted.php" file, due to:                                    
         "System error: "Cannot rename "/tmp/flatted.phpNOlInC" to "node_modules/flatted/php/flatted.php":              
         rename(/tmp/flatted.phpNOlInC,node_modules/flatted/php/flatted.php): Permission denied" 

We are running Docker containers and I haven't seen this error on other rules. 

I've added the report. 

 [ERROR] Could not process "/app/node_modules/flatted/php/flatted.php" file, due to:                                    
         "System error: "Cannot rename "/tmp/flatted.phpnkfFPA" to "node_modules/flatted/php/flatted.php":              
         rename(/tmp/flatted.phpnkfFPA,node_modules/flatted/php/flatted.php): Permission denied"                        
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/symfony/filesystem/Filesystem.php(593):                                         
         RectorPrefix202308\Symfony\Component\Filesystem\Filesystem->rename('/tmp/flatted.ph...', 'node_modul...',      
         true)                                                                                                          
         #1 vendor/rector/rector/src/PhpParser/Printer/FormatPerservingPrinter.php(48):                                 
         RectorPrefix202308\Symfony\Component\Filesystem\Filesystem->dumpFile('node_modul...', '<?php\n\n/*!\n *        
         I...')                                                                                                         
         #2 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(199):                               
         Rector\Core\PhpParser\Printer\FormatPerservingPrinter->dumpFile('node_modul...', '<?php\n\n/*!\n * I...')      
         #3 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(108):                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->printFile(Object(Rector\Core\ValueObject\Application\F 
         ile), Object(Rector\Core\ValueObject\Configuration))                                                           
         #4 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(167):                                     
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil 
         e), Object(Rector\Core\ValueObject\Configuration))                                                             
         #5 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(140):                                     
         Rector\Core\Application\ApplicationFileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File) 
         , Array, Object(Rector\Core\ValueObject\Configuration))                                                        
         #6 vendor/rector/rector/packages/Parallel/WorkerRunner.php(56):                                                
         Rector\Core\Application\ApplicationFileProcessor->processFiles(Array,                                          
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #7 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                             
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #8 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                         
         RectorPrefix202308\Evenement\EventEmitter->emit('data', Array)                                                 
         #9 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                             
         RectorPrefix202308\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #10 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202308\Evenement\EventEmitter->emit('data', Array)                                                 
         #11 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202308\React\Stream\Util::RectorPrefix202308\React\Stream\{closure}('{"action":"main...')          
         #12 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202308\Evenement\EventEmitter->emit('data', Array)                                                 
         #13 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202308\React\Stream\DuplexResourceStream->handleData(Resource id #2918)                            
         #14 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202308\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #15 vendor/rector/rector/src/Console/Command/WorkerCommand.php(73):                                            
         RectorPrefix202308\React\EventLoop\StreamSelectLoop->run()                                                     
         #16 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202308\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))                          
         #17 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202308\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202308\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))           
         #18 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202308\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202308\Symfony\Component\Console\Input\ArgvInput),                              
         Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #19 vendor/rector/rector/src/Console/ConsoleApplication.php(65):                                               
         RectorPrefix202308\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202308\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))             
         #20 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202308\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202308\Symfony\Component\Console\Output\ConsoleOutput))                               
         #21 vendor/rector/rector/bin/rector.php(132): RectorPrefix202308\Symfony\Component\Console\Application->run()  
         #22 vendor/rector/rector/bin/rector(5): require_once('vendor/rec...')                                          
         #23 vendor/bin/rector(119): include('vendor/rec...')                                                           
         #24 {main}". On line: 283

**Comment by TomasVotruba** [comment]
This will be related to Rector not having write-permission in Docker. 

It's generic problem area with Docker and tools that write the code, so Docker context, not Rector specifically. Look into Docker permission solutions.

**Comment by HVSoftware** [comment]
I ran the following command:
 - docker-compose run --rm php vendor/bin/rector process

I have split the command to handle both our source and tests folder:
 - docker-compose run --rm php vendor/bin/rector process src
 - docker-compose run --rm php vendor/bin/rector process tests

This solved the problem.

**Comment by HVSoftware** [comment]
There was one file - called `flatten.php` - within the `node_modules` folder. So passing the folder to the command iso of handing the whole project is better. 

Love the tool. Looks like this ticket can be closed.
