### ISSUE TITLE
Upgrading to PHP8.3 - lint issue

### ISSUE THREAD

**Issue by priyankaamonker** [rectorphp/rector#8412]
**My code is:**
```
public function __construct()
    {
        try {
            $variable1 = (new siteModel())->getSettingValue('setting_name', 'variable1');
            $this->error = 1;
        } catch (\Throwable) {
            $this->error = 0;
        }

        parent::__construct();
   }
```

**And the error I get when I do git commit is:**
```
employee@mycompany % php -l src/app/csis.php 
PHP Parse error:  syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in src/app/csis.php on line 56

Parse error: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in src/app/csis.php on line 56
Errors parsing src/app/csis.php
employee@mycompany % 
```

**Line 56 is:**
`} catch (\Throwable) { `

I did upgrade from php7.4 to php8.2 using rector. 
Line 56 was: 
} catch (\Throwable th) {

Changed to:
} catch (\Throwable) {

I ran `php -l files` in pre-commit. I want to keep keep php lint ON. 

Could some one help me with this issue?

**Comment by samsonasik** [comment]
You seems have different php version between cli and web, ensure both are php 8.3 ;)

**Comment by priyankaamonker** [comment]
Thank you! Let me check on it.
