### ISSUE TITLE
Rector AnnotationToAttributeRector does nothing at all

### ISSUE THREAD

**Issue by kaktusas2598** [rectorphp/rector#8414]
Hello, I am trying to convert these annotations in my codebase:
```
    /**
     * @Inject
     * @param SiteCreator $siteCreator
     */
    public function setSiteCreator(SiteCreator $siteCreator): void {
        $this->siteCreator = $siteCreator;
    }
```
To use attributes:
```
    #[Inject]   
    public function setSiteCreator(SiteCreator $siteCreator): void {
        $this->siteCreator = $siteCreator;
    }
```
However running rector with this command does absolutely nothing:
``` vendor/bin/rector process application/modules/sites/code/Controller/TagController.php --dry-run --debug -vvv```

I have tried specifying config file explicitily and it makes no difference, even if I remove dry run option it does nothing, here is my rector.php:
```
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Php80\Rector\Class_\AnnotationToAttributeRector;
use Rector\Set\ValueObject\SetList;
use Rector\Doctrine\Set\DoctrineSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/application',
        __DIR__ . '/assets',
        __DIR__ . '/frontend',
        __DIR__ . '/lambda',
        __DIR__ . '/library',
        __DIR__ . '/public',
        __DIR__ . '/tests',
    ]);

    // register a single rule
    $rectorConfig->rule(AnnotationToAttributeRector::class);

    // define sets of rules
    // tried using different sets and it made no difference
    $rectorConfig->sets([
        SetList::PHP_80,
        //SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES,
        //DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
        //DoctrineSetList::GEDMO_ANNOTATIONS_TO_ATTRIBUTES,
        DoctrineSetList::DOCTRINE_ORM_29
    ]);
};
```

In the end I only get ouput saying : "[OK] Rector is done!" and that's it, nothing was done to refactor my controller, any help would be appreciated

**Comment by kaktusas2598** [comment]
Just to add more information I am using Rector version 0.19.1 and latest PHP version 8.3. I installed rector using composer require with --dev flag and I am running this inside Docker container

**Comment by samsonasik** [comment]
There is no configured for `@Inject`, you can add yourself for your needs

https://getrector.com/demo/8457fa36-9970-48e1-8e69-9a6efb04ed14

**Comment by samsonasik** [comment]
closing as answered.

**Comment by kaktusas2598** [comment]
@samsonasik 
Thanks, this does work:
`<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Php80\Rector\Class_\AnnotationToAttributeRector;
use Rector\Php80\ValueObject\AnnotationToAttribute;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig
        ->ruleWithConfiguration(AnnotationToAttributeRector::class, [
            new AnnotationToAttribute('Inject', 'Inject'),
        ]);
};`

But it replaces everything to "#[\Inject]" Instead of just "#[Inject]" any way to remove that backslash?

**Comment by kaktusas2598** [comment]
Also it would be awesome if it added these:
```
 use DI\Attribute\Inject;
 ```
 for every file which has these Inject attributes refactored, is that possible?
