### ISSUE TITLE
documentation site is down

### ISSUE THREAD

**Issue by exts** [rectorphp/rector#8422]
# Bug Report

Documentation site 503 https://getrector.com

## Expected Behaviour

Open the website and it doesn't 503

**Comment by samsonasik** [comment]
Thank you for reporting, I am looking into it.

**Comment by exts** [comment]
It went down about an hour before this ticket was written if it helps you find anything.

**Comment by samsonasik** [comment]
@exts it fixed now, please clear cache and try again.
