### ISSUE TITLE
RenameClassRector doesn't modify Group Use Declarations

### ISSUE THREAD

**Issue by MonkeyMaster** [rectorphp/rector#8426]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.19.2             |

When ClassA is moved to another namespace rector doesn't modify group use containing that class, keeping orphan there. This also prevents it from adding use with new namespace and it replaces all short names of that class to FQN all over the file.

## Minimal PHP Code Causing Issue

```php
use some\namespace\{ClassA, ClassB, ClassC as C};
new ClassA;
```
## Current Behaviour

```php
use some\namespace\{ClassA, ClassB, ClassC as C};
new another\namespace\ClassA;
```

## Expected Behaviour

```php
use some\namespace\{ClassB, ClassC as C};
use another\namespace\ClassA;
new ClassA;
```

Without group uses it works as expected

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by MonkeyMaster** [comment]
> Thank you for your report!
> 
> We'll need an isolated failing demo link from: http://getrector.com/demo, that way we can reproduce the bug.

https://getrector.com/demo/03ca449c-9482-4f6e-bc57-7e704ae63052

**Comment by samsonasik** [comment]
That's expected, we don't modify group use as its too complex to handle, as it conflict with other class inside the group, the target reference classname already replaced with fqcn, that's the goal.

Thank you for understanding.

**Comment by MonkeyMaster** [comment]
Group uses **without aliases** are just compact forms and not too complex:
```php
use some\namespace\ClassA;
use some\namespace\ClassB;
```
```php
use some\namespace\{ClassA, ClassB};
```
Please consider processing this simple case of group uses - we have 6k+ ones in our project

**Comment by samsonasik** [comment]
Rename + auto import is the complex one, and we were dealing with edge cases for that, that's why we don't support group use, as dealing with its Scope.
