### ISSUE TITLE
Moving from PHP 5.6 to 8.1

### ISSUE THREAD

**Issue by LDSTATXPERT** [rectorphp/rector#8428]
Hello  everyone, and particularly those who can help ^^.
I tried to install rector in Windows OS and the following error appears after executing "php vendor\bin\rector init" : "Expected a callable. Got: integer".
Any idea why and how to fix it ?
Many thanks!

**Comment by LDSTATXPERT** [comment]
Thanks samsonasik. The version I installed is 0.19.2.
... and the issue remains unchanged. after following the documentation :(

**Comment by LDSTATXPERT** [comment]
I see a lot of bizarre cascading folder names under my site's: vendor/rector/rector/vendor/rector/.
is it normal?

**Comment by samsonasik** [comment]
That's normal, that's rector packages inside prefixed vendor. You may have different php version, or some invalid config, could you try share a reproduced repo?

**Comment by samsonasik** [comment]
Got integer error can be due to your `rector.php` doen't have `return`, ensure that the configuration is correct. You can take a look at example of `rector.php` on https://getrector.com/demo

If the issue persist, we may need a reproducible repo.

I am closing as answered.
