### ISSUE TITLE
Is there a way to avoid adding type declarations for anonymous functions / callbacks?

### ISSUE THREAD

**Issue by larskoole** [rectorphp/rector#8429]
# Question
Is there a way to avoid adding type declarations to anonymous functions / callbacks?

In the image below I'd like to keep the `handle(): void` change but avoid the `->chunk(100, function (Collection $rules): void` change.

<img width="495" alt="image" src="https://github.com/rectorphp/rector/assets/8629456/b00d4647-20b7-42f7-bf4b-437bba38c8bf">

Is there a configuration I might be missing?

**Comment by samsonasik** [comment]
why you not add `void` return, is the closure return something and rector add void into it?

**Comment by larskoole** [comment]
Adding type declarations to closures is not something we want to adhere to in our code style. While it might be technically correct, for us it adds bloat we'd like to avoid.

**Comment by samsonasik** [comment]
For most usage, that enforce code quality, I think it need to keep add that :). 

Thank you for understanding.
