### ISSUE TITLE
Could not process a file due to System error: Cannot rename

### ISSUE THREAD

**Issue by stein197** [rectorphp/rector#8432]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.19.2 |
| PHP version | 8.2.11 TS |
| System | Windows 11 x64 |

Rector fails to process a task. It cannot write changes to a file. Each time I run `composer exec -- rector process` it gives me the next error message:
```
[ERROR] Could not process "C:\Projects\diinfo\trunk\diService.php" file, due to:

"System error: "Cannot rename "C:\Projects\diinfo\trunk\diS67E3.tmp" to
"C:\Projects\diinfo\trunk\diService.php":
rename(C:\Projects\diinfo\trunk\diS67E3.tmp,C:\Projects\diinfo\trunk\diService.php):
Zugriff verweigert (code: 5)"
Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 286
```

## Minimal PHP Code Causing Issue
**rector.php**
```php
<?php
declare(strict_types=1);

use Rector\Config\RectorConfig;
use Utils\Rector\ReplaceUTF8Functions;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
		__DIR__ . \DIRECTORY_SEPARATOR . 'diService.php'
	]);
	$rectorConfig->rule(ReplaceUTF8Functions::class);;
};
```
**ReplaceUTF8Functions.php**
```php
<?php
namespace Utils\Rector;

use PhpParser\Node;
use PhpParser\Node\Name;
use PhpParser\Node\Expr\FuncCall;
use Rector\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;
use function array_key_exists;

final class ReplaceUTF8Functions extends AbstractRector {

	private const REPLACEMENT = [
		'utf8_decode' => 'utf8ToLatin1',
		'utf8_encode' => 'latin1ToUtf8'
	];

	public function getNodeTypes(): array {
		return [
			FuncCall::class
		];
	}

	/**
	 * @param FuncCall $node
	 * @return null|Node
	 */
	public function refactor(Node $node): ?Node {
		$name = $this->getName($node->name);
		if (!array_key_exists($name, self::REPLACEMENT))
			return null;
		$node->name = new Name(self::REPLACEMENT[$name]);
		return $node;
	}

    public function getRuleDefinition(): RuleDefinition {
		return new RuleDefinition('Ersetzen die utf8_* Funktionen durch andere', [
				new CodeSample(
					'utf8_decode(\'string\')',
					'utf8ToLatin1(\'string\')'
				)
			]
		);
	}
}
```
I've tried:
- to run as administrator
- to run as `vendor\bin\rector process`
- to grant rights to the current user on the file I want to process
- ask on [StackOverflow](https://stackoverflow.com/questions/77885259/php-rector-does-not-work-at-all-because-of-cannot-rename)

## Expected Behaviour
Rector should be able to write it changes to files

**Comment by samsonasik** [comment]
That's look like a permission issue, if you are using powershell, try use cmd or bash for windows,that's known drawback https://github.com/rectorphp/rector#known-drawbacks

Also, ensure you run rector from root directory or try `$rectorConfig->disableParallel()`

**Comment by stein197** [comment]
@samsonasik I've tried to run it in PowerShell (5.x and 7.x), CMD, Git Bash and ConEmu but it does not help. I also tried with `$rectorConfig->disableParallel()`

**Comment by samsonasik** [comment]
that's strange, we need reproducible repo for that, with github action running with `windows-latest` on os definition, something like this PR:

- https://github.com/rectorphp/rector-src/pull/5504/files#diff-95557d53bf91069e59d82b9d8fcfaf52ec84a762858983edd5ef3c9b3e4c8191

**Comment by samsonasik** [comment]
Ok, it possibly a php issue on windows if the target file is being executed with UAC, see issue:

- https://github.com/php/php-src/issues/7910

Could you try another drive? eg: `D:\` ?

**Comment by samsonasik** [comment]
ok, `FormatPerservingPrinter::dump()` is using `Symfony\Component\Filesystem\Filesystem::dumpFile()` which utilize `rename()` from php, 

There is open issue on symfony:

- https://github.com/symfony/symfony/issues/50326

There is draft PR on php-src for it:

- https://github.com/php/php-src/pull/9351

**Comment by samsonasik** [comment]
@stein197 please latest `rector/rector:dev-main` and verify if it now resolved:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

thank you.

**Comment by stein197** [comment]
@samsonasik I've tried the latest changes from the `dev-main` branch and it worked. Thank you!
