### ISSUE TITLE
AnnotationToAttributeRector makes incorrect boolean arg

### ISSUE THREAD

**Issue by texnicii** [rectorphp/rector#8433]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/f7be5a7f-12f4-49f8-9fff-ebc8d79f0baa

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

class TestProjectScriptTask
{
    /**
     * @ORM\Column(type="bigint", nullable="true")
     *
     * @var int
     */
    private int $stop_ts;
}
```

Rector makes `#[ORM\Column(type: 'bigint', nullable: 'true')]` where `nullable: 'true'` is incorrect and must be `nullable: true`.
I guess this behavior so because correct source annotation is `nullable=true`, not `nullable="true"`, but both of syntax available for annotations and for attributes not.

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

`#[ORM\Column(type: 'bigint', nullable: true)]` (without quotes when boolean type expected)

**Comment by samsonasik** [comment]
I think the solution is fix by case, on this case, patch on `Doctrine\ORM\Mapping\Column` only to avoid using "true" as string on purpose.
