### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8437]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

the `@readonly` phpdocs is intermixed with the regular stuff

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/26085255-ba8e-40df-ae5d-33a4ee5b860a

```php
<?php

namespace Fare\Form\Viewmodel;

final class AkFilterFormVM
{
    /**
     * @readonly
     */
    public string $sort;

    /**
     * @readonly
     */
    public string $query;

    /**
     * @readonly
     */
    public string $auftragsart;

    public function __construct(string $sort, string $query, string $auftragsart)
    {
        if (! \in_array($sort, ['akid asc', 'akid desc', 'datum asc', 'datum desc'], true)) {
            $sort = 'akid desc';
        }

        $this->sort = $sort;
        $this->query = $query;
        $this->auftragsart = $auftragsart;
    }
}
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

phpdoc needs to be above the constructor, not in-between the params

**Comment by samsonasik** [comment]
There is no `@param @readonly` usage, as it needs pointed to the specific param, so I think the existing in between params is already correct, see 

between params (no errors): https://phpstan.org/r/8334fb39-ef94-4d27-8b44-2ccffabd29ec 
above constructor (errors): https://phpstan.org/r/969d32b7-43b9-4c7a-9cea-74d0924ff0b1

**Comment by samsonasik** [comment]
I am closing it as between param is already correct, otherwise, transform from `@readonly` to `@property-read type $propertyname` may be needed, even that doesn't trigger error if property value overridden, and that's not of this rule scope.
