### ISSUE TITLE
`and` keyword is misinterpreted

### ISSUE THREAD

**Issue by mcharytoniuk** [rectorphp/rector#8441]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.19.3             |

## Minimal PHP Code Causing Issue

```php
function myFunction(): bool
{
    /**
     * @var bool $isValid
     */
    $isValid = true;

     foreach ([true, false, true] => $item) {
           $isValid = $isValid and otherFunction();
    }

    return $isValid;
}
```

I wanted to use `and` to both go through all the items in the array and keep the `$isValid` variable updated (if any of them is false, then `$isValid` should be false, but the code should go through all of them anyway). Rector hanges the above code to that, which doesn't make sense:

```php
private function myFunction(): bool
{
    /**
     * @var bool $isValid
     */
    $isValid = true;

    foreach ([true, false, true] => $item) {
        if ($isValid = $isValid) {
            otherFunction();
        }
    }

    return $isValid;
}
```

Rules that were triggered on that file:
* `InlineIfToExplicitIfRector`
* `LogicalToBooleanRector`
* `RemoveUnusedPrivateMethodParameterRector`
* `DisallowedEmptyRuleFixerRector`

I think it's the `InlineIfToExplicitIfRector` rule that makes the above change

## Expected Behaviour

Something like this maybe:

```php
function myFunction(): bool
{
    /**
     * @var bool $isValid
     */
    $isValid = true;

     foreach ([true, false, true] => $item) {
           if (false === otherCode()) {
               $isValid = false;
           }
    }

    return $isValid;
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by mcharytoniuk** [comment]
@TomasVotruba here you go:

https://getrector.com/demo/219d9e57-087a-4eec-abd6-f3275ca92c86

It's those rules combined:

```php
use Rector\CodeQuality\Rector\Expression\InlineIfToExplicitIfRector;
use Rector\CodeQuality\Rector\LogicalAnd\LogicalToBooleanRector;
```

```diff
-            $isValid = $isValid and otherFunction();
+            if ($isValid = $isValid) {
+                otherFunction();
+            }
```
