### ISSUE TITLE
Can't configure Rector with Symfony, using latest RectorConfigBuilder

### ISSUE THREAD

**Issue by Perf** [rectorphp/rector#8444]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.19.5             |
| Symfony version | 6.4.2 |
| PHP version | 8.3.1 |

After installation f a Rector, executed `vendor/bin/rector` - it asked to create a config `rector.php` which I accepted.
The file below was generated:

## Minimal PHP Code Causing Issue

```
...
return RectorConfig::configure()
    ->withPaths([
        __DIR__.'/config',
        __DIR__.'/public',
        __DIR__.'/src',
        __DIR__.'/tests',
    ])
    ->withRules([
        InlineConstructorDefaultToPropertyRector::class
    ])
    ->withSets([
        LevelSetList::UP_TO_PHP_83,
    ]);
```

I tried to configure Rector using instructions on https://github.com/rectorphp/rector-symfony?tab=readme-ov-file#configuration
But it's not possible, as `RectorConfigBuilder` doesn't provides methods for configuring of Symfony container, like `symfonyContainerXml` and `symfonyContainerPhp`.

## Expected Behaviour

It should be possible to configure Rector with Symfony, using `RectorConfigBuilder`.

**Comment by samsonasik** [comment]
@Perf could you create a patch PR for it at https://github.com/rectorphp/rector-src/blob/f680a070335ee796de19b25a98c2d4ac172b6fe8/src/Configuration/RectorConfigBuilder.php#L27 , should be add 4 methods:

- withSymfonyContainerXml()
- withSymfonyContainerPhp()
- withSingleton()
- withAlias()

 ? thank you.

**Comment by Perf** [comment]
@samsonasik done!
https://github.com/rectorphp/rector-src/pull/5524

**Comment by TomasVotruba** [comment]
Thanks 👍

What are aliases needed for? `RectorConfigBuilder` should not duplicate full containers features, so we have only relevant methods to autocomplete by IDE.

**Comment by Perf** [comment]
@TomasVotruba, actually, I am not so confident about requested `withSingletons` and `withAliases`.
If these needs to be removed from PR, please let me know.

**Comment by TomasVotruba** [comment]
@Perf  Let's do the 2 Symfony methods at the moment. I'll think about the service-ones later, if really needed.

**Comment by Perf** [comment]
@TomasVotruba done!

**Comment by Perf** [comment]
You are welcome, guys!
Just one question - when it's going to be released?

**Comment by TomasVotruba** [comment]
We're waiting for more bug fixes to collect. 
I think by the end of this week we'll make a release. 

At the moment you can use `dev-main` branch to get early access :wink:
