### ISSUE TITLE
mysql() functions

### ISSUE THREAD

**Issue by Tayouza** [rectorphp/rector#8445]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.19.4

mysql() functions are not being updated to mysqli() or PDO

**Comment by TomasVotruba** [comment]
This set is not part of our code base as it breaking way too often.

You can find result and re-use them ↓
See https://github.com/rectorphp/rector-src/pull/4448
