### ISSUE TITLE
Incorrect behavior of MakeEntityDateTimePropertyDateTimeInterfaceRector

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#8446]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.19.2     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/c1de8a19-85ed-440c-8d10-039dae4df9b9

```php
<?php

/**
 * @final
 */
class VideoCreator
{
    /** @var \DateTime */
    protected $date;
}
```

### Responsible rules

* `MakeEntityDateTimePropertyDateTimeInterfaceRector`

## Expected Behavior

Rector should skip this service, as it is not a declared Doctrine Entity.

**Comment by TomasVotruba** [comment]
Thank you for reporting. I'm looking into this :+1:

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector/issues/8446

**Comment by mvhirsch** [comment]
Thank you very much!

Fixed in https://github.com/rectorphp/rector-doctrine/pull/256
