### ISSUE TITLE
ConvertRenderTemplateShortNotationToBundleSyntaxRector doesn't work with variables

### ISSUE THREAD

**Issue by jackbentley** [rectorphp/rector#8449]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | [2efd56](https://github.com/rectorphp/rector-src/commit/2efd56)             |

## Minimal PHP Code Causing Issue

1. Example of an error when rector is unable to get a value for the variable:

    https://getrector.com/demo/45bbcf19-eb55-41b6-bf1a-dfff90ccb15a

    ```php
    function deferRender($template)
    {
        $this->render($template);
    }
    ```

2. Example of incorrect fix when using a variable:

    https://getrector.com/demo/dafd210e-8b13-4861-a3c8-dcb135d84a43

    ```php
    function indexAction()
    {
        $template = 'appBundle:Landing\Main:index.html.twig';
        $this->render($template);
    }
    ```

### Responsible rules

* `ConvertRenderTemplateShortNotationToBundleSyntaxRector`

## Expected Behaviour

1. No error, no change
2. Change the variable if hard-coded or no change.

**Comment by samsonasik** [comment]
For case 1, yes that should be skipped.

For case 2, you can enable set list dead code to clean the variable value definiton:

https://getrector.com/demo/85ed8f9c-4a63-4d8f-a23a-6982efebe8e3

the variable is unused, just use the value instead.

**Comment by jackbentley** [comment]
Not sure I like the idea of having to enable deadCode for the output not to be silly. However I suppose it's still functional code at the end of the day. Thanks for fixing 1. 😄
