### ISSUE TITLE
Import names combines import aliases

### ISSUE THREAD

**Issue by jackbentley** [rectorphp/rector#8451]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | [f03a6f](https://github.com/rectorphp/rector-src/commit/f03a6f)             |

When enabling `importNames` with imports which are aliased multiple times they get renamed. This never used to happen on `0.18.5`

## Minimal PHP Code Causing Issue

https://getrector.com/demo/3aa5b5c0-08ed-4363-8c7a-8fef84e5cb98

## Expected Behaviour

No changes expected.

**Comment by samsonasik** [comment]
That's expected, aliases is prioritized when exists. You can enable remove unused imports option for clean unused use

https://getrector.com/demo/d0d2de68-f104-47b9-9717-25aa0678e0ac

That's trade off to avoid double loop to verify back and forth it, same class should not redefined multiple times in use statement.
