### ISSUE TITLE
FinalizeTestCaseClassRector  removes newlines

### ISSUE THREAD

**Issue by kamil-tekiela** [rectorphp/rector#8454]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/59c0cc0f-f1dd-493f-acf0-5ab80137c46c

```php
<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;

abstract class AbstractTestCase extends TestCase{}

#[CoversClass(Advisor::class)]
class AdvisorTest extends AbstractTestCase
    
{}
```

### Responsible rules

* `FinalizeTestCaseClassRector`

## Expected Behavior

I expect that the newline is kept. The newline is removed after the attribute.

**Comment by samsonasik** [comment]
Reprint is needed when class has attrGroups, eg:

```php
if ($node->attrGroups !== []) {
    $node->setAttribute(AttributeKey::ORIGINAL_NODE, null);
}

return $node;
```

Could you try provide a patch with include test case? Thank you.
