### ISSUE TITLE
Could not resolve PHP level set list for "80199"

### ISSUE THREAD

**Issue by kamil-tekiela** [rectorphp/rector#8455]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.19.6           |

When using Rector with the default config and the option `->withPhpSets()` to let Rector figure out the PHP version on its own, I get this error:
>[ERROR] Could not resolve PHP level set list for "80199"

```
        "platform": {
            "php": "8.1.99"
        }
```

This is because in composer.json I have 

I would expect Rector to pick PHP 8.1 set.

**Comment by TomasVotruba** [comment]
Thanks for reporting

Fixed inhttps://github.com/rectorphp/rector-src/pull/5555
