### ISSUE TITLE
Unnecessary code removal by the RemoveDeadLoopRector

### ISSUE THREAD

**Issue by SerafimArts** [rectorphp/rector#8458]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.19.6           |

Rector removes calls to arbitrary iterator, which leads to errors.

## Minimal PHP Code Causing Issue

```php
function example(): iterable
{
    yield 'Some significant code execution';
}

$iterator = example();

foreach ($iterator as $_); // Executes important code
```

## Actual Behaviour

```php
function example(): iterable
{
    yield 'Some significant code execution';
}

$iterator = example();

// -  foreach ($iterator as $_);
// Removed by RemoveDeadLoopRector
```

## Expected Behaviour

```php
function example(): iterable
{
    yield 'Some significant code execution';
}

$iterator = example();

foreach ($iterator as $_); // This code is not "dead" and should not be removed
```

**Comment by samsonasik** [comment]
I think for that case, you can skip it, see documentation to skip rule or rule by path https://getrector.com/documentation/ignoring-rules-or-paths

**Comment by SerafimArts** [comment]
I understand, that’s exactly what I did, but "removing dead code" should remove, it seems, dead code.

However, iteration of iterators is not like that, therefore the code does not work correctly and removes code that should not be removed.

**Comment by samsonasik** [comment]
I suggest to refactor the code instead, use proper method to loop with more readable code, patch it will need some token based check for unreasonable reason.

Thank you for understanding.
