### ISSUE TITLE
Class `Rector\RectorGenerator\Exception\ConfigurationException` not found

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#8459]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.19.6 (invoke `vendor/bin/rector --version`)             |

![CleanShot 2024-02-04 at 22 25 54@2x](https://github.com/rectorphp/rector/assets/995707/14200de7-2cd5-45f4-b03c-56090304bfb6)

```
Could not process                                                      
         "/home/runner/work/kanzlei-butler/kanzlei-butler/src/Domain/Value/WlanP
         assword.php" file, due to:                                             
         "System error: "Class                                                  
         "Rector\RectorGenerator\Exception\ConfigurationException" not found"   
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line:
         146
```

## Minimal PHP Code Causing Issue

I cannot reproduce this issue via a minimal reproducer

## Expected Behaviour

No error essage

**Comment by samsonasik** [comment]
Rector Generator seems on require-dev, while it used in various places in the code, I think the `ConfigurationException` should be replaced with `Rector\Exception\Configuration\InvalidConfigurationException`
