### ISSUE TITLE
SetList::PRIVATIZATION overwrites the previously configured paths

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8461]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.19.6 and v0.19.7  |

Using the set `SetList::PRIVATIZATION` will overwrite any previously set paths, resulting in this error:

```
 [ERROR] The given paths do not match any files
```

Stepping through the code, this happens in `RectorConfigBuilder::__invoke()` at the line saying `$rectorConfig->paths($this->paths);`.  This is executed during the import of the privatization set, but at that time `$this->paths` is `[]`.

## Minimal PHP Code Causing Issue

```
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $config): void {
    $config->paths([__DIR__ . '/src']);
    // The following seems to overwrite the paths.  Swapping the two lines makes it work again.
    $config->sets([SetList::PRIVATIZATION]);
};
```

Sorry, I cannot reproduce this with the sandbox.

## Expected Behaviour

The above config should analyze `src/`.

**Comment by samsonasik** [comment]
I confirm the bug, remove `SetList::PRIVATIZATION` somehow make it works if it along with other sets, I will look into it.

**Comment by samsonasik** [comment]
@TomasVotruba I see, the syntax:

```php
RectorConfig::configure()->withRules()
```

in `config/set/privatization.php` is override existing RectorConfig service 

https://github.com/rectorphp/rector/blob/7810dc2e74173949233058eff5f0a6c21cfdeb7e/config/set/privatization.php#L10
