### ISSUE TITLE
The `Rector\Php80\Rector\Class_\AnnotationToAttributeRector` rule requires configuration

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#8462]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.19.7|

```
[ERROR] Could not process "/Users/oskar.stark/dev/datana/**/migrations/Version20210701180837.php" file, due to:
         "System error: "The "Rector\Php80\Rector\Class_\AnnotationToAttributeRector" rule requires configuration."
```

## Minimal PHP Code Causing Issue

Not able to reproduce plus no info in the rules overview HOW to configure the rule

**Comment by samsonasik** [comment]
You can see example at

https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
