### ISSUE TITLE
RemoveAlwaysElseRector creates fatal error

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#8464]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e7e56992-140f-4226-8564-5c90f2a7c59f

```php
<?php

final class DemoFile
{
    public function run(bool $param)
    {
        if ( isset( $_POST['a'] ) ) {
			if ( $param === true ) {
				echo 'hello';
				exit;
			} else {
				// abc
				?>
				<strong><?php echo 'world'; ?>:</strong><?php echo 'acme'; ?>-
				<?php echo 'foo';
			}
		}
    }
}
```

### Responsible rules

* `RemoveAlwaysElseRector`

## Expected Behavior

See https://github.com/rectorphp/rector-src/pull/5564

**Comment by samsonasik** [comment]
That's the drawback of mix php+html. You can skip the rules for mixed php+html.

Thank you for understanding.
