### ISSUE TITLE
CombineIfRector creates fatal error when PHP closing tag at end of if

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#8465]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/6b4b9466-d3fe-449a-a265-5da3f7db4544

```php
<?php

final class DemoFile
{
    public function run(int $param, int $param_two)
    {
        if ($param > 0) {
            if ($param_two > 0) { ?>
                hello
            <?php }
        }
    }
}
```

### Responsible rules

* `CombineIfRector`

## Expected Behavior

https://github.com/rectorphp/rector-src/pull/5565

**Comment by samsonasik** [comment]
Rector is rely on nikic/php-parser, the support should be included there.
