### ISSUE TITLE
Vendor directory detection is too naive

### ISSUE THREAD

**Issue by ikari7789** [rectorphp/rector#8466]
# Feature Request? Maybe a Bug?

Did a search and didn't see anything about this, so just wanted to bring to attention that the current vendor directory detection is a little naive and catches false positives.

Working on a Laravel project, which has the implement where if you're extending a vendored view, you would add it to `resources/views/vendor/<package_name>/view.blade.php`, ([ref](https://laravel.com/docs/10.x/packages#publishing-views)) which the current vendor directory check picks up.

https://github.com/rectorphp/rector-src/blob/9a44c19598a21aff4b6b38f9a0db3b5ca30337c6/src/Application/ApplicationFileProcessor.php#L60-L67

The message itself is a little vague as when I first saw it, I really couldn't understand why it was being displayed. It may be more informative to show the filepath(s) which triggered the message so user has some reference for what is being shown, or if possible just make the check a little more specific (perhaps check for `/vendor/autoload.php` or  maybe `/vendor/composer/` though that still has some level of ambiguity). Maybe the best approach would be being able to specify a project root directory and checking for `vendor` at that root level, but even still could be a bit strange. Not sure.

As is, the message itself could probably be updated to say something like:

```
Rector has detected a "/vendor" directory in your configured paths. If this is Composer's vendor directory,
this is not necessary as it will be autoloaded. Scanning the Composer vendor directory will cause Rector
to run much slower and possibly with errors.

Consider removing "/vendor" from your configured paths and run again.
```

**Comment by samsonasik** [comment]
It may need to substr with `getcwd()` for more precise `vendor/` from root project, could you try provide a PR? Thank you.

**Comment by ikari7789** [comment]
Thanks for the quick PR!
