### ISSUE TITLE
Incorrect behavior of AddMethodCallBasedStrictParamTypeRector, ReturnTypeFromStrictBoolReturnExprRector, ReturnUnionTypeRector

### ISSUE THREAD

**Issue by Pingus74** [rectorphp/rector#8467]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a10d24b4-3e05-411e-b57a-2df5a33252d1

```php
<?php

final class DemoFile
{
    public function run(bool $param)
    {
        if ($this->isTrue($param)) {
            return 5;
        }

        return '10';
    }

    private function isTrue(int $value)
    {
        return $value === true;
    }
}
```

### Responsible rules

* `AddMethodCallBasedStrictParamTypeRector`

* `ReturnTypeFromStrictBoolReturnExprRector`

* `ReturnUnionTypeRector`

**Comment by samsonasik** [comment]
That's expected, 5 is int, '10' is string, union of it become `int|string`
