### ISSUE TITLE
Incorrect behavior of ReturnTypeFromStrictNewArrayRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8469]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/5c7fc4a5-9223-4558-868d-95b133acc6a2

```php
<?php declare(strict_types = 1);

class HelloWorld
{
	private function searchArrayAndGetKeys($searchArray, $searchText)
    {
        $matches = [];
        foreach ($searchArray as $key => $value) {
            if (false !== stripos($value, $searchText)) {
                $matches[] = $key;
            }
        }

        return $matches;
    }
}
```

### Responsible rules

* `ReturnTypeFromStrictNewArrayRector`

## Expected Behavior

I think rector should know that a array-key cannot be mixed but just `int|string`. PHP does not support other array-keys

**Comment by samsonasik** [comment]
That's look like phpstan bug, as I debugged it, the value (which collection of key) is `MixedType`

**Comment by staabm** [comment]
Yeah, I think the problem is, that the type the foreach is running over is not typed `array` and therefore phpstan doesn't narrows it

thanks for looking into it
