### ISSUE TITLE
used import is removed

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8478]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.0.0 (invoke `vendor/bin/rector --version`)             |

since rector is removing the `use` after code transformation phpstan errors will show up which did not before rector changes

## Minimal PHP Code Causing Issue

https://getrector.com/demo/a62e8936-002c-495b-934b-a22bfd432858

## Expected Behaviour

use shot not be removed because used via phpdoc

**Comment by samsonasik** [comment]
That seems due to multiple PhpDocNode, combine multiple into one seems working ok https://getrector.com/demo/7c397759-48f3-423f-bc49-f35e36cdcf14

**Comment by samsonasik** [comment]
`$node->getDocComment()` seems only read last one for multiple docs:

```
PhpParser\Comment\Doc #7672
   text: '/** @var LocationVO|null $testLocation */'
   startLine: 7
   startFilePos: 132
   startTokenPos: 14
   endLine: 7
   endFilePos: 172
   endTokenPos: 14
```

 The solution possibly need to use `$node->getComments()` and loop and combine the `Comment\Doc` on parsing:

```
array (2)
   0 => PhpParser\Comment\Doc #7729
   |  text: '/** @var AppointmentFormVM $vm */'
   |  startLine: 6
   |  startFilePos: 98
   |  startTokenPos: 12
   |  endLine: 6
   |  endFilePos: 130
   |  endTokenPos: 12
   1 => PhpParser\Comment\Doc #7672
   |  text: '/** @var LocationVO|null $testLocation */'
   |  startLine: 7
   |  startFilePos: 132
   |  startTokenPos: 14
   |  endLine: 7
   |  endFilePos: 172
```

**Comment by samsonasik** [comment]
@staabm  I guess new coding-style rule is better to cover this, eg: `CombineMultiCommentDocsRector` so it become combined, so it can be processed correctly, ensure that each stmts/params only have single `Comment\Doc`.

```diff
-/** @var AppointmentFormVM $vm */
-/** @var LocationVO|null $testLocation */
+/** 
+ * @var AppointmentFormVM $vm
+ * @var LocationVO|null $testLocation 
+ */
```

**Comment by staabm** [comment]
> I guess new coding-style rule is better to cover this, eg: `CombineMultiCommentDocsRector` so it become combined, so it can be processed correctly, ensure that each stmts/params only have single `Comment\Doc`.

I am not sure thats helpful for pre-existing code-bases. seems phpstan is able to differentiate those comments, so rector should be able to also support it?

**Comment by samsonasik** [comment]
Not sure, that may require big refactor on PhpDocInfoFactory, then parse and print handle on update/delete partial of it.

Imo, multiple docs should be combined, so it can be precisely get the main doc, and simplify update/add/delete on different rule that touch the node.

**Comment by staabm** [comment]
@kkmuffme could you post a repro example?

**Comment by samsonasik** [comment]
@kkmuffme that's same, the issue is multiple docs in single node, which should be combined imo
