### ISSUE TITLE
Documentation: Clearly and visibly document that rector does not work reliably when PHP closing tags are used anywhere in the file

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#8479]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.0             |

Please clearly document that currently rector does not reliably support files where PHP closing tags are used, except at the end of the file.
Lots of rules create fatal errors in files when you have a PHP closing tag somewhere in a file - which is incredibly common in legacy projects, which psalm is made for.
When reporting these errors it's always only met with https://github.com/rectorphp/rector/issues/8465#issuecomment-1928470384 but there's no mention of this anywhere in the docs - this should be something that's at the forefront, unless you want rector's users to spend hours checking/wasting their time why rector creates fatal errors in various files.

**Comment by TomasVotruba** [comment]
This is documented here: https://github.com/rectorphp/rector#known-drawbacks

The php-parser printer limitations are applied on any tool using it, not just Rector. The linked comment is right, as that's inherited trait. I recommend to promote the issue there, as fixing it would help all tools running on legacy projects.

I personally do not recommend to run any php-parser printer tool on mix of PHP/HTML.
