### ISSUE TITLE
Upgrading from php 5.5 to 8.2 : ERROR

### ISSUE THREAD

**Issue by protestToViolence** [rectorphp/rector#8480]
C:\xampp\htdocs\csms>vendor\bin\rector process --dry-run
use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    // Define paths to your PHP source code
    $parameters->set(Option::PATHS, [
        _DIR_ . '/admin',
    ]);

    // Define sets of rules for PHP version upgrades
    $containerConfigurator->import(SetList::PHP_81);

    // You might want to exclude some directories that do not contain PHP code or should not be modified
    $parameters->set(Option::SKIP, [
        _DIR_ . '/images',
        _DIR_ . '/fonts',
        // any other directories or files to be excluded
    ]);

    // Optionally set file extensions to be included
    $parameters->set(Option::FILE_EXTENSIONS, ['php']);

    // Add any additional Rector rules or configuration here
};

 [ERROR] Expected a callable. Got: integer

**Comment by samsonasik** [comment]
We no longer use symfony `ContainerConfigurator`, it seems you're using very old rector version.

Update to latest rector 1.0.0 and follow documentation https://getrector.com/documentation

**Comment by protestToViolence** [comment]
C:\xampp\htdocs\csms> vendor\bin\rector process --dry-run
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    // Define paths to your PHP source code
    $rectorConfig->paths([
        __DIR__, // Adjust this to target the directories you want
    ]);

    // Define sets of rules for PHP version upgrades
    $rectorConfig->import(SetList::PHP_74);

    // Optionally, set file extensions to be included
    $rectorConfig->fileExtensions(['php']);

    // Add any additional Rector rules or configuration here
};


 [ERROR] Expected a callable. Got: integer

**Comment by protestToViolence** [comment]
I have read the dociumentation but i am getting the error [ERROR] Expected a callable. Got: integer...i am not sure what is wrong i have done...My system is windows and i am trying to upgrade the php legacy code

**Comment by samsonasik** [comment]
It seems you're missing php open tag in your rector.php:

```php
<?php

**Comment by protestToViolence** [comment]
Thank you ..At least that error disappeared..vendor\bin\rector process --dry-run


 [WARNING] Rector is running on your "/vendor" directory. This is not necessary, as Rector access /vendor by composer
                                se Rector tu run much slower and possibly with errors.

           Remove "/vendor" from Rector paths and run again.


    0/5313 [>---------------------------]   0%

**Comment by samsonasik** [comment]
I updated documentation to avoid copy paste and got error happen again 

- https://github.com/rectorphp/getrector-com/pull/2034
