### ISSUE TITLE
LongArrayToShortArrayRector rule drops code formatting

### ISSUE THREAD

**Issue by interduo** [rectorphp/rector#8481]
# Bug Report
Rector v1.0.0 brokes manual code formatting.

## Minimal PHP Code Causing Issue
orginal code:
```
$script_parameters = array(
    'stdout' => 'c',
    'section:' => 's:',
);
```
modified code:
`$script_parameters = ['stdout' => 'c', 'section:' => 's:'];`

## Expected Behaviour
should be modified to state:
```
$script_parameters = [
    'stdout' => 'c',
    'section:' => 's:',
];
```

## Another example
but this:
`$script_parameters = array('from:' => 'f:', 'to:' => 't:', 'customerid:' => null);`

should be modified to:
`$script_parameters = ['from:' => 'f:', 'to:' => 't:', 'customerid:' => null];`

**Comment by samsonasik** [comment]
That's expected, you can use coding-standard for that, answered at https://github.com/rectorphp/rector/issues/8405

**Comment by samsonasik** [comment]
No, the array need to be reprint to get short array. As stated before, you need coding standard tool for that, that exists, eg with ecs as answered in https://github.com/rectorphp/rector/issues/8405#issuecomment-1892802293 you can check enable ecs rule one by one by yourself per your use case.
