### ISSUE TITLE
Exception stop rector:  Scope not available on "PhpParser\Node\Name\FullyQualified" node with parent node of "PhpParser\Node\Stmt\TraitUseAdaptation\Alias"...

### ISSUE THREAD

**Issue by hdietrich-timespin** [rectorphp/rector#8482]
Rector Version: 0.17.0

Firsttime I report the bug to https://github.com/sabbelasichon/typo3-rector/issues/4025
 
Following code:

```
<?php


trait t1
{
    public function do() {
        echo PHP_EOL . 't1 ';
    }
}

trait t2 {
    use t1 {
        t1::do as private t1do;
    }

    public function do() {
        echo PHP_EOL . 't2 ';
        $this->t1do();
    }
}


class c1 {
    use t2 {
        t2::do as private t2do;
    }

    public function do() {
        echo PHP_EOL . 'c1 ';
        $this->t2do();
    }
}


$c1 = new c1();
$c1->do();
```

throw following Error / Exception and stop the rector process 
![grafik](https://github.com/sabbelasichon/typo3-rector/assets/117842214/bf2ae721-e438-4daf-8cb5-351963f7168d)

  [Rector\Core\Exception\ShouldNotHappenException]
  Scope not available on "PhpParser\Node\Name\FullyQualified" node with parent node of "PhpParser\Node\Stmt\TraitUseAdaptation\Alias", but is required by a refactorWithScope() method of "Rector\Renami
  ng\Rector\Name\RenameClassRector" rule. Fix scope refresh on changed nodes first

Exception trace:
  at /www/project1/public/rector/vendor/rector/rector/src/Rector/AbstractScopeAwareRector.php:53
 Rector\Core\Rector\AbstractScopeAwareRector->refactor() at /www/project1/public/rector/vendor/rector/rector/src/Rector/AbstractRector.php:234
 Rector\Core\Rector\AbstractRector->enterNode() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:113
 PhpParser\NodeTraverser->traverseNode() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
 PhpParser\NodeTraverser->traverseNode() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
 PhpParser\NodeTraverser->traverseNode() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
 PhpParser\NodeTraverser->traverseNode() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /www/project1/public/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:85
 PhpParser\NodeTraverser->traverse() at /www/project1/public/rector/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php:42
 Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse() at /www/project1/public/rector/vendor/rector/rector/src/Application/FileProcessor.php:60
 Rector\Core\Application\FileProcessor->refactor() at /www/project1/public/rector/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php:115
 Rector\Core\Application\FileProcessor\PhpFileProcessor->process() at /www/project1/public/rector/vendor/rector/rector/src/Application/ApplicationFileProcessor.php:169
 Rector\Core\Application\ApplicationFileProcessor->processFiles() at /www/project1/public/rector/vendor/rector/rector/src/Application/ApplicationFileProcessor.php:139
 Rector\Core\Application\ApplicationFileProcessor->run() at /www/project1/public/rector/vendor/rector/rector/src/Console/Command/ProcessCommand.php:120
 Rector\Core\Console\Command\ProcessCommand->execute() at /www/project1/public/rector/vendor/rector/rector/vendor/symfony/console/Command/Command.php:325
 RectorPrefix202306\Symfony\Component\Console\Command\Command->run() at /www/project1/public/rector/vendor/rector/rector/vendor/symfony/console/Application.php:944
 RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand() at /www/project1/public/rector/vendor/rector/rector/vendor/symfony/console/Application.php:326
 RectorPrefix202306\Symfony\Component\Console\Application->doRun() at /www/project1/public/rector/vendor/rector/rector/src/Console/ConsoleApplication.php:49
 Rector\Core\Console\ConsoleApplication->doRun() at /www/project1/public/rector/vendor/rector/rector/vendor/symfony/console/Application.php:212
 RectorPrefix202306\Symfony\Component\Console\Application->run() at /www/project1/public/rector/vendor/rector/rector/bin/rector.php:132
 require_once() at /www/project1/public/rector/vendor/rector/rector/bin/rector:4
 include() at /www/project1/public/rector/vendor/bin/rector:115

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--no-progress-bar] [--no-diffs] [--output-format OUTPUT-FORMAT] [--debug] [--memory-limit MEMORY-LIMIT] [--clear-cache] [--port PORT] [--identifier IDENTIFIER] [--] [<source>...]

What can I do?

**Comment by samsonasik** [comment]
Rector already version 1.0.0, we no longer support Rector 0.17, as I see, sabbelasichon/typo3-rector was stick with old rector version due to custom File Processor, which no longer supported by Rector, 

Looking at latest main, it seems @sabbelasichon already upgraded to Rector 1.0.0 https://github.com/sabbelasichon/typo3-rector/commit/24a51eab929c5f8079b22fba5f959b873b0ba017

**Comment by hdietrich-timespin** [comment]
Thanks

I have checked the Problem on the following Demopage for rector: 
https://getrector.com/demo/b39a7020-f672-4fbc-8e4a-c6e98d469a4f 

In the newest Version of Rector the problem is away.
