### ISSUE TITLE
Please add Rule for using !empty() with tenary operator

### ISSUE THREAD

**Issue by interduo** [rectorphp/rector#8483]
# Feature Request
`empty()` test with negation used with tenary operator could be simplified - just change sides and remove negation.
 
## Diff

```diff
-!empty($var) ? $arr['parm1'] : $arr['parm2'];
+empty($var) ? $arr['parm2'] : $arr['parm1'];
```

**Comment by samsonasik** [comment]
There is `SwitchNegatedTernaryRector` rule for that, see https://getrector.com/demo/fdcb6097-5502-4666-b160-e03443527bbd
