### ISSUE TITLE
rector will remove else if, but is not correct

### ISSUE THREAD

**Issue by hdietrich-timespin** [rectorphp/rector#8484]
Rector: 1.0.0

rector will remove **else if($data['filter'] and $data['xls'])** , but is not correct. 

![grafik](https://github.com/rectorphp/rector/assets/117842214/3f48b8ef-90b0-46f2-b6fa-3c2f4bc5029e)

`    
if($data['filter'] and $data['pdf']) {
			
			$data['itemsperpage']=999999;
			$client = $this->clientRepository->findByFilter($data);
			$pdf = $this->clientRepository->makepdf($client);

		}
	    else if($data['filter'] and $data['xls']) {
			
			$data['itemsperpage']=999999;
			$client = $this->clientRepository->findByFilter($data);
			$xls = $this->clientRepository->makexls($client);

	 }`

**Comment by samsonasik** [comment]
Could you create reproducible on https://getrector.com/demo ? thank you.

**Comment by hdietrich-timespin** [comment]
> Could you create reproducible on https://getrector.com/demo ? thank you.

Here is the demo code:  https://getrector.com/demo/c4e3cef2-0f95-4915-8c1a-43c3025388ba

 I is not produceable! if repeat the rector process again on my code and nothing was removed. I dont know, why was changed in my code!
 
 THanks for the Demolink, so i can test if i found other problems.

**Comment by samsonasik** [comment]
that may already resolved in latest dev-main, you can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by hdietrich-timespin** [comment]
It was our problem. We have processed older Code with rector, and so was mixed with older Code changes and changes from rector. Rector is not the problem. 

Thanks for the tool!
