### ISSUE TITLE
example of rector.php config file with all rules and sets included but commented

### ISSUE THREAD

**Issue by interduo** [rectorphp/rector#8487]
# Feature Request
I suggest to make an example of `rector.php` config file with all available rules listed separately and all sets included but commented and make this file available in composer package.

Why this is important? 
1. Because of automation usability "Just uncomment rule one by one".
2. Running rector with oneliner (downloading,configuring,running) on projects.

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion. While this might favor some experienced users, it would discourage first time users.
Running Rector first time with those sets is like upgrading production to latest PHP without any testing locally.

Instead we mention only few rules, to let user discover more as they go.

We added a chapter about this this week: https://getrector.com/documentation/integration-to-new-project

**Comment by interduo** [comment]
> I think that would work 👍 We could add a new parameter to `--all`, to reuse existing convention:
> 
> ```shell
> vendor/bin/rector list-rules --all
> ```

> Could you create a PR to add this to `ListRulesCommand`?

Sorry but not now :( I am new in project, not now. I will send some PR after some recognition in rector codebase, need to settle in for some time.

**Comment by TomasVotruba** [comment]
Sure, no worries. Take your time 😇

**Comment by interduo** [comment]
There is https://github.com/rectorphp/rector/blob/main/templates/rector.php.dist maybe it should contains all rules listed one-by-one?

**Comment by TomasVotruba** [comment]
That would overwhelm user by many rules they don't need. The purpose of this file is to kick off easy config for a newcomer, easy to understand and runnable.
