### ISSUE TITLE
[DX] Accept y[es] and n[o] for initial config generation

### ISSUE THREAD

**Issue by oleg-andreyev** [rectorphp/rector#8488]
# Bug Report

Running rector for the first time. 
I get

`No "rector.php" config found. Should we generate it for you? [yes]:`

If I answer Y or N (used to it) nothing happens, no error, no config.

```
~/Development/failed-messages-bundle bin-tools* ❯ ./bin/rector                                                                                                                                               10:52:15

 No "rector.php" config found. Should we generate it for you? [yes]:
 > y

~/Development/failed-messages-bundle bin-tools* ❯ echo $?                                                                                                                                                    10:52:37
0
```

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.0            |

**Comment by TomasVotruba** [comment]
Hi, thanks for feedback :pray: 

TBH I thought we already had this... 
Fixed in https://github.com/rectorphp/rector-src/pull/5616
