### ISSUE TITLE
RectorConfigBuilder feedback

### ISSUE THREAD

**Issue by integer** [rectorphp/rector#8489]
# Question

Thanks for releasing Rector 1.0.0. I have updated Rector to this version and rewrite our rector config file with RectorConfigBuilder (`RectorConfig::configure()`) and I would like to share my feedback for this new recommended configuration style.

## `->withRules()`

You can call it only once. Later calls overwrite previous rules. It's confusing. Even when `withConfiguredRule` can bee called multiple times.

In our project we have enabled rector rules and our owns. Now we have to add all rules at once and it is little bit less organized.

**Do you plan to enable rules merging for `->withRules()`?**

## `->withSkip()`

Skip can be called also only once. But it accepts two types of parameters. 
Rule with optional paths to files where this rule should be skipped.
```
ReturnTypeFromStrictNewArrayRector::class => [
            __DIR__ . '/../../admin/controllers/BadController.php',
]
```
or path to files to complete ignore.

With previous configuration I have one statement for path and one statement for Rules. Now I have to merge it into one array and it is less organized.

**Do you consider new method `->withSkipPath()` for complete ignore some path which should not be mixed into configuration for skipping rules?**

## Named parametes in `withPreparedSets` and `withImportNames` and others

Named parameters are available from PHP 8.0. Rector requires PHP 7.2+. In article https://getrector.com/documentation/how-to-run-on-php-53 you use PHP 7.2 and in config file is example with named parameter: `->withPhpSets(php53: true)`. This will not work. 
Version for PHP7.2 is `withPhpSets(false, false, false, false, false, false, false, false, false, false, false, false, true)`. Ugh, too many parameters..

**Comment by TomasVotruba** [comment]
Hi,

thanks for honest feedback :+1: 

1) The rules and skips should be merged, indeed. Could you add it via PR?

2) As for named args, you're right. This features makes sense since PHP 8.0. The other option was to have ~20 names methods, but that would clutter config and make it hard to read.  

Getting to PHP 8.0 is a requirement, that can be achives with sets:

```php
->withSets([SetList::PHP_73, SetList::PHP_74, SetList::PHP_80]);
```

The idea behind Rector is to use it to upgrade PHP code to the latest. PHP 8.0 has been around 3,5 years so we assume new users will handle it. Rector should not be used to stay on old PHP version with sligtly better quality.

**Comment by TomasVotruba** [comment]
I'll update the https://getrector.com/documentation/how-to-run-on-php-53 page to reflect your notes, thanks :+1:

**Comment by TomasVotruba** [comment]
> Do you consider new method ->withSkipPath() for complete ignore some path which should not be mixed into configuration for skipping rules?

This sounds like a good improvement. Could you create a PR for this feature?

**Comment by integer** [comment]
Thanks for fast response. I will try to prepare PRs for both features after my working hours.

**Comment by integer** [comment]
If https://github.com/rectorphp/rector-src/pull/5623 will be merged I will prepare new method `->withSkipPath()` as alias for basic `->withSkip()` only with stricter doc type. Are you ok with this implementation?
