### ISSUE TITLE
RemoveAlwaysTrueIfConditionRector remove functional condition

### ISSUE THREAD

**Issue by Oviglo** [rectorphp/rector#8491]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.0.0 (invoke `vendor/bin/rector --version`)             |

Hi, this rule remove a functional condition, Doctrine ArrayCollection contains function not always return "true"

## Minimal PHP Code Causing Issue

![rector_RemoveCondition](https://github.com/rectorphp/rector/assets/4029073/d4937933-7198-40f5-8fa0-f79b9f581eaf)

**Comment by samsonasik** [comment]
I tried to replicate it, it seems can't be reproduced at https://getrector.com/demo/56449110-0b8e-4f1e-b13b-1842b151ccb5

Please try latest version, if the issue persist, please provide reproducible code so it covered.

Thank you.
