### ISSUE TITLE
Error when using PHPStan bleeding edge

### ISSUE THREAD

**Issue by philbates35** [rectorphp/rector#8492]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v.019.2 and v1.0.0            |

It seems that maybe #2431 and #2550 has crept back in again? On my fresh Laravel project, I have opted in to PHPStan bleeding edge by including `vendor/phpstan/phpstan/conf/bleedingEdge.neon` in my `includes`, and then call `$rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon.dist')` in my project, which causes two issues.

### Issue 1

Rector now fails with the following error:

```
Run composer run rector -- --dry-run
> rector process --ansi '--dry-run'

   _PHPStan_11268e5ee\Nette\FileNotFoundException 

  File 'phar://phpstan.phar/conf/bleedingEdge.neon' is missing or is not readable.

  at phar://vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php:29
     25▕      */
     26▕     public function load(string $file, ?bool $merge = \true) : array
     27▕     {
     28▕         if (!\is_file($file) || !\is_readable($file)) {
  ➜  29▕             throw new Nette\FileNotFoundException(\sprintf("File '%s' is missing or is not readable.", $file));
     30▕         }
     31▕         if (isset($this->loadedFiles[$file])) {
     32▕             throw new Nette\InvalidStateException(\sprintf("Recursive included file '%s'", $file));
     33▕         }

      +15 vendor frames 

  16  [internal]:0
      Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory::__construct()
      +25 vendor frames 

  42  [internal]:0
      RectorPrefix202401\Illuminate\Container\Container::RectorPrefix202401\Illuminate\Container\{closure}()
```

### Issue 2

When this error happens, rector must be returning with a 0 exit code, because my GitHub Actions rector job has been silently failing for some time now on every PR even though the job is showing as successful :grimacing: 

## Minimal PHP Code Causing Issue

You can check out an example of the failing job here: https://github.com/philbates35/laravel-starter/actions/runs/7904687577/job/21575586426, that repo is basically a fresh Laravel app with PHPStan, Larastan and rector configured.

## Expected Behaviour

I should be able to use `$rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon.dist')` as well as PHPStan strict mode without error.

**Comment by TomasVotruba** [comment]
Rector does not use bleeding edge and PHPStan rules.
The `phpstan.neon` for Rector should only contains extension that provide types. Some extension also load code and invoke PHPStan internals, that we do not use here.

If that's the case as in your project, the best practise is to create a custom `phpstan.neon` only for Rector that is fully static.

**Comment by philbates35** [comment]
@TomasVotruba For a dedicated `phpstan.neon` approach, I only really see two options:

### Option 1
Leave `phpstan.neon.dist` with the `bleedingEdge.neon` include, and duplicate the entire file removing just that one line where it is included into a new `phpstan.rector.neon` that is used by rector only, but I'm sure you can imagine that is far from ideal as there will inevitably be drift between the two files eventually.

### Option 2

Do something like this:

```neon
# phpstan.neon.dist
includes:
    - vendor/larastan/larastan/extension.neon
    - vendor/phpstan/phpstan-mockery/extension.neon
    - vendor/phpstan/phpstan-phpunit/extension.neon
    # And any other common extensions that should be used by both phpstan and rector...
```
```neon
# phpstan.rector.neon - used by rector only
includes:
    - phpstan.neon.dist
```
```neon
# phpstan.default.neon - used by phpstan only
includes:
    - phpstan.neon.dist
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon # This is the only difference between this and phpstan.rector.neon 
```
Which I think would work, but the downside is that to run phpstan by itself I now need to pass `-c phpstan.default.neon`, whereas it would be really nice if I could still just run `phpstan` and it just works.

Is there an alternative approach that would let me still use bleeding edge and rector, plus be able to run `phpstan` without needing to pass `-c`?

---

On the second issue I raised, would you agree that its unexpected that the exit code is 0 when this error occurred, resulting in the GitHub action to be considered successful? Is it worth keeping this issue at least open for that, or the creation of a new dedicated issue?

**Comment by TomasVotruba** [comment]
What I've seen on Github is that people include configs they need directly in `rector.php`:

```php
$rectorConfig->phpstanConfigs([
    __DIR___ . '/vendor/larastan/larastan/extension.neon',
    __DIR___ . '/vendor/phpstan/phpstan-mockery/extension.neon',
    __DIR___ . '/vendor/phpstan/phpstan-phpunit/extension.neon',
]);
```

As for the error code, instead of opening ticket, create a PR with your suggestion instead. It improves chances to land the feature :+1:

**Comment by samsonasik** [comment]
@philbates35 you can load bleeding edge with use use "full" path instead of internal relative phpstan path for load it, like what CodeIgniter/shield configure it and load from rector, see

https://github.com/codeigniter4/shield/blob/a538a1a2908cea156cfec77b69cd08baaa55f6a1/phpstan.neon.dist#L3

**Comment by samsonasik** [comment]
@philbates35 I created a PR to enable phpstan bleeding edge for that works for rector on your repo:

- https://github.com/philbates35/laravel-starter/pull/25

**Comment by janedbal** [comment]
> The phpstan.neon for Rector should only contains extension that provide types. 

But bleedingEdge enable multiple things, even type-related stuff like listTypes. So in order to have type resolution equal in Rector and PHPStan, you need to load bleedingEdge (if you use it within PHPStan).

-------------------

I bypassed this issue by this:

```php
// rector.php
\Phar::loadPhar($__DIR__ . '/vendor/phpstan/phpstan/phpstan.phar', 'phpstan.phar');

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->phpstanConfig(__DIR__ . '/rector.neon');
    ...
});
```

and

```neon
# rector.neon
includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
```

**Comment by samsonasik** [comment]
@janedbal using real path bleedingEdge.neon can work for both phpstan and rector already, see the solution https://github.com/philbates35/laravel-starter/pull/25
