### ISSUE TITLE
Unneeded brackets in variable declaration

### ISSUE THREAD

**Issue by interduo** [rectorphp/rector#8493]
# Feature Request
Remove unneded brackets when possible. I couldnt find any rule for that.
Is that the case for rector or for some code formatting tool like phpcbf?

Brackets are unneded in cases:
Case 1: whole variable declaration code is in brackets
```diff
-$test = (isset($var1) ?: $var2);
+$test = isset($var1) ?: $var2;
```

Case 2: some value in brackets when doing string cancelation
```diff
-$test = ($var1) . ' test123 ' . ($var2);
+$test = $var1 . ' test123 ' . $var2;
```

Case 3: double bracketings when brackets are stick together and no more brackets inside
```diff
-$test = $var3+(($var1+var2));
+$test = $var3+($var1+$var2);
```

**Comment by samsonasik** [comment]
Remove bracket seems not possible by nikic/php-parser as far as i know, as usually, re-print will add instead of remove.
