### ISSUE TITLE
Remove "/vendor" from Rector paths and run again.

### ISSUE THREAD

**Issue by parth391** [rectorphp/rector#8494]
# Question
Getting bellow warning on, `vendor/bin/rector process`

    [WARNING] Rector is running on your "/vendor" directory. This is not
              necessary, as Rector access /vendor by composer autoload. It will
              cause Rector tu run much slower and possibly with errors.
              Remove "/vendor" from Rector paths and run again.`

**Comment by samsonasik** [comment]
That means you need to exclude `__DIR__ . '/vendor` from the paths when possible in the rector config, eg, only `src` paths:

```php
<?php

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src',
    ])
    ->withRules([
        TypedPropertyFromAssignsRector::class
    ]);
```

If you have `vendor/` but not in the root directory, like what laravel vendor in templates part, you can try latest rector/rector:dev-main that already cover it at PR:

- https://github.com/rectorphp/rector-src/pull/5569

with

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

If you have `vendor/` that needs code upgrade, I suggest to upgrade the version of dependency instead.

**Comment by MrPunyapal** [comment]
@samsonasik I'm facing same Issue and I'm sure I have not  included it in paths.

**Comment by samsonasik** [comment]
Could you create a reproducible repo?

**Comment by parth391** [comment]
@samsonasik, one of my sub-folder had a vendor folder in it. By adding bellow code fix the issue.

    $rectorConfig->skip([
        __DIR__.'/**/vendor/*',
    ]);

**Comment by samsonasik** [comment]
That already handled on latest dev-main 👍

**Comment by parth391** [comment]
Yes, i am looking forward for new release.

**Comment by samsonasik** [comment]
1.0.1 is tagged https://github.com/rectorphp/rector/releases/tag/1.0.1
