### ISSUE TITLE
AddOverrideAttributeToOverriddenMethodsRector adds Override attribute to methods implementing interface

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#8497]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.1          |

## Minimal PHP Code Causing Issue

This is the code https://getrector.com/demo/9ded7338-8e46-4277-b343-f9e446d38f7a but I fail to reproduce the issue in the Demo.

This is my config

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);


    $rectorConfig->rule(AddOverrideAttributeToOverriddenMethodsRector::class);
};
```

Any idea why is it happening?

## Expected Behaviour

No Override is added to interface implementations.

**Comment by samsonasik** [comment]
Could you create reproducible repo/test with expected output? Thank you.

**Comment by simPod** [comment]
that, I can do. I'll be back.

**Comment by simPod** [comment]
https://github.com/simPod/repro-rector/actions/runs/7931449508/job/21655716248

**Comment by samsonasik** [comment]
That seems expected as it override parent?  https://github.com/simPod/repro-rector/actions/runs/7931449508/job/21655716248#step:5:22

```diff
 final readonly class FooImpl implements Foo
 {
+    #[\Override]
     public function process(): void
```

**Comment by simPod** [comment]
I see it applies to interfaces too. Aight, thanks for input!
