### ISSUE TITLE
Incorrect behavior of RemoveParentCallWithoutParentRector

### ISSUE THREAD

**Issue by micaherne** [rectorphp/rector#8500]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/57f6973b-fe57-4405-b934-61b6ebf70973

```php
<?php

class A extends B {
    public function some_method(): void {
        parent::test();
    }
}

class B extends C {
    
}
```

### Responsible rules

* `RemoveParentCallWithoutParentRector`

## Expected Behavior

I would expect no changes here as C, which isn't autoloaded, may contain the static method in question. (Similar to #8487)

**Comment by samsonasik** [comment]
No, that's expected, class B is exists, and no method should be removed.

You can skip the rule in case of that needed.

**Comment by micaherne** [comment]
Sorry I'm not understanding what you mean! If class C is this:

```php
class C {
    public static function test(): void {
        echo "test";
    }
}
```

then the call in class A is correct and shouldn't be removed, but it is.

**Comment by micaherne** [comment]
Like this: https://getrector.com/demo/b50966ba-6b90-4cf3-ada0-14ff43f8c13d

**Comment by samsonasik** [comment]
That mean the autoload should be resolved instead, climbing to with File re-read and transform is not what we want in Rector, the ClassReflection from PHPStan is used instead for out of scope file. See the documentation to solve the autoload issue https://getrector.com/documentation/static-reflection-and-autoload

**Comment by micaherne** [comment]
Thanks for the clarification, that makes sense. I'll disable that rule then as the codebase I'm working with is very large and I'm not convinced I have managed to set up autoloading for every class.
