### ISSUE TITLE
SetList::CODE_QUALITY

### ISSUE THREAD

**Issue by Telrik** [rectorphp/rector#8504]
process "C:\OSPanel\rector\vendor\bin\src\commands\EbayCommand.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Stmt\Expression" node, but is required by a
         refactorWithScope() method of "Rector\CodeQuality\Rector\Expression\TernaryFalseExpressionToIfRector" rule. Fix

         #0 C:\OSPanel\rector\vendor\rector\rector\src\Rector\AbstractRector.php(136):
         Rector\Rector\AbstractScopeAwareRector->refactor()
         #1 C:\OSPanel\rector\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(176):
         Rector\Rector\AbstractRector->enterNode()
         #2 C:\OSPanel\rector\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #3 C:\OSPanel\rector\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #4 C:\OSPanel\rector\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #5 C:\OSPanel\rector\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #6 C:\OSPanel\rector\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #7 C:\OSPanel\rector\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #8 C:\OSPanel\rector\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray()
         #9 C:\OSPanel\rector\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(41):
         PhpParser\NodeTraverser->traverse()
         #10 C:\OSPanel\rector\vendor\rector\rector\src\Application\FileProcessor.php(105):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #11 C:\OSPanel\rector\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(184):
         Rector\Application\FileProcessor->processFile()
         #12 C:\OSPanel\rector\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(161):
         Rector\Application\ApplicationFileProcessor->processFile()
         #13 C:\OSPanel\rector\vendor\rector\rector\src\Console\Command\WorkerCommand.php(118):
         Rector\Application\ApplicationFileProcessor->processFiles()
         #14 C:\OSPanel\rector\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):
         Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}()
         #15 C:\OSPanel\rector\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(117):
         RectorPrefix202402\Evenement\EventEmitter->emit()
         #16 C:\OSPanel\rector\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):
         RectorPrefix202402\Clue\React\NDJson\Decoder->handleData()
         #17 C:\OSPanel\rector\vendor\rector\rector\vendor\react\stream\src\Util.php(62):
         RectorPrefix202402\Evenement\EventEmitter->emit()
         #18 C:\OSPanel\rector\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(111):
         RectorPrefix202402\React\Stream\Util::RectorPrefix202402\React\Stream\{closure}()
         #19 C:\OSPanel\rector\vendor\rector\rector\vendor\react\stream\src\DuplexResourceStream.php(154):
         RectorPrefix202402\Evenement\EventEmitter->emit()
         #20 C:\OSPanel\rector\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(201):
         RectorPrefix202402\React\Stream\DuplexResourceStream->handleData()
         #21 C:\OSPanel\rector\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(173):
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #22 C:\OSPanel\rector\vendor\rector\rector\src\Console\Command\WorkerCommand.php(89):
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->run()
         #23 C:\OSPanel\rector\vendor\rector\rector\vendor\symfony\console\Command\Command.php(327):
         Rector\Console\Command\WorkerCommand->execute()
         #24 C:\OSPanel\rector\vendor\rector\rector\vendor\symfony\console\Application.php(960):
         RectorPrefix202402\Symfony\Component\Console\Command\Command->run()
         #25 C:\OSPanel\rector\vendor\rector\rector\vendor\symfony\console\Application.php(333):
         RectorPrefix202402\Symfony\Component\Console\Application->doRunCommand()
         #26 C:\OSPanel\rector\vendor\rector\rector\src\Console\ConsoleApplication.php(53):
         RectorPrefix202402\Symfony\Component\Console\Application->doRun()
         #27 C:\OSPanel\rector\vendor\rector\rector\vendor\symfony\console\Application.php(216):
         Rector\Console\ConsoleApplication->doRun()
         #28 C:\OSPanel\rector\vendor\rector\rector\bin\rector.php(130):
         RectorPrefix202402\Symfony\Component\Console\Application->run()
         #29 C:\OSPanel\rector\vendor\rector\rector\bin\rector(4): require_once('C:\\OSPanel\\rect...')
         #30 C:\OSPanel\rector\vendor\bin\rector(115): include('C:\\OSPanel\\rect...')
         #31 {main}". On line: 25

**Comment by samsonasik** [comment]
Could you create reproducible code at https://getrector.com/demo ? Also try latest `"rector/rector": "dev-main"` in case already resolved in latest main branch.

Thank you.

**Comment by Telrik** [comment]
Looks like your magic composer lines and update to php8 solve issues thanks.
