### ISSUE TITLE
Rector automatization: generate commits with every rule changes

### ISSUE THREAD

**Issue by interduo** [rectorphp/rector#8505]
# Question
@samsonasik I would like to run all rules but save changes in many commits (do commit per one rule) is it possible to do this without some bash wrapper?

something like that eg.
```
->withPhpSets(php74: true);
->withShellCmdBetweenRules->(['git commit -a -m "devel: RULESETNAME:RULENAME"']);
```

One very big commit with 1000 lines+ changes is very bad thing (can not do revert in easy way).

**Comment by samsonasik** [comment]
Git CLI seems not a rector scope, instead of doing many rules at one, register `withRules()` one by one instead for new projects ;)

**Comment by interduo** [comment]
Think in way of doing automatic refactoring :)

It's not just a git - it's just kind of integration with anything else.

`withShellCmdBetweenRules` between refactoring steps could be very flexible:

for eg could 
- send mail,
- could do git commit and git push to testing repos/env,
- create PR for review,
- run external php automatic test,
- run code cleanup tools,
- run code formatters,

If nothing like that is inside then we need to write a bash wrapper script for rector. This got some pros and cons and more cons.

Main thing - rector is doing rule1,rule2 checks or file1,file2 ?

**Comment by samsonasik** [comment]
You can setup github action, like using `stefanzweifel/git-auto-commit-action` for that for auto-commit, calling another CLI jobs is not part of rector job.

**Comment by cweiske** [comment]
With rector 2.0 and the `--only`-Option it's now possible to execute single rules only.
I built a script which creates git commits for each rule: https://github.com/mogic-le/rector-single-commit
