### ISSUE TITLE
Rector hangs for `RemoveDeadStmtRector` + `RemoveUnusedVariableAssignRector`

### ISSUE THREAD

**Issue by wojciech-z** [rectorphp/rector#8509]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.1 (via `bin/rector --version`)              |

Rector hangs on this rather simple code. On my machine it simply hangs for 3+ minutes (until i kill the process) and on the demo page it times out after 60 seconds. 

Seems that removing either of the rules or modifying the code in any way makes it finish within 1 second, but this combination makes it hang. 

Originally i had a much longer code triggering this, but i've managed to bring it down to a much smaller case.
Those two specific rules are part of `SetList::DEAD_CODE` rule set.

Demo link: https://getrector.com/demo/141cbff5-e71f-42a6-87ad-33216366a541

I am new to Rector, so maybe it is me doing something wrong?

## Minimal PHP Code Causing Issue

```
<?php

declare(strict_types=1);

class X
{
    public function f()
    {
        $var = $object->a() . $object->b();
    }
}
```

with config:

```
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;
use Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector;
use Rector\DeadCode\Rector\Expression\RemoveDeadStmtRector;

return RectorConfig::configure()
	->withRules([
        RemoveDeadStmtRector::class,
        RemoveUnusedVariableAssignRector::class,
    ]);
```

Getting an error in the demo page:
```
 Rector run Failed:
The process "'../vendor/bin/rector' 'process' '/var/www/src/../storage/demo/eqkyme1eznv67bwean0z/rector_analyzed_file.php' '--config' '/var/www/src/../storage/demo/eqkyme1eznv67bwean0z/rector.php' '--output-format' 'json'" exceeded the timeout of 60 seconds. 
```

## Expected Behaviour

Rector should finish this run within few seconds.

**Comment by threema-eduard** [comment]
It also seems to hang for `DeclareStrictTypesRector` even after the (rather quick, thanks for that) above fix.

**Comment by wojciech-z** [comment]
Many thanks, i can confirm it is working on [d24ee52](https://github.com/rectorphp/rector/commit/d24ee522cec3f40423add27ed5254457f735d13b)
