### ISSUE TITLE
Isn't the IntvalToTypeCastRector out of date? 

### ISSUE THREAD

**Issue by mingalevme** [rectorphp/rector#8510]
# Question

The modern versions of PHP do the same in case of `(int) $var` and `intval($var)`.

Example (PHP 8.3.1)

## (int) $var

```php
<?php
$str = getenv('TEST_ENV');
echo (int) $str;

```

Output

```sh
$ php -d opcache.enable_cli=1 -d opcache.opt_debug_level=0x10000 test.php

$_main:
     ; (lines=9, args=0, vars=1, tmps=3)
     ; (before optimizer)
     ; /.../test.php:1-4
     ; return  [] RANGE[0..0]
0000 EXT_STMT
0001 INIT_FCALL 1 112 string("getenv")
0002 SEND_VAL string("TEST_ENV") 1
0003 V1 = DO_ICALL
0004 ASSIGN CV0($str) V1
0005 EXT_STMT
0006 T3 = CAST (long) CV0($str)
0007 ECHO T3
0008 RETURN int(1)
```
## intval($var)

```php
<?php
$str = getenv('TEST_ENV');
echo intval($str);

```

Output

```sh
$ php -d opcache.enable_cli=1 -d opcache.opt_debug_level=0x10000 test.php

$_main:
     ; (lines=9, args=0, vars=1, tmps=3)
     ; (before optimizer)
     ; /.../test.php:1-4
     ; return  [] RANGE[0..0]
0000 EXT_STMT
0001 INIT_FCALL 1 112 string("getenv")
0002 SEND_VAL string("TEST_ENV") 1
0003 V1 = DO_ICALL
0004 ASSIGN CV0($str) V1
0005 EXT_STMT
0006 T3 = CAST (long) CV0($str)
0007 ECHO T3
0008 RETURN int(1)
```

So may be it's  a good idea to cosider to remove `IntvalToTypeCastRector` from `CODE_QUALITY` list? I'm personally sure that `intval($var)` is more readable than `(int) $var` especially when the whole statement is more complex cause it does not require additional braces and don't have to think about operators priority.

**Comment by samsonasik** [comment]
I think that personal preference, you can skip the rules if you don't need it ;)

**Comment by mingalevme** [comment]
Yes, of course, I know about the skipping the rules. My point was the rule is in the *QUALITY_LIST* because of `https://tonyshowoff.com/articles/casting-int-faster-than-intval-in-php/`, but `intval` isn't slower than '(int)' anymore ...

I just suggested an idea) thank you
