### ISSUE TITLE
Incorrect behavior of RemoveDoubleAssignRector

### ISSUE THREAD

**Issue by max4logist** [rectorphp/rector#8515]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/599f1d9f-535d-446b-ab8c-b909854be398

```php
<?php

$a = null; // This is 'A'
$b = null; // This is 'B'
$b = true;
```

### Responsible rules

* `RemoveDoubleAssignRector`

## Expected Behavior
Not sure about expected behavior, but first comment must be without changes. 
Second comment may be deleted, transferred to next line, or stay without changes 
```php
<?php

$a = null; // This is 'A'
$b = true; // This is 'B'
```
Or maybe 
```php
<?php

$a = null; // This is 'A'
// This is 'B'
$b = true; 
```

## Current Behavior
```php
<?php

$a = null; // This is 'B'
$b = true;
```

**Comment by samsonasik** [comment]
that's expected, comment is belong to next stmt, see https://github.com/nikic/PHP-Parser/issues/950

**Comment by max4logist** [comment]
@samsonasik But why this is valid behaviour, if this code

```php
$isFoo = false; // Deprecated value: Don't use it in future
$c = 2 * M_PI * $r; // This is the circumference
$c = 0;
```

was processed to

```php
$isFoo = false; // This is the circumference
$c = 0;
```

This breaks comments, not just from the line being deleted

**Comment by samsonasik** [comment]
Because the last stmt is the stmt that not removed, so it brings comment from previous line.

It can't be handled on rector, rather on php-parser side.
