### ISSUE TITLE
Incorrect behavior of RemoveDeadStmtRector

### ISSUE THREAD

**Issue by interduo** [rectorphp/rector#8519]
# Bug Report
Just remove empty else { } structure.
It's not needed and it's also somekind of "deadcode".

## Minimal PHP Code Causing Issue
See https://getrector.com/demo/6a6f3515-a904-414f-8a4d-83cf7530577b

### Responsible rules
* `RemoveDeadStmtRector`

## Expected Behavior
No empty else { } structure in code.

**Comment by samsonasik** [comment]
That's expected, the rule is removing `Expression`, not empty `Else_`, for that, another rule may be needed.
