### ISSUE TITLE
Is there a rule to convert implicitly nullable types to explict ones?

### ISSUE THREAD

**Issue by mfn** [rectorphp/rector#8520]
# Question
I learned about this via https://github.com/sebastianbergmann/phpunit/issues/5719 which references https://wiki.php.net/rfc/deprecate-implicitly-nullable-types , and I was wondering if per chance there is already a rule covering this?

I went through all of them but couldn't find one where I had the feeling it was the correct one; but maybe I searched for the wrong keywords (nullable, implicitly).

Thanks

**Comment by samsonasik** [comment]
That seems php 8.4 rfc, so I think we can wait until that got merged to master branch of php-src so we can add to `PhpVersionFeature`, also need to verify if that cause signature bc break.

**Comment by sebastianbergmann** [comment]
> also need to verify if that cause signature bc break

It does not.

**Comment by samsonasik** [comment]
@sebastianbergmann thank you for verify 👍

**Comment by samsonasik** [comment]
I created PR:

- https://github.com/rectorphp/rector-src/pull/5724

for it.

**Comment by staabm** [comment]
fwiw, I think this is already possible with PHP CS-Fixer and maybe ECS. not sure we need it also in rector.

**Comment by samsonasik** [comment]
@staabm let make it possible with rector as well 👍
