### ISSUE TITLE
Error: Class "RectorPrefix202402\Webmozart\Assert\Assert" not found

### ISSUE THREAD

**Issue by peterfox** [rectorphp/rector#8522]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.2                                                      |

Installing Rector 1.0.2 into Laravel Rector project causes an error when using `Rector\TypeDeclaration\Rector\FunctionLike\AddParamTypeForFunctionLikeWithinCallLikeArgDeclarationRector` rule.

Error:

```
Error: Class "RectorPrefix202402\Webmozart\Assert\Assert" not found
```

## Minimal PHP Code Causing Issue

```php

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\FunctionLike\AddParamTypeForFunctionLikeWithinCallLikeArgDeclarationRector;
use Rector\TypeDeclaration\ValueObject\AddParamTypeForFunctionLikeWithinCallLikeArgDeclaration;
use RectorLaravel\Rector\Param\AddParamTypeForFunctionLikeWithinCallLikeArgArrayValuesDeclarationRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(
        AddParamTypeForFunctionLikeWithinCallLikeArgDeclarationRector::class,
        [
            new AddParamTypeForFunctionLikeWithinCallLikeArgDeclaration(
                'Illuminate\Database\Eloquent\Model',
                'handleLazyLoadingViolationUsing',
                0,
                0,
                new \PHPStan\Type\ObjectType('Illuminate\Database\Eloquent\Model')
            ),
            new AddParamTypeForFunctionLikeWithinCallLikeArgDeclaration(
                'Illuminate\Database\Eloquent\Model',
                'handleLazyLoadingViolationUsing',
                0,
                1,
                new \PHPStan\Type\StringType(),
            )
        ]
    );
};
```

## Expected Behaviour

Class should exist, the vendor folder under `rector/rector` is there which contains `webmozart/assert` but when the rule is used it complains that it's not there.

## Notes

You can see the tests run on the project https://github.com/driftingly/rector-laravel/actions/runs/8133918360/job/22226089274

Possibly something is wrong with how the Laravel Rector project is set up rather than an issue with Rector.

**Comment by samsonasik** [comment]
The prefix is `RectorPrefix202403` now, I can't found `RectorPrefix202402` in the code, could you try remove vendor and composer lock, then re-run composer clear-cache ans composer update?

**Comment by peterfox** [comment]
@samsonasik no luck. The code installed in `vendor` points to `use RectorPrefix202403\Webmozart\Assert\Assert;` but when running the tests it still fails. Plus there should be no cache on that CI runner so I don't see how it's failing there if that's the situation.

**Comment by peterfox** [comment]
Ah, never mind, this is a problem with me in the Laravel Rector repo where I've imported the wrong Assert class and picked up the one from Rector rather than the one installed under composer directly. Was find until upgrading 😅
