### ISSUE TITLE
dollar brace string interpolation is not corrected with LevelSetList::UP_TO_PHP_82

### ISSUE THREAD

**Issue by divinity76** [rectorphp/rector#8525]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.2|

dollar brace string interpolation ("${variable_name}") has been deprecated in PHP8.2, rector should fix it but does not. for the RFC see https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation

## Minimal PHP Code Causing Issue

https://getrector.com/demo/7ce9638f-53db-4d03-9554-ea31616812e2

## Expected Behaviour

The code `"${v}"` should be changed to `"{$v}"` with >= \Rector\Set\ValueObject\LevelSetList::UP_TO_PHP_82

**Comment by samsonasik** [comment]
For demo uri update, `withPhpSets` should be used https://getrector.com/demo/7ce9638f-53db-4d03-9554-ea31616812e2

**Comment by samsonasik** [comment]
Notes for collection of valid and invalid string:

**valid** (escaped)

- https://3v4l.org/YnE1J
- https://3v4l.org/n4FtF

**deprecated**

- https://3v4l.org/W44Km
