### ISSUE TITLE
 [ERROR] Could not process 

### ISSUE THREAD

**Issue by terrytampa123** [rectorphp/rector#8527]
"System error: "Rector\Rector\AbstractRector::getType(): Argument #1 ($node) must be of type PhpParser\Node,   
         null given, called in                                                                                          
         vendor/rector/rector/vendor/rector/rector-phpunit/rules/CodeQuality/Rector/MethodCall/AssertEmptyNullableObject
         ToAssertInstanceofRector.php82"

**Comment by samsonasik** [comment]
looking on your error, I created PR 

- https://github.com/rectorphp/rector-phpunit/pull/315

for it.
