### ISSUE TITLE
Incorrect behavior of SwitchNegatedTernaryRector

### ISSUE THREAD

**Issue by interduo** [rectorphp/rector#8528]
# Bug Report
Created diff contains ('') whitch looks badly and I need to test deeply the code if its completly comparable in efects.

## Minimal PHP Code Causing Issue
See https://getrector.com/demo/8c873402-fcd8-4a0f-8b03-cfc8e2554e8b

```php
<?php
$somestring = 'string'
. (!empty($nodegroup) ? ($nodegroupnegation ? ' AND na.gcount IS NULL' : ' AND na.gcount = ' . (is_array($nodegroup) ? count($nodegroup) : 1)) : '')
. (!empty($consent_condition) ? ' AND ' . $consent_condition : '');
```

### Responsible rules
* `SwitchNegatedTernaryRector`

## Expected Behavior
Remove brackets `()` in ternary sides.
('') looks very badly.

**Comment by samsonasik** [comment]
same with https://github.com/rectorphp/rector/issues/8493, remove bracket seems not possible by nikic/php-parser as far as i know, as usually, re-print will add instead of remove.
