### ISSUE TITLE
ConfigurableRector: Rename function to static method

### ISSUE THREAD

**Issue by gharlan** [rectorphp/rector#8529]
# Feature Request

In the next major version of our CMS some functions are replaced by static methods. So it would be nice if we could provide a rector rule for these replacements.
 
## Diff 

```diff
-myFunc(1, 2, 3);
+Foo::bar(1, 2, 3);
```

**Comment by TomasVotruba** [comment]
Maybe this might help: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#staticcalltofunccallrector

**Comment by samsonasik** [comment]
There is Func to static call rector rule for that https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#funccalltostaticcallrector
