### ISSUE TITLE
ConfigurableRector: Replace construct calls by static constructor method

### ISSUE THREAD

**Issue by gharlan** [rectorphp/rector#8530]
# Feature Request

In our CMS some public constructors are deprecated and replaced by static constructor methods. It would be nice if we could provide a rector rule for replacing them.
 
## Diff 

```diff
-$foo = new Foo('bar');
+$foo = Foo::fromString('bar');
```

**Comment by TomasVotruba** [comment]
Hi, that sounds doable. Could you send a PR with your rule proposal?

**Comment by TomasVotruba** [comment]
Btw, would this help?
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#newtostaticcallrector

I always check that rule list before coming up with a PR for new one. Most of them already exist :)

**Comment by samsonasik** [comment]
@TomasVotruba yes, the `NewToStaticCallRector` already cover that

**Comment by gharlan** [comment]
Very cool, thanks! ❤️  
And sorry for the issues, next time I'll take a closer look to see if the rules already exist.
