### ISSUE TITLE
`DeclareStrictTypesRector::class`-rule with the `php83`-set can cause endless loop

### ISSUE THREAD

**Issue by kapersoft** [rectorphp/rector#8531]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 1.0.2             |

Applying the `DeclareStrictTypesRector`-rule with the `php83`-set on a class without a namespace, will result into an endless loop adding multiple `declare(strict_types=1);`-statements to the file. The issue does not occur when the class has a namespace or without the `php83`-set.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/d48ae5c2-c537-445c-9555-4a76bbaf12c2

https://github.com/kapersoft/rector-endless-loop/

## Expected Behaviour

Single `declare(strict_types=1)`-statement added to the class.

**Comment by samsonasik** [comment]
it is strange that I can't reproduce on latest dev-main on rector-src, I will check your repo.

**Comment by samsonasik** [comment]
it seems happen by 2 rules:

```
use Rector\Php72\Rector\FuncCall\ParseStrWithResultArgumentRector;
use Rector\TypeDeclaration\Rector\StmtsAwareInterface\DeclareStrictTypesRector;
```

Ref https://getrector.com/demo/5a192968-13d6-41da-924b-18c44a4a2784
