### ISSUE TITLE
Incorrect behavior of TernaryFalseExpressionToIfRector

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#8534]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a105e793-9d74-415c-a29d-4b69be9977e9

```php
<?php

class ArrayHelper
{
    public static function mksort(array &$array): void
    {
        $keys = array_keys($array);
        $isIndexedArray = array_reduce($keys, static fn ($result, $item): bool => $result && is_numeric($item), true);
        $isIndexedArray
            ? sort($array)
            : ksort($array);

        foreach ($array as &$value) {
            if (is_array($value)) {
                self::mksort($value);
            }
        }
    }
}
```

### Responsible rules

* `TernaryFalseExpressionToIfRector`

## Expected Behavior

The code is not changed.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by Aerendir** [comment]
Hi Tomas, here the PR:

- https://github.com/rectorphp/rector-src/pull/5702

Let me know if it well done 💪
