### ISSUE TITLE
actually rename classes (and interfaces, traits)

### ISSUE THREAD

**Issue by mindplay-dk** [rectorphp/rector#8539]
# Feature Request

From the description of [RenameClassRector](https://github.com/rectorphp/rector/blob/3e8c19254ee9017d210d859ecd73fd3733ecc867/rules/Renaming/Rector/Name/RenameClassRector.php), I had assumed I could use this to actually rename a class, which turns out not to be the case?

It appears to only update the *references* to a type, but seems it can't rename the type itself?

So the diff I'm looking for is something trivial like:

```diff
-class OldName
+class NewName
```

It appears I'm not the first person looking for something like this?

https://github.com/rectorphp/rector/discussions/6946

But based on a configuration, same as `RenameClassRector`.

Based on the [rule mentioned in that thread](https://github.com/dingo-d/rector-snake-case-rename-rule/tree/main/utils/rector/src/Rector/Renaming), I tried to cobble something together:

```php
<?php

declare(strict_types=1);

namespace LOL;

use PhpParser\Node;
use PhpParser\Node\Stmt\Class_;
use Rector\Rector\AbstractRector;
use Rector\Renaming\NodeManipulator\ClassRenamer;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;
use Rector\Configuration\RenamedClassesDataCollector;
use Rector\Contract\Rector\ConfigurableRectorInterface;

/**
 * Rector rule for renaming class names
 */
final class RenameClassNameRector extends AbstractRector implements ConfigurableRectorInterface
{
    /**
     * @readonly
     * @var ClassRenamer
     */
    private $classRenamer;

    /**
     * @readonly
     * @var \Rector\Configuration\RenamedClassesDataCollector
     */
    private $renamedClassesDataCollector;

    public function __construct(RenamedClassesDataCollector $renamedClassesDataCollector, ClassRenamer $classRenamer)
    {
        $this->classRenamer = $classRenamer;
        $this->renamedClassesDataCollector = $renamedClassesDataCollector;
    }

    /**
     * @throws \Symplify\RuleDocGenerator\Exception\PoorDocumentationException
     */
    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition(
            'Renames the configured classnames',
            [
                new CodeSample(
                    <<<'CODE_SAMPLE'
class OldClass
{
	public function run()
	{
		$this->something();
	}
}
CODE_SAMPLE
                    ,
                    <<<'CODE_SAMPLE'
class NewClass
{
	public function run()
	{
		$this->something();
	}
}
CODE_SAMPLE
                )
            ]
        );
    }

    /**
     * @return array<class-string<Node>>
     */
    public function getNodeTypes(): array
    {
        return [Class_::class];
    }

    /**
     * @param \PhpParser\Node\Stmt\Class_ $node
     */
    public function refactor(Node $node): ?Node
    {
        $oldName = $node->name->toLowerString();

        if ($this->renamedClassesDataCollector->hasOldClass(($oldName))) {
            $oldToNewClasses = $this->renamedClassesDataCollector->getOldToNewClasses();

            $newName = $oldToNewClasses[$oldName];

            $node->name = new Node\Identifier($newName);
    
            return $node;
        }

        return null;
    }

    /**
     * @param mixed[] $configuration
     */
    public function configure(array $configuration): void
    {
        $this->renamedClassesDataCollector->addOldToNewClasses($configuration);
    }
}
```

But by the looks of it, I've just reimplemented `RenameClassRector` exactly - it only updates the references, not the class declarations.

I'm guessing maybe `ClassRenamer` isn't actually capable of this at all?

It doesn't sound like an exotic requirement though? I was quite surprised it doesn't do this out of the box - it seems to be implied by the name and the configuration, although I understand it's not actually what the documentation shows in the example. Confusing name though, since this rule doesn't actually rename anything.

I don't want to propose a backwards incompatible change, and the configuration for the existing rule is just an array, so this can't just be added as an option for the existing rule, I guess? so I would suggest this be a new rule.

Would you consider it?

Or could you maybe point me in the right direction?

**Comment by samsonasik** [comment]
The feature exists in the past, but removed due to break autoloading. We do not handle file names and location changes, That's scope of IDE/manual rename.

see PR:

- https://github.com/rectorphp/rector-src/pull/5487
- https://github.com/rectorphp/rector-src/pull/5487

**Comment by mindplay-dk** [comment]
> The feature exists in the past, but removed due to break autoloading. We do not handle file names and location changes, That's scope of IDE/manual rename.

that's too bad. I have 100s of classes that need to be renamed as part of a code standard change and thought this was the tool.

does it have to break autoloading? only if you try to rename files on the fly - if you were to wait until all rules have finished processing, it wouldn't be a problem, I think? e.g. make the actual file changes as you go, but use e.g. `register_shutdown_function` and wait until rector exits before renaming the files.

I'd imagine there are plenty of upgrade/refactoring chores that requires class/file-name changes? WordPress upgrades etc.

sounds like a valuable feature was removed instead of fixing a problem?
