### ISSUE TITLE
How to correctly insert disableParallel in the rector.php file?

### ISSUE THREAD

**Issue by alex7070m** [rectorphp/rector#8541]
Hello! An error occurs when processing multiple php files:

  "Child process timed out after 120 seconds".

I read on this site that one of the ways to solve this problem is to turn off parallelism with the line

$rectorConfig->disableParallel();

What is the correct way to insert this in the rector.php file? Thanks

**Comment by samsonasik** [comment]
if you use `return RectorConfig::configure()`, you can call : 

```php
return RectorConfig::configure()
   // 
   ->withoutParallel();
```

at the fluent call, if you `return static function(RectorConfig $rectorConfig): void`, you can call:

```php
return static function(RectorConfig $rectorConfig): void {
   // 
   $rectorConfig->disableParallel();
};
```

**Comment by samsonasik** [comment]
see https://github.com/rectorphp/getrector-com/pull/2124
