### ISSUE TITLE
ClosureToArrowFunctionRector remove use() part in php code

### ISSUE THREAD

**Issue by shakaran** [rectorphp/rector#8544]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 1.0.2            |

The following code is not similar and break the processing. The part use ($issuerId, $keyId, $appId) got stripped and process breaks with a fatal.
```

    ---------- begin diff ----------
@@ @@

         $jwtFacade = new JwtFacade();

-        $closureBuilder = function (
-            Builder $builder,
-            DateTimeImmutable $now
-        ) use ($issuerId, $keyId, $appId): Builder
-        {
-            return $builder
-            ->issuedBy($issuerId)
-            ->permittedFor(self::TOKEN_PERMISSION)
-            ->withClaim('uid', 1)
-            ->withHeader('kid', $keyId)
-            ->withHeader('alg', 'ES256')
-            ->withHeader('type', 'JWT')
-            ->issuedAt($now)
-            ->identifiedBy($appId)
-            ->expiresAt($now->modify('+20 minutes'));
-        };
+        $closureBuilder = fn(Builder $builder, DateTimeImmutable $now): Builder => $builder
+        ->issuedBy($issuerId)
+        ->permittedFor(self::TOKEN_PERMISSION)
+        ->withClaim('uid', 1)
+        ->withHeader('kid', $keyId)
+        ->withHeader('alg', 'ES256')
+        ->withHeader('type', 'JWT')
+        ->issuedAt($now)
+        ->identifiedBy($appId)
+        ->expiresAt($now->modify('+20 minutes'));

         $token = $jwtFacade->issue(
             new Sha256(),
    ----------- end diff -----------

Applied rules:
 * MultiDirnameRector
 * ClosureToArrowFunctionRector (https://wiki.php.net/rfc/arrow_functions_v2)
                                                 
## Expected Behaviour

ClosureToArrowFunctionRector should support the use()

**Comment by samsonasik** [comment]
Could you create reproducible code and config at https://getrector.com/demo ? Thank you.

**Comment by shakaran** [comment]
100% reproducible

https://getrector.com/demo/bf52059b-c3e8-441e-b41f-68ab71c24b38

**Comment by samsonasik** [comment]
That's expected, arrow function doesn't use `use()` as the variable always directly available. If you got fatal error, you seems use diffetent php version cli vs web that has lower php version.

**Comment by shakaran** [comment]
The fatal error is because use() params are missing after the rewrite of rector.

That is, no part:

`use ($issuerId, $keyId, $appId)`

In any place.

In CLI I have PHP 8.2.10-2ubuntu1

If the arrow function doesn't use _use()_, then it don't should try to rewrite that part and skip this case in rector. Because it is breaking my code. Please reopen

**Comment by samsonasik** [comment]
No, see  the different:

on Closure: https://3v4l.org/FLT5p
on ArrowFunction: https://3v4l.org/d3cuL

the variable is always exists in ArrowFunction.
