### ISSUE TITLE
Refactor Switch to Match breaks code logic

### ISSUE THREAD

**Issue by ipradasgomez** [rectorphp/rector#8545]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.2        |

## Minimal PHP Code Causing Issue

```
class A {
	public static function create(): self
	{
		return new self();
	}
}

$builtA = new A();
$createdA = A::create();

switch ($builtA) {
	case $createdA: echo "With switch, Built and Crated are Equals";
	break;
	default: echo "With switch, Built and Created are not Equals";
}
```
The result of above execution is: _With switch, Built and Crated **are Equals**_

It generates:
```
$matchResult = match ($builtA) {
	$createdA => "With match, Built and Created are Equals",
	default => "With match, Built and Created are not Equals,"
};
```

The result of the above execution is: _With match, Built and Created are **not Equals**_,

[Demo link](https://getrector.com/demo/683849e4-3233-40ac-a41a-ca5e50e481c1)
## Expected Behaviour
If the evaluated variable is an instnace of class instead of a primitive type or the execution of a function which returns a primitive type, prevent the change

**Comment by samsonasik** [comment]
demo link is no change, you may need to try latest `"rector/rector": "dev-main"`, or you may need to create reproducible repo for it? thank you.

**Comment by ipradasgomez** [comment]
Hi @samsonasik 
You can test here in this repo: https://github.com/ipradasgomez/rector-switch-bug

- Please, execute composer install to install requeriments.
- Then, execute php ./src/demo.php to see first result.
- Then, execute vendor/bin/rector
- Finally, re-execute php ./src/demo.php to see how the result has changed.

There you are also the changes made by rector in my code:

```
class MyTest {
     public function doTheAction(MyClass $example): string
     {
-        switch ($example) {
-            case MyClass::build():
-                return 'MyClass and OtherMyClass are Equal';
-                break;
-            default:
-                return 'MyClass and OtherMyClass are Different';
-        }
+        return match ($example) {
+            MyClass::build() => 'MyClass and OtherMyClass are Equal',
+            default => 'MyClass and OtherMyClass are Different',
+        };
     }
 }
```
