### ISSUE TITLE
Child process timed out after 120 seconds

### ISSUE THREAD

**Issue by alex7070m** [rectorphp/rector#8547]
Hello! I turned off parallelism, but when processing some php files I still get an error like

  [ERROR] Could not process
          "C:\Users\alexa\www\someproject\vendor\rector\rector\vendor\symplify\easy-parallel\src\ValueObject\ParallelPro

          "Child process timed out after 120 seconds." On line: 108

          "Reached system errors count limit of 50, exiting...".

How to fix it? Thanks
![2024-03-13](https://github.com/rectorphp/rector/assets/69157204/631f173a-a1c6-4234-ab14-958c2a88e6b3)

**Comment by samsonasik** [comment]
You can increase timeout or reduce jobSize arg value, see documentation https://getrector.com/documentation/troubleshooting-parallel

see improved doc PR for detail https://github.com/rectorphp/getrector-com/pull/2124/files

**Comment by alex7070m** [comment]
It’s not clear why this happens if parallelism is turned off?

rector.php:

`<?php

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\Property\TypedPropertyFromStrictConstructorRector;

return RectorConfig::configure()
    // register single rule
    ->withRules([
        TypedPropertyFromStrictConstructorRector::class
    ])
    // here we can define, what prepared sets of rules will be applied
    ->withPreparedSets(
        deadCode: true,
        codeQuality: true
    );
return static function(RectorConfig $rectorConfig): void {
   //
   $rectorConfig->disableParallel();
}; `
