### ISSUE TITLE
RectorConfigBuilderRector not applied

### ISSUE THREAD

**Issue by mbrodala** [rectorphp/rector#8548]
# Question

I have added the `RectorConfigBuilderRector` rule to my `rector.php` and did expect Rector to rector the rector.php to use the RectorConfigBuilder. However, the file is left unchanged. How should this rector be used?

**Comment by samsonasik** [comment]
Yes, it is not perfect yet :), there is `else` for next iteration

https://github.com/rectorphp/rector/blob/d9fea10f3e80961cf820c8ca57ebafaa0e2b0e9f/rules/Transform/Rector/FileWithoutNamespace/RectorConfigBuilderRector.php#L157-L158

**Comment by mbrodala** [comment]
I know but it's there and can be used AFAIS, at least there are tests which work. So how should one use it currently? Or is it not supposed to be used at all ATM? Then it should probably be hidden from the docs.

**Comment by samsonasik** [comment]
The test fixtures are at rector-src https://github.com/rectorphp/rector-src/tree/main/rules-tests/Transform/Rector/FileWithoutNamespace/RectorConfigBuilderRector/Fixture

Feel free to add more fixture and contribute to improve it.

The documentation is generated by `composer docs` command, and I as far as I see, there is no "skip rule to be generated into docs" command yet.

Feel free to contribute to improve it if you find area that can be improved.

**Comment by samsonasik** [comment]
that seems not working, or bug on rule-doc-generator itself, or I run incorrectly, regarding `AbstractCollectorRector`, that no longer exists, so that's should be removed from --skip-type

**Comment by samsonasik** [comment]
Ref https://github.com/rectorphp/rector-src/pull/5720

**Comment by mbrodala** [comment]
OK. Then my comments at least had one positive effect. :sweat_smile:
