### ISSUE TITLE
Incorrect behavior of LongArrayToShortArrayRector

### ISSUE THREAD

**Issue by ipradasgomez** [rectorphp/rector#8549]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/7ba68092-de28-4283-a63a-093feeecb3cf

```php
<?php

static $languages = array(
    'es' => 'spanish',
    'en' => 'english',
    'zh' => 'chinese',
    'nl' => 'dutch',
    'fr' => 'french',
    'de' => 'german',
    'it' => 'italian',
    'ja' => 'japanese',
    'jp' => 'japanese',
    'pl' => 'polish',
    'pt' => 'portuguese',
    'br' => 'portuguese',
    'ru' => 'russian',
    'kr' => 'korean',
    'ko' => 'korean',
);
```

### Responsible rules

* `LongArrayToShortArrayRector`

## Expected Behavior

Rector does the change but it makes it in a single line, breaking the max-line limitation of 120 characters established in https://www.php-fig.org/psr/psr-12/#23-lines and breaking the array style

**Comment by TomasVotruba** [comment]
Rector can change the code, but sometimes does not keep previous formatting due to AST limitations: https://github.com/rectorphp/rector#known-drawbacks

That's why you should always use a coding standard tool to tidy up :+1:
