### ISSUE TITLE
[CodeQuality] Null compares to callesce queue

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#855]
Ref https://github.com/Sylius/Sylius/pull/9902/files#r231438895

```diff
-if (null !== $this->orderItem) {
-    return $this->orderItem;
-}
-if (null !== $this->orderItemUnit) {
-    return $this->orderItemUnit;
-}
-return null;
+return $this->orderItem ?? $this->orderItemUnit;
```

_Originally posted by @TomasVotruba in https://github.com/rectorphp/rector/issues/424#issuecomment-447123076_

**Comment by Mx-Glitter** [comment]
The last conditional is a case in itself that can be simplified from

```php
if (null !== $this->orderItemUnit) {
    return $this->orderItemUnit;
}
return null;
```

to

```php
return $this->orderItemUnit;
```

**Comment by TomasVotruba** [comment]
How would you simplify whole code then?

```diff
if (null !== $this->orderItem) {
    return $this->orderItem;
}
if (null !== $this->orderItemUnit) {
    return $this->orderItemUnit;
}
return null;
``

**Comment by Mx-Glitter** [comment]
Sorry I wasn't clear, I thought going in two steps could be easier to simplify:

- first a case of

    ```diff
    - if ($a !== $b) {
    -     return $b;
    - }
    - return $a;
    + return $b;
    ```

    with `$a = null` and `$b = $this->orderItemUnit`

- then a case of

    ```diff
    - if (null !== $a) {
    -    return $a;
    - }
    - return $b;
    + return $a ?? $b;
    ```

    with `$a = $this->orderItem` and `$b = $this->orderItemUnit`

- which would lead to the solution you proposed

**Comment by Mx-Glitter** [comment]
The last lines could also be simplified in:

```diff
- if (null !== $this->orderItemUnit) {
-     return $this->orderItemUnit;
- }
- return null;
+ return $this->orderItemUnit ?? null;
```

then

```diff
- return $this->orderItemUnit ?? null;
+ return $this->orderItemUnit;
```

**Comment by TomasVotruba** [comment]
These cases are already covered. Point if this issue is solve the big code all together.

**Comment by Mx-Glitter** [comment]
Yes, I totally agree with you, I was thinking about how to work on the implementation, sorry for the misunderstanding 😅

I thought we could perhaps try to apply rector multiple times until there is no change left (and handle cases where there is a cycle) and you wouldn't have to make composite rules in the code.

**Comment by TomasVotruba** [comment]
I see :) well, you could add your ideas as test cases here: https://github.com/rectorphp/rector/blob/0da7927469304258bb72ca383e735138b9b6d0de/packages/CodeQuality/tests/Rector/If_/SimplifyIfNotNullReturnRector/SimplifyIfNotNullReturnRectorTest.php
