### ISSUE TITLE
Incorrect behavior of ParenthesizeNestedTernaryRector: elvis operator is interpreted as a ternary

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#8552]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.0.3      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d8a31c5d-069e-4a8c-9535-be6262219372

```php
<?php

// PS: here "sort" is a custom function, not the standard PHP one, not that it matters in this context
$array = sort([/* whatever */], static fn (array $a, array $b): int
    => $a['key1'] <=> $b['key1']
    ?: $a['key2'] <=> $b['key2']
    ?: $a['key3'] <=> $b['key3'],
);
```

### Responsible rules

* `ParenthesizeNestedTernaryRector`

## Expected Behavior

Rector should not interpret `?:` as a "ternary".

**Comment by samsonasik** [comment]
Elvis is also ternary itself, just without if, I tried verify your code, and it is confusing for me tbh, the check is by token, and it hard to verify + read which code belong to if, then cover to else.

I suggest to refactor to use if else for readable code. You can skip the rule if the transformed code is not what you want to https://getrector.com/documentation/ignoring-rules-or-paths

**Comment by gnutix** [comment]
This code is sorting an array according to multiple criterion. Nothing fancy, it just uses the combination of the spaceship operator (returning `-1|0|1`) and the Elvis operator, which will execute the next sorting only if the first one returned `0`.

**Comment by samsonasik** [comment]
That unfortunatelly hard to cover in php-parser which verify token parentheses check, and elvis verify after that.
