### ISSUE TITLE
Incorrect behavior of Rector\Php83\Rector\ClassConst\AddTypeToConstRector

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#8553]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/93fbe8d7-c64c-4406-ae37-0773028842f2

```php
<?php

final class DemoFile
{
    public const CIAO = 'ciao';
    public function run(bool $param)
    {
        if ($this->isTrue($param)) {
            return 5;
        }

        return '10';
    }

    private function isTrue($value)
    {
        return $value === true;
    }
}
```

### Responsible rules

* `\Rector\Php83\Rector\ClassConst\AddTypeToConstRector`

## Expected Behavior

I expect this change (the others are just to make possible to create the issue: if no change is applied, it is not possible to create an issue):

```diff
final class DemoFile
{
-    public const CIAO = 'ciao';
+    public const string CIAO = 'ciao';
    public function run(bool $param)
    {
        if ($this->isTrue($param)) {
            return 5;
        }

        return '10';
    }

    private function isTrue($value)
    {
        return $value === true;
    }
}
```

# Side note

I cannot create a failing test case as the button to create it is not present on the demo page.

**Comment by samsonasik** [comment]
You need to set `withPhpVersion()` for that if you don't use `withPhpSets()`, see https://getrector.com/demo/b501d96a-a8ba-4cb3-8e9c-0efd70ce6ecb
