### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector: it renames properties (which may break code)

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#8554]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.0.3      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/b272aaab-1607-4c91-a098-23a82185320d

```php
<?php

final class DemoFile
{
    private bool $something;
    
    public function __construct(bool $param)
    {
        $this->something = $param;
    }
}

new DemoFile(param: true);
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

IMHO, the property should probably be left untouched. Renaming a property should be a conscious decision by the developer.

I'm surprised no one noticed this issue before. I ran the rule on my project, and the very first file I've looked at had this scenario. Maybe I'm lucky... ? :P

**Comment by samsonasik** [comment]
The rule is configurable, you can disable renaming, see example config for that

https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/config/configured_rule_disabled_renaming.php

**Comment by gnutix** [comment]
Not sure how the concept of a "risky" / "unsafe" rule is managed in this project, but I'm surprised that the PHP 8.0 "set" isn't configured to skip renaming then.

**Comment by samsonasik** [comment]
we are enforcing upgrade as possible, if there is usage for framework specific use case for this rule, the configured config already available for that :)
