### ISSUE TITLE
ClassPropertyAssignToConstructorPromotionRector could still promote a property even if the variable is used in the constructor

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#8556]
# Feature Request

I noticed some properties that were not promoted by this Rector because the variable was used in the constructor in a way. But these could be replaced by a `$this->` version.

Currently, it does nothing, see : https://getrector.com/demo/baa551a6-a2c9-4de6-9923-ca81dfedf7cf
 
## Diff 

The code could be replaced by Rector as such : 

```diff
<?php

final class DemoFile
{
-    private string $value;
-
-    public function __construct(string $value)
+    public function __construct(private string $value)
    {
-        assert(in_array($value, ['in', 'out'], strict: true));
+        assert(in_array($this->value, ['in', 'out'], strict: true));        
-        $this->value = $value;
    }
}
```

**Comment by samsonasik** [comment]
The rule is cover assign verify only, otherwise, marked as side effect, that's why it skipped.

Thank you for understanding.

**Comment by samsonasik** [comment]
This rule is only verify assignment, otherwise, it will become too complex to add, as that will require impure function call usage verify, and once we added, another requirement will continue add.

we may can add that improvement in the future, but not for current stage :)
