### ISSUE TITLE
Parent class return type is added which is breaking the code

### ISSUE THREAD

**Issue by nuryagdym** [rectorphp/rector#8557]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.3            |

From the example below, rector is adding return type to the parent method.
![image](https://github.com/rectorphp/rector/assets/26792980/b0ff3177-d229-4ebe-979f-bb908b8b381c)

As child can have different return type it is causing PHP error

## Minimal PHP Code Causing Issue

```php
<?php

abstract class ParentDemoFile
{
    protected function formatAmount(float $amount)
    {
        return $amount;
    }
}

 class DemoFile extends ParentDemoFile
{
    protected function formatAmount(float $amount): int
    {
        return (int) (\round($amount, 2) * 100);
    }
}
```

rector.php
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return RectorConfig::configure()
    ->withSets([
        LevelSetList::UP_TO_PHP_74,
    ])
    ->withSkip([
        // ALL of these rules doing the same breaking change
        //\Rector\TypeDeclaration\Rector\ClassMethod\NumericReturnTypeFromStrictScalarReturnsRector::class,
        //\Rector\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictScalarReturnExprRector::class,
        //\Rector\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictParamRector::class,
    ])
    ->withPreparedSets(
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    );
```

## Expected Behaviour

Do not break PHP code

**Comment by samsonasik** [comment]
There is use case that change abstract class's method is ok:

- https://getrector.com/demo/8c15a2a4-9fe6-410a-88d8-d746f8900673

which for most use case, the overridden method should follow the parent definition, it was introduced by PR:

- https://github.com/rectorphp/rector-src/pull/5344

we can rollback to skip inside abstract class, but need some consideration:

- why child class change behaviour of abstract class methods?
- how many use case that happen?

If the use case is small, eg: only on 1 or 2 use cases, I think you can simply skip it https://getrector.com/documentation/ignoring-rules-or-paths

**Comment by nuryagdym** [comment]
Child class can return more specific type, I don't think it is a rare case when child returns more specific type.

In my case I am build a request for different type of bank APIs, each can accept different amount format.

For example, for one bank I need to convert `12.56` to `1256`.

**Comment by samsonasik** [comment]
I see, it was possible due to we had child class detection, which verify if child class override return type. The issue was, child class detection is not reliable, so it dropped, but it left kept.

we have 2 options for it:

1. skip abstract class on `ClassMethodReturnTypeOverrideGuard` like original functionality
2. find a way to "preload" all classes very early, so they detected by phpstan reflection with all tree structure (possibly not possible, but if possible, will be very useful.

The safest thing seems option 1

**Comment by samsonasik** [comment]
Ref for possible way to get classes https://github.com/Roave/BetterReflection/blob/6.6.x/docs/usage.md#inspecting-code-and-dependencies-of-a-composer-based-project , and may need check with loop and calll `class_exists() || interface_exists() || trait_exists()` so phpstan autoload the class, ref

https://github.com/samsonasik/ci4-album/blob/8fd88b3f556f74c5923e0c21ecc73fa9d6601507/bootstrap.php#L19-L20

**Comment by samsonasik** [comment]
@TomasVotruba the possible way seems use `AggregateSourceLocator` on `Rector\NodeTypeResolver\Reflection\BetterReflection\SourceLocatorProvider\DynamicSourceLocatorProvider::provide()` something like:

```php
        $this->aggregateSourceLocator = new AggregateSourceLocator($sourceLocators);
        $reflector = new DefaultReflector($this->aggregateSourceLocator);
        foreach ($sourceLocators as $sourceLocator) {
            $classLikes = $sourceLocator->locateIdentifiersByType($reflector, new class extends IdentifierType {
                public function isClass(): bool
                {
                    return true;
                }
            });

            foreach ($classLikes as $classLike) {
                $classLikeName = $classLike->getName();

                // make autoload
                class_exists($classLikeName) || interface_exists($classLikeName) || trait_exists($classLikeName);
            }
        }
```

I will try create an experimental PR for it.

**Comment by TomasVotruba** [comment]
@samsonasik I think this is one of rule we'll have to apply on `final` classes only. It belongs to the same group as finalize classes - https://github.com/rectorphp/rector/issues/8439 and we'll never know what child classes extend it or not.

**Comment by samsonasik** [comment]
@TomasVotruba I think we need to find solution and trades-off first for that, while risky, add return type will benefit many, and most of the time, override method is not changing return type, mostly wider type.

We can possibly add option to `enable_on_final_class_only` for that, but I am thinking if that can be on last resort.
