### ISSUE TITLE
RenameParamToMatchTypeRector should not rename Exception parameter $previous

### ISSUE THREAD

**Issue by nuryagdym** [rectorphp/rector#8558]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.3         |

`\Exception` class's third parameter is `$previous` and when it is extended the parameter name should stay the same

![image](https://github.com/rectorphp/rector/assets/26792980/96b3dd77-bfd2-4ecd-9a90-073161781623)

## Minimal PHP Code Causing Issue

```php
<?php

class BankClassNullException extends \Exception
{
    public function __construct(string $message = 'Class must be specified!', int $code = 331, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
}
```

rector.php
```
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return RectorConfig::configure()
    ->withSets([
        LevelSetList::UP_TO_PHP_74,
    ])
    ->withSkip([
        // rule that is causing the change
        //\Rector\Naming\Rector\ClassMethod\RenameParamToMatchTypeRector::class
    ])
    ->withPreparedSets(
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    );
```

## Expected Behaviour

Don't change `$previous` parameter name in child classes of `\Exception`

**Comment by samsonasik** [comment]
I think you can simply skip it for your use case and needs https://getrector.com/documentation/ignoring-rules-or-paths

Thank you for understanding.
