### ISSUE TITLE
 "Reached system errors count limit of 50, exiting..."

### ISSUE THREAD

**Issue by alex7070m** [rectorphp/rector#8559]
Hello!

I set the following parallel parameters:

return static function(RectorConfig $rectorConfig): void {
    //
    $rectorConfig->parallel(180, 2, 10);

I'm trying to process a large PHP file (16 thousand lines) and I get errors:

  [ERROR] Could not process
          "C:\Users\alexa\www\someproject\vendor\rector\rector\vendor\symplify\easy-parallel\src\ValueObject\ParallelPro

          "Child process timed out after 120 seconds". On line: 108

          "Reached system errors count limit of 50, exiting...".

What needs to be changed to process my file?

Is it possible to increase the errors count limit somewhere? Thanks

**Comment by samsonasik** [comment]
16000 lines seems quite large file. You may need to `disableParallel()`, and try reduce applied rules, to found the possible bottlenect.

You need to invest time to narrow down rules half by half until it found the minimal rule(s) that cause it,
and the expected output.

Read this post: https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

I am closing it as it won't go anywere unless it reproducible.

Try learn debugging, slowly, no need to spam question every issue you found.
