### ISSUE TITLE
 [ERROR] Class "Rector\Core\Rector\AbstractRector" not found    

### ISSUE THREAD

**Issue by bphmigas** [rectorphp/rector#8560]
# Bug Report

 [ERROR] Class "Rector\Core\Rector\AbstractRector" not found    

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.0.0 (invoke `vendor/bin/rector --version`)             |
"rector/rector": "^1.0",
"rector/rector-phpoffice": "^0.14.0",
"phpoffice/phpspreadsheet": "^1.29",

I follow this instructions
https://github.com/PHPOffice/PhpSpreadsheet/blob/master/docs/topics/migration-from-PHPExcel.md
<img width="1624" alt="image" src="https://github.com/rectorphp/rector/assets/127707886/7123d984-0066-4bf8-a636-9ab94227369f">

but error like this
<img width="682" alt="image" src="https://github.com/rectorphp/rector/assets/127707886/ec94f4e6-f3fd-4ff3-bc8d-904d68c03789">

## Minimal PHP Code Causing Issue

"php": "^8.2",

## Expected Behaviour

should Rector change the code

**Comment by samsonasik** [comment]
`rector-phpoffice` is abandoned, see https://github.com/rectorphp/rector-phpoffice message header.

, you may need to request to phpspreadsheet repo to let the author/maintainer take over/fork it

https://github.com/PHPOffice/PhpSpreadsheet/issues :)
