### ISSUE TITLE
Parallel configuration does not work correctly

### ISSUE THREAD

**Issue by alex7070m** [rectorphp/rector#8562]
Hello! My parallel configuration says:

return static function(RectorConfig $rectorConfig): void {
    //
    $rectorConfig->parallel(3600, 16, 16);
};

However, an error occurs:

    "Child process timed out after 120 seconds". On line: 108

But according to the configuration, such error can only occur after 3600 seconds?

**Comment by samsonasik** [comment]
I can't reproduce, we use rector in big project with 5000+ files, with many files with 4000+ lines, working fine with tweaked parallel config, again, we need full config and/or reproducible repo for it, otherwise, nothing we can do.

Please stop spamming, back to learning on debugging.
