### ISSUE TITLE
Incorrect behavior of ChildDoctrineRepositoryClassTypeRector 

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8569]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.3             |

Rector is adding a generic type as return type declaration:

```
1 file with changes
===================
1) src/ExtendedEntityRepository.php:34
    ---------- begin diff ----------
@@ @@
      *
      * @return T
      */
-    public function findOneByOrThrow(array $conditions) {
+    public function findOneByOrThrow(array $conditions): ?T {
         $entity = $this->findOneBy($conditions);
         if ($entity === null) {
    ----------- end diff -----------
Applied rules:
 * ChildDoctrineRepositoryClassTypeRector
```

## Minimal PHP Code Causing Issue

The bug doesn't get triggered in the demo sandbox, unfortunately, but here's the code: https://getrector.com/demo/c6a5e684-b19a-4873-8047-cf43b809c207

If need be, I can try to construct a full reproduction repository.

## Expected Behaviour

No changes.

**Comment by samsonasik** [comment]
@jlherren is this happen on `"rector/rector": "dev-main"` as well? If yes, simple reproducible repo is needed then, thank you.

**Comment by TomasVotruba** [comment]
Thanks for reporting @jlherren 
The demo did not pick up the rule, because the `Doctrine\ORM\EntityRepository` class was missing there: https://getrector.com/demo/5a25bf0c-adcf-4ec5-ad3d-ce0764e53981

Fixed in https://github.com/rectorphp/rector-src/pull/5746
