### ISSUE TITLE
Incorrect behavior of ReturnNeverTypeRector

### ISSUE THREAD

**Issue by micaherne** [rectorphp/rector#8570]
# Bug Report

Rector appears to add a never return type to a base class even when there are subclasses which return something. I'm reluctant to call this a bug as the original code is so terrible, but the fact is that Rector is changing something that will run in PHP 8 to something that will throw a fatal error.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/5e741063-cd01-493c-a9c9-60aeb1146a3a

```php
<?php
class A {
    public function foo() {
        throw new \Exception("method must be overridden");
    }
}

class B extends A {
    public function foo() {
        return "string";
    }
}
```

### Responsible rules

* `ReturnNeverTypeRector`

## Expected Behavior

Rector should either skip the code or ensure that the return type added to the base class is compatible with any subclasses.

**Comment by samsonasik** [comment]
I am reworking child class detection on PR:

- https://github.com/rectorphp/rector-src/pull/5735

just currently busy on other things :)

**Comment by samsonasik** [comment]
Resolved by PR:

- https://github.com/rectorphp/rector-src/pull/5735

Ref https://getrector.com/demo/7780b01d-f5e9-4f0f-87c7-4c58557cd96d
