### ISSUE TITLE
How to use disableParallel() with RectorConfig::configure()?

### ISSUE THREAD

**Issue by BenMorel** [rectorphp/rector#8572]
I'm upgrading rector from `0.19` to `1.0`. So far we were using the Closure configuration:

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);

    if (($_ENV['GITLAB_CI'] ?? null) === 'true') {
        $rectorConfig->disableParallel();
    }

    $rectorConfig->rules([
        RemoveUnusedPrivatePropertyRector::class,
        ReadOnlyClassRector::class,
        ReadOnlyPropertyRector::class,
        StaticDataProviderClassMethodRector::class,
    ]);
};
```

I'd like to convert this to `RectorConfig::configure()`, as this seems to be the new way to configure rector.

However, I noticed that `disableParallel()` is not available on `RectorConfigBuilder`:

```php
$rectorConfig = RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->withRules([
        RemoveUnusedPrivatePropertyRector::class,
        ReadOnlyClassRector::class,
        ReadOnlyPropertyRector::class,
        StaticDataProviderClassMethodRector::class,
    ]);

if (($_ENV['GITLAB_CI'] ?? null) === 'true') {
    $rectorConfig->disableParallel(); // method not found in RectorConfigBuilder
}

return $rectorConfig;
```

Is this intentional? Did I miss something?

**Comment by samsonasik** [comment]
There is `withoutParallel()` for that, see

https://github.com/rectorphp/rector/blob/c59507a9090b465d65e1aceed91e5b81986e375b/src/Configuration/RectorConfigBuilder.php#L443-L447

**Comment by BenMorel** [comment]
Not sure how I could miss that :flushed:

Thank you, @samsonasik!

**Comment by samsonasik** [comment]
I updated documentation for it ;) https://getrector.com/documentation/troubleshooting-parallel
