### ISSUE TITLE
first-class-callable-syntax is not allow on property

### ISSUE THREAD

**Issue by oleg-andreyev** [rectorphp/rector#8578]
## Problem

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.19.8             |

![image](https://github.com/rectorphp/rector/assets/1244112/587f5151-605f-4685-8dc4-553b61de0ef2)
![image](https://github.com/rectorphp/rector/assets/1244112/948ff982-31e6-489a-a33c-276b5c6092af)

## Minimal PHP Code Causing Issue

https://getrector.com/demo/829e7f19-0ecc-4e09-8e18-071a93beac37

## Expected Behaviour

Rector should skip it.

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by samsonasik** [comment]
Could you also create a patch for it, here the steps:

1. Create a fixture test under https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php81/Rector/Array_/FirstClassCallableRector/Fixture with `skip_` prefix fixture, you can see other example fixture
2. Create a patch, basically, it needs to be skipped under `ClassConst` and `Property` so you can add to `getNodeTypes()` before `Array_`

```diff
    public function getNodeTypes(): array
    {
-        return [Array_::class];
+        return [\PhpParser\Node\Stmt\ClassConst::class, \PhpParser\Node\Stmt\Property::class, Array_::class];
```

then, on `refactor()`, verify first to return early:

```diff
    /**
-     * @param Array_ $node
+     * @param \PhpParser\Node\Stmt\ClassConst|\PhpParser\Node\Stmt\Property|Array_ $node
     */
-    public function refactorWithScope(Node $node, Scope $scope): null|StaticCall|MethodCall
+    public function refactorWithScope(Node $node, Scope $scope): null|StaticCall|MethodCall|int
    {
+         if ($node instanceof  \PhpParser\Node\Stmt\ClassConst || $node \PhpParser\Node\Stmt\Property) {
+               return \PhpParser\NodeTraverser::DONT_TRAVERSE_CURRENT_AND_CHILDREN;
+.       }       
```

above is pseudo code, but you have the idea ;)
