### ISSUE TITLE
Misbehavior by ExplicitReturnNull rule 

### ISSUE THREAD

**Issue by KorDum** [rectorphp/rector#8586]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.4            |

If a method does not have an explicit return value type and there is a try-return-finally construct in the code, rector suggests adding `return null` through the `ExplicitReturnNull` rule. If you specify an explicit return type, there is no error. Unfortunately, in my code I cannot specify the return type explicitly because of some peculiarities.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/c753eba9-6a70-492c-9d87-9496d053ac1b

## Expected Behaviour

There is no error, rector should skip it.

**Comment by samsonasik** [comment]
That is expected, if no return in root last stmt, then add return null, except on finally, you specify return as well, see https://getrector.com/demo/a9aa21cf-63ad-4593-9d43-5e9328ebcc38

You can skip the rule if that not what you want https://getrector.com/documentation/ignoring-rules-or-paths

**Comment by KorDum** [comment]
This is incorrect behaviour, see example:
```php
final class ExampleTest extends UnitTestCase
{
    public function testExample(): void
    {
        $result = $this->example();

        $this->assertSame(1, $result); // Failed asserting that null is identical to 1.
    }

    private function example()
    {
        try {
            return 1;
        } finally {
            return null;
        }
    }
}
```
Rector changes the behavior of the code, making it incorrect.

**Comment by samsonasik** [comment]
I see, reopen then.
