### ISSUE TITLE
Rule to rewrite `$arr['idx'] += $value` to `$arr['idx'] = ($arr['idx'] ?? null) + $value` to avoid Undefined index error

### ISSUE THREAD

**Issue by eduard-sukharev** [rectorphp/rector#8588]
# Feature Request

There is an **Undefined index error** in cases when there's an attempt to increment/decrement/multiply/divide the value array offset to/by some other value, and when no such array offset exists:
```php
$arr = [];
$arr['idx'] += 42;
```
This is applicable to `-=`, `+=`, `/=`, `*=` (and probably their respectful postfix forms?)

## Diff 

```diff
$arr = [];
-$arr['idx'] += 42;
+$arr['idx'] = ($arr['idx'] ?? null) + 42;
```

**Comment by samsonasik** [comment]
I am closing it as rector is not error handler, however, you can create custom rule for that, thank you for understanding.

**Comment by eduard-sukharev** [comment]
This is a proposal to make a rule that fixes a Notice that becomes a Warning starting php8.0. I suppose adding this rule to rector makes it less painful to migrate from previous versions. And from my perspective, it is more useful than, for example, a `ArraySpreadInsteadOfArrayMergeRector` rule - it makes migration less painful.

**Comment by samsonasik** [comment]
PhpParser don't verify logic code, it only throw on syntax error, so can't decide if there is logic error. I see that php 7 and php 8 has different notice vs warning usage.

I suggest to use dedicated error handler for that, for example, if you use laminas, you can see my ErrorHeroModule https://github.com/samsonasik/ErrorHeroModule
