### ISSUE TITLE
Upgrade each method inside a while loop to foreach

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#8589]
# Bug Report

Currently the listeach method does not work inside a while loop. I think best would be to migrate it to a foreach.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/10c9ef9e-a3b7-4bd0-8155-5e5a303a595b

## Expected Behaviour

```diff
-        while (list($name, $value) = each($directives)) {
+        foreach ($directives as $name => $value) {
        }
```

**Comment by samsonasik** [comment]
there is `WhileEachToForeachRector` for that, see https://getrector.com/demo/4463859b-c999-4395-9dad-337716714b3a
