### ISSUE TITLE
JSON output formatter outputs invalid JSON

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#8590]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.4            |

When I run Rector with `--output-format=json` it outputs JSON which has literal new lines. Valid JSON cannot have literal newlines, it should be all one line with `\n` instead of newlines.

## Minimal PHP Code Causing Issue

n/a

## Expected Behaviour

Outputs valid JSON

**Comment by samsonasik** [comment]
Could you create failing test case or repoducible repo with step by step and expected vs actual result of it ? thank you.

**Comment by canvural** [comment]
Looks like this is an issue on my end. Sorry for the noise 😅
