### ISSUE TITLE
Mysql to Mysqli migration rector

### ISSUE THREAD

**Issue by Manishrawatarcnet** [rectorphp/rector#8592]
# Question
i want mysql_connect() to mysqli_connect() change function need with rector php
 still :    $this->link = @mysql_connect($this->host, $this->user, $this->password);
need : $this->link = @mysqli_connect($this->host, $this->user, $this->password);

**Comment by samsonasik** [comment]
The mysql set is removed, see 

- https://github.com/rectorphp/rector-src/pull/4448 

for the reasoning.
