### ISSUE TITLE
Incorrect behavior of AssertCompareToSpecificMethodRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8593]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a2c93c41-3204-4ef7-ace6-e8d03300c6ca

```php
<?php

use PHPUnit\Framework\TestCase;

final class DemoFile extends TestCase {
    private function testSomething($handle) {
        self::assertSame('resource', gettype($handle));
    }
}
```

### Responsible rules

* `AssertCompareToSpecificMethodRector`

## Expected Behavior

Rector changes the code to use `assertInternalType()`, but this method has been [deprecated in PHPUnit 8](https://github.com/sebastianbergmann/phpunit/issues/3369) and [removed in PHPUnit 9](https://github.com/sebastianbergmann/phpunit/issues/3370).

Rector should transform code to the [the new assert methods](https://github.com/sebastianbergmann/phpunit/issues/3368) (also see the [assertions about closed resources](https://github.com/sebastianbergmann/phpunit/pull/4365)).

**Comment by samsonasik** [comment]
I think the rule is fine, it just need another rule to change deprecated assertInternal* under phpunit80 config set, set continuation change will apply based on version applied.

**Comment by TomasVotruba** [comment]
Thanks for reporting!

Looking at PHPUnit change back and forth, I think the best way is to skip `gettype()` as it would work only for a year :)
Fixed in: https://github.com/rectorphp/rector-phpunit/pull/337
