### ISSUE TITLE
Incorrect behaviour of FirstClassCallableRector with __invoke

### ISSUE THREAD

**Issue by AJDurant** [rectorphp/rector#8594]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 1.0.4             |

`[InvokableClass::class, '__invoke']` in incorrectly transformed to `InvokableClass::_invoke(...)`

## Minimal PHP Code Causing Issue

I can't get a working reproducer in the demo (https://getrector.com/demo/83d1ad6a-3aa8-4238-916d-8a76bf2e3050), but the original code that produced this was in Laravel:
```php
    Route::get('verify-email', [EmailVerificationPromptController::class, '__invoke'])
        ->name('verification.notice');
```

## Expected Behaviour

It should become `(new InvokableClass())(...)`

I updated my code to:
```php
    Route::get('verify-email', (new EmailVerificationPromptController())(...))
        ->name('verification.notice');
```

**Comment by samsonasik** [comment]
reproduced at https://getrector.com/demo/4ca36426-9ab7-419c-b418-2ed7fa734623

**Comment by AJDurant** [comment]
Thanks @samsonasik!

Sorry I forgot to mention the reason I reported it was getting the "Non-static method A::__invoke() cannot be called statically" error.
