### ISSUE TITLE
RenameClass not working

### ISSUE THREAD

**Issue by MauroVinicius** [rectorphp/rector#8596]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| v1.0.4 | Rule RenameClassRector not working             |

When using RenameClassRector to rename a class the rule is not working

## Minimal PHP Code Causing Issue

https://getrector.com/demo/be9640d4-64b7-4b7b-ae29-233045ec61b8

## Expected Behaviour

Rename class DemoFile to SomeNewClass

**Comment by samsonasik** [comment]
`RenameClassRector` is only rename reference, not `class ClassName` name, as it break autoload, see these PRs for references:

- https://github.com/rectorphp/rector-src/pull/5487
- https://github.com/rectorphp/rector-src/pull/5488

**Comment by MauroVinicius** [comment]
I understand, in this case I believe it would be better to change the name of this class, instead of calling it `RenameClassRector` it would be better to change it to `RenameClassReferenceRector`, this way it is easier to understand what this rule does in the rector

**Comment by MauroVinicius** [comment]
@samsonasik I understand, in this case I believe it would be better to change the name of this class, instead of calling it RenameClassRector it would be better to change it to RenameClassReferenceRector, this way it is easier to understand what this rule does in the rector
