### ISSUE TITLE
Incorrect behavior of NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8597]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/64b4ea05-a489-4aad-b421-60f22fb9c94e

```php
<?php

final class DemoFile {
    public function getTitle(string $html): string {
        $dom = new DOMDocument();
        $dom->loadHTML($html);
        $titleElement = $dom->getElementsByTagName('title')->item(0);
        return $titleElement?->nodeValue !== null ? trim($titleElement->nodeValue) : 'Unnamed document';
    }
}
```

### Responsible rules

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

No change.

The value passed to `trim()` is always a string due to the null check. After adding the cast to string, [PHPStan starts to complain](https://phpstan.org/r/67f93f6e-8da0-461a-96b9-0ca9171296ea) (strict rules only).

**Comment by samsonasik** [comment]
The issue seems exists even on normal `if else` https://getrector.com/demo/dcde4cb6-7d5e-4989-853a-824dbde409af

reproduced in phpstan demo https://phpstan.org/r/c3b12b3c-2b2a-437b-a52c-6cf73cbfb154
