### ISSUE TITLE
[ERROR] Could not process  due to "System error: "Undefined constant "RepoName\Shell\CONSTANT_NAME""

### ISSUE THREAD

**Issue by pankaj-a-kumar** [rectorphp/rector#8603]
[ERROR] Could not process                                                                                              
         "repo-name/cakephp/app/plugins/RepoName/src/Shell/MyShell.php"     
         file, due to:                                                                                                  
         "System error: "Undefined constant "RepoName\Shell\CONSTANT_NAME""                                          
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(276): [constant expression]()               
         #1 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(276): defined('RepoName\\Shel...')        
         #2 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(209):                                       
         Rector\PhpParser\Node\Value\ValueResolver->resolveClassConstFetch(Object(PhpParser\Node\Expr\ClassConstFetch)) 
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(131):                     
         Rector\PhpParser\Node\Value\ValueResolver->Rector\PhpParser\Node\Value\{closure}(Object(PhpParser\Node\Expr\Cl 
         assConstFetch))                                                                                                
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(96):                      
         PhpParser\ConstExprEvaluator->evaluate(Object(PhpParser\Node\Expr\ClassConstFetch))                            
         #5 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(184):                                       
         PhpParser\ConstExprEvaluator->evaluateDirectly(Object(PhpParser\Node\Expr\ClassConstFetch))                    
         #6 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(119):                                       
         Rector\PhpParser\Node\Value\ValueResolver->resolveExprValueForConst(Object(PhpParser\Node\Expr\ClassConstFetch 
         ))                                                                                                             
         #7 vendor/rector/rector/src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php(144):                    
         Rector\PhpParser\Node\Value\ValueResolver->getValue(Object(PhpParser\Node\Expr\ClassConstFetch))               
         #8 vendor/rector/rector/src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php(180):                    
         Rector\NodeCollector\NodeAnalyzer\ArrayCallableMethodMatcher->resolveClassContextType(Object(PhpParser\Node\Ex 
         pr\ClassConstFetch), Object(PHPStan\Analyser\MutatingScope), NULL)                                             
         #9 vendor/rector/rector/src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php(77):                     
         Rector\NodeCollector\NodeAnalyzer\ArrayCallableMethodMatcher->resolveCallerType(Object(PhpParser\Node\Expr\Cla 
         ssConstFetch), Object(PHPStan\Analyser\MutatingScope), NULL)                                                   
         #10 vendor/rector/rector/rules/Php81/Rector/Array_/FirstClassCallableRector.php(90):                           
         Rector\NodeCollector\NodeAnalyzer\ArrayCallableMethodMatcher->match(Object(PhpParser\Node\Expr\Array_),        
         Object(PHPStan\Analyser\MutatingScope))                                                                        
         #11 vendor/rector/rector/src/Rector/AbstractScopeAwareRector.php(27):                                          
         Rector\Php81\Rector\Array_\FirstClassCallableRector->refactorWithScope(Object(PhpParser\Node\Expr\Array_),     
         Object(PHPStan\Analyser\MutatingScope))                                                                        
         #12 vendor/rector/rector/src/Rector/AbstractRector.php(136):                                                   
         Rector\Rector\AbstractScopeAwareRector->refactor(Object(PhpParser\Node\Expr\Array_))                           
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                         
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\Array_))                                    
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))                                      
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\TryCatch))                                    
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #21 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #22 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #23 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #24 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #25 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #26 vendor/rector/rector/src/Application/FileProcessor.php(111):                                               
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                            
         #27 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):                                    
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),                     
         Object(Rector\ValueObject\Configuration))                                                                      
         #28 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):                                    
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),          
         Object(Rector\ValueObject\Configuration))                                                                      
         #29 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(138):                                    
         Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),     
         Object(Closure), Object(Closure))                                                                              
         #30 vendor/rector/rector/src/Console/Command/ProcessCommand.php(117):                                          
         Rector\Application\ApplicationFileProcessor->run(Object(Rector\ValueObject\Configuration),                     
         Object(RectorPrefix202404\Symfony\Component\Console\Input\ArgvInput))                                          
         #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Console\Command\ProcessCommand->execute(Object(RectorPrefix202404\Symfony\Component\Console\Input\ArgvI 
         nput), Object(RectorPrefix202404\Symfony\Component\Console\Output\ConsoleOutput))                              
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(960):                                          
         RectorPrefix202404\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202404\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202404\Symfony\Component\Console\Output\ConsoleOutput))           
         #33 vendor/rector/rector/vendor/symfony/console/Application.php(333):                                          
         RectorPrefix202404\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\ProcessCo 
         mmand), Object(RectorPrefix202404\Symfony\Component\Console\Input\ArgvInput),                                  
         Object(RectorPrefix202404\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #34 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202404\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202404\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202404\Symfony\Component\Console\Output\ConsoleOutput))             
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(216):                                          
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202404\Symfony\Component\Console\Input\ArgvInput), 
         Object(RectorPrefix202404\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #36 vendor/rector/rector/bin/rector.php(130): RectorPrefix202404\Symfony\Component\Console\Application->run()  
         #37 vendor/rector/rector/bin/rector(5): require_once('/...')                                     
         #38 vendor/bin/rector(119): include('/...')                                                      
         #39 {main}". On line: 15

**Comment by samsonasik** [comment]
Could you create reproducible repo for it? Thank you.

**Comment by samsonasik** [comment]
It seems you're using cakephp, I suggest to ensure autoload correctly defined

https://getrector.com/documentation/static-reflection-and-autoload

If the issue persist, please reopen with minimal reproducible repo with step by step to reproduce it.
