### ISSUE TITLE
[Bug] Functions with comments are being converted to short functions

### ISSUE THREAD

**Issue by dbpolito** [rectorphp/rector#8606]
This ended up generating invalid code...

![image](https://github.com/rectorphp/rector/assets/347400/b27879c5-e837-463b-835a-3ae86f3aee4b)

**Comment by samsonasik** [comment]
That seems still valid code, `@var` should working fine with Arrow Function Expr, to be kept there. What error you got? Could you create reproducible at https://getrector.com/demo ?

**Comment by dbpolito** [comment]
Oh it is valid, interesting, it seems VS Code with InteliPhense doesn't like it... nvm... sorry for bothering you... i will move this ticket there i think...

Thanks...

**Comment by yusufkandemir** [comment]
Yes, it's valid in terms of syntax and runtime behavior. But it's not recognized by either PHP Intelephense or PHPStan(https://github.com/phpstan/phpstan/issues/3770), making the comment ineffective. So, I'd expect it not to convert it to a short function if a PHPDoc comment is detected by default, or at least through a configuration.

So, the only possible way now seems to disable it for a given file:
```php
use Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector;
// ...
->withSkip([
    ClosureToArrowFunctionRector::class => [
        __DIR__ . '/app/whatever.php',
    ],
]);
```
