### ISSUE TITLE
OptionalParametersAfterRequiredRector not making all replacements

### ISSUE THREAD

**Issue by erikpb** [rectorphp/rector#8608]
# Question
I'm upgrading a very large codebase from PHP 7.4 to 8.0 using Rector. When I run Rector with `withSets([SetList::PHP_80])` , the rule `OptionalParametersAfterRequiredRector` is missing certain function calls. However when I run Rector with just `withRules([OptionalParametersAfterRequiredRector::class])` it is picking up all function calls.
Is there a memory requirement or other limit that could be causing this? It's running on a Mac M1 in Docker with resources of 4 CPUs and 8GB.

PS: Really enjoyed Tomas' talk at Laracon Amsterdam!

**Comment by samsonasik** [comment]
For `FuncCall` support, I created PR https://github.com/rectorphp/rector-src/pull/5835 for it, for "not picking all", that maybe due to autoload, you can read the doc https://getrector.com/documentation/static-reflection-and-autoload so phpstan know the FunctionReflection of it.

**Comment by erikpb** [comment]
Thank you. The weird thing is that it works fine when the rule is run by itself but not if it's run as part of set, like PHP_80 set.

**Comment by samsonasik** [comment]
@erikpb feel free to provide simple reproducible repo so it can be covered 👍
