### ISSUE TITLE
`LiteralGetToRequestClassConstantRector` won't work on `KernelBrowser` using Symfony 5+

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#8613]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.4             |
| symfony/http-kernel | v6.4.6 |

Looks like the bugfix in #7135 prevents updating my tests on a Symfony 6.4 project.
The `HttpKernel\Client` class [got removed in `symfony/http-kernel` v5.0.0.](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpKernel/CHANGELOG.md#500). Now it's impossible to reach the needed path of execution.

https://github.com/rectorphp/rector-symfony/blob/b8126e8bf6e239fd53329fcd715ea117a4b4c34c/rules/CodeQuality/Rector/MethodCall/LiteralGetToRequestClassConstantRector.php#L78-L85

By removing the check for that class, it starts refactoring as expected. 

```diff
         // for client, the transitional dependency to browser-kit might be missing and cause fatal error on PHPStan reflection
         // in most cases that should be skipped, @changelog https://github.com/rectorphp/rector/issues/7135
         if (
-            $this->reflectionProvider->hasClass('Symfony\Component\BrowserKit\AbstractBrowser') &&
-            $this->isObjectType($node->var, new ObjectType('Symfony\Component\HttpKernel\Client'))
+            $this->reflectionProvider->hasClass('Symfony\Component\BrowserKit\AbstractBrowser')
         ) {
             return $this->refactorClientMethodCall($node);
         }
```

I love using Rector :heart: 

## Minimal PHP Code Causing Issue

(copied from https://symfony.com/doc/current/testing.html#write-your-first-application-test)

```php
// tests/Controller/PostControllerTest.php
namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class PostControllerTest extends WebTestCase
{
    public function testSomething(): void
    {
        // This calls KernelTestCase::bootKernel(), and creates a
        // "client" that is acting as the browser
        $client = static::createClient();

        // Request a specific page
        $crawler = $client->request('GET', '/');

        // Validate a successful response and some content
        $this->assertResponseIsSuccessful();
        $this->assertSelectorTextContains('h1', 'Hello World');
    }
}
```

## Expected Behaviour

```diff
          // Request a specific page
-         $crawler = $client->request('GET', '/');
+         $crawler = $client->request(Request::METHOD_GET, '/');
```

**Comment by samsonasik** [comment]
What is `static::createClient())` return?

**Comment by mvhirsch** [comment]
> What is static::createClient() return?

Since [Symfony 4.3](https://github.com/symfony/symfony/blob/43688482bc01c40ec421ff9552e1455df460d3f3/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php#L39) (up to 7.1) it returns an instance of `Symfony\Bundle\FrameworkBundle\KernelBrowser`

**Comment by samsonasik** [comment]
I think both `Symfony\Component\HttpKernel\Client` + `Symfony\Bundle\FrameworkBundle\KernelBrowser` should be supported, so check `isObjectType()` with `||` for both objects support is needed, is that works?, eg:

```php
if (
         $this->reflectionProvider->hasClass('Symfony\Component\BrowserKit\AbstractBrowser') &&
(            

     $this->isObjectType($node->var, new ObjectType('Symfony\Component\HttpKernel\Client'))

     ||

  $this->isObjectType($node->var, new ObjectType('Symfony\Bundle\FrameworkBundle\KernelBrowser'))

)
      
         ) {
```
