### ISSUE TITLE
Wrong documentation for `FinalizeTestCaseClassRector`

### ISSUE THREAD

**Issue by DerpgonCz** [rectorphp/rector#8616]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.4                                                           |

## Issue
The documentation (https://github.com/rectorphp/rector/blob/main/rules/Privatization/Rector/Class_/FinalizeTestCaseClassRector.php) clearly shows how the code is edited. It adds the `final` keyword before a `use` statement, however the real behavior is adding the `final` keyword before the `class` keyword.

This confused me at first as I was wondering if this is a new feature.

## Expected Behaviour
The documentation should show adding the keyword before the `class` keyword, not the `use` keyword.

This could also be a bug with the existing code, but I am not sure as I do not understand these constructs.

**Comment by samsonasik** [comment]
Could you try provide a patch PR? You can edit https://github.com/rectorphp/rector-src/blob/cc4b63fe261a39b55b621e426d87346042412741/rules/Privatization/Rector/Class_/FinalizeTestCaseClassRector.php#L41 and run `composer docs` to regenerate docs

Thank you.
