### ISSUE TITLE
AllowDynamicProperties rule works not as expected

### ISSUE THREAD

**Issue by renakdup** [rectorphp/rector#8617]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.0.0 (invoke `vendor/bin/rector --version`)             |

I added rule 
```
->withRules([
        \Rector\Transform\Rector\Class_\AddAllowDynamicPropertiesAttributeRector::class
	])
```
to analyze and fix deprecation issues with Dynamic Properties of objects. But looks that it didn't analyze code and just add `#[AllowDynamicProperties]`  for all classes that do not fit these conditions: 

```
final class AddAllowDynamicPropertiesAttributeRector ... {
//.....
    private function shouldSkip(Class_ $class) : bool
    {
        if ($this->isDescendantOfStdclass($class)) {
            return \true;
        }
        if ($this->hasNeededAttributeAlready($class)) {
            return \true;
        }
        if ($this->hasMagicSetMethod($class)) {
            return \true;
        }
...
```

## Expected Behaviour

Expected that the check would analyze tokens and identify of using dynamic properties instead of add it for all classes.

**Comment by renakdup** [comment]
Yes sure, https://getrector.com/demo/5271e231-81e3-4871-84fa-5ff6ceec1b11

**Comment by samsonasik** [comment]
That's expected, we don't check "the usage" of object. The rule is for transformation of possible `$obj->dynamicProp`, which no property also means possible has dynamic prop,  you can configure to only transform on specific namespace

https://github.com/rectorphp/rector-src/blob/57275efac450b9b0466e9dc934d3c07e2e9a1e43/rules/Transform/Rector/Class_/AddAllowDynamicPropertiesAttributeRector.php#L65
