### ISSUE TITLE
documentation for withPHPStanConfigs()

### ISSUE THREAD

**Issue by SebSept** [rectorphp/rector#8625]
# Question

I can't find any documentation for this configuration, `withPHPStanConfigs`.

`RectorConfig::configure()->withPHPStanConfigs([__DIR__.'/phpstan.neon'])`

What does it do/provides ?

**Comment by samsonasik** [comment]
This is documented on the code

https://github.com/rectorphp/rector/blob/582a864f3396fe13f519ed25dac9126229fc3fd9/src/Config/RectorConfig.php#L126

**Comment by SebSept** [comment]
Sure, but what does that mean concretely? That Rector will modify code according to some phpstan rules ?
Do you have an example ?

**Comment by samsonasik** [comment]
For example, you have phpstan config to activate `parent` attribute from a Node, you need to enable `nodeConnectingVisitorCompatibility`, which default is disabled on rector.

https://github.com/rectorphp/rector/blob/efb3c476c700fdd3a3a61819c4d1a6fdda91e741/config/phpstan/static-reflection.neon#L5

so you can enable it by setting it to true:

```diff
parameters:
    featureToggles:
-        nodeConnectingVisitorCompatibility: false
+        nodeConnectingVisitorCompatibility: true
```

Then, you should can call:

```php
$node->getAttribute('parent');
```
