### ISSUE TITLE
missing native array typehint

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8627]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.0.0 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/45658bf6-99fd-457d-9601-4a9d496c12b3

## Expected Behaviour

I wonder why none of the `typeDeclaration`-rules adds a native `array` property type for `private $exitcodeLabels;` in this code

**Comment by staabm** [comment]
ok, let me debug `TypedPropertyFromStrictConstructorRector `

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-src/pull/5861 already.
