### ISSUE TITLE
ForRepeatedCountToOwnVariableRector put php code outside open php tag

### ISSUE THREAD

**Issue by allanforms** [rectorphp/rector#8628]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| ForRepeatedCountToOwnVariableRector | 1.0.4             |

ForRepeatedCountToOwnVariableRector detected a correction on the following code
```
		</tr>

		<?php
		for ($i = 0; $i < count($arrlinks); $i++) { ?>
			<tr bgcolor="#FFFFFF">
```

and corrected to this

```
		</tr>

		
$counter = count($arrlinks);<?php
		for ($i = 0; $i < $counter; $i++) { ?>
			<tr bgcolor="#FFFFFF">
```

## Expected Behaviour

I thought it would make something like this
```
	</tr>

		
<?php $counter = count($arrlinks);
		for ($i = 0; $i < $counter; $i++) { ?>
			<tr bgcolor="#FFFFFF">
```
or this
```
		</tr>

		<?php
$counter = count($arrlinks);
		for ($i = 0; $i < $counter; $i++) { ?>
			<tr bgcolor="#FFFFFF">
```
or this
```
		</tr>

<?php
$counter = count($arrlinks);
		for ($i = 0; $i < $counter; $i++) { ?>

**Comment by samsonasik** [comment]
That expected drawback of mix PHP+HTML, you need to verify manually on that, see https://github.com/rectorphp/rector?tab=readme-ov-file#may-cause-unexpected-output-on-file-with-mixed-phphtml-content
