### ISSUE TITLE
error running process

### ISSUE THREAD

**Issue by zac1** [rectorphp/rector#8632]
# Question
I'm using plain PHP and wish to upgrade it to a leter version but when I run rector process --dry-run:
Getting the following error:
Argument 1 passed to Rector\Config\RectorConfig::{closure}() must be an instance of                           
         Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator, instance of                  
         Rector\Config\RectorConfig given, called in                                                                   
         C:\wamp64\www\rector24\vendor\rector\rector\src\Config\RectorConfig.php on line 198      

I'm not using any PHP packages - is there a way I can sort this ?

**Comment by samsonasik** [comment]
It seems you are using old config, you can upgrade to latest version and new config, ensure rector installed on root project.

https://getrector.com/documentation

**Comment by zac1** [comment]
I used that link to install rector using composer. Is there another config that I need to download ?

**Comment by samsonasik** [comment]
No. Could you try reproduce the error at https://getrector.com/demo ?

**Comment by zac1** [comment]
I have followed the instructions again on the link you attached. I've just downloaded rector again using composer and when I try to run it from bin folder : vendor/bin/rector
I get the following message: The filename, directory name, or volume label syntax is incorrect.
I have used an older version of rector successfully in the past to get my code to PHP8 but now wish to upgrade further.

**Comment by samsonasik** [comment]
Based on your error, I guess you're on windows, ref https://stackoverflow.com/questions/24782826/the-filename-directory-name-or-volume-label-syntax-is-incorrect-inside-batch

if you're using powershell, try using command prompt (cmd) or bash for Windows, see known drawback https://github.com/rectorphp/rector/?tab=readme-ov-file#known-drawbacks

or try disable parallel:

```php
return RectorConfig::configure()
   //
   ->withoutParallel();
```

ref https://getrector.com/documentation/troubleshooting-parallel

If the issue persist, we may need reproducible repo, with github action enabled, so it can be look up.
