### ISSUE TITLE
Incorrect behavior of `MixedTypeRector`

### ISSUE THREAD

**Issue by maks-rafalko** [rectorphp/rector#8633]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/393aa099-ae74-4edc-a562-f65d5d2f1491

```php
<?php

interface FileFilter {}

class ConcreteFileFilter implements FileFilter {}

/**
 * @param ConcreteFileFilter|FileFilter $fileFilter
 */
function usesFileFilter(FileFilter $fileFilter) {}
```

### Change

```diff
@@ -4,7 +4,4 @@
 
 class ConcreteFileFilter implements FileFilter {}
 
-/**
- * @param ConcreteFileFilter|FileFilter $fileFilter
- */
 function usesFileFilter(FileFilter $fileFilter) {}
```

### Responsible rules

* `MixedTypeRector`

## Expected Behavior

No change is expected (Rector didn't remove phpdoc on 1.0.3, started removing on 1.0.4 and later)

**Comment by samsonasik** [comment]
The `@param` usage is invalid, as it use child and parent in union, which one invalidate another, choose one instead if you one to keep the doc, eg:

```php
@param ConcreteFileFilter $fileFilter
```

https://getrector.com/demo/019ddfd5-98e9-455a-80e6-044a4fa686a9

**Comment by maks-rafalko** [comment]
Let me ask a couple of questions:

1. why it's invalid? what rule this union type breaks? From static analysis point of view, everything is good: https://phpstan.org/r/09f93713-b38e-4255-90f3-cdb825f45307
2. is it `MixedTypeRector`'s job to decide to remove or not remove this param? It's a bit confusing cause this rule's description says "Change mixed docs type to mixed typed"

**Comment by samsonasik** [comment]
1. The `@param` is still invalid, even phpstan decide it is fine, that dead code, that will still be removed if you enable `deadCode` set list.
2. the `MixedTypeRector` indeed should not remove the doc if it not change the mixed type, I will add check for that.

**Comment by staabm** [comment]
fyi, phpstan normalized the phpdoc away: 
https://phpstan.org/r/177beddc-6dd6-47e8-afe2-0f852e05661d

so we could argue that the phpdoc is misleading and leads to wrong assumptions by the the dev
