### ISSUE TITLE
Internal error when adding return types with an ObjectType

### ISSUE THREAD

**Issue by simonschaufi** [rectorphp/rector#8641]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.5              |

I'm using rector to add return types to methods and this used to work with phpstan 1.10.67

The problem lies within ReflectionProviderStaticAccessor::getInstance as the internal instance is null at this point

See also the reported issue on phpstan but they blame rector for the error: https://github.com/phpstan/phpstan/issues/11045

## Minimal PHP Code Causing Issue

https://getrector.com/demo/873bfbb1-5cbc-4311-8ee2-e4e3af16621f

## Expected Behaviour

It should not break

**Comment by ondrejmirtes** [comment]
Alright, I might understand the problem now. Rector doesn't call ReflectionProviderAccessor but the error is called by doing `new ObjectType`.

The internal error wouldn't happen if PHPStan's ContainerFactory and DI Container was created prior to executing the configuration file.

Also: can you please post the full stack trace of the error?

**Comment by simonschaufi** [comment]
> Also: can you please post the full stack trace of the error?

How do I do that?

**Comment by samsonasik** [comment]
@simonschaufi I tried latest dev-main, it seems already resolved, with diff:

```diff

There was 1 failure:

1) Rector\Tests\TypeDeclaration\Rector\ClassMethod\AddReturnTypeDeclarationRector\AddReturnTypeDeclarationRectorTest::test with data set #2 ('/Users/samsonasik/www/rector-...hp.inc')
Failed on fixture file "null_with_object_type.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 class Demo extends FolderInterface
 {
-    public function create(string $fileName)
+    public function create(string $fileName): ?\Rector\Tests\TypeDeclaration\Rector\ClassMethod\AddReturnTypeDeclarationRector\Fixture\FileInterface
     {
 
     }
```

could you try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

and verify if it already resolved?

**Comment by samsonasik** [comment]
And actually, the `AddReturnTypeDeclarationRector` is designed to add return type on `Class_`, not interface, I add test to add returns on class instead in latest rector dev-main above.

**Comment by simonschaufi** [comment]
> And actually, the `AddReturnTypeDeclarationRector` is designed to add return type on `Class_`, not interface, I add test to add returns on class instead in latest rector dev-main above.

I've also noticed that. Sorry for the wrong code example

**Comment by simonschaufi** [comment]
> @simonschaufi I tried latest dev-main, it seems already resolved, with diff:
> and verify if it already resolved?

yes, latest rector version actually solves this issue! Thank you!

**Comment by samsonasik** [comment]
Thank you for verify, I created unit test PR for it to proof that it already resolved

- https://github.com/rectorphp/rector-src/pull/5887

**Comment by simonschaufi** [comment]
Thank you, then I hope that you soon release a new version of rector!

**Comment by samsonasik** [comment]
You can use dev-main for now :)

**Comment by samsonasik** [comment]
@simonschaufi Rector 1.1.0 is tagged https://github.com/rectorphp/rector/releases/tag/1.1.0

**Comment by simonschaufi** [comment]
thank you

**Comment by simonschaufi** [comment]
Strangely the error still occurs in TYPO3 Rector with the new rector version. Is there anything we need to change as well on our side?

**Comment by samsonasik** [comment]
@simonschaufi that seems due to `TypeCombinator::addNull()` usage, I change to:

```diff
-                TypeCombinator::addNull(new IntegerType())
+                new \PHPStan\Type\UnionType([new \PHPStan\Type\NullType, new IntegerType()])
```

and it seems working ok:

```
➜  typo3-rector git:(update-rector) ✗ vendor/bin/rector process src/Helper --config templates/rector.php --dry-run --ansi --clear-cache
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] Rector is done!                                                                                                   
                                                                                                                        
```

**Comment by simonschaufi** [comment]
You are amazing! Thank you so much for your great support! Really appreciate!
