### ISSUE TITLE
EmptyOnNullableObjectToInstanceOfRector inserts broken code when applied to a non-nullable variable

### ISSUE THREAD

**Issue by janklan** [rectorphp/rector#8643]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.5 |

Rector thinks a non-nullable property is nullable, and makes a breaking change when the property is not initialised and at the same time the code uses `empty()` function to check the initialisation status.

```
    ---------- begin diff ----------
@@ @@

     public function setId(Uuid $id): self
     {
-        if (!empty($this->id) && !$id->equals($this->id)) {
+        if ($this->id instanceof \Symfony\Component\Uid\Uuid && !$id->equals($this->id)) {
             throw new \InvalidArgumentException('The ID is already set.');
         }
    ----------- end diff -----------

Applied rules:
 * EmptyOnNullableObjectToInstanceOfRector
```

The full code of the class being rectored is in the demo link below. 

Because the variable is non-nullable and **not initialised**, the new code throws `Fatal error: Uncaught Error: Typed property DemoFile::$id must not be accessed before initialization`.

## Minimal PHP Code Causing Issue

Almost the same config as what I use in my app, less links to phpstan.neon and Symfony container.

https://getrector.com/demo/f0b409ef-98a6-43ff-81dc-2608d8cb7c02

## Expected Behaviour

I expect `!empty($this->id)` to stay as is, or if rector has to touch it, it should be changed to `isset($this->id)`.

**Comment by samsonasik** [comment]
How is not initialized? Could you create https://3v4l.org/ example that show the error for real full example.

**Comment by janklan** [comment]
> Could you create https://3v4l.org/ example that show the error for real full example.

Look at the example I linked in the issue description please.

**Comment by samsonasik** [comment]
The property is not nullable on the first place, and typed, so I guess it should be nullable and has default value first, so kinda a code design issue

I need https://3v4l.org/ that show error when it use instanceof

**Comment by janklan** [comment]
No, it should not be nullable. Technically speaking, it could, but I do not need or want it nullable. I want it to be undeclared until I decide to call `setId()` and to declare it. 

I also want to prevent multiple `setId()` calls where consecutive calls could change the value. Effectively, I want the ID to be readonly, but I don't want to assign the value in the constructor. 

Because rector replaced `!empty()` with type comparison, PHP expects the value to be initialised.

The issue I'm reporting is the fact that, according to what the name of the applied rule indicates, Rector thinks the property is nullable, which is incorrect.

https://3v4l.org/CEWO3

**Comment by benharold** [comment]
Undefined and null are different concepts. You want `isset`

https://getrector.com/demo/847f8aab-f5b7-45ec-b9f4-b31aa6362daf

**Comment by janklan** [comment]
> Undefined and null are different concepts.

I'm well aware. 

> You want asset

No, I really want to report the fact that Rector thinks `private Uuid $id;` is nullable, or the rule name `EmptyOnNullableObjectToInstanceOfRector ` is incorrect/confusing because it applies also to non-nullable.

It's perfectly OK to use both `isset` and `empty` to test whether a property is not initialised.

**Comment by benharold** [comment]
That checks out: https://3v4l.org/Z3qBk

**Comment by janklan** [comment]
I updated the issue description to better reflect the discussion above.
