### ISSUE TITLE
[TypeDeclarations] Add return try/catch fail rule

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8646]
I've run Rector on one legacy project and noticed the type declaration set missed a try/catch case.

It's pretty straight forward so we should hook into 1st-level `TryCatch` node:

```diff
-public function some()
+public function some(): int
{
    try {
        return 100;
    } catch (Exception $exception) {
        // some logging
        throw $exception;
    }
}
```

It should handle any returns of known native value, e.g.:

```php
return 100 + 5;

// or
return $this->getInteger();

// ...

public function getInteger()
{
     return 100;
}
```

**Comment by samsonasik** [comment]
It seems already rule for that, see https://getrector.com/demo/d08967f6-e1f7-497a-977c-5697d66611e2

**Comment by samsonasik** [comment]
The issue seems on call another method inside try catch:

https://getrector.com/demo/dd05c072-b136-4687-aa4f-d230c47f0dd5

But running twice will solve it:

https://getrector.com/demo/bec90cd6-3c6d-49e0-9273-d99264113745

**Comment by samsonasik** [comment]
I created a PR for recursive check for it

- https://github.com/rectorphp/rector-src/pull/5903

**Comment by samsonasik** [comment]
I created new PR for specificly on cast return:

- https://github.com/rectorphp/rector-src/pull/5905
