### ISSUE TITLE
`MixedTypeRector` remove phpdoc with descriptions

### ISSUE THREAD

**Issue by vjik** [rectorphp/rector#8647]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  v1.1.0             |

`MixedTypeRector` remove phpdoc annotations with useful descriptions.

## Minimal PHP Code Causing Issue

```php
/**
 * @param mixed $value Value for dump
 */
public function test(mixed $value): void
{
    var_dump($value);
}
```

After run rector:

```php
public function test(mixed $value): void
{
    var_dump($value);
}
```

## Expected Behaviour

Keep code as is.

**Comment by duyphuongn** [comment]
I have the same issue with Rector v1.1.0. Just came here and was about to open a new issue, then I saw this report.
