### ISSUE TITLE
[TypeDeclaration] Infer object return type from serializer method

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8650]
The serializer of `Symfony\Component\Serializer\Serializer` type that unserialize to an object have only 1 exact return type.

That means we can add specific type on `deserialize()` call, based on 2nd argument:

```diff
-public function resolveEntity($data)
+public function resolveEntity($data): SomeType
{
    return $this->serializer->deserialize($data, SomeType::class, 'json');
}
```

If the `deserialize()` fails, it will throw an exception. So the value is never nullable.

The rule should handle only direct returns like these, keep it simple.

This rule should be part of type declaration set.

**Comment by samsonasik** [comment]
I created a PR : 

- https://github.com/rectorphp/rector-src/pull/5908

for it.
