### ISSUE TITLE
[TypeDeclaration] Add resource to object type rule

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8651]
The last type that is only available in docblock, not in native code.

```php
/** 
 * @return resource|null
 */
public function ...
``` 

The only way to "typehint" the resource is to use `mixed`, which does not add any value at all and allow passing different types.

Based on the discussion from PHP 7 times https://stackoverflow.com/questions/38429595/php-7-and-strict-resource-types, one of best practise is to use own typed object, e.g. `App\ValueObject\Resource`, that wraps the resource to validated and typed object, e.g. https://3v4l.org/62vFN

Then we should have an optional rule in type declarations set that converts all occurences of `resource` in docblock into real native types, e.g.:

```diff
-/** 
- * @return resource|null
- */
-public function getResource()
+public function getResource(): ?App\ValueObject\Resource
{
     // ...
}
```

Same for property/param types.

<br>

The "App\ValueObject\Resource" value should be configurable, with this as default.

**Comment by TomasVotruba** [comment]
@samsonasik Could you look into this? :pray: Thanks

**Comment by samsonasik** [comment]
I will try
