### ISSUE TITLE
[TypeDeclaration] Add typed property based on serialize attribute

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8652]
This rule is simple, the JMS annotations state exact type, that can be added to the property.
If on PHH 8.0+ (due to attributes, lets skip annotations to keep rule simple and more reliable), we can add known typed property:

```diff
 [JMS\Type('string')]
-private $name;
+private ?string $name = null;
```

**Comment by samsonasik** [comment]
is the `$name` property never assigned? if it assigned, it will always have the property type, eg: on ` TypedPropertyFromStrictConstructorRector`  https://getrector.com/demo/c341d282-86d9-4c7a-a8c5-31a4afdb6458
or `TypedPropertyFromAssignsRector` https://getrector.com/demo/ae279a4d-2c18-491a-afe9-7a9bfb198502

**Comment by TomasVotruba** [comment]
Indeed, it's never assigned via constructor. It's not covered by existing rules.

This is handled magically by the serializer itself. Usually by setter or private accessors. That's why it has to be nullable.

**Comment by samsonasik** [comment]
I created PR:

- https://github.com/rectorphp/rector-src/pull/5909

for it.
