### ISSUE TITLE
[ERROR] when trying to process rector

### ISSUE THREAD

**Issue by orionseye** [rectorphp/rector#8653]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.1.0            |
| OS | Windows 10 64bit            |
| PHP| 7.4.30            |

## rector.php (auto-generated)
```
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\ClassMethod\AddVoidReturnTypeWhereNoReturnRector;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src',
    ])
    // uncomment to reach your current PHP version
    // ->withPhpSets()
    ->withRules([
        AddVoidReturnTypeWhereNoReturnRector::class,
    ]);
```
1) New setup according to your documentation https://getrector.com/documentation/
2) rector.php = auto generated file by rector

While testing with auto-generated file, rector works like a charm.
As soon as i am using **withPreparedSets** this causes 
`[ERROR] syntax error, unexpected ':', expecting ')'`

From there on, even if i try 'rector --version' same ERROR happens

## rector.php with withPreparedSets
```
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src',
    ])
    ->withPreparedSets(deadCode: true);
```

**Comment by samsonasik** [comment]
It seems you're using old php version (7.x), you can do:

```
withPreparedSets(true)
```

as deadCode is first parameter to set.
