### ISSUE TITLE
[DX] Make withSkip() report rules that are ignored, but never registered

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8657]
Some rules that were parts of sets before can be excluded. E.g. json throw error rule, that made all json functions fail, or literal separator that changed all integer numbers.

Still those rules are ignored in `withSkip()` methods, ref https://x.com/hackbard/status/1792988835267150104
In some cases, it can be 10+ ignored that are not really needed. The Rector config should be small and with meaning lines.

The `withSkip()` method should be smart enough to go through registered rules + sets, and compare to report those rules:

```php
->withSkip([
    JsonThrowOnErrorRector::class,
]);
```

↓

```bash
[Note] The rule  JsonThrowOnErrorRector is ignored, but its actually never registered. You can remove it from the withSkip([...]) method
```

Note: it should also report rector classes that no longer exist (`class_exists(...) === false`)

**Comment by samsonasik** [comment]
It seems the check should be after all config(s) loaded, ensuring not overlapped by next configuration and report invalid warning

**Comment by samsonasik** [comment]
`array_diff` seems can be used to compare 2 collection array after all collected https://3v4l.org/FKDMr

**Comment by samsonasik** [comment]
I created PR

- https://github.com/rectorphp/rector-src/pull/5919 

for it.
