### ISSUE TITLE
Better behavior of ReadOnlyClassRector

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#8661]
ReadOnlyClassRector makes changes only if class is final. We have many classes (e.g. cqrs comands or DTOs) that do not have `final` keyword but are not extended (most of developers do not have this "final by default" habbit when coding).
As a consequence we cannot use Rector to migrate to PHP 8.2 readonly classes without adding `final` everywhere.

I understand that Rector works in a scope of a class so it cannot migrate to readonly class because it doesn't know whether there is a non-readonly class that extends a readonly class but even if there were then it would be reported at the start of PHP script. I'm everyone executes a script at least once (manually or in CI) before deploying to production. 

Maybe this could be configured, e.g. `migrate_also_non_final_classes => true`?

https://getrector.com/demo/e7d4f122-40e5-42bc-a20f-5785e4074f0c

**Comment by samsonasik** [comment]
Hi @javaDeveloperKid,

I think you can write your own custom rule for that.

https://getrector.com/documentation/custom-rule

We have in core only apply on final class for `readonly` flag to ensure everything safe for it.

Thank you for understanding.
