### ISSUE TITLE
'join' alias is not processed by ConsistentImplodeRector.php

### ISSUE THREAD

**Issue by amfleurke** [rectorphp/rector#8662]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.1.0 

## Minimal PHP Code Causing Issue
join(['a'], "string");

https://getrector.com/demo/19b79beb-de09-488e-8a60-5ec82d8a9cdf
## Expected Behaviour
join("string",['a']);

Either the rector should take the alias 'join' into account, OR the php80.php should do as first line:
$rectorConfig->ruleWithConfiguration(RenameFunctionRector::class, ['join' => 'implode']);

**Comment by samsonasik** [comment]
@amfleurke Could you try provide a patch, first, add fixture test at

https://github.com/rectorphp/rector-src/tree/main/rules-tests/CodingStyle/Rector/FuncCall/ConsistentImplodeRector/Fixture

Then, provide a patch at: 

https://github.com/rectorphp/rector-src/blob/a3ed07f8c8c0b2f7cbd78ce7711871d31bad3998/rules/CodingStyle/Rector/FuncCall/ConsistentImplodeRector.php#L73

I am on mobile, but should be something like:

```diff
-if (! $this->isName($node, 'implode')) {
+if (! $this->isNames($node, ['implode', 'join')) {
            return null;
        }

**Comment by amfleurke** [comment]
@samsonasik thanks! I didn't get around trying to fix it myself yet.
