### ISSUE TITLE
Incorrect behavior of BooleanInBooleanNotRuleFixerRector

### ISSUE THREAD

**Issue by rtm-ctrlz** [rectorphp/rector#8663]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/6c9e6aa3-5582-4c51-ad40-d9e27c5303a0

```php
<?php

final class DemoFile
{
    public function run(bool $param): bool
    {
        if (!preg_match('/^.+$/', $param)) {
	        return true;
        }
        return false;
    }
}
```
```diff
@@ -4,7 +4,7 @@
 {
     public function run(bool $param): bool
     {
-        if (!preg_match('/^.+$/', $param)) {
+        if (preg_match('/^.+$/', $param) === 0 || preg_match('/^.+$/', $param) === 0 || preg_match('/^.+$/', $param) === false) {
 	        return true;
         }
         return false;
```

### Responsible rules

* `BooleanInBooleanNotRuleFixerRector`

## BTW custom function creates a bit different diff

See https://getrector.com/demo/6c9e6aa3-5582-4c51-ad40-d9e27c5303a0

```php
<?php
function test(string $a): int|false {
    return preg_match('/^.+$/', $a);
}
function run(bool $param): bool
{
    if (!test($param)) {
        return true;
    }
    return false;
}
```

```diff
@@ -4,8 +4,8 @@
 }
 function run(bool $param): bool
 {
-    if (!test($param)) {
+    if (test($param) === 0 || test($param) === false) {
         return true;
     }
     return false;
 }
```

## Expected Behavior

I see couple ways:
 - adding variable (yes, naming is hard)
 - skip or add a warning (if it is possible)

I'm not sure which way is better, but changing code to calling function more than one time (for this case) may lead to bugs, because we never know if the function have any side-effects or not.

**Comment by samsonasik** [comment]
I think we can focus to fixing duplicated `=== 0` comparison first, as it is complex logic :)

then if possible, make use of `in_array()` for Callike usage, but that may in separate PR
