### ISSUE TITLE
  "System error: "Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getParamImmediatelyInvokedCallableTagValues()" 

### ISSUE THREAD

**Issue by ayedbelsem** [rectorphp/rector#8665]
I got this error with rector when after migrating php from php8.2 to php8.3.
`[ERROR] Could not process "src/Controller/MyController.php" file, due to:                                     
         "Call to undefined method                                                                                      
         PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getParamImmediatelyInvokedCallableTagValues()". On line: 307  `

PHP version: php8.3
"rector/rector": "^0.18.1"
"phpstan/phpstan": "^1.2",
 "phpstan/phpstan-phpunit": "^1.0",
 "phpstan/phpstan-symfony": "^1.0",

**Comment by tiggerduck** [comment]
I got the same error after updating phpstan/phpstan to "1.11.*"

PHP version was already: 8.3

**Comment by ayedbelsem** [comment]
updating rector to 1.1.0 resolved the problem , thanks
