### ISSUE TITLE
Some public const enum values `types` are added on php 8.3 but on some it doesn't work.

### ISSUE THREAD

**Issue by talha-core** [rectorphp/rector#8668]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.1.0            |

I upgraded to php 8.3

When I run rector, on some classes it changes the type of public const but on some it doesn't

`public const string SOME_NAME = 'some_value';`

## Minimal PHP Code Causing Issue

My config:
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;

/*
 * Rector configuration file for coreShop project.
 *
 * @param RectorConfig $rectorConfig The Rector configuration object.
 * @return void
 */
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__.'/config',
        __DIR__.'/public',
        __DIR__.'/src',
        __DIR__.'/tests',
    ]);

    $rectorConfig->sets([
        SetList::CODE_QUALITY,
        SetList::CODING_STYLE,
        SetList::DEAD_CODE,
        SetList::STRICT_BOOLEANS,
        SetList::EARLY_RETURN,
        SetList::PRIVATIZATION,
        SetList::INSTANCEOF,
        SetList::TYPE_DECLARATION,
        LevelSetList::UP_TO_PHP_84,
    ]);
};

```

## Expected Behaviour

The type of public constants should update on all classes

**Comment by samsonasik** [comment]
Please create reproducible at https://getrector.com/demo , otherwise, it is just assumption of use case and what before vs after change you want.

**Comment by samsonasik** [comment]
I am closing it as no reproducible code provided.
