### ISSUE TITLE
FirstClassCallableRector should also change simple function names

### ISSUE THREAD

**Issue by flack** [rectorphp/rector#8670]
# Feature Request

Currently, `FirstClassCallableRector` will transform this code:

```diff
-$result = array_map([$this, 'removeWhitespace'], $input);
+$result = array_map($this->removeWhitespace(...), $input);
```

It would be great if it could also transform this:

```diff
-$result = array_map('trim', $input);
+$result = array_map(trim(...), $input);
```

**Comment by samsonasik** [comment]
implemented at https://github.com/rectorphp/rector-src/pull/6027

**Comment by nikolicaleksa** [comment]
@flack Please be aware that with the next release of Rector you will explicitly need to enable the first-class-callable rule for functions. See [this issue](https://github.com/rectorphp/rector/issues/8728) and [this PR](https://github.com/rectorphp/rector-src/pull/6131)
