### ISSUE TITLE
Incorrect behavior of DowngradeThrowExprRector

### ISSUE THREAD

**Issue by defunctl** [rectorphp/rector#8671]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/f00e4092-b508-48dc-a41a-ebe1139e81a7

```php
<?php declare(strict_types=1);

use \DB;
use \Repository_Exception;

final readonly class DemoFile
{
        private string $table = 'test';
    
	public function find( int $id ): array {
		return DB::table( $this->table )
			->where( 'id', $id )
			->get( ARRAY_A ) ?: throw new Repository_Exception( sprintf( 'Unable to find ID: %s', $id ) );
	}
}
```

### Responsible rules

* `DowngradeReadonlyPropertyRector`

* `DowngradeReadonlyClassRector`

## Expected Behavior

I believe the [DowngradeThrowExprRector::refactorTernary()](https://github.com/rectorphp/rector-downgrade-php/blob/080d51d45b929d07b9538ab93cd0bd69de273ef8/rules/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector.php#L134) should have been used here?

**Comment by samsonasik** [comment]
Confirmed the error https://3v4l.org/koQgQ#v7.4.33

**Comment by defunctl** [comment]
Thanks @samsonasik! 

Do you know which version this will be released in?

**Comment by samsonasik** [comment]
This should be included in next release, you can use dev-main while wait for that.

**Comment by defunctl** [comment]
@samsonasik I don't think this should run any statements twice and should instead find a way to assign a variable to a returned value?

For example, I am running database queries and throwing if something went wrong, which means my queries are being run twice once the code is downgraded.

Should I open a new issue?

**Comment by samsonasik** [comment]
That's out of scope of downgrade task, more and more we tweak language origin, that may cause unwanted bug, but feel free to create PR improvement for that on CallLike in ternary, or create your own custom rule for that :)

**Comment by samsonasik** [comment]
@defunctl Rector 1.1.1 tagged https://github.com/rectorphp/rector/releases/tag/1.1.1
