### ISSUE TITLE
@param mixed type removed although there is a comment

### ISSUE THREAD

**Issue by theofidry** [rectorphp/rector#8674]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.1.0   |

## Minimal PHP Code Causing Issue

Running Rector on Box, I have the following changes:

```

1 file with changes
===================

1) src/Configuration/Configuration.php:401

    ---------- begin diff ----------
@@ @@
      * @param string                 $mainScriptPath           The main script file path
      * @param string                 $mainScriptContents       The processed content of the main script file
      * @param MapFile                $fileMapper               Utility to map the files from outside and inside the PHAR
-     * @param mixed                  $metadata                 The PHAR Metadata
      * @param bool                   $promptForPrivateKey      If the user should be prompted for the private key passphrase
      * @param array                  $processedReplacements    The processed list of replacement placeholders and their values
      * @param null|non-empty-string  $shebang                  The shebang line
    ----------- end diff -----------

Applied rules:
 * MixedTypeRector


 [OK] 1 file would have changed (dry-run) by Rector  
```

## Expected Behaviour

It is both undesired and unexpected. Undesired because here there is a comment (`The PHAR Metadata`), so I do not expect the `@param` line to be removed.

It is unexpected however because I could not reproduce it on the playground. An attempt with as close as possible as the source code used in Box: https://getrector.com/demo/53b14ca2-6036-4f25-a662-64569c33ed36

As you can see the issue is not reproduced there. And it of course also does not misbehave with a simpler scenario: https://getrector.com/demo/841269a5-a28a-4d67-b260-7fe841773850

I was encountering this issue before in `0.18.10` as well, I tried to upgrade in an attempt to fix it. I can reproduce this locally, I made sure to clear the cache beforehand too. So I have no clue, do you have any idea what could cause a difference between locally or Box's CI and the playground?

Link to the CI in Box with 1.1.0: https://github.com/box-project/box/actions/runs/9544803995/job/26304252786?pr=1378#step:10:22
Link to the CI in Box with 0.18.10: https://github.com/box-project/box/actions/runs/9544803995/job/26304252786?pr=1378#step:10:22

**Comment by samsonasik** [comment]
That already resolved in latest dev-main, You can use dev-main for now.
