### ISSUE TITLE
[DX] Allow more granulated return type completion, to separate from closures and makes easier to review

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8678]
We've done similar split in the past, to make type declaration level work in as small steps as possible.
This would concert few `ReturnType*` rules that now handle all functions, method, closure together.

The closure rules should be split of these and have separate rule inside `TypeDeclarationLevel`

Ref https://x.com/apefm/status/1803148500693102681

**Comment by TomasVotruba** [comment]
At the moment we have single `AddArrowFunctionReturnTypeRector` to handle these cases. I think it makes sense, as in the wild there is hundreds of methods/functions, but much less callbacks/arrow functions. So it's easier to review these cases without granulation.

**Comment by samsonasik** [comment]
`ClosureReturnTypeRector` can be added, and register after other closure return types rules so executed on last

**Comment by TomasVotruba** [comment]
@samsonasik That's the plan. `void` and `never` are the easy ones to pick
