### ISSUE TITLE
Incorrect behavior of RemoveUnusedPublicMethodParameterRector

### ISSUE THREAD

**Issue by stephanvierkant** [rectorphp/rector#8680]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/fc2b72d3-8f36-4159-bc10-c3c3b4bd0614

```php
<?php

declare(strict_types=1);

namespace App\MessageHandler\Cron;

use App\Model\Message\Job\DatabaseCleanupJob;
use App\Services\DatabaseCleanup;
use Symfony\Component\Lock\LockFactory;

#[\Symfony\Component\Messenger\Attribute\AsMessageHandler]
final readonly class DatabaseCleanupJobHandler
{
    private \Symfony\Component\Lock\LockInterface $lock;

    public function __construct(private DatabaseCleanup $cleanup, private LockFactory $lockFactory)
    {
        $this->lock = $this->lockFactory->createLock('database-cleanup-cron');
    }

    public function __invoke(DatabaseCleanupJob $cleanupJob) : void
    {
        if (! $this->lock->acquire()) {
            return;
        }

        $this->cleanup->execute();

        $this->lock->release();
    }
}
```

### Responsible rules

* `RemoveUnusedPublicMethodParameterRector`

## Expected Behavior

I think there's nothing wrong with an unused parameter when using `__invoke` isn't it?

**Comment by samsonasik** [comment]
The change is fine, unlike other magic method, the `__invoke()` is special method that allow modification while always be public.

The `$cleanupJob` parameter is never used, and this rule only on final class + no extends + no implements, so the change is valid and not cause bc break.

**Comment by stephanvierkant** [comment]
But this is a message handler. Without the parameter, it looses its purpose. The `DatabaseCleanupJob` is a DTO, but without any properties. But that doesn't mean it useless.

**Comment by samsonasik** [comment]
I think you can just skip the rule for it :)

On reality, it will only usefull when it used, otherwise, it just useless signature. The class is not extends nor implements anything, and final, nothing should be added on parameter when never used. The rule is smart enough to not remove parameter in the middle, as that will be BC break on caller, when not used, it doesn't have purpose as that dead code :)

**Comment by TomasVotruba** [comment]
@stephanvierkant Thanks for reporting. Just checking,,what error do you get in your project when the parameter is removed?
Where is it passed?

**Comment by stephanvierkant** [comment]
See https://symfony.com/doc/current/scheduler.html and/or https://symfony.com/doc/current/messenger.html.

I'm sending a (scheduled) message to the message bus. That message can be empty (so there is a DTO without properties), so I think there is a valid use case for having a parameter that isn't used.

**Comment by samsonasik** [comment]
@stephanvierkant that strange,  why it will not handle the message the parameter on `__invoke()` is local variable, and never used, seems framework tied magic, or you need to define by `new DatabaseCleanupJob()` instance inside instead.

if that only on specific paths, I think you can use `->withSkip()` on paths instead :) 

```php
->withSkip([
       RemoveUnusedPublicMethodParameterRector::class => [
          __DIR__ . '/src/MessageHandler',
      ],
])
```

**Comment by stephanvierkant** [comment]
Yes, this is Symfony magic :). I've skipped the rule for now, but since I'm using it exactly like documented, other people might encounter the same issue.

**Comment by TomasVotruba** [comment]
@stephanvierkant I see, thanks for sharing. How can we detect this Symfony magic and skip it?

**Comment by stephanvierkant** [comment]
I think the best way is to check if it has #[AsMessageHandler]

**Comment by TomasVotruba** [comment]
@stephanvierkant I see, I'll look into it :), thanks

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/6001 :+1: 

If there are some more Symfony attributes that make us of similar magic, let us know so we can skip them :pray:
