### ISSUE TITLE
BC Break - Class removed in patch version

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#8681]
![CleanShot 2024-06-21 at 13 07 50@2x](https://github.com/rectorphp/rector/assets/995707/4bcd7a01-f23c-42d5-ad4c-6a520485149c)

cc @silasjoisten

**Comment by samsonasik** [comment]
PHPUnitLevelSetList is deprecated since  0.19.2, so it removed at:

- https://github.com/rectorphp/rector-phpunit/pull/333

Now, we already on 1+. You can use `PHPUnitSetList` instead.
