### ISSUE TITLE
Change EncapsedStringsToSprintfRector to always use sprintf

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#8690]
I looked at the EncapsedStringsToSprintfRector rule and it seems that it chooses when to use concat or sprintf.

In our team, we'd like to always use sprintf.

Would it be OK if I send a PR to modify the EncapsedStringsToSprintfRector so that this mode can be configured? The default behavior can be the same.

**Comment by TomasVotruba** [comment]
Sounds good :+1: 

Do you have any code snippets where you need the preference?

**Comment by ruudk** [comment]
While trying to create a PR for this feature I noticed that you recently undid a few things that I just want in https://github.com/rectorphp/rector-src/commit/412d0bd50130f82d8f5388060301a7e1debf50ad

@TomasVotruba Could you elaborate why this was done? The [PR](https://github.com/rectorphp/rector-src/pull/4897) does not contain any information.

**Comment by TomasVotruba** [comment]
@ruudk I think the goal was to make use of standalone variables if possible. Variables are easier to analyse and also to hook to.

```diff
-echo "Try {$allowed}";
+echo 'Try ' . $allowed;
```

**Comment by ruudk** [comment]
Are you OK if I make they configurable? For me it makes sense to convert all concatenations to sprintf as that is also the name of the rule.

**Comment by TomasVotruba** [comment]
Sure, go for it 👌

**Comment by ruudk** [comment]
Created this PR: 
- https://github.com/rectorphp/rector-src/pull/6050
