### ISSUE TITLE
Incorrect behavior of DateTimeInstanceToCarbonRector

### ISSUE THREAD

**Issue by roelvanduijnhoven** [rectorphp/rector#8692]
Thanks for this awesome tool :clap:. I encountered the following when trying out the new Carbon feature.

# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/80869081-67ea-4103-ae61-5a3ed24b3c98

```php
<?php
$date = new \DateTime('-5 days');
```

### Responsible rules

* `DateTimeInstanceToCarbonRector`

## Expected Behavior

```diff
<?php
- $date = new \DateTime('-5 days');
+ $date = new \Carbon('-5 days');
```

**Comment by samsonasik** [comment]
It seems it works on `+5 days`, https://getrector.com/demo/1340bced-4190-414a-92d4-f8ba1d55fde9

But not works on `-5 days`, so it missing functionality on `-`, could you try provide a patch? Here the steps:

1. Add fixture test at https://github.com/rectorphp/rector-src/tree/main/rules-tests/Carbon/Rector/New_/DateTimeInstanceToCarbonRector/Fixture

2. Make a patch, it should be on `CarbonCallFactory` https://github.com/rectorphp/rector-src/blob/main/rules/Carbon/NodeFactory/CarbonCallFactory.php

Thank you.
