### ISSUE TITLE
Incorrect behavior of RenameParamToMatchTypeRector

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#8693]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

When param name used as ArrowFunction param, it should be skipped.

See https://getrector.com/demo/14b8b5f1-05ee-4ecb-9d84-973ddc5297a4

```php
<?php

use PhpParser\Node\Stmt\Foreach_;
use PhpParser\Node\Expr\Variable;

final class DemoFile
{
    public function run(Foreach_ $node)
    {
      array_map(
          fn (Variable $node) 
          => $node,
          []
          );
    }
}
```

### Responsible rules

* `RenameParamToMatchTypeRector`

## Expected Behavior

Should be skipped, ref rectify error at https://github.com/rectorphp/rector-src/pull/6045/commits/33ddf96050a1f96f91df42aca410038d509e53e9

**Comment by nikolicaleksa** [comment]
> /cc @nikolicaleksa this reported as bug to be resolved :)

Sorry didn't get that, is there something I need to do or are just letting me know because you noticed it in the MR where you were fixing Foreach to Foreach_?

**Comment by samsonasik** [comment]
nothing, the bug of `RenameParamToMatchTypeRector` found when running naming rule on your rule.

The downgrade error was different: `Foreach` is part of php 7.x syntax, so cannot become namespace name, so I renamed to `Foreach_`

**Comment by samsonasik** [comment]
Ref https://3v4l.org/Ba9fQ
