### ISSUE TITLE
FinalizeClassesWithoutChildrenRector missing in 1.1.1

### ISSUE THREAD

**Issue by ximamedia** [rectorphp/rector#8697]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.1.1     |

Since v1.1.1 the class rules/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector.php is missing.

Since there's no changelog, I can't see why this has been done or if it's a failure.

We skipped this rule so now we get

```
[ERROR] These rules from "$rectorConfig->skip()" does not exist - remove them or fix their names:                      
          * Rector\Privatization\Rector\Class_\FinalizeClassesWithoutChildrenRector
```

I suspect, we can remove this skip because the rule doesn#t exist anyway?

Thanks in advance for any clearification :)

**Comment by staabm** [comment]
The release notes mention this rule was removed:

https://github.com/rectorphp/rector/releases

**Comment by samsonasik** [comment]
The rule is deprecated since 0.19.6. We already in 1.x, so this rule removed.
