### ISSUE TITLE
Support array shapes in ReturnTypeFromStrictNewArrayRector

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#8699]
# Feature Request

Would it be possible to enhance the ReturnTypeFromStrictNewArrayRector with support for array shapes?

I know it's better to use (collection) objects instead of array shapes. But sometimes you have to deal with what you have 😅 

Would be great to automatically add the returned shape, so that calling code can rely more on the keys and types.
 
## Diff 

Example:

```diff
 final class ArrayShapeComplexArray
 {
+    /**
+     * @return array{id: ?int, name: string, roles: list<string>, active?: bool}
+     */
     public function run() : array
     {
         $items = [];
 
         $items['id'] = rand(0, 1) ? 1 : null;
         $items['name'] = 'Ruud';
         $items['roles'] = ['admin', 'user'];
 
         if (rand(0, 1)) {
             $items['active'] = true;
         }
 
         return $items;
     }
 }
```

**Comment by TomasVotruba** [comment]
We actually had such a rule in the past, but results yielded mixed feelings. In same cases array shapes were helpful, in other they took 10 lines of docblock code hard to read. This rules only work with native PHP, so it would not be a right fit.

If you need this feature, please create a custom rule to battle test it. If it prooves to be working well, I might reconsider  :)
