### ISSUE TITLE
PHP version-dependent constant handling

### ISSUE THREAD

**Issue by savinmikhail** [rectorphp/rector#8704]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.1.1             |
| PHP version | 8.3.7|

I have library, written for php 8.2. I used Rector to create php 7.4 compatible version. In my code I used token contants, like (T_CLASS, T_ENUM)
I used the following rector config
```php
return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->withSets([DowngradeLevelSetList::DOWN_TO_PHP_74]);
   ```

After executing, the T_ENUM constant has been still present in my code, which lead to the error on php 7.4 server:
```bash
PHP Warning:  Use of undefined constant T_ENUM - assumed 'T_ENUM' (this will throw an Error in a future version of PHP) in /var/www/vendor/savinmikhail/comments-density/src/MissingDocBlockAnalyzer.php on line 40
```
## Minimal PHP Code Causing Issue

```php
 if ($token[0] === T_DOC_COMMENT) {
                $lastDocBlock = $token[1];
            } elseif (in_array($token[0], [T_CLASS, T_TRAIT, T_INTERFACE, T_ENUM, T_FUNCTION], true)) {
                if (empty($lastDocBlock)) {
                    $missingDocBlocks[] = [
                        'type' => 'missingDocblock',
                        'content' => '',
                        'file' => $filename,
                        'line' => $token[2]
                    ];
                }
 ```

## Expected Behaviour

I think the easiest way would be report of such PHP version-dependent constants

**Comment by samsonasik** [comment]
constant value set with add if constant exists check seems needed, on downgrade, looking at https://3v4l.org/mHBk2 , the value seems different between PHP 8.1 to PHP 8.3, replace with statement if not onstant exist and php < 8.3, then  336, else 372

**Comment by TomasVotruba** [comment]
@savinmikhail We'll need a minimal reproducer repository to tackle this. Could you share one?

**Comment by savinmikhail** [comment]
@TomasVotruba for sure! Here you go https://github.com/savinmikhail/rector_-8704

**Comment by samsonasik** [comment]
@savinmikhail new rule: DowngradeTEnumConstantRector seems needed, to add:

```diff
+ if (! defined('T_ENUM')) {
+      define...
+
```

Before the statement that use it, there is service `ExprInTopStmtMatcher`

https://github.com/rectorphp/rector-downgrade-php/blob/c053b9795a81bb9fd5b8d59e05c7556f19267893/src/NodeAnalyzer/ExprInTopStmtMatcher.php#L28

to match `Expr` for it so we can prepend if check before...

**Comment by TomasVotruba** [comment]
@samsonasik Awesome! Could you handle this?

**Comment by samsonasik** [comment]
I will try

**Comment by savinmikhail** [comment]
@samsonasik I believe very few people use the T_ENUM constant. Mb the rule should check all PHP constants?
See, many of them are version-specific
<img width="513" alt="image" src="https://github.com/rectorphp/rector/assets/99592925/d53736df-8928-41bc-9767-4af6baaf5dae">

**Comment by samsonasik** [comment]
another way is you can create your own constants.php and register to your composer.json under autoload -> files config, add if php version and defined check there :)

**Comment by savinmikhail** [comment]
@samsonasik thank you. I dont need this functional, just thought it might be helpful for others

**Comment by TomasVotruba** [comment]
Thanks :+1: I guess this can be closed then.
