### ISSUE TITLE
Rector 1.2.0 problem with reflection class 

### ISSUE THREAD

**Issue by tomasnorre** [rectorphp/rector#8708]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.0            |
| PHP version | 8.1.29            |

When running `.Build/bin/rector process --dry-run --config rector-ci.php` I get folowing errors

```shell 
PHP Fatal error:  Uncaught ReflectionException: Class "Rector\Symfony\NodeAnalyzer\Command\SetAliasesMethodCallExtractor" does not exist in /home/tomas/Projects/Private/crawler/.Build/vendor/rector/rector/vendor/illuminate/container/Container.php:782

Next RectorPrefix202407\Illuminate\Contracts\Container\BindingResolutionException: Target class [Rector\Symfony\NodeAnalyzer\Command\SetAliasesMethodCallExtractor] does not exist. in /home/tomas/Projects/Private/crawler/.Build/vendor/rector/rector/vendor/illuminate/container/Container.php:784

Additional stack trace can be added if needed.
```

When downgrading to rector version 1.1.1 it all works like expected again.

## Minimal PHP Code Causing Issue

I don't have a code sample to reproduce this. 
It's currently testing with the commit https://github.com/tomasnorre/crawler/commit/68e72580ad300ab8ac545daf64c62f62cc897871 from tomasnorre/crawler

## Expected Behavior

I would not expect Exceptions thrown. 

Please let me know if I can do anything to help further.

**Comment by samsonasik** [comment]
The service seems removed at 

- https://github.com/rectorphp/rector-symfony/pull/619

and used by your included custom rule, I think you can copy paste removed service from that PR and register as service

https://github.com/rectorphp/rector-src/blob/b4c0d8dd10d3172e4bb9d00a3e206691ccf73edf/src/Configuration/RectorConfigBuilder.php#L930

**Comment by TomasVotruba** [comment]
Thanks for report. Could share your custom rule using this service?

**Comment by samsonasik** [comment]
It seems came from typo3 set list 

https://github.com/tomasnorre/crawler/blob/68e72580ad300ab8ac545daf64c62f62cc897871/rector-ci.php#L58-L59

**Comment by tomasnorre** [comment]
It works with `registerService()` like @samsonasik suggestion. Thanks. 
https://github.com/rectorphp/rector-src/blob/b4c0d8dd10d3172e4bb9d00a3e206691ccf73edf/src/Configuration/RectorConfigBuilder.php#L930

It's a change like this considered breaking? As the working config broke afterwards? The bump was only made from 1.1.1 to 1.2.0. Asking of interest/to gain knowledge not blaming.

**Comment by TomasVotruba** [comment]
@tomasnorre I'd say its a glitch in autowire. We don't keep BC for some framework-specific services, as mostly helper classes for single rule.

This was actually part of fix for a Symfony rule that worked only partially. I made the service code part of rule and filled the gaps.

Rule of thumb for next time: use services only from core rector-src.
