### ISSUE TITLE
DataProviderAttributeToAnnotationRector

### ISSUE THREAD

**Issue by savinmikhail** [rectorphp/rector#8709]
# Feature Request
 
## Diff 

```diff
-#[DataProvider('fooDataProvider')]
+/**
+* @dataProvider fooDataProvider
+*/
public function foo(array $array): void
```

There's an upgrade version of this rule exist, but none for downgrade, so I had to write it manually after rector, after downgraded from PHP 8.2 to PHP 7.4

**Comment by TomasVotruba** [comment]
Hi, the downgrade sets are not meant for fully functional codebases, only to deploy releasable versions for projects/packages. 

What is your use case?

**Comment by savinmikhail** [comment]
I was preparing php-7.4 compatible version for my php-8.2 library. Rector just removed my existed
#[DataProvider()]
and i didn't find the rule which will replace it with
/**
* @dataProvider
*/

Not sure that I answered your question, though

**Comment by TomasVotruba** [comment]
That's out of our scope, as a dev code. Downgrade sets are for release-only code.
Tests should never be part of deployed code.

**Comment by savinmikhail** [comment]
Now I get it, thanks
My package: https://github.com/savinmikhail/Comments-Density
We can close this issue, as soon as it out of your scope :)

**Comment by TomasVotruba** [comment]
I see. Perfect :)

End-users don't use tests, just the `/src`

Also make sure the dependencies are either scoped and in own `/vendor` directory, are part of codebase:

https://github.com/savinmikhail/Comments-Density/blob/d1baf3cda248ae8a6a4586a5626252f3c7c89ed0/composer.json#L23-L27 

These might come handy:

* https://tomasvotruba.com/blog/how-to-release-php-81-and-72-package-in-the-same-repository/
* https://tomasvotruba.com/blog/how-to-develop-sole-package-in-php81-and-downgrade-to-php72/

If you want to see a minimalistic package with full downgrade, including dependencies, I can share this one:

**Comment by TomasVotruba** [comment]
Cool idea with comments, btw. Too dense comments are annoying :)

This is how I deal with them: https://github.com/rectorphp/swiss-knife/#2-detect-commented-code

**Comment by savinmikhail** [comment]
> * https://github.com/TomasVotruba/lines/

I will appreciate a star from you, if you liked it :)

Thanks a lot for the reference, I wasn't able to find it when started my project :(

Also your "Lines" is a cool idea!

It was a pleasure to work with you

**Comment by TomasVotruba** [comment]
Thanks 🙏

Keep up great work 💪
