### ISSUE TITLE
Incorrect behavior of `NewlineBeforeNewAssignSetRector`

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#8710]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.1.1 + last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/5ad14da9-36d4-4f62-8421-6116190f7bd8

```php
<?php

final class Fetcher
{
    public function setExclusionElements(array $elements) {}
    public function getRecommendations(object $episode) {}
    
}

final class DemoFile
{
    public function run(bool $param)
    {
        $fetcher = new Fetcher();
        $fetcher->setExlusionElements([$element]); // exclude
        $result = $fetcher->getRecommendations($episode);

        return '10';
    }

    private function isTrue($value)
    {
        return $value === true;
    }
}
```

### Responsible rules

* `NewlineBeforeNewAssignSetRector`

## Expected Behavior

I didn't expect my comment to move into a newline. In my opinion this should have been like this:

```diff
        $fetcher->setExlusionElements([$element]); // exclude
+
        $result = $fetcher->getRecommendations($episode);
```

## Additional words

I :heart: rector. It makes my life easier.

**Comment by samsonasik** [comment]
that's not possible due to current php-parser :), comment is belong to next stmt, so inline comment after stmt will go to next stmt

**Comment by TomasVotruba** [comment]
Thanks for reporting! As @samsonasik writes, this is actually how php-parser bounds comments 
The comments after PHP code are bound with following line of code. We simply inherit this feature and it will behave in same way in other rule.

The best way to fix is: 

```php
// exclude
$fetcher->setExlusionElements([$element]); 
```

I recall slevomat coding standard had such a fixer to automate work :+1:

**Comment by mvhirsch** [comment]
I see, thanks for clarifying :+1:
