### ISSUE TITLE
Cast argument when converting `Annotations` to `Attributes`

### ISSUE THREAD

**Issue by etshy** [rectorphp/rector#8713]
# Feature Request

When converting Annotation into Attributes, try to guess and cast arguments values
 
## Diff 

```diff
-/**
-  * @Constraints\Length(min="1", max="50")
- */
- private $props;
- 
+ #[Constraints\Length(min: 1, max: 50)]
+ private $props;

```

Actually, the `min` and `max` argument stays as strings.
Not sure if we can guess type during the process though.

Additionnaly it would be good to import FQCN if the class exists in project or vendor
```diff
-/**
-  * @Mapping\Entity(repositoryClass="App\EntityRepository")
- */
- class entity
+ use App\EntityRepository;
+
+ #[ORM\Entity(repositoryClass: EntityRepository::class)]
+ class entity
```

**Comment by TomasVotruba** [comment]
That's a valid suggestiion, thanks! 

I'll look into this :+1:

**Comment by TomasVotruba** [comment]
> Additionnaly it would be good to import FQCN if the class exists in project or vendor

This is handled at single place by https://getrector.com/documentation/import-names 
Best practise is to migrate first, then enable auto importing.

**Comment by etshy** [comment]
I didn't see importname options I'll try that thanks.
