### ISSUE TITLE
Incorrect behavior of DeclareStrictTypesRector with shebang

### ISSUE THREAD

**Issue by justim** [rectorphp/rector#8715]
# Bug Report

When running Rector on a file that has a shebang as the first line in the file (ex `#!/usr/bin/env php`) the `DeclareStrictTypesRector` rule does something wonky. It adds the `declare(strict_types=1);` statement as the first line of the file, before the shebang and before the `<?php`. This results in an invalid file.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/89e666c5-addb-41c3-b63c-2e5b60e9000d

```php
#!/usr/bin/env php
<?php

echo 'Hello world!';
```

### Responsible rules

* `DeclareStrictTypesRector`

## Expected output

```php
#!/usr/bin/env php
<?php

declare(strict_types=1);

echo 'Hello world!';
```

## Actual output

```php
declare(strict_types=1);

#!/usr/bin/env php
<?php

echo 'Hello world!';
```

Resulting in an invalid PHP file.

**Comment by samsonasik** [comment]
The current solution I found is skip when first element is InlineHTML ...

**Comment by justim** [comment]
Thanks for the fix! 👍
