### ISSUE TITLE
Deprecation of function to cast rules

### ISSUE THREAD

**Issue by OA** [rectorphp/rector#8716]
# Bug Report

Why are these getting deprecated? It still makes sense to have a unified way of casting in a software project.

```
        BoolvalToTypeCastRector::class,
        IntvalToTypeCastRector::class,
        FloatvalToTypeCastRector::class,
        StrvalToTypeCastRector::class,
```

**Comment by TomasVotruba** [comment]
There were few reasons, one was misconception for one being faster for another: https://stackoverflow.com/a/35949025/1348344

Behavior or purpose of `intval()` is slightly different, thanks for 2nd parameter - https://www.php.net/manual/en/function.intval.php

In the community use, they were often ignored from the code quality sets, as personal syntax suggar preference. That's scope of coding standard tools.

They're quite easy to implement in single custom rule :+1:

**Comment by BenMorel** [comment]
> That's scope of coding standard tools.

For anyone affected by this removal, this is notably supported by php-cs-fixer's [modernize_types_casting](https://cs.symfony.com/doc/rules/cast_notation/modernize_types_casting.html) rule.
