### ISSUE TITLE
Incorrect behavior of DeclareStrictTypesRector

### ISSUE THREAD

**Issue by Morgy93** [rectorphp/rector#8718]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/031cfe76-98e7-4c8d-8220-533aa17097f4

```php
<?php

declare(strict_types=1);

final class DemoFile
{

    public function getHash(int $id): string
    {
        return md5($id);
    }
}
```

### Responsible rules

* `DeclareStrictTypesRector`

## Expected Behavior

It throws `Argument '1' passed to md5() is expected to be of type string, int given`.
It should at least show a message or change to:

`return md5((string) $orderId);`

**Comment by samsonasik** [comment]
`DeclareStrictTypesRector` doesn't validate param type, and rector is not error handler.

I suggest to verify with PHPStan early, fix that and re-run the rule.

https://phpstan.org/r/f9b52b28-4d9c-47ad-b483-0d9a2cda1e75

**Comment by Morgy93** [comment]
@samsonasik Interesting and thanks for quick answer.

But why did it refactor some type errors and others not?

For example it changed `$apiResult = json_decode($responseContent);` to `$apiResult = json_decode((string) $responseContent);`

**Comment by samsonasik** [comment]
you probably applied other rules for that, for legacy code, try to not apply all rules, but 1 by 1, verify, and continue progress.
