### ISSUE TITLE
Import class short name conflict

### ISSUE THREAD

**Issue by MauroVinicius** [rectorphp/rector#8723]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.2.0 (invoke `vendor/bin/rector --version`)             |

I'm trying to use the option to import short names in some files in a project, but strangely this option is not working, the TableDisease class is being imported as "\Project\PedBook\Auto\Stc\TableDisease" instead of just "TableDisease"

This happens in example 1, in example 2 removing the use of "Project\PedBook\Auto\Obj\TableDisease as ObjTableDisease" solves the problem, I have this same class in the namespace \Stc\ and \Obj\ and I needed to use both at the same time but with everyone using a short name

## Minimal PHP Code Causing Issue

Example 1: https://getrector.com/demo/0002f0db-3e34-4794-bef0-b1bf15b8487c
Example 2: https://getrector.com/demo/5b8952bb-fe93-4ea2-9690-8951e47429fc

## Expected Behaviour

![image](https://github.com/rectorphp/rector/assets/32529671/055dab1c-e0a0-4394-9b68-d5c4f318c31e)

**Comment by samsonasik** [comment]
I checked this, and the change is expected due to conflict with root name of the alias, and seems the transformation is valid per configuration.

we have a lot of alias conflict handling, to cover this, same last name is skipped to be imported to avoid overlapped last apply.

Thank you for understanding ;)

**Comment by MauroVinicius** [comment]
> I checked this, and the change is expected due to conflict with root name of the alias, and seems the transformation is valid per configuration.
> 
> we have a lot of alias conflict handling, to cover this, same last name is skipped to be imported to avoid overlapped last apply.
> 
> Thank you for understanding ;)

@samsonasik In this case, is there any way for me to configure the alias of each class through Rector? I looked in the documentation but I didn't find this rule or configuration, if I need it I can create my own custom rule here but I believe it would be useful to have this rule as a default rule available to everyone

Example: If there is a "use" conflict, the class should be called StcTableDisease, if there is still a conflict it should be called AutoStcTableDisease, if there is another conflict another name and so on

**Comment by samsonasik** [comment]
I think you can create custom rule for that, since auto import is very complex process, except it cause invalid transformation, skip the aliased and conflict is the way to go

We don't want to make it too much process, since it can be node or docblock :)

**Comment by MauroVinicius** [comment]
@samsonasik I understand, each project has its own namespace rules, in which case I will create my own rule to deal with this

Anyway, thank you very much for your attention, now I will continue with my tasks here
