### ISSUE TITLE
Trying to install and finish the initial Setup of rector

### ISSUE THREAD

**Issue by ghevia99** [rectorphp/rector#8726]
I have received thre different projects with PHP ( different version from 5.3 to 7.4 ), so, I found Rector as a possible tool to make easier the upgrade, thenn, I sent a request asking for support to find where is the issue.  ( Req# 8714 ), somebody took the report.
Then, I really want to find where is the issue and fix it, then, whenever I have rector working, then I iwill have the time to learn.
What I really need to have rector, working, and according to the video I found from Tomas Voruba, rector was created to make it easy, not to learn with PHP, and then, use it.  So, please ,let me know what would be the issue.  how to fix it, and set my starting point.

Thanks

Gustavo Hevia

**Comment by TomasVotruba** [comment]
Hi, thanks for the ping. I've now explored the #8714 issue again. 

Rector is a PHP tool and it requires PHP skills like namespace imports. Without basic PHP knowledge, you'll struggle with further usage as well. 
If you're using Rector first time, I recommend adding only single rule at a time. To get familiar with and learn tool slowly. 
Jumping into full set upgrade like your use case in first try might back-fire.

Better take it slowly with single rule at a time. Rules from "code quality" group might be a good start: https://getrector.com/find-rule?set=CODE+QUALITY

**Comment by ghevia99** [comment]
Ok, it sounds good.
Thanks for your quick reponse.

Then, to start with the correct foot.
What I need is to have the good  start point.
Then, I would need to have the first escebario, upgrading 5.3 to 7.4.

  1.  Should I download the 7.4 or maybe i could use 8.2 to upgrade to any point between 7.4 and 8.2.
  2.  I downloaded composer version 1.1c is that important for the upgrade level I want to go as a target ?
  3.  What shouls be the correct php source code to have in the rector.php?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TomasVotruba** [comment]
PHP version is up to you, 7.4 till 8.3 all work. 

There is now Composer 2.7, better use latest version: https://getcomposer.org/download/

For questions related Rector upgrade process, you can find answers in the documentation: https://getrector.com/documentation

**Comment by ghevia99** [comment]
> Hi, thanks for the ping. I've now explored the #8714 issue again.
> 
> Rector is a PHP tool and it requires PHP skills like namespace imports. Without basic PHP knowledge, you'll struggle with further usage as well. If you're using Rector first time, I recommend adding only single rule at a time. To get familiar with and learn tool slowly. Jumping into full set upgrade like your use case in first try might back-fire.
> 
> Better take it slowly with single rule at a time. Rules from "code quality" group might be a good start: https://getrector.com/find-rule?set=CODE+QUALITY

Yes, I understand that, but I have pressure to make this work, so, what I need is to have a starting point with Rector, then, from there I will go slowly, and learning with PHP, but I don't have time to learn PHP at this time, then trying to do this I got the error, that made me looose a lot of time, testing. So, I started with the recoemmended source using withPreaparedSets, but I changed to withSets as receommended on the Documentation page, then I got errors,
I want to have a good source code for the rector.php  that works, doing the basic, then as you said, go slowly, and learning, but still I don't have that.
So, this is the first code I tried : 

![image](https://github.com/rectorphp/rector/assets/143755546/dab4747d-e9f4-43f0-b11a-d5e1e3659d6a)

then, this is the second code I tried, following the recommendation on the Documentation page : https://getrector.com/documentation/

as this : 

![image](https://github.com/rectorphp/rector/assets/143755546/896ae2e1-b7af-49c6-b39a-82f8dee0eaa1)

but, then, I got the error :  

 [ERROR] The given paths do not match any file

SO, this is an endless history of errors, I fix one and then appears another one, this path given is about the first three lines ?

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\Property\TypedPropertyFromStrictConstructorRector;
use Rector\Set\ValueObject\SetList;

Please, give me something, I would appreciate it.
Thanks.

**Comment by samsonasik** [comment]
define the path to be scan, read the doc

https://getrector.com/documentation/define-paths

**Comment by ghevia99** [comment]
> define the path to be scan, read the doc
> 
> https://getrector.com/documentation/define-paths

Yes, I see that, then, I have questions about that,  first option : 

<?php

use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src/SingleFile.php',
        __DIR__ . '/src/WholeDirectory',
    ]);

1. on the withPaths section the section  "__DIR__", should I substitute with the location of the SRC folder ?.
2. If I want to check the source files, just on the SRC files, would be enough the WholeDirectory option, right ?

Then, the second question, is about the last option as  File Sufixxes : 
<?php

use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withFileExtensions(['php', 'phtml']);

1. That would be needed to check the PHP files located on a different folder location, (i.e ) whenever I started the upgrade process of one application?
2. If I select the first one above, I don't need the last one?, or still I would need the last one, for the upgrade ?
