### ISSUE TITLE
TypedPropertyFromToOneRelationTypeRector should add nullable property according to doctrine mappin

### ISSUE THREAD

**Issue by abuhamza** [rectorphp/rector#8727]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |1.1.1           |

With the rule TypedPropertyFromToOneRelationTypeRector, rector is setting the property type according to the doctrine mapping. However when the property is mapped as non-nullable, rector is add a nullable PHP property.
Example : 
```diff
34) src/Entity/TrackProvider.php:18

    ---------- begin diff ----------
@@ @@
     /** @var Track */
     #[ORM\JoinColumn(name: 'track_id', referencedColumnName: 'id', nullable: false)]
     #[ORM\ManyToOne(targetEntity: Track::class, inversedBy: 'trackProvider')]
-    private $track;
+    private ?Track $track = null;
    ----------- end diff -----------

Applied rules:
 * TypedPropertyFromToOneRelationTypeRector
```

## Minimal PHP Code Causing Issue

8.2

## Expected Behaviour
As the property is mapped as nullable : false, recto should also add a non nullable property
```diff
34) src/Entity/TrackProvider.php:18

    ---------- begin diff ----------
@@ @@
     /** @var Track */
     #[ORM\JoinColumn(name: 'track_id', referencedColumnName: 'id', nullable: false)]
     #[ORM\ManyToOne(targetEntity: Track::class, inversedBy: 'trackProvider')]
-    private $track;
+    private Track $track;
    ----------- end diff -----------

Applied rules:
 * TypedPropertyFromToOneRelationTypeRector
```

**Comment by samsonasik** [comment]
the rule is configurable, you can force it to non-nullable with set it to false, see

https://getrector.com/demo/03613c17-de4f-4d40-8952-1a42841cfd58

**Comment by abuhamza** [comment]
Thank you @samsonasik
