### ISSUE TITLE
Incorrect behavior of FirstClassCallableRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8728]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

I don't think this change makes sense

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/5ce94f90-8ad2-4768-ae8f-043c0289d3ae

```php
<?php

final class DemoFile
{
    private function validateForm(array $formData): void
    {
        $formData = array_map('trim', $formData);
    }
}
```

### Responsible rules

* `FirstClassCallableRector`

## Expected Behavior

no change

**Comment by staabm** [comment]
per https://3v4l.org/07X6j the change itself is correct.

I didn't expect his IMO controversial syntax in the default php 8.1 upgrade set.

**Comment by samsonasik** [comment]
This possibly needs to be configurable or separate rule, per my review on this https://github.com/rectorphp/rector-src/pull/6027#issuecomment-2188239310

**Comment by TomasVotruba** [comment]
I see. Probably separate optional rule be best.

cc @nikolicaleksa Could you check it?

**Comment by nikolicaleksa** [comment]
@TomasVotruba Yeah, I'll create a MR later to extract it to a separate rule. I'm assuming we should move that new rule from PHP81 to CodingStyle so it's not enabled by default, right?

**Comment by TomasVotruba** [comment]
@nikolicaleksa That would be best! Thank you :+1:

**Comment by flack** [comment]
IMO, the advantages for changing simple strings are the same as for changing callable arrays, namely better IDE support (help tooltips, jump to definition etc) and easier static analysis. But well, to each their own. Making it optional is probably a good compromise.

**Comment by staabm** [comment]
> IMO, the advantages for changing simple strings are the same as for changing callable arrays, namely better IDE support (help tooltips

I agree with your points. still I think this rector is more about code-style then it is about upgrading the php-version

**Comment by flack** [comment]
@staabm yeah, maybe. And it's really not a big deal if you can just add a second rector to get both transformations. Although with only the array transformation you might miss some opportunities to spot identical code, e.g.

```diff
- array_filter('my_class::filter', $value) == array_filter([my_class::class, 'filter'], $value);
+ array_filter('my_class::filter', $value) == array_filter(my_class::filter(...), $value);
```
