### ISSUE TITLE
[ERROR] The given paths do not match any files

### ISSUE THREAD

**Issue by VictorMARNETTO** [rectorphp/rector#8729]
Hi everyone, 

I have two old PHP apps I need to migrate to PHP 8.3 and I would like to use Rector which I don't know much about so I decided to follow the Github ReadMe Documentation.

The problem is, I installed composer and ran the command lines that are mentioned in documentation and followed the instruction but when I'm trying to "dry run" rector, I'm getting the following error : "[ERROR] The given paths do not match any files"

![image](https://github.com/rectorphp/rector/assets/47305928/9c3dcd25-3143-4131-b1e3-e117a0895123)

Could you please help me with this ? 
It might be something I did wrong but I don't know why and I can't find anything even on Stackoverflow.

Thank you for your help.

**Comment by samsonasik** [comment]
ensure that you have `src` dir in root directory, if you have directory named `app` , use `app` instead.

**Comment by VictorMARNETTO** [comment]
> ensure that you have `src` dir in root directory, if you have directory named `app` , use `app` instead.

Do you mean in PHP root directory ? If so I don't have any directory called app or src actually 

I have a directory called "_WEB" in which I saved the 2 apps I have to migrate and a directory called PHP in which I installed PHP 8.3 (dev, ext, extras, libs & vendor directories are inside this one) 

And I'm actually running rector command lines from my PHP directory, am I wrong ?
