### ISSUE TITLE
DeadCode rule fail to remove some params

### ISSUE THREAD

**Issue by etshy** [rectorphp/rector#8732]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.0            |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/b073cf8f-02c0-4874-9de7-708671d245c2

In the project, the `MyParameters` is in the same folder, hence no import used.
But it doesn't seem to be related to the lack of import though, here is a demo with an import and rector still dooesn't remove the `@param`
https://getrector.com/demo/5d195468-5383-40e0-ab10-d66f1266e98f

And here is a light config repro : https://getrector.com/demo/932a2e33-39a4-4e47-8d29-a00f9f38a6b8

## Expected Behaviour

The same with `Filesystem` the `@param` match the type-hint, so `@param MyParameters` should be removed
Recotr should have done that.
```diff
-    /**
-     * @param string $filename
-     * @param Filesystem $filesystem
-     * @param MyParameters $parameters
-     * @return bool
-     */
     public function export(string $filename, Filesystem $filesystem, MyParameters $parameters): bool;
```

**Comment by samsonasik** [comment]
You need to ensure `MyParameters` is autoloaded, see with defined class https://getrector.com/demo/f37aa823-2622-4a96-990b-0975dbd5c3f6

**Comment by etshy** [comment]
In the context of my project do you mean the file should be in `vendor/composer/autoload_classmap.php` ?
That's already the case.

Does rector need another autoload ?

**Comment by TomasVotruba** [comment]
It seems the param is not removed, even if class exists: https://getrector.com/demo/9f856c2d-9559-443f-b4d1-0a33943afac4

Interesting :)

**Comment by TomasVotruba** [comment]
@etshy Could you add failing test fixture?

**Comment by samsonasik** [comment]
@TomasVotruba it removed, see https://getrector.com/demo/f37aa823-2622-4a96-990b-0975dbd5c3f6

**Comment by TomasVotruba** [comment]
@samsonasik Why not this one, then? https://getrector.com/demo/e7a4a041-a4da-4637-b1da-a6a2f653c1f3
