### ISSUE TITLE
         Could not process "C:\xampp72\htdocs\oldboys\atk\ui\smarty\Smarty_Compiler.class.php" file, due to:      1"

### ISSUE THREAD

**Issue by wayneh** [rectorphp/rector#8737]
[Smarty_Compiler.class.pdf](https://github.com/user-attachments/files/16231756/Smarty_Compiler.class.pdf)

         #0
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\ParserAbstract.
         php(146): PhpParser\ParserAbstract->doParse()
         #1 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\PhpParser\Parser\SimplePhpParser.php(55):
         PhpParser\ParserAbstract->parse('<?php $this->_q...')
         #2
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\rules\Php72\NodeFactory\AnonymousFunctionFactory.php(
         152): Rector\PhpParser\Parser\SimplePhpParser->parseString('<?php $this->_q...')
         #3
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\rules\Php55\Rector\FuncCall\PregReplaceEModifierRecto
         r.php(98):
         Rector\Php72\NodeFactory\AnonymousFunctionFactory->createAnonymousFunctionFromExpr(Object(PhpParser\Node\Expr
         \BinaryOp\Concat))
         #4 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\Rector\AbstractRector.php(136):
         Rector\Php55\Rector\FuncCall\PregReplaceEModifierRector->refactor(Object(PhpParser\Node\Expr\FuncCall))
         #5
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(113): Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))
         #6
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(133): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
         #7
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
         #8
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(105): PhpParser\NodeTraverser->traverseArray(Array)
         #9
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #10
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(105): PhpParser\NodeTraverser->traverseArray(Array)
         #11
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #12
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(105): PhpParser\NodeTraverser->traverseArray(Array)
         #13
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(196): PhpParser\NodeTraverser->traverseNode(Object(Rector\PhpParser\Node\CustomNode\FileWithoutNamespace))
         #14
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.p
         hp(85): PhpParser\NodeTraverser->traverseArray(Array)
         #15
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(4
         1): PhpParser\NodeTraverser->traverse(Array)
         #16 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\Application\FileProcessor.php(105):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #17
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(184):
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #18
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(161):
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #19 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\Console\Command\WorkerCommand.php(118):
         Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),
         Object(Closure))
         #20
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(
         111): Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}(Array)
         #21 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(117):
         RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)
         #22
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(
         111): RectorPrefix202402\Clue\React\NDJson\Decoder->handleData(Array)
         #23 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\react\stream\src\Util.php(62):
         RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)
         #24
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.php(
         111): RectorPrefix202402\React\Stream\Util::RectorPrefix202402\React\Stream\{closure}('{"action":"main...')
         #25
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\react\stream\src\DuplexResourceStream.php(154)
         : RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)
         #26
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(201)
         : RectorPrefix202402\React\Stream\DuplexResourceStream->handleData(Resource id #1591)
         #27
         C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(173)
         : RectorPrefix202402\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #28 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\Console\Command\WorkerCommand.php(89):
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->run()
         #29 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\symfony\console\Command\Command.php(327):
         Rector\Console\Command\WorkerCommand->execute(Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvI
         nput), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))
         #30 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\symfony\console\Application.php(960):
         RectorPrefix202402\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202402\Symfony\Component
         \Console\Input\ArgvInput), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))
         #31 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\symfony\console\Application.php(333):
         RectorPrefix202402\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\WorkerCo
         mmand), Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))
         #32 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\src\Console\ConsoleApplication.php(53):
         RectorPrefix202402\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202402\Symfony\Component\C
         onsole\Input\ArgvInput), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))
         #33 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\vendor\symfony\console\Application.php(216):
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))
         #34 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\bin\rector.php(130):
         RectorPrefix202402\Symfony\Component\Console\Application->run()
         #35 C:\xampp72\htdocs\rector-standalone\vendor\rector\rector\bin\rector(4):
         require_once('C:\\xampp72\\htdo...')
         #36 C:\xampp72\htdocs\rector-standalone\vendor\bin\rector(115): include('C:\\xampp72\\htdo...')
         #37 {main}". On line: 272

**Comment by samsonasik** [comment]
Please provide reproducible code and config at https://getrector.com/demo or small reproducible repo with step by step to get the error, otherwise, nothing we can do

**Comment by samsonasik** [comment]
it possibly due to `PregReplaceEModifierRector`, I think parse error needs to be skipped on it

https://getrector.com/demo/dd106a78-dca5-454c-a991-090d76bd1ab7
