### ISSUE TITLE
Incorrect behavior of StrictArrayParamDimFetchRector

### ISSUE THREAD

**Issue by rtm-ctrlz** [rectorphp/rector#8743]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/ddbbd3d2-33cf-4d2b-acb7-8a72a616d100

```php
<?php

final class MyTest
{
    public function testDummy(...$args): mixed {
        return $args[count($args) - 1];
    }
}
```

### Responsible rules

* `StrictArrayParamDimFetchRector`

Suggested will break the code when `$args` is not an array of arrays:
```diff
-    public function testDummy(...$args): mixed {
+    public function testDummy(array ...$args): mixed {
```

## Expected Behavior

I think variadic parameters should be skipped in this case, see #8738.

**Comment by samsonasik** [comment]
Could you provide a patch? Thank you.
