### ISSUE TITLE
Incorrect behavior of ParamTypeByMethodCallTypeRector

### ISSUE THREAD

**Issue by benharold** [rectorphp/rector#8745]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/b671b569-f7b0-49f4-af09-ce5f86206260
Also https://getrector.com/demo/4fc301cd-e31e-47a8-bfdb-7dff625cf2d7

```php
<?php

class Example {
    public function hashSet(string $key, array $value): void {
        // whatever
    }
    
    /**
     * @param string $key
     * @param string|array $value
     */
    public function valueSet(string $key, $value): void {
        // whatever
    }
    
    public function set(string $type, string $key, $value): void {
    	switch ($type) {
            case 'hash':
                $this->hashSet($key, $value);
            case 'value':
                $this->valueSet($key, $value);
            default:
                throw Exception('ohno');
        }
    }
}
```

### Responsible rules

* `ParamTypeByMethodCallTypeRector`

## Expected Behavior

I would not expect the `array` type hint to be added to the `$value` parameter of the `set` method since `$value` can be either a `string` or an `array`.

**Comment by samsonasik** [comment]
It seems need to be `array|string`, and skip on non-native type included
