### ISSUE TITLE
Rector Error Report Post

### ISSUE THREAD

**Issue by smadarasptg** [rectorphp/rector#8747]
lando 14:20:10 VERBOSE ==> starting bootstrap at level engine...
lando 14:20:10 VERBOSE ==> config bootstrap beginning...
lando 14:20:10 VERBOSE ==> building proxy config...
lando 14:20:10 VERBOSE ==> config bootstrap completed.
lando 14:20:10 VERBOSE ==> tasks bootstrap beginning...
lando 14:20:11 VERBOSE ==> tasks bootstrap completed.
lando 14:20:11 VERBOSE ==> engine bootstrap beginning...
lando 14:20:11 VERBOSE ==> engine bootstrap completed.
lando 14:20:11 VERBOSE ==> bootstrap completed.
lando 14:20:11 VERBOSE ==> docker-engine exists: true
lando 14:20:11 VERBOSE ==> docker-compose exists: true
lando 14:20:13 VERBOSE ==> checking docker version compatibility...
web/forgot.html

 [ERROR] Could not process "web/forgot.html" file, due to:
         "System error: "str_starts_with(): Argument #1 ($haystack) must be of type string, null given"

         Stack trace:
         #0 utils/rector/src/Rector/TempoHeaderLocationToRedirectExceptionRector.php(69): str_starts_with(NULL,
         'Location')
         #1 vendor/rector/rector/src/Rector/AbstractRector.php(136):
         Utils\Rector\Rector\TempoHeaderLocationToRedirectExceptionRector->refactor(Object(PhpParser\Node\Expr\FuncCall
         ))
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(Rector\PhpParser\Node\CustomNode\FileWithoutNamespace))
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray(Array)
         #11 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):
         PhpParser\NodeTraverser->traverse(Array)
         #12 vendor/rector/rector/src/Application/FileProcessor.php(111):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #13 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #14 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #15 vendor/rector/rector/src/Console/Command/WorkerCommand.php(118):
         Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),
         Object(Closure))
         #16 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}(Array)
         #17 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202403\Evenement\EventEmitter->emit('data', Array)
         #18 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202403\Clue\React\NDJson\Decoder->handleData(Array)
         #19 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202403\Evenement\EventEmitter->emit('data', Array)
         #20 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202403\React\Stream\Util::RectorPrefix202403\React\Stream\{closure}('{"action":"main...')
         #21 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202403\Evenement\EventEmitter->emit('data', Array)
         #22 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202403\React\Stream\DuplexResourceStream->handleData(Resource id #1596)
         #23 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202403\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #24 vendor/rector/rector/src/Console/Command/WorkerCommand.php(89):
         RectorPrefix202403\React\EventLoop\StreamSelectLoop->run()
         #25 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):
         Rector\Console\Command\WorkerCommand->execute(Object(RectorPrefix202403\Symfony\Component\Console\Input\ArgvIn
         put), Object(RectorPrefix202403\Symfony\Component\Console\Output\ConsoleOutput))
         #26 vendor/rector/rector/vendor/symfony/console/Application.php(960):
         RectorPrefix202403\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202403\Symfony\Component\
         Console\Input\ArgvInput), Object(RectorPrefix202403\Symfony\Component\Console\Output\ConsoleOutput))
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(333):
         RectorPrefix202403\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\WorkerCom
         mand), Object(RectorPrefix202403\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202403\Symfony\Component\Console\Output\ConsoleOutput))
         #28 vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202403\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202403\Symfony\Component\Co
         nsole\Input\ArgvInput), Object(RectorPrefix202403\Symfony\Component\Console\Output\ConsoleOutput))
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(216):
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202403\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202403\Symfony\Component\Console\Output\ConsoleOutput))
         #30 vendor/rector/rector/bin/rector.php(130): RectorPrefix202403\Symfony\Component\Console\Application->run()
         #31 vendor/rector/rector/bin/rector(5): require_once('vendor/rec...')
         #32 vendor/bin/rector(119): include('vendor/rec...')
         #33 {main}". On line: 69

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by samsonasik** [comment]
It seems you're using custom rule: `TempoHeaderLocationToRedirectExceptionRector`, create a code: `str_starts_with(NULL, 'Location')`, which error after executed, see https://3v4l.org/poQJQ

refactor your custom rule to make string on 1st `str_starts_with()` ;)

In case you want to upgrade first, you may need to refactor to pass empty string instead, with `NullToStrictStringFuncCallArgRector`, see https://getrector.com/demo/7e636cc2-3461-41da-a03c-fc2b142a3e08
