### ISSUE TITLE
Incorrect behavior of RemoveNonExistingVarAnnotationRector

### ISSUE THREAD

**Issue by joshbmarshall** [rectorphp/rector#8750]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/bc06bd69-5e00-42e3-bb8b-bceac8a601d1

```php
<?php

/** @var array $params */
ob_start();
echo $params['test'];
echo ob_get_clean();
```

### Responsible rules

* `RemoveNonExistingVarAnnotationRector`

## Expected Behavior

Rector should not have removed the var annotation as that variable does exist in the file.

If it is immediately before the `echo $params['test'];` line it does not remove it.

I put these at the top of the file for convenience, as sometimes there are multiple variables and it's neater to define them all in a block at the top rather than intermingled throughout the file.

**Comment by samsonasik** [comment]
In that case, you need to define after `ob_start()`, see https://getrector.com/demo/1ca8e867-8176-4419-8d95-4795e729c958

**Comment by samsonasik** [comment]
closing as the solution provided above.

**Comment by joshbmarshall** [comment]
This is inconsistent with this example, that doesn't need the `ob_start()` to be before the define:

https://getrector.com/demo/9befcded-56f0-4167-ae01-54681f6a2fed

**Comment by samsonasik** [comment]
The rule don't remove multiple `@var`.
