### ISSUE TITLE
Incorrect behavior of NullToStrictStringFuncCallArgRector

### ISSUE THREAD

**Issue by joshbmarshall** [rectorphp/rector#8751]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/34d5f287-81c1-4f4a-9f87-6f62dd106e16

```php
<?php

namespace Sell;

class Customer
{
    public static function currentCustomer(): \Sell\Customer
    {
        return \Sell\Customer::q()->find_one();
    }

    public static function findOrCreate(string $name)
    {
        $customer = self::currentCustomer();
        if ($customer) {
            return $customer;
        }

        $customer = \Sell\Customer::q()->find_one();

        $names = explode(' ', trim($name), 2);

        return $customer;
    }

}
```

### Responsible rules

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

Rector is adding a (string) before the `$name` inside the `trim` but it is typed as a string already.

This is the most minimal code I could get it to add that in. If I remove other lines it does not add the (string)

**Comment by samsonasik** [comment]
That's due to `self::currentCustomer()` never returns empty data, which always return native `Customer` instance,  update `currentCustomer` method to returns nullable, so after conditional always valid, see https://getrector.com/demo/d8521c0e-bdee-408d-a90b-736b7c761bca

**Comment by joshbmarshall** [comment]
That makes no sense whatever. `$name` is unaffected by `currentCustomer()` so why is an unrelated piece of code causing it to enforce type?

**Comment by samsonasik** [comment]
because it detect by type, ensure that you have phpstan in place first to know the reasoning.

**Comment by joshbmarshall** [comment]
Yes I agree in the example, `findOrCreate` function will return early and the `explode` will never run (dead code) but I don't understand why `$name` would be forced type in the `trim`.

**Comment by samsonasik** [comment]
because the type become mixed after always true condition above, again, verify with phpstan, fix that, and you will get expected output.
