### ISSUE TITLE
Could not to remove positional value from annotation

### ISSUE THREAD

**Issue by pincher2012** [rectorphp/rector#8752]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.1           |

Could not remove positional parameter from DoctrineAnnotationTagValueNode by int index, because `AbstractValuesAwareNode::removeValue` have string type.

## Minimal PHP Code Causing Issue

```php
/**
 * @OA\Schema(
 *     schema="ContentBlockTreeResponseDTO",
 *     @OA\Property(property="id", type="integer"),
 * )
 */
class SchemaWithUnnamedParameterDto
{
}
```

```php
foreach ($doctrineTagValueNode->getValues() as $value) {
    $doctrineTagValueNode->removeValue($key);
}
```

```
TypeError: Rector\BetterPhpDocParser\ValueObject\PhpDoc\DoctrineAnnotation\AbstractValuesAwareNode::removeValue(): Argument #1 ($desiredKey) must be of type string, int given
```

## Expected Behaviour

I have ability to remove annotation positional value

**Comment by samsonasik** [comment]
Could you create failing test case for it, basically, create a reproducible test like this one https://github.com/rectorphp/rector-src/tree/main/tests/Issues/PartialValueDocblockUpdate , that's are:

1.  `Source` have custom rule example,
2.  `Fixture` for expected input and output,
3.  `config` for config to load for custom rule, 
4.   test class for it.

**Comment by pincher2012** [comment]
Ready!
https://github.com/pincher2012/rector-8752

**Comment by pincher2012** [comment]
@samsonasik I create test cases in my fork. Should I create PR?

**Comment by samsonasik** [comment]
yes please 👍

**Comment by TomasVotruba** [comment]
Closing as answered in https://github.com/rectorphp/rector-src/pull/6172 :+1:
