### ISSUE TITLE
`UnusedForeachValueToArrayKeysRector` removes values that are used

### ISSUE THREAD

**Issue by sreichel** [rectorphp/rector#8753]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.1             |
| Rule | UnusedForeachValueToArrayKeysRector             |

This rule also removes values that are later used in that method ...

## Minimal PHP Code Causing Issue

Demo-page returns 500 error ... 

See 

- https://github.com/sreichel/magento-lts/pull/1/files#diff-f41ae70f01bb5969abbb4c815813e7393574ddb38562951b6012b0c1a8a84a5d (search for app/code/core/Mage/Core/Model/Date.php)
- https://github.com/sreichel/magento-lts/actions/runs/10020627174/job/27698413846

## Expected Behaviour

If the value is used lat,er it should be skipped.

**Comment by samsonasik** [comment]
Demo page should be fixed now, could you retry?

**Comment by sreichel** [comment]
Nice. Thanks.

https://getrector.com/demo/49c46d79-b116-40e9-bed3-e14e98c24405

**Comment by sreichel** [comment]
Another one ... `&$storeCode` changed to `&$storeId` ... ?!?

`$storeCode` isnt used later. Did not test it, but this looks wrong ...

![github3](https://github.com/user-attachments/assets/1e0b8cf3-b19b-49e5-bdf4-ebe501c7a181)

**Comment by samsonasik** [comment]
Could you create example at https://3v4l.org/ that show invalid result on reference?

**Comment by sreichel** [comment]
Yes, i will do. But 2nd one is strange ... there is similiar code in the same file (unsed referernce) that is not changed. Gimme one or two days to test.

**Comment by samsonasik** [comment]
No worries, we can fix one by one with new issue if needed
