### ISSUE TITLE
Incorrect behavior of AddMethodCallBasedStrictParamTypeRector, BoolReturnTypeFromBooleanStrictReturnsRector, ReturnUnionTypeRector

### ISSUE THREAD

**Issue by atasky** [rectorphp/rector#8758]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d65fd944-cae7-4edd-b3b7-2674b0e2ed93

```php
<?php

final class DemoFile
{
    public function run(bool $param)
    {
        if ($this->isTrue($param)) {
            return 5;
        }

        return '10';
    }

    private function isTrue($value)
    {
        return $value === true;
    }
}
```

### Responsible rules

* `AddMethodCallBasedStrictParamTypeRector`

* `BoolReturnTypeFromBooleanStrictReturnsRector`

* `ReturnUnionTypeRector`

**Comment by samsonasik** [comment]
that's expected.
