### ISSUE TITLE
Cannot instantiate custom generator `doctrine.ulid_generator`

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#8760]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.1.1 |

This issue got already reported here #7911, but closed with an inappropriate solution (using FQCN). As @nicolas-grekas pointed out in https://github.com/symfony/symfony-docs/pull/18427#pullrequestreview-1486527166, this is not the same. Using the FQCN won't return the service, but a new one.

While using the `phpstan/phpstan-doctrine` extension in `phpstan` and `rector`, I only face this issue using rector. PHPStan is fine.

```php
// rector.php
    ->withPHPStanConfigs([
        __DIR__.'/phpstan.dist.neon',
        __DIR__.'/vendor/phpstan/phpstan-doctrine/extension.neon',
       // ...
```

```neon
# phpstan.dist.neon
parameters:
    doctrine:
        objectManagerLoader: tests/phpstan/object-manager.php
```

@SiebeVE already asked in https://github.com/rectorphp/rector/issues/7911#issuecomment-1798160928 for this, but it didn't get any attention yet. Probably because the issue was prematurely closed.

While it's true it may work using the FQCN, Rector should be able to use PHPStans configuration. 

If I'm able to create a reproducer (as 2 entities prior to my latest changes used `doctrine.ulid_generator` instead of FQCN, but the generated code of `symfonycasts/password-reset-bundle` broke it), I'll provide it.

## Minimal PHP Code Causing Issue

```php
class MyEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.ulid_generator')]
    #[ORM\Column(type: UlidType::NAME, unique: true)]
    private Ulid $ulid;
}
```

## Expected Behaviour

Rector should be able to understand it, since PHPStan does already.

**Comment by TomasVotruba** [comment]
Thanks for reporting. Could you put in simple words, what is the issue?
Is it some specific Rector rule or simple parsing the file?

We're not always using same autoload paths as PHPStan. The problem is that Doctrine extension breaks static reflection and loads container of project:

```neon
    objectManagerLoader: tests/phpstan/object-manager.php
```

That's a trade off that disables using Doctrine extension directly in Rector. Typical fix is to use custom PHPStan config without those dynamic configurations:

```php
return RectorConfig::configure()
    ->withPHPStanConfigs([
        __DIR__ . '/rector-phpstan.neon` 
    ]);
```

**Comment by mvhirsch** [comment]
> Thanks for reporting. Could you put in simple words, what is the issue?
>  Is it some specific Rector rule or simple parsing the file?

I'm sorry, I thought it was clear by referencing the original issue, as I'm facing the same issue. However, my issue is, that I'm facing this error message, using PHPStan's `phpstan/phpstan-doctrine` extension enabled in rector (see configuration above):

```
[ERROR] Could not process "/path/to/project/src/Controller/ResetPasswordController.php" file, due to: 
         "System error: "Cannot instantiate custom generator : array (                                                  
           'class' => 'doctrine.ulid_generator',                                                                        
         )"       
```

I did not expect this error. 

> Ideally always provide https://getrector.com/demo link or if not possible, minimal reproducible repository on Github with failing action. That way we avoid back-and-forth- guessing.

I understand that. As I mentioned already I'll provide a reproducer if I'm able to reproduce it using `symfonycasts/reset-password-bundle` on a public project. The fact that it did work prior installing this bundle confuses me and let me research a bit (resulting in linked issues above).

> That's a trade off that disables using Doctrine extension directly in Rector. Typical fix is to use custom PHPStan config without those dynamic configurations:

That's something I did not know. Is there any guide that covers known issues like these? What PHPStan extensions should I turn off/on while using PHPStan on the very same project?

**Comment by TomasVotruba** [comment]
> Is there any guide that covers known issues like these? What PHPStan extensions should I turn off/on while using PHPStan on the very same project?

Not at the moment, as it's edge case behavior.

I usually disable doctrine entity manager line and it does the job.
