### ISSUE TITLE
Rector\CodeQuality\Rector\FunctionLike\SimplifyUselessVariableRector; in deadcode level

### ISSUE THREAD

**Issue by Harfusha** [rectorphp/rector#8763]
In rector deadcode level there is Rector\CodeQuality\Rector\FunctionLike\SimplifyUselessVariableRector; used and when deadcode level is used with codequality level, then this error is thrown 
**[ERROR] Following rules are registered twice: Rector\CodeQuality\Rector\FunctionLike\SimplifyUselessVariableRector**

**Comment by TomasVotruba** [comment]
I see. The `SimplifyUselessVariableRector` rule should be removed from code quality set, to make sets mutually exclusive.

**Comment by samsonasik** [comment]
since it has `CodeQuality` namespace, the one that needs to be removed is in `CodeQualityLevel` imo

**Comment by Harfusha** [comment]
https://github.com/rectorphp/rector/pull/8764

**Comment by samsonasik** [comment]
@Harfusha please create at rector-src instead https://github.com/rectorphp/rector-src

**Comment by TomasVotruba** [comment]
@samsonasik Regardlress the namespace, this rule only removes dead code. That's why I'd expect it in there.

**Comment by Harfusha** [comment]
https://github.com/rectorphp/rector-src/pull/6201

**Comment by TomasVotruba** [comment]
Thanks @Harfusha :+1: 

Resolved in https://github.com/rectorphp/rector-src/pull/6201
