### ISSUE TITLE
@doesNotPerformAssertions is added even if assertion is done in called function

### ISSUE THREAD

**Issue by Harfusha** [rectorphp/rector#8765]
In unittest i have checker method that is making assertions.
These tests that have no assertions on first level but are calling this checker method.
For all tests that are not making any assertions but are calling checker method is @doesNotPerformAssertions added and then phpunit is throwing warnings

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:
