### ISSUE TITLE
Unexpected behaviour in LongArrayToShortArrayRector

### ISSUE THREAD

**Issue by BorislavSabev** [rectorphp/rector#8767]
# Bug Report

| Subject            | Details    |
| :-------------------| :------------|
| Rector version | 1.2.2       |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/9fc895d1-a0ec-486e-bddf-285805fa8eda

**Input:**
```php
<?php

$longArray = array(
    'key1' => 'val',
    'key2' => 'val',
    'key3' => 'val',
    'key4' => 'val',
    'key5' => 'val',
    'key6' => 'val',
    'key7' => 'val',
    'key8' => 'val',
    'key9' => 'val',
    'key10' => 'val'
);
```

**Output:**
```
<?php

$longArray = ['key1' => 'val', 'key2' => 'val', 'key3' => 'val', 'key4' => 'val', 'key5' => 'val', 'key6' => 'val', 'key7' => 'val', 'key8' => 'val', 'key9' => 'val', 'key10' => 'val'];

```

### Responsible rules

* `LongArrayToShortArrayRector`

## Expected Behavior

I expect that Rector would only replace `array()` with `[]` but not remove the newlines between the opening and closing braces.
Additionally the /demo page does not display the closing bracket in it's diff output. This works fine locally.

**Comment by samsonasik** [comment]
That's expected, as it reprinted, you can use coding standard tool to tidy that.

**Comment by BorislavSabev** [comment]
@samsonasik I understand why that happens. At the same time the `LongArrayToShortArrayRector` rector is quite handy. Can it not be changed to not act as that?
Is there a global convention that rector should not apply style rules?

**Comment by samsonasik** [comment]
No.
