### ISSUE TITLE
Class property as return in willReturnCallback throws an exception

### ISSUE THREAD

**Issue by grambas** [rectorphp/rector#8769]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  v1.2.2     |

Using property as return in `willReturnCallback` provokes an exception. The problem should be in definition of property - `private (\Exception&MockObject)|null $mock = null;`  If property is not nullable then no exception is thrown: `private Exception&MockObject) $mock;`

## Minimal PHP Code Causing Issue

https://getrector.com/demo/25acb1a3-ba76-4822-8f1d-41ced4a3f365

**Comment by samsonasik** [comment]
Reproduced by `ClosureReturnTypeRector` https://getrector.com/demo/cd38cb79-577b-45b2-8ef4-162f8352c273
