### ISSUE TITLE
Documentation indicates that withSkipPath takes an array, but it only works with a string.

### ISSUE THREAD

**Issue by sflanker** [rectorphp/rector#8770]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| PHP Version | 8.2.22 |
| Rector version | tested on v1.0.4 and v1.2.2             |

The [documentation](https://getrector.com/documentation/ignoring-rules-or-paths) indicates that withSkipPath can be used with an array, but it only works with a string

## Minimal PHP Code Causing Issue

I cannot get anything using `withPaths` or `withSkipPath` to work on https://getrector.com/demo/, but the following `rector.php` used with `composer exec rector -- --dry-run` locally demonstrates the issue:

```
<?php

use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withSkipPath([
        __DIR__ . '/src/SingleFile.php',
        __DIR__ . '/src/WholeDirectory',
        // or use fnmatch
        __DIR__ . '/src/*/Tests/*',
    ]);
```

## Actual Behaviour

```
[ERROR] Rector\Configuration\RectorConfigBuilder::withSkipPath(): Argument #1 ($skipPath) must be of type string, array
         given, called in /app/rector.php on line 10     
```

## Expected Behaviour

Either withSkipPath should work as documented or the documentation should be updated to reflect reality.

**Comment by samsonasik** [comment]
Could you create PR to https://github.com/rectorphp/getrector-com/blob/main/resources/docs/ignoring-rules-or-paths.md with update to use `withSkip()` instead? Thank you.
