### ISSUE TITLE
Incorrect behavior of MultiExceptionCatchRector with inherited exceptions and orders

### ISSUE THREAD

**Issue by namex42** [rectorphp/rector#8771]
# Bug Report

Incorrect behaviour when an order is important.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.0     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d085aaf1-187f-47c7-a65b-8d9093cd28c3

```php
<?php

try {
    // some
} catch(RuntimeException $e) {
   throw new Exception(); 
} catch(TypeError $e) {
    echo 123;
    
    throw new Exception();
} catch(Error $e) {
    throw new Exception();
}
```

### Responsible rules

* `MultiExceptionCatchRector`

## Expected Behavior
Leave as is or:
```php
<?php

try {
    // some
} catch(RuntimeException|Error $e) {
   if ($e instanceof TypeError) {
       echo 123;
   }

   throw new Exception(); 
}
```

**Comment by samsonasik** [comment]
Could you create demo on https://3v4l.org/ where order is matter?

**Comment by namex42** [comment]
@samsonasik, oops, sorry, I provided the wrong code example. Сorrected.

https://3v4l.org/W84ZQ - right case when 123 is printed. 
https://3v4l.org/19AlE - refactored code but 123 was not printed.

**Comment by TomasVotruba** [comment]
@namex42 Got it! I'm looking into this
