### ISSUE TITLE
Method name "readonly" mistaken for PHP keyword (with null-safe operator) (PHP 8.1)

### ISSUE THREAD

**Issue by s-ude** [rectorphp/rector#8772]
`PHP`: 8.1.29
`rector/rector`: 0.17.0
`phpstan/phpstan`: 1.11.9

I think this is the minimum setup needed to reproduce the issue. It only happens when I use the null-safe operator `?->`.

The same code does work, when I use PHP 8.2, though this might also change the installed rector and phpstan versions.

```php
class Test {
    public function test(): void {
        $this->foo?->readonly();
    }
}
```

Error:
```
Syntax error, unexpected T_READONLY, expecting T_STRING or T_VARIABLE or '{' or '$'74
```

**Comment by TomasVotruba** [comment]
Thanks for reporting. We no longer support Rector 0.17, upgrade to Rector 1.1 to get latest features & fixes.
