### ISSUE TITLE
Issue with Rector Compatibility with PHPStan and extension-installer?

### ISSUE THREAD

**Issue by VoDmAl** [rectorphp/rector#8773]
Hello,

I'm encountering an issue when using Rector in conjunction with PHPStan and the extension-installer. The problem seems to arise when Rector attempts to use the PHPStan configuration, leading to an error that doesn't occur when running PHPStan on its own.

Here's a minimal example that replicates the issue: [rector-phpstan-extension-installer](https://github.com/VoDmAl/rector-phpstan-extension-installer)

To reproduce:
Run PHPStan only. This works without any issues:
```
composer phpstan
```

Run Rector with the PHPStan configuration. This results in an error, seemingly due to the interaction with phpstan/extension-installer:
```
composer rector
```

I would appreciate any insights or guidance on how to resolve this incompatibility.

Thank you for your assistance!

**Comment by TomasVotruba** [comment]
My guess is that there is a problem with:

```neon
includes:
    - phar://vendor/phpstan/phpstan/phpstan.phar/conf/bleedingEdge.neon
```

As it loads differently in PHPStan and in Rector (due to different autoload priorities, as each has own php-parser and composer gets bit tricky there).

I'd try using custom phpstan config only for Rector. Simliar to: https://github.com/rectorphp/rector/issues/8760#issuecomment-2255859559

**Comment by VoDmAl** [comment]
Thank you for the insight. 

I see that maintaining separate configurations for Rector and PHPStan is a workaround. I have a lot of custom settings in my PHPStan configuration, and maintaining a separate, "clean" configuration for Rector... Let me think. 

Actually, I was hoping there might be a way to integrate them more seamlessly, especially since you've developed some interesting extensions for PHPStan. :)

**Comment by TomasVotruba** [comment]
We tried to automate it, but it created more bugs than help. It was trial & error work, as extension have tendency to add bit of static and bit of dynamic analysis. Later breaking static analysis we rely on.

In practice, Rector rarely pick ups a PHPStan extension feature :) We focus on native types and usually avoid magic that PHPStan extension try to cover.
