### ISSUE TITLE
Refactor using PropertyFetch with ClassConstFetch causes doom

### ISSUE THREAD

**Issue by Fabrn** [rectorphp/rector#8775]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.2             |

As I am working to replace our code using the `elao/enum` package by native PHP enums, I need to replace **class const fetches** (e.g. `Enum::CONSTANT`) and **method calls** (e.g. `Enum::CONSTANT()->getValue()`) by "enum case value getter" (e.g. `Enum::Constant->value`). This should be generated as a `PropertyFetch` (`Enum::Constant`) that holds a `ClassConstFetch` that fetches the property `value`. However, as I return my `PropertyFetch` **the command freezes and I have to force it to stop**, whether I use the `PropertyFetch` constructor or the node factory.

I then checked the `SpatieEnumMethodCallToEnumConstRector` which does the same thing, so this should not be a problem.

## Minimal PHP Code Causing Issue

I'm not able to reproduce a demo since it would require a real Spatie enum to try (I tried [like so](https://getrector.com/demo/8f4d29e2-7c3a-4491-a731-603362353176)) but here is a sample of code that should cause the issue : 

The enum : 

```php
use Elao\Enum\AutoDiscoveredValuesTrait;
use Elao\Enum\Enum;

/**
 * @method static MyEnum SOME_CONSTANT()
 */
class MyEnum extends Enum
{
    use AutoDiscoveredValuesTrait;

    final public const SOME_CONSTANT = 'my_value';
}
```

Some code : 

```php
return match ('test') {
    MyEnum::SOME_CONSTANT()->getValue() => "A",
    default => "",
};
```

The refactor code : 

```php
return $this->nodeFactory->createPropertyFetch(
    $this->nodeFactory->createClassConstFetchFromName(new Node\Name($enumName), $caseName),
    'value',
 );
```

## Expected Behaviour

The `MyEnum::SOME_CONSTANT()->getValue()` should be replaced by `MyEnum::SomeConstant->value` (don't the change to pascal case, it's something I added on my side but it doesn't impact the result).

## Additional information

If I replace the `ClassConstFetch` by a raw string it works. Also If I don't replace my Node by a `PropertyFetch` but simply using the `ClassConstFetch` it also works. Also if I only use the `ClassConstFetch` it works. It is specifically not working with that case.

I hope you will be able to reproduce it to prove I'm not crazy 😆 

Thanks in advance have a great day !

**Comment by Fabrn** [comment]
I'm back with some information. The issue (if we consider there is one) is caused by the fact that my custom rule listens to `ClassConstFetch` and it looks like that if I generate a `ClassConstFetch` wrapped in something, which is a `PropertyFetch` here, I create a loop because my rule tries to update something that just got generated over and over.

I confirm that removing the `ClassConstFetch` listening solves this issue. However, we do have them using Elao. I need to dodge nodes that were generated by the current rule.

**Comment by samsonasik** [comment]
You may looking for `\PhpParser\NodeTraverser\DONT_TRAVERSE_CHILDREN` when on specific Node, see these discussion and blog post:

- https://github.com/rectorphp/rector/discussions/8742
- https://getrector.com/blog/5-tricks-to-write-better-custom-rules

also, on very specific use case, you may need to have some flag on a node itself, eg, via attribute, something like this;

https://github.com/rectorphp/rector/blob/d40c7c43014c3c24135fdccb5600b69ca7e46c23/rules/Php54/Rector/Array_/LongArrayToShortArrayRector.php#L57-L64

You may need to specify your own attribute into the node for this check :)

**Comment by Fabrn** [comment]
Thanks for your quick answer ! I couldn't figure out a better way to check for the "startLine" attribute which is not set for new `ClassConstFetch` elements. I confirm it works now 🙂 

Sorry for the fake issue !
