### ISSUE TITLE
phpstan reports "Class xyz referenced with incorrect case" - how to automatically fix with rector?

### ISSUE THREAD

**Issue by MrJamesEllis** [rectorphp/rector#8776]
# Question

Hi, running phpstan 1.11 at level 5 across some code and it reports something like this in a file:

```sh
Class Org\Module\SomeClass referenced with incorrect case: Org\Module\Someclass
```

`Org\Module\SomeClass` is the correct case in Org/Module/SomeClass.php

I understand why this is reported, but I can't find a way with rector to automatically fix this.

The change in the file would be: 

```php
use Org\Module\Someclass;
```
to

```php
use Org\Module\SomeClass;
```

I think I'm missing something ?

**Comment by samsonasik** [comment]
You can use RenameClassRector, 

without auto import enabled: https://getrector.com/demo/261351e3-d4a7-490a-bbb6-db441ee85f7a
with auto import enabled + remove unused imports: https://getrector.com/demo/5d381a37-c708-443c-8a39-8d06fb26a925 to replace conflict lower name.
