### ISSUE TITLE
Incorrect behavior of ExplicitNullableParamTypeRector

### ISSUE THREAD

**Issue by jreklund** [rectorphp/rector#8777]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.2.2      |
| Installed as   | composer dependency  |

Rector overrides local files (same folder) and imported folder with FQN. Don't know if this is the indented behavior, but as I only enabled one rule to add `?` in front of all arguments I expected the rest to be kept as is. Could not find a configuration in the documentation to disable it at least.

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d27a7b83-6cab-4cdb-aa9d-38965ce92037

```php
<?php

namespace Subfolder\Demo;

use Orm\Auth;

final class DemoFile
{
	public function method(string $param, Auth\Group $group = null): array
    {
        return [];
    }
    
	public function method(string $param, Local $local = null): array
    {
        return [];
    }
}
```

### Responsible rules

* `ExplicitNullableParamTypeRector`

## Current Behavior

```php
public function method(string $param, ?\Orm\Auth\Group $group = null): array
```
```php
public function method(string $param, ?\Subfolder\Demo\Local $local = null): array
```

## Expected Behavior

```php
public function method(string $param, ?Auth\Group $group = null): array
```

```php
public function method(string $param, ?Local $local = null): array
```

**Comment by samsonasik** [comment]
This is expected as new type is grabbed from phpstan type: check not contains null -> add null type -> print node from old phpstan type + null type.

You can enable import names, while not same it apply to use statement instead of FQCN. https://getrector.com/demo/19b2656c-120b-4dbb-ad18-fa32ffd95a88

**Comment by jreklund** [comment]
Thanks for the quick reply. I'm afraid `withImportNames` does more harm than good in our use case. Will run it as is and fix the unwanted changes manually. It saves a lot of time than doing it completely by hand! <3
