### ISSUE TITLE
Php4ConstructorRector is skipping classes due to faulty reflection

### ISSUE THREAD

**Issue by kosimas** [rectorphp/rector#8778]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.2              |

I have a very big, messy and old php project. The project contains hundreds of php files and in each file there are sometimes up to 20 defined classes with a few thousand lines of code. All classes are using the php4 constructor method.
My config looks like this
```php
<?php

declare(strict_types=1);

require_once "./utils/rector/src/Rector/DefaultValuesObjectRector.php";

use Rector\Config\RectorConfig;
use Rector\Php70\Rector\ClassMethod\Php4ConstructorRector;
use Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector;
use Utils\Rector\Rector\DefaultValuesObjectRector;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/dbdt13',
    ])
    ->withRules([
        Php4ConstructorRector::class,
        CompleteDynamicPropertiesRector::class,
        DefaultValuesObjectRector::class,
    ])
    ->withoutParallel()
    ->withMemoryLimit("16384M");
```
I start rector like this (I'm using ddev for development)
```
ddev php vendor/bin/rector -n -vvv --clear-cache --xdebug
```

All classes are getting processed by the Php4ConstructorRector rule. However classes that inherit from another class are getting skipped at this line:
https://github.com/rectorphp/rector/blob/cbfdee3c3438aab426547722ff7935b95b98fb73/rules/Php70/Rector/ClassMethod/Php4ConstructorRector.php#L102

This happens because $classReflection->methods contains a __construct PhpMethodReflection instance. When reviewing $this->file->fileContent and originalFileContent there is no __construct method for these classes. Also the amount of methods and properties inside the reflection does not match up with the source code. However The displayName does match up with the class name. 

When I only process a single file with my rector config, everything works as expected. In this case the amount of methods still don't match up but the old constructor method gets replaced with __construct. There is no __construct method in $classReflection->methods which is correct.
## Minimal PHP Code Causing Issue
So far I was not able to reproduce this behavior outside of this specific project. I'm not allowed to share code from this project.
As soon as I manage to reproduce the error, I will add the code to this issue.

## Expected Behaviour
The Php4ConstructorRector rule should replace all old constructor methods when rector is processing a lot of files.

## What I tried so far
 - Reinstalling all composer packages
 - Updating rector
 - A little bit of tinkering with the rector config
 - Searching for similar rector issues

I'm by far no php or rector expert and the problem could also be caused by phpstan. I'm not sure.
Maybe someone with more knowledge can assist me with this issue.

**Comment by samsonasik** [comment]
if you have specific files to load, you can bootstrap the specific files, see documentation https://getrector.com/documentation/static-reflection-and-autoload

feel free to provide a reproducible repo if you have a chance ;)

**Comment by staabm** [comment]
I would try running cs-fixer instead of rector on the codebase for your condtructor case at hand

https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/class_notation/no_php4_constructor.rst
