### ISSUE TITLE
[RFC] Add an Help section inside the rector cli -h for fast info 

### ISSUE THREAD

**Issue by 94noni** [rectorphp/rector#8779]
`php vendor/bin/php-cs-fixer -h`

<img width="1246" alt="Capture d’écran 2024-08-08 à 17 43 52" src="https://github.com/user-attachments/assets/bc379375-ef06-4a5e-8f77-01bb195b347d">

`php vendor/bin/rector -h`

<img width="1393" alt="Capture d’écran 2024-08-08 à 17 44 24" src="https://github.com/user-attachments/assets/c5e8f084-b004-409c-8eac-df23e2a3c234">

**Comment by TomasVotruba** [comment]
Sounds good 👍 can you send PR?

**Comment by 94noni** [comment]
I will probably do for sure!
