### ISSUE TITLE
Inline comments after array get moved to next line and last comment is removed

### ISSUE THREAD

**Issue by Yohn** [rectorphp/rector#8780]
# Bug Report

Thanks for creating this script! 
I just installed it today and been playing with some old scripts, and saw this happen, and couldn't find anywhere else mentioning it.

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.2             |

I expected it to change the `array()` to `[]` but it moved the comments, which isn't that bad, but it would be better it the comments got moved before the array, instead of after the array. And please don't remove the last comment from the array.

## Minimal PHP Code Causing Issue

```php
$this->adminAlerts = array(
	'layout' => 1,	// new layout to approve
	'image' => 2, 	// "	image "		"
	'tutorial' => 3,// "	tutorial	"
	'Replay' => 4, // flagged layout
	'Repimg' => 5,	// "	image
	'Reppics' => 6,// " gallery pic
	'Repnotes' => 7 // reporting a note
);
```
## Expected Behavior
Change the `array()` to `[]`
```php
$this->adminAlerts = [
	'layout' => 1,	// new layout to approve
	'image' => 2, 	// "	image "		"
	'tutorial' => 3,// "	tutorial	"
	'Replay' => 4, // flagged layout
	'Repimg' => 5,	// "	image
	'Reppics' => 6,// " gallery pic
	'Repnotes' => 7 // reporting a note
];
```
## Actual Behavior
Comments got moved to new line, and now the last comment is missing
```php
$this->adminAlerts = [
	'layout' => 1,
	// new layout to approve
	'image' => 2,
	// "	image "		"
	'tutorial' => 3,
	// "	tutorial	"
	'Replay' => 4,
	// flagged layout
	'Repimg' => 5,
	// "	image
	'Reppics' => 6,
	// " gallery pic
	'Repnotes' => 7,
];
```

**Comment by samsonasik** [comment]
That's expected, we use nikic/php-parser, which current behaviour is comment is belong to next node. Last comment doesn't have node to hold, that's why it removed.

**Comment by Yohn** [comment]
Ok, thanks for the info! I can accept that. 
Is there anyway to change this to either keep the comments inline or place the comment before the node with the change rules, custom rules, or another way?

**Comment by samsonasik** [comment]
That's not possible via rector, you may need to use coding standard tool for that

**Comment by Yohn** [comment]
Aight, thanks for the info!
