### ISSUE TITLE
Incorrect behavior of SimplifyIfReturnBoolRector

### ISSUE THREAD

**Issue by kiatng** [rectorphp/rector#8781]
# Bug Report

It's not bug. The resulting code is convoluted and less readable.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/ec03b365-db13-4e75-8ecd-d3773ae96870

```php
<?php

final class DemoFile
{
    public function run($value)
    {
        if (!is_null($value) && !$value) {
            return false;
        }
        return true;
    }
}
```

### Responsible rules

* `SimplifyIfReturnBoolRector`

## Expected Behavior

With DeMorgan's Law, the result should be 

```php
        return is_null($value) || $value;
       // instead of
        return !(!is_null($value) && !$value);
```

**Comment by samsonasik** [comment]
That's possibly an improvement for separate rule: `SimplifyDeMorganBinaryRector`

https://github.com/rectorphp/rector/blob/39ccd68bc8f82aa88a5ef60e33c8561a616c24ac/rules/CodeQuality/Rector/BooleanNot/SimplifyDeMorganBinaryRector.php#L17

**Comment by kiatng** [comment]
Not sure if I made the test on `SimplifyDeMorganBinaryRector` correctly: https://getrector.com/demo/6a07c84e-3a20-45c6-9513-d20329994eb8 Please correct if mistakes were made. Rector should be able to simplify the convoluted bool expression produced from its own rule `SimplifyIfReturnBoolRector`.

**Comment by samsonasik** [comment]
That's complex, as I tried on "and" on https://github.com/rectorphp/rector-src/pull/6229 which cause unwanted apply. 

The rule currently only apply on negation on "or" operation inside, not "and", see https://getrector.com/demo/65df3a68-354d-4969-a1ec-29a4fc9c99b0

**Comment by samsonasik** [comment]
The roundable is expected, as new logic is printed by php-parser

**Comment by samsonasik** [comment]
I am going to close, as it not a bug, rather improvement for "and" with all negation inside operator, while I am not sure it worth the effort as too complex to cover unwanted change when run itself on rector-src codebase (run `bin/rector` under `rector/src`)

Feel free to create PR if you have better approach then my original PR https://github.com/rectorphp/rector-src/pull/6229

Thank you for understanding.

**Comment by sreichel** [comment]
Can we re-open this and put in "on hold".

I know its a complex task, but it is valid.

**Comment by samsonasik** [comment]
Feel free to create PR improvement yourself.
