### ISSUE TITLE
[type-declarations] New rule to fill param array based on param traverse callbacks

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8782]
I've found myself filling these types manually, while be always know the value fir sure :) 

If we we have a closure with strict param type e.g. `Type`, we know the passed array type will be `Type[]`. 

```diff
+/**
+ * @param KnownType[] $items
+ */
public function process(array $items)
{
	usort($items, function (KnownType $item) {
    {
    }
}
```

Functions like `array_walk()` and `array_filter()` should be checked for strict param type. Then new `@param Type[] $items` should be added.

This rule should target  `ClassMethod` and `Function_`.

We're adding docblock type here based on iterated strict type, so it's helpful to cover :+1:

**Comment by samsonasik** [comment]
I will try 👍
