### ISSUE TITLE
struggling with my first rule

### ISSUE THREAD

**Issue by DanielRuf** [rectorphp/rector#8784]
# Question

I'm trying to change some code like that:

```php
use \Namespace\ClassD;

ClassD::getA();
ClassD::getA(1,2,3);
```

to this:

```php
use \Namespace\ClassC;

ClassC::getB()->getValue();
ClassC::getB()->getValue(1, null, 2,3);
```

I tried to change `name` and `class` of `StaticCall::class` but I can not get the args. And I don't know how to change or add the `use` statement.

any pointers for the smallest possible solution?

**Comment by DanielRuf** [comment]
Thanks, that brings me a bit further.

> then after that, you can create custom rule to inject argument in the middle on MethodCall args which came from Namespace\ClassC::getB() StaticCall, and place the rule after that to inject the argument as needed.

Hm, I tried that but probably `$node->args` and `$node->getArgs()` is not correct. `$node` is `StaticCall` according to my IDE.

**Comment by DanielRuf** [comment]
Hm, what about the extra `getB()` in `getB()->getValue()`? Can I simply use a string like `getB()->getValue`?

**Comment by samsonasik** [comment]
You can learn about Node structure at AST page https://getrector.com/ast

For example https://getrector.com/ast/a4686a7810518c6c740f126e056bdb77c39b4847 , I renamed namespace named "Namespace" to "Some" for demo due to namespace is php syntax to avoid error.

**Comment by DanielRuf** [comment]
> You can learn about Node structure at AST page https://getrector.com/ast

Sure, but since this is a support issue the quick closure is not that helpful as it leaves me (the user) hanging with just too little information. I tried different ways but so far I still need some time to grasp the whole logic.

It's great that you are that quick, but it would be better to take some time to give a complete answer.

**Comment by samsonasik** [comment]
Learning AST requires time, and be slow is the way to go :)

On another chance , use discusion instead of issue https://github.com/rectorphp/rector/discussions/categories/q-a :)
