### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector

### ISSUE THREAD

**Issue by AlexeyKosov** [rectorphp/rector#8789]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/81bd8088-7e98-49ff-962c-8a69107c2651

```php
<?php

use Symfony\Component\Validator\Constraints as Assert;

class Model
{
    /**
     * @Assert\Type("string")
     */
    protected string $str;    
    
    /**
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     */
    protected array $items;
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

```php
<?php

use Symfony\Component\Validator\Constraints as Assert;

class Model
{
    #[Assert\Type('string')]
    protected string $str;    
    
    #[Assert\All([
        new Assert\Type('string'),
    ])]
    protected array $items;
}
```

**Comment by samsonasik** [comment]
that's specific on symfony 5.4 set list, you can register `SYMFONY_54` set list, ref https://getrector.com/demo/8b335703-58e4-425f-a388-b68b04ed8dbb
