### ISSUE TITLE
shor tag echo, reference assignment operator

### ISSUE THREAD

**Issue by trueliarx** [rectorphp/rector#8794]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.3    |

## Minimal PHP Code Causing Issue
1)
`<a href="abc.php?<?=$linkord?>">whatever</a>`

reported error: "System error: "Syntax error, unexpected '='"

The problem is related to very old code, including the short tag <?=

-----
2) 
=& (reference assignment operator).

reported error: Could not process

The problem is related to old code that works in php4/5.
ex. ckfinder 2 / ckeditor line 62. I will not update/refactor it (ckeditor) through rector but it is reported as non parsable.

## Expected Behaviour
1)
Identify it as a short for "echo".
`<a href="abc.php?<?php echo $linkord; ?>">whatever</a>`

2) 
https://stackoverflow.com/questions/1768343/reference-assignment-operator-in-php

**Comment by samsonasik** [comment]
we use nikic/php-parser which on mix HTML + PHP may cause unexpexted behaviour, use coding standard tool early to transform short open tag to long open tag :)
