### ISSUE TITLE
AddTypeToConstRector not working on Rector example code

### ISSUE THREAD

**Issue by integer** [rectorphp/rector#8795]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | [fc1e74](https://github.com/rectorphp/rector-src/commit/fc1e74)             |

I tried [AddTypeToConstRector](https://getrector.com/rule-detail/add-type-to-const-rector) and on many places no type added. So I tried example code in Rector definition and it provide no change. See linked demo below 👇 

## Minimal PHP Code Causing Issue

https://getrector.com/demo/c729d175-31da-419a-9772-a072d27f72d0

## Expected Behaviour

```
 final class SomeClass
 {
    public const string TYPE = 'some_type';
 }
```

**Comment by samsonasik** [comment]
That's PHP 8.3 feature, the demo page is using php 8.2, you can define php 8.3 feature flag to show it

https://getrector.com/demo/f279c66d-3a86-436c-a888-56af7080fbf8

otherwise, it will read composer.json php flag
