### ISSUE TITLE
Incorrect behavior of RenameForeachValueVariableToMatchExprVariableRector

### ISSUE THREAD

**Issue by frankii91** [rectorphp/rector#8796]
# Bug Report

error with more complex code...

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | now()        |

## Minimal PHP Code Causing Issue
code before using rector:

        if (isset($parameter['smarty_internal_index'])) {
            $output = "<?php \$_smarty_tpl->createLocalArrayVariable($_attr[var], {$_nocache}, {$_scope});\n\$_smarty_tpl->tpl_vars[$_attr[var]]->value$parameter[smarty_internal_index] = $_attr[value];";
        } elseif ($compiler->template->smarty instanceof SmartyBC) {
            // implement Smarty2's behaviour of variables assigned by reference
            $output = "<?php if (isset(\$_smarty_tpl->tpl_vars[$_attr[var]])) {\$_smarty_tpl->tpl_vars[$_attr[var]] = clone \$_smarty_tpl->tpl_vars[$_attr[var]];";
            $output .= "\n\$_smarty_tpl->tpl_vars[$_attr[var]]->value = $_attr[value]; \$_smarty_tpl->tpl_vars[$_attr[var]]->nocache = $_nocache; \$_smarty_tpl->tpl_vars[$_attr[var]]->scope = $_scope;";
            $output .= "\n} else \$_smarty_tpl->tpl_vars[$_attr[var]] = new SmartyVariable($_attr[value], $_nocache, $_scope);";
        } else {
            $output = "<?php \$_smarty_tpl->tpl_vars[$_attr[var]] = new SmartyVariable($_attr[value], $_nocache, $_scope);";
        }

code with syntax errors after changing:
    if (isset($parameter['smarty_internal_index'])) {
            $output = "<?php \$_smarty_tpl->createLocalArrayVariable($_attr[var], {$_nocache}, {$_scope});\n\$_smarty_tpl->tpl_vars[$_attr[var]]->value$parameter[smarty_internal_index] = $_attr[value];";
        } elseif ($compiler->template->smarty instanceof SmartyBC) {
            // implement Smarty2's behaviour of variables assigned by reference
            $output = sprintf('<?php if (isset($_smarty_tpl->tpl_vars[%s])) {$_smarty_tpl->tpl_vars[%s] = clone $_smarty_tpl->tpl_vars[%s];', $_attr[var], $_attr[var], $_attr[var]);
            $output .= "\n\$_smarty_tpl->tpl_vars[$_attr[var]]->value = $_attr[value]; \$_smarty_tpl->tpl_vars[$_attr[var]]->nocache = {$_nocache}; \$_smarty_tpl->tpl_vars[$_attr[var]]->scope = {$_scope};";
            $output .= "\n} else \$_smarty_tpl->tpl_vars[$_attr[var]] = new SmartyVariable($_attr[value], {$_nocache}, {$_scope});";
        } else {
            $output = sprintf('<?php $_smarty_tpl->tpl_vars[%s] = new SmartyVariable(%s, %s, %s);', $_attr[var], $_attr[value], $_nocache, $_scope);
        }

**Comment by samsonasik** [comment]
Could you reproduce at https://getrector.com/demo ? Thank you

**Comment by samsonasik** [comment]
I am closing it as no code and config provided. If I check your example, it seems you're changing smarty, that third party vendor, my suggestion is to not change vendor or third party code.

You can skip the path of it https://getrector.com/documentation/ignoring-rules-or-paths

**Comment by frankii91** [comment]
t4o że smarty to nie znaczy że w pełni zewnętrzne odłamane w około 2015 i
optymalizowane na własną rękę ...

pt., 30 sie 2024 o 20:42 Abdul Malik Ikhsan ***@***.***>
napisał(a):
