### ISSUE TITLE
Incorrect behavior of `TypedPropertyFromColumnTypeRector`

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#8797]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.2.2     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/512c28e0-0ebf-4e4a-86c8-1ceb600fdd71

```php
<?php

namespace App\Entity;

use App\Repository\AttachmentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AttachmentRepository::class, readOnly=true)
 */
class Attachment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="blob")
     *
     * @var resource
     */
    private $content = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return resource
     */
    public function getContent()
    {
        return $this->content;
    }
}
```

### Responsible rules

* `TypedPropertyFromColumnTypeRector`

## Expected Behavior

~Rector should add `resource` on blobs, not `string`.~ See DBAL types mapping: https://www.doctrine-project.org/projects/doctrine-dbal/en/4.0/reference/types.html#blob

**EDIT**: as there is no native `resource` type hint in PHP, rector must not add any changes in case above.

I really :heart: rector. It makes my work lot easier, especially on large, legacy code-bases. Thank you very much!

**Comment by samsonasik** [comment]
I am on mobile, resource seems can't be a type https://3v4l.org/o3sb7 , what change it should be?

**Comment by mvhirsch** [comment]
> I am on mobile, resource seems can't be a type https://3v4l.org/o3sb7 , what change it should be?

It should be `\resource`: https://3v4l.org/EP4lW

```diff
-   public ?resource $y;
+   public ?\resource $y;
```

Please note my project still uses PHP 7.4, that's why I typed it using PHPDoc. Sorry for inconvenience.

**Comment by mvhirsch** [comment]
Sorry, my fault. There is no typehint for `resource` as of this [RFC](https://wiki.php.net/rfc/scalar_type_hints). So the correct behaviour of `TypedPropertyFromColumnTypeRector` would be "no change" in my case.

**Comment by samsonasik** [comment]
I created PR:

- https://github.com/rectorphp/rector-doctrine/pull/340

for it, could you verify? Thank you.
