### ISSUE TITLE
Run coding standard check for every pull request

### ISSUE THREAD

**Issue by carlos-granados** [rectorphp/rector#8798]
# Feature Request

Right now you have a Github workflow that generates a weekly pull request to fix the coding standard style but I think this is not enough. Right now you allow pull requests that do not fully pass the cs check to be merged. This means that if you check out the main branch, do some work and run `composer complete-check`, it will find coding standard issues that have not been introduced by your work. These issues many times end up being fixed in unrelated pull requests, which is not ideal (see https://github.com/rectorphp/rector-src/pull/6238 for example, the fix for `tests/Issues/AutoImport/config/configured_rule.php` is unrelated to the rest of the code)

So I would add another job to the jobs that are run when you create a pull request that would either check the coding standard and notify you if it fails or directly fix the coding standard (I prefer the first option but you may disagree). Once this is done, the weekly job that creates the fix-cs pull request can be removed, as main should be passing the cs test all the time

**Comment by carlos-granados** [comment]
I can work on adding these changes if you confirm they are ok

**Comment by TomasVotruba** [comment]
The reason we don't have coding standard in CI is to make contributions easier. We take the burden of running it once upon a time.

While it would solve issue you describe, it would (and did) discouragged many first-time contributors.
It's a trade off to ease new contributors and give them as low entry level barrier as possible :pray:

**Comment by staabm** [comment]
Agree with having unrelated changes in PRs is super annoying and wastes time while reviewing for anyone
