### ISSUE TITLE
Remove -inline- unused variable assign

### ISSUE THREAD

**Issue by darthf1** [rectorphp/rector#8805]
# Feature Request

It would be great if there is a rule (or an upgrade of `RemoveUnusedVariableAssignRector`?) to also remove unused variables assigns if they are inline.
 
## Diff 

```diff
<?php

final class DemoFile
{
    public function run(bool $param): array
    {
        $returnValue = [
-            $innerValue = [
+           [
                'ok',
            ],
        ];
        
-	return $yes = $returnValue;
+       return $returnValue;
    }
}
```

**Comment by samsonasik** [comment]
I think you can create your own custom rule for that, testing variable inside array may be dangerous as I see, as variable can be anywhere outside the scope, while we should only check linear scope.

thank you for understanding.
