### ISSUE TITLE
Rules are registered twice when using helper methods and result in error

### ISSUE THREAD

**Issue by mrcyna** [rectorphp/rector#8806]
# Bug Report

When using helpers to add more rules (from different rules set) you will face error "Following rules are registered twice....":

My code:
```
return RectorConfig::configure()
    // ...
    ->withDeadCodeLevel(44)
    ->withTypeCoverageLevel(47)
    ->withCodeQualityLevel(12)
    //...
 ;
```

The error I get:
```
#####################################################
### Rector is analyzing the code to upgrade
#####################################################
##
####
#
[ERROR] Following rules are registered twice: Rector\CodeQuality\Rector\FunctionLike\SimplifyUselessVariableRector
```

**Reason is that we need to pass a unique array of rules.**

My solution at the moment was this but I wish I could use helper without being worry about duplications.
```
return RectorConfig::configure()
    // ...
    ->withRules(array_unique(array_merge(
        LevelRulesResolver::resolve(44, DeadCodeLevel::RULES, 'RectorConfig::withDeadCodeLevel()'),
        LevelRulesResolver::resolve(47, TypeDeclarationLevel::RULES, 'RectorConfig::withTypeCoverageLevel()'),
        LevelRulesResolver::resolve(12, CodeQualityLevel::RULES, 'RectorConfig::withCodeQualityLevel()')
    )))
   // ...
;
```

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 1.2.2             |
| PHP version | 5.4.42             |

Thank you for the great tool to help us with better coding.

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

Could you try latest 1.2.3? I recall this was fixed

**Comment by mrcyna** [comment]
> ->withDeadCodeLevel(44)
>     ->withTypeCoverageLevel(47)
>     ->withCodeQualityLevel(12)

You are right. It's working on the latest version.

Thank you for the help.

**Comment by szabrzyski** [comment]
Hi @TomasVotruba, I ran into this problem again in Rector 2.0.9 with different levels:

```
    ->withCodeQualityLevel(56)
    ->withCodingStyleLevel(18)
```

>  [ERROR] Following rules are registered twice: Rector\CodingStyle\Rector\ClassMethod\FuncGetArgsToVariadicParamRector,  
>          Rector\CodingStyle\Rector\FuncCall\CallUserFuncToMethodCallRector,                                             
>          Rector\CodingStyle\Rector\FuncCall\CountArrayToEmptyArrayComparisonRector
