### ISSUE TITLE
Much slower require on v1.2.4

### ISSUE THREAD

**Issue by andrei-e-random** [rectorphp/rector#8811]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.4  |

`Dockerfile:`

```
FROM composer

RUN mkdir /opt/rector-standalone \
    && cd /opt/rector-standalone \
    && composer require rector/rector --dev --prefer-dist -vvv --profile
```

`.dockerignore`:

```
*
```

Results in:

```
docker build .
[...]
#5 0.307 Running 2.7.8 (2024-08-22 15:28:36) with PHP 8.3.10 on Linux / 6.5.0-44-generic
[...]
#5 4.829 [82.0MiB/4.52s] Built pool.
#5 4.829 [82.0MiB/4.52s] Running pool optimizer.
#5 53.75 [147.8MiB/53.45s] Pool optimizer completed in 48.925 seconds
#5 53.75 [147.8MiB/53.45s] Found 13,712 package versions referenced in your dependency graph. 8,601 (63%) were optimized away.
[...]
#5 65.06 [67.2MiB/64.75s] Installs: phpstan/phpstan:1.12.0, rector/rector:1.2.4
#5 65.06 [67.2MiB/64.75s]   - Locking phpstan/phpstan (1.12.0) from composer repo (https://repo.packagist.org)
#5 65.06 [67.2MiB/64.75s]   - Locking rector/rector (1.2.4) from composer repo (https://repo.packagist.org)
[...]
```

Note the 48 seconds it takes for the pool optimizer to complete and the 13k+ packages referenced in your dependency graph. The issue appears to have been introduced in `v.1.2.4` because `Dockerfile`:

```
FROM composer

RUN mkdir /opt/rector-standalone \
    && cd /opt/rector-standalone \
    && composer require rector/rector:1.2.3 --dev --prefer-dist -vvv --profile
```

Results in
```
docker build .
[...]
#5 0.341 Running 2.7.8 (2024-08-22 15:28:36) with PHP 8.3.10 on Linux / 6.5.0-44-generic
[...]
#5 1.347 [12.7MiB/1.01s] Built pool.
#5 1.347 [12.7MiB/1.01s] Running pool optimizer.
#5 1.348 [12.8MiB/1.01s] Pool optimizer completed in 0.002 seconds
#5 1.348 [12.8MiB/1.01s] Found 64 package versions referenced in your dependency graph. 3 (5%) were optimized away.
[...]
#5 1.356 [13.0MiB/1.01s] Installs: phpstan/phpstan:1.12.0, rector/rector:1.2.3
#5 1.356 [13.0MiB/1.01s]   - Locking phpstan/phpstan (1.12.0) from composer repo (https://repo.packagist.org)
#5 1.356 [13.0MiB/1.01s]   - Locking rector/rector (1.2.3) from composer repo (https://repo.packagist.org)
```

**Comment by samsonasik** [comment]
never use `--profile` on composer require myself, it probably unrelated with us, as we only require phpstan in composer.json, probably commit composer.lock is usefull for your usecase.

**Comment by andrei-e-random** [comment]
@samsonasik 

I'm building a image where I provide useful tools for PHP upgrade, rector being one of them (btw, thanks a lot!). I try to have them installed as standalone - which is [supported by rector for the purpose of updating really old legacy codebases](https://getrector.com/documentation/how-to-run-on-php-53).

I don't usually use `--profile` myself, I just had to do it this time because my image is built in CI and CI (in this case bitbucket) just decided to kill `composer require rector/rector --dev` after a while. So I used `--profile` locally to see what was going on. I suspect the size of the pool is also taking a lot of memory, not just CPU, and that's what triggers Bitbucket CI to kill it.

The issue is unlikely to have the root cause in `rector`, it's much more likely to be in one of the dependencies, I agree. Nevertheless, it does affect the usage of `rector` as described in the link above.

Using `composer install` on a versioned lock files would kind of defeat the purpose of CI in this case. I will probably either do that or some other workaround for now, but that doesn't change the fact that your supported use-case is affected :)

**Comment by samsonasik** [comment]
I am not sure we can help with it, even I look in the previous commit, the "only added" next it immediatelly removed, see

https://github.com/rectorphp/rector-src/blob/816c73347df4a5e4da48903af1190c131fcccb8c/build/build-rector-scoped.sh#L37-L38

It maybe on other lib that interdependency with it.

My suggestion when building tools for rector is pin rector on specific version, and commit composer.lock, so you will get stable tool, for example, on laminas-servicemanager-migration, we add rector to require (not dev), commit composer.lock, and use renovate for notification of new release

https://github.com/laminas/laminas-servicemanager-migration

Thank you for understanding.

**Comment by andrei-e-random** [comment]
@samsonasik Thanks. That's how I'll handle it, for now:

> My suggestion when building tools for rector is pin rector on specific version, and commit composer.lock, so you will get stable tool, for example, on laminas-servicemanager-migration, we add rector to require (not dev), commit composer.lock, and use renovate for notification of new release
