### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector, MixedTypeRector

### ISSUE THREAD

**Issue by devnix** [rectorphp/rector#8812]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/436fdb2d-13f2-4619-bf26-483368f39f56

```php
<?php

final class DemoFile
{
    /**
     * The embodied request object.
     *
     * @var RequestInterface
     */
    protected $request;
    
    
    /**
     * The data contained in the response.
     *
     * @var mixed
     */
    protected $data;
    
    /**
     * Constructor
     *
     * @param RequestInterface $request the initiating request.
     * @param mixed $data
     */
    public function __construct(RequestInterface $request, $data)
    {
        $this->request = $request;
        $this->data = $data;
    }
}
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

* `MixedTypeRector`

**Comment by samsonasik** [comment]
That's due RequestInterface not autoloaded, ensure it autoloaded, and it will correctly applied, see https://getrector.com/demo/68f5a0c9-78ec-4085-85df-a0ec94d59ce2
