### ISSUE TITLE
Use Destructure/Destructuring instead of Destruct in the name of some rules and constants

### ISSUE THREAD

**Issue by carlos-granados** [rectorphp/rector#8813]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.4            |

In the `rector-src` repository there are several rector rules and constants that use the word `Destruct` instead of `Destructure` and they don't mean the same:
- Destruct is equivalent to destroy
- Destructure is equivalent to dismantle, split into separate parts

This can make these names seem wrong. For example the `ListToArrayDestructRector` seems to imply that the array is destroyed, while it is just split into several items. The name should be `ListToArrayDestructureRector` or `ListToArrayDestructuringRector` (I prefer the second one).

Affected rules and constants:
- `ListToArrayDestructRector`
- `MultiDimensionalArrayToArrayDestructRector`
- `ARRAY_DESTRUCT`

(Plus any related functions/tests)

**Comment by carlos-granados** [comment]
I can create a PR with these changes but would like to know what you want to do with the existing rules to avoid a BC break

**Comment by TomasVotruba** [comment]
This is not priority at the moment, as we try to keep BC of not-optimally named rules in case they're used.

Thanks :+1:
