### ISSUE TITLE
"System error: "Method pass() was not found"

### ISSUE THREAD

**Issue by WMedDavidSpillers** [rectorphp/rector#8816]
[ERROR] Could not process                                                                                              
         "modules/webform/tests/src/Traits/WebformBrowserTestTrait.php" file, due to: 
         "System error: "Method pass() was not found in reflection of class                                             
         Drupal\Tests\webform\Traits\WebformBrowserTestTrait."                                                          
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/palantirnet/drupal-rector/src/Utility/GetDeclaringSourceTrait.php(34):                               
         PHPStan\Reflection\ClassReflection->getMethod()                                                                
         #1 vendor/palantirnet/drupal-rector/src/Drupal9/Rector/Deprecation/PassRector.php(53):                         
         DrupalRector\Drupal9\Rector\Deprecation\PassRector->getDeclaringSource()                                       
         #2 vendor/rector/rector/src/Rector/AbstractRector.php(139):                                                    
         DrupalRector\Drupal9\Rector\Deprecation\PassRector->refactor()                                                 
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                          
         Rector\Rector\AbstractRector->enterNode()                                                                      
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #11 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):                              
         PhpParser\NodeTraverser->traverse()                                                                            
         #12 vendor/rector/rector/src/Application/FileProcessor.php(113):                                               
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                                 
         #13 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):                                    
         Rector\Application\FileProcessor->processFile()                                                                
         #14 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):                                    
         Rector\Application\ApplicationFileProcessor->processFile()                                                     
         #15 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(138):                                    
         Rector\Application\ApplicationFileProcessor->processFiles()                                                    
         #16 vendor/rector/rector/src/Console/Command/ProcessCommand.php(131):                                          
         Rector\Application\ApplicationFileProcessor->run()                                                             
         #17 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Console\Command\ProcessCommand->execute()                                                               
         #18 vendor/rector/rector/vendor/symfony/console/Application.php(960):                                          
         RectorPrefix202408\Symfony\Component\Console\Command\Command->run()                                            
         #19 vendor/rector/rector/vendor/symfony/console/Application.php(333):                                          
         RectorPrefix202408\Symfony\Component\Console\Application->doRunCommand()                                       
         #20 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202408\Symfony\Component\Console\Application->doRun()                                              
         #21 vendor/rector/rector/vendor/symfony/console/Application.php(216):                                          
         Rector\Console\ConsoleApplication->doRun()                                                                     
         #22 vendor/rector/rector/bin/rector.php(130): RectorPrefix202408\Symfony\Component\Console\Application->run()  
         #23 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #24 vendor/bin/rector(119): include('...')                                                                     
         #25 {main}". On line: 553

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by samsonasik** [comment]
It seems you're using drupal-rector, you can report to the drupal-rector repo or fix there https://github.com/palantirnet/drupal-rector
