### ISSUE TITLE
Error on running rector

### ISSUE THREAD

**Issue by xmanolis** [rectorphp/rector#8817]
# Question
Hi, 

I use the latest version of rector (1.2.4) and regardless of what I try in the config, I always get the error "The given paths do not match any files".

Not sure if it plays any role, but I have the vendor file inside a library folder, thus the command I run is 
"library/Vendor/bin/rector process src --dry-run".

Here is the config (it's actually the default one): 
`<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/application',
        __DIR__ . '/library',
    ])
    // uncomment to reach your current PHP version
    // ->withPhpSets()
    ->withTypeCoverageLevel(0);`

Any ideas?

**Comment by samsonasik** [comment]
You should place rector in root project when possible, also point `__DIR__ . /application` means `application` is linear with `rector.php` which same structure with `vendor` location as project root of the rector:

```
.
├── application
│   ├── Model
├── vendor
│   ├── rector
│   │   └── rector
├── composer.json
├── rector.php
```

see documentation for getting started https://getrector.com/documentation

**Comment by xmanolis** [comment]
But rector.php is already in root, structure is

.
├── application
│   ├── Model
├── library
 |    ├── Vendor 
│       ├── rector
│        │   └── rector
├── composer.json
├── rector.php

**Comment by samsonasik** [comment]
You pass `src` in the command, which `src` is not exists: `library/Vendor/bin/rector process src --dry-run`

**Comment by xmanolis** [comment]
Ah, so src is supposed to match to the folder, which I don't have. 
I get this error when I try also
library/Vendor/bin/rector process --dry-run

But I see now that it seems to be working when I run
library/Vendor/bin/rector process library --dry-run
So how is this argument after process taken into account? Is this the folder that rector should check or?

**Comment by samsonasik** [comment]
when you pass path in command, it read path passed, when not, it read config path.

**Comment by xmanolis** [comment]
ok, thanks, I got it, we either define the paths in the config or in the command. Thus it's working with command "library/Vendor/bin/rector process --dry-run", or to be more precise, it starts, it reaches 5% and then it throws

Applied rules:
 * Utf8DecodeEncodeToMbConvertEncodingRector
 
[ERROR] Could not process
         "/var/www/html/library/Vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/Para
         llelProcess.php" file, due to:		 
         "Child process timed out after 120 seconds". On line: 108
		 
[ERROR] Could not process some files, due to:
         "Reached system errors count limit of 50, exiting..."

**Comment by samsonasik** [comment]
You can read documentation for it https://getrector.com/documentation/troubleshooting-parallel

I guess you're scanning too many files, can be a third party, which you can skip instead, read the doc for it https://getrector.com/documentation/ignoring-rules-or-paths
