### ISSUE TITLE
[CodeQuality] Add new rule to change "static::CONSTANT" to "self::CONSTANT"

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#8818]
In class that has constant in the same class, has no parent class, follwoing should be changed to `self` as no other constant is available.

```diff
class SomeClass
{
    private const NAME = 'cool rule';


  public function run()
  {
-	return static::NAME;
+	return self::NAME;
   }   
}
```

It also fixes PHPStan reports :+1:

**Comment by samsonasik** [comment]
It seems only works on private constant, on protected/public, it still needed, see

https://3v4l.org/rPYm0 vs https://3v4l.org/80571

**Comment by samsonasik** [comment]
Actually, there is already rule `ConvertStaticPrivateConstantToSelfRector` for that, see https://getrector.com/demo/5c3ff3fc-8b61-45d1-acab-2bb3f974f3af

**Comment by samsonasik** [comment]
I added ability to change into self on final class:

- https://github.com/rectorphp/rector-src/pull/6295

**Comment by TomasVotruba** [comment]
Thank you 🙏
