### ISSUE TITLE
Incorrect behavior of TypedPropertyFromColumnTypeRector

### ISSUE THREAD

**Issue by Nialsihg** [rectorphp/rector#8819]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/5c42ba26-7643-4727-b119-b63e0703353a

```php
<?php

declare(strict_types=1);

use Doctrine\ORM\Mapping as ORM;

class CardEngine
{
    /**
     * @var bool
     */
    #[ORM\Column(name: 'canonical', type: 'boolean', options: ['default' => 0])]
    private $canonical = false;
}
```

### Responsible rules

* `TypedPropertyFromColumnTypeRector`

## Expected Behavior

```php
<?php

declare(strict_types=1);

use Doctrine\ORM\Mapping as ORM;

class CardEngine
{
    /**
     * @var bool
     */
    #[ORM\Column(name: 'canonical', type: 'boolean', options: ['default' => 0])]
    private bool $canonical = false;
}
```

The property should be typed as `bool` instead of `?bool` because the default value for the `nullable` argument is `false`.

Note that the issue doesn't appear if we declare explicitly the `nullabe` argument to `false`.

**Comment by samsonasik** [comment]
without initialization in __construct, nullable is expected.

Closing as duplicated with https://github.com/rectorphp/rector/issues/7709 and there is unfinished configurable PR for it https://github.com/rectorphp/rector-doctrine/pull/191

**Comment by Nialsihg** [comment]
> without initialization in __construct, nullable is expected.

Hi @samsonasik ,

I understand that this is to avoid the `uninitialized property` error.

However, I believe there is still a bug in this particular case because the property is already initialized.

Using the constructor to initialize the property still produces `?bool` instead `bool`.

See https://getrector.com/demo/4244ba67-831f-46d9-85ce-e2b742d17266

```php
<?php

declare(strict_types=1);

use Doctrine\ORM\Mapping as ORM;

class CardEngine
{
    /**
     * @var bool
     */
    #[ORM\Column(name: 'canonical', type: 'boolean', options: ['default' => 0])]
    private $canonical;
    
    public function __construct() {
        $this->canonical = false;
    }
}
````

⚠️ I noticed that the rule behaves correctly if I explicitly set `nullable: false` in the `ORM\Column` attribute even though it's already [the default value](https://github.com/doctrine/orm/blob/3.2.x/src/Mapping/Column.php#L27)

See https://getrector.com/demo/456122d7-ca1f-40cd-b0e4-9e01f0cd36be
```php
<?php

declare(strict_types=1);

use Doctrine\ORM\Mapping as ORM;

class CardEngine
{
    /**
     * @var bool
     */
    #[ORM\Column(name: 'canonical', type: 'boolean', nullable: false, options: ['default' => 0])]
    private $canonical = false;
}
````

After a bit of debugging it seems that the method [`Rector\Doctrine\NodeAnalyzer\AttributeFinder::findAttributeByClassArgByName()`](https://github.com/rectorphp/rector-doctrine/blob/main/src/NodeManipulator/NullabilityColumnPropertyTypeResolver.php#L37) isn't able to find the attribute if the `nullable` argument is not declared explicitly on the attribute 🤔

**Comment by samsonasik** [comment]
`nullable` needs to be defined, otherwise, it will be nullable.

in that case, if you want more strict, typeDeclarations set can be enabled early, that better to use for your use case https://getrector.com/demo/e653593d-bc70-40da-8503-ffb7d31f8417

improvement is welcome, but require user effort for it, as previous configurable PR is stalled. Most of the time, when it never filled, it will become nullable as that is the safe belt.

For tip: you can use `TrustedClassMethodPropertyTypeInferer::inferProperty()` for that :)

**Comment by Nialsihg** [comment]
> nullable needs to be defined, otherwise, it will be nullable.

I'm sorry if I misunderstood, but why ?

I believe it should be the opposite because the `Column` attribute as `public readonly bool $nullable = false` in its constructor

See https://github.com/doctrine/orm/blob/3.2.x/src/Mapping/Column.php#L27
```php
<?php

declare(strict_types=1);

namespace Doctrine\ORM\Mapping;

use Attribute;
use BackedEnum;

#[Attribute(Attribute::TARGET_PROPERTY)]
final class Column implements MappingAttribute
{
    /**
     * @param int|null                      $precision The precision for a decimal (exact numeric) column (Applies only for decimal column).
     * @param int|null                      $scale     The scale for a decimal (exact numeric) column (Applies only for decimal column).
     * @param class-string<BackedEnum>|null $enumType
     * @param array<string,mixed>           $options
     * @psalm-param 'NEVER'|'INSERT'|'ALWAYS'|null $generated
     */
    public function __construct(
        public readonly string|null $name = null,
        public readonly string|null $type = null,
        public readonly int|null $length = null,
        public readonly int|null $precision = null,
        public readonly int|null $scale = null,
        public readonly bool $unique = false,
        public readonly bool $nullable = false,
        public readonly bool $insertable = true,
        public readonly bool $updatable = true,
        public readonly string|null $enumType = null,
        public readonly array $options = [],
        public readonly string|null $columnDefinition = null,
        public readonly string|null $generated = null,
    ) {
    }
}
```

Which meens that
```php
#[ORM\Column(name: 'canonical', type: 'boolean', nullable: false)]
```

Is exactly the same as
```php
#[ORM\Column(name: 'canonical', type: 'boolean')]
```
and the output of the rule shouldn't differ

**Comment by samsonasik** [comment]
Feel free to contribite with provide improvement PR, otherwise, use typeDeclarations set as I mentioned before should fit for you.

thanks!
