### ISSUE TITLE
Issue after upgrading from 1.2.4 to 1.2.5

### ISSUE THREAD

**Issue by u01jmg3** [rectorphp/rector#8820]
# Bug Report

- After using `1.2.4` with no issues and then upgrading to `1.2.5` Rector now fails with the following.

**On GitHub Actions I get multiple errors which state:**

Could not process                                                      
`/home/runner/work/ars/laravel/app/Http/Controllers/Admin/AbstractSubmissionController.php` file, due to: "System error: `PhpParser\Node\Stmt\ClassMethod` itself does not have any type. Check the `PhpParser\Node\Stmt\ClassLike` node instead". On line: 132

**Locally, on Windows I get:**

<img width="50%" src="https://github.com/user-attachments/assets/fade4198-b712-436a-bf17-ba65a0e2c927">

## Minimal PHP Code Causing Issue

Before I dig into the code, what has changed with Rector to break it for me so catastrophically?

## Expected Behaviour

To work as it did on `1.2.4`

**Comment by samsonasik** [comment]
sure, see https://github.com/driftingly/rector-laravel/pull/247

**Comment by TomasVotruba** [comment]
Thank you @samsonasik :+1:
