### ISSUE TITLE
`composer update` failure on applying patches on `rector-src` on MacOS M3

### ISSUE THREAD

**Issue by SanderMuller** [rectorphp/rector#8821]
# Question

I'm trying to get https://github.com/rectorphp/rector-src running locally on MacOS M3.

However, `composer update` gets stuck on applying patches:
![image](https://github.com/user-attachments/assets/7d7fcd13-eb11-483a-ade1-550c4435ae2c)

---- 
When I run `composer update -v` I can see that it's asking interactive questions, but it doesn't help in actually getting it to execute without failures:

![image](https://github.com/user-attachments/assets/d0ad45f1-b526-480c-8393-1fb1e564a331)

![image](https://github.com/user-attachments/assets/61ce1458-d233-45a2-aefb-ac18ee8498d6)

---

Does anyone have experience getting this to run on their Sillicon Macbook? 

Thanks in advance, would greatly appreciate it!

**Comment by samsonasik** [comment]
You need to install gpatch:

```
brew install gpatch
```

https://github.com/symplify/vendor-patches?tab=readme-ov-file#troubleshooting

**Comment by SanderMuller** [comment]
> You need to install gpatch:
> 
> ```
> brew install gpatch
> ```
> 
> https://github.com/symplify/vendor-patches?tab=readme-ov-file#troubleshooting

Thank you!
