### ISSUE TITLE
InlineConstructorDefaultToPropertyRector does not handle comments correctly

### ISSUE THREAD

**Issue by carlos-granados** [rectorphp/rector#8826]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.5            |

When moving the initialization of a property from the constructor to the default value of the property we do not move the corresponding comments, which can result in weird code

## Minimal PHP Code Causing Issue

https://getrector.com/demo/42b75150-e5b9-40b4-9b12-6f215cbaf569

## Expected Behaviour

The comment should we moved with the default value, for the example I would expect an output of:

```diff
 final class MyClass
 {
-    private int $type;
+    private int $type = 0; //default type for this class
     
     private Collection $myCollection;
 
     public function __construct()
     {
-        $this->myCollection = new ArrayCollection();
-        $this->type = 0; //default type for this class
+        $this->myCollection = new ArrayCollection();
     }
 }
```

**Comment by samsonasik** [comment]
That's expected, we use nikic/php-parser, which current behaviour is comment is belong to next node. Last comment doesn't have node to hold, that's why it removed.
