### ISSUE TITLE
Incorrect removal of a used import when using casts

### ISSUE THREAD

**Issue by flatcapco** [rectorphp/rector#8832]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2         |

When using removeUnusedImports: true, I've noticed that casts in my model (laravel project) are being removed, even though they are indeed used. I'm not sure how I can show a demo to replicate this online since its using imports.

## Minimal PHP Code Causing Issue

```php

namespace App\Models;

use App\Casts\EuropeParisDateTimeCast;


class User extends Authenticatable implements MustVerifyEmail
{

    #[\Override]
    protected function casts(): array
    {
        return [
...
            'created_at'        => EuropeParisDatetimeCast::class,
            'updated_at'        => EuropeParisDatetimeCast::class,
        ];
    }
}

```

**Comment by samsonasik** [comment]
That seems due to case sensitive usage, on import vs usage:

```diff
+EuropeParisDateTimeCast
-EuropeParisDatetimeCast
```

see https://getrector.com/demo/8ba74aef-3069-4976-9396-8d9cda8dd30c

Fix the case, for whatever which one is correct, and it will not be removed, see https://getrector.com/demo/c7147007-23ac-4a5c-ad39-db4f86e2449c

**Comment by flatcapco** [comment]
@samsonasik very well spotted! sorry for not spotting that myself
