### ISSUE TITLE
Incorrect behavior of PreparedValueToEarlyReturnRector

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#8837]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/c2b3b979-445a-4fe4-93fc-5b75d731f741

```php
<?php

final class DemoFile
{
    public function run(string $param)
    {        
        $r = preg_replace( '#^/(foo|bar)/(\w+)/.+$#', '$2', $param, 1, $count );
        if ( $count !== 1 ) {
            $r = preg_replace( '#^/hello/(\w+)/.+$#', '$1', $param, 1 );
        }

        return $r;
    }
}
```

### Responsible rules

* `PreparedValueToEarlyReturnRector`

## Expected Behavior

https://github.com/rectorphp/rector-src/pull/6325

```
final class DemoFile
{
    public function run(string $param)
    {        
        $r = preg_replace( '#^/(foo|bar)/(\w+)/.+$#', '$2', $param, 1, $count );
        if ( $count === 1 ) {
            return $r;
        }

        return preg_replace( '#^/hello/(\w+)/.+$#', '$1', $param, 1 );
    }
}
```

**Comment by samsonasik** [comment]
this is expected, the rule usage is not change if condition, but remove unnecessary prepared value.
