### ISSUE TITLE
EncapsedStringsToSprintfRector does not respect gettext method _()

### ISSUE THREAD

**Issue by SantosSi** [rectorphp/rector#8838]
It transforms:
`echo _("My translatable text with '{$pattern}'.");`
to (regard also the unnecessary replacement of ' with "):
`echo _(sprintf('My translatable text with \'%s\'.', $pattern));`
It should do optimally:
`echo sprintf(_("My translatable text with '%s'."), $pattern);`
or at least:
`echo sprintf(_('My translatable text with \'%s\'.'), $pattern);`

Currently, instead of passing only text to the translator, it passes code to the translator.
Funnily, in a second run SymplifyQuoteEscapeRector corrects the " to ' issue, that EncapsedStringsToSprintfRector unnecessarily introduced.

**Comment by SantosSi** [comment]
The single and double quote topic is a secondary issue.
I am not sure the core of this issue was resolved, and I find no indication of a resolution in the committed code: 
`_(sprintf('This parameter was left empty: %s', $variable'))`
is not what you want, instead it should be 
`sprintf(_('This parameter was left empty: %s'), $variable)`
The earlier is wrong, as it requires a translation per content of $variable, which is not foreseeable at all!
The latter is correct, as it allows the text to be translated including the placeholder %s, which can be filled on runtime by whatever $variable is set to, in one translation.

**Comment by TomasVotruba** [comment]
I see. Could you send failing test fixture to https://github.com/rectorphp/rector-src/tree/main/rules-tests/CodingStyle/Rector/Encapsed/EncapsedStringsToSprintfRector/Fixture ?

Code snippet is worth thousand words :)
