### ISSUE TITLE
Wrong parenthesis in union types (Docblocks)

### ISSUE THREAD

**Issue by Sergiobop** [rectorphp/rector#8839]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.5             |

Using importNames is bugged when parameters in docblock are union types

## Minimal PHP Code Causing Issue
https://getrector.com/demo/cf0e000e-4926-4427-9bad-6193e6ff4a58

## Expected Behaviour
Original phpdoc:
 * @method static orderByDistance(\Illuminate\Database\Query\Expression|string $column, \Illuminate\Database\Query\Expression|string $geometryOrColumn)

The resulting phpdoc after executing rector is:
+ * @method static orderByDistance((Expression | string) $column, (Expression | string) $geometryOrColumn)

This is wrong (the parenthesis is wrong), the code should be:
+ * @method static orderByDistance(Expression | string $column, Expression | string $geometryOrColumn)

**Comment by samsonasik** [comment]
Reprinting doc is by phpstan's phpdoc-parser, so add the parentheses on union under `@method` param definition on print seems expected there, probably related with issue https://github.com/phpstan/phpdoc-parser/issues/74.

Not really an issue when read by phpstan afaik. Not sure if it worth tweak on rector side.
