### ISSUE TITLE
Call to a member function end() on null in symplify

### ISSUE THREAD

**Issue by sakarikl** [rectorphp/rector#8845]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 1.2.5             |

PHP Fatal error:  Uncaught Error: Call to a member function end() on null in rector/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php:120

I'm not sure if this problem is with rector or with symplify/easy-parallel

## Minimal PHP Code Causing Issue

I do not have minimal set to reproduce it. I have a large symfony 1.4 application which I am running to date with step by step guide. 
Some runs produce that bug but not repeatably.

**Comment by sakarikl** [comment]
it seems that it was caused by tecnickcom/tcpdf library. While trying to run rector on it caused those errors.

**Comment by samsonasik** [comment]
It seems you're trying to upgrade third party code, which should live in `vendor`. Usually, we don't upgrade `vendor/` code, instead, use latest version of `vendor/` component that support latest php version that used.

For third party that not live in `vendor/`, ensure it autoloadable, ensure that you setup autoload correctly https://getrector.com/documentation/static-reflection-and-autoload , or better, upgrade to use composer autoload instead :)
