### ISSUE TITLE
JsonThrowCaseSensitiveConstFetchTest fails

### ISSUE THREAD

**Issue by jorgsowa** [rectorphp/rector#8849]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | master             |

One of rector tests fail when I execute following command:
> vendor/bin/phpunit -d --enable-pretty-print 

```

Time: 00:49.969, Memory: 525.00 MB

There was 1 failure:

1) Rector\Tests\Issues\ScopeNotAvailable\JsonThrowCaseSensitiveConstFetchTest::test with data set #0 ('/Users/...hp.inc')
Failed on fixture file "fixture.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     {
         $user = $_REQUEST['param'];
 
-        $user = json_decode($user, null, 512, JSON_THROW_ON_ERROR);
+        $user = json_decode($user);
 
         $condition = true;
         if ($condition) {
@@ @@
         }
 
         $output = [];
-        echo(json_encode($output, JSON_THROW_ON_ERROR));
+        echo(json_encode($output));
     }
 }
```

PHP: PHP 8.3.8 (cli) (built: Jun  4 2024 14:53:17) (NTS)

Platform requirements:

> Checking platform requirements for packages in the vendor dir
> composer-plugin-api  2.6.0      success                                       
> composer-runtime-api 2.2.2      success                                       
> ext-ctype            8.3.8      success                                       
> ext-curl             8.3.8      success                                       
> ext-dom              20031129   success                                       
> ext-json             8.3.8      success                                       
> ext-libxml           8.3.8      success                                       
> ext-mbstring         *          success provided by symfony/polyfill-mbstring 
> ext-phar             8.3.8      success                                       
> ext-session          8.3.8      success                                       
> ext-tokenizer        8.3.8      success                                       
> ext-xml              8.3.8      success                                       
> ext-xmlwriter        8.3.8      success                                       
> php                  8.3.8      success

## Expected Behaviour

0 failed tests

Please let me know what can I check to fix this issue. I cloned Rector repo for the first time and I expected all tests to pass on clean instance.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by samsonasik** [comment]
I can't reproduce on rector-src, we have linux and window in CI, and locally, I tested in macOS, it works fine.

When on yours, it probably related with output buffering somewhere.

I am not using docker, but that's probably the way you can test if needed https://github.com/rectorphp/rector-src/blob/main/CONTRIBUTING.md#using-docker

otherwise, just ignore it :), it just one failure glitch :)
