### ISSUE TITLE
[Feature] Convert non-property @var to assert()

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#8857]
# Feature Request

It would be great if there was a rule that would convert non-property @var annotations to asserts().
This would make lots of code bases more robust, since any invalid or outdated @var annotations would throw exceptions

A very simplistic example:

```
/**
 * @var string
 */
$foo = strtok($foo, '/');
```

to

```
$foo = strtok($foo, '/');
assert(is_string($foo));
```

As a start, I'd suggest to only do it for the main types (int, string,...), for their array counter parts (e.g. string[]) and objects (e.g. @var Bar which is checked with instanceof)
And that continously add more cases like non-empty/falsy-string, non-empty-array/list and array{...} shapes

**Comment by TomasVotruba** [comment]
Thanks for proposal. 
This could make lot of code to crash, depending on php.ini server setup for asserts.

Yet, I can imagine this could be part some custom strict set with focus on these types of changes, like https://github.com/phpstan/phpstan-strict-rules

Make such a set and let's see if it useful in the wild :+1:

**Comment by samsonasik** [comment]
There is `InlineVarDocTagToAssertRector` rule for that, you can manually enable it 

https://getrector.com/rule-detail/inline-var-doc-tag-to-assert-rector

**Comment by TomasVotruba** [comment]
@samsonasik Event better :) :+1:
