### ISSUE TITLE
Undefined constant PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode::KIND_NON_EMPTY_LIST

### ISSUE THREAD

**Issue by brendt** [rectorphp/rector#8864]
# Bug Report

Rector 1.2.7

Running rector on https://github.com/tempestphp/tempest-framework results in the above error. I've attached the debug log

[rector.log](https://github.com/user-attachments/files/17434397/rector.log)

**Comment by samsonasik** [comment]
The constant seems exists on latest prefixed vendor

https://github.com/rectorphp/rector/blob/ca3b59bfae8f033aa1a6b1b8964b8bc21bd344a7/vendor/phpstan/phpdoc-parser/src/Ast/Type/ArrayShapeNode.php#L13

on commit https://github.com/rectorphp/rector/commit/adf15bb534fb2d71dafe047e112dcf89bb7e6d55#diff-d2a87d36be22b25ebf2febece038b966c651cc98bea7d731c967cb531ce6426b

You can use latest `"rector/rector": "dev-main"` while wait for new release :)

**Comment by brendt** [comment]
Ok, thank you. It's not the first time our Rector build breaks with minor or patch updates though, does Rector follow semver or should I better lock it to a fixed version?

**Comment by samsonasik** [comment]
You can use composer.lock and fixed version of dependencies, use dependabot or renovate to regerate composer.json and composer.lock

**Comment by brendt** [comment]
Ok, not sure if that answers my question, but all fine :) 

I'll close this issue and wait for the next version/dev-main to fix it.

**Comment by samsonasik** [comment]
You can use `"rector/rector": "dev-main"` version for now, and verify if it fixed already in dev-main, if not, then something is wrong in the middle :)

**Comment by samsonasik** [comment]
this kind of issue is usually happen when "new file" introduced in phpstan/phpdoc-parser, not new constant, as it pointed to same file, so should be no issue, but if the issue exists, it can possibly due to you have other dependency that require phpstan/phpdoc-parser as well, so it cross dependency, while autoload match

**Comment by samsonasik** [comment]
Rector 1.2.8 just released :) https://github.com/rectorphp/rector/releases/tag/1.2.8
