### ISSUE TITLE
AddOverrideAttributeToOverriddenMethodsRector does not work with anonymous classes

### ISSUE THREAD

**Issue by pilif** [rectorphp/rector#8869]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a32f1069-7a9b-428b-afaf-2089a1e0f5eb

```php
<?php

class A {
    function foo(){}
}

class B extends A {
    function foo(){}
}

$c = new class() extends A {
    function foo(){}
};
```

### Responsible rules

* `AddOverrideAttributeToOverriddenMethodsRector`

## Expected Behavior

I expect the `AddOverrideAttributeToOverriddenMethodsRector` to work with anonymous classes.

```php
<?php
$c = new class() extends A {
    #[\Override]
    function foo(){}
};
```

**Comment by samsonasik** [comment]
This is on purpose, as override attribute is not mandatory, and usage on anonymous class is mostly on stubs, which can be on purpose to not have the feature :)
