### ISSUE TITLE
False positive of RemoveUselessVarTagRector

### ISSUE THREAD

**Issue by dragosprotung** [rectorphp/rector#8870]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/c779dd90-39ba-4cf1-8222-984a30d19816

```php
<?php

interface Properties{}

/**
 * @template TProperties of Properties|null
 */
final class DemoFile
{
    /** @var TProperties */
    private Properties|null $properties;
}
```

### Responsible rules

* `RemoveUselessVarTagRector`

## Expected Behavior

Tag should not be removed

**Comment by samsonasik** [comment]
That's expected `TProperties` is defined as `Properties|null`, while native property tyep is `Properties|null` itself, so they are equal, so dead code is expected :)

even child implementor, using `@template` tag will mark as 

```
Property DemoFile<TPropertyImpl of PropertiesImpl|null>::$properties (TPropertyImpl of PropertiesImpl|null) does not accept PropertiesImpl.
```

see:

https://phpstan.org/r/abf330cf-4372-49ac-ba92-51ffa77d0c3a

so possibly a phpstan bug on invalid detecting it :)

I suggest to change to just direct property definition, if child is used, see 

https://phpstan.org/r/9414d887-ce5c-45c2-9985-b930517127cc

**Comment by dragosprotung** [comment]
@samsonasik `null` must be part of the template. This is because some implementations might always return `null` (they do not have properties).

Here is another example https://getrector.com/demo/f83b300c-0b97-4536-b793-00e88cd836ab

**Comment by samsonasik** [comment]
You can use direct child implementor of native type as docblock if you don't want it to be removed, see https://getrector.com/demo/59fb3ce1-5118-44e2-a52f-2b3bdcaf66e1

**Comment by dragosprotung** [comment]
I need to keep the property in the base abstract class.

I've made the 2 versions for PHPStan:
https://phpstan.org/r/1ab4f06b-5184-46c3-bbd8-c30c6f418027 (with the `@var` tag)
https://phpstan.org/r/fff02c41-586a-42c6-84f1-66a5696953cf (without the `@var` tag)

I do not consider this a PHPStan bug.

I also made it in Psalm:
https://psalm.dev/r/00ee6fbeb9 (with the `@var` tag)
https://psalm.dev/r/447851edd4 (without the `@var` tag)

**Comment by samsonasik** [comment]
Ok, reopen then.

**Comment by dragosprotung** [comment]
Great work @samsonasik, thank you! 
Unfortunatly I still can not use it in some of my cases because I have more than 1 template defined. I created PR #6402 to address this.
