### ISSUE TITLE
Execution on Windows

### ISSUE THREAD

**Issue by abrahamsaanchez** [rectorphp/rector#8871]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.8            |

I follow the installation guide on https://getrector.com/documentation but I cant execute rector.

```bash
$ composer require rector/rector --dev
./composer.json has been updated
Running composer update rector/rector
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking phpstan/phpstan (1.12.7)
  - Locking rector/rector (1.2.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
INFORMACIÓN: no se pudo encontrar ningún archivo para los patrones dados.
  - Installing phpstan/phpstan (1.12.7): Extracting archive
  - Installing rector/rector (1.2.8): Extracting archive
Generating autoload files
68 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
Using version ^1.2 for rector/rector

$ vendor/bin/rector
El sistema no puede encontrar la ruta especificada.
```

Don't know if it's a Windows issue, but the error is saying "The system cannot find the path specified." (my OS is in Spanish).

**Comment by samsonasik** [comment]
define paths, read the documentation https://getrector.com/documentation/define-paths

**Comment by abrahamsaanchez** [comment]
> define paths, read the documentation https://getrector.com/documentation/define-paths

Rector is not even configured (the rector.php file is not created and it should be created by rector automatically).

Even if I create the rector.php configuration file, doesn't work:

```php
<?php

use Rector\Config\RectorConfig;

// Also tried with ->withPaths([ __DIR__ . '/src'])
return RectorConfig::configure()
    ->withRootFiles();
```

```bash
$ vendor/bin/rector
El sistema no puede encontrar la ruta especificada.
```

**Comment by samsonasik** [comment]
I can't reproduce, ensure you're using prompt or bash, per documentation known drawback https://github.com/rectorphp/rector?tab=readme-ov-file#known-drawbacks

**Comment by abrahamsaanchez** [comment]
I tried with Bash, prompt and PowerShell and the error is the same.

The process die with the error message on the `Application` class, when the `doRun` method is called.

Don't know if this can help, but I made changes to the `Application`  file to see when the process dies:

## `run` method
```php
print_r('before doRun');
exit;
$exitCode = $this->doRun($input, $output);
```
```bash
$ vendor/bin/rector
before doRun
```

```php
$exitCode = $this->doRun($input, $output);
print_r('after doRun');
exit;
```
```bash
$ vendor/bin/rector
El sistema no puede encontrar la ruta especificada.
```

## `doRun` method
```php
public function doRun(InputInterface $input, OutputInterface $output)
{
    print_r('inside doRun');
    exit;
```
```bash
$ vendor/bin/rector
El sistema no puede encontrar la ruta especificada.
```

**Comment by samsonasik** [comment]
we may need github repo with reproducible example, eg: via github action :)

**Comment by nschilling** [comment]
I had a similar problem on Windows 11. I disabled xdebug in the php.ini to make rector work.

When xdebug is enabled the handler `\RectorPrefix202409\Composer\XdebugHandler\XdebugHandler` tries to restart rector without xdebug.
Unfortunately it produces an invalid command on windows. It is similar to this:
~~~
"C:\path with spaces\php.exe" "-n" "-c" "C:\Users\path with spaces\AppData\Local\Temp\1234.tmp" ".\bin\rector"
~~~

But it should be more like this in PowerShell, I think;
~~~
& 'C:\path with spaces\php.exe' "-n" "-c" "C:\Users\path with spaces\AppData\Local\Temp\1234.tmp" ".\bin\rector"
~~~

**Comment by samsonasik** [comment]
The effort to cover windows with spaced path and enable parallel was on PR:

- https://github.com/rectorphp/rector-src/pull/4813

on `WorkerCommandLineFactory` which works on bash and prompt,  feel free to provide better patch that support powershell as well.

**Comment by staabm** [comment]
> When xdebug is enabled the handler \RectorPrefix202409\Composer\XdebugHandler\XdebugHandler tries to restart rector without xdebug.
Unfortunately it produces an invalid command on windows.

If reproducible in isolation this should be reported to the xdebug-handler repo
