### ISSUE TITLE
Please make BetterStandardPrinter not final, extending it can allow for some custom reformatting of code

### ISSUE THREAD

**Issue by nlighteneddesign** [rectorphp/rector#8873]
# Feature Request
https://github.com/rectorphp/rector/blob/main/src/PhpParser/Printer/BetterStandardPrinter.php

We are using it here: https://github.com/palantirnet/drupal-rector/pull/308/commits/18a242e63c6663e448e9b06848ce7dc049104efa#diff-c73155380cb9a638f8a420029b397b4295cd599bedd57a4cf688f06921098ee9R53

To allow us to convert single line arrays to multiline arrays.

**Comment by nlighteneddesign** [comment]
https://github.com/rectorphp/rector-src/pull/6397/files

**Comment by samsonasik** [comment]
Don't extends, create your own printer for your specific usecase :)

**Comment by chx** [comment]
You can't create your own printer because

```
final readonly class FileProcessor
{
    public function __construct(
        private BetterStandardPrinter $betterStandardPrinter,
```

**Comment by bbrala** [comment]
If it can be injected into the container with an interface that would help. Not sure if the one in rector has some extra methods compared to the standard. If so that probably needs consodering

**Comment by samsonasik** [comment]
You can create your own class, then make alias into `Rector\PhpParser\Printer\BetterStandardPrinter`, the `RectorConfig` is extends the `Illuminate\Container\Container`
