### ISSUE TITLE
BetterStandardPrinter's Nop hack removes whitespace from strings

### ISSUE THREAD

**Issue by schlndh** [rectorphp/rector#8876]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.7              |

Rector incorrectly removes whitespace from strings, heredocs, nowdocs and inline "HTML" when Nop node is present. This happens even if they are in a part of code where rector shouldn't do any changes. This is generally not safe, because these strings may be whitespace-sensitive. Though I'm mainly annoyed by the fact that it occasionally messes up formatting in some of my files with inline HTML.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/c1a78144-8b2b-4219-8f47-33c91f640843 (the empty line inside the strings contains whitespace that gets removed).

```php
<?php
use Rector\Tests\Transform\Rector\Assign\PropertyFetchToMethodCallRector\Source\Generator;

$fn = function (Generator $o) {echo $o->word; };

if (rand()) {
    $a = "
    
    ";
    $b = <<<TXT
    
TXT;
    $c = <<<'TXT'
    
TXT;
    //
}
?>
    <?php if (rand()):
        //
        ?>
    <?php endif; ?>
```

For some reason the demo only reports a change in the inline HTML and not in the other strings. When I run the same thing via phpunit it changes all of them.

The issue is caused by [this line](https://github.com/rectorphp/rector-src/blob/61ebcc53b5c50f244ce0f7dfb626ded8d371c0a5/src/PhpParser/Printer/BetterStandardPrinter.php#L256). PhpParser returns correctly formatted code in this case (though not in others, so the line has a purpose).

## Expected Behaviour

The whitespace should be preserved.

**Comment by samsonasik** [comment]
I am closing as answered https://github.com/rectorphp/rector-src/pull/6403#issuecomment-2445305134

**Comment by schlndh** [comment]
@samsonasik I'm not sure what's the harm in leaving it open. You provided an explanation and a possible workaround. But it's still clearly a bug.

I'm not asking anyone to fix it if they don't want to. But perhaps one day in a distant future someone will see the report and be inclined to fix it?

**Comment by samsonasik** [comment]
We are going to revisit printer and trimming handling on change once we upgraded to php-parser 5 and phpstan 2 :), so that probably will cover it.

We rely on ast technology, which doesn't know about spaces for user DX vs usability, so some edge case will always exists.

Thank you for understanding.
