### ISSUE TITLE
Incorrect behavior of RemoveUselessParamTagRector

### ISSUE THREAD

**Issue by sreichel** [rectorphp/rector#8877]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

Do not remove child-classes from phpDocs to avoid ...

> Potentially polymorphic call. Varien_Object does not have members in its hierarchy

## Suggestion

Only remove DOC when no parameters child class is set.

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/2cab2711-e61e-4e2a-9191-fc1404954add

```php
<?php

class AClass
{
    /**
     * ISSUE: would be removed
     * @param Varien_Object_Sub|Varien_Object $object
     */
    public function basic(Varien_Object $object)
    {
        # ISSUE: Varien_Object_Sub is required for show tooltips in phpstorm
        $test = $object->getTest();
    }
}

class MyClass extends AClass
{
    public function basic()
    {
        $object = new Varien_Object_Sub($object);
        $this->basic($object);
    }
}

class Varien_Object
{
}

class Varien_Object_Sub extends Varien_Object
{
    public function getTest()
    {
    }
}
```

### Responsible rules

* `RemoveUselessParamTagRector`

**Comment by samsonasik** [comment]
That's expected, use sub type in docblock instead if you want to keep docblock, see https://getrector.com/demo/88d35319-c383-4acc-a249-cf38163a785d

as once you define parent, child is not needed
