### ISSUE TITLE
False positive of RemoveUselessReturnTagRector

### ISSUE THREAD

**Issue by dragosprotung** [rectorphp/rector#8883]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d61ce159-b0cf-463d-b1d9-77ca9272e5c9

```php
<?php

interface Performance {}

/**
 * @template TPerformance of Performance
 */
interface Task {
    /** @return TPerformance|null */
    public function performance(): Performance|null;
}
```

This is somehow related to https://github.com/rectorphp/rector/issues/8870

I have created 2 example for PHPStan output:
https://phpstan.org/r/afa02580-d14c-4e4c-bb06-c89f6f0a2566 (with the `@return` tag)
https://phpstan.org/r/ac59fd57-083b-4d14-a140-b03ec7eada3e (without the `@return` tag)

### Responsible rules

* `RemoveUselessReturnTagRector`

## Expected Behavior

Tag should not be removed

**Comment by mvhirsch** [comment]
Thank you! :clap:
