### ISSUE TITLE
Error with phpstan/phpstan 1.12.7

### ISSUE THREAD

**Issue by sss-CRS-sss** [rectorphp/rector#8884]
Update package phpstan/phpstan for 1.12.7 and get error 
```
 Could not process "/app/src/...php" file, due to:
"System error: "Undefined constant PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode::KIND_NON_EMPTY_LIST" 
```

Downgrade for 1.12.6 -> ok

**Comment by samsonasik** [comment]
what rector version you're using? 1.2.9 was released 18 hours ago, which should include latest preload

**Comment by sss-CRS-sss** [comment]
Hi! I use last version - 1.2.9

**Comment by samsonasik** [comment]
The constant is exists at rector prefixed vendor https://github.com/rectorphp/rector/blob/7923bd5e48f8c26a922df91f7174f5bca2b3671d/vendor/phpstan/phpdoc-parser/src/Ast/Type/ArrayShapeNode.php#L13

so probably you conflict with your own requirement of phpstan-phpdoc-parser, Try upgrade to latest phpstan/phpdoc-parser

https://github.com/phpstan/phpdoc-parser/releases/tag/1.33.0

**Comment by samsonasik** [comment]
I am closing it as it mostly interdependency issue, ensure you have latest phpstan/phpdoc-parser requirement in your composer.json.

Feel free to provide reproducible repository if you still have issue after updating your own requirement of `phpstan/phpdoc-parser` to latest version so we can check.

Thank you for understanding.
