### ISSUE TITLE
Error when processing nullable operator on function return

### ISSUE THREAD

**Issue by cmonard** [rectorphp/rector#8889]
Rector fail when processing this kind of code : 

`
    protected static function sL(string $key, array $arguments = null, string $default = ''): string
    {
        return LocalizationUtility::translate(
            'projectsolr.backend.solr_administration.' . $key,
            'ProjectSolr',
            $arguments
        ) ?? $default;
    }
`
it work if i split the code
`
    protected static function sL(string $key, array $arguments = null, string $default = ''): string
    {
        $localised = LocalizationUtility::translate(
            'projectsolr.backend.solr_administration.' . $key,
            'ProjectSolr',
            $arguments
        );
        return $localised ?? $default;
    }
`

Error log : 
`
[ERROR] Could not process
         "/var/www/html/packages/project_solr/Classes/Controller/Backend/SolrAdministrationModuleController.php" file,
         due to:
         "System error: "PHPStan\Analyser\TypeSpecifier::create(): Argument #1 ($expr) must be of type
         PhpParser\Node\Expr, null given, called in
         phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/TypeSpecifier.php549"

         Stack trace:
         #0 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/TypeSpecifier.php(549):
         PHPStan\Analyser\TypeSpecifier->create()
         #1 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3041):
         PHPStan\Analyser\TypeSpecifier->specifyTypesInCondition()
         #2 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1528):
         PHPStan\Analyser\MutatingScope->filterByTruthyValue()
         #3 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(622):
         PHPStan\Analyser\MutatingScope->resolveType()
         #4 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1798):
         PHPStan\Analyser\MutatingScope->getType()
         #5 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(724):
         PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr()
         #6 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(429):
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()
         #7 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(296):
         PHPStan\Analyser\NodeScopeResolver->processNodes()
         #8 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(268):
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->nodeScopeResolverProcessNodes()
         #9 vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(58):
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes()
         #10 vendor/rector/rector/src/Rector/AbstractRector.php(309):
         Rector\Application\ChangedNodeScopeRefresher->refresh()
         #11 vendor/rector/rector/src/Rector/AbstractRector.php(299): Rector\Rector\AbstractRector->refreshScopeNodes()
         #12 vendor/rector/rector/src/Rector/AbstractRector.php(168):
         Rector\Rector\AbstractRector->postRefactorProcess()
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114):
         Rector\Rector\AbstractRector->enterNode()
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):
         PhpParser\NodeTraverser->traverseNode()
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):
         PhpParser\NodeTraverser->traverseNode()
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):
         PhpParser\NodeTraverser->traverseNode()
         #19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):
         PhpParser\NodeTraverser->traverseNode()
         #21 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray()
         #22 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(47):
         PhpParser\NodeTraverser->traverse()
         #23 vendor/rector/rector/src/Application/FileProcessor.php(113):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #24 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):
         Rector\Application\FileProcessor->processFile()
         #25 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):
         Rector\Application\ApplicationFileProcessor->processFile()
         #26 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(138):
         Rector\Application\ApplicationFileProcessor->processFiles()
         #27 vendor/rector/rector/src/Console/Command/ProcessCommand.php(156):
         Rector\Application\ApplicationFileProcessor->run()
         #28 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):
         Rector\Console\Command\ProcessCommand->execute()
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(960):
         RectorPrefix202411\Symfony\Component\Console\Command\Command->run()
         #30 vendor/rector/rector/vendor/symfony/console/Application.php(333):
         RectorPrefix202411\Symfony\Component\Console\Application->doRunCommand()
         #31 vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202411\Symfony\Component\Console\Application->doRun()
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(216):
         Rector\Console\ConsoleApplication->doRun()
         #33 vendor/rector/rector/bin/rector.php(130): RectorPrefix202411\Symfony\Component\Console\Application->run()
         #34 vendor/rector/rector/bin/rector(5): require_once('...')
         #35 vendor/bin/rector(119): include('...')
         #36 {main}". On line: 1055
`

**Comment by samsonasik** [comment]
Please provide reproducible code and config at https://getrector.com/demo , thank you.

**Comment by samsonasik** [comment]
Closing as no reproducible code and config provided.
