### ISSUE TITLE
Config withPhpSets does not work with composer require php-64bit

### ISSUE THREAD

**Issue by Tetragramat** [rectorphp/rector#8890]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.2             |

If I use `withPhpSets` without arguments on project that has in `composer.json` php defined only as require.php-64bit then I'll get error.
```
 [ERROR] We could not find local "composer.json" to determine your PHP version.                                       
         Please, fill the PHP version set in withPhpSets() manually. 
```

## Minimal PHP Code Causing Issue

rector.php
```php
return RectorConfig::configure()
    ->withPhpSets();
```
composer.json
```json
{
    "require": {
        "php-64bit": "8.1.*",
    }
}
```

## Expected Behaviour

In `\Rector\Php\PhpVersionResolver\ProjectComposerJsonPhpVersionResolver::resolve` should be added read for php-64bit instead of just php.

That means this line should be changed for example like this
```diff
-$requirePhpVersion = $projectComposerJson['require']['php'] ?? null;
+$requirePhpVersion = $projectComposerJson['require']['php'] ?? $projectComposerJson['require']['php-64bit'] ?? null;
```

**Comment by TomasVotruba** [comment]
Thanks for reporting 💪

Could you send proposed fix?
