### ISSUE TITLE
New rule: typed property from initial assignment

### ISSUE THREAD

**Issue by hildebro** [rectorphp/rector#8892]
# Feature Request

There's already `TypedPropertyFromStrictConstructorRector` for this refactoring:

```diff
 class SomeObject
 {
-    private $name;
+    private string $name;

     public function __construct(string $name)
     {
         $this->name = $name;
     }
 }
```

I would like to see a similar rule that takes initial assignments like these into account (including values from enums or constants), instead of constructor parameters: 

```diff
 class SomeObject
 {
-    private $name;
+    private string $name;

     public function __construct()
     {
         $this->name = 'default';
     }
 }
```

```diff
 class SomeObject
 {
-    private $name = 'default';
+    private string $name = 'default';

     public function __construct()
     {
     }
 }
```

**Comment by TomasVotruba** [comment]
Try this one: https://getrector.com/rule-detail/typed-property-from-assigns-rector

<b>

Use the full set to get the best out of all type rules:

```php
return RectorConfig::configure()
    ->withPreparedSets(typeDeclarations: true)
```

**Comment by TomasVotruba** [comment]
I see. The Doctrine properties are skipped, as they are often access magically via Symfony forms or property accessor. Even non-nullable properties are actually nullable. 

The rule caused crashing very easily, so we skip it by default and let users decide about Doctrine properties.

**Comment by hildebro** [comment]
Ah I see. Would be cool, if it was possible to configure these rules so they either do or don't ignore doctrine properties, defaulting to ignore. But I'd understand if that's not a huge prio for you guys.

**Comment by TomasVotruba** [comment]
This is rather magic of Doctrine. Because of Doctrine properties uses reflection under the hood, we know the property type is alwasy nullable. We approach other magic in similar way, e.g. do not fill types in classes with `__get()` and `__call()`.

**Comment by samsonasik** [comment]
@hildebro you may looking for rector-doctrine rule : `Rector\Doctrine\CodeQuality\Rector\Property\TypedPropertyFromColumnTypeRector`

https://getrector.com/rule-detail/typed-property-from-column-type-rector

**Comment by hildebro** [comment]
@samsonasik  
> @hildebro you may looking for rector-doctrine rule : `\Rector\Doctrine\CodeQuality\Rector\Property\TypedPropertyFromColumnTypeRector`
> 
> https://getrector.com/rule-detail/typed-property-from-column-type-rector

This doesn't add any typing to my array example above. In another case I have:
```
    /**
     * @var string
     */
    #[ORM\Column(type: 'string')]
    protected $state = State::STATE_RAW;
```
It adds `?string` typing even though three different indicators (`@var`, Column defining `nullalble=false` by default and the assignment of `STATE_RAW`) imply that the type should be `string` instead. 

Does that rule you suggested have any configurations?

**Comment by samsonasik** [comment]
You're typo: `nullalble=false` should be `nullable=false`

define `nullable=false` should apply type non-nullable, see fixture 

https://github.com/rectorphp/rector-doctrine/blob/e75008c293679e0bb0637bf09cf6dd43ff34526a/rules-tests/CodeQuality/Rector/Property/TypedPropertyFromColumnTypeRector/Fixture/column_not_nullable.php.inc#L7-L29

**Comment by hildebro** [comment]
Adding nullable=false does help in that example. Is there another rule that adds `nullable=false` to all `Column` attributes that haven't defined anything yet?

Also the json array example from [above](https://github.com/rectorphp/rector/issues/8892#issuecomment-2468298883) is still not getting typed with `array` by that rule
