### ISSUE TITLE
Incorrect behavior of ReturnTypeFromStrictFluentReturnRector, ReturnUnionTypeRector must return self

### ISSUE THREAD

**Issue by kzscorpion** [rectorphp/rector#8893]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/60808a6d-fef6-43cd-a3fe-c18a65b50ce4

```php
<?php

class DemoFile
{
    private $name;
    public function run(bool $param)
    {
        if ($this->isTrue($param)) {
            return 5;
        }

        return '10';
    }

    public function setName($name)
    {
         $this->name = $name;
        
        return $this;
    }
}
```

### Responsible rules

* `ReturnTypeFromStrictFluentReturnRector`

* `ReturnUnionTypeRector`

**Comment by samsonasik** [comment]
That's expected.
