### ISSUE TITLE
Rectorphp silently exits before completing the run

### ISSUE THREAD

**Issue by christopherowen** [rectorphp/rector#8894]
Rector 1.2.10, php 8.3.13, MacOS Sequoia (latest)

When running rectorphp on a reasonably-sized code base, it will reach a percentage less than 100% and exit.  The exit code is successful.  This is problematic for because:

- I am expecting the code to be well-formatted during a php version update and am depending on rectorphp, and the exit code suggests the code is well-formatted (it is not)
- I am wiring this to a CI/CD, and the successful exit code suggests deployments should continue (it should not)
- I suspect there may be some bad code which could lead to this, and I would like to identify it in order to improve it

```
% vendor/bin/rector process --clear-cache --memory-limit=512M
 144/160 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  90%

                                                                                                                        
 [OK] Rector is done! 
 
% echo $?                                            
 0
```

How can I debug this or otherwise make rectorphp return the error that it is experiencing?

This could be a display bug, but running the files individually discovered extra edits recommended by rectorphp:

```
find . -name "*php" | while read line; do vendor/bin/rector process --clear-cache $line; done
```

**Comment by christopherowen** [comment]
I disabled parallelism in my rector.php with 

```
    ->withParallel(240, 1, 16) // seconds, maxNumberOfProcess, jobSize
```

if I remove this configuration it works as intended.
if I changed the jobSize to 64 it works as intended.

I had wanted to run rectorphp with one process for use in the CI/CD pipeline.  With multiple concurrent projects running rectorphp simultaneously it could crash the server.

My questions now become:

- Can we have rectorphp return an error for problems related to jobSize?
- How does one choose the correct jobSize setting?
- Is there a better way to disable parallelism?

**Comment by samsonasik** [comment]
jobSize is how many files in hold per process, you may can increase timeout, but reduce jobSize:

```php
return RectorConfig::configure()
    ->withParallel(240, 16, 8);
```

also, you may can start per directory basis to lookup what code that cause it, eg:

```
vendor/bin/rector process app/Model
vendor/bin/rector process app/Entity
```

also do half by half rule by rule, so you can help us found a bottleneck :)

**Comment by christopherowen** [comment]
I changed jobSize to 50 and it would complete.

It is very easy to reproduce the early exit by setting jobSize to 1 on a project with a few 100 files.

**Comment by samsonasik** [comment]
It will very hard to patch without reproducible repo :), feel free to provide reproducible repo so it can be fixed, otherwise, it just shooting in the dark, nothing we can do.
