### ISSUE TITLE
Incorrect behavior of Php4ConstructorRector

### ISSUE THREAD

**Issue by afilina** [rectorphp/rector#8895]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/77e1ebc3-b1f9-49b4-ae84-8e1c4eb47e41

```php
<?php

class B
{
	public function B() {}
}

class A extends B {
    public function A() { 
        $this->B(); 
    }
}
```

### Responsible rules

* `Php4ConstructorRector`

## Expected Behavior

Should have changed `$this->B();` to `B::__construct()`. See reference here: https://www.zend.com/php-migration/function-name-restrictions/removed-php4-style-constructor

Edit:

## Current Behavior

Runtime fatal error because the expression `$this->B()` remains unchanged.

**Comment by samsonasik** [comment]
I think this only make sense when B has another extends, eg: `class B extends ParentB`
