### ISSUE TITLE
withRootFiles() ignores ".php-cs-fixer.dist.php"

### ISSUE THREAD

**Issue by andrew-demb** [rectorphp/rector#8896]
# Feature Request

Documentation at [1] states, that using `withRootFiles` will make sure, that rector will apply rules to the root directory PHP files like a "rector.php", "ecs.php", etc.

But rector doesn't apply rules for ".php-cs-fixer.dist.php" at the root directory for now.

Feature request is: `withRootFiles` should include hidden PHP files from the root (or at least for well known files like a ".php-cs-fixer.dist.php")

[1] https://getrector.com/documentation/define-paths

## Diff 

N/A

**Comment by TomasVotruba** [comment]
Sounds reasonable. Could you send PR with the fix?

**Comment by andrew-demb** [comment]
@TomasVotruba what's the proper way to fix it?

1. Include any dot-prefixed PHP files
2. Include just ".php-cs-fixer.dist.php"

**Comment by TomasVotruba** [comment]
What would be behavior you'd expect?

**Comment by andrew-demb** [comment]
> What would be behavior you'd expect?

Include any dot-prefixed PHP files

Here's the PR https://github.com/rectorphp/rector-src/pull/6592
