### ISSUE TITLE
Incorrect behavior of NestedAnnotationToAttributeRector

### ISSUE THREAD

**Issue by caugner** [rectorphp/rector#8897]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/0badab97-fad4-45fb-b09b-c6794775b44f

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="changelog",
 *   indexes={
 *     @ORM\Index(name="entity", columns={"entity_class", "entity_id"}),
 *   }
 * ))
 * @ORM\Entity(repositoryClass="ChangeLogRepository")
 * @ORM\HasLifecycleCallbacks
 */
class ChangeLog
{
}
```

### Responsible rules

* `NestedAnnotationToAttributeRector`

## Expected Behavior

Despite the minor syntax error (extra closing parenthesis after `@ORM\Table` annotation), the `Entity` and `HasLifecycleCallbacks` annotations should have been either kept as is, or converted to attributes anyhow (because Doctrine properly parses those annotations, despite the syntax error).

**Comment by samsonasik** [comment]
Closing per https://github.com/rectorphp/rector-src/pull/6437#issuecomment-2495500512
