### ISSUE TITLE
Re-enable archived rector-php-parser

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#8902]
# Feature Request

Repo: https://github.com/rectorphp/rector-php-parser

`rector-php-parser` was archived and readonly, it usefull for upgrade php-parser to php-parser 5 nodes, I tried to create PR to bump to PHPStan 2 and PHPParser 5 code there, but can't as it readonly, here my changes

but needs to pointed from my fork to the repo

https://github.com/samsonasik/rector-php-parser/compare/main...samsonasik:rector-php-parser:bump-to-phpstan-2-php-parser5?expand=1

**Comment by TomasVotruba** [comment]
Done https://github.com/rectorphp/rector-php-parser :+1:

**Comment by samsonasik** [comment]
Ok, here the PR:

 - https://github.com/rectorphp/rector-php-parser/pull/6

**Comment by samsonasik** [comment]
Thank you.
