### ISSUE TITLE
Private property gets removed despite being used by `get_object_vars`

### ISSUE THREAD

**Issue by uncaught** [rectorphp/rector#8904]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.10 |

Rector removes seemingly unused properties, but which are used by `get_object_vars`.

## Minimal PHP Code Causing Issue

```php
class Foo implements \JsonSerializable {
  public function __construct(private readonly string $foo) {
  }

  public function jsonSerialize(): array {
    return get_object_vars($this);
  }
}
```

## Expected Behaviour

Rector should not remove property `$foo` here.

-----

I would think that whenever there is a `get_object_vars($this)` in a class, rector should not remove any non-static properties or see them as used.

**Comment by samsonasik** [comment]
Reproduced at https://getrector.com/demo/65df94bf-d85e-4387-ae17-a70930158dc4

with proof different result https://3v4l.org/f1JNG vs https://3v4l.org/JolHc
