### ISSUE TITLE
Function is turned into non-static while being used statically

### ISSUE THREAD

**Issue by uncaught** [rectorphp/rector#8905]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.10 |

Rector removes the `static` from a method while being used in a static context.

## Minimal PHP Code Causing Issue

```php
class Foo {
  private static function bar(string $a, string $b): int {
    return $a <=> $b;
  }

  public static function foo(): void {
    $array = [];
    usort($array, [self::class, 'bar']);
  }
}
```

## Expected Behaviour

`bar` should remain `static`, but rector removes the `static` key word.

```diff
class Foo {
-  private function bar(string $a, string $b): int {
+  private static function bar(string $a, string $b): int {
    return $a <=> $b;
  }

  public static function foo(): void {
    $array = [];
    usort($array, self::bar(...));
  }
}

```

**Comment by samsonasik** [comment]
Reproduced at https://getrector.com/demo/d3fb8379-9b92-484a-882d-ddff3b6aba5a

with proof https://3v4l.org/7MUOm vs https://3v4l.org/t2Ijk
