### ISSUE TITLE
RemoveUnusedPrivateMethodRector removes PHPUnit data providers

### ISSUE THREAD

**Issue by umpirsky** [rectorphp/rector#8910]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.6             |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/327f47bc-8129-4400-a71d-859fe94918c9

```php
<?php

class PaymentMethodTest
{
    /**
     * @dataProvider fooDataProvider
     */
    public function testFoo(): void
    {
        
    }

    private function fooDataProvider(): array
    {
        return [
            [],
        ];
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior

Data provider should not be removed.

**Comment by samsonasik** [comment]
PHPUnit data provider should be public on the first place, If you're using phpunit 10, think you can register phpunit 10 set list first, then it will be resolved:

https://getrector.com/demo/3ff32c15-6572-4e06-8119-c9a70c76a594

**Comment by TomasVotruba** [comment]
@samsonasik That is true, but this code is valid in PHPUnit 9. Rector should keep the method.
