### ISSUE TITLE
Dies in a heap on encountering "new without parens"

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#8911]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.10             |

 "Syntax error, unexpected T_OBJECT_OPERATOR, expecting ')', Syntax error, unexpected ','"

## Minimal PHP Code Causing Issue

```php
class C {
  function F() {}
}

new C()->F();
```

## Expected Behaviour

Do not die in a heap.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by Bilge** [comment]
I don't think your tool emits error produced by Rector dying.

**Comment by Bilge** [comment]
>PHP 8.4.1 (cli) (built: Nov 20 2024 11:13:29) (ZTS Visual C++ 2022 x64)

**Comment by TomasVotruba** [comment]
This will be most likely fixed in https://github.com/rectorphp/rector/issues/8815

**Comment by samsonasik** [comment]
Resolved on latest dev-main with php-parser 5.

**Comment by Bilge** [comment]
@samsonasik Thanks. When will this be released?

**Comment by samsonasik** [comment]
see https://github.com/rectorphp/rector/issues/8815#issuecomment-2493467044
