### ISSUE TITLE
UnusedImport eating comment

### ISSUE THREAD

**Issue by jorgsowa** [rectorphp/rector#8913]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/17f0aab1-b99f-49db-bbcd-edb6a8dcee27

```php
<?php

// comment

use UnusedImport;
```

### Responsible rules

* `removeUnusedImports`

## Expected Behavior

The comment shouldn't be removed.

**Comment by samsonasik** [comment]
Oh, I see, you mean should'not be removed. Actualy, comment rely on its stmt, so when remove stmt, it always removed, so this is expected.

**Comment by samsonasik** [comment]
I think I found a solution for it, first Use statement can be replaced with Nop in case it has comment, as it may be important license docblock.

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-src/pull/6522

**Comment by jorgsowa** [comment]
Thank you!
