### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivateMethodRector

### ISSUE THREAD

**Issue by umpirsky** [rectorphp/rector#8914]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/4cb6f33d-c7bd-4624-be8a-3f612ed024fb

```php
<?php

class Sasa
{
    public static function createAfterResult($openRating, $rating)
    {
        $instance = new self();

        $instance
            ->setStatDate(new \DateTime())
            ->setDayOpenRating($openRating)
        ;

        return $instance;
    }

    private function setDayOpenRating($dayOpenRating)
    {
        $this->dayOpenRating = $dayOpenRating;

        return $this;
    }

    private function setStatDate(DateTime $statDate)
    {
        $this->statDate = new DoctrineIdDate($statDate);

        return $this;
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior

`setDayOpenRating()` should not be removed as it is in use.

**Comment by samsonasik** [comment]
The `setDayOpenRating()` and `setStatDate()` not return `self`, so it can't be validated as return self object from phpstan, if it has, it will be correctly skipped, see

https://getrector.com/demo/7e965f6d-21d4-4740-a48a-6bb26ef41bf5

**Comment by umpirsky** [comment]
OK, this is very risky, thanks.

I expected `RemoveUnusedPrivateMethodRector` skipping the removal when it can't reliably determine if the method is used or now.

**Comment by samsonasik** [comment]
Fluent call can't be validated, unless all methods native return typed :), we already did very complex logic for it :)
