### ISSUE TITLE
Incorrect behavior of ReduceAlwaysFalseIfOrRector

### ISSUE THREAD

**Issue by splitbrain** [rectorphp/rector#8916]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/6a8bfd9f-5ba0-48a8-af4c-d1702b2f6fbf

```php
<?php

/** @var AuthPlugin $auth */
global $auth;

$disabled=[];


if (!$auth instanceof AuthPlugin) {
    $disabled[] = 'login';
}

if (!$auth instanceof AuthPlugin || !$auth->canDo('logout')) {
    $disabled[] = 'logout';
}
```

### Responsible rules

* `ReduceAlwaysFalseIfOrRector`

## Expected Behavior

Rector should not remove the instanceof check in the second if clause. Just because the the check has been done in the previous if, doesn't mean it can be done in the second one, because the first one does not influence the second one. Removing the check will cause an error when $auth is null.

**Comment by samsonasik** [comment]
That's because you enforce it via:

```
/** @var AuthPlugin $auth */
```

You can make it nullable var, and it will be correctly skipped, see 

https://getrector.com/demo/c7a9836e-07ee-4ebe-9652-fdfc9c3b3532

**Comment by samsonasik** [comment]
Closing as answered above, even PHPStan `->getNativeType()` can't detect it correctly on boolean or in left because of the enforcing `@var` with multiple condition. It should be resolved there, or you can do `@var null|AuthPlugin $auth` to handle yourself.

**Comment by splitbrain** [comment]
Why does it not show the same behavior when the first if is removed, but the type hint is kept as is?

https://getrector.com/demo/7d4b95e1-9ad7-4825-a905-ea1311e033ce
