### ISSUE TITLE
System error: "Call to a member function setAttribute() on null

### ISSUE THREAD

**Issue by moritz-ngo** [rectorphp/rector#8917]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :-------------------------------------------------------------- |
| Rector version | 1.2.10                                                          |

After upgrading Composer packages I'm getting the following error when running rector on my existing code base:

```
 [ERROR] Could not process "/var/www/html/packages/my-ext/Classes/Services/Captcha/FriendlyCaptchaAdapter.php"
         file, due to:
         "System error: "Call to a member function setAttribute() on null"

Stack trace:
#0 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(196):Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processBinaryOp(Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(PHPStan\Analyser\MutatingScope))
#1 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(729):Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->Rector\NodeTypeResolver\PHPStan\Scope\{closure}(Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(PHPStan\Analyser\MutatingScope))
#2 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3256):PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\BinaryOp\Coalesce),Object(PHPStan\Analyser\MutatingScope))
#3 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1831):PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression(Object(Closure),Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(PHPStan\Analyser\MutatingScope),Object(PHPStan\Analyser\ExpressionContext))
#4 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(728):PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Stmt\Expression),Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(PHPStan\Analyser\MutatingScope), Object(Closure),Object(PHPStan\Analyser\ExpressionContext))
#5 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(430):PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression),Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#6 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(296):PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope),Object(Closure))
#7 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(268):Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->nodeScopeResolverProcessNodes(Array,Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#8 vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(58):Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, 'p...',Object(PHPStan\Analyser\MutatingScope))
#9 vendor/rector/rector/src/Rector/AbstractRector.php(309):Rector\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Expr\BinaryOp\Coalesce), 'p...',Object(PHPStan\Analyser\MutatingScope))
#10 vendor/rector/rector/src/Rector/AbstractRector.php(299):Rector\Rector\AbstractRector->refreshScopeNodes(Object(PhpParser\Node\Expr\BinaryOp\Coalesce), 'p...',Object(PHPStan\Analyser\MutatingScope))
#11 vendor/rector/rector/src/Rector/AbstractRector.php(168):Rector\Rector\AbstractRector->postRefactorProcess(Object(PhpParser\Node\Expr\BinaryOp\Coalesce),Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(PhpParser\Node\Expr\BinaryOp\Coalesce), 'p...')
#12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114):Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\BinaryOp\Coalesce))
#13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
#14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):PhpParser\NodeTraverser->traverseArray(Array)
#15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(134):PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\MethodCall))
#16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):PhpParser\NodeTraverser->traverseArray(Array)
#18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
#19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):PhpParser\NodeTraverser->traverseArray(Array)
#20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#21 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):PhpParser\NodeTraverser->traverseArray(Array)
#22 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#23 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):PhpParser\NodeTraverser->traverseArray(Array)
#24 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#25 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):PhpParser\NodeTraverser->traverseArray(Array)
#26 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(47):PhpParser\NodeTraverser->traverse(Array)
#27 vendor/rector/rector/src/Application/FileProcessor.php(113):Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#28 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),Object(Rector\ValueObject\Configuration))
#29 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),Object(Rector\ValueObject\Configuration))
#30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(118):Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),NULL)
#31 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}(Array)
#32 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):RectorPrefix202411\Evenement\EventEmitter->emit('data', Array)
#33 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):RectorPrefix202411\Clue\React\NDJson\Decoder->handleData(Array)
#34 vendor/rector/rector/vendor/react/stream/src/Util.php(62):RectorPrefix202411\Evenement\EventEmitter->emit('data', Array)
#35 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):RectorPrefix202411\React\Stream\Util::RectorPrefix202411\React\Stream\{closure}('{"action":"main...')
#36 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(168):RectorPrefix202411\Evenement\EventEmitter->emit('data', Array)
#37 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):RectorPrefix202411\React\Stream\DuplexResourceStream->handleData(Resource id #2236)
#38 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):RectorPrefix202411\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#39 vendor/rector/rector/src/Console/Command/WorkerCommand.php(89):RectorPrefix202411\React\EventLoop\StreamSelectLoop->run()
#40 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):Rector\Console\Command\WorkerCommand->execute(Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
#41 vendor/rector/rector/vendor/symfony/console/Application.php(960):RectorPrefix202411\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
#42 vendor/rector/rector/vendor/symfony/console/Application.php(333):RectorPrefix202411\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\WorkerCommand), Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput),Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
#43 vendor/rector/rector/src/Console/ConsoleApplication.php(53):RectorPrefix202411\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
#44 vendor/rector/rector/vendor/symfony/console/Application.php(216):Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput),Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
#45 vendor/rector/rector/bin/rector.php(130): RectorPrefix202411\Symfony\Component\Console\Application->run()
#46 vendor/rector/rector/bin/rector(5): require_once('v...')
#47 vendor/bin/rector(119): include('v...')
#48 {main}". On line: 395
```

## Minimal PHP Code Causing Issue

**`/var/www/html/packages/my-ext/Classes/Services/Captcha/FriendlyCaptchaAdapter.php`:**
```
<?php

declare(strict_types=1);

namespace MyVendor\MyExt\Services\Captcha;

use Evoweb\SfRegister\Services\Captcha\AbstractAdapter;
use StudioMitte\FriendlyCaptcha\Service\Api;
use TYPO3\CMS\Extbase\Utility\LocalizationUtility;

class FriendlyCaptchaAdapter extends AbstractAdapter
{
    public function __construct(
        protected Api $captchaService,
    ) {}

    public function render(): string
    {
        return '';
    }

    public function isValid(string $value): bool
    {
        $validCaptcha = true;

        if (
            $this->captchaService instanceof Api
            && ! $this->captchaService->verify($value)
        ) {
            $validCaptcha = false;
            $this->addError(
                LocalizationUtility::translate(
                    'error_captcha_notcorrect',
                    'SfRegister'
                ) ?? '',
                1306910429
            );
        }

        return $validCaptcha;
    }
}

```

**`rector.php`:**
```
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\EarlyReturn\Rector\Foreach_\ChangeNestedForeachIfsToEarlyContinueRector;
use Rector\EarlyReturn\Rector\If_\ChangeIfElseValueAssignToEarlyReturnRector;
use Rector\EarlyReturn\Rector\If_\ChangeNestedIfsToEarlyReturnRector;
use Rector\PostRector\Rector\NameImportingPostRector;
use Rector\Set\ValueObject\LevelSetList;
use Rector\ValueObject\PhpVersion;
use Ssch\TYPO3Rector\CodeQuality\General\ConvertImplicitVariablesToExplicitGlobalsRector;
use Ssch\TYPO3Rector\CodeQuality\General\ExtEmConfRector;
use Ssch\TYPO3Rector\CodeQuality\General\RenameClassMapAliasRector;
use Ssch\TYPO3Rector\Configuration\Typo3Option;
use Ssch\TYPO3Rector\Set\Typo3LevelSetList;
use Ssch\TYPO3Rector\Set\Typo3SetList;
use Ssch\Typo3RectorTestingFramework\Set\NimutTestingFrameworkSetList;
use Ssch\Typo3RectorTestingFramework\Set\TYPO3TestingFrameworkSetList;
use Rector\Set\ValueObject\SetList;

$configBuilder = RectorConfig::configure();

$configBuilder->withSets([
    Typo3LevelSetList::UP_TO_TYPO3_12,
    // Typo3SetList::TYPO3_13,
    NimutTestingFrameworkSetList::NIMUT_TESTING_FRAMEWORK_TO_TYPO3_TESTING_FRAMEWORK,
    TYPO3TestingFrameworkSetList::TYPO3_TESTING_FRAMEWORK_7,
    SetList::TYPE_DECLARATION,
    SetList::INSTANCEOF,
    SetList::EARLY_RETURN,
    // SetList::DEAD_CODE,
]);

// In order to have a better analysis from phpstan we teach it here some more things
$configBuilder->withPHPStanConfigs([
    Typo3Option::PHPSTAN_FOR_RECTOR_PATH
]);

// FQN classes are not imported by default. If you don't do it manually after every Rector run, enable it by:
$configBuilder->withImportNames();

// // Disable parallel otherwise non php file processing is not working i.e. typoscript
// $configBuilder->withoutParallel();

// This will not import root namespace classes, like \DateTime or \Exception
$configBuilder->withImportNames(false);

// Define your target version which you want to support
$configBuilder->withPhpLevel(PhpVersion::PHP_82);
$configBuilder->withSets([LevelSetList::UP_TO_PHP_82]);

// If you only want to process one/some TYPO3 extension(s), you can specify its path(s) here.
// If you use the option --config change __DIR__ to getcwd()
$configBuilder->withPaths([
    __DIR__ . '/rector.php',
    // __DIR__ . '/.php-cs-fixer.php',
    __DIR__ . '/config/',
    __DIR__ . '/packages/',
]);

// If you set option Option::AUTO_IMPORT_NAMES to true, you should consider excluding some TYPO3 files.
// If you use the option --config change __DIR__ to getcwd()
$configBuilder->withSkip([
    __DIR__ . '/packages/**/.Build',
    __DIR__ . '/packages/**/*.bak',
    // @see https://github.com/sabbelasichon/typo3-rector/issues/2536
    __DIR__ . '/**/Configuration/ExtensionBuilder/*',
    // We skip those directories on purpose as there might be node_modules or similar
    // that include typescript which would result in false positive processing
    __DIR__ . '/**/Resources/**/node_modules/*',
    __DIR__ . '/**/Resources/**/NodeModules/*',
    __DIR__ . '/**/Resources/**/bower_components/*',
    __DIR__ . '/**/Resources/**/BowerComponents/*',
    __DIR__ . '/**/Resources/**/build/*',
    __DIR__ . '/**/Resources/Public/*',
    __DIR__ . '/vendor/*',
    __DIR__ . '/Build/*',
    __DIR__ . '/public/*',
    __DIR__ . '/.github/*',
    __DIR__ . '/.Build/*',
    NameImportingPostRector::class => [
        'ext_localconf.php',
        'ext_tables.php',
        'ext_emconf.php',
        'ClassAliasMap.php',
        // following two are suggested by typo3-rector
        __DIR__ . '/**/Configuration/*.php',
        __DIR__ . '/**/Configuration/**/*.php',
    ],
]);

$configBuilder->withRules([
    ChangeIfElseValueAssignToEarlyReturnRector::class,
    ChangeNestedForeachIfsToEarlyContinueRector::class,
    ChangeNestedIfsToEarlyReturnRector::class,
]);

$configBuilder->withRules([
    ConvertImplicitVariablesToExplicitGlobalsRector::class,
    RenameClassMapAliasRector::class
]);
$configBuilder->withConfiguredRule(ExtEmConfRector::class, [
    ExtEmConfRector::ADDITIONAL_VALUES_TO_BE_REMOVED => []
]);

return $configBuilder;
```

## Expected Behaviour

Rector should run without any internal/system errors.

## Here's a comple list of all installed packages:

| Package                                   | Version              |
| :---------------------------------------- | -------------------: |
| `b13/container`                           | `2.3.6`              |
| `bacon/bacon-qr-code`                     | `2.0.8`              |
| `bnf/phpstan-psr-container`               | `1.1.0`              |
| `brick/phonenumber`                       | `0.6.0`              |
| `captainhook/captainhook`                 | `5.21.2`             |
| `captainhook/plugin-composer`             | `5.3.3`              |
| `captainhook/secrets`                     | `0.9.6`              |
| `christian-riesen/base32`                 | `1.6.0`              |
| `clue/ndjson-react`                       | `1.3.0`              |
| `composer/class-map-generator`            | `1.5.0`              |
| `composer/pcre`                           | `3.3.2`              |
| `composer/semver`                         | `3.4.3`              |
| `composer/xdebug-handler`                 | `3.0.5`              |
| `cweagans/composer-patches`               | `1.7.3`              |
| `dasprid/enum`                            | `1.0.6`              |
| `de-swebhosting-typo3-extension/tinyurls` | `12.1.0`             |
| `deeplcom/deepl-php`                      | `1.10.1`             |
| `deployer/deployer`                       | `7.5.8`              |
| `dmitryd/dd-deepl`                        | `12.7.0`             |
| `doctrine/annotations`                    | `2.0.2`              |
| `doctrine/cache`                          | `2.2.0`              |
| `doctrine/dbal`                           | `3.9.3`              |
| `doctrine/deprecations`                   | `1.1.3`              |
| `doctrine/event-manager`                  | `2.0.1`              |
| `doctrine/instantiator`                   | `2.0.0`              |
| `doctrine/lexer`                          | `3.0.1`              |
| `egulias/email-validator`                 | `4.0.2`              |
| `enshrined/svg-sanitize`                  | `0.18.0`             |
| `evenement/evenement`                     | `3.0.2`              |
| `evoweb/extender`                         | `10.1.1`             |
| `evoweb/sf-register`                      | `12.0.1`             |
| `fidry/cpu-core-counter`                  | `1.2.0`              |
| `firebase/php-jwt`                        | `6.10.2`             |
| `friendsofphp/php-cs-fixer`               | `3.65.0`             |
| `friendsoftypo3/fontawesome-provider`     | `1.0.3`              |
| `friendsoftypo3/tt-address`               | `8.1.1`              |
| `georgringer/eventnews`                   | `6.0.2`              |
| `georgringer/news`                        | `11.4.3`             |
| `georgringer/numbered-pagination`         | `2.1.0`              |
| `giggsey/libphonenumber-for-php`          | `8.13.51`            |
| `giggsey/locale`                          | `2.7.0`              |
| `goetas-webservices/xsd-reader`           | `0.4.8`              |
| `guzzlehttp/guzzle`                       | `7.9.2`              |
| `guzzlehttp/promises`                     | `2.0.4`              |
| `guzzlehttp/psr7`                         | `2.7.0`              |
| `helhum/config-loader`                    | `0.12.5`             |
| `helhum/dotenv-connector`                 | `3.1.0`              |
| `helhum/php-error-reporting`              | `1.0.1`              |
| `helhum/typo3-config-handling`            | `2.0.0`              |
| `helhum/typo3-console`                    | `8.2.1`              |
| `helmich/typo3-typoscript-lint`           | `3.2.1`              |
| `helmich/typo3-typoscript-parser`         | `2.6.1`              |
| `ichhabrecht/content-defender`            | `3.5.0`              |
| `jangregor/phpstan-prophecy`              | `1.0.2`              |
| `jean85/pretty-package-versions`          | `2.1.0`              |
| `jweiland/video-shariff`                  | `3.2.0`              |
| `league/flysystem`                        | `3.29.1`             |
| `league/flysystem-local`                  | `3.29.0`             |
| `league/flysystem-memory`                 | `3.29.0`             |
| `league/mime-type-detection`              | `1.16.0`             |
| `lolli/dbdoctor`                          | `0.5.0`              |
| `lolli42/finediff`                        | `1.1.1`              |
| `masterminds/html5`                       | `2.9.0`              |
| `michielroos/typo3scan`                   | `1.7.7`              |
| `myclabs/deep-copy`                       | `1.12.1`             |
| `nette/utils`                             | `4.0.5`              |
| `networkteam/sentry-client`               | `5.2.0`              |
| `nikic/php-parser`                        | `4.19.4`             |
| `phar-io/manifest`                        | `2.0.4`              |
| `phar-io/version`                         | `3.2.1`              |
| `php-http/discovery`                      | `1.20.0`             |
| `php-http/guzzle7-adapter`                | `1.1.0`              |
| `php-http/httplug`                        | `2.4.1`              |
| `php-http/multipart-stream-builder`       | `1.4.2`              |
| `php-http/promise`                        | `1.3.1`              |
| `phpdocumentor/reflection-common`         | `2.2.0`              |
| `phpdocumentor/reflection-docblock`       | `5.6.0`              |
| `phpdocumentor/type-resolver`             | `1.10.0`             |
| `phplucidframe/console-table`             | `1.3.0`              |
| `phpspec/prophecy`                        | `1.20.0`             |
| `phpspec/prophecy-phpunit`                | `2.3.0`              |
| `phpstan/extension-installer`             | `1.4.3`              |
| `phpstan/phpdoc-parser`                   | `1.33.0`             |
| `phpstan/phpstan`                         | `1.12.12`            |
| `phpstan/phpstan-phpunit`                 | `1.4.1`              |
| `phpunit/php-code-coverage`               | `10.1.16`            |
| `phpunit/php-file-iterator`               | `4.1.0`              |
| `phpunit/php-invoker`                     | `4.0.0`              |
| `phpunit/php-text-template`               | `3.0.1`              |
| `phpunit/php-timer`                       | `6.0.0`              |
| `phpunit/phpunit`                         | `10.5.38`            |
| `psr/cache`                               | `3.0.0`              |
| `psr/clock`                               | `1.0.0`              |
| `psr/container`                           | `2.0.2`              |
| `psr/event-dispatcher`                    | `1.0.0`              |
| `psr/http-client`                         | `1.0.3`              |
| `psr/http-factory`                        | `1.1.0`              |
| `psr/http-message`                        | `2.0 |`              |
| `psr/http-server-handler`                 | `1.0.2`              |
| `psr/http-server-middleware`              | `1.0.2`              |
| `psr/log`                                 | `3.0.2`              |
| `ralouphie/getallheaders`                 | `3.0.3`              |
| `react/cache`                             | `1.2.0`              |
| `react/child-process`                     | `0.6.5`              |
| `react/dns`                               | `1.13.0`             |
| `react/event-loop`                        | `1.5.0`              |
| `react/promise`                           | `3.2.0`              |
| `react/socket`                            | `1.16.0`             |
| `react/stream`                            | `1.4.0`              |
| `rector/rector`                           | `1.2.10`             |
| `roave/security-advisories`               | `dev-latest 759d73e` |
| `saschaegerer/phpstan-typo3`              | `1.10.2`             |
| `sebastian/cli-parser`                    | `2.0.1`              |
| `sebastian/code-unit`                     | `2.0.0`              |
| `sebastian/code-unit-reverse-lookup`      | `3.0.0`              |
| `sebastian/comparator`                    | `5.0.3`              |
| `sebastian/complexity`                    | `3.2.0`              |
| `sebastian/diff`                          | `5.1.1`              |
| `sebastian/environment`                   | `6.1.0`              |
| `sebastian/exporter`                      | `5.1.2`              |
| `sebastian/global-state`                  | `6.0.2`              |
| `sebastian/lines-of-code`                 | `2.0.2`              |
| `sebastian/object-enumerator`             | `5.0.0`              |
| `sebastian/object-reflector`              | `3.0.0`              |
| `sebastian/recursion-context`             | `5.0.0`              |
| `sebastian/type`                          | `4.0.0`              |
| `sebastian/version`                       | `4.0.1`              |
| `sebastianfeldmann/camino`                | `0.9.5`              |
| `sebastianfeldmann/cli`                   | `3.4.2`              |
| `sebastianfeldmann/git`                   | `3.11.1`             |
| `sentry/sentry`                           | `4.10.0`             |
| `smichaelsen/no-insecure-typo3extensions` | `dev-master 5abad2b` |
| `spatie/enum`                             | `3.13.0`             |
| `spatie/icalendar-generator`              | `2.9.0`              |
| `ssch/typo3-debug-dump-pass`              | `0.0.2`              |
| `ssch/typo3-rector`                       | `2.12.0`             |
| `ssch/typo3-rector-testing-framework`     | `2.0.1`              |
| `studiomitte/friendlycaptcha`             | `0.1.8`              |
| `symfony/cache`                           | `7.2.0`              |
| `symfony/cache-contracts`                 | `3.5.1`              |
| `symfony/clock`                           | `7.2.0`              |
| `symfony/config`                          | `7.0.8`              |
| `symfony/console`                         | `6.4.15`             |
| `symfony/dependency-injection`            | `7.2.0`              |
| `symfony/deprecation-contracts`           | `3.5.1`              |
| `symfony/doctrine-messenger`              | `7.2.0`              |
| `symfony/dotenv`                          | `7.2.0`              |
| `symfony/event-dispatcher`                | `7.2.0`              |
| `symfony/event-dispatcher-contracts`      | `3.5.1`              |
| `symfony/expression-language`             | `7.2.0`              |
| `symfony/filesystem`                      | `6.4.13`             |
| `symfony/finder`                          | `7.2.0`              |
| `symfony/http-foundation`                 | `7.2.0`              |
| `symfony/mailer`                          | `7.2.0`              |
| `symfony/messenger`                       | `7.1.9`              |
| `symfony/mime`                            | `7.2.0`              |
| `symfony/options-resolver`                | `7.2.0`              |
| `symfony/polyfill-ctype`                  | `1.31.0`             |
| `symfony/polyfill-intl-grapheme`          | `1.31.0`             |
| `symfony/polyfill-intl-idn`               | `1.31.0`             |
| `symfony/polyfill-intl-normalizer`        | `1.31.0`             |
| `symfony/polyfill-mbstring`               | `1.31.0`             |
| `symfony/polyfill-php80`                  | `1.31.0`             |
| `symfony/polyfill-php81`                  | `1.31.0`             |
| `symfony/polyfill-php83`                  | `1.31.0`             |
| `symfony/polyfill-uuid`                   | `1.31.0`             |
| `symfony/process`                         | `7.2.0`              |
| `symfony/property-access`                 | `7.2.0`              |
| `symfony/property-info`                   | `7.2.0`              |
| `symfony/rate-limiter`                    | `7.2.0`              |
| `symfony/routing`                         | `7.2.0`              |
| `symfony/service-contracts`               | `3.5.1`              |
| `symfony/stopwatch`                       | `7.2.0`              |
| `symfony/string`                          | `7.2.0`              |
| `symfony/type-info`                       | `7.2.0`              |
| `symfony/uid`                             | `7.2.0`              |
| `symfony/var-dumper`                      | `7.2.0`              |
| `symfony/var-exporter`                    | `7.2.0`              |
| `symfony/yaml`                            | `7.2.0`              |
| `theseer/tokenizer`                       | `1.2.3`              |
| `tpwd/ke_search`                          | `5.6.1`              |
| `tpwd/ke_search_premium`                  | `5.0.7`              |
| `typo3/class-alias-loader`                | `1.2.0`              |
| `typo3/cms-adminpanel`                    | `12.4.23`            |
| `typo3/cms-backend`                       | `12.4.23`            |
| `typo3/cms-belog`                         | `12.4.23`            |
| `typo3/cms-beuser`                        | `12.4.23`            |
| `typo3/cms-cli`                           | `3.1.2`              |
| `typo3/cms-composer-installers`           | `5.0.1`              |
| `typo3/cms-core`                          | `12.4.23`            |
| `typo3/cms-dashboard`                     | `12.4.23`            |
| `typo3/cms-extbase`                       | `12.4.23`            |
| `typo3/cms-extensionmanager`              | `12.4.23`            |
| `typo3/cms-felogin`                       | `12.4.23`            |
| `typo3/cms-filelist`                      | `12.4.23`            |
| `typo3/cms-filemetadata`                  | `12.4.23`            |
| `typo3/cms-fluid`                         | `12.4.23`            |
| `typo3/cms-fluid-styled-content`          | `12.4.23`            |
| `typo3/cms-form`                          | `12.4.23`            |
| `typo3/cms-frontend`                      | `12.4.23`            |
| `typo3/cms-impexp`                        | `12.4.23`            |
| `typo3/cms-info`                          | `12.4.23`            |
| `typo3/cms-install`                       | `12.4.23`            |
| `typo3/cms-linkvalidator`                 | `12.4.23`            |
| `typo3/cms-lowlevel`                      | `12.4.23`            |
| `typo3/cms-opendocs`                      | `12.4.23`            |
| `typo3/cms-reactions`                     | `12.4.23`            |
| `typo3/cms-recycler`                      | `12.4.23`            |
| `typo3/cms-redirects`                     | `12.4.23`            |
| `typo3/cms-rte-ckeditor`                  | `12.4.23`            |
| `typo3/cms-scheduler`                     | `12.4.23`            |
| `typo3/cms-seo`                           | `12.4.23`            |
| `typo3/cms-setup`                         | `12.4.23`            |
| `typo3/cms-sys-note`                      | `12.4.23`            |
| `typo3/cms-t3editor`                      | `12.4.23`            |
| `typo3/cms-tstemplate`                    | `12.4.23`            |
| `typo3/cms-viewpage`                      | `12.4.23`            |
| `typo3/cms-webhooks`                      | `12.4.23`            |
| `typo3/coding-standards`                  | `0.7.1`              |
| `typo3/html-sanitizer`                    | `2.2.0`              |
| `typo3/testing-framework`                 | `8.2.6`              |
| `typo3fluid/fluid`                        | `2.15.0`             |
| `wapplersystems/videos`                   | `12.0.9`             |
| `webmozart/assert`                        | `1.11.0`             |

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by moritz-ngo** [comment]
@TomasVotruba @samsonasik thanks for your feedback.
I can confirm, that the issue is not related to `rector/rector` directly, but rather with the latest updates of `ssch/typo3-rector`. 

I'll close this issue and report it in that repository.
