### ISSUE TITLE
ExplicitNullableParamTypeRector not working properly

### ISSUE THREAD

**Issue by bednic** [rectorphp/rector#8919]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.10             |

Rector does not fix issue with missing question mark for implicit nullable parameter.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/8e07815f-7515-4857-b4f8-4e8b5b386e67

## Expected Behaviour

Expect 
```
      string $parentId = null,
      DateTimeInterface $from = null,
      DateTimeInterface $to = null
```
to be 
```
      ?string $parentId = null,
      ?DateTimeInterface $from = null,
      ?DateTimeInterface $to = null
```

**Comment by samsonasik** [comment]
That's php 8.4 feature, you need to enforce it if you don't have runtime php version and not match with your `composer.json` php version requirement.

```php
->withPhpVersion(\Rector\ValueObject\PhpVersion::PHP_84);
```

see https://getrector.com/demo/982533bf-ceb4-48b9-8475-96895612da02

If you're not in php 8.4 yet, it is recommended to update step by step per php version, see full answer here

https://github.com/rectorphp/rector/discussions/8823#discussioncomment-10599155
