### ISSUE TITLE
Incorrect behavior of ReduceAlwaysFalseIfOrRector

### ISSUE THREAD

**Issue by gruberroland** [rectorphp/rector#8920]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/f22cd193-d54c-4957-80d8-54618371cb5c

```php
<?php

final class DemoFile
{
    public function run()
    {
        $list = explode(",", callSomeExternalService());
        if ((sizeof($list) == 0) || in_array("testval", $list)) {
				return false;
		}
        doSomethingElse();
    }

}
```

### Responsible rules

* `ReduceAlwaysFalseIfOrRector`

## Expected Behavior

There should be no change but Rector removes the "(sizeof($list) == 0) ||" in the if-condition. If callSomeExternalService() returns an empty string then this will change the logic.

**Comment by samsonasik** [comment]
That's expected, it only remove left side, which sizeof of explode never 0.
