### ISSUE TITLE
withComposerBased method is not available despite being described in the documentation

### ISSUE THREAD

**Issue by fab0492** [rectorphp/rector#8921]
# Question
In this [blog post](https://getrector.com/blog/introducing-composer-version-based-sets) and in the documentation it appeared a new method of the `RectorConfiguBuilder::withComposerBased`. I tried to install the latest version 1.2.10 with composer, but the option is not available. 

![image](https://github.com/user-attachments/assets/c43e4272-1bc5-43ea-aef3-5a66d37f3aa7)

Is it something intended? I see that this new method [is inside the main branch](https://github.com/rectorphp/rector/blob/main/src/Configuration/RectorConfigBuilder.php#L506)... when will this feature be released? Thank you

**Comment by samsonasik** [comment]
You can try latest 2.0 0rc2 or dev-main

**Comment by fab0492** [comment]
@samsonasik got it, thanks!
