### ISSUE TITLE
Rector does not support class properties in interfaces with PHP 8.4

### ISSUE THREAD

**Issue by martio** [rectorphp/rector#8922]
# Bug Report

I encountered an issue with Laravel Pint when using PHP 8.4. Specifically, Rector is unable to handle class properties defined in interfaces, which is a new feature in PHP 8.4.

Rector version: 1.2.10
PHP Version: 8.4.1

Steps to Reproduce:

1. Use PHP 8.4 and create an interface with class properties:

```php
interface Identifiable
{
    public Uid $aggregateIdentifier { get; }
}
```

2. Implement the interface in a class and define a property getter:

```php
class User implements Identifiable
{
    public Uid $aggregateIdentifier {
        get => $this->userId;
    }
}
```

3. Run Rector.

**Comment by samsonasik** [comment]
That should parsed correctly on latest dev-main, you can try latest 2.0.0rc2

https://getrector.com/demo/ffe5adfa-17bc-4ef9-9fcf-b65a523218a8
