### ISSUE TITLE
Regression: AddOverrideAttributeToOverriddenMethodsRector no longer works on interface methods.

### ISSUE THREAD

**Issue by mickverm** [rectorphp/rector#8932]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `2.0.3` |

```
interface ParentInterface
{
    public function foo(): void;
}

final class ChildClass implements ParentInterface
{
    public function foo(): void
    {
        echo 'foo';
    }
}
````

```
vendor/bin/rector
 2/2 [============================] 100%

 [OK] Rector is done!                                                                                                   
```

https://getrector.com/demo/6b373960-2730-45c4-8909-f362446e9c28

## Expected Behaviour

This is the behaviour using Rector `1.2.10`

````
vendor/bin/rector
 2/2 [============================] 100%
1 file with changes
===================

1) src/ChildClass.php:0

    ---------- begin diff ----------
@@ @@
 #Warning: Strings contain different line endings!
 <?php

 namespace App;
@@ @@

 final class ChildClass implements ParentInterface
 {
+    #[\Override]
     public function foo(): void
     {
         echo 'foo';
    ----------- end diff -----------

Applied rules:
 * AddOverrideAttributeToOverriddenMethodsRector

 [OK] 1 file has been changed by Rector                                                                                                                        
````

**Comment by samsonasik** [comment]
That's expected, see PR:

- https://github.com/rectorphp/rector-src/pull/6447

for reasoning.

**Comment by mickverm** [comment]
Any chance the old behaviour could become opt-in? Or a Rector rule that removes unnecessary `#[Override]`s from the interface implementer?

**Comment by samsonasik** [comment]
I think you can create custom rule for that :)

**Comment by mickverm** [comment]
Linking this to other MRs and issues related to AddOverrideAttributeToOverriddenMethodsRector on interfaces:

- https://github.com/rectorphp/rector-src/pull/5429
- https://github.com/rectorphp/rector/issues/8386
- https://github.com/rectorphp/rector/issues/8497
