### ISSUE TITLE
Incorrect behavior of IfIssetToCoalescingRector

### ISSUE THREAD

**Issue by yguedidi** [rectorphp/rector#8933]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.2.10      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/b74a1b1b-f13c-4f65-a7a1-a23c36ca40c7

```php
<?php

final class DemoFile
{
    private string|null $value;
    
    public function run(string $param)
    {
        if (isset($this->value)) {
            return $this->value;
        }

        return $this->value = $param;
    }
}
```

### Responsible rules

* `IfIssetToCoalescingRector`

## Expected Behavior

This gives `return $this->value ?? $this->value = $param;`
Would have expected `return $this->value ??= $param;` directly, seems not catch even after additional runs of Rector

**Comment by samsonasik** [comment]
is the result equals? if yes, then it is a feature, not a bug, as that's possible improvement.

**Comment by samsonasik** [comment]
I checked, it is part of php7.0 set, assign op is not supported at php 7.0 yet, and only exists in php 7.4, see

https://3v4l.org/3K0lc#v7.0.32 vs https://3v4l.org/3K0lc#v7.4.8

The existing functionality with coealese op binary is the way it can be for php 7.0:

https://3v4l.org/hHQ5C#v7.0.32

If you really need it, I think new rule for php 7.4 is needed for that, feel free to provide PR for php 7.4 feature for it so it clear for compatible syntax to be changed.
