### ISSUE TITLE
Incorrect behavior of ReadOnlyPropertyRector

### ISSUE THREAD

**Issue by blinkseb** [rectorphp/rector#8936]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/386aedcf-bc10-485f-9750-94110a617105

```php
<?php

class Filter
{
    private int $selectedFrom;
    private int $selectedTo;
    
    public function run()
    {
        [$this->selectedFrom, $this->selectedTo] = [0, 1];
        [$this->selectedFrom, $this->selectedTo] = [0, 1];
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

Rector incorrectly adds the `readonly` modifier to `$selectedFrom` and `$selectedTo`

**Comment by samsonasik** [comment]
could you show what error it produce? using readony seems working on https://3v4l.org/3rs0P

**Comment by blinkseb** [comment]
> could you show what error it produce? using readony seems working on https://3v4l.org/3rs0P

I'm sorry it looks like I simplified the repro case a bit too much! The "correct" code is this one: https://3v4l.org/ZZH6s. The property has to be set at least twice for the error to trigger. I've updated my issue.

Thanks for looking at this so quickly! :)
