### ISSUE TITLE
PHPUnit: assertEquals() -> assertSame()

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8945]
# Bug Report

I would expect the phpunit code quality set to transform `assertEquals()` to `assertSame()` - which it does - sometimes.

it [notes that `bool` and `null`](https://github.com/rectorphp/rector-phpunit/blob/4bd1f6ee4a7b55fc09368b5150e886c998a471dd/rules/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector.php#L39-L40) will be executed by a different rector.

but the mentioned AssertEqualsParameterToSpecificMethodsTypeRector rector is only part of the phpunit 80 set, which means on a codebase which uses phpunit 9 or 10 which likely does not run these old phpunit sets, will not be covered..?

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.0.0 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/6030d0b3-b68d-4d62-8880-b83de9225626

## Expected Behaviour

rector transforms `assertEquals()` to `assertSame()` for bools when using the phpunit code quality set

**Comment by staabm** [comment]
fun fact: even adding `AssertEqualsParameterToSpecificMethodsTypeRector` manually does not work in this case

see https://getrector.com/demo/718d63bb-d071-4bd7-b834-3a8cb84f685c

**Comment by samsonasik** [comment]
There is `AssertEqualsToSameRector`, currently work on strict scalars, see

https://getrector.com/demo/bb9ce182-2bfc-4bc8-a2a6-b7f1ece5b14a

**Comment by staabm** [comment]
yeah my point is that this config
```
return RectorConfig::configure()
    ->withPreparedSets(phpunitCodeQuality: true)
;
```

my example the `AssertEqualsToSameRector` does not run the necessary transformation

**Comment by TomasVotruba** [comment]
These methods should be handled to assertNull() and assertFalse() by different Rector rule instead. 

Is it missing in the set?

**Comment by samsonasik** [comment]
@TomasVotruba it compare expected vs actual which values are dynamic bool, can be `false` or `true`, so assertSame() is the way

**Comment by TomasVotruba** [comment]
Ah, I see. Dynamic booleans should be handled by the assertSame() rule :+1: . Could you fix it?

**Comment by samsonasik** [comment]
I will try
