### ISSUE TITLE
Update some articles to rector 2.0

### ISSUE THREAD

**Issue by tacman** [rectorphp/rector#8947]
# Feature Request

Some of the articles refer to an older version of rector.  For example, I often want to add return types, and find my self here:

https://getrector.com/blog/how-to-automatically-add-return-type-declarations-without-breaking-your-code
 
If there's an updated version of this article, could you provide a link on that page to where it is?  

Thanks.

**Comment by TomasVotruba** [comment]
Thanks for feedbac! Updating old posts could lead to complete rewrite, as structure and way we add types is much different now. That might confuse reader who are using old Rector version.


To your answer, see `->withTypeCoverageLevel()` method: https://getrector.com/blog/rector-1-0-is-here

Blog is rather "what is new" type of information. For the documentation, check https://getrector.com/documentation

**Comment by tacman** [comment]
Thanks, how about updating the article with that link, like "If you're using 1.0 or greater of rector, see ->withTypeCoverageLevel?

**Comment by TomasVotruba** [comment]
Sounds good 👍 could you send PR?

**Comment by tacman** [comment]
Can you add a link to the github from the blog itself?  

I'm not sure the blog needs to support showing how to configure rector prior to Version 1, when configuring with at least 1.0 is the recommended practice I assume.

**Comment by TomasVotruba** [comment]
Here it is: https://github.com/rectorphp/getrector-com
