### ISSUE TITLE
Sets lists

### ISSUE THREAD

**Issue by franck-paul** [rectorphp/rector#8949]
# Question
Is there any page in documentation where I can find an exhaustive list of all sets available?

I discover some by looking in code or in some site on the web, but anywhere in the doc.

I'm using this in my config, but I don't know if it is enough (PHP 8.1 to 8.4 application):

```php
return RectorConfig::configure()
    ->withPaths([
        ...
    ])
    ->withPhpSets()
    ->withPhpSets(php81: true)
    ->withPhpSets(php82: true)
    ->withPhpSets(php83: true)
    ->withPhpSets(php84: true)
    // Generic sets
    ->withTypeCoverageLevel(999)
    ->withDeadCodeLevel(999)
    ->withCodeQualityLevel(999)
;
```

**Comment by samsonasik** [comment]
You can read step by step to integrate to new project https://getrector.com/documentation/integration-to-new-project

**Comment by TomasVotruba** [comment]
@franck-paul This docs page contains start with sets: https://getrector.com/documentation/set-lists

I'll add a new page that contains levels setup, thanks for feedback :+1:

**Comment by franck-paul** [comment]
> You can read step by step to integrate to new project https://getrector.com/documentation/integration-to-new-project

Yes, it's a beginning but anywhere in the documentation I found a full list of prepared sets.

**Comment by TomasVotruba** [comment]
@franck-paul See https://getrector.com/documentation/set-lists#content-prepared-sets

These sets grow in time, so there is no point in duplicating them in the docs. IDE is good enough to autocomplete them :+1:
