### ISSUE TITLE
Wrong refactor on RemoveAlwaysTrueIfConditionRector rule

### ISSUE THREAD

**Issue by franck-paul** [rectorphp/rector#8952]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 2.0.1             |

Rector propose a wrong refactor on a specific code (see below)

## Minimal PHP Code Causing Issue

https://getrector.com/demo/8ad0a81a-e056-43d9-b759-5f5442a3dc78

## Expected Behaviour

The test on variables should remain, as called function may have modified their values:

```php
if (empty($rows) || empty($url)) {
            Throw new Exception('error');
}
```

**Comment by samsonasik** [comment]
PHPStan 2.0 no longer support after usage by ref variable on argument, even with `@param-out`, it won't help on this case :)

I think for this, you can simply skip the file, or define docblock for it:

```php
        /** 
         * @var array<non-empty-string>|array{} $rows
         * @var array<non-empty-string>|array{} $urls
         */
        if (empty($rows) || empty($url)) {
            Throw new Exception('error');
        }
```

see https://getrector.com/demo/c7bfb1fb-eec4-4a10-974e-3c2a6df2d3b0

**Comment by franck-paul** [comment]
Thanks for suggestion!
