### ISSUE TITLE
/.github/ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by voku** [rectorphp/rector#917]
Maybe adding a issue template can help to report more standardized issues?

e.g.:
- https://raw.githubusercontent.com/phpstan/phpstan/master/.github/ISSUE_TEMPLATE.md 
- https://raw.githubusercontent.com/symfony-cmf/core-bundle/master/.github/ISSUE_TEMPLATE.md
- https://raw.githubusercontent.com/voku/portable-utf8/master/ISSUE_TEMPLATE.md
...

**Comment by TomasVotruba** [comment]
It might. Feel free to send one
