### ISSUE TITLE
rector (phpunit-yield-data-provider): create broken php code

### ISSUE THREAD

**Issue by voku** [rectorphp/rector#946]
command: (example)
```
git clone https://github.com/nikic/PHP-Parser
composer require rector/rector --dev
php7.1 vendor/bin/rector process test/PhpParser --level phpunit-yield-data-provider --autoload-file test/bootstrap.php --debug -v
```

input:
```php
public function getParseOutput(Parser $parser, $code, array $modes) { ... }
```

output:
```php
public function getParseOutput(Parser $parser, $code, array $modes\Iterator) {
```

---

PS: I think phpcs fixer will check after a file modification, if the file still is valid php code, otherwise the revert it ... maybe you could also throw a exception or something like that ... only a idea :)

**Comment by TomasVotruba** [comment]
Add PS: Linter is good idea. Could you add it?

**Comment by TomasVotruba** [comment]
As for the failed code, please add test case here: https://github.com/rectorphp/rector/blob/6e86548b55f3aee2554184c1678439533ae6f5ed/packages/CodingStyle/tests/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector/ReturnArrayClassMethodToYieldRectorTest.php#L20

**Comment by voku** [comment]
I can't reproduce this in the tests, maybe file (line-ending, encoding or something like that) related?

---

info from the command line: related?
```
PHP Notice:  Undefined offset: 3 in /home/lmoelleken/testing/git/PHP-Parser/lib/PhpParser/PrettyPrinterAbstract.php on line 619
PHP Notice:  Undefined offset: 3 in /home/lmoelleken/testing/git/PHP-Parser/lib/PhpParser/PrettyPrinterAbstract.php on line 619
```

diff:
```diff
-    public function getParseOutput(Parser $parser, $code, array $modes) {
+    public function getParseOutput(Parser $parser, $code, array $modes\Iterator) {
```

**Comment by TomasVotruba** [comment]
> I can't reproduce this in the tests, maybe file (line-ending, encoding or something like that) related?

Maybe line-ending. Without tests we can't even find the tool that is causing this.

**Comment by TomasVotruba** [comment]
It looks like php-parser printer is failing here. I'd like to know why. I contribute there a lot lately and would like to fix it. It would be really great to have failing test, not just for Rector.

**Comment by voku** [comment]
@TomasVotruba here I try to add a simple lint for the changed php files, maybe you can take a look at that, thanks :)

https://github.com/voku/rector/commit/fd5daa70b12f582018be36e917637407776344c0

**Comment by TomasVotruba** [comment]
Send that as PR please, so we have review at one place.

**Comment by TomasVotruba** [comment]
Closing as test case is missing.
