### ISSUE TITLE
[PHP] ReturnTypeDeclarationRector void

### ISSUE THREAD

**Issue by pavarnos** [rectorphp/rector#962]
Allow detection of a void return type and let Rector add the `: void` to the end of the function declaration.

```diff
- public function deleteThing(int $thingID)
+ public function deleteThing(int $thingID): void
{
    $this->repository->deleteRow($thingID);
    $this->cache->clear($thingID);
    $this->eventDispatcher->dispatch(new ThingChangedEvent($thingID));
}
```

See https://disqus.com/home/discussion/itsworthsharing/how_to_complete_type_declarations_without_docblocks_with_rector/#comment-4289736615

**Comment by pavarnos** [comment]
Thanks for the super fast response. rector + phpstan = better code + more sleep

**Comment by TomasVotruba** [comment]
Glad to help. Luckily, this one was easy pick (after I refactored tests to correct ones in 3 hours) :)

**Comment by mwgamble** [comment]
I'm trying to run rector against a codebase that needs to run on PHP 7.0, which doesn't support `void`. Is there any way to stop the `ReturnTypeDeclarationRector` service from adding `void`?

**Comment by TomasVotruba** [comment]
For PHP 7.0 older there is no configuration yet. It would be good idea to create one - please create new issue.

<br>

As for use statements, Rectors tried to respect original spacing if possible, but it's still an AST = very bad at coding standard, even imports.

That's a job of coding standard tool, that was written to do this. You should run if after each run, to keep code clean, see: https://github.com/rectorphp/rector#how-to-apply-coding-standards
