### ISSUE TITLE
[Docker] Error running rector outside of rectors folder

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#972]
Let's have situation:

Rector is installed (cloned) in: `/rector`  
Application is in: `/app`  
Working directory is: `/app`

Running `/rector/bin/rector process src` ends up with error:  
<img width="1355" alt="screenshot 2019-01-21 17 53 07" src="https://user-images.githubusercontent.com/3995003/51488655-63f09a80-1da6-11e9-9351-895f0b139c66.png">

With situation i change working directory to `/rector` and call `bin/rector process /app` it is okay.

I think there will be something wrong with loading autoloader or working directory.

Let me know if you need more info, i will try to debug. Maybe we can try to fix tomorrow 😄

**Comment by JanMikes** [comment]
@TomasVotruba this is most probably the cause of error: https://github.com/rectorphp/rector/blob/master/bin/bootstrap.php#L23 (or at least it is almost 100% related to the bootstrap.php)

**Comment by TomasVotruba** [comment]
That's the prefixed issue we talked about. The `ContainerLoader::load()` method has 2 different versions

**Comment by JanMikes** [comment]
Ah, but isn't that weirdo that if working directory is rector's and project is in other directory, it works? 😄

**Comment by TomasVotruba** [comment]
In project directory the project `vendor/autoload.php` is autoloaded.

**Comment by TomasVotruba** [comment]
Duplicated issue to better described: https://github.com/rectorphp/rector/issues/177
