### ISSUE TITLE
Code Readability level

### ISSUE THREAD

**Issue by voku** [rectorphp/rector#986]
Hi, maybe you can provide a new level for more readable code? 

Something like this ... 

- avoid ternary operator (e.g.: https://exakat.readthedocs.io/en/latest/Rules.html#id452)
- avoid fluend api (e.g.: https://ocramius.github.io/extremely-defensive-php/#/71)
- avoid using "+=" / "-=" / "/=" / ".=" shorthands 
- ... and avoid more stuff like spaceship operator etc. so that everybody in the team can easily understand and read the code.

**Comment by TomasVotruba** [comment]
Hey, 

I don't see a problem with that. Just send PR with first Rector to create it.
