### ISSUE TITLE
StaticCallOnNonStaticToInstanceCallRector: fixes valid static calls

### ISSUE THREAD

**Issue by jkuchar** [rectorphp/rector#991]
`Rector\Php\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector` is broken.

`dibi::setConnection()` which is valid static call. And it is fixed to

![image](https://user-images.githubusercontent.com/133822/51803107-7c066500-2251-11e9-82ce-edf199313bb6.png)

which is not valid anymore - as setConnection is static method. There is probably something wrong with detection of which method is static and which is not.

**Comment by TomasVotruba** [comment]
Could you send me link to `dibi` class on Github?
The exact version you're using in your code.

If it's forked class,  please provide minimal content to replicate

**Comment by jkuchar** [comment]
I use [forked version of dibi](https://github.com/grifart/dibi/tree/grifartis-fork), but both changes are already merged in master. 

- https://github.com/dg/dibi/commit/2b5683d0f205f7db90d6e2ccf8641731147f2daf
- https://github.com/dg/dibi/commit/76593b7da460c42ca0595bed19b8ee418513e28a

**Comment by TomasVotruba** [comment]
The static annotation is already covered: https://github.com/rectorphp/rector/commit/bf3c583cc2b57cb51694ea1a537211a6b0141979

**Comment by TomasVotruba** [comment]
I think it's due to missing annotation, that were not in your required code yet.

Closed as covered by test. If the bug still occurs, please send new PR with test to prove that.
